define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Käytä infografiikkaa ja raportteja, jotka sisältävät yhteenvedon minkä tahansa alueen tärkeimmistä ilmaisimista ja aineistosta.</div><br><div>Valitse kartalta piste tai alue, etsi osoitetta tai paikkaa, piirrä alue tai kiinnitä karttaan nasta, jos haluat tarkastella tärkeitä ilmaisimia ja alueeseen liittyviä tietoja.</div>",
  "defineWhichInfographics": "Määritä, mikä infografiikka on käytettävissä pienoisohjelmassa:",
  "defineWhichReports": "Määritä, mitkä raportit ovat käytettävissä pienoisohjelmassa:",
  "defaultValues": "Oletusarvot:",
  "disable": "Poista käytöstä",
  "drawFreehandPolygon": "Piirrä vapaankäden aluekohde",
  "drawPolygon": "Piirrä polygoni",
  "driveTime": "Ajoaika",
  "dropPin": "Pudota nasta",
  "dynamicHTML": "Dynaaminen HTML",
  "exportOptions": "Vientiasetukset:",
  "home": "Aloitussivu",
  "image": "kuva",
  "infographics": "Infografiikka",
  "invalidValueRing": "Arvojen on oltava välillä 0–1 000.",
  "invalidValueDTWT": "Arvojen on oltava välillä 0–300.",
  "km": "km",
  "makeDefault": "Aseta oletukseksi",
  "miles": "mailia",
  "minutes": "minuuttia",
  "options": "Valinnat:",
  "pdf": "PDF",
  "print": "Tulosta",
  "radius": "Säde",
  "removeDefault": "Poista oletusarvo",
  "reports": "Raportit",
  "rings": "Renkaat",
  "searchTextBox": "Haun tekstiruutu",
  "selectCountryOrRegion": "Valitse maa tai alue:",
  "thisEntryIsNotValid": "Tämä merkintä ei kelpaa.",
  "time": "Kellonaika",
  "walkTime": "Kävelyaika"
});