define({
  "feedbackStyleLabel": "Slog povratnih informacij razdalje in navodil za pot",
  "showTabLabel": "Pokaži vse zavihke",
  "tabErrorMessage": "Izberite vsaj en zavihek v skupini \"Slog povratnih informacij razdalje in navodil za pot\"",
  "lineLabel": "Črta",
  "circleLabel": "Krog",
  "ellipseLabel": "Elipsa",
  "ringsLabel": "Obroči",
  "transparency": "Prosojnost",
  "operationalLineLayerSelectLabel": "Izberite operativni sloj polilinije za rezultate linije in obročev",
  "operationalPolygonLayerSelectLabel": "Izberite operativni sloj polilinije za rezultate kroga in elipse",
  "helpIconPolylineTooltip": "Seznam operativnega sloja je izpolnjen s sloji iz trenutne spletne karte, ki so polilinijske geometrijske vrste.",
  "helpIconPolygonTooltip": "Seznam operativnega sloja je izpolnjen s sloji iz trenutne spletne karte, ki so poligonske geometrijske vrste.",
  "feedbackResultsLayerLabel": "Sloj rezultata povratnih informacij razdalje in navodil za pot",
  "editSymbologyHint": "Namig: Kliknite ikono za predogled za urejanje simbologije",
  "feedbackTextColorLabel": "Barva besedila napisa za povratne informacije",
  "feedbackTextSizeLabel": "Velikost besedila napisa za povratne informacije",
  "previewLabel": "Predogled",
  "lineSymbologyPopupTittle": "Simbologija črt",
  "circleSymbologyPopupTittle": "Simbologija krogov",
  "ellipseSymbologyPopupTittle": "Simbologija elips",
  "ringSymbologyPopupTittle": "Simbologija obročev"
});