define({
  "labelBookmarkName": "Geçerli görünümü yer işaretlerine ekle",
  "labelPlay": "Tümünü oynat",
  "labelStop": "Durdur",
  "labelDelete": "Sil",
  "placeholderBookmarkName": "Yer işareti adı",
  "errorNameExist": "Yer işareti mevcut!",
  "errorNameNull": "Geçersiz yer işareti adı!",
  "editTip": "Yer imlerini düzenle",
  "exitEditTip": "Düzenleme modundan çık",
  "syncTip": "Eşle",
  "cardsTips": "Kılavuz görünümü",
  "listTips": "Liste görünümü",
  "addBtn": "Ekle",
  "deleteBtn": "Sil",
  "changeThumbnailTip": "Küçük resmi değiştir",
  "dragReorderTip": "Yeniden düzenlemek için sürükle ve bırak",
  "deleteBtnTip": "Yer imini sil",
  "editBtnTip": "Yer imini düzenle",
  "withVisibility": "Katman görünürlüğüyle",
  "searchBookmark": "Arama",
  "bookmarksFromConfig": "Önceden yapılandırılmış yer işaretleri",
  "bookmarksFromCache": "Yerel geçici yer işaretleri",
  "notice": "Dikkat",
  "changeNoticeTips": "Değişiklikler yalnızca tarayıcınızın önbelleğine kaydedilecektir. Değişiklikler yaptığınızda, araç ve yapılandırması arasındaki senkronizasyon bağlantısı kesilir.",
  "syncNoticeTips": "Bu değişikliklerinizi siler ve yapılandırılmış yer imlerini geri yükler.",
  "dontShowAgain": "Bir daha gösterme",
  "saveVisibility": "Katman görünürlüğünü kaydet",
  "_widgetLabel": "Yer İmi"
});