define({
  "enableUndoRedo": "Активиране на Undo/Redo",
  "toolbarVisible": "Видима лента с инструменти",
  "toolbarOptions": "Опции на лента с инструменти",
  "mergeVisible": "Обединяване",
  "cutVisible": "Изрязване",
  "reshapeVisible": "Повторно оформяне",
  "back": "Назад",
  "label": "Слой",
  "edit": "Редактируеми",
  "update": "Деактивиране на геометричното обновяване",
  "fields": "Повърхности",
  "actions": "Действия",
  "editpageName": "Име",
  "editpageAlias": "Псевдоним",
  "editpageVisible": "Видимост",
  "editpageEditable": "Редактируеми",
  "noLayers": "Не са налични редактируеми слоеве с обекти",
  "configureFields": "Конфигуриране полетата на слоя",
  "useFilterEdit": "Използване на филтър на обектен шаблон",
  "display": "Показване",
  "autoApplyEditWhenGeometryIsMoved": "Приложете редакцията автоматично, когато геометрията се премести",
  "snappingTolerance": "Задаване на толеранс на прилепване в пиксели",
  "popupTolerance": "Задаване на толеранса на изскачащия прозорец за редактиране на атрибути в пиксели",
  "stickyMoveTolerance": "Задаване толерантност на прилепване при преместване в пиксели",
  "usingSaveButton": "Не прилагайте редакции към атрибутите, докато не натиснете върху бутона Записване",
  "generalSettings": "Общи настройки",
  "editableLayersSetting": "Настройки на редактируемите слоеве",
  "honorTheWebMapSetting": "Настройки за почитане в уеб картата",
  "honorTheWebMapSettingTip1": "Тези настройки включват:",
  "honorTheWebMapSettingTip2": "Кои слоеве могат да се редактират",
  "honorTheWebMapSettingTip3": "Полетата, които искате да покажете и редактирате",
  "honorTheWebMapSettingTip4": "Псевдоним, ред и формат на поле",
  "customSettings": "Потребителски настройки"
});