define({
  "transparencyLabel": "الشفافية",
  "outline": "الحدود",
  "fill": "تعبئة (لا ينطبق اللون إلا عند تعيين النمط إلى مُصمَت)",
  "style": "نمط",
  "selectOpLayerLabel": "تحديد طبقة تشغيلية للنتائج",
  "selectDefaultMeasurementLabel": "تحديد وحدة قياس افتراضية",
  "helpIconTooltip": "يتم ملء الطبقة التشغيلية بالطبقات من خريطة الويب الحالية التي تكون من نوع شكل المضلع الهندسي.",
  "lineStyles": {
    "esriSLSDash": "شَرطَة",
    "esriSLSDashDot": "شَرطَة ونقطة",
    "esriSLSDashDotDot": "شرطة ونقطتين",
    "esriSLSDot": "نقطة",
    "esriSLSLongDash": "شرطة طويلة",
    "esriSLSLongDashDot": "شرطة ونقطة طويلين",
    "esriSLSNull": "خالِ",
    "esriSLSShortDash": "شَرطَة قصيرة",
    "esriSLSShortDashDot": "نقطة شرطة قصيرة",
    "esriSLSShortDashDotDot": "نقطة نقطة شرطة قصيرة",
    "esriSLSShortDot": "منطقة صغيرة",
    "esriSLSSolid": "متصل"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "للخلف",
    "esriSFSCross": "شكل متصالب",
    "esriSFSDiagonalCross": "قطري",
    "esriSFSForwardDiagonal": "للأمام",
    "esriSFSHorizontal": "أفقياً",
    "esriSFSNull": "خالِ",
    "esriSFSSolid": "متصل",
    "esriSFSVertical": "عمودي"
  },
  "threatTypeLabel": "نوع التهديد",
  "generalLabel": "عام",
  "addThreatTypesLabel": "إضافة نوع تهديد",
  "actions": "الإجراءات",
  "newThreatTypePopupLabel": "نوع تهديد جديد",
  "units": "الوحدات",
  "chooseDefaultThreatLabel": "تحديد نوع التهديد الافتراضي",
  "defaultThreatTypePopUpLabel": "أنواع التهديدات الافتراضية",
  "editThreatLabel": "تحرير تهديد",
  "defaultThreatTypeIconTooltip": "قائمة أنواع التهديدات الافتراضية",
  "uniqueThreatTypeMsg": "أدخل نوع تحديد متميز، يوجد نوع تحديد بهذا الاسم بالفعل.",
  "requiredMsg": "يلزم هذا الحقل",
  "unitMeasureLabel": "المسافات في {0}",
  "chooseDefaultThreatTypeIconLabel": "اختيار من الافتراضي",
  "pipeBombLabel": "قنبلة أنبوبية",
  "suicideBombLabel": "قنبلة انتحارية",
  "briefcaseLabel": "حقيبة ملفات",
  "carLabel": "سيارة",
  "suvVanLabel": "سيارة متعددة الاستخدامات/سيارة نقل",
  "smallDeliveryTruckLabel": "شاحنة تسليم صغيرة",
  "containerWaterTruckLabel": "شاحنة ماء/شاحنة بحاوية",
  "semiTrailerLabel": "نصف مقطورة",
  "chemicalThreatLegendLabel": "التهديد الكيميائي",
  "lpgThreatLegendLabel": "تهديد الغاز النفطي المسال",
  "smallLPGTank": "صهريج غاز نفطي مسال صغير",
  "largeLPGTank": "صهريج غاز نفطي مسال كبير",
  "commercialResidentialLPGTank": "صهريج غاز نفطي مسال تجاري/سكني",
  "smallLPGTruck": "شاحنة غاز نفطي مسال صغيرة",
  "semiTankerLPG": "غاز نفطي مسال في نصف صهريج",
  "threatDescriptionColLabel": "وصف التهديد",
  "addThreatZoneButtonLabel": "إضافة منطقة تهديد",
  "zoneDescColLabel": "وصف المنطقة",
  "distanceLabel": "المسافة (${unitAbbr})",
  "threatTypeHelp": "<p>تأكد من استيفاء الشروط التالية لنوع التهديد:<br/><ul><li>لا يمكن أن يكون نوع التهديد فارغًا ويجب أن يكون فريدًا</li><li> يجب أن يكون للتهديد منطقة صالحة واحدة على الأقل</li><li>يجب أن يكون وصف المنطقة فريدًا بالنسبة للتهديد</li></ul><p/>",
  "descriptionLabel": "الوصف",
  "newThreatZonePopupLabel": "منطقة تهديد جديدة",
  "editThreatZonePopupLabel": "تحرير منطقة تهديد",
  "uniqueZoneDescriptionMsg": "أدخل وصفًا فريدًا للمنطقة، وصف المنطقة بهذا الاسم موجود بالفعل.",
  "symbologyColLabel": "الترميز",
  "zoneDescriptionColLabel": "وصف المنطقة",
  "uniqueZoneRequiredMsg": "يجب أن يكون اسم المنطقة فريدًا لـ",
  "interactive": "بشكل تفاعلي",
  "fromCoord": "إحداثي ثابت",
  "existingFeature": "من المعالم الحالية",
  "defaultInputLocationLabel": "موقع الإدخال الافتراضي",
  "defaultInputLayer": "طبقة الإدخال الافتراضي",
  "defaultThreatType": "نوع التهديد الافتراضي",
  "selectLabel": "تحديد",
  "mandatoryLabel": "مسافة الإخلاء الإجبارية",
  "safeLabel": "مسافة الإخلاء الآمنة",
  "lpgSafeDistanceLable": "المسافة الآمنة",
  "fireBallDiameterLable": "قطر كرة اللهب"
});