define({
  "_widgetLabel": "Viedā rediģēšana",
  "_featureAction_SmartEditor": "Viedā rediģēšana",
  "noEditPrivileges": "Jūsu kontam nav piešķirta atļauja izveidot vai modificēt datus.",
  "loginPopupTitle": "Pierakstīties",
  "loginPopupMessage": "Lai meklētu un saglabātu adreses informāciju, ${widgetName} nepieciešamas atļaujas un servisa kredīti. Vai vēlaties pierakstīties un izmantot šo iespēju?",
  "noCreditsOrPrivilegeWarningMessage": "Jūsu kontam nav atļauju un servisa kredītu, lai meklētu un saglabātu adreses informāciju, izmantojot ${widgetName}. Lai pieprasītu atļaujas un servisa kredītus, sazinieties ar savas organizācijas administratoru. Lai turpinātu rediģēšanu, klikšķiniet uz Labi.",
  "unableToUseLocator": "Meklētājs nav pieejams. Adreses atribūtu darbības netiks veiktas. Lai turpinātu rediģēšanu, klikšķiniet uz Labi.",
  "locatorDisabledWaning": "Meklētājs nav iespējots. Lai izmantotu šo iespēju, sazinieties ar savas organizācijas administratoru. Lai turpinātu rediģēšanu, klikšķiniet uz Labi.",
  "noFeatureInAIWarning": "Nav atlasīts neviens elements. Lūdzu, atlasiet elementu, lai veiktu rediģēšanu, vai noklikšķiniet uz Atcelt, lai atgrieztos galvenajā ekrānā.",
  "noEditableLayerWarning": "Jūsu kontam nav atļaujas izveidot vai mainīt datus, vai arī šajā tīmekļa kartē nav neviena rediģējama slāņa.",
  "noVisibleCreateLayerWarning": "Slāņi pašreizējā tālummaiņas līmenī nav redzami. Tuviniet vai tāliniet, lai izveidotu/mainītu elementus.",
  "noVisibleUpdateLayerWarning": "Slāņi pašreizējā tālummaiņas līmenī nav redzami. Tuviniet vai tāliniet, lai mainītu elementus.",
  "checkLayerVisibilityInWebMapWarning": "Pārliecinieties, vai kartē ir redzami slāņi, lai izveidotu vai mainītu elementus.",
  "showSelectionInAITitle": "Atlasītie elementi",
  "showSelectionInAIMsg": "Vai vēlaties ielādēt pašreizējo atlasi ${widgetName}?",
  "widgetActive": "Aktīvs",
  "widgetNotActive": "Neaktīvs",
  "pressStr": "Nospiediet ",
  "ctrlStr": " CTRL ",
  "snapStr": " , lai iespējotu pieķeršanos",
  "noAvailableTempaltes": "Nav pieejamu veidņu",
  "editorCache": " - Redaktora kešatmiņa",
  "presetFieldAlias": "Lauks",
  "presetValue": "Iepriekš iestatīta vērtība",
  "usePresetValues": " Izmantot iepriekš iestatītās vērtības (tikai jauniem elementiem)",
  "editGeometry": " Rediģēt ģeometriju",
  "savePromptTitle": "Saglabāt elementu",
  "savePrompt": "Vai vēlaties saglabāt esošo elementu?",
  "deletePromptTitle": "Izdzēst elementu",
  "deleteAttachment": "Dzēst pielikumu",
  "deletePrompt": "Vai tiešām vēlaties izdzēst izvēlēto elementu?",
  "attachmentLoadingError": "Augšupielādējot pielikumus, radās kļūda",
  "attachmentSaveDeleteWarning": "Brīdinājums: pielikumos saglabātās izmaiņas tiek saglabātas automātiski",
  "autoSaveEdits": "Automātiski saglabāt jaunus elementus",
  "addNewFeature": "Izveidot jaunu elementu",
  "featureCreationFailedMsg": "Nevar izveidot jaunu ierakstu/elementu",
  "relatedItemTitle": "Saistītā tabula/slānis",
  "relatedFeatureCount": "${layerTitle} ar ${featureCount} elementu(iem)",
  "createNewFeatureLabel": "Izveidot jaunu elementu slānim ${layerTitle}",
  "invalidRelationShipMsg": "Lūdzu, pārliecinieties, vai primārās atslēgas laukam '${parentKeyField}' ir derīga vērtība",
  "pendingFeatureSaveMsg": "Lūdzu, saglabājiet elementu labojumus, pirms veidojat saistītu elementu.",
  "attachmentsRequiredMsg": "(*) Pielikumi ir obligāti.",
  "coordinatePopupTitle": "Pārvietot elementu uz XY novietojumu",
  "coordinatesSelectTitle": "Koordinātu sistēma",
  "mapSpecialReferenceDropdownOption": "Kartes telpiskā atskaite",
  "latLongDropdownOption": "Platums/Garums",
  "mgrsDropdownOption": "Militārā režģa atsauces sistēma (Military Grid Reference System, MGRS)",
  "mgrsTextBoxLabel": "Koordināta:",
  "xAttributeTextBoxLabel": "X koordināta:",
  "yAttributeTextBoxLabel": "Y koordināta:",
  "latitudeTextBoxLabel": "Platums:",
  "longitudeTextBoxLabel": "Garums:",
  "presetGroupFieldsLabel": "Grupas nosaukums ${groupName} tiks lietots šiem slāņa laukiem:",
  "presetGroupNoFieldsLabel": "Grupas nosaukumam ${groupName} nav neviena saistīta lauka",
  "groupInfoLabel": "Grupas informācija par grupu ${groupName}",
  "editGroupInfoIcon": "Rediģēt grupas ${groupName} vērtību",
  "filterEditor": {
    "all": "Visi",
    "noAvailableTempaltes": "Nav pieejamas veidnes",
    "searchTemplates": "Meklēt veidnes",
    "filterLayerLabel": "Filtra slāņi"
  },
  "invalidConfiguration": "Logrīks nav konfigurēts vai konfigurētie slāņi vairs nav pieejami kartē. Lūdzu, atveriet programmu veidotāja režīmā un konfigurējiet logrīku atkārtoti.",
  "geometryServiceURLNotFoundMSG": "Nevar iegūt ģeometrijas servisa URL",
  "clearSelection": "Aizvērt",
  "refreshAttributes": "Atjaunināt dinamisko elementu atribūtus",
  "automaticAttributeUpdatesOn": "Automātiski atjaunināt elementu atribūtus: Ieslēgt",
  "automaticAttributeUpdatesOff": "Automātiski atjaunināt elementu atribūtus: Izslēgt",
  "moveSelectedFeatureToGPS": "Pārvietot izvēlēto elementu uz pašreizējo GPS novietojumu",
  "moveSelectedFeatureToXY": "Pārvietot izvēlēto elementu uz XY novietojumu",
  "mapNavigationLocked": "Kartes navigācija: bloķēta",
  "mapNavigationUnLocked": "Kartes navigācija: atbloķēta",
  "copyFeatures": {
    "title": "Izvēlēties elementus, kas jākopē",
    "createFeatures": "Izveidot elementus",
    "createSingleFeature": "Izveidot 1 vairākdaļu elementu",
    "createOneSingleFeature": "Izveidot elementu",
    "noFeaturesSelectedMessage": "Nav atlasītu elementu",
    "selectFeatureToCopyMessage": "Lūdzu, atlasiet elementus kopēšanai",
    "multipleFeatureSaveWarning": "Ja veidosiet vairākdaļu elementus, izmantojot šo funkciju, visi jaunie elementi tiks uzreiz saglabāti Lauku atbilstība netiek atbalstīta, veidojot jaunu vairākdaļu elementu.",
    "copyFeatureUpdateGeometryError": "Nevar atjaunināt atlasīto elementu ģeometriju",
    "canNotSaveMultipleFeatureWarning": "Varat kopēt tikai vienu elementu, ja mērķa punktu slānim ir unikāli vērtību lauki.",
    "createOnlyOneMultipartFeatureWarning": "Varat kopēt tikai vienu elementu vai izveidot vienu vairākdaļu elementu, ja mērķa slānim ir unikāli vērtību lauki.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} no ${totalFeatures} elementiem ir atlasīti"
  },
  "addingFeatureError": "Pievienojot izvēlētos elementus slānim, radās kļūda. Lūdzu, mēģiniet vēlreiz.",
  "addingFeatureErrorCount": "Neizdevās nokopēt “${copyFeatureErrorCount}” elementu(s). Vai vēlaties mēģināt vēlreiz trūkstošajiem elementiem?",
  "selectingFeatureError": "Izvēloties elementus slānī, radās kļūda. Lūdzu, mēģiniet vēlreiz.",
  "customSelectOptionLabel": "Izvēlēties elementus, kas jākopē",
  "copyFeaturesWithPolygon": "Kopēt ar poligonu",
  "copyFeaturesWithRect": "Kopēt ar taisnstūri",
  "copyFeaturesWithLasso": "Kopēt ar laso",
  "noFeatureSelectedMessage": "Nav atlasīts neviens elements",
  "multipleFeatureSaveMessage": "Visi elementi tiks nekavējoties saglabāti. Vai vēlaties turpināt?",
  "relativeDates": {
    "dateTypeLabel": "Datuma veids",
    "valueLabel": "Vērtība",
    "fixed": "Fiksēts",
    "current": "Pašreizējs",
    "past": "Notikušie",
    "future": "Nākotnes",
    "popupTitle": "Izvēlēties vērtību",
    "hintForFixedDateType": "Padoms. Norādītais datums un laiks tiks izmantots kā iepriekš iestatīta noklusējuma vērtība.",
    "hintForCurrentDateType": "Padoms. Pašreizējais datums un laiks tiks izmantots kā iepriekš iestatīta noklusējuma vērtība.",
    "hintForPastDateType": "Padoms. Lai noteiktu iepriekš iestatīto noklusējuma vērtību, norādītā vērtība tiks atņemta no pašreizējā datuma un laika.",
    "hintForFutureDateType": "Padoms. Lai noteiktu iepriekš iestatīto noklusējuma vērtību, norādītā vērtība tiks pieskaitīta pašreizējam datumam un laikam.",
    "noDateDefinedTooltip": "Datums nav noteikts",
    "relativeDateWarning": "Lai saglabātu iepriekš iestatīto noklusējuma vērtību, jānorāda datuma un laika vērtība.",
    "customLabel": "Pielāgots",
    "layerLabel": "Slānis",
    "domainFieldHintLabel": "Atlasītā vērtība ir kodētas vērtības domēns. Tiks izmantota vērtība: “${domainValue}”"
  },
  "valuePicker": {
    "popupTitle": "Izvēlēties vērtību",
    "popupHint": "Pašreizējais elements šķeļ vairākus elementus, izvēlieties attiecīgā lauka vērtību",
    "buttonTooltip": "Atlasiet vērtību no vairākiem elementiem, kuri tiek šķelti"
  },
  "uniqueValueErrorMessage": "Vērtība, kas atrodas “${fieldName}”, jau pastāv; lūdzu, norādiet jaunu vērtību.",
  "requiredFields": {
    "displayMsg": "Obligāti aizpildāmie lauki nevar būt tukši. Norādiet zemāk minēto kopējo lauku vērtības.",
    "popupTittle": "Obligāti aizpildāmie lauki",
    "foundNullRecordCount": "${fieldName} (atrasts ${count} ierakstos)"
  },
  "fieldsMapping": {
    "popupTittle": "Lietot lauka atbilstību",
    "fieldsMatchingCheckboxLabel": "Vērtība(s) no kopētā(ajiem) elementa(iem) pārraksta noklusējuma vērtību(as) mērķa laukā(os)",
    "resetLabel": "Atiestatīt",
    "clearLabel": "Notīrīt",
    "fieldsInTargetLayerLabel": "Mērķis",
    "fieldsInSourceLayerLabel": "Avots",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} lauki atbilst)",
    "selectSourceFieldLabel": "- Atlasīt -",
    "selectFieldAriaLabel": "Atlasīt avota lauku mērķa laukam ${targetField}",
    "informativeText": "Pārskatiet lauku atbilstību no avota uz mērķi un vajadzības gadījumā pielāgojiet.",
    "dynamicValueText": "Ir iestatīta dinamiska vērtība",
    "noFieldsToMatchLabel": "Nav atbilstošu lauku"
  },
  "cantLocateUserLocation": "Jūsu atrašanās vietu nevarēja noteikt",
  "tryAgainButtonLabel": "Mēģiniet vēlreiz",
  "copyFeatureFailedPopupTitle": "Ak vai!"
});