define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Acceda a Infografías e Informes que resumen los indicadores clave y datos de cualquier área.</div><br><div>Seleccione un punto o un polígono en el mapa, busque una dirección o un lugar, dibuje un polígono o suelte una chincheta en el mapa para visualizar información e indicadores clave sobre el área.</div>",
  "defineWhichInfographics": "Defina qué infografías están disponibles en el widget:",
  "defineWhichReports": "Defina qué informes están disponibles en el widget:",
  "defaultValues": "Valores predeterminados:",
  "disable": "Deshabilitar",
  "drawFreehandPolygon": "Dibujar un polígono a mano alzada",
  "drawPolygon": "Dibujar polígono",
  "driveTime": "Tiempo de recorrido por vehículo",
  "dropPin": "Colocar marcador",
  "dynamicHTML": "HTML dinámico",
  "exportOptions": "Opciones de exportación:",
  "home": "Inicio",
  "image": "Imagen",
  "infographics": "Infografía",
  "invalidValueRing": "Los valores deben estar entre el rango de 0 a 1.000.",
  "invalidValueDTWT": "Los valores deben estar entre el rango de 0 a 300.",
  "km": "km",
  "makeDefault": "Definir como predeterminado",
  "miles": "millas",
  "minutes": "minutos",
  "options": "Opciones:",
  "pdf": "PDF",
  "print": "Imprimir",
  "radius": "Radio",
  "removeDefault": "Eliminar predeterminado",
  "reports": "Informes",
  "rings": "Anillos",
  "searchTextBox": "Cuadro de texto de búsqueda",
  "selectCountryOrRegion": "Seleccionar país o región:",
  "thisEntryIsNotValid": "Esta entrada no es válida.",
  "time": "Time",
  "walkTime": "Tiempo de recorrido a pie"
});