define({
  "_widgetLabel": "Batch Attribute Editor",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Laagnaam",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Geen bewerkbare lagen geconfigureerd",
  "editorPopupTitle": "Batch Attribute Editor",
  "editorPopupSaveBtn": "Opslaan",
  "editorPopupMultipleValues": "",
  "clear": "Wissen",
  "featuresUpdated": "${0} / ${1} object(en) geactualiseerd",
  "featuresSelected": "${0} object(en) geselecteerd",
  "featuresSkipped": "Omgeleid",
  "featuresNoPermision": "${0} object(en) geselecteerd, maar geen toestemming om te bewerken.",
  "search": "Zoeken",
  "queryInput": "Voer querywaarde in",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Stel het filter correct in.",
  "filterPopup": "Filter laag",
  "filterAppend": "Als de filter in de webmap bestaat voor deze kaartlaag",
  "filterAppendOR": "Eén expressie toevoegen aan bestaande kaartfilter",
  "filterAppendAND": "Alle expressies toevoegen aan bestaande kaartfilter",
  "cancel": "Annuleren",
  "noValue": "Geen waarde",
  "emptyString": "Lege tekenreeks",
  "existingValue": "Bestaande waarde gebruiken",
  "newDate": "Nieuwe gegevens",
  "valueChooser": "Selecteer/type een waarde",
  "ok": "OK",
  "drawBox": {
    "point": "Punt",
    "line": "Lijn",
    "polyline": "Polylijn",
    "freehandPolyline": "Polylijn in vrije stijl",
    "extent": "Extent",
    "polygon": "Vlak",
    "freehandPolygon": "Veelhoek in vrije stijl",
    "clear": "Wissen",
    "addPointToolTip": "Klik om in dit gebied te selecteren",
    "addShapeToolTip": "Teken een vorm om objecten te selecteren",
    "freehandToolTip": "Houd ingedrukt om een vorm te tekenen om objecten te selecteren",
    "startToolTip": "Teken een vorm om objecten te selecteren"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Het object van ${0} gaf een ongeldige ID",
    "noSelectedLayers": "Geen geselecteerde lagen met te actualiseren records",
    "inputValueError": "Ongeldige waarde in de vorm",
    "saveError": "Kan ${0} objecten niet opslaan",
    "requiredValue": "Vereiste waarde"
  }
});