///////////////////////////////////////////////////////////////////////////
// Copyright ï¿½ Esri. All Rights Reserved.
//
// Licensed under the Apache License Version 2.0 (the 'License');
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
///////////////////////////////////////////////////////////////////////////
define({
  "units": {
    "areaSquareFeetUnit": "Квадратен фут",
    "areaAcresUnit": "Акри",
    "areaSquareMetersUnit": "Квадратни метри",
    "areaSquareKilometersUnit": "Квадратни километри",
    "areaHectaresUnit": "Хектари",
    "areaSquareMilesUnit": "Квадратни мили",
    "lengthFeetUnit": "Фут",
    "lengthMilesUnit": "Мили",
    "lengthMetersUnit": "Метри",
    "lengthKilometersUnit": "Километри"
  },
  "analysisTab": {
    "analysisTabLabel": "Анализи",
    "selectAnalysisLayerLabel": "Слоеве за анализ",
    "addLayerLabel": "Добавяне на слоеве",
    "noValidLayersForAnalysis": "В избраната уеб карта няма намерени валидни слоеве.",
    "noValidFieldsForAnalysis": "В избраната уеб карта няма намерени валидни полета. Моля, премахнете избрания слой.",
    "allowGroupingLabel": "Групиране на обекти по поле с една и съща стойност",
    "groupingHintDescription": "Съвет: По подразбиране всички обекти с една и съща стойност за избраните полета ще бъдат групирани, за да се покажат като един запис в отчета. Деактивирайте групирането по подобни атрибути, за да покажете вместо това запис за всеки обект.",
    "addLayersHintText": "Съвет: Изберете слоевете и полетата, които да включите в анализа и отчета",
    "queryCapabilityHintText": "Ще бъдат изброени само слоеве с възможности за заявка",
    "addLayerNameTitle": "Име на слой",
    "addFieldsLabel": "Добавяне на поле",
    "addFieldsPopupTitle": "Избор на поле",
    "addFieldsNameTitle": "Имена на полета",
    "aoiToolsLegendLabel": "Инструменти в областта на интересите",
    "aoiToolsDescriptionLabel": "Изберете и етикетирайте наличните инструменти за създаване на област на интерес.",
    "placenameLabel": "Име на населено място",
    "drawToolsLabel": "Избор на чертожни инструменти",
    "uploadShapeFileLabel": "Качване на шейп файл",
    "coordinatesLabel": "Координати",
    "coordinatesDrpDwnHintText": "Съвет: Изберете мерна единица за показване на въведените маршрути.",
    "coordinatesBearingDrpDwnHintText": "Съвет: Изберете ъгъл от известна посока за показване на въведените маршрути",
    "allowShapefilesUploadLabel": "Позволете на потребителите да качват шейп файлове, които да включат в анализа",
    "allowShapefilesUploadLabelHintText": "Съвет: Добавете опция към раздела Отчет, където потребителите могат да качват свои собствени данни като шейп файл за включване в отчета за анализ",
    "allowVisibleLayerAnalysisLabel": "Не анализирайте и не докладвайте резултати за слоеве, които не са видими",
    "allowVisibleLayerAnalysisHintText": "Съвет: Слоевете, които са изключени или не се виждат поради настройките за видимост на мащаба, няма да бъдат анализирани или включени в отпечатани или изтеглени резултати.",
    "areaUnitsLabel": "Мерни единици за резултати от анализа (Област)",
    "lengthUnitsLabel": "Мерни единици за резултати от анализа (Дължина)",
    "maxFeatureForAnalysisLabel": "Максимален брой на обекти за анализ",
    "maxFeatureForAnalysisHintText": "Съвет: Задайте максималния брой обекти, които ще бъдат включени в анализа",
    "searchToleranceLabelText": "Толеранс при търсене",
    "searchToleranceHint": "Съвет: Толерансът при търсене се използва при анализ на въвеждания за точка и линия",
    "placenameButtonText": "Име на населено място",
    "drawToolsButtonText": "Изчертаване",
    "shapefileButtonText": "Шейп файл",
    "coordinatesButtonText": "Координати",
    "invalidLayerErrorMsg": "Моля, конфигурирайте полетата за",
    "drawToolSelectableLayersLabel": "Изберете селектируеми слоеве",
    "drawToolSelectableLayersHint": "Съвет: Изберете слоевете, които съдържат обектите, които могат да бъдат селектирани с помощта на Инструмент за чертане селект",
    "drawToolsSettingsFieldsetLabel": "Инструменти за чертане",
    "drawToolPointLabel": "Точка",
    "drawToolPolylineLabel": "Полилиния",
    "drawToolExtentLabel": "Обхват",
    "drawToolPolygonLabel": "Полигон",
    "drawToolCircleLabel": "Окръжност",
    "selectDrawToolsText": "Изберете наличните инструменти за чертане за създаване на област на интерес",
    "selectingDrawToolErrorMessage": "Изберете поне един инструменти за чертане или изберете слой за използване на опцията Чертожни инструменти за област на интерес (AOI).",
    "sortingSettingsLegend": "Настройки за сортиране",
    "ascendingLabel": "Възходящ",
    "descendingLabel": "Низходящ",
    "sortFieldSelectLabel": "Избор на поле за сортиране",
    "statisticsCountLabel": "Статистика: Преброяване",
    "statisticsTotalLengthLabel": "Статистика: Обща дължина",
    "statisticsTotalAreaLabel": "Статистика: Общо област"
  },
  "downloadTab": {
    "downloadLegend": "Настройки за изтегляне",
    "reportLegend": "Настройки на отчет",
    "downloadTabLabel": "Изтегляне",
    "syncEnableOptionLabel": "Обектни слоеве",
    "syncEnableOptionHint": "Съвет: Изберете слоевете, които можете да изтеглите, и посочете форматите, в които всеки слой е наличен. Изтеглените набори от данни ще включват онези обекти, които пресичат областта на интерес.",
    "syncEnableOptionNote": "Съвет: Изтеглянията на файлова геобаза данни и шейп файловете изискват слоеве с активирана функция за синхронизация. Шейп файл формат се поддържа само на обектни слоеве, хоствани от ArcGIS Online.",
    "extractDataTaskOptionLabel": "Услуга за геообработка на задача за извличане на данни",
    "extractDataTaskOptionHint": "Съвет: Използвайте публикувана услуга за геообработка на задача за извличане на данни, за да изтеглите обекти, които пресичат областта на интереси във файлова геобаза данни или шейп файл формат.",
    "cannotDownloadOptionLabel": "Деактивиране на изтегляне",
    "syncEnableTableHeaderTitle": {
      "layerNameLabel": "Име на слой",
      "csvFileFormatLabel": "CSV",
      "fileGDBFormatLabel": "Файлова геобаза данни",
      "ShapefileFormatLabel": "Shapefile",
      "allowDownloadLabel": "Разрешаване на изтегляне"
    },
    "setButtonLabel": "Настройване",
    "GPTaskLabel": "Посочете URL адрес за услугата за геообраотка на данни",
    "printGPServiceLabel": "URL адрес на услугата за печат",
    "setGPTaskTitle": "Посочете необходимия URL адрес на услугата за геообработка",
    "logoLabel": "Лого",
    "logoChooserHint": "Съвет: Натиснете иконата с изображение, за да промените логото, показано в горния ляв ъгъл на отчета",
    "footnoteLabel": "Бележка под линия",
    "columnTitleColorPickerLabel": "Цвят на заглавието на колоната на отчета",
    "reportTitleLabel": "Заглавие на отчета",
    "displaySummaryLabel": "Показване на резюме",
    "hideZeroValueRowLabel": "Скриване на редовете със стойност 0 за всички полета за анализ",
    "hideNullValueRowLabel": "Скриване на редове без стойност на данните (NULL или празно) за всички полета за анализ",
    "errorMessages": {
      "invalidGPTaskURL": "Невалидна услуга за геообработка. Моля, изберете услуга за геообработка, съдържаща задача за извличане на данни.",
      "noExtractDataTaskURL": "Моля, изберете услуга за геообработка, съдържаща задача за извличане на данни.",
      "duplicateCustomOption": "Съществува дублиран запис за ${duplicateValueSizeName}.",
      "invalidLayoutWidth": "Въведена е невалидна широчина за ${customLayoutOptionValue}.",
      "invalidLayoutHeight": "Въведена е невалидна височина за ${customLayoutOptionValue}.",
      "invalidLayoutPageUnits": "Избрана е невалидна мерна единица за страница за ${customLayoutOptionValue}.",
      "failtofetchbuddyTaskDimension": "Грешка при извличане на информация за размерите на партньорска задача. Моля, опитайте отново.",
      "failtofetchbuddyTaskName": "Грешка при извличането на името на партньорска задача. Моля, опитайте отново.",
      "failtofetchChoiceList": "Грешка при извличането на списъка за избор от услугата за печат. Моля, опитайте отново.",
      "invalidWidth": "Невалидна широчина",
      "invalidHeight": "Невалидна височина"
    },
    "addCustomLayoutTitle": "Добавяне на персонализирано оформление",
    "customLayoutOptionHint": "Съвет: Добавете оформление от вашата услуга за печат към списъка с опции за печат.",
    "reportDefaultOptionLabel": "Оформление по подразбиране",
    "pageSizeUnits": {
      "millimeters": "Милиметри",
      "points": "Точки"
    },
    "noDataTextRepresentation": "Няма стойност на данните",
    "naTextRepresentation": "Неприложима стойност",
    "noDataDefaultText": "Няма данни",
    "notApplicableDefaultText": "N/A"
  },
  "generalTab": {
    "generalTabLabel": "Общ",
    "tabLabelsLegend": "Етикети на панела",
    "tabLabelsHint": "Съвет: Посочете надписи",
    "AOITabLabel": "Панел за области на интерес",
    "ReportTabLabel": "Панел за отчет",
    "bufferSettingsLegend": "Настройки на буфер",
    "defaultBufferDistanceLabel": "Стандартно буферно разстояние",
    "defaultBufferUnitsLabel": "Мерни единици за буфер",
    "generalBufferSymbologyHint": "Съвет: Симвология, която да се използва за обозначаване на буферната област около дефинираната зона на интерес",
    "aoiGraphicsSymbologyLegend": "Симвология на област на интерес",
    "aoiGraphicsSymbologyHint": "Съвет: Символогията, използвана за посочване на точкови, линейни и полигонни области на интерес",
    "pointSymbologyLabel": "Точка",
    "previewLabel": "Предварителен преглед",
    "lineSymbologyLabel": "Линия",
    "polygonSymbologyLabel": "Полигон",
    "aoiBufferSymbologyLabel": "Симвология на буфер",
    "pointSymbolChooserPopupTitle": "Символ за местоположение на адрес или точка",
    "polygonSymbolChooserPopupTitle": "Символ на полигон",
    "lineSymbolChooserPopupTitle": "Символ на линия",
    "aoiSymbolChooserPopupTitle": "Символ на буфер",
    "aoiTabText": "AOI (Област на интерес)",
    "reportTabText": "Отчет",
    "invalidSymbolValue": "Невалидна стойност на символ."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Настройки на източник на търсене",
    "searchSourceSettingTitle": "Настройки на източник на търсене",
    "searchSourceSettingTitleHintText": "Добавете и конфигурирайте услуги за геокодиране или обектни слоеве като източници на търсене. Тези посочени източници определят какво може да се търси в полето за търсене",
    "addSearchSourceLabel": "Добавяне на източник за търсене",
    "featureLayerLabel": "Обектен слой",
    "geocoderLabel": "Геокодер",
    "generalSettingLabel": "Общи настройки",
    "allPlaceholderLabel": "Алтернативен текст за търсене във всички:",
    "allPlaceholderHintText": "Съвет: Въведете текст, който да се показва като алтернативен, докато търсите във всички слоеве и геокодер",
    "generalSettingCheckboxLabel": "Показване на изскачащи прозорци за намерените обекти или местоположения",
    "countryCode": "Код (-ове) на държава или район",
    "countryCodeEg": "напр. ",
    "countryCodeHint": "Ако оставите тази стойност празна, ще търсите във всички държави и райони.",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Търсене само в обхвата на текущата карта",
    "locatorUrl": "URL адрес на геокодер",
    "locatorName": "Име на геокодер",
    "locatorExample": "Пример",
    "locatorWarning": "Тази версия на услугата за геокодиране не се поддържа. Изпълнимият модул поддържа услуга за геокодиране с версия 10.0 и по-нова.",
    "locatorTips": "Предложенията не са налични, тъй като услугата за геокодиране не поддържа възможността за предлагане.",
    "layerSource": "Източник на слой",
    "setLayerSource": "Задаване на източник на слой",
    "setGeocoderURL": "Задаване на URL адрес на геокодер",
    "searchLayerTips": "Предложенията не са налични, тъй като услугата за обекти не поддържа възможност за разбиване на страници.",
    "placeholder": "Алтернативен текст",
    "searchFields": "Полета за търсене",
    "displayField": "Поле за показване",
    "exactMatch": "Точно съвпадение",
    "maxSuggestions": "Максимален брой предложения",
    "maxResults": "Максимален брой резултати",
    "enableLocalSearch": "Активиране на локално търсене",
    "minScale": "Минимално мащабиране",
    "minScaleHint": "Когато мащабът на картата е по-голям от този мащаб, ще се приложи локално търсене",
    "radius": "Радиус",
    "radiusHint": "Задава радиус на област около текущия център на картата, която се използва за повишаване на ранга на кандидатите за геокодиране, така че кандидатите, най-близки до местоположението, да бъдат върнати първи",
    "setSearchFields": "Задаване на полета за търсене",
    "set": "Настройване",
    "invalidUrlTip": "URL адресът ${URL} е невалиден или е недостъпен.",
    "invalidSearchSources": "Настройките на източника на търсене са невалидни"
  },
  "errorMsg": {
    "textboxFieldsEmptyErrorMsg": "Моля, попълнете задължителните полета",
    "bufferDistanceFieldsErrorMsg": "Моля, въведете валидни стойности",
    "invalidSearchToleranceErrorMsg": "Моля, въведете валидна стойност за толеранс при търсене",
    "atLeastOneCheckboxCheckedErrorMsg": "Невалидна конфигурация: Изисква се поне един инструмент от областта на интереси.",
    "noLayerAvailableErrorMsg": "Няма налични слоеве",
    "layerNotSupportedErrorMsg": "Не се поддържа ",
    "noFieldSelected": "Моля, използвайте действието \"редактиране\", за да изберете полета за анализ.",
    "duplicateFieldsLabels": "Добавен е дублиран надпис \"${labelText}\" за : \"${itemNames}\"",
    "noLayerSelected": "Моля, изберете поне един слой за анализ.",
    "errorInSelectingLayer": "Не може да се избере слой. Моля, опитайте отново.",
    "errorInMaxFeatureCount": "Моля, въведете валиден максимален брой обекти за анализ."
  }
});