define({
  "_widgetLabel": "Análise de ameaças",
  "threatAnalysisMainPageTitle": "Baseado no Guia de contraterrorismo JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Introduzir localização",
  "interactive": "Interativo",
  "fromCoord": "Coordenadas fixas",
  "existingFeature": "A partir de elementos existentes",
  "threatAnalysisCoordInputLabel": "Localização de ameaças",
  "enterCoords": "Introduzir Coordenadas",
  "threatAddPointToolTip": "Adicionar localização da ameaça",
  "threatDrawPointToolTip": "Clicar para adicionar localização da ameaça",
  "threatType": "Tipo de ameaça",
  "threatPlaceholder": "Começar a digitar para pesquisar uma ameaça",
  "zoneTypeLabel": "Tipo de zona",
  "feetLabel": "Pés",
  "metersLabel": "Metros",
  "unitsLabel": "Unidades",
  "threatGraphicLayer": "Gráfico de Ameaças",
  "style": "Estilo",
  "settingsTitle": "Configurações",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço e Ponto",
    "esriSLSDashDotDot": "Traço, Ponto e Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo e Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Traço Curto e Ponto",
    "esriSLSShortDashDotDot": "Traço Curto, Ponto e Ponto",
    "esriSLSShortDot": "Traço Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Ao Contrário",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para a frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultados",
  "publishTABtn": "Publicar",
  "layerName": "Nome da camada publicada",
  "invalidLayerName": "O nome da camada pode apenas conter caracteres alfanuméricos e traços inferiores.",
  "missingLayerNameMessage": "Tem de introduzir um nome de camada válido antes de poder publicar",
  "publishingFailedLayerExists": "Falha ao publicar: já possui um serviço de elementos denominado {0}. Escolha outro nome para a camada.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não é possível criar: {0}",
  "addToDefinition": "Adicionar a definição: {0}",
  "successfullyPublished": "Camada web publicada com sucesso",
  "successfullyAppended": "Novos elementos anexados à camada web com êxito",
  "manageWebLayerText": "Gerir a camada web",
  "userRole": "Não é possível criar o serviço porque o utilizador não possui permissões",
  "retrieveExistingLayerError": "Não foi possível obter {0}. Publique utilizando outro nome para a camada",
  "publishToNewLayer": "Publicar resultados numa nova camada de elementos",
  "layerNameExists": "O nome da camada já existe. Utilize um nome da camada diferente.",
  "pipeBombLabel": "Bomba de Tubo",
  "suicideBombLabel": "Bomba Suicida",
  "briefcaseLabel": "Pasta",
  "carLabel": "Carro",
  "suvVanLabel": "SUV/CARRINHA",
  "smallDeliveryTruckLabel": "Carrinha de Entregas Pequena",
  "containerWaterTruckLabel": "Camião Cisterna/de Água",
  "semiTrailerLabel": "Semirreboque",
  "transparencyLabel": "Transparência",
  "outline": "Contorno",
  "fill": "Preenchimento (Apenas é aplicada cor quando o estilo é definido como sólido)",
  "createBtn": "Criar Zonas",
  "clearBtn": "Apagar",
  "invalidNumberMessage": "O valor introduzido não é válido",
  "invalidRangeMessage": "O valor tem de ser maior do que 0",
  "parseCoordinatesError": "Não foi possível analisar as coordenadas. Verifique a introdução.",
  "selectDrawModeLabel": "Selecionar Modo de Desenho",
  "selectFeatureLabel": "Selecionar Elemento Desta Camada",
  "smallLPGTank": "Tanque Pequeno GPL",
  "largeLPGTank": "Tanque Grande GPL",
  "commercialResidentialLPGTank": "Tanque GPL Comercial/Residencial",
  "smallLPGTruck": "Camião Pequeno GPL",
  "semiTankerLPG": "Semirreboque GPL",
  "zoneDescriptionColLabel": "Descrição de zona",
  "distanceColLabel": "Distância",
  "zoneDescColLabel": "Descrição de zona",
  "descriptionLabel": "Descrição",
  "editThreatZonePopupLabel": "Editar simbologia de zona de ameaça",
  "symbologyColLabel": "Simbologia",
  "actions": "Ações",
  "threatTypeSelectLabel": "Selecionar tipo de ameaça:",
  "distanceLabel": "Distância (${unitAbbr})",
  "layerCountHint": "Sugestão: uma camada web com ${layerCount} elemento(s) de camada será publicada.",
  "selectLabel": "Selecionar",
  "mandatoryLabel": "Distância de evacuação obrigatória",
  "safeLabel": "Distância de evacuação segura",
  "fireBallDiameterLable": "Diâmetro de Bola de Fogo",
  "lpgSafeDistanceLable": "Distância Segura"
});