define({
  "locatorUrl": "Locator-URL",
  "set": "Instellen",
  "locatorName": "Locatornaam",
  "locatorExample": "Voorbeeld",
  "countryCode": "Land- of regiocode(s)",
  "eg": "bijv. ",
  "countryCodeHint": "Laat deze waarde leeg en alle landen en regio's worden gezocht",
  "minCandidateScore": "Minimum kandidaatscore",
  "minCandidateScoreHint": "Als u deze waarde leeg laat, gebruikt u een minimum kandidaatscore van 90",
  "enableSingleField": "Opties voor één veld",
  "singleFieldHint": "Adresgegevens zullen in een enkel veld zijn",
  "enableMultiField": "Opties voor meerdere velden",
  "multiFieldHint": "Adresgegevens zullen in meerdere velden zijn",
  "enableXYField": "X/Y-veldopties",
  "xyFieldHint": "Gegevens zal X/Y-coördinaatwaarden bevatten",
  "instructionGeocode": "Locatorservices toevoegen en configureren.",
  "invalidUrlTip": "De URL ${URL} is ongeldig of ontoegankelijk.",
  "geocodeTabLabel": "Locatie-instellingen",
  "lookupList": "Veldnamen om te herkennen",
  "isRecognized": "Veldnamen in de onderstaande tabel worden automatisch herkend voor dit veld",
  "needsEditablePointLayers": "De webkaart moet ten minste één bewerkbare puntlaag bevatten.",
  "editpageAlias": "Alias",
  "configureFields": "Laagvelden configureren",
  "configureSingleFields": "Configureer een enkel adresveld",
  "configureMultiFields": "Configureer meerdere adresvelden",
  "configureXYFields": "Configureer X/Y-velden",
  "noFields": "Gebruik de actie Bewerken om één of meer velden weer te geven.",
  "display": "Weergeven",
  "duplicate": "Dubbele zoeken",
  "duplicateTip": "Zoek in dit veld naar identieke waarden tussen het brondbestand en de doellaag./n Als een identieke match is gevonden wordt het record van het bestand niet gevonden en gemarkeerd als dubbel.",
  "noSelectField": "Selecteer eerst de optie Objectlaag",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (lengtegraad)",
  "xyFieldsLabelY": "Y (breedtegraad)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Oostwaarde",
  "northing": "Noordwaarde",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Kies de laag om data naartoe te sturen.",
  "layerFieldTitle": "Doellaag",
  "tempSymbolHint": "Kies het symbool dat gebruikt wordt om de objecten weer te geven.",
  "tempSymbolTitle": "Weergavesymbool",
  "maxRecords": "Max records",
  "maxRecordsHint": "Max aantal te zoeken gegevens",
  "searchRadius": "Zoekradius",
  "searchRadiusHint": "Afstand om te zoeken naar dubbele objecten van laag",
  "requiresInteger": "Voer een numerieke waarde in.",
  "requiresInteger0100": "Voer een numerieke waarde in tussen 0 en 100",
  "requiresLocator": "Voeg minimaal één geldige locator toe.",
  "layerFields": "Laaginstellingen",
  "layerFieldsHint": "Specificeer velden van de doellaag die worden gebruikt voor de bronvelden.",
  "locatorError": "Locator is ongeldig of ontoegankelijk.",
  "optionNotMatch": "Veldopties niet consisteent binnen locators. Failover werkt mogelijk niet zoals verwacht.",
  "targetLayerTabTitle": "Doellaag",
  "locationSettingsTabTitle": "Locatie-instellingen",
  "generalSettingsTabTitle": "Algemene instellingen",
  "addTargetLayersLabel": "Doellaag toevoegen",
  "introductoryText": "Maak instructionele content voor de widget",
  "defaultStartPageInstructions": "Deze widget helpt bij het verwerken en verzenden van gegevens van een bestand naar de geselecteerde laag op de kaart.<br/><br/> Waarden in het bestand moeten worden gescheiden door een komma, tab, puntkomma of verticale streep.",
  "noTargetLayerConfiguredErrorMsg": "Geen doellaag geconfigureerd",
  "noFieldsForTargetLayer": "Laaginstellingen zijn niet gedefinieerd voor de doellaag",
  "locationSettingsNotConfigured": "Locatie-instellingen zijn niet goed geconfigureerd",
  "questionMark": "?"
});