define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Pridať bod kliknutím na mapu",
  "addPolygon": "Vytvoriť polygón kreslením na mapu",
  "addFreehandPolygon": "Vytvoriť polygón voľnou rukou kreslením na mapu",
  "addRingsDtWt": "Pridať okruhy, čas jazdy a čas chôdze.",
  "apply": "Použiť",
  "back": "Späť",
  "colon": ":",
  "creditInformation": "Informácie o úvere",
  "customPolygon": "Vlastný polygón",
  "driveTime": "Čas jazdy",
  "esriInfographics": "Esri infografika",
  "esriReports": "Esri reporty",
  "headerDescription_km": "kilometer",
  "headerDescription_miles": "míľa",
  "headerDescription_minutes": "minúta",
  "infographics": "Infografiky",
  "invalidValueRing": "Hodnoty musia byť v rozmedzí od 0 do 1,000.",
  "invalidValueDTWT": "Hodnoty musia byť v rozmedzí od 0 do 300.",
  "km": "km",
  "miles": "míle",
  "minutes": "minúty",
  "myInfographics": "Moje infografiky",
  "myReports": "Moje prehľady",
  "noPermissions": "Váš účet nevie spustiť Business Analyst widget. Za účelom spustenia Business Analyst widgetu, administrátor vašej organizácie vám musí udeliť GeoEnrichment a Network Analysis<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">oprávnenia</a>, a tiež vám prideliť <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredity</a>.",
  "geServiceNotConfigured": "Business Analyst widget sa nedá spustiť na tomto portáli, pretože služba<a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a>preň nie je nakonfigurovaná.",
  "dirRoutingServiceNotConfigured": "Business Analyst widget sa nedá spustiť na tomto portáli, pretože služba<a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Navigácia a Trasovanie</a> preň nie je nakonfigurovaná.",
  "geAndDirRoutingServicesNotConfigured": "Business Analyst widget sa nedá spustiť na tomto portáli, pretože služby <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> a <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Navigácia a Trasovanie</a> preň nie sú nakonfigurované.",
  "radii": "polomery",
  "radius": "Polomer",
  "radius_lowercase": "polomer",
  "reports": "Prehľady",
  "ring": "Prstenec",
  "rings": "Prstence",
  "runInfographic": "Spustiť infografiku",
  "runReport": "Spustiť prehľad",
  "selectPointOrPolygon": "Zvoliť bod alebo polygón na mape, hľadať adresu alebo miesto, nakresliť polygón, alebo pripnúť špendlík na mapu, aby ste zobrazili kľúčové indikátory a informácie o oblasti.",
  "selectReport": "Zvoliť prehľad",
  "selectTemplate": "Vybrať šablónu",
  "sharedInfographics": "Zdieľané infografiky",
  "sharedReports": "Zdieľané prehľady",
  "thisEntryIsNotValid": "Tento vstup nie je platný.",
  "time": "Čas",
  "walkTime": "Čas chôdze",
  "widgetDescription": "Pristúpiť k infografike a prehľadom, ktoré sumarizujú kľúčové indikátory a údaje pre ktorúkoľek oblasť.",
  "None": "Zvoliť..."
});