define({
  "add": "Kliknite pre pridanie nového",
  "title": "Názov",
  "placeholderBookmarkName": "Názov záložky",
  "ok": "OK",
  "cancel": "Zrušiť",
  "warning": "Dokončite úpravu!",
  "edit": "Upraviť záložku",
  "errorNameExist": "Záložka existuje!",
  "errorNameNull": "Neplatný názov záložky!",
  "addBookmark": "Vytvoriť novú",
  "thumbnail": "Miniatúra",
  "thumbnailHint": "Kliknite pre aktualizáciu obrázku",
  "displayBookmarksAs": "Zobrazenie záložky ako",
  "cards": "Karty",
  "list": "Zoznam",
  "cardsTips": "Zobrazenie karty",
  "listTips": "Zobrazenie zoznamu",
  "makeAsDefault": "Nastaviť ako predvolené",
  "default": "Predvolené",
  "editable": "Povoliť pridanie záložiek do widgetu.",
  "alwaysSync": "Zobrazenie záložiek z webovej mapy",
  "configCustom": "Zobrazenie vlastných záložiek",
  "import": "Importovať",
  "create": "Vytvoriť",
  "importTitle": "Importovať záložky",
  "importFromWeb": "Importovať záložky z aktuálnej webovej mapy",
  "selectAll": "Vybrať všetko",
  "noBookmarkInConfig": "Kliknite na â€œImportovaťâ€ or â€œVytvoriť novúâ€ pre pridanie záložky.",
  "noBookmarkInWebMap": "Žiadna záložka nie je konfigurovaná v mape.",
  "extent": "Rozsah",
  "saveExtent": "Uložiť rozsah mapy do tejto záložky",
  "savelayers": "Uložiť viditeľnosť vrstvy",
  "withVisibility": "S viditeľnosťou vrstvy",
  "bookmark": "Záložka",
  "addBtn": "Pridať",
  "deleteBtn": "Vymazať",
  "editBtn": "Aplikačná šablóna \"Edit\"",
  "dragReorderTip": "Podržaním a ťahaním zmeniť poradie",
  "deleteBtnTip": "Odstrániť záložku",
  "editBtnTip": "Upraviť záložku"
});