define({
  "_widgetLabel": "Editeur intelligent",
  "_featureAction_SmartEditor": "Editeur intelligent",
  "noEditPrivileges": "Votre compte ne dispose pas des autorisations de création ou de modification des données.",
  "widgetActive": "Activé",
  "widgetNotActive": "Non activé",
  "pressStr": "Appuyez sur ",
  "ctrlStr": " CTRL ",
  "snapStr": " pour activer la capture",
  "noAvailableTempaltes": "Aucun modèle disponible",
  "editorCache": " - Cache de l'éditeur",
  "presetFieldAlias": "Champ",
  "presetValue": "Valeur prédéfinie",
  "usePresetValues": " Utiliser des valeurs prédéfinies (nouvelles entités uniquement)",
  "editGeometry": " Mettre à jour la géométrie",
  "savePromptTitle": "Enregistrer l'entité",
  "savePrompt": "Voulez-vous enregistrer l'entité actuelle ?",
  "deletePromptTitle": "Supprimer l'entité",
  "deleteAttachment": "Supprimer une pièce jointe",
  "deletePrompt": "Etes-vous sûr de vouloir supprimer l'entité sélectionnée ?",
  "attachmentLoadingError": "Erreur de chargement des pièces jointes",
  "attachmentSaveDeleteWarning": "Avertissement : les modifications apportées aux pièces jointes sont enregistrées automatiquement",
  "autoSaveEdits": "Enregistrer automatiquement les nouvelles entités",
  "addNewFeature": "Créer une entité",
  "featureCreationFailedMsg": "Impossible de créer un enregistrement/une entité",
  "relatedItemTitle": "Table/couche associée",
  "relatedFeatureCount": "${layerTitle} avec ${featureCount} entités",
  "createNewFeatureLabel": "Créer une nouvelle entité pour ${layerTitle}",
  "invalidRelationShipMsg": "Vérifiez que le champ de clé primaire : '${parentKeyField}' a une valeur valide",
  "pendingFeatureSaveMsg": "Enregistrez les mises à jour apportées à l’entité avant de créer une entité associée.",
  "attachmentsRequiredMsg": "(*) Pièces jointes obligatoires.",
  "coordinatePopupTitle": "Déplacer l’entité vers l’emplacement XY",
  "coordinatesSelectTitle": "Système de coordonnées :",
  "mapSpecialReferenceDropdownOption": "Référence spatiale de la carte",
  "latLongDropdownOption": "Latitude/Longitude",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Coordonnées :",
  "xAttributeTextBoxLabel": "Coordonnée X :",
  "yAttributeTextBoxLabel": "Coordonnée Y :",
  "latitudeTextBoxLabel": "Latitude :",
  "longitudeTextBoxLabel": "Longitude :",
  "presetGroupFieldsLabel": "’${groupName}’ sera appliqué aux champs de couche suivants :",
  "presetGroupNoFieldsLabel": "Aucun champ n’est associé à’ ${groupName}’",
  "groupInfoLabel": "Informations de groupe pour ’${groupName}’",
  "editGroupInfoIcon": "Modifier la valeur de groupe pour ${groupName}",
  "filterEditor": {
    "all": "Tout",
    "noAvailableTempaltes": "Aucun modèle disponible",
    "searchTemplates": "Rechercher des modèles",
    "filterLayerLabel": "Filtrer les couches"
  },
  "invalidConfiguration": "Le widget n'est pas configuré ou les couches de la configuration ne figurent plus sur la carte. Ouvrez l'application en mode de générateur et reconfigurez le widget.",
  "geometryServiceURLNotFoundMSG": "Impossible d'obtenir l'URL du service de géométrie",
  "clearSelection": "Fermer",
  "refreshAttributes": "Mettre à jour les attributs d’entités dynamiques",
  "automaticAttributeUpdatesOn": "Mise à jour auto. des attributs d’entités : activée",
  "automaticAttributeUpdatesOff": "Mise à jour auto. des attributs d’entités : désactivée",
  "moveSelectedFeatureToGPS": "Déplacer l’entité sélectionnée vers l’emplacement GPS actuel",
  "moveSelectedFeatureToXY": "Déplacer l’entité sélectionnée vers l’emplacement XY",
  "mapNavigationLocked": "Navigation sur la carte : verrouillée",
  "mapNavigationUnLocked": "Navigation sur la carte : déverrouillée",
  "copyFeatures": {
    "title": "Copier des entités",
    "createFeatures": "Créer des entités",
    "createSingleFeature": "Créer une entité à plusieurs géométries",
    "noFeaturesSelectedMessage": "Aucune entité sélectionnée",
    "selectFeatureToCopyMessage": "Sélectionnez les entités à copier.",
    "multipleFeatureSaveWarning": "Remarque : créer plusieurs entités en les copiant enregistre toutes les entités immédiatement",
    "copyFeatureUpdateGeometryError": "Impossible de mettre à jour la géométrie des entités sélectionnées",
    "canNotSaveMultipleFeatureWarning": "Remarque : impossible de copier plusieurs entités utilisant la même valeur pour les champs de valeur unique. Sélectionnez une seule entité.",
    "createOnlyOneMultipartFeatureWarning": "Remarque : une seule entité multi-parties peut être créée."
  },
  "addingFeatureError": "Une erreur s’est produite lors de l’ajout des entités sélectionnées dans la couche. Réessayez ultérieurement.",
  "addingFeatureErrorCount": "Échec de la copie de '${copyFeatureErrorCount}' entités.",
  "selectingFeatureError": "Une erreur s’est produite lors de la sélection d’entités dans la couche. Réessayez ultérieurement.",
  "customSelectOptionLabel": "Sélectionner les entités à copier",
  "noFeatureSelectedMessage": "Aucune entité sélectionnée.",
  "multipleFeatureSaveMessage": "Toutes les entités seront immédiatement enregistrées. Voulez-vous continuer ?",
  "relativeDates": {
    "dateTypeLabel": "Type de date",
    "valueLabel": "Valeur",
    "fixed": "Fixé",
    "current": "Actuel",
    "past": "Passé",
    "future": "Futur",
    "popupTitle": "Sélectionner une valeur",
    "hintForFixedDateType": "Astuce : la date et l’heure spécifiées seront utilisées comme valeurs prédéfinies par défaut.",
    "hintForCurrentDateType": "Astuce : la date et l’heure actuelle seront utilisées comme valeurs prédéfinies par défaut.",
    "hintForPastDateType": "Astuce : la valeur spécifiée sera soustraite des valeurs de date et d’heure actuelles pour la valeur prédéfinie par défaut.",
    "hintForFutureDateType": "Astuce : la valeur spécifiée sera ajoutée aux valeurs de date et d’heure actuelles pour la valeur prédéfinie par défaut.",
    "noDateDefinedTooltip": "Aucune date n’est définie",
    "relativeDateWarning": "Pour enregistrer la valeur prédéfinie par défaut, vous devez spécifier une valeur pour la date ou l’heure.",
    "customLabel": "Personnalisée",
    "layerLabel": "Couche",
    "domainFieldHintLabel": "La valeur sélectionnée correspond à un domaine de valeurs précodées. La valeur : ${domainValue} sera utilisée"
  },
  "valuePicker": {
    "popupTitle": "Sélectionner une valeur",
    "popupHint": "L’entité actuelle est en intersection avec plusieurs entités. Choisissez une valeur pour chaque champ respectif.",
    "buttonTooltip": "Sélectionnez une valeur à partir de plusieurs entités d’intersection."
  },
  "uniqueValueErrorMessage": "La valeur dans \"${fieldName}\" existe déjà. Fournissez une nouvelle valeur.",
  "requiredFields": {
    "displayMsg": "Les champs requis doivent être renseignés. Indiquez des valeurs pour les champs communs ci-dessous.",
    "popupTittle": "Champs requis",
    "foundNullRecordCount": "${fieldName} (trouvé dans ${count} enregistrements)"
  },
  "cantLocateUserLocation": "Impossible de déterminer votre localisation"
});