define({
  "chartSettingLabel": "Nestavenia grafu",
  "addNewLabel": "Pridať novú",
  "generalSettingLabel": "Všeobecné nastavenia",
  "searchSourceSettingLabel": "Nastavenia zdroja vyhľadávania",
  "layerChooser": {
    "title": "Vyberte vrstvu na rádiometrickú korekciu",
    "selectPolygonLayerLabel": "Vybrať vrstvu",
    "selectPolygonLayerHintText": "Tip: Ak konfigurujete viacero grafov, vrstvy musia byť rovnakého geometrického typu",
    "selectRelatedTableLayerLabel": "Zvoľte tabuľku relačne súvisiacu s vrstvou",
    "selectRelatedTableLayerHintText": "Tip: Iba tabuľky s číselnými stĺpcami budú zobrazené",
    "errorInSelectingPolygonLayer": "Prosím zvoľte vrstvu, ktorá má relačne súvisiacu bodovú vrstvu.",
    "errorInSelectingRelatedLayer": "Prosím vyberte platnú tabuľku/vrstvu relačne súvisiacu s vrstvou",
    "polygonLayerNotHavingRelationships": "Zvolená vrstva nemá žiadnu relačne súvisiacu tabuľku/vrstvu."
  },
  "ChartSetting": {
    "sectionTitle": "Názov časti",
    "sectionTitleHintText": "Tip: Zobrazené v názve hlavičky sekcie",
    "chartTitle": "Názov grafu",
    "chartTitleHintText": "Tip: Zobrazené v strede na vrchu grafu",
    "chartDescription": "Opis",
    "chartDescriptionHintText": "Tip: Zobrazené pod grafom",
    "chartType": "Typ grafu",
    "barChart": "Pruhový graf",
    "pieChart": "Koláčový graf",
    "polarChart": "Polárny graf",
    "lineChart": "Čiarový graf",
    "dataSeriesField": "Stĺpec pre údajové rady",
    "lineDataSeriesField": "Stĺpec s hodnotami",
    "labelField": "Stĺpec s označeniami kategórií",
    "lineLabelSeriesField": "Sekvenčný stĺpec",
    "chartColor": "Farba grafu",
    "singleColor": "Jedna farba",
    "colorByTheme": "Farba podľa motívu",
    "colorByFieldValue": "Farba podľa hodnoty stĺpca",
    "xAxisTitle": "Názov osi-X",
    "xAxisHintText": "Tip: názov osi-X",
    "yAxisTitle": "Názov osi-Y",
    "yAxisHintText": "Tip: názov osi-Y",
    "fieldColorLabel": "Opis",
    "fieldColorColor": "Farba",
    "defaultFieldSelectLabel": "Vybrať",
    "errMsgFieldValuesNotFound": "Nie je možné nájsť hodnoty pre zvolený stĺpec",
    "errMsgSectionTitle": "Prosím zadajte názov časti",
    "errMsgFieldByValue": "Prosím zvoľte farbu podľa hodnoty stĺpca",
    "errMsgDataSeriesField": "Prosím zvoľte hodnotu stĺpca",
    "settingTabTitle": "Nastavenie",
    "layoutTabTitle": "Rozloženie",
    "polarChartSelectFieldsHintText": "Nápoveda: Zvoľte stĺpce na generovanie polárneho grafu",
    "visibilityText": "Viditeľnosť",
    "fieldNameText": "Názov poľa",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Prosím zvoľte tri alebo viac stĺpcov na generovanie polárneho grafu",
    "polarChartPolygonFillLabel": "Vyplniť polygón",
    "polarChartPolygonFillHintText": "Nápoveda: Zvoliť začiarkavacie políčko na zobrazenie výplne polygónu v polárnom grafe",
    "viewLayoutLabel": "Rozloženie",
    "setValueFields": "Nastaviť stĺpce s hodnotami",
    "layoutSeriesLabel": "Rady",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Púšť",
      "themeDistinctive": "Zreteľný",
      "themeDollar": "Dolár",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Írsko",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Mokraď",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Všeobecné nastavenia",
    "locationSymbolLabel": "Symbol grafickej polohy",
    "locationSymbolHintText": "Tip: Používané na zobrazenie symbolu pre adresu a kliknutie polohy",
    "refreshIntervalLabel": "Interval obnovovania",
    "refreshIntervalHintText": "Tip: Používané na obnovovanie grafov podľa tohto intervalu. Špecifikovať hodnotu medzi 1 a 1440 minút",
    "errMsgRefreshInterval": "Prosím špecifikujte interval obnovovania medzi 0 a 1440 minút",
    "symbolPickerPreviewText": "Náhľad:",
    "showToolToSelectLabel": "Nastaviť tlačidlo umiestnenia",
    "showToolToSelectHintText": "Pomôcka: Poskytuje tlačidlo na nastavenie umiestnenia na mape namiesto nastavenia umiestnenia vždy po kliknutí na mapu"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Nastavenia zdroja vyhľadávania",
    "searchSourceSettingTitle": "Nastavenia zdroja vyhľadávania",
    "searchSourceSettingTitleHintText": "Pridať a konfigurovať geokódovaciu službu alebo vrstvy prvkov ako zdroje vyhľadávania. Tieto špecifikované zdroje určujú, čo sa dá vyhľadávať v rámci vyhľadávacieho poľa",
    "addSearchSourceLabel": "Pridať zdroj vyhľadávania",
    "featureLayerLabel": "Vektorová vrstva",
    "geocoderLabel": "Geokodér",
    "nameTitle": "Meno",
    "generalSettingLabel": "Všeobecné nastavenie",
    "allPlaceholderLabel": "Zástupný text pre vyhľadávanie vo všetkých zdrojoch:",
    "allPlaceholderHintText": "Pomôcka: Pri vyhľadávaní vo všetkých vrstvách a geokodéroch zadajte text, ktorý sa má zobraziť ako zástupný text",
    "generalSettingCheckboxLabel": "Zobraziť kontextové okno pre nájdený prvok alebo umiestnenie",
    "countryCode": "Kód(y) krajiny alebo regiónu",
    "countryCodeEg": "napr. ",
    "countryCodeHint": "Ak ponecháte túto hodnotu prázdnu, budesa vyhľadávať vo všetkých krajinách a regiónoch",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Vyhľadávať iba v aktuálnom rozsahu mapy",
    "zoomScale": "Mierka priblíženia",
    "locatorUrl": "URL geokodéra",
    "locatorName": "Názov geokodéra",
    "locatorExample": "Príklad",
    "locatorWarning": "Táto verzia geokódovacej služby nie je podporovaná. Widget podporuje geokódovaciu službu 10.0 a vyššiu.",
    "locatorTips": "Návrhy nie sú k dipozícii, pretože geokódovacia služba nepodporuje možnosť návrhov.",
    "layerSource": "Zdroj vrstvy",
    "setLayerSource": "Nastaviť zdroj vrstvy",
    "setGeocoderURL": "Nastaviť URL geokodéru",
    "searchLayerTips": "Návrhy nie sú k dispozícii, pretože služba pre prvky nepodporuje stránkovanie.",
    "placeholder": "Zástupný text",
    "searchFields": "Vyhľadávacie polia",
    "displayField": "Zobraziť polia",
    "exactMatch": "Presná zhoda",
    "maxSuggestions": "Maximum návrhov",
    "maxResults": "Maximum výsledkov",
    "enableLocalSearch": "Aktivovať lokálne vyhľadávanie",
    "minScale": "Minimálna mierka",
    "minScaleHint": "Keď je mierka mapy väčšia, než táto mierka, použije sa lokálne vyhľadávanie",
    "radius": "Polomer",
    "radiusHint": "Určuje polomer oblasti okolo aktuálneho stredu mapy, ktorý sa používa na zvýšenie poradia kandidátov na geokódovanie, aby sa kandidátske záznamy najbližšie k umiestneniu vrátili ako prvé.",
    "meters": "Metre",
    "setSearchFields": "Nastaviť polia vyhľadávania",
    "set": "Nastaviť",
    "fieldName": "Meno",
    "invalidSearchSources": "Neplatné nastavenia zdroja vyhľadávania",
    "invalidUrlTip": "URL ${URL} je neplatná alebo nedostupná.",
    "maxSuggestionErrorMessage": "Prosím zadajte platnú maximálnu hodnotu odporúčaní. Hodnota je mimo rozpätia alebo je neplatná.",
    "maxResultsErrorMessage": "Prosím zadajte platnú maximálnu hodnotu výsledkov. Hodnota je mimo rozpätia alebo je neplatná.",
    "zoomScaleErrorMessage": "Prosím zadajte platnú hodnotu miery priblíženia. Hodnota je mimo rozpätia alebo je neplatná.",
    "minScaleErrorMessage": "Prosím zadajte platnú minimálnu hodnotu mierky. Hodnota je mimo rozmedzia alebo je neplatná.",
    "radiusErrorMessage": "Prosím zadajte platnú hodnotu polomeru. Hodnota je mimo rozpätia alebo je neplatná."
  }
});