define({
  "layersPage": {
    "allLayers": "Todas as Camadas",
    "title": "Escolha um modelo para criar elementos ou clique num elemento no mapa para editá-lo",
    "generalSettings": "Configurações Gerais",
    "layerSettings": "Configurações de Camada",
    "webmapSettingsRadioBtnLabel": "Respeitar definições no mapa web",
    "customSettingsRadioBtnLabel": "Definições personalizadas",
    "smartActionsTabTitle": "Ações Inteligentes",
    "attributeActionsTabTitle": "Ações de Atributos",
    "geocoderSettingsText": "Definições de Geocodificador",
    "editDescription": "Fornecer o texto a exibir no painel de edição",
    "editDescriptionTip": "Este texto é exibido acima do seletor Modelo, deixe em branco caso prefira que não haja texto.",
    "promptOnSave": "Mensagem para guardar edições não guardadas quando o formulário é fechado ou alterado para o registo seguinte",
    "promptOnSaveTip": "Exibir uma mensagem quando o elemento atual tiver edições não guardadas. (A cópia de vários elementos é guardada automaticamente.)",
    "promptOnDelete": "Requer confirmação ao eliminar um registo",
    "promptOnDeleteTip": "Exibir uma solicitação quando o utilizador clica em eliminar para confirmar a acção.",
    "removeOnSave": "Remover elemento de seleção ao guardar",
    "removeOnSaveTip": "Opção para remover o elemento do conjunto de seleção quando o registo é guardado.  Casos e trate do único registo selecionado, o painel regressa à página do modelo.",
    "useFilterEditor": "Utilizar filtro de modelo de elemento",
    "useFilterEditorTip": "Opção para utilizar o seletor Modelo de Filtro, que oferece a possibilidade de visualizar o modelo de uma camada ou pesquisar modelos por nome.",
    "groupFilteredTemplates": "Agrupar resultados da pesquisa",
    "groupFilteredTemplatesTip": "Opção para agrupar os resultados da pesquisa por camada.",
    "displayShapeSelector": "Exibir opções de desenho",
    "createNewFeaturesFromExisting": "Permitir a criação de novos elementos a partir de elementos existentes",
    "createNewFeaturesFromExistingTip": "Opção para permitir ao utilizador copiar elementos existentes para criar novos elementos",
    "copiedFeaturesOverrideDefaults": "Os valores dos elementos copiados substituem os valores predefinidos nos campos de destino",
    "copiedFeaturesOverrideDefaultsTip": "Os valores de elementos copiados substituirão os valores do modelo predefinido apenas para o(s) campo(s) que corresponda(m)",
    "displayShapeSelectorTip": "Opção para exibir uma lista de opções de desenho válidas para o modelo selecionado.",
    "displayPresetTop": "Exibir lista de valores predefinidos no topo",
    "displayPresetTopTip": "Opção para exibir a lista de valores predefinidos acima do seletor de modelos.",
    "listenToGroupFilter": "Aplicar valores de filtros do widget Agrupar Filtros para Predefinir campos",
    "listenToGroupFilterTip": "Quando um filtro é aplicado no widget Agrupar Filtros, aplique o valor a um campo correspondente na lista de valor Predefinido.",
    "keepTemplateActive": "Manter modelo selecionado ativo",
    "editLayerAddedFromAddData": "Permitir a edição de camadas adicionadas a partir do widget Adicionar Dados",
    "editLayerAddedFromAddDataTip": "As camadas editáveis adicionadas à aplicação com o widget Adicionar Dados podem ser editadas",
    "keepTemplateActiveTip": "Quando o seletor de modelos é exibido, caso um modelo tenha sido selecionado anteriormente, volte a selecioná-lo.",
    "geometryEditDefault": "Ativar edição de geometria por defeito",
    "autoSaveEdits": "Guardar novos elementos automaticamente",
    "enableAttributeUpdates": "Exibir botão de atualização Ações de Atributos",
    "enableAutomaticAttributeUpdates": "Chamar automaticamente Ações de Atributos após a atualização da geometria",
    "enableLockingMapNavigation": "Ativar bloqueio de navegação no mapa",
    "enableMovingSelectedFeatureToGPS": "Ativar deslocamento de elemento de ponto selecionado para localização GPS",
    "enableMovingSelectedFeatureToXY": "Ativar deslocamento de elemento de ponto selecionado para localização XY",
    "featureTemplateLegendLabel": "Definições de Modelo de Elementos e de Valor de Filtro",
    "saveSettingsLegendLabel": "Guardar Definições",
    "geometrySettingsLegendLabel": "Definições de Geometria",
    "actionsSettingsLegendLabel": "Definições de Ações",
    "buttonPositionsLabel": "Posição dos botões Guardar, Eliminar, Regressar e Fechar",
    "belowEditLabel": "Abaixo do Formulário de Edição",
    "aboveEditLabel": "Acima do Formulário de Edição",
    "switchToMultilineInput": "Mudar para entrada multilinha quando o comprimento do campo exceder",
    "enableValuePicker": "Ativar seletor de valor de intersecção",
    "enableValuePickerHint": "Exibir uma mensagem quando vários valores estão disponíveis para um campo com uma ação de atributo de intersecção",
    "expandRelatedTable": "Expandir todas as tabelas/camadas relacionadas ao carregar",
    "expandMainTable": "Expandir todas as camadas principais ao carregar",
    "copyAndAppendFeatureLabel": "Copiar e Acrescentar Elementos",
    "allowCopyPolygonLabel": "Permitir cópia de polígono para ponto",
    "allowCopyPolygonTooltip": "Opção para permitir a cópia de elementos de polígono para modelos de elementos de destino de ponto com transformações de geometria",
    "allowCopyLineLabel": "Permitir cópia de linha para ponto",
    "allowCopyLineTooltip": "Opção para permitir a cópia de elementos de linha para modelos de elementos de destino de ponto com transformações de geometria",
    "pointAtStartLabel": "Ponto no início",
    "pointAtStartTooltip": "Adicionar um ponto ao início da linha que está a ser copiada",
    "pointAtEndLabel": "Ponto no fim",
    "pointAtEndTooltip": "Adicionar um ponto ao fim da linha que está a ser copiada",
    "layerSettingsTable": {
      "allowDelete": "Permitir Eliminação",
      "allowDeleteTip": "Permitir Eliminação: opção que permite ao utilizador eliminar um elemento; é desativada caso a camada não suporte eliminação",
      "edit": "Editável",
      "editTip": "Editável: opção para incluir a camada no widget",
      "label": "Camada",
      "labelTip": "Camada: nome da camada tal como definido no mapa",
      "update": "Desativar Edição de Geometria",
      "updateTip": "Desativar Edição de Geometria: opção para desativar a capacidade de mover a geometria após colocada ou mover a geometria num elemento existente",
      "allowUpdateOnly": "Atualizar Apenas",
      "allowUpdateOnlyTip": "Apenas Atualização: opção que permite apenas a modificação de elementos existentes está selecionada por predefinição e desativada caso a camada não suporte a criação de novos elementos",
      "fieldsTip": "Modificar os campos para serem editados e definir Atributos Inteligentes",
      "actionsTip": "Ações: opção para editar campos ou aceder a camadas/tabelas relacionadas",
      "description": "Descrição",
      "descriptionTip": "Descrição: opção para introduzir texto a exibir na parte superior da página de atributos.",
      "relationTip": "Visualizar camadas e tabelas relacionadas"
    },
    "editFieldError": "Modificações de campos e atributos Inteligentes não se encontram disponíveis para camadas que não são editáveis",
    "noConfigedLayersError": "O Smart Editor requer uma ou mais camadas editáveis.",
    "toleranceErrorMsg": "Valor de Tolerância de Interseção Predefinida inválido",
    "pixelsToleranecErrorMsg": "Valor de Tolerância de Píxeis Predefinida inválido",
    "invalidMaxCharacterErrorMsg": "Valor inválido ao mudar para entrada multilinha",
    "featuresSelectionTolerance": "Definir a tolerância para a seleção do elemento (píxeis)",
    "featuresSelectionToleranceTooltip": "Permite aos utilizadores abrir facilmente a janela pop-up de edição de atributos ao clicar no elemento",
    "featuresSelectionToleranceErrorMsg": "Valor de tolerância de seleção do elemento inválido",
    "autoSaveAttrUpdates": "Guardar atualizações de atributos e geometrias automaticamente",
    "defaultCoordinateSystem": "Sistema de Referência Padrão",
    "defaultCoordinateSystemTooltip": "Defina o sistema de referência padrão ao mover um elemento de ponto selecionado para uma nova localização"
  },
  "editDescriptionPage": {
    "title": "Defina o texto de vista geral de atributos para <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Configure campos para <b>${layername}</b>",
    "copyActionTip": "Ações de Atributos",
    "editActionTip": "Ações Inteligentes",
    "description": "Utilize o botão de edição Ações para ativar Atributos Inteligentes numa camada. Os Atributos Inteligentes podem requerer, ocultar ou desativar um campo com base em valores de outros campos. Utilize o botão de cópia Ações para ativar e definir origem de valor de campo por interseção, endereço, coordenadas e predefinição.",
    "fieldsNotes": "* é um campo exigido.  Caso desmarque Exibir para este campo, e o modelo de edição não preencha esse valor de campo, não lhe será possível  guardar um novo registo.",
    "smartAttachmentText": "Configurar Ações Inteligentes para anexos",
    "smartAttachmentPopupTitle": "Configurar Ações Inteligentes para anexos em <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Selecione pelo menos um campo de exibição para a camada ${layerName}",
    "fieldsSettingsTable": {
      "display": "Exibir",
      "displayTip": "Exibir: determinar se o campo não é visível",
      "edit": "Editável",
      "editTip": "Editável: marcar se o campo estiver presente no formulário de atributos",
      "fieldName": "Nome",
      "fieldNameTip": "Nome: nome do campo definido na base de dados",
      "fieldAlias": "Nome Alternativo",
      "fieldAliasTip": "Nome alternativo: nome do campo definido no mapa",
      "canPresetValue": "Pré-definido",
      "canPresetValueTip": "Predefinição: opção para exibir o campo na lista de campos predefinidos e permitir ao utilizador definir o valor antes de editar",
      "actions": "Acções",
      "actionsTip": "Ações: alterar a ordem dos campos ou configurar Atributos Inteligentes"
    },
    "smartAttSupport": "Os Atributos Inteligentes não são suportados nos campos obrigatórios da base de dados"
  },
  "actionPage": {
    "title": "Configurar as Acções de Atributos para <b>${fieldname}</b>",
    "smartActionTitle": "Configurar Ações Inteligentes para <b>${fieldname}</b>",
    "description": "As ações estão sempre desativadas, a não ser que especifique os critérios através dos quais são desencadeadas.   As ações são processadas por ordem e apenas uma ação por campo será desencadeada.  Utilize o botão Edição de Critérios para definir os critérios.",
    "copyAttributesNote": "A desativação de qualquer ação com um nome de grupo terá o mesmo efeito que a edição dessa ação de forma independente e irá remover a ação para este campo do respetivo grupo.",
    "searchPlaceHolder": "Pesquisar",
    "expandAllLabel": "Expandir todas as camadas",
    "selectAllLabel": "Selecionar todos os campos",
    "domainListTitle": "Campos de domínio",
    "noValidFieldTypeMsg": "Não existe uma camada adequada disponível no mapa para este tipo de dados",
    "actionsSettingsTable": {
      "rule": "Ação",
      "ruleTip": "Ação: ação executada quando os critérios são correspondidos",
      "expression": "Expressão",
      "expressionTip": "Expressão: a expressão resultante em formato SQL dos critérios definidos",
      "groupName": "Nome do Grupo",
      "groupNameTip": "Nome do Grupo: exibe o nome do grupo a partir do qual a expressão é aplicada",
      "actions": "Critérios",
      "actionsTip": "Critério: altera a ordem da regra e define os critérios quando este é ativado"
    },
    "copyAction": {
      "description": "As fontes de valor de campo são processadas por ordem se ativadas até que um critério válido seja acionado ou até que a lista seja completada. Use o botão Editar Critérios para definir os critérios.",
      "intersection": "Intersecção",
      "coordinates": "Coordenadas",
      "address": "Endereço",
      "preset": "Pré-definido",
      "actionText": "Ações",
      "criteriaText": "Critérios",
      "enableText": "Ativado"
    },
    "actions": {
      "hide": "Esconder",
      "required": "Exigido",
      "disabled": "Desativado"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Aviso: a edição independente irá remover do grupo a ação do atributo selecionada associada para este campo",
      "editGroupHint": "Aviso: a edição independente irá remover do grupo a ação inteligente selecionada associada para este campo",
      "popupTitle": "Escolher opção de edição",
      "editAttributeGroup": "A ação de atributo selecionada é definida a partir do grupo. Escolha uma das seguintes opções para editar a ação de atributo:",
      "expression": "A expressão da ação inteligente selecionada é definida a partir do grupo. Escolha uma das seguintes opções para editar a expressão da ação inteligente:",
      "editGroupButton": "Editar Grupo",
      "editIndependentlyButton": "Editar Independentemente"
    }
  },
  "filterPage": {
    "submitHidden": "Enviar dados de atributos para campos, mesmo quando se encontram ocultos",
    "title": "Configurar expressão para a regra ${action}",
    "filterBuilder": "Definir ação para campo quando o registo corresponde a ${any_or_all} das expressões seguintes",
    "noFilterTip": "Utilizando as ferramentas acima, defina a declaração apresentada quando a ação se encontra ativa."
  },
  "geocoderPage": {
    "setGeocoderURL": "Definir URL Geocodificador",
    "hintMsg": "Nota: Está a modificar o serviço de geocodificador, por favor, atualize quaisquer cartografias de campo de geocodificador que tenha configurado.",
    "invalidUrlTip": "O URL ${URL} é inválido ou inacessível."
  },
  "addressPage": {
    "popupTitle": "Endereço",
    "checkboxLabel": "Obter valor do Geocodificador",
    "selectFieldTitle": "Atributo",
    "geocoderHint": "Para mudar de geocodificador, utilize o botão 'Definições de Geocodificador' nas definições gerais",
    "prevConfigruedFieldChangedMsg": "O atributo configurado anteriormente não é encontrado nas definições de geocodificador atuais. As predefinições do atributo foram repostas.",
    "questionMark": "?",
    "consumesCredits": "Esta ferramenta consome créditos quando utilizada com o ArcGIS Online World Geocoding Service"
  },
  "coordinatesPage": {
    "popupTitle": "Coordenadas",
    "checkboxLabel": "Obter coordenadas",
    "coordinatesSelectTitle": "Sistema de Referência",
    "coordinatesAttributeTitle": "Atributo",
    "mapSpatialReferenceOptionLabel": "Referência Espacial do Mapa",
    "latLongOptionLabel": "Latitude/Longitude",
    "MGRS": "Sistema de Referência da Rede Militar (MGRS)",
    "allGroupsCreatedMsg": "Já foram criados todos os grupos possíveis",
    "coordinatesSourceTitle": "Fonte de Coordenadas",
    "featureLocation": "Localização do Elemento",
    "myLocation": "O Meu Local",
    "LatLong": {
      "y": "Latitude",
      "x": "Longitude",
      "xy": "Longitude Latitude",
      "yx": "Latitude Longitude"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Pré-definido",
    "checkboxLabel": "O campo será predefinido",
    "showOnlyDomainFields": "Exibir apenas campos de domínio",
    "hideInPresetDisplay": "Ocultar na apresentação dos valores predefinidos",
    "presetValueLabel": "O atual valor de predefinição é:",
    "changePresetValueHint": "Para alterar este valor de predefinição, utilize o botão 'Definir Valores de Predefinição' nas definições gerais"
  },
  "intersectionPage": {
    "groupNameLabel": "Nome do Grupo",
    "dataTypeLabel": "Tipo de Dados",
    "ignoreLayerRankingCheckboxLabel": "Ignorar classificação de camada e encontrar elemento mais próximo em todas as camadas definidas",
    "intersectingLayersLabel": "Camada(s) para extrair um valor",
    "layerAndFieldsApplyLabel": "Camada(s) e campo(s) para aplicar o valor extraído",
    "checkboxLabel": "Obter valor a prtir do campo da camada de interseção",
    "layerText": "Camadas",
    "fieldText": "Campos",
    "actionsText": "Ações",
    "toleranceSettingText": "Definições de Tolerância",
    "addLayerLinkText": "Adicionar uma Camada",
    "useDefaultToleranceText": "Utilizar Tolerância Predefinida",
    "toleranceValueText": "Valor de Tolerância",
    "toleranceUnitText": "Unidade de Tolerância",
    "pixelsUnitText": "Pixeis",
    "useLayerName": "- Utilizar Nome da Camada -",
    "noLayersMessage": "Não foi encontrado qualquer campo nas camadas do mapa que corresponda ao tipo de dados selecionado.",
    "intersectionLayerHint": "A classificação da camada está em ordem descendente. Utilize as setas sob Ações para reordenar as camadas e alterar a prioridade de intersecção."
  },
  "presetAll": {
    "popupTitle": "Definir os valores de predefinição padrão",
    "deleteTitle": "Eliminar valor de predefinição",
    "hintMsg": "Todos os nomes de campos predefinidos únicos são apresentados aqui. A remoção de um campo predefinido irá desativar o respetivo campo enquanto predefinição de todas as camadas/tabelas."
  },
  "intersectionTolerance": {
    "intersectionLabel": "Tolerância de intersecção predefinida para todos os elementos",
    "intersectionTitle": "Ativar uma tolerância global para interseções",
    "pixelsToleranceLabel": "Tolerância de interseção predefinida (valor de píxeis) a ser aplicada apenas a elementos de ponto",
    "pixelsToleranceTitle": "Se a tolerância de interseção padrão para todos os elementos estiver definida para 0, use a definição para elementos de ponto"
  },
  "smartActionsPage": {
    "smartActionLabel": "Configurar uma Ação Inteligente",
    "addNewSmartActionLinkText": "Adicionar Nova",
    "definedActions": "Ações Definidas",
    "priorityPopupTitle": "Definir prioridade de Ações Inteligentes",
    "priorityPopupColumnTitle": "Ações Inteligentes",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Nome do Grupo",
    "layerForExpressionLabel": "Camada para Expressão",
    "layerForExpressionNote": "Nota: Estes campos da camada são utilizados para definir os critérios da expressão. 'Camadas e campos para aplicar a' apenas exibe camadas e tabelas que têm o(s) campo(s) definido(s) na Expressão.",
    "expressionText": "Expressão",
    "editExpressionLabel": "Editar Expressão",
    "layerAndFieldsApplyLabel": "Camadas e campos aos quais aplicar",
    "submitAttributeText": "Enviar dados de atributos para campos, mesmo quando se encontram ocultos",
    "priorityColumnText": "Prioritário",
    "requiredGroupNameMsg": "Este valor é necessário",
    "uniqueGroupNameMsg": "Introduzir um nome de grupo único. Já existe um grupo com este nome.",
    "deleteGroupPopupTitle": "Eliminar Grupo de Ações Inteligentes",
    "deleteGroupPopupMsg": "A eliminação do grupo fará com que a expressão seja removida de todas as Ações de Campo(s) associadas.",
    "invalidExpression": "A expressão não pode estar vazia",
    "warningMsgOnLayerChange": "Os campos na qual a expressão definida está aplicada serão eliminados.",
    "smartActionsTable": {
      "name": "Nome",
      "expression": "Expressão",
      "definedFor": "Definido Para"
    }
  },
  "attributeActionsPage": {
    "name": "Nome",
    "type": "Tipo",
    "deleteGroupPopupTitle": "Eliminar Grupo de Ações de Atributos",
    "deleteGroupPopupMsg": "A eliminação do grupo fará com que a ação de atributo seja removida de todos os Campos associados.",
    "alreadyAppliedActionMsg": "A ação ${action} está aplicada a este campo no grupo",
    "alreadyAppliedActionLayerMsg": "A ação ${action} está aplicada a este campo nas Definições de Camada",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Este grupo não contém campos associados.",
    "presetNoFieldWarningMsg": "Configure pelo menos um campo para o grupo predefinido: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Campo",
    "valueLabel": "Valor",
    "selectValueLabel": "Selecionar Valor",
    "domainFieldHintLabel": "O valor selecionado é um domínio de valor codificado. O valor: ${domainValue} será usado"
  },
  "presetPopup": {
    "presetValueLAbel": "Valor Predefinido"
  },
  "dataType": {
    "esriFieldTypeString": "Texto",
    "esriFieldTypeInteger": "Número",
    "esriFieldTypeDate": "Data",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Tipo de Dados",
    "valueLabel": "Valor",
    "fixed": "Corrigido",
    "current": "Actual",
    "past": "Passados",
    "future": "Futuro",
    "popupTitle": "Selecionar Valor",
    "hintForFixedDateType": "Sugestão: a data e hora especificadas serão utilizadas como valor padrão predefinido",
    "hintForCurrentDateType": "Sugestão: a data e hora atuais serão utilizadas como valor padrão predefinido",
    "hintForPastDateType": "Sugestão: o valor especificado será subtraído à data e hora atuais para o valor padrão da definição.",
    "hintForFutureDateType": "Sugestão: o valor especificado será adicionado à data e hora atuais para o valor padrão da definição.",
    "noDateDefinedTooltip": "Nenhuma data definida",
    "relativeDateWarning": "Deve ser especificado um valor para a data ou hora para permitir guardar o valor padrão predefinido.",
    "customLabel": "Personalizar"
  },
  "relativeDomains": {
    "fieldSetTitle": "Lista",
    "valueText": "Valor",
    "defaultText": "Padrão",
    "selectedDomainFieldsHint": "Campo(s) de domínio selecionado(s): ${domainFields}",
    "selectDefaultDomainMsg": "Selecione um domínio de valor padrão ou certifique-se de que a caixa de verificação do domínio padrão está assinalada"
  }
});