define({
  "locatorUrl": "ระบุตำแหน่ง URL",
  "set": "ตั้งค่า",
  "locatorName": "ชื่อโลเคเตอร์",
  "locatorExample": "ตัวอย่าง",
  "countryCode": "ประเทศหรือรหัสภูมิภาค(s)",
  "eg": "เช่น ",
  "countryCodeHint": "ปล่อยให้เป็นค่าว่างจะค้นหาทุกประเทศและภูมิภาค",
  "minCandidateScore": "คะแนนตัวเลือกขั้นต่ำ",
  "minCandidateScoreHint": "หากปล่อยให้ค่านี้ว่าง ระบบจะใช้คะแนนต่ำสุดคือ 90",
  "enableSingleField": "ตัวเลือกฟิลด์เดียว",
  "singleFieldHint": "ข้อมูลที่อยู่จะอยู่ในฟิลด์เดียว",
  "enableMultiField": "ตัวเลือกหลายฟิลด์",
  "multiFieldHint": "ข้อมูลที่อยู่จะอยู่ในหลายฟิลด์",
  "enableXYField": "ตัวเลือกฟิลด์ X/Y",
  "xyFieldHint": "ข้อมูลจะมีค่าพิกัด X/Y",
  "instructionGeocode": "เพิ่มและกำหนดค่าบริการระบุตำแหน่ง",
  "invalidUrlTip": "URL ${URL} ไม่ถูกต้อง หรือไม่สามารถเข้าถึงได้",
  "geocodeTabLabel": "ตั้งค่าตำแหน่งสถานที่",
  "lookupList": "ชื่อฟิลด์ที่จะจำ",
  "isRecognized": "ชื่อฟิลด์ในตารางด้านล่างจะได้รับการจำโดยอัตโนมัติสำหรับฟิลด์นี้",
  "needsEditablePointLayers": "เว็บแมพต้องมีอย่างน้อยชั้นข้อมูลจุดที่แก้ไขได้หนึ่งชั้น",
  "editpageAlias": "ชื่อย่อ",
  "configureFields": "ปรับแต่งฟิลด์ชั้นข้อมูล",
  "configureSingleFields": "กำหนดค่าฟิลด์ที่อยู่เดียว",
  "configureMultiFields": "กำหนดค่าฟิลด์ที่อยู่หลายรายการ",
  "configureXYFields": "กำหนดค่าฟิลด์ X/Y",
  "noFields": "ใช้การดำเนินการแก้ไข เพื่อกำหนดค่าอย่างน้อยหนึ่งฟิลด์ที่จะแสดงผล",
  "display": "แสดงผล",
  "duplicate": "ค้นหารายการซ้ำ",
  "duplicateTip": "ค้นหาฟิลด์นี้เพื่อหาค่าที่เหมือนกันระหว่างไฟล์ต้นทางและชั้นข้อมูลเป้าหมาย/n เมื่อพบค่าที่เหมือนกัน ระบบจะไม่ระบุตำแหน่งบันทึกข้อมูลจากไฟล์ และจะทำเครื่องหมายว่าเป็นรายการซ้ำ",
  "noSelectField": "เลือกตัวเลือกชั้นข้อมูลฟีเจอร์ก่อน",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (ลองจิจูด)",
  "xyFieldsLabelY": "Y (ละติจูด)",
  "xyFieldsX": "เอ๊ก",
  "xyFieldsY": "วาย",
  "easting": "ทิศตะวันออก",
  "northing": "ทิศเหนือ",
  "lon": "ลอง",
  "lat": "ละ",
  "layerOptionHint": "เลือกชั้นข้อมูลที่จะส่งข้อมูลไป",
  "layerFieldTitle": "ชั้นข้อมูลเป้าหมาย",
  "tempSymbolHint": "เลือกสัญลักษณ์ที่จะใช้ในการแสดงผลฟีเจอร์",
  "tempSymbolTitle": "สัญลักษณ์แสดงผล",
  "maxRecords": "บันทึกสูงสุด",
  "maxRecordsHint": "จำนวนบันทึกข้อมูลสูงสุดที่จะระบุตำแหน่ง",
  "searchRadius": "รัศมีการค้นหา",
  "searchRadiusHint": "ระยะทางในการค้นหาฟีเจอร์ที่ซ้ำกันจากชั้นข้อมูล",
  "requiresInteger": "ป้อนค่าตัวเลข",
  "requiresInteger0100": "ป้อนค่าตัวเลขระหว่าง 0 ถึง 100",
  "requiresLocator": "เพิ่งอย่างน้อยหนึ่งตัวระบุตำแหน่งที่ถูกต้อง",
  "layerFields": "การตั้งค่าชั้นข้อมูล",
  "layerFieldsHint": "ระบุฟิลด์จากชั้นข้อมูลเป้าหมายที่จะทำการแมปลงในฟิลด์ต้นทาง",
  "locatorError": "ตัวระบุตำแหน่งไม่ถูกต้องหรือเข้าใช้งานไม่ได้",
  "optionNotMatch": "ตัวเลือกฟิลด์ไม่สอดคล้องกันระหว่างตัวระบุตำแหน่ง Failover อาจไม่ทำงานตามที่คาดไว้",
  "targetLayerTabTitle": "ชั้นข้อมูลเป้าหมาย",
  "locationSettingsTabTitle": "ตั้งค่าตำแหน่งสถานที่",
  "generalSettingsTabTitle": "ตั้งค่าทั่วไป",
  "addTargetLayersLabel": "เพิ่มชั้นข้อมูลเป้าหมาย",
  "introductoryText": "สร้างเนื้อหาเชิงแนะนำสำหรับวิดเจ็ต",
  "defaultStartPageInstructions": "วิดเจ็ตนี้จะช่วยสนับสนุนการประมวลผลและการส่งข้อมูลจากไฟล์ไปยังชั้นข้อมูลที่เลือกในแผนที่<br/> <br/> จะต้องคั่นระหว่างค่าภายในไฟล์ด้วยจุลภาค แท็บ เซมิโคลอน หรือขีดตั้ง",
  "noTargetLayerConfiguredErrorMsg": "ไม่ได้กำหนดค่าชั้นข้อมูลเป้าหมายไว้",
  "noFieldsForTargetLayer": "ไม่ได้กำหนดการตั้งค่าชั้นข้อมูลสำหรับชั้นข้อมูลเป้าหมาย",
  "locationSettingsNotConfigured": "ไม่ได้กำหนดการตั้งค่าตำแหน่งอย่างถูกต้อง",
  "questionMark": "?"
});