define({
  "layersPage": {
    "allLayers": "Tất cả các Lớp",
    "title": "Chọn một biểu mẫu để tạo các đối tượng hoặc nhấp vào một đối tượng trên bản đồ để chỉnh sửa",
    "generalSettings": "Thiết lập Tổng quan",
    "layerSettings": "Thiết lập Lớp",
    "webmapSettingsRadioBtnLabel": "Thiết lập nhận trả trong bản đồ web",
    "customSettingsRadioBtnLabel": "Thiết lập tùy chỉnh",
    "smartActionsTabTitle": "Hành động Thông minh",
    "attributeActionsTabTitle": "Hành động Thuộc tính",
    "geocoderSettingsText": "Cài đặt Bộ mã hóa địa lý",
    "editDescription": "Cung cấp văn bản để hiển thị cho bảng chỉnh sửa",
    "editDescriptionTip": "Văn bản này được hiển thị bên trên trình chọn Mẫu, để trống nếu không có văn bản nào.",
    "promptOnSave": "Nhắc lưu các chỉnh sửa chưa lưu khi đóng biểu mẫu hoặc chuyển sang bản ghi tiếp theo",
    "promptOnSaveTip": "Hiển thị lời nhắc khi đối tượng hiện tại có thay đổi chưa lưu. (Việc sao chép nhiều đối tượng được tự động lưu.)",
    "promptOnDelete": "Yêu cầu xác nhận khi xóa một bản ghi",
    "promptOnDeleteTip": "Hiển thị lời nhắc khi người dùng nhấp vào xóa để xác nhận tác vụ.",
    "removeOnSave": "Xóa đối tượng khỏi lựa chọn khi lưu",
    "removeOnSaveTip": "Tùy chọn để xóa đối tượng khỏi lựa chọn đã đặt khi bản ghi được lưu. Nếu đó là bản ghi duy nhất được chọn, bảng điều khiển được chuyển trở về trang mẫu.",
    "useFilterEditor": "Sử dụng bộ lọc mẫu đối tượng",
    "useFilterEditorTip": "Tùy chọn sử dụng chức năng chọn Bộ lọc Mẫu cung cấp khả năng xem một lớp mẫu hoặc tìm kiếm mẫu theo tên.",
    "groupFilteredTemplates": "Nhóm các kết quả tìm kiếm",
    "groupFilteredTemplatesTip": "Tùy chọn nhóm các kết quả tìm kiếm theo lớp.",
    "displayShapeSelector": "Hiện các tùy chọn vẽ",
    "createNewFeaturesFromExisting": "Cho phép người dùng tạo đối tượng mới từ đối tượng hiện có",
    "createNewFeaturesFromExistingTip": "Tùy chọn cho phép người dùng sao chép đối tượng hiện có để tạo đối tượng mới",
    "copiedFeaturesOverrideDefaults": "Các giá trị đối tượng được sao chép sẽ ghi đè mục mặc định",
    "copiedFeaturesOverrideDefaultsTip": "Các giá trị từ đối tượng được sao chép sẽ chỉ ghi đè các giá trị biểu mẫu mặc định với (các) trường phù hợp",
    "displayShapeSelectorTip": "Tùy chọn hiển thị danh sách các tùy chọn vẽ hợp lệ dành cho biểu mẫu được chọn.",
    "displayPresetTop": "Hiển thị danh sách các giá trị được thiết lập trước trên cùng",
    "displayPresetTopTip": "Tùy chọn hiển thị danh sách giá trị được thiết lập trước trên trình chọn biểu mẫu.",
    "listenToGroupFilter": "Áp dụng các giá trị bộ lọc từ tiện ích Bộ lọc Nhóm cho các trường Thiết lập sẵn",
    "listenToGroupFilterTip": "Khi áp dụng một bộ lọc trong tiện ích Bộ lọc Nhóm, bộ lọc sẽ áp dụng giá trị cho một trường phù hợp trong danh sách giá trị đã Thiết lập sẵn.",
    "keepTemplateActive": "Giữ cho biểu mẫu được chọn hoạt động",
    "editLayerAddedFromAddData": "Cho phép chỉnh sửa các lớp được thêm từ tiện ích Thêm Dữ liệu",
    "editLayerAddedFromAddDataTip": "Có thể chỉnh sửa các lớp được thêm vào ứng dụng bằng tiện ích Thêm Dữ liệu",
    "keepTemplateActiveTip": "Khi trình chọn biểu mẫu được hiển thị, nếu trước đó đã chọn một biểu mẫu, hãy bỏ chọn biểu mẫu đó.",
    "geometryEditDefault": "Bật chỉnh sửa hình học theo mặc định",
    "autoSaveEdits": "Tự động lưu đối tượng mới",
    "enableAttributeUpdates": "Hiển thị nút cập nhật Hành động Thuộc tính",
    "enableAutomaticAttributeUpdates": "Tự động mở chức năng Hành động Thuộc tính sau khi cập nhật thông tin hình học",
    "enableLockingMapNavigation": "Bật chức năng khóa điều hướng bản đồ",
    "enableMovingSelectedFeatureToGPS": "Bật chức năng di chuyển điểm đã chọn đến vị trí GPS",
    "enableMovingSelectedFeatureToXY": "Bật chức năng di chuyển điểm đã chọn đến vị trí XY",
    "featureTemplateLegendLabel": "Thiết lập Feature Template và giá trị Bộ lọc",
    "saveSettingsLegendLabel": "Lưu Thiết lập",
    "geometrySettingsLegendLabel": "Thiết lập Thông tin hình học",
    "actionsSettingsLegendLabel": "Thiết lập Hành động",
    "buttonPositionsLabel": "Vị trí của các nút Lưu, Xóa, Quay lại và Hủy bỏ",
    "belowEditLabel": "Bên dưới chức năng Chỉnh sửa Biểu mẫu",
    "aboveEditLabel": "Bên trên chức năng Chỉnh sửa Biểu mẫu",
    "switchToMultilineInput": "Chuyển sang đầu vào nhiều dòng khi vượt quá độ dài trường",
    "enableValuePicker": "Bật trình chọn giá trị giao cắt",
    "enableValuePickerHint": "Hiển thị lời nhắc khi nhiều giá trị có sẵn cho một trường có hành động thuộc tính giao cắt",
    "expandRelatedTable": "Mở rộng tất cả bảng/lớp khi tải",
    "expandMainTable": "Mở rộng tất cả lớp chính khi tải",
    "layerSettingsTable": {
      "allowDelete": "Cho phép Xóa",
      "allowDeleteTip": "Cho phép Xóa - Tùy chọn để cho phép người dùng xóa đối tượng; tắt nếu lớp không hỗ trợ xóa",
      "edit": "Có thể chỉnh sửa",
      "editTip": "Có thể chỉnh sửa - Tùy chọn để đưa lớp vào tiện ích",
      "label": "Lớp",
      "labelTip": "Lớp - Tên của lớp như được xác định trong bản đồ",
      "update": "Tắt Chỉnh sửa Hình học",
      "updateTip": "Tắt Chỉnh sửa Hình học - Tùy chọn để tắt khả năng di chuyển hình học sau khi đã đặt vào vị trí hoặc di chuyển hình học trên một đối tượng hiện có",
      "allowUpdateOnly": "Chỉ Cập nhật",
      "allowUpdateOnlyTip": "Chỉ Cập nhật - Tùy chọn để cho phép chỉ sửa đổi đối tượng hiện có, được chọn theo mặc định và tắt nếu lớp không hỗ trợ tạo đối tượng mới",
      "fieldsTip": "Sửa đổi các trường cần chỉnh sửa và xác định Thuộc tính Thông minh",
      "actionsTip": "Hành động - Tùy chọn để chỉnh sửa trường hoặc truy cập lớp/bảng liên quan",
      "description": "Mô tả",
      "descriptionTip": "Mô tả - Tùy chọn nhập văn bản để hiển thị trên đầu trang thuộc tính.",
      "relationTip": "Xem các lớp và bảng liên quan"
    },
    "editFieldError": "Các sửa đổi trường và thuộc tính Thông minh không sẵn có với các lớp không thể chỉnh sửa",
    "noConfigedLayersError": "Trình biên tập Thông minh yêu cầu một hoặc nhiều lớp có thể chỉnh sửa.",
    "toleranceErrorMsg": "Giá trị Dung sai Giao cắt Mặc định không hợp lệ",
    "pixelsToleranecErrorMsg": "Giá trị Dung sai Pixel Mặc định không hợp lệ",
    "invalidMaxCharacterErrorMsg": "Giá trị không hợp lệ khi chuyển sang đầu vào nhiều dòng",
    "featuresSelectionTolerance": "Đặt sai số cho lựa chọn đối tượng (pixel)",
    "featuresSelectionToleranceTooltip": "Cho phép người dùng dễ dàng mở bảng chỉnh sửa thuộc tính bằng cách nhấp vào đối tượng địa lý",
    "featuresSelectionToleranceErrorMsg": "Giá trị sai số lựa chọn đối tượng không hợp lệ",
    "autoSaveAttrUpdates": "Tự động lưu các bản cập nhật thuộc tính"
  },
  "editDescriptionPage": {
    "title": "Xác định văn bản tổng quan của thuộc tính cho <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Cấu hình trường cho <b>${layername}</b>",
    "copyActionTip": "Hành động Thuộc tính",
    "editActionTip": "Hành động Thông minh",
    "description": "Sử dụng nút chỉnh sửa Hành động để kích hoạt Thuộc tính Thông minh trên một lớp. Thuộc tính Thông minh có thể yêu cầu, ẩn hoặc vô hiệu hóa một trường dựa trên các giá trị trong trường khác. Sử dụng nút sao chép Hành động để kích hoạt và xác định nguồn giá trị của trường bằng giao lộ, địa chỉ, tọa độ và thiết lập trước.",
    "fieldsNotes": "* là trường bắt buộc. Nếu bạn bỏ chọn Hiển thị cho trường này và mẫu chỉnh sửa không điền giá trị của trường đó, bạn sẽ không thể lưu bản ghi mới.",
    "smartAttachmentText": "Cấu hình Hành động Thông minh cho tệp tin đính kèm",
    "smartAttachmentPopupTitle": "Cấu hình Hành động Thông minh cho tệp tin đính kèm trong <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Vui lòng chọn ít nhất một trường hiển thị cho lớp ${layerName}",
    "fieldsSettingsTable": {
      "display": "Hiển thị",
      "displayTip": "Hiển thị - Xác định có hiển thị trường hay không",
      "edit": "Có thể chỉnh sửa",
      "editTip": "Có thể chỉnh sửa - Chọn nếu trường có trong biểu mẫu thuộc tính",
      "fieldName": "Tên",
      "fieldNameTip": "Tên - Tên của trường được xác định trong cơ sở dữ liệu",
      "fieldAlias": "Bí danh",
      "fieldAliasTip": "Tên hiển thị - Tên của trường được xác định trong bản đồ",
      "canPresetValue": "Thiết lập trước",
      "canPresetValueTip": "Đặt trước - Tùy chọn để hiển thị trường trong danh sách trường cài sẵn và cho phép người dùng đặt giá trị trước khi chỉnh sửa",
      "actions": "Các hành động",
      "actionsTip": "Hành động - Thay đổi thứ tự của các trường hoặc thiết lập Thuộc tính Thông minh"
    },
    "smartAttSupport": "Không hỗ trợ Thuộc tính Thông minh trên các trường cơ sở dữ liệu bắt buộc"
  },
  "actionPage": {
    "title": "Cấu hình Hành động Thuộc tính cho <b>${fieldname}</b>",
    "smartActionTitle": "Cấu hình Hành động Thông minh cho <b>${fieldname}</b>",
    "description": "Các tác vụ luôn được tắt trừ khi bạn chỉ định tiêu chí kích hoạt tác vụ. Các tác vụ được xử lý theo thứ tự và chỉ một tác vụ được kích hoạt mỗi trường. Sử dụng nút Chỉnh sửa Tiêu chí để xác định tiêu chí.",
    "copyAttributesNote": "Vô hiệu hóa bất kỳ hành động nào có tên nhóm sẽ giống như điều chỉnh hành động đó độc lập và sẽ xóa hành động cho trường này khỏi nhóm tương ứng.",
    "searchPlaceHolder": "Tìm kiếm",
    "expandAllLabel": "Mở rộng tất cả các lớp",
    "selectAllLabel": "Chọn tất cả các trường",
    "domainListTitle": "Các trường tên miền",
    "noValidFieldTypeMsg": "Không có sẵn lớp thích hợp trong bản đồ cho loại dữ liệu này",
    "actionsSettingsTable": {
      "rule": "Hành động",
      "ruleTip": "Hành động - Hành động được thực hiện khi các tiêu chí được thỏa mãn",
      "expression": "Biểu thức",
      "expressionTip": "Biểu thức - Biểu thức kết quả ở định dạng SQL từ tiêu chí được xác định",
      "groupName": "Tên Nhóm",
      "groupNameTip": "Tên Nhóm - Hiển thị tên nhóm mà từ đó biểu thức được áp dụng",
      "actions": "Tiêu chí",
      "actionsTip": "Tiêu chí - Thay đổi thứ tự của quy tắc và xác định tiêu chí khi kích hoạt"
    },
    "copyAction": {
      "description": "Nguồn giá trị của trường được xử lý để nếu được kích hoạt cho đến khi một tiêu chí hợp lệ được kích hoạt hoặc danh sách hoàn chỉnh. Sử dụng nút Chỉnh sửa Tiêu chí để xác định tiêu chí.",
      "intersection": "Giao lộ",
      "coordinates": "Tọa độ",
      "address": "Địa chỉ",
      "preset": "Thiết lập trước",
      "actionText": "Các hành động",
      "criteriaText": "Tiêu chí",
      "enableText": "Đã bật"
    },
    "actions": {
      "hide": "Ẩn",
      "required": "Yêu cầu",
      "disabled": "Vô hiệu hóa"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Cảnh báo: Việc chỉnh sửa độc lập sẽ xóa hành động thuộc tính được chọn liên quan đến trường này ra khỏi nhóm",
      "editGroupHint": "Cảnh báo: Việc chỉnh sửa độc lập sẽ xóa hành động thông minh được chọn liên quan đến trường này ra khỏi nhóm",
      "popupTitle": "Chọn tùy chọn chỉnh sửa",
      "editAttributeGroup": "Hành động thuộc tính đã chọn được xác định từ nhóm. Chọn một trong các tùy chọn sau để chỉnh sửa hành động thuộc tính:",
      "expression": "Biểu thức của hành động thông minh đã chọn được xác định từ nhóm. Chọn một trong các tùy chọn sau để chỉnh sửa biểu thức hành động thông minh:",
      "editGroupButton": "Chỉnh sửa Nhóm",
      "editIndependentlyButton": "Chỉnh sửa Riêng"
    }
  },
  "filterPage": {
    "submitHidden": "Gửi dữ liệu thuộc tính cho các trường này ngay cả khi bị ẩn",
    "title": "Cấu hình biểu thức cho quy tắc ${action}",
    "filterBuilder": "Đặt tác vụ trên trường khi bản ghi trùng khớp với ${any_or_all} các biểu thức sau",
    "noFilterTip": "Sử dụng các công cụ bên trên, xác định câu lệnh về thời điểm tác vụ được kích hoạt."
  },
  "geocoderPage": {
    "setGeocoderURL": "Thiết lập URL Trình mã hóa địa lý",
    "hintMsg": "Lưu ý: Bạn đang thay đổi dịch vụ mã hóa địa lý, hãy chắc chắn cập nhật mọi quá trình lập bản đồ trường mã hóa địa lý bạn đã cấu hình.",
    "invalidUrlTip": "URL ${URL} không hợp lệ hoặc không thể truy cập được."
  },
  "addressPage": {
    "popupTitle": "Địa chỉ",
    "checkboxLabel": "Nhận giá trị từ Bộ mã hóa địa lý",
    "selectFieldTitle": "Thuộc tính",
    "geocoderHint": "Để thay đổi bộ mã hóa địa lý, chọn nút 'Cài đặt Bộ mã hóa địa lý' trong phần cài đặt chung",
    "prevConfigruedFieldChangedMsg": "Không tìm thấy thuộc tính được cấu hình trước đó trong cài đặt bộ mã hóa địa lý hiện tại. Thuộc tính đã được đặt lại về mặc định.",
    "questionMark": "?",
    "consumesCredits": "Công cụ này tiêu tốn điểm tín dụng khi dùng với Dịch vụ Mã hóa địa lý Thế giới Trực tuyến của ArcGIS"
  },
  "coordinatesPage": {
    "popupTitle": "Tọa độ",
    "checkboxLabel": "Nhận tọa độ",
    "coordinatesSelectTitle": "Hệ Tham chiếu",
    "coordinatesAttributeTitle": "Thuộc tính",
    "mapSpatialReferenceOptionLabel": "Tham chiếu Không gian Bản đồ",
    "latLongOptionLabel": "Vĩ độ/Kinh độ",
    "MGRS": "MGRS",
    "allGroupsCreatedMsg": "Tất cả các nhóm có thể có đã được tạo",
    "coordinatesSourceTitle": "Nguồn Tọa độ",
    "featureLocation": "Vị trí Đối tượng",
    "myLocation": "Vị trí của tôi",
    "LatLong": {
      "y": "Vĩ độ",
      "x": "Kinh độ",
      "xy": "Kinh độ Vĩ độ",
      "yx": "Vĩ độ Kinh độ"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Thiết lập trước",
    "checkboxLabel": "Trường sẽ được đặt trước",
    "showOnlyDomainFields": "Chỉ hiển thị các trường có domain",
    "hideInPresetDisplay": "Ẩn trong phần hiển thị giá trị định sẵn",
    "presetValueLabel": "Giá trị đặt trước hiện tại là:",
    "changePresetValueHint": "Để thay đổi giá trị đã thiết lập này, chọn nút “Xác định Giá trị Đặt trước” trong phần cài đặt chung"
  },
  "intersectionPage": {
    "groupNameLabel": "Tên Nhóm",
    "dataTypeLabel": "Loại Dữ liệu",
    "ignoreLayerRankingCheckboxLabel": "Bỏ qua xếp hạng lớp và tìm đối tượng gần nhất trên tất cả các lớp đã định",
    "intersectingLayersLabel": "Lớp cần trích xuất giá trị",
    "layerAndFieldsApplyLabel": "Lớp và trường cần áp dụng giá trị đã trích xuất",
    "checkboxLabel": "Nhận giá trị từ trường của lớp giao cắt",
    "layerText": "Lớp",
    "fieldText": "Trường",
    "actionsText": "Các hành động",
    "toleranceSettingText": "Cài đặt Dung sai",
    "addLayerLinkText": "Thêm lớp",
    "useDefaultToleranceText": "Sử dụng Dung sai Mặc định",
    "toleranceValueText": "Giá trị Dung sai",
    "toleranceUnitText": "Đơn vị Dung sai",
    "pixelsUnitText": "Pixel",
    "useLayerName": "- Sử dụng Tên Lớp -",
    "noLayersMessage": "Không tìm thấy trường nào trong các lớp bản đồ khớp với kiểu dữ liệu đã chọn.",
    "intersectionLayerHint": "Xếp hạng cho lớp được xác định theo thứ tự giảm dần. Sử dụng mũi tên trong Hành động để thay đổi thứ tự cho lớp và thay đổi ưu tiên giao cắt."
  },
  "presetAll": {
    "popupTitle": "Xác định giá trị đặt trước mặc định",
    "deleteTitle": "Xóa giá trị đặt trước",
    "hintMsg": "Ở đây liệt kê tất cả các tên trường đặt trước duy nhất. Xóa một trường đặt trước sẽ vô hiệu hóa trường tương ứng được đặt làm giá trị thiết lập sẵn từ tất cả các lớp/bảng."
  },
  "intersectionTolerance": {
    "intersectionTitle": "Dung sai giao cắt mặc định cho tất cả đối tượng",
    "pixelsToleranceTitle": "Dung sai giao cắt mặc định (giá trị pixel) chỉ được áp dụng cho các đối tượng điểm"
  },
  "smartActionsPage": {
    "smartActionLabel": "Cấu hình Hoạt động Thông minh",
    "addNewSmartActionLinkText": "Thêm Mới",
    "definedActions": "Hành động được Xác định",
    "priorityPopupTitle": "Thiết lập mức độ ưu tiên của Hành động Thông minh",
    "priorityPopupColumnTitle": "Hành động Thông minh",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Tên Nhóm",
    "layerForExpressionLabel": "Lớp cho Biểu thức",
    "layerForExpressionNote": "Lưu ý: Các trường của lớp này được sử dụng để xác định các tiêu chí biểu thức. 'Các lớp và trường được áp dụng' chỉ hiển thị các lớp và bảng đã được xác định trường trong Biểu thức.",
    "expressionText": "Biểu thức",
    "editExpressionLabel": "Chỉnh sửa Biểu thức",
    "layerAndFieldsApplyLabel": "Lớp và trường cần áp dụng trên",
    "submitAttributeText": "Gửi dữ liệu thuộc tính cho các trường này ngay cả khi bị ẩn",
    "priorityColumnText": "Ưu tiên",
    "requiredGroupNameMsg": "Giá trị này là bắt buộc.",
    "uniqueGroupNameMsg": "Nhập tên nhóm duy nhất, đã tồn tại nhóm có tên này.",
    "deleteGroupPopupTitle": "Xóa Nhóm Hành động Thông minh",
    "deleteGroupPopupMsg": "Xóa nhóm sẽ xóa biểu thức khỏi tất cả Hành động của Trường được liên kết.",
    "invalidExpression": "Không được để trống biểu thức.",
    "warningMsgOnLayerChange": "Biểu thức được xác định và các trường được áp dụng sẽ bị xóa.",
    "smartActionsTable": {
      "name": "Tên",
      "expression": "Biểu thức",
      "definedFor": "Được xác định cho"
    }
  },
  "attributeActionsPage": {
    "name": "Tên",
    "type": "Loại",
    "deleteGroupPopupTitle": "Xóa Nhóm Hành động Thuộc tính",
    "deleteGroupPopupMsg": "Xóa nhóm sẽ dẫn đến xóa hành động thuộc tính khỏi tất cả Trường được liên kết.",
    "alreadyAppliedActionMsg": "Hành động ${action} được áp dụng cho trường này trong nhóm",
    "alreadyAppliedActionLayerMsg": "Hành động ${action} được áp dụng cho trường này từ Thiết lập Lớp",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Nhóm này không có các trường liên quan.",
    "presetNoFieldWarningMsg": "Vui lòng cấu hình ít nhất một trường cho nhóm đặt trước : ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Trường",
    "valueLabel": "Giá trị",
    "selectValueLabel": "Chọn Giá trị",
    "domainFieldHintLabel": "Giá trị được chọn là một miền giá trị mã hóa. Giá trị: ${domainValue} sẽ được sử dụng"
  },
  "presetPopup": {
    "presetValueLAbel": "Giá trị Đặt trước"
  },
  "dataType": {
    "esriFieldTypeString": "Chuỗi",
    "esriFieldTypeInteger": "Số",
    "esriFieldTypeDate": "Ngày",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Loại Ngày",
    "valueLabel": "Giá trị",
    "fixed": "Cố định",
    "current": "Hiện tại",
    "past": "Quá khứ",
    "future": "Tương lai",
    "popupTitle": "Chọn Giá trị",
    "hintForFixedDateType": "Gợi ý: Ngày và giờ chỉ định sẽ được sử dụng làm giá trị mặc định đặt trước",
    "hintForCurrentDateType": "Gợi ý: Ngày và giờ hiện tại sẽ được sử dụng làm giá trị mặc định đặt trước",
    "hintForPastDateType": "Gợi ý: Giá trị chỉ định sẽ được trừ đi từ ngày và giờ hiện tại để tính giá trị đặt trước mặc định.",
    "hintForFutureDateType": "Gợi ý: Giá trị chỉ định sẽ được trừ cộng vào ngày và giờ hiện tại để tính giá trị đặt trước mặc định.",
    "noDateDefinedTooltip": "Không xác định ngày",
    "relativeDateWarning": "Phải chỉ định giá trị cho ngày hoặc thời gian để có thể lưu giá trị đặt trước mặc định.",
    "customLabel": "Tùy chỉnh"
  },
  "relativeDomains": {
    "fieldSetTitle": "Danh sách",
    "valueText": "Giá trị",
    "defaultText": "Mặc định",
    "selectedDomainFieldsHint": "(Các) trường tên miền đã chọn: ${domainFields}",
    "selectDefaultDomainMsg": "Vui lòng chọn giá trị domain mặc định hoặc chắc chắn đánh dấu hộp kiểm tra domain mặc định đã chọn"
  }
});