define({
  "addLayer": "Pridať vrstvu",
  "layerName": "Vrstva",
  "layerRefresh": "Obnoviť",
  "layerLabel": "Označenie",
  "actions": "Akcie",
  "mainPanelTextPlaceholder": "napr: Naposledy aktualizované:",
  "invalidInterval": "Povolené sú výlučne kladné celé čísla",
  "uploadImage": "Nahrať obrázok",
  "iconColumnText": "Zobrazenie",
  "refreshInterval": "Čas v minútach",
  "refreshIntervalTitle": "Vyhodnotené ako čas v minútach",
  "mainPanelText": "Text hlavného panelu",
  "mainPanelIcon": "Obrázok hlavného panela",
  "refreshIntervalInstruction": "Obnoviť vrstvy každých:",
  "optionsText": "Možnosti",
  "symbolOptionsText": "Symbolika mapy",
  "iconOptionsText": "Symbolika panela",
  "sympolPopupTitle": "Nastavenie zobrazenia",
  "rdoLayer": "Predvolený symbol",
  "rdoCustom": "Použiť obrázok",
  "chkCluster": "Povoliť vytváranie klastrov",
  "defineClusterSymbol": "Špecifikovať symbol zhluku",
  "rdoEsri": "Vybrať symbol",
  "rdoLayerIcon": "Použiť symbol mapy",
  "rdoCustomIcon": "Použiť obrázok",
  "editCustomSymbol": "Upraviť vlastný symbol",
  "editCustomIcon": "Upraviť vlastnú ikonu",
  "missingRefreshValue": "Prosím poskytnite hodnotu intervalu obnovovania.",
  "panelIconOption": "Zobraziť obrázok loga",
  "enableRefresh": "Povoliť obnovovanie vrstvy",
  "disableRefresh": "Obnovovanie vrstvy povolené len pre zbierky prvkov.",
  "refreshUnit": "minúty.minút.",
  "symbolOptions": "Symbol",
  "panelFeatureDisplay": "Panel",
  "chkGroup": "Zoskupiť prvky",
  "selectField": "Pole",
  "fieldLabel": "Označenie",
  "addField": "Pridať stĺpec",
  "featureOptionsText": "Možnosti vrstvy",
  "groupOptionsText": "Možnosti skupiny",
  "panelCountOption": "Zobraziť počet prvkov",
  "missingLayerInWebMap": "Nebola nájdená operačná vrstva.",
  "displayClusterCnt": "Zobraziť počet prvkov",
  "defineClusterFont": "Špecifikovať farbu písma",
  "max_records": "Bol dosiahnutý maximálny limit stĺpca",
  "hidePanel": "Skryť panel",
  "hidePanelHelp": "Povoliť/Zakázať zobrazenie hlavného panela.",
  "continuousRefreshHelp": "Poznámka: Obnovovanie zbierky prvkov sa bude opakovať nepretržite.",
  "panelCountOptionHelp": "Povoliť/Zakázať zobrazenie počtu prvkov",
  "panelIconOptionHelp": "Povoliť/Zakázať zobrazenie loga na hlavnom paneli.",
  "rdoGroupByField": "podľa stĺpca",
  "rdoGroupByRenderer": "podľa vykresľovača",
  "expandList": "Rozbaliť zoznam pri štarte",
  "expandListHelp": "Povoliť/Zakázať predvolené rozbalenie zoznamu.",
  "chkFeatureDisplay": "Deaktivovať zoznam prvkov",
  "showAllFeaturesHelp": "Povoliť/Zakázať zobrazenie všetkých prvkov bez ohľadu na rozsah.",
  "showAllFeatures": "Zobraziť všetky prvky",
  "fieldsWarning": "Žiadne stĺpce neboli definované v kontextovom okne. Voliteľné: Použite akciu úpravy na definovanie možností zobrazenia panela.",
  "displayClusterLayer": "Zachovať symboly zhluku po zatvorení widgetu",
  "invalidSymbolWidthMessage": "Výberovník symbolov obsahuje chybu, prosím, opravte ich pred použitím.",
  "sortLabel": "Zoradiť",
  "ascRadioBtnLabel": "Vzostupne",
  "descRadioBtnLabel": "Zostupne"
});