define({
  "taskUrl": "URL úlohy",
  "serviceURLPlaceholder": "Prosím vložte URL geoprocesnej úlohy",
  "layerOrder": "Poradie vrstiev",
  "defaultValue": "Predvolená hodnota",
  "inputFeatureBy": "Vložiť prvok podľa",
  "inputRecordBy": "Vložiť záznam podľa",
  "renderer": "Vykresľovač",
  "displayType": "Typ zobrazenia",
  "helpUrl": "URL pomocníka",
  "useResultMapService": "Zobraziť výsledok prostredníctvom mapovej služby",
  "drawOnMap": "Interaktívne kresliť na mape",
  "selectLayer": "Vybrať vrstvu z mapy",
  "selectTable": "Vybrať tabuľku z mapy",
  "shareResults": "Pridať výsledok ako operačnú vrstvu",
  "setTask": "Nastaviť",
  "setTaskTitle": "Nastaviť GP úlohu",
  "enablePopup": "Povoliť kontextové okno",
  "unSupportGeometryType": "Vykresľovač sa nedá nastaviť kvôli neznámemu typu geometrie.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Nahrať súbor",
  "selectFileToUpload": "Vybrať súbor...",
  "rasterFormat": "Formát rastrových údajov",
  "noFileSelected": "Žiadny vybraný súbor!",
  "uploadSuccess": "Súbor bol úspešne nahratý!",
  "showLayerContent": "Zobraziť obsah vrstvy",
  "urlPlaceholder": "URL na prístup k údajom",
  "useShapefile": "Použiť shapefile v lokálnom systéme súborov",
  "allowToExport": "Povoliť export výsledkov",
  "useDynamicSchema": "Výstup môže mať odlišnú schému, použiť dynamickú schému namiesto preddefinovanej.",
  "useCurrentMapExtent": "Použiť aktuálny rozsah mapy",
  "ignoreOutput": "Ignorovať tento výstup",
  "turnOffOutput": "Predvolene vypnúť túto vrstvu",
  "inputJSONString": "Vložiť JSON reťazec",
  "useFeatureCollection": "Neposielajte URL ale FeatureCollections ako vstup."
});