define({
  "transparencyLabel": "Transparence",
  "outline": "Contour",
  "fill": "Remplissage (La couleur s’applique uniquement lorsque le style est uni)",
  "style": "Style",
  "mandatoryLabel": "Distance d’évacuation obligatoire",
  "mandatoryButtonLabel": "Configurer les paramètres de distance d’évacuation obligatoire",
  "safeLabel": "Distance d’évacuation de sécurité",
  "safeButtonLabel": "Configurer les paramètres de distance d’évacuation de sécurité",
  "selectOpLayerLabel": "Sélectionner une couche opérationnelle pour les résultats",
  "selectDefaultMeasurementLabel": "Sélectionner une unité de mesure par défaut.",
  "helpIconTooltip": "La liste des couches opérationnelles est renseignée à l’aide des couches de la carte web actuelle dont le type de géométrie est Polygone.",
  "lineStyles": {
    "esriSLSDash": "Tiret",
    "esriSLSDashDot": "Tiret-point",
    "esriSLSDashDotDot": "Tiret-point-point",
    "esriSLSDot": "Point",
    "esriSLSLongDash": "Tiret long",
    "esriSLSLongDashDot": "Tiret-point long",
    "esriSLSNull": "Nulle",
    "esriSLSShortDash": "Tiret court",
    "esriSLSShortDashDot": "Tiret court-point",
    "esriSLSShortDashDotDot": "Tiret court-point-point",
    "esriSLSShortDot": "Point court",
    "esriSLSSolid": "Solide"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Arrière",
    "esriSFSCross": "Croiser",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Avant",
    "esriSFSHorizontal": "Horizontale",
    "esriSFSNull": "Nulle",
    "esriSFSSolid": "Solide",
    "esriSFSVertical": "Verticale"
  },
  "threatTypeLabel": "Type de risque",
  "symbologyLabel": "Symbologie",
  "generalLabel": "Généralités",
  "addThreatTypesLabel": "Ajouter un type de risque",
  "threatTypeColLabel": "Type de risque chimique",
  "actions": "Actions",
  "newThreatTypePopupLabel": "Nouveau type de risque",
  "chooseDefaultThreatTypeIconLabel": "Choisir parmi les valeurs par défaut",
  "mandatoryDistance": "Distance d’évacuation obligatoire",
  "safeDistance": "Distance d’évacuation de sécurité",
  "units": "Unités",
  "chooseDefaultThreatLabel": "Sélectionner un type de risque par défaut",
  "defaultThreatTypePopUpLabel": "Type de risque par défaut",
  "editThreatLabel": "Mettre à jour le risque",
  "defaultThreatTypeIconTooltip": "Liste des types de risque par défaut",
  "uniqueThreatTypeMsg": "Saisissez un type de risque unique. Un type de risque portant ce nom existe déjà.",
  "requiredThreatTypeMsg": "Ce champ est obligatoire.",
  "unitMeasureLabel": "Les distances sont en {0}",
  "pipeBombLabel": "Bombe artisanale",
  "suicideBombLabel": "Attentat-suicide",
  "briefcaseLabel": "Colis piégé",
  "carLabel": "Voiture",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Camionnette de livraison",
  "containerWaterTruckLabel": "Camion-citerne/remorque",
  "semiTrailerLabel": "Semi-remorque",
  "lpgSafeDistanceLable": "Distance de sécurité",
  "fireBallDiameterLable": "Diamètre de boule de feu",
  "lpgthreatTypeColLabel": "Type de risque lié au GPL",
  "threatTypeCatagoryLabel": "Catégorie du type de risque",
  "chemicalThreatLegendLabel": "Risque chimique",
  "lpgThreatLegendLabel": "Risque lié au GPL",
  "fireballButtonLabel": "Configurer les paramètres de diamètre de boule de feu",
  "safeDistanceButtonLabel": "Configurer les paramètres de distance de sécurité",
  "chemicalThreatCatagoryLabel": "Chimique",
  "lpgThreatCatagoryLabel": "GPL",
  "smallLPGTank": "Petit réservoir GPL",
  "largeLPGTank": "Grand réservoir GPL",
  "commercialResidentialLPGTank": "Réservoir GPL commercial/résidentiel",
  "smallLPGTruck": "Petit camion GPL",
  "semiTankerLPG": "Camion-citerne GPL"
});