define({
  "_widgetLabel": "Trình biên tập Thuộc tính Theo đợt",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Tên lớp",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Không có lớp có thể chỉnh sửa nào được cấu hình",
  "editorPopupTitle": "Trình biên tập Thuộc tính Theo đợt",
  "editorPopupSaveBtn": "Lưu",
  "editorPopupMultipleValues": "",
  "clear": "Xóa",
  "featuresUpdated": "Đã cập nhật (các) đối tượng ${0} / ${1}",
  "featuresSelected": "Đã chọn ${0} đối tượng",
  "featuresSkipped": "Đã vượt qua",
  "featuresNoPermision": "Đã chọn ${0} đối tượng nhưng không có quyền chỉnh sửa.",
  "search": "Tìm kiếm",
  "queryInput": "Nhập giá trị để truy vấn",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Vui lòng thiết lập bộ lọc chính xác.",
  "filterPopup": "Lớp Lọc",
  "filterAppend": "Nếu một bộ lọc đã tồn tại trong bản đồ web cho lớp này",
  "filterAppendOR": "Thêm biểu thức bất kỳ vào bộ lọc bản đồ hiện tại",
  "filterAppendAND": "Thêm tất cả biểu thức vào bộ lọc bản đồ hiện tại",
  "cancel": "Hủy",
  "noValue": "Không có Giá trị",
  "emptyString": "Chuỗi Trống",
  "existingValue": "Giữ Giá trị Có sẵn",
  "newDate": "Dữ liệu Mới",
  "valueChooser": "Chọn/Nhập một Giá trị",
  "ok": "OK",
  "drawBox": {
    "point": "Điểm",
    "line": "Đường",
    "polyline": "Hình nhiều đường",
    "freehandPolyline": "Đa tuyến vẽ tay",
    "extent": "Phạm vi",
    "polygon": "Hình đa giác",
    "freehandPolygon": "Đa giác vẽ tay",
    "clear": "Xóa",
    "addPointToolTip": "Bấm để chọn trong diện tích này",
    "addShapeToolTip": "Vẽ một hình để chọn đối tượng",
    "freehandToolTip": "Nhấn và giữ để vẽ một hình để chọn đối tượng",
    "startToolTip": "Vẽ một hình để chọn đối tượng"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Đối tượng từ ${0} đã trả về ID không hợp lệ",
    "noSelectedLayers": "Không có lớp được chọn nào có bản ghi cần cập nhật",
    "inputValueError": "Giá trị không hợp lệ trong biểu mẫu",
    "saveError": "Không thể lưu ${0} đối tượng",
    "requiredValue": "Giá trị Yêu cầu"
  }
});