define({
  "feedbackStyleLabel": "Estilo de Feedback de Distância e Direção",
  "showTabLabel": "Mostrar todos os separadores",
  "tabErrorMessage": "Selecione pelo menos um separador no grupo \"Estilo de Feedback de Distância e Direção\"",
  "lineLabel": "Linha",
  "circleLabel": "Círculo",
  "ellipseLabel": "Elipse",
  "ringsLabel": "Anéis",
  "transparency": "Transparência",
  "operationalLineLayerSelectLabel": "Selecionar uma camada de polilinhas operacional para resultados de linha e anéis",
  "operationalPolygonLayerSelectLabel": "Selecionar uma camada de polígonos operacional para resultados de círculo e elipse",
  "helpIconPolylineTooltip": "A lista de camadas operacionais é preenchida com camadas do mapa web atual do tipo de geometria de polilinha.",
  "helpIconPolygonTooltip": "A lista de camadas operacionais é preenchida com camadas do mapa web atual do tipo de geometria de polígono.",
  "feedbackResultsLayerLabel": "Camada de Resultados de Estilo de Feedback de Distância e Direção",
  "editSymbologyHint": "Sugestão: clique no ícone de pré-visualização para editar a simbologia",
  "feedbackTextColorLabel": "Cor do texto da etiqueta de feedback",
  "feedbackTextSizeLabel": "Tamanho do texto da etiqueta de feedback",
  "previewLabel": "Pré-visualizar",
  "lineSymbologyPopupTittle": "Simbologia de linha",
  "circleSymbologyPopupTittle": "Simbologia de círculo",
  "ellipseSymbologyPopupTittle": "Simbologia de elipse",
  "ringSymbologyPopupTittle": "Simbologia de anéis"
});