define({
  "_widgetLabel": "Atributų paketo rengyklė",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Sluoksnio pavadinimas",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Sukonfigūruotų redaguojamų sluoksnių nėra",
  "editorPopupTitle": "Atributų paketo rengyklė",
  "editorPopupSaveBtn": "Įrašyti",
  "editorPopupMultipleValues": "",
  "clear": "Valyti",
  "featuresUpdated": "${0} / ${1} elementas (-ų) atnaujintas",
  "featuresSelected": "${0} elementas (-ų) pasirinktas",
  "featuresSkipped": "Apeita",
  "featuresNoPermision": "Pasirinkta (-os) ${0} funkcija (-os), bet nėra leidimo redaguoti.",
  "search": "Ieškoti",
  "queryInput": "Įveskite reikšmę į užklausą",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Nustatykite filtrą tinkamai.",
  "filterPopup": "Filtruoti sluoksnį",
  "filterAppend": "Jei šio sluoksnio internetiniame žemėlapyje jau yra filtras",
  "filterAppendOR": "Pridėti bet kurią sąlygą prie esamo žemėlapio filtro",
  "filterAppendAND": "Pridėti visas sąlygas prie esamo žemėlapio filtro",
  "cancel": "Atšaukti",
  "noValue": "Reikšmių nėra",
  "emptyString": "Tuščia eilutė",
  "existingValue": "Palikti esamas reikšmes",
  "newDate": "Nauja data",
  "valueChooser": "Pasirinkite / įveskite reikšmę",
  "ok": "Gerai",
  "drawBox": {
    "point": "Kyšulys",
    "line": "Linija",
    "polyline": "Polilinija",
    "freehandPolyline": "Laisvai piešiama linija",
    "extent": "Aprėptis",
    "polygon": "Plotas",
    "freehandPolygon": "Laisvai piešiamas poligonas",
    "clear": "Valyti",
    "addPointToolTip": "Spustelėkite, kad pasirinktumėte šioje vietovėje",
    "addShapeToolTip": "Nubrėžkite figūrą, kad pasirinktumėte elementus",
    "freehandToolTip": "Paspauskite ir laikykite, kad nubrėžtumėte figūrą ir pasirinktumėte elementus",
    "startToolTip": "Nubrėžkite figūrą, kad pasirinktumėte elementus"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Elementas iš ${0} pateikė netinkamą ID",
    "noSelectedLayers": "Nėra naujinamų sluoksnių su įrašais",
    "inputValueError": "Netinkama reikšmė formoje",
    "saveError": "Nepavyko įrašyti ${0} elementų",
    "requiredValue": "Būtina reikšmė"
  }
});