define({
  "taskUrl": "Vaateväljateenuse URL",
  "portalURL": "Määrake oma ArcGIS Online'i organisatsiooni veebilehe või Portal for ArcGIS-i URL",
  "portalURLError": "ArcGIS Online'i organisatsiooni veebilehe või Portal for ArcGIS-i konfigureeritud URL ei ole kehtiv.",
  "privilegeError": "Teie kasutajaroll ei luba teha analüüsi. Analüüsi tegemiseks peab teie organisatsiooni administraator andma teile teatud <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">õigused</a>.",
  "noServiceError": "Kõrgusanalüüsi teenus pole saadaval. Kontrollige ArcGIS Online'i organisatsiooni veebilehe või Portal for ArcGIS-i konfiguratsioone.",
  "maximumRangeMessage": "Maksimaalne vaadeldav vahemik peab olema suurem kui minimaalne vaadeldav vahemik ja ei tohi ületada ${limit} ${units}.",
  "serviceURLPlaceholder": "Sisestage vaatevälja geotöötluse toimingu URL",
  "setTask": "Määra",
  "setTaskTitle": "Määrake vaatevälja geotöötluse toiming",
  "serviceURLError": "Geotöötluse toiming, mida proovite selle vidina kaudu konfigureerida, ei sobi. Valige sobiv vaatevälja geotöötluse toimingu URL.",
  "defaultMilsForAnglesLabel": "Kasuta nurkade vaikeühikuna milliradiaane",
  "defaultObserverHeightLabel": "Vaatleja kõrguse vaikeühik",
  "defaultObservableDistanceLabel": "Vaadeldava kauguse vaikeühik",
  "defaultObserveHeightLabel": "Vaatleja vaikekõrgus",
  "defaultMinimumObservableDistanceLabel": "Minimaalne vaadeldav vaikekaugus",
  "defaultMaximumObservableDistanceLabel": "Maksimaalne vaadeldav vaikekaugus",
  "units": {
    "miles": "mi",
    "kilometers": "km",
    "feet": "ft",
    "meters": "m",
    "yards": "jardi",
    "nauticalMiles": "Meremiili"
  },
  "helpIconTooltip": "Töökihtide nimekiri sisaldab kihte praegusest veebikaardist, mis on polügooni tüüpi.",
  "selectOperationalLayerLabel": "Valige tulemuste jaoks töökiht",
  "lineOfSightTabTitle": "Vaateväli",
  "symbologyTabTitle": "Sümboloogia",
  "transparency": "Läbipaistvus",
  "outline": "Äärejoon",
  "fill": "Täida (värv rakendatakse ainult juhul, kui valitud on pidev laad)",
  "style": "Stiil",
  "selectOpLayerLabel": "Vali tulemuste töökiht",
  "selectDefaultMeasurementLabel": "Vali vaikimisi mõõtühik",
  "visibleSectionLabel": "Nähtav sektsioon",
  "nonVisibleSectionLabel": "Nähtamatu sektsioon",
  "visibleSectionButtonLabel": "Konfigureeri nähtava sektsiooni sätted",
  "nonVisibleSectionButtonLabel": "Konfigureeri nähtamatu sektsiooni sätted",
  "colorPicker": "Värvivalija",
  "lineStyles": {
    "esriSLSDash": "Katkendlik",
    "esriSLSDashDot": "Katkendlik punktiga",
    "esriSLSDashDotDot": "Katkendlik kahe punktiga",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Pikk katkendlik kriips",
    "esriSLSLongDashDot": "Pikk katkendlik kriips punktiga",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lühike katkendlik kriips",
    "esriSLSShortDashDot": "Lühike katkendlik kriips punktiga",
    "esriSLSShortDashDotDot": "Lühike katkendlik kriips kahe punktiga",
    "esriSLSShortDot": "Lühike punktiir",
    "esriSLSSolid": "Pidev"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Tagasi",
    "esriSFSCross": "Rist",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Edasi",
    "esriSFSHorizontal": "Horisontaalne",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Pidev",
    "esriSFSVertical": "Vertikaalne"
  }
});