define({
  "locatorUrl": "URL localizator",
  "set": "Setare",
  "locatorName": "Nume localizator",
  "locatorExample": "Exemplu",
  "countryCode": "Cod(uri) ţară sau regiune",
  "eg": "de ex. ",
  "countryCodeHint": "Dacă lăsaţi această valoare necompletată, vor fi căutate toate ţările şi regiunile",
  "minCandidateScore": "Scor minim candidat",
  "minCandidateScoreHint": "Dacă lăsaţi această valoare necompletată, se va folosi un scor minim candidat de 90",
  "enableSingleField": "Opțiuni câmp unic",
  "singleFieldHint": "Datele cu privire la adresă vor fi trecute într-un singur câmp",
  "enableMultiField": "Opțiuni câmpuri multiple",
  "multiFieldHint": "Datele cu privire la adresă vor fi trecute în câmpuri multiple",
  "enableXYField": "Opțiuni câmp X/Y",
  "xyFieldHint": "Datele vor conţine valori ale coordonatelor X/Y",
  "instructionGeocode": "Adăugați și configurați servicii de localizare.",
  "invalidUrlTip": "Adresa URL ${URL} este nevalidă sau inaccesibilă.",
  "geocodeTabLabel": "Setări locaţie",
  "lookupList": "Nume câmp de recunoscut",
  "isRecognized": "Numele câmpurilor din tabelul de mai jos sunt recunoscute automat pentru acest câmp",
  "needsEditablePointLayers": "Harta web trebuie să conţină cel puţin un strat tematic de tip punct editabil.",
  "editpageAlias": "Pseudonim",
  "configureFields": "Configuraţi câmpuri strat tematic",
  "configureSingleFields": "Configuraţi câmp cu adresă unică",
  "configureMultiFields": "Configuraţi câmpuri cu adrese multiple",
  "configureXYFields": "Configuraţi câmpuri X/Y",
  "noFields": "Utilizați acțiunea de editare pentru a defini unul sau mai multe câmpuri de afișat",
  "display": "Afişare",
  "duplicate": "Căutare duplicat",
  "duplicateTip": "Căutați în acest câmp valorile identice între fișierul sursă și stratul tematic țintă./n Atunci când este găsită o potrivire identică, înregistrarea din fișier nu va fi localizată și va fi marcată ca duplicat.",
  "noSelectField": "Selectați mai întâi opțiunea Strat tematic de obiecte spațiale",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (longitudine)",
  "xyFieldsLabelY": "Y (latitudine)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Spre est",
  "northing": "Spre nord",
  "lon": "LON.",
  "lat": "LAT.",
  "layerOptionHint": "Alegeți stratul tematic către care doriți să se transmită datele.",
  "layerFieldTitle": "Stratul tematic țintă",
  "tempSymbolHint": "Alegeți simbolul care va fi utilizat pentru afișarea obiectelor spațiale.",
  "tempSymbolTitle": "Simbolul afișat",
  "maxRecords": "Max. înregistrări",
  "maxRecordsHint": "Numărul maxim de înregistrări de localizat",
  "searchRadius": "Rază de căutare",
  "searchRadiusHint": "Distanţa faţă de stratul tematic până la care se caută obiecte spaţiale duplicate",
  "requiresInteger": "Introduceți o valoare numerică.",
  "requiresInteger0100": "Introduceți o valoare numerică între 0 și 100",
  "requiresLocator": "Adăugați cel puțin un localizator valabil.",
  "layerFields": "Setări strat tematic",
  "layerFieldsHint": "Specificați câmpurile din stratul tematic țintă care vor fi cartografiate la câmpurile țintă.",
  "locatorError": "Localizatorul este nevalid sau inaccesibil.",
  "optionNotMatch": "Opțiunile de câmp nu sunt consistente în toate localizatoarele. Este posibil ca reluarea în caz de nereușită să nu funcționeze în modul așteptat.",
  "targetLayerTabTitle": "Stratul tematic țintă",
  "locationSettingsTabTitle": "Setări locaţie",
  "generalSettingsTabTitle": "Setări generale",
  "addTargetLayersLabel": "Adăugare strat tematic țintă",
  "introductoryText": "Creare conținut de instruire pentru widget",
  "defaultStartPageInstructions": "Acest widget vă va ajuta la prelucrarea și transmiterea datelor dintr-un fișier către stratul tematic selectat din hartă.<br/> <br/> Valorile din fișier trebuie să fie delimitate de virgulă, tabulator, punct și virgulă sau bară verticală.",
  "noTargetLayerConfiguredErrorMsg": "Nu este configurat niciun strat tematic țintă",
  "noFieldsForTargetLayer": "Setările de strat tematic nu sunt definite pentru stratul tematic țintă",
  "locationSettingsNotConfigured": "Setările de localizare nu sunt configurate în mod adecvat"
});