define({
  "_widgetLabel": "Lausaline atribuutide redaktor",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Kihi nimi",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Muudetavaid kihte pole konfigureeritud",
  "editorPopupTitle": "Lausaline atribuutide redaktor",
  "editorPopupSaveBtn": "Salvesta",
  "editorPopupMultipleValues": "",
  "clear": "Eemalda",
  "featuresUpdated": "${0} / ${1} objekt(i) värskendatud",
  "featuresSelected": "${0} objekt(i) valitud",
  "featuresSkipped": "Eiratakse",
  "featuresNoPermision": "${0} funktsioon(i) on valitud, kuid muutmisõigus puudub.",
  "search": "Otsi",
  "queryInput": "Sisestage päringu jaoks väärtus",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Määrake filter õigesti.",
  "filterPopup": "Filtreeri kiht",
  "filterAppend": "Kui filter on selle kihi veebikaardil juba olemas",
  "filterAppendOR": "Lisa mis tahes avaldis olemasolevasse kaardifiltrisse",
  "filterAppendAND": "Lisa kõik avaldised olemasolevasse kaardifiltrisse",
  "cancel": "Tühista",
  "noValue": "Väärtus puudub",
  "emptyString": "Tühi string",
  "existingValue": "Säilita olemasolev väärtus",
  "newDate": "Uus kuupäev",
  "valueChooser": "Valige või sisestage väärtus",
  "ok": "OK",
  "drawBox": {
    "point": "Punkt",
    "line": "Joon",
    "polyline": "Joon",
    "freehandPolyline": "Vabakäe joon",
    "extent": "Kuvaulatus",
    "polygon": "Polügoon",
    "freehandPolygon": "Vabakäe polügoon",
    "clear": "Eemalda",
    "addPointToolTip": "Klõpsake selles alas valimiseks",
    "addShapeToolTip": "Joonistage kujund objektide valimiseks",
    "freehandToolTip": "Hoidke all, et joonistada kujund objektide valimiseks",
    "startToolTip": "Joonistage kujund objektide valimiseks"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Üksuse ${0} objekt tagastas kehtetu ID",
    "noSelectedLayers": "Värskendatavate kirjetega kihte pole valitud",
    "inputValueError": "Kehtetu väärtus vormis",
    "saveError": "Ei saa ${0} objekte salvestada",
    "requiredValue": "Nõutav väärtus"
  }
});