define({
  "_widgetLabel": "Програма за моделиране на съответствие",
  "general": {
    "clear": "Изчистване",
    "cancel": "Отказ",
    "save": "Стартиране",
    "saveAs": "Експорт"
  },
  "saveModel": {
    "save": "Експорт",
    "title": "Заглавие: ",
    "summary": "Обобщение: ",
    "description": "Описание: ",
    "tags": "Отбелязвания: ",
    "folder": "Папка: ",
    "homeFolderPattern": "{username} (Начална страница)",
    "failed": "Неуспешен експорт."
  },
  "util": {
    "colorRamp": {
      "1": "Изключително ниско",
      "2": "Много ниско",
      "3": "Ниско",
      "4": "Ниско до средно",
      "5": "Средни",
      "6": "Високо до средно",
      "7": "Високо",
      "8": "Много високо",
      "9": "Изключително високо",
      "low": "Ниско",
      "high": "Високо",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Транспониране"
    }
  },
  "wro": {
    "caption": "Програма за моделиране на съответствие",
    "browsePrompt": "Услуга за претеглено наслагване",
    "selectLayersCaption": "Избиране на слоеве",
    "selectLayers": "Слоеве",
    "designModelCaption": "Проектиране на модел",
    "designModel": "Проектиране на модел",
    "transparency": "Прозрачност",
    "visible": "Видимост",
    "total": "Общо",
    "unableToLoad": "Моделът не може да се зареди.",
    "projectNotOpen": "Проектът не е отворен.",
    "readMore": "Прочетете повече",
    "validation": {
      "validating": "Проверка ...",
      "invalidItemCaption": "Предупреждение за Услуга за претеглено наслагване",
      "notAnImageService": "Този елемент не е Услуга за изображение.",
      "notAWroService": "Този елемент не е Услуга за претеглено наслагване",
      "undefinedUrl": "URL адресът на този елемент не е дефиниран.",
      "inaccessible": "Услугата е недостъпна.",
      "generalError": "Елементът не може да се отвори.",
      "missingFieldPattern": "{field} е задължително поле",
      "notAllowRasterFunction": "allowRasterFunction трябва да бъде зададена на true",
      "notNearestResampling": "defaultResamplingMethod трябва да е най-близък",
      "notIsWeightedOverlayProp": "Ключовото свойство IsWeightedOverlay трябва да бъде зададено на true",
      "invalidLink": "Невалиден URL адрес. Неуспешно отваряне на сайта за избрания слой.",
      "unexpectedError": "Възникна неочаквано състояние.",
      "rangeMessage": "Стойността трябва да е между ${0} и ${1}",
      "rangeMessage100": "Стойността трябва да е между 0 и 100",
      "maxLayers": "Максималният брой ${0} слоеве, разрешен от услугата, първо трябва да премахнете слой, преди да добавите нов.",
      "notFound": "Не е намерен слой ${0} в услугата за претеглено наслагване",
      "wroServiceNotDefined": "Няма определена услуга за претеглено наслагване за модел.",
      "overlayLayerOutputInvalid": "Изходната стойност на [${0}] диапазоните за пренастройване на слоя на наслагване на картата [${1}] липсва или е невалидна",
      "overlayLayerInputInvalid": "Входната минимална/максимална стойност на [${0}] диапазоните за пренастройване на слоя на наслагване на картата[${1}] липсва или е невалидна",
      "overlayLayerRangesMissing": "Липсват диапазони за пренастройване на слоя на наслагване [${0}] на картата",
      "overlayLayerWeight": "Натискът на писалката на наслагващия слой трябва да бъде до 100",
      "overlayLayerRequired": "Изисква се поне един наслагващ слой",
      "overlayLayerNotDefined": "Слоевете на наслагване не са дефинирани",
      "requiresColormap": "Тази растерна функция изисква цветова карта, но моделът няма валидна дефиниция на цветова карта",
      "createModelError": "Грешка при създаване на модел",
      "invalidModel": "Моделът не е валиден",
      "imageServiceNotDefined": "Слоят на услугата за изображение не е дефиниран",
      "imageLayerNotDefined": "Слоят на услугата за изображение не е дефиниран",
      "histogramNotDefined": "Функцията на хистограмата за претеглено наслагване не е дефинирана."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Зелено Жълто Червено",
      "Red Yellow Green": "Червено Жълто Зелено",
      "Yellow to Dark Red": "Жълто до тъмно червено",
      "Dark Red to Yellow": "Тъмно червено до жълто",
      "Light Gray to Dark Gray": "Светло сиво до тъмно сиво",
      "Dark Gray to Light Gray": "Тъмно сиво до светло сиво",
      "Light Brown to Dark Brown": "Светло кафяво до тъмно кафяво",
      "Dark Brown to Light Brown": "Тъмно кафяво до светло кафяво",
      "Full Spectrum - Bright Red to Blue": "Пълен спектър - от ярко червено до синьо",
      "Full Spectrum - Bright Blue to Red": "Пълен спектър - от ярко синьо до червено",
      "Partial Spectrum - Yellow to Blue": "Частичен спектър - от жълто до синьо",
      "Partial Spectrum - Blue to Yellow": "Частичен спектър - от синьо до жълто",
      "Yellow-Green to Dark Blue": "Жълто-зелено до тъмно синьо",
      "Dark Blue to Yellow-Green": "Тъмно синьо до жълто-зелено",
      "Cold to Hot Diverging": "Студената до топлата гама се разминават",
      "Hot to Cold Diverging": "Топлата до студената гама се разминават",
      "Surface - Low to High": "Повърхност - от ниска към висока",
      "Surface - High to Low": "Повърхност - от висока към ниска"
    }
  },
  "tabs": {
    "layers": "Слоеве",
    "model": "Модел",
    "chart": "Диаграма"
  },
  "chart": {
    "prompt": "Обекти",
    "working": "Обновява се...",
    "polygonTool": "Начертайте полигон",
    "freehandPolygonTool": "Начертайте полигон на ръка",
    "selectTool": "Изберете от слой",
    "panTool": "Местене",
    "clearButton": "Изчистване",
    "noModelLayer": "Няма модел",
    "noSubjectLayers": "Вашата карта няма полигонни слоеве.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});