define({
  "transparencyLabel": "Átlátszóság",
  "outline": "Kontúr",
  "fill": "Kitöltés (a Szín beállítás csak az egyszínű stílus beállítása esetén érhető el)",
  "style": "Stílus",
  "mandatoryLabel": "Kötelező evakuálási távolság",
  "mandatoryButtonLabel": "Kötelező evakuálási távolság beállításainak konfigurálása",
  "safeLabel": "Biztonságos evakuálási távolság",
  "safeButtonLabel": "Biztonságos evakuálási távolság beállításainak konfigurálása",
  "selectOpLayerLabel": "Válasszon operatív réteget az eredmények számára",
  "selectDefaultMeasurementLabel": "Válasszon alapértelmezett mértékegységet",
  "helpIconTooltip": "Az operatív réteget a rendszer olyan rétegekkel tölti fel az aktuális webtérképből, amelyek poligon típusú geometriával rendelkeznek.",
  "lineStyles": {
    "esriSLSDash": "Szaggatott",
    "esriSLSDashDot": "Vonal-pont",
    "esriSLSDashDotDot": "Vonal-pont-pont",
    "esriSLSDot": "Pont",
    "esriSLSLongDash": "Hosszú vonal",
    "esriSLSLongDashDot": "Hosszú vonal-pont",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Rövid vonal",
    "esriSLSShortDashDot": "Rövid vonal-pont",
    "esriSLSShortDashDotDot": "Rövid vonal-pont-pont",
    "esriSLSShortDot": "Rövid pont",
    "esriSLSSolid": "Folytonos"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Hátra",
    "esriSFSCross": "Kereszt",
    "esriSFSDiagonalCross": "Átlós",
    "esriSFSForwardDiagonal": "Előre",
    "esriSFSHorizontal": "Vízszintes",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Folytonos",
    "esriSFSVertical": "Függőleges"
  },
  "threatTypeLabel": "Fenyegetés típusa",
  "symbologyLabel": "Szimbólumrendszer",
  "generalLabel": "Általános",
  "addThreatTypesLabel": "Fenyegetés típusának hozzáadása",
  "threatTypeColLabel": "Vegyi anyag okozta veszély típusa",
  "actions": "Műveletek",
  "newThreatTypePopupLabel": "Új fenyegetéstípus",
  "chooseDefaultThreatTypeIconLabel": "Választás alapértelmezettből",
  "mandatoryDistance": "Kötelező evakuálási távolság",
  "safeDistance": "Biztonságos evakuálási távolság",
  "units": "Mértékegységek",
  "chooseDefaultThreatLabel": "Válasszon alapértelmezett fenyegetéstípust",
  "defaultThreatTypePopUpLabel": "Alapértelmezett fenyegetéstípusok",
  "editThreatLabel": "Fenyegetés szerkesztése",
  "defaultThreatTypeIconTooltip": "Alapértelmezett fenyegetéstípusok listája",
  "uniqueThreatTypeMsg": "Egyedi fenyegetéstípust adjon meg: már létezik fenyegetéstípus ilyen névvel.",
  "requiredThreatTypeMsg": "A mező kitöltése kötelező",
  "unitMeasureLabel": "A távolságok {0} mértékegységben vannak megadva",
  "pipeBombLabel": "Csőbomba",
  "suicideBombLabel": "Öngyilkos merénylő",
  "briefcaseLabel": "Aktatáska",
  "carLabel": "Autó",
  "suvVanLabel": "SUV/FURGON",
  "smallDeliveryTruckLabel": "Kisteherautó",
  "containerWaterTruckLabel": "Konténerszállító/vízszállító teherautó",
  "semiTrailerLabel": "Félpótkocsis teherautó",
  "lpgSafeDistanceLable": "Biztonságos távolság",
  "fireBallDiameterLable": "Tűzgömb átmérője",
  "lpgthreatTypeColLabel": "LPG okozta veszély típusa",
  "threatTypeCatagoryLabel": "Fenyegetés típusának kategóriája",
  "chemicalThreatLegendLabel": "Vegyi anyag okozta veszély",
  "lpgThreatLegendLabel": "LPG okozta veszély",
  "fireballButtonLabel": "Tűzgömbátmérő beállításainak konfigurálása",
  "safeDistanceButtonLabel": "Biztonságos távolság beállításainak konfigurálása",
  "chemicalThreatCatagoryLabel": "Vegyi anyag",
  "lpgThreatCatagoryLabel": "LPG",
  "smallLPGTank": "Kis LPG-tartály",
  "largeLPGTank": "Nagy LPG-tartály",
  "commercialResidentialLPGTank": "Kereskedelmi célú/lakossági LPG-tartály",
  "smallLPGTruck": "Kis LPG-szállító teherautó",
  "semiTankerLPG": "LPG-szállító tartályos félpótkocsi"
});