define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Krijg toegang tot infographics en rapporten die belangrijke indicators en data voor een gebied samenvatten.</div><br><div>Selecteer een punt of polygoon op de kaart, zoek naar een adres of plaats, of plaats een pin op de kaart om meer informatie over gebieden te bekijken.</div>",
  "defineWhichInfographics": "Definieer welke infographics er beschikbaar zijn in de widget:",
  "defineWhichReports": "Definieer welke rapporten er beschikbaar zijn in de widget:",
  "defaultValues": "Standaardwaarden:",
  "disable": "Uitschakelen",
  "drawFreehandPolygon": "Teken een polygoon in vrije stijl",
  "drawPolygon": "Teken een polygoon",
  "driveTime": "Reistijd",
  "dropPin": "Zet speld neer",
  "dynamicHTML": "Dynamische HTML",
  "exportOptions": "Exportopties:",
  "home": "Start",
  "image": "Afbeelding",
  "infographics": "Infographics",
  "invalidValueRing": "De waarde moet tussen 0 en 1000 liggen.",
  "invalidValueDTWT": "De waarde moet tussen 0 en 300 liggen.",
  "km": "km",
  "makeDefault": "Standaard maken",
  "miles": "mijl",
  "minutes": "minuten",
  "options": "Opties:",
  "pdf": "PDF",
  "print": "Afdrukken",
  "radius": "Straal",
  "removeDefault": "Standaard verwijderen",
  "reports": "Reports",
  "rings": "Ringen",
  "searchTextBox": "Tekstvak zoeken",
  "selectCountryOrRegion": "Selecteer land of regio:",
  "thisEntryIsNotValid": "De ingevoerde waarde is ongeldig.",
  "time": "Tijd",
  "walkTime": "Wandeltijd"
});