define({
  "taskUrl": "URL adresa servisa vidnog polja",
  "portalURL": "Navedite URL adresu za vašu ArcGIS Online organizaciju ili Portal for ArcGIS",
  "portalURLError": "Konfigurisana URL adresa za vašu ArcGIS Online organizaciju ili Portal for ArcGIS nije validna.",
  "privilegeError": "Vaša korisnička uloga ne može da vrši analizu. Da bi analiza bila izvršena, administrator organizacije mora da vam omogući određene <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privileges</a>.",
  "noServiceError": "Servis analize elevacije nije dostupan. Proverite konfiguracije za ArcGIS Online organizaciju ili Portal for ArcGIS.",
  "serviceURLPlaceholder": "Unesite URL adresu zadatka geoprocesiranja vidnog polja",
  "setTask": "Postavi",
  "setTaskTitle": "Podesi zadatak geoprocesiranja vidnog polja",
  "serviceURLError": "Zadatak geoobrade koji pokušavate da konfigurišete pomoću ovog vidžeta nije važeći. Izaberite važeću URL adresu Viewshed zadatka geoobrade",
  "defaultMilsForAnglesLabel": "Podrazumevano postavi mil za uglove",
  "defaultObserverHeightLabel": "Podrazumevana jedinica za visinu posmatrača",
  "defaultObservableDistanceLabel": "Podrazumevana jedinica za rastojanje koje je moguće posmatrati",
  "units": {
    "miles": "Milje",
    "kilometers": "Kilometri",
    "feet": "Stope",
    "meters": "Metri",
    "yards": "Jardi",
    "nauticalMiles": "Nautičke milje"
  },
  "helpIconTooltip": "Lista operativnih slojeva se popunjava slojevima iz trenutne veb mape koji su tipa poligonalne geometrije.",
  "selectOperationalLayerLabel": "Izaberite operativni sloj za rezultate",
  "lineOfSightTabTitle": "Linija vida",
  "symbologyTabTitle": "Simbologija",
  "transparency": "Prozirnost",
  "outline": "Kontura",
  "fill": "Popuna (boja se primenjuje samo kada je stil podešen da bude neproziran)",
  "style": "Stil",
  "selectOpLayerLabel": "Izaberite operativni sloj za rezultate",
  "selectDefaultMeasurementLabel": "Izaberite podrazumevanu jedinicu mere",
  "visibleSectionLabel": "Vidljivi odeljak",
  "nonVisibleSectionLabel": "Nevidljivi odeljak",
  "visibleSectionButtonLabel": "Postavka vidljivog odeljka Postavke",
  "nonVisibleSectionButtonLabel": "Postavka nevidljivog odeljka Postavke",
  "colorPicker": "Birač boja",
  "lineStyles": {
    "esriSLSDash": "Crta",
    "esriSLSDashDot": "Crta tačka",
    "esriSLSDashDotDot": "Crta tačka tačka",
    "esriSLSDot": "Tačka",
    "esriSLSLongDash": "Duga crta",
    "esriSLSLongDashDot": "Duga crta tačka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kratka crta",
    "esriSLSShortDashDot": "Kratka crta tačka",
    "esriSLSShortDashDotDot": "Kratka crta tačka tačka",
    "esriSLSShortDot": "Kratka tačka",
    "esriSLSSolid": "Neprozirno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unazad",
    "esriSFSCross": "Krst",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Unapred",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Neprozirno",
    "esriSFSVertical": "Vertikalno"
  }
});