define({
  "_widgetLabel": "Nutikas redaktor",
  "_featureAction_SmartEditor": "Nutikas redaktor",
  "noEditPrivileges": "Teie kontol puudub andmete loomise või muutmise õigus.",
  "loginPopupTitle": "Logi sisse",
  "loginPopupMessage": "${widgetName} nõuab aadressiteabe otsimiseks ja salvestamiseks õigusi ja krediite. Kas soovite sisse logida ja seda võimalust kasutada?",
  "noCreditsOrPrivilegeWarningMessage": "Teie kontol pole lubasid ja krediite, et otsida ja salvestada aadressiteavet vidinaga ${widgetName}. Õiguste ja krediitide taotlemiseks võtke ühendust oma organisatsiooni administraatoriga.",
  "unableToUseLocator": "Lokaator pole juurdepääsetav. Aadressi atribuudi toimingut (toiminguid) ei teostata.",
  "locatorDisabledWaning": "Lokaator pole aktiveeritud. Selle funktsiooni taotlemiseks pöörduge oma organisatsiooni administraatori poole.",
  "noFeatureInAIWarning": "Objekti (objekte) pole valitud. Muudatuste tegemiseks valige objekt või peakuvale naasmiseks klõpsake Tühista.",
  "noEditableLayerWarning": "Teie kontol pole õigust andmeid luua või muuta või see veebikaart ei sisalda muudetavaid kihte.",
  "noVisibleCreateLayerWarning": "Kiht (kihid) pole praegusel suumitasemel nähtav(ad). Objektide loomiseks/muutmiseks suurendage või vähendage kuva.",
  "noVisibleUpdateLayerWarning": "Kiht (kihid) pole praegusel suumitasemel nähtav(ad). Objektide muutmiseks suurendage või vähendage kuva.",
  "checkLayerVisibilityInWebMapWarning": "Objektide loomiseks või muutmiseks veenduge, et kihid on kaardil nähtavad.",
  "showSelectionInAITitle": "Valitud objektid",
  "showSelectionInAIMsg": "Kas soovite praeguse valiku vidinas ${widgetName}laadida?",
  "widgetActive": "Aktiivne",
  "widgetNotActive": "Pole aktiivne",
  "pressStr": "Snäppimise võimaldamiseks ",
  "ctrlStr": " vajutage ",
  "snapStr": " CTRL",
  "noAvailableTempaltes": "Ühtki malli pole saadaval",
  "editorCache": " - redaktori vahemälu",
  "presetFieldAlias": "Väli",
  "presetValue": "Eelseatud väärtus",
  "usePresetValues": " Kasuta eelseatud väärtusi (ainult uute objektide korral)",
  "editGeometry": " Muuda geomeetriat",
  "savePromptTitle": "Salvesta objekt",
  "savePrompt": "Kas soovite salvestada praeguse objekti?",
  "deletePromptTitle": "Kustuta objekt",
  "deleteAttachment": "Kustuta manus",
  "deletePrompt": "Kas soovite kindlasti kustutada valitud objekti?",
  "attachmentLoadingError": "Tõrge manuste üleslaadimisel",
  "attachmentSaveDeleteWarning": "Hoiatus: manuste muudatused salvestatakse automaatselt",
  "autoSaveEdits": "Salvesta uued objektid automaatselt",
  "addNewFeature": "Loo uus objekt",
  "featureCreationFailedMsg": "Uut kirjet/objekti ei saa luua",
  "relatedItemTitle": "Seotud tabel/kiht",
  "relatedFeatureCount": "${layerTitle} koos ${featureCount} objektiga",
  "createNewFeatureLabel": "Loo kihi ${layerTitle} jaoks uus objekt",
  "invalidRelationShipMsg": "Veenduge, et primaarvõtme väljal „${parentKeyField}“ oleks sobiv väärtus.",
  "pendingFeatureSaveMsg": "Enne seotud objekti loomist salvestage objekti osas tehtud muudatused.",
  "attachmentsRequiredMsg": "(*) Manused on nõutavad.",
  "coordinatePopupTitle": "Teisalda objekt XY-asukohta",
  "coordinatesSelectTitle": "Koordinaatsüsteem:",
  "mapSpecialReferenceDropdownOption": "Kaardi koordinaatsüsteem",
  "latLongDropdownOption": "Laius/Pikkus",
  "mgrsDropdownOption": "Sõjaväevõrgustiku viitesüsteem (MGRS)",
  "mgrsTextBoxLabel": "Koordinaat:",
  "xAttributeTextBoxLabel": "X-koordinaat:",
  "yAttributeTextBoxLabel": "Y-koordinaat:",
  "latitudeTextBoxLabel": "Laiuskraad:",
  "longitudeTextBoxLabel": "Pikkuskraad:",
  "presetGroupFieldsLabel": "${groupName} rakendatakse järgmistele kihiväljadele:",
  "presetGroupNoFieldsLabel": "Grupil ${groupName} pole seostatud välju",
  "groupInfoLabel": "Grupi ${groupName} teave",
  "editGroupInfoIcon": "Muuda grupi ${groupName} väärtust",
  "filterEditor": {
    "all": "Kõik",
    "noAvailableTempaltes": "Ühtki malli pole saadaval",
    "searchTemplates": "Otsingumallid",
    "filterLayerLabel": "Filtreeri kihid"
  },
  "invalidConfiguration": "Vidin on konfigureerimata või pole konfiguratsioonis sisalduvad kihid enam kaardil. Avage rakendus koostajarežiimis ja konfigureerige vidin uuesti.",
  "geometryServiceURLNotFoundMSG": "Geomeetriateenuse URL-i ei saa tuua",
  "clearSelection": "Sule",
  "refreshAttributes": "Uuenda dünaamilise objekti atribuute",
  "automaticAttributeUpdatesOn": "Uuenda objekti atribuudid automaatselt: SEES",
  "automaticAttributeUpdatesOff": "Uuenda objekti atribuudid automaatselt: VÄLJAS",
  "moveSelectedFeatureToGPS": "Teisalda valitud objekt praegusesse GPS-i asukohta",
  "moveSelectedFeatureToXY": "Teisalda valitud objekt XY-asukohta",
  "mapNavigationLocked": "Kaardil navigeerimine: lukustatud",
  "mapNavigationUnLocked": "Kaardil navigeerimine: lukustamata",
  "copyFeatures": {
    "title": "Kopeeri objektid",
    "createFeatures": "Loo objektid",
    "createSingleFeature": "Loo üks mitmeosalise geomeetriaga objekt",
    "createOneSingleFeature": "Loo objekt",
    "noFeaturesSelectedMessage": "Objekte pole valitud",
    "selectFeatureToCopyMessage": "Valige kopeeritavad objektid",
    "multipleFeatureSaveWarning": "Märkus: Mitme objekti loomisel kopeerimisfunktsiooni abil salvestatakse uued objektid kohe",
    "copyFeatureUpdateGeometryError": "Valitud objektide geomeetriat ei saa uuendada",
    "canNotSaveMultipleFeatureWarning": "Märkus. Kordumatutele väärtuseväljadele ei saa sama väärtuse abil kopeerida mitut objekti. Valige ainult üks objekt",
    "createOnlyOneMultipartFeatureWarning": "Märkus. Luua saab ainult ühe mitmeosalise objekti"
  },
  "addingFeatureError": "Viga valitud objektide kihile lisamisel. Palun proovige uuesti",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' objekti kopeerimine nurjus. Kas soovite puuduva(te) objekti(de) puhul proovida uuesti?",
  "selectingFeatureError": "Viga objektide valimisel kihis. Palun proovige uuesti",
  "customSelectOptionLabel": "Valige kopeeritavad objektid",
  "noFeatureSelectedMessage": "Objekte pole valitud",
  "multipleFeatureSaveMessage": "Kõik objektid salvestatakse kohe. Kas soovite jätkata?",
  "relativeDates": {
    "dateTypeLabel": "Kuupäeva tüüp",
    "valueLabel": "Väärtus",
    "fixed": "Parandatud",
    "current": "Praegune",
    "past": "Möödas",
    "future": "Tulevane",
    "popupTitle": "Vali väärtus",
    "hintForFixedDateType": "Vihje: Eelseadistatud vaikeväärtusena kasutatakse määratud kuupäeva ja kellaaega.",
    "hintForCurrentDateType": "Vihje: Eelseadistatud vaikeväärtusena kasutatakse praegust kuupäeva ja kellaaega.",
    "hintForPastDateType": "Vihje: määratud väärtus lahutatakse valmisvaikeväärtuse saamiseks praegusest kuupäevast ja kellaajast",
    "hintForFutureDateType": "Vihje: määratud väärtus liidetakse valmisvaikeväärtuse saamiseks praegusele kuupäevale ja kellaajale",
    "noDateDefinedTooltip": "Kuupäeva pole määratletud",
    "relativeDateWarning": "Eelseadistatud vaikeväärtuse salvestamiseks tuleb määrata kuupäeva või kellaaja väärtus.",
    "customLabel": "Kohandatud",
    "layerLabel": "Kiht",
    "domainFieldHintLabel": "Valitud väärtus on kodeeritud väärtuse domeen. Kasutatakse väärtust: \"${domainValue}\""
  },
  "valuePicker": {
    "popupTitle": "Vali väärtus",
    "popupHint": "Praegune objekt lõikub mitme objektiga, valige vastava välja väärtus",
    "buttonTooltip": "Valige väärtus mitme lõikuva objekti hulgast"
  },
  "uniqueValueErrorMessage": "Vastav \"${fieldName}\" on väärtus juba olemas; palun sisestage uus väärtus.",
  "requiredFields": {
    "displayMsg": "Nõutavad väljad ei tohi olla tühjad. Lisage allolevatele ühistele väljadele väärtused.",
    "popupTittle": "Nõutavad väljad",
    "foundNullRecordCount": "${fieldName} (Leitud ${count} kirjel)"
  },
  "cantLocateUserLocation": "Teie asukohta ei saanud määrata",
  "tryAgainButtonLabel": "Proovi uuesti",
  "copyFeatureFailedPopupTitle": "Oih!"
});