define({
  "_widgetLabel": "威脅分析",
  "threatAnalysisMainPageTitle": "根據 JCAT 反恐指南",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "輸入位置",
  "interactive": "互動",
  "fromCoord": "固定座標",
  "existingFeature": "來自現有的圖徵",
  "threatAnalysisCoordInputLabel": "威脅位置",
  "enterCoords": "輸入坐標",
  "threatAddPointToolTip": "新增威脅位置",
  "threatDrawPointToolTip": "按一下以新增威脅位置",
  "threatType": "威脅類型",
  "threatPlaceholder": "開始輸入以搜尋威脅",
  "zoneTypeLabel": "區域類型",
  "feetLabel": "英呎",
  "metersLabel": "公尺",
  "unitsLabel": "單位",
  "threatGraphicLayer": "威脅圖形",
  "style": "樣式",
  "settingsTitle": "設定",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "虛線",
    "esriSLSDashDot": "虛線點",
    "esriSLSDashDotDot": "虛線點點",
    "esriSLSDot": "點",
    "esriSLSLongDash": "長虛線",
    "esriSLSLongDashDot": "長虛線點",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "短虛線",
    "esriSLSShortDashDot": "短虛線點",
    "esriSLSShortDashDotDot": "短雙虛線點",
    "esriSLSShortDot": "短點",
    "esriSLSSolid": "實心"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向後",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "對角線",
    "esriSFSForwardDiagonal": "轉寄",
    "esriSFSHorizontal": "水平對齊",
    "esriSFSNull": "Null",
    "esriSFSSolid": "實心",
    "esriSFSVertical": "垂直"
  },
  "resultsTitle": "結果",
  "publishTABtn": "發佈",
  "layerName": "發佈的圖層名稱",
  "invalidLayerName": "圖層名稱只能包含英數字元和底線",
  "missingLayerNameMessage": "您必須先輸入有效的圖層名稱，之後才能發佈",
  "publishingFailedLayerExists": "發佈失敗: 您已擁有名為 {0} 的圖徵服務。 請選擇其他圖層名稱。",
  "checkService": "檢查服務: {0}",
  "createService": "建立服務: {0}",
  "unableToCreate": "無法建立: {0}",
  "addToDefinition": "新增至定義: {0}",
  "successfullyPublished": "已成功發佈 Web 圖層",
  "successfullyAppended": "已將新圖徵成功附加到 Web 圖層",
  "manageWebLayerText": "管理 Web 圖層",
  "userRole": "無法建立服務，因為使用者沒有權限",
  "retrieveExistingLayerError": "無法擷取 {0}。 請使用其他圖層名稱予以發佈",
  "publishToNewLayer": "將結果發佈到新圖徵圖層",
  "layerNameExists": "圖層名稱已存在。 請使用不同的圖層名稱。",
  "pipeBombLabel": "土製鐵管炸彈",
  "suicideBombLabel": "自殺炸彈",
  "briefcaseLabel": "公事包",
  "carLabel": "汽車",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "小型送貨卡車",
  "containerWaterTruckLabel": "容器/水車",
  "semiTrailerLabel": "半掛車",
  "transparencyLabel": "透明度",
  "outline": "輪廓",
  "fill": "填充 (將樣式設為實心時所套用的顏色)",
  "createBtn": "建立區域",
  "clearBtn": "清除",
  "invalidNumberMessage": "輸入的值無效",
  "invalidRangeMessage": "值必須大於 0",
  "parseCoordinatesError": "無法剖析座標。 請檢查您的輸入。",
  "selectDrawModeLabel": "選擇繪製模式",
  "selectFeatureLabel": "從此圖層中選擇圖徵",
  "smallLPGTank": "小型 LPG 罐",
  "largeLPGTank": "大型 LPG 罐",
  "commercialResidentialLPGTank": "化學/殘餘 LPG 罐",
  "smallLPGTruck": "小型 LPG 卡車",
  "semiTankerLPG": "半罐式 LPG",
  "zoneDescriptionColLabel": "區域描述",
  "distanceColLabel": "距離",
  "zoneDescColLabel": "區域描述",
  "descriptionLabel": "描述",
  "editThreatZonePopupLabel": "編輯威脅區域符號系統",
  "symbologyColLabel": "符號系統",
  "actions": "操作",
  "threatTypeSelectLabel": "選取威脅類型:",
  "distanceLabel": "距離 (${unitAbbr})",
  "layerCountHint": "提示: 將發佈具有 ${layerCount} 個圖徵圖層的 Web 圖層。",
  "selectLabel": "選擇",
  "mandatoryLabel": "強制疏散距離",
  "safeLabel": "安全疏散距離",
  "fireBallDiameterLable": "火球直徑",
  "lpgSafeDistanceLable": "安全距離"
});