define({
  "feedbackStyleLabel": "Stil för återkoppling på avstånd och riktning",
  "showTabLabel": "Visa alla flikar",
  "tabErrorMessage": "Välj minst en flik i gruppen \"Stil för återkoppling på avstånd och riktning\"",
  "lineLabel": "Linje",
  "circleLabel": "Cirkel",
  "ellipseLabel": "Ellips",
  "ringsLabel": "Ringar",
  "transparency": "Transparens",
  "operationalLineLayerSelectLabel": "Välj ett operationellt polylinjelager för resultat med linjer och ringar",
  "operationalPolygonLayerSelectLabel": "Välj ett operationellt polylinjelager för resultat med cirklar och ellipser",
  "helpIconPolylineTooltip": "Listan med funktionslager innehåller lager från den aktuella webbkartan som är av typen polylinjegeometri.",
  "helpIconPolygonTooltip": "Listan med funktionslager innehåller lager från den aktuella webbkartan som är av typen polygongeometri.",
  "feedbackResultsLayerLabel": "Lager för avstånds- och riktningsåterkopplingsresultat",
  "editSymbologyHint": "Tips: Klicka på förhandsgranskningsikonen för att redigera symbologin",
  "feedbackTextColorLabel": "Textfärg för återkopplingsetikett",
  "feedbackTextSizeLabel": "Textstorlek för återkopplingsetikett",
  "previewLabel": "Förhandsgranska",
  "lineSymbologyPopupTittle": "Linjesymbologi",
  "circleSymbologyPopupTittle": "Cirkelsymbologi",
  "ellipseSymbologyPopupTittle": "Ellipssymbologi",
  "ringSymbologyPopupTittle": "Ringsymbologi"
});