define({
  "taskUrl": "URL Tugas",
  "setTask": "Atur",
  "setTaskPopupTitle": "Atur Tugas",
  "validate": "Atur",
  "inValidGPService": "Harap masukkan layanan geoprocessing yang valid.",
  "noOutputParameterWithGeometryType": "Layanan geoprocessing yang telah dipilih harus memiliki setidaknya satu parameter output dengan jenis geometri yang telah ditentukan. Harap pilih layanan geoprocessing yang berbeda.",
  "invalidOutputGeometry": "Jenis geometri output layanan geoprocessing yang dipilih tidak kompatibel dengan pengaturan proyek. Hasil layanan geoprocessing tidak bisa disimpan.",
  "GPFeatureRecordSetLayerERR": "Harap masukkan layanan geoprocessing dengan input hanya jenis 'GPFeatureRecordSetLayer'.",
  "invalidInputParameters": "Jumlah parameter input adalah kurang dari 1 atau lebih dari 3. Harap masukkan layanan geoprocessing yang valid.",
  "projectSetting": {
    "title": "Pengaturan Proyek",
    "note": "Catatan: Pengaturan Proyek bersifat opsional, setelah pengguna yang dikonfigurasi dapat menyimpan proyek di layer webmap yang diinginkan dengan area pemadaman jaringan dan parameter input. Pengguna dapat menyimpan parameter output lain dari tab 'Output'.",
    "projectPolygonLayer": "Layer poligon proyek",
    "outputParameterName": "Nama parameter output",
    "projectPointLayer": "Layer titik proyek",
    "selectLabel": "Pilih",
    "polygonLayerHelp": "<p>Layer poligon dengan syarat berikut akan ditampilkan:<br/><ul><li>Layer harus memiliki kemampuan pengeditan, yaitu 'Buat', 'Hapus', dan 'Perbarui'</li><li>Layer harus memiliki 2 kolom dengan nama dan tipe data yang tepat:</li><ul><li>nama (Kolom tipe string</li><li>globalid (Kolom tipe GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Layer poligon output dari URL tugas akan ditampilkan<p/>",
    "pointLayerHelp": "<p>Layer titik dengan kondisi berikut akan ditampilkan: <br/><ul><li>Layer harus memiliki kemampuan pengeditan seperti 'Buat', 'Hapus', dan 'Perbarui'</li><li>Layer harus memiliki setidaknya 2 kolom dengan nama dan tipe data yang pasti:</li><ul><li>inputtype (Kolom tipe string)</li><li>projectid (Kolom tipe GUID)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Bendera",
    "barrier": "Pembatas",
    "skip": "Lewati",
    "title": "Input",
    "inputTooltip": "Tooltip",
    "typeText": "Jenis",
    "symbol": "Simbol",
    "summaryEditorText": "Teks Ringkasan",
    "summaryTextTitle": "Sediakan teks yang akan ditampilkan untuk tab input"
  },
  "summaryTab": {
    "title": "Output",
    "summaryFieldsetText": "Pengaturan ringkasan",
    "inputOutput": "Input/Output",
    "field": "Kolom",
    "operator": "Operator",
    "inputOperatorCountOption": "Jumlah",
    "outputOperatorCountOption": "Jumlah",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Jumlah",
    "fieldOperatorMinOption": "Min",
    "fieldOperatorMaxOption": "Maks",
    "fieldOperatorMeanOption": "Rata-rata",
    "expressionAddButtonText": "Tambahkan",
    "expressionVerifyButtonText": "Verifikasi",
    "summaryEditorText": "Teks Ringkasan",
    "zoomText": "Zoom otomatis setelah pelacakan",
    "summarSettingTooltipText": "Tambahkan jumlah input/output",
    "symbol": "Simbol",
    "outputParametersText": "Parameter Output",
    "skipText": "Dapat Dilewati",
    "visibilityText": "Terlihat",
    "exportToCsvText": "Ekspor ke CSV",
    "settitngstext": "Pengaturan",
    "saveToLayerText": "Simpan ke Layer (Opsional)",
    "inputLabel": "Label",
    "inputTooltip": "Tooltip",
    "outputDisplay": "Tampilkan teks",
    "addFieldTitle": "Tambah Kolom",
    "setScale": "Atur Skala",
    "enterDisplayText": "Masukkan teks tampilan",
    "saveToLayerHelp": "<p>Layer dengan kondisi berikut ini akan ditampilkan:<br/><ul><li>Layer harus memiliki kemampuan pengedit yaitu Buat, Hapus, dan 'Perbarui'</li><li>Layer harus memiliki dua kolom dengan nama dan tipe data:</li><ul><li>parametername (Kolom tipe string)</li><li>projectid (Kolom tipe Guid)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Sediakan teks ringkasan yang akan ditampilkan di tab output",
    "addSummaryItemsTitle": "Tambahkan Item Ringkasan"
  },
  "validationErrorMessage": {
    "webMapError": "Tidak ada layer yang tersedia dalam webmap. Harap pilih webmap yang valid.",
    "inputTypeFlagGreaterThanError": "Input bendera jenis tidak boleh lebih dari satu.",
    "inputTypeFlagLessThanError": "Setidaknya satu input bendera jenis diperlukan.",
    "inputTypeBarrierErr": "Input penghalang jenis tidak boleh lebih dari satu.",
    "inputTypeSkipErr": "Input lewati jenis tidak boleh lebih dari satu.",
    "displayTextForButtonError": "Tampilkan teks untuk tombol 'Jalankan' tidak boleh kosong.",
    "UnableToLoadGeoprocessError": "Tidak dapat memuat layanan geoprocessing.",
    "invalidSummaryExpression": "Ekspresi tidak valid.",
    "validSummaryExpression": "Sukses !",
    "invalidProjectSettings": "Pengaturan Proyek Tidak Valid.<br/> Harap pilih nilai dalam '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Petunjuk: Berikan label tampilan untuk panel hasil dalam parameter output.",
    "displayTextHint": "Petunjuk: Ini akan ditampilkan dalam panel detail untuk parameter output ini.",
    "inputTextHint": "Petunjuk: Kembangkan ekspresi Anda di bawah dengan menggunakan tombol tambahkan item ringkasan.",
    "expressionHint": "Petunjuk: Pilih item dan klik tambahkan untuk mengembangkan ekspresi."
  }
});