define({
  "taskUrl": "Διεύθυνση URL υπηρεσίας ανάλυσης ορατότητας",
  "portalURL": "Καθορίστε τη URL διεύθυνση του ArcGIS Online οργανισμού ή του Portal for ArcGIS που διαθέτετε",
  "portalURLError": "Η παραμετροποιημένη διεύθυνση URL για τον οργανισμό σας στο ArcGIS Online ή για το Portal for ArcGIS δεν είναι έγκυρη.",
  "privilegeError": "Ο ρόλος χρήστη σας δεν μπορεί να εκτελέσει ανάλυση. Για να μπορέσετε να εκτελέσετε ανάλυση, ο διαχειριστής του οργανισμού σας χρειάζεται να σας χορηγήσει ορισμένα <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">δικαιώματα</a>.",
  "noServiceError": "Η υπηρεσία ανάλυσης υψομέτρου δεν είναι διαθέσιμη. Ελέγξτε τις παραμετροποιήσεις σας για τον οργανισμό σας στο ArcGIS Online ή για το Portal for ArcGIS.",
  "serviceURLPlaceholder": "Καταχωρίστε τη διεύθυνση URL της εργασίας γεωεπεξεργασίας ανάλυσης ορατότητας.",
  "setTask": "Ορισμός",
  "setTaskTitle": "Καθορισμός εργασίας γεωεπεξεργασίας ανάλυσης ορατότητας",
  "serviceURLError": "Η εργασία γεωεπεξεργασίας που επιχειρείτε να παραμετροποιήσετε μέσω αυτού του widget δεν είναι έγκυρη. Επιλέξτε μια έγκυρη διεύθυνση URL για την εργασία γεωεπεξεργασίας ανάλυσης ορατότητας.",
  "defaultMilsForAnglesLabel": "Καθορισμός mil ως προεπιλεγμένης μονάδας για γωνίες",
  "defaultObserverHeightLabel": "Προεπιλεγμένη μονάδα ύψους θέσης παρατήρησης",
  "defaultObservableDistanceLabel": "Προεπιλεγμένη μονάδα παρατηρήσιμης απόστασης",
  "units": {
    "miles": "Μίλια",
    "kilometers": "Χιλιόμετρα",
    "feet": "Πόδια",
    "meters": "Μέτρα",
    "yards": "Γιάρδες",
    "nauticalMiles": "Ναυτικά μίλια"
  },
  "helpIconTooltip": "Η λίστα των λειτουργικών θεματικών επιπέδων συμπληρώνεται με θεματικά επίπεδα τύπου γεωμετρίας πολυγώνου από τον τρέχοντα web χάρτη.",
  "selectOperationalLayerLabel": "Επιλέξτε ένα λειτουργικό θεματικό επίπεδο για αποτελέσματα.",
  "lineOfSightTabTitle": "Οπτική γραμμή",
  "symbologyTabTitle": "Συμβολολογία",
  "transparency": "Διαφάνεια",
  "outline": "Περίγραμμα",
  "fill": "Γέμισμα (Το χρώμα εφαρμόζεται μόνο όταν έχετε καθορίσει τη χρήση του συμπαγούς στιλ.)",
  "style": "Style",
  "selectOpLayerLabel": "Επιλέξτε ένα λειτουργικό θεματικό επίπεδο για αποτελέσματα.",
  "selectDefaultMeasurementLabel": "Επιλέξτε μια προεπιλεγμένη μονάδα μέτρησης.",
  "visibleSectionLabel": "Ορατό τμήμα",
  "nonVisibleSectionLabel": "Μη ορατό τμήμα",
  "visibleSectionButtonLabel": "Διαμόρφωση ρυθμίσεων ορατού τμήματος",
  "nonVisibleSectionButtonLabel": "Διαμόρφωση ρυθμίσεων μη ορατού τμήματος",
  "colorPicker": "Εργαλείο Επιλογής Χρώματος",
  "lineStyles": {
    "esriSLSDash": "Παύλα",
    "esriSLSDashDot": "Παύλα τελεία",
    "esriSLSDashDotDot": "Παύλα τελεία τελεία",
    "esriSLSDot": "Τελεία",
    "esriSLSLongDash": "Μεγάλη παύλα",
    "esriSLSLongDashDot": "Μεγάλη παύλα τελεία",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Μικρή παύλα",
    "esriSLSShortDashDot": "Μικρή παύλα τελεία",
    "esriSLSShortDashDotDot": "Μικρή παύλα τελεία τελεία",
    "esriSLSShortDot": "Μικρή τελεία",
    "esriSLSSolid": "Συμπαγές"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Προς τα πίσω",
    "esriSFSCross": "Σταυρός",
    "esriSFSDiagonalCross": "Διαγώνια",
    "esriSFSForwardDiagonal": "Προώθηση",
    "esriSFSHorizontal": "Οριζόντια",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Συμπαγές",
    "esriSFSVertical": "Κατακόρυφα"
  }
});