define({
  "transparencyLabel": "Průhlednost",
  "outline": "Obrys",
  "fill": "Výplň (barva se použije, pouze pokud je styl nastaven jako plný)",
  "style": "Styl",
  "selectOpLayerLabel": "Pro výsledky vyberte provozní vrstvu",
  "selectDefaultMeasurementLabel": "Vybrat výchozí měrnou jednotku",
  "helpIconTooltip": "Seznam provozních vrstev je vyplněn vrstvami z aktuální webové mapy, které jsou typu polygonové geometrie.",
  "lineStyles": {
    "esriSLSDash": "Čárkovaná",
    "esriSLSDashDot": "Čerchovaná",
    "esriSLSDashDotDot": "Dvojčerchovaná",
    "esriSLSDot": "Tečka",
    "esriSLSLongDash": "Čárkovaná s dlouhými čárkami",
    "esriSLSLongDashDot": "Čerchovaná s dlouhými čárkami",
    "esriSLSNull": "Prázdný",
    "esriSLSShortDash": "Krátké čárky",
    "esriSLSShortDashDot": "Čerchovaná s krátkými čárkami",
    "esriSLSShortDashDotDot": "Dvojitě čerchovaná s krátkými čárkami",
    "esriSLSShortDot": "Tečkovaná",
    "esriSLSSolid": "Plný"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Dozadu",
    "esriSFSCross": "Křížek",
    "esriSFSDiagonalCross": "Diagonální",
    "esriSFSForwardDiagonal": "Dopředu",
    "esriSFSHorizontal": "Vodorovně",
    "esriSFSNull": "Prázdný",
    "esriSFSSolid": "Plný",
    "esriSFSVertical": "Svisle"
  },
  "threatTypeLabel": "Typ hrozby",
  "generalLabel": "Obecné",
  "addThreatTypesLabel": "Přidat typ hrozby",
  "actions": "Akce",
  "newThreatTypePopupLabel": "Nový typ hrozby",
  "units": "Jednotky",
  "chooseDefaultThreatLabel": "Vyberte výchozí typ hrozby",
  "defaultThreatTypePopUpLabel": "Výchozí typy hrozeb",
  "editThreatLabel": "Upravit hrozbu",
  "defaultThreatTypeIconTooltip": "Seznam výchozích typů hrozeb",
  "uniqueThreatTypeMsg": "Zadejte nový typ hrozby, typ hrozby s tímto názvem již existuje.",
  "requiredMsg": "Toto pole je vyžadováno.",
  "unitMeasureLabel": "Vzdálenosti jsou v {0}",
  "chooseDefaultThreatTypeIconLabel": "Vybrat z výchozích",
  "pipeBombLabel": "Trubková bomba",
  "suicideBombLabel": "Bomba pro sebevražedný útok",
  "briefcaseLabel": "Kufřík",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Malá dodávka",
  "containerWaterTruckLabel": "Auto s kontejnerem/cisternou",
  "semiTrailerLabel": "Návěs",
  "chemicalThreatLegendLabel": "Chemická hrozba",
  "lpgThreatLegendLabel": "Hrozba LPG",
  "smallLPGTank": "Malá nádrž na LPG",
  "largeLPGTank": "Velká nádrž na LPG",
  "commercialResidentialLPGTank": "Komerční/rezidenční nádrž na LPG",
  "smallLPGTruck": "Malé nákladní vozidlo pro přepravu LPG",
  "semiTankerLPG": "Semi tanker pro přepravu LPG",
  "threatDescriptionColLabel": "Popis hrozby",
  "addThreatZoneButtonLabel": "Přidat zónu hrozby",
  "zoneDescColLabel": "Popis zóny",
  "distanceLabel": "Vzdálenost (${unitAbbr})",
  "threatTypeHelp": "<p>Ujistěte se, že jsou pro typ hrozby splněny následující podmínky:<br/><ul><li>Typ hrozby nesmí být nevyplněný a měl by být jedinečný</li><li>Hrozba by měla mít alespoň jednu platnou zónu</li><li>Popis zóny by měl být pro hrozbu jedinečný</li></ul><p/>",
  "descriptionLabel": "Popis",
  "newThreatZonePopupLabel": "Nová zóna hrozby",
  "editThreatZonePopupLabel": "Upravit zónu hrozby",
  "uniqueZoneDescriptionMsg": "Zadejte jedinečný popis zóny, popis zóny s tímto názvem již existuje.",
  "symbologyColLabel": "Nastavení symbolů",
  "zoneDescriptionColLabel": "Popis zóny",
  "uniqueZoneRequiredMsg": "Název zóny by měl být jedinečný pro",
  "interactive": "Interaktivní",
  "fromCoord": "Pevná souřadnice",
  "existingFeature": "Z existujících prvků",
  "defaultInputLocationLabel": "Výchozí vstupní umístění",
  "defaultInputLayer": "Výchozí vstupní vrstva",
  "defaultThreatType": "Výchozí typ hrozby",
  "selectLabel": "Vybrat",
  "mandatoryLabel": "Povinná evakuační vzdálenost",
  "safeLabel": "Bezpečná evakuační vzdálenost",
  "lpgSafeDistanceLable": "Bezpečná vzdálenost",
  "fireBallDiameterLable": "Poloměr ohnivé koule"
});