define({
  "layersPage": {
    "allLayers": "כל השכבות",
    "title": "בחר תבנית כדי ליצור ישויות או לחץ על ישות במפה כדי לערוך אותה",
    "generalSettings": "הגדרות כלליות",
    "layerSettings": "הגדרות שכבה",
    "webmapSettingsRadioBtnLabel": "פעל בהתאם להגדרות במפת האינטרנט",
    "customSettingsRadioBtnLabel": "הגדרות מותאמות אישית",
    "smartActionsTabTitle": "פעולות חכמות",
    "attributeActionsTabTitle": "פעולות מאפיינים",
    "geocoderSettingsText": "הגדרות הכלי לעיגון כתובות",
    "editDescription": "ספק טקסט להצגה עבור לוח העריכה",
    "editDescriptionTip": "טקסט זה מוצג מעל לבורר התבניות. אם אינך מעוניין להציג טקסט, השאר ריק.",
    "promptOnSave": "עם סגירת טופס או מעבר לרשומה הבאה, שאל אם לשמור פעולות עריכה שלא נשמרו",
    "promptOnSaveTip": "הצג הודעה כאשר בוצעו בישות הנוכחית פעולות עריכה שלא נשמרו. (העתקת מספר ישויות שומרת אוטומטית.)",
    "promptOnDelete": "בקש אישור בעת מחיקת רשומה",
    "promptOnDeleteTip": "כאשר משתמש לוחץ למחיקה, בקש אישור לביצוע הפעולה.",
    "removeOnSave": "הסר ישות מהבחירה בעת שמירה",
    "removeOnSaveTip": "אפשרות להסרת הישות מהבחירה שנקבעה בעת שמירת הרשומה. אם זו הרשומה היחידה שנבחרה, החלונית חוזרת לדף התבניות.",
    "useFilterEditor": "השתמש בפילטר של תבניות ישות",
    "useFilterEditorTip": "אפשרות להשתמש בבורר תבניות הסינון שמאפשר להציג תבנית של שכבה יחידה או לחפש תבניות לפי שם.",
    "groupFilteredTemplates": "קיבוץ תוצאות חיפוש",
    "groupFilteredTemplatesTip": "אפשרות לקבץ את תוצאות החיפוש לפי שכבה.",
    "displayShapeSelector": "הצג אפשרויות שרטוט",
    "createNewFeaturesFromExisting": "אפשר למשתמש ליצור ישויות חדשות מישויות קיימות",
    "createNewFeaturesFromExistingTip": "אפשרות שהמשתמש יוכל להעתיק ישות קיימת וליצור ישויות חדשות",
    "copiedFeaturesOverrideDefaults": "הערכים של הישויות שהועתקו מחליפים את ברירות המחדל",
    "copiedFeaturesOverrideDefaultsTip": "ערכים מישויות שהועתקו יחליפו את הערכים מתבנית ברירת המחדל רק עבור השדות המתאימים",
    "displayShapeSelectorTip": "אפשרות להציג רשימה של אפשרויות שרטוט חוקיות עבור התבנית שנבחרה.",
    "displayPresetTop": "הצג רשימת ערכים קבועה מראש למעלה",
    "displayPresetTopTip": "אפשרות להציג רשימת ערכים קבועה מראש מעל לבורר התבניות.",
    "listenToGroupFilter": "החל ערכי מסננים מהווידג'ט 'מסנן קבוצתי' על השדות המוגדרים מראש",
    "listenToGroupFilterTip": "כאשר מסנן מיושם בווידג'ט 'מסנן קבוצתי', החל את הערך על שדה תואם ברשימת הערכים המוגדרים מראש.",
    "keepTemplateActive": "השאר את התבנית שנבחרה במצב פעיל",
    "editLayerAddedFromAddData": "אפשר עריכה של שכבות שנוספו מווידג'ט הוספת הנתונים",
    "editLayerAddedFromAddDataTip": "ניתן לערוך את השכבות המאפשרות עריכה שנוספו לאפליקציה באמצעות ווידג'ט הוספת הנתונים",
    "keepTemplateActiveTip": "כאשר בורר התבניות מוצג, אם תבנית מסוימת נבחרה קודם לכן, בחר אותה מחדש.",
    "geometryEditDefault": "הפעל עריכת גיאומטריה כברירת מחדל",
    "autoSaveEdits": "שמור ישויות חדשות באופן אוטומטי",
    "enableAttributeUpdates": "הצג לחצן לעדכון פעולות מאפיינים",
    "enableAutomaticAttributeUpdates": "קריאה אוטומטית לפעולת המאפיין לאחר עדכון הגיאומטריה",
    "enableLockingMapNavigation": "אפשר נעילה של הניווט במפה",
    "enableMovingSelectedFeatureToGPS": "אפשר העברה של ישות הנקודה שנבחרה למיקום GPS",
    "enableMovingSelectedFeatureToXY": "אפשר העברה של ישות הנקודה שנבחרה למיקום XY",
    "featureTemplateLegendLabel": "הגדרות ערכי תבנית ישויות ומסנן",
    "saveSettingsLegendLabel": "שמור הגדרות",
    "geometrySettingsLegendLabel": "הגדרות גיאומטריה",
    "actionsSettingsLegendLabel": "הגדרות של פעולות",
    "buttonPositionsLabel": "מיקום לחצני השמירה, המחיקה, החזרה והביטול",
    "belowEditLabel": "מתחת לטופס העריכה",
    "aboveEditLabel": "מעל טופס העריכה",
    "switchToMultilineInput": "עבור לקלט מרובה קווים כאשר אורך השדה מעל",
    "enableValuePicker": "אפשר בורר של ערכי צמתים",
    "enableValuePickerHint": "הצג הודעה כאשר יש כמה ערכים זמינים לשדה עם פעולה של מאפיין צומת",
    "expandRelatedTable": "הרחב את כל הטבלאות/השכבות הקשורות בעת טעינה",
    "expandMainTable": "הרחב את כל שכבות האב בעת טעינה",
    "layerSettingsTable": {
      "allowDelete": "אפשר מחיקה",
      "allowDeleteTip": "התר מחיקה - אפשרות להתיר למשתמש למחוק ישות; מושבת אם השכבה לא תומכת במחיקה",
      "edit": "ניתן לעריכה",
      "editTip": "ניתנת לעריכה - אפשרות לכלול את השכבה בווידג'ט",
      "label": "שכבה",
      "labelTip": "שכבה - שם השכבה כפי שמוגדר במפה",
      "update": "השבת עריכת גיאומטריה",
      "updateTip": "השבת עריכת גאומטריה - אפשרות להשבית את היכולת להזזת הגיאומטריה לאחר הצבתה, או להזזת הגיאומטריה בישות קיימת",
      "allowUpdateOnly": "עדכון בלבד",
      "allowUpdateOnlyTip": "עדכון בלבד - אפשרות להתרת ביצוע פעולות של שינוי בלבד בישויות קיימות; מופעל כברירת מחדל ומושבת אם השכבה לא תומכת ביצירת תכונות חדשות",
      "fieldsTip": "שנה את השדות שמיועדים לעריכה, והגדר ישויות חכמות",
      "actionsTip": "פעולות - אפשרות לעריכת שדות או לגישה אל שכבות/טבלאות קשורות",
      "description": "תאור",
      "descriptionTip": "תיאור - אפשרות להזין טקסט שיוצג בחלק העליון של דף המאפיינים.",
      "relationTip": "הצג שכבות וטבלאות קשורות"
    },
    "editFieldError": "שינויים בשדות וישויות חכמות אינם זמינים בשכבות שלא ניתנות לעריכה",
    "noConfigedLayersError": "'עורך חכם' דורש שכבה ניתנת לעריכה אחת לפחות",
    "toleranceErrorMsg": "ערך טולרנס ברירת מחדל לא חוקי של צומת",
    "pixelsToleranecErrorMsg": "ערך טולרנס ברירת מחדל לא חוקי של צומת",
    "invalidMaxCharacterErrorMsg": "ערך לא חוקי במעבר לקלט מרובה קווים",
    "featuresSelectionTolerance": "הגדר את הטולרנס לצורך בחירת ישויות (פיקסלים)",
    "featuresSelectionToleranceTooltip": "מאפשר למשתמשים לפתוח בקלות את חלונית עריכת התכונות על ידי לחיצה על הישות",
    "featuresSelectionToleranceErrorMsg": "ערך לא חוקי של טולרנס לבחירת ישויות",
    "autoSaveAttrUpdates": "שמור עדכוני תכונות באופן אוטומטי"
  },
  "editDescriptionPage": {
    "title": "הגדר טקסט סקירה כללית לישויות עבור <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "הגדר שדות עבור <b>${layername}</b>",
    "copyActionTip": "פעולות מאפיינים",
    "editActionTip": "פעולות חכמות",
    "description": "השתמש בלחצן העריכה של הפעולות כדי להפעיל מאפיינים חכמים בשכבה. המאפיינים החכמים יכולים לדרוש, להסתיר או להשבית שדה על בסיס ערכים של שדות אחרים. השתמש בלחצן ההעתקה של הפעולות כדי להפעיל ולהגדיר את מקור הערך של שדה לפי צומת, כתובת, קואורדינטות וערך שנקבע מראש.",
    "fieldsNotes": "* מציין שדה חובה. אם אתה מבטל את הסימון להצגה עבור השדה הזה ותבנית העריכה לא משלימה את ערך השדה, לא תוכל לשמור רשומה חדשה.",
    "smartAttachmentText": "הגדר פעולות חכמות לקבצים מצורפים",
    "smartAttachmentPopupTitle": "הגדר פעולות חכמות לקבצים מצורפים ב-<b>${layername}</b>",
    "noDisplayFieldWarningMsg": "בחר לפחות שדה תצוגה אחד לשכבה ${layerName}",
    "fieldsSettingsTable": {
      "display": "תצוגה",
      "displayTip": "תצוגה - קבע אם השדה אינו נראה",
      "edit": "ניתן לעריכה",
      "editTip": "ניתן לעריכה - הפעל אם השדה קיים בטופס המאפיינים",
      "fieldName": "שם",
      "fieldNameTip": "שם - שם השדה מוגדר במסד הנתונים",
      "fieldAlias": "כינוי",
      "fieldAliasTip": "כינוי - שם השדה מוגדר במפה",
      "canPresetValue": "קבוע מראש",
      "canPresetValueTip": "הגדרה מראש - אפשרות להצגת השדה ברשימת השדות המתוכנתים, ולהתיר למשתמש להגדיר ערך לפני העריכה",
      "actions": "פעולות",
      "actionsTip": "פעולות - שנה את סדר השדות או הגדר מאפיינים חכמים"
    },
    "smartAttSupport": "מאפיינים חכמים לא נתמכים בשדות חובה של מסדי נתונים"
  },
  "actionPage": {
    "title": "הגדר את פעולות המאפיינים עבור <b>${fieldname}</b>",
    "smartActionTitle": "הגדר פעולות חכמות עבור <b>${fieldname}</b>",
    "description": "הפעולות תמיד מושבתות, למעט אם אתה מציין את הקריטריונים להפעלתן. הפעולות מעובדות לפי הסדר ורק פעולה אחת תופעל לכל שדה. השתמש בלחצן 'עריכת קריטריונים' להגדרת הקריטריונים.",
    "copyAttributesNote": "השבתה של פעולה כלשהי שיש לה שם קבוצה תהיה זהה לעריכה של הפעולה באופן עצמאי, והיא תסיר את הפעולה על השדה הזה מהקבוצה המתאימה.",
    "searchPlaceHolder": "חיפוש",
    "expandAllLabel": "הרחב את כל השכבות",
    "selectAllLabel": "בחר את כל השדות",
    "domainListTitle": "שדות דומיין",
    "noValidFieldTypeMsg": "אין שכבה מתאימה זמינה במפה עבור סוג נתונים זה",
    "actionsSettingsTable": {
      "rule": "פעולה",
      "ruleTip": "פעולה - הפעולה מתבצעת כשהקריטריונים מתמלאים",
      "expression": "ביטוי",
      "expressionTip": "ביטוי - הביטוי שמתקבל בפורמט SQL מהקריטריונים שהוגדרו",
      "groupName": "שם קבוצה",
      "groupNameTip": "שם הקבוצה - מציג את שם הקבוצה שממנה הביטוי חל",
      "actions": "קריטריונים",
      "actionsTip": "קריטריונים - שנה את סדר הכלל והגדר את הקריטריונים להפעלתו"
    },
    "copyAction": {
      "description": "המקורות של ערכי השדות עוברים עיבוד לפי הסדר, אם הם מופעלים, עד שקריטריון חוקי מתמלא או עד שהמערכת מגיע לסוף הרשימה. השתמש בלחצן העריכה של הקריטריונים כדי להגדיר את הקריטריונים.",
      "intersection": "חיתוך",
      "coordinates": "קואורדינטות",
      "address": "כתובת",
      "preset": "קבוע מראש",
      "actionText": "פעולות",
      "criteriaText": "קריטריונים",
      "enableText": "מאופשר"
    },
    "actions": {
      "hide": "הסתר",
      "required": "נדרש",
      "disabled": "לא פעיל"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "אזהרה: עריכה עצמאית תגרום להסרה מהקבוצה של פעולת המאפיין שנבחר הקשורה לשדה זה",
      "editGroupHint": "אזהרה: עריכה עצמאית תגרום להסרה מהקבוצה של הפעולה החכמה שנבחרה הקשורה לשדה זה",
      "popupTitle": "בחר אפשרות עריכה",
      "editAttributeGroup": "פעולת המאפיין שנבחרה מוגדרת לפי הקבוצה. בחר אחת מהאפשרויות הבאות כדי לערוך את פעולת המאפיין:",
      "expression": "הביטוי של הפעולה החכמה שנבחרה מוגדר מהקבוצה. בחר אחת מהאפשרויות הבאות כדי לערוך את הביטוי של הפעולה החכמה:",
      "editGroupButton": "ערוך שכבה",
      "editIndependentlyButton": "ערוך בנפרד"
    }
  },
  "filterPage": {
    "submitHidden": "שלח נתוני מאפיינים עבור שדות גם כאשר מוסתרים",
    "title": "הגדר ביטוי עבור החוק ${action}",
    "filterBuilder": "הגדר פעולה בשדה כאשר הרשומה תואמת ל-${any_or_all} מהביטויים הבאים",
    "noFilterTip": "באמצעות הכלים הבאים, הגדר את ההצהרה ליישום הפעולה."
  },
  "geocoderPage": {
    "setGeocoderURL": "הגדר URL של מעגן הכתובות",
    "hintMsg": "הערה: אתה מבצע שינוי בשירות של הכלי לעיגון כתובות. הקפד לעדכן את כל מיפויי השדות שהגדרת בכלי לעיגון כתובות.",
    "invalidUrlTip": "ה-URL ‏${URL} שגוי או אינו נגיש."
  },
  "addressPage": {
    "popupTitle": "כתובת",
    "checkboxLabel": "קבל ערך מהכלי לעיגון כתובות",
    "selectFieldTitle": "מאפיין",
    "geocoderHint": "כדי לבצע שינויים בכלי לעיגון כתובות, לחץ על הלחצן 'הגדרות הכלי לעיגון כתובות' בהגדרות הכלליות",
    "prevConfigruedFieldChangedMsg": "מאפיין שהוגדר קודם לא נמצא בהגדרות הנוכחיות של הכלי לעיגון כתובות. בוצע איפוס של המאפיין לברירת המחדל.",
    "questionMark": "?",
    "consumesCredits": "כלי זה צורך קרדיטים בעת השימוש עם שירות עיגון הכתובות העולמי של ArcGIS Online."
  },
  "coordinatesPage": {
    "popupTitle": "קואורדינטות",
    "checkboxLabel": "קבל קואורדינטות",
    "coordinatesSelectTitle": "מערכת ייחוס",
    "coordinatesAttributeTitle": "מאפיין",
    "mapSpatialReferenceOptionLabel": "ייחוס מרחבי של מפה",
    "latLongOptionLabel": "קו רוחב/אורך",
    "MGRS": "MGRS",
    "allGroupsCreatedMsg": "כל הקבוצות האפשריות כבר נוצרו",
    "coordinatesSourceTitle": "מקור הקואורדינטות",
    "featureLocation": "מיקום ישויות",
    "myLocation": "המיקום שלי",
    "LatLong": {
      "y": "קו רוחב",
      "x": "קו אורך",
      "xy": "קו אורך קו רוחב",
      "yx": "קו רוחב קו אורך"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "קבוע מראש",
    "checkboxLabel": "השדה ייקבע מראש",
    "showOnlyDomainFields": "הצג רק שדות דומיין",
    "hideInPresetDisplay": "הסתר בתצוגת ערך מוגדר מראש",
    "presetValueLabel": "הערך הנוכחי הקבוע מראש הוא:",
    "changePresetValueHint": "כדי לשנות ערך זה שנקבע מראש, עבור אל 'הגדר ערכים קבועים מראש' בהגדרות הכלליות"
  },
  "intersectionPage": {
    "groupNameLabel": "שם קבוצה",
    "dataTypeLabel": "סוג נתונים",
    "ignoreLayerRankingCheckboxLabel": "התעלם מדירוג השכבה ומצא את הישות הקרובה ביותר בכל השכבות המוגדרות",
    "intersectingLayersLabel": "שכבות לחילוץ ערך",
    "layerAndFieldsApplyLabel": "שכבות ושדות שעליהם יחול הערך שחולץ",
    "checkboxLabel": "קבל ערך מהשדה של שכבת הצמתים",
    "layerText": "שכבות",
    "fieldText": "שדות",
    "actionsText": "פעולות",
    "toleranceSettingText": "הגדרות טולרנס",
    "addLayerLinkText": "הוסף שכבה",
    "useDefaultToleranceText": "השתמש בטולרנס ברירת המחדל",
    "toleranceValueText": "ערך טולורנס",
    "toleranceUnitText": "יחידת טולרנס",
    "pixelsUnitText": "פיקסלים",
    "useLayerName": "- השתמש בשם השכבה -",
    "noLayersMessage": "לא נמצא שדה בשכבות המפה שמתאים לסוג הנתונים שנבחר.",
    "intersectionLayerHint": "דירוג שכבות נקבע בסדר יורד. השתמש בחצים שמתחת ל'פעולות' כדי לשנות את סדר השכבות ולשנות קדימות של צמתים."
  },
  "presetAll": {
    "popupTitle": "הגדר את ערכי ברירת המחדל הקבועים מראש",
    "deleteTitle": "מחק ערך קבוע מראש",
    "hintMsg": "כל שמות השדות הקבועים מראש הייחודיים מפורטים כאן. הסרה של שדה קבוע מראש תביא להשבתת השדה התואם כערך קבוע מראש בכל השכבות/הטבלאות."
  },
  "intersectionTolerance": {
    "intersectionTitle": "טולרנס ברירת המחדל של צמתים לכל הישויות",
    "pixelsToleranceTitle": "טולרנס ברירת המחדל של צמתים (ערך פיקסל) שיחול על ישויות נקודתיות בלבד"
  },
  "smartActionsPage": {
    "smartActionLabel": "הגדר פעולה חכמה",
    "addNewSmartActionLinkText": "הוסף חדש",
    "definedActions": "פעולות שהוגדרו",
    "priorityPopupTitle": "הגדר עדיפות לפעולות חכמות",
    "priorityPopupColumnTitle": "פעולות חכמות",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "שם קבוצה",
    "layerForExpressionLabel": "שכבה לביטוי",
    "layerForExpressionNote": "הערה: השדות של שכבה זו משמשים להגדרת הקריטריונים של הביטוי. 'שכבות ושדות שעליהם יחול' מציג רק שכבות וטבלאות שבהם השדות מוגדרים בביטוי.",
    "expressionText": "ביטוי",
    "editExpressionLabel": "ערוך ביטוי",
    "layerAndFieldsApplyLabel": "שכבות ושדות שעליהם יחול",
    "submitAttributeText": "שלח נתוני מאפיינים עבור שדות גם כאשר מוסתרים",
    "priorityColumnText": "עדיפות",
    "requiredGroupNameMsg": "חובה להזין את הערך הזה",
    "uniqueGroupNameMsg": "הזן שם קבוצה ייחודי, כבר קיימת קבוצה עם השם הזה.",
    "deleteGroupPopupTitle": "מחק קבוצה של פעולות חכמות",
    "deleteGroupPopupMsg": "מחיקת קבוצה תגרום להסרת הביטוי מכל הפעולות הקשורות על שדות.",
    "invalidExpression": "הביטוי לא יכול להיות ריק",
    "warningMsgOnLayerChange": "יבוצע ניקוי של הביטוי שהוגדר והשדות שעליהם הוא חל.",
    "smartActionsTable": {
      "name": "שם",
      "expression": "ביטוי",
      "definedFor": "הוגדר עבור"
    }
  },
  "attributeActionsPage": {
    "name": "שם",
    "type": "סוג",
    "deleteGroupPopupTitle": "מחק קבוצה של פעולות מאפיינים",
    "deleteGroupPopupMsg": "מחיקת קבוצה תגרום להסרת פעולת המאפיינים מכל השדות הקשורים.",
    "alreadyAppliedActionMsg": "פעולת ${action} בוצעה על השדה הזה בקבוצה",
    "alreadyAppliedActionLayerMsg": "פעולת ${action} בוצעה על שדה זה בהגדרות השכבה",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "לקבוצה הזו אין שדות משויכים.",
    "presetNoFieldWarningMsg": "יש להגדיר לפחות שדה אחד לקבוצה שנקבעה מראש:${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "שדה",
    "valueLabel": "ערך",
    "selectValueLabel": "בחר ערך",
    "domainFieldHintLabel": "הערך שנבחר הוא דומיין של ערכים מקודדים. ייעשה שימוש בערך: ${domainValue}"
  },
  "presetPopup": {
    "presetValueLAbel": "ערך קבוע מראש"
  },
  "dataType": {
    "esriFieldTypeString": "מחרוזת",
    "esriFieldTypeInteger": "מספר",
    "esriFieldTypeDate": "תאריך",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "סוג תאריך",
    "valueLabel": "ערך",
    "fixed": "קבוע",
    "current": "נוכחי",
    "past": "עבור",
    "future": "עתיד",
    "popupTitle": "בחר ערך",
    "hintForFixedDateType": "עצה: התאריך והשעה שצוינו ישמשו כערך ברירת מחדל מוגדר מראש",
    "hintForCurrentDateType": "עצה: התאריך והשעה הנוכחיים ישמשו כערך ברירת מחדל מוגדר מראש",
    "hintForPastDateType": "עצה: הערך שצוין יופחת מהתאריך והשעה הנוכחיים לקבלת ערך ברירת המחדל של ההגדרה מראש.",
    "hintForFutureDateType": "עצה: הערך שצוין יתווסף לתאריך ולשעה הנוכחיים לקבלת ערך ברירת המחדל של ההגדרה מראש.",
    "noDateDefinedTooltip": "לא הוגדר תאריך",
    "relativeDateWarning": "חובה לציין ערך עבור תאריך או שעה כדי שניתן יהיה לשמור את ערך ברירת המחדל הקבוע מראש.",
    "customLabel": "מותאם אישית"
  },
  "relativeDomains": {
    "fieldSetTitle": "רשימה",
    "valueText": "ערך",
    "defaultText": "ברירת מחדל",
    "selectedDomainFieldsHint": "שדות דומיין שנבחרו: ${domainFields}",
    "selectDefaultDomainMsg": "בחר דומיין ערך ברירת מחדל או ודא שתיבת הסימון של דומיין ברירת המחדל שנבחר מסומנת"
  }
});