define({
  "_widgetLabel": "Duomenų agregavimas",
  "startPage": {
    "defaultStartPageInstructions": "Šis valdiklis padės apdoroti ir pateikti failo duomenis pasirinktame žemėlapio sluoksnyje.<br/> <br/> Reikšmės faile turi būti atskirtos kableliais, tabuliavimo žingsniais, kabliataškiais arba vertikaliaisiais brūkšniais.",
    "dragDrop": "Nuvilkti",
    "browse": "Parinkti failą",
    "or": "'ARBA'",
    "userPrivilege": "Jūsų paskyra neturi teisės kurti arba modifikuoti duomenų.",
    "userCredits": "„${widgetName}“ reikia kreditų, kad galėtų naudoti lokatorių ${locator}.",
    "contactAdmin": "Dėl papildomų kreditų kreipkitės į organizacijos administratorių.",
    "contactAdminEdit": "Dėl redagavimo teisių kreipkitės į organizacijos administratorių.",
    "canUseLocator": "Lokatorius ${locator} bus naudojamas elementams rasti.",
    "notEnoughCredits": "Nepakanka kreditų.",
    "locationAndField": "Vietos ir lauko informacija",
    "locationAndFieldHint": "Pasirinkite reikšmes iš failo, kurios turėtų būti naudojamos tiksliniam sluoksniui atnaujinti.",
    "cannotUseLocator": "Nepavyksta naudoti ${widgetName}",
    "noAnonymousEdit": "Sluoksnis ${layerName} nepalaiko anoniminio redagavimo.",
    "pleaseLogin": "Jei norite įjungti anoniminį redagavimą, prisijunkite prie organizacijos ${org} arba susisiekite su organizacijos administratoriumi.",
    "invalidEdit": "Netinkamos teisės",
    "unableToAccess": "Nepavyksta pasiekti ${layerName}",
    "appropriateCredentials": "Patikrinkite, ar prisijungėte naudodami tinkamus kredencialus.",
    "shared": "Norėdami prašyti prieigos prie sluoksnio „${layerName}“ kreipkitės į organizacijos administratorių.",
    "targetLayerLabel": "Tikslinis sluoksnis",
    "homeButtonLabel": "Pradžia",
    "mappingErrorMsg": "Paspauskite šalia esančią rodyklę ir apibrėžkite laukus"
  },
  "mapping": {
    "schemaMapping": "Lauko informacija",
    "schemaMappingHint": "Pasirinkite failo laukus, kurie yra susiję su laukais, esančiais sluoksnyje.",
    "locationMapping": "Vietos informacija",
    "locationMappingHint": "Pasirinkite adreso tipą arba koordinačių informaciją, kurios tikitės iš failo."
  },
  "locationMapping": {
    "locationMappingPageHint": "Pasirinkite vietos tipą",
    "useAddress": "Rasti pagal adresą",
    "useAddressHint": "Duomenyse yra adreso informacija",
    "useCoordinates": "Rasti pagal koordinates",
    "useCoordinatesHint": "Duomenyse yra X/Y koordinačių reikšmės"
  },
  "address": {
    "addressPageHint": "Pasirinkite adreso tipą",
    "singleField": "Vienas laukas",
    "singleFieldHint": "Pasirinkite lauką, kuriame yra adreso informacija",
    "multiField": "Keli laukai",
    "multiFieldHint": "Pasirinkite laukus, kuriuose yra adreso informacija"
  },
  "coordinates": {
    "coordinatesPageHint": "Pasirinkite laukus, kuriuose yra koordinačių duomenys"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Pasirinkite šaltinio lauką, kuris susieja su tiksliniu lauku",
    "sourceField": "Atitinkantis šaltinio laukas",
    "targetField": "Paskirties vietos laukas"
  },
  "buttons": {
    "addToMap": "Pridėti į žemėlapį",
    "submit": "Pateikti",
    "download": "Atsisiųsti"
  },
  "review": {
    "matched": "Rasta",
    "reviewMatched": "Vietų rasta",
    "reviewMatchedHint": "Peržiūrėkite rastas vietas.",
    "unMatched": "Nerasta",
    "reviewUnMatched": "Vietų nerasta",
    "reviewUnMatchedHint": "Peržiūrėkite nerastas vietas. Nepataisyti elementai nebus pateikti.",
    "duplicate": "Dubliuoti",
    "reviewDuplicate": "Pasikartojančios vietos",
    "reviewDuplicateHint": "Peržiūrėkite vietas, kurios jau buvo rastos sluoksnyje. Neišspęsti elementai nebus pateikti.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Naudoti:",
    "fromLayer": "Tikslinė informacija",
    "target": "Paskirties vieta",
    "source": "Šaltinis",
    "fromFile": "Šaltinio informacija",
    "locationControlHint": "Peržiūrėkite adreso informaciją",
    "duplicateAction": "Pasirinkite veiksmą",
    "item": "Įrašyti:",
    "locateFeature": "Rasti elementą",
    "removeFeature": "Pašalinti elementą",
    "featureLocated": "Vieta rasta",
    "valuesDoNotMatch": "Nesutampa su esama reikšme",
    "sync": "Sinchronizuoti adreso informaciją su lauko informacija",
    "noFeaturesSaved": "Nė vienas elementas neįrašytas sėkmingai",
    "someFeaturesSaved": "Tiek elementų įrašyta sėkmingai: ${num}",
    "someFeaturesNotSaved": "Tiek elementų neįrašyta sėkmingai: ${num}.",
    "feature": "Peržiūrėti elemento informaciją",
    "locationInfo": "Peržiūrėti vietos informaciją",
    "selectValue": "Pasirinkite reikšmę",
    "reviewData": "Peržiūrėti duomenis",
    "reviewDataHint": "Peržiūrėkite savo duomenis prieš pateikdami į sluoksnį.",
    "reviewFeatureHint": "Peržiūrėkite arba redaguokite elemento ir vietos informaciją.",
    "duplicateModify": "Dublikatas, reikalingas pakeitimas",
    "duplicateSave": "Įrašyti kaip naują elementą"
  },
  "warningsAndErrors": {
    "invalidCSV": "Gaunant elementus iš CSV saugyklos įvyko klaida. Patikrinkite, ar pasirinktas tinkamas CSV failas.",
    "noLayersWarning": "Nesukonfigūruotas tinkamas tikslinis sluoksnis. Patikrinkite konfigūraciją.",
    "loadWarning": "Šiam valdikliui reikia elementų paslaugos duomenų šaltinio. Sukonfigūruokite valdiklį ir apibrėžkite duomenų šaltinį.",
    "saveError": "Įrašant elementus įvyko klaida.",
    "consumesCredits": "Šis įrankis naudoja kreditus, kai pasitelkiama ArcGIS Online pasaulinio geokodavimo paslauga",
    "noValue": "Pasirinkti lauką",
    "mappingTitle": "",
    "locationMappingComplete": "Vietos susiejimas atliktas",
    "fieldMappingComplete": "Lauko susiejimas atliktas",
    "settingsCleared": "Parametrai bus išvalyti.",
    "proceed": "Norite tęsti?",
    "itemMoveMatch": "Elementas buvo rastas ir perkeltas į rastų vietų sąrašą",
    "itemMoveUnMatched": "Nepavyksta rasti elemento. Perkelta į nerastų vietų sąrašą.",
    "itemWillBeLocated": "Elementas bus pašalintas iš pasikartojančių vietų sąrašo.",
    "cannotLocate": "Nepavyksta rasti elemento. Patikrinkite vietos informaciją.",
    "invalidMessage": "Netinkama reikšmė.",
    "rangeMessage": "Reikšmė turi būti trumpesnė nei ${num} simb.",
    "locatorError": "Lokatorius netinkamas arba nepasiekiamas.",
    "notConfigured": "esamų ieškojimo parinkčių lokatorius nesukonfigūruotas",
    "noMoreLocators": "papildomi lokatoriai nesukonfigūruoti"
  },
  "featureToolbar": {
    "locate": "Rasti",
    "save": "Įrašyti įrašą",
    "cancel": "Atšaukti redagavimus",
    "cancelTitle": "Atšaukti redagavimus",
    "cancelMessage": "Atšaukti esamo įrašo redagavimus?"
  }
});