define({
  "enableUndoRedo": "Aktivovať krok späť/vrátiť",
  "toolbarVisible": "Panel nástrojov viditeľný",
  "toolbarOptions": "Možnosti panela nástrojov",
  "mergeVisible": "Zlúčiť",
  "cutVisible": "Orezať",
  "reshapeVisible": "Zmeniť tvar",
  "back": "Späť",
  "label": "Vrstva",
  "edit": "Upraviteľný",
  "update": "Zakázať aktualizáciu geometrie",
  "fields": "Polia",
  "actions": "Akcie",
  "editpageName": "Meno",
  "editpageAlias": "Alias",
  "editpageVisible": "Viditeľný",
  "editpageEditable": "Upraviteľný",
  "noLayers": "Nie sú dostupné žiadne editovateľné vrstvy prvkov",
  "configureFields": "Konfigurovať polia vrstvy",
  "useFilterEdit": "Použiť filter šablóny prvku",
  "display": "Zobrazenie",
  "autoApplyEditWhenGeometryIsMoved": "Upraviť automaticky pri pohybe geometrie",
  "snappingTolerance": "Nastaviť toleranciu prichytávania v pixeloch",
  "popupTolerance": "Nastaviť toleranciu vyskakovacieho okna na úpravu atribútov v pixeloch",
  "stickyMoveTolerance": "Nastaviť toleranciu priľnutia pohybu v pixeloch",
  "usingSaveButton": "Neupravujte atribúty pokiaľ nekliknete na tlačidlo Uložiť",
  "generalSettings": "Všeobecné nastavenia",
  "editableLayersSetting": "Nastavenia editovateľných vrstiev",
  "honorTheWebMapSetting": "Dodržiavať nastavenia vo webovej mape",
  "honorTheWebMapSettingTip1": "Tieto nastavenia obsahujú:",
  "honorTheWebMapSettingTip2": "Ktoré vrstvy sú editovateľné",
  "honorTheWebMapSettingTip3": "Polia, ktoré chcete zobraziť a editovať",
  "honorTheWebMapSettingTip4": "Alias, poradie a formát poľa",
  "customSettings": "Vlastné nastavenia"
});