define({
  "taskUrl": "URL de Serviço de Panorama",
  "portalURL": "Especifique a URL para sua organização do ArcGIS Online ou Portal for ArcGIS",
  "portalURLError": "A URL configurada para sua organização do ArcGIS Online ou Portal for ArcGIS não é valida.",
  "privilegeError": "Seu papel de usuário não pode executar análise. Para executar análise, o administrador da sua organização precisa conceder a você determinados <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilégios</a>.",
  "noServiceError": "Serviço de análise de elevação não disponível. Verifique as configurações da sua organização do ArcGIS Online ou Portal for ArcGIS.",
  "serviceURLPlaceholder": "Insira URL da tarefa de Geoprocessamento de Panorama",
  "setTask": "Configurar",
  "setTaskTitle": "Configurar Tarefa de Geoprocessamento de Panorama",
  "serviceURLError": "A tarefa de Geoprocessamento que você está tentando configurar com este widget não é válida. Selecione uma URL da tarefa de Geoprocessamento de Panorama válida",
  "defaultMilsForAnglesLabel": "Definir mils para ângulos como padrão",
  "defaultObserverHeightLabel": "Unidades de Altura do Observador Padrão",
  "defaultObservableDistanceLabel": "Unidade de Distância Observável por Padrão",
  "units": {
    "miles": "Milhas",
    "kilometers": "Quilômetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nauticalMiles": "Milhas náuticas"
  },
  "helpIconTooltip": "A lista de camada operacional é preenchida com camadas a partir do mapa da web atual que são do tipo de geometria de polígono.",
  "selectOperationalLayerLabel": "Selecione uma camada operacional para resultados",
  "lineOfSightTabTitle": "Linha de Visão",
  "symbologyTabTitle": "Simbologia",
  "transparency": "Transparência",
  "outline": "Contorno",
  "fill": "Preencher (a cor somente se aplica quando o estilo é definido para sólido)",
  "style": "Estilo",
  "selectOpLayerLabel": "Selecione uma camada operacional para resultados",
  "selectDefaultMeasurementLabel": "Selecione uma unidade de medição padrão",
  "visibleSectionLabel": "Seção visível",
  "nonVisibleSectionLabel": "Seção não visível",
  "visibleSectionButtonLabel": "Definir as configurações da seção visível",
  "nonVisibleSectionButtonLabel": "Definir as configurações da seção não visível",
  "colorPicker": "Seletor de Cores",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Ponto Traço Curto",
    "esriSLSShortDashDotDot": "Ponto Ponto Traço Curto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Para Trás",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para Frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  }
});