define({
  "_widgetLabel": "Reviewer Dashboard",
  "spatialFilterSelection": "Filtrovať výsledky podľa oblasti",
  "drawSelectionArea": "Kresliť výslednú oblasť výberu na mapu",
  "currentSelection": "Zobraziť výsledky len v aktuálnom rozsahu mapy",
  "censusBlockGroup": "Zobraziť výsledky podľa oblasti",
  "noSpatialFilter": " Nepoužiť žiadny priestorový filter",
  "reviewerSessionFilter": "Filtrovať výsledky podľa Reviewer relácie",
  "selectAttributeFilters": "Vybrať informácie na zobrazenie",
  "phaseFieldName": "fáza životného cyklu",
  "statusFieldName": "status životného cyklu",
  "allSessions": "Všetky relácie",
  "dashboardTab": "Dashboard",
  "filtersTab": "Nastavenia",
  "noResults": "Neboli nájdené žiadne výsledky",
  "resultsBy": "Výsledky podľa: ",
  "reviewed": "Skontrolovať",
  "corrected": "Korekcia",
  "verified": "Overenie",
  "OtherCategory": "Iné",
  "backButton": "Späť"
});