define({
  "_widgetLabel": "Видимост",
  "observerLocation": "Местоположение на наблюдател",
  "formatIconTooltip": "Формат на въвеждане",
  "addPointToolTip": "Добавяне на местоположение на наблюдател",
  "fieldOfView": "Поле за изглед",
  "useMilsText": "Използване на мил за ъгли",
  "observerHeight": "Височина на наблюдател",
  "minObsDistance": "Минимално видимо разстояние",
  "maxObsDistance": "Максимално видимо разстояние",
  "taskURLError": "URL адресът на конфигурационния файл на изпълнимия модул е недостъпен. Моля, обърнете се към системния си администратор",
  "taskURLInvalid": "Конфигурираната задача за геообработка с този изпълним модул не е валидна. Моля, обърнете се към системния си администратор",
  "viewshedError": "Появи се грешка при създаването на видимост. Моля, уверете се, че местоположението на вашия наблюдател попада в рамките на ограничаващия правоъгълник на вашата височина на повърхност.</p>",
  "validationError": "<p>Формулярът за създаване на видимост има липсващи или невалидни параметри, моля, уверете се, че:</p><ul><li>Зададено е местоположение за наблюдател.</li><li>Видимата зона на наблюдателя не е 0.</li><li>Височината на наблюдателя съдържа валидна стойност.</li><li>Минималното и максималното наблюдавани разстояния съдържат валидни стойности.</li></ul>",
  "comfirmInputNotation": "Потвърждаване на нотацията за входни данни",
  "notationsMatch": "нотациите съответстват на въведеното от вас, моля, потвърдете кое бихте искали да използвате:",
  "createBtn": "Създаване",
  "clearBtn": "Изчистване",
  "setCoordFormat": "Задайте текстов формат за координатите",
  "prefixNumbers": "Добавете префикса „+/-“ съответно за положителни и отрицателни числа",
  "parseCoordinatesError": "Не може да се прави разбор на координатите. Моля, проверете входните си данни.",
  "cancelBtn": "Отказ",
  "applyBtn": "Прилагане",
  "invalidMessage": "Моля, въведете цифрова стойност.",
  "observerRangeMessage": "Невалидна височина на наблюдателя",
  "minimumRangeMessage": "Невалиден минимален обхват на наблюдение",
  "maximumRangeMessage": "Максималният обхват на наблюдение трябва да бъде по-голям от минималния обхват на наблюдение и не може да бъде по-голям от ${limit} ${units}.",
  "portalURLError": "URL адресът към Вашата организация в ArcGIS Online или Portal for ArcGIS не е конфигуриран. Моля, обърнете се към системния си администратор",
  "privilegeError": "Вашата потребителска роля не може да извършва анализ. За да извършите анализ, администраторът на вашата организация трябва да ви предостави определени <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">привилегии</a>.",
  "noServiceError": "Услугата за височинен анализ не е налична. Моля, проверете конфигурациите на Вашата организация в ArcGIS Online или Portal for ArcGIS.",
  "pointToolTooltip": "Натиснете, за да добавите местоположение на наблюдател",
  "degreesLabel": "градуси",
  "milsLabel": "милс",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM (Универсална напречна проекция на Меркатор)",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Десетични градуси – географска ширина/географска дължина",
  "DDLongLatNotation": "Десетични градуси – географска дължина/географска ширина",
  "DDMLatLongNotation": "Градуси десетични минути – геаографска ширина/географска дължина",
  "DDMLongLatNotation": "Градуси десетични минути – географска дължина/географска ширина",
  "DMSLatLongNotation": "Градуси Минути Секунди – географска ширина/географска дължина",
  "DMSLongLatNotation": "Градуси Минути Секунди – географска дължина/географска ширина",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Буква на честотна лента",
  "UTMHemNotation": "UTM - Полукълбо (С/Ю)",
  "mainPageTitle": "Радиална линия на видимост",
  "resultsTitle": "Резултати",
  "publishBtnLabel": "Публикуване",
  "layerName": "Публикувано име на слой",
  "invalidLayerName": "Името на слоя трябва да съдържа само буквено-цифрови знаци и долни черти",
  "back": "Назад",
  "publishingFailedLayerExists": "Неуспешно публикуване: Вече има услуга с обекти с това име {0}. Моля, изберете друго име.",
  "checkService": "Поставете отметка на услугата: {0}",
  "createService": "Създаване на услуга: {0}",
  "unableToCreate": "Не може да се създаде: {0}",
  "addToDefinition": "Добавяне към дефиниция: {0}",
  "successfullyPublished": "Успешно публикуван уеб слой {0}Управление на уеб слоя",
  "userRole": "Не може да се създаде услуга, тъй като потребителят няма разрешения",
  "publishToNewLayer": "Публикуване на резултати на нов обектен слой",
  "missingLayerNameMessage": "Трябва да въведете валидно име на слой, преди да можете да публикувате",
  "layerNameExists": "Името на слоя вече съществува. Моля, използвайте различно име на слой.",
  "regionTypeLabel": "Тип район",
  "centerPointLabel": "Централна точка",
  "observationHeightLabel": "Височина на наблюдение",
  "heightUnitLabel": "Мерна единица за височина",
  "minObservationDistanceLabel": "Минимален визуален обхват",
  "maxObservationDistance": "Максимално визуално разстояние",
  "distanceUnitLabel": "Мерна единица за разстояние",
  "fovstartAngleLabel": "Начален ъгъл на зрително поле (FOV)",
  "fovEndAngleLabel": "Краен ъгъл на зрително поле (FOV)",
  "andleUnitsLabel": "Мерни единици за ъгъл",
  "visibleSectionLabel": "Видим раздел",
  "nonVisibleSectionLabel": "Невидим раздел",
  "visibleSectionButtonLabel": "Конфигуриране на настройките на видимия раздел",
  "nonVisibleSectionButtonLabel": "Конфигуриране на настройките на невидимия раздел",
  "transparency": "Прозрачност",
  "outline": "Контур",
  "fill": "Попълване (Цветът се прилага само когато стилът е зададен като плътен)",
  "style": "Стил",
  "colorPicker": "Инструмент за избор на цвят",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире Точка",
    "esriSLSDashDotDot": "Тире Точка Точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Дълго тире",
    "esriSLSLongDashDot": "Дълго тире Точка",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Малко тире",
    "esriSLSShortDashDot": "Малко тире Точка",
    "esriSLSShortDashDotDot": "Малко тире Точка Точка",
    "esriSLSShortDot": "Малка точка",
    "esriSLSSolid": "Плътно"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Пресичане",
    "esriSFSDiagonalCross": "Диагонал",
    "esriSFSForwardDiagonal": "Напред",
    "esriSFSHorizontal": "Хоризонтално",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Плътно",
    "esriSFSVertical": "Вертикално"
  },
  "settingsTitle": "Настройки"
});