define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<div><br>Truy cập Thông tin đồ họa và Báo cáo tổng kết các chỉ báo chính và dữ liệu cho khu vực bất kỳ.</div><br><div>Chọn một điểm hoặc vùng trên bản đồ, tìm kiếm một địa chỉ hoặc địa điểm, vẽ một vùng hoặc ghim một vị trí trên bản đồ để xem các chỉ báo chính và thông tin về khu vực đó.</div>",
  "defineWhichInfographics": "Xác định thông tin đồ họa nào có sẵn trong tiện ích:",
  "defineWhichReports": "Xác định báo cáo nào có sẵn trong tiện ích:",
  "defaultValues": "Giá trị mặc định:",
  "disable": "Vô hiệu hóa",
  "drawFreehandPolygon": "Vẽ Vùng Tùy ý",
  "drawPolygon": "Vẽ Vùng",
  "driveTime": "Thời gian lái xe",
  "dropPin": "Cắm Ghim",
  "dynamicHTML": "HTML động",
  "exportOptions": "Tùy chọn Xuất:",
  "home": "Trang chủ",
  "image": "Hình ảnh",
  "infographics": "Thông tin đồ họa",
  "invalidValueRing": "Giá trị phải nằm trong khoảng 0 đến 1.000.",
  "invalidValueDTWT": "Giá trị phải nằm trong khoảng 0 đến 300.",
  "km": "km",
  "makeDefault": "Đặt làm mặc định",
  "miles": "dặm",
  "minutes": "phút",
  "options": "Tùy chọn:",
  "pdf": "PDF",
  "print": "In",
  "radius": "Bán kính",
  "removeDefault": "Xóa mặc định",
  "reports": "Báo cáo",
  "rings": "Vòng",
  "searchTextBox": "Hộp Văn Bản Tìm kiếm",
  "selectCountryOrRegion": "Chọn quốc gia hoặc khu vực:",
  "thisEntryIsNotValid": "Thông tin nhập này không hợp lệ.",
  "time": "Thời gian",
  "walkTime": "Thời gian đi bộ"
});