define({
  "transparencyLabel": "Gjennomsiktighet",
  "outline": "Omriss",
  "fill": "Fyll (farge brukes bare når heldekkende er valgt som stil)",
  "style": "Stil",
  "selectOpLayerLabel": "Velg et operativt lag til resultater",
  "selectDefaultMeasurementLabel": "Velg en standard måleenhet",
  "helpIconTooltip": "Listen med operative lag fylles med lagene fra gjeldende webkart som er av geometritypen polygon.",
  "lineStyles": {
    "esriSLSDash": "Strek",
    "esriSLSDashDot": "Strek prikk",
    "esriSLSDashDotDot": "Strek prikk prikk",
    "esriSLSDot": "Prikk",
    "esriSLSLongDash": "Lang strek",
    "esriSLSLongDashDot": "Lang strek-prikk",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort strek",
    "esriSLSShortDashDot": "Kort strek-prikk",
    "esriSLSShortDashDotDot": "Kort strek-prikk-prikk",
    "esriSLSShortDot": "Kort prikk",
    "esriSLSSolid": "Heltrukken"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakover",
    "esriSFSCross": "Kryss",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Fremover",
    "esriSFSHorizontal": "Vannrett",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Heltrukken",
    "esriSFSVertical": "Loddrett"
  },
  "threatTypeLabel": "Trusseltype",
  "generalLabel": "Generelt",
  "addThreatTypesLabel": "Legg til trusseltype",
  "actions": "Handlinger",
  "newThreatTypePopupLabel": "Ny trusseltype",
  "units": "Enheter",
  "chooseDefaultThreatLabel": "Velg standard trusseltype",
  "defaultThreatTypePopUpLabel": "Standard trusseltyper",
  "editThreatLabel": "Rediger trussel",
  "defaultThreatTypeIconTooltip": "Standard trusseltypeliste",
  "uniqueThreatTypeMsg": "Oppgi en unik trusseltype. Det finnes allerede en trusseltype med dette navnet.",
  "requiredMsg": "Dette feltet er obligatorisk.",
  "unitMeasureLabel": "Avstander er i {0}",
  "chooseDefaultThreatTypeIconLabel": "Velg fra standard",
  "pipeBombLabel": "Rørbombe",
  "suicideBombLabel": "Selvmordsbombe",
  "briefcaseLabel": "Mappe",
  "carLabel": "Bil",
  "suvVanLabel": "SUV/VAREBIL",
  "smallDeliveryTruckLabel": "Liten varebil",
  "containerWaterTruckLabel": "Container/tankbil",
  "semiTrailerLabel": "Semitrailer",
  "chemicalThreatLegendLabel": "Kjemisk trussel",
  "lpgThreatLegendLabel": "LPG-trussel",
  "smallLPGTank": "Liten LPG-tank",
  "largeLPGTank": "Stor LPG-tank",
  "commercialResidentialLPGTank": "LGP-tank til nærings-/husholdningsbruk",
  "smallLPGTruck": "Liten LPG-lastebil",
  "semiTankerLPG": "Semitanker-LPG",
  "threatDescriptionColLabel": "Trusselbeskrivelse",
  "addThreatZoneButtonLabel": "Legg til trusselsone",
  "zoneDescColLabel": "Sonebeskrivelse",
  "distanceLabel": "Avstand (${unitAbbr})",
  "threatTypeHelp": "<p>Kontroller at følgende betingelser oppfylles for en trusseltype:<br/><ul><li>Trusseltype må oppgis, og den må være unik.</li><li>Trusselen må ha minst én gyldig sone.</li><li>Sonebeskrivelsen må være unik for en trussel.</li></ul><p/>",
  "descriptionLabel": "Beskrivelse",
  "newThreatZonePopupLabel": "Ny trusselsone",
  "editThreatZonePopupLabel": "Rediger trusselsone",
  "uniqueZoneDescriptionMsg": "Angi en unik sonebeskrivelse. Det finnes allerede en sonebeskrivelse med dette navnet.",
  "symbologyColLabel": "Symboler",
  "zoneDescriptionColLabel": "Sonebeskrivelse",
  "uniqueZoneRequiredMsg": "Sonenavnet må være unikt for",
  "interactive": "Interaktiv",
  "fromCoord": "Fast koordinat",
  "existingFeature": "Fra eksisterende geoobjekter",
  "defaultInputLocationLabel": "Standard inndatalokasjon",
  "defaultInputLayer": "Standard inndatalag",
  "defaultThreatType": "Standard trusseltype",
  "selectLabel": "Velg",
  "mandatoryLabel": "Obligatorisk evakueringsavstand",
  "safeLabel": "Sikker evakueringsavstand",
  "lpgSafeDistanceLable": "Trygg avstand",
  "fireBallDiameterLable": "Ildkulediameter"
});