define({
  "_widgetLabel": "Konverzia súradníc",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desatinné stupne - Zemepisná šírka/dĺžka",
  "DDLongLatNotation": "Desatinné stupne - Zemepisná dĺžka/šírka",
  "DDMLatLongNotation": "Stupne desatinné minúty - Zemepisná šírka/dĺžka",
  "DDMLongLatNotation": "Stupne desatinné minúty - Zemepisná dĺžka/šírka",
  "DMSLatLongNotation": "Stupne minúty sekundy - Zemepisná šírka/dĺžka",
  "DMSLongLatNotation": "Stupné minúty sekundy - Zemepisná dĺžka/šírka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - znak pásma",
  "UTMHemNotation": "UTM - pologuľa (S/J)",
  "formatInput": "Formátovanie vstupu",
  "copyAll": "Kopírovať všetko",
  "copySuccessful": "Kopírovanie bolo úspešné",
  "copyFailed": "Kopírovanie nie je možné. Použite ctrl+c ako alternatívu.",
  "parseCoordinatesError": "Nie je možné interpretovať súradnice. Skontrolujte svoj vstup.",
  "comfirmInputNotation": "Potvrdiť zápis vstupu",
  "latLongWarningMessage": "Zistilo sa, že vstupná súradnica má predponu aj príponu pre zemepisnú šírku alebo dĺžku, vrátená súradnica je založená na predpone.",
  "inputLabel": "Vstup",
  "outputLabel": "Výstup",
  "cancelButtonLabel": "Zrušiť",
  "applyButtonLabel": "Použiť",
  "posNegPrefixLabel": "Pridať \"+/-\" predponu ku kladným a záporným číslam",
  "editCoordinateDialogTitle": "Nastaviť zápis formátu súradníc",
  "rememberDecisionLabel": "Zapamätať si moje rozhodnutie a znova sa nepýtať,<br/>",
  "coordinateInputLabel": "Zadajte súradnice alebo kliknite na mapu",
  "zoomLabel": "Priblíženie",
  "multipleNotationLabel": "nájdené zápisy, ktoré sa zhodujú s vaším vstupom. Prosím potvrďte, ktoré by ste chceli použiť:",
  "copyToClipboard": "Kopírovať do schránky",
  "formatOutput": "Formátovanie výstupu",
  "addNewNotation": "Pridať nový zápis",
  "notationAddedMessage": "Nový zápis pridaný",
  "addLabel": "Pridať",
  "removeCoordinate": "Odstrániť súradnice",
  "expandOutput": "Rozbaliť výstup",
  "latitudeLabel": "Zem. šírka",
  "longitudeLabel": "Zem. dĺžka",
  "quadrantLabel": "Kvadrant",
  "keyLabel": "Kľúč",
  "fifteenDegreeLabel": "15° štvorček",
  "oneDegreeLabel": "1° štvorček",
  "eastingLabel": "posun na východ",
  "northingLabel": "posun na server",
  "zoneLabel": "Zóna",
  "bandLabel": "Hemisféra",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Štvorcová mriežka",
  "hemisphereLabel": "Pologuľa",
  "addPointLabel": "Pridať bod"
});