define({
  "feedbackStyleLabel": "Estilo de comentarios de distancia y dirección",
  "showTabLabel": "Mostrar todas las pestañas",
  "tabErrorMessage": "Seleccione al menos una pestaña del grupo \"Estilo de comentarios de distancia y dirección\"",
  "lineLabel": "Línea",
  "circleLabel": "Círculo",
  "ellipseLabel": "Elipse",
  "ringsLabel": "Anillos",
  "transparency": "Transparencia",
  "operationalLineLayerSelectLabel": "Seleccionar una capa operativa de polilíneas para resultados de línea y anillos",
  "operationalPolygonLayerSelectLabel": "Seleccionar una capa operativa de polígonos para resultados de círculo y elipse",
  "helpIconPolylineTooltip": "La lista de capas operativas se rellena con las capas del mapa web actual que corresponden al tipo de geometría de polilínea.",
  "helpIconPolygonTooltip": "La lista de capas operativas se rellena con las capas del mapa web actual que corresponden al tipo de geometría de polígono.",
  "feedbackResultsLayerLabel": "Capa de resultados de comentarios de distancia y dirección",
  "editSymbologyHint": "Sugerencia: Haga clic en el icono de vista previa para editar la simbología",
  "feedbackTextColorLabel": "Color de texto de etiqueta de comentarios",
  "feedbackTextSizeLabel": "Tamaño de texto de etiqueta de comentarios",
  "previewLabel": "Previsualización",
  "lineSymbologyPopupTittle": "Simbología de línea",
  "circleSymbologyPopupTittle": "Simbología de círculo",
  "ellipseSymbologyPopupTittle": "Simbología de elipse",
  "ringSymbologyPopupTittle": "Simbología de anillos"
});