define({
  "_widgetLabel": "Ohuanalüüs",
  "threatAnalysisMainPageTitle": "Põhineb JCATi terrorismivastasel juhendil",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Sisendi asukoht",
  "interactive": "Interaktiivne",
  "fromCoord": "Fikseeritud koordinaat",
  "existingFeature": "Olemasolevatest objektidest",
  "threatAnalysisCoordInputLabel": "Ohu asukoht",
  "enterCoords": "Sisestage koordinaadid",
  "threatAddPointToolTip": "Lisa ohu asukoht",
  "threatDrawPointToolTip": "Klõpsake ohu asukoha lisamiseks",
  "threatType": "Ohu tüüp",
  "threatPlaceholder": "Ohu otsimiseks alustage tippimist",
  "zoneTypeLabel": "Tsooni tüüp",
  "feetLabel": "ft",
  "metersLabel": "m",
  "unitsLabel": "Ühikud",
  "threatGraphicLayer": "Ohu graafik",
  "style": "Laad",
  "settingsTitle": "Sätted",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Katkendlik",
    "esriSLSDashDot": "Katkendlik punktiga",
    "esriSLSDashDotDot": "Katkendlik kahe punktiga",
    "esriSLSDot": "Punktiir",
    "esriSLSLongDash": "Pikk katkendlik kriips",
    "esriSLSLongDashDot": "Pikk katkendlik kriips punktiga",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lühike katkendlik kriips",
    "esriSLSShortDashDot": "Lühike katkendlik kriips punktiga",
    "esriSLSShortDashDotDot": "Lühike katkendlik kriips kahe punktiga",
    "esriSLSShortDot": "Lühike punktiir",
    "esriSLSSolid": "Pidev"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Tagasi",
    "esriSFSCross": "Rist",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Edasi",
    "esriSFSHorizontal": "Horisontaalne",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Pidev",
    "esriSFSVertical": "Vertikaalne"
  },
  "resultsTitle": "Tulemused",
  "publishTABtn": "Avalda",
  "layerName": "Avaldatud kihi nimi",
  "invalidLayerName": "Kihi nimi tohib sisaldada ainult tähe- ja numbrimärke ning allkriipse",
  "missingLayerNameMessage": "Avaldamiseks peate esmalt sisestama sobiva kihinime",
  "publishingFailedLayerExists": "Avaldamine nurjus: objektiteenus nimega {0} on juba olemas. Vali mõne muu objekti nimi.",
  "checkService": "Kontrolli teenust: {0}",
  "createService": "Loo teenus: {0}",
  "unableToCreate": "Ei saa luua: {0}",
  "addToDefinition": "Lisa definitsiooni: {0}",
  "successfullyPublished": "Veebikiht on avaldatud",
  "successfullyAppended": "Uued objektid on lisatud veebikihti",
  "manageWebLayerText": "Halda veebikihti",
  "userRole": "Teenust ei saa luua, kuna kasutajal pole nõutavaid õigusi",
  "retrieveExistingLayerError": "{0} ei saa hankida. Avalda mõni muu kihi nimi.",
  "publishToNewLayer": "Avalda uue objektikihi tulemused",
  "layerNameExists": "Kihi nimi on juba olemas. Valige kihile mõni muu nimi.",
  "pipeBombLabel": "Torupomm",
  "suicideBombLabel": "Enesetapupomm",
  "briefcaseLabel": "Portfell",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Väike kaubaauto",
  "containerWaterTruckLabel": "Konteineriveok / veepaagiga veok",
  "semiTrailerLabel": "Poolhaagis",
  "transparencyLabel": "Läbipaistvus",
  "outline": "Äärejoon",
  "fill": "Täida (värv rakendatakse ainult juhul, kui valitud on pidev laad)",
  "createBtn": "Loo tsoonid",
  "clearBtn": "Tühista",
  "invalidNumberMessage": "Sisestatud väärtus ei sobi",
  "invalidRangeMessage": "Väärtus peab olema suurem kui 0",
  "parseCoordinatesError": "Koordinaate ei saa parsida. Kontrollige sisestatud teavet.",
  "selectDrawModeLabel": "Valige joonistusrežiim",
  "selectFeatureLabel": "Valige objekt sellest kihist",
  "smallLPGTank": "Väike LPG paak",
  "largeLPGTank": "Suur LPG paak",
  "commercialResidentialLPGTank": "Äriline/elamu LPG paak",
  "smallLPGTruck": "Väike LPG veok",
  "semiTankerLPG": "Poolhaagisega LPG tsisternveok",
  "zoneDescriptionColLabel": "Tsooni kirjeldus",
  "distanceColLabel": "Vahemaa",
  "zoneDescColLabel": "Tsooni kirjeldus",
  "descriptionLabel": "Kirjeldus",
  "editThreatZonePopupLabel": "Muuda ohutsooni sümboloogiat",
  "symbologyColLabel": "Sümboloogia",
  "actions": "Toimingud",
  "threatTypeSelectLabel": "Valige ohu tüüp:",
  "distanceLabel": "Kaugus (${unitAbbr})",
  "layerCountHint": "Vihje. Avaldatakse objektikihiga/objektikihtidega ${layerCount} veebikiht.",
  "selectLabel": "Vali",
  "mandatoryLabel": "Kohustuslik evakueerimise kaugus",
  "safeLabel": "Ohutu evakueerimise kaugus",
  "fireBallDiameterLable": "Tulekera läbimõõt",
  "lpgSafeDistanceLable": "Ohutu vahemaa"
});