define({
  "addLayer": "Добавяне на слой",
  "layerName": "Слой",
  "layerRefresh": "Обновяване",
  "layerLabel": "Етикет",
  "actions": "Действия",
  "mainPanelTextPlaceholder": "пример: Последно обновени:",
  "invalidInterval": "Позволение са само положителни цели числа",
  "uploadImage": "Качване на изображение",
  "iconColumnText": "Показване",
  "refreshInterval": "Време в минути",
  "refreshIntervalTitle": "Оценено като време в минути",
  "mainPanelText": "Текст на основния панел",
  "mainPanelIcon": "Изображение на основния панел",
  "refreshIntervalInstruction": "Опресняване на слоевете на всеки:",
  "optionsText": "Опции",
  "symbolOptionsText": "Симвология на карта",
  "iconOptionsText": "Симвология на панел",
  "sympolPopupTitle": "Настройки за показване",
  "rdoLayer": "Стандартен символ",
  "rdoCustom": "Използване на изображение",
  "chkCluster": "Активиране на групиране по общ признак",
  "defineClusterSymbol": "Посочете символ на клъстера",
  "rdoEsri": "Избор на символ",
  "rdoLayerIcon": "Използване на символ на картата",
  "rdoCustomIcon": "Използване на изображение",
  "editCustomSymbol": "Редактиране на потребителски символ",
  "editCustomIcon": "Редактиране на потребителска икона",
  "missingRefreshValue": "Моля, посочете обновена стойност на интервал за обновяване.",
  "panelIconOption": "Показване на изображение на логото",
  "enableRefresh": "Активиране на обновяване на слой",
  "disableRefresh": "Опресняването на слоевете се поддържа само за колекции от обекти.",
  "refreshUnit": "минути.",
  "symbolOptions": "Символ",
  "panelFeatureDisplay": "Панел",
  "chkGroup": "Група обекти",
  "selectField": "Поле",
  "fieldLabel": "Етикет",
  "addField": "Добавяне на поле",
  "featureOptionsText": "Опции за слой",
  "groupOptionsText": "Опции за група",
  "panelCountOption": "Брой на показваните обекти",
  "missingLayerInWebMap": "Няма намерени оперативни слоеве.",
  "displayClusterCnt": "Брой на показваните обекти",
  "defineClusterFont": "Посочете цвят на шрифта",
  "max_records": "Достигнат е максималният лимит за поле",
  "hidePanel": "Скриване на панела",
  "hidePanelHelp": "Активиране/деактивиране на показването на основния панел.",
  "continuousRefreshHelp": "Забележка: Обновяването на колекцията от обекти ще се извършва непрекъснато.",
  "panelCountOptionHelp": "Активиране/деактивиране на показването на брой обекти.",
  "panelIconOptionHelp": "Активиране/деактивиране на показването на логото на основния панел.",
  "rdoGroupByField": "по поле",
  "rdoGroupByRenderer": "по генериране на цифрово изображение",
  "expandList": "Разширен списък при стартиране",
  "expandListHelp": "Активиране/деактивиране на стандартно разширение на списъка.",
  "chkFeatureDisplay": "Деактивиране на списък с обекти",
  "showAllFeaturesHelp": "Активиране/деактивиране на показването на всички обекти, независимо от ограничаващия правоъгълник.",
  "showAllFeatures": "Показване на всички обекти",
  "fieldsWarning": "В изскачащия прозорец няма определени полета. Опционално: Използвайте действието за редактиране, за да определите опциите за показване на панела.",
  "displayClusterLayer": "Запазване на символите на клъстерите след затваряне на изпълнимия модул",
  "invalidSymbolWidthMessage": "Изборът на символи съдържа грешка, моля, поправете я, преди да използвате.",
  "sortLabel": "Сортиране",
  "ascRadioBtnLabel": "Възходящ",
  "descRadioBtnLabel": "Низходящ"
});