define({
  "_widgetLabel": "Batchattributredigeraren",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Lagernamn",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Inga redigerbara lager har konfigurerats",
  "editorPopupTitle": "Batchattributredigeraren",
  "editorPopupSaveBtn": "Spara",
  "editorPopupMultipleValues": "",
  "clear": "Rensa",
  "featuresUpdated": "${0}/${1} geoobjekt har uppdaterats",
  "featuresSelected": "${0} geoobjekt har markerats",
  "featuresSkipped": "Har kringgåtts",
  "featuresNoPermision": "${0} geoobjekt har valts men ingen behörighet att redigera.",
  "search": "Sök",
  "queryInput": "Ange ett värde för en fråga",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Ange filtret korrekt.",
  "filterPopup": "Filtrera lager",
  "filterAppend": "Om filtret redan finns i webbkartan för det här lagret.",
  "filterAppendOR": "Bifoga ett eller flera uttryck till befintligt kartfilter",
  "filterAppendAND": "Bifoga alla uttryck till befintligt kartfilter",
  "cancel": "Avbryt",
  "noValue": "Inget värde",
  "emptyString": "Tom sträng",
  "existingValue": "Behåll befintligt värde",
  "newDate": "Nytt datum",
  "valueChooser": "Välj/skriv ett värde",
  "ok": "OK",
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihandspolylinje",
    "extent": "Utbredning",
    "polygon": "Polygon",
    "freehandPolygon": "Frihandspolygon",
    "clear": "Rensa",
    "addPointToolTip": "Klicka om du vill markera området",
    "addShapeToolTip": "Markera geoobjekt genom att rita en form",
    "freehandToolTip": "Rita en form för att markera geoobjekt genom att trycka",
    "startToolTip": "Markera geoobjekt genom att rita en form"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Geoobjektet från ${0} returnerade ett ogiltigt ID",
    "noSelectedLayers": "Inga markerade lager har poster att uppdatera",
    "inputValueError": "Ogiltigt värde i formuläret",
    "saveError": "Det gick inte att spara ${0} geoobjekt",
    "requiredValue": "Obligatoriskt värde"
  }
});