define({
  "_widgetLabel": "Умный редактор",
  "_featureAction_SmartEditor": "Умный редактор",
  "noEditPrivileges": "У вашей учетной записи нет прав на создание или изменение данных.",
  "loginPopupTitle": "Вход",
  "loginPopupMessage": "Для ${widgetName} необходимы права доступа и кредиты для поиска и хранения адресной информации. Хотите войти в систему и использовать эту возможность?",
  "noCreditsOrPrivilegeWarningMessage": "У вашей учетной записи нет прав и кредитов для поиска и хранения адресной информации с помощью ${widgetName}. Обратитесь к администратору организации , чтобы запросить права доступа и кредиты. Щелкните ОК, чтобы продолжить редактирование.",
  "unableToUseLocator": "Локатор не доступен. Действия атрибута адреса не будут выполнены. Щелкните ОК, чтобы продолжить редактирование.",
  "locatorDisabledWaning": "Локатор не включен. Обратитесь к администратору организации , чтобы запросить эту возможность. Щелкните ОК, чтобы продолжить редактирование.",
  "noFeatureInAIWarning": "Объекты не выбраны. Выберите объект для выполнения редактирования или щелкните Отмена, чтобы вернуться на главный экран.",
  "noEditableLayerWarning": "У вашей учетной записи нет прав на создание или изменение данных, или на этой веб-карте нет слоев, доступных для редактирования.",
  "noVisibleCreateLayerWarning": "Слои не видны при текущем уровне масштабирования. Увеличьте или уменьшите масштаб для создания/изменения объектов.",
  "noVisibleUpdateLayerWarning": "Слои не видны при текущем уровне масштабирования. Увеличьте или уменьшите масштаб для изменения объектов.",
  "checkLayerVisibilityInWebMapWarning": "Убедитесь, что слои видимы на карте, чтобы создавать или изменять объекты.",
  "showSelectionInAITitle": "Выбранные объекты",
  "showSelectionInAIMsg": "Вы хотите загрузить текущую выборку в ${widgetName}?",
  "widgetActive": "Активный",
  "widgetNotActive": "Неактивно",
  "pressStr": "Нажмите ",
  "ctrlStr": " CTRL ",
  "snapStr": " чтобы включить замыкание",
  "noAvailableTempaltes": "Нет доступных шаблонов",
  "editorCache": " – Кэш редактора",
  "presetFieldAlias": "Поле",
  "presetValue": "Заданное значение",
  "usePresetValues": " Использовать заданные ранее значения (только новые объекты)",
  "editGeometry": " Редактировать геометрию",
  "savePromptTitle": "Сохранить объект",
  "savePrompt": "Вы хотите сохранить текущий объект?",
  "deletePromptTitle": "Удалить объект",
  "deleteAttachment": "Удалить вложение",
  "deletePrompt": "Действительно удалить выбранный объект?",
  "attachmentLoadingError": "Ошибка загрузки вложений",
  "attachmentSaveDeleteWarning": "Внимание: изменения вложений сохраняются автоматически",
  "autoSaveEdits": "Сохранить новые объекты автоматически",
  "addNewFeature": "Создать новый объект",
  "featureCreationFailedMsg": "Невозможно создать новую запись/объект",
  "relatedItemTitle": "Связанная таблица/слой",
  "relatedFeatureCount": "${layerTitle} с ${featureCount} объектами",
  "createNewFeatureLabel": "Создать новый объект для ${layerTitle}",
  "invalidRelationShipMsg": "Проверьте, что поле первичного ключа: '${parentKeyField}' имеет корректное значение",
  "pendingFeatureSaveMsg": "Сохраните изменения объекта для создания связанного объекта.",
  "attachmentsRequiredMsg": "(*) Необходимы вложения.",
  "coordinatePopupTitle": "Переместить объект в местоположение XY",
  "coordinatesSelectTitle": "Система координат:",
  "mapSpecialReferenceDropdownOption": "Пространственная привязка карты",
  "latLongDropdownOption": "Широта/Долгота",
  "mgrsDropdownOption": "Военная система прямоугольных координат (MGRS)",
  "mgrsTextBoxLabel": "Координата:",
  "xAttributeTextBoxLabel": "X-координата:",
  "yAttributeTextBoxLabel": "Y-координата:",
  "latitudeTextBoxLabel": "Широта:",
  "longitudeTextBoxLabel": "Долгота:",
  "presetGroupFieldsLabel": "'${groupName}' будет применено к следующим полям слоя:",
  "presetGroupNoFieldsLabel": "'${groupName}' не содержит связанных полей",
  "groupInfoLabel": "Информация по группе '${groupName}'",
  "editGroupInfoIcon": "Изменить значение группы ${groupName}",
  "filterEditor": {
    "all": "Все",
    "noAvailableTempaltes": "Нет доступных шаблонов",
    "searchTemplates": "Поиск шаблонов",
    "filterLayerLabel": "Отобрать слои"
  },
  "invalidConfiguration": "Виджет не настроен, или на карте больше нет слоёв из конфигурации. Откройте приложение в режиме конструктора и настройте виджет.",
  "geometryServiceURLNotFoundMSG": "Невозможно получить URL сервиса геометрии",
  "clearSelection": "Закрыть",
  "refreshAttributes": "Динамически обновлять атрибуты объектов",
  "automaticAttributeUpdatesOn": "Автоматически обновлять атрибуты объекта: ВКЛ",
  "automaticAttributeUpdatesOff": "Автоматически обновлять атрибуты объекта: ВЫКЛ",
  "moveSelectedFeatureToGPS": "Переместить выбранный объект в текущее местоположение GPS",
  "moveSelectedFeatureToXY": "Переместить выбранный объект в местоположение XY",
  "mapNavigationLocked": "Навигация по карте: Блокирована",
  "mapNavigationUnLocked": "Навигация по карте: Разблокирована",
  "copyFeatures": {
    "title": "Выбрать объекты для копирования",
    "createFeatures": "Создать объекты",
    "createSingleFeature": "Создать 1 составной объект",
    "createOneSingleFeature": "Создать объект",
    "noFeaturesSelectedMessage": "Объекты не выбраны",
    "selectFeatureToCopyMessage": "Выберите объекты для копирования",
    "multipleFeatureSaveWarning": "Создание нескольких объектов с помощью этой функции приведет к немедленному сохранению всех новых объектов. Сопоставление полей не поддерживается при создании нового составного объекта.",
    "copyFeatureUpdateGeometryError": "Не удалось обновить геометрию выбранных объектов",
    "canNotSaveMultipleFeatureWarning": "Вы можете скопировать только один объект, если целевой точечный слой имеет уникальные поля значений.",
    "createOnlyOneMultipartFeatureWarning": "Вы можете скопировать только один объект или создать один объект, состоящий из нескольких частей, если целевой слой имеет уникальные поля значений.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} из ${totalFeatures} объектов выбрано"
  },
  "addingFeatureError": "Ошибка при добавлении выбранных объектов в слое. Повторите попытку еще раз.",
  "addingFeatureErrorCount": "Не удалось скопировать объектов: '${copyFeatureErrorCount}' Хотите повторить попытку для пропущенных объектов?",
  "selectingFeatureError": "Ошибка при выборке объектов в слое. Повторите попытку еще раз.",
  "customSelectOptionLabel": "Выбрать объекты для копирования",
  "copyFeaturesWithPolygon": "Копировать полигоном",
  "copyFeaturesWithRect": "Копировать прямоугольником",
  "copyFeaturesWithLasso": "Копировать лассо",
  "noFeatureSelectedMessage": "Объекты не выбраны.",
  "multipleFeatureSaveMessage": "Все объекты будут сразу же сохранены. Продолжить?",
  "relativeDates": {
    "dateTypeLabel": "Тип даты",
    "valueLabel": "Значение",
    "fixed": "Фиксированный",
    "current": "Текущий",
    "past": "Прошедшие",
    "future": "Будущее",
    "popupTitle": "Выберите значение",
    "hintForFixedDateType": "Подсказка: указанные время и дата будут использованы как значения по умолчанию.",
    "hintForCurrentDateType": "Подсказка: текущие время и дата будут использованы как значения по умолчанию.",
    "hintForPastDateType": "Подсказка: указанное значение будет вычтено из текущего времени и даты для задания значения по умолчанию.",
    "hintForFutureDateType": "Подсказка: указанное значение будет добавлено к текущему времени и дате для задания значения по умолчанию.",
    "noDateDefinedTooltip": "Дата не задана",
    "relativeDateWarning": "Для сохранения заданного значения по умолчанию необходимо указать значение даты или времени.",
    "customLabel": "Пользовательский",
    "layerLabel": "Слой",
    "domainFieldHintLabel": "Выбранное значение принадлежит домену кодированных значений Будет использовано значение \"${domainValue}\""
  },
  "valuePicker": {
    "popupTitle": "Выберите значение",
    "popupHint": "Текущий объект пересекается с несколькими объектами, выберите значение для соответствующего поля",
    "buttonTooltip": "Выберите значение из нескольких пересекающихся объектов"
  },
  "uniqueValueErrorMessage": "Значение в \"${fieldName}\" уже существует, введите новое значение.",
  "requiredFields": {
    "displayMsg": "Обязательные поля не могут быть пустыми. Укажите значения для общих полей ниже",
    "popupTittle": "Обязательные поля",
    "foundNullRecordCount": "${fieldName} (Найдено в ${count} записях)"
  },
  "fieldsMapping": {
    "popupTittle": "Применить сопоставление полей",
    "fieldsMatchingCheckboxLabel": "Значения из скопированных объектов переопределят значения в целевых полях по умолчанию в шаблоне",
    "resetLabel": "Сбросить",
    "clearLabel": "Очистить",
    "fieldsInTargetLayerLabel": "Цель",
    "fieldsInSourceLayerLabel": "Источник",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} полей сопоставлено)",
    "selectSourceFieldLabel": "- Выбрать -",
    "selectFieldAriaLabel": "Выберите поле источника для целевого поля ${targetField}",
    "informativeText": "Просмотрите сопоставление исходных и целевых полей и измените его, если необходимо.",
    "dynamicValueText": "Задано динамическое значение",
    "noFieldsToMatchLabel": "Нет полей для сопоставления"
  },
  "cantLocateUserLocation": "Ваше местоположение невозможно определить",
  "tryAgainButtonLabel": "Попробуйте еще раз",
  "copyFeatureFailedPopupTitle": "Ой!"
});