define({
  "taskUrl": "URL dels servei de conca visual",
  "portalURL": "Especifiqueu l'adreça URL de la vostra organització de l'ArcGIS Online o del component Portal for ArcGIS.",
  "portalURLError": "La URL configurada per a la vostra organització de l'ArcGIS Online o el Portal for ArcGIS no és vàlida.",
  "privilegeError": "El vostre rol d'usuari no pot executar l'anàlisi. Per poder-lo executar, l'administrador de l'organització us ha d'atorgar uns <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">permisos</a> determinats.",
  "noServiceError": "El servei d'anàlisi d'elevació no està disponible. Consulteu les configuracions de la vostra organització de l'ArcGIS Online o del Portal for ArcGIS.",
  "maximumRangeMessage": "L'interval observable màxim ha de ser més gran que l'interval observable mínim i no pot ser de més de ${limit} ${units}.",
  "serviceURLPlaceholder": "Introduïu la URL de la tasca de geoprocessament de conca visual",
  "setTask": "Defineix",
  "setTaskTitle": "Defineix la tasca de geoprocessament de conca visual",
  "serviceURLError": "La tasca de geoprocessament que intenteu configurar amb aquest widget no és vàlida. Seleccioneu una URL de la tasca de geoprocessament de conca visual vàlida",
  "defaultMilsForAnglesLabel": "Definiu els mil·liradians dels angles com a valor per defecte",
  "defaultObserverHeightLabel": "Unitat d'altura de l'observador per defecte",
  "defaultObservableDistanceLabel": "Unitat de distància observable per defecte",
  "defaultObserveHeightLabel": "Altura de l'observador per defecte",
  "defaultMinimumObservableDistanceLabel": "Distància observable mínima per defecte",
  "defaultMaximumObservableDistanceLabel": "Distància observable màxima per defecte",
  "units": {
    "miles": "Milles",
    "kilometers": "Quilòmetres",
    "feet": "Peus",
    "meters": "Metres",
    "yards": "Iardes",
    "nauticalMiles": "Milles nàutiques"
  },
  "helpIconTooltip": "La llista de capes operatives s'emplena amb capes del mapa web actual amb el tipus de geometria de polígon.",
  "selectOperationalLayerLabel": "Seleccioneu una capa operativa per als resultats",
  "lineOfSightTabTitle": "Línea de visión",
  "symbologyTabTitle": "Simbologia",
  "transparency": "Transparència",
  "outline": "Contorn",
  "fill": "Emplenament (el color només s'aplica quan l'estil està definit com a sòlid)",
  "style": "Estil",
  "selectOpLayerLabel": "Seleccioneu una capa operativa per als resultats",
  "selectDefaultMeasurementLabel": "Seleccioneu una unitat de mesura per defecte",
  "visibleSectionLabel": "Secció visible",
  "nonVisibleSectionLabel": "Secció no visible",
  "visibleSectionButtonLabel": "Configura la secció visible",
  "nonVisibleSectionButtonLabel": "Configura la secció no visible",
  "colorPicker": "Selector de color",
  "lineStyles": {
    "esriSLSDash": "Guió",
    "esriSLSDashDot": "Guió punt",
    "esriSLSDashDotDot": "Guió punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Guió llarg",
    "esriSLSLongDashDot": "Guió llarg punt",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Guió curt",
    "esriSLSShortDashDot": "Guió curt punt",
    "esriSLSShortDashDotDot": "Guió curt punt punt",
    "esriSLSShortDot": "Punt",
    "esriSLSSolid": "Sòlid"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Enrere",
    "esriSFSCross": "Creu",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Endavant",
    "esriSFSHorizontal": "Horitzontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Sòlid",
    "esriSFSVertical": "Vertical"
  }
});