define({
  "_widgetLabel": "Akıllı Düzenleyici",
  "_featureAction_SmartEditor": "Akıllı Düzenleyici",
  "noEditPrivileges": "Hesabınızın veri oluşturma veya değiştirme izni yok.",
  "loginPopupTitle": "Oturum Aç",
  "loginPopupMessage": "${widgetName}, adres bilgilerinin aranması ve saklanması için izinler ve krediler gerektirir. Bu özelliği kullanmak için oturum açmak ister misiniz?",
  "noCreditsOrPrivilegeWarningMessage": "Hesabınız, ${widgetName} ile adres bilgilerini aramak ve saklamak için gerekli izinlere ve kredilere sahip değil. İzin ve kredi istemek için lütfen kuruluş yöneticinizle iletişime geçin. Düzenlemeye devam etmek için Tamam ögesine tıklayın.",
  "unableToUseLocator": "Konumlandırıcıya erişilemiyor. Adres öznitelik eylemi/eylemleri gerçekleştirilmeyecek. Düzenlemeye devam etmek için Tamam ögesine tıklayın.",
  "locatorDisabledWaning": "Konumlandırıcı etkin değil. Bu özelliği talep etmek için lütfen kuruluş yöneticinizle iletişime geçin. Düzenlemeye devam etmek için Tamam ögesine tıklayın.",
  "noFeatureInAIWarning": "Hiç detay seçilmedi. Lütfen düzenlemeleri gerçekleştirmek için bir detay seçin veya ana ekrana dönmek için İptal'e tıklayın.",
  "noEditableLayerWarning": "Hesabınız veri oluşturmak ya da değiştirmek için gerekli izne sahip değil veya bu web haritası düzenlenebilir katman içermiyor.",
  "noVisibleCreateLayerWarning": "Katmanlar mevcut yakınlaştırma seviyesinde görünür değil. Detay oluşturmak/değiştirmek için yakınlaştırın veya uzaklaştırın.",
  "noVisibleUpdateLayerWarning": "Katmanlar mevcut yakınlaştırma seviyesinde görünür değil. Detayları değiştirmek için yakınlaştırın veya uzaklaştırın.",
  "checkLayerVisibilityInWebMapWarning": "Detay oluşturmak veya detayları değiştirmek için katmanların haritada görünür olduğundan emin olun.",
  "showSelectionInAITitle": "Seçili Detaylar",
  "showSelectionInAIMsg": "Mevcut seçimi ${widgetName}'e yüklemek istiyor musunuz?",
  "widgetActive": "Etkin",
  "widgetNotActive": "Etkin Değil",
  "pressStr": "Basılacak Tuş ",
  "ctrlStr": " CTRL ",
  "snapStr": " yakalamayı etkinleştirmek için",
  "noAvailableTempaltes": "Kullanılabilir şablon yok",
  "editorCache": " - Düzenleyici Önbelleği",
  "presetFieldAlias": "Alan",
  "presetValue": "Ön Ayar Değeri",
  "usePresetValues": " Ön ayar değerlerini kullan (yalnızca yeni detaylar)",
  "editGeometry": " Geometriyi Düzenle",
  "savePromptTitle": "Detayı kaydet",
  "savePrompt": "Geçerli detayı kaydetmek ister misiniz?",
  "deletePromptTitle": "Detayı sil",
  "deleteAttachment": "Eki sil",
  "deletePrompt": "Seçili detayı silmek istediğinizden emin misiniz?",
  "attachmentLoadingError": "Ek yükleme hatası",
  "attachmentSaveDeleteWarning": "Uyarı: Ekler üzerinde yapılan değişiklikler otomatik olarak kaydedilir",
  "autoSaveEdits": "Yeni detayları otomatik olarak kaydet",
  "addNewFeature": "Yeni detay oluştur",
  "featureCreationFailedMsg": "Yeni bir kayıt/detay oluşturulamıyor",
  "relatedItemTitle": "İlgili Tablo/Katman",
  "relatedFeatureCount": "${featureCount} detayları ile ${layerTitle}",
  "createNewFeatureLabel": "${layerTitle} için yeni detay oluştur",
  "invalidRelationShipMsg": "Lütfen ‘${parentKeyField}’ birincil anahtar alanda geçerli bir değer bulunduğundan emin olun",
  "pendingFeatureSaveMsg": "Lütfen ilgili bir detay oluşturmadan önce detay düzenlemelerini kaydedin.",
  "attachmentsRequiredMsg": "(*) Ekler gereklidir.",
  "coordinatePopupTitle": "Detayı XY konumuna taşı",
  "coordinatesSelectTitle": "Koordinat Sistemi:",
  "mapSpecialReferenceDropdownOption": "Harita Mekansal Referansı",
  "latLongDropdownOption": "Enlem/Boylam",
  "mgrsDropdownOption": "Askeri Kafes Başvuru Sistemi (MGRS)",
  "mgrsTextBoxLabel": "Koordinat:",
  "xAttributeTextBoxLabel": "X koordinatı:",
  "yAttributeTextBoxLabel": "Y koordinatı:",
  "latitudeTextBoxLabel": "Enlem:",
  "longitudeTextBoxLabel": "Boylam:",
  "presetGroupFieldsLabel": "'${groupName}' şu katman alanlarına uygulanacaktır:",
  "presetGroupNoFieldsLabel": "'${groupName}' ile ilişkili alan yok",
  "groupInfoLabel": "'${groupName}’ için grup bilgisi",
  "editGroupInfoIcon": "${groupName} için grup değerini düzenle",
  "filterEditor": {
    "all": "Tümü",
    "noAvailableTempaltes": "Kullanılabilir şablon yok",
    "searchTemplates": "Şablon Ara",
    "filterLayerLabel": "Katmanları filtrele"
  },
  "invalidConfiguration": "Araç yapılandırılmamış veya yapılandırmadaki katmanlar artık haritada değil. Uygulamayı oluşturucu modda açın ve aracı yeniden yapılandırın.",
  "geometryServiceURLNotFoundMSG": "Geometri Servisi URL’si alınamıyor",
  "clearSelection": "Kapat",
  "refreshAttributes": "Dinamik detay özniteliklerini güncelle",
  "automaticAttributeUpdatesOn": "Detay özniteliklerini otomatik olarak güncelleme: AÇIK",
  "automaticAttributeUpdatesOff": "Detay özniteliklerini otomatik olarak güncelleme: KAPALI",
  "moveSelectedFeatureToGPS": "Seçilen detayı mevcut GPS konumuna taşı",
  "moveSelectedFeatureToXY": "Seçilen detayı XY konumuna taşı",
  "mapNavigationLocked": "Haritada Gezinme: Kilitli",
  "mapNavigationUnLocked": "Haritada Gezinme: Açık",
  "copyFeatures": {
    "title": "Kopyalanacak detayları seç",
    "createFeatures": "Detay Oluştur",
    "createSingleFeature": "1 Çok Parçalı Detay Oluştur",
    "createOneSingleFeature": "Detay Oluştur",
    "noFeaturesSelectedMessage": "Seçili Detay Yok",
    "selectFeatureToCopyMessage": "Lütfen kopyalanacak detayları seçin",
    "multipleFeatureSaveWarning": "Bu işlevselliği kullanarak birden fazla detay oluşturmak, tüm detayları anında kaydeder Yeni bir çok parçalı detay oluştururken alan eşleştirme desteklenmez.",
    "copyFeatureUpdateGeometryError": "Seçilen detayların geometrisi güncellenemedi",
    "canNotSaveMultipleFeatureWarning": "Hedef nokta katmanında benzersiz değer alanları olduğunda yalnızca bir detayı kopyalayabilirsiniz.",
    "createOnlyOneMultipartFeatureWarning": "Hedef katmanda benzersiz değer alanları olduğunda yalnızca bir detayı kopyalayabilir veya çok parçalı bir detay oluşturabilirsiniz.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} / ${totalFeatures} detay seçildi"
  },
  "addingFeatureError": "Seçilen detaylar katmana eklenirken hata oluştu. Yeniden deneyin.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' detay kopyalanamadı. Eksik detaylar için tekrar denemek ister misiniz?",
  "selectingFeatureError": "Katmanda detaylar seçilirken hata oluştu. Yeniden deneyin.",
  "customSelectOptionLabel": "Kopyalanacak detayları seç",
  "copyFeaturesWithPolygon": "Çokgenle kopyala",
  "copyFeaturesWithRect": "Dikdörtgenle kopyala",
  "copyFeaturesWithLasso": "Serbest şekille kopyala",
  "noFeatureSelectedMessage": "Hiç detay seçilmedi",
  "multipleFeatureSaveMessage": "Tüm detaylar hemen kaydedilir. Devam etmek istiyor musunuz?",
  "relativeDates": {
    "dateTypeLabel": "Tarih Türü",
    "valueLabel": "Değer",
    "fixed": "Sabit",
    "current": "Geçerli",
    "past": "Geçmiş",
    "future": "Gelecek",
    "popupTitle": "Değer Seç",
    "hintForFixedDateType": "İpucu: Belirtilen tarih ve saat önceden ayarlanmış varsayılan değer olarak kullanılacaktır.",
    "hintForCurrentDateType": "İpucu: Geçerli tarih ve saat önceden ayarlanmış varsayılan değer olarak kullanılacaktır.",
    "hintForPastDateType": "İpucu: Belirtilen değer, ön ayarın varsayılan değeri için geçerli tarih ve saatten çıkarılacaktır.",
    "hintForFutureDateType": "İpucu: Belirtilen değer, ön ayarın varsayılan değeri için geçerli tarih ve saatine eklenecektir.",
    "noDateDefinedTooltip": "Tanımlanmış tarih yok",
    "relativeDateWarning": "Önceden ayarlanmış varsayılan değeri kaydedebilmek için tarih veya saat için bir değer belirtilmelidir.",
    "customLabel": "Özel",
    "layerLabel": "Katman",
    "domainFieldHintLabel": "Seçilen değer kodlu değer domainidir. Değer: \"${domainValue}\" kullanılacak"
  },
  "valuePicker": {
    "popupTitle": "Değer Seç",
    "popupHint": "Mevcut detay birden fazla detayla kesişiyor; ilgili alan için değer seçin",
    "buttonTooltip": "Çoklu kesişen detaylardan değer seçin"
  },
  "uniqueValueErrorMessage": "\"${fieldName}\" içindeki değer zaten var; lütfen yeni bir değer girin.",
  "requiredFields": {
    "displayMsg": "Zorunlu alanlar boş olamaz. Aşağıdaki ortak alanlara değerler sağlayın.",
    "popupTittle": "Zorunlu alanlar",
    "foundNullRecordCount": "${fieldName} (${count} kayıtta bulundu)"
  },
  "fieldsMapping": {
    "popupTittle": "Alan Eşleştirme Uygulayın",
    "fieldsMatchingCheckboxLabel": "Kopyalanan detayların değerleri hedef alandaki varsayılan değeri geçersiz kılar",
    "resetLabel": "Sıfırla",
    "clearLabel": "Temizle",
    "fieldsInTargetLayerLabel": "Hedef",
    "fieldsInSourceLayerLabel": "Kaynak",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} alanlar eşleşti)",
    "selectSourceFieldLabel": "- Seç -",
    "selectFieldAriaLabel": "Hedef alanı ${targetField} için kaynak alanı seç",
    "informativeText": "Kaynaktan hedefe eşleşen alanları gözden geçirin ve gerekirse özelleştirin.",
    "dynamicValueText": "Dinamik bir değer ayarlandı",
    "noFieldsToMatchLabel": "Eşleşecek alan yok"
  },
  "cantLocateUserLocation": "Konumunuz belirlenemedi",
  "tryAgainButtonLabel": "Yeniden dene",
  "copyFeatureFailedPopupTitle": "Hay aksi!"
});