define({
  "taskUrl": "งาน URL",
  "setTask": "ตั้ง",
  "setTaskPopupTitle": "ตั้งค่างาน",
  "validate": "ตั้ง",
  "inValidGPService": "โปรดป้อนเซอร์วิสการประมวลผลข้อมูลทางภูมิศาสตร์ที่ใช้งานได้",
  "noOutputParameterWithGeometryType": "เซอร์วิสการประมวลผลข้อมูลทางภูมิศาสตร์ จะต้องมีอย่างน้อยหนึ่งพารามิเตอร์เอาท์พุทที่มีประเภทรูปทรงเรขาคณิตที่กำหนด โปรดเลือกเซอร์วิสการประมวลผลข้อมูลทางภูมิศาสตร์อื่น",
  "invalidOutputGeometry": "ประเภทรูปทรงเรขาคณิตเอาท์พุทของเซอร์วิสการประมวลผลข้อมูลทางภูมิศาสตร์ที่เลือก ไม่สามารถทำงานร่วมกับการตั้งค่าโปรเจคได้ ไม่สามารถจัดเก็บผลของเซอร์วิสการประมวลผลข้อมูลทางภูมิศาสตร์ได้",
  "GPFeatureRecordSetLayerERR": "โปรดป้อนเซอร์วิสการประมวลผลข้อมูลทางภูมิศาสตร์ โดยใช้อินพุทประเภท 'GPFeatureRecordSetLayer' เท่านั้น",
  "invalidInputParameters": "จำนวนอินพุทพารามิเตอร์น้อยกว่า 1 หรือมากกว่า 3 โปรดป้อนเซอร์วิสการประมวลผลข้อมูลทางภูมิศาสตร์ที่ใช้งานได้",
  "projectSetting": {
    "title": "การตั้งค่าโปรเจค",
    "note": "หมายเหตุ: การตั้งค่าโปรเจคเป็นทางเลือก เมื่อกำหนดค่าแล้ว ผู้ใช้จะสามารถจัดเก็บโปรเจคไว้ในชั้นข้อมูลเว็บแมปที่ต้องการ พร้อมเครือข่ายพื้นที่ไฟดับและอินพุทพารามิเตอร์ ผู้ใช้สามารถจัดเก็บพารามิเตอร์เอาท์พุทได้จากแท็บ 'เอาท์พุท'",
    "projectPolygonLayer": "ชั้นข้อมูลโพลีกอนโปรเจค",
    "outputParameterName": "ชื่อพารามิเตอร์เอาท์พุท",
    "projectPointLayer": "ชั้นข้อมูลจุดโปรเจค",
    "selectLabel": "เลือก",
    "polygonLayerHelp": "<p>ชั้นข้อมูลโพลีกอนตามเงื่อนไขต่อไปนี้จะปรากฏขึ้น:<br/><ul><li>ชั้นข้อมูลจะต้องมีความสามารถในการแก้ไข ที่ชื่อ 'สร้าง', 'ลบ' และ 'อัพเดต'</li><li>ชั้นข้อมูลจะต้องมี 2 ฟิลด์ที่มีชื่อและประเภทข้อมูลตรงกัน:</li><ul><li>name (ฟิลด์ประเภทสตริง)</li><li>globalid (ฟิลด์ประเภท GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>เอาท์พุทชั้นข้อมูลโพลีกอนจาก URL งานจะปรากฏขึ้น<p/>",
    "pointLayerHelp": "<p>ชั้นข้อมูลจุดตามเงื่อนไขต่อไปนี้จะปรากฏขึ้น: <br/><ul><li>ชั้นข้อมูลจะต้องมีความสามารถในการแก้ไข ที่ชื่อ 'สร้าง', 'ลบ' และ 'อัพเดต'</li><li>ชั้นข้อมูลจะต้องมี 2 ฟิลด์ที่มีชื่อและประเภทข้อมูลตรงกัน:</li><ul><li>inputtype (ฟิลด์ประเภทสตริง)</li><li>projectid (ฟิลด์ประเภท GUID)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "ธง",
    "barrier": "อุปสรรค",
    "skip": "ข้ามไป",
    "title": "ข้อมูลนำเข้า",
    "inputTooltip": "คำแนะนำการใช้เครื่องมือ",
    "typeText": "ชนิด",
    "symbol": "สัญลักษณ์",
    "summaryEditorText": "ข้อความสรุป",
    "summaryTextTitle": "กำหนดข้อความที่จะแสดงผลสำหรับแท็บอินพุท"
  },
  "summaryTab": {
    "title": "ผลลัพธ์",
    "summaryFieldsetText": "การตั้งค่าสรุป",
    "inputOutput": "อินพุท / เอาท์พุท",
    "field": "ฟิลด์",
    "operator": "ผู้ปฏิบัติการ",
    "inputOperatorCountOption": "นับ",
    "outputOperatorCountOption": "นับ",
    "outputOperatorSkipCountOption": "ข้ามการนับ",
    "fieldOperatorSumOption": "รวม",
    "fieldOperatorMinOption": "ต่ำสุด",
    "fieldOperatorMaxOption": "มากที่สุด",
    "fieldOperatorMeanOption": "ค่าเฉลี่ย",
    "expressionAddButtonText": "เพิ่ม",
    "expressionVerifyButtonText": "ยืนยัน",
    "summaryEditorText": "ข้อความสรุป",
    "zoomText": "ซูมอัตโนมัติหลังการติดตาม",
    "summarSettingTooltipText": "เพิ่มจำนวนอินพุท/เอาท์พุท",
    "symbol": "สัญลักษณ์",
    "outputParametersText": "เอาท์พุทพารามิเตอร์",
    "skipText": "ข้ามได้",
    "visibilityText": "มองเห็น",
    "exportToCsvText": "บันทึกเป็นไฟล์ CSV",
    "settitngstext": "การตั้งค่า",
    "saveToLayerText": "บันทึกไปยังชั้นข้อมูล (ทางเลือก)",
    "inputLabel": "ป้ายชื่อ",
    "inputTooltip": "คำแนะนำการใช้เครื่องมือ",
    "outputDisplay": "แสดงข้อความ",
    "addFieldTitle": "เพิ่มฟิลด์",
    "setScale": "เลือกสเกล",
    "enterDisplayText": "ป้อนข้อความที่แสดง",
    "saveToLayerHelp": "<p>จะแสดงชั้นข้อมูลที่ตรงตามเงื่อนไขต่อไปนี้:<br/><ul><li>ชั้นข้อมูลจะต้องมีความสามารถในการแก้ไข ที่ชื่อ 'สร้าง', 'ลบ' และ 'อัพเดต'</li><li>ชั้นข้อมูลจะต้องมีสองฟิลด์ที่มีชื่อและประเภทข้อมูลตรงกัน:</li><ul><li>parametername (ฟิลด์ประเภทสตริง)</li><li>projectid (ฟิลด์ประเภท Guid)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "กำหนดข้อความสรุปที่จะแสดงผลบนแท็บเอาท์พุท",
    "addSummaryItemsTitle": "เพิ่มรายการสรุป"
  },
  "validationErrorMessage": {
    "webMapError": "ไม่มีชั้นข้อมูลในเว็บแมป โปรดเลือกเว็บแมปที่ถูกต้อง",
    "inputTypeFlagGreaterThanError": "ไม่สามารถมีอินพุทประเภทธงมากกว่าหนึ่งรายการได้",
    "inputTypeFlagLessThanError": "จำเป็นต้องมีอินพุทประเภทธงอย่างน้อยหนึ่งรายการ",
    "inputTypeBarrierErr": "ไม่สามารถมีอินพุทประเภทอุปสรรคมากกว่าหนึ่งรายการได้",
    "inputTypeSkipErr": "ไม่สามารถมีอินพุทประเภทข้ามมากกว่าหนึ่งรายการได้",
    "displayTextForButtonError": "ต้องไม่เว้นว่างข้อความที่แสดงสำหรับปุ่ม 'เรียกใช้'",
    "UnableToLoadGeoprocessError": "ไม่สามารถโหลดเซอร์วิสการประมวลผลทางภูมิศาสตร์ได้",
    "invalidSummaryExpression": "นิพจน์ไม่ถูกต้อง",
    "validSummaryExpression": "สำเร็จ !",
    "invalidProjectSettings": "การตั้งค่าโปรเจคไม่ถูกต้อง<br/> โปรดเลือกค่าที่ถูกต้องใน '${projectSetting}'"
  },
  "hintText": {
    "labelTextHint": "เคล็ดลับ: ระบุป้ายกำกับการแสดงผลสำหรับแผงควบคุมผลลัพธ์ของเอาท์พุทพารามิเตอร์",
    "displayTextHint": "เคล็ดลับ: ส่วนนี้จะปรากฏอยู่ในแผงควบคุมรายละเอียดของเอาท์พุทพารามิเตอร์นี้",
    "inputTextHint": "เคล็ดลับ: สร้างนิพจน์ของคุณไว้ด้านล่าง โดยใช้ปุ่ม เพิ่มรายการสรุป",
    "expressionHint": "เคล็ดลับ: เลือกรายการ แล้วคลิกเพิ่ม เพื่อสร้างนิพจน์"
  }
});