define({
  "taskUrl": "Tehtävän URL-osoite",
  "setTask": "Määritä",
  "setTaskPopupTitle": "Määritä tehtävä",
  "validate": "Määritä",
  "inValidGPService": "Anna kelvollinen geoprosessointipalvelu.",
  "noOutputParameterWithGeometryType": "Valitulla geoprosessointipalvelulla on oltava vähintään yksi tulosaineiston parametri, jonka geometriatyyppi on määritetty. Valitse toinen geoprosessointipalvelu.",
  "invalidOutputGeometry": "Valitun geoprosessointipalvelun tulosaineiston geometriatyyppi ei ole yhteensopiva projektiasetusten kanssa. Geoprosessointipalvelun tuloksia ei voi tallentaa.",
  "GPFeatureRecordSetLayerERR": "Anna geoprosessointipalvelu, jossa on vain GPFeatureRecordSetLayer-tyypin lähtöaineistoa.",
  "invalidInputParameters": "Syöteparametreja on alle 1 tai yli 3. Anna kelvollinen geoprosessointipalvelu.",
  "projectSetting": {
    "title": "Projektiasetukset",
    "note": "Huomautus: projektiasetukset ovat valinnaiset, koska määritetty käyttäjä voi tallentaa projektin haluamiinsa web-kartan karttatasoihin verkon käyttökatkoalueiden ja lähtöaineiston parametrien kanssa. Käyttäjä voi tallentaa muut tulosaineiston parametrit Tulosaineisto-välilehdestä.",
    "projectPolygonLayer": "Projektin aluekarttataso",
    "outputParameterName": "Tulosparametrin nimi",
    "projectPointLayer": "Projektin pistekarttataso",
    "selectLabel": "Valitse",
    "polygonLayerHelp": "<p>Seuraavia ehtoja vastaavat aluekarttatasot näytetään:<br/><ul><li>Karttatasossa on oltava muokkaustoiminnot eli Luo, Poista ja Päivitä</li><li>Karttatasossa on oltava kaksi kenttää, joissa on tarkat nimi- ja tietotyypit:</li><ul><li>nimi (String-tyypin kenttä)</li><li>globalid (GlobalID-tyypin kenttä)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Tehtävän URL-osoitteen tulosaineiston aluekarttatasot näytetään<p/>",
    "pointLayerHelp": "<p>Seuraavia ehtoja vastaavat pistekarttatasot näytetään:<br/><ul><li>Karttatasossa on oltava muokkaustoiminnot eli Luo, Poista ja Päivitä</li><li>Karttatasossa on oltava kaksi kenttää, joissa on tarkat nimi- ja tietotyypit:</li><ul><li>inputtype (String-tyypin kenttä)</li><li>projectid (GlobalID-tyypin kenttä)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Lippu",
    "barrier": "Este",
    "skip": "Ohita",
    "title": "Lähtöaineisto",
    "inputTooltip": "Työkalun ohje",
    "typeText": "Tyyppi",
    "symbol": "Symboli",
    "summaryEditorText": "Yhteenvetoteksti",
    "summaryTextTitle": "Määritä syötevälilehdessä näytettävä teksti"
  },
  "summaryTab": {
    "title": "Tulosaineisto",
    "summaryFieldsetText": "Yhteenvetoasetukset",
    "inputOutput": "Syöte/Tulos",
    "field": "Kenttä",
    "operator": "Laskutoimitus",
    "inputOperatorCountOption": "Lukumäärä",
    "outputOperatorCountOption": "Lukumäärä",
    "outputOperatorSkipCountOption": "OhitettavaMäärä",
    "fieldOperatorSumOption": "Summa",
    "fieldOperatorMinOption": "Vähimmäisarvo",
    "fieldOperatorMaxOption": "Enimmäisarvo",
    "fieldOperatorMeanOption": "Keskiarvo",
    "expressionAddButtonText": "Lisää",
    "expressionVerifyButtonText": "Tarkasta",
    "summaryEditorText": "Yhteenvetoteksti",
    "zoomText": "Automaattinen tarkennus jäljityksen jälkeen",
    "summarSettingTooltipText": "Lisää lähtöaineiston/tulosaineiston määrä",
    "symbol": "Symboli",
    "outputParametersText": "Tulosparametrit",
    "skipText": "Ohitettavissa",
    "visibilityText": "Näkyvä",
    "exportToCsvText": "Vie CSV-tiedostoon",
    "settitngstext": "Asetukset",
    "saveToLayerText": "Tallenna karttatasoon (valinnainen)",
    "inputLabel": "Tunnusteksti",
    "inputTooltip": "Työkalun ohje",
    "outputDisplay": "Näyttöteksti",
    "addFieldTitle": "Lisää kenttä",
    "setScale": "Määritä mittakaava",
    "enterDisplayText": "Kirjoita näyttöteksti",
    "saveToLayerHelp": "<p>Seuraavia ehtoja vastaava karttataso näytetään:<br/><ul><li>Karttatasossa on oltava muokkaustoiminnot eli Luo, Poista ja Päivitä</li><li>Karttatasossa on oltava kaksi kenttää, joissa on nimi- ja tietotyypit:</li><ul><li>parametername (String-tyypin kenttä)</li><li>projectid (GUID-tyypin kenttä)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Määritä tulosvälilehdessä näytettävä yhteenvetoteksti",
    "addSummaryItemsTitle": "Lisää yhteenvetokohteet"
  },
  "validationErrorMessage": {
    "webMapError": "Web-kartassa ei ole karttatasoja. Valitse kelvollinen web-kartta.",
    "inputTypeFlagGreaterThanError": "Lipputyypin syötteitä ei voi olla yhtä enempää.",
    "inputTypeFlagLessThanError": "Vähintään yksi lipputyypin syöte on pakollinen.",
    "inputTypeBarrierErr": "Estetyypin syötteitä ei voi olla yhtä enempää.",
    "inputTypeSkipErr": "Ohitustyypin syötteitä ei voi olla yhtä enempää.",
    "displayTextForButtonError": "Suorita-painikkeen näyttöteksti ei voi olla tyhjä.",
    "UnableToLoadGeoprocessError": "Geoprosessointipalvelua ei voi ladata.",
    "invalidSummaryExpression": "Virheellinen lauseke.",
    "validSummaryExpression": "Onnistui!",
    "invalidProjectSettings": "Virheelliset projektiasetukset.<br/> Valitse kelvollinen arvo asetuksessa ${projectSetting}."
  },
  "hintText": {
    "labelTextHint": "Vihje: määritä tulosparametrin tulosruudussa näytettävä tunnusteksti.",
    "displayTextHint": "Vihje: tämä näytetään tämän tulosparametrin Tiedot-ruudussa.",
    "inputTextHint": "Vihje: muodosta lausekkeesi alla käyttämällä Lisää yhteenvetokohteet -painiketta.",
    "expressionHint": "Vihje: muodosta lauseke valitsemalla kohteet ja napsauttamalla Lisää."
  }
});