define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Προσθήκη σημείου με κλικ στον χάρτη",
  "addPolygon": "Δημιουργία πολυγώνου με σχεδίαση στον χάρτη",
  "addFreehandPolygon": "Δημιουργία πολυγώνου ελεύθερης σχεδίασης με σχεδίαση στον χάρτη",
  "addRingsDtWt": "Προσθέστε δακτυλίους, χρόνο οδήγησης και χρόνο πεζοπορίας.",
  "apply": "Εφαρμογή",
  "back": "Πίσω",
  "colon": ":",
  "creditInformation": "Πληροφορίες για τις μονάδες κατανάλωσης",
  "customPolygon": "Εξατομικευμένο πολύγωνο",
  "driveTime": "Χρόνος οδήγησης",
  "esriInfographics": "Infographic της Esri",
  "esriReports": "Αναφορές της Esri",
  "headerDescription_km": "χιλιόμετρο",
  "headerDescription_miles": "μίλι",
  "headerDescription_minutes": "λεπτό",
  "infographics": "Γραφικές αναπαραστάσεις δεδομένων (Infographics)",
  "invalidValueRing": "Οι τιμές πρέπει να είναι από 0 έως 1.000.",
  "invalidValueDTWT": "Οι τιμές πρέπει να είναι από 0 έως 300.",
  "km": "km",
  "miles": "μίλια",
  "minutes": "λεπτά",
  "myInfographics": "Τα infographic μου",
  "myReports": "Οι αναφορές μου",
  "noPermissions": "Ο λογαριασμός σας δεν έχει δικαίωμα εκτέλεσης του widget Business Analyst. Για να καταστεί δυνατή η εκτέλεση του widget Business Analyst, ο διαχειριστής του οργανισμού σας χρειάζεται να σας χορηγήσει <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">δικαιώματα</a> για τις εργασίες GeoEnrichment και Ανάλυση δικτύου και επίσης να σας εκχωρήσει <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">μονάδες κατανάλωσης</a>.",
  "geServiceNotConfigured": "Δεν είναι δυνατή η εκτέλεση του widget Business Analyst στο portal αυτό επειδή δεν έχει παραμετροποιημένη την υπηρεσία <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a>.",
  "dirRoutingServiceNotConfigured": "Δεν είναι δυνατή η εκτέλεση του widget Business Analyst στο portal αυτό επειδή δεν έχει παραμετροποιημένη την υπηρεσία <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Οδηγίες και δρομολόγηση</a>.",
  "geAndDirRoutingServicesNotConfigured": "Δεν είναι δυνατή η εκτέλεση του widget Business Analyst στο portal αυτό επειδή δεν έχει παραμετροποιημένη την υπηρεσία <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> και την υπηρεσία <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Οδηγίες και δρομολόγηση</a>.",
  "radii": "ακτίνες",
  "radius": "Ακτίνα",
  "radius_lowercase": "ακτίνα",
  "reports": "Αναφορές",
  "ring": "Δακτύλιος",
  "rings": "Δακτύλιοι",
  "runInfographic": "Εκτέλεση infographic",
  "runReport": "Εκτέλεση αναφοράς",
  "selectPointOrPolygon": "Επιλέξτε ένα σημείο ή ένα πολύγωνο στον χάρτη, αναζητήστε μια διεύθυνση ή έναν τόπο, σχεδιάστε ένα πολύγωνο ή αποθέστε μια καρφίτσα στον χάρτη για προβολή βασικών δεικτών και πληροφοριών όσον αφορά την περιοχή.",
  "selectReport": "Επιλογή αναφοράς",
  "selectTemplate": "Επιλογή προτύπου",
  "sharedInfographics": "Κοινοποιημένα infographic",
  "sharedReports": "Κοινοποιημένες αναφορές",
  "thisEntryIsNotValid": "Η καταχώριση αυτή δεν είναι έγκυρη.",
  "time": "Χρόνος",
  "walkTime": "Χρόνος πεζοπορίας",
  "widgetDescription": "Αποκτήστε πρόσβαση σε infographic και αναφορές που συνοψίζουν βασικούς δείκτες και δεδομένα για οποιαδήποτε περιοχή.",
  "None": "Επιλογή..."
});