version: '3.6'
services:
  webappbuilder:
    container_name: webappbuilder
    image: webappbuilderforarcgis
    env_file: .env
    environment:
      VIRTUAL_HOST: ${WAB_VIRTUAL_HOST}
      VIRTUAL_PORT: 3344
      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${WAB_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    networks:
      - proxy_net
    ports:
      - 3344:3344
#    volumes:
#
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
   
#volumes:
#
networks:
  # This is a network we share with our reverse proxy
  proxy_net:
    # Won't be created or destroyed with docker-compose up|down
    external: true
