version: '3.6'
services:

  webappbuilder:
    container_name: wabde
    image: wabde
    env_file: .env
#    environment:
#      VIRTUAL_HOST: ${WAB_VIRTUAL_HOST}
#      VIRTUAL_PORT: 3344
#      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${WAB_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    ports:
      - 3344:3344
    volumes:
      - esri_apps:/home/node/apps
      - esri_widgets:/home/node/widgets
    restart: unless-stopped
# Because of the weird requirements to build manually see the Makefile and README, don't build here
#    build:
#      context: .
#      dockerfile: Dockerfile


# I am thinking about adding a microserver to allow add and remove widgets and apps
# I briefly tested "filebrowser" and decided not to use it. It works but it's not what I want.
#  filebrowser:
#    container_name: esri_filebrowser
#    image: filebrowser/filebrowser:latest
#    ports:
#      - 80:80
#    volumes:
#      - esri_apps:/srv/apps
#      - esri_widgets:/srv/widgets
#      - ~/source/docker-WebAppBuilderForArcGIS/filebrowser_database.db:/database.db
#      - ~/source/docker-WebAppBuilderForArcGIS/filebrowser.json:/.filebrowser.json
   
volumes:
  esri_apps:
    name: esri_apps
  esri_widgets:
    name: esri_widgets
