version: '3.7'

volumes:
  db:
  widgets:
      
services:
  wabde:
    image: wildsong/wabde
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Americas/Los_Angeles
    ports:
      - 3344:3344
    volumes:
      - ./apps:/srv/server/apps
      - db:/srv/server/db
      - widgets:/srv/client/stemapp/widgets
