version: '3.7'

volumes:
  apps:
  db:
# use this one to use only the standard widget set
#  widgets:
      
services:
  wabde:
    image: wildsong/wabde
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Americas/Los_Angeles
    ports:
      - 3344:3344
    volumes:
      - apps:/srv/server/apps
      - db:/srv/server/db

    # use this one to use only the standard widget set
    #  - widgets:/srv/client/stemapp/widgets
    # use this one to use the github widget set
      - ./widgets:/srv/client/stemapp/widgets
