version: '3.7'

volumes:
  esri_apps:
    name: esri_apps
#  esri_widgets:
#    name: esri_widgets

services:

# See the README (or Makefile) for the image build instructions.

  webappbuilder:
    image: wildsong/wabde
    env_file: .env
    ports:
      - 3344:3344
    volumes:
      - esri_apps:/home/node/WebAppBuilderForArcGIS/server/apps
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#      - esri_widgets:/home/node/widgets
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITSERVER: ${GITSERVER}

# I am thinking about adding a web microserver to allow add and remove widgets and apps
# I briefly tested "filebrowser" and decided not to use it. It works but it's not what I want.
#  filebrowser:
#    image: filebrowser/filebrowser:latest
#    ports:
#      - 80:80
#    volumes:
#      - esri_apps:/srv/apps
#      - esri_widgets:/srv/widgets
#      - ~/source/docker-WebAppBuilderForArcGIS/filebrowser_database.db:/database.db
#      - ~/source/docker-WebAppBuilderForArcGIS/filebrowser.json:/.filebrowser.json
   
