version: '3.7'

# The db/apps file has the portal url embedded in it
# so I need to have separate apps and db volumes.
# I think I can still share the widgets though.

volumes:
  db:
    name: wabde_agol_db
  widgets:
      
services:

  wabde:
    image: wildsong/wabde
    environment:
      - TZ=Americas/Los_Angeles
    ports:
      - 3344:3344
    volumes:
      - ./apps_agol:/srv/server/apps
      - db:/srv/server/db
      - widgets:/srv/client/stemapp/widgets

      # This is a sample of using a bind mount for the json file.
      # The file "signininfo-agol.json" has to exist
      # in the local directory for this to work.

      - ./signininfo-agol.json:/srv/server/signininfo.json
