version: '3.7'

volumes:
  apps:
  db:
  widgets:
      
services:
  wabde:
    image: wildsong/wabde
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ:Americas/Los_Angeles
    ports:
      - 3344:3344
    volumes:
      - apps:/home/node/ArcGISWebAppBuilder/server/apps
      - db:/home/node/ArcGISWebAppBuilder/server/db
      - widgets:/home/node/ArcGISWebAppBuilder/client/stemapp/widgets

#      - ./apps:/home/node/ArcGISWebAppBuilder/server/apps
#      - ./widgets:/home/node/ArcGISWebAppBuilder/client/stemapp/widgets




