define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>エリアの主要指標とデータを集計するインフォグラフィックスとレポートにアクセスします。</div><br><div>マップ上のポイントまたはポリゴンを選択するか、住所または場所を検索するか、ポリゴンを描画するか、マップ上にピンを配置してエリアの主要指標と重要な情報を表示します。</div>",
  "defineWhichInfographics": "ウィジェットで利用可能なインフォグラフィックスを定義:",
  "defineWhichReports": "ウィジェットで利用可能なレポートを定義:",
  "defaultValues": "デフォルト値:",
  "disable": "無効化",
  "drawFreehandPolygon": "フリーハンド ポリゴンの描画",
  "drawPolygon": "ポリゴンの描画",
  "driveTime": "運転時間",
  "dropPin": "ピンをドロップ",
  "dynamicHTML": "ダイナミック HTML",
  "exportOptions": "エクスポート オプション:",
  "home": "ホーム",
  "image": "画像",
  "infographics": "インフォグラフィックス",
  "invalidValueRing": "値 は 0 ～ 1,000 の範囲内でなければなりません。",
  "invalidValueDTWT": "値 は 0 ～ 300 の範囲内でなければなりません。",
  "km": "キロメートル",
  "makeDefault": "デフォルトに設定",
  "miles": "マイル",
  "minutes": "分",
  "options": "オプション:",
  "pdf": "PDF",
  "print": "印刷",
  "radius": "半径",
  "removeDefault": "デフォルトの削除",
  "reports": "レポート",
  "rings": "リング",
  "searchTextBox": "テキスト ボックスを検索",
  "selectCountryOrRegion": "国または地域の選択:",
  "thisEntryIsNotValid": "このエントリは有効ではありません。",
  "time": "現在の時間",
  "walkTime": "徒歩時間"
});