define({
  "layersPage": {
    "allLayers": "Všetky vrstvy",
    "title": "Vyberte šablónu na tvorbu prvkov alebo kliknite na prvok v mape a editujte ho",
    "generalSettings": "Všeobecné nastavenia",
    "layerSettings": "Nastavenia vrstvy",
    "webmapSettingsRadioBtnLabel": "Dodržiavať nastavenia vo webovej mape",
    "customSettingsRadioBtnLabel": "Vlastné nastavenia",
    "smartActionsTabTitle": "Šikovné akcie",
    "attributeActionsTabTitle": "Atribútové akcie",
    "geocoderSettingsText": "Nastavenia geokodéra",
    "editDescription": "Zadajte text na zobrazenie pre panel úprav",
    "editDescriptionTip": "Tento text je zobrazený nad výberom šablón, zanechajte prázdny pre žiadny text.",
    "promptOnSave": "Výzva na uloženie neuložených úprav, keď je formulár zatvorený alebo prepnutý na ďalší záznam",
    "promptOnSaveTip": "Zobraziť výzvu, keď súčasný prvok obsahuje neuložené úpravy. (Kopírovanie viacerých prvkov sa ukladá automaticky.)",
    "promptOnDelete": "Požadovať potvrdenie pri mazaní záznamu",
    "promptOnDeleteTip": "Zobraziť výzvu, keď užívateľ stlačí delete na potvrdenie akcie.",
    "removeOnSave": "Odstrániť prvok z výberu pri uložení",
    "removeOnSaveTip": "Možnosť odstrániť prvok zo sady výberu pri uložení záznamu. Ak je to jediný uložený záznam, panel sa prepne späť na stránku so šablónou.",
    "useFilterEditor": "Použiť filter šablóny prvku",
    "useFilterEditorTip": "Možnosť použiť voľbu šablóny filtra, ktorá poskytuje možnosť zobraziť jednu vrstvu šablóny alebo hľadať šablóny podľa mena.",
    "groupFilteredTemplates": "Zoskupiť výsledky vyhľadávania",
    "groupFilteredTemplatesTip": "Umožňuje zoskupiť výsledky vyhľadávania podľa vrstvy.",
    "displayShapeSelector": "Zobraziť možnosti kreslenia",
    "createNewFeaturesFromExisting": "Povoliť užívateľovi vytvoriť nový prvok(y) z existujúceho prvku(ov)",
    "createNewFeaturesFromExistingTip": "Možnosť povoliť užívateľovi skopírovať existujúci prvok na vytvorenie nových prvkov",
    "copiedFeaturesOverrideDefaults": "Skopírované hodnoty prvkov obchádzajú predvolené hodnoty",
    "copiedFeaturesOverrideDefaultsTip": "Hodnoty zo skopírovaných prvkov obchádzajú predvolené hodnoty šablóny len pre zhodné stĺpce",
    "displayShapeSelectorTip": "Možnosť zobraziť zoznam platných možností kreslenia pre zvolenú šablónu.",
    "displayPresetTop": "Zobraziť zoznam prednastavených hodnôt na vrchu",
    "displayPresetTopTip": "Možnosť zobraziť zoznam prednastavených hodnôt nad voľbou šablón.",
    "listenToGroupFilter": "Použiť hodnoty filtra z widgetu skupinového filtra na prednastavené stĺpce",
    "listenToGroupFilterTip": "Keď je filter použitý vo widgete skupinového filtra, vložte hodnotu do príslušného poľa v zozname prednastavených hodnôt.",
    "keepTemplateActive": "Ponechať zvolenú šablónu aktívnu",
    "editLayerAddedFromAddData": "Povoliť editáciu vrstiev pridaných widgetom Pridať dáta",
    "editLayerAddedFromAddDataTip": "Editovateľné vrstvy, ktoré sa do aplikácie pridajú pomocou widgetu Pridať dáta je možné editovať",
    "keepTemplateActiveTip": "Keď je zobrazená voľba šablóny, ak bola predtým zvolená šablóna, bude zvolená znova.",
    "geometryEditDefault": "Východiskovo povoliť úpravy geometrie",
    "autoSaveEdits": "Automaticky uložiť nové prvky",
    "enableAttributeUpdates": "Zobraziť tlačidlo aktualizácie atribútových akcií",
    "enableAutomaticAttributeUpdates": "Automaticky zavolať atribútové akcie po aktualizácii geometrie",
    "enableLockingMapNavigation": "Povoliť zamknutie navigácie mapy",
    "enableMovingSelectedFeatureToGPS": "Povoliť posun zvoleného bodového prvku na GPS polohu",
    "enableMovingSelectedFeatureToXY": "Povoliť posun zvoleného bodového prvku na XY polohu",
    "featureTemplateLegendLabel": "Nastavenia hodnoty šablóny prvkov a filtra",
    "saveSettingsLegendLabel": "Nastavenia uloženia",
    "geometrySettingsLegendLabel": "Nastavenia geometrie",
    "actionsSettingsLegendLabel": "Nastavenia akcií",
    "buttonPositionsLabel": "Pozícia tlačidiel uložiť, zmazať, späť a zrušiť",
    "belowEditLabel": "Pod formulárom úprav",
    "aboveEditLabel": "Nad formulárom úprav",
    "switchToMultilineInput": "Prepnúť na vstup multilínií, keď je prekročená dĺžka stĺpca",
    "enableValuePicker": "Povoliť voľbu hodnoty pretínania",
    "enableValuePickerHint": "Zobraziť výzvu, keď je dostupných viacero hodnôt pre stĺpec s akciou atribútu pretínania",
    "expandRelatedTable": "Rozbaliť všetký súvisiace tabuľky/vrstvy pri načítaní",
    "expandMainTable": "Rozbaliť všetky nadradené vrstvy pri načítaní",
    "layerSettingsTable": {
      "allowDelete": "Povoliť zmazanie",
      "allowDeleteTip": "Povoliť zmazanie - Možnosť povoliť užívateľovi zmazať prvok; deaktivované, ak vrstva nepodporuje mazanie",
      "edit": "Editovateľný",
      "editTip": "Editovateľné - Možnosť zahrnúť vrstvu do widgetu",
      "label": "Vrstva",
      "labelTip": "Vrstva - Meno vrstvy podľa definície v mape",
      "update": "Zakázať úpravy geometrie",
      "updateTip": "Zakázať úpravy geometrie - Možnost deaktivovať schopnosť pohybu geometrie, keď je uť raz umiestnená, alebo presunu geometrie na existujúci prvok",
      "allowUpdateOnly": "Len aktualizácie",
      "allowUpdateOnlyTip": "Len aktualizácie - Možnosť povoliť len modifikácie existujúcich prvkov, predvolene kontrolované a deaktivované, ak vrstva nepodporuje tvorbu nových prvkov",
      "fieldsTip": "Modifikovať stĺpce, ktoré budú upravené a definovať Smart atribúty",
      "actionsTip": "Akcie - Možnosť upraviť stĺpce alebo pristúpiť do súvisiacich do vrstiev/tabuliek",
      "description": "Opis",
      "descriptionTip": "Popis - Možnosť zadať text na zobrazenie vo vrchnej časti stránky s atribútmi.",
      "relationTip": "Zobraziť relačne súvisiace vrstvy a tabuľky"
    },
    "editFieldError": "Modifikácie stĺpca a Šikovných atribútov nie sú dostupné pre vrstvy, ktoré nie sú editovateľné",
    "noConfigedLayersError": "Smart editor vyžaduje jednu alebo viac editovaťeľných vrstiev",
    "toleranceErrorMsg": "Neplatná hodnota predvolenej tolerancie pretínania",
    "pixelsToleranecErrorMsg": "Neplatná hodnota predvolenej tolerancie pixelov",
    "invalidMaxCharacterErrorMsg": "Neplatná hodnota v prepínači do viacerých vstupov",
    "featuresSelectionTolerance": "Nastaviť toleranciu pre výber prvku (v pixeloch)",
    "featuresSelectionToleranceTooltip": "Umožniť používateľom otvoriť panel editovania atribútov kliknutím na prvok",
    "featuresSelectionToleranceErrorMsg": "Neplatná hodnota tolerancie pre výber prvku",
    "autoSaveAttrUpdates": "Automaticky uložiť aktualizácie atribútov"
  },
  "editDescriptionPage": {
    "title": "Definovať text prehľadu atribútov pre <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Konfigurovať stĺpce pre <b>${layername}</b>",
    "copyActionTip": "Atribútové akcie",
    "editActionTip": "Šikovné akcie",
    "description": "Použiť tlačidlo úpravy akcií na aktiváciu Šikovných atribútov vo vrstve. Šikovné atribúty môžu požadovať, skryť alebo deaktivovať stĺpce podľa hodnôt v iných stĺpcoch. Použiť tlačidlo kopírovania akcií na aktiváciu a definovanie zdroja hodnoty stĺpca podľa pretínania, adresy, súradníc a predvolieb.",
    "fieldsNotes": "* je povinný stĺpec. Ak odčiarknete zobrazenie pre tento stĺpec a šablóna úpravy nevyplní túto hodnotu stĺpca, nebudete schopný uložiť nový záznam.",
    "smartAttachmentText": "Konfigurovať Šikovné akcie pre prílohy",
    "smartAttachmentPopupTitle": "Konfigurovať Šikovné akcie pre prílohy v <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Prosím zvoľte aspoň jeden stĺpec zobrazenia pre vrstvu ${layerName}",
    "fieldsSettingsTable": {
      "display": "Zobrazenie",
      "displayTip": "Zobrazenie - Určiť, či je stĺpec neviditeľný",
      "edit": "Editovateľný",
      "editTip": "Editovateľný - Skontrolovať, či je stĺpec prítomný vo formulári atribútov",
      "fieldName": "Meno",
      "fieldNameTip": "Meno - Meno stĺpca definované v databáze",
      "fieldAlias": "Alias",
      "fieldAliasTip": "Alias - Meno stĺpca definované v mape",
      "canPresetValue": "Prednastaviť",
      "canPresetValueTip": "Predvoľba- Možnosť zobraziť stĺpec v zozname prednastavených stĺpcov a povoliť používateľovi nastaviť hodnotu ešte pred editovaním",
      "actions": "Akcie",
      "actionsTip": "Akcie - Zmeniť poradie stĺpcov alebo nastaviť Šikovné atribúty"
    },
    "smartAttSupport": "Smart atribúty nie sú podporované na požadovaných stĺpcoch v databáze"
  },
  "actionPage": {
    "title": "Konfigurovať atribútové akcie pre <b>${fieldname}</b>",
    "smartActionTitle": "Konfigurovať Smart Actions pre <b>${fieldname}</b>",
    "description": "Akcie sú vždy vypnuté, okrem prípadov kedy špecifikujete kritériá, podľa ktorých budú spustené. Akcie sú spracované v poradí a iba jedna akcia bude spustená pre jeden stĺpec. Použiť tlačidlo úpravy kritérií na definovanie kritérií.",
    "copyAttributesNote": "Deaktivácia ktorýchkoľvek akcií s menom skupiny bude rovnaká, ako úprava tejto akcie nezávisle a odstráni akciu pre tento stĺpec z príslušnej skupiny.",
    "searchPlaceHolder": "Vyhľadávanie",
    "expandAllLabel": "Rozbaliť všetky vrstvy",
    "selectAllLabel": "Zvoliť všetky vrstvy",
    "domainListTitle": "Číselníkové stĺpce",
    "noValidFieldTypeMsg": "Pre tento typ dát nie je v mape k dispozícii žiadna vhodná vrstva",
    "actionsSettingsTable": {
      "rule": "Akcia",
      "ruleTip": "Akcia - Akcia vykonaná, keď sú kritéria splnené",
      "expression": "Výraz",
      "expressionTip": "Výraz - Výsledný výraz v SQL formáte z definovaných kritérií",
      "groupName": "Názov skupiny",
      "groupNameTip": "Názov skupiny - Zobrazí názov skupiny, z ktorej je výraz použitý",
      "actions": "Kritériá",
      "actionsTip": "Kritériá - Zmeniť poradie pravidiel a definovať kritériá, keďsú spustené"
    },
    "copyAction": {
      "description": "Zdroj hodnoty poľa sú spracované v poradí, ak sú aktivované, pokým sú platné kritéria spustené alebo je zoznam dokončený. Použiť tlačidlo úpravy kritérií na definovanie kritérií.",
      "intersection": "Križovatka",
      "coordinates": "súradnice",
      "address": "Adresa",
      "preset": "Prednastaviť",
      "actionText": "Akcie",
      "criteriaText": "Kritéria",
      "enableText": "Aktivovaný"
    },
    "actions": {
      "hide": "Skryť",
      "required": "Vyžadované",
      "disabled": "Deaktivovaný"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Varovanie: Upraviť nezávisle odstráni zvolenú atribútovú akciu priradenú pre tento stĺpec zo skupiny",
      "editGroupHint": "Varovanie: Upraviť nezávisle odstráni zvolenú Šikovnú akciu priradenú pre tento stĺpec zo skupiny",
      "popupTitle": "Zvoliť možnosť editovania",
      "editAttributeGroup": "Akcia zvolených atribútov je definovaná zo skupiny. Vybrať jednu z nasledujúcich možností na úpravu akcie atribútov:",
      "expression": "Výraz zvolenej Šikovné akcie je definovaný zo skupiny. Vybrať jednu z nasledujúcich možností na úpravu výrazu šikovnej akcie:",
      "editGroupButton": "Skupina úprav",
      "editIndependentlyButton": "Upraviť nezávisle"
    }
  },
  "filterPage": {
    "submitHidden": "Potvrdiť údaje atribútov pre stĺpce aj keď sú skryté",
    "title": "Konfigurovať výraz pre ${action} pravidlo",
    "filterBuilder": "Nastaviť akciu stĺpca, keď sa záznamy zhodujú ${any_or_all} s nasledujúcimi výrazmi",
    "noFilterTip": "Za použitia nástrojov vyššie definujte stav pre akciu, keď je aktívna."
  },
  "geocoderPage": {
    "setGeocoderURL": "Nastaviť URL geokodéru",
    "hintMsg": "Poznámka: Meníte službu geokodéra, prosím uistite sa, že aktualizujete akékoľvek mapovania stĺpcov geokodéra, ktoré ste konfigurovali.",
    "invalidUrlTip": "URL ${URL} je neplatná alebo nedostupná."
  },
  "addressPage": {
    "popupTitle": "Adresa",
    "checkboxLabel": "Získať hodnotu z geokodéra",
    "selectFieldTitle": "Atribút",
    "geocoderHint": "Pre zmenu geokodéra, navštívte tlačidlo 'Nastavenia geokodéra' vo všeobecných nastaveniach",
    "prevConfigruedFieldChangedMsg": "V minulosti konfigurovaný atribút nebol nájdený v súčasných nastaveniach geokodéra. Atribút bol obnovený na predvolené nastavenie.",
    "questionMark": "?",
    "consumesCredits": "Tento nástroj využíva kredity ak je používaný s geokódovacou službou ArcGIS Online World."
  },
  "coordinatesPage": {
    "popupTitle": "súradnice",
    "checkboxLabel": "Získať súradnice",
    "coordinatesSelectTitle": "Referenčný systém",
    "coordinatesAttributeTitle": "Atribút",
    "mapSpatialReferenceOptionLabel": "Súradnicový systém mapy",
    "latLongOptionLabel": "Zemepisná šírka/Zemepisná dĺžka",
    "MGRS": "MGRS",
    "allGroupsCreatedMsg": "Všetky možné skupiny sú už vytvorené",
    "coordinatesSourceTitle": "Zdroj súradníc",
    "featureLocation": "Poloha prvku",
    "myLocation": "Moja poloha",
    "LatLong": {
      "y": "Zemepisná šírka",
      "x": "Zemepisná dĺžka",
      "xy": "Zemepisná dĺžka Zemepisná šírka",
      "yx": "Zemepisná šírka Zemepisná dĺžka"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Prednastaviť",
    "checkboxLabel": "Pole bude prednastavené",
    "showOnlyDomainFields": "Zobraziť len stĺpce číselníka",
    "hideInPresetDisplay": "Skryť v zobrazení prednastavenej hodnoty",
    "presetValueLabel": "Aktuálna prednastavená hodnota je:",
    "changePresetValueHint": "Pre zmenu tejto hodnoty navštívte tlačidlo 'Definovať prednastavené hodnoty' vo všeobecných nastaveniach"
  },
  "intersectionPage": {
    "groupNameLabel": "Názov skupiny",
    "dataTypeLabel": "Typ údajov",
    "ignoreLayerRankingCheckboxLabel": "Ignorovať poradie vrstvy a nájsť najbližší prvok naprieč všetkými definovanými vrstvami",
    "intersectingLayersLabel": "Vrstva(y) na extrahovanie hodnoty",
    "layerAndFieldsApplyLabel": "Vrstva(y) a stĺpce na použitie extrahovanej hodnoty",
    "checkboxLabel": "Získať hodnotu z priesečníka stĺpca vrstvy",
    "layerText": "Vrstvy",
    "fieldText": "Stĺpce",
    "actionsText": "Akcie",
    "toleranceSettingText": "Nastavenia tolerancie",
    "addLayerLinkText": "Pridať vrstvu",
    "useDefaultToleranceText": "Použiť predvolenú toleranciu",
    "toleranceValueText": "Hodnota tolerancie",
    "toleranceUnitText": "Jednotka tolerancie",
    "pixelsUnitText": "Pixle",
    "useLayerName": "- Použiť meno vrstvy -",
    "noLayersMessage": "Nebol nájdený žiadny stĺpec vo vrstvách mapy zhodných so zvoleným typom údajov.",
    "intersectionLayerHint": "Poradie vrstiev sa určuje zostupne. Použite šípky pod akciami pre zmenu poradia vrstiev a zmenu priority priesečníkov."
  },
  "presetAll": {
    "popupTitle": "Definovať predvolené prednastavené hodnoty",
    "deleteTitle": "Vymazať prednastavenú hodnotu",
    "hintMsg": "Všetky unikátne prednastavené názvy stĺpcov sú uvedené tu. Odstránenie prednastaveného stĺpca deaktivuje príslušný stĺpec ako prednastavenie zo všetkých vrstiev/tabuliek."
  },
  "intersectionTolerance": {
    "intersectionTitle": "Predvolená tolerancia priesečníka pre všetky prvky",
    "pixelsToleranceTitle": "Predvolená tolerancia priesečníka (pixelová hodnota) bude použitá len pre bodové prvky"
  },
  "smartActionsPage": {
    "smartActionLabel": "Konfigurovať Šikovnú akciu",
    "addNewSmartActionLinkText": "Pridať nové",
    "definedActions": "Definované akcie",
    "priorityPopupTitle": "Nastaviť prioritu Šikovných akcií",
    "priorityPopupColumnTitle": "Smart akcie",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Názov skupiny",
    "layerForExpressionLabel": "Vrstvy pre výrazy",
    "layerForExpressionNote": "Poznámka: Polia tejto vrstvy sú použité na definovanie kritérií výrazu. 'Vrstvy a polia pre použitie' zobrazuje iba vrstvy a tabuľky, ktoré majú polia definované vo výraze.",
    "expressionText": "Výraz",
    "editExpressionLabel": "Upraviť výraz",
    "layerAndFieldsApplyLabel": "Vrstvy a stĺpce, na ktorých budú použité",
    "submitAttributeText": "Potvrdiť údaje atribútov pre stĺpce aj keď sú skryté",
    "priorityColumnText": "Priorita",
    "requiredGroupNameMsg": "Vyžaduje sa táto hodnota",
    "uniqueGroupNameMsg": "Zadať unikátne meno skupiny, skupina s týmto menom už existuje.",
    "deleteGroupPopupTitle": "Zmazať skupinu Šikovné akcie",
    "deleteGroupPopupMsg": "Zmazanie skupiny spôsobí odstránenie výrazu zo všetkých asociovaných stĺpcov akcií",
    "invalidExpression": "Výraz nemôže byť prázdny",
    "warningMsgOnLayerChange": "Definovaný výraz a stĺpce, na ktorých je použitý, budú vyprázdnené.",
    "smartActionsTable": {
      "name": "Meno",
      "expression": "Výraz",
      "definedFor": "Definované pre"
    }
  },
  "attributeActionsPage": {
    "name": "Meno",
    "type": "Typ",
    "deleteGroupPopupTitle": "Zmazať skupinu akcií atribútov",
    "deleteGroupPopupMsg": "Zmazanie skupiny spôsobí odstránenie akcie atribútu zo všetkých asociovaných stĺpcov",
    "alreadyAppliedActionMsg": "${action} akcia použitá na tomto stĺpci skupiny",
    "alreadyAppliedActionLayerMsg": "${action} akcia použitá na tomto stĺpci z Nastavení vrstvy",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Táto skupina nemá asociované stĺpce.",
    "presetNoFieldWarningMsg": "Prosím konfigurujte aspoň jeden stĺpec pre prednastavenú skupinu: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Stĺpec",
    "valueLabel": "Hodnota",
    "selectValueLabel": "Vybrať hodnotu",
    "domainFieldHintLabel": "Zvolená hodnota je doména s kódovanými hodnotami. Hodnota: ${domainValue} bude použitá"
  },
  "presetPopup": {
    "presetValueLAbel": "Prednastavená hodnota"
  },
  "dataType": {
    "esriFieldTypeString": "Reťazec",
    "esriFieldTypeInteger": "Číslo",
    "esriFieldTypeDate": "Dátum",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Typ dátumu",
    "valueLabel": "Hodnota",
    "fixed": "Fixné",
    "current": "Aktuálna",
    "past": "Minulosť",
    "future": "Budúcnosť",
    "popupTitle": "Vybrať hodnotu",
    "hintForFixedDateType": "Tip: Špecifikovaný dátum a čas bude použitý ako prednastavená predvolená hodnota",
    "hintForCurrentDateType": "Tip: Aktuálny dátum a čas bude použitý ako prednastavená predvolená hodnota",
    "hintForPastDateType": "Tip: Špecifikovaná hodnota bude odčítaná od aktuálneho dátumu a času pre predvolenú hodnotu predvoľby.",
    "hintForFutureDateType": "Tip: Špecifikovaná hodnota bude pridaná k aktuálnemu dátumu a času pre predvolenú hodnotu prednastavenia.",
    "noDateDefinedTooltip": "Žiadny definovaný dátum",
    "relativeDateWarning": "Hodnota pre dátum a čas musí byť špecifikovaná, aby sa dala predvolená prednastavená hodnota uložiť.",
    "customLabel": "Vlastné"
  },
  "relativeDomains": {
    "fieldSetTitle": "Zoznam",
    "valueText": "Hodnota",
    "defaultText": "Predvolené",
    "selectedDomainFieldsHint": "Zvolené stĺpce číselníka: ${domainFields}",
    "selectDefaultDomainMsg": "Prosím zvoľte predvolenú prednastavenú hodnotu v číselníku alebo sa uistite, že začiarkavacie políčko vybratého predvolenéha číselníka je začiarknuté"
  }
});