define({
  "_widgetLabel": "แก้ไขแบบสมาร์ท",
  "_featureAction_SmartEditor": "แก้ไขแบบสมาร์ท",
  "noEditPrivileges": "บัญชีของคุณไม่ได้รับอนุญาตให้สร้างหรือปรับเปลี่ยนข้อมูล",
  "loginPopupTitle": "ลงชื่อเข้าใช้",
  "loginPopupMessage": "${widgetName} ต้องการการอนุญาตและเครดิตเพื่อค้นหาและจัดเก็บข้อมูลที่อยู่ คุณต้องการลงชื่อเข้าใช้และใช้ความสามารถนี้หรือไม่",
  "noCreditsOrPrivilegeWarningMessage": "บัญชีของคุณไม่มีสิทธิ์และเครดิตในการค้นหาและจัดเก็บข้อมูลที่อยู่ด้วย ${widgetName} โปรดติดต่อผู้ดูแลระบบขององค์กรของคุณเพื่อขอสิทธิ์และเครดิต คลิก OK เพื่อดำเนินการแก้ไขต่อ",
  "unableToUseLocator": "ไม่สามารถเข้าถึงตัวระบุตำแหน่งได้ จะยังไม่มีการดำเนินการในส่วนคุณลักษณะแอดเดรส คลิก OK เพื่อดำเนินการแก้ไขต่อ",
  "locatorDisabledWaning": "ตัวระบุตำแหน่งไม่พร้อมใช้งาน โปรดติดต่อผู้ดูแลระบบขององค์กรของคุณเพื่อขอขีดความสามารถนี้ คลิก OK เพื่อดำเนินการแก้ไขต่อ",
  "noFeatureInAIWarning": "ไม่ได้เลือกคุณสมบัติ โปรดเลือกคุณสมบัติเพื่อทำการแก้ไขหรือคลิกยกเลิกเพื่อกลับไปที่หน้าจอหลัก",
  "noEditableLayerWarning": "บัญชีของคุณไม่ได้รับอนุญาตให้สร้างหรือแก้ไขข้อมูลหรือแผนที่เว็บนี้ไม่มีชั้นข้อมูลที่แก้ไขได้",
  "noVisibleCreateLayerWarning": "มองไม่เห็นชั้นข้อมูลที่ระดับการซูมปัจจุบัน ซูมเข้าหรือออกเพื่อสร้าง/แก้ไขฟีเจอร์",
  "noVisibleUpdateLayerWarning": "มองไม่เห็นชั้นข้อมูลที่ระดับการซูมปัจจุบัน ซูมเข้าหรือออกเพื่อแก้ไขฟีเจอร์",
  "checkLayerVisibilityInWebMapWarning": "ตรวจสอบให้แน่ใจว่าชั้นข้อมูลต่าง ๆ สามารถมองเห็นได้ในแผนที่เพื่อสร้างหรือปรับเปลี่ยนคุณสมบัติ",
  "showSelectionInAITitle": "ฟีเจอร์ที่เลือก",
  "showSelectionInAIMsg": "คุณต้องการโหลดการเลือกปัจจุบันใน ${widgetName} หรือไม่",
  "widgetActive": "ใช้การได้",
  "widgetNotActive": "ไม่สามารถใช้งานได้",
  "pressStr": "กด ",
  "ctrlStr": " CTRL ",
  "snapStr": " เพื่อเปิดการใช้งาน Snapping",
  "noAvailableTempaltes": "ไม่มีแม่แบบที่ใช้งานได้",
  "editorCache": " - แคชการแก้ไข",
  "presetFieldAlias": "ฟิลด์",
  "presetValue": "ค่าที่ตั้งไว้ล่วงหน้า",
  "usePresetValues": " ใช้ค่าพรีเซ็ต (ฟีเจอร์ใหม่เท่านั้น)",
  "editGeometry": " แก้ไขรูปร่างเรขาคณิต",
  "savePromptTitle": "บันทึกข้อมูล",
  "savePrompt": "คุณต้องการที่จะบันทึกข้อมูลปัจจุบันหรือไม่?",
  "deletePromptTitle": "ลบข้อมูลนี้",
  "deleteAttachment": "ลบไฟล์แนบ",
  "deletePrompt": "คุณแน่ใจหรือไม่ว่าคุณต้องการลบข้อมูลที่เลือก?",
  "attachmentLoadingError": "การอัปโหลดสิ่งที่แนบมามีข้อผิดพลาด",
  "attachmentSaveDeleteWarning": "คำเตือน: การเปลี่ยนแปลงสิ่งที่แนบมาจะถูกบันทึกไว้โดยอัตโนมัติ",
  "autoSaveEdits": "บันทึกฟีเจอร์ใหม่โดยอัตโนมัติ",
  "addNewFeature": "สร้างฟีเจอร์ใหม่",
  "featureCreationFailedMsg": "ไม่สามารถสร้างบันทึก/ฟีเจอร์ใหม่",
  "relatedItemTitle": "ตาราง/ชั้นข้อมูลที่เกี่ยวข้อง",
  "relatedFeatureCount": "${layerTitle} กับ ${featureCount} ฟีเจอร์",
  "createNewFeatureLabel": "สร้างฟีเจอร์ใหม่สำหรับ ${layerTitle}",
  "invalidRelationShipMsg": "โปรดตรวจสอบฟิลด์คีย์หลัก: '${parentKeyField}' มีค่าที่ถูกต้อง",
  "pendingFeatureSaveMsg": "โปรดบันทึกการแก้ไขฟีเจอร์ก่อนสร้างฟีเจอร์ที่เกี่ยวข้อง",
  "attachmentsRequiredMsg": "ต้องมีไฟล์แนบ (*)",
  "coordinatePopupTitle": "ย้ายฟีเจอร์ไปยังที่ตั้ง XY",
  "coordinatesSelectTitle": "ระบบพิกัด:",
  "mapSpecialReferenceDropdownOption": "การอ้างอิงเชิงพื้นที่ของแผนที่",
  "latLongDropdownOption": "ละติจูด/ลองจิจูด",
  "mgrsDropdownOption": "ระบบพิกัดทางการทหาร (MGRS)",
  "mgrsTextBoxLabel": "พิกัด:",
  "xAttributeTextBoxLabel": "พิกัด X:",
  "yAttributeTextBoxLabel": "พิกัด Y:",
  "latitudeTextBoxLabel": "ละติจูด:",
  "longitudeTextBoxLabel": "ลองจิจูด:",
  "presetGroupFieldsLabel": "'${groupName}' จะถูกใช้กับฟิลด์ชั้นข้อมูลต่อไปนี้:",
  "presetGroupNoFieldsLabel": "'${groupName}' ไม่มีฟิลด์ที่เชื่อมโยง",
  "groupInfoLabel": "ข้อมูลกลุ่มสำหรับ '${groupName}'",
  "editGroupInfoIcon": "แก้ไขค่ากลุ่มสำหรับ ${groupName}",
  "filterEditor": {
    "all": "ทั้งหมด",
    "noAvailableTempaltes": "ไม่มีแม่แบบที่ใช้งานได้",
    "searchTemplates": "ค้นหาแม่แบบ",
    "filterLayerLabel": "กรองชั้นข้อมูล"
  },
  "invalidConfiguration": "วิดเจ็ตอย่างใดอย่างหนึ่งไม่ได้กำหนดค่า หรือชั้นข้อมูลที่ใช้ในการกำหนดค่าที่ไม่ได้อยู่ในแผนที่ กรุณาเปิดแอปในโหมดผู้สร้างและกำหนดค่าวิดเจ็ต",
  "geometryServiceURLNotFoundMSG": "ไม่สามารถรับ URL เซอร์วิสเรขาคณิต",
  "clearSelection": "ปิด",
  "refreshAttributes": "อัพเดตแอตทริบิวต์ไดนามิกฟีเจอร์",
  "automaticAttributeUpdatesOn": "อัพเดตฟีเจอร์แอตทริบิวต์อัตโนมัติ: เปิด",
  "automaticAttributeUpdatesOff": "อัพเดตฟีเจอร์แอตทริบิวต์อัตโนมัติ: ปิด",
  "moveSelectedFeatureToGPS": "ย้ายฟีเจอร์ที่เลือกไปยังที่ตั้ง GPS ปัจจุบัน",
  "moveSelectedFeatureToXY": "ย้ายฟีเจอร์ที่เลือกไปยังที่ตั้ง XY",
  "mapNavigationLocked": "การนำทางแผนที่: ล็อค",
  "mapNavigationUnLocked": "การนำทางแผนที่: ปลดล็อค",
  "copyFeatures": {
    "title": "เลือกฟีเจอร์ที่จะคัดลอก",
    "createFeatures": "สร้างฟีเจอร์",
    "createSingleFeature": "สร้างฟีเจอร์หลายส่วน 1 รายการ",
    "createOneSingleFeature": "สร้างฟีเจอร์",
    "noFeaturesSelectedMessage": "ไม่ได้เลือกฟีเจอร์",
    "selectFeatureToCopyMessage": "โปรดเลือกฟีเจอร์ที่จะคัดลอก",
    "multipleFeatureSaveWarning": "การสร้างหลายฟีเจอร์โดยใช้ฟังก์ชันนี้ จะเป็นการบันทึกฟีเจอร์ใหม่ทั้งหมดในทันที ไม่รองรับการจับคู่ฟิลด์ขณะสร้างฟีเจอร์ใหม่แบบหลายส่วน",
    "copyFeatureUpdateGeometryError": "ไม่สามารถอัพเดตเรขาคณิตของฟีเจอร์ที่เลือกได้",
    "canNotSaveMultipleFeatureWarning": "คุณสามารถคัดลอกได้เพียงฟีเจอร์เดียวเท่านั้นเมื่อชั้นข้อมูลจุดเป้าหมายมีฟิลด์ค่าที่ไม่ซ้ำกัน",
    "createOnlyOneMultipartFeatureWarning": "คุณสามารถคัดลอกหนึ่งฟีเจอร์หรือสร้างฟีเจอร์แบบหลายส่วนได้เมื่อชั้นข้อมูลเป้าหมายมีฟิลด์ค่าที่ไม่ซ้ำกัน",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} จาก ${totalFeatures} ฟีเจอร์ที่เลือก"
  },
  "addingFeatureError": "เกิดข้อผิดพลาดขณะเพิ่มฟีเจอร์ที่เลือกลงในชั้นข้อมูล โปรดลองอีกครั้ง",
  "addingFeatureErrorCount": "คัดลอกฟีเจอร์ '${copyFeatureErrorCount}' ไม่สำเร็จ คุณต้องการลองอีกครั้งสำหรับฟีเจอร์ที่ขาดหายไปหรือไม่",
  "selectingFeatureError": "เกิดข้อผิดพลาดขณะเลือกฟีเจอร์ในชั้นข้อมูล โปรดลองอีกครั้ง",
  "customSelectOptionLabel": "เลือกฟีเจอร์ที่จะคัดลอก",
  "copyFeaturesWithPolygon": "คัดลอกตามโพลีกอน",
  "copyFeaturesWithRect": "คัดลอกตามสี่เหลี่ยมผืนผ้า",
  "copyFeaturesWithLasso": "คัดลอกตามการวาดเส้น",
  "noFeatureSelectedMessage": "ไม่ได้เลือกฟีเจอร์",
  "multipleFeatureSaveMessage": "ฟีเจอร์ทั้งหมดจะถูกบันทึกในทันที คุณต้องการดำเนินการต่อหรือไม่",
  "relativeDates": {
    "dateTypeLabel": "ประเภทวันที่",
    "valueLabel": "ค่า",
    "fixed": "คงที่",
    "current": "ปัจจุบัน",
    "past": "อดีต",
    "future": "อนาคต",
    "popupTitle": "เลือกค่า",
    "hintForFixedDateType": "เคล็ดลับ: วันที่และเวลาที่กำหนด จะถูกใช้เป็นค่าเริ่มต้นพรีเซ็ต",
    "hintForCurrentDateType": "เคล็ดลับ: วันที่และเวลาปัจจุบัน จะถูกใช้เป็นค่าเริ่มต้นพรีเซ็ต",
    "hintForPastDateType": "เคล็ดลับ: ค่าที่ระบุจะถูกลบออกจากวันที่และเวลาปัจจุบัน สำหรับค่าเริ่มต้นของพรีเซ็ต",
    "hintForFutureDateType": "เคล็ดลับ: ค่าที่ระบุจะถูกเพิ่มลงในวันที่และเวลาปัจจุบัน สำหรับค่าเริ่มต้นของพรีเซ็ต",
    "noDateDefinedTooltip": "ไม่ได้กำหนดวันที่ไว้",
    "relativeDateWarning": "จะต้องระบุค่าวันที่หรือเวลา เพื่อให้สามารถบันทึกค่าพรีเซ็ตเริ่มต้นได้",
    "customLabel": "แก้ไขเอง",
    "layerLabel": "ชั้นข้อมูล",
    "domainFieldHintLabel": "ค่าที่เลือกเป็นโดเมนค่าที่เข้ารหัสไว้ ค่า: \"${domainValue}\" จะถูกใช้"
  },
  "valuePicker": {
    "popupTitle": "เลือกค่า",
    "popupHint": "ฟีเจอร์ปัจจุบัน ตัดกับหลายฟีเจอร์ เลือกค่าของฟิลด์เรียงตามลำดับ",
    "buttonTooltip": "เลือกค่าจากหลายฟีเจอร์ที่ตัดกัน"
  },
  "uniqueValueErrorMessage": "มีค่าใน \"${fieldName}\" อยู่แล้ว โปรดป้อนค่าใหม่",
  "requiredFields": {
    "displayMsg": "ต้องไม่เว้นว่างฟิลด์ที่จำเป็น ป้อนค่าสำหรับฟิลด์ทั่วไปด้านล่าง",
    "popupTittle": "ฟิลด์ที่ต้องใช้หรือต้องมี",
    "foundNullRecordCount": "${fieldName} (พบใน ${count} บันทึกข้อมูล)"
  },
  "fieldsMapping": {
    "popupTittle": "ใช้การจับคู่ฟิลด์",
    "fieldsMatchingCheckboxLabel": "ค่าจากฟีเจอร์ที่คัดลอก จะแทนที่ค่าเริ่มต้นในฟิลด์เป้าหมาย",
    "resetLabel": "เริ่มใหม่",
    "clearLabel": "ชัดเจน",
    "fieldsInTargetLayerLabel": "เป้าหมาย",
    "fieldsInSourceLayerLabel": "แหล่ง",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} ฟิลด์ที่ตรงกัน)",
    "selectSourceFieldLabel": "- เลือก -",
    "selectFieldAriaLabel": "เลือกฟิลด์ต้นทางสำหรับฟิลด์เป้าหมาย ${targetField}",
    "informativeText": "ตรวจสอบการจับคู่ฟิลด์จากต้นทางไปยังเป้าหมาย และปรับแต่งตามความจำเป็น",
    "dynamicValueText": "ตั้งค่าแบบไดนามิก",
    "noFieldsToMatchLabel": "ไม่มีฟิลด์ที่ตรงกัน"
  },
  "cantLocateUserLocation": "ไม่สามารถระบุตำแหน่งของคุณได้",
  "tryAgainButtonLabel": "ลองอีกครั้ง",
  "copyFeatureFailedPopupTitle": "ขออภัย!"
});