define({
  "businessAnalyst": "Üzleti elemző",
  "defaultFirstPageText": "<br><div>Az adott terület fő mutatóit és adatait összegző inforgrafikákhoz és jelentésekhez férhet hozzá.</div><br><div>Válasszon pontot vagy poligont a térképen, keressen címet vagy helyet, rajzoljon poligont, vagy helyezzen el jelölőt a térképen, ha szeretne további jelzőket és információkat megtekinteni a területre vonatkozóan.</div>",
  "defineWhichInfographics": "Határozza meg, hogy mely infografikák álljanak rendelkezésre a widgetben:",
  "defineWhichReports": "Határozza meg, hogy mely jelentések álljanak rendelkezésre a widgetben:",
  "defaultValues": "Alapértelmezett értékek:",
  "disable": "Letiltás",
  "drawFreehandPolygon": "Szabadkézi polygon rajzolása",
  "drawPolygon": "Polygon rajzolása",
  "driveTime": "Vezetési idő",
  "dropPin": "Tű elhelyezése",
  "dynamicHTML": "Dinamikus HTML",
  "exportOptions": "Exportálási beállítások",
  "home": "Kiindulás",
  "image": "Kép",
  "infographics": "Infógrafika",
  "invalidValueRing": "Az értékeknek 0-1000 között kell lennie.",
  "invalidValueDTWT": "Az értékeknek 0-300 között kell lennie.",
  "km": "km",
  "makeDefault": "Legyen alapértelmezett",
  "miles": "mérföld",
  "minutes": "perc",
  "options": "Beállítások:",
  "pdf": "PDF",
  "print": "Nyomtatás",
  "radius": "Sugár",
  "removeDefault": "Alapértelmezett eltávolítása",
  "reports": "Jelentések",
  "rings": "Gyűrűk",
  "searchTextBox": "Keresés a szövegmezőben",
  "selectCountryOrRegion": "Válassza ki az országot vagy a régiót:",
  "thisEntryIsNotValid": "A megadott érték érvénytelen.",
  "time": "Idő",
  "walkTime": "Gyaloglási idő"
});