define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Aceda a Infografias e Relatórios que resumam indicadores-chave e dados de qualquer área.</div><br><div>Selecione um ponto ou polígono no mapa, pesquise um endereço ou local, desenhe um polígono ou coloque um alfinete no mapa para visualizar indicadores-chave e informações sobre a área.</div>",
  "defineWhichInfographics": "Definir infografia disponível no widget:",
  "defineWhichReports": "Definir relatórios disponíveis no widget:",
  "defaultValues": "Valores predefinidos:",
  "disable": "Desativar",
  "drawFreehandPolygon": "Desenhar Polígono à Mão",
  "drawPolygon": "Desenhar Polígono",
  "driveTime": "Tempo de condução",
  "dropPin": "Colocar Alfinete",
  "dynamicHTML": "HTML Dinâmico",
  "exportOptions": "Opções de Exportação:",
  "home": "Início",
  "image": "Imagem",
  "infographics": "Infográficos",
  "invalidValueRing": "Os valores devem estar no intervalo de 0 a 1000.",
  "invalidValueDTWT": "Os valores devem estar no intervalo de 0 a 300.",
  "km": "km",
  "makeDefault": "Criar predefinição",
  "miles": "milhas",
  "minutes": "minutos",
  "options": "Opções:",
  "pdf": "PDF",
  "print": "Imprimir",
  "radius": "Raio",
  "removeDefault": "Remover predefinição",
  "reports": "Relatórios",
  "rings": "Anéis",
  "searchTextBox": "Caixa de Texto de Pesquisa",
  "selectCountryOrRegion": "Selecionar país ou região:",
  "thisEntryIsNotValid": "Esta entrada não é válida.",
  "time": "Hora",
  "walkTime": "Tempo de Caminhada"
});