define({
  "_widgetLabel": "Uređivač atributa serije",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Naziv sloja",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Nema konfiguriranih slojeva koji se mogu uređivati",
  "editorPopupTitle": "Uređivač atributa serije",
  "editorPopupSaveBtn": "Spremi",
  "editorPopupMultipleValues": "",
  "clear": "Očisti",
  "featuresUpdated": "${0} / ${1} geoobjek(a)t(a) ažurirano",
  "featuresSelected": "${0} geoobjek(a)t(a) odabrano",
  "featuresSkipped": "Zaobiđeno",
  "featuresNoPermision": "Odabrano je ${0} geoobjekata ali nema dopuštenja za uređivanje.",
  "search": "Pretraži",
  "queryInput": "Unesite vrijednost za upit",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Ispravno postavite filtar.",
  "filterPopup": "Sloj za filtriranje",
  "filterAppend": "Ako u web karti za ovaj sloj već postoji filtar",
  "filterAppendOR": "Dodaj bilo koje izraze postojećem filtru karte",
  "filterAppendAND": "Dodaj sve izraze postojećem filtru karte",
  "cancel": "Odustani",
  "noValue": "Nema vrijednosti",
  "emptyString": "Prazan tekst",
  "existingValue": "Zadrži postojeću vrijednost",
  "newDate": "Novi datum",
  "valueChooser": "Odaberite/upišite vrijednost",
  "ok": "U redu",
  "drawBox": {
    "point": "Točka",
    "line": "Linija",
    "polyline": "Polilinija",
    "freehandPolyline": "Prostoručna polilinija",
    "extent": "Obuhvat",
    "polygon": "Poligon",
    "freehandPolygon": "Prostoručni poligon",
    "clear": "Očisti",
    "addPointToolTip": "Kliknite za odabir u ovom području",
    "addShapeToolTip": "Nacrtajte oblik da biste odabrali geoobjekt",
    "freehandToolTip": "Pritisnite i držite da biste nacrtali oblik za odabir geoobjekta",
    "startToolTip": "Nacrtajte oblik da biste odabrali geoobjekt"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Geoobjekt s ${0} vratio je nevažeći ID",
    "noSelectedLayers": "Nema odabranih slojeva sa zapisima koje treba ažurirati",
    "inputValueError": "Nevažeća vrijednost u obliku",
    "saveError": "Nije moguće spremiti ${0} geoobjekata",
    "requiredValue": "Obvezna vrijednost"
  }
});