define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Accédez à des infographies et rapports synthétisant les indicateurs et données clés sur une zone en particulier.</div><br><div>Sélectionnez un point ou un polygone sur la carte, recherchez une adresse ou un lieu, dessinez un polygone ou déposez une épingle sur la carte pour afficher les indicateurs et données clés concernant la zone.</div>",
  "defineWhichInfographics": "Définir les infographies disponibles dans le widget :",
  "defineWhichReports": "Définir les rapports disponibles dans le widget :",
  "defaultValues": "Valeurs par défaut :",
  "disable": "Désactiver",
  "drawFreehandPolygon": "Dessiner un polygone à main levée",
  "drawPolygon": "Dessiner un polygone",
  "driveTime": "Temps de conduite",
  "dropPin": "Placer une punaise",
  "dynamicHTML": "HTML dynamique",
  "exportOptions": "Options d’exportation :",
  "home": "Accueil",
  "image": "Image",
  "infographics": "Infographie",
  "invalidValueRing": "Les valeurs doivent être comprises entre 0 et 1 000.",
  "invalidValueDTWT": "Les valeurs doivent être comprises entre 0 et 300.",
  "km": "km",
  "makeDefault": "Définir par défaut",
  "miles": "miles",
  "minutes": "minutes",
  "options": "Options :",
  "pdf": "PDF",
  "print": "Imprimer",
  "radius": "Rayon",
  "removeDefault": "Supprimer l’élément par défaut",
  "reports": "Rapports",
  "rings": "Anneaux",
  "searchTextBox": "Zone de texte de recherche",
  "selectCountryOrRegion": "Sélectionner le pays ou la région",
  "thisEntryIsNotValid": "L’entrée n’est pas valide.",
  "time": "Durée",
  "walkTime": "Temps de marche"
});