define({
  "_widgetLabel": "Преобразуване на координати",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMРев.",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM (Универсална напречна проекция на Меркатор)",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Десетични градуси – географска ширина/географска дължина",
  "DDLongLatNotation": "Десетични градуси – географска дължина/географска ширина",
  "DDMLatLongNotation": "Градуси десетични минути – геаографска ширина/географска дължина",
  "DDMLongLatNotation": "Градуси десетични минути – географска дължина/географска ширина",
  "DMSLatLongNotation": "Градуси Минути Секунди – географска ширина/географска дължина",
  "DMSLongLatNotation": "Градуси Минути Секунди – географска дължина/географска ширина",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Буква на честотна лента",
  "UTMHemNotation": "UTM - Полукълбо (С/Ю)",
  "formatInput": "Формат на въвеждане",
  "copyAll": "Копиране на всичко",
  "copySuccessful": "Успешно копиране",
  "copyFailed": "Не може да се копира. Моля, като алтернатива използвайте ctrl+c.",
  "parseCoordinatesError": "Не може да се прави разбор на координатите. Моля, проверете входните си данни.",
  "comfirmInputNotation": "Потвърждаване на нотацията за входни данни",
  "latLongWarningMessage": "Входната координата е открита като имаща и префикс, и суфикс за стойността на географската ширина или дължина, координатата е върната поради префикса.",
  "inputLabel": "Въвеждане",
  "outputLabel": "Извеждане",
  "cancelButtonLabel": "Отказ",
  "applyButtonLabel": "Прилагане",
  "posNegPrefixLabel": "Добавете префикс „+/-“ съответно за положителни и отрицателни числа",
  "editCoordinateDialogTitle": "Задайте текстов формат за координатите",
  "rememberDecisionLabel": "Запомни решението ми и не ме питай отново.<br/>",
  "coordinateInputLabel": "Въведете координати или натиснете върху картата",
  "zoomLabel": "Мащабиране",
  "multipleNotationLabel": "намерени са нотации, които съответстват на въведеното от Вас. Моля, потвърдете кое бихте желали да използвате:",
  "copyToClipboard": "Копиране в клипборда",
  "formatOutput": "Изходен формат",
  "addNewNotation": "Добавяне на нова нотация",
  "notationAddedMessage": "Добавена е нова нотация",
  "addLabel": "Добавяне",
  "removeCoordinate": "Премахване на координата",
  "expandOutput": "Разширяване на изхода",
  "latitudeLabel": "Шир.",
  "longitudeLabel": "Дълж.",
  "quadrantLabel": "Квадрант",
  "keyLabel": "Ключ",
  "fifteenDegreeLabel": "15° квадр.",
  "oneDegreeLabel": "1° квадр.",
  "eastingLabel": "На изток",
  "northingLabel": "На север",
  "zoneLabel": "Зона",
  "bandLabel": "Честотна лента",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Кв. мрежа",
  "hemisphereLabel": "Полукълбо",
  "addPointLabel": "Добавяне на точка"
});