define({
  "_widgetLabel": "تحليل التهديدات",
  "threatAnalysisMainPageTitle": "على أساس دليل JCAT Counterterrorism",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "موقع الإدخال",
  "interactive": "بشكل تفاعلي",
  "fromCoord": "إحداثي ثابت",
  "existingFeature": "من المعالم الحالية",
  "threatAnalysisCoordInputLabel": "موقع التهديد",
  "enterCoords": "أدخل الإحداثيات",
  "threatAddPointToolTip": "إضافة موقع التهديد",
  "threatDrawPointToolTip": "انقر لإضافة موقع التهديد",
  "threatType": "نوع التهديد",
  "threatPlaceholder": "بدء الكتابة للبحث عن تهديد",
  "mandatoryLabel": "مسافة الإخلاء الإجبارية",
  "safeLabel": "مسافة الإخلاء الآمنة",
  "zoneTypeLabel": "نوع النطاق",
  "feetLabel": "قدم",
  "metersLabel": "أمتار",
  "unitsLabel": "وحدات",
  "threatGraphicLayer": "رسوم التهديدات",
  "settingsTitle": "إعدادات",
  "mandatoryButtonLabel": "تكوين إعدادات مسافة الإخلاء الإجبارية",
  "safeButtonLabel": "تكوين إعدادات توفير مأوى في مكان الحالة",
  "style": "نمط",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "شَرطَة",
    "esriSLSDashDot": "شَرطَة ونقطة",
    "esriSLSDashDotDot": "شرطة ونقطتين",
    "esriSLSDot": "نقطة",
    "esriSLSLongDash": "شرطة طويلة",
    "esriSLSLongDashDot": "شرطة ونقطة طويلين",
    "esriSLSNull": "خالِ",
    "esriSLSShortDash": "شَرطَة قصيرة",
    "esriSLSShortDashDot": "نقطة شرطة قصيرة",
    "esriSLSShortDashDotDot": "نقطة نقطة شرطة قصيرة",
    "esriSLSShortDot": "منطقة صغيرة",
    "esriSLSSolid": "متصل"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "للخلف",
    "esriSFSCross": "شكل متصالب",
    "esriSFSDiagonalCross": "قطري",
    "esriSFSForwardDiagonal": "للأمام",
    "esriSFSHorizontal": "أفقياً",
    "esriSFSNull": "خالِ",
    "esriSFSSolid": "متصل",
    "esriSFSVertical": "عمودي"
  },
  "resultsTitle": "النتائج",
  "publishTABtn": "نشر",
  "layerName": "اسم الطبقة المنشورة",
  "invalidLayerName": "يجب ألا يحتوي اسم الطبقة إلا على أحرف أبجدية رقمية وتسطير سفلي",
  "missingLayerNameMessage": "يجب إدخال اسم طبقة صحيح قبل النشر",
  "publishingFailedLayerExists": "فشل النشر: لديك خدمة معالم باسم {0}. يرجى اختيار اسم طبقة مختلف.",
  "checkService": "فحص الخدمة: {0}.",
  "createService": "إنشاء الخدمة: {0}.",
  "unableToCreate": "يتعذر إنشاء: {0}",
  "addToDefinition": "إضافة إلى تعريف: {0}",
  "successfullyPublished": "تم نشر طبقة الويب بنجاح",
  "successfullyAppended": "تم إرفاق معالم جديدة بطبقة الويب",
  "manageWebLayerText": "إدارة مشهد الويب",
  "userRole": "تحديث إنشاء الخدمة لأن المستخدم لا يتمتع بأذونات",
  "retrieveExistingLayerError": "يتعذر استرداد {0}. يرجى النشر باستخدام اسم طبقة مختلف.",
  "publishToNewLayer": "نشر النتائج إلى طبقة معلم جديدة",
  "layerNameExists": "اسم الطبقة موجود بالفعل يرجى استخدام اسم طبقة مختلف.",
  "pipeBombLabel": "قنبلة أنبوبية",
  "suicideBombLabel": "قنبلة انتحارية",
  "briefcaseLabel": "حقيبة الملفات",
  "carLabel": "سيارة",
  "suvVanLabel": "سيارة دفع رباعي/سيارة نقل",
  "smallDeliveryTruckLabel": "شاحنة تسليم صغيرة",
  "containerWaterTruckLabel": "شاحنة ماء/شاحنة بحاوية",
  "semiTrailerLabel": "نصف مقطورة",
  "transparencyLabel": "الشفافية",
  "outline": "الحدود",
  "fill": "تعبئة (لا ينطبق اللون إلا عند تعيين النمط إلى مُصمَت)",
  "createBtn": "إنشاء مناطق",
  "clearBtn": "مسح",
  "invalidNumberMessage": "القيمة الافتراضية غير صحيحة",
  "invalidRangeMessage": "يجب أن تكون القيمة أكبر من 0",
  "parseCoordinatesError": "يتعذر تحليل الإحداثيات. يرجى التحقق من مدخلاتك.",
  "selectDrawModeLabel": "تحديد وضع الرسم",
  "selectFeatureLabel": "تحديد معلم من هذه الطبقة",
  "fireBallDiameterLable": "قطر كرة اللهب",
  "lpgSafeDistanceLable": "المسافة الآمنة",
  "threatTypeCatagoryLabel": "فئة نوع التهديد",
  "fireballButtonLabel": "تكوين إعدادات قطر كرة اللهب",
  "safeDistanceButtonLabel": "تكوين إعدادات المسافة الآمنة",
  "chemicalThreatCatagoryLabel": "كيميائي",
  "lpgThreatCatagoryLabel": "غاز نفطي مسال",
  "chemicalThreatLabel": "التهديد الكيميائي",
  "lpgThreatLabel": "تهديد الغاز النفطي المسال",
  "fireBallDiameterFieldAlias": "قطر كرة لهب غاز نفطي مسال",
  "lpgSafeDistanceFieldAlias": "المسافة الآمنة للغاز النفطي المسال",
  "smallLPGTank": "صهريج غاز نفطي مسال صغير",
  "largeLPGTank": "صهريج غاز نفطي مسال كبير",
  "commercialResidentialLPGTank": "صهريج غاز نفطي مسال تجاري/سكني",
  "smallLPGTruck": "شاحنة غاز نفطي مسال صغيرة",
  "semiTankerLPG": "غاز نفطي مسال في نصف صهريج"
});