define({
  "_widgetLabel": "Prvok hlásenia",
  "select": "Vybrať",
  "draw": "Nakresliť",
  "chooseALayer": "Vybrať vrstvu",
  "clickAFeature": "Kliknite na prvok na mape, aby ste ho vybrali.",
  "loadingFeatures": "Získavam podrobnosti o zvolenom prvku...",
  "errorTitle": "Chyba",
  "errorIdentify": "Identifikovať chyby prvkov. Prosím, pre podrobnosti skontrolujte záznamy konzoly.",
  "infoWindowTitle": "Podrobnosti",
  "layerLabel": "Názov vrstvy",
  "reviewStatusLabel": "Stav kontroly",
  "selectReviewStatusAdd": "Pridať prvok",
  "selectReviewStatusDelete": "Zmazať prvok",
  "selectReviewStatusMove": "Posunúť prvok",
  "selectReviewStatusReshape": "Upraviť tvar prvku",
  "drawReviewStatusMissing": "Chýbajúci prvok(y)",
  "drawReviewStatusPosition": "Chyba polohy",
  "drawReviewStatusShape": "Chyba tvaru",
  "drawReviewStatusAttribute": "Chyba atribútu",
  "notesLabel": "Poznámky",
  "severityLabel": "Závažnosť",
  "reportedByLabel": "Nahlásené",
  "reportedByDefault": "anonymný",
  "reportButton": "Prehľad",
  "reportMessage": "Hlásenie obdržané",
  "errorReportMessage": "Pri nahlasovaní vášho prvku sa vyskytla chyba",
  "drawErrorInstructions": "Zvoliť bod, líniu alebo polygón a nakresliť chybu geometrie na mape:",
  "errorMapService": "Pri získavaní informácií z mapovej služby sa vyskytla chyba",
  "noFeatureSelected": "Na zakliknutom mieste sa nenašli žiadne prvky",
  "selectFeatureMapPoint": "Kliknite pre výber prvku",
  "drawFeatureMapPoint": "Kliknite pre pridanie bodu",
  "popupMessage": "Správa",
  "popupError": "Chyba",
  "manyFeaturesSelected": "Bol nájdený viac ako jeden prvok. Prosím priblížte a zvoľte prvok na nahlásenie."
});