define({
  "transparencyLabel": "Transparenz",
  "outline": "Umrisslinie",
  "fill": "Füllung (Farbe wird nur angewendet, wenn der Style auf Vollfarbe festgelegt ist)",
  "style": "Style",
  "selectOpLayerLabel": "Operationalen Layer für die Ergebnisse auswählen",
  "selectDefaultMeasurementLabel": "Standardmesseinheit auswählen",
  "helpIconTooltip": "Die Liste der operationalen Layer wird mit Layern der aktuellen Webkarte, die einen Polygon-Geometrietyp aufweisen, gefüllt.",
  "lineStyles": {
    "esriSLSDash": "Strich",
    "esriSLSDashDot": "Strich-Punkt",
    "esriSLSDashDotDot": "Strich-Punkt-Punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Langer Strich",
    "esriSLSLongDashDot": "Langer Strich-Punkt",
    "esriSLSNull": "NULL",
    "esriSLSShortDash": "Kurzer Strich",
    "esriSLSShortDashDot": "Kurzer Strich-Punkt",
    "esriSLSShortDashDotDot": "Kurzer Strich-Punkt-Punkt",
    "esriSLSShortDot": "Kurzer Punkt",
    "esriSLSSolid": "Durchgezogen"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Rückwärts",
    "esriSFSCross": "Kreuzförmig",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Vorwärts",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "NULL",
    "esriSFSSolid": "Vollfarbe",
    "esriSFSVertical": "Vertikal"
  },
  "threatTypeLabel": "Bedrohungstyp",
  "generalLabel": "Allgemein",
  "addThreatTypesLabel": "Bedrohungstyp hinzufügen",
  "actions": "Aktionen",
  "newThreatTypePopupLabel": "Neuer Bedrohungstyp",
  "units": "Einheiten",
  "chooseDefaultThreatLabel": "Standardmäßigen Bedrohungstyp auswählen",
  "defaultThreatTypePopUpLabel": "Standardmäßige Bedrohungstypen",
  "editThreatLabel": "Bedrohung bearbeiten",
  "defaultThreatTypeIconTooltip": "Liste der standardmäßigen Bedrohungstypen",
  "uniqueThreatTypeMsg": "Geben Sie einen eindeutigen Bedrohungstyp an. Ein Bedrohungstyp mit diesem Namen ist bereits vorhanden.",
  "requiredMsg": "Dies ist ein Pflichtfeld",
  "unitMeasureLabel": "Entfernungen sind in {0} angegeben",
  "chooseDefaultThreatTypeIconLabel": "Aus Standard auswählen",
  "pipeBombLabel": "Rohrbombe",
  "suicideBombLabel": "Selbstmordattentat",
  "briefcaseLabel": "Aktenkoffer",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/Van",
  "smallDeliveryTruckLabel": "Kleiner Lieferwagen",
  "containerWaterTruckLabel": "Container-Lkw/Wassertankwagen",
  "semiTrailerLabel": "Sattelschlepper",
  "chemicalThreatLegendLabel": "Chemische Bedrohung",
  "lpgThreatLegendLabel": "Bedrohung durch Flüssiggas",
  "smallLPGTank": "Kleiner Flüssiggastank",
  "largeLPGTank": "Großer Flüssiggastank",
  "commercialResidentialLPGTank": "Gewerblicher/privater Flüssiggastank",
  "smallLPGTruck": "Kleiner Flüssiggas-Lkw",
  "semiTankerLPG": "Flüssiggas-Tankauflieger",
  "threatDescriptionColLabel": "Bedrohungsbeschreibung",
  "addThreatZoneButtonLabel": "Gefahrenzone hinzufügen",
  "zoneDescColLabel": "Zonenbeschreibung",
  "distanceLabel": "Entfernung (${unitAbbr})",
  "threatTypeHelp": "<p>Stellen Sie sicher, dass die folgenden Bedingungen für einen Bedrohungstyp erfüllt sind:<br/><ul><li>Der Bedrohungstyp darf nicht leer sein, und er muss eindeutig sein.</li><li>Die Bedrohung muss mindestens eine gültige Zone aufweisen.</li><li>Die Zonenbeschreibung muss für eine Bedrohung eindeutig sein.</li></ul><p/>",
  "descriptionLabel": "Beschreibung",
  "newThreatZonePopupLabel": "Neue Gefahrenzone",
  "editThreatZonePopupLabel": "Gefahrenzone bearbeiten",
  "uniqueZoneDescriptionMsg": "Geben Sie eine eindeutige Zonenbeschreibung an. Eine Zonenbeschreibung mit diesem Namen ist bereits vorhanden.",
  "symbologyColLabel": "Symbolisierung",
  "zoneDescriptionColLabel": "Zonenbeschreibung",
  "uniqueZoneRequiredMsg": "Der Zonenname muss eindeutig sein für",
  "interactive": "Interaktiv",
  "fromCoord": "Feste Koordinate",
  "existingFeature": "Aus vorhandenen Features",
  "defaultInputLocationLabel": "Standardmäßige Eingabeposition",
  "defaultInputLayer": "Standardmäßiger Eingabe-Layer",
  "defaultThreatType": "Standardmäßiger Bedrohungstyp",
  "selectLabel": "Auswählen",
  "mandatoryLabel": "Entfernung für obligatorische Evakuierung",
  "safeLabel": "Entfernung für sichere Evakuierung",
  "lpgSafeDistanceLable": "Sichere Entfernung",
  "fireBallDiameterLable": "Feuerball-Durchmesser"
});