define({
  "locatorUrl": "로케이터 URL",
  "set": "설정",
  "locatorName": "로케이터 이름",
  "locatorExample": "Example",
  "countryCode": "국가 또는 지역 코드",
  "eg": "예: ",
  "countryCodeHint": "이 값을 비워 두면 모든 국가와 지역이 검색됩니다.",
  "minCandidateScore": "최소 후보 점수",
  "minCandidateScoreHint": "이 값을 비워 두면 최소 후보 점수인 90이 사용됨",
  "enableSingleField": "단일 필드 옵션",
  "singleFieldHint": "주소 데이터가 단일 필드에 있게 됨",
  "enableMultiField": "여러 필드 옵션",
  "multiFieldHint": "주소 데이터가 여러 필드에 있게 됨",
  "enableXYField": "X/Y 필드 옵션",
  "xyFieldHint": "데이터에 X/Y 좌표값이 포함됨",
  "instructionGeocode": "로케이터 서비스를 추가하고 구성합니다.",
  "invalidUrlTip": "${URL} URL이 잘못되었거나 접근할 수 없습니다.",
  "geocodeTabLabel": "위치 설정",
  "lookupList": "인식할 필드 이름",
  "isRecognized": "아래 테이블의 필드 이름은 이 필드에 자동으로 인식됨",
  "needsEditablePointLayers": "편집 가능한 포인트 레이어가 웹 맵에 하나 이상 포함되어 있어야 합니다.",
  "editpageAlias": "별칭",
  "configureFields": "레이어 필드 구성",
  "configureSingleFields": "단일 주소 필드 구성",
  "configureMultiFields": "여러 주소 필드 구성",
  "configureXYFields": "X/Y 필드 구성",
  "noFields": "표시할 필드를 하나 또는 여러 개 정의하려면 편집 작업을 사용하세요.",
  "display": "디스플레이",
  "duplicate": "중복 항목 찾기",
  "duplicateTip": "이 필드에서 소스 파일과 대상 레이어 사이의 동일한 값을 검색합니다./n 동일한 일치 항목을 발견한 경우 파일의 레코드를 찾을 수 없으며 중복 항목으로 플래그 지정됩니다.",
  "noSelectField": "먼저 피처 레이어 옵션을 선택합니다.",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X(경도)",
  "xyFieldsLabelY": "Y(위도)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Easting",
  "northing": "Northing",
  "lon": "경도",
  "lat": "위도",
  "layerOptionHint": "데이터를 제출할 레이어를 선택합니다.",
  "layerFieldTitle": "대상 레이어",
  "tempSymbolHint": "피처를 표시하는 데 사용할 심볼을 선택합니다.",
  "tempSymbolTitle": "심볼 표시",
  "maxRecords": "최대 레코드 수",
  "maxRecordsHint": "찾을 최대 레코드 수",
  "searchRadius": "검색 반경",
  "searchRadiusHint": "레이어에서 중복 피처를 검색할 거리",
  "requiresInteger": "숫자 값을 입력합니다.",
  "requiresInteger0100": "0에서 100 사이의 숫자 값을 입력합니다.",
  "requiresLocator": "올바른 로케이터를 하나 이상 추가합니다.",
  "layerFields": "레이어 설정",
  "layerFieldsHint": "원본 필드에 매핑할 대상 레이어의 필드를 지정합니다.",
  "locatorError": "로케이터가 잘못되었거나 접속할 수 없습니다.",
  "optionNotMatch": "필드 옵션이 로케이터 전반에서 일관되지 않습니다. 페일오버가 예상대로 작동하지 않을 수 있습니다.",
  "targetLayerTabTitle": "대상 레이어",
  "locationSettingsTabTitle": "위치 설정",
  "generalSettingsTabTitle": "일반 설정",
  "addTargetLayersLabel": "대상 레이어 추가",
  "introductoryText": "위젯의 교육용 콘텐츠용 생성",
  "defaultStartPageInstructions": "이 위젯을 사용하면 파일에서 가져온 데이터를 처리하여 맵의 선택된 레이어에 제출할 수 있습니다.<br/> <br/> 파일 내의 값은 쉼표, 탭, 세미콜론 또는 수직 막대로 구분되어 있어야 합니다.",
  "noTargetLayerConfiguredErrorMsg": "구성된 대상 레이어가 없음",
  "noFieldsForTargetLayer": "대상 레이어의 설정이 정의되지 않았습니다.",
  "locationSettingsNotConfigured": "위치 설정이 제대로 구성되지 않았습니다.",
  "questionMark": "?"
});