define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Dodaj punkt, klikając na mapie",
  "addPolygon": "Utwórz poligon, rysując na mapie",
  "addFreehandPolygon": "Utwórz poligon odręczny, rysując na mapie",
  "addRingsDtWt": "Dodaj pierścienie, czas przejazdu lub czas pokonania trasy pieszej.",
  "apply": "Zastosuj",
  "back": "Wstecz",
  "colon": ":",
  "creditInformation": "Informacje o kredytach",
  "customPolygon": "Poligon niestandardowy",
  "driveTime": "Czas przejazdu",
  "esriInfographics": "Infografiki Esri",
  "esriReports": "Raporty Esri",
  "headerDescription_km": "kilometr",
  "headerDescription_miles": "mila",
  "headerDescription_minutes": "minuta",
  "infographics": "Infografiki",
  "invalidValueRing": "Wartości muszą należeć do zakresu od 0 do 1 000.",
  "invalidValueDTWT": "Wartości muszą należeć do zakresu od 0 do 300.",
  "km": "km",
  "miles": "mil",
  "minutes": "minut(y)",
  "myInfographics": "Moje infografiki",
  "myReports": "Moje raporty",
  "noPermissions": "Na Twoim koncie nie można uruchomić widżetu Business Analyst.  Aby uruchomić widżet Business Analyst, administrator instytucji musi nadać Tobie <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">uprawnienia</a> do wzbogacania danych przestrzennych i analizy sieciowej, a także przydzielić <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredyty</a>.",
  "geServiceNotConfigured": "Nie można uruchomić widżetu Business Analyst w tym portalu, ponieważ nie została w nim skonfigurowana usługa <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">wzbogacania danych przestrzennych</a>.",
  "dirRoutingServiceNotConfigured": "Nie można uruchomić widżetu Business Analyst w tym portalu, ponieważ nie została w nim skonfigurowana usługa <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">wskazówek dojazdu i wyznaczania tras</a>.",
  "geAndDirRoutingServicesNotConfigured": "Nie można uruchomić widżetu Business Analyst w tym portalu, ponieważ nie zostały w nim skonfigurowane usługi <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">wzbogacania danych przestrzennych</a> oraz <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">wskazówek dojazdu i wyznaczania tras</a>.",
  "radii": "promienie",
  "radius": "Promień",
  "radius_lowercase": "promień",
  "reports": "Raporty",
  "ring": "Pierścień",
  "rings": "Pierścienie",
  "runInfographic": "Uruchom infografikę",
  "runReport": "Uruchom raport",
  "selectPointOrPolygon": "Wybierz na mapie punkt lub poligon, wyszukaj adres lub miejsce, narysuj poligon albo umieść na mapie szpilkę, aby wyświetlić kluczowe wskaźniki i informacje o tym obszarze.",
  "selectReport": "Wybierz raport",
  "selectTemplate": "Wybierz szablon",
  "sharedInfographics": "Udostępnione infografiki",
  "sharedReports": "Udostępnione raporty",
  "thisEntryIsNotValid": "Ten wpis nie jest prawidłowy.",
  "time": "Czas",
  "walkTime": "Czas pokonania trasy pieszej",
  "widgetDescription": "Uzyskaj dostęp do infografik i raportów podsumowujących kluczowe wskaźniki i dane w dowolnym obszarze.",
  "None": "Wybierz..."
});