define({
  "_widgetLabel": "Tlačiť",
  "title": "Názov mapy",
  "format": "Formát",
  "layout": "Rozloženie",
  "settings": "Rozšírené",
  "labels": "Označenia",
  "showLabels": "Zobraziť označenia",
  "mapScaleExtent": "Mierka/rozsah mapy",
  "preserve": "Zachovať",
  "mapScale": "mierka mapy",
  "mapExtent": "rozsah mapy",
  "forceScale": "Vynútiť mierku",
  "getCurrentScale": "aktuálna",
  "mapMetadata": "Metaúdaje rozloženia",
  "author": "Autor",
  "copyright": "Autorské právo",
  "fullLayoutOptions": "Úplné možnosti rozloženia",
  "scaleBarUnit": "Jednotka grafickej mierky",
  "scaleBarUnitsMetric": "Metrické jednotky grafickej mierky",
  "scaleBarUnitsNonMetric": "Nemetrické jednotky grafickej mierky",
  "unitsMiles": "Míle",
  "unitsKilometers": "Kilometre",
  "unitsMeters": "Metre",
  "unitsFeet": "Stopy",
  "unitsYards": "Yardy",
  "unitsNauticalMiles": "Námorné míle",
  "lncludeLegend": "Zahrnúť legendu",
  "printQualityOptions": "Kvalita tlače",
  "dpi": "DPI",
  "mapOnlyOptions": "MAP_ONLY veľkosť",
  "width": "Šírka (px)",
  "height": "Výška (px)",
  "print": "Tlačiť",
  "clearList": "Vymazať výtlačky",
  "creatingPrint": "Vytváranie výtlačku",
  "printError": "Chyba, skúste to znova",
  "forceFeatureAttributes": "Atribúty prvku",
  "includeFeatureAttributes": "Zahrnúť atribúty",
  "outputSR": "Výstupný súradnicový systém",
  "invalidWkid": "Neplatný WKID kód"
});