define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Infografice și rapoarte care rezumă indicatorii șid atele principale pentru orice zonă.</div><br><div>Selectați un punct sau un poligon pe hartă, căutați o adresă sau un loc, trasați un poligon sau fixați un ac pe hartă pentru a vedea indicatoare cheie și informații referitoare la zonă.</div>",
  "defineWhichInfographics": "Definiți ce grafice informative sunt disponibile în widget:",
  "defineWhichReports": "Definiți ce rapoarte sunt disponibile în widget:",
  "defaultValues": "Valori implicite:",
  "disable": "Dezactivare",
  "drawFreehandPolygon": "Trasare poligon liber",
  "drawPolygon": "Trasare poligon",
  "driveTime": "Timp de conducere",
  "dropPin": "Fixare ac",
  "dynamicHTML": "HTML dinamic",
  "exportOptions": "Opțiuni de export:",
  "home": "Prima pagină",
  "image": "Imagine",
  "infographics": "Grafice informative",
  "invalidValueRing": "Valorile trebuie să fie cuprinse între 0 și 1.000.",
  "invalidValueDTWT": "Valorile trebuie să fie cuprinse între 0 și 300.",
  "km": "km",
  "makeDefault": "Setare ca implicit",
  "miles": "mile",
  "minutes": "minute",
  "options": "Opţiuni:",
  "pdf": "PDF",
  "print": "Imprimare",
  "radius": "Rază",
  "removeDefault": "Eliminați implicit",
  "reports": "Rapoarte",
  "rings": "Inele",
  "searchTextBox": "Căutare casetă text",
  "selectCountryOrRegion": "Selectați țara sau regiunea:",
  "thisEntryIsNotValid": "Această intrare nu este validă.",
  "time": "Timp",
  "walkTime": "Timp de deplasare"
});