define({
  "transparencyLabel": "Prozirnost",
  "outline": "Obris",
  "fill": "Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",
  "style": "Stil",
  "selectOpLayerLabel": "Odabir operativnog sloja za rezultate",
  "selectDefaultMeasurementLabel": "Odabir zadane mjerne jedinice",
  "helpIconTooltip": "Operativni sloj popunjen je slojevima poligonalnog tipa geometrije iz trenutačne web-karte.",
  "lineStyles": {
    "esriSLSDash": "Linija s crticom",
    "esriSLSDashDot": "Linija s crticom i točkom",
    "esriSLSDashDotDot": "Linija s crticom i dvije točke",
    "esriSLSDot": "Točka",
    "esriSLSLongDash": "Duga crtica",
    "esriSLSLongDashDot": "Duga crtica i točka",
    "esriSLSNull": "Nema vrijednosti",
    "esriSLSShortDash": "Kratka crtica",
    "esriSLSShortDashDot": "Kratka crtica i točka",
    "esriSLSShortDashDotDot": "Kratka crtica i dvije točke",
    "esriSLSShortDot": "Kratka točka",
    "esriSLSSolid": "Puna linija"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unatrag",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Naprijed",
    "esriSFSHorizontal": "Vodoravni",
    "esriSFSNull": "Nema vrijednosti",
    "esriSFSSolid": "Puna linija",
    "esriSFSVertical": "Uspravno"
  },
  "threatTypeLabel": "Vrsta prijetnje",
  "generalLabel": "Općenito",
  "addThreatTypesLabel": "Dodaj vrstu prijetnje",
  "actions": "Radnje",
  "newThreatTypePopupLabel": "Nova vrsta prijetnje",
  "units": "Jedinice",
  "chooseDefaultThreatLabel": "Odaberi zadanu vrstu prijetnje",
  "defaultThreatTypePopUpLabel": "Zadane vrste prijetnje",
  "editThreatLabel": "Uredi prijetnju",
  "defaultThreatTypeIconTooltip": "Popis zadanih vrsta prijetnje",
  "uniqueThreatTypeMsg": "Unesite jedinstvenu vrstu prijetnje. Vrsta prijetnje s tim nazivom već postoji.",
  "requiredMsg": "Ovo je polje obavezno",
  "unitMeasureLabel": "Udaljenosti su u: {0}",
  "chooseDefaultThreatTypeIconLabel": "Izaberi iz zadanih opcija",
  "pipeBombLabel": "Cijevna bomba",
  "suicideBombLabel": "Bomba za samoubilački napad",
  "briefcaseLabel": "Aktovka",
  "carLabel": "Automobil",
  "suvVanLabel": "SUV/KAMION",
  "smallDeliveryTruckLabel": "Mali kamion za dostavu",
  "containerWaterTruckLabel": "Kamion za prijevoz kontejnera/vode",
  "semiTrailerLabel": "Poluprikolica",
  "chemicalThreatLegendLabel": "Kemijska prijetnja",
  "lpgThreatLegendLabel": "LPG prijetnja",
  "smallLPGTank": "Mali LPG spremnik",
  "largeLPGTank": "Veliki LPG spremnik",
  "commercialResidentialLPGTank": "Komercijalni/stambeni LPG spremnik",
  "smallLPGTruck": "Mali LPG kamion",
  "semiTankerLPG": "LPG polucisterna",
  "threatDescriptionColLabel": "Opis prijetnje",
  "addThreatZoneButtonLabel": "Dodaj zonu prijetnje",
  "zoneDescColLabel": "Opis zone",
  "distanceLabel": "Udaljenost (${unitAbbr})",
  "threatTypeHelp": "<p>Provjerite jesu li sljedeći zahtjevi zadovoljeni za vrstu prijetnje:<br/><ul><li>Vrsta prijetnje ne može biti prazna te mora biti jedinstvena</li><li>Prijetnja mora imati najmanje jednu valjanu zonu</li><li>Opis zone mora biti jedinstven za prijetnju</li></ul><p/>",
  "descriptionLabel": "Opis",
  "newThreatZonePopupLabel": "Nova zona prijetnje",
  "editThreatZonePopupLabel": "Uredi zonu prijetnje",
  "uniqueZoneDescriptionMsg": "Unesite jedinstven opis zone, opis zone s ovim nazivom već postoji.",
  "symbologyColLabel": "Simbologija",
  "zoneDescriptionColLabel": "Opis zone",
  "uniqueZoneRequiredMsg": "Naziv zone mora biti jedinstven za",
  "interactive": "Interaktivno",
  "fromCoord": "Fiksna koordinata",
  "existingFeature": "Iz postojećih geoobjekata",
  "defaultInputLocationLabel": "Zadana lokacija unosa",
  "defaultInputLayer": "Zadani sloj unosa",
  "defaultThreatType": "Zadana vrsta prijetnje",
  "selectLabel": "Odaberi",
  "mandatoryLabel": "Obavezna udaljenost za evakuaciju",
  "safeLabel": "Sigurna udaljenost za evakuaciju",
  "lpgSafeDistanceLable": "Sigurna udaljenost",
  "fireBallDiameterLable": "Promjer vatrene kugle"
});