define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Pristupite infografikama i izvješćima koji sažimaju ključne pokazatelje i podatke za bilo koje područje.</div><br><div>Odaberite točku ili poligon na karti, tražite adresu ili mjesto, nacrtajte poligon ili stavite pribadaču na kartu kako bi vidjeli ključne indikatore ili informacije o području.</div>",
  "defineWhichInfographics": "Definirajte koje su infografike dostupne u widgetu:",
  "defineWhichReports": "Definirajte koja su izvješća dostupna u widgetu:",
  "defaultValues": "Zadane vrijednosti:",
  "disable": "Onemogući",
  "drawFreehandPolygon": "Nacrtaj poligon prostoručno",
  "drawPolygon": "Nacrtaj poligon",
  "driveTime": "Vrijeme vožnje",
  "dropPin": "Ispusti pribadaču",
  "dynamicHTML": "Dinamični HTML",
  "exportOptions": "Opcije izvoza:",
  "home": "Početna lokacija",
  "image": "Slika",
  "infographics": "Grafički prikaz",
  "invalidValueRing": "Vrijednosti moraju biti u rasponu od 0 do 1000.",
  "invalidValueDTWT": "Vrijednosti moraju biti u rasponu od 0 do 300.",
  "km": "km",
  "makeDefault": "Postavi zadano",
  "miles": "milja",
  "minutes": "minuta",
  "options": "Opcije:",
  "pdf": "PDF",
  "print": "Ispis",
  "radius": "Polumjer",
  "removeDefault": "Ukloni zadano",
  "reports": "Izvješća",
  "rings": "Prsteni",
  "searchTextBox": "Tekstni okvir pretrage",
  "selectCountryOrRegion": "Odaberite državu ili regiju:",
  "thisEntryIsNotValid": "Unos nije važeći.",
  "time": "Vrijeme",
  "walkTime": "Vrijeme hodanja"
});