define({
  "locatorUrl": "Lokaliseringsfils-URL",
  "set": "Ange",
  "locatorName": "Namn på placeringsfil",
  "locatorExample": "Exempel",
  "countryCode": "Lands- eller regionkoder",
  "eg": "t.ex. ",
  "countryCodeHint": "Om du lämnar det här värdet tomt sker sökningen i alla länder och regioner",
  "minCandidateScore": "Minsta kandidatpoäng",
  "minCandidateScoreHint": "Om det här fältet lämnas tomt används en minsta kandidatpoäng på 90",
  "enableSingleField": "Alternativ för enstaka fält",
  "singleFieldHint": "Adressdata är i ett enda fält",
  "enableMultiField": "Alternativ för flera fält",
  "multiFieldHint": "Adressdata är i flera fält",
  "enableXYField": "Alternativ för X/Y-fält",
  "xyFieldHint": "Data innehåller X/Y-koordinatvärden",
  "instructionGeocode": "Lägg till och konfigurera lokaliseringsfilstjänster.",
  "invalidUrlTip": "URL:en ${URL} är ogiltig eller går inte att öppna.",
  "geocodeTabLabel": "Platsinställningar",
  "lookupList": "Fältnamn som ska kännas igen",
  "isRecognized": "Fältnamnen i tabellen nedan känns automatiskt igen för det här fältet",
  "needsEditablePointLayers": "Webbkartan måste innehålla minst ett redigerbart punktlager.",
  "editpageAlias": "Alias",
  "configureFields": "Konfigurera lagerfält",
  "configureSingleFields": "Konfigurera ett enstaka adressfält",
  "configureMultiFields": "Konfigurera flera adressfält",
  "configureXYFields": "Konfigurera X/Y-fält",
  "noFields": "Definiera ett eller flera fält att visa med hjälp av åtgärden Redigera",
  "display": "Visa",
  "duplicate": "Hitta dubblett",
  "duplicateTip": "Sök i det här fältet efter identiska värden mellan källagret och mållagret./n När en identisk matchning upptäcks hittas inte posten från filen och flaggas som en dubblett.",
  "noSelectField": "Välj alternativet Geoobjektlager först",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (longitud)",
  "xyFieldsLabelY": "Y (latitud)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Östlig",
  "northing": "Nordlig",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Välj lager att skicka data till:",
  "layerFieldTitle": "Mållager",
  "tempSymbolHint": "Välj den symbol som ska användas för att visa geoobjekten.",
  "tempSymbolTitle": "Visningssymbol",
  "maxRecords": "Max antal poster",
  "maxRecordsHint": "Maximalt antal poster att hitta",
  "searchRadius": "Sökradie",
  "searchRadiusHint": "Avstånd till sökning efter dubblerade geoobjekt från lager",
  "requiresInteger": "Ange ett numeriskt värde.",
  "requiresInteger0100": "Ange ett numeriskt värde mellan 0 och 100",
  "requiresLocator": "Lägg till minst en giltig lokaliseringsfil.",
  "layerFields": "Lagerinställningar",
  "layerFieldsHint": "Ange fält från mållagret som ska karteras till källfälten.",
  "locatorError": "Lokaliseringsfilen är ogiltig eller inte tillgänglig.",
  "optionNotMatch": "Fältalternativen är inte konsekventa mellan lokaliseringsfiler. Redundansen kanske inte fungerar som väntat.",
  "targetLayerTabTitle": "Mållager",
  "locationSettingsTabTitle": "Platsinställningar",
  "generalSettingsTabTitle": "Allmänna inställningar",
  "addTargetLayersLabel": "Lägg till mållager",
  "introductoryText": "Skapa instruktionsinnehåll för widgeten",
  "defaultStartPageInstructions": "Den här widgeten hjälper till med bearbetning och överföring av data från en fil till det valda lagret i kartan.<br/> <br/>Värden i filen måste avgränsas med komma, tabb, semikolon eller vertikalstreck.",
  "noTargetLayerConfiguredErrorMsg": "Inget mållager är konfigurerat",
  "noFieldsForTargetLayer": "Lagerinställningar är inte definierade för mållagret",
  "locationSettingsNotConfigured": "Platsinställningarna är inte korrekt konfigurerade"
});