define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<div><br>قم بالوصول إلى الرسومات البيانية والتقارير التي تلخص المؤشرات والبيانات الرئيسية لأي منطقة.</div><br><div>حدد نقطة أو مضلعًا على الخريطة، أو ابحث عن عنوان أو مكان، أو ارسم مضلعًا، أو أسقط دبوسًا على الخريطة لعرض المؤشرات والمعلومات الرئيسية حول المنطقة.</div>",
  "defineWhichInfographics": "حدد أي مخططات معلومات بيانية متوفرة في عنصر واجهة المستخدم:",
  "defineWhichReports": "حدد أي تقارير متوفرة في عنصر واجهة المستخدم:",
  "defaultValues": "القيم الافتراضية:",
  "disable": "تعطيل",
  "drawFreehandPolygon": "رسم مضلع يدويًا",
  "drawPolygon": "رسم مضلع",
  "driveTime": "وقت القيادة",
  "dropPin": "إسقاط",
  "dynamicHTML": "HTML ديناميكي",
  "exportOptions": "خيارات التصدير:",
  "home": "الصفحة الرئيسية",
  "image": "صورة",
  "infographics": "إنفوجرافكس",
  "invalidValueRing": "يجب أن تكون القيم ضمن نطاق من 0 إلى 1000.",
  "invalidValueDTWT": "يجب أن تكون القيم ضمن نطاق من 0 إلى 300.",
  "km": "كيلومتر",
  "makeDefault": "اجعلها افتراضية",
  "miles": "أميال",
  "minutes": "دقائق",
  "options": "خيارات:",
  "pdf": "PDF",
  "print": "طباعة",
  "radius": "نصف القطر",
  "removeDefault": "إزالة الافتراضي",
  "reports": "تقارير",
  "rings": "حلقات",
  "searchTextBox": "البحث عن المربع النصي",
  "selectCountryOrRegion": "تحديد البلد أو المنطقة:",
  "thisEntryIsNotValid": "هذا الإدخال غير صالح.",
  "time": "الوقت",
  "walkTime": "زمن السير"
});