define({
  "feedbackStyleLabel": "รูปแบบผลตอบกลับของระยะทางและทิศทาง",
  "showTabLabel": "แสดงแท็บทั้งหมด",
  "tabErrorMessage": "โปรดเลือกอย่างน้อยหนึ่งแท็บในกลุ่ม \"รูปแบบความคิดเห็นเกี่ยวกับระยะทางและทิศทาง\"",
  "lineLabel": "เส้น",
  "circleLabel": "วงกลม",
  "ellipseLabel": "วงรี",
  "ringsLabel": "วงแหวน",
  "transparency": "โปร่งแสง",
  "operationalLineLayerSelectLabel": "เลือกชั้นข้อมูลโพลีไลน์ดำเนินการสำหรับผลลัพธ์ไลน์และวงแหวน",
  "operationalPolygonLayerSelectLabel": "เลือกชั้นข้อมูลโพลีไลน์ดำเนินการสำหรับผลลัพธ์วงกลมและวงรี",
  "helpIconPolylineTooltip": "รายการชั้นข้อมูลดำเนินการจะถูกเติมด้วยชั้นข้อมูลจากเว็บแมปปัจจุบันที่เป็นประเภทรูปทรงเรขาคณิตโพลีไลน์",
  "helpIconPolygonTooltip": "รายการชั้นข้อมูลดำเนินการ จะถูกนำเข้าแบบอัตโนมัติพร้อมชั้นข้อมูลจากเว็บแมปปัจจุบัน ซึ่งเป็นประเภทรูปทรงเรขาคณิตโพลีกอน",
  "feedbackResultsLayerLabel": "ระยะทางและทิศทางข้อเสนอแนะผลลัพธ์ชั้นข้อมูล",
  "editSymbologyHint": "คำแนะนำ: คลิกที่ไอคอนแสดงตัวอย่างเพื่อแก้ไขสัญลักษณ์",
  "feedbackTextColorLabel": "ผลตอบรับสีป้ายกำกับข้อความ",
  "feedbackTextSizeLabel": "ผลตอบรับขนาดป้ายกำกับข้อความ",
  "previewLabel": "แสดงตัวอย่าง",
  "lineSymbologyPopupTittle": "สัญลักษณ์เส้น",
  "circleSymbologyPopupTittle": "สัญลักษณ์วงกลม",
  "ellipseSymbologyPopupTittle": "สัญลักษณ์วงรี",
  "ringSymbologyPopupTittle": "สัญลักษณ์วงแหวน"
});