define({
  "_widgetLabel": "Εργαλείο έξυπνης επεξεργασίας",
  "_featureAction_SmartEditor": "Εργαλείο έξυπνης επεξεργασίας",
  "noEditPrivileges": "Ο λογαριασμός σας δεν έχει δικαίωμα δημιουργίας ή τροποποίησης δεδομένων.",
  "widgetActive": "Ενεργή",
  "widgetNotActive": "Μη ενεργή",
  "pressStr": "Πατήστε ",
  "ctrlStr": " CTRL ",
  "snapStr": " για να ενεργοποιηθεί η λειτουργία αγκίστρωσης",
  "noAvailableTempaltes": "Δεν υπάρχουν διαθέσιμα πρότυπα",
  "editorCache": " - Εργαλείο επεξεργασίας Cache",
  "presetFieldAlias": "Πεδίο",
  "presetValue": "Προκαθορισμένη τιμή",
  "usePresetValues": " Χρήση προκαθορισμένων τιμών (μόνο σε νέα στοιχεία)",
  "editGeometry": " Επεξεργασία γεωμετρικού τύπου",
  "savePromptTitle": "Αποθήκευση στοιχείου",
  "savePrompt": "Θέλετε να αποθηκευτεί το τρέχον στοιχείο;",
  "deletePromptTitle": "Διαγραφή στοιχείου",
  "deleteAttachment": "Διαγραφή συνημμένου",
  "deletePrompt": "Είστε βέβαιοι ότι θέλετε να διαγράψετε το επιλεγμένο στοιχείο;",
  "attachmentLoadingError": "Σφάλμα στην αποστολή των συνημμένων",
  "attachmentSaveDeleteWarning": "Προειδοποίηση: Οι αλλαγές στα συνημμένα αποθηκεύτηκαν αυτόματα",
  "autoSaveEdits": "Αυτόματη αποθήκευση νέων στοιχείων",
  "addNewFeature": "Δημιουργία νέου στοιχείου",
  "featureCreationFailedMsg": "Δεν είναι δυνατή η δημιουργία νέας εγγραφής/νέου στοιχείου.",
  "relatedItemTitle": "Σχετικός πίνακας/Σχετικό θεματικό επίπεδο",
  "relatedFeatureCount": "Θεματικό επίπεδο «${layerTitle}» με ${featureCount} στοιχεία",
  "createNewFeatureLabel": "Δημιουργία νέου στοιχείου για το θεματικό επίπεδο «${layerTitle}»",
  "invalidRelationShipMsg": "Βεβαιωθείτε ότι το πεδίο πρωτεύοντος κλειδιού '${parentKeyField}' έχει έγκυρη τιμή.",
  "pendingFeatureSaveMsg": "Αποθηκεύστε τις αλλαγές στο στοιχείο προτού δημιουργήσετε σχετικό στοιχείο.",
  "attachmentsRequiredMsg": "(*) Απαιτούνται συνημμένα.",
  "coordinatePopupTitle": "Μετακίνηση στοιχείου στην τοποθεσία XY",
  "coordinatesSelectTitle": "Σύστημα συντεταγμένων:",
  "mapSpecialReferenceDropdownOption": "Χωρική αναφορά χάρτη",
  "latLongDropdownOption": "Γεωγραφικό πλάτος/Γεωγραφικό μήκος",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Συντεταγμένη:",
  "xAttributeTextBoxLabel": "Συντεταγμένη στον άξονα X:",
  "yAttributeTextBoxLabel": "Συντεταγμένη στον άξονα Y:",
  "latitudeTextBoxLabel": "Γεωγραφικό πλάτος:",
  "longitudeTextBoxLabel": "Γεωγραφικό μήκος:",
  "presetGroupFieldsLabel": "Το όνομα «${groupName}» θα εφαρμοστεί στα πεδία των εξής θεματικών επιπέδων:",
  "presetGroupNoFieldsLabel": "Το όνομα «${groupName}» δεν έχει συσχετισμένα πεδία.",
  "groupInfoLabel": "Πληροφορίες για την ομάδα «${groupName}»",
  "editGroupInfoIcon": "Επεξεργασία τιμής για την ομάδα «${groupName}»",
  "filterEditor": {
    "all": "Όλοι",
    "noAvailableTempaltes": "Δεν υπάρχουν διαθέσιμα πρότυπα",
    "searchTemplates": "Αναζήτηση προτύπων",
    "filterLayerLabel": "Φιλτράρισμα θεματικών επιπέδων"
  },
  "invalidConfiguration": "To widget δεν είναι διαμορφωμένο ή τα θεματικά επίπεδα στη διαμόρφωση δεν βρίσκονται πλέον στο χάρτη. Ανοίξτε την εφαρμογή στη λειτουργία Εργαλείο δημιουργίας και αναδιαμορφώστε το widget.",
  "geometryServiceURLNotFoundMSG": "Αδύνατη η λήψη Geometry Service URL",
  "clearSelection": "Κλείσιμο",
  "refreshAttributes": "Ενημέρωση δυναμικών γνωρισμάτων στοιχείων",
  "automaticAttributeUpdatesOn": "Αυτόματη ενημέρωση γνωρισμάτων στοιχείων: ΕΝΕΡΓΟΠΟΙΗΣΗ",
  "automaticAttributeUpdatesOff": "Αυτόματη ενημέρωση γνωρισμάτων στοιχείων: ΑΠΕΝΕΡΓΟΠΟΙΗΣΗ",
  "moveSelectedFeatureToGPS": "Μετακίνηση επιλεγμένου στοιχείου στην τρέχουσα τοποθεσία μέσω GPS",
  "moveSelectedFeatureToXY": "Μετακίνηση επιλεγμένου στοιχείου στην τοποθεσία XY",
  "mapNavigationLocked": "Πλοήγηση στον χάρτη: Κλειδωμένη",
  "mapNavigationUnLocked": "Πλοήγηση στον χάρτη: Ξεκλειδωμένη",
  "copyFeatures": {
    "title": "Αντιγραφή στοιχείων",
    "createFeatures": "Δημιουργία στοιχείων",
    "createSingleFeature": "Δημιουργία 1 στοιχείου πολλαπλής γεωμετρίας",
    "noFeaturesSelectedMessage": "Κανένα επιλεγμένο στοιχείο",
    "selectFeatureToCopyMessage": "Επιλέξτε στοιχεία προς αντιγραφή.",
    "multipleFeatureSaveWarning": "Σημείωση: Αν δημιουργήσετε πολλαπλά στοιχεία χρησιμοποιώντας τη δυνατότητα αντιγραφής, όλα τα στοιχεία θα αποθηκευτούν αμέσως.",
    "copyFeatureUpdateGeometryError": "Δεν είναι δυνατή η ενημέρωση της γεωμετρίας των επιλεγμένων στοιχείων.",
    "canNotSaveMultipleFeatureWarning": "Σημείωση: Δεν είναι δυνατή η αντιγραφή πολλαπλών στοιχείων με χρήση της ίδιας τιμής για πεδία μοναδικής τιμής. Επιλέξτε μόνο ένα στοιχείο.",
    "createOnlyOneMultipartFeatureWarning": "Σημείωση: Μπορείτε να δημιουργήσετε μόνο ένα πολυτμηματικό στοιχείο."
  },
  "addingFeatureError": "Σφάλμα κατά την προσθήκη επιλεγμένων στοιχείων στο θεματικό επίπεδο. Προσπαθήστε ξανά.",
  "addingFeatureErrorCount": "Απέτυχε η αντιγραφή '${copyFeatureErrorCount}' στοιχείων.",
  "selectingFeatureError": "Σφάλμα κατά την επιλογή στοιχείων στο θεματικό επίπεδο. Προσπαθήστε ξανά.",
  "customSelectOptionLabel": "Επιλογή στοιχείων προς αντιγραφή",
  "noFeatureSelectedMessage": "Δεν έχει επιλεχθεί κανένα στοιχείο.",
  "multipleFeatureSaveMessage": "Όλα τα στοιχεία θα αποθηκευτούν αμέσως. Θέλετε οπωσδήποτε να προχωρήσετε;",
  "relativeDates": {
    "dateTypeLabel": "Τύπος ημερομηνίας",
    "valueLabel": "Τιμή",
    "fixed": "Καθορισμένη",
    "current": "Τρέχουσα",
    "past": "Παλαιότερη",
    "future": "Μελλοντική",
    "popupTitle": "Επιλογή τιμής",
    "hintForFixedDateType": "Υπόδειξη: Η καθορισμένη τιμή ημερομηνίας και ώρας θα χρησιμοποιηθεί ως προκαθορισμένη προεπιλεγμένη τιμή.",
    "hintForCurrentDateType": "Υπόδειξη: Η τρέχουσα τιμή ημερομηνίας και ώρας θα χρησιμοποιηθεί ως προκαθορισμένη προεπιλεγμένη τιμή.",
    "hintForPastDateType": "Υπόδειξη: Η καθορισμένη τιμή θα αφαιρεθεί από την τρέχουσα τιμή ημερομηνίας και ώρας για να υπολογιστεί η προκαθορισμένη προεπιλεγμένη τιμή.",
    "hintForFutureDateType": "Υπόδειξη: Η καθορισμένη τιμή θα προστεθεί στην τρέχουσα τιμή ημερομηνίας και ώρας για να υπολογιστεί η προκαθορισμένη προεπιλεγμένη τιμή.",
    "noDateDefinedTooltip": "Δεν έχει καθοριστεί ημερομηνία.",
    "relativeDateWarning": "Πρέπει να καθορίσετε μια τιμή για ημερομηνία και ώρα προκειμένου να μπορέσετε να αποθηκεύσετε την προεπιλεγμένη προκαθορισμένη τιμή.",
    "customLabel": "Προσαρμοσμένη",
    "layerLabel": "Θεματικό επίπεδο",
    "domainFieldHintLabel": "Η επιλεγμένη τιμή είναι domain κωδικοποιημένων τιμών. Θα χρησιμοποιηθεί η τιμή: ${domainValue}"
  },
  "valuePicker": {
    "popupTitle": "Επιλογή τιμής",
    "popupHint": "Το τρέχον στοιχείο τέμνει πολλαπλά στοιχεία. Επιλέξτε τιμή για το αντίστοιχο πεδίο.",
    "buttonTooltip": "Επιλογή τιμής από πολλαπλά τεμνόμενα στοιχεία"
  },
  "uniqueValueErrorMessage": "Η τιμή στο «${fieldName}» ήδη υπάρχει. Καταχωρίστε νέα τιμή.",
  "requiredFields": {
    "displayMsg": "Τα απαιτούμενα πεδία δεν επιτρέπεται να είναι κενά. Καταχωρίστε τιμές για κοινά πεδία παρακάτω.",
    "popupTittle": "Απαιτούμενα πεδία",
    "foundNullRecordCount": "${fieldName} (Βρέθηκαν σε ${count} εγγραφές.)"
  },
  "cantLocateUserLocation": "Δεν ήταν δυνατός ο εντοπισμός της τοποθεσίας σας."
});