define({
  "taskUrl": "URL for utsiktsområdetjeneste",
  "portalURL": "Angi URL-en til ArcGIS Online-organisasjonen eller Portal for ArcGIS",
  "portalURLError": "Den konfigurerte URL-en til ArcGIS Online-organisasjonen eller Portal for ArcGIS er ikke gyldig.",
  "privilegeError": "Brukerrollen din har kan ikke utføre analyser. Hvis du vil utføre analyser, må administratoren i organisasjonen gi deg bestemte <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">rettigheter</a>.",
  "noServiceError": "Høydeanalysetjeneste er ikke tilgjengelig. Sjekk konfigurasjonen for ArcGIS Online-organisasjonen eller Portal for ArcGIS.",
  "maximumRangeMessage": "Største observasjonsområde må være større enn minste observasjonsområde og kan ikke være mer enn ${limit} ${units}.",
  "serviceURLPlaceholder": "Oppgi URL for geoprosesseringsoppgave for utsiktsområde",
  "setTask": "Angi",
  "setTaskTitle": "Angi geoprosesseringsoppgave for utsiktsområde",
  "serviceURLError": "Geoprosesseringsoppgaven du prøver å konfigurere med dette miniprogrammet, er ugyldig. Angi en gyldig URL for geoprosesseringsoppgave for utsiktsområde",
  "defaultMilsForAnglesLabel": "Sett streker for vinkler som standard",
  "defaultObserverHeightLabel": "Standardenhet for tilskuerhøyde",
  "defaultObservableDistanceLabel": "Standardenhet for observerbar avstand",
  "defaultObserveHeightLabel": "Standard tilskuerhøyde",
  "defaultMinimumObservableDistanceLabel": "Standard for minste observerbare avstand",
  "defaultMaximumObservableDistanceLabel": "Standard for største observerbare avstand",
  "units": {
    "miles": "Miles",
    "kilometers": "Kilometer",
    "feet": "Fot",
    "meters": "Meter",
    "yards": "Yard",
    "nauticalMiles": "Nautiske mil"
  },
  "helpIconTooltip": "Listen med operative lag fylles med lagene fra gjeldende webkart som er av geometritypen polygon.",
  "selectOperationalLayerLabel": "Velg et operativt lag til resultater",
  "lineOfSightTabTitle": "Siktlinje",
  "symbologyTabTitle": "Symboler",
  "transparency": "Gjennomsiktighet",
  "outline": "Omriss",
  "fill": "Fyll (farge brukes bare når heldekkende er valgt som stil)",
  "style": "Stil",
  "selectOpLayerLabel": "Velg et operativt lag til resultater",
  "selectDefaultMeasurementLabel": "Velg en standard måleenhet",
  "visibleSectionLabel": "Synlig seksjon",
  "nonVisibleSectionLabel": "Usynlig seksjon",
  "visibleSectionButtonLabel": "Konfigurer innstillinger for synlig seksjon",
  "nonVisibleSectionButtonLabel": "Konfigurer innstillinger for usynlig seksjon",
  "colorPicker": "Fargevelgeren",
  "lineStyles": {
    "esriSLSDash": "Strek",
    "esriSLSDashDot": "Strek prikk",
    "esriSLSDashDotDot": "Strek prikk prikk",
    "esriSLSDot": "Prikk",
    "esriSLSLongDash": "Lang strek",
    "esriSLSLongDashDot": "Lang strek-prikk",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort strek",
    "esriSLSShortDashDot": "Kort strek-prikk",
    "esriSLSShortDashDotDot": "Kort strek-prikk-prikk",
    "esriSLSShortDot": "Kort prikk",
    "esriSLSSolid": "Heltrukken"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakover",
    "esriSFSCross": "Kryss",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Fremover",
    "esriSFSHorizontal": "Vannrett",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Heltrukken",
    "esriSFSVertical": "Loddrett"
  }
});