define({
  "taskUrl": "URL сервісу видимості",
  "portalURL": "Вкажіть URL для вашої організації ArcGIS Online або Portal for ArcGIS",
  "portalURLError": "Налаштований URL для вашої організації ArcGIS Online або Portal for ArcGIS не дійсний.",
  "privilegeError": "Користувач не може виконувати аналіз. Для виконання аналізу адміністратор вашої організації повинен надати вам певні <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">права</a>.",
  "noServiceError": "Сервіс аналізу висот не доступний. Перевірте конфігурацію ArcGIS для вашої організації ArcGIS Online або Portal for ArcGIS.",
  "maximumRangeMessage": "Максимальний діапазон, який спостерігається, повинен бути більшим, ніж мінімальний діапазон, який спостерігається, та не може становити більше ${limit} ${units}.",
  "serviceURLPlaceholder": "Введіть URL задачі геообробки видимості",
  "setTask": "Задати",
  "setTaskTitle": "Задати задачу геообробки видимості",
  "serviceURLError": "Задача геообробки, яку ви намагаєтесь налаштувати за допомогою цього віджету, недійсна. Виберіть дійсний URL задачі геообробки видимості",
  "defaultMilsForAnglesLabel": "Задати мілі для кутів за замовчуванням",
  "defaultObserverHeightLabel": "Одиниця висоту спостерігача за замовчуванням",
  "defaultObservableDistanceLabel": "Одиниця довжини, що спостерігається, за замовчуванням",
  "defaultObserveHeightLabel": "Висота спостерігача за замовчуванням",
  "defaultMinimumObservableDistanceLabel": "Мінімальна довжина, що спостерігається, за замовчуванням",
  "defaultMaximumObservableDistanceLabel": "Максимальна довжина, що спостерігається, за замовчуванням",
  "units": {
    "miles": "Милі",
    "kilometers": "Кілометри",
    "feet": "Фути",
    "meters": "Метри",
    "yards": "Ярди",
    "nauticalMiles": "Морські милі"
  },
  "helpIconTooltip": "Робочий шар заповнюється шарами з поточної веб-карти, що відносяться до типу геометрії «полігон».",
  "selectOperationalLayerLabel": "Вибрати робочий шар для результатів",
  "lineOfSightTabTitle": "Лінія погляду",
  "symbologyTabTitle": "Умовні позначення",
  "transparency": "Прозорість",
  "outline": "Контур",
  "fill": "Заливка (колір застосовується, тільки коли для стиля вибрано параметр «Суцільний»)",
  "style": "Стиль",
  "selectOpLayerLabel": "Вибрати робочий шар для результатів",
  "selectDefaultMeasurementLabel": "Вибрати одиниці виміру за замовчуванням",
  "visibleSectionLabel": "Видима секція",
  "nonVisibleSectionLabel": "Невидима секція",
  "visibleSectionButtonLabel": "Налаштувати параметри видимої секції",
  "nonVisibleSectionButtonLabel": "Налаштувати параметри невидимої секції",
  "colorPicker": "Панель вибору кольору",
  "lineStyles": {
    "esriSLSDash": "Пунктир",
    "esriSLSDashDot": "Штрихпунктир",
    "esriSLSDashDotDot": "Штрихпунктир з двома крапками",
    "esriSLSDot": "Точковий пунктир",
    "esriSLSLongDash": "Пунктир з довгим тире",
    "esriSLSLongDashDot": "Штрихпунктир з довгим тире",
    "esriSLSNull": "Нуль",
    "esriSLSShortDash": "Пунктир з коротким тире",
    "esriSLSShortDashDot": "Штрихпунктир з коротким тире",
    "esriSLSShortDashDotDot": "Штрихпунктир з коротким тире та двома крапками",
    "esriSLSShortDot": "Штрихпунктир з коротким тире",
    "esriSLSSolid": "Суцільний"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Перехрестя",
    "esriSFSDiagonalCross": "Діагональ",
    "esriSFSForwardDiagonal": "Вперед",
    "esriSFSHorizontal": "Горизонтальна",
    "esriSFSNull": "Нуль",
    "esriSFSSolid": "Суцільний",
    "esriSFSVertical": "Вертикальна"
  }
});