define({
  "_widgetLabel": "Изчертаване",
  "selectDrawMode": "Избор на режим изчертаване",
  "clear": "Изчистване",
  "point": "Точка",
  "line": "Линия",
  "polyline": "Полилиния",
  "freehandPolyline": "Произволна полилиния",
  "triangle": "Триъгълник",
  "extent": "Плик",
  "circle": "Окръжност",
  "ellipse": "Елипса",
  "polygon": "Полигон",
  "freehandPolygon": "Произволен полигон",
  "text": "Текст",
  "style": "Стил",
  "alpha": "Прозрачност",
  "width": "Ширина",
  "size": "Размер",
  "color": "Цвят",
  "markerColor": "Цвят на маркер",
  "outlineColor": "Цвят на контур",
  "lineColor": "Цвят на линия",
  "fillColor": "Цвят за запълване",
  "showMeasurements": "Показване на измервания",
  "showLocationMeasurement": "Показване измерване на местоположение",
  "showAreaMeasurement": "Показване измерване на област",
  "showDistanceMeasurement": "Показване измерване на разстояние",
  "showDistanceMeasurementForLine": "Показване измерване на дължина",
  "showDistanceMeasurementForPolygon": "Показване измерване на периметър",
  "locationToggleOn": "Натиснете бутона за превключване, за да покажете измерване на местоположение",
  "locationToggleOff": "Натиснете бутона за превключване, за да скриете измерване на местоположение",
  "areaToggleOn": "Натиснете бутона за превключване, за да покажете измерване на област",
  "areaToggleOff": "Натиснете бутона за превключване, за да скриете измерване на област",
  "distanceForLineToggleOn": "Натиснете бутона за превключване, за да покажете измерване на дължина",
  "distanceForLineToggleOff": "Натиснете бутона за превключване, за да скриете измерване на дължина",
  "distanceForPolygonToggleOn": "Натиснете бутона за превключване, за да покажете измерване на периметър",
  "distanceForPolygonToggleOff": "Натиснете бутона за превключване, за да скриете измерване на периметър",
  "areaUnits": "Единици за област",
  "distanceUnits": "Единици за разстояние",
  "kilometers": "Километри",
  "miles": "Мили",
  "meters": "Метри",
  "feet": "Фута",
  "yards": "Ярда",
  "nauticalmiles": "Морски мили",
  "squareKilometers": "Квадратни километри",
  "squareMiles": "Квадратни мили",
  "acres": "Акри",
  "hectares": "Хектара",
  "squareMeters": "Квадратни метри",
  "squareFeet": "Квадратни фута",
  "squareYards": "Квадратни ярда",
  "undo": "Отмяна",
  "redo": "Връщане",
  "results": "Резултати",
  "points": "Точки",
  "lines": "Линии",
  "areas": "Области",
  "locationLabel": "Местоположение: ${value}",
  "areaLabel": "Област: ${value} ${unit}",
  "distanceLabel": "Разстояние: ${value} ${unit}",
  "distanceLabelForLine": "Дължина: ${value} ${unit}",
  "distanceLabelForPolygon": "Периметър: ${value} ${unit}"
});