define({
  "transparencyLabel": "Διαφάνεια",
  "outline": "Περίγραμμα",
  "fill": "Γέμισμα (Το χρώμα εφαρμόζεται μόνο όταν έχετε καθορίσει τη χρήση του συμπαγούς στιλ.)",
  "style": "Στιλ",
  "selectOpLayerLabel": "Επιλέξτε ένα λειτουργικό θεματικό επίπεδο για αποτελέσματα.",
  "selectDefaultMeasurementLabel": "Επιλέξτε μια προεπιλεγμένη μονάδα μέτρησης.",
  "helpIconTooltip": "Η λίστα των λειτουργικών θεματικών επιπέδων συμπληρώνεται με θεματικά επίπεδα τύπου γεωμετρίας πολυγώνου από τον τρέχοντα web χάρτη.",
  "lineStyles": {
    "esriSLSDash": "Παύλα",
    "esriSLSDashDot": "Παύλα τελεία",
    "esriSLSDashDotDot": "Παύλα τελεία τελεία",
    "esriSLSDot": "Τελεία",
    "esriSLSLongDash": "Μεγάλη παύλα",
    "esriSLSLongDashDot": "Μεγάλη παύλα τελεία",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Μικρή παύλα",
    "esriSLSShortDashDot": "Μικρή παύλα τελεία",
    "esriSLSShortDashDotDot": "Μικρή παύλα τελεία τελεία",
    "esriSLSShortDot": "Μικρή τελεία",
    "esriSLSSolid": "Συμπαγές"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Προς τα πίσω",
    "esriSFSCross": "Σταυρός",
    "esriSFSDiagonalCross": "Διαγώνια",
    "esriSFSForwardDiagonal": "Προώθηση",
    "esriSFSHorizontal": "Οριζόντια",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Συμπαγές",
    "esriSFSVertical": "Κατακόρυφα"
  },
  "threatTypeLabel": "Τύπος απειλής",
  "generalLabel": "Γενική",
  "addThreatTypesLabel": "Προσθήκη τύπου απειλής",
  "actions": "Ενέργειες",
  "newThreatTypePopupLabel": "Νέος τύπος απειλής",
  "units": "Μονάδες",
  "chooseDefaultThreatLabel": "Επιλογή προεπιλεγμένου τύπου απειλής",
  "defaultThreatTypePopUpLabel": "Προεπιλεγμένοι τύποι απειλής",
  "editThreatLabel": "Επεξεργασία απειλής",
  "defaultThreatTypeIconTooltip": "Λίστα προεπιλεγμένων τύπων απειλής",
  "uniqueThreatTypeMsg": "Καταχωρίστε έναν μοναδικό τύπο απειλής. Ο τύπος απειλής με το όνομα αυτό ήδη υπάρχει.",
  "requiredMsg": "Αυτό το πεδίο είναι υποχρεωτικό",
  "unitMeasureLabel": "Οι αποστάσεις είναι σε {0}.",
  "chooseDefaultThreatTypeIconLabel": "Επιλογή από προεπιλεγμένους τύπους",
  "pipeBombLabel": "Βόμβα σε μεταλλικό σωλήνα",
  "suicideBombLabel": "Βόμβα αυτοκτονίας",
  "briefcaseLabel": "Χαρτοφύλακας",
  "carLabel": "Αυτοκίνητο",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Μικρό φορτηγό παραδόσεων",
  "containerWaterTruckLabel": "Φορτηγό με κοντέινερ/Υδροφόρα",
  "semiTrailerLabel": "Ημιρυμουλκούμενο",
  "chemicalThreatLegendLabel": "Χημική απειλή",
  "lpgThreatLegendLabel": "Απειλή λόγω LPG",
  "smallLPGTank": "Μικρή δεξαμενή LPG",
  "largeLPGTank": "Μεγάλη δεξαμενή LPG",
  "commercialResidentialLPGTank": "Εμπορική/Οικιακή δεξαμενή LPG",
  "smallLPGTruck": "Μικρό φορτηγό LPG",
  "semiTankerLPG": "Ημιβυτιοφόρο LPG",
  "threatDescriptionColLabel": "Περιγραφή απειλής",
  "addThreatZoneButtonLabel": "Προσθήκη ζώνης απειλής",
  "zoneDescColLabel": "Περιγραφή ζώνης",
  "distanceLabel": "Απόσταση (${unitAbbr})",
  "threatTypeHelp": "<p>Βεβαιωθείτε ότι πληρούνται οι ακόλουθες προϋποθέσεις για έναν τύπο απειλής:<br/><ul><li>Ο τύπος απειλής δεν μπορεί να είναι κενός και πρέπει να είναι μοναδικός</li><li>Η απειλή πρέπει να έχει τουλάχιστον μία έγκυρη ζώνη</li><li>Η περιγραφή ζώνης πρέπει να είναι μοναδική για μια απειλή</li></ul><p/>",
  "descriptionLabel": "Περιγραφή",
  "newThreatZonePopupLabel": "Νέα ζώνη απειλής",
  "editThreatZonePopupLabel": "Επεξεργασία ζώνης απειλής",
  "uniqueZoneDescriptionMsg": "Καταχωρίστε μια μοναδική περιγραφή ζώνης. Η περιγραφή ζώνηςμε το όνομα αυτό ήδη υπάρχει.",
  "symbologyColLabel": "Συμβολισμός",
  "zoneDescriptionColLabel": "Περιγραφή ζώνης",
  "uniqueZoneRequiredMsg": "Το όνομα ζώνης πρέπει να είναι μοναδικό για το",
  "interactive": "Διαδραστικά",
  "fromCoord": "Σταθερή συντεταγμένη",
  "existingFeature": "Από υπάρχοντα στοιχεία",
  "defaultInputLocationLabel": "Προεπιλεγμένη τοποθεσία εισόδου",
  "defaultInputLayer": "Προεπιλεγμένο θεματικό επίπεδο εισόδου",
  "defaultThreatType": "Προεπιλεγμένος τύπος απειλής",
  "selectLabel": "Επιλογή",
  "mandatoryLabel": "Υποχρεωτική απόσταση εκκένωσης",
  "safeLabel": "Ασφαλής απόσταση εκκένωσης",
  "lpgSafeDistanceLable": "Ασφαλής απόσταση",
  "fireBallDiameterLable": "Διάμετρος fireball"
});