define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Pasiekite infografikus ir ataskaitas, kurios apibendrina bet kurios teritorijos svarbiausius rodiklius ir duomenis.</div><br><div>Žemėlapyje pasirinkite tašką arba poligoną, ieškokite adreso ar vietos, apibrėžkite poligoną arba padėkite smeigtuką žemėlapyje, jei norite peržiūrėti pagrindinius indikatorius ir informaciją apie teritoriją.</div>",
  "defineWhichInfographics": "Apibrėžkite, kurie infografikai pasiekiami valdiklyje:",
  "defineWhichReports": "Apibrėžkite, kurios ataskaitos pasiekiamos valdiklyje:",
  "defaultValues": "Numatytosios reikšmės:",
  "disable": "Išjungti",
  "drawFreehandPolygon": "Laisvai brėžti poligoną",
  "drawPolygon": "Brėžti plotą",
  "driveTime": "Važiavimo laikas",
  "dropPin": "Smeigtukas",
  "dynamicHTML": "Dinaminis HTML",
  "exportOptions": "Eksportavimo parinktys:",
  "home": "Pradžia",
  "image": "Paveikslėlis",
  "infographics": "Infografikai",
  "invalidValueRing": "Reikšmės turi būti nuo 0 iki 1 000.",
  "invalidValueDTWT": "Reikšmės turi būti nuo 0 iki 300.",
  "km": "km",
  "makeDefault": "Nustatyti kaip numatytąjį",
  "miles": "mylios",
  "minutes": "min.",
  "options": "Parinktys:",
  "pdf": "PDF",
  "print": "Spausdinti",
  "radius": "Spindulys",
  "removeDefault": "Pašalinti numatytąjį",
  "reports": "Ataskaitos",
  "rings": "Žiedai",
  "searchTextBox": "Paieškos teksto laukas",
  "selectCountryOrRegion": "Pasirinkite šalį arba regioną:",
  "thisEntryIsNotValid": "Šis įrašas yra netinkamas.",
  "time": "Laikas",
  "walkTime": "Ėjimo laikas"
});