define({
  "taskUrl": "Belátható terület szolgáltatási URL-címe",
  "portalURL": "Adja meg az ArcGIS Online szervezet vagy a Portal for ArcGIS URL-címét",
  "portalURLError": "Az ArcGIS Online szervezet vagy a Portal for ArcGIS konfigurált URL-címe nem érvényes.",
  "privilegeError": "Az Ön felhasználói szerepe nem alkalmas az elemzés elvégzésére. Az elemzések végrehajtásához az Ön szervezetének adminisztrátora által adott megfelelő <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank”a>jogosultság</a> szükséges.",
  "noServiceError": "A magasságelemzési szolgáltatás nem érhető el. Ellenőrizze az ArcGIS Online vagy a Portal for ArcGIS konfigurációját.",
  "serviceURLPlaceholder": "Adja meg a belátható terület téradatfeldolgozási feladatának URL-címét",
  "setTask": "Beállítás",
  "setTaskTitle": "Belátható terület téradatfeldolgozási feladatának beállítása",
  "serviceURLError": "A widgettel konfigurálni kívánt téradatfeldolgozási feladat érvénytelen. Adja meg egy olyan belátható terület téradatfeldolgozási feladatának URL-címét, amely érvényes.",
  "defaultMilsForAnglesLabel": "Ezredek beállítása alapértelmezettként a szögekhez",
  "defaultObserverHeightLabel": "Alapértelmezett megfigyelési pozíció mértékegysége",
  "defaultObservableDistanceLabel": "Alapértelmezett megfigyelhető távolság mértékegysége",
  "units": {
    "miles": "Mérföld",
    "kilometers": "Kilométer",
    "feet": "Láb",
    "meters": "Méter",
    "yards": "Yard",
    "nauticalMiles": "Tengeri mérföld"
  },
  "helpIconTooltip": "Az operatív réteget a rendszer olyan rétegekkel tölti fel az aktuális webtérképből, amelyek poligon típusú geometriával rendelkeznek.",
  "selectOperationalLayerLabel": "Válasszon operatív réteget az eredmények számára",
  "lineOfSightTabTitle": "Rálátás",
  "symbologyTabTitle": "Szimbólumrendszer",
  "transparency": "Átlátszóság",
  "outline": "Körvonal",
  "fill": "Kitöltés (a Szín beállítás csak az egyszínű stílus beállítása esetén érhető el)",
  "style": "Stílus",
  "selectOpLayerLabel": "Válasszon operatív réteget az eredmények számára",
  "selectDefaultMeasurementLabel": "Válasszon alapértelmezett mértékegységet",
  "visibleSectionLabel": "Látható szakasz",
  "nonVisibleSectionLabel": "Nem látható szakasz",
  "visibleSectionButtonLabel": "Látható szakasz beállításainak konfigurálása",
  "nonVisibleSectionButtonLabel": "Nem látható szakasz beállításainak konfigurálása",
  "colorPicker": "Színválasztó",
  "lineStyles": {
    "esriSLSDash": "Szaggatott",
    "esriSLSDashDot": "Vonal-pont",
    "esriSLSDashDotDot": "Vonal-pont-pont",
    "esriSLSDot": "Pont",
    "esriSLSLongDash": "Hosszú vonal",
    "esriSLSLongDashDot": "Hosszú vonal-pont",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Rövid vonal",
    "esriSLSShortDashDot": "Rövid vonal-pont",
    "esriSLSShortDashDotDot": "Rövid vonal-pont-pont",
    "esriSLSShortDot": "Rövid pont",
    "esriSLSSolid": "Egyszínű"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Hátra",
    "esriSFSCross": "Kereszt",
    "esriSFSDiagonalCross": "Átlós",
    "esriSFSForwardDiagonal": "Előre",
    "esriSFSHorizontal": "Vízszintes",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Egyszínű",
    "esriSFSVertical": "Függőleges"
  }
});