define({
  "locatorUrl": "כתובת URL של מגדיר עיגון כתובות",
  "set": "הגדר",
  "locatorName": "שם מגדיר עיגון כתובות",
  "locatorExample": "דוגמה",
  "countryCode": "קודי ארצות או אזורים",
  "eg": "לדוגמה ",
  "countryCodeHint": "השארת הערך הזה ריק תפעיל חיפוש בכל הארצות והאזורים",
  "minCandidateScore": "ציון מועמד מינימלי",
  "minCandidateScoreHint": "השארת הערך הזה ריק תביא לשימוש בציון מועמד מינימילי של 90",
  "enableSingleField": "אפשרויות שדה בודד",
  "singleFieldHint": "נתוני הכתובת יופיעו בשדה בודד",
  "enableMultiField": "אפשרויות שדות מרובים",
  "multiFieldHint": "נתוני הכתובת יופיעו בשדות מרובים",
  "enableXYField": "אפשרויות שדה X/Y",
  "xyFieldHint": "הנתונים יכילו ערכי X/Y של קואורדינטות",
  "instructionGeocode": "הוסף והגדר שירותי מדריך עיגון כתובות",
  "invalidUrlTip": "ה-URL ‏${URL} שגוי או אינו נגיש.",
  "geocodeTabLabel": "הגדרות מיקום",
  "lookupList": "שמות שדות לזיהוי",
  "isRecognized": "שמות השדות בטבלה הבאה מזוהים אוטומטית עבור שדה זה",
  "needsEditablePointLayers": "ה-Webmap חייב להכיל לפחות שכבת נקודות אחת הניתנת לעריכה.",
  "editpageAlias": "כינוי",
  "configureFields": "הגדר שדות שכבה",
  "configureSingleFields": "הגדר שדה כתובת בודד",
  "configureMultiFields": "הגדר שדות כתובת מרובים",
  "configureXYFields": "הגדר שדות X/Y",
  "noFields": "השתמש בפעולת העריכה כדי להגדיר שדה אחד או יותר לתצוגה",
  "display": "תצוגה",
  "duplicate": "מצא כפילות",
  "duplicateTip": "חפש בשדה זה ערכים זהים בין קובץ המקור לשכבת היעד./n אם נמצאה התאמה זהה, הרשומה מהקובץ לא תאותר ותסומן ככפילות.",
  "noSelectField": "בחר את שכבת הישויות תחילה",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (קו אורך)",
  "xyFieldsLabelY": "Y (קו רוחב)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "כלפי מזרח",
  "northing": "כלפי צפון",
  "lon": "קו אורך",
  "lat": "קו רוחב",
  "layerOptionHint": "בחר את השכבה שאליה יישלחו נתונים.",
  "layerFieldTitle": "שכבת יעד",
  "tempSymbolHint": "בחר את הסמל שישמש להצגת הישויות.",
  "tempSymbolTitle": "הצג סמל",
  "maxRecords": "מקסימום רשומות",
  "maxRecordsHint": "מספר הרשומות המקסימלי לעיגון כתובות",
  "searchRadius": "רדיוס חיפוש",
  "searchRadiusHint": "מרחק לחיפוש ישויות כפולות בשכבה",
  "requiresInteger": "הזן ערך מספרי.",
  "requiresInteger0100": "הזן ערך מספרי בין 0 ל-100",
  "requiresLocator": "הזן מגדיר עיגון כתובות חוקי אחד לפחות.",
  "layerFields": "הגדרות שכבה",
  "layerFieldsHint": "ציין את השדות משכבת היעד שימופו לשדות המקור.",
  "locatorError": "מגדיר עיגון הכתובות אינו חוקי או אינו נגיש.",
  "optionNotMatch": "אפשרויות שדה אינן עקביות בין מגדירי עיגון כתובות. ייתכן שגיבוי בעת כשל לא יעבוד כצפוי.",
  "targetLayerTabTitle": "שכבת יעד",
  "locationSettingsTabTitle": "הגדרות מיקום",
  "generalSettingsTabTitle": "הגדרות כלליות",
  "addTargetLayersLabel": "הוסף שכבת יעד",
  "introductoryText": "צור תוכן הוראתי עבור הווידג'ט",
  "defaultStartPageInstructions": "וידג'ט זה יסייע בעיבוד ובשליחה של נתונים מקובץ לשכבה שנבחרה במפה.<br/> <br/> יש להפריד בין ערכים בתוך הקובץ באמצעות פסיק, טאב, נקודה-פסיק או קו אנכי.",
  "noTargetLayerConfiguredErrorMsg": "לא הוגדרה שכבת יעד",
  "noFieldsForTargetLayer": "הגדרות שכבה לא הוגדרו עבור שכבת היעד",
  "locationSettingsNotConfigured": "הגדרות מיקום לא נקבעו כהלכה",
  "questionMark": "?"
});