define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Uzyskaj dostęp do infografik i raportów podsumowujących kluczowe wskaźniki i dane w dowolnym obszarze.</div><br><div>Wybierz na mapie punkt lub poligon, wyszukaj adres lub miejsce, narysuj poligon albo umieść na mapie szpilkę, aby wyświetlić kluczowe wskaźniki i informacje o tym obszarze.</div>",
  "defineWhichInfographics": "Zdefiniuj, które infografiki są dostępne w widżecie:",
  "defineWhichReports": "Zdefiniuj, które raporty są dostępne w widżecie:",
  "defaultValues": "Wartości domyślne:",
  "disable": "Dezaktywuj",
  "drawFreehandPolygon": "Rysuj dowolny poligon",
  "drawPolygon": "Rysowanie poligonu",
  "driveTime": "Czas przejazdu",
  "dropPin": "Umieść szpilkę",
  "dynamicHTML": "Dynamiczny kod HTML",
  "exportOptions": "Opcje eksportu:",
  "home": "Strona główna",
  "image": "Obraz",
  "infographics": "Infografiki",
  "invalidValueRing": "Wartości muszą należeć do zakresu od 0 do 1 000.",
  "invalidValueDTWT": "Wartości muszą należeć do zakresu od 0 do 300.",
  "km": "km",
  "makeDefault": "Ustaw jako domyślne",
  "miles": "mil",
  "minutes": "minut(y)",
  "options": "Opcje:",
  "pdf": "PDF",
  "print": "Drukuj",
  "radius": "Promień",
  "removeDefault": "Usuń domyślne",
  "reports": "Raporty",
  "rings": "Pierścienie",
  "searchTextBox": "Pole tekstowe wyszukiwania",
  "selectCountryOrRegion": "Wybierz kraj lub region:",
  "thisEntryIsNotValid": "Ten wpis nie jest prawidłowy.",
  "time": "Czas",
  "walkTime": "Czas pokonania trasy pieszej"
});