define({
  "addLocation": "Добавяне на единица за местоположение",
  "addDistance": "Добавяне на единица за дължина",
  "addArea": "Добавяне на единица за площ",
  "label": "Етикет",
  "abbr": "Абревиатура",
  "conversion": "Конверсия",
  "actions": "Действия",
  "areaUnits": "Единици за площ",
  "distanceUnits": "Единици за дължина",
  "kilometers": "Километри",
  "miles": "Мили",
  "meters": "Метри",
  "feet": "Фута",
  "yards": "Ярда",
  "nauticalmiles": "Морски мили",
  "squareKilometers": "Квадратни километри",
  "squareMiles": "Квадратни мили",
  "acres": "Акри",
  "hectares": "Хектари",
  "squareMeters": "Квадратни метри",
  "squareFeet": "Квадратни фута",
  "squareYards": "Квадратни ярда",
  "location": "Местоположения",
  "distance": "Разстояния",
  "area": "Области",
  "kilometersAbbreviation": "км",
  "milesAbbreviation": "миля",
  "metersAbbreviation": "м",
  "feetAbbreviation": "фут",
  "yardsAbbreviation": "ярд",
  "nauticalmilesAbbreviation": "нм",
  "squareKilometersAbbreviation": "кв. км",
  "squareMilesAbbreviation": "кв. мили",
  "acresAbbreviation": "акр.",
  "hectaresAbbreviation": "хек.ар.",
  "squareMetersAbbreviation": "кв.м",
  "squareFeetAbbreviation": "кв. фута",
  "squareYardsAbbreviation": "кв. ярда",
  "defineUnits": "Определяне на мерните единици.",
  "operationalLayer": "Добавяне на чертежа като оперативен слой на картата."
});