define({
  "_widgetLabel": "Šikovný editor",
  "_featureAction_SmartEditor": "Šikovný editor",
  "noEditPrivileges": "Váš účet nemá povolenie na vytvorenie alebo upravenie údajov.",
  "loginPopupTitle": "Prihlásiť sa",
  "loginPopupMessage": "${widgetName} vyžaduje povolenia a kredity na vyhľadanie a uloženie adresných informácií. Chcete sa prihlásiť a používať túto funkciu?",
  "noCreditsOrPrivilegeWarningMessage": "Váš účet nemá povolenia a kredity na vyhľadanie a uloženie adresných informácií pomocou ${widgetName}. Kontaktujte správcu svojej organizácie a požiadajte o povolenia a kredity.",
  "unableToUseLocator": "Lokátor nie je prístupný. Akcie súvisiace s adresným atribútom nebudú vykonané.",
  "locatorDisabledWaning": "Lokátor nie je aktivovaný. Požiadajte správcu vašej organizácie o aktivovanie tejto funkcie.",
  "noFeatureInAIWarning": "Nevybrali ste žiadne prvky. Vyberte prvok, ktorý chcete editovať, alebo kliknite na položku Zrušiť pre návrat na hlavnú obrazovku.",
  "noEditableLayerWarning": "Váš účet nemá povolenie na tvorbu alebo modifikáciu dát alebo táto webová mapa neobsahuje žiadne editovateľné vrstvy.",
  "noVisibleCreateLayerWarning": "Vrstvy nie sú v aktuálnej úrovni priblíženia viditeľné. Ak chcete vytvárať alebo modifikovať prvky, priblížte alebo oddiaľte zobrazenie.",
  "noVisibleUpdateLayerWarning": "Vrstvy nie sú v aktuálnej úrovni priblíženia viditeľné. Ak chcete modifikovať prvky, priblížte alebo oddiaľte zobrazenie.",
  "checkLayerVisibilityInWebMapWarning": "Ak chcete vytvárať alebo modifikovať prvky, uistite sa, že sú vrstvy viditeľné v mape.",
  "showSelectionInAITitle": "Vybraté prvky",
  "showSelectionInAIMsg": "Chcete načítať aktuálny výber v ${widgetName}?",
  "widgetActive": "Aktívny",
  "widgetNotActive": "Neaktívny",
  "pressStr": "Stlačiť ",
  "ctrlStr": " CTRL ",
  "snapStr": " na povolenie prichytávania",
  "noAvailableTempaltes": "Nie sú dostupné žiadne šablóny",
  "editorCache": " - vyrovnávacia pamäť editora",
  "presetFieldAlias": "Pole",
  "presetValue": "Prednastavená hodnota",
  "usePresetValues": " Použiť prednastavené hodnoty (len nové prvky)",
  "editGeometry": " Upraviť geometriu",
  "savePromptTitle": "Uložiť prvok",
  "savePrompt": "Chceli by ste uložiť aktuálny prvok?",
  "deletePromptTitle": "Zmazať prvok",
  "deleteAttachment": "Odstrániť prílohu",
  "deletePrompt": "Naozaj chcete vymazať vybrané prvky?",
  "attachmentLoadingError": "Chyba pri nahrávaní príloh",
  "attachmentSaveDeleteWarning": "Varovanie: Zmeny v prílohách sa ukladajú automaticky",
  "autoSaveEdits": "Automaticky uložiť nové prvky",
  "addNewFeature": "Vytvoriť nový prvok",
  "featureCreationFailedMsg": "Nie je možné vytvoriť nový záznam/prvok",
  "relatedItemTitle": "Relačná tabuľka/vrstva",
  "relatedFeatureCount": "${layerTitle} s ${featureCount} prvkami",
  "createNewFeatureLabel": "Vytvoriť nový prvok pre ${layerTitle}",
  "invalidRelationShipMsg": "Prosím uistite sa, že stĺpec primárneho kľúča: '${parentKeyField}' má platnú hodnotu",
  "pendingFeatureSaveMsg": "Prosím uložte úpravy prvku pred vytvorením relačne súvisiaceho prvku.",
  "attachmentsRequiredMsg": "(*) Prílohy sú požadované.",
  "coordinatePopupTitle": "Presunúť prvok na XY polohu",
  "coordinatesSelectTitle": "Súradnicový systém:",
  "mapSpecialReferenceDropdownOption": "Súradnicový systém mapy",
  "latLongDropdownOption": "Zemepisná šírka/Zemepisná dĺžka",
  "mgrsDropdownOption": "Vojenský mriežkový referenčný systém (MGRS)",
  "mgrsTextBoxLabel": "Súradnica:",
  "xAttributeTextBoxLabel": "Súradnica-X:",
  "yAttributeTextBoxLabel": "Súradnica-Y:",
  "latitudeTextBoxLabel": "Zemepisná šírka:",
  "longitudeTextBoxLabel": "Zemepisná dĺžka:",
  "presetGroupFieldsLabel": "'${groupName}' bude aplikované na nasledujúcich stĺpcoch vrstvy:",
  "presetGroupNoFieldsLabel": "'${groupName}' nemá žiadne asociované stĺpce",
  "groupInfoLabel": "Skupinové informácie pre '${groupName}'",
  "editGroupInfoIcon": "Upraviť skupinovú hodnotu pre ${groupName}",
  "filterEditor": {
    "all": "Všetky",
    "noAvailableTempaltes": "Nie sú dostupné žiadne šablóny",
    "searchTemplates": "Šablóny vyhľadávania",
    "filterLayerLabel": "Vrstvy filtrov"
  },
  "invalidConfiguration": "Widget buď nie je konfigurovaný, alebo vrstvy v konfigurácii už nie sú v mape. Otvorte aplikáciu v režime Builder a znova konfigurujte widget.",
  "geometryServiceURLNotFoundMSG": "Nepodarilo sa získať URL geometrickej služby",
  "clearSelection": "Zatvoriť",
  "refreshAttributes": "Aktualizovať atribúty dynamických prvkov",
  "automaticAttributeUpdatesOn": "Automatická aktualizácia atribútov prvku: Zapnutá",
  "automaticAttributeUpdatesOff": "Automatická aktualizácia atribútov prvku: Vypnutá",
  "moveSelectedFeatureToGPS": "Presunúť zvolený prvok na aktuálnu polohu GPS",
  "moveSelectedFeatureToXY": "Presunúť zvolený prvok na polohu XY",
  "mapNavigationLocked": "Navigácia mapy: Zamknutá",
  "mapNavigationUnLocked": "Navigácia mapy: Odomknutá",
  "copyFeatures": {
    "title": "Kopírovať prvky",
    "createFeatures": "Vytvoriť prvky",
    "createSingleFeature": "Vytvoriť jeden prvok skladajúci sa z viacerých častí",
    "createOneSingleFeature": "Vytvoriť prvok",
    "noFeaturesSelectedMessage": "Žiadne vybrané prvky",
    "selectFeatureToCopyMessage": "Vyberte prvky, ktoré chcete skopírovať",
    "multipleFeatureSaveWarning": "Poznámka: Ak vytvoríte viacero prvkov pomocou funkcie kopírovania, všetky nové prvky sa okamžite uložia",
    "copyFeatureUpdateGeometryError": "Nie je možné aktualizovať geometriu zvolených prvkov",
    "canNotSaveMultipleFeatureWarning": "Poznámka: Nie je možné skopírovať viacero prvkov pri použití rovnakej hodnoty pre pole unikátnych hodnôt, prosím vyberte iba jeden prvok",
    "createOnlyOneMultipartFeatureWarning": "Poznámka: Je možné vytvoriť iba jeden prvok skladajúci sa z viacerých častí"
  },
  "addingFeatureError": "Chyba pri pridávaní zvolených prvkov vo vrstve. Skúste prosím znova.",
  "addingFeatureErrorCount": "Počet prvkov, ktoré sa nepodarilo skopírovať: ${copyFeatureErrorCount}. Chcete to skúsiť znova pre chýbajúce prvky?",
  "selectingFeatureError": "Chyba pri voľbe prvkov vo vrstve. Skúste prosím znova.",
  "customSelectOptionLabel": "Zvoliť prvky na skopírovanie",
  "noFeatureSelectedMessage": "Žiadne vybrané prvky",
  "multipleFeatureSaveMessage": "Všetky prvky budú okamžite uložené. Chcete pokračovať?",
  "relativeDates": {
    "dateTypeLabel": "Typ dátumu",
    "valueLabel": "Hodnota",
    "fixed": "Fixné",
    "current": "Aktuálna",
    "past": "Minulosť",
    "future": "Budúcnosť",
    "popupTitle": "Vybrať hodnotu",
    "hintForFixedDateType": "Tip: Špecifikovaný dátum a čas bude použitý ako prednastavená predvolená hodnota.",
    "hintForCurrentDateType": "Tip: Aktuálny dátum a čas bude použitý ako prednastavená predvolená hodnota.",
    "hintForPastDateType": "Tip: Špecifikovaná hodnota bude odčítaná od aktuálneho dátumu a času pre predvolenú hodnotu prednastavenia.",
    "hintForFutureDateType": "Tip: Špecifikovaná hodnota bude pridaná k aktuálnemu dátumu a času pre predvolenú hodnotu prednastavenia.",
    "noDateDefinedTooltip": "Žiaden definovaný dátum",
    "relativeDateWarning": "Hodnota pre dátum a čas musí byť špecifikovaná, aby sa dala predvolená prednastavená hodnota uložiť.",
    "customLabel": "Vlastné",
    "layerLabel": "Vrstva",
    "domainFieldHintLabel": "Zvolená hodnota je doména s kódovanými hodnotami. Použije sa hodnota: ${domainValue}"
  },
  "valuePicker": {
    "popupTitle": "Vybrať hodnotu",
    "popupHint": "Súčasný prvok pretína viacero prvkov, vyberte hodnotu pre príslušný stĺpec",
    "buttonTooltip": "Zvoľte hodnotu z viacerých pretínajúcich sa prvkov"
  },
  "uniqueValueErrorMessage": "Hodnota v \"${fieldName}\" už existuje, zadajte novú hodnotu.",
  "requiredFields": {
    "displayMsg": "Vyžadované polia nemôžu byť prázdne. Poskytnite hodnoty pre spoločné polia nižšie.",
    "popupTittle": "Povinné políčka",
    "foundNullRecordCount": "${fieldName} (nájdené v ${count} záznamoch)"
  },
  "cantLocateUserLocation": "Nie je možné určiť vašu polohu",
  "tryAgainButtonLabel": "Skúsiť znova",
  "copyFeatureFailedPopupTitle": "Ups!"
});