define({
  "layersPage": {
    "allLayers": "Visi slāņi",
    "title": "Atlasiet veidni, lai izveidotu elementus, vai noklikšķiniet uz elementa kartē, lai to rediģētu",
    "generalSettings": "Vispārīgie iestatījumi",
    "layerSettings": "Slāņu iestatījumi",
    "webmapSettingsRadioBtnLabel": "Ievērot tīmekļa kartes iestatījumus",
    "customSettingsRadioBtnLabel": "Pielāgoti iestatījumi",
    "smartActionsTabTitle": "Viedās darbības",
    "attributeActionsTabTitle": "Atribūtu darbības",
    "geocoderSettingsText": "Ģeokodētāja iestatījumi",
    "editDescription": "Ievadiet tekstu, kas jāparāda rediģēšanas panelī",
    "editDescriptionTip": "Šis teksts tiek parādīts virs veidņu atlasītāja; ja teksta nav, atstājiet tukšu.",
    "promptOnSave": "Uzvedne saglabāt nesaglabātos labojumus, ja veidlapa tiek aizvērta vai notiek pārslēgšanās uz nākamo ierakstu",
    "promptOnSaveTip": "Parādīt uzvedni, ja pašreizējam elementam ir nesaglabāti labojumi. (Vairāku elementu kopēšana tiek saglabāta automātiski.)",
    "promptOnDelete": "Pieprasīt apstiprinājumu, ja tiek dzēsts ieraksts",
    "promptOnDeleteTip": "Parādīt darbības apstiprināšanas uzvedni, ja lietotājs noklikšķina uz Izdzēst.",
    "removeOnSave": "Saglabāšanas laikā noņemt elementu no atlases",
    "removeOnSaveTip": "Opcija noņemt elementu no iestatītās izvēles, kad tiek saglabāts ieraksts. Ja tas ir vienīgais izvēlētais ieraksts, panelis tiek pārslēgts atpakaļ uz veidnes lapu.",
    "useFilterEditor": "Izmantot elementu veidnes filtru",
    "useFilterEditorTip": "Opcija izmantot atlasītāju Filtrēt veidni, kas sniedz iespēju skatīt viena slāņa veidni vai meklēt veidnes pēc nosaukuma.",
    "groupFilteredTemplates": "Meklēšanas rezultātu grupēšana",
    "groupFilteredTemplatesTip": "Iespēja grupēt meklēšanas rezultātus pēc slāņa.",
    "displayShapeSelector": "Parādīt zīmēšanas veidus",
    "createNewFeaturesFromExisting": "Atļaut izveidot jaunu(s) elementu(s) no esošā(ajiem) elementa(iem)",
    "createNewFeaturesFromExistingTip": "Iespēja, kas ļauj lietotājam kopēt esošos elementus, lai izveidotu jaunus elementus",
    "copiedFeaturesOverrideDefaults": "Vērtība(s) no kopētā(ajiem) elementa(iem) pārraksta noklusējuma vērtību(as) mērķa laukā(os)",
    "copiedFeaturesOverrideDefaultsTip": "Kopēto elementu vērtības apies noklusējuma veidnes vērtības tikai atbilstošajiem laukiem",
    "displayShapeSelectorTip": "Iespēja parādīt sarakstu ar zīmēšanas veidiem, kas derīgi izvēlētajai veidnei.",
    "displayPresetTop": "Rādīt iepriekš iestatītu vērtību sarakstu augšpusē",
    "displayPresetTopTip": "Iespēja rādīt pašreizējo vērtību sarakstu virs veidņu atlasītāja.",
    "listenToGroupFilter": "Lietot grupu filtra logrīka filtra vērtības iepriekšnoteiktajiem laukiem",
    "listenToGroupFilterTip": "Kad grupu filtra logrīkā tiek lietots filtrs, lietot vērtību atbilstošā iepriekšnoteikto vērtību saraksta laukā.",
    "keepTemplateActive": "Uzturēt atlasīto veidni aktīvu",
    "editLayerAddedFromAddData": "Atļaut rediģēt slāņus, kas pievienoti no logrīka Datu pievienošana",
    "editLayerAddedFromAddDataTip": "Var rediģēt slāņus, kas programmai pievienoti, izmantojot logrīku Datu pievienošana",
    "keepTemplateActiveTip": "Kad tiek parādīts veidņu atlasītājs, atkārtoti atlasīt veidni, ja tā ir bijusi atlasīta iepriekš.",
    "geometryEditDefault": "Aktivizēt ģeometrijas labojumus pēc noklusējuma",
    "autoSaveEdits": "Automātiski saglabāt jaunus elementus",
    "enableAttributeUpdates": "Rādīt pogu Atribūtu darbību atjaunināšana",
    "enableAutomaticAttributeUpdates": "Automātiski izsaukt funkciju Atribūta darbības pēc ģeometrijas atjaunināšanas",
    "enableLockingMapNavigation": "Kartes navigācijas bloķēšanas aktivizēšana",
    "enableMovingSelectedFeatureToGPS": "Aktivizēt izvēlētā punkta elementu pārvietošanu uz GPS novietojumu",
    "enableMovingSelectedFeatureToXY": "Aktivizēt izvēlētā punkta elementu pārvietošanu uz XY novietojumu",
    "featureTemplateLegendLabel": "Elementu sagatave un Filtra vērtību iestatījumi",
    "saveSettingsLegendLabel": "Saglabāt iestatījumus",
    "geometrySettingsLegendLabel": "Ģeometrijas iestatījumi",
    "actionsSettingsLegendLabel": "Darbību iestatījumi",
    "buttonPositionsLabel": "Pogas Saglabāt, Dzēst, Atpakaļ un Aizvērt novietojums",
    "belowEditLabel": "Zem Rediģēt veidlapu",
    "aboveEditLabel": "Virs Rediģēt veidlapu",
    "switchToMultilineInput": "Pārslēdzieties uz vairākrindu ievadi, ja lauka garums pārsniedz",
    "enableValuePicker": "Iespējot šķelšanas (intersect) vērtību atlasītāju",
    "enableValuePickerHint": "Parādīt uzvedni, ja laukam ar šķelšanas (intersect) atribūta darbību ir pieejamas vairākas vērtības",
    "expandRelatedTable": "Izvērst visas saistītās tabulas/slāņus ielādēšanas laikā",
    "expandMainTable": "Izvērst visus vecākelementa slāņus ielādēšanas laikā",
    "copyAndAppendFeatureLabel": "Kopēt un pievienot elementus",
    "allowCopyPolygonLabel": "Ļaut kopēt poligonu pēc punktiem",
    "allowCopyPolygonTooltip": "Iespēja, kas ļauj kopēt poligona elementus par punktveida mērķa elementu veidnēm ar ģeometrijas transformācijām",
    "allowCopyLineLabel": "Ļaut kopēt līniju pēc punktiem",
    "allowCopyLineTooltip": "Iespēja, kas ļauj kopēt līnijas elementus par punktveida mērķa elementu veidnēm ar ģeometrijas transformācijām",
    "pointAtStartLabel": "Sākuma punkts",
    "pointAtStartTooltip": "Pievienot punktu kopējamās līnijas sākumā",
    "pointAtEndLabel": "Beigu punkts",
    "pointAtEndTooltip": "Pievienot punktu kopējamās līnijas beigās",
    "layerSettingsTable": {
      "allowDelete": "Atļaut dzēšanu",
      "allowDeleteTip": "Atļaut dzēšanu — opcija atļaut lietotājam izdzēst elementu; ja slānī dzēšana nav atbalstīta, opcija tiek atspējota",
      "edit": "Rediģējams",
      "editTip": "Rediģējams — opcija iekļaut slāni logrīkā",
      "label": "Slānis",
      "labelTip": "Slānis — slāņa nosaukums, kā tas ir norādīts kartē",
      "update": "Atspējot ģeometrijas rediģēšanu",
      "updateTip": "Atspējot ģeometrijas rediģēšanu — opcija atspējot iespēju pārvietot ģeometriju pēc izvietošanas vai pārvietot ģeometriju esošā elementā",
      "allowUpdateOnly": "Tikai atjaunināt",
      "allowUpdateOnlyTip": "Tikai atjaunināt — opcija atļaut tikai esošo elementu labošanu, kas ir atzīmēta pēc noklusējuma un tiek atspējota, ja slānis neatbalsta jaunu elementu izveidi",
      "fieldsTip": "Modificēt rediģējamos laukus un definēt viedos atribūtus",
      "actionsTip": "Darbības — opcija, lai rediģētu laukus vai piekļūtu saistītajiem slāņiem/tabulām",
      "description": "Apraksts",
      "descriptionTip": "Apraksts — opcija ievadīt tekstu, ko parādīt atribūtu lapas augšdaļā.",
      "relationTip": "Skatīt saistītos slāņus un tabulas"
    },
    "editFieldError": "Lauku modificēšanas iespējas un viedie atribūti nav pieejami tiem slāņiem, kas nav rediģējami",
    "noConfigedLayersError": "Programmai Smart Editor ir nepieciešams viens vai vairāki rediģējami slāņi",
    "toleranceErrorMsg": "Nederīga noklusējuma šķērsojuma pielaides vērtība",
    "pixelsToleranecErrorMsg": "Nederīga noklusējuma pikseļu pielaides vērtība",
    "invalidMaxCharacterErrorMsg": "Laukā Pārslēgšanās uz vairākrindu ievadi ir nederīga vērtība",
    "featuresSelectionTolerance": "Iestatiet pielaidi elementu atlasei (pikseļos)",
    "featuresSelectionToleranceTooltip": "Ļaujiet lietotājiem ērti atvērt atribūtu rediģēšanas paneli, noklikšķinot uz elementa",
    "featuresSelectionToleranceErrorMsg": "Nederīga elementa atlases pielaides vērtība",
    "autoSaveAttrUpdates": "Automātiski saglabāt atribūta un ģeometrijas atjauninājumus",
    "defaultCoordinateSystem": "Noklusējuma atskaites sistēma",
    "defaultCoordinateSystemTooltip": "Iestatīt noklusējuma atskaites sistēmu, pārvietojot izvēlēto punkta elementu uz jaunu novietojumu"
  },
  "editDescriptionPage": {
    "title": "Definēt atribūtu pārskata tekstu slānim <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Konfigurēt slāņa <b>${layername}</b> laukus",
    "copyActionTip": "Atribūtu darbības",
    "editActionTip": "Viedās darbības",
    "description": "Izmantojiet darbību rediģēšanas pogu, lai slānī aktivizētu viedos atribūtus. Viedie atribūti atkarībā no citu lauku vērtībām var pieprasīt, paslēpt vai atspējot lauku. Izmantojiet darbību kopēšanas pogu, lai aktivizētu un definētu lauka vērtības avotu pēc krustpunkta, adreses, koordinātām vai sākotnējiem iestatījumiem.",
    "fieldsNotes": "Ar zvaigznīti * tiek atzīmēti obligāti aizpildāmie lauki. Ja noņemsit šī lauka izvēli Parādīt, bet rediģēšanas veidnē netiks ievadīta šī lauka vērtība, jūs nevarēsiet saglabāt jaunu ierakstu.",
    "smartAttachmentText": "Konfigurēt Viedās darbības (Smart Actions) pielikumiem",
    "smartAttachmentPopupTitle": "Konfigurēt Viedās darbības (Smart Actions) pielikumiem šeit: <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Lūdzu, atlasiet vismaz vienu parādāmu lauku slānim ${layerName}",
    "fieldsSettingsTable": {
      "display": "Parādīt",
      "displayTip": "Attēlošana— nosaka vai lauks nav redzams",
      "edit": "Rediģējams",
      "editTip": "Rediģējams — pārbaudīt, vai lauks ir pieejams atribūtu veidlapā",
      "fieldName": "Nosaukums",
      "fieldNameTip": "Nosaukums — datu bāzē norādītais lauka nosaukums",
      "fieldAlias": "Aizstājvārds",
      "fieldAliasTip": "Aizstājvārds — kartē norādītais lauka nosaukums",
      "canPresetValue": "Iepriekš iestatīts",
      "canPresetValueTip": "Iepriekš iestatīts — opcija rādīt lauku iepriekš iestatīto lauku sarakstā un ļaut lietotājam iestatīt vērtību pirms rediģēšanas",
      "actions": "Darbības",
      "actionsTip": "Darbības — mainīt lauku secību vai iestatīt viedos atribūtus"
    },
    "smartAttSupport": "Viedie atribūti nav iestatīti nepieciešamajos datu bāzes laukos"
  },
  "actionPage": {
    "title": "Konfigurēt atribūtu darbības laukam <b>${fieldname}</b>",
    "smartActionTitle": "Konfigurēt viedās darbības (Smart Actions), kas paredzētas <b>${fieldname}</b>",
    "description": "Darbības vienmēr ir izslēgtas, ja vien jūs nenorādāt kritērijus, kas šīs darbības aktivizē. Darbības tiek apstrādātas secīgi, un katrā laukā tiks aktivizēta tikai viena darbība. Lai definētu kritērijus, izmantojiet kritēriju rediģēšanas pogu.",
    "copyAttributesNote": "Ja tiek atspējota jebkura darbība ar grupas nosaukumu, tas būs tas pats, kas darbības neatkarīga rediģēšana, un šī darbība saistībā ar šo lauku tiks noņemta no attiecīgās grupas.",
    "searchPlaceHolder": "Meklēt",
    "expandAllLabel": "Izvērst visus slāņus",
    "selectAllLabel": "Atlasīt visus laukus",
    "domainListTitle": "Domēna lauki",
    "noValidFieldTypeMsg": "Šim datu veidam kartē nav pieejams neviens piemērots slānis.",
    "actionsSettingsTable": {
      "rule": "Darbība",
      "ruleTip": "Darbība — darbība, kas tiek veikta, ja ir nodrošināta atbilstība kritērijiem",
      "expression": "Izteiksme",
      "expressionTip": "Izteiksme — rezultātā iegūtā izteiksme SQL formātā no definētajiem kritērijiem",
      "groupName": "Grupas nosaukums",
      "groupNameTip": "Grupas nosaukums — parāda grupas nosaukumu, no kura tiek piemērota izteiksme",
      "actions": "Kritēriji",
      "actionsTip": "Kritēriji — mainiet noteikuma secību un definējiet kritērijus, kad tā tiek aktivizēta"
    },
    "copyAction": {
      "description": "Lauka vērtības avots tiek apstrādāts secīgi, ja tas ir aktivizēts, līdz derīgu kritēriju aktivizēšanai vai saraksta pabeigšanai. Izmantojiet pogu Kritēriju rediģēšana, lai definētu kritērijus.",
      "intersection": "Krustpunkts",
      "coordinates": "Koordinātas",
      "address": "Adrese",
      "preset": "Priekšiestatīts",
      "actionText": "Darbības",
      "criteriaText": "Kritēriji",
      "enableText": "Iespējots"
    },
    "actions": {
      "hide": "Paslēpt",
      "required": "Nepieciešams",
      "disabled": "Atspējots"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Brīdinājums. Neatkarīga rediģēšana noņems izvēlēto atribūtu darbību, kas saistīta ar šo grupas lauku",
      "editGroupHint": "Brīdinājums. Neatkarīga rediģēšana noņems no grupas izvēlēto viedo darbību, kas saistīta ar šo lauku",
      "popupTitle": "Izvēlieties rediģēšanas opciju",
      "editAttributeGroup": "Izvēlētā atribūtu darbība ir norādīta no grupas. Izvēlieties kādu no zemāk norādītajām opcijām, lai rediģētu atribūtu darbību.",
      "expression": "Izvēlētās viedās darbības izteiksme ir norādīta no grupas. Izvēlieties kādu no zemāk norādītajām opcijām, lai rediģētu viedās darbības izteiksmi.",
      "editGroupButton": "Rediģēt grupu",
      "editIndependentlyButton": "Rediģēt neatkarīgi"
    }
  },
  "filterPage": {
    "submitHidden": "Iesniegt atribūta datus laukiem pat tad, ja tie ir paslēpti",
    "title": "Konfigurēt ${action} noteikuma izteiksmi",
    "filterBuilder": "Laukā iestatīt darbību, ja ieraksts atbilst ${any_or_all} no tālāk esošajām izteiksmēm",
    "noFilterTip": "Izmantojot iepriekš norādītos rīkus, definējiet pieprasījumu par to, kad darbība ir aktīva."
  },
  "geocoderPage": {
    "setGeocoderURL": "Iestatīt ģeokodētāja vietrādi URL",
    "hintMsg": "Piezīme. Jūs maināt ģeokodētāja servisu; noteikti atjaunojiet visus jūsu konfigurētos ģeokodētāja lauku kartējumus.",
    "invalidUrlTip": "URL ${URL} ir nederīgs vai tam nevar piekļūt."
  },
  "addressPage": {
    "popupTitle": "Adrese",
    "checkboxLabel": "Iegūt vērtību no ģeokodētāja",
    "selectFieldTitle": "Atribūti",
    "geocoderHint": "Lai mainītu ģeokodētāju, izmantojiet vispārējo iestatījumu pogu Ģeokodētāja iestatījumi",
    "prevConfigruedFieldChangedMsg": "Iepriekš konfigurētais atribūts nav atrasts pašreizējos ģeokodētāja iestatījumos. Atribūts ir atiestatīts uz noklusējumu.",
    "questionMark": "?",
    "consumesCredits": "Šis rīks patērē servisa kredītus, ja tiek izmantots kopā ar ArcGIS Online World Geocoding Service"
  },
  "coordinatesPage": {
    "popupTitle": "Koordinātas",
    "checkboxLabel": "Iegūt koordinātas",
    "coordinatesSelectTitle": "Atsauču sistēma",
    "coordinatesAttributeTitle": "Atribūti",
    "mapSpatialReferenceOptionLabel": "Kartes telpiskā atskaite",
    "latLongOptionLabel": "Platums/Garums",
    "MGRS": "Militārā režģa atsauces sistēma (Military Grid Reference System, MGRS)",
    "allGroupsCreatedMsg": "Visas iespējamās grupas jau ir izveidotas",
    "coordinatesSourceTitle": "Koordinātu avots",
    "featureLocation": "Elementa atrašanās vieta",
    "myLocation": "Mana atrašanās vieta",
    "LatLong": {
      "y": "Platums",
      "x": "Garums",
      "xy": "Garums Platums",
      "yx": "Platums Garums"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Iepriekš iestatīts",
    "checkboxLabel": "Lauks tiks iepriekšēji iestatīts",
    "showOnlyDomainFields": "Rādīt tikai domēna laukus",
    "hideInPresetDisplay": "Paslēpt iepriekš iestatīto vērtību displejā",
    "presetValueLabel": "Pašreizējā iepriekšēji iestatītā vērtība ir:",
    "changePresetValueHint": "Lai mainītu šo iepriekšēji iestatīto vērtību, izmantojiet vispārējo iestatījumu pogu Definēt iepriekš iestatītās vērtības"
  },
  "intersectionPage": {
    "groupNameLabel": "Grupas nosaukums",
    "dataTypeLabel": "Datu veids",
    "ignoreLayerRankingCheckboxLabel": "Ignorēt slāņu iedalījumu un sameklēt tuvāko elementu visos norādītajos slāņos",
    "intersectingLayersLabel": "Slāņi, no kuriem izgūstama vērtība",
    "layerAndFieldsApplyLabel": "Slāņi un lauki, kuriem jālieto izgūtā vērtība",
    "checkboxLabel": "Iegūt vērtību no krustpunkta slāņa lauka",
    "layerText": "Slāņi",
    "fieldText": "Lauki",
    "actionsText": "Darbības",
    "toleranceSettingText": "Pielaides iestatījumi",
    "addLayerLinkText": "Pievienot slāni",
    "useDefaultToleranceText": "Izmantot noklusējuma pielaidi",
    "toleranceValueText": "Pielaides vērtība",
    "toleranceUnitText": "Pielaides mērvienība",
    "pixelsUnitText": "Pikseļi",
    "useLayerName": "- Izmantot slāņa nosaukumu -",
    "noLayersMessage": "Kartes slāņos nav atrasts neviens lauks, kas atbilstu izvēlētajam datu tipam.",
    "intersectionLayerHint": "Slāņu ranks ir noteikts dilstošā secībā. Izmantojiet bultas sadaļā Darbības, lai pārkārtotu slāņus un mainītu pārklāšanās prioritāti."
  },
  "presetAll": {
    "popupTitle": "Definēt noklusējuma iepriekš iestatītās vērtības",
    "deleteTitle": "Izdzēst iepriekš iestatīto vērtību",
    "hintMsg": "Šeit ir uzskaitīti visu unikālo iepriekš iestatīto lauku nosaukumi. Noņemot iepriekš iestatīto lauku, visos slāņos/tabulās attiecīgais lauks tiks atspējots kā iepriekš iestatītais lauks."
  },
  "intersectionTolerance": {
    "intersectionLabel": "Noklusējuma šķelšanas pielaide visiem elementiem",
    "intersectionTitle": "Iespējot globālu pielaidi krustpunktiem",
    "pixelsToleranceLabel": "Noklusējuma šķelšanas pielaide (pikseļu vērtība), kas jālieto tikai punktu elementiem",
    "pixelsToleranceTitle": "Ja visu elementu noklusējuma krustpunktu pielaide ir iestatīta kā 0, izmantojiet šo iestatījumu punktu elementiem"
  },
  "smartActionsPage": {
    "smartActionLabel": "Konfigurēt viedo darbību",
    "addNewSmartActionLinkText": "Pievienot jaunu",
    "definedActions": "Norādītās darbības",
    "priorityPopupTitle": "Iestatīt viedo darbību prioritāti",
    "priorityPopupColumnTitle": "Viedās darbības",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Grupas nosaukums",
    "layerForExpressionLabel": "Izteiksmes slānis",
    "layerForExpressionNote": "Piezīme. Šī slāņa lauki tiek izmantoti izteiksmes kritēriju definēšanai. Opcija “Lietojamie slāņi un lauki” norāda tikai tos slāņus un tabulas, kuru lauki ir definēti Izteiksmē.",
    "expressionText": "Izteiksme",
    "editExpressionLabel": "Rediģēt izteiksmi",
    "layerAndFieldsApplyLabel": "Slāņi un lauki, kas jālieto",
    "submitAttributeText": "Iesniegt atribūta datus laukiem pat tad, ja tie ir paslēpti",
    "priorityColumnText": "Prioritāte",
    "requiredGroupNameMsg": "Šī vērtība ir obligāta",
    "uniqueGroupNameMsg": "Ievadiet unikālu grupas nosaukumu; grupa ar šādu nosaukumu jau pastāv.",
    "deleteGroupPopupTitle": "Dzēst viedo darbību grupu",
    "deleteGroupPopupMsg": "Dzēšot grupu, no visu saistīto lauku darbības tiks noņemta izteiksme.",
    "invalidExpression": "Izteiksme nevar būt tukša",
    "warningMsgOnLayerChange": "Norādītā izteiksme un lauki, kuriem tā lietota, tiks notīrīti.",
    "smartActionsTable": {
      "name": "Nosaukums",
      "expression": "Izteiksme",
      "definedFor": "Norādīts:"
    }
  },
  "attributeActionsPage": {
    "name": "Nosaukums",
    "type": "Veids",
    "deleteGroupPopupTitle": "Dzēst atribūtu darbības grupu",
    "deleteGroupPopupMsg": "Dzēšot grupu, no visiem saistītajiem laukiem tiks noņemta atribūtu darbība.",
    "alreadyAppliedActionMsg": "${action} darbība ir lietota šim laukam grupā",
    "alreadyAppliedActionLayerMsg": "${action} darbība ir lietota šajā laukā no slāņu iestatījumiem",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Šai grupai nav saistītu lauki.",
    "presetNoFieldWarningMsg": "Konfigurējiet vismaz vienu lauku sākotnēji iestatītai grupai: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Lauks",
    "valueLabel": "Vērtība",
    "selectValueLabel": "Izvēlēties vērtību",
    "domainFieldHintLabel": "Atlasītā vērtība ir kodētas vērtības domēns. Vērtība: tiks izmantots “${domainValue}”"
  },
  "presetPopup": {
    "presetValueLAbel": "Iepriekš iestatīta vērtība"
  },
  "dataType": {
    "esriFieldTypeString": "Virkne",
    "esriFieldTypeInteger": "Skaitlis",
    "esriFieldTypeDate": "Datums",
    "esriFieldTypeGUID": "GUID (vispārēji unikāls identifikators)"
  },
  "relativeDates": {
    "dateTypeLabel": "Datuma veids",
    "valueLabel": "Vērtība",
    "fixed": "Fiksēts",
    "current": "Pašreizējs",
    "past": "Notikušie",
    "future": "Nākotnes",
    "popupTitle": "Izvēlēties vērtību",
    "hintForFixedDateType": "Padoms. Norādītais datums un laiks tiks izmantots kā iepriekš iestatīta noklusējuma vērtība",
    "hintForCurrentDateType": "Padoms. Pašreizējais datums un laiks tiks izmantots kā iepriekš iestatīta noklusējuma vērtība",
    "hintForPastDateType": "Padoms. Lai noteiktu iepriekš iestatīto noklusējuma vērtību, norādītā vērtība tiks atņemta no pašreizējā datuma un laika.",
    "hintForFutureDateType": "Padoms. Lai noteiktu iepriekš iestatīto noklusējuma vērtību, norādītā vērtība tiks pieskaitīta pašreizējam datumam un laikam.",
    "noDateDefinedTooltip": "Datums nav noteikts",
    "relativeDateWarning": "Lai saglabātu iepriekš iestatīto noklusējuma vērtību, jānorāda datuma un laika vērtība.",
    "customLabel": "Pielāgots"
  },
  "relativeDomains": {
    "fieldSetTitle": "Saraksts",
    "valueText": "Vērtība",
    "defaultText": "Noklusējums",
    "selectedDomainFieldsHint": "Izvēlētie domēna lauki: ${domainFields}",
    "selectDefaultDomainMsg": "Izvēlieties noklusējuma domēnu vai atzīmējiet izvēlētā noklusējuma domēna izvēles lodziņu"
  }
});