define({
  "_widgetLabel": "属性一括編集",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "レイヤー名",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "編集可能なレイヤーが構成されていません",
  "editorPopupTitle": "属性一括編集",
  "editorPopupSaveBtn": "保存",
  "editorPopupMultipleValues": "",
  "clear": "消去",
  "featuresUpdated": "${0}/${1} 個のフィーチャが更新されました",
  "featuresSelected": "${0} 個のフィーチャが選択されました",
  "featuresSkipped": "バイパスされました",
  "featuresNoPermision": "${0} 個のフィーチャが選択されましたが、編集する権限がありません。",
  "search": "検索",
  "queryInput": "検索する値の入力",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "フィルターを正しく設定してください。",
  "filterPopup": "レイヤーのフィルター",
  "filterAppend": "フィルターがこのレイヤーの Web マップにすでに存在する場合",
  "filterAppendOR": "既存のマップ フィルターに条件式のいずれかを追加",
  "filterAppendAND": "既存のマップ フィルターにすべての条件式を追加",
  "cancel": "キャンセル",
  "noValue": "値がありません",
  "emptyString": "空の文字列",
  "existingValue": "既存の値を維持",
  "newDate": "新しい日付",
  "valueChooser": "値の選択/入力",
  "ok": "OK",
  "drawBox": {
    "point": "ポイント",
    "line": "ライン",
    "polyline": "ポリライン",
    "freehandPolyline": "フリーハンド ポリライン",
    "extent": "範囲",
    "polygon": "ポリゴン",
    "freehandPolygon": "フリーハンド ポリゴン",
    "clear": "消去",
    "addPointToolTip": "このエリア内でクリックして選択します",
    "addShapeToolTip": "図形を描画してフィーチャを選択します",
    "freehandToolTip": "マウス ボタンを押したまま図形を描画してフィーチャを選択します",
    "startToolTip": "図形を描画してフィーチャを選択します"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "${0} のフィーチャが無効な ID を返しました",
    "noSelectedLayers": "更新するレコードを持つレイヤーが選択されていません",
    "inputValueError": "フォーム内の値が無効です。",
    "saveError": "${0} フィーチャを保存できません",
    "requiredValue": "必須の値"
  }
});