define({
  "transparencyLabel": "Transparenz",
  "outline": "Umrisslinie",
  "fill": "Füllung (Farbe wird nur angewendet, wenn der Style auf Vollfarbe festgelegt ist)",
  "style": "Style",
  "mandatoryLabel": "Entfernung für obligatorische Evakuierung",
  "mandatoryButtonLabel": "Einstellungen für Entfernung für obligatorische Evakuierung konfigurieren",
  "safeLabel": "Entfernung für sichere Evakuierung",
  "safeButtonLabel": "Einstellungen für Entfernung für sichere Evakuierung konfigurieren",
  "selectOpLayerLabel": "Operationalen Layer für die Ergebnisse auswählen",
  "selectDefaultMeasurementLabel": "Standardmesseinheit auswählen",
  "helpIconTooltip": "Die Liste der operationalen Layer wird mit Layern der aktuellen Webkarte, die einen Polygon-Geometrietyp aufweisen, gefüllt.",
  "lineStyles": {
    "esriSLSDash": "Strich",
    "esriSLSDashDot": "Strich-Punkt",
    "esriSLSDashDotDot": "Strich-Punkt-Punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Langer Strich",
    "esriSLSLongDashDot": "Langer Strich-Punkt",
    "esriSLSNull": "NULL",
    "esriSLSShortDash": "Kurzer Strich",
    "esriSLSShortDashDot": "Kurzer Strich-Punkt",
    "esriSLSShortDashDotDot": "Kurzer Strich-Punkt-Punkt",
    "esriSLSShortDot": "Kurzer Punkt",
    "esriSLSSolid": "Durchgezogen"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Rückwärts",
    "esriSFSCross": "Kreuzförmig",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Vorwärts",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "NULL",
    "esriSFSSolid": "Vollfarbe",
    "esriSFSVertical": "Vertikal"
  },
  "threatTypeLabel": "Bedrohungstyp",
  "symbologyLabel": "Symbolisierung",
  "generalLabel": "Allgemein",
  "addThreatTypesLabel": "Bedrohungstyp hinzufügen",
  "threatTypeColLabel": "Chemischer Bedrohungstyp",
  "actions": "Aktionen",
  "newThreatTypePopupLabel": "Neuer Bedrohungstyp",
  "chooseDefaultThreatTypeIconLabel": "Aus Standard auswählen",
  "mandatoryDistance": "Entfernung für obligatorische Evakuierung",
  "safeDistance": "Entfernung für sichere Evakuierung",
  "units": "Einheiten",
  "chooseDefaultThreatLabel": "Standardmäßigen Bedrohungstyp auswählen",
  "defaultThreatTypePopUpLabel": "Standardmäßige Bedrohungstypen",
  "editThreatLabel": "Bedrohung bearbeiten",
  "defaultThreatTypeIconTooltip": "Liste der standardmäßigen Bedrohungstypen",
  "uniqueThreatTypeMsg": "Geben Sie einen eindeutigen Bedrohungstyp an. Ein Bedrohungstyp mit diesem Namen ist bereits vorhanden.",
  "requiredThreatTypeMsg": "Dies ist ein Pflichtfeld",
  "unitMeasureLabel": "Entfernungen sind in {0} angegeben",
  "pipeBombLabel": "Rohrbombe",
  "suicideBombLabel": "Selbstmordattentat",
  "briefcaseLabel": "Aktenkoffer",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/Van",
  "smallDeliveryTruckLabel": "Kleiner Lieferwagen",
  "containerWaterTruckLabel": "Container-Lkw/Wassertankwagen",
  "semiTrailerLabel": "Sattelschlepper",
  "lpgSafeDistanceLable": "Sichere Entfernung",
  "fireBallDiameterLable": "Feuerball-Durchmesser",
  "lpgthreatTypeColLabel": "Bedrohungstyp Flüssiggas",
  "threatTypeCatagoryLabel": "Bedrohungstyp-Kategorie",
  "chemicalThreatLegendLabel": "Chemische Bedrohung",
  "lpgThreatLegendLabel": "Bedrohung durch Flüssiggas",
  "fireballButtonLabel": "Einstellungen für Feuerball-Durchmesser konfigurieren",
  "safeDistanceButtonLabel": "Einstellungen für sichere Entfernung konfigurieren",
  "chemicalThreatCatagoryLabel": "Chemikalie",
  "lpgThreatCatagoryLabel": "Flüssiggas",
  "smallLPGTank": "Kleiner Flüssiggastank",
  "largeLPGTank": "Großer Flüssiggastank",
  "commercialResidentialLPGTank": "Gewerblicher/privater Flüssiggastank",
  "smallLPGTruck": "Kleiner Flüssiggas-Lkw",
  "semiTankerLPG": "Flüssiggas-Tankauflieger"
});