define({
  "addLocation": "Pridať jednotku umiestnenia",
  "addDistance": "Pridať jednotku dĺžky",
  "addArea": "Pridať jednotku plochy",
  "label": "Označenie",
  "abbr": "Skratka",
  "conversion": "Konverzia",
  "actions": "Akcie",
  "areaUnits": "Jednotky plochy",
  "distanceUnits": "Jednotky dĺžky",
  "kilometers": "Kilometre",
  "miles": "Míle",
  "meters": "Metre",
  "feet": "Stopy",
  "yards": "Yardy",
  "nauticalmiles": "Námorné míle",
  "squareKilometers": "Štvorcové kilometre",
  "squareMiles": "Štvorcové míle",
  "acres": "Akre",
  "hectares": "Hektáre",
  "squareMeters": "Štvorcové metre",
  "squareFeet": "Štvorcové stopy",
  "squareYards": "Štvorcové yardy",
  "location": "Umiestnenia",
  "distance": "Vzdialenosti",
  "area": "Plochy",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km^2",
  "squareMilesAbbreviation": "mi^2",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m^2",
  "squareFeetAbbreviation": "ft^2",
  "squareYardsAbbreviation": "yd^2",
  "defineUnits": "Definovať jednotky merania.",
  "operationalLayer": "Pridať nákres ako operačnú vrstvu mapy."
});