define({
  "_widgetLabel": "Smart redigering",
  "_featureAction_SmartEditor": "Smart redigering",
  "noEditPrivileges": "Kontoen har ikke rettigheter til å opprette eller endre data.",
  "loginPopupTitle": "Logg på",
  "loginPopupMessage": "${widgetName} krever tillatelser og credits for å slå opp og lagre adresseinformasjon. Vil du logge på og bruke denne funksjonen?",
  "noCreditsOrPrivilegeWarningMessage": "Kontoen din har ikke tillatelser og credits som kreves for å slå opp og lagre adresseinformasjon med ${widgetName}. Kontakt organisasjonens administrator for å be om tillatelser og credits.",
  "unableToUseLocator": "Lokator er ikke tilgjengelig. Adresseattributthandlingen(e) kan ikke utføres.",
  "locatorDisabledWaning": "Lokator er ikke aktivert. Kontakt organisasjonens administrator for å be om denne funksjonen.",
  "noFeatureInAIWarning": "Ingen geoobjekt(er) er valgt. Velg et geoobjekt for å redigere, eller klikk på Avbryt for å gå tilbake til hovedskjermen.",
  "noEditableLayerWarning": "Kontoen din har ikke tillatelse til å opprette eller endre data, eller det kan hende dette webkartet ikke inneholder lag som kan redigeres.",
  "noVisibleCreateLayerWarning": "Laget/lagene er ikke synlige med nåværende zoomnivå. Zoom inn eller ut for å opprette/endre geoobjekter.",
  "noVisibleUpdateLayerWarning": "Laget/lagene er ikke synlige med nåværende zoomnivå. Zoom inn eller ut for å endre geoobjekter.",
  "checkLayerVisibilityInWebMapWarning": "Sørg for at lagene er synlige i kartet når du skal opprette eller endre geoobjekter.",
  "showSelectionInAITitle": "Valgte geoobjekter",
  "showSelectionInAIMsg": "Vil du laste inn gjeldende utvalg i ${widgetName}?",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Ikke aktiv",
  "pressStr": "Trykk på ",
  "ctrlStr": " CTRL ",
  "snapStr": " for å aktivere festing",
  "noAvailableTempaltes": "Ingen tilgjengelige maler",
  "editorCache": " - Redigeringsbuffer",
  "presetFieldAlias": "Felt",
  "presetValue": "Forhåndsinnstilt verdi",
  "usePresetValues": " Bruk forhåndsinnstilte verdier (kun nye geoobjekter)",
  "editGeometry": " Rediger geometri",
  "savePromptTitle": "Lagre geoobjekt",
  "savePrompt": "Vil du lagre gjeldende geoobjekt?",
  "deletePromptTitle": "Slett geoobjekt",
  "deleteAttachment": "Slett vedlegg",
  "deletePrompt": "Er du sikker på at du vil slette det valgte geoobjektet?",
  "attachmentLoadingError": "Feil under opplasting av vedlegg",
  "attachmentSaveDeleteWarning": "Advarsel: Endringer i vedlegg lagres automatisk",
  "autoSaveEdits": "Lagre nye geoobjekter automatisk",
  "addNewFeature": "Opprett nytt geoobjekt",
  "featureCreationFailedMsg": "Kan ikke opprette ny post / nytt geoobjekt",
  "relatedItemTitle": "Relatert tabell/lag",
  "relatedFeatureCount": "${layerTitle} med ${featureCount} geoobjekter",
  "createNewFeatureLabel": "Opprett nytt geoobjekt for ${layerTitle}",
  "invalidRelationShipMsg": "Kontroller at feltet for primærnøkkel: '${parentKeyField}' inneholder en gyldig verdi",
  "pendingFeatureSaveMsg": "Lagre geoobjektsredigeringene før du oppretter et relatert geoobjekt.",
  "attachmentsRequiredMsg": "(*) Vedlegg er obligatorisk.",
  "coordinatePopupTitle": "Flytt geoobjekt til XY-posisjonen",
  "coordinatesSelectTitle": "Koordinatsystem:",
  "mapSpecialReferenceDropdownOption": "Kartets romlige referanse",
  "latLongDropdownOption": "Lengdegrad/breddegrad",
  "mgrsDropdownOption": "Militært rutenettsystem (MGRS)",
  "mgrsTextBoxLabel": "Koordinat:",
  "xAttributeTextBoxLabel": "X-koordinat:",
  "yAttributeTextBoxLabel": "Y-koordinat:",
  "latitudeTextBoxLabel": "Breddegrad:",
  "longitudeTextBoxLabel": "Lengdegrad:",
  "presetGroupFieldsLabel": "${groupName} blir brukt på følgende lagfelt:",
  "presetGroupNoFieldsLabel": "${groupName} har ingen tilknyttede felt",
  "groupInfoLabel": "Gruppeinformasjon for ${groupName}",
  "editGroupInfoIcon": "Rediger gruppeverdi for ${groupName}",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Ingen tilgjengelige maler",
    "searchTemplates": "Søk i maler",
    "filterLayerLabel": "Filtrer kartlag"
  },
  "invalidConfiguration": "Widgeten er ikke konfigurert eller lagene i konfigurasjonen finnes ikke i kartet lenger. Åpne appen i byggemodus, og konfigurer widgeten på nytt.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente URL for geometritjeneste",
  "clearSelection": "Lukk",
  "refreshAttributes": "Oppdater dynamiske geoobjektattributter",
  "automaticAttributeUpdatesOn": "Oppdater geoobjektattributter automatisk: PÅ",
  "automaticAttributeUpdatesOff": "Oppdater geoobjektattributter automatisk: AV",
  "moveSelectedFeatureToGPS": "Flytt det valgte geoobjektet til gjeldende GPS-posisjon",
  "moveSelectedFeatureToXY": "Flytt det valgte geoobjektet til XY-posisjonen",
  "mapNavigationLocked": "Kartnavigering: Låst",
  "mapNavigationUnLocked": "Kartnavigering: Ulåst",
  "copyFeatures": {
    "title": "Kopier geoobjekter",
    "createFeatures": "Opprett geoobjekter",
    "createSingleFeature": "Opprett ett geoobjekt med flere deler",
    "createOneSingleFeature": "Opprett geoobjekt",
    "noFeaturesSelectedMessage": "Ingen geoobjekter valgt",
    "selectFeatureToCopyMessage": "Velg geoobjekter som skal kopieres",
    "multipleFeatureSaveWarning": "Merk: Hvis du oppretter flere geoobjekter med kopifunksjonen, lagres alle de nye geoobjektene umiddelbart.",
    "copyFeatureUpdateGeometryError": "Kan ikke oppdatere geometrien i de valgte geoobjektene",
    "canNotSaveMultipleFeatureWarning": "Merk: Kan ikke kopiere flere geoobjekter med samme verdi i unike verdifelt. Velg bare ett geoobjekt.",
    "createOnlyOneMultipartFeatureWarning": "Merk: Bare ett geoobjekt med flere deler kan opprettes"
  },
  "addingFeatureError": "Feil under tillegging av valgte geoobjekter i laget. Prøv på nytt.",
  "addingFeatureErrorCount": "${copyFeatureErrorCount} geoobjekt(er) ble ikke kopiert. Vil du prøve på nytt for geoobjektet/geoobjektene som mangler?",
  "selectingFeatureError": "Feil under valg av geoobjekter i laget. Prøv på nytt.",
  "customSelectOptionLabel": "Velg geoobjekter som skal kopieres",
  "noFeatureSelectedMessage": "Ingen geoobjekter er valgt",
  "multipleFeatureSaveMessage": "Alle geoobjektene blir lagret umiddelbart. Vil du fortsette?",
  "relativeDates": {
    "dateTypeLabel": "Datotype",
    "valueLabel": "Verdi",
    "fixed": "Fast",
    "current": "Gjeldende",
    "past": "Tidligere",
    "future": "Fremtidig",
    "popupTitle": "Velg verdi",
    "hintForFixedDateType": "Hint: Angitt dato og klokkeslett brukes som forhåndsinnstilt standardverdi.",
    "hintForCurrentDateType": "Hint: Gjeldende dato og klokkeslett brukes som forhåndsinnstilt standardverdi.",
    "hintForPastDateType": "Hint:  Den angitte verdien trekkes fra gjeldende dato og klokkeslett for standardverdien for forhåndsinnstillingen.",
    "hintForFutureDateType": "Hint: Den angitte verdien legges til gjeldende dato og klokkeslett for standardverdien for forhåndsinnstillingen.",
    "noDateDefinedTooltip": "Ingen dato angitt",
    "relativeDateWarning": "Det må angis en verdi for dato og klokkeslett for å kunne lagre standardverdien for forhåndsinnstilling.",
    "customLabel": "Tilpasset",
    "layerLabel": "Lag",
    "domainFieldHintLabel": "Den valgte verdien er et kodet verdiområde. Verdien: ${domainValue} brukes"
  },
  "valuePicker": {
    "popupTitle": "Velg verdi",
    "popupHint": "Gjeldende geoobjekt krysser flere geoobjekter, velg en verdi for de respektive feltene",
    "buttonTooltip": "Velg verdi fra flere kryssende geoobjekter"
  },
  "uniqueValueErrorMessage": "Verdien i «${fieldName}» finnes allerede. Oppgi en ny verdi.",
  "requiredFields": {
    "displayMsg": "Obligatoriske felter må fylles ut. Angi verdier for fellesfelt nedenfor.",
    "popupTittle": "Obligatoriske felter",
    "foundNullRecordCount": "${fieldName} (Funnet i ${count} poster)"
  },
  "cantLocateUserLocation": "Kan ikke fastsette lokasjonen din",
  "tryAgainButtonLabel": "Prøv på nytt",
  "copyFeatureFailedPopupTitle": "Ops!"
});