define({
  "transparencyLabel": "Prosojnost",
  "outline": "Obroba",
  "fill": "Polnilo (barva se uporablja le, če je slog nastavljen na enobarvno polnilo)",
  "style": "Slog",
  "selectOpLayerLabel": "Izberi operativni sloj za rezultate",
  "selectDefaultMeasurementLabel": "Izberi privzeto mersko enoto",
  "helpIconTooltip": "Seznam operativnega sloja je poseljen s sloji iz trenutne spletne karte, ki so poligonske geometrijske vrste.",
  "lineStyles": {
    "esriSLSDash": "Črtica",
    "esriSLSDashDot": "Črtica pika",
    "esriSLSDashDotDot": "Črtica pika pika",
    "esriSLSDot": "Pika",
    "esriSLSLongDash": "Dolga črtica",
    "esriSLSLongDashDot": "Dolga črtica pika",
    "esriSLSNull": "Brez vrednosti",
    "esriSLSShortDash": "Kratka črtica",
    "esriSLSShortDashDot": "Kratka črtica pika",
    "esriSLSShortDashDotDot": "Kratka črtica pika pika",
    "esriSLSShortDot": "Kratka pika",
    "esriSLSSolid": "Enobarvno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Nazaj",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Diagonalno",
    "esriSFSForwardDiagonal": "Naprej",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Brez vrednosti",
    "esriSFSSolid": "Enobarvno",
    "esriSFSVertical": "Vertikalno"
  },
  "threatTypeLabel": "Vrsta nevarnosti",
  "generalLabel": "Splošno",
  "addThreatTypesLabel": "Dodajte vrsto nevarnosti",
  "actions": "Dejanja",
  "newThreatTypePopupLabel": "Nova vrsta nevarnosti",
  "units": "Enote",
  "chooseDefaultThreatLabel": "Izberite privzeto vrsto nevarnosti",
  "defaultThreatTypePopUpLabel": "Privzete vrste nevarnosti",
  "editThreatLabel": "Uredite nevarnost",
  "defaultThreatTypeIconTooltip": "Seznam privzetih vrst nevarnosti",
  "uniqueThreatTypeMsg": "Vnesite enolično vrsto nevarnosti, vrsta nevarnosti s tem imenom že obstaja.",
  "requiredMsg": "To polje ni obvezno",
  "unitMeasureLabel": "Razdalje so v {0}",
  "chooseDefaultThreatTypeIconLabel": "Izberite izmed privzetega",
  "pipeBombLabel": "Cevna bomba",
  "suicideBombLabel": "Samomorilska bomba",
  "briefcaseLabel": "Aktovka",
  "carLabel": "Avto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Majhno dostavno vozilo",
  "containerWaterTruckLabel": "Zabojnik/tovornjak za prevažanje vode",
  "semiTrailerLabel": "Polpriklopnik",
  "chemicalThreatLegendLabel": "Kemična nevarnost",
  "lpgThreatLegendLabel": "Nevarnost UNP",
  "smallLPGTank": "Majhen rezervoar z UNP",
  "largeLPGTank": "Velik rezervoar z UNP",
  "commercialResidentialLPGTank": "Komercialni/stanovanjski rezervoar z UNP",
  "smallLPGTruck": "Majhno tovorno vozilo z UNP",
  "semiTankerLPG": "Polpriklopnik s cisterno UNP",
  "threatDescriptionColLabel": "Opis nevarnosti",
  "addThreatZoneButtonLabel": "Dodajte cono nevarnosti",
  "zoneDescColLabel": "Opis cone",
  "distanceLabel": "Razdalja (${unitAbbr})",
  "threatTypeHelp": "<p>Prepričajte se, da so izpolnjeni naslednji pogoji za vrsto nevarnosti:<br/><ul><li>Vrsta nevarnosti ne more biti nedoločena in mora biti enolična</li><li>Nevarnost mora imeti vsaj eno veljavno cono</li><li>Opis cone mora biti enoličen za nevarnost</li></ul><p/>",
  "descriptionLabel": "Opis",
  "newThreatZonePopupLabel": "Nova cona nevarnosti",
  "editThreatZonePopupLabel": "Uredite cono nevarnosti",
  "uniqueZoneDescriptionMsg": "Vnesite enoličen opis cone, opis cone s tem imenom že obstaja.",
  "symbologyColLabel": "Simbologija",
  "zoneDescriptionColLabel": "Opis cone",
  "uniqueZoneRequiredMsg": "Ime cone mora biti enolično za",
  "interactive": "Interaktivno",
  "fromCoord": "Fiksne koordinate",
  "existingFeature": "Iz obstoječih geoobjektov",
  "defaultInputLocationLabel": "Privzeta vhodna lokacija",
  "defaultInputLayer": "Privzeti vhodni sloj",
  "defaultThreatType": "Privzeta vrsta nevarnosti",
  "selectLabel": "Izberi",
  "mandatoryLabel": "Obvezna razdalja za evakuacijo",
  "safeLabel": "Varna razdalja za evakuacijo",
  "lpgSafeDistanceLable": "Varna razdalja",
  "fireBallDiameterLable": "Premer ognjene krogle"
});