define({
  "_widgetLabel": "Редактор на партиден атрибут",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Име на слой",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Няма конфигурирани слоеве за редактиране",
  "editorPopupTitle": "Редактор на партидни атрибути",
  "editorPopupSaveBtn": "Запазване",
  "editorPopupMultipleValues": "",
  "clear": "Изчистване",
  "featuresUpdated": "${0} / ${1} обновен обект(и)",
  "featuresSelected": "${0} избран обект (и)",
  "featuresSkipped": "Заобиколен",
  "featuresNoPermision": "Избран (-и) е/са ${0} обект (-и), но няма разрешения за редактиране.",
  "search": "Търсене",
  "queryInput": "Въведете стойност за заявка",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Моля, задайте правилно филтър.",
  "filterPopup": "Филтър на слой",
  "filterAppend": "Ако в уеб картата вече съществува филтър за този слой",
  "filterAppendOR": "Добавяне на произволен израз към съществуващия филтър на картата",
  "filterAppendAND": "Добавяне на всички изрази към съществуващия филтър на картата",
  "cancel": "Отказ",
  "noValue": "Няма стойност",
  "emptyString": "Празен низ",
  "existingValue": "Запазване на съществуващата стойност",
  "newDate": "Нова дата",
  "valueChooser": "Избор/Тип стойност",
  "ok": "Ок",
  "drawBox": {
    "point": "Точка",
    "line": "Линия",
    "polyline": "Полилиния",
    "freehandPolyline": "Произволна полилиния",
    "extent": "Обхват",
    "polygon": "Полигон",
    "freehandPolygon": "Произволен полигон",
    "clear": "Изчистване",
    "addPointToolTip": "Натиснете, за да иберете в тази област",
    "addShapeToolTip": "Изчертаване на форма за избор на обекти",
    "freehandToolTip": "Натиснете и задръжте, за да изчертаете форма за избор на обекти",
    "startToolTip": "Изчертаване на форма за избор на обекти"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Обектът от ${0} върна невалиден идентификатор",
    "noSelectedLayers": "Няма избрани слоеве със записи за обновяване",
    "inputValueError": "Невалидна стойност във формуляра",
    "saveError": "${0} обекта не могат да се запишат",
    "requiredValue": "Необходима стойност"
  }
});