define({
  "_widgetLabel": "Edytor atrybutów wsadowych",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nazwa warstwy tematycznej",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Brak skonfigurowanych edytowalnych warstw",
  "editorPopupTitle": "Edytor atrybutów wsadowych",
  "editorPopupSaveBtn": "Zapisz",
  "editorPopupMultipleValues": "",
  "clear": "Wyczyść",
  "featuresUpdated": "Uaktualnione obiekty: ${0} / ${1}",
  "featuresSelected": "Wybrane obiekty: ${0}",
  "featuresSkipped": "Pominięte",
  "featuresNoPermision": "Wybrano następującą liczbę obiektów: ${0}, brakuje jednak uprawnień do edycji.",
  "search": "Szukaj",
  "queryInput": "Wprowadź wartość do zapytania",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Skonfiguruj poprawnie filtr.",
  "filterPopup": "Filtruj warstwę",
  "filterAppend": "Jeśli filtr już istnieje na mapie internetowej dla tej warstwy",
  "filterAppendOR": "Dołącz dowolne wyrażenie do istniejącego filtru map",
  "filterAppendAND": "Dołącz wszystkie wyrażenia do istniejącego filtru map",
  "cancel": "Anuluj",
  "noValue": "Brak wartości",
  "emptyString": "Pusty ciąg",
  "existingValue": "Zachowaj istniejącą wartość",
  "newDate": "Nowa data",
  "valueChooser": "Wybierz/wprowadź wartość",
  "ok": "OK",
  "drawBox": {
    "point": "Punkt",
    "line": "Linia",
    "polyline": "Polilinia",
    "freehandPolyline": "Polilinia odręczna",
    "extent": "Zasięg",
    "polygon": "Wielokąt",
    "freehandPolygon": "Poligon odręczny",
    "clear": "Wyczyść",
    "addPointToolTip": "Kliknij, aby wybrać na tym obszarze",
    "addShapeToolTip": "Aby wybrać obiekty, zaznacz obszar",
    "freehandToolTip": "Naciśnij i przytrzymaj, aby narysować kształt w celu zaznaczenia obiektów",
    "startToolTip": "Aby wybrać obiekty, zaznacz obszar"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Obiekt z ${0} zwrócił nieprawidłowy identyfikator",
    "noSelectedLayers": "Brak wybranych warstw z rekordami do uaktualnienia",
    "inputValueError": "Nieprawidłowa wartość w formularzu",
    "saveError": "Nie można zapisać obiektów: ${0}",
    "requiredValue": "Wartość wymagana"
  }
});