define({
  "serviceUrl": "Nastaviť url adresu služby:",
  "minIntSpacingLabel": "Minimálna veľkosť mriežky",
  "lineOpacityLabel": "Nepriehľadnosť línie",
  "labelOpacityLabel": "Nepriehľadnosť označenia",
  "centerLabelOpacityLabel": "Centrovať nepriehľadnosť označenia",
  "gridZonePlacementLabel": "Umiestnenie označenia zóny mriežky",
  "verticalLineLabels": "Označenia zvislých línií",
  "styleHeaderLabel": "Štýl",
  "indexHeaderLabel": "Komponent mriežky",
  "colorHeaderLabel": "Farba",
  "fontSizeHeaderLabel": "Veľkosť písma",
  "lineWidthHeaderLabel": "Šírka línie",
  "horizontalLabel": "Vodorovný",
  "verticalLabel": "Zvislý",
  "upperLeftLabel": "Vyššia ľavá",
  "upperRightLabel": "Vyššia pravá",
  "lowerLeftLabel": "Nižšia ľavá",
  "lowerRightLabel": "Nižšia pravá",
  "centerLabel": "V strede (vodorovne)",
  "errorMessage": "Konfiguračná stránka obsahuje chyby. Prosím opravte pred uložením.",
  "checkBoxLabel": "Zobraziť mriežku po zatvorení widgetu",
  "checkBoxLabelDashboard": "Zobraziť mriežku",
  "gzd": "Označenie zóny mriežky (Grid Zone Designator)",
  "gsid": "${number}-metrová identifikačná štvorcová mriežka (GSID)",
  "grid10k": "${number}-metrové línie mriežky",
  "grid1k": "${number}-metrové línie mriežky",
  "grid100m": "100-metrové línie mriežky",
  "grid10m": "10-metrové línie mriežky",
  "switchBasemap": "Prepnúť základnú mapu"
});