define({
  "_widgetLabel": "Okos szerkesztő",
  "_featureAction_SmartEditor": "Okos szerkesztő",
  "noEditPrivileges": "A fiókja nem teszi lehetővé az adatok létrehozását vagy módosítását.",
  "loginPopupTitle": "Bejelentkezés",
  "loginPopupMessage": "A(z) ${widgetName} widgetnek jogosultságra és kreditekre van szüksége a címadatok kereséséhez és tárolásához. Szeretne bejelentkezni, hogy használhassa a funkciót?",
  "noCreditsOrPrivilegeWarningMessage": "Fiókja nem rendelkezik az ahhoz szükséges jogosultságokkal és kreditekkel, hogy címadatokat kereshessen és tárolhasson a(z) ${widgetName} widgettel. A jogosultságok és kreditek igénylésével kapcsolatban forduljon a szervezete adminisztrátorához.",
  "unableToUseLocator": "A jelölő nem hozzáférhető. A cím attribútumműveletének végrehajtása nem történik meg.",
  "locatorDisabledWaning": "A jelölő nincs engedélyezve. A funkció engedélyezésének igénylésével kapcsolatban forduljon szervezete adminisztrátorához.",
  "noFeatureInAIWarning": "Nincs vektoros elem kiválasztva. Válassza ki a módosítani kívánt vektoros elemet, vagy pedig a Mégse gombra kattintva térjen vissza a főképernyőre.",
  "noEditableLayerWarning": "Fiókja nem rendelkezik az adatok létrehozásához vagy módosításához szükséges jogosultsággal, vagy pedig ez a webtérkép nem tartalmaz szerkeszthető rétegeket.",
  "noVisibleCreateLayerWarning": "Az aktuális nagyítási/kicsinyítési szinten nem láthatók rétegek. Vektoros elem létrehozásához/módosításához nagyítson vagy kicsinyítsen.",
  "noVisibleUpdateLayerWarning": "Az aktuális nagyítási/kicsinyítési szinten nem láthatók rétegek. Vektoros elem módosításához nagyítson vagy kicsinyítsen.",
  "checkLayerVisibilityInWebMapWarning": "Ha vektoros elemet kíván létrehozni vagy módosítani, győződjön meg róla, hogy a térképen láthatók rétegek.",
  "showSelectionInAITitle": "Kiválasztott vektoros elemek",
  "showSelectionInAIMsg": "Kívánja betölteni az aktuális kijelölést a(z) ${widgetName} widgetben?",
  "widgetActive": "Aktív",
  "widgetNotActive": "Nem aktív",
  "pressStr": "Nyomja meg a ",
  "ctrlStr": " CTRL ",
  "snapStr": " billentyűt a hozzáillesztés engedélyezéséhez",
  "noAvailableTempaltes": "Nincsenek elérhető sablonok",
  "editorCache": " - Szerkesztő gyorsítótára",
  "presetFieldAlias": "Mező",
  "presetValue": "Előre beállított érték",
  "usePresetValues": " Előre beállított értékek használata (csak új vektoros elemekhez)",
  "editGeometry": " Geometria szerkesztése",
  "savePromptTitle": "Vektoros elem mentése",
  "savePrompt": "Szeretné menteni az aktuális vektoros elemet?",
  "deletePromptTitle": "Vektoros elem törlése",
  "deleteAttachment": "Csatolmány törlése",
  "deletePrompt": "Biztosan törli a kiválasztott vektoros elemet?",
  "attachmentLoadingError": "Hiba a csatolmányok feltöltésekor",
  "attachmentSaveDeleteWarning": "Figyelmeztetés: A csatolmányok módosításai automatikusan mentésre kerülnek",
  "autoSaveEdits": "Új vektoros elemek automatikus mentése",
  "addNewFeature": "Új vektoros elem létrehozása",
  "featureCreationFailedMsg": "Nem lehet új rekordot/vektoros elemet létrehozni",
  "relatedItemTitle": "Kapcsolt tábla/réteg",
  "relatedFeatureCount": "${layerTitle} ${featureCount} vektoros elemmel",
  "createNewFeatureLabel": "Új vektoros elem létrehozása ehhez: ${layerTitle}",
  "invalidRelationShipMsg": "Győződjön meg arról, hogy az elsődleges kulcs '${parentKeyField}' mezőjében érvényes érték szerepel",
  "pendingFeatureSaveMsg": "Mentse a vektoros elem módosításait, mielőtt kapcsolt vektoros elemet hoz létre.",
  "attachmentsRequiredMsg": "(*) A csatolmányok megadása kötelező.",
  "coordinatePopupTitle": "A vektoros elem áthelyezése XY helyszínre",
  "coordinatesSelectTitle": "Koordináta-rendszer:",
  "mapSpecialReferenceDropdownOption": "Térkép koordináta-rendszere",
  "latLongDropdownOption": "Hosszúság/szélesség",
  "mgrsDropdownOption": "Katonai keresőhálózati rendeszer (MGRS)",
  "mgrsTextBoxLabel": "Koordináta:",
  "xAttributeTextBoxLabel": "X-koordináta:",
  "yAttributeTextBoxLabel": "Y-koordináta:",
  "latitudeTextBoxLabel": "Szélesség:",
  "longitudeTextBoxLabel": "Hosszúság:",
  "presetGroupFieldsLabel": "A(z) '${groupName}' a következő rétegmezőkre lesz alkalmazva:",
  "presetGroupNoFieldsLabel": "A(z) '${groupName}' nem rendelkezik egyetlen kapcsolódó mezővel sem",
  "groupInfoLabel": "Csoportinformációk ehhez: '${groupName}'",
  "editGroupInfoIcon": "Csoportérték szerkesztése ehhez: ${groupName}",
  "filterEditor": {
    "all": "Mind",
    "noAvailableTempaltes": "Nincsenek elérhető sablonok",
    "searchTemplates": "Sablonok keresése",
    "filterLayerLabel": "Szűrőrétegek"
  },
  "invalidConfiguration": "A widget nincs konfigurálva, vagy a konfigurációban lévő rétegek már nem szerepelnek a térképen. Nyissa meg az alkalmazást építő módban, és konfigurálja újra a widgetet.",
  "geometryServiceURLNotFoundMSG": "Nem sikerült meghatározni a geometriai adatszolgáltatás URL-címét",
  "clearSelection": "Bezárás",
  "refreshAttributes": "Dinamikus vektoroselem-attribútumok frissítése",
  "automaticAttributeUpdatesOn": "A vektoros elemek attribútumainak frissítése: BE",
  "automaticAttributeUpdatesOff": "A vektoros elemek attribútumainak frissítése: KI",
  "moveSelectedFeatureToGPS": "A kijelölt vektoros elem áthelyezése az aktuális GPS helyszínre",
  "moveSelectedFeatureToXY": "A kijelölt vektoros elem áthelyezése XY helyszínre",
  "mapNavigationLocked": "Térképnavigáció: zárolva",
  "mapNavigationUnLocked": "Térképnavigáció: engedélyezve",
  "copyFeatures": {
    "title": "Vektoros elemek másolása",
    "createFeatures": "Vektoros elemek létrehozása",
    "createSingleFeature": "1 több részes vektoros elem létrehozása",
    "createOneSingleFeature": "Vektoros elem létrehozása",
    "noFeaturesSelectedMessage": "Nincsenek vektoros elemek kijelölve",
    "selectFeatureToCopyMessage": "Válassza ki a másolni kívánt vektoros elemet",
    "multipleFeatureSaveWarning": "Tipp: Ha a Másolás funkcióval hoz létre több vektoros elemet, a rendszer az összes új vektoros elemet azonnal menti.",
    "copyFeatureUpdateGeometryError": "A kiválasztott vektoros elemek geometriájának frissítése nem lehetséges.",
    "canNotSaveMultipleFeatureWarning": "Megjegyzés: Több vektoros elem nem másolható, ha az egyedi mezők értékei azonosak. Kérjük, csak egy vektoros elemet válasszon ki.",
    "createOnlyOneMultipartFeatureWarning": "Megjegyzés: Csak egy többrészes vektoros elemet lehet létrehozni"
  },
  "addingFeatureError": "Hiba történt a rétegben lévő, kiválasztott vektoros elemek hozzáadásakor. Próbálja meg újra.",
  "addingFeatureErrorCount": "„${copyFeatureErrorCount}” vektoros elem másolása nem sikerült. Megpróbálja újból a hiányzó vektoros elem(ekre) vonatkozóan?",
  "selectingFeatureError": "Hiba történt a rétegben lévő vektoros elemek kiválasztásakor. Próbálja meg újra.",
  "customSelectOptionLabel": "Válassza ki a másolni kívánt vektoros elemeket.",
  "noFeatureSelectedMessage": "Nincsenek vektoros elemek kijelölve",
  "multipleFeatureSaveMessage": "A rendszer az összes vektoros elemet azonnal menti. Folytatni kívánja?",
  "relativeDates": {
    "dateTypeLabel": "Dátumtípus",
    "valueLabel": "Érték",
    "fixed": "Rögzített",
    "current": "Jelenlegi",
    "past": "Elmúlt",
    "future": "Jövőbeli",
    "popupTitle": "Érték kiválasztása",
    "hintForFixedDateType": "Tipp: A rendszer előre beállított alapértelmezett értékként kezeli a megadott dátumot és időt.",
    "hintForCurrentDateType": "Tipp: A rendszer előre beállított alapértelmezett értékként kezeli az aktuális dátumot és időt.",
    "hintForPastDateType": "Tipp: Az előre beállított alapértelmezett érték meghatározásához a rendszer levonja a megadott értéket az aktuális dátumból és időből.",
    "hintForFutureDateType": "Tipp: Az előre beállított alapértelmezett érték meghatározásához a rendszer hozzáadja a megadott értéket az aktuális dátumhoz és időhöz.",
    "noDateDefinedTooltip": "Nincs meghatározva dátum",
    "relativeDateWarning": "Ahhoz, hogy menteni lehessen az alapértelmezett beállított értéket, meg kell adni a dátum vagy az idő értékét.",
    "customLabel": "Egyéni",
    "layerLabel": "Réteg",
    "domainFieldHintLabel": "A kiválasztott érték egy kódolt értéktartomány A következő érték lesz használva: ${domainValue}"
  },
  "valuePicker": {
    "popupTitle": "Érték kiválasztása",
    "popupHint": "Az aktuális vektoros elem több vektoros elemmel is metszésben van, válasszon értéket a vonatkozó mezőnek.",
    "buttonTooltip": "Válasszon értéket a több metsző vektoros elemből"
  },
  "uniqueValueErrorMessage": "Az érték már létezik ebben: „${fieldName}” – adjon meg új értéket.",
  "requiredFields": {
    "displayMsg": "A kötelezően kitöltendő mezők nem lehetnek üresek. Az alábbi általános mezőkbe adjon meg értékeket.",
    "popupTittle": "Kötelező mezők",
    "foundNullRecordCount": "${fieldName} (${count} rekordban szerepel)"
  },
  "cantLocateUserLocation": "A tartózkodási helye nem határozható meg",
  "tryAgainButtonLabel": "Újrapróbálkozás",
  "copyFeatureFailedPopupTitle": "Hoppá!"
});