define({
  "viz_settings": "Nastavenia vizualizácie",
  "viz_type": "Typ vizualizácie",
  "max_height": "Maximálna výška symbolu (metre)",
  "max_width": "Maximálna šírka symbolu (metre)",
  "interval": "Interval (milisekundy)",
  "show_percent": "Zobraziť hodnoty ako percento všetkých hodnôt",
  "show_jettrail_end_points": "Zobraziť koncové body",
  "show_percentage_limited": "Toto je zakázané, pretože počet záznamov je vyšší ako 400.",
  "cycle_colors": "Meniť farby automaticky",
  "area_extrusion": "Vysúvanie plochy",
  "bounce": "Odskok",
  "fireball": "Ohnivá guľa",
  "grid_surface": " Rastrový povrch",
  "jet_trail": "Prúdová stopa",
  "point_extrusion": "Vysúvanie bodu",
  "pulse": "Pulz",
  "layer_settings": "Nastavenia vrstvy",
  "viz_layer": "Vrstva vizualizácie",
  "display_field": "Polia na zobrazenie",
  "add_field": "Pridať pole pre vizualizáciu",
  "field": "Pole",
  "label": "Označenie",
  "actions": "Akcie",
  "no_layers": " Vo vybranej webovej scéne nie sú k dispozícii žiadne vrstvy.",
  "viz_not_supported": "Nie je podporované pre typ geometrie vybranej vrstvy."
});