define({
  "_widgetLabel": "Заявка",
  "executeQueryTip": "Натиснете върху един от следните елементи на задачата, за да изпълните заявката.",
  "invalidConfig": "Невалидна конфигурация. Моля, използвайте страницата за настройка на заявката, за да получите правилна конфигурация.",
  "queryParams": "Опции",
  "parameters": "ОПЦИИ",
  "queries": "ЗАЯВКИ",
  "apply": "Прилагане",
  "queryResults": "Резултати",
  "clear": "Изчистване",
  "noResults": "Няма намерен обект.",
  "queryError": "Неуспешна заявка !",
  "numberFound": "Брой намерени обекти",
  "mapExtentTip": "Ограничете резултатите до текущата област на картата.",
  "noValue": "Няма стойност",
  "and": "и",
  "stringOperatorIs": "е",
  "stringOperatorIsNot": "не е",
  "stringOperatorStartsWith": "започва с/със",
  "stringOperatorEndsWith": "завършва на",
  "stringOperatorContains": "съдържа",
  "stringOperatorDoesNotContain": "не съдържа",
  "stringOperatorIsBlank": "е празно поле",
  "stringOperatorIsNotBlank": "не е празно поле",
  "dateOperatorIsOn": "е включено",
  "dateOperatorIsNotOn": "не е включено",
  "dateOperatorIsBefore": "е преди",
  "dateOperatorIsAfter": "е след",
  "dateOperatorDays": "дни",
  "dateOperatorWeeks": "седмици",
  "dateOperatorMonths": "месеци",
  "dateOperatorInTheLast": "е последното",
  "dateOperatorNotInTheLast": "не е последното",
  "dateOperatorIsBetween": "е между",
  "dateOperatorIsNotBetween": "не е между",
  "dateOperatorIsBlank": "е празно поле",
  "dateOperatorIsNotBlank": "не е празно поле",
  "numberOperatorIs": "е",
  "numberOperatorIsNot": "не е",
  "numberOperatorIsAtLeast": "е най-малко",
  "numberOperatorIsLessThan": "е по-малко от",
  "numberOperatorIsAtMost": "е най-много",
  "numberOperatorIsGreaterThan": "е по-голямо от",
  "numberOperatorIsBetween": "е между",
  "numberOperatorIsNotBetween": "не е между",
  "numberOperatorIsBlank": "е празно поле",
  "numberOperatorIsNotBlank": "не е празно поле",
  "operationalLayerTip": "Добавяне на резултат като оперативен слой",
  "queryResult": "Резултат от заявка",
  "specifyParamsTip": "Посочете параметри за тази задача",
  "useSpatialFilter": "Използвайте пространствен филтър, за да ограничите характеристиките",
  "useCurrentMapExtent": "Само характеристики, пресичащи текущата област на картата",
  "drawGraphicOnMap": "Само обекти, пресичащи определената от потребителя област",
  "specifySpatialFilterMsg": "Моля, задайте пространствен филтър за тази задача.",
  "clearResults": "Изчистване на резултатите",
  "operationalTip": "Когато тази опция е отметната, резултатите ще се запазят на картата, докато бутонът \"${clearResults}\" е натиснат.",
  "noneQueryTip": "Не е конфигурирана задача за заявка за този изпълним модул.",
  "noPermissionsMsg": "Нямате разрешение за достъп до тази услуга",
  "attributesFromRelationship": "Атрибути от свързаната таблица",
  "tasks": "Задачи",
  "applySpatialFilterToLimitResults": "Приложете пространствен филтър, за да ограничите резултатите",
  "useCurrentExtentTip": "Връщат се само обекти в рамките на текущия обхват на картата",
  "useDrawGraphicTip": "Връщат се само обекти, които се пресичат с формата, изчертана на картата.",
  "useFeaturesTip": "Връщат се само обекти, които имат пространствена връзка с обекти в друг слой",
  "noSpatialLimitTip": "Връща обекти в пълния обхват на картата",
  "applySearchDistance": "Използване на разстояние за търсене",
  "spatialRelationship": "Пространствени взаимоотношения",
  "relatedLayer": "Свързан слой",
  "bufferDistance": "Буферно разстояние",
  "miles": "Мили",
  "kilometers": "Километри",
  "feet": "Фут",
  "meters": "Метри",
  "yards": "Ярда",
  "nauticalMiles": "Морски мили",
  "back": "Назад",
  "execute": "Изпълнение",
  "zoomTo": "Мащабиране",
  "openAttributeTable": "Преглед в атрибутивната таблица",
  "noResult": "Няма резултат.",
  "noTask": "Няма задача.",
  "removeThisResult": "Изчистване на този резултат",
  "attributeCriteira": "Критерий за атрибут",
  "spatialFilter": "Пространствен филтър",
  "value": "СТОЙНОСТ",
  "noAttributeSpatialFilterTip": "Няма посочени филтри. Всички обекти ще бъдат върнати.",
  "showAllRelatedRecords": "Показване на всички свързани записи",
  "changeSymbol": "Промяна на символ",
  "queryCriteira": "Критерий за заявка",
  "customQuery": "Персонализирана заявка",
  "layer": "Слой",
  "createCustomQuery": "Създаване на персонализирана заявка.",
  "rename": "Преименуване",
  "clearShapeTip": "Изчистете тази форма след прилагане на заявката.",
  "displayedFeatures": "Показани обекти",
  "loadMore": "Зареждане на още",
  "expandAll": "Разгъване на всички",
  "collapseAll": "Сгъване на всички"
});