define({
  "queries": "Dopyty",
  "addNew": "Pridať novú",
  "newQuery": "Nový dopyt",
  "queryLayer": "Vrstva dopytu",
  "setSource": "Nastaviť",
  "setDataSource": "Nastaviť zdroj údajov",
  "name": "Meno",
  "querySource": "Zdroj údajov",
  "queryName": "Názov úlohy",
  "queryDefinition": "Definícia filtra",
  "resultsSetting": "Nastavenia výsledkov",
  "symbolSetting": "Nastavenia symbolu",
  "resultSettingTip": "Definovať, čo a ako zobraziť vo výstupných výsledkoch.",
  "resultItemTitle": "Názov každej výslednej položky",
  "resultItemContent": "Tieto atribúty stĺpca sa zobrazia",
  "fieldsSetTip": "Začiarknite políčka, ktoré chcete zobraziť. Vyberte stĺpec, ak chcete aktualizovať jeho alias, usporiadať ho a naformátovať.",
  "addField": "Pridať pole",
  "visibility": "Viditeľnosť",
  "alias": "Alias",
  "specialType": "Špeciálny typ",
  "actions": "Akcie",
  "none": "Žiadne",
  "link": "Prepojenie",
  "image": "Obrázok",
  "noField": "Žiadny stĺpec",
  "operationalLayerTip": "Pridať výsledok ako operačnú vrstvu",
  "setLayerSymbolTip": "Nastaviť symbol pre výsledky dopytu: ",
  "setSelectedSymbolTip": "Nastaviť symbol zvoleného prvku.",
  "notUseFilter": "Nepoužívať filter",
  "setSourceTip": "Prosím nastavte zdroj dopytu.",
  "setFilterTip": "Nastavte filter správne.",
  "ok": "OK",
  "cancel": "Zrušiť",
  "noFilterTip": "Bez definovaného výrazu filtra bude táto úloha dopytu obsahovať všetky prvky v zadanom zdroji dát.",
  "relationships": "Vzťahy",
  "addRelationshipLayer": "Pridať nový vzťah",
  "relatedTo": "Súvisiace s",
  "selectOption": "Prosím vyberte..",
  "resultItemSorting": "Výsledok triedenia položiek",
  "field": "Pole",
  "sortingOrder": "Poradie",
  "configureFieldsTip": "Prosím konfigurujte polia, podľa ktorých bude výsledok dopytu triedený.",
  "setSortingFields": "Nastaviť triediace stĺpce",
  "ascending": "Vzostupne",
  "descending": "Zostupne",
  "sortBy": "Zoradiť podľa",
  "thenBy": "Potom podľa",
  "addTask": "Pridať úlohu",
  "noTasksTip": "Žiadne konfigurované dopyty. Kliknite na \"${newQuery}\" pre pridanie nového filtra.",
  "infoText": "Informácie",
  "filters": "Filtre",
  "results": "Výsledky",
  "optionsText": "Možnosti",
  "summaryText": "Súhrn",
  "attributeFilter": "Filter atribútov",
  "attributeFilterTip": "Definovať výrazy atribútov na použitie vo widgete na filtrovanie vrstvy dopytu .",
  "defineWhereClause": "Definovať podmienku WHERE pre dopyt.",
  "noExpressionDefinedTip": "Žiaden definovaný výraz. Všetky záznamy budú vrátené.",
  "setExpressions": "Nastaviť výrazy",
  "spatialFilter": "Priestorové filtre",
  "spatialFilterTip": "Vybrať, ktoré prietorové filtre budú dostupné koncovým užívateľom.",
  "defaultOption": "Predvolené",
  "useCurrentExtentTip": "Vrátiť iba prvky v rámci súčasného rozsahu mapy",
  "useDrawGraphicTip": "Vrátiť iba prvky, ktoré sa pretínajú s tvarom nakresleným na mape",
  "useFeaturesTip": "Vrátiť iba prvky, ktoré majú priestorový vzťah s prvkami v inej vrstve",
  "noSpatialLimitTip": "Vrátiť prvky v rámci plného rozsahu mapy",
  "drawingTools": "Zvoliť nástroje na kreslenie",
  "bufferSettings": "Povoliť možnosť mapovej anotácie",
  "defaultDistance": "Predvolená vzdialenosť",
  "bufferDistance": "Vzdialenosť obalovej zóny",
  "defaultUnit": "Predvolená jednotka",
  "miles": "Míle",
  "kilometers": "Kilometre",
  "feet": "Stopy",
  "meters": "Metre",
  "yards": "Yardy",
  "nauticalMiles": "Námorné míle",
  "availableSpatialRelationships": "Vybrať pravidlá priestorového vzťahu",
  "setSpatialRelationships": "Nastaviť priestorové vzťahy",
  "availability": "Dostupnosť",
  "relationship": "Vzťah",
  "label": "Opis",
  "intersect": "pretínajú",
  "contain": "obsahujú",
  "areContainedIn": "sú obsiahnuté",
  "cross": "križujú",
  "envelopeIntersect": "pretínajú obálku",
  "overlap": "prekrývajú",
  "areOverlapped": "sú prekryté",
  "touch": "dotyk",
  "within": "v rámci",
  "areWithin": "sú v rámci",
  "indexIntersect": "pretínajú index",
  "itemTitle": "Názov položky",
  "displayFields": "Stĺpce na zobrazenie",
  "sortingFields": "Triediť výsledné položky",
  "setDisplayFields": "Nastaviť stĺpce zobrazenia",
  "symbol": "Symbol",
  "setSymbol": "Použiť vlastný symbol",
  "changeSymbolAtRuntime": "Povoliť zmenu symbolu počas užívania",
  "serviceSymbolTip": "Použiť symboly definované vrstvou",
  "exportTip": "Povoliť export výsledkov",
  "keepResultsTip": "Ponechať výsledky na mape po zatvorení widgetu",
  "queryRelatedRecords": "Dopytovať relačne súvisiace záznamy",
  "createLayerForTaskTip": "Špecifikovať ako úloha dopytu vytvára vrstvy",
  "oneLayerForTaskTip": "Prepísať vrstvu zakaždým, keď je dopyt vykonaný",
  "multipleLayerForTaskTip": "Vytvoriť novú vrstvu zakaždým, keď je dopyt vykonaný",
  "makeDefault": "Urobiť predvolené",
  "icon": "Ikona",
  "newTask": "Nová úloha",
  "addTaskTip": "Pridajte do widgetu jeden alebo viac dopytov a konfigurujte parametre pre každý z nich.",
  "webMapPopupTip": "Použiť konfiguráciu kontextového okna vrstvy vo webovej mape",
  "customPopupTip": "Konfigurovať vlastný obsah",
  "showResultsSetActions": "Zobraziť akcie pre výslednú sadu",
  "zoomTo": "Priblížiť na",
  "openAttributeTable": "Zobraziť v tabuľke atribútov",
  "content": "Obsah",
  "displaySQLTip": "Zobraziť SQL výrazy pre koncových užívateľov",
  "useLayerDefaultSymbol": "Použiť predvolený symbol vrstvy",
  "setCustomIcon": "Nastaviť vlastnú ikonu",
  "layerDefaultSymbolTip": "Použiť predvolený symbol vrstvy",
  "uploadImage": "Nahrať obrázok",
  "attributeCriteira": "Kritériá atribútov",
  "specifyFilterAtRuntimeTip": "Používatelia budú nútení špecifikovať parametre pre tento výraz",
  "value": "HODNOTA",
  "hideLayersTip": "Vypnite vrstvy výsledkov dopytu, keď je widget zatvorený.",
  "tabLabels": "Označenia záložky",
  "tasks": "Úlohy",
  "queryCriteira": "Kritériá dopytu",
  "allowCustomQuery": "Povoliť vytvorenie vlastného dopytu",
  "showFilterLabelTip": "Zobraziť oznčenia filtra",
  "querySettings": "Nastavenia dopytu",
  "expandTip": "Predvolene rozbaliť zoznam výsledkov",
  "customResultNameTip": "Zobraziť možnosti na konfigurovanie vlastného<strong> mena vrstvy výsledkov</strong>"
});