define({
  "serviceUrl": "Postavi URL adresu servisa:",
  "minIntSpacingLabel": "Minimalna veličina mreže",
  "lineOpacityLabel": "Neprozirnost linije",
  "labelOpacityLabel": "Neprozirnost oznake",
  "centerLabelOpacityLabel": "Neprozirnost centralne oznake",
  "gridZonePlacementLabel": "Raspored oznaka na mreži",
  "verticalLineLabels": "Oznake vertikalnih linija",
  "styleHeaderLabel": "Stil",
  "indexHeaderLabel": "Komponenta mreže",
  "colorHeaderLabel": "Boja",
  "fontSizeHeaderLabel": "Veličina fonta",
  "lineWidthHeaderLabel": "Širina linije",
  "horizontalLabel": "Horizontalno",
  "verticalLabel": "Vertikalno",
  "upperLeftLabel": "Gore levo",
  "upperRightLabel": "Gore desno",
  "lowerLeftLabel": "Dole levo",
  "lowerRightLabel": "Dole desno",
  "centerLabel": "Centar",
  "errorMessage": "Stranica za konfigurisanje ima greške. Popravite pre čuvanja.",
  "checkBoxLabel": "Prikaži mrežu kada je vidžet zatvoren",
  "checkBoxLabelDashboard": "Prikaži mrežu",
  "gzd": "Oznaka zone mreže (GZD)",
  "gsid": "${number}-mera; identifikacije kvadrata mreže (GSID)",
  "grid10k": "${number}-merač linije mreže",
  "grid1k": "${number}-merač linije mreže",
  "grid100m": "Linije mreže na 100 metara",
  "grid10m": "Linije mreže na 10 metara",
  "switchBasemap": "Promeni pozadinsku mapu"
});