define({
  "_widgetLabel": "Dataaggregering",
  "startPage": {
    "defaultStartPageInstructions": "Den här widgeten hjälper till med bearbetning och överföring av data från en fil till det valda lagret i kartan.<br/> <br/>Värden i filen måste avgränsas med komma, tabb, semikolon eller vertikalstreck.",
    "dragDrop": "Dra och släpp",
    "browse": "Bläddra till Arkiv",
    "or": "ELLER",
    "userPrivilege": "Ditt konto har inte behörighet att skapa eller ändra data.",
    "userCredits": "${widgetName} kräver krediter för att använda lokaliseringsfilen ${locator}.",
    "contactAdmin": "Kontakta organisationens administratör om du vill fråga efter ytterligare krediter.",
    "contactAdminEdit": "Kontakta organisationens administratör om du vill fråga efter redigeringsbehörighet.",
    "canUseLocator": "Lokaliseringsfilen ${locator} används för att hitta geoobjekt.",
    "notEnoughCredits": "Inte tillräckligt med krediter.",
    "locationAndField": "Plats- och fältinformation",
    "locationAndFieldHint": "Välj de värden från filen som ska användas för att uppdatera mållagret.",
    "cannotUseLocator": "Det gick inte att använda ${widgetName}",
    "noAnonymousEdit": "Lagret ${layerName} stöder inte anonym redigering.",
    "pleaseLogin": "Logga in på organisationen ${org} eller kontakta organisationens administratör för att be om att anonym redigering ska aktiveras.",
    "invalidEdit": "Ogiltiga behörigheter",
    "unableToAccess": "Det går inte att få åtkomst till ${layerName}",
    "appropriateCredentials": "Kontrollera att du har loggat in med rätt autentiseringsuppgifter.",
    "shared": "Kontakta organisationens administratör om du vill fråga efter åtkomst till lagret ${layerName}.",
    "targetLayerLabel": "Mållager",
    "homeButtonLabel": "Hem",
    "mappingErrorMsg": "Klicka på pilen bredvid definiera fälten"
  },
  "mapping": {
    "schemaMapping": "Fältinformation",
    "schemaMappingHint": "Välj fält från filen som motsvarar fälten i lagret.",
    "locationMapping": "Platsinformation",
    "locationMappingHint": "Välj den typ av adress- eller koordinatinformation som kan väntas från filen."
  },
  "locationMapping": {
    "locationMappingPageHint": "Välj platstyp",
    "useAddress": "Hitta med hjälp av en adress",
    "useAddressHint": "Data innehåller adressinformation",
    "useCoordinates": "Hitta med hjälp av koordinater",
    "useCoordinatesHint": "Data innehåller X/Y-koordinatvärden"
  },
  "address": {
    "addressPageHint": "Välj adresstyp",
    "singleField": "Enstaka fält",
    "singleFieldHint": "Välj det fält som innehåller adressinformationen",
    "multiField": "Flera fält",
    "multiFieldHint": "Välj de fält som innehåller adressinformationen"
  },
  "coordinates": {
    "coordinatesPageHint": "Välj de fält som innehåller koordinatdata"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Välj det källfält som mappar till målfältet",
    "sourceField": "Matchande källfält",
    "targetField": "Målfält"
  },
  "buttons": {
    "addToMap": "Lägg till på karta",
    "submit": "Utför",
    "download": "Hämta"
  },
  "review": {
    "matched": "Hittade",
    "reviewMatched": "Platser hittades",
    "reviewMatchedHint": "Granska platser som hittades.",
    "unMatched": "hittades inte",
    "reviewUnMatched": "Platser hittades inte",
    "reviewUnMatchedHint": "Granska platser som inte hittades. Objekt som inte korrigeras skickas inte.",
    "duplicate": "Duplicera",
    "reviewDuplicate": "Dubblettplatser",
    "reviewDuplicateHint": "Granska platser som redan fanns i lagret. Objekt som inte åtgärdas skickas inte.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Anv:",
    "fromLayer": "Målinformation",
    "target": "Mål",
    "source": "Källa",
    "fromFile": "Källinformation",
    "locationControlHint": "Granska adressuppgifter",
    "duplicateAction": "Välj en åtgärd",
    "item": "Post:",
    "locateFeature": "Hitta geoobjekt",
    "removeFeature": "Ta bort geoobjekt",
    "featureLocated": "Plats hittades",
    "valuesDoNotMatch": "Matchar inte befintligt värde",
    "sync": "Synkronisera adressuppgifter med fältinformation",
    "noFeaturesSaved": "Inga geoobjekt har sparats",
    "someFeaturesSaved": "${num} geoobjekt har sparats.",
    "someFeaturesNotSaved": "${num} geoobjekt har inte sparats.",
    "feature": "Granska geoobjektinformation",
    "locationInfo": "Granska platsinformation",
    "selectValue": "Välj ett värde",
    "reviewData": "Granska data",
    "reviewDataHint": "Granska dina data innan du skickar dem till lagret.",
    "reviewFeatureHint": "Granska eller redigera din geoobjekt- eller platsinformation.",
    "duplicateModify": "Dubblett, behöver ändras",
    "duplicateSave": "Spara som nytt geoobjekt"
  },
  "warningsAndErrors": {
    "invalidCSV": "Fel vid hämtning av objekt från CSV, kontrollera om en giltig CSV-fil har valts.",
    "noLayersWarning": "Inget giltigt mållager är konfigurerat, kontrollera konfigurationen.",
    "loadWarning": "Den här widgeten kräver en datakälla i form av en geoobjekttjänst. Definiera en datakälla genom att konfigurera widgeten.",
    "saveError": "Ett fel uppstod när geoobjekt sparades.",
    "consumesCredits": "Det här verktyget förbrukar krediter när det används med tjänsten för världsgeokodning i ArcGIS Online.",
    "noValue": "Välj ett fält",
    "mappingTitle": "",
    "locationMappingComplete": "Platsmatchning slutförd",
    "fieldMappingComplete": "Fältmatchning slutförd",
    "settingsCleared": "Inställningarna kommer att rensas.",
    "proceed": "Vill du fortsätta?",
    "itemMoveMatch": "Objektet hittades och flyttades till listan över hittade platser",
    "itemMoveUnMatched": "Det gick inte att hitta objektet. Det flyttades till listan över platser som inte hittades.",
    "itemWillBeLocated": "Objektet tas bort från listan över dubblettplatser.",
    "cannotLocate": "Det gick inte att hitta objektet. Bekräfta platsinformationen.",
    "invalidMessage": "Ogiltigt värde.",
    "rangeMessage": "Värdet måste vara mindre än ${num} tecken.",
    "locatorError": "Lokaliseringsfilen är ogiltig eller inte tillgänglig.",
    "notConfigured": "ingen lokaliseringsfil är konfigurerad för de aktuella lokaliseringsalternativen",
    "noMoreLocators": "inga ytterligare lokaliseringsfiler har konfigurerats"
  },
  "featureToolbar": {
    "locate": "Leta upp",
    "save": "Spara post",
    "cancel": "Avbryt redigeringar",
    "cancelTitle": "Avbryt redigeringar",
    "cancelMessage": "Avbryt redigeringar av den aktuella posten?"
  }
});