define({
  "transparencyLabel": "Transparencia",
  "outline": "Lista",
  "fill": "Relleno (el color solo se aplica si el estilo es sólido)",
  "style": "Estilo",
  "selectOpLayerLabel": "Seleccionar una capa operativa para los resultados",
  "selectDefaultMeasurementLabel": "Seleccionar una unidad de medida predeterminada",
  "helpIconTooltip": "La lista de capas operativas se rellena con las capas del mapa web actual que corresponden al tipo de geometría de polígono.",
  "lineStyles": {
    "esriSLSDash": "Guion",
    "esriSLSDashDot": "Guion Punto",
    "esriSLSDashDotDot": "Guion Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Guion largo",
    "esriSLSLongDashDot": "Guion largo, Punto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Guion corto",
    "esriSLSShortDashDot": "Guion corto Punto",
    "esriSLSShortDashDotDot": "Guion corto Punto Punto",
    "esriSLSShortDot": "Corto Punto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atrás",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Hacia delante",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "threatTypeLabel": "Tipo de amenaza",
  "generalLabel": "General",
  "addThreatTypesLabel": "Agregar tipo de amenaza",
  "actions": "Acciones",
  "newThreatTypePopupLabel": "Nuevo tipo de amenaza",
  "units": "Unidades",
  "chooseDefaultThreatLabel": "Seleccionar tipo de amenaza predeterminado",
  "defaultThreatTypePopUpLabel": "Tipos de amenaza predeterminados",
  "editThreatLabel": "Editar amenaza",
  "defaultThreatTypeIconTooltip": "Lista de tipos de amenaza predeterminados",
  "uniqueThreatTypeMsg": "Introduzca un tipo de amenaza único; ya existe un tipo de amenaza con este nombre.",
  "requiredMsg": "Este campo es obligatorio",
  "unitMeasureLabel": "Las distancias están en {0}",
  "chooseDefaultThreatTypeIconLabel": "Elegir de entre los valores predeterminados",
  "pipeBombLabel": "Bomba casera",
  "suicideBombLabel": "Bomba suicida",
  "briefcaseLabel": "Maletín",
  "carLabel": "Automóvil",
  "suvVanLabel": "Todoterreno/furgoneta",
  "smallDeliveryTruckLabel": "Camión de reparto pequeño",
  "containerWaterTruckLabel": "Contenedor/camión cisterna",
  "semiTrailerLabel": "Semirremolque",
  "chemicalThreatLegendLabel": "Amenaza química",
  "lpgThreatLegendLabel": "Amenaza de GLP",
  "smallLPGTank": "Depósito de GLP pequeño",
  "largeLPGTank": "Depósito de GLP grande",
  "commercialResidentialLPGTank": "Depósito de GLP comercial/residencial",
  "smallLPGTruck": "Camión cisterna de GLP pequeño",
  "semiTankerLPG": "Semirremolque cisterna de GLP",
  "threatDescriptionColLabel": "Descripción de la amenaza",
  "addThreatZoneButtonLabel": "Agregar zona de amenaza",
  "zoneDescColLabel": "Descripción de la zona",
  "distanceLabel": "Distancia (${unitAbbr})",
  "threatTypeHelp": "<p>Asegúrese de que se cumplan las siguientes condiciones para un tipo de amenaza:<br/><ul><li>El tipo de amenaza no puede estar en blanco y debe ser único</li><li>La amenaza debe tener al menos una zona válida</li><li>La descripción de la zona debe ser única para una amenaza</li></ul><p/>",
  "descriptionLabel": "Descripción",
  "newThreatZonePopupLabel": "Nueva zona de amenaza",
  "editThreatZonePopupLabel": "Editar zona de amenaza",
  "uniqueZoneDescriptionMsg": "Introduzca una descripción de zona única; ya existe una descripción de zona con este nombre.",
  "symbologyColLabel": "Simbología",
  "zoneDescriptionColLabel": "Descripción de la zona",
  "uniqueZoneRequiredMsg": "El nombre de zona debe ser único para",
  "interactive": "Interactiva",
  "fromCoord": "Coordenada fija",
  "existingFeature": "De entidades existentes",
  "defaultInputLocationLabel": "Ubicación de entrada predeterminada",
  "defaultInputLayer": "Capa de entrada predeterminada",
  "defaultThreatType": "Lista de amenazas predeterminadas",
  "selectLabel": "Seleccionar",
  "mandatoryLabel": "Distancia de evacuación obligatoria",
  "safeLabel": "Distancia de evacuación segura",
  "lpgSafeDistanceLable": "Distancia segura",
  "fireBallDiameterLable": "Diámetro de bola de fuego"
});