define({
  "transparencyLabel": "Transparansi",
  "outline": "Kerangka",
  "fill": "Isi (Warna hanya berlaku jika gaya diatur ke padat)",
  "style": "Gaya",
  "selectOpLayerLabel": "Pilih layer operasional untuk hasil",
  "selectDefaultMeasurementLabel": "Pilih satuan ukuran default",
  "helpIconTooltip": "Daftar layer operasional dikumpulkan dengan layer dari peta web saat ini yang berjenis geometri poligon.",
  "lineStyles": {
    "esriSLSDash": "Garis Datar",
    "esriSLSDashDot": "Garis Datar Titik",
    "esriSLSDashDotDot": "Garis Datar Titik Titik",
    "esriSLSDot": "Titik",
    "esriSLSLongDash": "Garis Datar Panjang",
    "esriSLSLongDashDot": "Garis Datar Panjang Titik",
    "esriSLSNull": "Nol",
    "esriSLSShortDash": "Garis Datar Pendek",
    "esriSLSShortDashDot": "Garis Datar Pendek Titik",
    "esriSLSShortDashDotDot": "Garis Datar Pendek Titik Titik",
    "esriSLSShortDot": "Titik Pendek",
    "esriSLSSolid": "Padat"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Belakang",
    "esriSFSCross": "Silang",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Depan",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nol",
    "esriSFSSolid": "Padat",
    "esriSFSVertical": "Vertikal"
  },
  "threatTypeLabel": "Jenis Ancaman",
  "generalLabel": "Umum",
  "addThreatTypesLabel": "Tambahkan jenis ancaman",
  "actions": "Tindakan",
  "newThreatTypePopupLabel": "Jenis ancaman baru",
  "units": "Unit",
  "chooseDefaultThreatLabel": "Pilih jenis ancaman default",
  "defaultThreatTypePopUpLabel": "Jenis Ancaman Default",
  "editThreatLabel": "Edit Ancaman",
  "defaultThreatTypeIconTooltip": "Daftar Jenis Ancaman Default",
  "uniqueThreatTypeMsg": "Masukkan jenis ancaman unik, jenis ancaman dengan nama ini sudah ada.",
  "requiredMsg": "Kolom ini wajib diisi",
  "unitMeasureLabel": "Jarak dalam {0}",
  "chooseDefaultThreatTypeIconLabel": "Pilih dari default",
  "pipeBombLabel": "Bom Pipa",
  "suicideBombLabel": "Bom Bunuh Diri",
  "briefcaseLabel": "Tas kerja",
  "carLabel": "Mobil",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Truk Pengiriman Kecil",
  "containerWaterTruckLabel": "Truk Kontainer/Truk Air",
  "semiTrailerLabel": "Truk Semi-Trailer",
  "chemicalThreatLegendLabel": "Perlakuan Kimiawi",
  "lpgThreatLegendLabel": "Perlakuan LPG",
  "smallLPGTank": "Tangki LPG Kecil",
  "largeLPGTank": "Tangki LPG Besar",
  "commercialResidentialLPGTank": "Tangko LPG Komersial/Residensial",
  "smallLPGTruck": "Truk LPG Kecil",
  "semiTankerLPG": "LPG Semi-Tanker",
  "threatDescriptionColLabel": "Deskripsi Ancaman",
  "addThreatZoneButtonLabel": "Tambahkan zona ancaman",
  "zoneDescColLabel": "Deskripsi zona",
  "distanceLabel": "Jarak (${unitAbbr})",
  "threatTypeHelp": "<p>Pastikan kondisi berikut terpenuhi untuk jenis ancaman:<br/><ul><li>Jenis ancaman tidak boleh kosong dan harus bersifat unik</li><li>Ancaman harus memiliki setidaknya satu zona yang valid</li><li>Deskripsi zona harus unik untuk ancaman</li></ul><p/>",
  "descriptionLabel": "Keterangan",
  "newThreatZonePopupLabel": "Zona ancaman baru",
  "editThreatZonePopupLabel": "Edit zona ancaman",
  "uniqueZoneDescriptionMsg": "Masukkan deskripsi zona unik, deskripsi zona dengan nama ini sudah ada.",
  "symbologyColLabel": "Simbologi",
  "zoneDescriptionColLabel": "Deskripsi zona",
  "uniqueZoneRequiredMsg": "Nama zona harus unik untuk",
  "interactive": "Interaktif",
  "fromCoord": "Koordinat Tetap",
  "existingFeature": "Dari Fitur yang Ada",
  "defaultInputLocationLabel": "Lokasi input default",
  "defaultInputLayer": "Layer input default",
  "defaultThreatType": "Jenis ancaman default",
  "selectLabel": "Pilih",
  "mandatoryLabel": "Jarak Evakuasi Wajib",
  "safeLabel": "Jarak Evakuasi Aman",
  "lpgSafeDistanceLable": "Jarak Aman",
  "fireBallDiameterLable": "Diameter Bola Api"
});