///////////////////////////////////////////////////////////////////////////
// Copyright © Esri. All Rights Reserved.
//
// Licensed under the Apache License Version 2.0 (the 'License');
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
///////////////////////////////////////////////////////////////////////////
define({
  "units": {
    "areaSquareFeetUnit": "Štvorcové stopy",
    "areaAcresUnit": "Akre",
    "areaSquareMetersUnit": "Štvorcové metre",
    "areaSquareKilometersUnit": "Štvorcové kilometre",
    "areaHectaresUnit": "Hektáre",
    "areaSquareMilesUnit": "Štvorcové míle",
    "lengthFeetUnit": "Stopy",
    "lengthMilesUnit": "Míle",
    "lengthMetersUnit": "Metre",
    "lengthKilometersUnit": "Kilometre"
  },
  "analysisTab": {
    "analysisTabLabel": "Analýza",
    "selectAnalysisLayerLabel": "Analytické vrstvy",
    "addLayerLabel": "Pridať vrstvy",
    "noValidLayersForAnalysis": "Vo zvolenej webovej mape neboli nájdené žiadne platné vrstvy",
    "noValidFieldsForAnalysis": "Vo zvolenej webovej mape neboli nájdené žiadne polia Prosím odstránte zvolenú vrstvu.",
    "allowGroupingLabel": "Zoskupiť prvky podľa stĺpca s rovnakou hodnotou",
    "groupingHintDescription": "Tip: Predvolene sú všetky prvky s rovnakou hodnotou pre zvolené stĺpce zoskupené, aby vyzerali ako jediný vstup v správe. Deaktivovať zoskupenie podľa podobných atribútov na zobrazenie vstupu pre každý prvok.",
    "addLayersHintText": "Tip: Vybrať vrstvy a stĺpce na zahrnutie v analýze a správe",
    "addLayerNameTitle": "Názov vrstvy",
    "addFieldsLabel": "Pridať stĺpec",
    "addFieldsPopupTitle": "Zvoliť stĺpce",
    "addFieldsNameTitle": "Mená stĺpcov",
    "aoiToolsLegendLabel": "Nástroje oblasti záujmu",
    "aoiToolsDescriptionLabel": "Zvoliť a popísať nástroje dostupné pre vytvorenie oblasti záujmu.",
    "placenameLabel": "Názov miesta",
    "drawToolsLabel": "Zvoliť nástroje na kreslenie",
    "uploadShapeFileLabel": "Nahrať shapefile",
    "coordinatesLabel": "súradnice",
    "coordinatesDrpDwnHintText": "Tip: Vybrať jednotku na zobrazenie zadaných traverzov",
    "coordinatesBearingDrpDwnHintText": "Tip: Vybrať pretínanie na zobrazenie zadaných traverzov",
    "allowShapefilesUploadLabel": "Povoliť užívateľom nahrať shapefile-y na zahrnutie do analýzy",
    "allowShapefilesUploadLabelHintText": "Tip: Pridať možnosť do karty správ, kde užívatelia môžu nahrať ich vlastné údaje ako shapefile na zahrnutie do správy analýzy",
    "allowVisibleLayerAnalysisLabel": "Neanalyzovať alebo hlásiť výsledky pre vrstvy, ktoré nie sú viditeľné",
    "allowVisibleLayerAnalysisHintText": "Tip: Vrstvy, ktoré boli vypnuté alebo nie sú viditeľné kvôli nastaveniam viditeľnosti mierky nebudú analyzované alebo zahrnuté v tlačených alebo stiahnutých výsledkoch.",
    "areaUnitsLabel": "Jednotky pre výsledky analýzy (plocha)",
    "lengthUnitsLabel": "Jednotky pre výsledky analýzy (dĺžka)",
    "maxFeatureForAnalysisLabel": "Maximálny počet prvkov na analýzu",
    "maxFeatureForAnalysisHintText": "Tip: Nastavte maximálny počet prvkov, ktoré budú zahrnuté v analýze",
    "searchToleranceLabelText": "Tolerancia vyhľadávania",
    "searchToleranceHint": "Tip: Tolerancia vyhľadávania je použitá, keď analyzuje bod a líniu vstupov",
    "placenameButtonText": "Názov miesta",
    "drawToolsButtonText": "Nakresliť",
    "shapefileButtonText": "Shapefile",
    "coordinatesButtonText": "súradnice",
    "invalidLayerErrorMsg": "Prosím konfigurujte stĺpce pre",
    "drawToolSelectableLayersLabel": "Vyberte selektovateľné vrstvy",
    "drawToolSelectableLayersHint": "Tip: Vybrať vrstvy, ktoré obsahujú prvky, ktoré môžu byť zvolené používajúc kresliaci nástroj voľby",
    "drawToolsSettingsFieldsetLabel": "Nástroje kreslenia",
    "drawToolPointLabel": "Bod",
    "drawToolPolylineLabel": "Lomená čiara",
    "drawToolExtentLabel": "Rozsah",
    "drawToolPolygonLabel": "Polygón",
    "drawToolCircleLabel": "Kruh",
    "selectDrawToolsText": "Vyberte nástroje kreslenia dostupné pre vytvorenie oblasti záujmu",
    "selectingDrawToolErrorMessage": "Vyberte aspoň jeden nástroj kreslenia alebo vrstvu výberu na použitie možnosti nástrojov kreslenia pre AOI nástroje."
  },
  "downloadTab": {
    "downloadLegend": "Stiahnuť nastavenia",
    "reportLegend": "Nastavenia prehľadu",
    "downloadTabLabel": "Stiahnuť",
    "syncEnableOptionLabel": "Vrstvy prvkov",
    "syncEnableOptionHint": "Tip: Vybrať vrstvy, ktoré môžu byť stiahnuté a špecifikovať formáty, v ktorých bude každá vrstva dostupná. Stiahnuté datasety budú zahŕňať tie prvky, ktoré sa pretínajú s oblasťou záujmu.",
    "syncEnableOptionNote": "Poznámka: Stiahnutia súboru geodatabázy a shapefile vyžadujú vrstvy prvkov s povolenou synchronizáciou. Formátu shapefile je podporovaný len s ArcGIS Online hostovanými vrstvami prvkov.",
    "extractDataTaskOptionLabel": "Extrahovať údajovú úlohu geoprocesnej služby",
    "extractDataTaskOptionHint": "Tip: Použite zverejnenú extract data task geoprocesigú službu na stiahnutie prvkov, ktoré sa pretínajú s oblasťou záujmu v súbore formátov geodatabáze alebo shapefile.",
    "cannotDownloadOptionLabel": "Vypnúť sťahovanie",
    "syncEnableTableHeaderTitle": {
      "layerNameLabel": "Názov vrstvy",
      "csvFileFormatLabel": "CSV",
      "fileGDBFormatLabel": "Súborová geodatabáza",
      "ShapefileFormatLabel": "Shapefile",
      "allowDownloadLabel": "Zapnúť sťahovanie"
    },
    "setButtonLabel": "Nastaviť",
    "GPTaskLabel": "Špecifikovať URL geoprocesnej služby",
    "printGPServiceLabel": "Vypísať URL služby",
    "setGPTaskTitle": "Špecifikovať požadovanú URL geoprocesnej služby",
    "logoLabel": "Logo",
    "logoChooserHint": "Tip: Kliknite na ikonu snímku pre zmenu loga zobrazeného v ľavom hornom rohu hlásenia",
    "footnoteLabel": "Poznámka dolu",
    "columnTitleColorPickerLabel": "Farbu názvu stĺpca s hlásením",
    "reportTitleLabel": "Názov hlásenia",
    "displaySummaryLabel": "Zobraziť zhrnutie",
    "hideZeroValueRowLabel": "Skryť riadky s hodnotou 0 pre všetky stĺpce analýzy",
    "hideNullValueRowLabel": "Skryť riadky bez žiadnej údajovej hodnoty (null alebo prázdne) pre všetky stĺpce analýzy",
    "errorMessages": {
      "invalidGPTaskURL": "Neplatná geoprocesná služba. Prosím zvoľte geoprocesnú službu obsahujúcu úlohu extrahovania údajov",
      "noExtractDataTaskURL": "Prosím zvoľte geoprocesnú službu obsahujúcu úlohu extrahovania údajov",
      "duplicateCustomOption": "Existuje duplicitný vstup pre ${duplicateValueSizeName} .",
      "invalidLayoutWidth": "Pre ${customLayoutOptionValue} bola zadaná neplatná dĺžka.",
      "invalidLayoutHeight": "Pre ${customLayoutOptionValue} bola zadaná neplatná výška.",
      "invalidLayoutPageUnits": "Pre ${customLayoutOptionValue} bola zadaná neplatná jednotka stránky.",
      "failtofetchbuddyTaskDimension": "Chyba pri získavaní rozmerov spriatelenej úlohy. Skúste prosím znova.",
      "failtofetchbuddyTaskName": "Chyba pri získavaní mena spriatelenej úlohy. Skúste prosím znova.",
      "failtofetchChoiceList": "Chyba pri získavaní zoznamu výberov z tlačovej služby. Skúste prosím znova.",
      "invalidWidth": "Neplatná šírka.",
      "invalidHeight": "Neplatná výška."
    },
    "addCustomLayoutTitle": "Pridať vlastné rozloženie",
    "customLayoutOptionHint": "Nápoveda: Pridať rozloženie z vašej tlačovej služby do zoznamu tlačových možností.",
    "reportDefaultOptionLabel": "Predvolené rozloženie",
    "pageSizeUnits": {
      "millimeters": "Milimetre",
      "points": "Body"
    },
    "noDataTextRepresentation": "Žiadna údajová hodnota",
    "naTextRepresentation": "Žiadna použiteľná hodnota",
    "noDataDefaultText": "Bez údajov",
    "notApplicableDefaultText": "Nedostupná"
  },
  "generalTab": {
    "generalTabLabel": "Všeobecné",
    "tabLabelsLegend": "Označenia panela",
    "tabLabelsHint": "Nápoveda: Špecifikovať označenia",
    "AOITabLabel": "Panel oblasti záujmu",
    "ReportTabLabel": "Panel hlásenia",
    "bufferSettingsLegend": "Nastavenia vyrovnávacej pamäte",
    "defaultBufferDistanceLabel": "Predvolená šírka obalovej zóny (buffer)",
    "defaultBufferUnitsLabel": "Jednotky obalovej zóny (buffer)",
    "generalBufferSymbologyHint": "Tip: Symbolika použitá na indikáciu plochy obalovej zóny okolo definovanej oblasti záujmu",
    "aoiGraphicsSymbologyLegend": "Symbolika oblasti záujmu",
    "aoiGraphicsSymbologyHint": "Tip: Symbolika použitá na indikáciu bodu, línie a polygónu oblasti záujmu",
    "pointSymbologyLabel": "Bod",
    "previewLabel": "Náhľad",
    "lineSymbologyLabel": "Línia",
    "polygonSymbologyLabel": "Polygón",
    "aoiBufferSymbologyLabel": "Symbolika mapovej anotácie",
    "pointSymbolChooserPopupTitle": "Symbol adresy alebo bodu umiestnenia",
    "polygonSymbolChooserPopupTitle": "Symbol polygónu",
    "lineSymbolChooserPopupTitle": "Symbol línie",
    "aoiSymbolChooserPopupTitle": "Symbol mapovej anotácie",
    "aoiTabText": "Oblasť záujmu (AOI)",
    "reportTabText": "Prehľad",
    "invalidSymbolValue": "Neplatná hodnota symbolu."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Nastavenia zdroja vyhľadávania",
    "searchSourceSettingTitle": "Nastavenia zdroja vyhľadávania",
    "searchSourceSettingTitleHintText": "Pridať a konfigurovať geokódovaciu službu alebo vrstvy prvkov ako zdroje vyhľadávania. Tieto špecifikované zdroje určujú, čo sa dá vyhľadávať v rámci vyhľadávacieho poľa",
    "addSearchSourceLabel": "Pridať zdroj vyhľadávania",
    "featureLayerLabel": "Vektorová vrstva",
    "geocoderLabel": "Geokodér",
    "generalSettingLabel": "Všeobecné nastavenie",
    "allPlaceholderLabel": "Zástupný text pre vyhľadávanie vo všetkých zdrojoch:",
    "allPlaceholderHintText": "Pomôcka: Pri vyhľadávaní vo všetkých vrstvách a geokodéroch zadajte text, ktorý sa má zobraziť ako zástupný text",
    "generalSettingCheckboxLabel": "Zobraziť kontextové okno pre nájdený prvok alebo umiestnenie",
    "countryCode": "Kód(y) krajiny alebo regiónu",
    "countryCodeEg": "napr. ",
    "countryCodeHint": "Ak ponecháte túto hodnotu prázdnu, budesa vyhľadávať vo všetkých krajinách a regiónoch",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Vyhľadávať iba v aktuálnom rozsahu mapy",
    "locatorUrl": "URL geokodéra",
    "locatorName": "Názov geokodéra",
    "locatorExample": "Príklad",
    "locatorWarning": "Táto verzia geokódovacej služby nie je podporovaná. Widget podporuje geokódovaciu službu 10.0 a vyššiu.",
    "locatorTips": "Návrhy nie sú k dipozícii, pretože geokódovacia služba nepodporuje možnosť návrhov.",
    "layerSource": "Zdroj vrstvy",
    "setLayerSource": "Nastaviť zdroj vrstvy",
    "setGeocoderURL": "Nastaviť URL geokodéru",
    "searchLayerTips": "Návrhy nie sú k dispozícii, pretože služba pre prvky nepodporuje stránkovanie.",
    "placeholder": "Zástupný text",
    "searchFields": "Vyhľadávacie polia",
    "displayField": "Zobraziť polia",
    "exactMatch": "Presná zhoda",
    "maxSuggestions": "Maximum návrhov",
    "maxResults": "Maximum výsledkov",
    "enableLocalSearch": "Aktivovať lokálne vyhľadávanie",
    "minScale": "Minimálna mierka",
    "minScaleHint": "Keď je mierka mapy väčšia, než táto mierka, použije sa lokálne vyhľadávanie",
    "radius": "Polomer",
    "radiusHint": "Určuje polomer oblasti okolo aktuálneho stredu mapy, ktorý sa používa na zvýšenie poradia kandidátov na geokódovanie, aby sa kandidátske záznamy najbližšie k umiestneniu vrátili ako prvé.",
    "setSearchFields": "Nastaviť polia vyhľadávania",
    "set": "Nastaviť",
    "invalidUrlTip": "URL ${URL} je neplatná alebo nedostupná.",
    "invalidSearchSources": "Neplatné nastavenia zdroja vyhľadávania"
  },
  "errorMsg": {
    "textboxFieldsEmptyErrorMsg": "Prosím dokončite požadované stĺpce",
    "bufferDistanceFieldsErrorMsg": "Prosím zadajte platné hodnoty",
    "invalidSearchToleranceErrorMsg": "Prosím zadajte platnú hodnotu pre toleranciu vyhľadávania",
    "atLeastOneCheckboxCheckedErrorMsg": "Neplatná konfigurácia: Aspoň jeden nástroj oblasti záujmu je požadovaný.",
    "noLayerAvailableErrorMsg": "Žiadne dostupné vrstvy",
    "layerNotSupportedErrorMsg": "Nie je podporované ",
    "noFieldSelected": "Prosím použite akciu úpravy na zvolenie stĺpcov pre analýzu",
    "duplicateFieldsLabels": "Duplicitné označenie \"${labelText}\" pridaná pre : \"${itemNames}\"",
    "noLayerSelected": "Prosím zvoľte aspoň jednu vrstvu pre analýzu.",
    "errorInSelectingLayer": "Nie je možné zvoliť vrstvu. Skúste prosím znova.",
    "errorInMaxFeatureCount": "Prosím zadajte platný maximálny počet prvkov pre analýzu."
  }
});