define({
  "_widgetLabel": "Ситуационна осведоменост",
  "locate_incident": "Локализиране на инцидент",
  "reverse_geocoded_address": "Най-близък адрес",
  "reverse_geocoded_error": "Няма налични",
  "actionLabel": "Задаване на местоположение",
  "drawPoint": "Начертаване на точка",
  "drawLine": "Начертаване на линия",
  "drawPolygon": "Начертаване на полигон",
  "saveIncident": "Запазване",
  "clearIncident": "Стартирането приключи",
  "noFeaturesFound": "Не са намерени обекти.",
  "downloadCSV": "Изтегляне",
  "sum": "Сума",
  "min": "Минимални",
  "max": "Максимални",
  "avg": "Средни",
  "count": "БРОЙ",
  "area": "ОБЛАСТ",
  "length": "ДЪЛЖИНА",
  "update_btn": "Готово",
  "delete_btn": "Изтриване",
  "get_directions": "Получаване на упътвания",
  "incident": "Инцидент",
  "incidents": "Инциденти",
  "buffer": "Буфер",
  "buffers": "Буфери",
  "_featureAction_ActionLabel": "Задаване на местоположение",
  "_featureAction_AddRemoveActionLabel": "Добавяне/Премахване на местоположение",
  "snapshot": "Папка SnapShot, създадена от идентификатора на приложението:",
  "user_credentials": "Потребителят няма валидни привилегии.",
  "notPolySnapShot": "Моля, посочете разстояние на буфер, преди да създадете моментна снимка.",
  "notPolyReport": "Няма валидни резултати за добавяне към отчета.",
  "notValidDownload": "Няма валидни резултати за изтегляне.",
  "of_append": "на",
  "layer_append": "слой",
  "downloadAll": "Изтегляне на всички",
  "createSnapshot": "Създаване на моментна снимка",
  "createReport": "Създаване на отчет",
  "calculated_results": "Обобщена информация",
  "closest": "Най-близкия обект",
  "proximity": "Приблизително",
  "summary": "Обобщение",
  "groupedSummary": "Групирани броеве",
  "_count": "Брой",
  "approximate": "приблизително",
  "snapshot_name": "Задаване на свойства на моментната снимка",
  "report_name": "Задаване на свойства на отчет",
  "invalid_snapshot_name": "Невалидно име на моментна снимка.",
  "invalid_report_name": "Невалидно заглавие на отчет.",
  "orientation": "Ориентация",
  "pageSize": "Размер на страница",
  "comments": "Коментари",
  "choose_group": "Групи",
  "forecast": "Прогноза",
  "select_group": "Избор на група",
  "select_group_instruction": "Моментната снимка ще бъде създадена и споделена с избраната група",
  "information_append": " Информация",
  "distance": "РАЗСТОЯНИЕ",
  "buffer_invalid": "Въведете валидна цифра между ${min} и ${max}",
  "layerNotAvalible": "Не е открит слой",
  "missingLayer": "Име: ${name}",
  "missingLayerHint": "Понастоящем не са налични един или повече слоеве, посочени в тази конфигурация.",
  "zoomToFeature": "Мащабиране към обекта",
  "saveIncidentErrorMessage": "Обектът (ите) не може да бъде запазен. <br> <br> <b> Описание: </b> <br>"
});