define({
  "_widgetLabel": "Agregacja danych",
  "startPage": {
    "defaultStartPageInstructions": "Ten widżet ułatwia przetwarzanie i wysłanie danych z pliku do wybranej warstwy na mapie.<br/> <br/> Wartości w pliku muszą być rozdzielane przecinkami, tabulatorami, średnikami lub kreskami pionowym.",
    "dragDrop": "Przeciąganie i upuszczanie",
    "browse": "Znajdź plik",
    "or": "LUB",
    "userPrivilege": "Twoje konto nie ma uprawnień do tworzenia ani modyfikowania danych.",
    "userCredits": "Widżet ${widgetName} wymaga kredytów, aby można było używać lokalizatora ${locator}.",
    "contactAdmin": "Skontaktuj się z administratorem instytucji i poproś o dodatkowe kredyty.",
    "contactAdminEdit": "Skontaktuj się z administratorem instytucji i poproś o uprawnienia do edycji.",
    "canUseLocator": "Do lokalizowania obiektów będzie używany lokalizator ${locator}.",
    "notEnoughCredits": "Za mało kredytów.",
    "locationAndField": "Informacje o lokalizacji i polach",
    "locationAndFieldHint": "Wybierz z pliku wartości, które będą używane do aktualizowania warstwy docelowej.",
    "cannotUseLocator": "Nie można użyć widżetu ${widgetName}",
    "noAnonymousEdit": "Warstwa ${layerName} nie obsługuje edycji anonimowej.",
    "pleaseLogin": "Zaloguj się w instytucji ${org} lub skontaktuj się z administratorem instytucji i poproś o włączenie edycji anonimowej.",
    "invalidEdit": "Nieprawidłowe uprawnienia",
    "unableToAccess": "Nie można uzyskać dostępu do warstwy ${layerName}",
    "appropriateCredentials": "Sprawdź, czy jesteś użytkownikiem zalogowanym i masz odpowiednie uprawnienia.",
    "shared": "Skontaktuj się z administratorem instytucji i poproś o dostęp do warstwy ${layerName}.",
    "targetLayerLabel": "Warstwa docelowa",
    "homeButtonLabel": "Strona główna",
    "mappingErrorMsg": "Kliknij strzałkę znajdującą się obok, aby zdefiniować pola"
  },
  "mapping": {
    "schemaMapping": "Informacje o polu",
    "schemaMappingHint": "Wybierz z pliku pola odpowiadające polom w warstwie.",
    "locationMapping": "Informacje dotyczące lokalizacji",
    "locationMappingHint": "Wybierz typ adresu lub informacje o współrzędnych, które mają pochodzić z pliku."
  },
  "locationMapping": {
    "locationMappingPageHint": "Wybierz typ lokalizacji",
    "useAddress": "Zlokalizuj z użyciem adresu",
    "useAddressHint": "Dane zawierają informacje o adresie",
    "useCoordinates": "Zlokalizuj z użyciem współrzędnych",
    "useCoordinatesHint": "Dane zawierają wartości współrzędnych X/Y"
  },
  "address": {
    "addressPageHint": "Wybierz typ adresu",
    "singleField": "Jedno pole",
    "singleFieldHint": "Wybierz pole zawierające informacje adresowe",
    "multiField": "Wiele pól",
    "multiFieldHint": "Wybierz pola zawierające informacje adresowe"
  },
  "coordinates": {
    "coordinatesPageHint": "Wybierz pola zawierające współrzędne"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Wybierz pole źródłowe, które jest przyporządkowane polu docelowemu",
    "sourceField": "Pasujące pole źródłowe",
    "targetField": "Pole docelowe"
  },
  "buttons": {
    "addToMap": "Dodaj do mapy",
    "submit": "Prześlij",
    "download": "Pobierz"
  },
  "review": {
    "matched": "Znaleziono",
    "reviewMatched": "Znaleziono lokalizacje",
    "reviewMatchedHint": "Przejrzyj znalezione lokalizacje.",
    "unMatched": "Nie znaleziono",
    "reviewUnMatched": "Nie znaleziono lokalizacji",
    "reviewUnMatchedHint": "Przejrzyj lokalizacje, których nie znaleziono. Elementy, które nie zostaną poprawione, nie będą przesyłane.",
    "duplicate": "Duplikuj",
    "reviewDuplicate": "Zduplikowane lokalizacje",
    "reviewDuplicateHint": "Przejrzyj lokalizacje, które znaleziono już w warstwie. Elementy, które nie zostaną zaadresowane, nie będą przesyłane.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Użyj:",
    "fromLayer": "Informacje o celu",
    "target": "Cel",
    "source": "Źródło",
    "fromFile": "Informacja źródłowa",
    "locationControlHint": "Przejrzyj informacje adresowe",
    "duplicateAction": "Wybierz działanie",
    "item": "Rekord:",
    "locateFeature": "Zlokalizuj obiekt",
    "removeFeature": "Usuń obiekt",
    "featureLocated": "Znaleziono lokalizację",
    "valuesDoNotMatch": "Nie jest zgodna z istniejącą wartością",
    "sync": "Zsynchronizuj informacje adresowe z informacjami w polu",
    "noFeaturesSaved": "Żadne obiekty nie zostały prawidłowo zapisane",
    "someFeaturesSaved": "Pomyślnie zapisano następującą liczbę obiektów: ${num}",
    "someFeaturesNotSaved": "Następująca liczba obiektów: ${num} nie została prawidłowo zapisana.",
    "feature": "Przejrzyj informacje o obiekcie",
    "locationInfo": "Przejrzyj informacje o lokalizacji",
    "selectValue": "Wybierz wartość",
    "reviewData": "Przejrzyj dane",
    "reviewDataHint": "Przejrzyj dane przed przesłaniem ich do warstwy.",
    "reviewFeatureHint": "Przejrzyj lub edytuj informacje o obiektach albo lokalizacjach.",
    "duplicateModify": "Duplikat, wymaga zmiany",
    "duplicateSave": "Zapisz jako nowy obiekt"
  },
  "warningsAndErrors": {
    "invalidCSV": "Błąd podczas pobierania elementów z pliku CSV. Sprawdź, czy wybrano prawidłowy plik CSV.",
    "noLayersWarning": "Nie skonfigurowano prawidłowej warstwy docelowej. Sprawdź konfigurację.",
    "loadWarning": "Ten widżet wymaga źródła danych Usługa obiektowa Skonfiguruj ten widżet, aby zdefiniować źródło danych.",
    "saveError": "Błąd podczas zapisywania obiektów.",
    "consumesCredits": "To narzędzie zużywa kredyty, jeśli jest używane z usługą ArcGIS Online World Geocoding Service",
    "noValue": "Wybierz pole",
    "mappingTitle": "",
    "locationMappingComplete": "Zakończono przyporządkowywanie lokalizacji",
    "fieldMappingComplete": "Zakończono przyporządkowywanie pól",
    "settingsCleared": "Ustawienia zostaną wyczyszczone",
    "proceed": "Czy chcesz kontynuować?",
    "itemMoveMatch": "Element został zlokalizowany i przeniesiony na listę znalezionych lokalizacji",
    "itemMoveUnMatched": "Nie można zlokalizować elementu. Przeniesiono go na listę nieznalezionych lokalizacji.",
    "itemWillBeLocated": "Element zostanie usunięty z listy zduplikowanych lokalizacji.",
    "cannotLocate": "Nie można zlokalizować elementu. Sprawdź informacje o lokalizacji.",
    "invalidMessage": "Nieprawidłowa wartość.",
    "rangeMessage": "Wartość musi zawierać mniej niż ${num} znaków.",
    "locatorError": "Lokalizator jest nieprawidłowy lub niedostępny.",
    "notConfigured": "lokalizator nie został skonfigurowany pod kątem aktualnych opcji lokalizowania",
    "noMoreLocators": "nie skonfigurowano dodatkowych lokalizatorów"
  },
  "featureToolbar": {
    "locate": "Lokalizuj",
    "save": "Zapisz rekord",
    "cancel": "Anuluj zmiany",
    "cancelTitle": "Anulowanie zmian",
    "cancelMessage": "Czy anulować zmiany aktualnego rekordu?"
  }
});