define({
  "transparencyLabel": "Прозрачност",
  "outline": "Контур",
  "fill": "Попълване (Цветът се прилага само когато стилът е зададен като плътен)",
  "style": "Стил",
  "selectOpLayerLabel": "Избиране на оперативен слой за резултати",
  "selectDefaultMeasurementLabel": "Избиране на мерна единица по подразбиране",
  "helpIconTooltip": "Списъкът на оперативния слой е попълнен със слоеве от текущата уеб карта, които са тип полигонна геометрия.",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире Точка",
    "esriSLSDashDotDot": "Тире Точка Точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Дълго тире",
    "esriSLSLongDashDot": "Дълго тире Точка",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Малко тире",
    "esriSLSShortDashDot": "Малко тире Точка",
    "esriSLSShortDashDotDot": "Малко тире Точка Точка",
    "esriSLSShortDot": "Малка точка",
    "esriSLSSolid": "Плътно"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Пресичане",
    "esriSFSDiagonalCross": "Диагонал",
    "esriSFSForwardDiagonal": "Напред",
    "esriSFSHorizontal": "Хоризонтално",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Плътно",
    "esriSFSVertical": "Вертикално"
  },
  "threatTypeLabel": "Тип заплаха",
  "generalLabel": "Общ",
  "addThreatTypesLabel": "Добавяне на тип заплаха",
  "actions": "Действия",
  "newThreatTypePopupLabel": "Нов тип заплаха",
  "units": "Мерни единици",
  "chooseDefaultThreatLabel": "Избиране на тип заплаха по подразбиране",
  "defaultThreatTypePopUpLabel": "Типове заплаха по подразбиране",
  "editThreatLabel": "Редактиране на заплаха",
  "defaultThreatTypeIconTooltip": "Списък на типове заплаха по подразбиране",
  "uniqueThreatTypeMsg": "Въведете уникален тип заплаха, тип заплаха с това име вече съществува.",
  "requiredMsg": "Това поле е задължително",
  "unitMeasureLabel": "Разстоянията са в {0}",
  "chooseDefaultThreatTypeIconLabel": "Изберете по подразбиране",
  "pipeBombLabel": "Самоделна тръбна бомба",
  "suicideBombLabel": "Самоубийствена бомба",
  "briefcaseLabel": "Куфар",
  "carLabel": "Кола",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Малък камион за доставка",
  "containerWaterTruckLabel": "Контейнер/Камион за вода",
  "semiTrailerLabel": "Полу-ремарке",
  "chemicalThreatLegendLabel": "Химическа заплаха",
  "lpgThreatLegendLabel": "Заплаха, свързана с пропан-бутан (LPG)",
  "smallLPGTank": "Малък резервоар за пропан-бутан (LPG)",
  "largeLPGTank": "Голям резервоар за пропан-бутан (LPG)",
  "commercialResidentialLPGTank": "Резервоар за пропан-бутан (LPG) за търговски/битови нужди",
  "smallLPGTruck": "Малък камион за пропан-бутан (LPG)",
  "semiTankerLPG": "Полу-танкер за пропан-бутан (LPG)",
  "threatDescriptionColLabel": "Описание на заплаха",
  "addThreatZoneButtonLabel": "Добавяне на зона на заплаха",
  "zoneDescColLabel": "Описание на зона",
  "distanceLabel": "Разстояние (${unitAbbr})",
  "threatTypeHelp": "<p>Уверете се, че са изпълнени следните условия за тип заплаха:<br/><ul><li>Типът на заплахата не може да бъде празен и трябва да е уникален</li><li>Трябва да има заплаха поне в една валидна зона</li><li>Описанието на зоната трябва да бъде уникално за заплаха</li></ul><p/>",
  "descriptionLabel": "Описание",
  "newThreatZonePopupLabel": "Нова зона на заплаха",
  "editThreatZonePopupLabel": "Редактиране на зоната на заплаха",
  "uniqueZoneDescriptionMsg": "Въведете уникално описание на зоната, описание на зона с това име вече съществува.",
  "symbologyColLabel": "Симвология",
  "zoneDescriptionColLabel": "Описание на зона",
  "uniqueZoneRequiredMsg": "Името на зоната трябва да бъде уникално за",
  "interactive": "Интерактивни",
  "fromCoord": "Фиксирани координати",
  "existingFeature": "От съществуващите обекти",
  "defaultInputLocationLabel": "Въвеждане на местоположение по подразбиране",
  "defaultInputLayer": "Въвеждане на слой по подразбиране",
  "defaultThreatType": "Тип заплаха по подразбиране",
  "selectLabel": "Избор",
  "mandatoryLabel": "Задължително разстояние за евакуация",
  "safeLabel": "Безопасно разстояние за евакуация",
  "lpgSafeDistanceLable": "Безопасно разстояние",
  "fireBallDiameterLable": "Диаметър на огненото кълбо"
});