define({
  "taskUrl": "Uzdevuma URL",
  "setTask": "Iestatīt",
  "setTaskPopupTitle": "Iestatīt uzdevumu",
  "validate": "Iestatīt",
  "inValidGPService": "Ievadiet derīgu ģeodatu apstrādes servisu.",
  "noOutputParameterWithGeometryType": "Izvēlētajā ģeodatu apstrādes servisā jābūt vismaz vienam izvades parametram ar norādītu ģeometrijas veidu. Lūdzu, izvēlieties citu ģeodatu apstrādes servisu.",
  "invalidOutputGeometry": "Izvēlētā ģeodatu apstrādes servisa izvades ģeometrijas veids nav saderīgs ar projekta iestatījumiem. Nevar saglabāt ģeodatu apstrādes servisa rezultātus.",
  "GPFeatureRecordSetLayerERR": "Ievadiet ģeodatu apstrādes servisu tikai ar ievadņu veidu “GPFeatureRecordSetLayer”.",
  "invalidInputParameters": "Ievades parametru skaits ir mazāks par 1 vai lielāks par 3. Lūdzu, atveriet derīgu ģeodatu apstrādes servisu.",
  "projectSetting": {
    "title": "Projekta iestatījumi",
    "note": "Piezīme: Projekta iestatījumi nav obligāti, jo tiklīdz konfigurējis, lietotājs var glabāt projektu vēlamajos tīmekļa kartes slāņos ar ievades parametriem un tīkla zuduma teritoriju. Lietotājs var saglabāt citus izvades parametrus no cilnes “Izvade”.",
    "projectPolygonLayer": "Projekta laukumu slānis",
    "outputParameterName": "Izvades parametra nosaukums",
    "projectPointLayer": "Projekta punktu slānis",
    "selectLabel": "Atlasīt",
    "polygonLayerHelp": "<p>Tiks parādīti laukuma slāņi ar šādiem nosacījumiem:<br/><ul><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar tieši šādiem nosaukumiem un datu veidiem:</li><ul><li>nosaukums (virknes veida lauks)</li><li>globalid GlobalID (GlobalID veida lauks)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Tiks parādīti izvades laukuma slāņi no uzdevuma vietrāža (URL)<p/>",
    "pointLayerHelp": "<p>Tiks parādīti punktu slāņi ar šādiem nosacījumiem:<br/><ul><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar tieši šādiem nosaukumiem un datu veidiem:</li><ul><li>inputtype (virknes veida lauks)</li><li>projectid (GlobalID veida lauks)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Karogs",
    "barrier": "Barjera",
    "skip": "Izlaist",
    "title": "Ievade",
    "inputTooltip": "Rīka padoms",
    "typeText": "Veids",
    "symbol": "Simbols",
    "summaryEditorText": "Kopsavilkuma teksts",
    "summaryTextTitle": "Ievadiet tekstu, kas jāparāda ievades cilnē"
  },
  "summaryTab": {
    "title": "Izvade",
    "summaryFieldsetText": "Kopsavilkuma iestatījumi",
    "inputOutput": "Ievade/izvade",
    "field": "Lauks",
    "operator": "Operators",
    "inputOperatorCountOption": "Skaits",
    "outputOperatorCountOption": "Skaits",
    "outputOperatorSkipCountOption": "Izlaist skaitu",
    "fieldOperatorSumOption": "Summa",
    "fieldOperatorMinOption": "Min.",
    "fieldOperatorMaxOption": "Maks.",
    "fieldOperatorMeanOption": "Vidējais",
    "expressionAddButtonText": "Pievienot",
    "expressionVerifyButtonText": "Verificēt",
    "summaryEditorText": "Kopsavilkuma teksts",
    "zoomText": "Automātiska tālummaiņa pēc trasēšanas",
    "summarSettingTooltipText": "Pievienot ievades/izvades skaitu",
    "symbol": "Simbols",
    "outputParametersText": "Izvades parametri",
    "skipText": "Izlaižams",
    "visibilityText": "Redzams",
    "exportToCsvText": "Eksportēt uz CSV",
    "settitngstext": "Iestatījumi",
    "saveToLayerText": "Saglabāt slānī (pēc izvēles)",
    "inputLabel": "Kartes teksts",
    "inputTooltip": "Rīka padoms",
    "outputDisplay": "Parādīt tekstu",
    "addFieldTitle": "Pievienot lauku",
    "setScale": "Iestatīt mērogu",
    "enterDisplayText": "Ievadīt parādāmo tekstu",
    "saveToLayerHelp": "<p>Tiks parādīts slānis ar šādiem nosacījumiem:<br/><ul><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar nosaukumu un datu veidu:</li><ul><li>parametername (virknes veida lauks)</li><li>projectid (Guid veida lauks)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Ievadiet kopsavilkuma tekstu, kas jāparāda izvades cilnē",
    "addSummaryItemsTitle": "Pievienot kopsavilkuma vienumus"
  },
  "validationErrorMessage": {
    "webMapError": "Tīmekļa karte nav neviena pieejama slāņa. Lūdzu, izvēlieties derīgu tīmekļa karti.",
    "inputTypeFlagGreaterThanError": "Ievadē karoga veids nevar būt vairāk par viena veida karogu (sākuma punktu).",
    "inputTypeFlagLessThanError": "Ir nepieciešama vismaz viena ievade veidā karogs (sākuma punkts).",
    "inputTypeBarrierErr": "Ievadē barjeras veids nevar būt vairāk par vienu barjeras veidu.",
    "inputTypeSkipErr": "Ievadē izlaišanas veids nevar  būt vairāk par vienu  ievadi.",
    "displayTextForButtonError": "Pogas “Palaist” parādāmais teksts nevar būt tukšs.",
    "UnableToLoadGeoprocessError": "Nevar ielādēt ģeodatu apstrādes servisu.",
    "invalidSummaryExpression": "Nederīga izteiksme.",
    "validSummaryExpression": "Izdevās!",
    "invalidProjectSettings": "Nederīgi projekta iestatījumi.<br/> Lūdzu, izvēlieties derīgu vērtību sadaļā “${projectSetting}”."
  },
  "hintText": {
    "labelTextHint": "Padoms. Nodrošiniet kartes attēlojuma tekstu izvades parametru rezultātu panelim.",
    "displayTextHint": "Padoms. Tas tiks parādīts šī izvades parametra datu panelī.",
    "inputTextHint": "Padoms. Zemāk izveidojiet savu izteiksmi, izmantojot pogu Pievienot kopsavilkums vienumus.",
    "expressionHint": "Padoms. Izvēlieties vienības un noklikšķiniet uz Pievienot, lai izveidotu izteiksmi."
  }
});