define({
  "_widgetLabel": "Príručka k núdzovej odozve",
  "ergMainPageTitle": "Založené na Smernici núdzovej odozvy 2020",
  "coordInputLabelStart": "Umiestnenie úniku",
  "coordInputLabel": "Umiestnenie úniku",
  "addPointToolTip": "Pridať umiestnenie úniku",
  "drawPointToolTip": "Kliknite pre pridanie umiestnenia úniku",
  "material": "Materiál",
  "materialPlaceholder": "Pre vyhľadanie materiálu začnite písať",
  "table3Message": "Materiál, ktorý ste vybrali, vyžaduje doplnkové informácie, ak máte čo dočinenia s veľkým únikom.\n\nUistite sa, že máte správne hodnoty vybrané pre rýchlosť vetra a prepravný kontajner.",
  "table2Message": "Materiál, ktorý ste vybrali, môže pri rozliatí do vody produkovať veľké množstvo toxických plynov nebezpečných pri vdýchnutí.\n\nMožno budete chcieť zvážiť použitie nasledujúcich materiálov:\n\n",
  "spillSize": "Veľkosť úniku",
  "small": "Malé",
  "large": "Veľké",
  "fireLabel": "Zobraziť zónu izolácie ohňa",
  "weatherLabel": "Aktuálne počasie v umiestnení úniku",
  "weatherIntialText": "<br />Aktualizované po zistení umiestnenia úniku",
  "temperature": "Teplota",
  "wind": "Vietor",
  "c": "Celzius",
  "f": "Fahrenheit",
  "weatherErrorMessage": "Informácie o počasí neboli získané. Aktualizovať hodnoty rýchlosti vetra a času úniku manuálne",
  "windDirection": "Smer vetra (fúka na)",
  "timeOfSpill": "Čas úniku",
  "day": "Deň",
  "night": "Noc",
  "windSpeed": "Rýchlosť vetra",
  "low": "Nízka",
  "moderate": "Stredná",
  "high": "Vysoká",
  "transportContainer": "Prepravný kontajner",
  "rail": "Železničná cisterna",
  "semi": "Cestná cisterna alebo príves",
  "mton": "Viactonové valce",
  "ston": "Niekoľko malých valcov alebo jednotonový valec",
  "ag": "Poľnohospodárska cisterna",
  "msm": "Niekoľko malých valcov",
  "bleveLabel": "Zobraziť zónu izolácie BLEVE",
  "capacity": "Kapacita kontajnera (litre)",
  "bleveMessage": "Pre materiál, ktorý ste vybrali, sa pre BLEVE môže zobraziť ďalšia evakuačná vzdialenosť.\n\nAk to chcete povoliť, zapnite Zobraziť zónu izolácie BLEVE a vyberte príslušnú kapacitu kontajnera.",
  "noPAZoneMessage": "Pre tento materiál neexistujú žiadne vzdialenosti ochranného pôsobenia. Vypočítali sa iba zóny počiatočnej izolácie a evakuácie",
  "settingsTitle": "Nastavenia",
  "spillLocationLabel": "Umiestnenie úniku",
  "spillLocationButtonLabel": "Konfigurovať nastavenia umiestnenia úniku",
  "IISettingsLabel": "Zóna počiatočnej izolácie",
  "IIButtonLabel": "Konfigurovať nastavenia počiatočnej izolácie",
  "PASettingsLabel": "Zóna ochranného pôsobenia",
  "PAButtonLabel": "Konfigurovať nastavenia ochranného pôsobenia",
  "downwindSettingsLabel": "Zóna v smere vetra",
  "downwindButtonLabel": "Konfigurovať nastavenia v smere vetra",
  "fireSettingsLabel": "Zóna izolácie ohňa",
  "fireButtonLabel": "Konfiurovať nastavenia izolácie ohňa",
  "bleveSettingsLabel": "Zóna izolácie BLEVE",
  "bleveButtonLabel": "Konfigurovať nastavenia BLEVE",
  "style": "Štýl",
  "lineStyles": {
    "esriSLSDash": "Pomlčka",
    "esriSLSDashDot": "Pomlčka bodka",
    "esriSLSDashDotDot": "Pomlčka bodka bodka",
    "esriSLSDot": "Bodka",
    "esriSLSLongDash": "Dlhá pomlčka",
    "esriSLSLongDashDot": "Dlhá pomlčka bodka",
    "esriSLSNull": "Nula",
    "esriSLSShortDash": "Krátka pomlčka",
    "esriSLSShortDashDot": "Krátka pomlčka bodka",
    "esriSLSShortDashDotDot": "Krátka pomlčka bodka bodka",
    "esriSLSShortDot": "Krátka bodka",
    "esriSLSSolid": "Plné"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Späť",
    "esriSFSCross": "Priečne",
    "esriSFSDiagonalCross": "Uhlopriečne",
    "esriSFSForwardDiagonal": "Vpred",
    "esriSFSHorizontal": "Horizontálne",
    "esriSFSNull": "Nula",
    "esriSFSSolid": "Plné",
    "esriSFSVertical": "Vertikálne"
  },
  "resultsTitle": "Výsledky",
  "publishERGBtn": "Publikovať",
  "ERGLayerName": "Publikovaný názov vrstvy podľa smernice k núdzovej odozve",
  "invalidERGLayerName": "Názov vrstvy musí obsahovať iba alfanumerické znaky a podčiarkovníky",
  "publishingFailedLayerExists": "Publikovanie zlyhalo: Už máte službu pre prvky s názvom {0}. Vyberte iný názov.",
  "checkService": "Skontrolovať službu: {0}",
  "createService": "Vytvoriť službu: {0}",
  "unableToCreate": "Nebolo možné vytvoriť: {0}",
  "addToDefinition": "Pridať do definície: {0}",
  "successfullyPublished": "Webová vrstva {0} úspešne publikovaná Spravovať webovú vrstvu",
  "userRole": "Nebolo možné vytvoriť službu, pretože používateľ nemá povolenia",
  "publishToNewLayer": "Publikovať výsledky do novej vrstvy prvkov",
  "unabletoWriteToLayer": "Nebolo možné publikovať do existujúcej vrstvy kvôli nedostatočným povoleniam. Vo vašej organizácii bude vytvorená nová vrstva",
  "layerNameExists": "Názov vrstvy už existuje. Použite iný názov vrstvy.",
  "transparency": "Priehľadnosť",
  "outline": "Obrys",
  "fill": "Výplň (Farba sa použije iba v prípade, že je štýl nastavený na plný)",
  "createERGBtn": "Vytvoriť zóny",
  "clearERGBtn": "Vyčistiť",
  "labelFormat": "Formát popisu",
  "helpIconTooltip": "Hranica medzi malými a veľkými veľkosťami úniku je:\nTekutiny - 55 galónov (208 litrov)\nPevné látky - 60 libier (300 kilogramov)",
  "cellWidth": "Šírka bunky (x)",
  "cellHeight": "Výška bunky (y)",
  "invalidNumberMessage": "Zadaná hodnota nie je platná",
  "invalidRangeMessage": "Hodnota musí byť medzi 0 - 359",
  "gridAngleInvalidRangeMessage": "Hodnota musí byť medzi -89,9 a 89,9",
  "formatIconTooltip": "Formát vstupu",
  "setCoordFormat": "Nastaviť zápis formátu súradníc",
  "prefixNumbers": "Pridať \"+/-\" ku kladným a záporným číslam",
  "cancelBtn": "Zrušiť",
  "applyBtn": "Použiť",
  "comfirmInputNotation": "Potvrdiť zápis vstupu",
  "notationsMatch": "zápisy zodpovedajú vášmu vstupu, prosím potvrďte, ktoré chcete použiť:",
  "missingLayerNameMessage": "Pred publikovaním musíte zadať platný názov vrstvy",
  "parseCoordinatesError": "Nie je možné interpretovať súradnice. Skontrolujte svoj vstup.",
  "colorPicker": "Výber farby",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desatinné stupne - Zemepisná šírka/dĺžka",
  "DDLongLatNotation": "Desatinné stupne - Zemepisná dĺžka/šírka",
  "DDMLatLongNotation": "Stupne desatinné minúty - Zemepisná šírka/dĺžka",
  "DDMLongLatNotation": "Stupne desatinné minúty - Zemepisná dĺžka/šírka",
  "DMSLatLongNotation": "Stupne minúty sekundy - Zemepisná šírka/dĺžka",
  "DMSLongLatNotation": "Stupné minúty sekundy - Zemepisná dĺžka/šírka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - písmeno hemisféry",
  "UTMHemNotation": "UTM - pologuľa (S/J)"
});