define({
  "_widgetLabel": "Печат",
  "title": "Заглавие на карта",
  "format": "Формат",
  "layout": "Оформление",
  "settings": "Разширени",
  "labels": "Етикети",
  "showLabels": "Показване на надписи",
  "mapScaleExtent": "Мащабиране/обхват на карта",
  "preserve": "Запазване",
  "mapScale": "мащаб на карта",
  "mapExtent": "обхват на карта",
  "forceScale": "Сила на мащаб",
  "getCurrentScale": "в момента",
  "mapMetadata": "Метаданни на оформление",
  "author": "Автор",
  "copyright": "Авторски права",
  "fullLayoutOptions": "Опции за пълно оформление",
  "scaleBarUnit": "Единица за скалата за мащаб",
  "scaleBarUnitsMetric": "Метрична единица на скалата за мащаб",
  "scaleBarUnitsNonMetric": "Неметрична единица на скалата за мащаб",
  "unitsMiles": "Мили",
  "unitsKilometers": "Километри",
  "unitsMeters": "Метри",
  "unitsFeet": "Фута",
  "unitsYards": "Ярда",
  "unitsNauticalMiles": "Морски мили",
  "lncludeLegend": "Включване на легенда",
  "printQualityOptions": "Качество на отпечатването",
  "dpi": "DPI",
  "mapOnlyOptions": "размер MAP_ONLY",
  "width": "Широчина (px)",
  "height": "Височина (px)",
  "print": "Печат",
  "clearList": "Изчистване на отпечатване",
  "creatingPrint": "Създаване на отпечатване",
  "printError": "Грешка, опитайте отново",
  "forceFeatureAttributes": "Атрибути на обекти",
  "includeFeatureAttributes": "Включване на атрибути",
  "outputSR": "Извеждане на пространствено отношение",
  "invalidWkid": "Невалиден wkid"
});