define({
  "taskUrl": "URL บริการ Viewshed",
  "portalURL": "ระบุ URL ให้กับ ArcGIS Online หรือ Portal for ArcGIS",
  "portalURLError": "URL ไปยังองค์กร ArcGIS Online ของคุณ หรือ Portal for ArcGIS ที่กำหนดค่าไว้ใช้ไม่ได้",
  "privilegeError": "บทบาทผู้ใช้ของคุณไม่สามารถทำการวิเคราะห์ได้ หากต้องการดำเนินการวิเคราะห์ ผู้ดูแลองค์กรของคุณจะต้องมอบ<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">สิทธิ์</a>บางอย่างให้กับคุณ",
  "noServiceError": "เซอร์วิสวิเคราะห์ระดับความสูงไม่พร้อมใช้งาน โปรดตรวจสอบการกำหนดค่าองค์กร ArcGIS Online ของคุณ หรือ Portal for ArcGIS",
  "serviceURLPlaceholder": "โปรดใส่ URL งานประมวลผลข้อมูลภูมิศาสตร์ Viewshed",
  "setTask": "ตั้ง",
  "setTaskTitle": "ตั้งค่างานประมวลผลข้อมูลภูมิศาสตร์ Viewshed",
  "serviceURLError": "งานประมวลผลข้อมูลภูมิศาสตร์ที่คุณกำลังพยายามกำหนดค่าด้วยวิดเจ็ตนี้ไม่ถูกต้อง โปรดเลือก URL งานประมวลผลข้อมูลภูมิศาสตร์ Viewshed ที่ถูกต้อง",
  "defaultMilsForAnglesLabel": "ตั้งค่า mils สำหรับมุมเป็นค่าเริ่มต้น",
  "defaultObserverHeightLabel": "ยูนิตความสูงตัวสังเกตการณ์เริ่มต้น",
  "defaultObservableDistanceLabel": "หน่วยระยะทางที่สังเกตการณ์ได้เริ่มต้น",
  "units": {
    "miles": "ไมล์",
    "kilometers": "กิโลเมตร",
    "feet": "ฟุต",
    "meters": "เมตร",
    "yards": "หลา",
    "nauticalMiles": "ไมล์ทะเล"
  },
  "helpIconTooltip": "รายการชั้นข้อมูลดำเนินการ จะถูกนำเข้าแบบอัตโนมัติพร้อมชั้นข้อมูลจากเว็บแมปปัจจุบัน ซึ่งเป็นประเภทรูปทรงเรขาคณิตโพลีกอน",
  "selectOperationalLayerLabel": "เลือกชั้นข้อมูลดำเนินการสำหรับผลลัพธ์",
  "lineOfSightTabTitle": "เส้นทางที่ปราศจากสิ่งกีดขวาง",
  "symbologyTabTitle": "เกี่ยวกับสัญลักษณ์",
  "transparency": "โปร่งแสง",
  "outline": "โครงร่าง",
  "fill": "พื้น (ใช้สีเฉพาะเมื่อรูปแบบถูกตั้งค่าเป็นแบบทึบ)",
  "style": "สไตล์",
  "selectOpLayerLabel": "เลือกชั้นข้อมูลดำเนินการสำหรับผลลัพธ์",
  "selectDefaultMeasurementLabel": "เลือกหน่วยวัดเริ่มต้น",
  "visibleSectionLabel": "ส่วนที่มองเห็น",
  "nonVisibleSectionLabel": "ส่วนที่มองไม่เห็น",
  "visibleSectionButtonLabel": "กำหนดค่าการตั้งค่าส่วนที่มองเห็น",
  "nonVisibleSectionButtonLabel": "กำหนดค่าการตั้งค่าส่วนที่มองไม่เห็น",
  "colorPicker": "ตัวเลือกสี",
  "lineStyles": {
    "esriSLSDash": "เส้นขีด",
    "esriSLSDashDot": "เส้นขีด จุด",
    "esriSLSDashDotDot": "เส้นขีด จุด จุด",
    "esriSLSDot": "จุด",
    "esriSLSLongDash": "เส้นขีดยาว",
    "esriSLSLongDashDot": "เส้นจุดยาว",
    "esriSLSNull": "ไม่มีค่า",
    "esriSLSShortDash": "เส้นขีดสั้น",
    "esriSLSShortDashDot": "เส้นจุดสั้น",
    "esriSLSShortDashDotDot": "เส้นขีดและจุดสั้น",
    "esriSLSShortDot": "จุดสั้น",
    "esriSLSSolid": "สีเดียว"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "ย้อนกลับ",
    "esriSFSCross": "กากบาท",
    "esriSFSDiagonalCross": "เส้นทแยงมุม",
    "esriSFSForwardDiagonal": "ส่งต่อ",
    "esriSFSHorizontal": "แนวนอน",
    "esriSFSNull": "ไม่มีค่า",
    "esriSFSSolid": "สีเดียว",
    "esriSFSVertical": "ตั้งฉาก"
  }
});