define({
  "_widgetLabel": "Координата",
  "hintMessage": "Натиснете върху картата, за да получите координати.",
  "defaultLabel": "По подразбиране",
  "realtimeLabel": "Преместете мишката, за да получите координати.",
  "computing": "Изчисляване...",
  "latitudeLabel": "Географска ширина",
  "longitudeLabel": "Географска дължина",
  "loading": "Зареждане...",
  "enableClick": "Натиснете, за да активирате получаването на координати като натиснете върху картата.",
  "disableClick": "Натиснете, за да деактивирате получаването на координати като натиснете върху картата.",
  "Default": "По подразбиране",
  "Inches": "Инч",
  "Foot": "Фута",
  "Yards": "Ярда",
  "Miles": "Мили",
  "Nautical_Miles": "Морски мили",
  "Millimeters": "Милиметри",
  "Centimeters": "Сантиметри",
  "Meter": "Метри",
  "Kilometers": "Километри",
  "Decimeters": "Дециметри",
  "Decimal_Degrees": "Градуси",
  "Degree_Minutes_Seconds": "Градуси минути секунди",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "на нивото на очите",
  "ELEV": "кота"
});