define({
  "transparencyLabel": "Trasparenza",
  "outline": "Bordo",
  "fill": "Riempimento (Il colore si applica solo quando lo stile è impostato su tinta unita)",
  "style": "Stile",
  "selectOpLayerLabel": "Selezionare un layer operativo per i risultati",
  "selectDefaultMeasurementLabel": "Selezionare un'unità di misura predefinita",
  "helpIconTooltip": "L'elenco dei layer operativi è popolato con i layer della mappa Web corrente che sono di tipo a geometria poligonale.",
  "lineStyles": {
    "esriSLSDash": "Trattino",
    "esriSLSDashDot": "Trattino punto",
    "esriSLSDashDotDot": "Trattino Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Trattino lungo",
    "esriSLSLongDashDot": "Trattino lungo punto",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trattino corto",
    "esriSLSShortDashDot": "Trattino corto punto",
    "esriSLSShortDashDotDot": "Trattino corto punto punto",
    "esriSLSShortDot": "Punto corto",
    "esriSLSSolid": "Tinta unita"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Indietro",
    "esriSFSCross": "Croce",
    "esriSFSDiagonalCross": "Diagonale",
    "esriSFSForwardDiagonal": "Avanti",
    "esriSFSHorizontal": "Orizzontale",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Tinta unita",
    "esriSFSVertical": "Verticale"
  },
  "threatTypeLabel": "Tipo di minaccia",
  "generalLabel": "Generale",
  "addThreatTypesLabel": "Aggiungi tipo di minaccia",
  "actions": "Azioni",
  "newThreatTypePopupLabel": "Nuovo tipo di minaccia",
  "units": "Unità",
  "chooseDefaultThreatLabel": "Seleziona tipo di minaccia predefinito",
  "defaultThreatTypePopUpLabel": "Tipi di minaccia predefiniti",
  "editThreatLabel": "Modifica minaccia",
  "defaultThreatTypeIconTooltip": "Elenco dei tipi di minaccia predefiniti",
  "uniqueThreatTypeMsg": "Immettere un tipo di minaccia univoco; esiste già un tipo di minaccia con questo nome.",
  "requiredMsg": "Campo obbligatorio",
  "unitMeasureLabel": "Le distanze sono in {0}",
  "chooseDefaultThreatTypeIconLabel": "Scegliere da predefiniti",
  "pipeBombLabel": "Tubo bomba",
  "suicideBombLabel": "Bomba suicida",
  "briefcaseLabel": "Valigetta",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Furgone per le consegne",
  "containerWaterTruckLabel": "Container/Cisterna",
  "semiTrailerLabel": "Semirimorchio",
  "chemicalThreatLegendLabel": "Minaccia chimica",
  "lpgThreatLegendLabel": "Minaccia GPL",
  "smallLPGTank": "Serbatoio GPL piccolo",
  "largeLPGTank": "Serbatoio GPL grande",
  "commercialResidentialLPGTank": "Serbatoio GPL residenziale/commerciale",
  "smallLPGTruck": "Camion GPL piccolo",
  "semiTankerLPG": "Semi-autocisterna GPL",
  "threatDescriptionColLabel": "Descrizione minaccia",
  "addThreatZoneButtonLabel": "Aggiungi zona di minaccia",
  "zoneDescColLabel": "Descrizione zona",
  "distanceLabel": "Distanza (${unitAbbr})",
  "threatTypeHelp": "<p>Assicurarsi che le seguenti condizioni siano rispettate per un tipo di minaccia:<br/><ul><li>Tipo di minaccia non può essere vuoto e dovrebbe essere unico</li><li>La minaccia dovrebbe almeno possedere una zona valida</li><li>La descrizione della zona dovrebbe essere unica per una minaccia</li></ul><p/>",
  "descriptionLabel": "Descrizione",
  "newThreatZonePopupLabel": "Nuova zona di minaccia",
  "editThreatZonePopupLabel": "Modifica zona di minaccia",
  "uniqueZoneDescriptionMsg": "Inserisci una descrizione unica della zona, la descrizione della zona con questo nome esiste già.",
  "symbologyColLabel": "Simbologia",
  "zoneDescriptionColLabel": "Descrizione zona",
  "uniqueZoneRequiredMsg": "Il nome della zona dovrebbe essere unico per",
  "interactive": "Interattivo",
  "fromCoord": "Coordinata fissa",
  "existingFeature": "Da feature esistenti",
  "defaultInputLocationLabel": "La posizione input predefinita",
  "defaultInputLayer": "Layer input predefinito",
  "defaultThreatType": "Tipo di minaccia predefinito",
  "selectLabel": "Seleziona",
  "mandatoryLabel": "Distanza di evacuazione obbligatoria",
  "safeLabel": "Distanza di evacuazione di sicurezza",
  "lpgSafeDistanceLable": "Distanza di sicurezza",
  "fireBallDiameterLable": "Diametro meteorite"
});