define({
  "_widgetLabel": "Batch-Attribut-Editor",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Layer-Name",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Es wurden keine Layer konfiguriert.",
  "editorPopupTitle": "Batch-Attribut-Editor",
  "editorPopupSaveBtn": "Speichern",
  "editorPopupMultipleValues": "",
  "clear": "Auswahl aufheben",
  "featuresUpdated": "${0} / ${1} Feature(s) wurde(n) aktualisiert",
  "featuresSelected": "${0} Feature(s) wurde(n) ausgewählt",
  "featuresSkipped": "Umgangen",
  "featuresNoPermision": "${0} Feature(s) wurde(n) ausgewählt, jedoch besteht keine Berechtigung zum Bearbeiten.",
  "search": "Suchen",
  "queryInput": "Abzufragenden Wert eingeben",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Legen Sie den Filter ordnungsgemäß fest.",
  "filterPopup": "Layer filtern",
  "filterAppend": "Wenn in der Webkarte bereits ein Filter für diesen Layer vorhanden ist",
  "filterAppendOR": "Einige Ausdrücke an vorhandenen Kartenfilter anhängen",
  "filterAppendAND": "Alle Ausdrücke an vorhandenen Kartenfilter anhängen",
  "cancel": "Abbrechen",
  "noValue": "Kein Wert",
  "emptyString": "Leere Zeichenfolge",
  "existingValue": "Vorhandenen Wert beibehalten",
  "newDate": "Neue Daten",
  "valueChooser": "Einen Wert auswählen/eingeben",
  "ok": "OK",
  "drawBox": {
    "point": "Punkt",
    "line": "Linie",
    "polyline": "Polylinie",
    "freehandPolyline": "Freihand-Polylinie",
    "extent": "Ausdehnung",
    "polygon": "Polygon",
    "freehandPolygon": "Freihand-Polygon",
    "clear": "Auswahl aufheben",
    "addPointToolTip": "Klicken Sie hier, um in diesem Bereich auszuwählen",
    "addShapeToolTip": "Zeichnen Sie eine Form, um Features auszuwählen",
    "freehandToolTip": "Halten Sie die Maustaste gedrückt, um eine Form zum Auswählen von Features zu zeichnen",
    "startToolTip": "Zeichnen Sie eine Form, um Features auszuwählen"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Das Feature aus ${0} gab eine ungültige ID zurück",
    "noSelectedLayers": "Keine ausgewählten Layer mit zu aktualisierenden Datensätzen",
    "inputValueError": "Ungültiger Wert im Formular",
    "saveError": "${0} Features können nicht gespeichert werden",
    "requiredValue": "Erforderlicher Wert"
  }
});