define({
  "_widgetLabel": "Išmanusis redaktorius",
  "_featureAction_SmartEditor": "Išmanusis redaktorius",
  "noEditPrivileges": "Jūsų paskyra neturi teisės kurti arba modifikuoti duomenų.",
  "loginPopupTitle": "Prisijungti",
  "loginPopupMessage": "Norint peržiūrėti ir saugoti adresų informaciją, ${widgetName} reikia teisių ir kreditų. Ar norite prisijungti ir šia galimybe pasinaudoti?",
  "noCreditsOrPrivilegeWarningMessage": "Jūsų paskyra neturi teisių ir kreditų ieškoti adresų informacijos ir ją saugoti naudojant ${widgetName}. Norėdami paprašyti teisių ir kreditų, susisiekite su savo organizacijos administratoriumi.",
  "unableToUseLocator": "Lokatorius nepasiekiamas. Adreso atributo veiksmas (-ai) nebus atliekamas (-i).",
  "locatorDisabledWaning": "Lokatorius neaktyvuotas. Norėdami paprašyti šios funkcijos, susisiekite su savo organizacijos administratoriumi.",
  "noFeatureInAIWarning": "Nepasirinkti joks (-ie) elementas (-ai). Pasirinkite elementą atlikti redagavimus arba spustelėkite Atšaukti, jei norite grįžti į pagrindinį ekraną.",
  "noEditableLayerWarning": "Jūsų paskyra nesuteikia teisės kurti ar modifikuoti duomenis arba šiame internetiniame žemėlapyje nėra jokių redaguojamų sluoksnių.",
  "noVisibleCreateLayerWarning": "Tokiu masteliu sluoksnis (-iai) nerodomi. Norėdami sukurti/modifikuoti elementus, padidinkite ar sumažinkite mastelį.",
  "noVisibleUpdateLayerWarning": "Tokiu masteliu sluoksnis (-iai) nerodomi. Norėdami modifikuoti elementus, padidinkite ar sumažinkite mastelį.",
  "checkLayerVisibilityInWebMapWarning": "Kuriant ar modifikuojant elementus, sluoksniai žemėlapyje turi būti rodomi.",
  "showSelectionInAITitle": "Pažymėti elementai",
  "showSelectionInAIMsg": "Ar norite dabartinį pasirinkimą įkelti į ${widgetName}?",
  "widgetActive": "Aktyvus",
  "widgetNotActive": "Neaktyvus",
  "pressStr": "Paspauskite ",
  "ctrlStr": " CTRL ",
  "snapStr": " pritraukimui įjungti",
  "noAvailableTempaltes": "Galimų šablonų nėra",
  "editorCache": " - Redagavimo podėlis",
  "presetFieldAlias": "Laukas",
  "presetValue": "Iš anksto nustatyta reikšmė",
  "usePresetValues": " Naudoti iš anksto nustatytas reikšmes (tik naujiems elementams)",
  "editGeometry": " Redaguoti geometriją",
  "savePromptTitle": "Įrašyti elementą",
  "savePrompt": "Ar norite išsaugoti šį elementą?",
  "deletePromptTitle": "Ištrinti elementą",
  "deleteAttachment": "Ištrinti priedą",
  "deletePrompt": "Ar tikrai norite ištrinti šį elementą?",
  "attachmentLoadingError": "Klaida įkeliant priedus",
  "attachmentSaveDeleteWarning": "Įspėjimas: priedų pakeitimai įrašomi automatiškai",
  "autoSaveEdits": "Automatiškai įrašyti naujus elementus",
  "addNewFeature": "Sukurti naują elementą",
  "featureCreationFailedMsg": "Negalima sukurti naujo įrašo / elemento",
  "relatedItemTitle": "Susijusi lentelė / sluoksnis",
  "relatedFeatureCount": "${layerTitle} su ${featureCount} elementais",
  "createNewFeatureLabel": "Kurti naują elementą, skirtą ${layerTitle}",
  "invalidRelationShipMsg": "Įsitikinkite, kad pirminio rakto: '${parentKeyField}' reikšmė yra tinkama",
  "pendingFeatureSaveMsg": "Įrašykite pakeistus elementus prieš kurdami susijusį elementą.",
  "attachmentsRequiredMsg": "(*) Reikalingi priedai.",
  "coordinatePopupTitle": "Perkelti elementą į XY vietą",
  "coordinatesSelectTitle": "Koordinačių sistema:",
  "mapSpecialReferenceDropdownOption": "Žemėlapio koordinačių sistema",
  "latLongDropdownOption": "Platuma/Ilguma",
  "mgrsDropdownOption": "Karinio tinklelio atskaitos sistema (MGRS)",
  "mgrsTextBoxLabel": "Koordinatė:",
  "xAttributeTextBoxLabel": "X koordinatė:",
  "yAttributeTextBoxLabel": "Y koordinatė:",
  "latitudeTextBoxLabel": "Platuma:",
  "longitudeTextBoxLabel": "Ilguma:",
  "presetGroupFieldsLabel": "${groupName} bus taikomas šiems sluoksnio laukams:",
  "presetGroupNoFieldsLabel": "${groupName} neturi jokių susijusių laukų",
  "groupInfoLabel": "${groupName} grupės informacija",
  "editGroupInfoIcon": "Redaguoti ${groupName} grupės reikšmę",
  "filterEditor": {
    "all": "Viskas",
    "noAvailableTempaltes": "Galimų šablonų nėra",
    "searchTemplates": "Ieškoti šablonų",
    "filterLayerLabel": "Filtruoti sluoksnius"
  },
  "invalidConfiguration": "Valdiklis nesukonfigūruotas arba konfigūracijos sluoksnių žemėlapyje nebėra. Atidarykite aplikaciją kūrimo režime ir iš naujo sukonfigūruokite valdiklį.",
  "geometryServiceURLNotFoundMSG": "Negalima gauti geometrijos paslaugos URL",
  "clearSelection": "Uždaryti",
  "refreshAttributes": "Naujinti dinaminius elementų atributus",
  "automaticAttributeUpdatesOn": "Automatiškai atnaujinti elementų atributus: ĮJUNGTA",
  "automaticAttributeUpdatesOff": "Automatiškai atnaujinti elementų atributus: IŠJUNGTA",
  "moveSelectedFeatureToGPS": "Perkelti pasirinktą elementą į dabartinę GPS vietą",
  "moveSelectedFeatureToXY": "Perkelti pasirinktą elementą į XY vietą",
  "mapNavigationLocked": "Žemėlapio naršymas: užrakintas",
  "mapNavigationUnLocked": "Žemėlapio naršymas: atrakintas",
  "copyFeatures": {
    "title": "Kopijuoti elementus",
    "createFeatures": "Kurti elementus",
    "createSingleFeature": "Kurti 1 kelių dalių elementą",
    "createOneSingleFeature": "Kurti elementą",
    "noFeaturesSelectedMessage": "Pasirinktų elementų nėra",
    "selectFeatureToCopyMessage": "Pasirinkite norimus kopijuoti elementus",
    "multipleFeatureSaveWarning": "Pastaba: kuriant kelis elementus naudojantis kopijavimo galimybe visi nauji elementai bus įrašyti iš karto",
    "copyFeatureUpdateGeometryError": "Pasirinktų elementų geometrijos atnaujinti nepavyko",
    "canNotSaveMultipleFeatureWarning": "Pastaba: negalima kopijuoti kelis elementus, naudojančius tą pačią reikšmę unikalių reikšmių laukams, pasirinkite tik vieną elementą",
    "createOnlyOneMultipartFeatureWarning": "Pastaba: galima sukurti tik vieną kelių dalių elementą"
  },
  "addingFeatureError": "Sluoksnyje pridedant pasirinktus elementus įvyko klaida. Pabandykite dar kartą.",
  "addingFeatureErrorCount": "Nepavyko nukopijuoti „${copyFeatureErrorCount}“ elemento (-ų). Ar su trūkstamu (-ais) elementu (-ais) norite bandyti dar kartą?",
  "selectingFeatureError": "Sluoksnyje pasirenkant elementus įvyko klaida. Pabandykite dar kartą.",
  "customSelectOptionLabel": "Pasirinkite norimus kopijuoti elementus",
  "noFeatureSelectedMessage": "Nepasirinkti jokie elementai",
  "multipleFeatureSaveMessage": "Visi elementai bus iš karto įrašyti. Ar norite tęsti?",
  "relativeDates": {
    "dateTypeLabel": "Datos tipas",
    "valueLabel": "Reikšmė",
    "fixed": "Fiksuotas",
    "current": "Dabartinis",
    "past": "Praėjęs",
    "future": "Būsimas",
    "popupTitle": "Pasirinkite reikšmę",
    "hintForFixedDateType": "Patarimas: nurodyta data ir laikas bus naudojami kaip iš anksto nustatyta numatytoji reikšmė.",
    "hintForCurrentDateType": "Patarimas: dabartinė data ir laikas bus naudojami kaip iš anksto nustatyta numatytoji reikšmė.",
    "hintForPastDateType": "Patarimas: nurodyta data ir laikas bus atimti iš dabartinės datos ir laiko ir skirti iš anksto nustatytai numatytai reikšmei.",
    "hintForFutureDateType": "Patarimas: nurodyta data ir laikas bus pridėti prie dabartinės datos ir laiko ir skirti iš anksto nustatytai numatytai reikšmei.",
    "noDateDefinedTooltip": "Data neapibrėžta",
    "relativeDateWarning": "Kad galėtumėte įrašyti numatytąją iš anksto nustatytą reikšmę, turi būti nurodyti datos ir laiko reikšmę.",
    "customLabel": "Adaptuotas",
    "layerLabel": "Sluoksnis",
    "domainFieldHintLabel": "Pasirinkta reikšmė yra koduotos reikšmės domenas. Reikšmė: bus naudojama „${domainValue}“"
  },
  "valuePicker": {
    "popupTitle": "Pasirinkti reikšmę",
    "popupHint": "Dabartinis objektas kertasi su keliais objektais. Pasirinkite atitinkamo lauko reikšmę",
    "buttonTooltip": "Pasirinkti vertę iš kelių susikertančių objektų"
  },
  "uniqueValueErrorMessage": "Reikšmė, nurodyta „${fieldName}“, jau yra. Pateikite naują reikšmę.",
  "requiredFields": {
    "displayMsg": "Būtini laukai negali būti tušti. Žemiau pateikite reikšmes bendriems laukams.",
    "popupTittle": "Būtini laukai",
    "foundNullRecordCount": "${fieldName} (rasta ${count} įrašuose)"
  },
  "cantLocateUserLocation": "Nepavyko nustatyti jūsų padėties",
  "tryAgainButtonLabel": "Bandykite iš naujo",
  "copyFeatureFailedPopupTitle": "Oi!"
});