define({
  "taskUrl": "Görüş Alanı Servisi URL'si",
  "portalURL": "ArcGIS Online kuruluşunuzun veya Portal for ArcGIS uygulamasının URL'sini belirtin",
  "portalURLError": "ArcGIS Online kuruluşunuz veya Portal for ArcGIS için yapılandırılan uygulama geçerli değil.",
  "privilegeError": "Kullanıcı rolünüz analiz gerçekleştiremiyor. Analiz gerçekleştirmek için kuruluşunuzun yöneticisi size belirli <a href=”http://doc.arcgis.com/en/arcgis-online/reference/roles.htm” target=”_blank”>ayrıcalıklar</a> vermelidir.",
  "noServiceError": "Yükselti analizi servisi kullanılabilir değil. Lütfen ArcGIS Online kuruluşunuzu veya Portal for ArcGIS yapılandırmalarını kontrol edin.",
  "maximumRangeMessage": "Maksimum Gözlemlenebilir Aralık Minimum Gözlemlenebilir Aralıktan büyük olmalı ve ${limit} ${units} daha fazla olmamalıdır.",
  "serviceURLPlaceholder": "Lütfen Görüş Alanı Coğrafi İşlem görevi URL’sini girin",
  "setTask": "Ayarla",
  "setTaskTitle": "Görüş Alanı Coğrafi İşlem Görevini Ayarla",
  "serviceURLError": "Bu araç ile yapılandırmaya çalıştığınız Coğrafi İşlem görevi geçerli değil. Lütfen geçerli bir Görüş Alanı Coğrafi İşlem URL’si seçin",
  "defaultMilsForAnglesLabel": "Açılar için varsayılan olarak mil seç",
  "defaultObserverHeightLabel": "Varsayılan Gözlemci Yüksekliği birimi",
  "defaultObservableDistanceLabel": "Varsayılan Gözlemlenebilir Uzaklık birimi",
  "defaultObserveHeightLabel": "Varsayılan Gözlemci Yüksekliği",
  "defaultMinimumObservableDistanceLabel": "Varsayılan Minimum Gözlemlenebilir Mesafe",
  "defaultMaximumObservableDistanceLabel": "Varsayılan Maksimum Gözlemlenebilir Mesafe",
  "units": {
    "miles": "Mil",
    "kilometers": "Kilometre",
    "feet": "Fit",
    "meters": "Metre",
    "yards": "Yarda",
    "nauticalMiles": "Deniz mili"
  },
  "helpIconTooltip": "İşlem katmanı listesi, geçerli web haritasından çokgen geometrisi türünde katmanlarla doldurulur.",
  "selectOperationalLayerLabel": "Sonuçlar için bir işlem katmanı seçin",
  "lineOfSightTabTitle": "Görüş Çizgisi",
  "symbologyTabTitle": "Semboloji",
  "transparency": "Şeffaflık",
  "outline": "Ana Hat",
  "fill": "Doldur (Renk sadece stil katı olarak ayarlandığında uygulanır)",
  "style": "Stil",
  "selectOpLayerLabel": "Sonuçlar için bir işlem katmanı seçin",
  "selectDefaultMeasurementLabel": "Varsayılan ölçüm birimini seçin",
  "visibleSectionLabel": "Görünür Bölüm",
  "nonVisibleSectionLabel": "Görünür Olmayan Bölüm",
  "visibleSectionButtonLabel": "Görünür bölüm Ayarlarını yapılandır",
  "nonVisibleSectionButtonLabel": "Görünür olmayan bölüm Ayarlarını yapılandır",
  "colorPicker": "Renk Seçici",
  "lineStyles": {
    "esriSLSDash": "Tire",
    "esriSLSDashDot": "Çizgi Nokta",
    "esriSLSDashDotDot": "Çizgi Nokta Nokta",
    "esriSLSDot": "Nokta",
    "esriSLSLongDash": "Uzun Çizgi",
    "esriSLSLongDashDot": "Uzun Çizgi Nokta",
    "esriSLSNull": "Boş",
    "esriSLSShortDash": "Kısa Çizgi",
    "esriSLSShortDashDot": "Kısa Çizgi Nokta",
    "esriSLSShortDashDotDot": "Kısa Çizgi Nokta Nokta",
    "esriSLSShortDot": "Kısa Nokta",
    "esriSLSSolid": "Dolu"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Geri",
    "esriSFSCross": "Çarpı",
    "esriSFSDiagonalCross": "Diyagonal",
    "esriSFSForwardDiagonal": "İleri",
    "esriSFSHorizontal": "Yatay",
    "esriSFSNull": "Boş",
    "esriSFSSolid": "Dolu",
    "esriSFSVertical": "Dikey"
  }
});