define({
  "taskUrl": "Adres URL usługi obszaru widoczności",
  "portalURL": "Podaj adres URL instytucji w usłudze ArcGIS Online lub witryny Portal for ArcGIS",
  "portalURLError": "Skonfigurowany adres URL instytucji w usłudze ArcGIS Online lub witryny Portal for ArcGIS jest niepoprawny.",
  "privilegeError": "Twoja rola użytkownika nie umożliwia wykonania analizy. Aby możliwe było wykonanie analizy, niezbędne jest nadanie Tobie przez administratora instytucji odpowiednich <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">uprawnień</a>.",
  "noServiceError": "Usługa analizy wysokościowej jest niedostępna. Sprawdź konfigurację instytucji w usłudze ArcGIS Online lub witryny Portal for ArcGIS.",
  "serviceURLPlaceholder": "Wprowadź adres URL zadania geoprzetwarzania obszaru widoczności",
  "setTask": "Ustaw",
  "setTaskTitle": "Skonfiguruj zadanie geoprzetwarzania obszaru widoczności",
  "serviceURLError": "Zadanie geoprzetwarzania konfigurowane przy użyciu tego widżetu jest nieprawidłowe. Wybierz prawidłowy adres URL zadania geoprzetwarzania obszaru widoczności",
  "defaultMilsForAnglesLabel": "Ustaw miliradiany jako domyślną jednostkę dla kątów",
  "defaultObserverHeightLabel": "Domyślna jednostka wysokości obserwatora",
  "defaultObservableDistanceLabel": "Domyślna jednostka widocznej odległości obserwatora",
  "units": {
    "miles": "Mile",
    "kilometers": "Kilometry",
    "feet": "Stopy",
    "meters": "Metry",
    "yards": "Jardy",
    "nauticalMiles": "Mile morskie"
  },
  "helpIconTooltip": "Lista warstw operacyjnych jest zapełniana warstwami z bieżącej mapy internetowej o typie geometrii poligonowej.",
  "selectOperationalLayerLabel": "Wybierz warstwę operacyjną dla wyników",
  "lineOfSightTabTitle": "Linia widoczności",
  "symbologyTabTitle": "Symbolizacja",
  "transparency": "Przezroczystość",
  "outline": "Obrys",
  "fill": "Wypełnienie (kolor zostanie zastosowany tylko wtedy, gdy wybranym stylem jest styl pełny)",
  "style": "Nadaj styl",
  "selectOpLayerLabel": "Wybierz warstwę operacyjną dla wyników",
  "selectDefaultMeasurementLabel": "Wybierz domyślną jednostkę miary",
  "visibleSectionLabel": "Widoczna sekcja",
  "nonVisibleSectionLabel": "Niewidoczna sekcja",
  "visibleSectionButtonLabel": "Skonfiguruj ustawienia widocznej sekcji",
  "nonVisibleSectionButtonLabel": "Skonfiguruj ustawienia niewidocznej sekcji",
  "colorPicker": "Okno wyboru kolorów",
  "lineStyles": {
    "esriSLSDash": "Przerywana",
    "esriSLSDashDot": "Kreska-kropka",
    "esriSLSDashDotDot": "Kreska-kropka-kropka",
    "esriSLSDot": "Kropka",
    "esriSLSLongDash": "Długa kreska",
    "esriSLSLongDashDot": "Długa kreska-kropka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Krótka kreska",
    "esriSLSShortDashDot": "Krótka kreska-kropka",
    "esriSLSShortDashDotDot": "Krótka kreska-kropka-kropka",
    "esriSLSShortDot": "Krótka kropka",
    "esriSLSSolid": "Stały"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Cofnij",
    "esriSFSCross": "Krzyż",
    "esriSFSDiagonalCross": "Po przekątnej",
    "esriSFSForwardDiagonal": "Do przodu",
    "esriSFSHorizontal": "Poziomo",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Stały",
    "esriSFSVertical": "Pionowo"
  }
});