define({
  "_widgetLabel": "Kötegelt attribútumszerkesztés",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Réteg neve",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Nincsenek konfigurálva szerkeszthető rétegek",
  "editorPopupTitle": "Kötegelt attribútumszerkesztés",
  "editorPopupSaveBtn": "Mentés",
  "editorPopupMultipleValues": "",
  "clear": "Törlés",
  "featuresUpdated": "${0} / ${1} vektoros elem frissítve",
  "featuresSelected": "${0} vektoros elem kiválasztva",
  "featuresSkipped": "Megkerülve",
  "featuresNoPermision": "${0} vektoros elem kiválasztva, de nincs engedély a szerkesztéshez.",
  "search": "Keresés",
  "queryInput": "Adja meg a lekérdezni kívánt értéket",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Állítsa be megfelelően a szűrőt.",
  "filterPopup": "Szűrőréteg",
  "filterAppend": "Ha már létezik szűrő a webtérképen ehhez a réteghez",
  "filterAppendOR": "Bármelyik kifejezés hozzáfűzése a meglévő térképszűrőhöz",
  "filterAppendAND": "Az összes kifejezés hozzáfűzése a meglévő térképszűrőhöz",
  "cancel": "Mégse",
  "noValue": "Nincs érték",
  "emptyString": "Üres karakterlánc",
  "existingValue": "Meglévő érték megőrzése",
  "newDate": "Új dátum",
  "valueChooser": "Válasszon/írjon be egy értéket",
  "ok": "OK",
  "drawBox": {
    "point": "Pont",
    "line": "Vonal",
    "polyline": "Polyline",
    "freehandPolyline": "Szabadkézi vonallánc",
    "extent": "Kiterjedés",
    "polygon": "Polygon",
    "freehandPolygon": "Szabadkézi sokszög",
    "clear": "Törlés",
    "addPointToolTip": "Kattintson a kiválasztáshoz ezen a területen",
    "addShapeToolTip": "Alakzat rajzolása a vektoros elemek kiválasztásához",
    "freehandToolTip": "Nyomja meg és tartsa lenyomva a gombot formarajzolás gombot a vektoros elemek kiválasztásához",
    "startToolTip": "Alakzat rajzolása a vektoros elemek kiválasztásához"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "A(z) ${0} rétegről származó vektoros elem azonosítója érvénytelen",
    "noSelectedLayers": "Nincsenek olyan kiválasztott rétegek, amelyek frissíthető rekordokkal rendelkeznek",
    "inputValueError": "Érvénytelen érték az űrlapon",
    "saveError": "${0} vektoros elem mentése nem sikerült",
    "requiredValue": "Kötelező érték"
  }
});