define({
  "taskUrl": "URL attività",
  "setTask": "Imposta",
  "setTaskPopupTitle": "Imposta attività",
  "validate": "Imposta",
  "inValidGPService": "Immettere un servizio di geoprocessing valido.",
  "noOutputParameterWithGeometryType": "Il servizio di geoprocessing selezionato deve avere almeno un parametro di output con un tipo di geometria specificato. Selezionare un servizio di geoprocessing diverso.",
  "invalidOutputGeometry": "Il tipo di geometria di output del servizio di geoprocessing selezionato non è compatibile con le impostazioni del progetto. Non è possibile memorizzare i risultati del servizio di geoprocessing.",
  "GPFeatureRecordSetLayerERR": "Immettere un servizio di geoprocessing solo con input di tipo 'GPFeatureRecordSetLayer'.",
  "invalidInputParameters": "Il numero di parametri di input è inferiore a 1 o superiore a 3. Immettere un servizio di geoprocessing valido.",
  "projectSetting": {
    "title": "Impostazioni di progetto",
    "note": "Nota: le impostazioni del progetto sono opzionali, una volta che l'utente configurato è in grado di memorizzare il progetto nei layer della mappa Web desiderati con l'area di interruzione della rete e i parametri di input. L'utente può memorizzare altri parametri di output dalla scheda \"Output\".",
    "projectPolygonLayer": "Layer poligonale di progetto",
    "outputParameterName": "Nome parametro di output",
    "projectPointLayer": "Layer puntuale di progetto",
    "selectLabel": "Seleziona",
    "polygonLayerHelp": "<p>Saranno mostrati i layer poligonali con le seguenti condizioni:<br/><ul><li>Il layer deve avere funzionalità di modifica ovvero \"Crea\", \"Elimina\" e \"Aggiorna\"</li><li>Il layer deve avere 2 campi con il nome e i tipi di dati esatti:</li><ul><li>name (campo tipo stringa)</li><li>globalid (campo tipo GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Saranno mostrati i layer poligonali di output dell’URL attività<p/>",
    "pointLayerHelp": "<p>Saranno mostrati i layer poligonali con le seguenti condizioni: <br/><ul><li>Il layer deve avere funzionalità di modifica ovvero \"Crea\", \"Elimina\" e \"Aggiorna\" </li><li>Il layer deve avere 2 campi con il nome e i tipi di dati esatti:</li><ul><li>inputtype (campo tipo stringa)</li><li>projectid (GUID type field)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Flag",
    "barrier": "Barriera",
    "skip": "Ignora",
    "title": "Input",
    "inputTooltip": "Descrizione comandi",
    "typeText": "Tipo",
    "symbol": "Simbolo",
    "summaryEditorText": "Testo di riepilogo",
    "summaryTextTitle": "Fornire testo da visualizzare per la scheda di input"
  },
  "summaryTab": {
    "title": "Output",
    "summaryFieldsetText": "Impostazioni di riepilogo",
    "inputOutput": "Input/Output",
    "field": "Campo",
    "operator": "Operatore",
    "inputOperatorCountOption": "Conteggio",
    "outputOperatorCountOption": "Conteggio",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Somma",
    "fieldOperatorMinOption": "Minima",
    "fieldOperatorMaxOption": "Massima",
    "fieldOperatorMeanOption": "Medio",
    "expressionAddButtonText": "Aggiungi",
    "expressionVerifyButtonText": "Verifica",
    "summaryEditorText": "Testo di riepilogo",
    "zoomText": "Zoom automatico dopo traccia",
    "summarSettingTooltipText": "Aggiungere conteggio di input/output",
    "symbol": "Simbolo",
    "outputParametersText": "Parametri di output",
    "skipText": "Salta",
    "visibilityText": "Visibile",
    "exportToCsvText": "Esporta in CSV",
    "settitngstext": "Impostazioni",
    "saveToLayerText": "Salva come layer (opzionale)",
    "inputLabel": "Etichetta",
    "inputTooltip": "Descrizione comandi",
    "outputDisplay": "Visualizza testo",
    "addFieldTitle": "Aggiungi campo",
    "setScale": "Imposta scala",
    "enterDisplayText": "Immetti testo da mostrare",
    "saveToLayerHelp": "<p>Saranno mostrati i layer poligonali con le seguenti condizioni:<br/><ul><li>Il layer deve avere funzionalità di modifica ovvero \"Crea\", \"Elimina\" e \"Aggiorna\"</li><li>Il layer deve avere due campi con il nome e i tipi di dati esatti:</li><ul><li>parametername (campo tipo stringa)</li><li>projectid (Guid type field)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Fornire testo di riepilogo da visualizzare sulla scheda di output",
    "addSummaryItemsTitle": "Aggiungi elementi di riepilogo"
  },
  "validationErrorMessage": {
    "webMapError": "Nessun layer disponibile nella mappa Web. Selezionare una mappa Web valida.",
    "inputTypeFlagGreaterThanError": "L’input di tipo flag non può essere più di uno.",
    "inputTypeFlagLessThanError": "È necessario almeno un input del flag tipo.",
    "inputTypeBarrierErr": "L’input di tipo barriera non può essere più di uno.",
    "inputTypeSkipErr": "L’input di tipo salto non può essere più di uno.",
    "displayTextForButtonError": "Visualizza testo per il pulsante 'Esegui' on può essere vuoto.",
    "UnableToLoadGeoprocessError": "Impossibile caricare servizio di geoprocessing.",
    "invalidSummaryExpression": "Espressione non valida.",
    "validSummaryExpression": "Operazione riuscita!",
    "invalidProjectSettings": "Impostazioni di progetto non valide.<br/> Selezionare un valore valido in '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Suggerimento: fornire un'etichetta di visualizzazione per il pannello dei risultati del parametro di output.",
    "displayTextHint": "Suggerimento: verrà visualizzato nel pannello dei dettagli per questo parametro di output.",
    "inputTextHint": "Suggerimento: creare l’espressione seguente utilizzando il pulsante per l'aggiunta degli elementi di riepilogo.",
    "expressionHint": "Suggerimento: selezionare gli elementi e fare clic su Aggiungi per creare un'espressione."
  }
});