define({
  "chartTasks": "Úlohy grafu",
  "addNew": "Pridať novú",
  "addNewTip": "Pridať novú úlohu grafu",
  "name": "Meno",
  "set": "Nastaviť",
  "setDataSource": "Nastaviť zdroj údajov",
  "generalSettingsTip": "Nastaviť zdroj údajov, názov a popis pre graf",
  "chartModeSettingTip": "Vybrať spôsob analýzy a zobrazenia údajov ako grafy.",
  "detailsSettingTip": "Nastaviť vzhľad grafu určením jeho typov a farby a hodnôt, ktoré sa v ňom majú zobraziť:",
  "symbolSettingTip": "Nastaviť zobrazenie mapy pre údaje z grafu.",
  "addFilterTip": "Pridať filter pre tieto údaje",
  "dataSource": "Zdroj údajov",
  "noResults": "Nebol nájdený žiadny prvok.",
  "chartTitle": "Názov grafu",
  "description": "Popis",
  "chartingMode": "Zobrazenie grafu",
  "featureOption": "Zobrazenie hodnôt po prvkoch",
  "categoryOption": "Zobrazenie hodnôt podľa kategórie",
  "countOption": "Zobrazenie počtu prvkov podľa kategórie",
  "fieldOption": "Zobrazenie hodnôt atribútu ako graf",
  "category": "Kategória",
  "axisLabel": "Popis kategórie",
  "categoryField": "Pole kategórie",
  "operation": "Operácia",
  "originalOption": "Použiť pôvodné hodnoty",
  "sumOption": "Súčet",
  "averageOption": "Priemer",
  "minOption": "Minimum",
  "maxOption": "Maximum",
  "valueFields": "Polia hodnôt",
  "moveUp": "Posunúť hore",
  "moveDown": "Posunúť dolu",
  "sortOrder": "Zoradiť grafy podľa popisov kategórií",
  "ascending": "Vzostupne",
  "descending": "Zostupne",
  "chartType": "Typ grafu",
  "column": "Stĺpcový graf",
  "bar": "Pruhový graf",
  "line": "Čiarový graf",
  "pie": "Koláčový graf",
  "chartColor": "Farba grafu",
  "showDataLabels": "Zobraziť popisy údajov",
  "setSymbol": "Symbol výberu",
  "setHighLightColor": "Farba zvýraznenia",
  "settings": "Nastavenia",
  "mapInterationOptions": "Možnosti interakcie mapy",
  "preview": "Náhľad",
  "ok": "OK",
  "cancel": "Zrušiť",
  "close": "Zatvoriť",
  "setFilterTip": "Nastavte filter správne. ",
  "setChartTitleTip": "Nastavte názov grafu.",
  "setChartTypeTip": "Vyberte aspoň jeden typ grafu.",
  "setDataFieldTip": "Vyberte aspoň jedno pole hodnôt.",
  "setOutputFieldTip": "Nastavte polia výstupu.",
  "count": "Počet",
  "label": "Označenie",
  "horizontalAxis": "Vodorovná os",
  "verticalAxis": "Zvislá os",
  "dataLabels": "Popisy údajov",
  "color": "Farba",
  "colorful": "Farebná",
  "monochromatic": "Monochromatická",
  "noTaskTip": "Kliknite na Pridať novú na pridanie úlohy grafu",
  "info": "Informácie",
  "charts": "Grafy",
  "options": "Možnosti",
  "taskName": "Názov úlohy",
  "summary": "Súhrn",
  "resultDescription": "Popis výsledku",
  "spatialFilterTip": "Pre obmedzenie výsledkov vyberte priestorový filter/filtre použité vo widgete.",
  "defaultOption": "Predvolené",
  "useCurrentExtentTip": "Čiastočne alebo úplne v rámci aktuálneho rozsahu mapy",
  "useDrawGraphicTip": "Čiastočne alebo úplne v rámci tvaru nakresleného na mape",
  "useFeaturesTip": "Na základe ich umiestnenia vzhľadom na prvky v inej vrstve",
  "noSpatialLimitTip": "Neobmedzovať výsledky priestorovo",
  "drawingTools": "Nástroje kreslenia",
  "bufferSettings": "Nastavenia vyrovnávacej pamäte",
  "defaultDistance": "Predvolená vzdialenosť",
  "bufferDistance": "Vzdialenosť obalovej zóny",
  "defaultUnit": "Predvolená jednotka",
  "miles": "Míle",
  "kilometers": "Kilometre",
  "feet": "Stopy",
  "meters": "Metre",
  "yards": "Yardy",
  "nauticalMiles": "Námorné míle",
  "availableSpatialRelationships": "Dostupné priestorové vzťahy",
  "setSpatialRelationships": "Nastaviť priestorové vzťahy",
  "availability": "Dostupnosť",
  "relationship": "Vzťah",
  "actions": "Akcie",
  "intersect": "pretínajú",
  "contain": "obsahujú",
  "areContainedIn": "sú obsiahnuté",
  "cross": "križujú",
  "envelopeIntersect": "pretínajú obálku",
  "overlap": "prekrývajú",
  "areOverlapped": "sú prekryté",
  "touche": "dotýkajú sa",
  "within": "v rámci",
  "areWithin": "sú v rámci",
  "indexIntersect": "pretínajú index",
  "valueStr": "Hodnota",
  "sortBy": "Triediť podľa"
});