define({
  "_widgetLabel": "Editor de Atributos em Batch",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nome da Camada",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Não foram configuradas quaisquer camadas editáveis",
  "editorPopupTitle": "Editor de Atributos em Batch",
  "editorPopupSaveBtn": "Guardar",
  "editorPopupMultipleValues": "",
  "clear": "Limpar",
  "featuresUpdated": "${0} / ${1} elemento(s) atualizado(s)",
  "featuresSelected": "${0} elemento(s) selecionado(s)",
  "featuresSkipped": "Ignorados",
  "featuresNoPermision": "${0} elemento(s) selecionado(s), mas sem permissão para editar.",
  "search": "Pesquisar",
  "queryInput": "Introduza um valor para consulta",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Por favor, defina o filtro corretamente.",
  "filterPopup": "Filtrar Camada",
  "filterAppend": "Caso um filtro já exista no mapa web para esta camada",
  "filterAppendOR": "Anexar qualquer expressão a um filtro de mapa existente",
  "filterAppendAND": "Anexar todas as expressões a um filtro de mapa existente",
  "cancel": "Cancelar",
  "noValue": "Nenhum Valor",
  "emptyString": "String Vazia",
  "existingValue": "Manter Valor Existente",
  "newDate": "Nova Data",
  "valueChooser": "Seleccionar/Introduzir um Valor",
  "ok": "OK",
  "drawBox": {
    "point": "Ponto",
    "line": "Linha",
    "polyline": "Polilinha",
    "freehandPolyline": "Polilinha À Mão Livre",
    "extent": "Estender",
    "polygon": "Polígono",
    "freehandPolygon": "Polígono À Mão Livre",
    "clear": "Limpar",
    "addPointToolTip": "Clique para selecionar nesta área",
    "addShapeToolTip": "Desenhe uma forma para selecionar elementos",
    "freehandToolTip": "Mantenha pessionado para desenhar uma forma para selecionar elementos",
    "startToolTip": "Desenhe uma forma para selecionar elementos"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "O elemento de ${0} foi devolvido com uma ID inválida",
    "noSelectedLayers": "Não existem camadas selecionadas com registos para atualizar",
    "inputValueError": "Valor inválido no formulário",
    "saveError": "Não foi possível guardar ${0} elementos",
    "requiredValue": "Valor Necessário"
  }
});