define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Få adgang til infografik og rapporter, der opsummerer nøgleindikatorer og -data for ethvert område.</div><br><div>Vælg et punkt- eller polygonobjekt på kortet, søg efter en adresse eller et sted, tegn en polygon, eller placér en kortnål på kortet for at få vist nøgleindikatorer og oplysninger om området.</div>",
  "defineWhichInfographics": "Definér, hvilken infografik der er tilgængelig i widget'en:",
  "defineWhichReports": "Definér, hvilke rapporter der er tilgængelige i widget'en:",
  "defaultValues": "Standardværdier:",
  "disable": "Deaktivér",
  "drawFreehandPolygon": "Tegn frihåndspolygon",
  "drawPolygon": "Tegn polygon",
  "driveTime": "Køretid",
  "dropPin": "Sæt tegnestift",
  "dynamicHTML": "Dynamisk HTML",
  "exportOptions": "Eksportmuligheder:",
  "home": "Hjem",
  "image": "Billede",
  "infographics": "Infografik",
  "invalidValueRing": "Værdierne skal ligge inden for området 0 til 1.000.",
  "invalidValueDTWT": "Værdierne skal ligge inden for området 0 til 300.",
  "km": "km",
  "makeDefault": "Gør til standard",
  "miles": "miles",
  "minutes": "minutter",
  "options": "Indstillinger:",
  "pdf": "PDF",
  "print": "Udskriv",
  "radius": "Radius",
  "removeDefault": "Fjern standard",
  "reports": "Rapporter",
  "rings": "Ringe",
  "searchTextBox": "Søgetekstboks",
  "selectCountryOrRegion": "Vælg land/region:",
  "thisEntryIsNotValid": "Denne angivelse er ikke gyldig.",
  "time": "Tid",
  "walkTime": "Gåtid"
});