define({
  "_widgetLabel": "Анализ угроз",
  "threatAnalysisMainPageTitle": "Основано на контртеррористическом руководстве JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Входное положение",
  "interactive": "Интерактивно",
  "fromCoord": "Фиксированные координаты",
  "existingFeature": "Из существующих объектов",
  "threatAnalysisCoordInputLabel": "Местоположение угроз",
  "enterCoords": "Введите координаты",
  "threatAddPointToolTip": "Добавить местоположение угроз",
  "threatDrawPointToolTip": "Щелкните, чтобы добавить местоположение угрозы",
  "threatType": "Тип угрозы",
  "threatPlaceholder": "Начать печатать, чтобы найти угрозу",
  "mandatoryLabel": "Обязательное расстояние эвакуации",
  "safeLabel": "Безопасное расстояние эвакуации",
  "zoneTypeLabel": "Тип зоны",
  "feetLabel": "Футы",
  "metersLabel": "Метры",
  "unitsLabel": "Ед. измерения",
  "threatGraphicLayer": "Угрозы – графика",
  "settingsTitle": "Настройки",
  "mandatoryButtonLabel": "Настроить обязательное расстояние эвакуации",
  "safeButtonLabel": "Настроить убежище в параметрах местоположения",
  "style": "Стиль",
  "colorPicker": "Палитра цветов",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире – точка",
    "esriSLSDashDotDot": "Тире – точка – точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Длинное тире",
    "esriSLSLongDashDot": "Длинное тире – точка",
    "esriSLSNull": "Пустой",
    "esriSLSShortDash": "Короткое тире",
    "esriSLSShortDashDot": "Короткое тире – точка",
    "esriSLSShortDashDotDot": "Короткое тире – точка – точка",
    "esriSLSShortDot": "Короткая точка",
    "esriSLSSolid": "Сплошной"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Обратно",
    "esriSFSCross": "Перекрестный",
    "esriSFSDiagonalCross": "Диагональ",
    "esriSFSForwardDiagonal": "Прямо",
    "esriSFSHorizontal": "Горизонтально",
    "esriSFSNull": "Пустой",
    "esriSFSSolid": "Сплошной",
    "esriSFSVertical": "Вертикальная"
  },
  "resultsTitle": "Результаты",
  "publishTABtn": "Публикация",
  "layerName": "Имя опубликованного слоя",
  "invalidLayerName": "Имя слоя должно содержать только буквы, цифры и подчеркивания.",
  "missingLayerNameMessage": "Перед публикацией необходимо ввести корректное имя слоя",
  "publishingFailedLayerExists": "Публикация не удалась: У вас уже имеется сервис объектов с именем {0}. Выберите другое имя слоя.",
  "checkService": "Проверить сервис: {0}",
  "createService": "Создать сервис: {0}",
  "unableToCreate": "Невозможно создать: {0}",
  "addToDefinition": "Добавить в определение: {0}",
  "successfullyPublished": "Веб-слой опубликован успешно",
  "successfullyAppended": "Новые объекты успешно добавлены в веб-слой",
  "manageWebLayerText": "Управлять веб-слоем",
  "userRole": "Не удается создать сервис, так как у пользователя нет прав",
  "retrieveExistingLayerError": "Невозможно получить {0}. Опубликуйте с использованием другого имени слоя",
  "publishToNewLayer": "Публикация результатов в новый слой объектов",
  "layerNameExists": "Имя слоя уже существует. Используйте другое имя слоя.",
  "pipeBombLabel": "Самодельная бомба",
  "suicideBombLabel": "Бомба смертника",
  "briefcaseLabel": "Чемоданчик",
  "carLabel": "Легковой автомобиль",
  "suvVanLabel": "Газель",
  "smallDeliveryTruckLabel": "Грузовик",
  "containerWaterTruckLabel": "Контейнеровоз/цистерна",
  "semiTrailerLabel": "Полуприцеп",
  "transparencyLabel": "Прозрачность",
  "outline": "Контур",
  "fill": "Заливка (Цвет применяется, только если задан сплошной)",
  "createBtn": "Создать зоны",
  "clearBtn": "Сбросить",
  "invalidNumberMessage": "Введенное значение некорректно",
  "invalidRangeMessage": "Значение должно быть больше 0",
  "parseCoordinatesError": "Не удалось обработать координаты. Проверьте входные данные.",
  "selectDrawModeLabel": "Выбрать режим рисования",
  "selectFeatureLabel": "Выбрать объект того слоя",
  "fireBallDiameterLable": "Диаметр огненного шара",
  "lpgSafeDistanceLable": "Безопасное расстояние",
  "threatTypeCatagoryLabel": "Категория типа угрозы",
  "fireballButtonLabel": "Настроить параметры огненного шара",
  "safeDistanceButtonLabel": "Настроить параметры безопасного расстояния",
  "chemicalThreatCatagoryLabel": "Химическая",
  "lpgThreatCatagoryLabel": "Сжиженный нефтяной газ",
  "chemicalThreatLabel": "Химическая угроза",
  "lpgThreatLabel": "Угроза от сжиженного газа",
  "fireBallDiameterFieldAlias": "Диаметр огненного шара от сжиженного газа",
  "lpgSafeDistanceFieldAlias": "Безопасное расстояние от сжиженного газа",
  "smallLPGTank": "Малое хранилище сжиженного газа",
  "largeLPGTank": "Большое хранилище сжиженного газа",
  "commercialResidentialLPGTank": "Коммерческое/Частное хранилище сжиженного газа",
  "smallLPGTruck": "Малый бензовоз для сжиженного газа",
  "semiTankerLPG": "Полутанкер для сжиженного газа"
});