define({
  "layersPage": {
    "allLayers": "جميع الطبقات",
    "title": "تحديد قالب لإنشاء المعالم أو النقر على معلم بالخريطة لتحريره",
    "generalSettings": "إعدادات عامة",
    "layerSettings": "إعدادات الطبقة",
    "webmapSettingsRadioBtnLabel": "تنفيذ الإعدادات في خريطة الويب",
    "customSettingsRadioBtnLabel": "إعدادات مخصصة",
    "smartActionsTabTitle": "الإجراءات الذكية",
    "attributeActionsTabTitle": "إجراءات سمات",
    "geocoderSettingsText": "إعداد المُكوِّد الجغرافي",
    "editDescription": "إدخال نص لعرضه للوحة التحرير",
    "editDescriptionTip": "يتم عرض النص أعلى منتقى القالب، اتركه فارغًا لعدم وجود نص.",
    "promptOnSave": "يتم توجيهك لحفظ عمليات التحرير غير المحفوظة عند غلق النموذج أو تحويله إلى السجل التالي",
    "promptOnSaveTip": "يتم عرض رسالة توجيهية عندما يحتوي المعلم الحالي على عمليات تحرير غير محفوظة. (يتم حفظ نسخ المعالم المتعددة تلقائيًا.)",
    "promptOnDelete": "يتطلب تأكيدًا عند حذف سجل",
    "promptOnDeleteTip": "عرض طلب عندما ينقر المستخدم على حذف لتأكيد الإجراء.",
    "removeOnSave": "إزالة معلم من التحديد عند الحفظ",
    "removeOnSaveTip": "هو خيار لإزالة المعلم من مجموعة التحديد عند حفظ السجل. وإذا كان عبارة عن السجل المحدد فقط، فإن اللوحة تعود إلى صفحة القالب.",
    "useFilterEditor": "استخدم عامل تصفية قالب المعلم",
    "useFilterEditorTip": "خيار لاستخدام منقى قالب التصفية الذي يوفر القدرة على عرض أحد قوالب الطبقة أو البحث عن القوالب باستخدام الاسم.",
    "groupFilteredTemplates": "نتائج بحث المجموعة",
    "groupFilteredTemplatesTip": "خيار تجميع نتائج البحث حسب الطبقة.",
    "displayShapeSelector": "إظهار خيارات الرسم",
    "createNewFeaturesFromExisting": "السماح للمستخدم بإنشاء معالم جديدة من المعالم الحالية",
    "createNewFeaturesFromExistingTip": "خيار يتيح للمستخدم نسخ المعلم الحالي لإنشاء معالم جديدة",
    "copiedFeaturesOverrideDefaults": "تحل قيم المعالم المنسوخة محل القيم الافتراضية",
    "copiedFeaturesOverrideDefaultsTip": "ستحل قيم المعالم المنسوخة محل قيم القالب الافتراضية وذلك للحقول المتطابقة فقط",
    "displayShapeSelectorTip": "خيار عرض قائمة من خيارات الرسم الصحيحة للقالب المحدد.",
    "displayPresetTop": "عرض قائمة قيم معينة مسبقًا في المقدمة",
    "displayPresetTopTip": "خيار عرض قائمة القيم المعينة مُسبقًا أعلى أداة اختيار القالب.",
    "listenToGroupFilter": "تطبيق قيم التصفية من عنصر واجهة استخدام \"عامل تصفية المجموعة\" على الحقول المُعدة مُسبقًا",
    "listenToGroupFilterTip": "عند تطبيق عامل التصفية في عنصر واجهة استخدام \"عامل تصفية المجموعة\"، قم بتطبيق القيمة على الحقل المطابق في قائمة القيمة المُعدة مُسبقًا.",
    "keepTemplateActive": "اجعل القالب المحدد نشطًا",
    "editLayerAddedFromAddData": "السماح بتحرير الطبقات المضافة من عنصر واجهة المستخدم \"إضافة بيانات\"",
    "editLayerAddedFromAddDataTip": "يمكن تحرير الطبقات القابلة للتحرير المضافة إلى التطبيق باستخدام أداة إضافة بيانات",
    "keepTemplateActiveTip": "عند إظهار منتقى القالب، وإذا تم تحديد القالب مُسبقًا، قم بإعادة تحديده مرة أخرى.",
    "geometryEditDefault": "تمكين تحرير الشكل الهندسي افتراضيًا",
    "autoSaveEdits": "حفظ المعالم الجديدة تلقائيًا",
    "enableAttributeUpdates": "إظهار زر تحديث إجراءات السمات",
    "enableAutomaticAttributeUpdates": "استدعاء إجراء السمات تلقائيًا بعد تحديث الشكل الهندسي",
    "enableLockingMapNavigation": "تمكين قفل تنقل الخريطة",
    "enableMovingSelectedFeatureToGPS": "تمكين تحريك معلم النقطة المحدد إلى موقع GPS",
    "enableMovingSelectedFeatureToXY": "تمكين تحريك معلم النقطة المحدد إلى موقع XY",
    "featureTemplateLegendLabel": "قالب المعلم وإعداد قيمة التصفية",
    "saveSettingsLegendLabel": "حفظ الإعدادات",
    "geometrySettingsLegendLabel": "إعدادات الشكل الهندسي",
    "actionsSettingsLegendLabel": "إجراءات الإعدادات",
    "buttonPositionsLabel": "موضع أزرار \"حفظ\" و\"حذف\" و\"رجوع\" و\"إلغاء\"",
    "belowEditLabel": "نموذج التحرير أدناه",
    "aboveEditLabel": "نموذج التحرير أعلاه",
    "switchToMultilineInput": "التبديل إلى الإدخال متعدد الخطوط عند تجاوز طول الحقل",
    "enableValuePicker": "تمكين أداة انتقاء قيمة التقاطع",
    "enableValuePickerHint": "عرض طلب عند توافر قيم متعددة لحقل ما باستخدام إجراء سمات التقاطع",
    "expandRelatedTable": "توسيع كل الجداول/الطبقات ذات الصلة عند التحميل",
    "expandMainTable": "توسيع كل الطبقات الأصلية عند التحميل",
    "layerSettingsTable": {
      "allowDelete": "السماح بالحذف",
      "allowDeleteTip": "إتاحة الحذف - خيار يتيح للمستخدم حذف معلم؛ يتم تعطيله إذا كانت الطبقة لا تدعم الحذف.",
      "edit": "يمكن تحريره",
      "editTip": "قابلية التحرير - خيار لتضمين الطبقة في عنصر واجهة المستخدم",
      "label": "الطبقة",
      "labelTip": "الطبقة - اسم الطبقة كما هو محدد في الخريطة",
      "update": "تعطيل تحرير الشكل الهندسي",
      "updateTip": "تعطيل تحرير الهندسة - خيار لتعطيل القدرة على نقل الشكل الهندسي عند وضعه أو نقل الشكل الهندسية على معلم موجود",
      "allowUpdateOnly": "تحديث فقط",
      "allowUpdateOnlyTip": "التحدث فقط - خيار للسماح فقط بتعديل المعالم الحالية، والتحقق منها افتراضيًا، وتعطيلها إذا كانت الطبقة لا تدعم عملية إنشاء معالم جديدة",
      "fieldsTip": "تعديل الحقول ليتم تحريرها وتعريف البيانات الجدولية الذكية",
      "actionsTip": "الإجراءات - خيارات تحرير الحقول أو الوصول إلى الجداول/الطبقات ذات الصلة",
      "description": "الوصف",
      "descriptionTip": "الوصف - خيار لإدخال نص لعرضه أعلى صفحة السمة.",
      "relationTip": "عرض الطبقات والجداول ذات الصلة"
    },
    "editFieldError": "لم تتوفر خاصية تعديلات الحقل والبيانات الجدولية الذكية للطبقات التي لا يمكن تحريرها",
    "noConfigedLayersError": "يتطلب المحرر الذكي طبقة واحدة أو مزيد من الطبقات القابلة للتحرير",
    "toleranceErrorMsg": "قيمة سماحية تقاطع افتراضية غير صالحة",
    "pixelsToleranecErrorMsg": "قيمة سماحية بكسل افتراضية غير صالحة",
    "invalidMaxCharacterErrorMsg": "قيمة غير صالحة عند التبديل إلى الإدخال متعدد الخطوط",
    "featuresSelectionTolerance": "تعيين سماحية اختيار المعلم (وحدات بكسل)",
    "featuresSelectionToleranceTooltip": "يتيح للمستخدمين فتح لوحة تحرير البيانات الجدولية بسهولة من خلال النقر فوق المعلم",
    "featuresSelectionToleranceErrorMsg": "قيمة سماحية تحديد المعلم غير صالحة",
    "autoSaveAttrUpdates": "حفظ تحديثات السمات تلقائيًا"
  },
  "editDescriptionPage": {
    "title": "نص النظرة العامة على تعريف البيانات الجدولية الخاص بـ <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "تكوين الحقول لـ <b>${layername}</b>",
    "copyActionTip": "إجراءات جدول البيانات",
    "editActionTip": "الإجراءات الذكية",
    "description": "استخدم زر تحرير الإجراءات لتنشيط جداول البيانات الذكية في الطبقة، وقد تتطلب جداول بيانات الطبقة الحقل أو تقوم بإخفاؤه أو تعطيله بناءً على القيم في الحقول الأخرى. استخدم زر نسخ الإجراءات لتنشيط وتحديد مصدر قيمة الحقل بواسطة التقاطع والعنوان والإحداثيات والتعيين المسبق.",
    "fieldsNotes": "* تعتبر حقل إلزامي. إذا قمت بإلغاء تحديد العرض لهذا الحقل وأن قالب التحرير لا يقوم بتعبئة قيمة الحقل، فلن تكون قادرًا على حفظ سجل جديد.",
    "smartAttachmentText": "تكوين إجراءات ذكية للمرفقات",
    "smartAttachmentPopupTitle": "تكوين مرفقات ذكية للمرفقات في <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "يرجى تحديد حقل عرض واحد على الأقل للطبقة ${layerName}",
    "fieldsSettingsTable": {
      "display": "العرض",
      "displayTip": "عرض - تحديد ما إذا يكون الحقل مرئي أم لا",
      "edit": "يمكن تحريره",
      "editTip": "قابلية التحرير - التحقق مما إذا كان الحقل موجود في نموذج سمة أم لا",
      "fieldName": "الاسم",
      "fieldNameTip": "الاسم - اسم الحقل المعرف في قاعدة البيانات",
      "fieldAlias": "الاسم المستعار",
      "fieldAliasTip": "الاسم المستعار - اسم الحقل المحدد في الخريطة",
      "canPresetValue": "تعيين مسبق",
      "canPresetValueTip": "التعيين المسبق - خيار لإظهار الحقل في قائمة الحقل التي تم تعيينها مُسبقًا والسماح للمستخدم بتعيين القيمة قبل عملية التحرير",
      "actions": "إجراءات",
      "actionsTip": "الإجراءات - تغيير ترتيب الحقول أو إعداد السمات الذكية"
    },
    "smartAttSupport": "لا تدعم البيانات الجدولية الذكية حقول قاعدة البيانات المطلوبة"
  },
  "actionPage": {
    "title": "تكوين إجراءات جدول البيانات لـ <b>${fieldname}</b>",
    "smartActionTitle": "تكوين الإجراءات الذكية لـ <b>${fieldname}</b>",
    "description": "دائمًا ما تكون الإجراءات غير مُفعلة مالم تحدد المعيار الذي يتم تشغيله عليها. تتم معالجة الإجراءات في ترتيب وسيتم تشغيل إجراء واحد فقط لكل حقل. ويمكنك استخدام زر تحرير المعيار لتحديد المعيار.",
    "copyAttributesNote": "سيكون تعطيل أي إجراء باسم مجموعة مثل تحرير هذا الإجراء على نحو مستقل، وسيزيل الإجراء لهذا الحقل من المجموعة المعنية.",
    "searchPlaceHolder": "بحث",
    "expandAllLabel": "توسيع كل الطبقات",
    "selectAllLabel": "تحديد كل الحقول",
    "domainListTitle": "حقول المجالات",
    "noValidFieldTypeMsg": "لا توجد أي طبقة مناسبة متوفرة في الخريطة لنوع البيانات هذا",
    "actionsSettingsTable": {
      "rule": "إجراء",
      "ruleTip": "الإجراء - الإجراء الذي تم تنفيذه عند استيفاء المعيار",
      "expression": "تعبير",
      "expressionTip": "التعبير - التعبير الناتج في تنسيق SQL من المعيار المحدد",
      "groupName": "اسم المجموعة",
      "groupNameTip": "اسم المجموعة - يعرض اسم المجموعة الذي تم منه تطبق التعبير",
      "actions": "معيار",
      "actionsTip": "المعايير - تغيير ترتيب القاعدة وتحديد المعيار عند تشغيله"
    },
    "copyAction": {
      "description": "تتم معالجة مصدر قيمة الحقل بالترتيب إذا تم تنشيطه حتى يتم تشغيل معيار صحيح أو اكتمال القائمة. استخدم زر \"تحرير المعيار\" لتحديد المعيار.",
      "intersection": "تقاطع",
      "coordinates": "إحداثيات",
      "address": "عنوان",
      "preset": "تعيين مُسبق",
      "actionText": "إجراءات",
      "criteriaText": "معيار",
      "enableText": "تم التمكين"
    },
    "actions": {
      "hide": "إخفاء",
      "required": "مطلوب",
      "disabled": "معطل"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "تحذير: سيزيل التحرير المستقل إجراء السمة المحدد المصاحب لهذا الحقل من المجموعة",
      "editGroupHint": "تحذير: سيزيل التحرير المستقل الإجراء الذكي المحدد المصاحب لهذا الحقل من المجموعة",
      "popupTitle": "اختر خيار التحرير",
      "editAttributeGroup": "يتم تحديد إجراء السمة المحدد من المجموعة. اختر أحد الخيارات التالية لتحرير إجراء السمة:",
      "expression": "يتم تحديد تعبير الإجراء الكي المحدد من المجموعة. اختر أحد الخيارات التالية لتحرير تعبير الإجراء الذكي:",
      "editGroupButton": "تحرير المجموعة",
      "editIndependentlyButton": "التحرير بشكل مستقل"
    }
  },
  "filterPage": {
    "submitHidden": "إرسال بيانات السمات للحقول حتى عند الإخفاء",
    "title": "عبارة التكوين الخاصة بقاعدة ${action}",
    "filterBuilder": "قم بتعيين إجراء على الحقل عند مطابقة السجل ${any_or_all} للتعبيرات التالية",
    "noFilterTip": "باستخدام الأدوات أعلاه، حدد العبارة عندما يكون الإجراء نشطًا."
  },
  "geocoderPage": {
    "setGeocoderURL": "تحديد عنوان URL للمكود الجغرافي",
    "hintMsg": "ملحوظة: أنت تقوم بتغيير خدمة المُكوِّد الجغرافي، يرجى التأكد من تحدي أي عمليات تخطيط لحقل المكود الجغرافي الذي قمت بتكوينه.",
    "invalidUrlTip": "عنوان URL لـ ${URL} غير صحيح أو لا يمكن الوصول إليه."
  },
  "addressPage": {
    "popupTitle": "عنوان",
    "checkboxLabel": "الحصول على قيمة من المكود الجغرافي",
    "selectFieldTitle": "جدول البيانات",
    "geocoderHint": "لتغيير المكود الجغرافي، انتقل إلى زر 'إعدادات المكود الجغرافي' في الإعدادات العامة.",
    "prevConfigruedFieldChangedMsg": "لم يتم العثور على السمة المكونة سابقًا في إعدادات المكود الجغرافي. تم تعيين سمة على الإعدادات الافتراضية.",
    "questionMark": "؟",
    "consumesCredits": "تستهلك هذه الأداة بيانات الاعتماد عند استخدام خدمة التكويد الجغرافي ArcGIS Online World."
  },
  "coordinatesPage": {
    "popupTitle": "إحداثيات",
    "checkboxLabel": "الحصول على الإحداثيات",
    "coordinatesSelectTitle": "نظام المرجع",
    "coordinatesAttributeTitle": "جدول البيانات",
    "mapSpatialReferenceOptionLabel": "الإسناد المكاني للخريطة",
    "latLongOptionLabel": "دائرة العرض/خط الطول",
    "MGRS": "MGRS",
    "allGroupsCreatedMsg": "جميع المجموعات الممكنة تم إنشاؤها بالفعل",
    "coordinatesSourceTitle": "مصدر الإحداثيات",
    "featureLocation": "موقع المعلم",
    "myLocation": "موقعي",
    "LatLong": {
      "y": "خط عرض",
      "x": "خط طول",
      "xy": "خط الطول، ودائرة العرض",
      "yx": "دائرة العرض وخط الطول"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "تعيين مُسبق",
    "checkboxLabel": "سيتم تعيين الحقل مُسبقًا",
    "showOnlyDomainFields": "عرض كل حقول النطاق",
    "hideInPresetDisplay": "إخفاء عرض قيمة الإعداد المسبق",
    "presetValueLabel": "القيمة الحالية المعينة مسبقًا هي:",
    "changePresetValueHint": "لتغيير هذه القيمة التي تم تعيينها مسبقًا، انتقل إلى زر 'تحديد القيم المعينة مُسبقًا' في الإعدادات العامة"
  },
  "intersectionPage": {
    "groupNameLabel": "اسم المجموعة",
    "dataTypeLabel": "نوع البيانات",
    "ignoreLayerRankingCheckboxLabel": "تجاهل ترتيب الطبقة والعثور على أقرب معالم عبر جميع الطبقات المحددة",
    "intersectingLayersLabel": "طبقات لاستخراج قيمة",
    "layerAndFieldsApplyLabel": "طبقات وحقول لتطبيق القيمة المستخرجة",
    "checkboxLabel": "الحصول على قيمة من حقل طبقة التقاطع",
    "layerText": "الطبقات",
    "fieldText": "حقول",
    "actionsText": "إجراءات",
    "toleranceSettingText": "إعدادات التسامح",
    "addLayerLinkText": "إضافة طبقة",
    "useDefaultToleranceText": "استخدام التسامح الافتراضي",
    "toleranceValueText": "قيمة السماحية",
    "toleranceUnitText": "وحدة التسامح",
    "pixelsUnitText": "البكسل",
    "useLayerName": "- استخدام اسم الطبقة -",
    "noLayersMessage": "لم يتم العثور على حقل في طبقات الخريطة يتطابق مع نوع البيانات المحددة.",
    "intersectionLayerHint": "تم تحديد ترتيب الطبقة بترتيب تنازلي. استخدم الأسهم أسفل الإجراءات لإعادة ترتيب الطبقات وتغيير أولوية التقاطع."
  },
  "presetAll": {
    "popupTitle": "تحديد القيم الافتراضية المعينة مسبقًا",
    "deleteTitle": "حذف قيمة معينة مسبقًا",
    "hintMsg": "جميع أسماء الحقول الفريدة المحددة مسبقًا مدرجة هنا. ستؤدي إزالة حقل محدد مسبقًا إلى تعطيل الحقل ذي الصلة كإعداد مسبق من جميع الطبقات/الجداول."
  },
  "intersectionTolerance": {
    "intersectionTitle": "سماحية التقاطع الافتراضية لكل المعالم",
    "pixelsToleranceTitle": "سماحية التقاطع الافتراضية لكل المعالم (قيمة البكسل) المراد تطبيقها لمعالم النقطة فقط"
  },
  "smartActionsPage": {
    "smartActionLabel": "تكوين الإجراء الذكي",
    "addNewSmartActionLinkText": "إضافة جديد",
    "definedActions": "الإجراءات المحددة",
    "priorityPopupTitle": "تعيين أولية الإجراءات الذكية",
    "priorityPopupColumnTitle": "الإجراءات الذكية",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "اسم المجموعة",
    "layerForExpressionLabel": "طبقة التعبير",
    "layerForExpressionNote": "ملحوظة: تُستخدم حقول هذه الطبقة لتحديد معايير التعبير. تعرض 'الطبقات والحقول المراد التطبيق عليها' الطبقات والجداول التي تحتوي على حقل (حقول) محددة في التعبير فقط.",
    "expressionText": "تعبير",
    "editExpressionLabel": "تحرير التعبير",
    "layerAndFieldsApplyLabel": "طبقات وحقول للتطبيق",
    "submitAttributeText": "إرسال بيانات السمات للحقول حتى عند الإخفاء",
    "priorityColumnText": "الأولوية",
    "requiredGroupNameMsg": "يتطلب وجود هذه القيمة",
    "uniqueGroupNameMsg": "أدخل اسم مجموعة فريد، حيث إن اسم هذه المجموعة موجود بالفعل.",
    "deleteGroupPopupTitle": "حذف مجموعة الإجراءات الذكية",
    "deleteGroupPopupMsg": "سيؤدي حذف المجموعة إلى إجراء إزالة التعبير من جميع الحقول المصاحبة.",
    "invalidExpression": "لا يمكن ترك التعبير فارغًا.",
    "warningMsgOnLayerChange": "سيتم إزالة التعبير المحدد والحقول التي ينطبق عليها.",
    "smartActionsTable": {
      "name": "الاسم",
      "expression": "تعبير",
      "definedFor": "محدد لأجل"
    }
  },
  "attributeActionsPage": {
    "name": "الاسم",
    "type": "النوع",
    "deleteGroupPopupTitle": "حذف مجموعة إجراءات السمة",
    "deleteGroupPopupMsg": "سيؤدي حذف المجموعة إلى إزالة إجراء السمة من جميع الحقول المقترنة.",
    "alreadyAppliedActionMsg": "تم تطبيق إجراء ${action} في هذا الحقل في المجموعة",
    "alreadyAppliedActionLayerMsg": "تم تطبيق إجراء ${action} في هذا الحقل من إعدادات الطبقة",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "لا يوجد في هذه المجموعة أي حقول ذات صلة.",
    "presetNoFieldWarningMsg": "يرجى تكوين حقل واحد على الأقل للمجموعة المعينة مسبقًا: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "حقل",
    "valueLabel": "قيمة",
    "selectValueLabel": "تحديد قيمة",
    "domainFieldHintLabel": "القيمة المحددة هي مجال قيمة مرمزة. القيمة: سيتم استخدام ${domainValue}"
  },
  "presetPopup": {
    "presetValueLAbel": "قيمة معينة مُسبقًا"
  },
  "dataType": {
    "esriFieldTypeString": "السلسلة",
    "esriFieldTypeInteger": "عدد",
    "esriFieldTypeDate": "التاريخ",
    "esriFieldTypeGUID": "معرف فريد عالمي"
  },
  "relativeDates": {
    "dateTypeLabel": "نوع التاريخ",
    "valueLabel": "قيمة",
    "fixed": "ثابت",
    "current": "حالي",
    "past": "ماضي",
    "future": "مستقبل",
    "popupTitle": "تحديد قيمة",
    "hintForFixedDateType": "تلميح: سيُستخدم التاريخ والوقت المحددين كقيمة إعداد مسبق افتراضية",
    "hintForCurrentDateType": "تلميح: سيُستخدم التاريخ والوقت الحاليين كقيمة إعداد مسبق افتراضية",
    "hintForPastDateType": "تلميح: ستطرح القيمة المحددة من التاريخ والوقت الحاليين للقيمة الافتراضية للإعداد المسبق.",
    "hintForFutureDateType": "تلميح: ستضاف القيمة المحددة إلى التاريخ والوقت الحاليين للقيمة الافتراضية للإعداد المسبق.",
    "noDateDefinedTooltip": "لا توجد بيانات محددة",
    "relativeDateWarning": "يجب تحديد قيمة للتاريخ أو الوقت لتتمكن من حفظ القيمة الافتراضية المحددة مسبقًا.",
    "customLabel": "تخصيص"
  },
  "relativeDomains": {
    "fieldSetTitle": "قائمة",
    "valueText": "قيمة",
    "defaultText": "الوضع الافتراضي",
    "selectedDomainFieldsHint": "حقول المجال المحددة: ${domainFields}",
    "selectDefaultDomainMsg": "يرجى تحديد نطاق قيمة افتراضية أو التأكد من تأشير خانة اختيار النطاق الافتراضي"
  }
});