define({
  root: ({
    _widgetLabel: "Smart Editor",
    _featureAction_SmartEditor: "Smart Editor",
    noEditPrivileges: "Your account does not have permission to create or modify data.",
    loginPopupTitle: "Sign In",
    loginPopupMessage: "${widgetName} requires permissions and credits to look up and store address information. Would you like to sign in and use this capability?",
    noCreditsOrPrivilegeWarningMessage: "Your account does not have the permissions and credits to look up and store address information with ${widgetName}. Please contact your organization administrator to request permissions and credits. Click OK to continue editing.",
    unableToUseLocator: "Locator is not accessible. The address attribute action(s) will not be performed. Click OK to continue editing.",
    locatorDisabledWaning: "Locator is not enabled. Please contact your organization administrator to request this capability. Click OK to continue editing.",
    noFeatureInAIWarning: "No feature(s) selected. Please select a feature to perform edits or click cancel to return to the main screen.",
    noEditableLayerWarning: "Your account does not have permission to create or modify data, or this web map does not contain any editable layers.",
    noVisibleCreateLayerWarning: "Layer(s) not visible at the current zoom level. Zoom in or out to create/modify features.",
    noVisibleUpdateLayerWarning:"Layer(s) not visible at the current zoom level. Zoom in or out to modify features.",
    checkLayerVisibilityInWebMapWarning: "Make sure layers are visible in the map to create or modify features.",
    showSelectionInAITitle: "Selected Features",
    showSelectionInAIMsg: "Do you want to load the current selection in ${widgetName}?",
    widgetActive: "Active",
    widgetNotActive: "Not Active",
    pressStr: "Press ",
    ctrlStr: " CTRL ",
    snapStr: " to enable snapping",
    noAvailableTempaltes: "No available templates",
    editorCache: " - Editor Cache",
    presetFieldAlias: "Field",
    presetValue: "Preset Value",
    usePresetValues: " Use preset values (new features only)",
    editGeometry: " Edit Geometry",
    savePromptTitle: "Save feature",
    savePrompt: "Would you like to save the current feature?",
    deletePromptTitle: "Delete feature",
    deleteAttachment: "Delete attachment",
    deletePrompt: "Are you sure you want to delete the selected feature?",
    attachmentLoadingError: "Error uploading attachments",
    attachmentSaveDeleteWarning: "Warning: Changes to attachments are saved automatically",
    autoSaveEdits: "Save new features automatically",
    addNewFeature: "Create new feature",
    featureCreationFailedMsg: "Cannot create a new record/feature",
    relatedItemTitle: "Related Table/Layer",
    relatedFeatureCount: "${layerTitle} with ${featureCount} features",
    createNewFeatureLabel:"Create new feature for ${layerTitle}",
    invalidRelationShipMsg: "Please make sure the primary key field: \'${parentKeyField}\' has a valid value",
    pendingFeatureSaveMsg: "Please save the feature edits before creating a related feature.",
    attachmentsRequiredMsg: "(*) Attachments are required.",
    coordinatePopupTitle : "Move feature to XY location",
    coordinatesSelectTitle : "Coordinate System:",
    mapSpecialReferenceDropdownOption : "Map Spatial Reference",
    latLongDropdownOption : "Latitude/Longitude",
    mgrsDropdownOption: "Military Grid Reference System (MGRS)",
    mgrsTextBoxLabel: "Coordinate:",
    xAttributeTextBoxLabel :"X-coordinate:",
    yAttributeTextBoxLabel :"Y-coordinate:",
    latitudeTextBoxLabel : "Latitude:",
    longitudeTextBoxLabel : "Longitude:",
    presetGroupFieldsLabel: "'${groupName}' will be applied to the following layer fields:",
    presetGroupNoFieldsLabel: "'${groupName}' does not have any associated fields",
    groupInfoLabel: "Group information for '${groupName}'",
    editGroupInfoIcon: "Edit group value for ${groupName}",
    filterEditor:{
      all: "All",
      noAvailableTempaltes: "No available templates",
      searchTemplates: "Search Templates",
      filterLayerLabel: "Filter layers"
    },
    invalidConfiguration: "Widget is either not configured or the layers in the configuration are no longer in the map.  Please open the app in the builder mode and reconfigure the widget.",
    geometryServiceURLNotFoundMSG: "Unable to get Geometry Service URL",
    clearSelection: "Close",
    refreshAttributes: "Update dynamic feature attributes", // displayed as a tooltip on refresh attribute button
    automaticAttributeUpdatesOn: "Auto update feature attributes: ON", // displayed as a tooltip on automatic attribute update on button
    automaticAttributeUpdatesOff: "Auto update feature attributes: OFF", // displayed as a tooltip on automatic attribute update off button
    moveSelectedFeatureToGPS: "Move selected feature to current GPS location", // displayed as a tooltip on current locate button
    moveSelectedFeatureToXY: "Move selected feature to XY location", // displayed as a tooltip on xy coordinate button
    mapNavigationLocked: "Map Navigation: Locked", // displayed as a tooltip on map navigation locked button
    mapNavigationUnLocked: "Map Navigation: Unlocked", // displayed as a tooltip on map navigation unlocked button
    copyFeatures: {
      title: "Select features to copy",
      createFeatures: "Create Features",
      createSingleFeature: "Create 1 Multi-Part Feature",
      createOneSingleFeature: "Create Feature",
      noFeaturesSelectedMessage: "No Features Selected",
      selectFeatureToCopyMessage: "Please select features to copy",
      multipleFeatureSaveWarning: "Creating multiple features using this functionality will save all the new features immediately. Field matching is not supported when creating a new multi-part feature.",
      copyFeatureUpdateGeometryError: "Unable to update geometry of selected features",
      canNotSaveMultipleFeatureWarning: "You can only copy one feature when the target point layer has unique value fields.",
      createOnlyOneMultipartFeatureWarning: "You can only copy one feature or create one multi-part feature when the target layer has unique value fields.",
      layerLabel: "${layerName} (${selectedFeatures}/${totalFeatures})",
      layerAriaLabel: "${layerName} ${selectedFeatures} of ${totalFeatures} features selected"
    },
    addingFeatureError: "Error while adding selected features in the layer. Please try again.", // error message while adding features
    addingFeatureErrorCount: "\'${copyFeatureErrorCount}\' feature(s) failed to be copied. Would you like to try again for the missing feature(s)?",
    selectingFeatureError: "Error while selecting features in the layer. Please try again.", // error message while selecting features
    customSelectOptionLabel: "Select features to copy", // displayed as a label for custom select tool
    copyFeaturesWithPolygon: "Copy by polygon",
    copyFeaturesWithRect: "Copy by rectangle",
    copyFeaturesWithLasso: "Copy by lasso",
    noFeatureSelectedMessage: "No features selected", // Displayed when no features are selected while using custom select tool
    multipleFeatureSaveMessage: "All the features will be saved immediately. Would you like to proceed?",
    relativeDates: {
      dateTypeLabel: "Date Type",
      valueLabel: "Value",
      fixed: "Fixed",
      current: "Current",
      past: "Past",
      future: "Future",
      popupTitle : "Select Value",
      hintForFixedDateType: "Hint: Specified date and time will be used as preset default value.",
      hintForCurrentDateType: "Hint: Current date and time will be used as preset default value.",
      hintForPastDateType: "Hint: The specified value will be subtracted from the current date and time for the default value of the preset.",
      hintForFutureDateType: "Hint: The specified value will be added to the current date and time for the default value of the preset.",
      noDateDefinedTooltip: "No date defined",
      relativeDateWarning: "A value for date or time must be specified to be able to save the default preset value.",
      customLabel: "Custom",
      layerLabel: "Layer",
      domainFieldHintLabel: "The selected value is a coded value domain. The value: \"${domainValue}\" will be used"
    },
    valuePicker: {
      popupTitle: "Select Value",
      popupHint: "Current feature is intersecting with multiple features, choose value for respective field",
      buttonTooltip: "Select value from multiple intersecting features"
    },
    uniqueValueErrorMessage: "The value in \"${fieldName}\" already exists, please provide a new value.",
    requiredFields: {
      displayMsg :"Required fields cannot be blank. Provide values for common fields below.",
      popupTittle: "Required fields",
      foundNullRecordCount: "${fieldName} (Found in ${count} records)"
    },
    fieldsMapping: {
      popupTittle: "Apply Field Matching",
      fieldsMatchingCheckboxLabel: "Value(s) from copied feature(s) override default value(s) in target field(s)",
      resetLabel: "Reset",
      clearLabel: "Clear",
      fieldsInTargetLayerLabel: "Target",
      fieldsInSourceLayerLabel: "Source",
      targetFieldsMatchedLabel: "${layerName} (${matchedFields}/${totalFields} fields matched)",
      selectSourceFieldLabel: "- Select -",
      selectFieldAriaLabel: "Select source field for target field ${targetField}",
      informativeText: "Review the fields matching from source to target and customize if needed.",
      dynamicValueText: "A dynamic value is set",
      noFieldsToMatchLabel: "No fields to match"
    },
    cantLocateUserLocation : "Your location could not be determined",
    tryAgainButtonLabel : "Try again",
    copyFeatureFailedPopupTitle: "Oops!"
  }),
  "ar": 1,
  "bg": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
