define({
  "taskUrl": "视域服务 URL",
  "portalURL": "指定 ArcGIS Online 组织或 Portal for ArcGIS 的 URL",
  "portalURLError": "ArcGIS Online 组织或 Portal for ArcGIS 配置的 URL 无效。",
  "privilegeError": "您的用户角色无法执行分析。 要执行分析，组织管理员需要授予您特定<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">权限</a>。",
  "noServiceError": "高程分析服务不可用。 请检查 ArcGIS Online 组织或 Portal for ArcGIS 配置。",
  "serviceURLPlaceholder": "请输入视域地理处理任务 URL",
  "setTask": "设置",
  "setTaskTitle": "设置视域地理处理任务",
  "serviceURLError": "您正在尝试使用此微件配置的地理处理任务无效。请选择有效的视域地理处理任务 URL",
  "defaultMilsForAnglesLabel": "默认情况下，将角度设置为以密耳为单位",
  "defaultObserverHeightLabel": "默认观察者高度单位",
  "defaultObservableDistanceLabel": "默认观测距离单位",
  "units": {
    "miles": "英里",
    "kilometers": "千米",
    "feet": "英尺",
    "meters": "米",
    "yards": "码",
    "nauticalMiles": "海里"
  },
  "helpIconTooltip": "使用当前 web 地图中面几何类型的图层来填充业务图层列表。",
  "selectOperationalLayerLabel": "选择结果的业务图层",
  "lineOfSightTabTitle": "通视分析",
  "symbologyTabTitle": "符号系统",
  "transparency": "透明度",
  "outline": "轮廓",
  "fill": "填充(仅在将样式设置为单色时应用颜色)",
  "style": "样式",
  "selectOpLayerLabel": "选择结果的业务图层",
  "selectDefaultMeasurementLabel": "选择默认测量单位。",
  "visibleSectionLabel": "可见部分",
  "nonVisibleSectionLabel": "不可见部分",
  "visibleSectionButtonLabel": "配置可见部分设置",
  "nonVisibleSectionButtonLabel": "配置不可见部分设置",
  "colorPicker": "颜色选取器",
  "lineStyles": {
    "esriSLSDash": "虚线",
    "esriSLSDashDot": "点划线",
    "esriSLSDashDotDot": "双点划线",
    "esriSLSDot": "点",
    "esriSLSLongDash": "长划线",
    "esriSLSLongDashDot": "长点划线",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "短虚线",
    "esriSLSShortDashDot": "短点划线",
    "esriSLSShortDashDotDot": "短双点划线",
    "esriSLSShortDot": "短点线",
    "esriSLSSolid": "实线"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "后退",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "对角线",
    "esriSFSForwardDiagonal": "前进",
    "esriSFSHorizontal": "水平对齐",
    "esriSFSNull": "Null",
    "esriSFSSolid": "实线",
    "esriSFSVertical": "垂直对齐"
  }
});