define({
  "_widgetLabel": "Uhka-analyysi",
  "threatAnalysisMainPageTitle": "Perustuu JCAT Counterterrorism Guide -oppaaseen",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Lähtösijainti",
  "interactive": "Vuorovaikutteinen",
  "fromCoord": "Kiinteä koordinaatti",
  "existingFeature": "Aiemmin määritetyistä kohteista",
  "threatAnalysisCoordInputLabel": "Uhkan sijainti",
  "enterCoords": "Kirjoita koordinaatit",
  "threatAddPointToolTip": "Lisää uhkan sijainti",
  "threatDrawPointToolTip": "Lisää uhkan sijainti napsauttamalla",
  "threatType": "Uhkan laji",
  "threatPlaceholder": "Etsi uhkaa aloittamalla sen nimen kirjoitus",
  "zoneTypeLabel": "Vyöhykkeen tyyppi",
  "feetLabel": "Jalkaa",
  "metersLabel": "Metriä",
  "unitsLabel": "Yksiköt",
  "threatGraphicLayer": "Uhka-alueen grafiikka",
  "style": "Tyyli",
  "settingsTitle": "Asetukset",
  "colorPicker": "värivalitsin",
  "lineStyles": {
    "esriSLSDash": "Viiva",
    "esriSLSDashDot": "Viiva-piste",
    "esriSLSDashDotDot": "Viiva-piste-piste",
    "esriSLSDot": "Piste",
    "esriSLSLongDash": "Pitkä viiva",
    "esriSLSLongDashDot": "Pitkä viiva-piste",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lyhyt viiva",
    "esriSLSShortDashDot": "Lyhyt viiva-piste",
    "esriSLSShortDashDotDot": "Lyhyt viiva-piste-piste",
    "esriSLSShortDot": "Lyhyt piste",
    "esriSLSSolid": "Yhtenäinen"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Taaksepäin",
    "esriSFSCross": "Risti",
    "esriSFSDiagonalCross": "Lävistäjän suunnassa",
    "esriSFSForwardDiagonal": "Eteenpäin",
    "esriSFSHorizontal": "Vaaka",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Yhtenäinen",
    "esriSFSVertical": "Pysty"
  },
  "resultsTitle": "Tulokset",
  "publishTABtn": "Julkaise",
  "layerName": "Julkaistun karttatason nimi",
  "invalidLayerName": "Karttatason nimi voi sisältää vain aakkosnumeerisia merkkejä ja alaviivoja",
  "missingLayerNameMessage": "Kelvollinen karttatason nimi on annettava ennen julkaisua",
  "publishingFailedLayerExists": "Julkaisu epäonnistui: Sinulla on jo kohdepalvelu nimeltä {0}. Valitse toinen karttatason nimi.",
  "checkService": "Tarkista palvelu: {0}",
  "createService": "Luo palvelu: {0}",
  "unableToCreate": "Kohteen {0} tuonti ei onnistu",
  "addToDefinition": "Lisää määritykseen: {0}",
  "successfullyPublished": "Web-karttatason julkaisu onnistui",
  "successfullyAppended": "Uudet kohteet on lisätty web-karttatasoon",
  "manageWebLayerText": "Hallitse web-karttatasoa",
  "userRole": "Palvelun luonti ei onnistu, koska käyttäjällä ei ole käyttöoikeuksia",
  "retrieveExistingLayerError": "Kohdetta {0} ei voi noutaa. Julkaisen käyttämällä toista karttatason nimeä",
  "publishToNewLayer": "Julkaise tulokset uuteen kohdekarttatasoon",
  "layerNameExists": "Karttatason nimi on jo käytössä. Käytä toista karttatason nimeä.",
  "pipeBombLabel": "Putkipommi",
  "suicideBombLabel": "Itsemurhapommi",
  "briefcaseLabel": "Salkku",
  "carLabel": "Auto",
  "suvVanLabel": "Kaupunkimaasturi/pakettiauto",
  "smallDeliveryTruckLabel": "Pieni jakeluauto",
  "containerWaterTruckLabel": "Säiliö-/vesisäiliöauto",
  "semiTrailerLabel": "Puoliperävaunu",
  "transparencyLabel": "Läpinäkyvyys",
  "outline": "Ääriviiva",
  "fill": "Täyttö (väriä käytetään vain, kun tyyliksi on määritetty yhtenäinen)",
  "createBtn": "Luo alueet",
  "clearBtn": "Tyhjennä",
  "invalidNumberMessage": "Annettu arvo ei kelpaa",
  "invalidRangeMessage": "Arvon on oltava suurempi kuin 0",
  "parseCoordinatesError": "Koordinaatteja ei voida jäsentää. Tarkista syötteesi.",
  "selectDrawModeLabel": "Valitse piirustustila",
  "selectFeatureLabel": "Valitse kohde tästä karttatasosta",
  "smallLPGTank": "Pieni nestekaasusäiliö",
  "largeLPGTank": "Suuri nestekaasusäiliö",
  "commercialResidentialLPGTank": "Kaupallinen tai kotitalouskäyttöön tarkoitettu nestekaasusäiliö",
  "smallLPGTruck": "Pieni nestekaasusäiliöauto",
  "semiTankerLPG": "Keskikokoinen nestekaasusäiliöauto",
  "zoneDescriptionColLabel": "Vyöhykkeen kuvaus",
  "distanceColLabel": "Etäisyys",
  "zoneDescColLabel": "Vyöhykkeen kuvaus",
  "descriptionLabel": "Kuvaus",
  "editThreatZonePopupLabel": "Muokkaa uhkavyöhykkeen symboleja",
  "symbologyColLabel": "Symbolit",
  "actions": "Toiminnot",
  "threatTypeSelectLabel": "Valitse uhkatyyppi:",
  "distanceLabel": "Etäisyys (${unitAbbr})",
  "layerCountHint": "Vihje: ${layerCount} kohdekarttatasoa sisältävä web-karttataso julkaistaan.",
  "selectLabel": "Valitse",
  "mandatoryLabel": "Pakollinen evakuointietäisyys",
  "safeLabel": "Turvallinen evakuointietäisyys",
  "fireBallDiameterLable": "Tulipallon läpimitta",
  "lpgSafeDistanceLable": "Turvaetäisyys"
});