define({
  "_widgetLabel": "แก้ไขแอตทริบิวต์ของชุดงาน",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "ชื่อชั้นข้อมูล",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "ไม่มีชั้นข้อมูลที่สามารถกำหนดค่าการแก้ไขได้",
  "editorPopupTitle": "แก้ไขแอตทริบิวต์ของชุดงาน",
  "editorPopupSaveBtn": "บันทึก",
  "editorPopupMultipleValues": "",
  "clear": "ชัดเจน",
  "featuresUpdated": "${0} / ${1} คุณลักษณะที่มีการอัพเดต",
  "featuresSelected": "${0} คุณลักษณะที่เลือก",
  "featuresSkipped": "ข้าม",
  "featuresNoPermision": "ฟีเจอร์ ${0} ที่เลือกแต่ไม่ได้รับอนุญาตให้แก้ไข",
  "search": "ค้นหา",
  "queryInput": "ระบุค่าในการค้นหา",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "โปรดตั้งค่าตัวกรองให้ถูกต้อง",
  "filterPopup": "ตัวกรองชั้นข้อมูล",
  "filterAppend": "หากมีตัวกรองในเว็บแมปสำหรับชั้นข้อมูลนี้อยู่แล้ว",
  "filterAppendOR": "ผนวกนิพจน์ใดๆ ลงในตัวกรองแผนที่ที่มีอยู่",
  "filterAppendAND": "ผนวกนิพจน์ทั้งหมดลงในตัวกรองแผนที่ที่มีอยู่",
  "cancel": "ยกเลิก",
  "noValue": "ไม่มีค่า",
  "emptyString": "ไม่พบตัวอักษร",
  "existingValue": "เก็บค่าเดิมไว้",
  "newDate": "วันที่ใหม่",
  "valueChooser": "เลือก / ประเภทของค่า",
  "ok": "ตกลง",
  "drawBox": {
    "point": "จุด",
    "line": "เส้น",
    "polyline": "เส้นหลายรูปแบบ",
    "freehandPolyline": "การวาดเส้นหลายเส้นด้วยมือเปล่า",
    "extent": "ขอบเขต",
    "polygon": "พื้นที่",
    "freehandPolygon": "การวาดรูปหลายเหลี่ยมด้วยมือเปล่า",
    "clear": "ชัดเจน",
    "addPointToolTip": "คลิกเพื่อเลือกในพื้นที่นี้",
    "addShapeToolTip": "วาดรูปร่างเพื่อเลือกคุณสมบัติ",
    "freehandToolTip": "กดค้างไว้เพื่อวาดรูปร่างเพื่อเลือกคุณสมบัติ",
    "startToolTip": "วาดรูปร่างเพื่อเลือกคุณสมบัติ"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "คุณลักษณะจาก ${0} ถูกส่งกลับเนื่องจาก ID ไม่ถูกต้อง",
    "noSelectedLayers": "ไม่ได้เลือกชั้นข้อมูลจากเรคคอร์ดที่มีการอัพเดต",
    "inputValueError": "ค่าอยู่ในรูปแบบที่ไม่ถูกต้อง",
    "saveError": "ไม่สามารถบันทึก ${0} ฟีเจอร์ได้",
    "requiredValue": "ต้องใส่ค่าข้อมูล"
  }
});