define({
  "locatorUrl": "URL lokátora",
  "set": "Nastaviť",
  "locatorName": "Názov lokátora",
  "locatorExample": "Príklad",
  "countryCode": "Kód(y) krajiny alebo regiónu",
  "eg": "napr. ",
  "countryCodeHint": "Ak ponecháte túto hodnotu prázdnu, budesa vyhľadávať vo všetkých krajinách a regiónoch",
  "minCandidateScore": "Minimálne skóre kandidáta",
  "minCandidateScoreHint": "Ak ponecháte túto hodnotu prázdnu, bude použité minimálne skóre kandidáta 90",
  "enableSingleField": "Možnosti jedného poľa",
  "singleFieldHint": "Údaje adries budú v jednom poli",
  "enableMultiField": "Možnosti viacerých polí",
  "multiFieldHint": "Údaje adries budú vo viacerých poliach",
  "enableXYField": "Možnosti poľa X/Y",
  "xyFieldHint": "Údaje budú obsahovať hodnoty súradníc X/Y",
  "instructionGeocode": "Pridať a konfigurovať služby lokátora.",
  "invalidUrlTip": "URL ${URL} je neplatná alebo nedostupná.",
  "geocodeTabLabel": "Nastavenia umiestnenia",
  "lookupList": "Názvy polí na rozoznanie",
  "isRecognized": "Názvy poľa v tabuľke nižšie sú automaticky pre toto pole rozoznávané",
  "needsEditablePointLayers": "Webová mapa musí obsahovať aspoň jednu editovateľnú bodovú vrstvu.",
  "editpageAlias": "Alias",
  "configureFields": "Konfigurovať polia vrstvy",
  "configureSingleFields": "Konfigurovať jedno pole adries",
  "configureMultiFields": "Konfigurovať viacero polí adries",
  "configureXYFields": "Konfigurovať polia X/Y",
  "noFields": "Pre definovanie jedného alebo viacerých polí na zobrazenie použite akciu editovania",
  "display": "Zobrazenie",
  "duplicate": "Nájsť duplicitu",
  "duplicateTip": "Vyhľadajte v tomto poli identické hodnoty medzi zdrojovým súborom a cieľovou vrstvou./n Ak sa nájde identická zhoda, záznam zo súboru nebude nájdený a bude označený ako duplicita.",
  "noSelectField": "Vybrať najskôr možnosť vektorovej vrstvy",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (zemepisná dĺžka)",
  "xyFieldsLabelY": "Y (zemepisná šírka)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Posun na východ",
  "northing": "Posun na sever",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Vyberte vrstvu, do ktorej chcete odoslať údaje.",
  "layerFieldTitle": "Cieľová vrstva",
  "tempSymbolHint": "Vyberte symbol, ktorý bude použitý na zobrazenie prvkov.",
  "tempSymbolTitle": "Zobraziť symbol",
  "maxRecords": "Maximum záznamov",
  "maxRecordsHint": "Maximálny počet záznamov na lokalizáciu",
  "searchRadius": "Polomer oblasti vyhľadávania",
  "searchRadiusHint": "Vzdialenosť na vyhľadanie duplicitných prvkov z vrstvy",
  "requiresInteger": "Zadajte číselnú hodnotu.",
  "requiresInteger0100": "Zadajte číselnú hodnotu medzi 0 a 100",
  "requiresLocator": "Pridajte aspoň jeden platný lokátor.",
  "layerFields": "Nastavenia vrstvy",
  "layerFieldsHint": "Zadajte polia z cieľovej vrstvy, ktoré sa napárujú na zdrojové polia.",
  "locatorError": "Lokátor je neplatný alebo nedostupný.",
  "optionNotMatch": "Možnosti poľa nie sú konzistentné vo všetkých lokátoroch. Oprava nemusí fungovať podľa očakávania.",
  "targetLayerTabTitle": "Cieľová vrstva",
  "locationSettingsTabTitle": "Nastavenia umiestnenia",
  "generalSettingsTabTitle": "Všeobecné nastavenia",
  "addTargetLayersLabel": "Pridať cieľovú vrstvu",
  "introductoryText": "Vytvoriť inštruktážny obsah pre widget",
  "defaultStartPageInstructions": "Tento widget bude asistovať so spracovaním a odoslaním dát zo súboru do vybranej vrstvy v mape.<br/><br/> Hodnoty v súbore musia byť ohraničené čiarkou, tabulátorom, bodkočiarkou alebo zvislou čiarou.",
  "noTargetLayerConfiguredErrorMsg": "Nie je konfigurovaná žiadna cieľová vrstva",
  "noFieldsForTargetLayer": "Nastavenia vrsty nie sú pre cieľovú vrstvu definované",
  "locationSettingsNotConfigured": "Nastavenia lokalizácie nie sú správne konfigurované",
  "questionMark": "?"
});