define({
  "_widgetLabel": "Agregación de datos",
  "startPage": {
    "defaultStartPageInstructions": "Este widget le ayudará a procesar y enviar datos de un archivo a la capa seleccionada en el mapa.<br/> <br/> Los valores contenidos en el archivo se deben delimitar por comas, tabulaciones, puntos y coma o barras verticales.",
    "dragDrop": "Arrastrar y soltar",
    "browse": "Ir a archivo",
    "or": "O BIEN",
    "userPrivilege": "Su cuenta no tiene permiso para crear o modificar datos.",
    "userCredits": "${widgetName} requiere créditos para usar el localizador ${locator}.",
    "contactAdmin": "Póngase en contacto con el administrador de la organización para solicitar créditos adicionales.",
    "contactAdminEdit": "Póngase en contacto con el administrador de la organización para solicitar privilegios de edición.",
    "canUseLocator": "El localizador ${locator} se utilizará para localizar entidades.",
    "notEnoughCredits": "No hay suficientes créditos.",
    "locationAndField": "Información de campo y ubicación",
    "locationAndFieldHint": "Seleccione los valores del archivo que se deberían utilizar para actualizar la capa de destino.",
    "cannotUseLocator": "No se puede utilizar ${widgetName}",
    "noAnonymousEdit": "La capa ${layerName} no admite la edición anónima.",
    "pleaseLogin": "Inicie sesión en la organización ${org} o póngase en contacto con el administrador de la organización para solicitar que se habilite la edición anónima.",
    "invalidEdit": "Privilegios no válidos",
    "unableToAccess": "No se puede acceder a ${layerName}",
    "appropriateCredentials": "Compruebe que ha iniciado sesión con las credenciales adecuadas.",
    "shared": "Póngase en contacto con el administrador de la organización para solicitar acceso a la capa ${layerName}.",
    "targetLayerLabel": "Capa de destino",
    "homeButtonLabel": "Inicio",
    "mappingErrorMsg": "Haga clic en la flecha situada al lado para definir los campos"
  },
  "mapping": {
    "schemaMapping": "Información de campo",
    "schemaMappingHint": "Elija los campos del archivo que se correspondan con los campos de la capa.",
    "locationMapping": "Información de ubicación",
    "locationMappingHint": "Elija el tipo de dirección o información de coordenada que se espera del archivo."
  },
  "locationMapping": {
    "locationMappingPageHint": "Elegir tipo de ubicación",
    "useAddress": "Localizar usando una dirección",
    "useAddressHint": "Los datos contienen información de dirección",
    "useCoordinates": "Localizar usando coordenadas",
    "useCoordinatesHint": "Los datos contienen valores de coordenadas X/Y"
  },
  "address": {
    "addressPageHint": "Elegir tipo de dirección",
    "singleField": "Campo único",
    "singleFieldHint": "Elegir el campo que contiene la información de dirección",
    "multiField": "Varios campos",
    "multiFieldHint": "Elegir los campos que contienen la información de dirección"
  },
  "coordinates": {
    "coordinatesPageHint": "Elegir los campos que contienen los datos de coordenadas"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Elegir el campo de origen asignado al campo objetivo",
    "sourceField": "Campo de origen coincidente",
    "targetField": "Campo de destino"
  },
  "buttons": {
    "addToMap": "Agregar al mapa",
    "submit": "Enviar",
    "download": "Descargar"
  },
  "review": {
    "matched": "Encontradas",
    "reviewMatched": "Ubicaciones encontradas",
    "reviewMatchedHint": "Revise las ubicaciones encontradas.",
    "unMatched": "No encontradas",
    "reviewUnMatched": "Ubicaciones no encontradas",
    "reviewUnMatchedHint": "Revise las ubicaciones no encontradas. Los elementos que no se corrijan no se enviarán.",
    "duplicate": "Duplicada",
    "reviewDuplicate": "Ubicaciones duplicadas",
    "reviewDuplicateHint": "Revise las ubicaciones ya encontradas en la capa. Los elementos que no se hayan abordado no se enviarán.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Usar:",
    "fromLayer": "Información de destino",
    "target": "Destino",
    "source": "Origen",
    "fromFile": "Información de fuente",
    "locationControlHint": "Revisar la información de dirección",
    "duplicateAction": "Elegir una acción",
    "item": "Registro:",
    "locateFeature": "Ubicar entidad",
    "removeFeature": "Eliminar entidad",
    "featureLocated": "Ubicación encontrada",
    "valuesDoNotMatch": "No coincide con el valor existente",
    "sync": "Sincronizar la información de dirección con la información de campo",
    "noFeaturesSaved": "No se ha guardado ninguna entidad correctamente",
    "someFeaturesSaved": "${num} entidad(es) guardada(s) correctamente.",
    "someFeaturesNotSaved": "${num} entidad(es) no guardada(s) correctamente.",
    "feature": "Revisar información de entidad",
    "locationInfo": "Revisar información de ubicación",
    "selectValue": "Seleccione un valor",
    "reviewData": "Revisar datos",
    "reviewDataHint": "Revise sus datos antes de enviarlos a la capa.",
    "reviewFeatureHint": "Revise o edite su información de ubicación y entidad.",
    "duplicateModify": "Duplicada; se debe cambiar",
    "duplicateSave": "Guardar como una entidad nueva"
  },
  "warningsAndErrors": {
    "invalidCSV": "Error al obtener los elementos del CSV; compruebe si se ha seleccionado un archivo CSV válido.",
    "noLayersWarning": "No hay ninguna capa de destino válida configurada; compruebe la configuración.",
    "loadWarning": "Este widget requiere una fuente de datos de Servicio de entidades. Configure el widget para definir una fuente de datos.",
    "saveError": "Error al guardar las entidades.",
    "consumesCredits": "Esta herramienta consume créditos cuando se utiliza con el Servicio de geocodificación mundial de ArcGIS Online",
    "noValue": "Seleccionar un campo",
    "mappingTitle": "",
    "locationMappingComplete": "Asignación de ubicación completada",
    "fieldMappingComplete": "Asignación de campos completada",
    "settingsCleared": "La configuración se eliminará.",
    "proceed": "¿Desea continuar?",
    "itemMoveMatch": "El elemento se localizó y se movió a la lista Ubicaciones encontradas",
    "itemMoveUnMatched": "No se puede localizar el elemento. Movido a la lista Ubicaciones no encontradas.",
    "itemWillBeLocated": "El elemento se eliminará de la lista Ubicaciones duplicadas.",
    "cannotLocate": "No se puede localizar el elemento. Verifique la información de ubicación.",
    "invalidMessage": "Valor no válido.",
    "rangeMessage": "El valor debe tener menos de ${num} caracteres.",
    "locatorError": "Localizador no válido o inaccesible.",
    "notConfigured": "El localizador no está configurado para las opciones de localización actuales",
    "noMoreLocators": "No hay localizadores adicionales configurados"
  },
  "featureToolbar": {
    "locate": "Locate",
    "save": "Guardar registro",
    "cancel": "Cancelar ediciones",
    "cancelTitle": "Cancelar ediciones",
    "cancelMessage": "¿Desea cancelar las ediciones del registro actual?"
  }
});