define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Accediu a la infografia i als informes que resumeixen els indicadors i les dades clau de qualsevol àrea.</div><br><div>Seleccioneu un punt o un polígon al mapa, cerqueu una adreça o un lloc, dibuixeu un polígon o col·loqueu una xinxeta al mapa per veure indicadors clau i informació sobre l'àrea.</div>",
  "defineWhichInfographics": "Definiu la infografia que estarà disponible al widget:",
  "defineWhichReports": "Definiu els informes que estaran disponibles al widget:",
  "defaultValues": "Valors per defecte:",
  "disable": "Deshabilita",
  "drawFreehandPolygon": "Dibuixa un polígon a mà alçada",
  "drawPolygon": "Dibuixa un polígon",
  "driveTime": "Temps de recorregut",
  "dropPin": "Marca amb una xinxeta",
  "dynamicHTML": "HTML dinàmic",
  "exportOptions": "Opcions d'exportació",
  "home": "Inici",
  "image": "Imatge",
  "infographics": "Infografia",
  "invalidValueRing": "Els valors han d'estar en un interval de 0 a 1.000.",
  "invalidValueDTWT": "Els valors han d'estar en un interval de 0 a 300.",
  "km": "km",
  "makeDefault": "Defineix-lo per defecte",
  "miles": "milles",
  "minutes": "minuts",
  "options": "Opcions:",
  "pdf": "PDF",
  "print": "Imprimeix",
  "radius": "Radi",
  "removeDefault": "Elimina el valor per defecte",
  "reports": "Informes",
  "rings": "Anells",
  "searchTextBox": "Quadre de text de cerca",
  "selectCountryOrRegion": "Seleccioneu un país o una regió:",
  "thisEntryIsNotValid": "Aquesta entrada no és vàlida.",
  "time": "Temps",
  "walkTime": "Temps de recorregut a peu"
});