define({
  "_widgetLabel": "일괄처리 속성 편집기",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "레이어 이름",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "구성된 편집 가능한 레이어 없음",
  "editorPopupTitle": "일괄처리 속성 편집기",
  "editorPopupSaveBtn": "저장",
  "editorPopupMultipleValues": "",
  "clear": "선택 해제",
  "featuresUpdated": "피처 ${0}/${1}개 업데이트함",
  "featuresSelected": "피처 ${0}개 선택함",
  "featuresSkipped": "무시함",
  "featuresNoPermision": "피처 ${0}개가 선택되었지만 편집할 수 있는 권한이 없습니다.",
  "search": "검색",
  "queryInput": "쿼리할 값 입력",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "필터를 올바르게 설정하세요.",
  "filterPopup": "레이어 필터",
  "filterAppend": "웹 맵에 이 레이어에 대한 필터가 이미 있는 경우",
  "filterAppendOR": "기존 맵 필터에 임의 식 추가",
  "filterAppendAND": "기존 맵 필터에 모든 식 추가",
  "cancel": "취소",
  "noValue": "값 없음",
  "emptyString": "빈 문자열",
  "existingValue": "기존 값 유지",
  "newDate": "최신 날짜",
  "valueChooser": "값 선택/입력",
  "ok": "확인",
  "drawBox": {
    "point": "포인트",
    "line": "라인",
    "polyline": "폴리라인",
    "freehandPolyline": "자유곡선 폴리라인",
    "extent": "범위",
    "polygon": "폴리곤",
    "freehandPolygon": "자유곡선 폴리곤",
    "clear": "선택 해제",
    "addPointToolTip": "이 면적에서 클릭하여 선택합니다.",
    "addShapeToolTip": "모양을 그려 피처를 선택합니다.",
    "freehandToolTip": "길게 누르고 모양을 그려 피처를 선택합니다.",
    "startToolTip": "모양을 그려 피처를 선택합니다."
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "${0}의 피처가 잘못된 ID를 반환했습니다.",
    "noSelectedLayers": "업데이트할 레코드와 함께 선택된 레이어가 없습니다.",
    "inputValueError": "양식의 값이 잘못되었습니다.",
    "saveError": "${0} 피처를 저장할 수 없음",
    "requiredValue": "필수 값"
  }
});