define({
  "locatorUrl": "URL du localisateur",
  "set": "Définir",
  "locatorName": "Nom du localisateur",
  "locatorExample": "Exemple",
  "countryCode": "Codes de pays ou de régions",
  "eg": "par exemple ",
  "countryCodeHint": "Si cette valeur n’est pas renseignée, la recherche s’effectue dans tous les pays et toutes les régions",
  "minCandidateScore": "Score minimum de candidat",
  "minCandidateScoreHint": "Si ce champ est laissé vide, un score minimum de candidat de 90 sera utilisé",
  "enableSingleField": "Options de champ unique",
  "singleFieldHint": "Les données d’adresses figureront dans un champ unique",
  "enableMultiField": "Options de champs multiples",
  "multiFieldHint": "Les données d’adresses figureront dans des champs multiples",
  "enableXYField": "Options de champs X/Y",
  "xyFieldHint": "Les données contiendront les valeurs de coordonnées X/Y",
  "instructionGeocode": "Ajoutez et configurez des services de localisateur.",
  "invalidUrlTip": "L’URL ${URL} est incorrecte ou inaccessible.",
  "geocodeTabLabel": "Paramètres de localisation",
  "lookupList": "Noms de champs à reconnaître",
  "isRecognized": "Les noms de champs dans la table ci-dessous sont automatiquement reconnus pour ce champ",
  "needsEditablePointLayers": "La carte Web doit contenir au moins une couche de points modifiable.",
  "editpageAlias": "Alias",
  "configureFields": "Configurer les champs de couche",
  "configureSingleFields": "Configurer un champ d’adresse unique",
  "configureMultiFields": "Configurer des champs d’adresse multiples",
  "configureXYFields": "Configurer des champs X/Y",
  "noFields": "Utiliser l’action de mise à jour pour définir un ou plusieurs champs à afficher",
  "display": "Affichage",
  "duplicate": "Rechercher les doublons",
  "duplicateTip": "Recherchez dans ce champ des valeurs identiques dans le fichier source et la couche cible./n Si un doublon est détecté, l’enregistrement provenant du fichier n’est pas localisé et il est marqué comme doublon.",
  "noSelectField": "Sélectionner d’abord l’option Couche d’entités",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Longitude)",
  "xyFieldsLabelY": "Y (Latitude)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Abscisse",
  "northing": "Ordonnée",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Sélectionnez la couche à laquelle envoyer les données.",
  "layerFieldTitle": "Couche cible",
  "tempSymbolHint": "Sélectionnez le symbole à utiliser pour l’affichage des entités.",
  "tempSymbolTitle": "Symbole d’affichage",
  "maxRecords": "Nbre max d’enregistrements",
  "maxRecordsHint": "Nombre maximum d’enregistrements à localiser",
  "searchRadius": "Rayon de recherche",
  "searchRadiusHint": "Distance de recherche des entités dupliquées de la couche",
  "requiresInteger": "Saisissez une valeur numérique.",
  "requiresInteger0100": "Saisissez une valeur numérique comprise entre 0 et 100",
  "requiresLocator": "Ajoutez au moins un localisateur valide.",
  "layerFields": "Paramètres de la couche",
  "layerFieldsHint": "Spécifiez les champs issus de la couche cible qui seront appariés aux champs source.",
  "locatorError": "Le localisateur n’est pas valide ou est inaccessible.",
  "optionNotMatch": "Les options des champs ne sont pas cohérentes pour l’ensemble des localisateurs. La reprise après incident risque de ne pas fonctionner comme prévu.",
  "targetLayerTabTitle": "Couche cible",
  "locationSettingsTabTitle": "Paramètres de localisation",
  "generalSettingsTabTitle": "Paramètres généraux",
  "addTargetLayersLabel": "Ajouter la couche cible",
  "introductoryText": "Créer un contenu explicatif pour le widget",
  "defaultStartPageInstructions": "Ce widget fournira de l’aide lors du traitement et de l’envoi de données depuis un fichier vers la couche sélectionnée dans la carte.<br/> <br/> Les valeurs au sein du fichier doivent être séparées par des virgules, des tabulations, des points-virgules ou des barres verticales.",
  "noTargetLayerConfiguredErrorMsg": "Aucune couche cible configurée",
  "noFieldsForTargetLayer": "Les paramètres de couche ne sont pas définis pour la couche cible",
  "locationSettingsNotConfigured": "Les paramètres de localisation ne sont pas correctement configurés"
});