define({
  "_widgetLabel": "Editor de atributos por lotes",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nombre de la capa",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "No se ha configurado ninguna capa editable",
  "editorPopupTitle": "Editor de atributos por lotes",
  "editorPopupSaveBtn": "Guardar",
  "editorPopupMultipleValues": "",
  "clear": "Borrar",
  "featuresUpdated": "${0}/${1} entidad(es) actualizada(s)",
  "featuresSelected": "${0} entidad(es) seleccionada(s)",
  "featuresSkipped": "Omitido",
  "featuresNoPermision": "${0} entidad o entidades seleccionadas, pero no se dispone del permiso de edición.",
  "search": "Búsqueda",
  "queryInput": "Introduce el valor que deseas consultar",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Define el filtro correctamente.",
  "filterPopup": "Capa de filtro",
  "filterAppend": "Si ya existe un filtro en el mapa web para esta capa",
  "filterAppendOR": "Incorporar cualquier expresión al filtro de mapa existente",
  "filterAppendAND": "Incorporar todas las expresiones al filtro de mapa existente",
  "cancel": "Cancelar",
  "noValue": "Sin valor",
  "emptyString": "Cadena de caracteres vacía",
  "existingValue": "Mantener valor existente",
  "newDate": "Nueva fecha",
  "valueChooser": "Seleccionar/escribir un valor",
  "ok": "Aceptar",
  "drawBox": {
    "point": "Punto",
    "line": "Línea",
    "polyline": "Polilínea",
    "freehandPolyline": "Polilínea a mano alzada",
    "extent": "Extensión",
    "polygon": "de polígono",
    "freehandPolygon": "Polígono a mano alzada",
    "clear": "Borrar",
    "addPointToolTip": "Haz clic para seleccionar en esta área",
    "addShapeToolTip": "Dibuja una forma para seleccionar entidades",
    "freehandToolTip": "Pulsa y mantén pulsado para dibujar una forma y seleccionar entidades",
    "startToolTip": "Dibuja una forma para seleccionar entidades"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "La entidad de ${0} ha devuelto un Id. no válido",
    "noSelectedLayers": "No se ha seleccionado ninguna capa con registros para actualizar",
    "inputValueError": "Valor no válido en el formulario",
    "saveError": "No se pueden guardar ${0} entidades",
    "requiredValue": "Valor requerido"
  }
});