define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Akun Anda tidak memiliki izin untuk membuat atau mengubah data.",
  "loginPopupTitle": "Masuk",
  "loginPopupMessage": "${widgetName} memerlukan izin dan kredit untuk mencari dan menyimpan informasi alamat. Apa Anda ingin masuk dan menggunakan kemampuan ini?",
  "noCreditsOrPrivilegeWarningMessage": "Akun Anda tidak memiliki izin dan kredit untuk mencari serta menyimpan informasi alamat dengan ${widgetName}. Hubungilah administrator organisasi Anda untuk meminta izin dan kredit.",
  "unableToUseLocator": "Penentu lokasi tidak dapat diakses. Tindakan atribut alamat tidak akan dijalankan.",
  "locatorDisabledWaning": "Penanda lokasi tidak aktif. Hubungi administrator organisasi Anda untuk meminta kemampuan ini.",
  "noFeatureInAIWarning": "Tidak ada fitur yang dipilih. Pilih fitur untuk mengedit atau klik batal untuk kembali ke layar utama.",
  "noEditableLayerWarning": "Akun Anda tidak memiliki izin untuk membuat atau memodifikasi data, atau peta web ini tidak berisi layer yang dapat diedit.",
  "noVisibleCreateLayerWarning": "Layer tidak dapat dilihat pada level zoom saat ini. Perbesar atau perkecil untuk membuat/memodifikasi fitur.",
  "noVisibleUpdateLayerWarning": "Layer tidak dapat dilihat pada level zoom saat ini. Perbesar atau perkecil untuk memodifikasi fitur.",
  "checkLayerVisibilityInWebMapWarning": "Pastikan layer dapat dilihat di peta untuk membuat atau memodifikasi fitur.",
  "showSelectionInAITitle": "Fitur yang Dipilih",
  "showSelectionInAIMsg": "Apa Anda ingin memuat pilihan saat ini di ${widgetName}?",
  "widgetActive": "Aktif",
  "widgetNotActive": "Tidak Aktif",
  "pressStr": "Tekan ",
  "ctrlStr": " CTRL ",
  "snapStr": " untuk mengaktifkan snapping",
  "noAvailableTempaltes": "Template tidak tersedia",
  "editorCache": " - Editor Cache",
  "presetFieldAlias": "Kolom",
  "presetValue": "Nilai Preset",
  "usePresetValues": " Gunakan nilai prasetel (khusus fitur baru)",
  "editGeometry": " Edit Geometri",
  "savePromptTitle": "Simpan fitur",
  "savePrompt": "Anda ingin menyimpan fitur saat ini?",
  "deletePromptTitle": "Hapus fitur",
  "deleteAttachment": "Hapus lampiran",
  "deletePrompt": "Anda yakin ingin menghapus fitur terpilih?",
  "attachmentLoadingError": "Kesalahan mengunggah lampiran",
  "attachmentSaveDeleteWarning": "Peringatan: Perubahan pada lampiran disimpan secara otomatis",
  "autoSaveEdits": "Simpan fitur baru secara otomatis",
  "addNewFeature": "Buat fitur baru",
  "featureCreationFailedMsg": "Tidak dapat membuat catatan/fitur baru",
  "relatedItemTitle": "Tabel/Layer Terkait",
  "relatedFeatureCount": "${layerTitle} dengan ${featureCount} fitur",
  "createNewFeatureLabel": "Buat fitur baru untuk ${layerTitle}",
  "invalidRelationShipMsg": "Harap pastikan kolom kunci utama: '${parentKeyField}' memiliki nilai valid",
  "pendingFeatureSaveMsg": "Harap simpan editan fitur sebelum membuat fitur terkait.",
  "attachmentsRequiredMsg": "(*) Lampiran harus ada.",
  "coordinatePopupTitle": "Pindahkan fitur ke lokasi XY",
  "coordinatesSelectTitle": "Sistem Koordinat:",
  "mapSpecialReferenceDropdownOption": "Referensi Spasial Peta",
  "latLongDropdownOption": "Garis Lintang/Garis Bujur",
  "mgrsDropdownOption": "Sistem Referensi Grid Militer (MGRS)",
  "mgrsTextBoxLabel": "Koordinat:",
  "xAttributeTextBoxLabel": "Koordinat-X:",
  "yAttributeTextBoxLabel": "Koordinat-Y:",
  "latitudeTextBoxLabel": "Garis Lintang:",
  "longitudeTextBoxLabel": "Garis Bujur:",
  "presetGroupFieldsLabel": "'${groupName}' akan diterapkan ke kolom layer berikut:",
  "presetGroupNoFieldsLabel": "'${groupName}' tidak memiliki kolom terkait",
  "groupInfoLabel": "Informasi grup untuk '${groupName}'",
  "editGroupInfoIcon": "Edit nilai grup untuk ${groupName}",
  "filterEditor": {
    "all": "Semua",
    "noAvailableTempaltes": "Template tidak tersedia",
    "searchTemplates": "Pencarian Template",
    "filterLayerLabel": "Filter layer"
  },
  "invalidConfiguration": "Widget tidak dikonfigurasi atau layer dalam konfigurasi tidak ada lagi di peta. Harap buka aplikasi dengan mode pembangun (builder) dan konfigurasi ulang widget.",
  "geometryServiceURLNotFoundMSG": "Tidak dapat memperoleh URL Service Geometri",
  "clearSelection": "Tutup",
  "refreshAttributes": "Perbarui atribut fitur dinamis",
  "automaticAttributeUpdatesOn": "Perbarui otomatis atribut fitur: ON",
  "automaticAttributeUpdatesOff": "Perbarui otomatis atribut fitur: OFF",
  "moveSelectedFeatureToGPS": "Pindahkan fitur terpilih ke lokasi GPS saat ini",
  "moveSelectedFeatureToXY": "Pindahkan fitur terpilih ke lokasi XY",
  "mapNavigationLocked": "Navigasi Peta: Terkunci",
  "mapNavigationUnLocked": "Navigasi Peta: Tidak Terkunci",
  "copyFeatures": {
    "title": "Salin Fitur",
    "createFeatures": "Buat Fitur",
    "createSingleFeature": "Buat 1 Fitur Multibagian",
    "createOneSingleFeature": "Buat Fitur",
    "noFeaturesSelectedMessage": "Tidak Ada Fitur yang Dipilih",
    "selectFeatureToCopyMessage": "Pilih fitur yang akan disalin",
    "multipleFeatureSaveWarning": "Catatan: Membuat beberapa fitur menggunakan fungsi salin akan menyimpan semua fitur baru secara langsung",
    "copyFeatureUpdateGeometryError": "Tidak dapat memperbarui geometri fitur yang dipilih",
    "canNotSaveMultipleFeatureWarning": "Catatan: Tidak bisa menyalin beberapa fitur yang menggunakan nilai yang sama untuk kolom nilai unik, harap pilih satu fitur saja",
    "createOnlyOneMultipartFeatureWarning": "Catatan: Hanya satu fitur multi-bagian yang bisa dibuat"
  },
  "addingFeatureError": "Kesalahan saat menambahkan fitur pilihan dalam layer. Harap coba lagi.",
  "addingFeatureErrorCount": "Fitur '${copyFeatureErrorCount}' gagal disalin. Apa Anda ingin mencoba lagi untuk fitur yang terlewat?",
  "selectingFeatureError": "Kesalahan saat memilih fitur dalam layer. Harap coba lagi.",
  "customSelectOptionLabel": "Pilih fitur untuk disalin",
  "noFeatureSelectedMessage": "Tidak ada fitur dipilih",
  "multipleFeatureSaveMessage": "Semua fitur akan segera disimpan. Anda ingin melanjutkan?",
  "relativeDates": {
    "dateTypeLabel": "Tipe Data",
    "valueLabel": "Nilai",
    "fixed": "Tetap",
    "current": "Saat ini",
    "past": "Telah lalu",
    "future": "Mendatang",
    "popupTitle": "Pilih Nilai",
    "hintForFixedDateType": "Petunjuk: Tanggal dan waktu yang ditentukan akan digunakan sebagai nilai default prasetel.",
    "hintForCurrentDateType": "Petunjuk: Tanggal dan waktu saat ini akan digunakan sebagai nilai default prasetel.",
    "hintForPastDateType": "Petunjuk: Nilai yang ditentukan akan disubtraksi dari tanggal dan waktu saat ini untuk nilai default preset.",
    "hintForFutureDateType": "Petunjuk: Nilai yang ditentukan akan ditambahkan ke tanggal dan waktu saat ini untuk nilai default preset.",
    "noDateDefinedTooltip": "Tidak ada tanggal ditentukan",
    "relativeDateWarning": "Nilai untuk tanggal atau waktu harus ditetapkan untuk dapat menyimpan nilai prasetel default.",
    "customLabel": "Khusus",
    "layerLabel": "Layer",
    "domainFieldHintLabel": "Nilai yang dipilih adalah domain nilai yang dikodekan. Nilai: \"${domainValue}\" akan digunakan"
  },
  "valuePicker": {
    "popupTitle": "Pilih Nilai",
    "popupHint": "Fitur saat ini berpotongan dengan beberapa fitur, pilih nilai untuk masing-masing kolom",
    "buttonTooltip": "Pilih nilai dari beberapa fitur berpotongan"
  },
  "uniqueValueErrorMessage": "Nilai pada \"${fieldName}\" sudah ada, berikan nilai yang baru.",
  "requiredFields": {
    "displayMsg": "Kolom wajib tidak boleh kosong. Berikan nilai untuk kolom umum di bawah.",
    "popupTittle": "Kolom yang wajib diisi",
    "foundNullRecordCount": "${fieldName} (Ditemukan di ${count} rekaman)"
  },
  "cantLocateUserLocation": "Lokasi Anda tidak dapat ditentukan",
  "tryAgainButtonLabel": "Coba lagi",
  "copyFeatureFailedPopupTitle": "Ups!"
});