define({
  "taskUrl": "כתובת URL של שירות השטחים הנצפים",
  "portalURL": "ציין את ה-URL של ארגון ArcGIS Online או הפורטל של ArcGIS",
  "portalURLError": "כתובת ה-URL שהוגדרה עבור ארגון ArcGIS Online או הפורטל של ArcGIS אינה חוקית.",
  "privilegeError": "תפקיד המשתמש שלך לא יכול לבצע ניתוח. כדי שתוכל לבצע ניתוח, מנהל המערכת של הארגון צריך להעניק לך ‎<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">‎הרשאות‎</a>‎ מסוימות.",
  "noServiceError": "שירות ניתוח הגובה לא זמין. בדוק את התצורה של ארגון ArcGIS Online או הפורטל של ArcGIS.",
  "maximumRangeMessage": "טווח התצפית המרבי חייב להיות גדול מטווח התצפית המינימלי ולא יוכל להיות גדול מ-‎${limit} ${units}.",
  "serviceURLPlaceholder": "הזן כתובת URL של משימת עיבוד גיאוגרפי של שטחים נצפים",
  "setTask": "הגדר",
  "setTaskTitle": "הגדר משימת עיבוד גיאוגרפי של שטחים נצפים",
  "serviceURLError": "משימת העיבוד הגיאוגרפי שאתה מנסה להגדיר באמצעות ווידג'ט זה אינה חוקית. בחר כתובת URL חוקית של משימת עיבוד גיאוגרפי של שטחים נצפים",
  "defaultMilsForAnglesLabel": "הגדר מיילים לזוויות כברירת מחדל",
  "defaultObserverHeightLabel": "ברירת מחדל של יחידת גובה צופה",
  "defaultObservableDistanceLabel": "ברירת מחדל של יחידת מרחק שניתנת לצפייה",
  "defaultObserveHeightLabel": "ברירת מחדל של גובה צופה",
  "defaultMinimumObservableDistanceLabel": "ברירת מחדל של מרחק מינימלי שניתן לצפייה",
  "defaultMaximumObservableDistanceLabel": "ברירת מחדל של מרחק מרבי שניתן לצפייה",
  "units": {
    "miles": "מייל",
    "kilometers": "קילומטרים",
    "feet": "רגליים",
    "meters": "מטרים",
    "yards": "יארדים",
    "nauticalMiles": "מיילים ימיים"
  },
  "helpIconTooltip": "הרשימה של שכבת התפעול מתמלאת בשכבות מה-Web Map הנוכחית, שסוג הגיאומטריה שלהן הוא פוליגון.",
  "selectOperationalLayerLabel": "בחר שכבת תפעול לקבלת תוצאות",
  "lineOfSightTabTitle": "קו ראייה",
  "symbologyTabTitle": "סימבולוגיה",
  "transparency": "שקיפות",
  "outline": "קו תוחם",
  "fill": "מילוי (הצבע חל רק כשהסגנון הוא 'מלא')",
  "style": "סגנון",
  "selectOpLayerLabel": "בחר שכבת תפעול לקבלת תוצאות",
  "selectDefaultMeasurementLabel": "בחר יחידת מידה שתהווה ברירת מחדל",
  "visibleSectionLabel": "קטע נראה",
  "nonVisibleSectionLabel": "קטע לא נראה",
  "visibleSectionButtonLabel": "קבע הגדרות קטע נראה",
  "nonVisibleSectionButtonLabel": "קבע הגדרות קטע לא נראה",
  "colorPicker": "בורר צבעים",
  "lineStyles": {
    "esriSLSDash": "מקווקו",
    "esriSLSDashDot": "קו נקודה",
    "esriSLSDashDotDot": "קו נקודה נקודה",
    "esriSLSDot": "נקודה",
    "esriSLSLongDash": "קו ארוך",
    "esriSLSLongDashDot": "קו נקודה ארוך",
    "esriSLSNull": "ריק",
    "esriSLSShortDash": "קו קצר",
    "esriSLSShortDashDot": "קו נקודה קצר",
    "esriSLSShortDashDotDot": "קו נקודה נקודה קצר",
    "esriSLSShortDot": "נקודה קצרה",
    "esriSLSSolid": "מלא"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "לאחור",
    "esriSFSCross": "צלב",
    "esriSFSDiagonalCross": "אלכסוני",
    "esriSFSForwardDiagonal": "קדם",
    "esriSFSHorizontal": "אופקי",
    "esriSFSNull": "ריק",
    "esriSFSSolid": "מלא",
    "esriSFSVertical": "אנכי"
  }
});