define({
  "locatorUrl": "URL localizzatore",
  "set": "Imposta",
  "locatorName": "Nome localizzatore",
  "locatorExample": "Esempio",
  "countryCode": "Codici paesi o regioni",
  "eg": "es. ",
  "countryCodeHint": "Se si lascia vuoto questo campo, la ricerca verrà effettuata in tutti i paesi e le regioni",
  "minCandidateScore": "Punteggio minimo per candidato",
  "minCandidateScoreHint": "Se si lascia vuoto questo campo, si userà un punteggio minimo per candidato di 90",
  "enableSingleField": "Opzioni Single-field",
  "singleFieldHint": "I dati relativi all’indirizzo saranno inseriti in un campo singolo",
  "enableMultiField": "Opzioni Multi-field",
  "multiFieldHint": "I dati relativi all’indirizzo saranno inseriti in campi multipli",
  "enableXYField": "Opzioni campo X/Y",
  "xyFieldHint": "I dati conterranno i valori delle coordinate X/Y",
  "instructionGeocode": "Aggiungere e configurare i servizi locator.",
  "invalidUrlTip": "URL ${URL} non valido o non accessibile.",
  "geocodeTabLabel": "Impostazioni posizione",
  "lookupList": "Field Names to Recognize",
  "isRecognized": "I nomi del campo nella tabella in basso sono automaticamente riconosciuti per questo campo",
  "needsEditablePointLayers": "La webmap deve contenere almeno un layer puntuale modificabile.",
  "editpageAlias": "Alias",
  "configureFields": "Configura campi layer",
  "configureSingleFields": "Configura un campo di un singolo indirizzo",
  "configureMultiFields": "Configura campi a indirizzo multiplo",
  "configureXYFields": "Configura campi X/Y",
  "noFields": "Utilizzare l'azione di modifica per definire uno o più campi da visualizzare",
  "display": "Visualizza",
  "duplicate": "Trova duplicato",
  "duplicateTip": "Cercare in questo campo valori identici tra il file di origine e il layer di destinazione./n Quando si trova una corrispondenza identica, il record del file non sarà localizzato e sarà contrassegnato come duplicato.",
  "noSelectField": "Seleziona prima l'opzione Feature Layer",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Longitudine)",
  "xyFieldsLabelY": "Y (Latitudine)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Ad Est",
  "northing": "A Nord",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Scegliere il layer a cui inviare dati.",
  "layerFieldTitle": "Layer di destinazione",
  "tempSymbolHint": "Scegliere il simbolo che si utilizzerà per visualizzare le feature.",
  "tempSymbolTitle": "Visualizza simbolo",
  "maxRecords": "Max records",
  "maxRecordsHint": "Numero massimo di record da localizzare",
  "searchRadius": "Raggio di ricerca",
  "searchRadiusHint": "Distanza di ricerca per le feature duplicate dal layer",
  "requiresInteger": "Immettere un valore numerico.",
  "requiresInteger0100": "Immettere un valore numerico compreso tra 0 e 100",
  "requiresLocator": "Aggiungere almeno un localizzatore valido.",
  "layerFields": "Impostazioni layer",
  "layerFieldsHint": "Specificare i campi del layer di destinazione che saranno mappati sui campi di origine.",
  "locatorError": "Il locator non è valido o non è accessibile.",
  "optionNotMatch": "Opzioni di campo non coerenti tra i locator. Il failover potrebbe non funzionare come previsto.",
  "targetLayerTabTitle": "Layer di destinazione",
  "locationSettingsTabTitle": "Impostazioni posizione",
  "generalSettingsTabTitle": "Impostazioni generali",
  "addTargetLayersLabel": "Aggiungi layer di destinazione",
  "introductoryText": "Crea contenuto con istruzioni per il widget",
  "defaultStartPageInstructions": "Questo widget assisterà nell’elaborazione e nell’invio di dati da un file al layer selezionato nella mappa.<br/> <br/> I valori all’interno del file devono essere delimitati da virgola, tab, punto e virgola o barra verticale.",
  "noTargetLayerConfiguredErrorMsg": "Nessun layer di destinazione configurato",
  "noFieldsForTargetLayer": "Le impostazioni del layer non sono definite per il layer di destinazione",
  "locationSettingsNotConfigured": "Le impostazioni di posizione non sono configurate correttamente"
});