define({
  "_widgetLabel": "スマート エディター",
  "_featureAction_SmartEditor": "スマート エディター",
  "noEditPrivileges": "ご使用のアカウントには、データを作成/変更する権限がありません。",
  "widgetActive": "アクティブ",
  "widgetNotActive": "アクティブではない",
  "pressStr": "押す ",
  "ctrlStr": " Ctrl キー ",
  "snapStr": " スナップを有効にします",
  "noAvailableTempaltes": "利用可能なテンプレートがありません",
  "editorCache": " - エディターのキャッシュ",
  "presetFieldAlias": "フィールド",
  "presetValue": "設定済みの値",
  "usePresetValues": " 設定済みの値を使用 (新しいフィーチャのみ)",
  "editGeometry": " ジオメトリの編集",
  "savePromptTitle": "フィーチャの保存",
  "savePrompt": "現在のフィーチャを保存しますか？",
  "deletePromptTitle": "フィーチャの削除",
  "deleteAttachment": "添付ファイルの削除",
  "deletePrompt": "選択フィーチャを削除しますか？",
  "attachmentLoadingError": "アタッチメントのアップロード中にエラーが発生しました",
  "attachmentSaveDeleteWarning": "警告: アタッチメントへの変更は自動的に保存されます",
  "autoSaveEdits": "自動的に新しいフィーチャを保存",
  "addNewFeature": "新しいフィーチャの作成",
  "featureCreationFailedMsg": "新しいレコード/フィーチャを作成できません。",
  "relatedItemTitle": "関連テーブル/レイヤー",
  "relatedFeatureCount": "${featureCount} のフィーチャがある ${layerTitle}",
  "createNewFeatureLabel": "${layerTitle} の新しいフィーチャを作成",
  "invalidRelationShipMsg": "主キー フィールドを確認してください: '${parentKeyField}' に有効な値があります。",
  "pendingFeatureSaveMsg": "関連フィーチャを作成する前に、フィーチャの編集を保存してください。",
  "attachmentsRequiredMsg": "(*) アタッチメントが必要です。",
  "coordinatePopupTitle": "XY 位置にフィーチャを移動",
  "coordinatesSelectTitle": "座標系:",
  "mapSpecialReferenceDropdownOption": "マップの空間参照",
  "latLongDropdownOption": "緯度/経度",
  "mgrsDropdownOption": "MGRS (Military Grid Reference System)",
  "mgrsTextBoxLabel": "座標:",
  "xAttributeTextBoxLabel": "X 座標",
  "yAttributeTextBoxLabel": "Y 座標",
  "latitudeTextBoxLabel": "緯度:",
  "longitudeTextBoxLabel": "経度 :",
  "presetGroupFieldsLabel": "'${groupName}' は次のレイヤー フィールドに適用されます:",
  "presetGroupNoFieldsLabel": "'${groupName}' に関連フィールドがありません",
  "groupInfoLabel": "'${groupName}' のグループ情報",
  "editGroupInfoIcon": "${groupName} のグループ値を編集",
  "filterEditor": {
    "all": "すべて",
    "noAvailableTempaltes": "利用可能なテンプレートがありません",
    "searchTemplates": "テンプレートの検索",
    "filterLayerLabel": "レイヤーのフィルター"
  },
  "invalidConfiguration": "ウィジェットが構成されていないか、構成で指定されたレイヤーがマップ内に存在しません。アプリをビルダー モードで開き、ウィジェットを再構成してください。",
  "geometryServiceURLNotFoundMSG": "ジオメトリ サービスの URL を取得できません",
  "clearSelection": "閉じる",
  "refreshAttributes": "動的フィーチャ属性の更新",
  "automaticAttributeUpdatesOn": "フィーチャ属性の自動更新: ON",
  "automaticAttributeUpdatesOff": "フィーチャ属性の自動更新: OFF",
  "moveSelectedFeatureToGPS": "現在の GPS 位置に選択したフィーチャを移動",
  "moveSelectedFeatureToXY": "XY 位置に選択したフィーチャを移動",
  "mapNavigationLocked": "マップ ナビゲーション: ロック",
  "mapNavigationUnLocked": "マップ ナビゲーション: ロック解除",
  "copyFeatures": {
    "title": "フィーチャのコピー",
    "createFeatures": "フィーチャ作成",
    "createSingleFeature": "マルチジオメトリ フィーチャを 1 つ作成",
    "noFeaturesSelectedMessage": "フィーチャが選択されていません",
    "selectFeatureToCopyMessage": "コピーするフィーチャを選択してください。",
    "multipleFeatureSaveWarning": "注意: フィーチャのコピーを使用して複数のフィーチャを作成すると、すべてのフィーチャが直ちに保存されます",
    "copyFeatureUpdateGeometryError": "選択したフィーチャのジオメトリを更新できません",
    "canNotSaveMultipleFeatureWarning": "注意: 個別値フィールドに同じ値を使用して複数のフィーチャをコピーすることはできません。1 つのフィーチャのみを選択してください",
    "createOnlyOneMultipartFeatureWarning": "注意: 作成できるマルチパート フィーチャは 1 つのみです。"
  },
  "addingFeatureError": "レイヤー内で選択したフィーチャを追加中にエラーが発生しました。 もう一度お試しください。",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' フィーチャをコピーできませんでした。",
  "selectingFeatureError": "レイヤー内のフィーチャを選択中にエラーが発生しました。 もう一度お試しください。",
  "customSelectOptionLabel": "コピーするフィーチャを選択",
  "noFeatureSelectedMessage": "フィーチャが選択されていません。",
  "multipleFeatureSaveMessage": "すべてのフィーチャが直ちに保存されます。 続行しますか？",
  "relativeDates": {
    "dateTypeLabel": "日付タイプ",
    "valueLabel": "値",
    "fixed": "固定",
    "current": "現在",
    "past": "過去",
    "future": "未来",
    "popupTitle": "値の選択",
    "hintForFixedDateType": "ヒント: 指定した日付と時刻は、プリセットのデフォルト値として使用されます。",
    "hintForCurrentDateType": "ヒント: 現在の日付と時刻は、プリセットのデフォルト値として使用されます。",
    "hintForPastDateType": "ヒント: 指定した値が現在の日付と時刻から引かれて、プリセットのデフォルト値になります。",
    "hintForFutureDateType": "ヒント: 指定した値が現在の日付と時刻に追加されて、プリセットのデフォルト値になります。",
    "noDateDefinedTooltip": "日付が定義されていません",
    "relativeDateWarning": "デフォルトのプリセット値を保存できるようにするには、日付または時刻の値を指定する必要があります。",
    "customLabel": "カスタム",
    "layerLabel": "レイヤー",
    "domainFieldHintLabel": "選択した値はコード値ドメインです。 値: ${domainValue} が使用されます"
  },
  "valuePicker": {
    "popupTitle": "値の選択",
    "popupHint": "現在のフィーチャは、複数のフィーチャと交差しています。各フィールドの値を選択してください。",
    "buttonTooltip": "交差する複数のフィーチャから値を選択"
  },
  "uniqueValueErrorMessage": "\"${fieldName}\" の値はすでに存在します。新しい値を指定してください。",
  "requiredFields": {
    "displayMsg": "必須フィールドは空白のままにすることはできません。 以下の共通フィールドに値を入力します。",
    "popupTittle": "必須フィールド",
    "foundNullRecordCount": "${fieldName} (${count} 秒で検索)"
  },
  "cantLocateUserLocation": "現在の位置を特定できませんでした"
});