define({
  "_widgetLabel": "Analiza prijetnji",
  "threatAnalysisMainPageTitle": "Na temelju protuterorističkog vodiča JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ulazna lokacija",
  "interactive": "Interaktivno",
  "fromCoord": "Fiksne koordinate",
  "existingFeature": "Iz postojećih geoobjekata",
  "threatAnalysisCoordInputLabel": "Lokacija prijetnje",
  "enterCoords": "Unesi koordinate",
  "threatAddPointToolTip": "Dodaj lokaciju prijetnje",
  "threatDrawPointToolTip": "Kliknite da biste dodali lokaciju",
  "threatType": "Vrsta prijetnje",
  "threatPlaceholder": "Počnite tipkati za traženje prijetnje",
  "zoneTypeLabel": "Tip zone",
  "feetLabel": "Stope",
  "metersLabel": "Metri",
  "unitsLabel": "Jedinice",
  "threatGraphicLayer": "Grafika za prijetnju",
  "style": "Stil",
  "settingsTitle": "Postavke",
  "colorPicker": "birač boja",
  "lineStyles": {
    "esriSLSDash": "Linija s crticom",
    "esriSLSDashDot": "Linija s crticom i točkom",
    "esriSLSDashDotDot": "Linija s crticom i dvije točke",
    "esriSLSDot": "Točka",
    "esriSLSLongDash": "Duga crtica",
    "esriSLSLongDashDot": "Duga crtica i točka",
    "esriSLSNull": "Nema vrijednosti",
    "esriSLSShortDash": "Kratka crtica",
    "esriSLSShortDashDot": "Kratka crtica i točka",
    "esriSLSShortDashDotDot": "Kratka crtica i dvije točke",
    "esriSLSShortDot": "Kratka točka",
    "esriSLSSolid": "Puna linija"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unatrag",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Naprijed",
    "esriSFSHorizontal": "Vodoravni",
    "esriSFSNull": "Nema vrijednosti",
    "esriSFSSolid": "Puna linija",
    "esriSFSVertical": "Uspravno"
  },
  "resultsTitle": "Rezultati",
  "publishTABtn": "Objavi",
  "layerName": "Naziv objavljenog sloja",
  "invalidLayerName": "Naziv sloja mora sadržavati samo alfanumeričke znakove i podvlake",
  "missingLayerNameMessage": "Morate unijeti važeći naziv sloja prije objavljivanja",
  "publishingFailedLayerExists": "Objavljivanje nije uspjelo: već imate uslugu geoobjekata s nazivom {0}. Odaberite drugi naziv sloja.",
  "checkService": "Provjeri uslugu: {0}",
  "createService": "Stvori uslugu: {0}",
  "unableToCreate": "Nije moguće stvoriti: {0}",
  "addToDefinition": "Dodaj definiciji: {0}",
  "successfullyPublished": "Uspješno objavljen web-sloj",
  "successfullyAppended": "Novi geoobjekti uspješno su dodani web-sloju",
  "manageWebLayerText": "Upravljanje web-slojem",
  "userRole": "Nije moguće stvoriti uslugu jer korisnik nema dopuštenja",
  "retrieveExistingLayerError": "Nije moguće dohvatiti stavku {0}. Objavite pod drugim nazivom sloja",
  "publishToNewLayer": "Objava rezultata na novom sloju geoobjekta",
  "layerNameExists": "Naziv sloja već postoji. Izaberite drugi naziv sloja.",
  "pipeBombLabel": "Cijevna bomba",
  "suicideBombLabel": "Bomba za samoubilački napad",
  "briefcaseLabel": "Aktovka",
  "carLabel": "Automobil",
  "suvVanLabel": "SUV/KAMION",
  "smallDeliveryTruckLabel": "Mali kamion za dostavu",
  "containerWaterTruckLabel": "Kamion za prijevoz kontejnera/vode",
  "semiTrailerLabel": "Poluprikolica",
  "transparencyLabel": "Prozirnost",
  "outline": "Obris",
  "fill": "Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",
  "createBtn": "Stvori zone",
  "clearBtn": "Očisti",
  "invalidNumberMessage": "Unesena vrijednost nije valjana",
  "invalidRangeMessage": "Vrijednost mora biti veća od 0",
  "parseCoordinatesError": "Nije moguće parsirati koordinate. Provjerite unos.",
  "selectDrawModeLabel": "Odaberi način crtanja",
  "selectFeatureLabel": "Odaberite geoobjekt iz ovog sloja",
  "smallLPGTank": "Mali LPG spremnik",
  "largeLPGTank": "Veliki LPG spremnik",
  "commercialResidentialLPGTank": "Komercijalni/stambeni LPG spremnik",
  "smallLPGTruck": "Mali LPG kamion",
  "semiTankerLPG": "LPG polucisterna",
  "zoneDescriptionColLabel": "Opis zone",
  "distanceColLabel": "Udaljenosti",
  "zoneDescColLabel": "Opis zone",
  "descriptionLabel": "Opis",
  "editThreatZonePopupLabel": "Uredi simbologiju zone prijetnje",
  "symbologyColLabel": "Simbologija",
  "actions": "Radnje",
  "threatTypeSelectLabel": "Odaberite vrstu prijetnje:",
  "distanceLabel": "Udaljenost (${unitAbbr})",
  "layerCountHint": "Podsjetnik: bit će objavljen web-sloj s ${layerCount} slojem/slojeva geoobjekta.",
  "selectLabel": "Odaberi",
  "mandatoryLabel": "Obavezna udaljenost za evakuaciju",
  "safeLabel": "Sigurna udaljenost za evakuaciju",
  "fireBallDiameterLable": "Promjer vatrene kugle",
  "lpgSafeDistanceLable": "Sigurna udaljenost"
});