define({
  "locatorUrl": "URL lokatorja",
  "set": "Nastavi",
  "locatorName": "Ime lokatorja",
  "locatorExample": "Primer",
  "countryCode": "Šifre države ali regije",
  "eg": "npr. ",
  "countryCodeHint": "Če to vrednost pustite prazno, bo iskanje potekalo po vseh državah in regijah",
  "minCandidateScore": "Minimalna ocena kandidata",
  "minCandidateScoreHint": "Če to vrednost pustite prazno, bo uporabljena minimalna ocena kandidata 90",
  "enableSingleField": "Možnosti enega polja",
  "singleFieldHint": "Podatki o naslovu bodo v enem polju",
  "enableMultiField": "Možnosti več polj",
  "multiFieldHint": "Podatki o naslovu bodo v več poljih",
  "enableXYField": "Možnosti polja X/Y",
  "xyFieldHint": "Podatki bodo vsebovali vrednosti koordinat X/Y",
  "instructionGeocode": "Dodajte in konfigurirajte storitve lokatorja.",
  "invalidUrlTip": "URL ${URL} ni veljaven ali dostopen.",
  "geocodeTabLabel": "Nastavitve lokacije",
  "lookupList": "Imena polj za prepoznavanje",
  "isRecognized": "Imena polj v spodnji tabeli so samodejno prepoznana za to polje",
  "needsEditablePointLayers": "Spletna karta mora vsebovati vsaj en točkovni sloj za urejanje.",
  "editpageAlias": "Vzdevek",
  "configureFields": "Konfigurirajte polja sloja",
  "configureSingleFields": "Konfiguriraj polje z enim naslovom",
  "configureMultiFields": "Konfiguriraj polja z več naslovi",
  "configureXYFields": "Konfiguriraj polja X/Y",
  "noFields": "Uporabiti dejanje za urejanje, da opredelite eno ali več polj za prikaz",
  "display": "Prikaz",
  "duplicate": "Poišči podvojitev",
  "duplicateTip": "Po tem polju iščite identične vrednosti med izvorno datoteko in ciljnim slojem./n Ko je najdeno identično ujemanje, zapis iz datoteke ne bo najden in bo označen kot podvojitev.",
  "noSelectField": "Najprej izberite možnost geoobjektnega sloja",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (geografska dolžina)",
  "xyFieldsLabelY": "Y (geografska širina)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Pomik proti vzhodu",
  "northing": "Pomik proti severu",
  "lon": "G.D.",
  "lat": "G.Š.",
  "layerOptionHint": "Izberite sloj v katerega želite poslati podatke.",
  "layerFieldTitle": "Ciljni sloj",
  "tempSymbolHint": "Izberite simbol, ki bo uporabljen za prikaz geoobjektov.",
  "tempSymbolTitle": "Prikazni simbol",
  "maxRecords": "Maks. zapisov",
  "maxRecordsHint": "Maksimalno število zapisov za iskanje",
  "searchRadius": "Iskalni polmer",
  "searchRadiusHint": "Razdalje za iskanje podvojenih geoobjektov iz sloja",
  "requiresInteger": "Vnesite številsko vrednost.",
  "requiresInteger0100": "Vnesite številsko vrednost med 0 in 100",
  "requiresLocator": "Dodajte vsaj en veljaven lokator.",
  "layerFields": "Nastavitve sloja",
  "layerFieldsHint": "Določite polja iz ciljnega sloja, ki bodo preslikana v izvorna polja.",
  "locatorError": "Lokator je neveljaven ali nedostopen.",
  "optionNotMatch": "Možnosti polja niso dosledna po celotnih lokatorjih. Nadomestni način morda ne bo deloval kot pričakovano.",
  "targetLayerTabTitle": "Ciljni sloj",
  "locationSettingsTabTitle": "Nastavitve lokacije",
  "generalSettingsTabTitle": "Splošne nastavitve",
  "addTargetLayersLabel": "Dodajte ciljni sloj",
  "introductoryText": "Ustvarite vsebino z navodili za pripomoček",
  "defaultStartPageInstructions": "Ta pripomoček vam bo v pomoč pri obdelavi in pošiljanju podatkov iz datoteke v izbrani sloj na karti.<br/> <br/> Vrednosti znotraj datoteke morajo biti ločene z vejico, presledkom, podpičjem ali navpičnico.",
  "noTargetLayerConfiguredErrorMsg": "Noben ciljni sloj ni konfiguriran",
  "noFieldsForTargetLayer": "Nastavitve sloja niso opredeljene za ciljni sloj",
  "locationSettingsNotConfigured": "Nastavitve lokacije niso ustrezno konfigurirane"
});