define({
  "feedbackStyleLabel": "Стиль зворотнього зв’язку для відстані та напрямку",
  "showTabLabel": "Показати всі вкладки",
  "tabErrorMessage": "Виберіть принаймні одну вкладку в групі «Стиль зворотнього зв’язку для відстані та напрямку».",
  "lineLabel": "Лінія",
  "circleLabel": "Коло",
  "ellipseLabel": "Еліпс",
  "ringsLabel": "Кільця",
  "transparency": "Прозорість",
  "operationalLineLayerSelectLabel": "Оберіть робочий шар полілінії для лінійних і кільцевих результатів",
  "operationalPolygonLayerSelectLabel": "Оберіть робочий шар полігону для кругових і еліптичних результатів",
  "helpIconPolylineTooltip": "Робочий шар заповнюється шарами з поточної веб-карти, що відносяться до типу геометрії «полілінія».",
  "helpIconPolygonTooltip": "Робочий шар заповнюється шарами з поточної веб-карти, що відносяться до типу геометрії «полігон».",
  "feedbackResultsLayerLabel": "Шар результатів зворотнього зв’язку для відстані та напрямку",
  "editSymbologyHint": "Підказка: клацніть на значок попереднього перегляду, щоб змінити символи",
  "feedbackTextColorLabel": "Колір тексту напису зворотнього зв’язку",
  "feedbackTextSizeLabel": "Розмір тексту напису зворотнього зв’язку",
  "previewLabel": "Попередній перегляд",
  "lineSymbologyPopupTittle": "Умовні позначення лінії",
  "circleSymbologyPopupTittle": "Умовні позначення кола",
  "ellipseSymbologyPopupTittle": "Умовні позначення еліпсу",
  "ringSymbologyPopupTittle": "Умовні позначення кільця"
});