define({
  "_widgetLabel": "Agregació de dades",
  "startPage": {
    "defaultStartPageInstructions": "Aquest widget us ajudarà a processar i enviar dades d'un fitxer a la capa del mapa seleccionada.<br/> <br/> Els valors del fitxer han d'estar delimitats per comes, punts i coma, tabuladors o barres verticals.",
    "dragDrop": "Arrossega i deixa anar",
    "browse": "Ves al fitxer",
    "or": "OR",
    "userPrivilege": "El vostre compte no té permís per crear o modificar dades.",
    "userCredits": "${widgetName} necesita crèdits per fer servir el localitzador ${locator}.",
    "contactAdmin": "Poseu-vos en contacte amb l'administrador de l'organització per sol·licitar més crèdits.",
    "contactAdminEdit": "Poseu-vos en contacte amb l'administrador de l'organització per sol·licitar permisos d'edició.",
    "canUseLocator": "El localitzador ${locator} es farà servir per localitzar entitats.",
    "notEnoughCredits": "No hi ha prou crèdits.",
    "locationAndField": "Informació de les ubicacions i dels camps",
    "locationAndFieldHint": "Trieu els valors del fitxer que s'han de fer servir per actualitzar la capa de destinació.",
    "cannotUseLocator": "No es pot utilitzar ${widgetName}",
    "noAnonymousEdit": "La capa ${layerName} no admet l'edició anònima.",
    "pleaseLogin": "Inicieu la sessió a l'organització ${org} o poseu-vos en contacte amb l'administrador de l'organització per sol·licitar que s'habiliti l'edició anònima.",
    "invalidEdit": "Els privilegis no són vàlids",
    "unableToAccess": "No es pot accedir a ${layerName}",
    "appropriateCredentials": "Comproveu que hàgiu iniciat la sessió amb les credencials correctes.",
    "shared": "Poseu-vos en contacte amb l'administrador de l'organització per sol·licitar accés a la capa ${layerName}.",
    "targetLayerLabel": "Capa de destinació",
    "homeButtonLabel": "Inici",
    "mappingErrorMsg": "Feu clic a la fletxa Següent per definir els camps"
  },
  "mapping": {
    "schemaMapping": "Informació dels camps",
    "schemaMappingHint": "Trieu camps del fitxer que estiguin relacionats amb els camps de la capa.",
    "locationMapping": "Informació de les ubicacions",
    "locationMappingHint": "Trieu el tipus d'adreça o la informació de coordenades esperats del fitxer."
  },
  "locationMapping": {
    "locationMappingPageHint": "Trieu el tipus d'ubicació",
    "useAddress": "Localitza a partir d'una adreça",
    "useAddressHint": "Les dades contenen informació de l'adreça",
    "useCoordinates": "Localitza a partir de coordenades",
    "useCoordinatesHint": "Les dades contenen valors de coordenades X/Y"
  },
  "address": {
    "addressPageHint": "Trieu el tipus d'adreça",
    "singleField": "Camp únic",
    "singleFieldHint": "Trieu el camp que conté la informació de l'adreça",
    "multiField": "Diversos camps",
    "multiFieldHint": "Trieu els camps que contenen la informació de l'adreça"
  },
  "coordinates": {
    "coordinatesPageHint": "Trieu els camps que contenen les dades de coordenades"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Trieu el camp d'origen associat al camp de destinació",
    "sourceField": "Camp d'origen coincident",
    "targetField": "Camp de destinació"
  },
  "buttons": {
    "addToMap": "Afegeix al mapa",
    "submit": "Envia",
    "download": "Baixa"
  },
  "review": {
    "matched": "S'ha trobat",
    "reviewMatched": "S'han trobat ubicacions",
    "reviewMatchedHint": "Reviseu les ubicacions que s'han trobat.",
    "unMatched": "no s'ha trobat",
    "reviewUnMatched": "Ubicacions no trobades",
    "reviewUnMatchedHint": "Reviseu les ubicacions que no s'han trobat. Els elements que no es corregeixin no s'enviaran.",
    "duplicate": "Duplica",
    "reviewDuplicate": "Ubicacions duplicades",
    "reviewDuplicateHint": "Reviseu les ubicacions que ja s'havien trobat a la capa. Els elements que no es corregeixin no s'enviaran.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Ús:",
    "fromLayer": "Informació de la destinació",
    "target": "Objectiu",
    "source": "Origen",
    "fromFile": "Informació de l'origen",
    "locationControlHint": "Reviseu la informació d'adreces",
    "duplicateAction": "Trieu una acció",
    "item": "Registre:",
    "locateFeature": "Localitza l'entitat",
    "removeFeature": "Elimina l'entitat",
    "featureLocated": "S'ha trobat la ubicació",
    "valuesDoNotMatch": "No coincideix amb el valor actual",
    "sync": "Sincornitza la informació de l'adreça amb la informació del camp",
    "noFeaturesSaved": "No s'ha desat cap entitat correctament",
    "someFeaturesSaved": "Entitats desades correctament: ${num}.",
    "someFeaturesNotSaved": "Entitats no desades correctament: ${num}.",
    "feature": "Reviseu la informació de l'entitat",
    "locationInfo": "Reviseu la informació de la ubicació",
    "selectValue": "Seleccioneu un valor",
    "reviewData": "Reviseu les dades",
    "reviewDataHint": "Reviseu les dades abans d'enviar-les a la capa.",
    "reviewFeatureHint": "Reviseu o editeu la informació de les entitats i les ubicacions.",
    "duplicateModify": "Duplicat, cal canviar-ho",
    "duplicateSave": "Desa com una entitat nova"
  },
  "warningsAndErrors": {
    "invalidCSV": "S'ha produït un error en recuperar els elements del CSV; comproveu que s'hagi seleccionat un fitxer CSV vàlid.",
    "noLayersWarning": "No s'ha configurat cap capa de destinació vàlida; comproveu la configuració.",
    "loadWarning": "Aquest widget necessita una font de dades de servei d'entitats. Configureu el widget per definir la font de dades.",
    "saveError": "S'ha produït un error en desar les entitats.",
    "consumesCredits": "Aquesta eina consumeix crèdits quan es fa servir amb el servei de geocodificació mundial de l'ArcGIS Online",
    "noValue": "Seleccioneu un camp",
    "mappingTitle": "",
    "locationMappingComplete": "Representació geogràfica de les ubicacions completada",
    "fieldMappingComplete": "Representació geogràfica dels camps completada",
    "settingsCleared": "La configuració s'esborrarà.",
    "proceed": "Voleu continuar?",
    "itemMoveMatch": "L'element s'ha localitzat i s'ha mogut a la llista d'ubicacions trobades",
    "itemMoveUnMatched": "No s'ha pogut localitzar l'element. S'ha mogut a la llista d'ubicacions no trobades.",
    "itemWillBeLocated": "L'element s'eliminarà de la llista d'ubicacions duplicades.",
    "cannotLocate": "No s'ha pogut localitzar l'element. Verifiqueu la informació d'ubicació.",
    "invalidMessage": "El valor no és vàlid.",
    "rangeMessage": "El valor ha de tenir menys de ${num} caràcters.",
    "locatorError": "El localitzador no és vàlid o no s'hi pot accedir.",
    "notConfigured": "El localitzador no està configurat per a les ocpions de localització actuals",
    "noMoreLocators": "No s'ha configurat cap localitzador addicional"
  },
  "featureToolbar": {
    "locate": "Localitza",
    "save": "Desa el registre",
    "cancel": "Cancel·la les edicions",
    "cancelTitle": "Cancel·la les edicions",
    "cancelMessage": "Voleu cancel·lar les edicions del registre actual?"
  }
});