define({
  "taskUrl": "Taak-URL",
  "setTask": "Instellen",
  "setTaskPopupTitle": "Taak instellen",
  "validate": "Instellen",
  "inValidGPService": "Voer geldige geoprocessing service in.",
  "noOutputParameterWithGeometryType": "De geselecteerde geoprocessing service moet ten minste één uitvoerparameter met een gespecificeerd geometrietype hebben. Selecteer een andere geoprocessing service.",
  "invalidOutputGeometry": "Het uitvoertype van de geometrie van de geselecteerde geoprocessing service is niet compatibel met de projectinstellingen. De resultaten van de geoprocessing service kunnen niet worden opgeslagen.",
  "GPFeatureRecordSetLayerERR": "Voer alleen een geoprocessing service in met inputs van het type 'GPFeatureRecordSetLayer'.",
  "invalidInputParameters": "Het aantal inputparameters is minder dan 1 of meer dan 3. Voer een geldige geoprocessing service in.",
  "projectSetting": {
    "title": "Projectinstellingen",
    "note": "Opmerking: Projectinstellingen zijn optioneel, zodra ze zijn ingesteld kan de gebruiker een project opslaan in de gewenste webmaplagen met netwerkuitvalgebied en inputparameters. Gebruiker kan outputparameters uit het tabblad \"Output\" opslaan.",
    "projectPolygonLayer": "Project-polygoonlaag",
    "outputParameterName": "Naam outputparameter",
    "projectPointLayer": "Project-puntlaag",
    "selectLabel": "Selecteren",
    "polygonLayerHelp": "<p>Polygoonla(a)g(en) die voldoen aan de volgende voorwaarden zullen worden weergegeven:<br/><ul><li>Laag moet bewerkingsfuncties hebben, namelijk \"Creëren\", \"Verwijderen\" en \"Bijwerken\"</li><li>Laag moet 2 velden hebben met exacte naam en gegevenstype:</li><ul><li>naam (String type veld)</li><li>globalid (GlobalID type veld)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Output-polygoonla(a)g(en) uit de taak-URL worden weergegeven<p/>",
    "pointLayerHelp": "<p>Puntlaag die voldoet aan de volgende voorwaarden zal worden weergegeven: <br/><ul><li>Laag moet bewerkingsfuncties hebben, namelijk \"Creëren\", \"Verwijderen\" en \"Bijwerken\"</li><li>Laag moet twee velden hebben met naam en gegevenstypes:</li><ul><li>inputtype (String type veld)</li><li>projectid (GUID type veld)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Vlag",
    "barrier": "Barrière",
    "skip": "Overslaan",
    "title": "Invoer",
    "inputTooltip": "Knopinfo",
    "typeText": "Type",
    "symbol": "Symbool",
    "summaryEditorText": "Samenvattingstekst",
    "summaryTextTitle": "Geef tekst op die moet worden weergegeven voor het tabblad invoer."
  },
  "summaryTab": {
    "title": "Uitvoer",
    "summaryFieldsetText": "Samenvattingsinstellingen",
    "inputOutput": "Input/output",
    "field": "Veld",
    "operator": "Operator",
    "inputOperatorCountOption": "Aantal",
    "outputOperatorCountOption": "Aantal",
    "outputOperatorSkipCountOption": "TellingOverslaan",
    "fieldOperatorSumOption": "Som",
    "fieldOperatorMinOption": "Min",
    "fieldOperatorMaxOption": "Max",
    "fieldOperatorMeanOption": "Mediaan",
    "expressionAddButtonText": "Toevoegen",
    "expressionVerifyButtonText": "Verifiëren",
    "summaryEditorText": "Samenvattingstekst",
    "zoomText": "Autozoom na tracering",
    "summarSettingTooltipText": "Input/output-telling toevoegen",
    "symbol": "Symbool",
    "outputParametersText": "Outputparameters",
    "skipText": "Kan worden overgeslagen",
    "visibilityText": "Zichtbaar",
    "exportToCsvText": "Export to CSV",
    "settitngstext": "Instellingen",
    "saveToLayerText": "Opslaan in laag (optioneel)",
    "inputLabel": "Label",
    "inputTooltip": "Knopinfo",
    "outputDisplay": "Displaytekst",
    "addFieldTitle": "Veld toevoegen",
    "setScale": "Schaal instellen",
    "enterDisplayText": "Displaytekst invoeren",
    "saveToLayerHelp": "<p>Laag die voldoet aan de volgende voorwaarden zal worden weergegeven:<br/><ul><li>Laag moet bewerkingsfuncties hebben, namelijk \"Creëren\", \"Verwijderen\" en \"Bijwerken\"</li><li>Laag moet twee velden hebben met naam en gegevenstype:</li><ul><li>parameternaam (String type veld)</li><li>projectid (Guid type veld)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Geef samenvattingstekst op die moet worden weergegeven op het tabblad uitvoer.",
    "addSummaryItemsTitle": "Samenvattingsitems toevoegen"
  },
  "validationErrorMessage": {
    "webMapError": "Geen lagen beschikbaar in de webmap. Selecteer een geldige webmap.",
    "inputTypeFlagGreaterThanError": "Input van typevlag kan niet meer dan één zijn.",
    "inputTypeFlagLessThanError": "Ten minste één input van typevlag vereist.",
    "inputTypeBarrierErr": "Input van typebarrière kan niet meer dan één zijn.",
    "inputTypeSkipErr": "Input van type overslaan kan niet meer dan één zijn.",
    "displayTextForButtonError": "Displaytekst voor 'Uitvoeren'-knop kan niet leeg zijn.",
    "UnableToLoadGeoprocessError": "Niet in staat geoprocessing service te laden.",
    "invalidSummaryExpression": "Ongeldige expressie.",
    "validSummaryExpression": "Succes!",
    "invalidProjectSettings": "Ongeldige projectinstellingen.<br/> Selecteer een geldige waarde in '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Hint: Verschaf een displaylabel voor resultaatdeelvenster van outputparameter.",
    "displayTextHint": "Hint: Dit zal worden weergegeven in het detailsdeelvenster voor deze outputparameter.",
    "inputTextHint": "Hint: Stel uw expressie hieronder samen met de knop samenvattingsitems toevoegen.",
    "expressionHint": "Hint: Selecteer items en klik op Toevoegen om een expressie samen te stellen."
  }
});