define({
  "feedbackStyleLabel": "距离和方向反馈样式",
  "showTabLabel": "显示所有选项卡",
  "tabErrorMessage": "请在“距离和方向反馈样式”组中至少选择一个选项卡。",
  "lineLabel": "线",
  "circleLabel": "圆形",
  "ellipseLabel": "椭圆",
  "ringsLabel": "环",
  "transparency": "透明度",
  "operationalLineLayerSelectLabel": "为线和环结果选择业务折线图层",
  "operationalPolygonLayerSelectLabel": "为圆形和椭圆形结果选择业务面图层",
  "helpIconPolylineTooltip": "使用当前 web 地图中折线几何类型的图层来填充业务图层列表。",
  "helpIconPolygonTooltip": "使用当前 web 地图中面几何类型的图层来填充业务图层列表。",
  "feedbackResultsLayerLabel": "距离和方向反馈结果图层",
  "editSymbologyHint": "提示：单击预览图标可编辑符号系统",
  "feedbackTextColorLabel": "反馈标注文本颜色",
  "feedbackTextSizeLabel": "反馈标注文本大小",
  "previewLabel": "预览",
  "lineSymbologyPopupTittle": "线符号系统",
  "circleSymbologyPopupTittle": "圆圈符号系统",
  "ellipseSymbologyPopupTittle": "椭圆符号系统",
  "ringSymbologyPopupTittle": "环形符号系统"
});