define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Akses Infografis dan Laporan yang merangkum indikator kunci dan data untuk berbagai area.</div><br><div>Pilih titik atau poligon di peta, cari alamat atau tempat, gambar poligon, atau beri pin pada peta untuk menampilkan indikator kunci dan informasi tentang area tersebut.</div>",
  "defineWhichInfographics": "Tentukan infografis mana yang tersedia di widget:",
  "defineWhichReports": "Tentukan laporan mana yang tersedia di widget:",
  "defaultValues": "Nilai default:",
  "disable": "Nonaktifkan",
  "drawFreehandPolygon": "Gambar Poligon Bebas",
  "drawPolygon": "Gambar Poligon",
  "driveTime": "Waktu berkendara",
  "dropPin": "Letakkan Pin",
  "dynamicHTML": "HTML Dinamis",
  "exportOptions": "Ekspor Opsi:",
  "home": "Rumah",
  "image": "Citra",
  "infographics": "Infografis",
  "invalidValueRing": "Nilai harus berada dalam rentang 0 hingga 1.000.",
  "invalidValueDTWT": "Nilai harus berada dalam rentang 0 hingga 300.",
  "km": "km",
  "makeDefault": "Jadikan Default",
  "miles": "mil",
  "minutes": "menit",
  "options": "Opsi:",
  "pdf": "PDF",
  "print": "Cetak",
  "radius": "Radius",
  "removeDefault": "Hapus default",
  "reports": "Laporan",
  "rings": "Cincin",
  "searchTextBox": "Cari Kotak Teks",
  "selectCountryOrRegion": "Pilih negara atau wilayah:",
  "thisEntryIsNotValid": "Entri ini tidak valid.",
  "time": "Waktu",
  "walkTime": "Waktu berjalan"
});