define({
  root: ({
    locatorUrl: "Locator URL",
    set: "Set",
    locatorName: "Locator Name",
    locatorExample: "Example",
    countryCode: "Country or Region Code(s)",
    eg: "e.g. ",
    countryCodeHint: "Leaving this value blank will search all countries and regions",
    minCandidateScore: "Minimum Candidate Score",
    minCandidateScoreHint: "Leaving this value blank will use a minimum candidate score of 90",
    enableSingleField: "Single-field Options",
    singleFieldHint: "Address data will be in a single field",
    enableMultiField: "Multi-field Options",
    multiFieldHint: "Address data will be in multiple fields",
    enableXYField: "X/Y Field Options",
    xyFieldHint: "Data will contain X/Y coordinate values",
    instructionGeocode: "Add and configure locator services.",
    invalidUrlTip: "The URL ${URL} is invalid or inaccessible.",
    geocodeTabLabel: "Location Settings",
    lookupList: "Field Names to Recognize",
    isRecognized: "Field names in the table below are automatically recognized for this field",
    needsEditablePointLayers: "The webmap must contain at least one editable point layer.",
    editpageAlias: "Alias",
    configureFields: "Configure Layer Fields",
    configureSingleFields: "Configure a Single Address Field",
    configureMultiFields: "Configure Multiple Address Fields",
    configureXYFields: "Configure X/Y Fields",
    noFields: "Use the edit action to define one or more fields to display",
    display: "Display",
    duplicate: "Find Duplicate",
    duplicateTip: "Search this field for identical values between the source file and target layer./n When an identical match is found the record from the file will not be located and will be flagged as a duplicate.",
    noSelectField: "Select the Feature Layer option first",
    newNamePlaceholder: "",
    xyFieldsLabelX: "X (Longitude)",
    xyFieldsLabelY: "Y (Latitude)",
    xyFieldsX: "X",
    xyFieldsY: "Y",
    easting: "Easting",
    northing: "Northing",
    lon: "LON",
    lat: "LAT",
    layerOptionHint: "Choose the layer to submit data to.",
    layerFieldTitle: "Target Layer",
    tempSymbolHint: "Choose the symbol that will be used to display the features.",
    tempSymbolTitle: "Display Symbol",
    maxRecords: "Max records",
    maxRecordsHint: "Max number of records to locate",
    searchRadius: "Search radius",
    searchRadiusHint: "Distance to search for duplicate features from layer",
    requiresInteger: "Enter a numeric value.",
    requiresInteger0100: "Enter a numeric value between 0 and 100",
    requiresLocator: "Add at least one valid locator.",
    layerFields: "Layer Settings",
    layerFieldsHint: "Specify fields from the Target Layer that will be mapped to the source fields.",
    locatorError: "Locator is invalid or inaccessible.",
    optionNotMatch: "Field options not consistent across locators. Failover may not work as expected.",
    targetLayerTabTitle: "Target Layer",
    locationSettingsTabTitle: "Location Settings",
    generalSettingsTabTitle: "General Settings",
    addTargetLayersLabel: "Add Target Layer",
    introductoryText: "Create instructional content for the widget",
    defaultStartPageInstructions: "This widget will assist with processing and submitting data from a file to the selected layer in the map.<br/> <br/> Values within the file must be delimited by comma, tab, semi-colon, or vertical bar.",
    noTargetLayerConfiguredErrorMsg: "No target layer configured",
    noFieldsForTargetLayer: "Layer settings are not defined for the target layer",
    locationSettingsNotConfigured: "Location settings are not properly configured"
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});