define({
  "tabs_section_Label": "Раздели",
  "addTab": "Добавяне на раздел",
  "layerName": "Слой",
  "layerType": "Тип анализ",
  "layerLabel": "Етикет",
  "actions": "Действия",
  "closest": "Най-близкия обект",
  "proximity": "Приблизително",
  "summary": "Обобщение",
  "select_lbl": "-- Изберете--",
  "general_setting_Label": "Общи настройки",
  "units_text_lbl": "Единици за разстояние",
  "maximum_distance_lbl": "Максимално разстояние до най-близкия обект",
  "buffer_text_lbl": "Етикет на буфер",
  "buffer_lbl": "Буферно разстояние",
  "buffer_max_lbl": "Максимално буферно разстояние",
  "buffer_min_lbl": "Минимално буферно разстояние",
  "buffer_default_lbl": "Стандартно буферно разстояние",
  "not_less_than_max": "Разстоянието трябва да е по-малко от максималното буферно разстояние",
  "not_between": "Разстоянието трябва да е между минималното и максималното буферно разстояние",
  "not_more_than_min": "Разстоянието трябва да е по-голямо от минималното буферно разстояние",
  "not_valid_number": "Трябва да е валидно число",
  "invalid_value": "${type} стойност е невалидна",
  "routing_checkBox": "Активиране на маршрутизиране",
  "weather_removed_message": "Опциите за прогноза за времето вече не са налични за този изпълним модул.",
  "currentlySelectedLayer": "Изберете от слоевете на картата",
  "missingTabLabel": "Най-малко един раздел няма етикет",
  "missingLayerInWebMap": "Няма намерени оперативни слоеве.",
  "selectFields": "Избор на полета",
  "addField": "Добавяне на поле",
  "sum": "Сума",
  "min": "Минимални",
  "max": "Максимални",
  "avg": "Средни",
  "count": "БРОЙ",
  "area": "ОБЛАСТ",
  "length": "ДЪЛЖИНА",
  "count_checkBox": "Показва броя обекти",
  "area_checkBox": "Показва сумата от площта",
  "length_checkBox": "Показва сумата от дължината",
  "max_records": "Достигнат е максималния лимит",
  "save_label": "Опции за запазване",
  "save_checkbox": "Активиране на запазването",
  "report_label": "Опции на отчет",
  "report_checkbox": "Активиране на отчет",
  "csv_label": "CSV опции",
  "display_label": "Опции на индикатор",
  "display_checkbox": "Показване на обобщените обекти",
  "setSelectionColor": "Задаване на цвета за избор",
  "snapshot_label": "Опции на моментна снимка",
  "snapshot_checkbox": "Активиране на моментна снимка",
  "must_select_template": "Моля, изберете един от шаблоните за редактиране в Опции за запазване.",
  "count_label": "Брой етикети",
  "area_label": "Надпис на област",
  "length_label": "Дължина на надпис",
  "invalid_string_width": "Стойността е твърде дълга. ",
  "layer_type_not_supported": "Типът слой не се поддържа",
  "groupedSummary": "Групиран брой",
  "groupByField": "Групиране по поле",
  "labelType": "Добавяне на надпис",
  "prefix": "Като префикс",
  "suffix": "Като суфикс",
  "need_group_field": "Моля, използвайте действието за редактиране, за да дефинирате група по поле.",
  "fieldTitle": "Поле",
  "typeTitle": "Тип",
  "actionsTitle": "Действия",
  "save_point_checkbox": "Запазване на точки",
  "save_line_checkbox": "Запазване на линии",
  "save_poly_checkbox": "Запазване на полигони",
  "no_valid_popup_fields": "Няма валидни полета в изскачащия прозорец. Моля, използвайте действието за редактиране, за да дефинирате поле.",
  "no_valid_fields": "Няма валидни полета. Моля, използвайте действието за редактиране, за да дефинирате опциите за показване.",
  "incident_label": "Етикет на раздел",
  "locate_incident_label": "Етикет на област на интерес",
  "incident": "Инцидент",
  "locate_incident": "Локализиране на инцидент",
  "buffer_value": "Буферно разстояние",
  "tab_options": "Анализи",
  "export_options": "Изход",
  "instruction_save": "Запазете местоположението в услуга с обекти.",
  "instruction_snapshot": "Създайте уеб карта въз основа на местоположението.",
  "instruction_report": "Създайте отпечатан отчет на местоположението.",
  "instruction_all_fields": "Експортирайте полета с изтегляне на CSV.",
  "data_label": "Изходни настройки на данни",
  "layer_error": "Слоят липсва или е невалиден.",
  "visibility_checkBox": "Деактивиране на управлението на видимостта на слоя",
  "allFieldsLabel": "Всички полета",
  "configuredPopUpFieldsLabel": "Конфигурирани изскачащи полета",
  "analysisTypeFieldsLabel": "Тип на полета за анализ",
  "reportOptionsMsg": "Трябва да бъде избрана поне една опция за отчет",
  "analysisSummaryLabelForReport": "Обобщение на типа анализ",
  "popUpSummaryLabelForReport": "Резюме на конфигурираните изскачащи полета",
  "downloadTab": {
    "reportLegend": "Настройки на отчет",
    "textColorLabel": "Изберете цвят за заглавката на колоната",
    "setButtonLabel": "Настройване",
    "printGPServiceLabel": "URL адрес на услугата за печат",
    "logoLabel": "Лого",
    "logoChooserHint": "Натиснете иконата за изображение, за да промените изображението",
    "footnoteLabel": "Бележка под линия"
  },
  "roundValue": "Закръгляне към",
  "roundValueTitle": "Закръгляне стойностите на поле",
  "truncateValue": "Съкращаване на",
  "truncateValueTitle": "Съкратете стойностите на полетата",
  "significantFigures": "значими цифри",
  "fieldOptions": "Опции на поле",
  "modifyValues": "Променете стойностите на полетата",
  "validatePlaces": "Трябва да е цяло число",
  "onlyDouble": "Допълнителни опции на полета се поддържат само за числови полета.",
  "layerNotAvalible": "Не е открит слой",
  "missingLayer": "Име: ${name}",
  "missingLayerHint": "Понастоящем не са налични един или повече слоеве, посочени в тази конфигурация.",
  "drawGeodesic": "Изчертаване на геодезични форми",
  "show1KSeparatorLabel": "Показване на разделител за 1000"
});