define({
  "_widgetLabel": "Trình biên tập Thông minh",
  "_featureAction_SmartEditor": "Trình biên tập Thông minh",
  "noEditPrivileges": "Tài khoản của bạn không có quyền tạo hoặc sửa đổi dữ liệu.",
  "widgetActive": "Hoạt động",
  "widgetNotActive": "Không Hoạt động",
  "pressStr": "Nhấn ",
  "ctrlStr": " CTRL ",
  "snapStr": " để bật tính năng chụp ảnh nhanh",
  "noAvailableTempaltes": "Không có mẫu khả dụng",
  "editorCache": " - Bộ nhớ cache Trình biên tập",
  "presetFieldAlias": "Trường",
  "presetValue": "Giá trị Đặt trước",
  "usePresetValues": " Sử dụng giá trị thiết lập trước (chỉ các đối tượng mới)",
  "editGeometry": " Chỉnh sửa Hình học",
  "savePromptTitle": "Lưu đối tượng",
  "savePrompt": "Bạn có muốn lưu đối tượng hiện tại không?",
  "deletePromptTitle": "Xóa đối tượng",
  "deleteAttachment": "Xóa tệp đính kèm",
  "deletePrompt": "Bạn có chắc chắn muốn xóa đối tượng được chọn không?",
  "attachmentLoadingError": "Đã xảy ra lỗi khi tải lên tệp đính kèm",
  "attachmentSaveDeleteWarning": "Cảnh báo: Tự động lưu các thay đổi với tệp đính kèm",
  "autoSaveEdits": "Tự động lưu đối tượng mới",
  "addNewFeature": "Tạo đối tượng mới",
  "featureCreationFailedMsg": "Không thể tạo bản ghi/đối tượng mới",
  "relatedItemTitle": "Bảng/lớp liên quan",
  "relatedFeatureCount": "${layerTitle} với ${featureCount} đối tượng",
  "createNewFeatureLabel": "Tạo đối tượng mới cho ${layerTitle}",
  "invalidRelationShipMsg": "Vui lòng đảm bảo trường khóa chính: '${parentKeyField}’ chứa giá trị hợp lệ",
  "pendingFeatureSaveMsg": "Vui lòng lưu các chỉnh sửa đối tượng trước khi tạo đối tượng liên quan.",
  "attachmentsRequiredMsg": "(*) Bắt buộc thêm tệp đính kèm.",
  "coordinatePopupTitle": "Di chuyển đối tượng đến vị trí XY",
  "coordinatesSelectTitle": "Hệ Tọa độ:",
  "mapSpecialReferenceDropdownOption": "Tham chiếu Không gian Bản đồ",
  "latLongDropdownOption": "Vĩ độ/Kinh độ",
  "mgrsDropdownOption": "Hệ thống Tham chiếu Không gian Quân sự (MGRS)",
  "mgrsTextBoxLabel": "Tọa độ:",
  "xAttributeTextBoxLabel": "Tọa độ X:",
  "yAttributeTextBoxLabel": "Tọa độ Y:",
  "latitudeTextBoxLabel": "Vĩ độ:",
  "longitudeTextBoxLabel": "Kinh độ:",
  "presetGroupFieldsLabel": "'${groupName}' sẽ được áp dụng cho các trường lớp sau:",
  "presetGroupNoFieldsLabel": "'${groupName}' không có trường nào được liên kết",
  "groupInfoLabel": "Thông tin nhóm cho '${groupName}'",
  "editGroupInfoIcon": "Chỉnh sửa giá trị nhóm cho ${groupName}",
  "filterEditor": {
    "all": "Tất cả",
    "noAvailableTempaltes": "Không có mẫu khả dụng",
    "searchTemplates": "Mẫu Tìm kiếm",
    "filterLayerLabel": "Lớp lọc"
  },
  "invalidConfiguration": "Tiện ích chưa được cấu hình hoặc lớp trong cấu hình không còn trong bản đồ. Vui lòng mở ứng dụng trong chế độ bộ thiết lập và cấu hình lại tiện ích.",
  "geometryServiceURLNotFoundMSG": "Không thể nhận URL Dịch vụ hình học",
  "clearSelection": "Đóng",
  "refreshAttributes": "Cập nhật các thông tin thuộc tính cho đối tượng động",
  "automaticAttributeUpdatesOn": "Tự động cập nhật thông tin thuộc tính đối tượng: BẬT",
  "automaticAttributeUpdatesOff": "Tự động cập nhật thông tin thuộc tính đối tượng: TẮT",
  "moveSelectedFeatureToGPS": "Di chuyển đối tượng đã chọn đến vị trí GPS hiện tại",
  "moveSelectedFeatureToXY": "Di chuyển đối tượng đã chọn đến vị trí XY",
  "mapNavigationLocked": "Điều hướng Bản đồ: Khóa",
  "mapNavigationUnLocked": "Điều hướng Bản đồ: Mở khóa",
  "copyFeatures": {
    "title": "Sao chép Đối tượng",
    "createFeatures": "Tạo Đối tượng",
    "createSingleFeature": "Tạo 1 Đối tượng Đa hình học",
    "noFeaturesSelectedMessage": "Không có Đối tượng nào được chọn",
    "selectFeatureToCopyMessage": "Hãy chọn đối tượng để sao chép.",
    "multipleFeatureSaveWarning": "Lưu ý: Tạo nhiều đối tượng bằng cách sao chép đối tượng sẽ lưu tất cả các đối tượng ngay lập tức",
    "copyFeatureUpdateGeometryError": "Không thể cập nhật hình học của đối tượng được chọn",
    "canNotSaveMultipleFeatureWarning": "Lưu ý: Không thể sao chép nhiều đối tượng sử dụng cùng một giá trị cho các trường giá trị duy nhất, vui lòng chỉ chọn một đối tượng",
    "createOnlyOneMultipartFeatureWarning": "Lưu ý: Chỉ có thể tạo một đối tượng nhiều phần"
  },
  "addingFeatureError": "Lỗi xảy ra khi thêm các đối tượng được chọn vào lớp. Vui lòng thử lại.",
  "addingFeatureErrorCount": "Không thể sao chép '${copyFeatureErrorCount}' đối tượng.",
  "selectingFeatureError": "Lỗi xảy ra khi chọn các đối tượng trong lớp. Vui lòng thử lại.",
  "customSelectOptionLabel": "Chọn đối tượng để sao chép",
  "noFeatureSelectedMessage": "Không có đối tượng nào được chọn.",
  "multipleFeatureSaveMessage": "Tất cả đối tượng sẽ được lưu ngay lập tức. Bạn có muốn tiếp tục?",
  "relativeDates": {
    "dateTypeLabel": "Loại Ngày",
    "valueLabel": "Giá trị",
    "fixed": "Cố định",
    "current": "Hiện tại",
    "past": "Quá khứ",
    "future": "Tương lai",
    "popupTitle": "Chọn Giá trị",
    "hintForFixedDateType": "Gợi ý: Ngày và giờ chỉ định sẽ được sử dụng làm giá trị mặc định đặt trước.",
    "hintForCurrentDateType": "Gợi ý: Ngày và giờ hiện tại sẽ được sử dụng làm giá trị mặc định đặt trước.",
    "hintForPastDateType": "Gợi ý: Giá trị chỉ định sẽ được trừ đi từ ngày và giờ hiện tại để tính giá trị đặt trước mặc định.",
    "hintForFutureDateType": "Gợi ý: Giá trị chỉ định sẽ được trừ cộng vào ngày và giờ hiện tại để tính giá trị đặt trước mặc định.",
    "noDateDefinedTooltip": "Không xác định ngày",
    "relativeDateWarning": "Bạn phải chỉ định giá trị ngày hoặc thời gian để có thể lưu giá trị cài đặt sẵn mặc định.",
    "customLabel": "Tùy chỉnh",
    "layerLabel": "Lớp",
    "domainFieldHintLabel": "Giá trị được chọn là một miền giá trị mã hóa. Giá trị: ${domainValue} sẽ được sử dụng"
  },
  "valuePicker": {
    "popupTitle": "Chọn Giá trị",
    "popupHint": "Đối tượng hiện tại đang giao cắt với nhiều tối tượng, vui lòng chọn giá trị cho trường tương ứng",
    "buttonTooltip": "Chọn giá trị từ nhiều đối tượng giao cắt"
  },
  "uniqueValueErrorMessage": "Giá trị trong \"${fieldName}\" đã tồn tại, vui lòng cung cấp một giá trị mới.",
  "requiredFields": {
    "displayMsg": "Không được để trống các trường bắt buộc. Cung cấp giá trị cho các trường phổ biến bên dưới.",
    "popupTittle": "Trường bắt buộc",
    "foundNullRecordCount": "${fieldName}(Tìm thấy trong ${count} bản ghi)"
  },
  "cantLocateUserLocation": "Không thể xác định vị trí của bạn"
});