define({
  "instruction": "Käynnistyskuva tulee näkyviin, ennen kuin sovellusta voi käyttää.",
  "defaultContent": "Lisää tähän tekstiä, linkkejä ja pieniä kuvia.",
  "requireConfirm": "Edellytä vahvistamista ennen jatkamista",
  "noRequireConfirm": "Älä edellytä vahvistamista ennen jatkamista",
  "optionText": "Vaihtoehto, jolla käyttäjä voi poistaa aloitusnäytön käytöstä sovelluksen käynnistyessä.",
  "confirmLabel": "Vahvistustekstit: ",
  "confirmLabelColor": "Vahvistustekstien väri",
  "defaultConfirmText": "Hyväksyn edellä esitetyt käyttöehdot",
  "confirmOption": "Näytä aina tämä käynnistyskuva sovelluksen käynnistyessä",
  "backgroundColor": "Taustaväri",
  "content": "Sisältö",
  "contentDescription": "Määritä käynnistyskuvassa näkyvä sisältö.",
  "appearance": "Ulkoasu",
  "appearanceDescription": "Määritä käynnistyskuvan ulkoasu.",
  "size": "Koko",
  "width": "Leveys",
  "height": "Korkeus",
  "custom": "Mukautettu",
  "background": "Tausta",
  "colorFill": "Väritäyttö",
  "imageFill": "Kuvatäyttö",
  "chooseFile": "Valitse tiedosto",
  "noFileChosen": "Yhtään tiedostoa ei ole valittu",
  "transparency": "Läpinäkyvyys",
  "sizeFill": "Täyttö",
  "sizeFit": "Sovita",
  "sizeStretch": "Täytä venyttämällä",
  "sizeCenter": "Keskitä",
  "sizeTile": "Vierekkäin",
  "buttonColor": "Painikkeen väri",
  "buttonText": "Painikkeen teksti",
  "buttonTextColor": "Painikkeen tekstin väri",
  "contentAlign": "Sisällön kohdistus",
  "alignTop": "Yläosa",
  "alignMiddle": "Keskikohta",
  "maskColor": "Maskin väri",
  "options": "Asetukset",
  "optionsDescription": "Määritä käynnistyskuvan toiminta."
});