define({
  "_widgetLabel": "Мрежова графика за справка",
  "newGRGFromAreaButtonLabel": "Определяне на мрежа от област",
  "newGRGFromPointButtonLabel": "Определяне на мрежа от точка",
  "defineGridFromAreaDesc": "Създайте мрежи, като дефинирате областта по размер или по референтна система",
  "defineGridFromAreaDimensionDesc": "Създайте мрежа от дефиниран от потребителя ограничаващ правоъгълник и определена широчина и височина на клетката или брой хоризонтални и вертикални клетки",
  "defineGridFromaAreaRefSystemDesc": "Създайте мрежа от дефиниран от потребителя ограничаващ правоъгълник, базирана на система за справка",
  "defineGridFromPointDesc": "Използвайте точка, за да създадете мрежи, определени от точка по размер, референтна система или време и скорост",
  "defineGridFromPointByDimensionDesc": "Създайте мрежа от дефинирана от потребителя точка, ръчно въведена или интерактивно избрана, въз основа на броя хоризонтални и вертикални клетки и широчината и височината на клетката",
  "defineGridFromPointByRefSystemDesc": "Създайте мрежа от дефинирана от потребителя точка, ръчно въведена или интерактивно избрана, въз основа на референтна система",
  "defineGridFromPointTimeSpeedDesc": "Създайте мрежа от дефинирана от потребителя точка, ръчно въведена или интерактивно избрана, на базата на времето и скоростта",
  "newGRGFromAreaTitle": "Определете мрежа от област",
  "newGRGFromPointTitle": "Определяне на мрежа от точка",
  "newGRGBySizeButtonLabel": "По размер",
  "newGRGFromRefSystemButtonLabel": "По референтна система",
  "newGRGByTimeLabel": "По време и скорост",
  "newGRGFromNonStandardButtonLabel": "Определяне на нестандартна схема",
  "newGRGAreaBySizeTitle": "GRG от област по размер",
  "newGRGAreaBySizeDefineAreaLabel": "GRG област",
  "addGRGAreaPolygonToolTip": "Изчертайте GRG област с помощта на полигон",
  "addGRGAreaExtentToolTip": "Изчертайте GRG област с помощта на ограничаващ правоъгълник",
  "rotation": "Завъртане на мрежа",
  "numberRowsColumnsLabel": "Определяне на броя на редовете и колоните",
  "newGRGAreaByRefSystemTitle": "GRG от област по референтна система",
  "gridSize": "Размер на мрежа",
  "UTMZoneandBand": "Зона на мрежа",
  "100000m": "100 000 метър",
  "10000m": "10 000 метър",
  "1000m": "1000 метър",
  "100m": "100 метър",
  "10m": "10 метър",
  "clipGrid": "Изрязване на мрежа на GRG област",
  "newGRGAreaFromNonStandardTitle": "Нова NRG",
  "newGRGPointBySizeTitle": "GRG от точка по размер",
  "newGRGPointByRefSystemTitle": "GRG от точка по система за справка",
  "newGRGPointByTimeTitle": "GRG от точка с помощта на време и скорост",
  "time": "Време",
  "rate": "Скорост",
  "hours": "Часове",
  "minutes": "Минути",
  "seconds": "Секунди",
  "ftPerSec": "Фута / секунда",
  "ftPerHour": "Фута / час",
  "kmPerSec": "Километри / секунда",
  "kmPerHour": "Километри/час",
  "mPerSec": "Метри / секунда",
  "mPerHour": "Метри / час",
  "miPerSec": "Мили / секунда",
  "miPerHour": "Мили / час",
  "nMPerSec": "Морски мили / секунда",
  "nMPerHour": "Морски мили / час",
  "settingsTitle": "Настройки",
  "labelSettingsLabel": "Настройки на надпис",
  "labelSettingsButtonLabel": "Настройки за конфигурация на етикет",
  "gridSettingsLabel": "Настройки на мрежа",
  "gridSettingsButtonLabel": "Настройки за конфигуриране на мрежа",
  "transparency": "Прозрачност",
  "labelStyle": "Стил на надпис",
  "font": "Шрифт",
  "textSize": "Размер на текст",
  "textColor": "Цвят на текст",
  "halo": "Оконтурявне",
  "show": "Показване",
  "lockSettings": "Настройките са заключени от собственика на приложението",
  "gridSettings": {
    "cellShape": "Форма на клетка",
    "cellUnits": "Мерни единици за клетка",
    "cellOutline": "Настройки за контур на клетка",
    "cellFill": "Настройки за попълване на клетка",
    "gridReferenceSystem": "Референтна система",
    "gridDatum": "Данни: Световна геодезическа система 1984 г. (WGS84)",
    "labelStartPosition": "Оригинален надпис",
    "labelType": "Тип надпис",
    "labelDirection": "Посока на надпис",
    "gridOrigin": "Начална точка на мрежа",
    "default": "Правоъгълник",
    "hexagon": "Шестоъгълник",
    "miles": "Мили",
    "kilometers": "Километри",
    "feet": "Фута",
    "meters": "Метри",
    "yards": "Ярда",
    "nautical-miles": "Морски мили",
    "lowerLeft": "Долен ляв ъгъл",
    "lowerRight": "Долен десен ъгъл",
    "upperLeft": "Горен ляв ъгъл",
    "upperRight": "Горен десен ъгъл",
    "center": "Центриран",
    "alphaNumeric": "Алфа-Цифрови данни",
    "alphaAlpha": "Алфа-Алфа",
    "numeric": "Цифрови данни",
    "horizontal": "Хоризонтално",
    "vertical": "Вертикално",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "UTM": "UTM (Универсална напречна проекция на Меркатор)",
    "showLabels": "Показване на надписи",
    "colorPicker": "Избор на цвят",
    "bold": "Удебелен шрифт",
    "italic": "Курсивен шрифт",
    "underline": "Подчертан текст"
  },
  "publishTitle": "Публикуване на GRG в Portal",
  "publishGRGBtn": "Публикуване",
  "GRGLayerName": "Име на слой на публикувана GRG",
  "invalidGRGLayerName": "Името на слоя трябва да съдържа само буквено-цифрови знаци и долни черти",
  "publishWorskpaceError": "ГРЕШКА: Грешка при отваряне на работно място",
  "publishToNewLayer": "Публикуване на резултати на нов обектен слой",
  "publishingFailedLayerExists": "Неуспешно публикуване: Вече има услуга с обекти с това име {0}. Моля, изберете друго име.",
  "checkService": "Поставете отметка на услугата: {0}",
  "createService": "Създаване на услуга: {0}",
  "unableToCreate": "Не може да се създаде: {0}",
  "addToDefinition": "Добавяне към дефиниция: {0}",
  "successfullyPublished": "Успешно публикуван уеб слой {0}Управление на уеб слоя",
  "userRole": "Не може да се създаде услуга, тъй като потребителят няма разрешения",
  "layerNameExists": "Името на слоя вече съществува. Моля, използвайте различно име на слой.",
  "createGRGBtn": "Създаване на GRG",
  "clearGRGBtn": "Изчистване",
  "labelFormat": "Формат на етикет",
  "helpIconTooltip": "Z: Обозначение на мрежовата зона (GZD)\nS: ${number}-метър Идентификация на мрежовите квадрати (GSID)\nX: На изток (X координата)\nY: На север (Y координата)\n\nПримери:\nZSXY е 15SWC8081751205\nZS X,Y е 15SWC 80817,51205",
  "addPointToolTip": "Добавяне на начална точка на GRG",
  "cellWidth": "Ширина на клетка (x)",
  "cellHeight": "Височина на клетка (y)",
  "invalidNumberMessage": "Въведената стойност не е валидна",
  "invalidRangeMessage": "Стойността трябва да бъде по-голяма от 0",
  "gridAngleInvalidRangeMessage": "Стойността трябва да бъде между -89.9 и 89.9",
  "formatIconTooltip": "Формат на въвеждане",
  "coordInputLabel": "Начална точка на GRG",
  "setCoordFormat": "Задайте низ за формат на координати",
  "prefixNumbers": "Добавете префикса „+/-“ съответно за положителни и отрицателни числа",
  "cancelBtn": "Отказ",
  "applyBtn": "Прилагане",
  "comfirmInputNotation": "Потвърждаване на нотацията за входни данни",
  "notationsMatch": "нотациите съответстват на въведеното от вас, моля, потвърдете кое бихте искали да използвате:",
  "numberOfCellsHorizontal": "# Хоризонтални клетки",
  "numberOfCellsVertical": "# Вертикални клетки",
  "gridAngle": "Завъртане на мрежа",
  "tooManyCellsErrorMessage": "Опитвате се да създадете мрежа, състояща се от повече от 2000 клетки. Препоръчително е да намалите броя на създаваните клетки, като промените размера на мрежата или площта на мрежата.",
  "missingParametersMessage": "<p>Формулярът за създаване на GRG има липсващи или невалидни параметри, моля, проверете:</p><ul><li>Начертана е област GRG.</li><li>Широчината и височината на клетката съдържат валидни стойности.</li></ul>",
  "missingOriginParametersMessage": "<p>Формулярът за създаване на GRG има липсващи или невалидни параметри, моля, проверете:</p><ul><li>Настроена е начална точка на GRG.</li><li>Въведените данни за време, скорост и ъгъл съдържат валидни стойности.</li></ul>",
  "projectionNotSupported": "Вашият браузър не поддържа WebAssembly. Поддръжката на WebAssembly е необходима, тъй като този изпълним модул използва механизма за прожектиране от страна на клиента за създаване на GRG.",
  "invalidWidthHeightParametersMessage": "<p>Формулярът за създаване на GRG има липсващи и невалидни стойности. Уверете се, че въведените стойности за широчина и височина на клетката съдържат валидни стойности.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Формулярът за създаване на GRG има липсващи или невалидни параметри. Уверете се, че броят на клетките по хоризонталата и по вертикалата съдържа валидни стойности.</p>",
  "drawPointToolTip": "Натиснете, за да добавите начална точка за GRG",
  "missingLayerNameMessage": "Трябва да въведете валидно име на слой, преди да можете да публикувате",
  "parseCoordinatesError": "Не може да се прави разбор на координатите. Моля, проверете входните си данни.",
  "grgPolarRegionError": "Ограничаващият правоъгълник на GRG е в рамките на полярния регион. Клетки, които попадат в полярната област, няма да бъдат създадени.",
  "grgPolarOriginError": "Началната точка на GRG не може да се намира в полярна област, когато се създава GRG по референтна система.",
  "deleteBtn": "Изтриване",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDРев.",
  "DDMRev": "DDMРев.",
  "DMSRev": "DMSРев.",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM (Универсална напречна проекция на Меркатор)",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Десетични градуси – географска ширина/географска дължина",
  "DDLongLatNotation": "Десетични градуси – географска дължина/географска ширина",
  "DDMLatLongNotation": "Десетични градуси минути – геаографска ширина/географска дължина",
  "DDMLongLatNotation": "Десетични градуси минути – географска дължина/географска ширина",
  "DMSLatLongNotation": "Десетични градуси секунди – географска ширина/географска дължина",
  "DMSLongLatNotation": "Десетични градуси секунди – географска дължина/географска ширина",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Буква на честотна лента",
  "UTMHemNotation": "UTM - Полукълбо (С/Ю)"
});