define({
  "_widgetLabel": "Chytrá editace",
  "_featureAction_SmartEditor": "Chytrá editace",
  "noEditPrivileges": "Váš online účet nemá přístupová práva k vytváření nebo úpravě dat.",
  "loginPopupTitle": "Přihlásit",
  "loginPopupMessage": "${widgetName} vyžaduje oprávnění a kredity pro vyhledání a ukládání informací o adrese. Chcete se přihlásit a používat tuto funkcionalitu?",
  "noCreditsOrPrivilegeWarningMessage": "Váš účet nemá oprávnění a kredity pro vyhledání a ukládání informací o adrese pomocí ${widgetName}. Pokud chcete požádat o oprávnění a kredity, obraťte se na administrátora vaší organizace.",
  "unableToUseLocator": "Lokátor není dostupný. Akce související s atributy adres nebudou provedeny.",
  "locatorDisabledWaning": "Lokátor není povolen. Pokud chcete využívat tuto funkcionalitu, obraťte se na administrátora vaší organizace.",
  "noFeatureInAIWarning": "Žádné prvky nebyly vybrány. Vyberte prvek, který chcete upravit, nebo klikněte na Storno pro návrat na hlavní obrazovku.",
  "noEditableLayerWarning": "Váš účet nemá oprávnění vytvářet či upravovat data nebo tato webová mapa neobsahuje žádné editovatelné vrstvy.",
  "noVisibleCreateLayerWarning": "Vrstvy nejsou na této úrovni přiblížení viditelné. Přiblížit nebo oddálit pro vytvoření/úpravu prvků.",
  "noVisibleUpdateLayerWarning": "Vrstvy nejsou na této úrovni přiblížení viditelné. Přiblížit nebo oddálit pro úpravu prvků.",
  "checkLayerVisibilityInWebMapWarning": "Pro vytvoření nebo úpravu prvků zkontrolujte, že vrstvy jsou viditelné v mapě.",
  "showSelectionInAITitle": "Vybrané prvky",
  "showSelectionInAIMsg": "Chcete načíst aktuální výběr do ${widgetName}?",
  "widgetActive": "Aktivní",
  "widgetNotActive": "Neaktivní",
  "pressStr": "Stisknutím ",
  "ctrlStr": " CTRL ",
  "snapStr": " aktivujete přichytávání.",
  "noAvailableTempaltes": "Žádné šablony nejsou k dispozici.",
  "editorCache": " – cache editoru",
  "presetFieldAlias": "Pole",
  "presetValue": "Přednastavená hodnota",
  "usePresetValues": " Použít přednastavené hodnoty (pouze nové prvky)",
  "editGeometry": " Upravit geometrii",
  "savePromptTitle": "Uložit prvek",
  "savePrompt": "Přejete si uložit aktuální prvek?",
  "deletePromptTitle": "Odstranit prvek",
  "deleteAttachment": "Smazat přílohu",
  "deletePrompt": "Určitě chcete odstranit vybraný prvek?",
  "attachmentLoadingError": "Při nahrávání příloh došlo k chybě.",
  "attachmentSaveDeleteWarning": "Varování: Změny příloh se automaticky uloží.",
  "autoSaveEdits": "Automaticky ukládat nové prvky",
  "addNewFeature": "Vytvořit nový prvek",
  "featureCreationFailedMsg": "Nelze vytvořit nový záznam/prvek",
  "relatedItemTitle": "Související tabulka/vrstva",
  "relatedFeatureCount": "${layerTitle} s ${featureCount} prvky",
  "createNewFeatureLabel": "Vytvořit nový prvek pro ${layerTitle}",
  "invalidRelationShipMsg": "Ujistěte se prosím, že primární klíčové pole: ‚${parentKeyField}‘ obsahuje platnou hodnotu",
  "pendingFeatureSaveMsg": "Před tím, než vytvoříte související prvek, uložte prosím editaci prvku.",
  "attachmentsRequiredMsg": "(*) Jsou vyžadovány přílohy.",
  "coordinatePopupTitle": "Přesunout prvek na umístění XY",
  "coordinatesSelectTitle": "Souřadnicový systém:",
  "mapSpecialReferenceDropdownOption": "Souřadnicový systém mapy",
  "latLongDropdownOption": "zeměpisné šířky/délky",
  "mgrsDropdownOption": "Referenční systém vojenské sítě (MGRS)",
  "mgrsTextBoxLabel": "Souřadnice:",
  "xAttributeTextBoxLabel": "Souřadnice X:",
  "yAttributeTextBoxLabel": "Souřadnice Y:",
  "latitudeTextBoxLabel": "Zeměpisná šířka:",
  "longitudeTextBoxLabel": "Zeměpisná délka:",
  "presetGroupFieldsLabel": "'${groupName}' bude použito pro následující pole vrstvy:",
  "presetGroupNoFieldsLabel": "'${groupName}' nemá přidružená žádná pole",
  "groupInfoLabel": "Informace o skupině pro '${groupName}'",
  "editGroupInfoIcon": "Upravit skupinovou hodnotu pro ${groupName}",
  "filterEditor": {
    "all": "Všechny",
    "noAvailableTempaltes": "Žádné šablony nejsou k dispozici.",
    "searchTemplates": "Vyhledávání šablon",
    "filterLayerLabel": "Filtrovat vrstvy"
  },
  "invalidConfiguration": "Widget není nakonfigurován nebo se vrstvy v konfiguraci již nenacházejí v mapě. Spusťte aplikaci v režimu tvorby a upravte konfiguraci widgetu.",
  "geometryServiceURLNotFoundMSG": "Nelze načíst adresu URL služby geometrie",
  "clearSelection": "Zavřít",
  "refreshAttributes": "Aktualizovat dynamické atributy prvků",
  "automaticAttributeUpdatesOn": "Automaticky aktualizovat atributy prvků: ZAPNOUT",
  "automaticAttributeUpdatesOff": "Automaticky aktualizovat atributy prvků: VYPNOUT",
  "moveSelectedFeatureToGPS": "Přesunout vybraný prvek na aktuální umístění GPS",
  "moveSelectedFeatureToXY": "Přesunout vybraný prvek na umístění XY",
  "mapNavigationLocked": "Mapová navigace: Uzamknuto",
  "mapNavigationUnLocked": "Mapová navigace: Odemknuto",
  "copyFeatures": {
    "title": "Kopírovat prvky",
    "createFeatures": "Vytvořit prvky",
    "createSingleFeature": "Vytvořit 1 vícenásobný prvek",
    "createOneSingleFeature": "Vytvořit prvek",
    "noFeaturesSelectedMessage": "Nejsou vybrány žádné prvky",
    "selectFeatureToCopyMessage": "Vyberte prvky ke zkopírování",
    "multipleFeatureSaveWarning": "Poznámka: Při vytváření více prvků pomocí funkce kopírovat, jsou všechny nové prvky okamžitě uloženy",
    "copyFeatureUpdateGeometryError": "Nelze aktualizovat geometrii vybraných prvků",
    "canNotSaveMultipleFeatureWarning": "Poznámka: Nelze kopírovat více prvků pomocí stejné hodnoty pro pole jedinečné hodnoty, vyberte prosím pouze jeden prvek",
    "createOnlyOneMultipartFeatureWarning": "Poznámka: Lze vytvořit pouze jeden vícenásobný prvek"
  },
  "addingFeatureError": "Během přidávání vybraných prvků ve vrstvě došlo k chybě. Zkuste to prosím znovu.",
  "addingFeatureErrorCount": "„${copyFeatureErrorCount}” prvků se nepodařilo zkopírovat. Chcete to zkusit znovu pro chybějící prvky?",
  "selectingFeatureError": "Během výběru prvků ve vrstvě došlo k chybě. Zkuste to prosím znovu.",
  "customSelectOptionLabel": "Vyberte prvky, které se mají zkopírovat",
  "noFeatureSelectedMessage": "Nebyly vybrány žádné prvky",
  "multipleFeatureSaveMessage": "Všechny prvky budou ihned uloženy. Přejete si pokračovat?",
  "relativeDates": {
    "dateTypeLabel": "Typ data",
    "valueLabel": "Hodnota",
    "fixed": "Fixní",
    "current": "Aktuální",
    "past": "Minulé",
    "future": "Budoucí",
    "popupTitle": "Vybrat hodnotu",
    "hintForFixedDateType": "Nápověda: Nastavené datum a čas bude použito jako přednastavená výchozí hodnota.",
    "hintForCurrentDateType": "Nápověda: Aktuální datum a čas bude použito jako přednastavená výchozí hodnota.",
    "hintForPastDateType": "Nápověda: Zadaná hodnota bude odečtena od aktuálního data a času, a bude tak určena výchozí hodnota pro přednastavení.",
    "hintForFutureDateType": "Nápověda: Zadaná hodnota bude přidána od aktuálního data a času, a bude tak určena výchozí hodnota pro přednastavení.",
    "noDateDefinedTooltip": "Není určeno žádné datum",
    "relativeDateWarning": "Aby bylo možné uložit výchozí přednastavenou hodnotu, musí být zadána hodnota pro datum nebo čas.",
    "customLabel": "Vlastní",
    "layerLabel": "Vrstva",
    "domainFieldHintLabel": "Vybraná hodnota je doménou specifikovanou kódovanými hodnotami. Hodnota: „${domainValue}\" bude použita"
  },
  "valuePicker": {
    "popupTitle": "Vybrat hodnotu",
    "popupHint": "Aktuální prvek se protíná s několika dalšími prvky, vyberte hodnotu pro příslušné pole",
    "buttonTooltip": "Vyberte hodnotu z několika protínajících se prvků"
  },
  "uniqueValueErrorMessage": "Hodnota již v \"${fieldName}\" existuje, zadejte novou hodnotu.",
  "requiredFields": {
    "displayMsg": "Povinná pole nemohou být prázdná. Níže zadejte hodnoty do běžných polí.",
    "popupTittle": "Povinná pole",
    "foundNullRecordCount": "${fieldName} (Nalezeno v ${count} záznamech)"
  },
  "cantLocateUserLocation": "Vaši polohu nebylo možné určit.",
  "tryAgainButtonLabel": "Zkusit znovu",
  "copyFeatureFailedPopupTitle": "Chyba"
});