define({
  "_widgetLabel": "Vidljivost",
  "observerLocation": "Lokacija posmatrača",
  "formatIconTooltip": "Unos formata",
  "addPointToolTip": "Dodaj lokaciju posmatrača",
  "fieldOfView": "Vidno polje",
  "useMilsText": "Koristi mil za uglove",
  "observerHeight": "Visina posmatrača",
  "minObsDistance": "Min. rastojanje koje je moguće posmatrati",
  "maxObsDistance": "Maks. rastojanje koje je moguće posmatrati",
  "taskURLError": "Datoteka konfiguracije vidžeta sadrži URL adresu koja je nedostupna. Proverite kod administratora sistema",
  "taskURLInvalid": "Zadatak geoprocesiranja koji je konfigurisan sa ovim vidžetom nije važeći. Proverite kod administratora sistema",
  "viewshedError": "Došlo je do greške prilikom kreiranja vidljivosti. Vodite računa da se lokacija posmatrača nalazi unutar obuhvata elevacione površi.</p>",
  "validationError": "<p>Obrazac za kreiranje vidljivosti ima parametre koji nedostaju ili su nevažeći. Uverite se da :</p><ul><li>Lokacija posmatrača je podešena.</li><li>Vidno polje posmatrača nije 0.</li><li>Visina posmatrača sadrži važeću vrednost.</li><li>Min. i maks. rastojanja koja je moguće posmatrati sadrže važeće vrednosti.</li></ul>",
  "comfirmInputNotation": "Proverite unesenu oznaku",
  "notationsMatch": "oznake se podudaraju sa unosom potvrdite koje biste želeli da koristite:",
  "createBtn": "Kreiraj",
  "clearBtn": "Obriši",
  "setCoordFormat": "Postavi nisku formata koordinata",
  "prefixNumbers": "Dodajte prefiks '+/-' pozitivnim i negativnim brojevima",
  "parseCoordinatesError": "Raščlanjivanje koordinata nije moguće. Proverite unos.",
  "cancelBtn": "Otkaži",
  "applyBtn": "Primeni",
  "invalidMessage": "Unesite brojčanu vrednost.",
  "observerRangeMessage": "Nevažeća visina posmatrača",
  "minimumRangeMessage": "Nevažeći minimalni opseg za posmatranje",
  "maximumRangeMessage": "Maksimalni opseg za posmatranje mora da bude veći od minimalnog opsega za posmatranje i ne može da bude veći od ${limit} ${units}.",
  "portalURLError": "URL adresa za vašu ArcGIS Online organizaciju ili Portal for ArcGIS nije konfigurisana. Proverite sa vašim administratorom sistema.",
  "privilegeError": "Vaša korisnička uloga ne može da vrši analizu. Da bi analiza bila izvršena, administrator organizacije mora da vam omogući određene <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegije</a>.",
  "noServiceError": "Servis analize elevacije nije dostupan. Proverite konfiguracije za ArcGIS Online organizaciju ili Portal for ArcGIS.",
  "pointToolTooltip": "Kliknite da biste dodali lokaciju posmatrača",
  "degreesLabel": "stepeni",
  "milsLabel": "Mil",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "Univerzalni Transverzalni Merkatorov koordinatni sistem (H)",
  "UTM": "Univerzalni Transverzalni Merkatorov koordinatni sistem (UTM)",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalni stepeni – geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stepeni – geografska dužina/širina",
  "DDMLatLongNotation": "Decimalni stepeni minuti – geografska širina/dužina",
  "DDMLongLatNotation": "Decimalni stepeni minuti – geografska dužina/širina",
  "DMSLatLongNotation": "Decimalni stepeni sekundi – geografska širina/dužina",
  "DMSLongLatNotation": "Decimalni stepeni sekundi – geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – slovo opsega",
  "UTMHemNotation": "UTM – hemisfera (S/J)",
  "mainPageTitle": "Radijalna linija vida",
  "resultsTitle": "Rezultati",
  "publishBtnLabel": "Objavi",
  "layerName": "Naziv objavljenog sloja",
  "invalidLayerName": "Ime sloja sme da sadrži samo alfanumeričke znakove i donje crte",
  "back": "Nazad",
  "publishingFailedLayerExists": "Objavljivanje nije uspelo: Već imate servis geoobjekata sa nazivom {0}. Izaberite drugi naziv.",
  "checkService": "Provera servisa: {0}",
  "createService": "Kreiranje servisa: {0}",
  "unableToCreate": "Kreiranje nije moguće: {0}",
  "addToDefinition": "Dodaj u definiciju: {0}",
  "successfullyPublished": "Uspešno objavljen veb sloj{0}Upravljaj veb slojem",
  "userRole": "Kreiranje servisa nije moguće, jer korisnik nema dozvole",
  "publishToNewLayer": "Objavi rezultate u novom sloju geoobjekata",
  "missingLayerNameMessage": "Morate da unesete važeće ime sloja da biste mogli da objavite",
  "layerNameExists": "Naziv sloja već postoji. Izaberite drugi naziv sloja.",
  "regionTypeLabel": "Tip regiona",
  "centerPointLabel": "Središnja tačka",
  "observationHeightLabel": "Visina za posmatranje",
  "heightUnitLabel": "Jedinica visine",
  "minObservationDistanceLabel": "Minimalna distanca za posmatranje",
  "maxObservationDistance": "Maksimalna distanca za posmatranje",
  "distanceUnitLabel": "Jedinica rastojanja",
  "fovstartAngleLabel": "Početni ugao vidnog polja",
  "fovEndAngleLabel": "Krajnji ugao vidnog polja",
  "andleUnitsLabel": "Jedinice za ugao",
  "visibleSectionLabel": "Vidljivi odeljak",
  "nonVisibleSectionLabel": "Nevidljivi odeljak",
  "visibleSectionButtonLabel": "Postavka vidljivog odeljka Postavke",
  "nonVisibleSectionButtonLabel": "Postavka nevidljivog odeljka Postavke",
  "transparency": "Prozirnost",
  "outline": "Kontura",
  "fill": "Popuna (boja se primenjuje samo kada je stil podešen da bude neproziran)",
  "style": "Stil",
  "colorPicker": "Birač boja",
  "lineStyles": {
    "esriSLSDash": "Crta",
    "esriSLSDashDot": "Crta tačka",
    "esriSLSDashDotDot": "Crta tačka tačka",
    "esriSLSDot": "Tačka",
    "esriSLSLongDash": "Duga crta",
    "esriSLSLongDashDot": "Duga crta tačka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kratka crta",
    "esriSLSShortDashDot": "Kratka crta tačka",
    "esriSLSShortDashDotDot": "Kratka crta tačka tačka",
    "esriSLSShortDot": "Kratka tačka",
    "esriSLSSolid": "Neprozirno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unazad",
    "esriSFSCross": "Krst",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Unapred",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Neprozirno",
    "esriSFSVertical": "Vertikalno"
  },
  "settingsTitle": "Podešavanja"
});