define({
  "tabs_section_Label": "Раздели",
  "addTab": "Добавяне на раздел",
  "layerName": "Слой",
  "layerType": "Тип анализ",
  "layerLabel": "Етикет",
  "actions": "Действия",
  "closest": "Най-близкия обект",
  "proximity": "Приблизително",
  "summary": "Обобщение",
  "select_lbl": "-- Изберете--",
  "general_setting_Label": "Общи настройки",
  "units_text_lbl": "Единици за разстояние",
  "miles": "Мили",
  "kilometers": "Километри",
  "feet": "Фута",
  "meters": "Метри",
  "yards": "Ярда",
  "nauticalMiles": "Морски мили",
  "maximum_distance_lbl": "Максимално разстояние до най-близкия обект",
  "buffer_text_lbl": "Етикет на буфер",
  "buffer_lbl": "Буферно разстояние",
  "buffer_max_lbl": "Максимално буферно разстояние",
  "buffer_min_lbl": "Минимално буферно разстояние",
  "routing_checkBox": "Активиране на маршрутизиране",
  "weather_Label": "Опции за времето",
  "weather_checkBox": "Включване на информация за времето",
  "weather_celsius": "Целзий-Километри",
  "selectLayers": "Избор на слоеве за времето",
  "currentlySelectedLayer": "Избрани понастоящем слоеве за времето",
  "missingTabLabel": "Най-малко един раздел няма надпис",
  "cancel": "Отказ",
  "ok": "Добре",
  "missingLayerInWebMap": "Няма намерени оперативни слоеве.",
  "selectFields": "Избор на обекти",
  "addField": "Добавяне на поле",
  "sum": "СУМА",
  "min": "МИН.",
  "max": "МАКС.",
  "avg": "СР.",
  "count": "БРОЙ",
  "area": "ОБЛАСТ",
  "length": "ДЪЛЖИНА",
  "count_checkBox": "Показване на брой",
  "area_checkBox": "Показване на област",
  "length_checkBox": "Показване на дължина",
  "max_records": "Достигнат е максималния лимит",
  "disable_checkBox": "Деактивиране на управлението на видимостта на слоя",
  "optional_lbl": "Допълнителни етикети",
  "incident_lbl": "Инцидент",
  "locate_lbl": "Локализиране на инцидент"
});