define({
  "showLayerLabels": "Показване на имена на слой",
  "autoPlay": "Автоматично стартиране на плъзгача",
  "loopPlay": "Непрекъснат времеви цикъл",
  "dateAndTimeFormat": "Формат на дата и час",
  "mapDefault": "Карта по подразбиране",
  "custom": "Персонализиран",
  "formatInstruction": "Инструкция за формат",
  "playback": "позиция за възпроизвеждане, запазена с карта",
  "MMMMYYYY": "юли 2015 г.",
  "MMMYYYY": "юли 2015 г.",
  "MMMMDYYYY": "21 юли, 2015 г.",
  "dddMMMDDYYYY": "вт.21 юли, 2015 г.",
  "MDDYYYY": "7/21/2015 г.",
  "YYYYMDD": "2015/7/21",
  "MDDYY": "7/21/15 г.",
  "YYYY": "2015 г.",
  "MDDYYYYhmma": "7/21/2015 г. 8:00 ч.",
  "dddMMMDDhmma": "вт. юли 21 8:00 ч.",
  "sliderSetting": "Настройки на плъзгач",
  "autoRefresh": "Опресняване на плъзгача на всеки",
  "timeSetting": "Настройки на време",
  "useWebMapSetting": "Спазвайте настройките за време на уеб картата",
  "useConfigureSetting": "Конфигурирайте настройките за време",
  "timeSettingBtn": "настройки",
  "calenderError": "Началното време трябва да е по-малко от Крайното време.",
  "timeSpan": "Период от време",
  "startTime": "Начален час",
  "endTime": "Краен час",
  "unit": "Мерна единица",
  "timeDisplay": "Индикатор за време",
  "displayDataIn": "Индикатор за данни в",
  "interval": "Интервал",
  "displayAllData": "Постепенно показване на всички данни",
  "layerTimeExtent": "Активиране на време за анимация",
  "layerTableCol1": "Слой",
  "layerTableCol2": "Времеви обхват",
  "timeTo": "до",
  "calender": "Календар",
  "time": "Време",
  "now": "Сега",
  "today": "Днес",
  "maximum": "Максимум от всички избрани",
  "minimum": "Минимум от всички избрани"
});