define({
  "labelBookmarkName": "Créer un géosignet pour la vue courante",
  "labelPlay": "Lire tout",
  "labelStop": "Arrêter",
  "labelDelete": "Supprimer",
  "placeholderBookmarkName": "Nom du géosignet",
  "errorNameExist": "Le géosignet existe !",
  "errorNameNull": "Nom de géosignet non valide !",
  "editTip": "Modifier les géosignets",
  "exitEditTip": "Quitter le mode d’édition",
  "syncTip": "Synchroniser",
  "cardsTips": "Vue Grille",
  "listTips": "Vue Liste",
  "addBtn": "Ajouter",
  "deleteBtn": "Effacer",
  "changeThumbnailTip": "Modifier la miniature",
  "dragReorderTip": "Maintenir enfoncé et faire glisser pour réorganiser",
  "deleteBtnTip": "Supprimer le géosignet",
  "editBtnTip": "Modifier le géosignet",
  "withVisibility": "Avec la visibilité des couches",
  "searchBookmark": "Rechercher",
  "bookmarksFromConfig": "Géosignets préconfigurés",
  "bookmarksFromCache": "Géosignets temporaires locaux",
  "notice": "Avis",
  "changeNoticeTips": "Les modifications seront uniquement enregistrées dans le cache de votre navigateur. Lorsque des modifications sont apportées, la synchronisation entre le widget et sa configuration est désactivée.",
  "syncNoticeTips": "Cela a pour effet d’effacer toutes vos modifications et de restaurer les géosignets configurés.",
  "dontShowAgain": "Ne plus afficher",
  "saveVisibility": "Enregistrer la visibilité des couches",
  "_widgetLabel": "Géosignet"
});