define({
  "taskUrl": "Webbadress till siktområdestjänst",
  "portalURL": "Ange URL:en till ArcGIS Online-organisationen eller Portal for ArcGIS",
  "portalURLError": "Den konfigurerade URL:en till din ArcGIS Online-organisation eller Portal for ArcGIS är inte giltig.",
  "privilegeError": "Din användarroll kan inte utföra analyser. För att du ska kunna utföra analyser måste organisationens administratör bevilja dig vissa <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">behörigheter</a>.",
  "noServiceError": "Tjänsten för höjdanalys är inte tillgänglig. Kontrollera konfigurationerna för din ArcGIS Online-organisation eller Portal for ArcGIS.",
  "serviceURLPlaceholder": "Ange URL för geobearbetningsåtgärden för siktområde",
  "setTask": "Ange",
  "setTaskTitle": "Ange geobearbetningsåtgärd för siktområde",
  "serviceURLError": "Den geobearbetningsåtgärd du försöker konfigurera med denna widget är inte giltig. Välj en giltig URL för geobearbetningsåtgärd för siktområde",
  "defaultMilsForAnglesLabel": "Ange streck för vinklar som standard",
  "defaultObserverHeightLabel": "Standardenhet för observatörs höjd över marken",
  "defaultObservableDistanceLabel": "Standardenhet för observerbart avstånd",
  "units": {
    "miles": "Mile",
    "kilometers": "Kilometer",
    "feet": "Fot",
    "meters": "Meter",
    "yards": "Yard",
    "nauticalMiles": "Nautiska mil"
  },
  "helpIconTooltip": "Listan med funktionslager innehåller lager från den aktuella webbkartan som är av typen polygongeometri.",
  "selectOperationalLayerLabel": "Välj ett funktionslager för resultat",
  "lineOfSightTabTitle": "Siktlinje",
  "symbologyTabTitle": "Symbologi",
  "transparency": "Transparens",
  "outline": "Kontur",
  "fill": "Fyllningsfärg (Färgen tillämpas enbart när stilen anges till solid)",
  "style": "Format",
  "selectOpLayerLabel": "Välj ett funktionslager för resultat",
  "selectDefaultMeasurementLabel": "Ange en standardmåttenhet",
  "visibleSectionLabel": "Synlig sektion",
  "nonVisibleSectionLabel": "Icke synlig sektion",
  "visibleSectionButtonLabel": "Konfigurera inställningar för synlig sektion",
  "nonVisibleSectionButtonLabel": "Konfigurera inställningar för icke-synlig sektion",
  "colorPicker": "Färgurval",
  "lineStyles": {
    "esriSLSDash": "Streck",
    "esriSLSDashDot": "Streck punkt",
    "esriSLSDashDotDot": "Streck punkt punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Långt streck",
    "esriSLSLongDashDot": "Lång streck-punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort streck",
    "esriSLSShortDashDot": "Kort streck-punkt",
    "esriSLSShortDashDotDot": "Kort streck-punkt-punkt",
    "esriSLSShortDot": "Kort punkt",
    "esriSLSSolid": "Solid"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakåt",
    "esriSFSCross": "Kors",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Framåt",
    "esriSFSHorizontal": "Horisontell",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Solid",
    "esriSFSVertical": "Vertikal"
  }
});