// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/map-config/CustomizeScale.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"scale-input-div" data-dojo-attach-point\x3d"scaleInputDiv"\x3e\r\n    \x3cdiv class\x3d"add-btn jimu-float-leading" data-dojo-attach-point\x3d"btnAdd" data-dojo-attach-event\x3d"onclick:_onBtnAddClicked"\x3e+\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"operations-div"\x3e\r\n    \x3cdiv class\x3d"jimu-float-leading operation-btn delete-btn" data-dojo-attach-point\x3d"btnDelete" data-dojo-attach-event\x3d"onclick:_onBtnDeleteClicked"\x3e\r\n      \x3cspan class\x3d"jimu-float-leading icon"\x3e\x3c/span\x3e\r\n      \x3cspan class\x3d"jimu-float-leading label"\x3e${nls.deleteTip}\x3c/span\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"jimu-float-leading operation-btn reset-btn" data-dojo-attach-event\x3d"onclick:_onBtnResetClicked"\x3e\r\n      \x3cspan class\x3d"jimu-float-leading icon"\x3e\x3c/span\x3e\r\n      \x3cspan class\x3d"jimu-float-leading label"\x3e${nls.resetTip}\x3c/span\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"list" data-dojo-attach-point\x3d"listNode" data-dojo-attach-event\x3d"onclick:_onLodListClicked"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./CustomizeScale.html dojo/query dojo/_base/lang dojo/_base/array dojo/_base/html jimu/utils jimu/dijit/Message dijit/form/NumberTextBox".split(" "),function(p,q,r,t,u,l,h,k,d,n,v,w){return p([q,r,t],{templateString:u,baseClass:"mapconfig-customize-scale",map:null,postCreate:function(){this.inherited(arguments);this._initSelf()},_initSelf:function(){this.scaleNumberBox=new w({placeholder:this.nls.scale,
intermediateChanges:!0,trim:!0,constraints:{min:1,pattern:"###############0.################"},style:"width:550px;height:100%;"});d.addClass(this.scaleNumberBox.domNode,"jimu-float-leading");this.scaleNumberBox.placeAt(this.scaleInputDiv,"first");var a=this.getLodsFromMap();this._resetLodListByLods(a)},getLodsFromMap:function(){var a=[];this.map._params&&this.map._params.lods&&(a=k.map(this.map._params.lods,h.hitch(this,function(b){return b.toJson()})));return a},_getLodsFromBasemapLayer:function(){var a=
[],b=this.map.getLayer(this.map.layerIds[0]);b&&b.tileInfo&&b.tileInfo.lods&&(a=k.map(b.tileInfo.lods,h.hitch(this,function(e){return{level:e.level,resolution:e.resolution,scale:e.scale}})));return a},getLodsFromListNode:function(){for(var a=this._getLodItems(),b=[],e=null,f=0;f<a.length;f++)e=a[f].lod,b.push({level:e.level,scale:e.scale,resolution:e.resolution});return b},_resetLodListByLods:function(a){d.empty(this.listNode);k.forEach(a,h.hitch(this,function(b){b=this._createLodItem(b);d.place(b,
this.listNode)}))},_createLodItem:function(a){var b=d.create("div",{innerHTML:n.sanitizeHTML(n.localizeNumber(a.scale)),"class":"lod-item"});b.lod=a;return b},_getLodItems:function(){return l(".lod-item",this.listNode)},_getSelectedLodItem:function(){var a=null,b=l(".selected",this.listNode);0<b.length&&(a=b[0]);return a},_selectLodItem:function(a){this._removeSelectedClass();d.addClass(a,"selected");d.addClass(this.btnDelete,"enabled-operation");a.previousSibling||d.setStyle(a,"borderTop","0")},
_removeSelectedClass:function(){l(".lod-item",this.listNode).removeClass("selected");d.removeClass(this.btnDelete,"enabled-operation")},_onLodListClicked:function(a){a=a.target||a.srcElement;d.hasClass(a,"lod-item")&&this._selectLodItem(a)},_onBtnAddClicked:function(){if(this.scaleNumberBox.validate()){var a=this.scaleNumberBox.get("value");this.scaleNumberBox.set("displayedValue","");var b=this._getLodItems();if(0!==b.length&&!k.some(b,h.hitch(this,function(x){return x.lod.scale===a}))){var e=b.length-
1,f=b[0].lod,g=b[e].lod,c=null;c={level:null,resolution:f.resolution/f.scale*a,scale:a};if(c.scale>f.scale)c.level=f.level-1,c=this._createLodItem(c),d.place(c,this.listNode,"first");else if(c.scale<g.scale)c.level=g.level+1,c=this._createLodItem(c),d.place(c,this.listNode);else{var m=null;f=null;for(g=e;1<=g;g--)if(m=b[g],f=b[g-1],c.scale>m.lod.scale&&c.scale<f.lod.scale){c.level=m.lod.level;c=this._createLodItem(c);d.place(c,f,"after");for(c=g;c<=e;c++)b[c].lod.level+=1;break}}}}},_onBtnDeleteClicked:function(){var a=
this._getSelectedLodItem();if(a)if(1===this.getLodsFromListNode().length)new v({message:this.nls.atLeastOneScale});else{var b=a;if(!a.previousSibling)for(;a.nextSibling;)a=a.nextSibling,--a.lod.level;d.destroy(b);this._removeSelectedClass()}},_onBtnResetClicked:function(){this._removeSelectedClass();var a=this._getLodsFromBasemapLayer();this._resetLodListByLods(a)}})});