define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Ihrem Konto sind keine Berechtigungen zum Erstellen oder Ändern von Daten zugewiesen.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Nicht aktiv",
  "pressStr": "Drücken Sie ",
  "ctrlStr": " STRG ",
  "snapStr": " , um die Fangfunktion zu aktivieren.",
  "noAvailableTempaltes": "Keine verfügbaren Vorlagen",
  "editorCache": " - Editor-Cache",
  "presetFieldAlias": "Feld",
  "presetValue": "Voreingestellter Wert",
  "usePresetValues": " Voreingestellte Werte verwenden (nur neue Features)",
  "editGeometry": " Geometrie bearbeiten",
  "savePromptTitle": "Feature speichern",
  "savePrompt": "Möchten Sie das aktuelle Feature speichern?",
  "deletePromptTitle": "Feature löschen",
  "deleteAttachment": "Anlage löschen",
  "deletePrompt": "Soll das ausgewählte Feature tatsächlich gelöscht werden?",
  "attachmentLoadingError": "Fehler beim Hochladen der Anlagen",
  "attachmentSaveDeleteWarning": "Warnung: Änderungen an Anlagen werden automatisch gespeichert.",
  "autoSaveEdits": "Neue Features automatisch speichern",
  "addNewFeature": "Neues Feature erstellen",
  "featureCreationFailedMsg": "Neuer Datensatz/neues Feature kann nicht erstellt werden",
  "relatedItemTitle": "Zugehörige(r) Tabelle/Layer",
  "relatedFeatureCount": "${layerTitle} mit ${featureCount} Features",
  "createNewFeatureLabel": "Neues Feature für ${layerTitle} erstellen",
  "invalidRelationShipMsg": "Stellen Sie sicher, dass der Wert des Primärschlüsselfeldes '${parentKeyField}' gültig ist.",
  "pendingFeatureSaveMsg": "Speichern Sie die Feature-Änderungen, bevor Sie ein zugehöriges Feature erstellen.",
  "attachmentsRequiredMsg": "(*) Anlagen sind erforderlich.",
  "coordinatePopupTitle": "Feature an XY-Position verschieben",
  "coordinatesSelectTitle": "Koordinatensystem:",
  "mapSpecialReferenceDropdownOption": "Raumbezug der Karte",
  "latLongDropdownOption": "Breitengrad/Längengrad",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Koordinate:",
  "xAttributeTextBoxLabel": "X-Koordinate:",
  "yAttributeTextBoxLabel": "Y-Koordinate:",
  "latitudeTextBoxLabel": "Breitengrad:",
  "longitudeTextBoxLabel": "Längengrad:",
  "presetGroupFieldsLabel": "\"${groupName}\" wird für die folgenden Layer-Felder übernommen:",
  "presetGroupNoFieldsLabel": "\"${groupName}\" sind keine Felder zugeordnet.",
  "groupInfoLabel": "Gruppeninformationen für \"${groupName}\"",
  "editGroupInfoIcon": "Gruppenwert für \"${groupName}\" bearbeiten",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Keine verfügbaren Vorlagen",
    "searchTemplates": "Vorlagen durchsuchen",
    "filterLayerLabel": "Layer filtern"
  },
  "invalidConfiguration": "Das Widget wurde nicht konfiguriert oder die Layer in der Konfiguration sind nicht mehr in der Karte enthalten.  Öffnen Sie die App im Builder-Modus, und konfigurieren Sie das Widget neu.",
  "geometryServiceURLNotFoundMSG": "URL des Geometrieservice kann nicht abgerufen werden",
  "clearSelection": "Schließen",
  "refreshAttributes": "Dynamische Feature-Attribute aktualisieren",
  "automaticAttributeUpdatesOn": "Feature-Attribute automatisch aktualisieren: EIN",
  "automaticAttributeUpdatesOff": "Feature-Attribute automatisch aktualisieren: AUS",
  "moveSelectedFeatureToGPS": "Selektiertes Feature an aktuelle GPS-Position verschieben",
  "moveSelectedFeatureToXY": "Selektiertes Feature an XY-Position verschieben",
  "mapNavigationLocked": "Kartennavigation: Gesperrt",
  "mapNavigationUnLocked": "Kartennavigation: Entsperrt",
  "copyFeatures": {
    "title": "Features kopieren",
    "createFeatures": "Features erstellen",
    "createSingleFeature": "1 Multi-Geometrie-Feature erstellen",
    "noFeaturesSelectedMessage": "Keine Features ausgewählt",
    "selectFeatureToCopyMessage": "Wählen Sie Features für den Kopiervorgang aus.",
    "multipleFeatureSaveWarning": "Hinweis: Beim Erstellen mehrerer Features mit \"Feature kopieren\" werden alle Features sofort gespeichert.",
    "copyFeatureUpdateGeometryError": "Die Geometrie der ausgewählten Features kann nicht aktualisiert werden.",
    "canNotSaveMultipleFeatureWarning": "Hinweis: Es ist nicht möglich, mehrere Features mit demselben Wert für Einzelwertfelder zu kopieren. Wählen Sie nur ein Feature aus.",
    "createOnlyOneMultipartFeatureWarning": "Hinweis: Es kann nur ein Multipart-Feature erstellt werden."
  },
  "addingFeatureError": "Fehler beim Hinzufügen von ausgewählten Features im Layer. Versuchen Sie es erneut.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' Features konnten nicht kopiert werden.",
  "selectingFeatureError": "Fehler beim Auswählen von Features im Layer. Versuchen Sie es erneut.",
  "customSelectOptionLabel": "Zu kopierende Features auswählen",
  "noFeatureSelectedMessage": "Keine Features ausgewählt.",
  "multipleFeatureSaveMessage": "Alle Features werden sofort gespeichert. Möchten Sie den Vorgang fortsetzen?",
  "relativeDates": {
    "dateTypeLabel": "Datumstyp",
    "valueLabel": "Wert",
    "fixed": "Beschränkt",
    "current": "Aktuell",
    "past": "Vergangen",
    "future": "Zukunft",
    "popupTitle": "Wert auswählen",
    "hintForFixedDateType": "Hinweis: Der angegebene Wert für Datum und Uhrzeit wird als voreingestellter Standardwert verwendet.",
    "hintForCurrentDateType": "Hinweis: Der aktuelle Wert für Datum und Uhrzeit wird als voreingestellter Standardwert verwendet.",
    "hintForPastDateType": "Hinweis: Der angegebene Wert wird für den Standardwert der Voreinstellung vom aktuellen Wert für Datum und Uhrzeit subtrahiert.",
    "hintForFutureDateType": "Hinweis: Der angegebene Wert wird für den Standardwert der Voreinstellung zum aktuellen Wert für Datum und Uhrzeit addiert.",
    "noDateDefinedTooltip": "Kein Datum definiert",
    "relativeDateWarning": "Es muss ein Wert für Datum oder Uhrzeit angegeben werden, damit der voreingestellte Standardwert gespeichert werden kann.",
    "customLabel": "Benutzerdefiniert",
    "layerLabel": "Layer",
    "domainFieldHintLabel": "Der ausgewählte Wert ist eine Domäne mit codierten Werten. Der Wert \"${domainValue}\" wird verwendet."
  },
  "valuePicker": {
    "popupTitle": "Wert auswählen",
    "popupHint": "Das aktuelle Feature schneidet mehrere Features. Wählen Sie einen Wert für das jeweilige Feld aus.",
    "buttonTooltip": "Wert aus mehreren schneidenden Features auswählen"
  },
  "uniqueValueErrorMessage": "Der Wert in \"${fieldName}\" ist bereits vorhanden. Geben Sie einen neuen Wert ein.",
  "requiredFields": {
    "displayMsg": "Erforderliche Felder dürfen nicht leer sein. Geben Sie unten Werte für gemeinsame Felder ein.",
    "popupTittle": "Erforderliche Felder",
    "foundNullRecordCount": "${fieldName} (gefunden in ${count} Datensätzen)"
  },
  "cantLocateUserLocation": "Ihre Position konnte nicht ermittelt werden."
});