define({
  "_widgetLabel": "Vzdialenosť a smer",
  "tabLineTitle": "Línia",
  "tabCircleTitle": "Kruh",
  "tabEllipseTitle": "Elipsa",
  "tabRingsTitle": "Kruhy",
  "multipleNotationsMessage": " zápisy, ktoré sa zhodujú s vaším vstupom. Potvrďte, ktoré by ste chceli použiť:",
  "invalidCoordinateMessage": "Neplatná súradnica",
  "confirmInputNotationMessage": "Potvrdiť zápis vstupu",
  "prefixSuffixMessage": "Zistilo sa, že vstupná súradnica má predponu aj príponu pre zemepisnú šírku alebo dĺžku, vrátená súradnica je založená na predpone.",
  "rememberDecisionMessage": "Zapamätať si moje rozhodnutie a znova sa nepýtať,<br/>",
  "majorAxisTooltipMessage": "Kliknite pre dĺžku hlavnej osi",
  "minorAxisTooltipMessage": "Pre nastavenie vedľajšej osi pohnite myšou späť na štartovaciu pozíciu a dokončite nakreslenie elipsy",
  "clickToFinishLineMessage": "Pre dokončenie kreslenia línie kliknite",
  "doubleClickEllipseMesage": "Pre dokončenie kreslenia kruhov rozsahu dvakrát kliknite",
  "invalidCoordinateTypeMessage": "Nie je možné určiť typ vstupnej súradnice. Skontrolujte svoj vstup",
  "noCenterPointSetMessage": "Nie je nastavený stredový bod. Skontrolujte svoj vstup",
  "ellipseMajorAxis": "Hlavná os",
  "ellipseMinorAxis": "Vedľajšia os",
  "degreesRangeMessage": "Hodnota musí byť medzi 0 a 360",
  "millsRangeMessage": "Hodnota musí byť medzi 0 a 6400",
  "lengthLabel": "Dĺžka",
  "angleLabel": "Uhol",
  "startPointLabel": "Začiatočný bod",
  "endPointLabel": "Koncový bod",
  "centerPointLabel": "Stredový bod",
  "distanceTableErrorMessage": "Tabuľka vzdialeností je prázdna. Uistite sa, že zadáte nejaké vzdialenosti.",
  "setCoordFormatStringMessage": "Nastaviť zápis formátu súradníc",
  "prefixMessage": "Pridať \"+/-\" ku kladným a záporným číslam",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Desatinné stupne - Zemepisná šírka/dĺžka",
  "DDLongLatNotation": "Desatinné stupne - Zemepisná dĺžka/šírka",
  "DDMLatLongNotation": "Stupne desatinné minúty - Zemepisná šírka/dĺžka",
  "DDMLongLatNotation": "Stupne desatinné minúty - Zemepisná dĺžka/šírka",
  "DMSLatLongNotation": "Stupne minúty sekundy - Zemepisná šírka/dĺžka",
  "DMSLongLatNotation": "Stupné minúty sekundy - Zemepisná dĺžka/šírka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - znak pásma",
  "UTMHemNotation": "UTM - pologuľa (S/J)",
  "circleTitle": "Vytvoriť kruh z",
  "radiusLabel": "Polomer",
  "diameterLabel": "Priemer",
  "startPointPlaceHolderLabel": "Zadať súradnice",
  "formatInputLabel": "Formátovanie vstupu",
  "drawCircleLabel": "Nakresliť kruh",
  "drawLineLabel": "Nakresliť líniu",
  "createCircleInteractivelyLabel": "Interaktívne vytvoriť kruh",
  "rangeErrorMessage": "Neplatný polomer alebo priemer",
  "numericInvalidMessage": "Zadajte číselnú hodnotu",
  "timeLabel": "Čas",
  "invalidTimeMessage": "Neplatná hodnota času",
  "hoursLabel": "Hodiny",
  "minutesLabel": "Minúty",
  "secondsLabel": "Sekundy",
  "rateLabel": "Sadzba",
  "invalidDistanceMessage": "Neplatná hodnota vzdialenosti",
  "feetSecondsLabel": "Stopy / sekundu",
  "feetHourLabel": "Stopy / hodinu",
  "kmSecondLabel": "Kilometre / sekundu",
  "kmHourLabel": "Kilometre / hodinu",
  "metersSecondLabel": "Metre / sekundu",
  "metersHourLabel": "Metre / hodinu",
  "milesSecondLabel": "Míle / sekundu",
  "milesHourLabel": "Míle / hodinu",
  "nauticalMilesSecondLabel": "Námorné míle / sekundu",
  "nauticalMilesHourLabel": "Námorné míle / hodinu",
  "clearGraphicsLabel": "Vymazať grafiku",
  "ellipseTypeLabel": "Typ elipsy",
  "ellipseSemiLabel": "Polovičná",
  "ellipseFullLabel": "Plná",
  "drawEllipseLabel": "Nakresliť elipsu",
  "createEllipseInteractively": "Interaktívne vytvoriť elipsu",
  "axisLabel": "Os",
  "unitLabel": "Jednotka",
  "majorRadiusLabel": "Hlavná (polomer)",
  "majorDiameterLabel": "Hlavná (priemer)",
  "axisErrorMessage": "Hodnota musí byť väčšia než 0",
  "minorRadiusLabel": "Vedľajšia (polomer)",
  "minorDiameterLabel": "Vedľajšia (priemer)",
  "orientationLabel": "Orientácia",
  "orientationErrorMessage": "Hodnota musí byť medzi 0 a 360",
  "warningMessage": "Upozornenie: Grafika generovaná pomocou nástroja elipsy nie je geodetická",
  "fromLabel": "Od",
  "distanceBearingLabel": "Vzdialenosť a smerník",
  "pointsLabel": "Body",
  "createLineInteractively": "Interaktívne vytvoriť líniu",
  "lineLengthErrorMessage": "Neplatná dĺžka línie",
  "degreesLabel": "Stupne",
  "milsLabel": "Míle",
  "lineTypeLabel": "Typ",
  "interactiveLabel": "Interaktívne",
  "fixedLabel": "Fixné",
  "originLabel": "Počiatočné",
  "cumulativeLabel": "Kumulatívne",
  "numberOfRingsLabel": "Počet kruhov",
  "ringsErrorMessage": "Neplatný počet kruhov",
  "distanceBetweenRingsLabel": "Vzdialenosť medzi kruhmi",
  "ringsDecimalErrorMessage": "Zadajte číselnú hodnotu do 2 desatinných miest",
  "distanceUnitsLabel": "Jednotky vzdialenosti",
  "distancesLabel": "Vzdialenosti",
  "numberOfRadialsLabel": "Počet radiál",
  "upLabel": "Hore",
  "downLabel": "Dole",
  "deleteLabel": "Vymazať",
  "radialsErrorMessage": "Neplatný počet radiál Maximálny povolený počet je 360",
  "radialsInvalidMessage": "Neplatná hodnota pre radiály",
  "addPointLabel": "Pridať bod",
  "valueLabel": "Hodnota",
  "valueText": "Zadať hodnotu",
  "actionLabel": "Akcia",
  "distanceCalculatorLabel": "Kalkulátor vzdialenosti",
  "abbrevMetersLabel": "m",
  "abbrevFeetLabel": "ft",
  "abbrevKmLabel": "km",
  "abbrevMilesLabel": "mi",
  "abbrevYardsLabel": "yd",
  "abbrevNauticalMilesLabel": "nm",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "mil",
  "abbrevHoursLabel": "h",
  "abbrevMinutesLabel": "m",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "ft/s",
  "abbrevFeetHourLabel": "ft/h",
  "abbrevKmSecondLabel": "km/s",
  "abbrevKmHourLabel": "km/h",
  "abbrevMetersSecondLabel": "m/s",
  "abbrevMetersHourLabel": "m/h",
  "abbrevMilesSecondLabel": "mi/s",
  "abbrevMilesHourLabel": "mi/h",
  "abbrevNauticalMilesSecondLabel": "nm/s",
  "abbrevNauticalMilesHourLabel": "nm/h",
  "publishDDBtn": "Publikovať",
  "publishTitle": "Publikovať grafiku",
  "ddLayerName": "Názov publikovanej vrstvy",
  "publishToNewLayer": "Publikovať výsledky do novej vrstvy prvkov",
  "checkService": "Skontrolovať službu: {0}",
  "createService": "Vytvoriť službu: {0}",
  "unableToCreate": "Nebolo možné vytvoriť: {0}",
  "addToDefinition": "Pridať do definície: {0}",
  "successfullyPublished": "Webová vrstva úspešne publikovaná{0} Spravovať webovú vrstvu",
  "userRole": "Nebolo možné vytvoriť službu, pretože používateľ nemá povolenia",
  "missingLayerNameMessage": "Pred publikovaním musíte zadať platný názov vrstvy",
  "invalidLayerName": "Názov vrstvy musí obsahovať iba alfanumerické znaky a podčiarkovníky",
  "layerNameExists": "Názov vrstvy už existuje. Použite iný názov vrstvy.",
  "distanceLabel": "Vzdialenosť",
  "radiusDistance": "Vzdialenosť polomeru",
  "radials": "Radiály",
  "rings": "Kruhy",
  "orientationUnit": "Jednotka orientácie",
  "radiusUnit": "Jednotka polomeru",
  "angleUnitLabel": "Jednotka uhla",
  "editSymbologyHint": "Tip: Symboliku upravíte kliknutím na ikonu náhľadu",
  "lineSymbologyPopupTittle": "Symbolika línie",
  "circleSymbologyPopupTittle": "Symbolika kruhu",
  "ellipseSymbologyPopupTittle": "Symbolika elipsy",
  "ringSymbologyPopupTittle": "Symbolika prstencov",
  "symbolAndLabelSettingsLabel": "Nastavenia symbolov a popisov",
  "symbologyPreviewLabel": "Náhľad symboliky",
  "ColorAndSizeLabel": "Farba a veľkosť popisov",
  "colorPickerLabel": "Výber farby"
});