define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Få åtkomst till infografik och rapporter som sammanfattar nyckeltal och data för alla områden.</div><br><div>Välj en punkt eller polygon på kartan, sök efter en adress eller plats eller släpp en nål på kartan för att visa information om områdena.</div>",
  "defineWhichInfographics": "Definiera vilken infografik som ska finnas tillgänglig i widgeten:",
  "defineWhichReports": "Definiera vilka rapporter som ska finnas tillgängliga i widgeten:",
  "defaultValues": "Standardvärden:",
  "disable": "Inaktivera",
  "drawFreehandPolygon": "Rita frihandspolygon",
  "drawPolygon": "Rita polygon",
  "driveTime": "Körtid",
  "dropPin": "Släpp nål",
  "dynamicHTML": "Dynamisk HTML",
  "exportOptions": "Exportalternativ:",
  "home": "Hem",
  "image": "Bild",
  "infographics": "Infografik",
  "invalidValueRing": "Värdena måste vara inom intervallet 0 till 1 000.",
  "invalidValueDTWT": "Värdena måste vara inom intervallet 0 till 300.",
  "km": "km",
  "makeDefault": "Utse till standard",
  "miles": "engelska mil",
  "minutes": "minuter",
  "options": "Alternativ:",
  "pdf": "PDF",
  "print": "Skriv ut",
  "radius": "Radie",
  "removeDefault": "Ta bort standard",
  "reports": "Rapporter",
  "rings": "Ringar",
  "searchTextBox": "Söktextruta",
  "selectCountryOrRegion": "Välj land eller region:",
  "thisEntryIsNotValid": "Den här inmatningen är inte giltig.",
  "time": "Tid",
  "walkTime": "Gångtid"
});