define({
  "transparencyLabel": "Прозрачность",
  "outline": "Контур",
  "fill": "Заливка (Цвет применяется, только если задан сплошной)",
  "style": "Стиль",
  "mandatoryLabel": "Обязательное расстояние эвакуации",
  "mandatoryButtonLabel": "Настроить обязательное расстояние эвакуации",
  "safeLabel": "Безопасное расстояние эвакуации",
  "safeButtonLabel": "Настроить безопасное расстояние эвакуации",
  "selectOpLayerLabel": "Выберите операционный слой для результатов",
  "selectDefaultMeasurementLabel": "Выберите единицы измерения по умолчанию",
  "helpIconTooltip": "Список операционных слоев заполнен слоями текущей веб-карты с типом геометрии - полигон.",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире – точка",
    "esriSLSDashDotDot": "Тире – точка – точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Длинное тире",
    "esriSLSLongDashDot": "Длинное тире – точка",
    "esriSLSNull": "Пустой",
    "esriSLSShortDash": "Короткое тире",
    "esriSLSShortDashDot": "Короткое тире – точка",
    "esriSLSShortDashDotDot": "Короткое тире – точка – точка",
    "esriSLSShortDot": "Короткая точка",
    "esriSLSSolid": "Сплошной"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Обратно",
    "esriSFSCross": "Перекрестный",
    "esriSFSDiagonalCross": "Диагональ",
    "esriSFSForwardDiagonal": "Прямо",
    "esriSFSHorizontal": "Горизонтально",
    "esriSFSNull": "Пустой",
    "esriSFSSolid": "Сплошной",
    "esriSFSVertical": "Вертикальная"
  },
  "threatTypeLabel": "Тип угрозы",
  "symbologyLabel": "Символы",
  "generalLabel": "Общее",
  "addThreatTypesLabel": "Добавить тип угрозы",
  "threatTypeColLabel": "Тип химической угрозы",
  "actions": "Действия",
  "newThreatTypePopupLabel": "Новый тип угрозы",
  "chooseDefaultThreatTypeIconLabel": "Выбрать из предлагаемых по умолчанию",
  "mandatoryDistance": "Обязательное расстояние эвакуации",
  "safeDistance": "Безопасное расстояние эвакуации",
  "units": "Ед. измерения",
  "chooseDefaultThreatLabel": "Выбрать тип угрозы по умолчанию",
  "defaultThreatTypePopUpLabel": "Типы угрозы по умолчанию",
  "editThreatLabel": "Редактировать угрозу",
  "defaultThreatTypeIconTooltip": "Список типов угрозы по умолчанию",
  "uniqueThreatTypeMsg": "Введите уникальный тип угрозы, тип угрозы с таким именем уже существует.",
  "requiredThreatTypeMsg": "Это поле обязательно",
  "unitMeasureLabel": "Расстояния в {0}",
  "pipeBombLabel": "Самодельная бомба",
  "suicideBombLabel": "Бомба смертника",
  "briefcaseLabel": "Чемоданчик",
  "carLabel": "Легковой автомобиль",
  "suvVanLabel": "Газель",
  "smallDeliveryTruckLabel": "Грузовик",
  "containerWaterTruckLabel": "Контейнеровоз/цистерна",
  "semiTrailerLabel": "Полуприцеп",
  "lpgSafeDistanceLable": "Безопасное расстояние",
  "fireBallDiameterLable": "Диаметр огненного шара",
  "lpgthreatTypeColLabel": "Тип угрозы от сжиженного газа",
  "threatTypeCatagoryLabel": "Категория типа угрозы",
  "chemicalThreatLegendLabel": "Химическая угроза",
  "lpgThreatLegendLabel": "Угроза от сжиженного газа",
  "fireballButtonLabel": "Настроить параметры огненного шара",
  "safeDistanceButtonLabel": "Настроить параметры безопасного расстояния",
  "chemicalThreatCatagoryLabel": "Химическая",
  "lpgThreatCatagoryLabel": "Сжиженный нефтяной газ",
  "smallLPGTank": "Малое хранилище сжиженного газа",
  "largeLPGTank": "Большое хранилище сжиженного газа",
  "commercialResidentialLPGTank": "Коммерческое/Частное хранилище сжиженного газа",
  "smallLPGTruck": "Малый бензовоз для сжиженного газа",
  "semiTankerLPG": "Полутанкер для сжиженного газа"
});