define({
  "feedbackStyleLabel": "Mesafe ve Yön Geri Bildirim Stili",
  "showTabLabel": "Tüm sekmeleri göster",
  "tabErrorMessage": "Lütfen \"Mesafe ve Yön Geri Bildirim Stili\" grubundan en az bir sekme seçin",
  "lineLabel": "Çizgi",
  "circleLabel": "Daire",
  "ellipseLabel": "Elips",
  "ringsLabel": "Halkalar",
  "transparency": "Şeffaflık",
  "operationalLineLayerSelectLabel": "Çizgi ve halka sonuçları için operasyonel bir çoklu çizgi katmanı seçin",
  "operationalPolygonLayerSelectLabel": "Daire ve elips sonuçları için operasyonel bir çokgen katmanı seçin",
  "helpIconPolylineTooltip": "İşlem katmanı listesi, geçerli web haritasından çoklu çizgi geometrisi türünde katmanlarla doldurulur.",
  "helpIconPolygonTooltip": "İşlem katmanı listesi, geçerli web haritasından çokgen geometrisi türünde katmanlarla doldurulur.",
  "feedbackResultsLayerLabel": "Mesafe ve Yön Geri Bildirim Sonuçlar Katmanı",
  "editSymbologyHint": "İpucu: Sembolojiyi düzenlemek için ön izleme simgesine tıklayın",
  "feedbackTextColorLabel": "Geri besleme etiket metin rengi",
  "feedbackTextSizeLabel": "Geri besleme etiket metin boyutu",
  "previewLabel": "Önizleme",
  "lineSymbologyPopupTittle": "Çizgi sembolojisi",
  "circleSymbologyPopupTittle": "Daire sembolojisi",
  "ellipseSymbologyPopupTittle": "Elips sembolojisi",
  "ringSymbologyPopupTittle": "Halkalar sembolojisi"
});