define({
  "_widgetLabel": "데이터 집계",
  "startPage": {
    "defaultStartPageInstructions": "이 위젯을 사용하면 파일에서 가져온 데이터를 처리하여 맵의 선택된 레이어에 제출할 수 있습니다.<br/> <br/> 파일 내의 값은 쉼표, 탭, 세미콜론 또는 수직 막대로 구분되어 있어야 합니다.",
    "dragDrop": "드래그 앤 드롭",
    "browse": "파일로 이동",
    "or": "OR",
    "userPrivilege": "내 계정에 데이터를 만들거나 수정할 권한이 없습니다.",
    "userCredits": "${widgetName}을(를) 사용하려면 ${locator} 로케이터를 사용할 크레딧이 필요합니다.",
    "contactAdmin": "기관 관리자에게 문의하여 추가 크레딧을 요청하세요.",
    "contactAdminEdit": "기관 관리자에게 문의하여 편집 권한을 요청하세요.",
    "canUseLocator": "${locator} 로케이터가 피처를 찾는 데 사용됩니다.",
    "notEnoughCredits": "크레딧이 부족합니다.",
    "locationAndField": "위치 및 필드 정보",
    "locationAndFieldHint": "대상 레이어를 업데이트하는 데 사용해야 하는 값을 파일에서 선택합니다.",
    "cannotUseLocator": "${widgetName}을(를) 사용할 수 없음",
    "noAnonymousEdit": "${layerName} 레이어는 익명 편집을 지원하지 않습니다.",
    "pleaseLogin": "${org} 기관에 Sign in하거나 기관 관리자에게 문의하여 익명 편집 활성화를 요청합니다.",
    "invalidEdit": "잘못된 권한",
    "unableToAccess": "${layerName}에 접속할 수 없음",
    "appropriateCredentials": "적절한 자격 증명으로 Sign in했는지 확인합니다.",
    "shared": "${layerName} 레이어에 대한 접속 권한을 요청하려면 기관 관리자에게 문의하세요.",
    "targetLayerLabel": "대상 레이어",
    "homeButtonLabel": "홈",
    "mappingErrorMsg": "옆의 화살표를 클릭하여 필드 정의"
  },
  "mapping": {
    "schemaMapping": "필드 정보",
    "schemaMappingHint": "파일에서 레이어의 필드와 연관되는 필드를 선택합니다.",
    "locationMapping": "위치 정보",
    "locationMappingHint": "파일에서 사용할 주소 또는 좌표 정보 유형을 선택합니다."
  },
  "locationMapping": {
    "locationMappingPageHint": "위치 유형 선택",
    "useAddress": "주소를 사용하여 찾기",
    "useAddressHint": "주소 정보가 포함된 데이터",
    "useCoordinates": "좌표를 사용하여 찾기",
    "useCoordinatesHint": "X/Y 좌표값이 포함된 데이터"
  },
  "address": {
    "addressPageHint": "주소 유형 선택",
    "singleField": "단일 필드",
    "singleFieldHint": "주소 정보가 포함된 하나의 필드 선택",
    "multiField": "여러 필드",
    "multiFieldHint": "주소 정보가 포함된 여러 필드 선택"
  },
  "coordinates": {
    "coordinatesPageHint": "좌표 데이터가 포함된 여러 필드 선택"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "대상 필드에 매핑할 원본 필드 선택",
    "sourceField": "원본 필드 일치",
    "targetField": "대상 필드"
  },
  "buttons": {
    "addToMap": "맵에 추가",
    "submit": "제출",
    "download": "다운로드"
  },
  "review": {
    "matched": "찾음",
    "reviewMatched": "위치 찾음",
    "reviewMatchedHint": "찾은 위치를 검토합니다.",
    "unMatched": "찾을 수 없음",
    "reviewUnMatched": "위치를 찾을 수 없음",
    "reviewUnMatchedHint": "찾을 수 없는 위치를 검토합니다. 보정되지 않은 항목은 제출되지 않습니다.",
    "duplicate": "복제",
    "reviewDuplicate": "중복 위치",
    "reviewDuplicateHint": "레이어에서 이미 찾은 위치를 검토합니다. 해결되지 않은 항목은 제출되지 않습니다.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "사용:",
    "fromLayer": "대상 정보",
    "target": "대상",
    "source": "소스",
    "fromFile": "원본 정보",
    "locationControlHint": "주소 정보 검토",
    "duplicateAction": "작업 선택",
    "item": "레코드:",
    "locateFeature": "피처 찾기",
    "removeFeature": "피처 제거",
    "featureLocated": "위치 찾음",
    "valuesDoNotMatch": "기존 값과 일치하지 않음",
    "sync": "주소 정보를 필드 정보와 동기화",
    "noFeaturesSaved": "피처가 저장되지 않음",
    "someFeaturesSaved": "${num}개의 피처가 저장되었습니다.",
    "someFeaturesNotSaved": "${num}개의 피처가 저장되지 않았습니다.",
    "feature": "피처 정보 검토",
    "locationInfo": "위치 정보 검토",
    "selectValue": "값 선택",
    "reviewData": "데이터 검토",
    "reviewDataHint": "레이어에 제출하기 전에 데이터를 검토합니다.",
    "reviewFeatureHint": "피처 및 위치 정보를 검토하거나 편집합니다.",
    "duplicateModify": "중복 항목, 변경 필요",
    "duplicateSave": "새 피처로 저장"
  },
  "warningsAndErrors": {
    "invalidCSV": "CSV에서 항목 불러오기 오류, 유효한 CSV 파일을 선택했는지 확인합니다.",
    "noLayersWarning": "유효한 대상 레이어가 구성되지 않음, 구성을 확인합니다.",
    "loadWarning": "이 위젯을 사용하려면 피처 서비스 데이터 원본이 있어야 합니다. 데이터 원본을 정의하는 위젯을 구성하세요.",
    "saveError": "피처를 저장하는 중 오류가 발생했습니다.",
    "consumesCredits": "이 도구는 ArcGIS Online World Geocoding Service와 함께 사용할 때 크레딧을 사용합니다.",
    "noValue": "필드 선택",
    "mappingTitle": "",
    "locationMappingComplete": "위치 매핑 완료",
    "fieldMappingComplete": "필드 매핑 완료",
    "settingsCleared": "설정이 지워집니다.",
    "proceed": "진행하시겠습니까?",
    "itemMoveMatch": "찾은 항목은 위치 찾음 목록으로 이동됨",
    "itemMoveUnMatched": "항목을 찾을 수 없습니다. 위치를 찾을 수 없음 목록으로 이동되었습니다.",
    "itemWillBeLocated": "항목이 중복 위치 목록에서 제거됩니다.",
    "cannotLocate": "항목을 찾을 수 없습니다. 위치 정보를 확인합니다.",
    "invalidMessage": "잘못된 값입니다.",
    "rangeMessage": "값은 ${num}자 미만이어야 합니다.",
    "locatorError": "로케이터가 잘못되었거나 접속할 수 없습니다.",
    "notConfigured": "현재 위치 찾기 옵션에 대해 로케이터가 구성되지 않음",
    "noMoreLocators": "구성된 추가 로케이터가 없음"
  },
  "featureToolbar": {
    "locate": "위치 찾기",
    "save": "레코드 저장",
    "cancel": "편집 내용 취소",
    "cancelTitle": "편집 내용 취소",
    "cancelMessage": "현재 레코드에 대한 편집 내용을 취소하시겠습니까?"
  }
});