define({
  "serviceUrl": "Задати URL сервісу:",
  "minIntSpacingLabel": "Мінімальний розмір сітки",
  "lineOpacityLabel": "Непрозорість лінії",
  "labelOpacityLabel": "Непрозорість напису",
  "centerLabelOpacityLabel": "Непрозорість центрального напису",
  "gridZonePlacementLabel": "Розміщення напису зони сітки",
  "verticalLineLabels": "Написи вертикальних ліній",
  "styleHeaderLabel": "Стиль",
  "indexHeaderLabel": "Компонент сітки",
  "colorHeaderLabel": "Колір",
  "fontSizeHeaderLabel": "Розмір шрифту",
  "lineWidthHeaderLabel": "Ширина лінії",
  "horizontalLabel": "Горизонтальний",
  "verticalLabel": "Вертикальний",
  "upperLeftLabel": "Зверху зліва",
  "upperRightLabel": "Зверху справа",
  "lowerLeftLabel": "Внизу зліва",
  "lowerRightLabel": "Внизу справа",
  "centerLabel": "По центру",
  "errorMessage": "Сторінка конфігурації містить помилки. Виправте помилки перед збереженням.",
  "checkBoxLabel": "Відображати сітку при закритті віджету",
  "checkBoxLabelDashboard": "Відображати сітку",
  "gzd": "Покажчик зони сітки (GZD)",
  "gsid": "${number}-метровий квадратний ідентифікатор сітки (GSID)",
  "grid10k": "${number}-метрові лінії сітки",
  "grid1k": "${number}-метрові лінії сітки",
  "grid100m": "100-метрові лінії сітки",
  "grid10m": "10-метрові лінії сітки",
  "switchBasemap": "Переключити базову карту"
});