define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>영역의 핵심 지표와 데이터를 요약한 인포그래픽과 보고서에 접근합니다.</div><br><div>맵에서 포인트이나 폴리곤을 선택하거나, 주소 또는 장소를 검색하거나, 폴리곤을 그리거나, 맵에 핀을 놓아 영역에 대한 핵심 지표 및 정보를 볼 수 있습니다.</div>",
  "defineWhichInfographics": "위젯에서 사용할 수 있는 인포그래픽 정의:",
  "defineWhichReports": "위젯에서 사용할 수 있는 보고서 정의:",
  "defaultValues": "기본값:",
  "disable": "비활성화",
  "drawFreehandPolygon": "자유곡선 폴리곤 그리기",
  "drawPolygon": "폴리곤 그리기",
  "driveTime": "운전 시간",
  "dropPin": "핀 놓기",
  "dynamicHTML": "DHTML",
  "exportOptions": "내보내기 옵션:",
  "home": "홈",
  "image": "이미지",
  "infographics": "인포그래픽",
  "invalidValueRing": "값은 0~1,000 범위에 속해야 합니다.",
  "invalidValueDTWT": "값은 0~300 범위에 속해야 합니다.",
  "km": "킬로미터",
  "makeDefault": "기본으로 설정",
  "miles": "마일",
  "minutes": "분",
  "options": "옵션:",
  "pdf": "PDF",
  "print": "인쇄",
  "radius": "반경",
  "removeDefault": "기본값 제거",
  "reports": "보고서",
  "rings": "링",
  "searchTextBox": "검색 텍스트 상자",
  "selectCountryOrRegion": "국가 또는 지역 선택:",
  "thisEntryIsNotValid": "이 항목은 유효하지 않습니다.",
  "time": "시간",
  "walkTime": "도보 시간"
});