define({
  "taskUrl": "URL de service du champ de vision",
  "portalURL": "Entrez l’URL de votre organisation ArcGIS Online ou de Portal for ArcGIS",
  "portalURLError": "L’URL configurée pour votre organisation ArcGIS Online ou Portal for ArcGIS n’est pas valide.",
  "privilegeError": "Votre rôle d’utilisateur ne peut pas réaliser d’analyse. Pour effectuer une analyse, l’administrateur de votre organisation doit vous accorder certains <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilèges</a>.",
  "noServiceError": "Le service d’analyse d’altitude n’est pas disponible. Vérifiez les configurations de votre organisation ArcGIS Online ou Portal for ArcGIS.",
  "maximumRangeMessage": "La plage observable maximale doit être supérieure à la plage observable minimale et ne doit pas dépasser ${limit}${units}.",
  "serviceURLPlaceholder": "Saisissez l’URL de la tâche de géotraitement du champ de vision",
  "setTask": "Définir",
  "setTaskTitle": "Définir la tâche de géotraitement du champ de vision",
  "serviceURLError": "La tâche de géotraitement que vous essayez de configurer avec ce widget n’est pas valide. Sélectionnez une URL valide pour la tâche de géotraitement du champ de vision",
  "defaultMilsForAnglesLabel": "Définir des valeurs en mils pour les angles par défaut",
  "defaultObserverHeightLabel": "Unité de hauteur de l’observateur par défaut",
  "defaultObservableDistanceLabel": "Unité de distance observable par défaut",
  "defaultObserveHeightLabel": "Hauteur de l’observateur par défaut",
  "defaultMinimumObservableDistanceLabel": "Distance observable minimale par défaut",
  "defaultMaximumObservableDistanceLabel": "Distance observable maximale par défaut",
  "units": {
    "miles": "Miles",
    "kilometers": "Kilomètres",
    "feet": "Pieds",
    "meters": "Mètres",
    "yards": "Yards",
    "nauticalMiles": "Milles nautiques"
  },
  "helpIconTooltip": "La liste des couches opérationnelles est renseignée à l’aide des couches de la carte Web actuelle dont le type de géométrie est polygone.",
  "selectOperationalLayerLabel": "Sélectionner une couche opérationnelle pour les résultats",
  "lineOfSightTabTitle": "Ligne de visée",
  "symbologyTabTitle": "Symbologie",
  "transparency": "Transparence",
  "outline": "Contour",
  "fill": "Remplissage (la couleur s’applique uniquement lorsque le style est défini sur Uni)",
  "style": "Style",
  "selectOpLayerLabel": "Sélectionner une couche opérationnelle pour les résultats",
  "selectDefaultMeasurementLabel": "Sélectionner une unité de mesure par défaut.",
  "visibleSectionLabel": "Section visible",
  "nonVisibleSectionLabel": "Section non visible",
  "visibleSectionButtonLabel": "Configurer les paramètres de la section visible",
  "nonVisibleSectionButtonLabel": "Configurer les paramètres de la section non visible",
  "colorPicker": "Sélecteur de couleurs",
  "lineStyles": {
    "esriSLSDash": "Tiret",
    "esriSLSDashDot": "Tiret-point",
    "esriSLSDashDotDot": "Tiret-point-point",
    "esriSLSDot": "Point",
    "esriSLSLongDash": "Tiret long",
    "esriSLSLongDashDot": "Tiret long-point",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Tiret court",
    "esriSLSShortDashDot": "Tiret court-point",
    "esriSLSShortDashDotDot": "Tiret court-point-point",
    "esriSLSShortDot": "Point court",
    "esriSLSSolid": "Uni"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Arrière",
    "esriSFSCross": "Croix",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Avant",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Uni",
    "esriSFSVertical": "Vertical"
  }
});