define({
  "_widgetLabel": "Visibilidade",
  "observerLocation": "Localização do Observador",
  "formatIconTooltip": "Entrada de Formato",
  "addPointToolTip": "Adicionar Localização do Observador",
  "fieldOfView": "Campo de Visualização",
  "useMilsText": "Utilizar milésimo para ângulos",
  "observerHeight": "Altura do Observador",
  "minObsDistance": "Distância Mínima Observável",
  "maxObsDistance": "Distância Máxima Observável",
  "taskURLError": "O arquivo de configuração do widget contém uma URL que é inalcançável. Confira com seu administrador do sistema",
  "taskURLInvalid": "A tarefa de geoprocessamento configurada com este widget não é válida. Confira com seu administrador do sistema",
  "viewshedError": "Ocorreu um erro ao criar visibilidade. Garanta que a localização do seu observador caia dentro da extensão da sua superfície de elevação.</p>",
  "validationError": "<p>O formulário de criação de visibilidade tem parâmetros inválidos ou ausentes, garanta que:</p><ul><li>Uma localização do observador tenha sido definida.</li><li>O Campo de Visualização do observador não seja 0.</li><li>A altura do observador contém um valor válido.</li><li>As distâncias observáveis mínimas e máximas contém valores válidos.</li></ul>",
  "comfirmInputNotation": "Confirmar Anotação de Entrada",
  "notationsMatch": "anotações que correspondem à sua entrada, confirme o que você gostaria de utilizar:",
  "createBtn": "Criar",
  "clearBtn": "Apagar",
  "setCoordFormat": "Definir String de Formato de Coordenadas",
  "prefixNumbers": "Adicionar o prefixo '+/-' para números positivos e negativos",
  "parseCoordinatesError": "Não é possível analisar coordenadas. Verifique sua entrada.",
  "cancelBtn": "Cancelar",
  "applyBtn": "Aplicar",
  "invalidMessage": "Insira um valor numérico.",
  "observerRangeMessage": "Altura do Observador Inválida",
  "minimumRangeMessage": "Intervalo Mínimo Observável Inválido",
  "maximumRangeMessage": "O Intervalo Máximo Observável deve ser maior que o Intervalo Mínimo Observável e não pode ser superior a ${limit} ${units}.",
  "portalURLError": "A URL para sua organização do ArcGIS Online ou Portal for ArcGIS não está configurada. Verifique com seu administrador de sistema.",
  "privilegeError": "Seu papel de usuário não pode executar análise. Para executar análise, o administrador da sua organização precisa conceder a você determinados <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilégios</a>.",
  "noServiceError": "Serviço de análise de elevação não disponível. Verifique as configurações da sua organização do ArcGIS Online ou Portal for ArcGIS.",
  "pointToolTooltip": "Clique para adicionar localização do observador",
  "degreesLabel": "graus",
  "milsLabel": "milésimo",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Minutos Decimais - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Minutos Decimais - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra da Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)",
  "mainPageTitle": "Linha de Visada Radial",
  "resultsTitle": "Resultados",
  "publishBtnLabel": "Publicar",
  "layerName": "Nome da Camada Publicada",
  "invalidLayerName": "O nome da camada deve conter somente caracteres alfanuméricos e underscores",
  "back": "Voltar",
  "publishingFailedLayerExists": "Falha na Publicação: Você já tem um serviço de feição denominado {0}. Escolha outro nome.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não foi possível criar: {0}",
  "addToDefinition": "Adicionar à definição: {0}",
  "successfullyPublished": "Camada da web publicada com sucesso{0}Gerenciar a camada da web",
  "userRole": "Não foi possível criar serviço pois o usuário não tem permissões",
  "publishToNewLayer": "Publicar resultados para uma nova camada de feição",
  "missingLayerNameMessage": "Você deve inserir um nome de camada válida antes de poder publicar",
  "layerNameExists": "O nome da camada já existe. Utilize um nome de camada diferente.",
  "regionTypeLabel": "Tipo de Região",
  "centerPointLabel": "Ponto Central",
  "observationHeightLabel": "Altura de Observação",
  "heightUnitLabel": "Unidades de Altura",
  "minObservationDistanceLabel": "Distância Mínima de Observação",
  "maxObservationDistance": "Distância Máxima de Observação",
  "distanceUnitLabel": "Unidade de Distância",
  "fovstartAngleLabel": "Ângulo Inicial FOV",
  "fovEndAngleLabel": "Ângulo Final FOV",
  "andleUnitsLabel": "Unidade do Ângulo",
  "visibleSectionLabel": "Seção visível",
  "nonVisibleSectionLabel": "Seção não visível",
  "visibleSectionButtonLabel": "Definir as configurações da seção visível",
  "nonVisibleSectionButtonLabel": "Definir as configurações da seção não visível",
  "transparency": "Transparência",
  "outline": "Contorno",
  "fill": "Preencher (a cor somente se aplica quando o estilo é definido para sólido)",
  "style": "Estilo",
  "colorPicker": "Seletor de Cores",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Ponto Traço Curto",
    "esriSLSShortDashDotDot": "Ponto Ponto Traço Curto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Para Trás",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para Frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "settingsTitle": "Configurações"
});