define({
  "_widgetLabel": "Отчет за обект",
  "select": "Избор",
  "draw": "Изчертаване",
  "chooseALayer": "Избиране на слой",
  "clickAFeature": "Натиснете върху обект на картата, за да го изберете.",
  "loadingFeatures": "Получават се подробности за избрания обект ...",
  "errorTitle": "Грешка",
  "errorIdentify": "Идентифицирайте грешката на обектите. Моля, проверете регистъра на конзолата за подробности.",
  "infoWindowTitle": "Подробни данни",
  "layerLabel": "Име на слой",
  "reviewStatusLabel": "Преглед на състояние",
  "selectReviewStatusAdd": "Добавяне на обект",
  "selectReviewStatusDelete": "Изтриване на обект",
  "selectReviewStatusMove": "Преместване на обект",
  "selectReviewStatusReshape": "Повторно оформяне на обект",
  "drawReviewStatusMissing": "Липсващ обект(и)",
  "drawReviewStatusPosition": "Позиционна грешка",
  "drawReviewStatusShape": "Грешка във формата",
  "drawReviewStatusAttribute": "Грешка на атрибут",
  "notesLabel": "Бележки",
  "severityLabel": "Щателност (на преглед)",
  "reportedByLabel": "Докладван от",
  "reportedByDefault": "анонимен",
  "reportButton": "Отчет",
  "reportMessage": "Отчетът е получен",
  "errorReportMessage": "При докладването на обекта ви възникна грешка",
  "drawErrorInstructions": "Изберете точка, линия или полигон и начертайте геометрията на грешката на картата:",
  "errorMapService": "При получаването на информация за услугата на картата възникна грешка",
  "noFeatureSelected": "Не бяха намерени обекти на избраното местоположение",
  "selectFeatureMapPoint": "Натиснете, за да изберете обект",
  "drawFeatureMapPoint": "Натиснете, за да добавите точка",
  "popupMessage": "Съобщение",
  "popupError": "Грешка",
  "manyFeaturesSelected": "Намерен е повече от един обект. Моля, увеличете и изберете обект за докладване."
});