define({
  "transparencyLabel": "Läbipaistvus",
  "outline": "Äärejoon",
  "fill": "Täida (värv rakendatakse ainult juhul, kui valitud on pidev laad)",
  "style": "Laad",
  "selectOpLayerLabel": "Vali tulemuste töökiht",
  "selectDefaultMeasurementLabel": "Vali vaikimisi mõõtühik",
  "helpIconTooltip": "Töökihtide nimekiri sisaldab kihte praeguselt veebikaardilt, mis on polügooni tüüpi.",
  "lineStyles": {
    "esriSLSDash": "Katkendlik",
    "esriSLSDashDot": "Katkendlik punktiga",
    "esriSLSDashDotDot": "Katkendlik kahe punktiga",
    "esriSLSDot": "Punktiir",
    "esriSLSLongDash": "Pikk katkendlik kriips",
    "esriSLSLongDashDot": "Pikk katkendlik kriips punktiga",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lühike katkendlik kriips",
    "esriSLSShortDashDot": "Lühike katkendlik kriips punktiga",
    "esriSLSShortDashDotDot": "Lühike katkendlik kriips kahe punktiga",
    "esriSLSShortDot": "Lühike punktiir",
    "esriSLSSolid": "Pidev"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Tagasi",
    "esriSFSCross": "Rist",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Edasi",
    "esriSFSHorizontal": "Horisontaalne",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Pidev",
    "esriSFSVertical": "Vertikaalne"
  },
  "threatTypeLabel": "Ohu tüüp",
  "generalLabel": "Üldine",
  "addThreatTypesLabel": "Lisa ohu tüüp",
  "actions": "Toimingud",
  "newThreatTypePopupLabel": "Uus ohu tüüp",
  "units": "Ühikud",
  "chooseDefaultThreatLabel": "Vali ohu vaiketüüp",
  "defaultThreatTypePopUpLabel": "Ohu vaiketüübid",
  "editThreatLabel": "Muuda ohtu",
  "defaultThreatTypeIconTooltip": "Ohu vaiketüüpide loend",
  "uniqueThreatTypeMsg": "Sisestage unikaalne ohu tüüp; selle nimega ohu tüüp on juba olemas.",
  "requiredMsg": "See väli on nõutav",
  "unitMeasureLabel": "Kauguste mõõtühik on {0}",
  "chooseDefaultThreatTypeIconLabel": "Vali vaikeväärtusest",
  "pipeBombLabel": "Torupomm",
  "suicideBombLabel": "Enesetapupomm",
  "briefcaseLabel": "Portfell",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Väike kaubaauto",
  "containerWaterTruckLabel": "Konteinerveok/Veepaagiga veok",
  "semiTrailerLabel": "Poolhaagis",
  "chemicalThreatLegendLabel": "Keemiline oht",
  "lpgThreatLegendLabel": "LPG oht",
  "smallLPGTank": "Väike LPG paak",
  "largeLPGTank": "Suur LPG paak",
  "commercialResidentialLPGTank": "Äriline/elamu LPG paak",
  "smallLPGTruck": "Väike LPG veok",
  "semiTankerLPG": "Poolhaagisega LPG tsisternveok",
  "threatDescriptionColLabel": "Ohu kirjeldus",
  "addThreatZoneButtonLabel": "Lisa ohutsoon",
  "zoneDescColLabel": "Tsooni kirjeldus",
  "distanceLabel": "Kaugus (${unitAbbr})",
  "threatTypeHelp": "<p>Veenduge, et ohutüüp vastab järgmistele tingimustele:<br/><ul><li>ohutüübi väli ei tohi olla tühi ja see peab olema kordumatu</li><li>ohul peab olema vähemalt üks kehtiv tsoon</li><li>tsooni kirjeldus peab ohu jaoks olema kordumatu</li></ul><p/>",
  "descriptionLabel": "Kirjeldus",
  "newThreatZonePopupLabel": "Uus ohutsoon",
  "editThreatZonePopupLabel": "Muuda ohutsooni",
  "uniqueZoneDescriptionMsg": "Sisestage kordumatu ohukirjeldus. Selle nimega ohukirjeldus on juba olemas.",
  "symbologyColLabel": "Sümboloogia",
  "zoneDescriptionColLabel": "Tsooni kirjeldus",
  "uniqueZoneRequiredMsg": "Tsooni nimi peab olema kordumatu:",
  "interactive": "Interaktiivne",
  "fromCoord": "Fikseeritud koordinaat",
  "existingFeature": "Olemasolevatest objektidest",
  "defaultInputLocationLabel": "Sisendi vaikeasukoht",
  "defaultInputLayer": "Sisendi vaikekiht",
  "defaultThreatType": "Ohu vaiketüüp",
  "selectLabel": "Vali",
  "mandatoryLabel": "Kohustuslik evakueerimise kaugus",
  "safeLabel": "Ohutu evakueerimise kaugus",
  "lpgSafeDistanceLable": "Ohutu vahemaa",
  "fireBallDiameterLable": "Tulekera läbimõõt"
});