define({
  "locatorUrl": "URL adresa lokatora",
  "set": "Postavi",
  "locatorName": "Naziv lokatora",
  "locatorExample": "Primer",
  "countryCode": "Kôd(ovi) zemlje ili regiona",
  "eg": "npr. ",
  "countryCodeHint": "Ako ova vrednost ostane prazna, pretražuju se sve zemlje i regioni",
  "minCandidateScore": "Minimalni rezultat kandidata",
  "minCandidateScoreHint": "Ako ostavite ovu vrednost praznom, minimalni rezultat kandidata od 90 će da bude korišćen",
  "enableSingleField": "Opcije jednog polja",
  "singleFieldHint": "Podaci adrese će da budu u jednom polju",
  "enableMultiField": "Opcije više polja",
  "multiFieldHint": "Podaci adrese će da budu u više polja",
  "enableXYField": "Opcije X/Y polja",
  "xyFieldHint": "Podaci će da sadrže vrednosti X/Y koordinate",
  "instructionGeocode": "Dodaj i podesi uslugu lokacije.",
  "invalidUrlTip": "URL adresa ${URL} nije validna ili nije dostupna.",
  "geocodeTabLabel": "Postavke lokacije",
  "lookupList": "Nazivi polja za prepoznavanje",
  "isRecognized": "Nazivi polja u tabeli ispod su automatski prepoznati za ovo polje",
  "needsEditablePointLayers": "Veb mapa mora da sadrži makar jedan tačkasti sloj koji može da se uređuje.",
  "editpageAlias": "Pseudonim",
  "configureFields": "Konfigurišite polja sloja",
  "configureSingleFields": "Konfiguriši jedno polje za adresu",
  "configureMultiFields": "Konfiguriši više polja za adresu",
  "configureXYFields": "Konfiguriši X/Y polja",
  "noFields": "Upotrebite postupak za uređivanje da biste definisali jedno ili više polja za prikaz",
  "display": "Prikaz",
  "duplicate": "Pronađi duplikat",
  "duplicateTip": "Pretražite ovo polje za identične vrednosti između izvorne datoteke i ciljanog sloja./n Kada se pronađe identično poklapanje, zapis iz datoteke neće biti lociran i biće i označen kao duplikat.",
  "noSelectField": "Prvo izaberite opciju Sloj geoobjekta",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (geografska dužina)",
  "xyFieldsLabelY": "Y (geografska širina)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Razdaljina u odnosu na Y osu",
  "northing": "Razdaljina u odnosu na X osu",
  "lon": "DUŽ.",
  "lat": "ŠIR.",
  "layerOptionHint": "Izaberite sloj za slanje podataka.",
  "layerFieldTitle": "Ciljani sloj",
  "tempSymbolHint": "Izaberite simbol koji će se koristiti za prikaz geoobjekata.",
  "tempSymbolTitle": "Simbol za prikaz",
  "maxRecords": "Maksimalno zapisa",
  "maxRecordsHint": "Maksimalni broj zapisa za lociranje",
  "searchRadius": "Prečnik pretrage",
  "searchRadiusHint": "Razdaljina za pretragu za duplikate geoobjekata sa sloja",
  "requiresInteger": "Unesite numeričku vrednost.",
  "requiresInteger0100": "Unesite numeričku vrednost između 0 i 100.",
  "requiresLocator": "Dodajte bar jedan validni lokator.",
  "layerFields": "Postavke sloja",
  "layerFieldsHint": "Navedite polja iz ciljanog sloja koji će biti mapiran u izvornim poljima.",
  "locatorError": "Lokator je pogrešan ili nedostupan.",
  "optionNotMatch": "Opcije za polja nisu dosledne na lokacijama. Prelivanje možda neće raditi kao što se očekuje.",
  "targetLayerTabTitle": "Ciljani sloj",
  "locationSettingsTabTitle": "Postavke lokacije",
  "generalSettingsTabTitle": "Opšte postavke",
  "addTargetLayersLabel": "Dodaj ciljani sloj",
  "introductoryText": "Kreiranje instrukcionog sadržaja za vidžet",
  "defaultStartPageInstructions": "Ovaj vidžet će pomoći u obradi i prenosu podataka iz datoteke u izabrani sloj na mapi.<br/> <br/> Vrednosti u okviru datoteke moraju da se odvoje zapetom, tabulatorom, tačka zapetom ili vertikalnom crtom.",
  "noTargetLayerConfiguredErrorMsg": "Nema podešenog ciljanog sloja",
  "noFieldsForTargetLayer": "Podešavanja sloja nisu definisana za ciljani sloj",
  "locationSettingsNotConfigured": "Podešavanja lokacije nisu pravilno postavljena",
  "questionMark": "?"
});