define({
  "taskUrl": "가시권역 서비스 URL",
  "portalURL": "ArcGIS Online 기관 또는 Portal for ArcGIS의 URL을 지정합니다.",
  "portalURLError": "ArcGIS Online 기관 또는 Portal for ArcGIS에 구성된 URL이 유효하지 않습니다.",
  "privilegeError": "귀하의 사용자 역할은 분석을 수행할 수 없습니다. 분석을 수행하려면 내 기관의 관리자가 특정 <a href=”http://doc.arcgis.com/en/arcgis-online/reference/roles.htm” target=”_blank”>권한</a>을 부여해야 합니다.",
  "noServiceError": "고도 분석 서비스를 사용할 수 없습니다. ArcGIS Online 기관 또는 Portal for ArcGIS의 구성을 확인하세요.",
  "maximumRangeMessage": "관측 가능한 최대 범위는 관측 가능한 최소 범위보다 커야 하며 ${limit} ${units}을(를) 초과할 수 없습니다.",
  "serviceURLPlaceholder": "가시권역 지오프로세싱 작업 URL을 입력하세요.",
  "setTask": "설정",
  "setTaskTitle": "가시권역 지오프로세싱 작업 설정",
  "serviceURLError": "이 위젯으로 구성하려는 지오프로세싱 작업이 올바르지 않습니다. 올바른 가시권역 지오프로세싱 작업 URL을 선택하세요.",
  "defaultMilsForAnglesLabel": "밀을 각도의 기본 단위로 설정",
  "defaultObserverHeightLabel": "기본 관측자 높이 단위",
  "defaultObservableDistanceLabel": "기본 관측 가능 거리 단위",
  "defaultObserveHeightLabel": "기본 관측자 높이",
  "defaultMinimumObservableDistanceLabel": "기본 관측 가능 최소 거리",
  "defaultMaximumObservableDistanceLabel": "기본 관측 가능 최대 거리",
  "units": {
    "miles": "마일",
    "kilometers": "킬로미터",
    "feet": "피트",
    "meters": "미터",
    "yards": "야드",
    "nauticalMiles": "해리"
  },
  "helpIconTooltip": "운영 레이어 목록은 폴리곤 지오메트리 유형인 현재 웹맵의 레이어로 채워집니다.",
  "selectOperationalLayerLabel": "결과에 대한 운영 레이어 선택",
  "lineOfSightTabTitle": "가시선",
  "symbologyTabTitle": "심볼",
  "transparency": "투명도",
  "outline": "윤곽선",
  "fill": "채우기(스타일이 솔리드로 설정된 경우에만 색상이 적용됨)",
  "style": "스타일",
  "selectOpLayerLabel": "결과에 대한 운영 레이어 선택",
  "selectDefaultMeasurementLabel": "측정의 기본 단위 선택",
  "visibleSectionLabel": "보이는 섹션",
  "nonVisibleSectionLabel": "보이지 않는 섹션",
  "visibleSectionButtonLabel": "보이는 섹션 설정 구성",
  "nonVisibleSectionButtonLabel": "보이지 않는 섹션 설정 구성",
  "colorPicker": "색상 선택기",
  "lineStyles": {
    "esriSLSDash": "대시",
    "esriSLSDashDot": "대시 점",
    "esriSLSDashDotDot": "대시 점 점",
    "esriSLSDot": "점",
    "esriSLSLongDash": "긴 대시",
    "esriSLSLongDashDot": "긴 대시 점",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "짧은 대시",
    "esriSLSShortDashDot": "짧은 대시 점",
    "esriSLSShortDashDotDot": "짧은 대시 점 점",
    "esriSLSShortDot": "짧은 점",
    "esriSLSSolid": "실선"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "뒤로",
    "esriSFSCross": "십자모양",
    "esriSFSDiagonalCross": "대각선",
    "esriSFSForwardDiagonal": "순방향",
    "esriSFSHorizontal": "수평",
    "esriSFSNull": "Null",
    "esriSFSSolid": "실선",
    "esriSFSVertical": "수직"
  }
});