define({
  "_widgetLabel": "Viditeľnosť",
  "observerLocation": "Umiestnenie pozorovateľa",
  "formatIconTooltip": "Formát vstupu",
  "addPointToolTip": "Pridať umiestnenie pozorovateľa",
  "fieldOfView": "Pole pohľadu",
  "useMilsText": "Použiť mily pre uhly",
  "observerHeight": "Výška pozorovateľa",
  "minObsDistance": "Minimálna pozorovateľná vzdialenosť",
  "maxObsDistance": "Maximálna pozorovateľná vzdialenosť",
  "taskURLError": "Konfigurácia widgetu obsahuje URL, ktorá je nedostupná Prosím skonzultujte so svojím systémovým administrátorom",
  "taskURLInvalid": "Geoprocesná úloha nakonfigurovaná s týmto widgetom nie je platná. Prosím skonzultujte so svojím systémovým administrátorom",
  "viewshedError": "Chyba nastala pri vykonávaní analýzy viditeľnosti. Prosím uistite sa, že vaše umiestnenie pozorovateľa spadá do oblasti rozsahu vášho povrchu nadmorských výšok.</p>",
  "validationError": "<p>Formulár pre analýzu viditeľnosti má chýbajúce alebo neplatné parametre, prosím uistite sa:</p><ul><li>A umiestnenie pozorovateľa bolo nastavené.</li><li> Pole pohľadu pozorovateľa nie je 0.</li><li>Výška pozorovateľa obsahuje platnú hodnotu.</li><li>Minimálna a maximálna pozorovateľná vzdialenosť obsahuje platné hodnoty.</li></ul>",
  "comfirmInputNotation": "Potvrdiť zápis vstupu",
  "notationsMatch": "zápisy zodpovedajú vášmu vstupu, prosím potvrďte, ktoré chcete použiť:",
  "createBtn": "Vytvoriť",
  "clearBtn": "Vyčistiť",
  "setCoordFormat": "Nastaviť zápis formátu súradníc",
  "prefixNumbers": "Pridať \"+/-\" ku kladným a záporným číslam",
  "parseCoordinatesError": "Nie je možné interpretovať súradnice. Skontrolujte svoj vstup.",
  "cancelBtn": "Zrušiť",
  "applyBtn": "Použiť",
  "invalidMessage": "Zadajte číselnú hodnotu.",
  "observerRangeMessage": "Neplatná výška pozorovateľa",
  "minimumRangeMessage": "Neplatný minimálny pozorovateľný rozsah",
  "maximumRangeMessage": "Maximálny pozorovateľný rozsah musí byť väčší ako minimálny porozovateľný rozsah a nemôže byť väčší ako ${limit}${units}.",
  "portalURLError": "URL adresa k vašej ArcGIS Online organizácii alebo Portálu pre ArcGIS nie je konfigurovaná. Prosím skonzultujte so svojím systémovým administrátorom",
  "privilegeError": "Vaša rola používateľa nemôže vykonať analýzu. Ak chcete vykonať analýzu, správca vašej organizácie vám musí udeliť určité<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">oprávnenia</a>.",
  "noServiceError": "Služba analýzy nadmorskej výšky nie je dostupná. Prosím skontrolujte vaše ArcGIS Online organizáciu alebo Portal pre ArcGIS konfigurácie.",
  "pointToolTooltip": "Kliknite pre pridanie umiestnenia pozorovateľa",
  "degreesLabel": "stupne",
  "milsLabel": "Míle",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desatinné stupne - Zemepisná šírka/dĺžka",
  "DDLongLatNotation": "Desatinné stupne - Zemepisná dĺžka/šírka",
  "DDMLatLongNotation": "Stupne desatinné minúty - Zemepisná šírka/dĺžka",
  "DDMLongLatNotation": "Stupne desatinné minúty - Zemepisná dĺžka/šírka",
  "DMSLatLongNotation": "Stupne minúty sekundy - Zemepisná šírka/dĺžka",
  "DMSLongLatNotation": "Stupné minúty sekundy - Zemepisná dĺžka/šírka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - znak pásma",
  "UTMHemNotation": "UTM - pologuľa (S/J)",
  "mainPageTitle": "Radiálne zorné pole",
  "resultsTitle": "Výsledky",
  "publishBtnLabel": "Publikovať",
  "layerName": "Názov publikovanej vrstvy",
  "invalidLayerName": "Názov vrstvy musí obsahovať iba alfanumerické znaky a podčiarkovníky",
  "back": "Späť",
  "publishingFailedLayerExists": "Publikovanie zlyhalo: Už máte službu pre prvky s názvom {0}. Vyberte iný názov.",
  "checkService": "Skontrolovať službu: {0}",
  "createService": "Vytvoriť službu: {0}",
  "unableToCreate": "Nebolo možné vytvoriť: {0}",
  "addToDefinition": "Pridať do definície: {0}",
  "successfullyPublished": "Webová vrstva úspešne publikovaná{0} Spravovať webovú vrstvu",
  "userRole": "Nebolo možné vytvoriť službu, pretože používateľ nemá povolenia",
  "publishToNewLayer": "Publikovať výsledky do novej vrstvy prvkov",
  "missingLayerNameMessage": "Pred publikovaním musíte zadať platný názov vrstvy",
  "layerNameExists": "Názov vrstvy už existuje. Použite iný názov vrstvy.",
  "regionTypeLabel": "Typ regiónu",
  "centerPointLabel": "Stredový bod",
  "observationHeightLabel": "Výška pozorovania",
  "heightUnitLabel": "Jednotka výšky",
  "minObservationDistanceLabel": "Minimálna vzdialenosť pozorovania",
  "maxObservationDistance": "Maximálna vzdialenosť pozorovania",
  "distanceUnitLabel": "Jednotka vzdialenosti",
  "fovstartAngleLabel": "FOV začiatočný uhol",
  "fovEndAngleLabel": "Oblasť pohľadu (Field-Of-View) - konečný uhol",
  "andleUnitsLabel": "Jednotky uhla",
  "visibleSectionLabel": "Viditeľná sekcia",
  "nonVisibleSectionLabel": "Neviditeľná sekcia",
  "visibleSectionButtonLabel": "Konfigurovať nastavenia viditeľnej sekcie",
  "nonVisibleSectionButtonLabel": "Konfigurovať nastavenia neviditeľnej sekcie",
  "transparency": "Priehľadnosť",
  "outline": "Obrys",
  "fill": "Výplň (Farba sa použije iba v prípade, že je štýl nastavený na plný)",
  "style": "Štýl",
  "colorPicker": "Výber farby",
  "lineStyles": {
    "esriSLSDash": "Pomlčka",
    "esriSLSDashDot": "Pomlčka bodka",
    "esriSLSDashDotDot": "Pomlčka bodka bodka",
    "esriSLSDot": "Bodka",
    "esriSLSLongDash": "Dlhá pomlčka",
    "esriSLSLongDashDot": "Dlhá pomlčka bodka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Krátka pomlčka",
    "esriSLSShortDashDot": "Krátka pomlčka bodka",
    "esriSLSShortDashDotDot": "Krátka pomlčka bodka bodka",
    "esriSLSShortDot": "Krátka bodka",
    "esriSLSSolid": "Plné"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Späť",
    "esriSFSCross": "Priečne",
    "esriSFSDiagonalCross": "Uhlopriečne",
    "esriSFSForwardDiagonal": "Vpred",
    "esriSFSHorizontal": "Vodorovný",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Plné",
    "esriSFSVertical": "Zvislý"
  },
  "settingsTitle": "Nastavenia"
});