define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Ihrem Konto sind keine Berechtigungen zum Erstellen oder Ändern von Daten zugewiesen.",
  "loginPopupTitle": "Anmelden",
  "loginPopupMessage": "Zum Suchen und Speichern von Adresseninformationen mit ${widgetName} sind Berechtigungen und Credits erforderlich. Möchten Sie sich anmelden und diese Funktion verwenden?",
  "noCreditsOrPrivilegeWarningMessage": "Ihrem Konto sind keine Berechtigungen und Credits zum Suchen und Speichern von Adresseninformationen mit ${widgetName} zugewiesen. Wenden Sie sich an den Organisationsadministrator, um Berechtigungen und Credits anzufordern. Klicken Sie auf OK, um die Bearbeitung fortzusetzen.",
  "unableToUseLocator": "Auf den Locator kann nicht zugegriffen werden. Die Adress-Attributaktionen werden nicht durchgeführt. Klicken Sie auf OK, um die Bearbeitung fortzusetzen.",
  "locatorDisabledWaning": "Locator ist nicht aktiviert. Wenden Sie sich an den Organisationsadministrator, um diese Funktion anzufordern. Klicken Sie auf OK, um die Bearbeitung fortzusetzen.",
  "noFeatureInAIWarning": "Keine Features ausgewählt. Wählen Sie ein Feature aus, um Bearbeitungen vorzunehmen, oder klicken Sie auf \"Abbrechen\", um zum Hauptbildschirm zurückzukehren.",
  "noEditableLayerWarning": "Ihrem Konto sind keine Berechtigungen zum Erstellen oder Ändern von Daten zugewiesen, oder diese Webkarte enthält keine editierbaren Layer.",
  "noVisibleCreateLayerWarning": "Layer auf der aktuellen Zoomstufe nicht sichtbar. Vergrößern oder verkleinern Sie die Ansicht, um Features zu erstellen/zu ändern.",
  "noVisibleUpdateLayerWarning": "Layer auf der aktuellen Zoomstufe nicht sichtbar. Vergrößern oder verkleinern Sie die Ansicht, um Features zu ändern.",
  "checkLayerVisibilityInWebMapWarning": "Stellen Sie sicher, dass Layer auf der Karte sichtbar sind, um Features zu erstellen oder zu ändern.",
  "showSelectionInAITitle": "Ausgewählte Features",
  "showSelectionInAIMsg": "Möchten Sie die aktuelle Auswahl in ${widgetName} laden?",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Nicht aktiv",
  "pressStr": "Drücken Sie ",
  "ctrlStr": " STRG ",
  "snapStr": " , um die Fangfunktion zu aktivieren.",
  "noAvailableTempaltes": "Keine verfügbaren Vorlagen",
  "editorCache": " - Editor-Cache",
  "presetFieldAlias": "Feld",
  "presetValue": "Voreingestellter Wert",
  "usePresetValues": " Voreingestellte Werte verwenden (nur neue Features)",
  "editGeometry": " Geometrie bearbeiten",
  "savePromptTitle": "Feature speichern",
  "savePrompt": "Möchten Sie das aktuelle Feature speichern?",
  "deletePromptTitle": "Feature löschen",
  "deleteAttachment": "Anlage löschen",
  "deletePrompt": "Soll das ausgewählte Feature tatsächlich gelöscht werden?",
  "attachmentLoadingError": "Fehler beim Hochladen der Anlagen",
  "attachmentSaveDeleteWarning": "Warnung: Änderungen an Anlagen werden automatisch gespeichert.",
  "autoSaveEdits": "Neue Features automatisch speichern",
  "addNewFeature": "Neues Feature erstellen",
  "featureCreationFailedMsg": "Neuer Datensatz/neues Feature kann nicht erstellt werden",
  "relatedItemTitle": "Zugehörige(r) Tabelle/Layer",
  "relatedFeatureCount": "${layerTitle} mit ${featureCount} Features",
  "createNewFeatureLabel": "Neues Feature für ${layerTitle} erstellen",
  "invalidRelationShipMsg": "Stellen Sie sicher, dass der Wert des Primärschlüsselfeldes '${parentKeyField}' gültig ist.",
  "pendingFeatureSaveMsg": "Speichern Sie die Feature-Änderungen, bevor Sie ein zugehöriges Feature erstellen.",
  "attachmentsRequiredMsg": "(*) Anlagen sind erforderlich.",
  "coordinatePopupTitle": "Feature an XY-Position verschieben",
  "coordinatesSelectTitle": "Koordinatensystem:",
  "mapSpecialReferenceDropdownOption": "Raumbezug der Karte",
  "latLongDropdownOption": "Breitengrad/Längengrad",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Koordinate:",
  "xAttributeTextBoxLabel": "X-Koordinate:",
  "yAttributeTextBoxLabel": "Y-Koordinate:",
  "latitudeTextBoxLabel": "Breitengrad:",
  "longitudeTextBoxLabel": "Längengrad:",
  "presetGroupFieldsLabel": "\"${groupName}\" wird für die folgenden Layer-Felder übernommen:",
  "presetGroupNoFieldsLabel": "\"${groupName}\" sind keine Felder zugeordnet.",
  "groupInfoLabel": "Gruppeninformationen für \"${groupName}\"",
  "editGroupInfoIcon": "Gruppenwert für \"${groupName}\" bearbeiten",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Keine verfügbaren Vorlagen",
    "searchTemplates": "Vorlagen durchsuchen",
    "filterLayerLabel": "Layer filtern"
  },
  "invalidConfiguration": "Das Widget wurde nicht konfiguriert oder die Layer in der Konfiguration sind nicht mehr in der Karte enthalten.  Öffnen Sie die App im Builder-Modus, und konfigurieren Sie das Widget neu.",
  "geometryServiceURLNotFoundMSG": "URL des Geometrieservice kann nicht abgerufen werden",
  "clearSelection": "Schließen",
  "refreshAttributes": "Dynamische Feature-Attribute aktualisieren",
  "automaticAttributeUpdatesOn": "Feature-Attribute automatisch aktualisieren: EIN",
  "automaticAttributeUpdatesOff": "Feature-Attribute automatisch aktualisieren: AUS",
  "moveSelectedFeatureToGPS": "Selektiertes Feature an aktuelle GPS-Position verschieben",
  "moveSelectedFeatureToXY": "Selektiertes Feature an XY-Position verschieben",
  "mapNavigationLocked": "Kartennavigation: Gesperrt",
  "mapNavigationUnLocked": "Kartennavigation: Entsperrt",
  "copyFeatures": {
    "title": "Zu kopierende Features auswählen",
    "createFeatures": "Features erstellen",
    "createSingleFeature": "1 Multipart-Feature erstellen",
    "createOneSingleFeature": "Feature erstellen",
    "noFeaturesSelectedMessage": "Keine Features ausgewählt",
    "selectFeatureToCopyMessage": "Wählen Sie Features für den Kopiervorgang aus.",
    "multipleFeatureSaveWarning": "Beim Erstellen mehrerer Features mit dieser Funktionalität werden alle neuen Features sofort gespeichert. Der Feldabgleich wird beim Erstellen eines neuen Multipart-Features nicht unterstützt.",
    "copyFeatureUpdateGeometryError": "Die Geometrie der ausgewählten Features kann nicht aktualisiert werden.",
    "canNotSaveMultipleFeatureWarning": "Sie können nur ein Feature kopieren, wenn der Ziel-Punkt-Layer Einzelwertfelder aufweist.",
    "createOnlyOneMultipartFeatureWarning": "Sie können nur ein Feature kopieren oder ein Multipart-Feature erstellen, wenn der Ziel-Layer Einzelwertfelder aufweist.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} von ${totalFeatures} Features ausgewählt"
  },
  "addingFeatureError": "Fehler beim Hinzufügen von ausgewählten Features im Layer. Versuchen Sie es erneut.",
  "addingFeatureErrorCount": "Feature(s) \"${copyFeatureErrorCount}\" konnte(n) nicht kopiert werden. Möchten Sie den Vorgang für die fehlenden Features wiederholen?",
  "selectingFeatureError": "Fehler beim Auswählen von Features im Layer. Versuchen Sie es erneut.",
  "customSelectOptionLabel": "Zu kopierende Features auswählen",
  "copyFeaturesWithPolygon": "Mit Polygon kopieren",
  "copyFeaturesWithRect": "Mit Rechteck kopieren",
  "copyFeaturesWithLasso": "Mit Lasso kopieren",
  "noFeatureSelectedMessage": "Keine Features ausgewählt",
  "multipleFeatureSaveMessage": "Alle Features werden sofort gespeichert. Möchten Sie fortfahren?",
  "relativeDates": {
    "dateTypeLabel": "Datumstyp",
    "valueLabel": "Wert",
    "fixed": "Beschränkt",
    "current": "Aktuell",
    "past": "Vergangen",
    "future": "Zukunft",
    "popupTitle": "Wert auswählen",
    "hintForFixedDateType": "Hinweis: Der angegebene Wert für Datum und Uhrzeit wird als voreingestellter Standardwert verwendet.",
    "hintForCurrentDateType": "Hinweis: Der aktuelle Wert für Datum und Uhrzeit wird als voreingestellter Standardwert verwendet.",
    "hintForPastDateType": "Hinweis: Der angegebene Wert wird für den Standardwert der Voreinstellung vom aktuellen Wert für Datum und Uhrzeit subtrahiert.",
    "hintForFutureDateType": "Hinweis: Der angegebene Wert wird für den Standardwert der Voreinstellung zum aktuellen Wert für Datum und Uhrzeit addiert.",
    "noDateDefinedTooltip": "Kein Datum definiert",
    "relativeDateWarning": "Es muss ein Wert für Datum oder Uhrzeit angegeben werden, damit der voreingestellte Standardwert gespeichert werden kann.",
    "customLabel": "Benutzerdefiniert",
    "layerLabel": "Layer",
    "domainFieldHintLabel": "Der ausgewählte Wert ist eine Domäne mit codierten Werten. Der Wert \"${domainValue}\" wird verwendet."
  },
  "valuePicker": {
    "popupTitle": "Wert auswählen",
    "popupHint": "Das aktuelle Feature schneidet mehrere Features. Wählen Sie einen Wert für das jeweilige Feld aus.",
    "buttonTooltip": "Wert aus mehreren schneidenden Features auswählen"
  },
  "uniqueValueErrorMessage": "Der Wert in \"${fieldName}\" ist bereits vorhanden. Geben Sie einen neuen Wert ein.",
  "requiredFields": {
    "displayMsg": "Erforderliche Felder dürfen nicht leer sein. Geben Sie unten Werte für gemeinsame Felder ein.",
    "popupTittle": "Erforderliche Felder",
    "foundNullRecordCount": "${fieldName} (gefunden in ${count} Datensätzen)"
  },
  "fieldsMapping": {
    "popupTittle": "Feldabgleich anwenden",
    "fieldsMatchingCheckboxLabel": "Werte aus kopierten Features setzen die Standardwerte in Zielfeldern außer Kraft",
    "resetLabel": "Zurücksetzen",
    "clearLabel": "Löschen",
    "fieldsInTargetLayerLabel": "Ziel",
    "fieldsInSourceLayerLabel": "Quelle",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} Felder stimmen überein)",
    "selectSourceFieldLabel": "- Auswählen -",
    "selectFieldAriaLabel": "Quellfeld für Zielfeld ${targetField} auswählen",
    "informativeText": "Überprüfen Sie die Felder aus der Quelle, die mit dem Ziel übereinstimmen, und passen Sie sie bei Bedarf an.",
    "dynamicValueText": "Ein dynamischer Wert ist festgelegt.",
    "noFieldsToMatchLabel": "Keine abzugleichenden Felder"
  },
  "cantLocateUserLocation": "Ihre Position konnte nicht ermittelt werden.",
  "tryAgainButtonLabel": "Erneut versuchen",
  "copyFeatureFailedPopupTitle": "Hoppla!"
});