define({
  "_widgetLabel": "Phân tích Mối đe dọa",
  "threatAnalysisMainPageTitle": "Dựa trên Hướng dẫn Chống khủng bố JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Vị trí đầu vào",
  "interactive": "Tương tác",
  "fromCoord": "Tọa độ cố định",
  "existingFeature": "Từ các đối tượng hiện tại",
  "threatAnalysisCoordInputLabel": "Vị trí Mối đe dọa",
  "enterCoords": "Nhập Tọa độ",
  "threatAddPointToolTip": "Thêm Vị trí Mối đe dọa",
  "threatDrawPointToolTip": "Bấm để thêm vị trí mối đe dọa",
  "threatType": "Loại Mối đe dọa",
  "threatPlaceholder": "Bắt đầu nhập để tìm kiếm mối đe dọa",
  "zoneTypeLabel": "Loại Khu vực",
  "feetLabel": "Feet",
  "metersLabel": "Mét",
  "unitsLabel": "Đơn vị",
  "threatGraphicLayer": "Đồ thị-Mối đe dọa",
  "style": "Kiểu",
  "settingsTitle": "Thiết lập",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  },
  "resultsTitle": "Kết quả",
  "publishTABtn": "Xuất bản",
  "layerName": "Tên Lớp đã Xuất bản",
  "invalidLayerName": "Tên lớp chỉ được chứa các ký tự chữ số và dấu gạch dưới",
  "missingLayerNameMessage": "Bạn phải nhập tên lớp hợp lệ trước khi có thể xuất bản",
  "publishingFailedLayerExists": "Xuất bản không thành công: Bạn đã có dịch vụ đối tượng có tên {0}. Vui lòng chọn tên lớp khác.",
  "checkService": "Kiểm tra Dịch vụ: {0}.",
  "createService": "Tạo Dịch vụ: {0}",
  "unableToCreate": "Không thể tạo: {0}",
  "addToDefinition": "Thêm vào định nghĩa: {0}",
  "successfullyPublished": "Đã xuất bản lớp web thành công",
  "successfullyAppended": "Đã thêm các đối tượng mới vào lớp web thành công",
  "manageWebLayerText": "Quản lý lớp web",
  "userRole": "Không thể tạo dịch vụ do người dùng không có đủ quyền",
  "retrieveExistingLayerError": "Không thể truy xuất {0}. Vui lòng xuất bản bằng tên lớp khác",
  "publishToNewLayer": "Xuất bản kết quả đến một lớp đối tượng mới",
  "layerNameExists": "Tên lớp đã tồn tại. Vui lòng sử dụng tên lớp khác.",
  "pipeBombLabel": "Bom ống",
  "suicideBombLabel": "Bom tự sát",
  "briefcaseLabel": "Cặp tài liệu",
  "carLabel": "Ô tô",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Xe tải giao hàng nhỏ",
  "containerWaterTruckLabel": "Container/Xe tưới nước",
  "semiTrailerLabel": "Xe bán tải",
  "transparencyLabel": "Độ trong suốt",
  "outline": "Viền",
  "fill": "Tô đầy (Màu chỉ áp dụng khi kiểu được thiết lập thành dạng khối)",
  "createBtn": "Tạo Vùng",
  "clearBtn": "Xóa",
  "invalidNumberMessage": "Giá trị đã nhập không hợp lệ",
  "invalidRangeMessage": "Giá trị phải lớn hơn 0",
  "parseCoordinatesError": "Không thể phân tích tọa độ. Vui lòng kiểm tra thông tin đầu vào.",
  "selectDrawModeLabel": "Chọn Chế độ Vẽ",
  "selectFeatureLabel": "Chọn Đối tượng từ Lớp này",
  "smallLPGTank": "Bồn LPG nhỏ",
  "largeLPGTank": "Bồn LPG lớn",
  "commercialResidentialLPGTank": "Bồn LPG thương mại/sinh hoạt",
  "smallLPGTruck": "Xe tải LPG nhỏ",
  "semiTankerLPG": "Xe bán tải LPG",
  "zoneDescriptionColLabel": "Thông tin mô tả vùng",
  "distanceColLabel": "Khoảng cách",
  "zoneDescColLabel": "Thông tin mô tả vùng",
  "descriptionLabel": "Thông tin mô tả",
  "editThreatZonePopupLabel": "Chỉnh sửa ký hiệu cho vùng có mối đe dọa",
  "symbologyColLabel": "Diễn đạt bằng ký hiệu",
  "actions": "Các hành động",
  "threatTypeSelectLabel": "Chọn loại mối đe dọa:",
  "distanceLabel": "Khoảng cách (${unitAbbr})",
  "layerCountHint": "Gợi ý: Một lớp web có ${layerCount} lớp đối tượng sẽ được xuất bản.",
  "selectLabel": "Chọn",
  "mandatoryLabel": "Khoảng cách Sơ tán Bắt buộc",
  "safeLabel": "Khoảng cách Sơ tán An toàn",
  "fireBallDiameterLable": "Đường kính Cầu lửa",
  "lpgSafeDistanceLable": "Khoảng cách An toàn"
});