define({
  "taskUrl": "Näkymäaluepalvelun URL-osoite",
  "portalURL": "Määritä ArcGIS Online -organisaatiosi tai Portal for ArcGIS -ohjelman URL-osoite",
  "portalURLError": "ArcGIS Online -organisaatiosi tai Portal for ArcGIS -ohjelman määritetty URL-osoite ei kelpaa.",
  "privilegeError": "käyttäjäroolisi ei voi suorittaa analyysia. Analyysin suoritus edellyttää, että organisaatiosi pääkäyttäjä myöntää sinulle tietyt <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">käyttöoikeudet</a>.",
  "noServiceError": "Korkeustason analyysipalvelu ei ole käytettävissä. Tarkista ArcGIS Online -organisaatiosi tai Portal for ArcGIS -kokoonpanoasetuksesi.",
  "maximumRangeMessage": "Tarkkailualueen enimmäisarvon on oltava suurempi kuin tarkkailualueen vähimmäisarvo eikä se saa olla suurempi kuin ${limit} ${units}.",
  "serviceURLPlaceholder": "Syötä näkymäalueen geoprosessointitehtävän URL-osoite",
  "setTask": "Aseta",
  "setTaskTitle": "Määritä näkymäalueen geoprosessointitehtävä",
  "serviceURLError": "Geoprosessointitehtävä, jota yrität määrittää tällä pienoisohjelmalla, ei kelpaa. Valitse kelvollinen näkymäalueen geoprosessointitehtävän URL-osoite",
  "defaultMilsForAnglesLabel": "Määritä kulma-asetukseksi mailit oletusarvoisesti",
  "defaultObserverHeightLabel": "Tarkkailupisteen korkeuden oletusyksikkö",
  "defaultObservableDistanceLabel": "Tarkkailtavissa olevan etäisyyden oletusyksikkö",
  "defaultObserveHeightLabel": "Tarkkailijan korkeuden oletusarvo",
  "defaultMinimumObservableDistanceLabel": "Tarkkailtavissa olevan vähimmäisetäisyyden oletusarvo",
  "defaultMaximumObservableDistanceLabel": "Tarkkailtavissa olevan enimmäisetäisyyden oletusarvo",
  "units": {
    "miles": "Mailia",
    "kilometers": "Kilometriä",
    "feet": "Jalkaa",
    "meters": "Metriä",
    "yards": "Jaardia",
    "nauticalMiles": "Meripeninkulmaa"
  },
  "helpIconTooltip": "Toiminnallisten karttatasojen luettelo täytetään nykyisen web-karttan karttatasoilla, jotka ovat tyypiltään aluekohdegeometrioita.",
  "selectOperationalLayerLabel": "Valitse toiminnallinen karttataso tuloksia varten",
  "lineOfSightTabTitle": "Näkemälinja",
  "symbologyTabTitle": "Symbolit",
  "transparency": "Läpinäkyvyys",
  "outline": "Ääriviiva",
  "fill": "Täyttö (väriä käytetään vain, kun tyyliksi on määritetty yhtenäinen)",
  "style": "Tyyli",
  "selectOpLayerLabel": "Valitse toiminnallinen karttataso tuloksia varten",
  "selectDefaultMeasurementLabel": "Valitse oletusmittayksikkö",
  "visibleSectionLabel": "Näkyvä osio",
  "nonVisibleSectionLabel": "Ei-näkyvä osio",
  "visibleSectionButtonLabel": "Määritä näkyvän osion asetukset",
  "nonVisibleSectionButtonLabel": "Määritä ei-näkyvän osion asetukset",
  "colorPicker": "Värinvalitsin",
  "lineStyles": {
    "esriSLSDash": "Viiva",
    "esriSLSDashDot": "Viiva-piste",
    "esriSLSDashDotDot": "Viiva-piste-piste",
    "esriSLSDot": "Piste",
    "esriSLSLongDash": "Pitkä viiva",
    "esriSLSLongDashDot": "Pitkä viiva-piste",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lyhyt viiva",
    "esriSLSShortDashDot": "Lyhyt viiva-piste",
    "esriSLSShortDashDotDot": "Lyhyt viiva-piste-piste",
    "esriSLSShortDot": "Lyhyt piste",
    "esriSLSSolid": "Yhtenäinen"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Taaksepäin",
    "esriSFSCross": "Risti",
    "esriSFSDiagonalCross": "Lävistäjän suunnassa",
    "esriSFSForwardDiagonal": "Eteenpäin",
    "esriSFSHorizontal": "Vaaka",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Yhtenäinen",
    "esriSFSVertical": "Pysty"
  }
});