define({
  "_widgetLabel": "Datu apkopošana",
  "startPage": {
    "defaultStartPageInstructions": "Šo logrīku var izmantot, lai apstrādātu un iesniegtu datus no faila atlasītajā kartes slānī.<br/> <br/> Vērtībām failā jābūt atdalītām ar komatu, tabulatoru, semikolu vai vertikālu joslu.",
    "dragDrop": "Vilkt un nomest",
    "browse": "Pārlūkot failu",
    "or": "'VAI'",
    "userPrivilege": "Jūsu kontam nav piešķirta atļauja izveidot vai modificēt datus.",
    "userCredits": "${widgetName} ir nepieciešami servisa kredīti, lai izmantotu vietrādi ${locator}.",
    "contactAdmin": "Sazinieties ar organizācijas administratoru, lai pieprasītu papildu servisa kredītus.",
    "contactAdminEdit": "Sazinieties ar organizācijas administratoru, lai pieprasītu rediģēšanas tiesības.",
    "canUseLocator": "Vietrādis ${locator} tiks izmantots elementu atrašanai.",
    "notEnoughCredits": "Nepietiek servisa kredītu.",
    "locationAndField": "Novietojuma un darba informācija",
    "locationAndFieldHint": "Izvēlieties vērtības no faila, kas jāizmanto, lai atjauninātu  mērķa slāņi.",
    "cannotUseLocator": "Nevar izmantot ${widgetName}",
    "noAnonymousEdit": "${layerName} slānis neatbalsta anonīmu rediģēšanu.",
    "pleaseLogin": "Pierakstieties ${org} organizācijā vai sazinieties ar organizācijas administratoru, lai pieprasītu iespējot anonīmas rediģēšanas iespēju.",
    "invalidEdit": "Nederīga atļauja",
    "unableToAccess": "Nevar piekļūt ${layerName}",
    "appropriateCredentials": "Pārbaudiet, vai esiet pierakstījies, izmantojot attiecīgos datus.",
    "shared": "Sazinieties ar organizācijas administratoru, lai pieprasītu piekļuvi ${layerName} slānim.",
    "targetLayerLabel": "Mērķa slānis",
    "homeButtonLabel": "Mājas",
    "mappingErrorMsg": "Lauku definēšanai noklikšķiniet uz blakus esošās bultas"
  },
  "mapping": {
    "schemaMapping": "Lauka informācija",
    "schemaMappingHint": "Izvēlieties tos faila laukus, kas korelē ar slāņa laukiem.",
    "locationMapping": "Novietojuma informācija",
    "locationMappingHint": "Izvēlieties no faila gaidāmo adreses vai koordinātu informācijas veidu."
  },
  "locationMapping": {
    "locationMappingPageHint": "Izvēlēties izvietojuma veidu",
    "useAddress": "Atrast, izmantojot adresi",
    "useAddressHint": "Dati ietver adreses informāciju",
    "useCoordinates": "Atrast, izmantojot koordinātas",
    "useCoordinatesHint": "Dati ietver X/Y koordinātu vērtības"
  },
  "address": {
    "addressPageHint": "Izvēlieties adreses tipu",
    "singleField": "Viens lauks",
    "singleFieldHint": "Izvēlieties lauku, kas ietver adreses informāciju",
    "multiField": "Vairāki lauki",
    "multiFieldHint": "Izvēlieties laukus, kas ietver adreses informāciju"
  },
  "coordinates": {
    "coordinatesPageHint": "Izvēlieties laukus, kas ietver koordinātu datus"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Izvēlieties avota lauku, kas veic kartēšanu mērķa laukā",
    "sourceField": "Atbilstošs avota lauks",
    "targetField": "Mērķa lauks"
  },
  "buttons": {
    "addToMap": "Pievienot kartei",
    "submit": "Iesniegt",
    "download": "Lejupielāde"
  },
  "review": {
    "matched": "Atrasts",
    "reviewMatched": "Atrasti novietojumi",
    "reviewMatchedHint": "Pārskatiet atrastos novietojumus.",
    "unMatched": "nav atrasts",
    "reviewUnMatched": "Novietojumi nav atrasti",
    "reviewUnMatchedHint": "Pārskatiet novietojumus, kas netika atrasti. Vienumi, kas nav laboti, netiks iesniegti.",
    "duplicate": "Dublēt",
    "reviewDuplicate": "Dublēt novietojumus",
    "reviewDuplicateHint": "Pārskatiet novietojumus, kas jau tika atrasti slānī. Vienumi, kuriem nav adreses, netiks iesniegti.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Izmantot:",
    "fromLayer": "Mērķa informācija",
    "target": "Mērķis",
    "source": "Avots",
    "fromFile": "Avota informācija",
    "locationControlHint": "Pārskatiet adreses informāciju",
    "duplicateAction": "Izvēlieties darbību",
    "item": "Ierakstīt:",
    "locateFeature": "Atrast elementu",
    "removeFeature": "Noņemt elementu",
    "featureLocated": "Atrasts novietojums",
    "valuesDoNotMatch": "Neatbilst esošai vērtībai",
    "sync": "Sinhronizēt adreses informācija ar darba vietas informāciju",
    "noFeaturesSaved": "Neviens elements netika veiksmīgi saglabāts",
    "someFeaturesSaved": "Tika veiksmīgi saglabāti ${num} elementi.",
    "someFeaturesNotSaved": "Neizdevās saglabāt ${num} elementus",
    "feature": "Pārskatīt elementu informāciju",
    "locationInfo": "Pārskatīt novietojuma informāciju",
    "selectValue": "Atlasīt vērtību",
    "reviewData": "Pārskatīt datus",
    "reviewDataHint": "Pārskatiet savus datus pirms to iesniegšanās slānī.",
    "reviewFeatureHint": "Pārskatiet vai rediģējiet elementu un novietojuma informāciju.",
    "duplicateModify": "Dublikāts, nepieciešamas izmaiņas",
    "duplicateSave": "Saglabāt kā jaunu elementu"
  },
  "warningsAndErrors": {
    "invalidCSV": "Izgūstot vienumus no CSV, radās kļūda. Pārbaudiet, vai ir atlasīts derīgs CSV fails.",
    "noLayersWarning": "Nav konfigurēts neviens derīgs mērķa slānis. Pārbaudiet konfigurāciju.",
    "loadWarning": "Šim logrīkam ir nepieciešams elementu servisa datu avots. Konfigurējiet logrīku, lai norādītu datu avotu.",
    "saveError": "Saglabājot elementus, radās kļūda.",
    "consumesCredits": "Šis rīks patērē servisa kredītus, ja tiek izmantots kopā ar ArcGIS Online servisu World Geocoding",
    "noValue": "Atlasīt lauku",
    "mappingTitle": "",
    "locationMappingComplete": "Novietojuma kartēšana ir pabeigta",
    "fieldMappingComplete": "Lauka kartēšana ir pabeigta",
    "settingsCleared": "Iestatījumi tiks notīrīti.",
    "proceed": "Vai vēlaties turpināt?",
    "itemMoveMatch": "Vienums tika atrasts un pārvietots uz atrasto vietu sarakstu",
    "itemMoveUnMatched": "Nevar atrast vienumu. Pārvietots uz neatrasto vietu sarakstu.",
    "itemWillBeLocated": "Vienums tiks noņemts no dublēto novietojumu saraksta.",
    "cannotLocate": "Nevar atrast vienumu. Pārbaudiet novietojuma informāciju.",
    "invalidMessage": "Nederīga vērtība.",
    "rangeMessage": "Vērtībai jābūt mazākai par ${num} rakstzīmēm.",
    "locatorError": "Vietrādis nav derīgs vai nav pieejams.",
    "notConfigured": "vietrādis nav konfigurēts pašreizējām meklēšanas vietu opcijām",
    "noMoreLocators": "nav konfigurēts neviens papildu vietrādis"
  },
  "featureToolbar": {
    "locate": "Izvietot",
    "save": "Saglabāt ierakstu",
    "cancel": "Atcelt rediģējumus",
    "cancelTitle": "Atcelt rediģējumus",
    "cancelMessage": "Vai atcelt pašreizējā ieraksta rediģējumus?"
  }
});