// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/widget-config/CustomWidgets.html":'\x3cdiv data-dojo-attach-event\x3d"onscroll:_onScroll"\x3e\r\n\t\x3cdiv data-dojo-attach-point\x3d"list" class\x3d"list widget-list" data-dojo-attach-event\x3d"onclick:_onClick"\x3e\x3c/div\x3e\r\n\t\x3cdiv data-dojo-type\x3d"jimu/dijit/LoadingIndicator" data-dojo-attach-point\x3d"loading" data-dojo-props\x3d\'hidden:true\'\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./CustomWidgets.html dojo/Evented dojo/query dojo/_base/lang dojo/_base/array dojo/_base/html jimu/utils jimu/portalUtils jimu/portalUrlUtils jimu/dijit/LoadingIndicator".split(" "),function(k,l,m,n,p,q,f,e,h,c,g,r,t){return k([l,m,n,q],{templateString:p,baseClass:"custom-widgets",query:null,nls:null,type:"AppBuilder Extension",portalUrl:null,hidden:!1,postMixInProperties:function(){this.nls=
window.jimuNls.itemSelector},postCreate:function(){this.inherited(arguments);this.portalUrl=t.getStandardPortalUrl(this.portalUrl);this.portal=r.getPortal(this.portalUrl);this.baseQ='type:"'+this.type+'" AND typekeywords:"Widget,'+window.appInfo.appType+'"';"HTML"===window.appInfo.appType.toUpperCase()&&(this.baseQ+=' -typekeywords:"HTML3D"');this.hidden&&this.hide()},filterLocally:function(a){f(".widget-node",this.domNode).forEach(e.hitch(this,function(b){a(b.item)?c.removeClass(b,"hidden"):c.addClass(b,
"hidden")}))},queryItems:function(a){a=a||{};this.loading.show();this.clear();e.mixin(this.query,a);this.query.start=1;this.query.q=a.q?this.baseQ+" AND "+a.q:this.baseQ;return this.portal.queryItems(this.query).then(e.hitch(this,function(b){if(this.domNode)return this.domNode&&this.loading.hide(),this.query.start=b.nextStart,this._createItemsNode(b)}),e.hitch(this,function(b){console.error(b);this.domNode&&this.loading.hide()}))},_createItemsNode:function(a){a=a.results;var b=this.type.toLowerCase();
a=h.filter(a,e.hitch(this,function(d){return(d.type&&d.type.toLowerCase()||"")===b}));h.forEach(a,e.hitch(this,function(d){this._createItemNode(d)}));return a},_createItemNode:function(a){var b=c.toDom('\x3cdiv class\x3d"widget-node"\x3e\x3cdiv class\x3d"box"\x3e\x3cimg class\x3d"icon"\x3e\x3ca target\x3d"_blank" class\x3d"detail-icon"\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d"box-selected"\x3e\x3c/div\x3e\x3cdiv class\x3d"label"\x3e\x3c/div\x3e\x3c/div\x3e');b.item=a;f("img",b)[0].src=g.widgetJson.getFolderUrlFromItem(a)+
"images/icon.png";var d=f(".label",b)[0];d.innerHTML=g.sanitizeHTML(a.title)||"";d.title=a.title||"";d=f(".detail-icon",b)[0];d.href=a.detailsPageUrl;d.title=this.nls.viewItemDetails||"View item details";c.place(b,this.list)},clear:function(){this.query={q:this.baseQ,sortField:"title",sortOrder:"asc",num:100,start:1};c.empty(this.list)},_onClick:function(a){a=a.target||a.srcElement;var b=null;if(b=c.hasClass(a,"widget-node")?a:g.getAncestorDom(a,function(d){return c.hasClass(d,"widget-node")},this.list))f(".official-section .jimu-state-selected",
this.widgetDomNode).removeClass("jimu-state-selected"),"addBtn"===this.fromNode.type?c.toggleClass(b,"jimu-state-selected"):(f(".jimu-state-selected",this.domNode).removeClass("jimu-state-selected"),c.addClass(b,"jimu-state-selected"))},_onScroll:function(){this._isScrollToBottom(this.domNode)},_isScrollToBottom:function(a){return g.isScrollToBottom(a)},getSelectedWidgetItems:function(){var a=f(".widget-node.jimu-state-selected",this.domNode).filter(e.hitch(this,function(b){return!c.hasClass(b,"hidden")}));
return h.map(a,e.hitch(this,function(b){return b.item}))},isVisible:function(){return!c.hasClass(this.domNode,"hidden")},show:function(){c.removeClass(this.domNode,"hidden")},hide:function(){c.addClass(this.domNode,"hidden")}})});