define({
  "taskUrl": "URL de Serviço de Viewshed",
  "portalURL": "Especificar o URL para a sua organização ArcGIS Online ou Portal for ArcGIS",
  "portalURLError": "O URL configurado para a sua organização ArcGIS Online ou Portal for ArcGIS não é válido.",
  "privilegeError": "O seu papel de utilizador não permite executar a análise. Para efetuar a análise, o administrador da sua organização tem de atribuir-lhe certos <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilégios</a>.",
  "noServiceError": "Serviço de análise de elevação não disponível Verifique a sua organização ArcGIS Online ou as configurações Portal for ArcGIS.",
  "serviceURLPlaceholder": "Por favor introduza o URL de tarefa de Geoprocessamento de Viewshed",
  "setTask": "Definir",
  "setTaskTitle": "Definir Tarefa de Geoprocessamento de Viewshed",
  "serviceURLError": "A tarefa de Geoprocessamento que está a tentar configurar com este widget não é válida. Por favor, selecione um URL de tarefa de Geoprocessamento de Viewshed válido",
  "defaultMilsForAnglesLabel": "Predefinir milhas para ângulos",
  "defaultObserverHeightLabel": "Unidade de altura do observador predefinida",
  "defaultObservableDistanceLabel": "Unidade de distância observável predefinida",
  "units": {
    "miles": "Milhas",
    "kilometers": "Quilómetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nauticalMiles": "Milhas náuticas"
  },
  "helpIconTooltip": "A lista de camadas operacionais é preenchida com camadas do mapa web atual do tipo de geometria de polígono.",
  "selectOperationalLayerLabel": "Selecionar uma nova camada operacional para os resultados",
  "lineOfSightTabTitle": "Linha de Visão",
  "symbologyTabTitle": "Simbologia",
  "transparency": "Transparência",
  "outline": "Contorno",
  "fill": "Preenchimento (Apenas é aplicada cor quando o estilo é definido como sólido)",
  "style": "Estilo",
  "selectOpLayerLabel": "Selecionar uma nova camada operacional para os resultados",
  "selectDefaultMeasurementLabel": "Selecionar a unidade de medida predefinida",
  "visibleSectionLabel": "Secção Visível",
  "nonVisibleSectionLabel": "Secção Não Visível",
  "visibleSectionButtonLabel": "Configurar Definições da secção visível",
  "nonVisibleSectionButtonLabel": "Configurar Definições da secção não visível",
  "colorPicker": "Selecionador de Cores",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo e Ponto",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Traço Curto e Ponto",
    "esriSLSShortDashDotDot": "Traço Curto, Ponto e Ponto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Ao Contrário",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para a frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  }
});