define({
  "transparencyLabel": "透明度",
  "outline": "轮廓",
  "fill": "填充(仅在将样式设置为单色时应用颜色)",
  "style": "样式",
  "selectOpLayerLabel": "选择结果的业务图层",
  "selectDefaultMeasurementLabel": "选择默认测量单位。",
  "helpIconTooltip": "使用当前 web 地图中面几何类型的图层来填充业务图层列表。",
  "lineStyles": {
    "esriSLSDash": "虚线",
    "esriSLSDashDot": "点划线",
    "esriSLSDashDotDot": "双点划线",
    "esriSLSDot": "点",
    "esriSLSLongDash": "长划线",
    "esriSLSLongDashDot": "长点划线",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "短虚线",
    "esriSLSShortDashDot": "短点划线",
    "esriSLSShortDashDotDot": "短双点划线",
    "esriSLSShortDot": "短点线",
    "esriSLSSolid": "实线"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向后",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "对角线",
    "esriSFSForwardDiagonal": "向前",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "Null",
    "esriSFSSolid": "实线",
    "esriSFSVertical": "竖直"
  },
  "threatTypeLabel": "威胁类型",
  "generalLabel": "常规",
  "addThreatTypesLabel": "添加威胁类型",
  "actions": "操作",
  "newThreatTypePopupLabel": "新威胁类型",
  "units": "单位",
  "chooseDefaultThreatLabel": "选择默认威胁类型",
  "defaultThreatTypePopUpLabel": "默认威胁类型",
  "editThreatLabel": "编辑威胁",
  "defaultThreatTypeIconTooltip": "默认威胁类型列表",
  "uniqueThreatTypeMsg": "请输入唯一威胁类型，具有此名称的威胁类型已经存在。",
  "requiredMsg": "此字段为必填字段",
  "unitMeasureLabel": "距离以 {0} 为单位",
  "chooseDefaultThreatTypeIconLabel": "从默认设置中选择",
  "pipeBombLabel": "管式炸弹",
  "suicideBombLabel": "自杀式炸弹",
  "briefcaseLabel": "公文包",
  "carLabel": "汽车",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "小型送货卡车",
  "containerWaterTruckLabel": "集装箱/水车",
  "semiTrailerLabel": "半挂车",
  "chemicalThreatLegendLabel": "化学威胁",
  "lpgThreatLegendLabel": "LPG 威胁",
  "smallLPGTank": "小型 LPG 罐",
  "largeLPGTank": "大型 LPG 罐",
  "commercialResidentialLPGTank": "商用/民用 LPG 罐",
  "smallLPGTruck": "小型 LPG 卡车",
  "semiTankerLPG": "LPG 罐半挂车",
  "threatDescriptionColLabel": "威胁描述",
  "addThreatZoneButtonLabel": "添加威胁区域",
  "zoneDescColLabel": "区域描述",
  "distanceLabel": "距离(${unitAbbr})",
  "threatTypeHelp": "<p>确保威胁类型满足以下条件：<br/><ul><li>此威胁类型不能为空且应是唯一的</li><li>威胁应至少具有一个有效区域</li><li>威胁的区域描述应是唯一的</li></ul><p/>",
  "descriptionLabel": "描述",
  "newThreatZonePopupLabel": "新威胁区域",
  "editThreatZonePopupLabel": "编辑威胁区域",
  "uniqueZoneDescriptionMsg": "请输入唯一的区域描述，具有此名称的区域描述已经存在。",
  "symbologyColLabel": "符号系统",
  "zoneDescriptionColLabel": "区域描述",
  "uniqueZoneRequiredMsg": "区域名称应是唯一的",
  "interactive": "交互式",
  "fromCoord": "固定坐标",
  "existingFeature": "从现有要素",
  "defaultInputLocationLabel": "默认输入位置",
  "defaultInputLayer": "默认输入图层",
  "defaultThreatType": "默认威胁类型",
  "selectLabel": "选择",
  "mandatoryLabel": "强制疏散距离",
  "safeLabel": "安全疏散距离",
  "lpgSafeDistanceLable": "安全距离",
  "fireBallDiameterLable": "火球直径"
});