define({
  "feedbackStyleLabel": "Gaya Umpan Balik Jarak dan Arah",
  "showTabLabel": "Tampilkan semua tab",
  "tabErrorMessage": "Pilih sedikitnya satu tab dalam grup \"Gaya Umpan Balik Jarak dan Arah\"",
  "lineLabel": "Garis",
  "circleLabel": "Lingkaran",
  "ellipseLabel": "Elips",
  "ringsLabel": "Cincin",
  "transparency": "Transparansi",
  "operationalLineLayerSelectLabel": "Pilih layer polyline operasional untuk hasil garis dan cincin",
  "operationalPolygonLayerSelectLabel": "Pilih layer poligon operasional untuk hasil lingkaran dan elips",
  "helpIconPolylineTooltip": "Daftar layer operasional dikumpulkan dengan layer dari peta web saat ini yang berjenis geometri polyline.",
  "helpIconPolygonTooltip": "Daftar layer operasional dikumpulkan dengan layer dari peta web saat ini yang berjenis geometri poligon.",
  "feedbackResultsLayerLabel": "Layer Hasil Umpan Balik Jarak dan Arah",
  "editSymbologyHint": "Petunjuk: Klik ikon pratinjau untuk mengedit simbologi",
  "feedbackTextColorLabel": "Warna teks label umpan balik",
  "feedbackTextSizeLabel": "Ukuran teks label umpan balik",
  "previewLabel": "Pratinjau",
  "lineSymbologyPopupTittle": "Simbologi garis",
  "circleSymbologyPopupTittle": "Simbologi lingkaran",
  "ellipseSymbologyPopupTittle": "Simbologi elips",
  "ringSymbologyPopupTittle": "Simbologi cincin"
});