define({
  "taskUrl": "عنوان URL لخدمة مجال الرؤية",
  "portalURL": "حدد عنوان URL لمؤسسة ArcGIS Online أو Portal for ArcGIS",
  "portalURLError": "عنوان URL المكون لمؤسسة ArcGIS Online الخاصة بك أو Portal for ArcGIS غير صالح.",
  "privilegeError": "دور المستخدم الخاص بك لا يمكنه إجراء تحليل. لتنفيذ التحليل، يتعين على مسئول المؤسسة منحك <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">امتيازات</a> محددة.",
  "noServiceError": "خدمة تحليل الارتفاع غير متوفرة. يرجى التحقق من تكوينات مؤسسة ArcGIS Online أو Portal for ArcGIS.",
  "maximumRangeMessage": "يجب أن يكون الحد الأقصى للنطاق الملحوظ أكبر من الحد الأدنى للنطاق الملحوظ ولا يمكن أن يكون أكثر من ${limit} ${units}.",
  "serviceURLPlaceholder": "يرجى إدخال عنوان URL لمهمة المعالجة الجغرافية لمجال الرؤية",
  "setTask": "تعيين",
  "setTaskTitle": "تعيين مهمة معالجة جغرافية لمجال الرؤية",
  "serviceURLError": "مهمة المعالجة الجغرافية التي تحاول تكوينها مع عنصر واجهة الاستخدام غير صحيح. الرجاء تحديد عنوان URL صحيح لمهمة المعالجة الجغرافية لطريقة العرض.",
  "defaultMilsForAnglesLabel": "تعيين أميال للزوايا كإعداد افتراضي",
  "defaultObserverHeightLabel": "وحدة ارتفاع المراقب الافتراضية",
  "defaultObservableDistanceLabel": "وحدة المسافة الافتراضية التي يمكن مراقبتها",
  "defaultObserveHeightLabel": "ارتفاع المراقب الافتراضية",
  "defaultMinimumObservableDistanceLabel": "الحد الأدنى الافتراضي للمسافة التي يمكن ملاحظتها",
  "defaultMaximumObservableDistanceLabel": "الحد الأقصى الافتراضي للمسافة التي يمكن ملاحظتها",
  "units": {
    "miles": "أميال",
    "kilometers": "كيلومتر",
    "feet": "قدم",
    "meters": "أمتار",
    "yards": "ياردة",
    "nauticalMiles": "أميال بحرية"
  },
  "helpIconTooltip": "يتم ملء الطبقة التشغيلية بالطبقات من خريطة الويب الحالية التي تكون من نوع شكل المضلع الهندسي.",
  "selectOperationalLayerLabel": "تحديد طبقة تشغيلية للنتائج",
  "lineOfSightTabTitle": "خط الرؤية",
  "symbologyTabTitle": "الترميز",
  "transparency": "الشفافية",
  "outline": "الحدود",
  "fill": "تعبئة (لا ينطبق اللون إلا عند تعيين النمط إلى مُصمَت)",
  "style": "نمط",
  "selectOpLayerLabel": "تحديد طبقة تشغيلية للنتائج",
  "selectDefaultMeasurementLabel": "تحديد وحدة قياس افتراضية",
  "visibleSectionLabel": "القسم المرئي",
  "nonVisibleSectionLabel": "القسم غير المرئي",
  "visibleSectionButtonLabel": "تكوين إعدادات القسم المرئي",
  "nonVisibleSectionButtonLabel": "تكوين إعدادات القسم غير المرئي",
  "colorPicker": "منتقى الألوان",
  "lineStyles": {
    "esriSLSDash": "شَرطَة",
    "esriSLSDashDot": "شَرطَة ونقطة",
    "esriSLSDashDotDot": "شرطة ونقطتان",
    "esriSLSDot": "نقطة",
    "esriSLSLongDash": "شرطة طويلة",
    "esriSLSLongDashDot": "شرطة ونقطة طويلين",
    "esriSLSNull": "خالِ",
    "esriSLSShortDash": "شَرطَة قصيرة",
    "esriSLSShortDashDot": "نقطة شرطة قصيرة",
    "esriSLSShortDashDotDot": "نقطة نقطة شرطة قصيرة",
    "esriSLSShortDot": "منطقة صغيرة",
    "esriSLSSolid": "متصل"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "للخلف",
    "esriSFSCross": "شكل متصالب",
    "esriSFSDiagonalCross": "قطري",
    "esriSFSForwardDiagonal": "للأمام",
    "esriSFSHorizontal": "أفقياً",
    "esriSFSNull": "خالِ",
    "esriSFSSolid": "متصل",
    "esriSFSVertical": "رأسي"
  }
});