define({
  "_widgetLabel": "Εργαλείο μαζικής επεξεργασίας περιγραφικών στοιχείων",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Όνομα επιπέδου",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Δεν έχουν καθοριστεί θεματικά επίπεδα με δυνατότητα επεξεργασίας",
  "editorPopupTitle": "Εργαλείο μαζικής επεξεργασίας περιγραφικών στοιχείων",
  "editorPopupSaveBtn": "Αποθήκευση",
  "editorPopupMultipleValues": "",
  "clear": "Απαλοιφή",
  "featuresUpdated": "Ενημερώθηκαν ${0} / ${1} στοιχεία",
  "featuresSelected": "Επιλέχθηκαν ${0} στοιχεία",
  "featuresSkipped": "Παρακάμφθηκαν",
  "featuresNoPermision": "${0} επιλεγμένο (α) στοιχείο (α), αλλά δεν επιτρέπεται η επεξεργασία.",
  "search": "Αναζήτηση",
  "queryInput": "Εισαγάγετε τιμή για δημιουργία ερωτήματος",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Ορίστε σωστά το φίλτρο.",
  "filterPopup": "Φιλτράρισμα θεματικού επιπέδου",
  "filterAppend": "Αν ήδη υπάρχει φίλτρο στον web χάρτη για αυτό το θεματικό επίπεδο",
  "filterAppendOR": "Προσάρτηση κάθε έκφρασης στο υπάρχον φίλτρο στον χάρτη",
  "filterAppendAND": "Προσάρτηση όλων των εκφράσεων στο υπάρχον φίλτρο στον χάρτη",
  "cancel": "Ακύρωση",
  "noValue": "Καμία τιμή",
  "emptyString": "Κενή συμβολοσειρά",
  "existingValue": "Διατήρηση υπάρχουσας τιμής",
  "newDate": "Νέα ημερομηνία",
  "valueChooser": "Επιλέξτε/πληκτρολογήστε μια τιμή",
  "ok": "OK",
  "drawBox": {
    "point": "Σημείο",
    "line": "Γραμμή",
    "polyline": "Πολλαπλές γραμμές",
    "freehandPolyline": "Γραμμή ελεύθερης σχεδίασης",
    "extent": "Έκταση",
    "polygon": "Πολύγωνο",
    "freehandPolygon": "Πολύγωνο ελεύθερης σχεδίασης",
    "clear": "Απαλοιφή",
    "addPointToolTip": "Κάντε κλικ, για να επιλέξετε σε αυτή την περιοχή",
    "addShapeToolTip": "Σχεδιάστε ένα σχήμα για να επιλέξετε στοιχεία",
    "freehandToolTip": "Πατήστε παρατεταμένα για να σχεδιάσετε ένα σχήμα για να επιλέξετε στοιχεία",
    "startToolTip": "Σχεδιάστε ένα σχήμα για να επιλέξετε στοιχεία"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Το στοιχείο από το ${0} επέστρεψε μη έγκυρο ID",
    "noSelectedLayers": "Δεν έχουν επιλεγεί θεματικά επίπεδα με εγγραφές για ενημέρωση",
    "inputValueError": "Μη έγκυρη τιμή στη φόρμα",
    "saveError": "Δεν είναι δυνατή η αποθήκευση ${0} στοιχείων",
    "requiredValue": "Απαιτείται τιμή"
  }
});