define({
  "_widgetLabel": "Pametni urejevalnik",
  "_featureAction_SmartEditor": "Pametni urejevalnik",
  "noEditPrivileges": "Vaš račun nima dovoljenja za ustvarjanje ali spreminjanje podatkov.",
  "loginPopupTitle": "Prijava",
  "loginPopupMessage": "${widgetName} zahteva dovoljenje in kredite za ogled in shranjevanje informacij naslova. Se želite vpisati in uporabiti to možnost?",
  "noCreditsOrPrivilegeWarningMessage": "Vaš račun nima dovoljenj in kreditov za ogled in shranjevanje informacij naslova s ${widgetName}. Obrnite se na administratorja v vaši organizaciji in zahtevajte dovoljenja ter kredite.",
  "unableToUseLocator": "Lokator ni dostopen. Dejanja atributov naslova ne bodo izvedena.",
  "locatorDisabledWaning": "Lokator ni omogočen. Obrnite se na administratorja v vaši organizaciji in zahtevajte to možnost.",
  "noFeatureInAIWarning": "Geoobjekti niso izbrani. Izberite geoobjekt, da izvedete urejanje, ali kliknite preklic, da se vrnete na glavni zaslon.",
  "noEditableLayerWarning": "Vaš račun nima dovoljenja za ustvarjanje ali spreminjanje podatkov oz. ta spletna karta ne vsebuje slojev, ki jih je mogoče urejati.",
  "noVisibleCreateLayerWarning": "Sloji niso vidni s trenutno stopnjo povečave. Povečajte ali pomanjšajte, da ustvarite/spremenite geoobjekte.",
  "noVisibleUpdateLayerWarning": "Sloji niso vidni s trenutno stopnjo povečave. Povečajte ali pomanjšajte, da spremenite geoobjekte.",
  "checkLayerVisibilityInWebMapWarning": "Prepričajte se, da so sloji vidni na karti, da ustvarite ali spremenite geoobjekte.",
  "showSelectionInAITitle": "Izbrani geoobjekti",
  "showSelectionInAIMsg": "Želite naložiti trenutno izbiro v ${widgetName}?",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Neaktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL, ",
  "snapStr": " da omogočite privlačnost",
  "noAvailableTempaltes": "Predloge niso na voljo",
  "editorCache": " – predpomnilnik urejevalnika",
  "presetFieldAlias": "Polje",
  "presetValue": "Prednastavljena vrednost",
  "usePresetValues": " Uporabi prednastavljeno vrednost (samo novi geoobjekti)",
  "editGeometry": " Uredi geometrijo",
  "savePromptTitle": "Shrani geoobjekt",
  "savePrompt": "Želite shraniti trenutni geoobjekt?",
  "deletePromptTitle": "Izbriši geoobjekt",
  "deleteAttachment": "Izbriši prilogo",
  "deletePrompt": "Ste prepričani, da želite izbrisati izbrani geoobjekt?",
  "attachmentLoadingError": "Napaka pri nalaganju prilog",
  "attachmentSaveDeleteWarning": "Opozorilo: Spremembe v prilogah so shranjene samodejno",
  "autoSaveEdits": "Samodejno shrani nove geoobjekte",
  "addNewFeature": "Ustvari nov geoobjekt",
  "featureCreationFailedMsg": "Ni bilo mogoče ustvariti novega zapisa/geoobjekta",
  "relatedItemTitle": "Relacijska tabela/sloj",
  "relatedFeatureCount": "${layerTitle} z geoobjekti ${featureCount}",
  "createNewFeatureLabel": "Ustvari nov geoobjekt za ${layerTitle}",
  "invalidRelationShipMsg": "Zagotovite, da ima polje primarnega ključa: »${parentKeyField}« veljavno vrednost",
  "pendingFeatureSaveMsg": "Shranite urejanja geoobjektov pred ustvarjanjem relacijskega geoobjekta.",
  "attachmentsRequiredMsg": "(*) Zahtevane so priloge.",
  "coordinatePopupTitle": "Premakni geoobjekt na lokacijo XY",
  "coordinatesSelectTitle": "Koordinatni sistem:",
  "mapSpecialReferenceDropdownOption": "Koordinatni sistem karte",
  "latLongDropdownOption": "Geografska širina/geografska dolžina",
  "mgrsDropdownOption": "Vojaški mrežni referenčni sistem (MGRS)",
  "mgrsTextBoxLabel": "Koordinata:",
  "xAttributeTextBoxLabel": "Koordinata X:",
  "yAttributeTextBoxLabel": "Koordinata Y:",
  "latitudeTextBoxLabel": "Geografska širina:",
  "longitudeTextBoxLabel": "Geografska dolžina:",
  "presetGroupFieldsLabel": "'${groupName}' bo uporabljeno za naslednja polja slojev:",
  "presetGroupNoFieldsLabel": "'${groupName}' nima nobenih povezanih polj",
  "groupInfoLabel": "Informacije skupine za '${groupName}'",
  "editGroupInfoIcon": "Uredi vrednost skupine za ${groupName}",
  "filterEditor": {
    "all": "Vsi",
    "noAvailableTempaltes": "Predloge niso na voljo",
    "searchTemplates": "Iskanje predlog",
    "filterLayerLabel": "Filtriraj sloje"
  },
  "invalidConfiguration": "Pripomoček morda ni konfiguriran ali pa slojev v konfiguraciji ni več na zemljevidu. Odprite aplikacijo v načinu izdelave in ponovno konfigurirajte pripomoček.",
  "geometryServiceURLNotFoundMSG": "URL geometrijske storitve ni mogoče pridobiti",
  "clearSelection": "Zapri",
  "refreshAttributes": "Posodobi dinamične atribute geoobjekta",
  "automaticAttributeUpdatesOn": "Samodejno posodabljajo atribute geoobjektov: VKLOP",
  "automaticAttributeUpdatesOff": "Samodejno posodobi atribute geoobjektov: IZKLOP",
  "moveSelectedFeatureToGPS": "Premakni izbrani geoobjekt na trenutno lokacijo GPS",
  "moveSelectedFeatureToXY": "Premakni izbrani geoobjekt na lokacijo XY",
  "mapNavigationLocked": "Navigacija po karti: zaklenjeno",
  "mapNavigationUnLocked": "Navigacija po karti: odklenjeno",
  "copyFeatures": {
    "title": "Kopiraj geoobjekte",
    "createFeatures": "Ustvari geoobjekte",
    "createSingleFeature": "Ustvari 1 večdelni geoobjekt",
    "createOneSingleFeature": "Ustvari geoobjekt",
    "noFeaturesSelectedMessage": "Ni izbranih geoobjektov",
    "selectFeatureToCopyMessage": "Izberite geoobjekte za kopiranje",
    "multipleFeatureSaveWarning": "Opomba: ustvarjanje več geoobjektov z uporabo funkcije kopiranja bo takoj shranilo vse nove geoobjekte",
    "copyFeatureUpdateGeometryError": "Geometrije izbranih geoobjektov ni mogoče posodobiti",
    "canNotSaveMultipleFeatureWarning": "Opomba: Kopiranje več geoobjektov z uporabo iste vrednosti za polja enolične vrednosti ni mogoče; uporabite samo en geoobjekt",
    "createOnlyOneMultipartFeatureWarning": "Opomba: Ustvarite lahko samo en večdelni geoobjekt"
  },
  "addingFeatureError": "Pri dodajanju izbranih geoobjektov v sloj se je pojavila napaka. Poskusite znova.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' geoobjektov ni bilo mogoče kopirati. Želite znova poskusiti za manjkajoče geoobjekte?",
  "selectingFeatureError": "Pri izbiranju geoobjektov v sloj se je pojavila napaka. Poskusite znova.",
  "customSelectOptionLabel": "Izberite geoobjekte za kopiranje.",
  "noFeatureSelectedMessage": "Ni izbranih geoobjektov",
  "multipleFeatureSaveMessage": "Vsi geoobjekti bodo takoj shranjeni. Želite nadaljevati?",
  "relativeDates": {
    "dateTypeLabel": "Tip podatkov",
    "valueLabel": "Vrednost",
    "fixed": "Fiksno",
    "current": "Trenutno",
    "past": "Pretekli",
    "future": "Prihodnost",
    "popupTitle": "Izberi vrednost",
    "hintForFixedDateType": "Namig: določena datum in čas bosta uporabljena kot prednastavljena privzeta vrednost.",
    "hintForCurrentDateType": "Namig: trenutni datum in čas bosta uporabljena kot prednastavljena privzeta vrednost.",
    "hintForPastDateType": "Namig: določena vrednost bo odšteta od trenutnega datuma in časa za privzeto vrednost prednastavitve.",
    "hintForFutureDateType": "Namig: določena vrednost bo dodana trenutnemu datumu in času za privzeto vrednost prednastavitve.",
    "noDateDefinedTooltip": "Noben datum ni določen",
    "relativeDateWarning": "Vrednost za datum ali čas mora biti določena, da jo lahko shranite kot privzeto prednastavljeno vrednost.",
    "customLabel": "Po meri",
    "layerLabel": "Sloj",
    "domainFieldHintLabel": "Izbrana vrednost je domena kodirane vrednosti. Vrednost: \"${domainValue}\" bo uporabljena"
  },
  "valuePicker": {
    "popupTitle": "Izberi vrednost",
    "popupHint": "Trenutni geoobjekt seka več geoobjektov, izberite vrednost za ustrezno polje",
    "buttonTooltip": "Izberite vrednost iz več presečnih geoobjektov"
  },
  "uniqueValueErrorMessage": "Vrednost v \"${fieldName}\" že obstaja; navedite drugo vrednost.",
  "requiredFields": {
    "displayMsg": "Obvezna polja ne smejo biti prazna. Navedene vrednosti za skupna polja spodaj.",
    "popupTittle": "Obvezna polja",
    "foundNullRecordCount": "${fieldName} (najdeno v ${count} zapisih)"
  },
  "cantLocateUserLocation": "Vaše lokacije ni bilo mogoče določiti",
  "tryAgainButtonLabel": "Poskusite znova",
  "copyFeatureFailedPopupTitle": "Ups!"
});