define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Acesse infográficos e relatórios que resumem os principais indicadores e dados de qualquer área.</div><br><div>Selecione um ponto ou polígono no mapa, pesquise um endereço ou lugar, desenhe um polígono ou coloque um alfinete no mapa para visualizar os principais indicadores e informações sobre a área.</div>",
  "defineWhichInfographics": "Defina quais infográficos estão disponíveis no widget:",
  "defineWhichReports": "Defina quais relatórios estão disponíveis no widget:",
  "defaultValues": "Valores padrão:",
  "disable": "Desabilitar",
  "drawFreehandPolygon": "Desenhar um polígono à mão livre",
  "drawPolygon": "Desenhar Polígono",
  "driveTime": "Tempo de percurso",
  "dropPin": "Baixar Alfinete",
  "dynamicHTML": "HTML Dinâmica",
  "exportOptions": "Opções de Exportação:",
  "home": "Local",
  "image": "Imagem",
  "infographics": "Infográficos",
  "invalidValueRing": "Os valores devem estar na faixa de 0 até1,000.",
  "invalidValueDTWT": "Os valores devem estar na faixa de 0 até 300.",
  "km": "km",
  "makeDefault": "Tornar padrão",
  "miles": "milhas",
  "minutes": "minutos",
  "options": "Opções:",
  "pdf": "PDF",
  "print": "Imprimir",
  "radius": "Proporção",
  "removeDefault": "Remover padrão",
  "reports": "Relatórios",
  "rings": "Anéis",
  "searchTextBox": "Caixa de Texto de Pesquisa",
  "selectCountryOrRegion": "Selecione país ou região:",
  "thisEntryIsNotValid": "Esta entrada não é válida.",
  "time": "Hora",
  "walkTime": "Tempo de caminhada"
});