define({
  "_widgetLabel": "Erämääritteen muokkain",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Karttatason nimi",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Muokattavia karttatasoja ei ole määritetty",
  "editorPopupTitle": "Erämääritteen muokkain",
  "editorPopupSaveBtn": "Tallenna",
  "editorPopupMultipleValues": "",
  "clear": "Tyhjennä",
  "featuresUpdated": "${0}/${1} kohdetta on päivitetty",
  "featuresSelected": "Kohteita on valittu ${0}",
  "featuresSkipped": "Ohitettu",
  "featuresNoPermision": "${0} kohdetta valittu, mutta muokkausoikeuksia ei ole.",
  "search": "Etsi",
  "queryInput": "Suorita kysely antamalla arvo",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Määritä suodatin oikein.",
  "filterPopup": "Suodata taso",
  "filterAppend": "Jos suodatin on jo olemassa web-kartassa tätä karttatasoa varten",
  "filterAppendOR": "Liitä mikä tahansa lauseke olemassa olevan kartan suodattimeen",
  "filterAppendAND": "Liitä kaikki lausekkeet olemassa olevaan kartan suodattimeen",
  "cancel": "Peruuta",
  "noValue": "Ei arvoa",
  "emptyString": "Tyhjä merkkijono",
  "existingValue": "Säilytä olemassa oleva arvo",
  "newDate": "Uusi päivämäärä",
  "valueChooser": "Valitse tai kirjoita arvo",
  "ok": "OK",
  "drawBox": {
    "point": "Piste",
    "line": "Viiva",
    "polyline": "Taiteviiva",
    "freehandPolyline": "Vapaakädenpiirto, viiva",
    "extent": "Laajuus",
    "polygon": "Alue",
    "freehandPolygon": "Vapaankäden alue",
    "clear": "Tyhjennä",
    "addPointToolTip": "Valitse tältä alueelta napsauttamalla",
    "addShapeToolTip": "Valitse kohteita piirtämällä muoto",
    "freehandToolTip": "Valitse kohteita piirtämällä muoto pitkällä painalluksella",
    "startToolTip": "Valitse kohteita piirtämällä muoto"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Kohde kohteesta ${0} palautti virheellisen tunnuksen",
    "noSelectedLayers": "Päivitettäviä karttatasoja ja tietueita ei ole valittu",
    "inputValueError": "Virheellinen arvo lomakkeessa",
    "saveError": "${0} kohdetta ei voi tallentaa",
    "requiredValue": "Pakollinen arvo"
  }
});