define({
  "_widgetLabel": "Editor inteligent",
  "_featureAction_SmartEditor": "Editor inteligent",
  "noEditPrivileges": "Contul dumneavoastră nu are permisiunea de a crea sau modifica date.",
  "loginPopupTitle": "Autentificare",
  "loginPopupMessage": "${widgetName} necesită premisiuni și credite pentru a căuta și stoca informațiile privind adresa. Doriți să vă conectați și să folosiți această capacitate?",
  "noCreditsOrPrivilegeWarningMessage": "Contul dvs. nu are permisiunile și creditele pentru a căuta și stoca informațiile privind adresele cu ${widgetName}. Contactați administratorul organizației pentru a cere permisiuni și credite. Dați clic pe OK pentru a continua editarea.",
  "unableToUseLocator": "Localizatorul nu este accesibil. Acțiunea(ile) atributului de adresă nu vor fi efectuate. Dați clic pe OK pentru a continua editarea.",
  "locatorDisabledWaning": "Localizatorul nu este activat. Contactați administratorul organizației pentru a cere această capacitate. Dați clic pe OK pentru a continua editarea.",
  "noFeatureInAIWarning": "Nu sunt selectate obiecte spațiale. Selectați un obiect spațial pentru a efectua editările sau dați clic pe anulare pentru a reveni la ecranul principal.",
  "noEditableLayerWarning": "Contul dvs. nu are permisiunea de a crea sau modifica date sau această hartă web nu include niciun strat tematic editabil.",
  "noVisibleCreateLayerWarning": "Straturile tematice nu sunt vizibile la nivelul actual de transforcare. Măriți sau micșorați imaginea pentru a crea/modifica obiecte spațiale.",
  "noVisibleUpdateLayerWarning": "Straturile tematice nu sunt vizibile la nivelul actual de transforcare. Măriți sau micșorați imaginea pentru a modifica obiecte spațiale.",
  "checkLayerVisibilityInWebMapWarning": "Asigurați-vă că straturile tematice sunt vizibile pe hartă pentru a crea sau modifica obiecte spațiale.",
  "showSelectionInAITitle": "Obiecte spaţiale selectate",
  "showSelectionInAIMsg": "Doriți să încărcați selecția actuală în ${widgetName}?",
  "widgetActive": "Activ",
  "widgetNotActive": "Inactiv",
  "pressStr": "Apăsaţi pe ",
  "ctrlStr": " CTRL ",
  "snapStr": " pentru a activa fixarea",
  "noAvailableTempaltes": "Nu există şabloane disponibile",
  "editorCache": " - Cache editor",
  "presetFieldAlias": "Câmp",
  "presetValue": "Valoare presetată",
  "usePresetValues": " Utilizare valori presetate (numai pentru obiectele spaţiale noi)",
  "editGeometry": " Editare geometrie",
  "savePromptTitle": "Salvare obiect spaţial",
  "savePrompt": "Doriţi să salvaţi obiectul spaţial curent?",
  "deletePromptTitle": "Ştergere obiect spaţial",
  "deleteAttachment": "Ștergere atașare",
  "deletePrompt": "Sigur doriţi să ştergeţi obiectul spaţial selectat?",
  "attachmentLoadingError": "Eroare la încărcarea fişierelor ataşate",
  "attachmentSaveDeleteWarning": "Avertisment: Modificările fişierelor ataşate sunt salvate automat",
  "autoSaveEdits": "Salvați noile obiecte spațiale în mod automat",
  "addNewFeature": "Creați un obiect spațial nou",
  "featureCreationFailedMsg": "Nu se poate crea o nouă înregistrare/un nou obiect spațial",
  "relatedItemTitle": "Tabel/Strat tematic corelat",
  "relatedFeatureCount": "${layerTitle} cu ${featureCount} obiecte spațiale",
  "createNewFeatureLabel": "Creați un obiect spațial nou pentru ${layerTitle}",
  "invalidRelationShipMsg": "Asigurați-vă că există o valoare valabilă a câmpului cheii primare: '${parentKeyField}’",
  "pendingFeatureSaveMsg": "Vă rugăm să salvați editările aduse obiectului spațial înainte de a crea un obiect spațial asociat.",
  "attachmentsRequiredMsg": "(*) Sunt necesare anexe.",
  "coordinatePopupTitle": "Mutați obiectul spațial în locația XY",
  "coordinatesSelectTitle": "Sistem de coordonate:",
  "mapSpecialReferenceDropdownOption": "Referință spațială de hartă",
  "latLongDropdownOption": "Latitudine/Longitudine",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Coordonată:",
  "xAttributeTextBoxLabel": "Coordonata X:",
  "yAttributeTextBoxLabel": "Coordonata Y:",
  "latitudeTextBoxLabel": "Latitudine:",
  "longitudeTextBoxLabel": "Longitudine:",
  "presetGroupFieldsLabel": "'${groupName}' se va aplica pentru următoarele câmpuri de strat tematic:",
  "presetGroupNoFieldsLabel": "'${groupName}' nu are câmpuri asociate",
  "groupInfoLabel": "Informații privind grupul '${groupName}'",
  "editGroupInfoIcon": "Editați valoarea de grup pentru ${groupName}",
  "filterEditor": {
    "all": "Toate",
    "noAvailableTempaltes": "Nu există şabloane disponibile",
    "searchTemplates": "Căutare şabloane",
    "filterLayerLabel": "Filtrați straturile tematice"
  },
  "invalidConfiguration": "Widgetul nu este configurat sau straturile tematice din configuraţie nu se mai află pe hartă.  Deschideţi aplicaţia în modul de creare şi reconfiguraţi widgetul.",
  "geometryServiceURLNotFoundMSG": "Imposibil de obţinut URL-ul serviciului de geometrie",
  "clearSelection": "Închidere",
  "refreshAttributes": "Actualizarea atributelor dinamice ale obiectelor spațiale",
  "automaticAttributeUpdatesOn": "Actualizarea automată a atributelor obiectelor spațiale: ACTIVATĂ",
  "automaticAttributeUpdatesOff": "Actualizarea automată a atributelor obiectelor spațiale: DEZACTIVATĂ",
  "moveSelectedFeatureToGPS": "Mutarea obiectului spațial selectat în locația GPS curentă",
  "moveSelectedFeatureToXY": "Mutarea obiectului spațial selectat în locația XY",
  "mapNavigationLocked": "Navigare în hartă: blocată",
  "mapNavigationUnLocked": "Navigare în hartă: deblocată",
  "copyFeatures": {
    "title": "Obiectele spațiale selectate care trebuie copiate",
    "createFeatures": "Creare obiecte spațiale",
    "createSingleFeature": "Creați un obiect spațial cu multiple părți",
    "createOneSingleFeature": "Creați obiect spațial",
    "noFeaturesSelectedMessage": "Niciun obiect spațial selectat",
    "selectFeatureToCopyMessage": "Selectați obiectele spațiale care trebuie copiate",
    "multipleFeatureSaveWarning": "Crearea mai multor obiecte spațiale utilizând această funcție va salva imediat toate obiectele spațiale noi. Corelarea câmpurilor nu este acceptată la crearea unui nou obiect spațial cu mai multe părți.",
    "copyFeatureUpdateGeometryError": "Nu se poate actualiza geometria obiectelor spațiale selectate",
    "canNotSaveMultipleFeatureWarning": "Puteți copia un singur obiect spațial când stratul tematic punct țintă are câmpuri cu valori unice.",
    "createOnlyOneMultipartFeatureWarning": "Puteți copia un singur obiect spațial sau crea un obiect spațial cu mai multe părți când stratul tematic țintă are câmpuri de valori unice.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} din ${totalFeatures} obiecte spațiale selectate"
  },
  "addingFeatureError": "Eroare la adăugare obiecte spațiale selectate. Încercați din nou.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' obiecte spațiale nu au fost copiate. Doriți să încercați din nou pentru obiectele spațiale lipsă?",
  "selectingFeatureError": "Eroare la adăugare obiecte spațiale selectate. Încercați din nou.",
  "customSelectOptionLabel": "Obiectele spațiale selectate care trebuie copiate",
  "copyFeaturesWithPolygon": "Copiere după poligon",
  "copyFeaturesWithRect": "Copiere după dreptunghi",
  "copyFeaturesWithLasso": "Copiere după lasou",
  "noFeatureSelectedMessage": "Nu sunt selectate obiecte spațiale",
  "multipleFeatureSaveMessage": "Toate obiectele spațiale vor fi salvate imediat. Doriţi să continuaţi?",
  "relativeDates": {
    "dateTypeLabel": "Tip dată",
    "valueLabel": "Valoare",
    "fixed": "Fixă",
    "current": "Curentă",
    "past": "Anterioară",
    "future": "Viitoare",
    "popupTitle": "Selectați valoarea",
    "hintForFixedDateType": "Sugestie: Data și ora specificate vor fi utilizate ca valoare implicită presetată.",
    "hintForCurrentDateType": "Sugestie: Data și ora curente vor fi utilizate ca valoare implicită presetată.",
    "hintForPastDateType": "Sugestie: Valoarea specificată va fi scăzută din data și ora curente pentru valoarea implicită a presetării.",
    "hintForFutureDateType": "Sugestie: Valoarea specificată va fi adăugată la data și ora curente pentru valoarea implicită a presetării.",
    "noDateDefinedTooltip": "Nicio dată definită",
    "relativeDateWarning": "Trebuie specificată o valoare pentru dată sau oră pentru a putea salva valoarea presetată implicită.",
    "customLabel": "Personalizare",
    "layerLabel": "Strat tematic",
    "domainFieldHintLabel": "Valoarea selectată este un domeniu cu valoare codificată. Va fi folosită valoarea: \"${domainValue}\""
  },
  "valuePicker": {
    "popupTitle": "Selectaţi valoarea",
    "popupHint": "Obiectul spațial actual se intersectează cu obiecte spațiale multiple, alegeți valoarea pentru câmpul respectiv",
    "buttonTooltip": "Selectați valoarea din obiecte spațiale multiple care se intersectează"
  },
  "uniqueValueErrorMessage": "Valoarea din \"${fieldName}\" există deja, furnizați o valoare nouă.",
  "requiredFields": {
    "displayMsg": "Câmpurile obligatorii nu pot fi goale. Furnizaţi valori pentru câmpurile comune de mai jos.",
    "popupTittle": "Câmpuri obligatorii",
    "foundNullRecordCount": "${fieldName} (Găsit în ${count} înregistrări)"
  },
  "fieldsMapping": {
    "popupTittle": "Aplicare potrivire câmp",
    "fieldsMatchingCheckboxLabel": "Valoarea(ile) din obiectul(ele) spațial(e) copiat(e) va (vor) ignora valorile implicite din câmpul(rile) țintă",
    "resetLabel": "Resetare",
    "clearLabel": "Golire",
    "fieldsInTargetLayerLabel": "Ţintă",
    "fieldsInSourceLayerLabel": "Sursă",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} câmpuri corelate)",
    "selectSourceFieldLabel": "- Selectați -",
    "selectFieldAriaLabel": "Selectați câmpul sursă pentru câmpul țintă ${targetField}",
    "informativeText": "Revizuiți corelarea câmpurilor de la sursă la țintă și particularizați-o, dacă este cazul.",
    "dynamicValueText": "Este stabilită o valoare dinamică",
    "noFieldsToMatchLabel": "Nu există câmpuri de corelat"
  },
  "cantLocateUserLocation": "Localizarea dvs. nu a putut fi stabilită.",
  "tryAgainButtonLabel": "Încercaţi din nou",
  "copyFeatureFailedPopupTitle": "Hopa!"
});