define({
  "_widgetLabel": "Agregace dat",
  "startPage": {
    "defaultStartPageInstructions": "Tento widget napomáhá se zpracováním a odesíláním dat ze souboru do vybrané vrstvy v mapě.<br/> <br/> Hodnoty v souboru musí být odděleny čárkou, tabulátorem středníkem nebo svislou čarou.Tento widget napomáhá se zpracováním a odesíláním dat ze souboru do vybrané vrstvy v mapě.<br/> <br/> Hodnoty v souboru musí být odděleny čárkou, tabulátorem středníkem nebo svislou čarou.",
    "dragDrop": "Ručně přetáhnutím",
    "browse": "Přejít k souboru",
    "or": "'NEBO'",
    "userPrivilege": "Váš online účet nemá přístupová práva k vytváření nebo úpravě dat.",
    "userCredits": "${widgetName} vyžaduje kredity k použití lokátoru ${locator}.",
    "contactAdmin": "Kontaktujte správce organizace a požádejte o další kredity.",
    "contactAdminEdit": "Kontaktujte správce organizace a požádejte o úpravu oprávnění.",
    "canUseLocator": "Lokátor ${locator} bude použit k lokalizaci prvků.",
    "notEnoughCredits": "Nemáte dostatek kreditů.",
    "locationAndField": "Informace o umístě a poli",
    "locationAndFieldHint": "Vyberte hodnoty ze souboru, které chcete použít k aktualizaci cílové vrstvy.",
    "cannotUseLocator": "Nelze použít ${widgetName}",
    "noAnonymousEdit": "Vrstva ${layerName} nepodporuje anonymní úpravy.",
    "pleaseLogin": "Přihlaste se do organizace ${org} nebo kontaktujte jejího správce a požádejte o aktivaci anonymních úprav.",
    "invalidEdit": "Neplatná přístupová práva",
    "unableToAccess": "Nelze získat přístup k ${layerName}",
    "appropriateCredentials": "Ujistěte se, že jste pro přihlášení použili správné přístupové údaje.",
    "shared": "Kontaktujte správce organizace a požádejte o přístup k vrstvě ${layerName}.",
    "targetLayerLabel": "Cílová vrstva",
    "homeButtonLabel": "Domů",
    "mappingErrorMsg": "Dále klikněte na šipku a definujte pole"
  },
  "mapping": {
    "schemaMapping": "Informace o poli",
    "schemaMappingHint": "Vyberte pole ze souboru, která odpovídají polím ve vrstvě.",
    "locationMapping": "Informace o umístění",
    "locationMappingHint": "Vyberte typ adresy nebo informace o souřadnicích, které by měly být v souboru."
  },
  "locationMapping": {
    "locationMappingPageHint": "Vybrat typ umístění",
    "useAddress": "Vyhledat pomocí adresy",
    "useAddressHint": "Data obsahují informace o adrese",
    "useCoordinates": "Vyhledat pomocí souřadnic",
    "useCoordinatesHint": "Data obsahují hodnoty souřadnic X, Y"
  },
  "address": {
    "addressPageHint": "Vyberte typ adresy",
    "singleField": "Jedno pole",
    "singleFieldHint": "Vyberte pole obsahující informace o adrese",
    "multiField": "Více polí",
    "multiFieldHint": "Vyberte pole, která obsahují informace o adrese"
  },
  "coordinates": {
    "coordinatesPageHint": "Vyberte pole, která obsahují data souřadnic"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Zvolte zdrojové pole, které odkazuje na cílové pole",
    "sourceField": "Odpovídající zdrojové pole",
    "targetField": "Cílové pole"
  },
  "buttons": {
    "addToMap": "Přidat do mapy",
    "submit": "Odeslat",
    "download": "Stahování"
  },
  "review": {
    "matched": "Nalezeno",
    "reviewMatched": "Nalezená umístění",
    "reviewMatchedHint": "Zkontrolovat nalezená umístění.",
    "unMatched": "nenalezeno",
    "reviewUnMatched": "Umístění nenelezena",
    "reviewUnMatchedHint": "Zkontrolovat nenalezená umístění. Neopravené položky nebudou odeslány.",
    "duplicate": "Duplikovat",
    "reviewDuplicate": "Duplikovat umístění",
    "reviewDuplicateHint": "Zkontrolovat umístění, která již byla nalezena, ve vrstvě. Nevyřešené položky nebudou odeslány.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Použít:",
    "fromLayer": "Informace o cíli",
    "target": "Cíl",
    "source": "Zdroj",
    "fromFile": "Informace zdroje",
    "locationControlHint": "Zkontrolovat informace o adrese",
    "duplicateAction": "Vybrat akci",
    "item": "Záznam:",
    "locateFeature": "Najít prvek",
    "removeFeature": "Odebrat prvek",
    "featureLocated": "Umístění nalezeno",
    "valuesDoNotMatch": "Neshoduje se s existující hodnotou",
    "sync": "Synchronizovat informace o adrese s informacemi o poli",
    "noFeaturesSaved": "Žádné prvky nebyly úspěšně uloženy",
    "someFeaturesSaved": "${num} prvků bylo úspěšně uloženo.",
    "someFeaturesNotSaved": "${num} prvků se nepodařilo úspěšně uložit.",
    "feature": "Zkontrolovat informace o prvku",
    "locationInfo": "Zkontrolovat informace o umístění",
    "selectValue": "Vyberte hodnotu",
    "reviewData": "Zkontrolovat data",
    "reviewDataHint": "Před odesláním do vrstvy svá data zkontrolujte.",
    "reviewFeatureHint": "Zkontrolujte nebo upravte informace o prvku a umístění.",
    "duplicateModify": "Duplikát, vyžaduje změnu",
    "duplicateSave": "Uložit jako nový prvek"
  },
  "warningsAndErrors": {
    "invalidCSV": "Došlo k chybě při získávání položek z CSV, zkontrolujte, zda byl vybrán platný soubor CSV.",
    "noLayersWarning": "Nebyla nanfigurována platná cílová vrstva, zkontrolujte konfiguraci.",
    "loadWarning": "Tento widget potřebuje zdroj dat feature služby. Nakonfigurujte v tomto widgetu zdroj dat.",
    "saveError": "Chyba při ukládání prvků.",
    "consumesCredits": "Tento nástroj spotřebovává kredity při použití se službou ArcGIS Online World Geocoding Service",
    "noValue": "Vyberte pole",
    "mappingTitle": "",
    "locationMappingComplete": "Mapování umístění dokončeno",
    "fieldMappingComplete": "Mapování polí dokončeno",
    "settingsCleared": "Nastavení se vymaže.",
    "proceed": "Chcete pokračovat?",
    "itemMoveMatch": "Položka byla nalezena a přesunuta do seznamu nalezených umístění",
    "itemMoveUnMatched": "Nepodařilo se najít položku. Přesunuto do seznamu nenalezených umístění.",
    "itemWillBeLocated": "Položka bude odebrána ze seznamu duplicitních umístění.",
    "cannotLocate": "Položku se nepodařilo najít. Ověřte informace o umístění.",
    "invalidMessage": "Neplatná hodnota.",
    "rangeMessage": "Hodnota musí být kratší než ${num} znaků.",
    "locatorError": "Neplatný nebo nepřístupný lokátor.",
    "notConfigured": "lokátor není nakonfigurován na aktuální možnosti lokalizace",
    "noMoreLocators": "nebyly nakonfigurovány žádné další lokátory"
  },
  "featureToolbar": {
    "locate": "Najít",
    "save": "Uložit záznam",
    "cancel": "Zrušit úpravy",
    "cancelTitle": "Zrušit úpravy",
    "cancelMessage": "Zrušit úpravy aktuálního záznamu?"
  }
});