define({
  "_widgetLabel": "Älykäs muokkausohjelma",
  "_featureAction_SmartEditor": "Älykäs muokkausohjelma",
  "noEditPrivileges": "Tililläsi ei ole tietojen luonti- tai muokkausoikeuksia.",
  "loginPopupTitle": "Kirjaudu sisään",
  "loginPopupMessage": "${widgetName} edellyttää käyttöoikeuksia ja krediittejä, jotta osoitetietoja voidaan hakea ja tallentaa. Haluatko kirjautua sisään ja käyttää tätä ominaisuutta?",
  "noCreditsOrPrivilegeWarningMessage": "Tililläsi ei ole käyttöoikeuksia ja krediittejä, joita osoitetietojen hakeminen ja tallentaminen pienoisohjelmalla ${widgetName} edellyttää. Ota yhteyttä organisaation pääkäyttäjään ja pyydä käyttöoikeuksia ja krediittejä. Jatka muokkaamista valitsemalla OK.",
  "unableToUseLocator": "Paikannin ei ole käytettävissä. Osoitteen ominaisuustiedon toiminto(j)a ei suoriteta. Jatka muokkaamista valitsemalla OK.",
  "locatorDisabledWaning": "Paikannin ei ole käytössä. Ota yhteyttä organisaation pääkäyttäjään ja pyydä tätä ominaisuutta. Jatka muokkaamista valitsemalla OK.",
  "noFeatureInAIWarning": "Yhtään kohdetta ei ole valittu. Valitse kohde, jotta voit tehdä muokkauksia, tai palaa päänäyttöön valitsemalla Peruuta.",
  "noEditableLayerWarning": "Tilisi käyttöoikeudet eivät riitä aineiston luontiin tai muokkaukseen, tai tämä web-kartta ei sisällä muokattavia karttatasoja.",
  "noVisibleCreateLayerWarning": "Karttaso(t) ei(vät) näy käytössä olevalla tarkennustasolla. Lähennä tai loitonna, jotta voit luoda/muokata kohteita.",
  "noVisibleUpdateLayerWarning": "Karttaso(t) ei(vät) näy käytössä olevalla tarkennustasolla. Lähennä tai loitonna, jotta voit muokata kohteita.",
  "checkLayerVisibilityInWebMapWarning": "Varmista, että karttatasot näkyvät kartassa, jotta voit luoda tai muokata kohteita.",
  "showSelectionInAITitle": "Valitut kohteet",
  "showSelectionInAIMsg": "Haluatko ladata nykyisen valinnan pienoisohjelmassa ${widgetName}?",
  "widgetActive": "Aktiivinen",
  "widgetNotActive": "Ei aktiivinen",
  "pressStr": "Paina ",
  "ctrlStr": " CTRL ",
  "snapStr": " tartunnan käyttöön ottamiseksi",
  "noAvailableTempaltes": "Yhtään mallia ei ole käytettävissä",
  "editorCache": " - Muokkausohjelman välimuisti",
  "presetFieldAlias": "Kenttä",
  "presetValue": "Esiasetettu arvo",
  "usePresetValues": " Käytä esiasetettuja arvoja (vain uudet kohteet)",
  "editGeometry": " Muokkaa geometriaa",
  "savePromptTitle": "Tallenna kohde",
  "savePrompt": "Haluatko tallentaa nykyisen kohteen?",
  "deletePromptTitle": "Poista kohde",
  "deleteAttachment": "Poista liite",
  "deletePrompt": "Haluatko varmasti poistaa valitun kohteen?",
  "attachmentLoadingError": "Virhe ladattaessa liitteitä",
  "attachmentSaveDeleteWarning": "Varoitus: liitteiden muutokset tallennetaan automaattisesti",
  "autoSaveEdits": "Tallenna uudet kohteet automaattisesti",
  "addNewFeature": "Luo uusi kohde",
  "featureCreationFailedMsg": "Uutta tietuetta tai kohdetta ei voi luoda",
  "relatedItemTitle": "Liittyvä taulukko tai karttataso",
  "relatedFeatureCount": "${layerTitle}, jossa on ${featureCount} kohdetta",
  "createNewFeatureLabel": "Luo uusi kohde karttatasolle ${layerTitle}",
  "invalidRelationShipMsg": "Varmista, että ensisijaisen avainkentän ${parentKeyField} arvo on kelvollinen",
  "pendingFeatureSaveMsg": "Tallenna kohteen muokkaukset ennen liittyvän kohteen luontia.",
  "attachmentsRequiredMsg": "(*) Liitteet ovat pakollisia.",
  "coordinatePopupTitle": "Siirrä kohde XY-sijaintiin",
  "coordinatesSelectTitle": "Koordinaattijärjestelmä:",
  "mapSpecialReferenceDropdownOption": "Kartan koordinaatistotieto",
  "latLongDropdownOption": "Leveysaste/Pituusaste",
  "mgrsDropdownOption": "MGRS (Military Grid Reference System)",
  "mgrsTextBoxLabel": "Koordinaatti:",
  "xAttributeTextBoxLabel": "X-koordinaatti:",
  "yAttributeTextBoxLabel": "Y-koordinaatti:",
  "latitudeTextBoxLabel": "Leveysaste:",
  "longitudeTextBoxLabel": "Pituusaste:",
  "presetGroupFieldsLabel": "Ryhmää ${groupName} käytetään seuraavissa karttatason kentissä:",
  "presetGroupNoFieldsLabel": "Ryhmään ${groupName}’ ei ole liitetty kenttiä",
  "groupInfoLabel": "Ryhmän ${groupName} tiedot",
  "editGroupInfoIcon": "Muokkaa ryhmän ${groupName} ryhmäarvoa",
  "filterEditor": {
    "all": "Kaikki",
    "noAvailableTempaltes": "Yhtään mallia ei ole käytettävissä",
    "searchTemplates": "Hae malleja",
    "filterLayerLabel": "Suodata karttatasot"
  },
  "invalidConfiguration": "Pienoisohjelmaa ei ole joko määritetty tai määrityksen karttatasoja ei ole enää kartassa. Avaa sovellus luontitilassa ja määritä pienoisohjelma uudelleen.",
  "geometryServiceURLNotFoundMSG": "Geometriapalvelun URL-osoitetta ei voi noutaa",
  "clearSelection": "Tallennettu",
  "refreshAttributes": "Päivitä dynaamisen kohteen ominaisuustiedot",
  "automaticAttributeUpdatesOn": "Päivitä kohteen ominaisuustiedot automaattisesti: KÄYTÖSSÄ",
  "automaticAttributeUpdatesOff": "Päivitä kohteen ominaisuustiedot automaattisesti: POIS KÄYTÖSTÄ",
  "moveSelectedFeatureToGPS": "Siirrä valittu kohde nykyiseen GPS-sijaintiin",
  "moveSelectedFeatureToXY": "Siirrä valittu kohde XY-sijaintiin",
  "mapNavigationLocked": "Kartan navigointi: lukittu",
  "mapNavigationUnLocked": "Kartan navigointi: ei lukittu",
  "copyFeatures": {
    "title": "Valitse kopioitavat kohteet",
    "createFeatures": "Luo kohteet",
    "createSingleFeature": "Luo yksi moniosainen kohde",
    "createOneSingleFeature": "Luo kohde",
    "noFeaturesSelectedMessage": "Yhtään kohdetta ei ole valittu",
    "selectFeatureToCopyMessage": "Valitse kopioitavat kohteet",
    "multipleFeatureSaveWarning": "Usean kohteen luonti tällä toiminnolla tallentaa kaikki uudet kohteet heti. Kenttien täsmäytystä ei tueta luotaessa uutta moniosaista kohdetta.",
    "copyFeatureUpdateGeometryError": "Valittujen kohteiden geometriaa ei voi päivittää",
    "canNotSaveMultipleFeatureWarning": "Voit kopioida vain yhden kohteen, kun kohdepistekarttatasossa on yksilöllisiä arvokenttiä.",
    "createOnlyOneMultipartFeatureWarning": "Voit kopioida vain yhden kohteen tai luoda yhden moniosaisen kohteen, kun kohdekarttatasossa on yksilöllisiä arvokenttiä.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures}/${totalFeatures} kohdetta valittu"
  },
  "addingFeatureError": "Virhe lisättäessä valittuja kohteita karttatasoon. Yritä uudelleen.",
  "addingFeatureErrorCount": "${copyFeatureErrorCount} kohteen kopiointi ei onnistunut. Haluatko yrittää uudelleen puuttuvien kohteiden osalta?",
  "selectingFeatureError": "Virhe valittaessa kohteita karttatasosta. Yritä uudelleen.",
  "customSelectOptionLabel": "Valitse kopioitavat kohteet",
  "copyFeaturesWithPolygon": "Kopioi aluekohteen mukaan",
  "copyFeaturesWithRect": "Kopioi suorakulmion mukaan",
  "copyFeaturesWithLasso": "Kopioi lasson mukaan",
  "noFeatureSelectedMessage": "Yhtään kohdetta ei ole valittu",
  "multipleFeatureSaveMessage": "Kaikki kohteet tallennetaan heti. Haluatko jatkaa?",
  "relativeDates": {
    "dateTypeLabel": "Päivämäärätyyppi",
    "valueLabel": "Arvo",
    "fixed": "Kiinteä",
    "current": "Nykyinen",
    "past": "Menneet",
    "future": "Tuleva",
    "popupTitle": "Valittu arvo",
    "hintForFixedDateType": "Vihje: määritettyä päivämäärää ja aikaa käytetään ennalta määritettynä oletusarvona.",
    "hintForCurrentDateType": "Vihje: nykyistä päivämäärää ja aikaa käytetään ennalta määritettynä oletusarvona.",
    "hintForPastDateType": "Vihje: määritetty arvo vähennetään nykyisestä päivämäärästä ja ajasta ennalta määritettyä oletusarvoa varten.",
    "hintForFutureDateType": "Vihje: määritetty arvo lisätään nykyiseen päivämäärään ja ajasta ennalta määritettyä oletusarvoa varten.",
    "noDateDefinedTooltip": "Päivämäärää ei ole määritetty",
    "relativeDateWarning": "Päivämäärä tai kellonaika pitää määrittää, jotta ennalta määritetty oletusarvo voidaan tallentaa.",
    "customLabel": "Mukautettu",
    "layerLabel": "Karttataso",
    "domainFieldHintLabel": "Valittu arvo on koodattu arvoalue. Arvoa ${domainValue} käytetään"
  },
  "valuePicker": {
    "popupTitle": "Valitse arvo",
    "popupHint": "Nykyinen kohde leikkaa useita kohteita, valitse arvo vastaavaa kenttää varten",
    "buttonTooltip": "Valitse arvo useasta leikkaavasta kohteesta"
  },
  "uniqueValueErrorMessage": "Kentän ${fieldName} arvo on jo olemassa. Anna uusi arvo.",
  "requiredFields": {
    "displayMsg": "Pakolliset kentät eivät voi olla tyhjiä. Määritä yleisten kenttien arvot alla.",
    "popupTittle": "Pakolliset kentät",
    "foundNullRecordCount": "${fieldName} (löytyi ${count} tietueesta)"
  },
  "fieldsMapping": {
    "popupTittle": "Käytä kenttien täsmäytystä",
    "fieldsMatchingCheckboxLabel": "Kopioitujen kohteiden arvot korvaavat kohdekenttien oletusarvot",
    "resetLabel": "Palauta",
    "clearLabel": "Tyhjennä",
    "fieldsInTargetLayerLabel": "Kohde",
    "fieldsInSourceLayerLabel": "Lähde",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} kenttää täsmäytetty)",
    "selectSourceFieldLabel": "– Valitse –",
    "selectFieldAriaLabel": "Valitse lähdekenttä kohdekentälle ${targetField}",
    "informativeText": "Tarkista täsmäytetyt lähde- ja kohdekentät ja mukauta tarvittaessa.",
    "dynamicValueText": "Dynaaminen arvo on asetettu",
    "noFieldsToMatchLabel": "Ei täsmäytettäviä kenttiä"
  },
  "cantLocateUserLocation": "Sijaintiasi ei voitu määrittää",
  "tryAgainButtonLabel": "Yritä uudelleen",
  "copyFeatureFailedPopupTitle": "Hups!"
});