define({
  "layersPage": {
    "allLayers": "Svi slojevi",
    "title": "Odaberite predložak za izradu značajki",
    "generalSettings": "Opće postavke",
    "layerSettings": "Postavke sloja",
    "webmapSettingsRadioBtnLabel": "Poštivanje postavki web-karte",
    "customSettingsRadioBtnLabel": "Prilagođene postavke",
    "smartActionsTabTitle": "Pametne radnje",
    "attributeActionsTabTitle": "Radnje atributa",
    "geocoderSettingsText": "Postavke Geokodera",
    "editDescription": "Navedite tekst za prikaz na ploči za uređivanje",
    "editDescriptionTip": "Ovaj se tekst prikazuje iznad birača predložaka, ostavite prazno ako ne želite da bude teksta.",
    "promptOnSave": "Upit za spremanjem nepohranjenih izmjena prilikom zatvaranja obrasca ili prebacivanja na sljedeći zapis",
    "promptOnSaveTip": "Prikazivanje upita kada trenutni geoobjekt ima nespremljena uređivanja. (Kopiranje više geoobjekata sprema automatski.)",
    "promptOnDelete": "Potrebna je potvrda prilikom brisanja zapisa",
    "promptOnDeleteTip": "Prikazivanje upita za potvrdu radnje kada korisnik klikne za brisanje.",
    "removeOnSave": "Uklanjanje geoobjekta iz odabira prilikom spremanja",
    "removeOnSaveTip": "Opcija za uklanjanje geoobjekta iz skupa za odabir kad se zapis spremi.  Ako je to jedini odabrani zapis, ploča se prebacuje natrag na stranicu predloška.",
    "useFilterEditor": "Upotrijebi filtar predloška geoobjekta",
    "useFilterEditorTip": "Opcija za upotrebu birača predloška filtra koja pruža mogućnost prikaza predloška jednog sloja ili pretraživanja predložaka po nazivu.",
    "displayShapeSelector": "Prikaži opcije crtanja",
    "createNewFeaturesFromExisting": "Omogući korisniku stvaranje novih geoobjekata iz postojećih geoobjekata",
    "createNewFeaturesFromExistingTip": "Opcija kojom se korisniku omogućuje kopiranje postojećeg geoobjekta kako bi se stvorili novi geoobjekti",
    "copiedFeaturesOverrideDefaults": "Vrijednosti kopiranih geoobjekata nadjačavaju zadane postavke",
    "copiedFeaturesOverrideDefaultsTip": "Vrijednosti iz kopiranih geoobjekata nadjačat će zadane vrijednosti predložaka samo za polja koja se podudaraju",
    "displayShapeSelectorTip": "Opcija za prikaz popisa valjanih opcija crtanja za odabrani predložak.",
    "displayPresetTop": "Prikaži prethodno postavljenu vrijednost na vrhu",
    "displayPresetTopTip": "Opcija za prikaz popisa prethodno postavljenih vrijednosti iznad odabirača predložaka.",
    "listenToGroupFilter": "Primijenite vrijednosti filtra iz widgeta grupnog filtra u predefinirana polja",
    "listenToGroupFilterTip": "Kada se primijeni filtar u widgetu grupnog filtra, primijenite vrijednost u odgovarajuće polje u popisu s predefiniranim vrijednostima.",
    "keepTemplateActive": "Ostavite aktivnim odabrani predložak",
    "keepTemplateActiveTip": "Kada se prikaže birač predloška, a prethodno je odabran predložak, ponovno ga odaberite.",
    "geometryEditDefault": "Omogući uređivanje geometrije po zadanim postavkama",
    "autoSaveEdits": "Automatski spremaj nove geoobjekte",
    "enableAttributeUpdates": "Prikaži gumb za ažuriranje radnji atributa",
    "enableAutomaticAttributeUpdates": "Automatsko pozivanje radnji atributa nakon ažuriranja geometrije",
    "enableLockingMapNavigation": "Omogući zaključavanje navigacije karte",
    "enableMovingSelectedFeatureToGPS": "Omogući pomicanje odabranih točkastih geoobjekata na GPS lokaciju",
    "enableMovingSelectedFeatureToXY": "Omogući pomicanje odabranih točkastih geoobjekata na XY lokaciju",
    "featureTemplateLegendLabel": "Predložak geoobjekta i postavke vrijednosti filtra",
    "saveSettingsLegendLabel": "Spremi postavke",
    "geometrySettingsLegendLabel": "Postavke geometrije",
    "actionsSettingsLegendLabel": "Postavke radnji",
    "buttonPositionsLabel": "Položaj gumba za spremanje, brisanje, povratak i poništavanje",
    "belowEditLabel": "Ispod obrasca za uređivanje",
    "aboveEditLabel": "Iznad obrasca za uređivanje",
    "switchToMultilineInput": "Prebaci na unos u više redaka kada se dužina polja prekorači",
    "enableValuePicker": "Omogućite alat za biranje vrijednosti presijecanja",
    "enableValuePickerHint": "Prikaz upita kada je za polje s radnjom atributa presijecanja dostupno više vrijednosti",
    "expandRelatedTable": "Proširi sve povezane tablice/slojeve pri učitavanju",
    "expandMainTable": "Proširi sve nadređene slojeve pri učitavanju",
    "layerSettingsTable": {
      "allowDelete": "Omogući brisanje",
      "allowDeleteTip": "Omogući opciju Izbriši - opcija za omogućavanje korisniku brisanje geoobjekta; onemogućeno ako sloj ne podržava brisanje",
      "edit": "Može se uređivati",
      "editTip": "Može se uređivati - opcija za uključivanje sloja u widget",
      "label": "Sloj",
      "labelTip": "Sloj - naziv sloja kako je definirano na karti",
      "update": "Onemogući uređivanje geometrije",
      "updateTip": "Onemogući uređivanje geometrije - opcija za onemogućivanje mogućnosti pomicanja geometrije jednom kad se postavi ili pomicanja geometrije na postojeći geoobjekt",
      "allowUpdateOnly": "Ažuriraj samo",
      "allowUpdateOnlyTip": "Samo ažuriraj - opcija za omogućivanje izmjena samo postojećih geoobjekata, omogućeno po zadanim postavkama i onemogućeno ako sloj ne podržava stvaranje novih geoobjekata",
      "fieldsTip": "Izmijenite polja za uređivanje i definirajte pametne atribute",
      "actionsTip": "Radnje - opcija za uređivanje polja ili pristup povezanim slojevima/tablicama",
      "description": "Opis",
      "descriptionTip": "Opis - opcija za unos teksta da se prikazuje na vrhu stranice atributa.",
      "relationTip": "Prikaži povezane slojeve i tablice"
    },
    "editFieldError": "Izmjena polja i pametni atributi nisu dostupni za slojeve koji se ne mogu uređivati",
    "noConfigedLayersError": "Za Pametni uređivač potreban je jedan ili više slojeva koji se mogu uređivati",
    "toleranceErrorMsg": "Nevažeća zadana vrijednost dopuštenog odstupanja presijecanja",
    "pixelsToleranecErrorMsg": "Nevažeća zadana vrijednost dopuštenog odstupanja piksela",
    "invalidMaxCharacterErrorMsg": "Nevažeća vrijednost kod prebacivanja na unos u više redaka",
    "featuresSelectionTolerance": "Postavite toleranciju za odabir geoobjekta (pikseli)",
    "featuresSelectionToleranceTooltip": "Omogućuje korisnicima lako otvaranje ploče za uređivanje atributa klikom na geoobjekt",
    "featuresSelectionToleranceErrorMsg": "Nevažeća vrijednost tolerancije za odabir geoobjekta"
  },
  "editDescriptionPage": {
    "title": "Definirajte tekst pregleda atributa za <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Konfigurirajte polja za <b>${layername}</b>",
    "copyActionTip": "Radnje atributa",
    "editActionTip": "Pametne radnje",
    "description": "Upotrijebite gumb za uređivanje radnji da biste aktivirali pametne atribute na sloju. Pametni atributi mogu zahtijevati, sakriti ili onemogućiti polje na temelju vrijednosti u drugim poljima. Upotrijebite gumb za kopiranje radnji kako biste aktivirali i definirali izvor vrijednosti polja presijecanjem, adresom, koordinatama te ih prethodno postavili.",
    "fieldsNotes": "* je obavezno polje. Ako odznačite prikaz za ovo polje i predložak uređivanja ne ispuni vrijednost tog polja, nećete moći spremiti novi zapis.",
    "smartAttachmentText": "Konfigurirajte pametne radnje za privitke",
    "smartAttachmentPopupTitle": "Konfigurirajte pametne radnje za privitke u <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Odaberite barem jedno polje prikaza za sloj ${layerName}",
    "fieldsSettingsTable": {
      "display": "Prikaži",
      "displayTip": "Prikaz - utvrdite je li polje nevidljivo",
      "edit": "Može se uređivati",
      "editTip": "Može se uređivati - provjerite postoji li polje u obliku atributa",
      "fieldName": "Naziv",
      "fieldNameTip": "Naziv - naziv polja definiran je u bazi podataka",
      "fieldAlias": "Alias",
      "fieldAliasTip": "Alias - naziv polja definiran na karti",
      "canPresetValue": "Zadano",
      "canPresetValueTip": "Prethodno postavi - opcija za prikazivanje polja u popisu prethodno postavljenih polja i omogućivanje korisniku postavljanje vrijednosti prije uređivanja",
      "actions": "Radnje",
      "actionsTip": "Radnje - promijenite redoslijed polja ili postavite pametne atribute"
    },
    "smartAttSupport": "Pametni atributi nisu podržani u potrebnim poljima baze podataka"
  },
  "actionPage": {
    "title": "Konfigurirajte radnje atributa za <b>${fieldname}</b>",
    "smartActionTitle": "Konfigurirajte pametne radnje za <b>${fieldname}</b>",
    "description": "Radnje su uvijek isključene osim ako ne odredite kriterije po kojima će se aktivirati.  Radnje se obrađuju po redu i samo će se jedna radnja aktivirati po polju.  Upotrijebite gumb za uređivanje kriterija kako biste definirali kriterije.",
    "copyAttributesNote": "Onemogućavanje bilo koje radnje s nazivom grupe bit će jednako kao i neovisno uređivanje te radnje te će ukloniti radnju za ovo polje iz odgovarajuće grupe.",
    "searchPlaceHolder": "Potraži",
    "expandAllLabel": "Proširi sve slojeve",
    "selectAllLabel": "Odaberi sva polja",
    "domainListTitle": "Polja domene",
    "noValidFieldTypeMsg": "Nema odgovarajućeg sloja dostupnog na karti za ovu vrstu podataka",
    "actionsSettingsTable": {
      "rule": "Radnja",
      "ruleTip": "Radnja - radnja izvršena kad su zadovoljeni kriteriji",
      "expression": "Izraz",
      "expressionTip": "Izraz - dobiveni izraz u SQL formatu od definiranih kriterija",
      "groupName": "Naziv grupe",
      "groupNameTip": "Naziv grupe - prikazuje naziv grupe iz kojega je izraz primijenjen",
      "actions": "Kriteriji",
      "actionsTip": "Kriteriji - promijenite redoslijed pravila i definirajte kriterije kad će se aktivirati"
    },
    "copyAction": {
      "description": "Izvori vrijednosti polja obrađuju se po redu ako su aktivirani dok se ne aktiviraju važeći kriteriji ili se popis ne dovrši. Upotrijebite gumb za uređivanje kriterija da biste definirali kriterije.",
      "intersection": "Raskrižje",
      "coordinates": "Koordinate",
      "address": "Adresa",
      "preset": "Zadano",
      "actionText": "Radnje",
      "criteriaText": "Kriteriji",
      "enableText": "Omogućeno"
    },
    "actions": {
      "hide": "Sakrij",
      "required": "Potrebno",
      "disabled": "Onemogućeno"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Upozorenje: značajka Uredi samostalno uklonit će odabranu radnju atributa pridruženu ovom polju iz grupe",
      "editGroupHint": "Upozorenje: značajka Uredi samostalno uklonit će odabranu pametnu radnju pridruženu ovom polju iz grupe",
      "popupTitle": "Odaberite opciju uređivanja",
      "editAttributeGroup": "Odabrana radnja atributa definirana je iz grupe. Odaberite jednu od sljedećih opcija za uređivanje radnje atributa:",
      "expression": "Izraz odabrane pametne radnje definiran je iz grupe. Odaberite jednu od sljedećih opcija za uređivanje izraza pametne radnje:",
      "editGroupButton": "Uredi grupu",
      "editIndependentlyButton": "Uredi pojedinačno"
    }
  },
  "filterPage": {
    "submitHidden": "Predaj podatke o atributu za ovo polje, čak i kad je skriveno",
    "title": "Konfiguriraj izraz za pravilo ${action}",
    "filterBuilder": "Postavite radnju za polje kad zapis odgovara ${any_or_all} sljedećim izrazima",
    "noFilterTip": "Pomoću gornjih alata definirajte izjavu za situaciju kad je radnja aktivna."
  },
  "geocoderPage": {
    "setGeocoderURL": "Postavi URL geokodera",
    "hintMsg": "Napomena: mijenjate uslugu geokodera, svakako ažurirajte kartiranja polja geokodera koja ste konfigurirali.",
    "invalidUrlTip": "URL ${URL} nije valjan ili dostupan."
  },
  "addressPage": {
    "popupTitle": "Adresa",
    "checkboxLabel": "Preuzmi vrijednost s Geokodera",
    "selectFieldTitle": "Atribut",
    "geocoderHint": "Da biste promijenili geokoder, idite na gumb „Postavke Geokodera” u općim postavkama",
    "prevConfigruedFieldChangedMsg": "Prethodno konfigurirani atribut nije pronađen u trenutačnim postavkama geokodera. Atribut je ponovno postavljen na zadane postavke.",
    "questionMark": "?"
  },
  "coordinatesPage": {
    "popupTitle": "Koordinate",
    "checkboxLabel": "Preuzmi koordinate",
    "coordinatesSelectTitle": "Referentni sustav",
    "coordinatesAttributeTitle": "Atribut",
    "mapSpatialReference": "Prostorna referenca karte",
    "latlong": "Geografska dužina/širina",
    "MGRS": "MGRS",
    "allGroupsCreatedMsg": "Sve moguće grupe već su stvorene",
    "coordinatesSourceTitle": "Izvor koordinata",
    "featureLocation": "Lokacija geoobjekta",
    "myLocation": "Moja lokacija"
  },
  "presetPage": {
    "popupTitle": "Zadano",
    "checkboxLabel": "Polje će se prethodno postaviti",
    "showOnlyDomainFields": "Prikaži samo polja domene",
    "hideInPresetDisplay": "Sakrij kod prikaza prethodno postavljenih vrijednosti",
    "presetValueLabel": "Trenutačna prethodno postavljena vrijednost iznosi:",
    "changePresetValueHint": "Da biste promijenili ovu prethodno postavljenu vrijednost, idite na gumb „Definiraj prethodno postavljene vrijednosti” u općim postavkama"
  },
  "intersectionPage": {
    "groupNameLabel": "Naziv grupe",
    "dataTypeLabel": "Vrsta podataka",
    "ignoreLayerRankingCheckboxLabel": "Zanemarite rangiranje slojeva i pronađite najbliži geoobjekt u svim definiranim slojevima",
    "intersectingLayersLabel": "Slojevi za izdvajanje vrijednosti",
    "layerAndFieldsApplyLabel": "Slojevi i polja za primjenu izvezene vrijednosti",
    "checkboxLabel": "Preuzmi vrijednost s polja sloja presijecanja",
    "layerText": "Slojevi",
    "fieldText": "Polja",
    "actionsText": "Radnje",
    "toleranceSettingText": "Postavke dopuštenog odstupanja",
    "addLayerLinkText": "Dodaj sloj",
    "useDefaultToleranceText": "Upotrijebi zadano dopušteno odstupanje",
    "toleranceValueText": "Vrijednost dopuštenog odstupanja",
    "toleranceUnitText": "Jedinica dopuštenog odstupanja",
    "pixelsUnitText": "Pikseli",
    "useLayerName": "- Upotrijebi naziv sloja -",
    "noLayersMessage": "Nijedno polje nije pronađeno na slojevima karte koje odgovara odabranoj vrsti podataka.",
    "intersectionLayerHint": "Poredak slojeva određuje se silaznim redoslijedom. Pomoću strelica u odjeljku Radnje promijenite redoslijed slojeva i promijenite prioritet raskrižja."
  },
  "presetAll": {
    "popupTitle": "Definiraj zadane prethodno postavljene vrijednosti",
    "deleteTitle": "Izbriši prethodno postavljenu vrijednost",
    "hintMsg": "Ovdje su navedeni svi jedinstveni prethodno postavljeni nazivi polja. Uklanjanje prethodno postavljenog polja onemogućit će odgovarajuće polje kao prethodno postavljeno iz svih slojeva/tablica."
  },
  "intersectionTolerance": {
    "intersectionTitle": "Zadano dopušteno odstupanje presijecanja za sve geoobjekte",
    "pixelsToleranceTitle": "Zadano dopušteno odstupanje presijecanja (vrijednost piksela) koje će se primjenjivati samo za točkaste geoobjekte"
  },
  "smartActionsPage": {
    "smartActionLabel": "Konfiguriraj opciju Pametna radnja",
    "addNewSmartActionLinkText": "Dodaj novi",
    "definedActions": "Definirane radnje",
    "priorityPopupTitle": "Postavi prioritet pametnih radnji",
    "priorityPopupColumnTitle": "Pametne radnje",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Naziv grupe",
    "layerForExpressionLabel": "Sloj za izraz",
    "layerForExpressionNote": "Napomena: Polja ovog sloja koriste se za definiranje kriterija izraza. 'Slojevi i polja za primjenu' prikazuje samo slojeve i tablice koji imaju polja definirana u izrazu.",
    "expressionText": "Izraz",
    "editExpressionLabel": "Uredi izraz",
    "layerAndFieldsApplyLabel": "Slojevi i polja za primjenu",
    "submitAttributeText": "Predaj podatke o atributu za ovo polje, čak i kad je skriveno",
    "priorityColumnText": "Prioritet",
    "requiredGroupNameMsg": "Ova je vrijednost obvezna",
    "uniqueGroupNameMsg": "Unesite jedinstveni naziv grupe, grupa s tim nazivom već postoji.",
    "deleteGroupPopupTitle": "Izbrišite grupu za pametne radnje",
    "deleteGroupPopupMsg": "Brisanje grupe rezultirat će uklanjanjem izraza iz svih pridruženih radnji polja.",
    "invalidExpression": "Izraz ne može biti prazan",
    "warningMsgOnLayerChange": "Izbrisat će se definirani izraz i polja na koja se on primjenjuje.",
    "smartActionsTable": {
      "name": "Naziv",
      "expression": "Izraz",
      "definedFor": "Definirano za"
    }
  },
  "attributeActionsPage": {
    "name": "Naziv",
    "type": "Vrsta",
    "deleteGroupPopupTitle": "Izbriši grupu za radnje atributa",
    "deleteGroupPopupMsg": "Brisanje grupe rezultirat će uklanjanjem radnje atributa iz svih pridruženih polja.",
    "alreadyAppliedActionMsg": "${action} akcija primjenjena na ovo polje u grupi",
    "alreadyAppliedActionLayerMsg": "${action} akcija primjenjena na ovo polje iz postavki sloja",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Ova grupa nema pridružena polja.",
    "presetNoFieldWarningMsg": "Konfigurirajte barem jedno polje za prisutnu grupu : ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Polje",
    "valueLabel": "Vrijednost",
    "selectValueLabel": "Odaberi vrijednost",
    "domainFieldHintLabel": "Odabrana vrijednost je domena kodirane vrijednosti. Vrijednost: ${domainValue} će biti korištena"
  },
  "presetPopup": {
    "presetValueLAbel": "Prethodno postavljena vrijednost"
  },
  "dataType": {
    "esriFieldTypeString": "Tekst",
    "esriFieldTypeInteger": "Broj",
    "esriFieldTypeDate": "Datum",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Vrsta datuma",
    "valueLabel": "Vrijednost",
    "fixed": "Popravljeno",
    "current": "Trenutačno",
    "past": "Prošli",
    "future": "Buduće",
    "popupTitle": "Odaberi vrijednost",
    "hintForFixedDateType": "Savjet: Određeni datum i vrijeme bit će upotrebljeni kao prethodno postavljene zadane vrijednosti",
    "hintForCurrentDateType": "Savjet: Trenutačni datum i vrijeme bit će upotrebljeni kao prethodno postavljene zadane vrijednosti",
    "hintForPastDateType": "Savjet: Određena vrijednost bit će odbijena od trenutačnog datuma i vremena za zadanu prethodno postavljenu vrijednost.",
    "hintForFutureDateType": "Savjet: Određena vrijednost bit će dodana trenutačnom datumu i vremenu za zadanu prethodno postavljenu vrijednost.",
    "noDateDefinedTooltip": "Nije određen datum",
    "relativeDateWarning": "Vrijednost datuma ili vremena mora se specificirati kako bi se mogla spremiti zadana unaprijed postavljena vrijednost.",
    "customLabel": "Prilagodi"
  },
  "relativeDomains": {
    "fieldSetTitle": "Popis",
    "valueText": "Vrijednost",
    "defaultText": "Zadano",
    "selectedDomainFieldsHint": "Odabrana polja domene: ${domainFields}",
    "selectDefaultDomainMsg": "Odaberite zadanu domenu vrijednosti ili osigurajte da je označen potvrdni okvir odabrane zadane domene"
  }
});