define({
  "transparencyLabel": "Transparens",
  "outline": "Kontur",
  "fill": "Fyllningsfärg (Färgen tillämpas enbart när stilen anges till solid)",
  "style": "Format",
  "selectOpLayerLabel": "Välj ett funktionslager för resultat",
  "selectDefaultMeasurementLabel": "Ange en standardmåttenhet",
  "helpIconTooltip": "Listan med funktionslager innehåller lager från den aktuella webbkartan som är av typen polygongeometri.",
  "lineStyles": {
    "esriSLSDash": "Streck",
    "esriSLSDashDot": "Streck punkt",
    "esriSLSDashDotDot": "Streck punkt punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Långt streck",
    "esriSLSLongDashDot": "Lång streck-punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort streck",
    "esriSLSShortDashDot": "Kort streck-punkt",
    "esriSLSShortDashDotDot": "Kort streck-punkt-punkt",
    "esriSLSShortDot": "Kort punkt",
    "esriSLSSolid": "Solid"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakåt",
    "esriSFSCross": "Kors",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Framåt",
    "esriSFSHorizontal": "Horisontell",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Solid",
    "esriSFSVertical": "Vertikal"
  },
  "threatTypeLabel": "Typ av hot",
  "generalLabel": "Allmänt",
  "addThreatTypesLabel": "Lägg till typ av hot",
  "actions": "Åtgärder",
  "newThreatTypePopupLabel": "Ny typ av hot",
  "units": "Enheter",
  "chooseDefaultThreatLabel": "Välj standardtyp för hot",
  "defaultThreatTypePopUpLabel": "Standardtyper för hot",
  "editThreatLabel": "Redigera hot",
  "defaultThreatTypeIconTooltip": "Lista med standardtyper för hot",
  "uniqueThreatTypeMsg": "Ange en unik typ av hot, det finns redan en typ av hot med det här namnet.",
  "requiredMsg": "Det här fältet är obligatoriskt.",
  "unitMeasureLabel": "Avstånd anges i {0}",
  "chooseDefaultThreatTypeIconLabel": "Välj från standard",
  "pipeBombLabel": "Rörbomb",
  "suicideBombLabel": "Självmordsbomb",
  "briefcaseLabel": "Portfölj",
  "carLabel": "Bil",
  "suvVanLabel": "SUV/skåpbil",
  "smallDeliveryTruckLabel": "Liten fraktlastbil",
  "containerWaterTruckLabel": "Containerlastbil/vattenlastbil",
  "semiTrailerLabel": "Påhängsvagn",
  "chemicalThreatLegendLabel": "Kemiskt hot",
  "lpgThreatLegendLabel": "Gasolhot",
  "smallLPGTank": "Liten gasoltank",
  "largeLPGTank": "Stor gasoltank",
  "commercialResidentialLPGTank": "Gasoltank för kommersiellt bruk eller hemmabruk",
  "smallLPGTruck": "Liten lastbil med gasol",
  "semiTankerLPG": "Påhängsvagn med gasol",
  "threatDescriptionColLabel": "Hotbeskrivning",
  "addThreatZoneButtonLabel": "Lägg till hotzon",
  "zoneDescColLabel": "Zonbeskrivning",
  "distanceLabel": "Avstånd (${unitAbbr})",
  "threatTypeHelp": "<p>Kontrollera att följande villkor är uppfyllda för en typ av hot:<br/><ul><li>Typ av hot kan inte vara tomt och det ska vara unikt</li><li>Hot ska ha minst en giltig zon</li><li>Zonbeskrivning ska vara unik för ett hot</li></ul><p/>",
  "descriptionLabel": "Beskrivning",
  "newThreatZonePopupLabel": "Ny hotzon",
  "editThreatZonePopupLabel": "Redigera hotzon",
  "uniqueZoneDescriptionMsg": "Ange en unik hotbeskrivning, det finns redan en hotbeskrivning med det här namnet.",
  "symbologyColLabel": "Symbologi",
  "zoneDescriptionColLabel": "Zonbeskrivning",
  "uniqueZoneRequiredMsg": "Zonnamnet ska vara unikt för",
  "interactive": "Interaktiv",
  "fromCoord": "Fast koordinat",
  "existingFeature": "Från befintliga geoobjekt",
  "defaultInputLocationLabel": "Standardindataplats",
  "defaultInputLayer": "Standardindatalager",
  "defaultThreatType": "Standardtyp för hot",
  "selectLabel": "Välj",
  "mandatoryLabel": "Obligatorisk evakueringsdistans",
  "safeLabel": "Säker evakueringsdistans",
  "lpgSafeDistanceLable": "Säkert avstånd",
  "fireBallDiameterLable": "Eldklotsdiameter"
});