define({
  "_widgetLabel": "Editor atribute în masă",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nume strat tematic",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Niciun strat tematic editabil configurat",
  "editorPopupTitle": "Editor atribute în masă",
  "editorPopupSaveBtn": "Salvare",
  "editorPopupMultipleValues": "",
  "clear": "Golire",
  "featuresUpdated": "${0} / ${1} obiecte spaţiale actualizate",
  "featuresSelected": "${0} obiecte spaţiale selectate",
  "featuresSkipped": "Ignorat",
  "featuresNoPermision": "${0} obiect(e) spațial(e) selectat(e), dar fără permisiune de editare.",
  "search": "Căutare",
  "queryInput": "Introduceţi o valoare care va fi interogată",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Setaţi corect filtrul.",
  "filterPopup": "Filtrare strat tematic",
  "filterAppend": "Dacă există deja un filtru în harta web pentru acest strat tematic",
  "filterAppendOR": "Anexați orice expresie filtrului de hartă existent",
  "filterAppendAND": "Anexați toate expresiile filtrului de hartă existent",
  "cancel": "Anulare",
  "noValue": "Nicio valoare",
  "emptyString": "Şir gol",
  "existingValue": "Se păstrează valoarea curentă",
  "newDate": "Dată nouă",
  "valueChooser": "Selectaţi/introduceţi o valoare",
  "ok": "OK",
  "drawBox": {
    "point": "Punct",
    "line": "Linie",
    "polyline": "Linie poligonală",
    "freehandPolyline": "Linie poligonală trasată manual",
    "extent": "Extindere",
    "polygon": "Poligon",
    "freehandPolygon": "Poligon trasat manual",
    "clear": "Golire",
    "addPointToolTip": "Faceţi clic pentru a selecta în această zonă",
    "addShapeToolTip": "Trasaţi o formă pentru a selecta obiectele spaţiale",
    "freehandToolTip": "Apăsaţi şi menţineţi apăsat pentru a trasa o formă pentru a selecta obiectele spaţiale",
    "startToolTip": "Trasaţi o formă pentru a selecta obiectele spaţiale"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Stratul tematic din ${0} a returnat un ID nevalid",
    "noSelectedLayers": "Niciun strat tematic selectat cu înregistrări de actualizat",
    "inputValueError": "Valoare nevalidă în formular",
    "saveError": "Imposibil de salvat obiectele spațiale ${0}",
    "requiredValue": "Valoare necesară"
  }
});