// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/widget-config/CustomWidgets.html":'\x3cdiv class\x3d"custom-widget-page"\x3e\r\n\t\x3cdiv data-dojo-attach-point\x3d"queryFromSection" class\x3d"hidden"\x3e\r\n\t\t\x3clabel\x3e\r\n\t\t\t\x3cinput data-dojo-attach-point\x3d"subscribedWidgets" data-dojo-type\x3d"dijit/form/RadioButton" name\x3d"widgetChoose"\r\n\t\t\t\ttype\x3d"radio" checked\x3d"true" class\x3d"jimu-radio-btn" data-dojo-attach-event\x3d"change:_onWidgetFromTypeChange"/\x3e\r\n\t\t\t${nls.subscribed}\r\n\t\t\x3c/label\x3e\r\n\t\t\x3clabel style\x3d"margin-left: 20px;"\x3e\r\n\t\t\t\x3cinput data-dojo-attach-point\x3d"providedWidgets" data-dojo-type\x3d"dijit/form/RadioButton" name\x3d"widgetChoose"\r\n\t\t\t\ttype\x3d"radio" class\x3d"jimu-radio-btn"/\x3e\r\n\t\t\t${nls.provided}\r\n\t\t\x3c/label\x3e\r\n\t\x3c/div\x3e\r\n\r\n\t\x3cdiv data-dojo-attach-point\x3d"list" class\x3d"list widget-list" data-dojo-attach-event\x3d"onclick:_onClick"\x3e\x3c/div\x3e\r\n\t\x3cdiv data-dojo-type\x3d"jimu/dijit/LoadingIndicator" data-dojo-attach-point\x3d"loading" data-dojo-props\x3d\'hidden:true\'\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./CustomWidgets.html dojo/Evented dojo/query dojo/promise/all dojo/_base/lang dojo/_base/array dojo/_base/html jimu/utils jimu/portalUrlUtils ./customWidgetUtils jimu/dijit/LoadingIndicator".split(" "),function(m,n,p,q,r,t,f,u,e,h,c,g,k,l){return m([n,p,q,t],{templateString:r,baseClass:"custom-widgets",nls:null,hidden:!1,q:null,queryFrom:null,postMixInProperties:function(){this.nls=e.mixin(this.nls,
window.jimuNls.itemSelector)},postCreate:function(){this.inherited(arguments);this.hidden?this.hide():k.isOnline(window.portalUrl)?this.queryFrom="subscribed":this.queryFrom="provided"},queryWidgets:function(b){var a=b?this._queryProvidedWidgets('title:"'+b+'"'):this._queryProvidedWidgets();return k.isOnline(window.portalUrl)?u([a,this._querySubscribedWidgets(b)]).then(function(d){return d[0].concat(d[1])}):a},_queryProvidedWidgets:function(b){this.q=b;this.clear();this.loading.show();return l.queryProvidedWidgets(b).then(e.hitch(this,
function(a){if(this.domNode)return this.loading.hide(),this._createItemsNode(a);this.loading.hide()}),e.hitch(this,function(a){console.error(a);this.domNode&&this.loading.hide()}))},_querySubscribedWidgets:function(b){this.q=b;this.clear();this.loading.show();return l.querySubscribedWidgets(b).then(e.hitch(this,function(a){if(this.domNode)return this.loading.hide(),this._createItemsNode(a);this.loading.hide()}),e.hitch(this,function(a){console.error(a);this.domNode&&this.loading.hide()}))},filterLocally:function(b){f(".widget-node",
this.domNode).forEach(e.hitch(this,function(a){b(a.item)?c.removeClass(a,"hidden"):c.addClass(a,"hidden")}))},_createItemsNode:function(b){h.forEach(b,e.hitch(this,function(a){this._createItemNode(a)}));return b},_createItemNode:function(b){var a=c.toDom('\x3cdiv class\x3d"widget-node"\x3e\x3cdiv class\x3d"box"\x3e\x3cimg class\x3d"icon"\x3e\x3ca target\x3d"_blank" class\x3d"detail-icon"\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d"box-selected"\x3e\x3c/div\x3e\x3cdiv class\x3d"label"\x3e\x3c/div\x3e\x3c/div\x3e');
a.item=b;var d=f("img",a)[0],v=g.widgetJson.getFolderUrlFromItem(b)+"images/icon.png";d.src=v;d=f(".label",a)[0];d.innerHTML=g.sanitizeHTML(b.title)||"";d.title=b.title||"";d=f(".detail-icon",a)[0];d.href=b.detailsPageUrl;d.title=this.nls.viewItemDetails||"View item details";c.place(a,this.list)},_onWidgetFromTypeChange:function(){this.providedWidgets.get("checked")?(this.queryFrom="provided",this._queryProvidedWidgets(this.q)):(this.queryFrom="subcribed",this._querySubscribedWidgets(this.q))},clear:function(){c.empty(this.list)},
_onClick:function(b){b=b.target||b.srcElement;var a=null;if(a=c.hasClass(b,"widget-node")?b:g.getAncestorDom(b,function(d){return c.hasClass(d,"widget-node")},this.list))f(".official-section .jimu-state-selected",this.widgetDomNode).removeClass("jimu-state-selected"),"addBtn"===this.fromNode.type?c.toggleClass(a,"jimu-state-selected"):(f(".jimu-state-selected",this.domNode).removeClass("jimu-state-selected"),c.addClass(a,"jimu-state-selected"))},getSelectedWidgetItems:function(){var b=f(".widget-node.jimu-state-selected",
this.domNode).filter(e.hitch(this,function(a){return!c.hasClass(a,"hidden")}));return h.map(b,e.hitch(this,function(a){return a.item}))},isVisible:function(){return!c.hasClass(this.domNode,"hidden")},show:function(){c.removeClass(this.domNode,"hidden")},hide:function(){c.addClass(this.domNode,"hidden")}})});