define({
  "serviceUrl": "Настройване на URL на услуга:",
  "minIntSpacingLabel": "Минимален размер на мрежа",
  "lineOpacityLabel": "Непрозрачност на линия",
  "labelOpacityLabel": "Непрозрачност на етикет",
  "centerLabelOpacityLabel": "Непрозрачност на етикета на центъра",
  "gridZonePlacementLabel": "Поставяне на етикет в зона на мрежа",
  "verticalLineLabels": "Етикети за вертикални линии",
  "styleHeaderLabel": "Стил",
  "indexHeaderLabel": "Компонент на мрежа",
  "colorHeaderLabel": "Цвят",
  "fontSizeHeaderLabel": "Размер на шрифт",
  "lineWidthHeaderLabel": "Ширина на линия",
  "horizontalLabel": "Хоризонтално",
  "verticalLabel": "Вертикално",
  "upperLeftLabel": "Горе вляво",
  "upperRightLabel": "Горе вдясно",
  "lowerLeftLabel": "Долу вляво",
  "lowerRightLabel": "Долу вдясно",
  "centerLabel": "Центриран",
  "errorMessage": "Страницата за конфигурация съдържа грешки. Преди да запазите, моля, поправете ги.",
  "checkBoxLabel": "Показване на мрежата, когато изпълнимият модул е затворен.",
  "checkBoxLabelDashboard": "Показване на мрежа",
  "gzd": "Обозначение на мрежовата зона (GZD)",
  "gsid": "${number}-метра обозначение на мрежовата зона (GZD)",
  "grid10k": "${number}-метра мрежови линии",
  "grid1k": "${number}-метра мрежови линии",
  "grid100m": "100-метра мрежови линии",
  "grid10m": "10-метра мрежови линии",
  "switchBasemap": "Превключване на базова карта"
});