define({
  "_widgetLabel": "Editor attributi batch",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nome layer",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Nessun layer modificabile configurato",
  "editorPopupTitle": "Editor attributi batch",
  "editorPopupSaveBtn": "Salva",
  "editorPopupMultipleValues": "",
  "clear": "Azzera",
  "featuresUpdated": "${0} / ${1} feature aggiornate",
  "featuresSelected": "${0} feature selezionate",
  "featuresSkipped": "Ignorate",
  "featuresNoPermision": "${0} feature selezionate ma nessun permesso di modifica.",
  "search": "Ricerca",
  "queryInput": "Immettere valore per l'interrogazione",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Impostare il filtro correttamente.",
  "filterPopup": "Filtra layer",
  "filterAppend": "Se esiste già un filtro nella Web Map per questo layer",
  "filterAppendOR": "Aggiungi una qualsiasi espressione al filtro della mappa esistente",
  "filterAppendAND": "Aggiungi tutte le espressioni al filtro della mappa esistente",
  "cancel": "Annulla",
  "noValue": "Nessun valore",
  "emptyString": "Stringa vuota",
  "existingValue": "Mantieni valore esistente",
  "newDate": "Nuova data",
  "valueChooser": "Selezionare/digitare un valore",
  "ok": "OK",
  "drawBox": {
    "point": "Punto",
    "line": "Linea",
    "polyline": "Polilinea",
    "freehandPolyline": "Polilinea a mano libera",
    "extent": "Estensione",
    "polygon": "Poligono",
    "freehandPolygon": "Poligono a mano libera",
    "clear": "Azzera",
    "addPointToolTip": "Fare clic per selezionare quest'area",
    "addShapeToolTip": "Disegnare una forma per selezionare le feature",
    "freehandToolTip": "Premere e tenere premuto per disegnare una forma per selezionare feature.",
    "startToolTip": "Disegnare una forma per selezionare le feature"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "La feature di ${0} ha restituito un ID non valido",
    "noSelectedLayers": "Nessun layer selezionato con record da aggiornare",
    "inputValueError": "Valore non valido nel modulo",
    "saveError": "Impossibile salvare le feature ${0}",
    "requiredValue": "Valore obbligatorio"
  }
});