define({
  "transparencyLabel": "Przezroczystość",
  "outline": "Obrys",
  "fill": "Wypełnienie (kolor zostanie zastosowany tylko wtedy, gdy wybranym stylem jest styl pełny)",
  "style": "Styl",
  "selectOpLayerLabel": "Wybierz warstwę operacyjną dla wyników",
  "selectDefaultMeasurementLabel": "Wybierz domyślną jednostkę miary",
  "helpIconTooltip": "Lista warstw operacyjnych jest zapełniana warstwami z bieżącej mapy internetowej o typie geometrii poligonowej.",
  "lineStyles": {
    "esriSLSDash": "Kreska",
    "esriSLSDashDot": "Kreska-kropka",
    "esriSLSDashDotDot": "Kreska-kropka-kropka",
    "esriSLSDot": "Kropka",
    "esriSLSLongDash": "Długa kreska",
    "esriSLSLongDashDot": "Długa kreska-kropka",
    "esriSLSNull": "Pusta wartość",
    "esriSLSShortDash": "Krótka kreska",
    "esriSLSShortDashDot": "Krótka kreska-kropka",
    "esriSLSShortDashDotDot": "Krótka kreska-kropka-kropka",
    "esriSLSShortDot": "Krótka kropka",
    "esriSLSSolid": "Stały"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Cofnij",
    "esriSFSCross": "Krzyż",
    "esriSFSDiagonalCross": "Po przekątnej",
    "esriSFSForwardDiagonal": "Dalej",
    "esriSFSHorizontal": "Poziomo",
    "esriSFSNull": "Pusta wartość",
    "esriSFSSolid": "Stały",
    "esriSFSVertical": "Pionowo"
  },
  "threatTypeLabel": "Typ zagrożenia",
  "generalLabel": "Ogólne",
  "addThreatTypesLabel": "Dodaj typ zagrożenia",
  "actions": "Akcje",
  "newThreatTypePopupLabel": "Nowy typ zagrożenia",
  "units": "Jednostki",
  "chooseDefaultThreatLabel": "Wybierz domyślny typ zagrożenia",
  "defaultThreatTypePopUpLabel": "Domyślne typy zagrożeń",
  "editThreatLabel": "Edytuj zagrożenie",
  "defaultThreatTypeIconTooltip": "Lista domyślnych typów zagrożeń",
  "uniqueThreatTypeMsg": "Wprowadź unikalny typ zagrożenia. Typ zagrożenia o tej nazwie już istnieje.",
  "requiredMsg": "To pole jest wymagane",
  "unitMeasureLabel": "Odległości są podawane w {0}",
  "chooseDefaultThreatTypeIconLabel": "Wybierz spośród domyślnych",
  "pipeBombLabel": "Bomba rurowa",
  "suicideBombLabel": "Bomba samobójcza",
  "briefcaseLabel": "Teczka",
  "carLabel": "Samochód",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Mały samochód dostawczy",
  "containerWaterTruckLabel": "Pojazd kontenerowy/cysterna",
  "semiTrailerLabel": "Naczepa",
  "chemicalThreatLegendLabel": "Zagrożenie chemiczne",
  "lpgThreatLegendLabel": "Zagrożenie LPG",
  "smallLPGTank": "Mały zbiornik LPG",
  "largeLPGTank": "Duży zbiornik LPG",
  "commercialResidentialLPGTank": "Komercyjny/przydomowy zbiornik LPG",
  "smallLPGTruck": "Mała cysterna LPG",
  "semiTankerLPG": "Naczepa z cysterną LPG",
  "threatDescriptionColLabel": "Opis zagrożenia",
  "addThreatZoneButtonLabel": "Dodaj strefę zagrożenia",
  "zoneDescColLabel": "Opis strefy",
  "distanceLabel": "Odległość (${unitAbbr})",
  "threatTypeHelp": "<p>Upewnij się, że typ zagrożenia spełnia następujące wymagania:<br/><ul><li>Typ zagrożenia nie może być pusty i powinien być unikalny</li><li>Zagrożenie powinno mieć co najmniej jedną prawidłową strefę</li><li>Opis strefy powinien być unikalny dla zagrożenia</li></ul><p/>",
  "descriptionLabel": "Opis",
  "newThreatZonePopupLabel": "Nowa strefa zagrożenia",
  "editThreatZonePopupLabel": "Edytuj strefę zagrożenia",
  "uniqueZoneDescriptionMsg": "Wprowadź unikalny opis strefy. Opis strefy o tej nazwie już istnieje.",
  "symbologyColLabel": "Symbolizacja",
  "zoneDescriptionColLabel": "Opis strefy",
  "uniqueZoneRequiredMsg": "Nazwa strefy powinna być unikalna dla",
  "interactive": "Interaktywnie",
  "fromCoord": "Stałe współrzędne",
  "existingFeature": "Od istniejących obiektów",
  "defaultInputLocationLabel": "Domyślna lokalizacja wejściowa",
  "defaultInputLayer": "Domyślna warstwa wejściowa",
  "defaultThreatType": "Domyślny typ zagrożenia",
  "selectLabel": "Wybierz",
  "mandatoryLabel": "Obowiązkowa odległość ewakuacji",
  "safeLabel": "Bezpieczna odległość ewakuacji",
  "lpgSafeDistanceLable": "Bezpieczna odległość",
  "fireBallDiameterLable": "Średnica kuli ognistej"
});