define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "Nastaviť ako vstup ",
  "requiredInfo": "je vyžadované.",
  "drawnOnMap": "Výsledok je nakreslený na mape.",
  "noToolConfig": "Nie je k dispozícii žiadna prednastavená geoprocesná úloha.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Nahrať súbor",
  "selectFileToUpload": "Vybrať súbor...",
  "rasterFormat": "Formát rastrových údajov",
  "noFileSelected": "Žiadny vybraný súbor!",
  "uploadSuccess": "Súbor sa podarilo úspešne nahrať!",
  "showLayerContent": "Zobraziť obsah vrstvy",
  "invalidUrl": "Neplatná URL adresa prvkovej služby",
  "urlPlaceholder": "URL na prístup k údajom",
  "addShapefile": "Pridať súbor Shapefile",
  "generateShapefileError": "Generovať chybu súboru Shapefile, skontrolujte prosím: ",
  "cleared": "Výsledok bol odstránený.",
  "enlargeView": "Zväčšiť zobrazenie",
  "exportOutput": "Export",
  "emptyResult": "Výsledok je prázdny.",
  "useSelectedFeatureset": "Použiť výsledné prvky.",
  "closeSelectedFeatureset": "Vymazať a použiť konfigurovanú možnosť vstupu.",
  "currentMapExtent": "Aktuálny rozsah mapy",
  "generalize": "Zovšeobecniť geometrie",
  "jsonPlaceholder": "JSON reťazec údajov",
  "chooseATable": "---Zvoliť tabuľku---"
});