define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Åpne infografikk og rapporter som oppsummerer viktige indikatorer og data for et område.</div><br><div>Velg et punkt- eller polygongeoobjekt i kartet, søk etter en adresse eller et sted, tegn en polygon eller plasser en nål på kartet for å vise nøkkelindikatorer og informasjon om området.</div>",
  "defineWhichInfographics": "Definer hvilken infografikk som er tilgjengelig i miniprogrammet:",
  "defineWhichReports": "Definer hvilke rapporter som er tilgjengelige i miniprogrammet:",
  "defaultValues": "Standardverdier:",
  "disable": "Deaktiver",
  "drawFreehandPolygon": "Tegn frihåndspolygon",
  "drawPolygon": "Tegn polygon",
  "driveTime": "Kjøretid",
  "dropPin": "Fest nål",
  "dynamicHTML": "Dynamisk HTML",
  "exportOptions": "Eksporter alternativer:",
  "home": "Hjem",
  "image": "Bilde",
  "infographics": "Infografikk",
  "invalidValueRing": "Verdiene må være fra 0 til 1000.",
  "invalidValueDTWT": "Verdiene må være fra 0 til 300.",
  "km": "km",
  "makeDefault": "Angi som standard",
  "miles": "miles",
  "minutes": "minutter",
  "options": "Alternativer:",
  "pdf": "PDF",
  "print": "Skriv ut",
  "radius": "Radius",
  "removeDefault": "Fjern standard",
  "reports": "Rapporter",
  "rings": "Ringer",
  "searchTextBox": "Søketekstboks",
  "selectCountryOrRegion": "Velg land eller region:",
  "thisEntryIsNotValid": "Denne oppføringen er ikke gyldig.",
  "time": "Tid",
  "walkTime": "Gåtid"
});