define({
  "taskUrl": "URL адрес на задача",
  "serviceURLPlaceholder": "Моля, въведете URL адрес на задача за геообработка.",
  "layerOrder": "Ред на слой",
  "defaultValue": "Стойност по подразбиране",
  "inputFeatureBy": "Входни данни по",
  "inputRecordBy": "Входен запис по",
  "renderer": "Генериране на цифрово изображение",
  "displayType": "Показан тип",
  "helpUrl": "URL адрес за помощ",
  "useResultMapService": "Изглед на резултата с услуга за карта",
  "drawOnMap": "Интерактивно изчертаване на картата",
  "selectLayer": "Изберете слой от картата.",
  "selectTable": "Изберете таблица от картата.",
  "shareResults": "Добавяне на резултат като оперативен слой",
  "setTask": "Настройване",
  "setTaskTitle": "Задаване на GP задача",
  "enablePopup": "Активиране на изскачащи прозорци",
  "unSupportGeometryType": "Не може да се зададе генериране на цифрово изображение на непознат тип геометрия.",
  "useUrlForGPInput": "URL адрес",
  "useUploadForGPInput": "Качване на файл",
  "selectFileToUpload": "Избор на файл...",
  "rasterFormat": "Растерен формат на данни",
  "noFileSelected": "Няма избран файл!",
  "uploadSuccess": "Качването на файла е успешно!",
  "showLayerContent": "Показване на съдържание на слой",
  "urlPlaceholder": "URL адрес за достъп до данните",
  "useShapefile": "Употреба на шейп файл в локална файлова система",
  "allowToExport": "Разрешаване на експортиране на резултати",
  "useDynamicSchema": "Резултатът може да има различна схема, вместо предварително избрана схема, използвайте динамична схема.",
  "useCurrentMapExtent": "Употреба на текущ ограничаващ правоъгълник на карта",
  "ignoreOutput": "Пренебрегване на този резултат",
  "turnOffOutput": "Изключване на този слой по подразбиране",
  "inputJSONString": "Входни данни от текстов тип JSON",
  "useFeatureCollection": "Не изпращайте URL, а FeatureCollections като входни данни."
});