define({
  "locatorUrl": "Paikantimen URL-osoite",
  "set": "Aseta",
  "locatorName": "Paikantimen nimi",
  "locatorExample": "Esimerkki",
  "countryCode": "Maa- tai aluekoodit",
  "eg": "esim. ",
  "countryCodeHint": "Jos jätät tämän arvon tyhjäksi, ohjelma etsii kaikista maista ja kaikilta alueilta",
  "minCandidateScore": "Pienin ehdokastulos",
  "minCandidateScoreHint": "Jos jätät tämän arvon tyhjäksi, ohjelma käyttää pienimmän ehdokastuloksen arvoa 90",
  "enableSingleField": "Yhden kentän asetukset",
  "singleFieldHint": "Osoitetiedot ovat yhdessä kentässä",
  "enableMultiField": "Usean kentän asetukset",
  "multiFieldHint": "Osoitetiedot ovat useassa kentässä",
  "enableXYField": "XY-kentän asetukset",
  "xyFieldHint": "Aineisto sisältää X-/Y-koordinaattiarvot",
  "instructionGeocode": "Lisää ja määritä paikannuspalvelut.",
  "invalidUrlTip": "Syötetty URL-osoite ${URL} on virheellinen, tai se ei ole käytettävissä.",
  "geocodeTabLabel": "Sijaintiasetukset",
  "lookupList": "Tunnistettavat kenttien nimet",
  "isRecognized": "Alla olevan taulukon kenttien nimet tunnistetaan automaattisesti tämän kentän osalta",
  "needsEditablePointLayers": "Web-kartassa on oltava vähintään yksi muokattava pistekarttataso.",
  "editpageAlias": "Alias",
  "configureFields": "Määritä karttatason kentät",
  "configureSingleFields": "Määritä yksi osoitekenttä",
  "configureMultiFields": "Määritä useita osoitekenttiä",
  "configureXYFields": "Määritä X/Y-kentät",
  "noFields": "Määritä vähintään yksi näytettävä kenttä muokkaustoiminnon avulla",
  "display": "Näytä",
  "duplicate": "Etsi kopio",
  "duplicateTip": "Etsi tästä kentästä identtisiä arvoja lähdetiedoston ja kohdekarttatason väliltä./n Kun identtinen vastine löytyy, tiedoston tietuetta ei paikanneta ja se merkitään kopioksi.",
  "noSelectField": "Valitse ensin Kohdekarttataso-vaihtoehto",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (pituusaste)",
  "xyFieldsLabelY": "Y (leveysaste)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Itäinen",
  "northing": "Pohjois",
  "lon": "PIT",
  "lat": "LEV",
  "layerOptionHint": "Valitse karttataso, johon aineisto lähetetään.",
  "layerFieldTitle": "Kohdekarttataso",
  "tempSymbolHint": "Valitse symboli, jota käytetään kohteiden näyttämiseen.",
  "tempSymbolTitle": "Näytettävä symboli",
  "maxRecords": "Tietueiden enimmäismäärä",
  "maxRecordsHint": "Paikannettavien tietueiden enimmäismäärä",
  "searchRadius": "Etsintäsäde",
  "searchRadiusHint": "Etäisyys, jolta karttatason kohteiden kaksoiskappaleita etsitään",
  "requiresInteger": "Anna numeroarvo.",
  "requiresInteger0100": "Anna numeroarvo väliltä 0–100",
  "requiresLocator": "Lisää vähintään yksi kelvollinen paikannin.",
  "layerFields": "Karttatason asetukset",
  "layerFieldsHint": "Määritä kohdekarttatason kentät, jotka täsmäytetään lähtöaineiston kenttien kanssa.",
  "locatorError": "Paikannin on virheellinen, tai se ei ole käytettävissä.",
  "optionNotMatch": "Kenttäasetukset eivät ole yhtenäiset paikantimien välillä. Vikasieto ei ehkä toimi odotetulla tavalla.",
  "targetLayerTabTitle": "Kohdekarttataso",
  "locationSettingsTabTitle": "Sijaintiasetukset",
  "generalSettingsTabTitle": "Yleiset asetukset",
  "addTargetLayersLabel": "Lisää kohdekarttataso",
  "introductoryText": "Luo ohjesisältöä pienoisohjelmaa varten",
  "defaultStartPageInstructions": "Tämä pienoisohjelma avustaa aineiston käsittelyssä ja lähettämisessä tiedostosta valittuun kartan karttatasoon.<br/> <br/> Tiedoston arvojen on oltava eroteltu pilkuin, sarkaimin, puolipistein tai pystyviivoin.",
  "noTargetLayerConfiguredErrorMsg": "Yhtään kohdekarttatasoa ei ole määritetty",
  "noFieldsForTargetLayer": "Karttatason asetuksia ei ole määritetty kohdekarttatasolle",
  "locationSettingsNotConfigured": "Sijaintiasetuksia ei ole määritetty oikein",
  "questionMark": "tulisi käyttää?"
});