define({
  "_widgetLabel": "Пакетний редактор атрибутів",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Назва шару",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Редаговані шари не налаштовано",
  "editorPopupTitle": "Пакетний редактор атрибутів",
  "editorPopupSaveBtn": "Зберегти",
  "editorPopupMultipleValues": "",
  "clear": "Очистити",
  "featuresUpdated": "${0} / ${1} об'єкт(-ів) оновлено",
  "featuresSelected": "${0} об'єкт(-ів) вибрано",
  "featuresSkipped": "Обійдені",
  "featuresNoPermision": "${0} об'єкт(-ів) вибрано, але немає дозволу на редагування.",
  "search": "Пошук",
  "queryInput": "Введіть значення для запиту",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Правильно задайте фільтр.",
  "filterPopup": "Фільтрувати шар",
  "filterAppend": "Якщо фільтр вже існує у веб-карті для цього шару",
  "filterAppendOR": "Приєднати будь-який вираз до існуючого фільтру карти",
  "filterAppendAND": "Приєднати всі вирази до існуючого фільтру карти",
  "cancel": "Скасувати",
  "noValue": "Немає значення",
  "emptyString": "Порожній рядок",
  "existingValue": "Зберігати існуюче значення",
  "newDate": "Нова дата",
  "valueChooser": "Вибрати/ввести значення",
  "ok": "OK",
  "drawBox": {
    "point": "Точка",
    "line": "Лінія",
    "polyline": "Полілінія",
    "freehandPolyline": "Довільна полілінія",
    "extent": "Екстент",
    "polygon": "Полігон",
    "freehandPolygon": "Довільний полігон",
    "clear": "Очистити",
    "addPointToolTip": "Клацніть для вибору у цій області",
    "addShapeToolTip": "Намалювати форму для вибору об'єктів",
    "freehandToolTip": "Натиснути та утримувати для малювання форми для вибору об'єктів",
    "startToolTip": "Намалювати форму для вибору об'єктів"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Об’єкт від ${0} повернув недійсний ідентифікатор",
    "noSelectedLayers": "Немає вибраних шарів з записами для оновлення",
    "inputValueError": "Недійсне значення у формі",
    "saveError": "Не вдалося зберегти ${0} об'єкти (-ів)",
    "requiredValue": "Потрібне значення"
  }
});