define({
  "_widgetLabel": "Ανάλυση απειλής",
  "threatAnalysisMainPageTitle": "Με βάση τον Οδηγό καταπολέμησης της τρομοκρατίας της JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Καταχώριση τοποθεσίας",
  "interactive": "Διαδραστικά",
  "fromCoord": "Σταθερή συντεταγμένη",
  "existingFeature": "Από υπάρχοντα στοιχεία",
  "threatAnalysisCoordInputLabel": "Τοποθεσία απειλής",
  "enterCoords": "Εισαγάγετε συντεταγμένες",
  "threatAddPointToolTip": "Προσθήκη τοποθεσίας απειλής",
  "threatDrawPointToolTip": "Κάντε κλικ για να προσθέσετε τοποθεσία απειλής.",
  "threatType": "Τύπος απειλής",
  "threatPlaceholder": "Αρχίστε να πληκτρολογείτε ώστε να εκτελεστεί αναζήτηση για μια απειλή.",
  "zoneTypeLabel": "Τύπος ζώνης",
  "feetLabel": "Πόδια",
  "metersLabel": "Μέτρα",
  "unitsLabel": "Μονάδες",
  "threatGraphicLayer": "Γραφικό απειλών",
  "style": "Στιλ",
  "settingsTitle": "Ρυθμίσεις",
  "colorPicker": "εργαλείο επιλογής χρώματος",
  "lineStyles": {
    "esriSLSDash": "Παύλα",
    "esriSLSDashDot": "Παύλα τελεία",
    "esriSLSDashDotDot": "Παύλα τελεία τελεία",
    "esriSLSDot": "Τελεία",
    "esriSLSLongDash": "Μεγάλη παύλα",
    "esriSLSLongDashDot": "Μεγάλη παύλα τελεία",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Μικρή παύλα",
    "esriSLSShortDashDot": "Μικρή παύλα τελεία",
    "esriSLSShortDashDotDot": "Μικρή παύλα τελεία τελεία",
    "esriSLSShortDot": "Μικρή τελεία",
    "esriSLSSolid": "Συμπαγές"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Προς τα πίσω",
    "esriSFSCross": "Σταυρός",
    "esriSFSDiagonalCross": "Διαγώνια",
    "esriSFSForwardDiagonal": "Προώθηση",
    "esriSFSHorizontal": "Οριζόντια",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Συμπαγές",
    "esriSFSVertical": "Κατακόρυφα"
  },
  "resultsTitle": "Αποτελέσματα",
  "publishTABtn": "Δημοσίευση",
  "layerName": "Όνομα δημοσιευμένου θεματικού επιπέδου",
  "invalidLayerName": "Το όνομα του θεματικού επιπέδου πρέπει να περιέχει μόνο αλφαριθμικούς χαρακτήρες και κάτω παύλες.",
  "missingLayerNameMessage": "Πρέπει να καταχωρίσετε έγκυρο όνομα θεματικού επιπέδου για να μπορέσετε να προχωρήσετε στη δημοσίευση.",
  "publishingFailedLayerExists": "Ανεπιτυχής δημοσίευση: Ήδη έχετε feature service με το όνομα {0}. Επιλέξτε κάποιο άλλο όνομα θεματικού επιπέδου.",
  "checkService": "Έλεγχος υπηρεσίας: {0}",
  "createService": "Δημιουργία υπηρεσίας: {0}",
  "unableToCreate": "Δεν είναι δυνατή η δημιουργία: {0}",
  "addToDefinition": "Προσθήκη στον ορισμό: {0}",
  "successfullyPublished": "Επιτυχής δημοσίευση του θεματικού επιπέδου web",
  "successfullyAppended": "Επιτυχής προσάρτηση νέων στοιχείων στο θεματικό επίπεδο web",
  "manageWebLayerText": "Διαχείριση του θεματικού επιπέδου web",
  "userRole": "Δεν είναι δυνατή η δημιουργία υπηρεσίας επειδή ο χρήστης δεν έχει τα ανάλογα δικαιώματα.",
  "retrieveExistingLayerError": "Δεν είναι δυνατή η ανάκτηση του {0}. Προχωρήστε στη δημοσίευση χρησιμοποιώντας κάποιο άλλο όνομα θεματικού επιπέδου.",
  "publishToNewLayer": "Δημοσίευση αποτελεσμάτων σε νέο feature layer",
  "layerNameExists": "Αυτό το όνομα θεματικού επιπέδου ήδη υπάρχει. Χρησιμοποιήστε διαφορετικό όνομα θεματικού επιπέδου.",
  "pipeBombLabel": "Βόμβα σε μεταλλικό σωλήνα",
  "suicideBombLabel": "Βόμβα αυτοκτονίας",
  "briefcaseLabel": "Χαρτοφύλακας",
  "carLabel": "Αυτοκίνητο",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Φορτηγάκι παραδόσεων",
  "containerWaterTruckLabel": "Φορτηγό με κοντέινερ/Υδροφόρα",
  "semiTrailerLabel": "Ημιρυμουλκούμενο φορτηγό",
  "transparencyLabel": "Διαφάνεια",
  "outline": "Περίγραμμα",
  "fill": "Γέμισμα (Το χρώμα εφαρμόζεται μόνο όταν έχετε καθορίσει τη χρήση του συμπαγούς στιλ.)",
  "createBtn": "Δημιουργία ζωνών",
  "clearBtn": "Εκκαθάριση",
  "invalidNumberMessage": "Η τιμή που καταχωρίσατε δεν είναι έγκυρη.",
  "invalidRangeMessage": "Η τιμή πρέπει να είναι μεγαλύτερη από το 0.",
  "parseCoordinatesError": "Δεν είναι δυνατή η ανάλυση των συντεταγμένων. Ελέγξτε τα στοιχεία που καταχωρίσατε.",
  "selectDrawModeLabel": "Επιλογή λειτουργίας σχεδίασης",
  "selectFeatureLabel": "Επιλογή στοιχείου από αυτό το θεματικό επίπεδο",
  "smallLPGTank": "Μικρή δεξαμενή LPG",
  "largeLPGTank": "Μεγάλη δεξαμενή LPG",
  "commercialResidentialLPGTank": "Εμπορική/Οικιακή δεξαμενή LPG",
  "smallLPGTruck": "Μικρό φορτηγό LPG",
  "semiTankerLPG": "Ημιβυτιοφόρο LPG",
  "zoneDescriptionColLabel": "Περιγραφή ζώνης",
  "distanceColLabel": "Απόσταση",
  "zoneDescColLabel": "Περιγραφή ζώνης",
  "descriptionLabel": "Περιγραφή",
  "editThreatZonePopupLabel": "Επεξεργασία συμβολολογίας ζώνης απειλής",
  "symbologyColLabel": "Συμβολισμός",
  "actions": "Ενέργειες",
  "threatTypeSelectLabel": "Επιλογή τύπου απειλής:",
  "distanceLabel": "Απόσταση (${unitAbbr})",
  "layerCountHint": "Υπόδειξη: Θα δημοσιευτεί ένα θεματικό επίπεδο web με ${layerCount} θεματικά επίπεδα στοιχείων",
  "selectLabel": "Επιλογή",
  "mandatoryLabel": "Υποχρεωτική απόσταση εκκένωσης",
  "safeLabel": "Ασφαλής απόσταση εκκένωσης",
  "fireBallDiameterLable": "Διάμετρος fireball",
  "lpgSafeDistanceLable": "Ασφαλής απόσταση"
});