define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Greifen Sie auf Infografiken und Berichte zu, die eine Zusammenfassung wichtiger Indikatoren und Daten für die einzelnen Bereiche enthalten.</div><br><div>Wählen Sie einen Punkt oder ein Polygon auf der Karte aus, suchen Sie nach einer Adresse oder einem Ort, zeichnen Sie ein Polygon, oder fügen Sie einen Pin auf der Karte ein, um wichtige Indikatoren und Informationen zu diesem Bereich anzuzeigen.</div>",
  "defineWhichInfographics": "Definieren Sie, welche Infografiken im Widget verfügbar sein sollen:",
  "defineWhichReports": "Definieren Sie, welche Berichte im Widget verfügbar sein sollen:",
  "defaultValues": "Standardwerte:",
  "disable": "Deaktivieren",
  "drawFreehandPolygon": "Freihandpolygon zeichnen",
  "drawPolygon": "Polygon zeichnen",
  "driveTime": "Fahrzeit",
  "dropPin": "Pin hinzufügen",
  "dynamicHTML": "Dynamisches HTML",
  "exportOptions": "Exportoptionen:",
  "home": "Startseite",
  "image": "Bild",
  "infographics": "Infografiken",
  "invalidValueRing": "Die Werte müssen im Bereich von 0 bis 1.000 liegen.",
  "invalidValueDTWT": "Die Werte müssen im Bereich von 0 bis 300 liegen.",
  "km": "km",
  "makeDefault": "Als Standard definieren",
  "miles": "Meilen",
  "minutes": "Minuten",
  "options": "Optionen:",
  "pdf": "PDF",
  "print": "Drucken",
  "radius": "Radius",
  "removeDefault": "Standardeinstellung entfernen",
  "reports": "Berichte",
  "rings": "Ringe",
  "searchTextBox": "Textfeld \"Suchen\"",
  "selectCountryOrRegion": "Land oder Region auswählen:",
  "thisEntryIsNotValid": "Dieser Eintrag ist ungültig.",
  "time": "Zeit",
  "walkTime": "Gehzeit"
});