define({
  "layersPage": {
    "allLayers": "Vsi sloji",
    "title": "Izberite predlogo za ustvarjanje geoobjektov ali kliknite geoobjekt na karti, da ga uredite",
    "generalSettings": "Splošne nastavitve",
    "layerSettings": "Nastavitve sloja",
    "webmapSettingsRadioBtnLabel": "Upoštevajte nastavitve spletne karte",
    "customSettingsRadioBtnLabel": "Nastavitve po meri",
    "smartActionsTabTitle": "Pametna dejanja",
    "attributeActionsTabTitle": "Dejanja atributov",
    "geocoderSettingsText": "Nastavitve geokodirnika",
    "editDescription": "Zagotovite besedila za prikaz pri plošči za urejanje",
    "editDescriptionTip": "To besedilo je prikazano nad izbirnikom predlog. Če ne želite prikaza, polje pustite prazno.",
    "promptOnSave": "Poziv k shranjevanju neshranjenih urejanj ob zapiranju obrazca ali preklapljanja na naslednji zapis",
    "promptOnSaveTip": "Prikaži poziv, kadar ima trenutni geoobjekt neshranjena urejanja. (Pri kopiranju več geoobjektov pride do samodejnega shranjevanja.)",
    "promptOnDelete": "Pri brisanju zapisa zahtevaj potrditev",
    "promptOnDeleteTip": "Prikaži poziv za potrditev dejanja, ko uporabnik klikne izbriši.",
    "removeOnSave": "Pri shranjevanju odstrani geoobjekt iz izbire.",
    "removeOnSaveTip": "Možnost, da odstranite geoobjekt iz nabora izbire, ko je zapis shranjen. Če obstaja samo izbrani zapis, se bo plošča preklopila nazaj na stran predlog.",
    "useFilterEditor": "Uporabite filter predlog geoobjektov",
    "useFilterEditorTip": "Možnost uporabe filtra izbirnika predlog, ki ponuja možnost ogleda predloge enega sloja ali iskanje predlog po imenu.",
    "groupFilteredTemplates": "Rezultati skupinskega iskanja",
    "groupFilteredTemplatesTip": "Možnost za skupinsko iskanje po sloju.",
    "displayShapeSelector": "Pokaži možnosti risanja",
    "createNewFeaturesFromExisting": "Dovolite ustvarjanje novih geoobjektov iz obstoječih geoobjektov",
    "createNewFeaturesFromExistingTip": "Možnost, ki uporabniku dovoljuje, da kopira obstoječi geoobjekt, da ustvari nove geoobjekte",
    "copiedFeaturesOverrideDefaults": "Vrednosti kopiranih geoobjektov bodo preglasile privzete vrednosti ciljnih polj",
    "copiedFeaturesOverrideDefaultsTip": "Vrednosti kopiranih geoobjektov bodo preglasile privzete vrednosti predlog samo za polja, ki se ujemajo.",
    "displayShapeSelectorTip": "Možnost, ki pokaže seznam veljavnih možnosti risanja za izbrano predlogo.",
    "displayPresetTop": "Prikaži na vrhu seznam prednastavljenih vrednosti",
    "displayPresetTopTip": "Možnost, ki pokaže seznam prednastavljenih vrednosti nad izbirnikom predloge.",
    "listenToGroupFilter": "V prednastavljenih poljih uporabi filtrirane vrednosti iz pripomočka skupinskega filtra",
    "listenToGroupFilterTip": "Ko je filter uporabljen v pripomočku skupinskega filtra, uporabite vrednost na ustreznem polju na seznamu prednastavljenih vrednosti.",
    "keepTemplateActive": "Ohrani izbrano predlogo aktivno",
    "editLayerAddedFromAddData": "Omogočite urejanje slojev, dodanih iz pripomočka Dodaj podatke",
    "editLayerAddedFromAddDataTip": "Sloje, ki jih je mogoče urejati, dodane iz aplikacije z uporabo pripomočka Dodaj podatke, je mogoče urejati",
    "keepTemplateActiveTip": "Ko je prikazan izbirnik predloge in če je bila predloga že izbrana, jo ponovno izberite.",
    "geometryEditDefault": "Privzeto omogočite urejanje geometrije.",
    "autoSaveEdits": "Samodejno shrani nove geoobjekte",
    "enableAttributeUpdates": "Prikaži gumb za posodobitev Dejanj atributov",
    "enableAutomaticAttributeUpdates": "Samodejno pokliči dejanja atributov po posodobitvi geometrije",
    "enableLockingMapNavigation": "Omogoči zaklepanje navigacije po karti",
    "enableMovingSelectedFeatureToGPS": "Omogoči premik izbranega točkovnega geoobjekta na lokacijo GPS",
    "enableMovingSelectedFeatureToXY": "Omogoči premik izbranega točkovnega geoobjekta na lokacijo XY",
    "featureTemplateLegendLabel": "Nastavitve predloge geoobjekta in vrednosti filtra",
    "saveSettingsLegendLabel": "Shrani nastavitve",
    "geometrySettingsLegendLabel": "Nastavitve geometrije",
    "actionsSettingsLegendLabel": "Nastavitve za dejanja",
    "buttonPositionsLabel": "Položaj gumbov Shrani, Izbriši, Nazaj in Zapri",
    "belowEditLabel": "Pod obrazcem za urejanje",
    "aboveEditLabel": "Nad obrazcem za urejanje",
    "switchToMultilineInput": "Preklopi na mnogolinijski vnos, ko dolžina polja preseže",
    "enableValuePicker": "Omogoči izbirnik vrednosti preseka",
    "enableValuePickerHint": "Prikaži poziv, kadar je na voljo več vrednosti za polje z dejanjem atributa preseka",
    "expandRelatedTable": "Razširi vse sorodne tabele/sloje pri nalaganju",
    "expandMainTable": "Razširi vse nadrejene sloje pri nalaganju",
    "copyAndAppendFeatureLabel": "Kopirajte in dodajte geoobjekte",
    "allowCopyPolygonLabel": "Dovolite kopiranje poligona na točko",
    "allowCopyPolygonTooltip": "Možnost, ki dovoljuje kopiranje poligonskih geoobjektov v točkovni cilj predlog geoobjekta s transformacijami geometrije",
    "allowCopyLineLabel": "Dovolite kopiranje linije na točko",
    "allowCopyLineTooltip": "Možnost, ki dovoljuje kopiranje linijskih geoobjektov v točkovni cilj predlog geoobjekta s transformacijami geometrije",
    "pointAtStartLabel": "Točka na začetku",
    "pointAtStartTooltip": "Dodajte točko na začetku linije, ki jo kopirate",
    "pointAtEndLabel": "Točka na koncu",
    "pointAtEndTooltip": "Dodajte točko na koncu linije, ki jo kopirate",
    "layerSettingsTable": {
      "allowDelete": "Brisanje",
      "allowDeleteTip": "Dovoli brisanje – privzeta je možnost, ki uporabnikom dovoljuje brisanje geoobjektov. V primeru, da sloj ne podpira brisanja, je onemogočena.",
      "edit": "Uredljiv",
      "editTip": "Uredljivo – možnost, da se v pripomoček vključi sloj.",
      "label": "Sloj",
      "labelTip": "Sloj – ime sloja, kot je določeno na karti.",
      "update": "Onemogoči urejanje",
      "updateTip": "Onemogoči urejanje geometrije– možnost, da se onemogoči sposobnost premikanja že postavljene geometrije ali premikanje geometrije na obstoječem geoobjektu",
      "allowUpdateOnly": "Posodobi",
      "allowUpdateOnlyTip": "Samo posodobi – privzeta je možnost, ki dovoljuje spremembe le na obstoječih geoobjektih. V primeru, da sloj ne podpira ustvarjanja novih geoobjektov, je onemogočena.",
      "fieldsTip": "Spremenite polja, da jih bo mogoče urejati, in določite pametne atribute",
      "actionsTip": "Dejanja – možnost za urejanje polj ali dostopanje do relacijskih slojev/tabel",
      "description": "Opis",
      "descriptionTip": "Opis – možnost vnosa besedila za prikaz na vrhu strani z atributi.",
      "relationTip": "Ogled relacijskih slojev in tabel"
    },
    "editFieldError": "Spremembe polja in pametni atributi niso na voljo za neuredljive sloje.",
    "noConfigedLayersError": "Pametni urejevalnik zahteva enega ali več uredljivih slojev",
    "toleranceErrorMsg": "Neveljavna privzeta vrednost tolerance preseka",
    "pixelsToleranecErrorMsg": "Neveljavna privzeta vrednost tolerance pikslov",
    "invalidMaxCharacterErrorMsg": "Neveljavna vrednost za preklop na večvrstični vnos",
    "featuresSelectionTolerance": "Nastavite toleranco za izbiro geoobjekta (piksli)",
    "featuresSelectionToleranceTooltip": "Uporabnikom omogoči, da s klikom na geoobjekt enostavno odprejo ploščo za urejanje atributa",
    "featuresSelectionToleranceErrorMsg": "Neveljavna vrednost tolerance izbire geoobjekta",
    "autoSaveAttrUpdates": "Samodejno shranite atribute in posodobitve geometrije",
    "defaultCoordinateSystem": "Privzeti referenčni sistem",
    "defaultCoordinateSystemTooltip": "Nastavite privzeti referenčni sistem ob premiku izbranega točkovnega geoobjekta na novo lokacijo."
  },
  "editDescriptionPage": {
    "title": "Določite besedilo pregleda atributov za <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Konfigurirajte polja za <b>${layername}</b>",
    "copyActionTip": "Dejanja atributov",
    "editActionTip": "Pametna dejanja",
    "description": "Uporabite gumb Urejanje dejanj, da aktivirate pametne atribute na sloju. Pametni atributi lahko zahtevajo, skrijejo ali onemogočijo polje glede na vrednost v drugih poljih. Uporabite gumb Kopiranje dejanj, da aktivirate in določite vir vrednosti polja po preseku, polju, koordinatah in prednastavitvi.",
    "fieldsNotes": "* je obvezno polje. Če odkljukate Prikaži za to polje, se vrednost tega polja v predlogi za urejanje ne izpolni. Novega zapisa tako ne boste mogli shraniti.",
    "smartAttachmentText": "Konfiguriraj pametna dejanja za priloge",
    "smartAttachmentPopupTitle": "Konfiguriraj pametna dejanja za priloge v <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Izberite vsaj eno prikazno polje za sloj ${layerName}",
    "fieldsSettingsTable": {
      "display": "Prikaz",
      "displayTip": "Prikaz – določite, če polje ni vidno.",
      "edit": "Uredljiv",
      "editTip": "Uredljivo – preverite, ali je polje prisotno v obrazcu z atributi.",
      "fieldName": "Ime",
      "fieldNameTip": "Ime – ime polja, kot je določeno v zbirki podatkov",
      "fieldAlias": "Vzdevek",
      "fieldAliasTip": "Vzdevek – ime polja, kot je določeno na karti",
      "canPresetValue": "Prednastavi",
      "canPresetValueTip": "Prednastavitev – možnost, da prikažete polje na seznamu predhodno nastavljenih polj in dovolite uporabnikom, da pred urejanjem nastavijo vrednost.",
      "actions": "Dejanja",
      "actionsTip": "Dejanja – spremenite vrsti red polj ali nastavite pametne atribute."
    },
    "smartAttSupport": "Pametni atributi niso podprti v zahtevanih poljih zbirke podatkov"
  },
  "actionPage": {
    "title": "Konfigurirajte dejanja atributov za <b>${fieldname}</b>",
    "smartActionTitle": "Konfiguriraj pametna dejanja za <b>${fieldname}</b>",
    "description": "Dejanja so vedno izklopljena, razen če navedete kriterije, ki jih bodo sprožila. Dejanja se obdelujejo po vrstnem redu in za vsako polje bo sproženo eno dejanje. Uporabite gumb Urejanje kriterijev, da jih določite.",
    "copyAttributesNote": "Onemogočenje katerega koli dejanja z imenom skupine bo enako kot neodvisno urejanje tega dejanja. Prav tako bo odstranjeno dejanje za to polje iz zadevne skupine.",
    "searchPlaceHolder": "Išči",
    "expandAllLabel": "Razširi vse sloje",
    "selectAllLabel": "Izberite vsa polja",
    "domainListTitle": "Polja domene",
    "noValidFieldTypeMsg": "Za to vrsto podatkov ni na voljo nobenega primernega sloja na karti",
    "actionsSettingsTable": {
      "rule": "Dejanje",
      "ruleTip": "Dejanje – izvedeno dejanje, ko je kriterij izpolnjen",
      "expression": "Izraz",
      "expressionTip": "Izraz – nastali izraz v obliki zapisa SQL iz določenih kriterijev",
      "groupName": "Ime skupine",
      "groupNameTip": "Ime skupine – prikaže ime skupine, iz katere se uporablja izraz.",
      "actions": "Kriterij",
      "actionsTip": "Kriterij – spremeni vrstni red pravil in določi sprožitvene kriterije"
    },
    "copyAction": {
      "description": "Vir vrednosti polja je obdelan, če bi bil aktiviran, dokler veljavni kriteriji ne bi bili sproženi ali obdelan celoten seznam. Uporabite gumb Urejanje kriterijev, da določite kriterije.",
      "intersection": "Presek",
      "coordinates": "Koordinate",
      "address": "Naslov",
      "preset": "Prednastavljeno",
      "actionText": "Dejanja",
      "criteriaText": "Kriterij",
      "enableText": "Omogočeno"
    },
    "actions": {
      "hide": "Skrij",
      "required": "Zahtevano",
      "disabled": "Onemogočeno"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Opozorilo – neodvisno urejanje odstrani dejanje izbranega atributa, povezanega za to polje iz te skupine.",
      "editGroupHint": "Opozorilo – neodvisno urejanje odstrani dejanje izbranega pametnega dejanja, povezanega za to polje iz te skupine.",
      "popupTitle": "Izberi možnost urejanja",
      "editAttributeGroup": "Izbrano dejanje atributa ni določeno iz skupine. Izberite eno izmed naslednjih možnosti za urejanje dejanja atributa:",
      "expression": "Izraz izbranega pametnega dejanja je opredeljen iz skupine. Izberite eno izmed naslednjih možnosti za urejanje izraza pametnega dejanja:",
      "editGroupButton": "Uredi skupino",
      "editIndependentlyButton": "Uredi neodvisno"
    }
  },
  "filterPage": {
    "submitHidden": "Pošljite atributne podatke za polja tudi, ko so skrita",
    "title": "Konfiguriraj izraz za pravilo ${action}",
    "filterBuilder": "Nastavi dejanje za polje, ko se zapisi ujemajo z ${any_or_all} naslednjimi izrazi",
    "noFilterTip": "Z uporabo zgornjih orodij opredelite izjavo za aktivnost dejanja."
  },
  "geocoderPage": {
    "setGeocoderURL": "Nastavi URL geokodirnika",
    "hintMsg": "Opomba: Spreminjate storitev geokodirnika, zagotovite, da boste posodobili katere koli preslikave polja geokodirnika, ki ste jih konfigurirali.",
    "invalidUrlTip": "URL ${URL} je neveljaven ali nedostopen."
  },
  "addressPage": {
    "popupTitle": "Naslov",
    "checkboxLabel": "Pridobi vrednosti iz geokodirnika",
    "selectFieldTitle": "Atribut",
    "geocoderHint": "Za spremembo geokodirnika pojdite na gumb »Nastavitve geokodirnika« v splošnih nastavitvah",
    "prevConfigruedFieldChangedMsg": "Predhodno konfiguriran atribut ni najden v trenutnih nastavitvah geokodirnika. Atribut je bil ponastavljen na privzeto.",
    "questionMark": "?",
    "consumesCredits": "To orodje porablja kredite, če uporabljate geokodirno storitev ArcGIS Online."
  },
  "coordinatesPage": {
    "popupTitle": "Koordinate",
    "checkboxLabel": "Pridobi koordinate",
    "coordinatesSelectTitle": "Referenčni sistem",
    "coordinatesAttributeTitle": "Atribut",
    "mapSpatialReferenceOptionLabel": "Določi koordinatni sistem",
    "latLongOptionLabel": "Geografska širina/Geografska dolžina",
    "MGRS": "Vojaški mrežni referenčni sistem (MGRS)",
    "allGroupsCreatedMsg": "Vse možne skupine so že ustvarjene.",
    "coordinatesSourceTitle": "Vir koordinat",
    "featureLocation": "Lokacija geoobjekta",
    "myLocation": "Moja lokacija",
    "LatLong": {
      "y": "Geografska širina",
      "x": "Geografska dolžina",
      "xy": "Geografska dolžina, geografska širina",
      "yx": "Geografska širina, geografska dolžina"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Prednastavljeno",
    "checkboxLabel": "Polje bo prednastavljeno",
    "showOnlyDomainFields": "Prikaži samo polja domene",
    "hideInPresetDisplay": "Skrij v prikazu prednastavljene vrednosti",
    "presetValueLabel": "Trenutna prednastavljena vrednost je:",
    "changePresetValueHint": "Če želite spremeniti to prednastavljeno vrednost, pojdite na gumb »Določi prednastavljene vrednosti« v splošnih nastavitvah"
  },
  "intersectionPage": {
    "groupNameLabel": "Ime skupine",
    "dataTypeLabel": "Tip podatkov",
    "ignoreLayerRankingCheckboxLabel": "Prezri razvrstitev sloja in poišči najbližji geoobjekt v vseh določenih slojih",
    "intersectingLayersLabel": "Sloji za razširitev vrednosti",
    "layerAndFieldsApplyLabel": "sloji in polja za uporabo razširjene vrednosti",
    "checkboxLabel": "Pridobi vrednosti iz polja presečnega sloja",
    "layerText": "Sloji",
    "fieldText": "Polja",
    "actionsText": "Dejanja",
    "toleranceSettingText": "Nastavitve tolerance",
    "addLayerLinkText": "Dodaj sloj",
    "useDefaultToleranceText": "Uporabi privzeto toleranco",
    "toleranceValueText": "Vrednost tolerance",
    "toleranceUnitText": "Enota tolerance",
    "pixelsUnitText": "Piksli",
    "useLayerName": "- Uporabi ime sloja -",
    "noLayersMessage": "Na slojih karte ni najdeno nobeno polje, ki se ujema z izbranim tipom podatkov.",
    "intersectionLayerHint": "Razvrščanje slojev je določeno v padajočem vrstnem redu. Uporabite puščice pod Dejanji, da spremenite vrstni red slojev in prioriteto preseka."
  },
  "presetAll": {
    "popupTitle": "Določi privzete prednastavljene vrednosti",
    "deleteTitle": "Izbriši prednastavljeno vrednost",
    "hintMsg": "Vsa edinstvena imena prednastavljenih polj so navedena tukaj. Odstranitev prednastavljenega polja onemogoči ustrezno polje kot prednastavljeno iz vseh slojev/tabel."
  },
  "intersectionTolerance": {
    "intersectionLabel": "Privzeta toleranca preseka za vse geoobjekte",
    "intersectionTitle": "Omogočite globalno toleranco za preseke",
    "pixelsToleranceLabel": "Privzeta toleranca preseka (vrednost piksla), ki bo uporabljena samo za točkovne geoobjekte",
    "pixelsToleranceTitle": "Če je privzeta toleranca preseka za vse geoobjekte nastavljena na 0, uporabite to nastavitev za točkovne geoobjekte"
  },
  "smartActionsPage": {
    "smartActionLabel": "Konfiguriraj Smart Action",
    "addNewSmartActionLinkText": "Dodaj novo",
    "definedActions": "Določena dejanja",
    "priorityPopupTitle": "Določi prioriteto pametnih dejanj",
    "priorityPopupColumnTitle": "Pametna dejanja",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Ime skupine",
    "layerForExpressionLabel": "Sloj za izraz",
    "layerForExpressionNote": "Opomba: polja tega sloja so uporabljena za določanje kriterijev izrazov. Možnost \"Sloji in polja za uporabo\" prikaže samo sloje in preglednice, ki vsebujejo polja, opredeljena v Izrazih.",
    "expressionText": "Izraz",
    "editExpressionLabel": "Uredi izraz",
    "layerAndFieldsApplyLabel": "Sloji in polja za uporabo",
    "submitAttributeText": "Pošljite atributne podatke za polja tudi, ko so skrita",
    "priorityColumnText": "Prioritetno",
    "requiredGroupNameMsg": "Ta vrednost je obvezna.",
    "uniqueGroupNameMsg": "Vnesite enolično ime skupine. Skupina s tem imenom že obstaja.",
    "deleteGroupPopupTitle": "Izbriši skupino pametnega dejanja",
    "deleteGroupPopupMsg": "Brisanje skupine bo povzročilo odstranitev izraza iz vseh povezanih polj dejanja.",
    "invalidExpression": "Polje z izrazom ne sme biti prazno.",
    "warningMsgOnLayerChange": "Določen izraz in polja, v katerih se uporablja, bodo počiščena.",
    "smartActionsTable": {
      "name": "Ime",
      "expression": "Izraz",
      "definedFor": "Določeno za"
    }
  },
  "attributeActionsPage": {
    "name": "Ime",
    "type": "Vrsta",
    "deleteGroupPopupTitle": "Izbriši skupino dejanja atributa",
    "deleteGroupPopupMsg": "Brisanje skupine bo povzročilo odstranitev dejanja atributa iz vseh povezanih polj.",
    "alreadyAppliedActionMsg": "Dejanje ${action} je bilo uporabljeno na tem polju v skupini",
    "alreadyAppliedActionLayerMsg": "Dejanje ${action} je bilo uporabljeno na tem polju iz nastavitev sloja",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Ta skupina nima povezanih polj.",
    "presetNoFieldWarningMsg": "Konfigurirajte vsaj eno polje za prednastavljeno skupino: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Polje",
    "valueLabel": "Vrednost",
    "selectValueLabel": "Izberi vrednost",
    "domainFieldHintLabel": "Izbrana vrednost je domena kodirane vrednosti. Uporabljena bo vrednost: ${domainValue}"
  },
  "presetPopup": {
    "presetValueLAbel": "Prednastavljena vrednost"
  },
  "dataType": {
    "esriFieldTypeString": "Besedilo",
    "esriFieldTypeInteger": "Število",
    "esriFieldTypeDate": "Datum",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Tip podatkov",
    "valueLabel": "Vrednost",
    "fixed": "Fiksno",
    "current": "Trenutno",
    "past": "Pretekli",
    "future": "Prihodnost",
    "popupTitle": "Izberi vrednost",
    "hintForFixedDateType": "Namig: določena datum in čas bosta uporabljena kot prednastavljena privzeta vrednost",
    "hintForCurrentDateType": "Namig: trenutna datum in čas bosta uporabljena kot prednastavljena privzeta vrednost",
    "hintForPastDateType": "Namig: določena vrednost bo odšteta od trenutnega datuma in časa za privzeto vrednost prednastavitve.",
    "hintForFutureDateType": "Namig: določena vrednost bo dodana trenutnemu datumu in času za privzeto vrednost prednastavitve.",
    "noDateDefinedTooltip": "Noben datum ni določen",
    "relativeDateWarning": "Vrednost za datum ali čas mora biti določena, da jo lahko shranite kot privzeto prednastavljeno vrednost.",
    "customLabel": "Po meri"
  },
  "relativeDomains": {
    "fieldSetTitle": "Seznam",
    "valueText": "Vrednost",
    "defaultText": "Privzeto",
    "selectedDomainFieldsHint": "Izbrano polje(-a) domene: ${domainFields}",
    "selectDefaultDomainMsg": "Prosimo, izberite domeno privzete vrednosti ali se prepričajte, da je potrditveno polje izbrane privzete domene označeno"
  }
});