define({
  "taskUrl": "URL služby pre analýzu viditeľnosti",
  "portalURL": "Špecifikujte URL pre vašu organizáciu ArcGIS Online alebo Portal pre ArcGIS",
  "portalURLError": "Konfigurovaná URL pre vašu ArcGIS Online organizáciu alebo Portal pre ArcGIS nie je platná.",
  "privilegeError": "Vaša rola používateľa nemôže vykonať analýzu. Ak chcete vykonať analýzu, správca vašej organizácie vám musí udeliť určité<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">oprávnenia</a>.",
  "noServiceError": "Služba analýzy nadmorskej výšky nie je dostupná. Prosím skontrolujte vašu ArcGIS Online organizačnú alebo Portal pre ArcGIS konfiguráciu.",
  "maximumRangeMessage": "Maximálny pozorovateľný rozsah musí byť väčší ako minimálny porozovateľný rozsah a nemôže byť väčší ako ${limit}${units}.",
  "serviceURLPlaceholder": "Prosím vložte URL geoprocesnej úlohy pohľadu",
  "setTask": "Nastaviť",
  "setTaskTitle": "Nastaviť geoprocesnú úlohu analýzy viditeľnosti",
  "serviceURLError": "Geoprocesná úloha, ktorú sa snažíte nakonfigurovať týmto widgetom nie je platná. Prosím zvoľte platnú URL geoprocesnej úlohy analýzy viditeľnosti",
  "defaultMilsForAnglesLabel": "Predvolene nastaviť mily pre uhly",
  "defaultObserverHeightLabel": "Predvolená jednotka výšky pozorovateľa",
  "defaultObservableDistanceLabel": "Predvolená jednotka pozorovateľnej vzdialenosti",
  "defaultObserveHeightLabel": "Predvolená výška pozorovateľa",
  "defaultMinimumObservableDistanceLabel": "Predvolená minimálna pozorovateľná vzdialenosť",
  "defaultMaximumObservableDistanceLabel": "Predvolená maximálna pozorovateľná vzdialenosť",
  "units": {
    "miles": "Míle",
    "kilometers": "Kilometre",
    "feet": "Stopy",
    "meters": "Metre",
    "yards": "Yardy",
    "nauticalMiles": "Námorné míle"
  },
  "helpIconTooltip": "Zoznam operačných vrstiev je vyplnený vrstvami z aktuálnej webovej mapy, ktoré sú typom geometrie polygónu.",
  "selectOperationalLayerLabel": "Vyberte operačnú vrstvu pre výsledky",
  "lineOfSightTabTitle": "Čiara priamej viditeľnosti",
  "symbologyTabTitle": "Symbolika",
  "transparency": "Priehľadnosť",
  "outline": "Obrys",
  "fill": "Výplň (Farba sa použije iba v prípade, že je štýl nastavený na plný)",
  "style": "Štýl",
  "selectOpLayerLabel": "Vyberte operačnú vrstvu pre výsledky",
  "selectDefaultMeasurementLabel": "Vyberte predvolenú mernú jednotku",
  "visibleSectionLabel": "Viditeľná sekcia",
  "nonVisibleSectionLabel": "Neviditeľná sekcia",
  "visibleSectionButtonLabel": "Konfigurovať nastavenia viditeľnej sekcie",
  "nonVisibleSectionButtonLabel": "Konfigurovať nastavenia neviditeľnej sekcie",
  "colorPicker": "Výber farby",
  "lineStyles": {
    "esriSLSDash": "Pomlčka",
    "esriSLSDashDot": "Pomlčka bodka",
    "esriSLSDashDotDot": "Pomlčka bodka bodka",
    "esriSLSDot": "Bodka",
    "esriSLSLongDash": "Dlhá pomlčka",
    "esriSLSLongDashDot": "Dlhá pomlčka bodka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Krátka pomlčka",
    "esriSLSShortDashDot": "Krátka pomlčka bodka",
    "esriSLSShortDashDotDot": "Krátka pomlčka bodka bodka",
    "esriSLSShortDot": "Krátka bodka",
    "esriSLSSolid": "Plné"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Späť",
    "esriSFSCross": "Priečne",
    "esriSFSDiagonalCross": "Uhlopriečne",
    "esriSFSForwardDiagonal": "Vpred",
    "esriSFSHorizontal": "Vodorovný",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Plné",
    "esriSFSVertical": "Zvislý"
  }
});