define({
  "_widgetLabel": "Anàlisi d'amenaces",
  "threatAnalysisMainPageTitle": "Es basa en la guia antiterrorisme del JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ubicació d'entrada",
  "interactive": "Interactiva",
  "fromCoord": "Coordenada fixa",
  "existingFeature": "Des de les entitats existents",
  "threatAnalysisCoordInputLabel": "Ubicació de l'amenaça",
  "enterCoords": "Introduïu les coordenades",
  "threatAddPointToolTip": "Afegeix la ubicació de l'amenaça",
  "threatDrawPointToolTip": "Feu clic per afegir la ubicació de l'amenaça",
  "threatType": "Tipus d'amenaça",
  "threatPlaceholder": "Comenceu a escriure per cercar una amenaça",
  "mandatoryLabel": "Distància d'evacuació obligatòria",
  "safeLabel": "Distància d'evacuació segura",
  "zoneTypeLabel": "Tipus de zona",
  "feetLabel": "Peus",
  "metersLabel": "Metres",
  "unitsLabel": "Unitats",
  "threatGraphicLayer": "Gràfic d'amenaces",
  "settingsTitle": "Configuració",
  "mandatoryButtonLabel": "Configura la distància d'evacuació obligatòria",
  "safeButtonLabel": "Configura les opcions del refugi existent",
  "style": "Estil",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Guió",
    "esriSLSDashDot": "Guió punt",
    "esriSLSDashDotDot": "Guió punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Guió llarg",
    "esriSLSLongDashDot": "Guió llarg punt",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Guió curt",
    "esriSLSShortDashDot": "Guió curt punt",
    "esriSLSShortDashDotDot": "Guió curt punt punt",
    "esriSLSShortDot": "Punt",
    "esriSLSSolid": "Cos geomètric"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Enrere",
    "esriSFSCross": "Creu",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Endavant",
    "esriSFSHorizontal": "Horitzontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Cos geomètric",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultats",
  "publishTABtn": "Publica",
  "layerName": "Nom de la capa publicada",
  "invalidLayerName": "El nom de la capa només pot contenir caràcters alfanumèrics i de subratllat",
  "missingLayerNameMessage": "Heu d'introduir un nom de capa vàlid per poder fer la publicació",
  "publishingFailedLayerExists": "Error de publicació: ja teniu un servei d'entitats anomenat {0}. Trieu un altre nom de capa.",
  "checkService": "Comprova el servei: {0}",
  "createService": "Crea el servei: {0}",
  "unableToCreate": "No es pot crear: {0}",
  "addToDefinition": "Afegeix a la definició: {0}",
  "successfullyPublished": "La capa web s'ha publicat correctament",
  "successfullyAppended": "Les noves entitats s'han afegit correctament a la capa web",
  "manageWebLayerText": "Gestiona la capa web",
  "userRole": "No es pot crear el servei perquè l'usuari no té permisos",
  "retrieveExistingLayerError": "No es pot recuperar {0}. Feu la publicació amb un altre nom de capa",
  "publishToNewLayer": "Publica els resultats en una nova capa d'entitats",
  "layerNameExists": "El nom de la capa ja existeix. Feu servir un altre nom de capa.",
  "pipeBombLabel": "Bomba casolana",
  "suicideBombLabel": "Bomba suïcida",
  "briefcaseLabel": "Maletí",
  "carLabel": "Cotxe",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Camió de distribució petit",
  "containerWaterTruckLabel": "Camió cisterna/contenidor",
  "semiTrailerLabel": "Semiremolc",
  "transparencyLabel": "Transparència",
  "outline": "Contorn",
  "fill": "Emplenament (el color només s'aplica quan l'estil està definit com a cos geomètric)",
  "createBtn": "Crea zones",
  "clearBtn": "Esborra",
  "invalidNumberMessage": "El valor que s'ha introduït no és vàlid",
  "invalidRangeMessage": "El valor ha de ser més gran que 0",
  "parseCoordinatesError": "No es poden analitzar les coordenades. Comproveu l'entrada.",
  "selectDrawModeLabel": "Seleccioneu el mode de dibuix",
  "selectFeatureLabel": "Seleccioneu una entitat d'aquesta capa",
  "fireBallDiameterLable": "Diàmetre de la bola de foc",
  "lpgSafeDistanceLable": "Distància segura",
  "threatTypeCatagoryLabel": "Categoria del tipus de perill",
  "fireballButtonLabel": "Configura el diàmetre de la bola de foc",
  "safeDistanceButtonLabel": "Configura la distància segura",
  "chemicalThreatCatagoryLabel": "Químic",
  "lpgThreatCatagoryLabel": "Gas liquat del petroli",
  "chemicalThreatLabel": "Perill químic",
  "lpgThreatLabel": "Perill de gas liquat del petroli",
  "fireBallDiameterFieldAlias": "Diàmetre de la bola de foc de gas liquat del petroli",
  "lpgSafeDistanceFieldAlias": "Distància segura de gas liquat del petroli",
  "smallLPGTank": "Dipòsit petit de gas liquat del petroli",
  "largeLPGTank": "Dipòsit gran de gas liquat del petroli",
  "commercialResidentialLPGTank": "Dipòsit comercial o residencial de gas liquat del petroli",
  "smallLPGTruck": "Camió petit de gas liquat del petroli",
  "semiTankerLPG": "Camió cisterna de gas liquat del petroli"
});