define({
  "tabs_section_Label": "Záložky",
  "addTab": "Pridať záložky",
  "layerName": "Vrstva",
  "layerType": "Typ analýzy",
  "layerLabel": "Opis",
  "actions": "Akcie",
  "closest": "Najbližší prvok",
  "proximity": "Blízkosť",
  "summary": "Súhrn",
  "select_lbl": "-- Vybrať --",
  "general_setting_Label": "Všeobecné nastavenia",
  "units_text_lbl": "Jednotky vzdialenosti",
  "maximum_distance_lbl": "Maximálna vzdialenosť najbližšieho prvku",
  "buffer_text_lbl": "Označenie obalovej zóny",
  "buffer_lbl": "Vzdialenosť obalovej zóny",
  "buffer_max_lbl": "Maximálna šírka obalovej zóny",
  "buffer_min_lbl": "Minimálna šírka obalovej zóny",
  "buffer_default_lbl": "Predvolená šírka obalovej zóny",
  "not_less_than_max": "Vzdialenosť musí byť menšia ako maximálna šírka obalovej zóny",
  "not_between": "Vzdialenosť musí byť medzi minimálnou a maximálnou šírkou obalovej zóny",
  "not_more_than_min": "Vzdialenosť musí byť väčšia ako minimálna šírka obalovej zóny",
  "not_valid_number": "Musí byť platné číslo",
  "invalid_value": "${type} hodnota je neplatná",
  "routing_checkBox": "Povoliť trasovanie",
  "weather_removed_message": "Možnosti počasia už nie sú dostupné pre tento widget.",
  "currentlySelectedLayer": "Zvoliť z vrstiev mapy",
  "missingTabLabel": "Aspoň jednej karte chýba jej označenie",
  "missingLayerInWebMap": "Neboli nájdené operačné vrstvy.",
  "selectFields": "Zvoliť stĺpce",
  "addField": "Pridať stĺpec",
  "sum": "Súčet",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Priemer",
  "count": "COUNT",
  "area": "PLOCHA",
  "length": "DĹŽKA",
  "count_checkBox": "Zobraziť počet prvkov",
  "area_checkBox": "Zobraziť súčet plochy",
  "length_checkBox": "Zobraziť súčet dĺžky",
  "max_records": "Bol dosiahnutý maximálny limit",
  "save_label": "Možnosti uloženia",
  "save_checkbox": "Povoliť uloženie",
  "report_label": "Možnosti hlásenia",
  "report_checkbox": "Povoliť hlásenie",
  "csv_label": "Možnosti CSV",
  "display_label": "Možnosti zobrazenia",
  "display_checkbox": "Zobraziť prvky zhrnutia",
  "setSelectionColor": "Nastavte farbu výberu",
  "snapshot_label": "Možnosti snímky",
  "snapshot_checkbox": "Povoliť snimky",
  "must_select_template": "Prosím zvoľte jednu z editovacích šablón v možnostiach ukladania.",
  "count_label": "Označenie počtu",
  "area_label": "Označenie plochy",
  "length_label": "Označenie dĺžky",
  "invalid_string_width": "Hodnota je príliš dlhá. ",
  "layer_type_not_supported": "Typ vrstvy nie je podporovaný",
  "groupedSummary": "Zoskupené počty",
  "groupByField": "Zoskupiť podľa stĺpca",
  "labelType": "Pripojiť označenie",
  "prefix": "Ako predpona",
  "suffix": "Ako prípona",
  "need_group_field": "Prosím použite akciu úprav na definovanie skupiny podľa stĺpca",
  "fieldTitle": "Pole",
  "typeTitle": "Typ",
  "actionsTitle": "Akcie",
  "save_point_checkbox": "Uložiť body",
  "save_line_checkbox": "Uložiť línie",
  "save_poly_checkbox": "Uložiť polygóny",
  "no_valid_popup_fields": "Žiadne platné stĺpce v kontextovom okne. Prosím použite akciu úprav na definovanie stĺpca.",
  "no_valid_fields": "Žiadne platné stĺpce. Prosím použite akciu úprav na definovanie možností zobrazenia.",
  "incident_label": "Označenie karty",
  "locate_incident_label": "Označenie oblasti záujmu",
  "incident": "Incident",
  "locate_incident": "Zamerať incident",
  "buffer_value": "Šírka obalovej zóny",
  "tab_options": "Analýza",
  "export_options": "Výstup",
  "instruction_save": "Uložiť umiestnenie do služby pre prvky.",
  "instruction_snapshot": "Vytvoriť webovú mapu podľa umiestnenia.",
  "instruction_report": "Vytvoriť tlačené hlásenie umiestnenia.",
  "instruction_all_fields": "Exportovať stĺpce s CSV stiahnutím.",
  "data_label": "Nastavenia výstupu údajov",
  "layer_error": "Vrstva chýba alebo je neplatná",
  "visibility_checkBox": "Deaktivovať správu viditeľnosti vrstvy",
  "allFieldsLabel": "Všetky stĺpce",
  "configuredPopUpFieldsLabel": "Konfigurované stĺpce kontextového okna",
  "analysisTypeFieldsLabel": "Stĺpce typu analýzy",
  "reportOptionsMsg": "Mala by byť vybraná aspoň jedna možnosť hlásenia.",
  "analysisSummaryLabelForReport": "Súhrn typu analýzy",
  "popUpSummaryLabelForReport": "Súhrn konfigurovaných stĺpcov kontextového okna",
  "downloadTab": {
    "reportLegend": "Nastavenia prehľadu",
    "textColorLabel": "Zvoliť farbu pre hlavičku stĺpca",
    "setButtonLabel": "Nastaviť",
    "printGPServiceLabel": "Vypísať URL služby",
    "logoLabel": "Logo",
    "logoChooserHint": "Kliknite na obrázok pre zmenu obrázka",
    "footnoteLabel": "Päta"
  },
  "roundValue": "Zaokrúhliť na",
  "roundValueTitle": "Zaokrúhliť hodnoty stĺpca",
  "truncateValue": "Skrátiť na",
  "truncateValueTitle": "Skrátiť hodnoty stĺpca",
  "significantFigures": "platné cifry",
  "fieldOptions": "Možnosti stĺpca",
  "modifyValues": "Modifikovať možnosti stĺpca",
  "validatePlaces": "Musí byť celé číslo",
  "onlyDouble": "Možnosti prídavného stĺpca sú podporované len pre číselné stĺpce.",
  "layerNotAvalible": "Vrstva nebola nájdená",
  "missingLayer": "Názov:${name}",
  "missingLayerHint": "Jedna alebo viac vrstiev spomenutých v tejto konfigurácií aktuálne nie sú dostupné.",
  "drawGeodesic": "Nakresliť geodetické tvary"
});