define({
  "defaultAreaUnit": "Predvolená jednotka plochy",
  "defaultLengthUnit": "Predvolená jednotka dĺžky",
  "acres": "Akre",
  "sqMiles": "Štvorcové míle",
  "sqKilometers": "Štvorcové kilometre",
  "hectares": "Hektáre",
  "sqYards": "Štvorcové yardy",
  "sqFeet": "Štvorcové stopy",
  "sqFeetUS": "Štvorcové stopy (US)",
  "sqMeters": "Štvorcové metre",
  "miles": "Míle",
  "kilometers": "Kilometre",
  "feet": "Stopy",
  "feetUS": "Stopy (US)",
  "meters": "Metre",
  "yards": "Yardy",
  "nauticalMiles": "Námorné míle",
  "showArea": "Plocha",
  "showDistance": "Vzdialenosť",
  "showLocation": "Poloha",
  "showtools": "Zobraziť nástroje merania:",
  "operationalLayer": "Pridať grafiku s meraniami ako operačnú vrstvu mapy.",
  "allHidedTips": "Mal by byť vybraný aspoň jeden nástroj."
});