define({
  "feedbackStyleLabel": "Etäisyyden ja suunnan palautteen tyyli",
  "showTabLabel": "Näytä kaikki välilehdet",
  "tabErrorMessage": "Valitse vähintään yksi välilehti Etäisyyden ja suunnan palautteen tyyli -ryhmästä",
  "lineLabel": "Viiva",
  "circleLabel": "Ympyrä",
  "ellipseLabel": "Ellipsi",
  "ringsLabel": "Renkaat",
  "transparency": "Läpinäkyvyys",
  "operationalLineLayerSelectLabel": "Valitse toiminnallinen taiteviivakarttataso viiva- ja rengastuloksille",
  "operationalPolygonLayerSelectLabel": "Valitse toiminnallinen aluekohdekarttataso ympyrä- ja ellipsituloksille",
  "helpIconPolylineTooltip": "Toiminnallisten karttatasojen luettelo täytetään nykyisen web-kartan karttatasoilla, jotka ovat tyypiltään taiteviivageometrioita.",
  "helpIconPolygonTooltip": "Toiminnallisten karttatasojen luettelo täytetään nykyisen web-kartan karttatasoilla, jotka ovat tyypiltään aluekohdegeometrioita.",
  "feedbackResultsLayerLabel": "Etäisyyden ja suunnan palautteen tuloskarttataso",
  "editSymbologyHint": "Vihje: muokkaa symboleja napsauttamalla esikatselukuvaketta",
  "feedbackTextColorLabel": "Palautteen tunnustekstin tekstin väri",
  "feedbackTextSizeLabel": "Palautteen tunnustekstin tekstin koko",
  "previewLabel": "Esikatselu",
  "lineSymbologyPopupTittle": "Viivasymbolit",
  "circleSymbologyPopupTittle": "Ympyräsymbolit",
  "ellipseSymbologyPopupTittle": "Ellipsisymbolit",
  "ringSymbologyPopupTittle": "Rengassymbolit"
});