define({
  "_widgetLabel": "Análise de Camada",
  "threatAnalysisMainPageTitle": "Baseado no Guia de Contraterrorismo do JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Local de Entrada",
  "interactive": "Interativo",
  "fromCoord": "Coordenada Fixa",
  "existingFeature": "Das Feições Existentes",
  "threatAnalysisCoordInputLabel": "Localização da Camada",
  "enterCoords": "Inserir Coordenadas",
  "threatAddPointToolTip": "Adicionar Localização da Camada",
  "threatDrawPointToolTip": "Clique para adicionar localização da camada",
  "threatType": "Tipo de Camada",
  "threatPlaceholder": "Inicie digitando para procurar por uma camada",
  "mandatoryLabel": "Distância Obrigatória de Evacuação",
  "safeLabel": "Distância de Evacuação Segura",
  "zoneTypeLabel": "Tipo de Zona",
  "feetLabel": "Pés",
  "metersLabel": "Metros",
  "unitsLabel": "Unidades",
  "threatGraphicLayer": "Ameaça-Gráfico",
  "settingsTitle": "Configurações",
  "mandatoryButtonLabel": "Definir Configurações de Distância Obrigatória de Evacuação",
  "safeButtonLabel": "Definir Configurações de Abrigo no Local",
  "style": "Estilo",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Ponto Traço Curto",
    "esriSLSShortDashDotDot": "Ponto Ponto Traço Curto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Para Trás",
    "esriSFSCross": "Transversal",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para Frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultados",
  "publishTABtn": "Publicar",
  "layerName": "Nome da Camada Publicada",
  "invalidLayerName": "O nome da camada deve conter somente caracteres alfanuméricos e underscores",
  "missingLayerNameMessage": "Você deve inserir um nome de camada válida antes de poder publicar",
  "publishingFailedLayerExists": "Falha na Publicação: Você já tem um serviço de feição denominado {0}. Escolha outro nome da camada.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não foi possível criar: {0}",
  "addToDefinition": "Adicionar à definição: {0}",
  "successfullyPublished": "Camada da web publicada com sucesso",
  "successfullyAppended": "Novas feições anexadas com sucesso na camada da web",
  "manageWebLayerText": "Gerenciar a camada de web",
  "userRole": "Não foi possível criar serviço pois o usuário não tem permissões",
  "retrieveExistingLayerError": "Não foi possível recuperar {0}. Publique utilizando outro nome da camada",
  "publishToNewLayer": "Publicar resultados para uma nova camada de feição",
  "layerNameExists": "A camada já existe. Utilize um nome de camada diferente.",
  "pipeBombLabel": "Bomba Caseira",
  "suicideBombLabel": "Ataque Suicida",
  "briefcaseLabel": "Porta-arquivos",
  "carLabel": "Carro",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Caminhão de entrega pequeno",
  "containerWaterTruckLabel": "Contêiner/Caminhão Pipa",
  "semiTrailerLabel": "Semi-Trailer",
  "transparencyLabel": "Transparência",
  "outline": "Contorno",
  "fill": "Preencher (a cor somente se aplica quando o estilo é definido para sólido)",
  "createBtn": "Criar Zonas",
  "clearBtn": "Apagar",
  "invalidNumberMessage": "Os valores inseridos não são válidos",
  "invalidRangeMessage": "O valor deve ser maior que 0",
  "parseCoordinatesError": "Não é possível analisar coordenadas. Verifique sua entrada.",
  "selectDrawModeLabel": "Selecionar Modo de Desenho",
  "selectFeatureLabel": "Selecionar Feição Desta Camada",
  "fireBallDiameterLable": "Diâmetro da Bola de Fogo",
  "lpgSafeDistanceLable": "Distância Segura",
  "threatTypeCatagoryLabel": "Categoria de Tipo de Ameaça",
  "fireballButtonLabel": "Definir as Configurações do Diâmetro da Bola de Fogo",
  "safeDistanceButtonLabel": "Definir Configurações de Distância Segura",
  "chemicalThreatCatagoryLabel": "Substância química",
  "lpgThreatCatagoryLabel": "Gás de Petróleo Liquefeito",
  "chemicalThreatLabel": "Ameaça Química",
  "lpgThreatLabel": "Ameaça de LPG",
  "fireBallDiameterFieldAlias": "Diâmetro da Bola de Fogo LPG",
  "lpgSafeDistanceFieldAlias": "Distância Segura LPG",
  "smallLPGTank": "Tanque LPG Pequeno",
  "largeLPGTank": "Tanque LPG Grande",
  "commercialResidentialLPGTank": "Tanque LPG Comercial/Residencial",
  "smallLPGTruck": "Caminhão LPG Pequeno",
  "semiTankerLPG": "Semi-petroleiro LPG"
});