define({
  "transparencyLabel": "Átlátszóság",
  "outline": "Kontúr",
  "fill": "Kitöltés (a Szín beállítás csak az egyszínű stílus beállítása esetén érhető el)",
  "style": "Stílus",
  "selectOpLayerLabel": "Válasszon operatív réteget az eredmények számára",
  "selectDefaultMeasurementLabel": "Válasszon alapértelmezett mértékegységet",
  "helpIconTooltip": "Az operatív réteget a rendszer olyan rétegekkel tölti fel az aktuális webtérképből, amelyek poligon típusú geometriával rendelkeznek.",
  "lineStyles": {
    "esriSLSDash": "Szaggatott",
    "esriSLSDashDot": "Vonal-pont",
    "esriSLSDashDotDot": "Vonal-pont-pont",
    "esriSLSDot": "Pont",
    "esriSLSLongDash": "Hosszú vonal",
    "esriSLSLongDashDot": "Hosszú vonal-pont",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Rövid vonal",
    "esriSLSShortDashDot": "Rövid vonal-pont",
    "esriSLSShortDashDotDot": "Rövid vonal-pont-pont",
    "esriSLSShortDot": "Rövid pont",
    "esriSLSSolid": "Folytonos"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Hátra",
    "esriSFSCross": "Kereszt",
    "esriSFSDiagonalCross": "Átlós",
    "esriSFSForwardDiagonal": "Előre",
    "esriSFSHorizontal": "Vízszintes",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Folytonos",
    "esriSFSVertical": "Függőleges"
  },
  "threatTypeLabel": "Fenyegetés típusa",
  "generalLabel": "Általános",
  "addThreatTypesLabel": "Fenyegetés típusának hozzáadása",
  "actions": "Műveletek",
  "newThreatTypePopupLabel": "Új fenyegetéstípus",
  "units": "Mértékegységek",
  "chooseDefaultThreatLabel": "Válasszon alapértelmezett fenyegetéstípust",
  "defaultThreatTypePopUpLabel": "Alapértelmezett fenyegetéstípusok",
  "editThreatLabel": "Fenyegetés szerkesztése",
  "defaultThreatTypeIconTooltip": "Alapértelmezett fenyegetéstípusok listája",
  "uniqueThreatTypeMsg": "Egyedi fenyegetéstípust adjon meg: már létezik fenyegetéstípus ilyen névvel.",
  "requiredMsg": "A mező kitöltése kötelező",
  "unitMeasureLabel": "A távolságok {0} mértékegységben vannak megadva",
  "chooseDefaultThreatTypeIconLabel": "Választás alapértelmezettből",
  "pipeBombLabel": "Csőbomba",
  "suicideBombLabel": "Öngyilkos merénylő",
  "briefcaseLabel": "Aktatáska",
  "carLabel": "Autó",
  "suvVanLabel": "SUV/FURGON",
  "smallDeliveryTruckLabel": "Kisteherautó",
  "containerWaterTruckLabel": "Konténerszállító/vízszállító teherautó",
  "semiTrailerLabel": "Félpótkocsis teherautó",
  "chemicalThreatLegendLabel": "Vegyi anyag okozta veszély",
  "lpgThreatLegendLabel": "LPG okozta veszély",
  "smallLPGTank": "Kis LPG-tartály",
  "largeLPGTank": "Nagy LPG-tartály",
  "commercialResidentialLPGTank": "Kereskedelmi célú/lakossági LPG-tartály",
  "smallLPGTruck": "Kis LPG-szállító teherautó",
  "semiTankerLPG": "LPG-szállító tartályos félpótkocsi",
  "threatDescriptionColLabel": "Fenyegetés leírása",
  "addThreatZoneButtonLabel": "Fenyegetési zóna hozzáadása",
  "zoneDescColLabel": "Zóna leírása",
  "distanceLabel": "Távolság (${unitAbbr})",
  "threatTypeHelp": "<p>Győződjön meg arról, hogy a következő feltételek teljesülnek a fenyegetéstípusok esetében:<br/><ul><li>A fenyegetéstípus nem lehet üres és egyedinek kell lennie</li><li>A fenyegetésnek legalább egy érvényes zónával kell rendelkeznie</li><li>A zóna leírásának egyedinek kell lennie a fenyegetéshez</li></ul><p/>",
  "descriptionLabel": "Leírás",
  "newThreatZonePopupLabel": "Új fenyegetési zóna",
  "editThreatZonePopupLabel": "Fenyegetési zóna szerkesztése",
  "uniqueZoneDescriptionMsg": "Adjon meg egyedi zónaleírást, ilyen nevű zónaleírás már létezik.",
  "symbologyColLabel": "Szimbólumrendszer",
  "zoneDescriptionColLabel": "Zóna leírása",
  "uniqueZoneRequiredMsg": "A zóna nevének egyedinek kell lennie:",
  "interactive": "Interaktív",
  "fromCoord": "Rögzített koordináta",
  "existingFeature": "Meglévő vektoros elemből",
  "defaultInputLocationLabel": "Alapértelmezett bemeneti hely",
  "defaultInputLayer": "Alapértelmezett bemeneti réteg",
  "defaultThreatType": "Alapértelmezett fenyegetéstípus",
  "selectLabel": "Kiválasztás",
  "mandatoryLabel": "Kötelező evakuálási távolság",
  "safeLabel": "Biztonságos evakuálási távolság",
  "lpgSafeDistanceLable": "Biztonságos távolság",
  "fireBallDiameterLable": "Tűzgömb átmérője"
});