define({
  "businessAnalyst": "การวิเคราะห์ทางธุรกิจ",
  "defaultFirstPageText": "<br><div>เข้าใช้งานอินโฟกราฟิกและรายงาน ที่สรุปข้อมูลตัวบ่งชี้หลักและข้อมูลของพื้นที่ใด ๆ </div><br><div>เลือกจุดหรือโพลีกอนบนแผนที่ ค้นหาที่อยู่หรือสถานที่ วาดโพลีกอน หรือปักหมุดบนแผนที่ เพื่อดูตัวบ่งชี้หลัก และข้อมูลเกี่ยวกับพื้นที่ดังกล่าว</div>",
  "defineWhichInfographics": "กำหนดอินโฟกราฟิกที่สามารถใช้งานได้ในวิดเจ็ท:",
  "defineWhichReports": "กำหนดรายงานที่สามารถใช้งานได้ในวิดเจ็ท:",
  "defaultValues": "ค่าเริ่มต้น:",
  "disable": "ปิดการใช้งาน",
  "drawFreehandPolygon": "วาดโพลีกอนด้วยมือ",
  "drawPolygon": "วาดรูปหลายเหลี่ยม",
  "driveTime": "ระยะทางขับรถ",
  "dropPin": "ปักหมุด",
  "dynamicHTML": "HTML แบบไดนามิก",
  "exportOptions": "ตัวเลือกการส่งออก:",
  "home": "หน้าหลัก",
  "image": "รูปภาพ",
  "infographics": "แผนภูมิ",
  "invalidValueRing": "ค่าต้องอยู่ในช่วง 0 ถึง 1,000",
  "invalidValueDTWT": "ค่าต้องอยู่ในช่วง 0 ถึง 300",
  "km": "กม",
  "makeDefault": "กำหนดให้เป็นค่าเริ่มต้น",
  "miles": "ไมล์",
  "minutes": "นาที",
  "options": "ตัวเลือก:",
  "pdf": "PDF",
  "print": "พิมพ์",
  "radius": "รัศมี",
  "removeDefault": "ลบค่าเริ่มต้น",
  "reports": "รายงาน",
  "rings": "วงแหวน",
  "searchTextBox": "กล่องข้อความค้นหา",
  "selectCountryOrRegion": "เลือกประเทศหรือภูมิภาค:",
  "thisEntryIsNotValid": "รายการนี้ไม่ถูกต้อง",
  "time": "เวลา",
  "walkTime": "เวลาเดิน"
});