define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Uw account heeft geen machtigingen om gegevens te maken of te wijzigen.",
  "loginPopupTitle": "Aanmelden",
  "loginPopupMessage": "${widgetName} vereist toestemmingen en credits om adresinformatie op te zoeken en op te slaan. Wilt u zich aanmelden en deze mogelijkheid gebruiken?",
  "noCreditsOrPrivilegeWarningMessage": "Uw account heeft niet de rechten en credits om adresinformatie op te zoeken en op te slaan met ${widgetName}.   Neem contact op met uw organisatiebeheerder om toestemmingen en credits aan te vragen.  Klik op OK om door te gaan met bewerken.",
  "unableToUseLocator": "Locator is niet toegankelijk.   De adresattribuutactie(s) worden niet uitgevoerd.  Klik op OK om door te gaan met bewerken.",
  "locatorDisabledWaning": "Locator is niet ingeschakeld.   Neem contact op met uw organisatiebeheerder om deze mogelijkheid aan te vragen. Klik op OK om door te gaan met bewerken.",
  "noFeatureInAIWarning": "Geen object(en) geselecteerd.   Selecteer een object om bewerkingen uit te voeren of klik op Annuleren om terug te keren naar het hoofdscherm.",
  "noEditableLayerWarning": "Uw account heeft geen toestemming om gegevens te maken of te wijzigen, of deze webmap bevat geen bewerkbare lagen.",
  "noVisibleCreateLayerWarning": "La(a)g(en) niet zichtbaar op het huidige zoomniveau. Zoom in of uit om objecten te maken / wijzigen.",
  "noVisibleUpdateLayerWarning": "La(a)g(en) niet zichtbaar op het huidige zoomniveau. Zoom in of uit om objecten te wijzigen.",
  "checkLayerVisibilityInWebMapWarning": "Zorg ervoor dat lagen zichtbaar zijn op de kaart om objecten te maken of te wijzigen.",
  "showSelectionInAITitle": "Geselecteerde objecten",
  "showSelectionInAIMsg": "Wilt u de huidige selectie laden in ${widgetName}?",
  "widgetActive": "Actief",
  "widgetNotActive": "Niet actief",
  "pressStr": "Druk op ",
  "ctrlStr": " CTRL ",
  "snapStr": " om snapping in te schakelen",
  "noAvailableTempaltes": "Geen beschikbare templates",
  "editorCache": " - Editor Cache",
  "presetFieldAlias": "Veld",
  "presetValue": "Ingestelde waarde",
  "usePresetValues": " Gebruik ingestelde waarden (alleen nieuwe objecten)",
  "editGeometry": " Geometrie bewerken",
  "savePromptTitle": "Object opslaan",
  "savePrompt": "Wilt u het huidige object nu opslaan?",
  "deletePromptTitle": "Object verwijderen",
  "deleteAttachment": "Bijlage verwijderen",
  "deletePrompt": "Weet u zeker dat u het geselecteerde object wilt verwijderen?",
  "attachmentLoadingError": "Fout opgetreden tijdens het uploaden van bijlagen",
  "attachmentSaveDeleteWarning": "Waarschuwing: wijzigingen in bijlagen worden automatisch opgeslagen",
  "autoSaveEdits": "Slaat nieuw object automatisch op",
  "addNewFeature": "Een nieuw object maken",
  "featureCreationFailedMsg": "Kan geen nieuw record/object maken",
  "relatedItemTitle": "Gerelateerde tabel/laag",
  "relatedFeatureCount": "${layerTitle} met ${featureCount} objecten",
  "createNewFeatureLabel": "Nieuw object maken voor ${layerTitle}",
  "invalidRelationShipMsg": "Zorg ervoor dat het primaire sleutelveld: '${parentKeyField}' een geldige waarde heeft",
  "pendingFeatureSaveMsg": "Sla de objectbewerkingen op voordat u een gerelateerd object maakt.",
  "attachmentsRequiredMsg": "(*) Bijlagen zijn vereist.",
  "coordinatePopupTitle": "Verplaats object naar XY-locatie",
  "coordinatesSelectTitle": "Coördinatensysteem",
  "mapSpecialReferenceDropdownOption": "Ruimtelijke referentie van de kaart",
  "latLongDropdownOption": "Breedtegraad/lengtegraad",
  "mgrsDropdownOption": "Militair rasterreferentiesysteem (Military Grid Reference System -MGRS)",
  "mgrsTextBoxLabel": "Coördinaat:",
  "xAttributeTextBoxLabel": "X-coordinaat:",
  "yAttributeTextBoxLabel": "Y-coördinaat:",
  "latitudeTextBoxLabel": "Breedtegraad:",
  "longitudeTextBoxLabel": "Lengtegraad:",
  "presetGroupFieldsLabel": "${groupName}' zal worden toegepast op de volgende laagvelden:",
  "presetGroupNoFieldsLabel": "'${groupName}' heeft geen bijbehorende velden",
  "groupInfoLabel": "Groepsinformatie voor '${groupName}'",
  "editGroupInfoIcon": "Groepswaarde bewerken voor ${groupName}",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Geen beschikbare templates",
    "searchTemplates": "Templates zoeken",
    "filterLayerLabel": "Lagen filteren"
  },
  "invalidConfiguration": "Widget is niet geconfigureerd of de lagen in de configuratie zijn niet langer in de kaart. Open de app in de bouwmodus en configureer de widget opnieuw.",
  "geometryServiceURLNotFoundMSG": "Kan geometrieservice-URL niet verkrijgen",
  "clearSelection": "Sluiten",
  "refreshAttributes": "De attributen van dynamische objecten bijwerken",
  "automaticAttributeUpdatesOn": "Automatisch objectattributen bijwerken: AAN",
  "automaticAttributeUpdatesOff": "Automatisch objectattributen bijwerken: UIT",
  "moveSelectedFeatureToGPS": "Verplaats geselecteerd object naar huidige GPS-locatie",
  "moveSelectedFeatureToXY": "Verplaats object naar XY-locatie",
  "mapNavigationLocked": "Kaartnavigatie: vergrendeld",
  "mapNavigationUnLocked": "Kaartnavigatie: ontgrendeld",
  "copyFeatures": {
    "title": "Selecteer objecten om te kopiëren",
    "createFeatures": "Objecten maken",
    "createSingleFeature": "1 multideel-object aanmaken",
    "createOneSingleFeature": "Object maken",
    "noFeaturesSelectedMessage": "Geen objecten geselecteerd",
    "selectFeatureToCopyMessage": "Selecteer de objecten die gekopieerd moeten worden",
    "multipleFeatureSaveWarning": "Als u meerdere objecten maakt met deze functionaliteit, worden alle nieuwe objecten onmiddellijk opgeslagen. Veldovereenkomsten worden niet ondersteund bij het maken van een nieuw meerdelig object.",
    "copyFeatureUpdateGeometryError": "Kan geometrie van geselecteerde objecten niet bijwerken.",
    "canNotSaveMultipleFeatureWarning": "U kunt slechts één object kopiëren als de doelpuntlaag unieke waardevelden heeft.",
    "createOnlyOneMultipartFeatureWarning": "U kunt slechts één object kopiëren of één meerdelig object maken als de doellaag unieke waardevelden heeft.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} van ${totalFeatures} objecten geselecteerd"
  },
  "addingFeatureError": "Fout bij het toevoegen van de geselecteerde objecten in de laag. Probeer het opnieuw.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' object(en) niet gekopieerd.  Wilt u het opnieuw proberen voor de ontbrekende object(en)?",
  "selectingFeatureError": "Fout bij het selecteren van objecten in de laag. Probeer het opnieuw.",
  "customSelectOptionLabel": "Selecteer objecten om te kopiëren",
  "copyFeaturesWithPolygon": "Kopiëren op vlak",
  "copyFeaturesWithRect": "Kopiëren op rechthoek",
  "copyFeaturesWithLasso": "Kopiëren op lasso",
  "noFeatureSelectedMessage": "Geen objecten geselecteerd",
  "multipleFeatureSaveMessage": "Alle objecten zullen onmiddellijk worden opgeslagen. Wilt u doorgaan?",
  "relativeDates": {
    "dateTypeLabel": "Datumtype",
    "valueLabel": "Waarde",
    "fixed": "Vast",
    "current": "Huidige",
    "past": "Voorbij(e)",
    "future": "Toekomst",
    "popupTitle": "Waarde selecteren",
    "hintForFixedDateType": "Tip: De opgegeven datum en tijd worden gebruikt als vooraf ingestelde standaardwaarde.",
    "hintForCurrentDateType": "Tip: Huidige datum en tijd worden gebruikt als vooraf ingestelde standaardwaarde.",
    "hintForPastDateType": "Tip: De opgegeven waarde wordt afgetrokken van de huidige datum en tijd voor de standaardwaarde van de preset.",
    "hintForFutureDateType": "Tip: De opgegeven waarde wordt toegevoegd aan de huidige datum en tijd voor de standaardwaarde van de preset.",
    "noDateDefinedTooltip": "Geen datum vastgelegd",
    "relativeDateWarning": "Er moet een waarde voor datum of tijd worden opgegeven om de standaard ingestelde waarde te kunnen opslaan.",
    "customLabel": "Aangepast",
    "layerLabel": "Kaartlaag",
    "domainFieldHintLabel": "De geselecteerde waarde is een gecodeerd waardedomein. De waarde: \"${domainValue}\" wordt gebruikt"
  },
  "valuePicker": {
    "popupTitle": "Waarde selecteren",
    "popupHint": "Huidig object kruist meerdere functies, kies waarde voor respectief veld",
    "buttonTooltip": "Selecteer waarde uit meerdere kruisende objecten"
  },
  "uniqueValueErrorMessage": "De waarde in \"${fieldName}\" bestaat al, geef een nieuwe waarde op.",
  "requiredFields": {
    "displayMsg": "Vereiste velden mogen niet leeg zijn Voer hieronder waarden in voor algemene velden.",
    "popupTittle": "Vereiste velden",
    "foundNullRecordCount": "${fieldName} (Gevonden in ${count} records)"
  },
  "fieldsMapping": {
    "popupTittle": "Veldkoppeling toepassen",
    "fieldsMatchingCheckboxLabel": "Waarde(n) van gekopieerde object(en) overschrijven standaardwaarde(n) in doelveld(en)",
    "resetLabel": "Opnieuw instellen",
    "clearLabel": "Wissen",
    "fieldsInTargetLayerLabel": "Doel",
    "fieldsInSourceLayerLabel": "Bron",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} overeenkomende velden)",
    "selectSourceFieldLabel": "- Selecteren -",
    "selectFieldAriaLabel": "Selecteer bronveld voor doelveld ${targetField}",
    "informativeText": "Bekijk de velden die overeenkomen van bron tot doel en pas deze indien nodig aan.",
    "dynamicValueText": "Er is een dynamische waarde ingesteld",
    "noFieldsToMatchLabel": "Geen overeen te stemmen velden"
  },
  "cantLocateUserLocation": "Uw locatie kon niet worden bepaald",
  "tryAgainButtonLabel": "Opnieuw proberen",
  "copyFeatureFailedPopupTitle": "Oeps!"
});