define({
  "_widgetLabel": "Analisis Ancaman",
  "threatAnalysisMainPageTitle": "Berdasarkan Pedoman Antiterorisme JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Input Lokasi",
  "interactive": "Interaktif",
  "fromCoord": "Koordinat Tetap",
  "existingFeature": "Dari Fitur yang Ada",
  "threatAnalysisCoordInputLabel": "Lokasi Ancaman",
  "enterCoords": "Masukkan Koordinat",
  "threatAddPointToolTip": "Tambahkan Lokasi Ancaman",
  "threatDrawPointToolTip": "Klik untuk menambahkan lokasi ancaman",
  "threatType": "Jenis Ancaman",
  "threatPlaceholder": "Mulai mengetik untuk mencari ancaman",
  "zoneTypeLabel": "Jenis Zona",
  "feetLabel": "Kaki",
  "metersLabel": "Meter",
  "unitsLabel": "Unit",
  "threatGraphicLayer": "Grafik Ancaman",
  "style": "Gaya",
  "settingsTitle": "Pengaturan",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Garis Datar",
    "esriSLSDashDot": "Garis Datar Titik",
    "esriSLSDashDotDot": "Garis Datar Titik Titik",
    "esriSLSDot": "Titik",
    "esriSLSLongDash": "Garis Datar Panjang",
    "esriSLSLongDashDot": "Garis Datar Panjang Titik",
    "esriSLSNull": "Nol",
    "esriSLSShortDash": "Garis Datar Pendek",
    "esriSLSShortDashDot": "Garis Datar Pendek Titik",
    "esriSLSShortDashDotDot": "Garis Datar Pendek Titik Titik",
    "esriSLSShortDot": "Titik Pendek",
    "esriSLSSolid": "Padat"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Belakang",
    "esriSFSCross": "Silang",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Depan",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nol",
    "esriSFSSolid": "Padat",
    "esriSFSVertical": "Vertikal"
  },
  "resultsTitle": "Hasil",
  "publishTABtn": "Terbitkan",
  "layerName": "Nama Layer yang Diterbitkan",
  "invalidLayerName": "Nama layer tidak boleh mengandung karakter alfa-numerik dan garis bawah",
  "missingLayerNameMessage": "Anda harus memasukkan nama layer yang valid sebelum Anda dapat menerbitkan",
  "publishingFailedLayerExists": "Penerbitan Gagal: Anda telah memiliki feature service bernama {0}.  Harap pilih nama layer yang lain.",
  "checkService": "Periksa Layanan: {0}",
  "createService": "Buat Layanan: {0}",
  "unableToCreate": "Tidak dapat membuat: {0}",
  "addToDefinition": "Tambahkan ke definisi: {0}",
  "successfullyPublished": "Berhasil memublikasikan layer web",
  "successfullyAppended": "Berhasil menambahkan fitur baru ke layer web",
  "manageWebLayerText": "Kelola layer web",
  "userRole": "Tidak dapat membuat layanan karena pengguna tidak memiliki izin",
  "retrieveExistingLayerError": "Tidak dapat mengambil {0}. Harap publikasikan dengan nama layer yang lain",
  "publishToNewLayer": "Publikasikan hasil ke feature layer baru",
  "layerNameExists": "Nama layer sudah ada. Gunakan nama layer yang berbeda.",
  "pipeBombLabel": "Bom Pipa",
  "suicideBombLabel": "Bom Bunuh Diri",
  "briefcaseLabel": "Tas kerja",
  "carLabel": "Mobil",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Truk Pengiriman Kecil",
  "containerWaterTruckLabel": "Truk Kontainer/Truk Air",
  "semiTrailerLabel": "Truk Semi-Trailer",
  "transparencyLabel": "Transparansi",
  "outline": "Kerangka",
  "fill": "Isi (Warna hanya berlaku jika gaya diatur ke padat)",
  "createBtn": "Buat Zona",
  "clearBtn": "Hapus",
  "invalidNumberMessage": "Nilai yang dimasukkan tidak valid",
  "invalidRangeMessage": "Nilai harus lebih besar dari 0",
  "parseCoordinatesError": "Tidak dapat menguraikan koordinat. Harap periksa input Anda.",
  "selectDrawModeLabel": "Pilih Mode Gambar",
  "selectFeatureLabel": "Pilih Fitur dari Layer Ini",
  "smallLPGTank": "Tangki LPG Kecil",
  "largeLPGTank": "Tangki LPG Besar",
  "commercialResidentialLPGTank": "Tangko LPG Komersial/Residensial",
  "smallLPGTruck": "Truk LPG Kecil",
  "semiTankerLPG": "LPG Semi-Tanker",
  "zoneDescriptionColLabel": "Deskripsi zona",
  "distanceColLabel": "Jarak",
  "zoneDescColLabel": "Deskripsi zona",
  "descriptionLabel": "Keterangan",
  "editThreatZonePopupLabel": "Edit simbologi zona ancaman",
  "symbologyColLabel": "Simbologi",
  "actions": "Tindakan",
  "threatTypeSelectLabel": "Pilih jenis ancaman:",
  "distanceLabel": "Jarak (${unitAbbr})",
  "layerCountHint": "Petunjuk: Layer web dengan ${layerCount} feature layer akan dipublikasikan.",
  "selectLabel": "Pilih",
  "mandatoryLabel": "Jarak Evakuasi Wajib",
  "safeLabel": "Jarak Evakuasi Aman",
  "fireBallDiameterLable": "Diameter Bola Api",
  "lpgSafeDistanceLable": "Jarak Aman"
});