define({
  "_widgetLabel": "Grėsmių analizė",
  "threatAnalysisMainPageTitle": "Paremta JCAT kovos su terorizmu vadovu",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Įvesties vieta",
  "interactive": "Interaktyvus",
  "fromCoord": "Fiksuota koordinatė",
  "existingFeature": "Iš esamų elementų",
  "threatAnalysisCoordInputLabel": "Grėsmės vieta",
  "enterCoords": "Įveskite koordinates",
  "threatAddPointToolTip": "Pridėti grėsmės vietą",
  "threatDrawPointToolTip": "Spustelėkite norėdami pridėti grėsmės vietą",
  "threatType": "Grėsmės tipas",
  "threatPlaceholder": "Pradėkite vesti tekstą, kad rastumėte grėsmę",
  "mandatoryLabel": "Būtinas evakuacijos atstumas",
  "safeLabel": "Saugus evakuacijos atstumas",
  "zoneTypeLabel": "Srities tipas",
  "feetLabel": "Pėdos",
  "metersLabel": "Metrai",
  "unitsLabel": "Vienetai",
  "threatGraphicLayer": "Grėsmės grafika",
  "settingsTitle": "Parametrai",
  "mandatoryButtonLabel": "Konfigūruoti būtino evakuacijos atstumo nustatymus",
  "safeButtonLabel": "Konfigūruoti pastogės vietoje nustatymus",
  "style": "Stilius",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Brūkšnys",
    "esriSLSDashDot": "Brūkšnys taškas",
    "esriSLSDashDotDot": "Brūkšnys taškas taškas",
    "esriSLSDot": "Taškas",
    "esriSLSLongDash": "Ilgas brūkšnys",
    "esriSLSLongDashDot": "Ilgas brūkšnys taškas",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trumpas brūkšnys",
    "esriSLSShortDashDot": "Trumpas brūkšnys taškas",
    "esriSLSShortDashDotDot": "Trumpas brūkšnys taškas taškas",
    "esriSLSShortDot": "Trumpas taškas",
    "esriSLSSolid": "Vientisas"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atgal",
    "esriSFSCross": "Skersai",
    "esriSFSDiagonalCross": "Įstrižai",
    "esriSFSForwardDiagonal": "Pirmyn",
    "esriSFSHorizontal": "Horizontalė",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vientisas",
    "esriSFSVertical": "Vertikalė"
  },
  "resultsTitle": "Rezultatai",
  "publishTABtn": "Publikuoti",
  "layerName": "Publikuotas sluoksnio pavadinimas",
  "invalidLayerName": "Sluoksnio pavadinime gali būti tik raidės, skaičiai ir pabraukimo brūkšniai",
  "missingLayerNameMessage": "Prieš publikuojant reikia įvesti tinkamą sluoksnio pavadinimą",
  "publishingFailedLayerExists": "Publikuoti nepavyko: jau turite elementų paslaugą, kurios pavadinimas {0}. Pasirinkite kitą sluoksnio pavadinimą.",
  "checkService": "Tikrinti paslaugą: {0}",
  "createService": "Kurti paslaugą: {0}",
  "unableToCreate": "Nepavyko sukurti: {0}",
  "addToDefinition": "Įtraukti į aprašą: {0}",
  "successfullyPublished": "Sėkmingai publikuotas žiniatinklio sluoksnis",
  "successfullyAppended": "Sėkmingai pridėti nauji elementai į žiniatinklio sluoksnį",
  "manageWebLayerText": "Tvarkyti žiniatinklio sluoksnį",
  "userRole": "Nepavyksta sukurti paslaugos, nes naudotojas neturi teisių",
  "retrieveExistingLayerError": "Neįmanoma gauti {0}. Publikuokite naudodami kitą sluoksnio pavadinimą",
  "publishToNewLayer": "Publikuoti rezultatus į naują elementų sluoksnį",
  "layerNameExists": "Toks sluoksnio pavadinimas jau yra. Pasirinkite kitokį sluoksnio pavadinimą.",
  "pipeBombLabel": "Vamzdinė bomba",
  "suicideBombLabel": "Savižudžio bomba",
  "briefcaseLabel": "Portfelis",
  "carLabel": "Automobilis",
  "suvVanLabel": "SUV / VAN",
  "smallDeliveryTruckLabel": "Mažų siuntų pristatymo sunkvežimis",
  "containerWaterTruckLabel": "Konteinervežis/ vandenvežis",
  "semiTrailerLabel": "Puspriekabė",
  "transparencyLabel": "Permatomumas",
  "outline": "Kontūras",
  "fill": "Užpildas (spalva taikoma, tik kai pasirinktas vientisas stilius)",
  "createBtn": "Kurti zonas",
  "clearBtn": "Valyti",
  "invalidNumberMessage": "Įvesta reikšmė yra netinkama",
  "invalidRangeMessage": "Reikšmė turi būti didesnė nei 0",
  "parseCoordinatesError": "Nepavyko apdoroti koordinačių. Patikrinkite įvestį.",
  "selectDrawModeLabel": "Pasirinkti braižymo režimą",
  "selectFeatureLabel": "Pasirinkti elementą iš šio sluoksnio",
  "fireBallDiameterLable": "Fireball skersmuo",
  "lpgSafeDistanceLable": "Saugus atstumas",
  "threatTypeCatagoryLabel": "Grėsmės tipo kategorija",
  "fireballButtonLabel": "Konfigūruoti Fireball skersmens nustatymus",
  "safeDistanceButtonLabel": "Konfigūruoti saugaus atstumo nustatymus",
  "chemicalThreatCatagoryLabel": "Cheminė",
  "lpgThreatCatagoryLabel": "Suskystintos dujos",
  "chemicalThreatLabel": "Cheminė grėsmė",
  "lpgThreatLabel": "SND grėsmė",
  "fireBallDiameterFieldAlias": "SND Fireball skersmuo",
  "lpgSafeDistanceFieldAlias": "SND saugus atstumas",
  "smallLPGTank": "Mažas SND rezervuaras",
  "largeLPGTank": "Didelis SND rezervuaras",
  "commercialResidentialLPGTank": "Komercinis / gyvenamasis SND rezervuaras",
  "smallLPGTruck": "Mažas SND sunkvežimis",
  "semiTankerLPG": "Puspriekabė su SND"
});