define({
  "taskUrl": "Matymo lauko paslaugos URL",
  "portalURL": "Nurodykite ArcGIS Online organizacijos arba Portal for ArcGIS URL",
  "portalURLError": "Sukonfigūruotas jūsų ArcGIS Online organizacijos arba Portal for ArcGIS URL netinkamas.",
  "privilegeError": "Jūsų naudotojo rolė negali vykdyti analizės. Kad galėtumėte atlikti analizę, jūsų organizacijos administratorius turi jums suteikti tam tikras <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">teises</a>.",
  "noServiceError": "Aukščių analizės paslauga nepasiekiama. Peržiūrėkite savo ArcGIS Online organizacijos arba Portal for ArcGIS konfigūracijas.",
  "serviceURLPlaceholder": "Įveskite matymo lauko geoduomenų apdorojimo užduoties URL",
  "setTask": "Taikyti",
  "setTaskTitle": "Nustatyti matymo lauko geoduomenų apdorojimo užduotį",
  "serviceURLError": "Šiuo valdikliu bandoma sukonfigūruoti geoduomenų apdorojimo užduotis yra netinkama. Pasirinkite tinkamą matymo lauko geoduomenų apdorojimo užduoties URL.",
  "defaultMilsForAnglesLabel": "Nustatyti kampų tūkstantąsias kaip numatytąsias",
  "defaultObserverHeightLabel": "Numatytieji stebėtojo aukščio vienetai",
  "defaultObservableDistanceLabel": "Numatytieji stebimo atstumo vienetai",
  "units": {
    "miles": "Mylios",
    "kilometers": "Kilometrai",
    "feet": "Pėdos",
    "meters": "Metrai",
    "yards": "Jardai",
    "nauticalMiles": "Jūrmylės"
  },
  "helpIconTooltip": "Darbinio sluoksnio sąrašas automatiškai užpildytas dabartinio internetinio žemėlapio poligonų geometrijos tipo sluoksniais.",
  "selectOperationalLayerLabel": "Pasirinkite rezultatų darbinį sluoksnį",
  "lineOfSightTabTitle": "Matymo linija",
  "symbologyTabTitle": "Simbolizacija",
  "transparency": "Permatomumas",
  "outline": "Kontūras",
  "fill": "Užpildas (spalva taikoma, tik kai pasirinktas vientisas stilius)",
  "style": "Stilius",
  "selectOpLayerLabel": "Pasirinkite rezultatų darbinį sluoksnį",
  "selectDefaultMeasurementLabel": "Pasirinkite numatytąjį matavimo vienetą",
  "visibleSectionLabel": "Matoma sritis",
  "nonVisibleSectionLabel": "Nematoma sritis",
  "visibleSectionButtonLabel": "Konfigūruoti matomos srities nustatymus",
  "nonVisibleSectionButtonLabel": "Konfigūruoti nematomos srities nustatymus",
  "colorPicker": "Spalvos parinkiklis",
  "lineStyles": {
    "esriSLSDash": "Brūkšnys",
    "esriSLSDashDot": "Brūkšnys taškas",
    "esriSLSDashDotDot": "Brūkšnys taškas taškas",
    "esriSLSDot": "Taškas",
    "esriSLSLongDash": "Ilgas brūkšnys",
    "esriSLSLongDashDot": "Ilgas brūkšnys taškas",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trumpas brūkšnys",
    "esriSLSShortDashDot": "Trumpas brūkšnys taškas",
    "esriSLSShortDashDotDot": "Trumpas brūkšnys taškas taškas",
    "esriSLSShortDot": "Trumpas taškas",
    "esriSLSSolid": "Vientisas"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atgal",
    "esriSFSCross": "Kryžius",
    "esriSFSDiagonalCross": "Įstrižai",
    "esriSFSForwardDiagonal": "Pirmyn",
    "esriSFSHorizontal": "Horizontaliai",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vientisas",
    "esriSFSVertical": "Vertikaliai"
  }
});