define({
  "taskUrl": "Viewshed Service URL",
  "portalURL": "Specificare l'URL dell'organizzazione ArcGIS Online o Portal for ArcGIS",
  "portalURLError": "L'URL dell'organizzazione ArcGIS Online o di Portal for ArcGIS configurato non è valido.",
  "privilegeError": "Il ruolo utente assegnato non consente di eseguire analisi. Per poter eseguire l'analisi, l'amministratore dell'organizzazione deve concedere all’utente determinati <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegi</a>.",
  "noServiceError": "Servizio di analisi elevazione non disponibile. Verificare le configurazioni dell’organizzazione ArcGIS Online o di Portal for ArcGIS.",
  "serviceURLPlaceholder": "Inserire l’URL dell’attività del campo di visibilità",
  "setTask": "Imposta",
  "setTaskTitle": "Inserire l’attività del campo di visibilità",
  "serviceURLError": "L’attività di geoprocessing che si sta tentando di configurare con questo widget non è valida. Selezionare un URL valido per l’attività di geoprocessing del campo di visibilità.",
  "defaultMilsForAnglesLabel": "Imposta miglia per angoli come impostazione predefinita",
  "defaultObserverHeightLabel": "Unità altezza dell’osservatore predefinita",
  "defaultObservableDistanceLabel": "Unità distanza dell’osservatore predefinita",
  "units": {
    "miles": "Miglia",
    "kilometers": "Chilometri",
    "feet": "Piedi",
    "meters": "Metri",
    "yards": "Iarde",
    "nauticalMiles": "Miglia nautiche"
  },
  "helpIconTooltip": "L'elenco dei layer operativi è popolato con i layer della mappa Web corrente che sono di tipo a geometria poligonale.",
  "selectOperationalLayerLabel": "Selezionare un layer operativo per i risultati",
  "lineOfSightTabTitle": "Campo visivo",
  "symbologyTabTitle": "Simbologia",
  "transparency": "Trasparenza",
  "outline": "Outline",
  "fill": "Riempimento (Il colore si applica solo quando lo stile è impostato su tinta unita)",
  "style": "Stile",
  "selectOpLayerLabel": "Selezionare un layer operativo per i risultati",
  "selectDefaultMeasurementLabel": "Selezionare un'unità di misura predefinita",
  "visibleSectionLabel": "Sezione visibile",
  "nonVisibleSectionLabel": "Sezione non visibile",
  "visibleSectionButtonLabel": "Configura impostazioni sezione visibile",
  "nonVisibleSectionButtonLabel": "Configura impostazioni sezione non visibile",
  "colorPicker": "Selettore colore",
  "lineStyles": {
    "esriSLSDash": "Trattino",
    "esriSLSDashDot": "Trattino punto",
    "esriSLSDashDotDot": "Linea punto punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Trattino lungo",
    "esriSLSLongDashDot": "Trattino lungo punto",
    "esriSLSNull": "Layer di Network Dataset",
    "esriSLSShortDash": "Trattino corto",
    "esriSLSShortDashDot": "Trattino corto punto",
    "esriSLSShortDashDotDot": "Trattino corto punto punto",
    "esriSLSShortDot": "Punto corto",
    "esriSLSSolid": "Intera"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Indietro",
    "esriSFSCross": "Croce",
    "esriSFSDiagonalCross": "Diagonale",
    "esriSFSForwardDiagonal": "Avanti",
    "esriSFSHorizontal": "Orizzontale",
    "esriSFSNull": "Layer di Network Dataset",
    "esriSFSSolid": "Intera",
    "esriSFSVertical": "Verticale"
  }
});