define({
  "_widgetLabel": "Editor d'atributs per lots",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nom de la capa",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "No s'ha configurat cap capa editable",
  "editorPopupTitle": "Editor d'atributs per lots",
  "editorPopupSaveBtn": "Desa",
  "editorPopupMultipleValues": "",
  "clear": "Esborra",
  "featuresUpdated": "Entitats actualitzades: ${0}/${1}",
  "featuresSelected": "Entitats seleccionades: ${0}",
  "featuresSkipped": "Omès",
  "featuresNoPermision": "S'han seleccionat ${0} entitats, però no teniu permís d'edició.",
  "search": "Cerca",
  "queryInput": "Introduïu el valor que vulgueu consultar",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Definiu el filtre correctament.",
  "filterPopup": "Filtra la capa",
  "filterAppend": "Si ja existeix un filtre al mapa web per a aquesta capa",
  "filterAppendOR": "Afegeix qualsevol expressió al filtre de mapa existent",
  "filterAppendAND": "Afegeix totes les expressions al filtre de mapa existent",
  "cancel": "Cancel·la",
  "noValue": "Sense valor",
  "emptyString": "Cadena buida",
  "existingValue": "Mantén el valor existent",
  "newDate": "Data nova",
  "valueChooser": "Seleccioneu o escriviu un valor",
  "ok": "D'acord",
  "drawBox": {
    "point": "Punt",
    "line": "Línia",
    "polyline": "Polilínia",
    "freehandPolyline": "Polilínia a mà alçada",
    "extent": "Extensió",
    "polygon": "Polígon",
    "freehandPolygon": "Polígon a mà alçada",
    "clear": "Esborra",
    "addPointToolTip": "Feu clic per seleccionar en aquesta àrea",
    "addShapeToolTip": "Dibuixa una forma per seleccionar entitats",
    "freehandToolTip": "Manteniu premut per dibuixar una forma i seleccionar entitats",
    "startToolTip": "Dibuixa una forma per seleccionar entitats"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "L'entitat de ${0} ha retornat un ID no vàlid",
    "noSelectedLayers": "No s'ha seleccionat cap capa amb registres per actualitzar",
    "inputValueError": "Valor no vàlid al formulari",
    "saveError": "No es poden desar ${0} entitats",
    "requiredValue": "Valor necessari"
  }
});