define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Získejte přístup k informačním grafikám a zprávám, které poskytují shrnutí klíčových ukazatelů a dat pro jakoukoli oblast.</div><br><div>Vyberte na mapě bod nebo polygon, vyhledejte adresu nebo místo, nakreslete polygon nebo umístěte do mapy špendlík pro zobrazení klíčových indikátorů a informací o oblasti.</div>",
  "defineWhichInfographics": "Definovat, jaké informační grafiky jsou dostupné ve widgetu:",
  "defineWhichReports": "Definovat, jaké zprávy jsou dostupné ve widgetu:",
  "defaultValues": "Výchozí hodnoty:",
  "disable": "Zakázat",
  "drawFreehandPolygon": "Nakreslit polygon od ruky",
  "drawPolygon": "Kreslit polygon",
  "driveTime": "Doba jízdy",
  "dropPin": "Umístit špendlík",
  "dynamicHTML": "Dynamické HTML",
  "exportOptions": "Možnosti exportu:",
  "home": "Domů",
  "image": "Obrázek",
  "infographics": "Informační grafika",
  "invalidValueRing": "Hodnoty musí být v rozsahu 0 až 1000.",
  "invalidValueDTWT": "Hodnoty musí být v rozsahu 0 až 300.",
  "km": "km",
  "makeDefault": "Nastavit jako výchozí",
  "miles": "mil",
  "minutes": "minut",
  "options": "Možnosti:",
  "pdf": "PDF",
  "print": "Tisk",
  "radius": "Poloměr",
  "removeDefault": "Odstranit výchozí",
  "reports": "Zprávy",
  "rings": "Kružnice",
  "searchTextBox": "Textové pole vyhledávání",
  "selectCountryOrRegion": "Vyberte stát nebo oblast:",
  "thisEntryIsNotValid": "Tento záznam není platný.",
  "time": "Čas",
  "walkTime": "Doba chůze"
});