define({
  "_widgetLabel": "การรวมข้อมูล",
  "startPage": {
    "defaultStartPageInstructions": "วิดเจ็ตนี้จะช่วยสนับสนุนการประมวลผลและการส่งข้อมูลจากไฟล์ไปยังชั้นข้อมูลที่เลือกในแผนที่<br/> <br/> จะต้องคั่นระหว่างค่าภายในไฟล์ด้วยคอมมา แท็บ เซมิโคลอน หรือขีดตั้ง",
    "dragDrop": "ลากและวาง",
    "browse": "เรียกดูไฟล์",
    "or": "หรือ",
    "userPrivilege": "บัญชีของคุณไม่ได้รับอนุญาตให้สร้างหรือปรับเปลี่ยนข้อมูล",
    "userCredits": "${widgetName} ต้องการเครดิตในการใช้งานตัวระบุตำแหน่ง ${locator}",
    "contactAdmin": "ติดต่อผู้ดูแลระบบขององค์กร เพื่อร้องขอเครดิตเพิ่มเติม",
    "contactAdminEdit": "ติดต่อผู้ดูแลระบบขององค์กร เพื่อร้องขอสิทธิ์การแก้ไข",
    "canUseLocator": "ตัวระบุตำแหน่ง ${locator} จะถูกใช้ในการระบุตำแหน่งฟีเจอร์",
    "notEnoughCredits": "เครดิตไม่เพียงพอ",
    "locationAndField": "ตำแหน่งและข้อมูลฟิลด์",
    "locationAndFieldHint": "เลือกค่าจากไฟล์ที่ควรใช้ในการอัพเดตชั้นข้อมูลเป้าหมาย",
    "cannotUseLocator": "ไม่สามารถใช้ ${widgetName} ได้",
    "noAnonymousEdit": "ชั้นข้อมูล ${layerName} ไม่รองรับการแก้ไขแบบไม่เปิดเผยตัวตน",
    "pleaseLogin": "ลงชื่อเข้าใช้องค์กร ${org} หรือติดต่อผู้ดูแลระบบขององค์กร เพื่อร้องขอให้เปิดใช้งานการแก้ไขแบบไม่เปิดเผยตัวตน",
    "invalidEdit": "สิทธิ์ไม่ถูกต้อง",
    "unableToAccess": "ไม่สามารถเข้าใช้งาน ${layerName} ได้",
    "appropriateCredentials": "ตรวจสอบว่าคุณลงชื่อเข้าใช้ด้วยข้อมูลประจำตัวที่ถูกต้อง",
    "shared": "ติดต่อผู้ดูแลระบบขององค์กร เพื่อร้องขอการเข้าใช้งานชั้นข้อมูล ${layerName}",
    "targetLayerLabel": "ชั้นข้อมูลเป้าหมาย",
    "homeButtonLabel": "หน้าหลัก",
    "mappingErrorMsg": "คลิกลูกศรถัดไป เพื่อกำหนดค่าฟิลด์"
  },
  "mapping": {
    "schemaMapping": "ข้อมูลฟิลด์",
    "schemaMappingHint": "เลือกฟิลด์จากไฟล์ที่สัมพันธ์กับฟิลด์ในชั้นข้อมูล",
    "locationMapping": "ข้อมูลสถานที่",
    "locationMappingHint": "เลือกประเภทที่อยู่หรือข้อมูลพิกัดที่ต้องการจากไฟล์"
  },
  "locationMapping": {
    "locationMappingPageHint": "เลือกประเภทของที่ตั้ง",
    "useAddress": "ระบุตำแหน่งโดยใช้ที่อยู่",
    "useAddressHint": "ข้อมูลจะมีข้อมูลที่อยู่",
    "useCoordinates": "ระบุตำแหน่งโดยใช้พิกัด",
    "useCoordinatesHint": "ข้อมูลจะมีค่าพิกัด X/Y"
  },
  "address": {
    "addressPageHint": "เลือกประเภทที่อยู่",
    "singleField": "ฟิลด์เดี่ยว",
    "singleFieldHint": "เลือกฟิลด์ที่มีข้อมูลที่อยู่",
    "multiField": "ฟิลด์หลายช่่อง",
    "multiFieldHint": "เลือกฟิลด์ที่มีข้อมูลที่อยู่"
  },
  "coordinates": {
    "coordinatesPageHint": "เลือกฟิลด์ที่มีข้อมูลพิกัด"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "เลือกฟิลด์ต้นทางที่แมปกับฟิลด์เป้าหมาย",
    "sourceField": "การจับคู่ฟิลด์ต้นทาง",
    "targetField": "เป้าหมายสนาม"
  },
  "buttons": {
    "addToMap": "เพิ่มไปยังแผนที่",
    "submit": "ส่ง",
    "download": "ดาวน์โหลด"
  },
  "review": {
    "matched": "พบ",
    "reviewMatched": "ตำแหน่งที่พบ",
    "reviewMatchedHint": "ตรวจสอบตำแหน่งที่พบ",
    "unMatched": "ไม่พบ",
    "reviewUnMatched": "ไม่พบตำแหน่ง",
    "reviewUnMatchedHint": "ตรวจสอบตำแหน่งที่ไม่พบ รายการที่ไม่ได้รับการแก้ไขจะไม่ถูกส่ง",
    "duplicate": "รายการซ้ำ",
    "reviewDuplicate": "ตำแหน่งซ้ำ",
    "reviewDuplicateHint": "ตรวจสอบตำแหน่งที่พบในชั้นข้อมูลอยู่แล้ว รายการที่ไม่ได้รับการจัดการจะไม่ถูกส่ง",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "ใช้:",
    "fromLayer": "ข้อมูลเป้าหมาย",
    "target": "เป้าหมาย",
    "source": "แหล่ง",
    "fromFile": "แหล่งที่มาของข้อมูล",
    "locationControlHint": "ตรวจสอบข้อมูลที่อยู่",
    "duplicateAction": "เลือกการดำเนินการ",
    "item": "บันทึกข้อมูล:",
    "locateFeature": "ระบุตำแหน่งฟีเจอร์",
    "removeFeature": "ลบฟีเจอร์",
    "featureLocated": "ตำแหน่งที่พบ",
    "valuesDoNotMatch": "ไม่ตรงกับค่าที่มีอยู่",
    "sync": "ซิงค์ข้อมูลที่อยู่กับข้อมูลฟิลด์",
    "noFeaturesSaved": "ไม่มีฟีเจอร์ที่บันทึกสำเร็จ",
    "someFeaturesSaved": "บันทึกสำเร็จ ${num} ฟีเจอร์",
    "someFeaturesNotSaved": "บันทึกไม่สำเร็จ ${num} ฟีเจอร์",
    "feature": "ตรวจสอบข้อมูลฟีเจอร์",
    "locationInfo": "ตรวจสอบข้อมูลตำแหน่ง",
    "selectValue": "เลือกค่า",
    "reviewData": "ตรวจสอบข้อมูล",
    "reviewDataHint": "ตรวจสอบข้อมูลของคุณก่อนที่จะส่งชั้นข้อมูล",
    "reviewFeatureHint": "ตรวจสอบหรือแก้ไขฟีเจอร์และข้อมูลตำแหน่งของคุณ",
    "duplicateModify": "รายการซ้ำ ต้องเปลี่ยนแปลง",
    "duplicateSave": "บันทึกเป็นฟีเจอร์ใหม่"
  },
  "warningsAndErrors": {
    "invalidCSV": "เกิดข้อผิดพลาดในการดึงข้อมูลรายการจาก CSV ตรวจสอบว่าเลือกไฟล์ CSV ที่ถูกต้องหรือไม่",
    "noLayersWarning": "ไม่ได้กำหนดค่าชั้นข้อมูลเป้าหมายที่ถูกต้อง ตรวจสอบการกำหนดค่า",
    "loadWarning": "วิดเจ็ตต้องการแหล่งข้อมูลฟีเจอร์เซอร์วิส กำหนดค่าวิดเจ็ตเพื่อกำหนดแหล่งข้อมูล",
    "saveError": "เกิดข้อผิดพลาดในการบันทึกฟีเจอร์",
    "consumesCredits": "เครื่องมือนี้ใช้เครดิตเมื่อใช้กับ ArcGIS Online World Geocoding Service",
    "noValue": "เลือกฟิลด์",
    "mappingTitle": "",
    "locationMappingComplete": "การแมปตำแหน่งเสร็จสมบูรณ์",
    "fieldMappingComplete": "การแมปฟิลด์เสร็จสมบูรณ์",
    "settingsCleared": "การตั้งค่าจะถูกล้างออก",
    "proceed": "คุณต้องการดำเนินงานหรือไม่",
    "itemMoveMatch": "ระบุตำแหน่งรายการและย้ายไปยังรายการตำแหน่งที่พบแล้ว",
    "itemMoveUnMatched": "ไม่สามารถระบุตำแหน่งรายการได้ ย้ายไปยังรายการไม่พบตำแหน่ง",
    "itemWillBeLocated": "รายการจะถูกลบออกจากรายการตำแหน่งซ้ำ",
    "cannotLocate": "ไม่สามารถระบุตำแหน่งรายการได้ ตรวจสอบข้อมูลตำแหน่ง",
    "invalidMessage": "ค่าไม่ถูกต้อง",
    "rangeMessage": "ค่าต้องน้อยกว่า ${num} อักขระ",
    "locatorError": "ตัวระบุตำแหน่งไม่ถูกต้องหรือไม่สามารถเข้าใช้งานได้",
    "notConfigured": "ไม่ได้กำหนดค่าตัวระบุตำแหน่งสำหรับตัวเลือกการระบุตำแหน่งปัจจุบัน",
    "noMoreLocators": "ไม่ได้กำหนดค่าตัวระบุตำแหน่งเพิ่มเติม"
  },
  "featureToolbar": {
    "locate": "ระบุตำแหน่ง",
    "save": "จัดเก็บบันทึกข้อมูล",
    "cancel": "ยกเลิกการแก้ไข",
    "cancelTitle": "ยกเลิกการแก้ไข",
    "cancelMessage": "ยกเลิกการแก้ไขบันทึกข้อมูลปัจจุบันหรือไม่"
  }
});