define({
  "_widgetLabel": "Graf",
  "executeChartTip": "Kliknutím na jednu z nasledujúcich položiek úlohy spustite graf.",
  "invalidConfig": "Neplatná konfigurácia.",
  "noneChartTip": "Pre tento widget nebol konfigurovaný žiadny graf.",
  "chartParams": "Možnosti",
  "charts": "GRAFY",
  "apply": "POUŽIŤ",
  "useSpatialFilter": "Použiť priestorový filter pre limitovanie prvkov",
  "useCurrentMapExtent": "Iba prvky pretínajúce aktuálnu oblasť mapy",
  "drawGraphicOnMap": "Iba prvky pretínajúce oblasť definovanú používateľom",
  "chartResults": "Výsledky grafu",
  "clearResults": "Vyčistiť výsledky",
  "noPermissionsMsg": "Nemáte oprávnenie na prístup k tejto službe.",
  "specifySpatialFilterMsg": "Nastavte priestorový filter pre túto úlohu.",
  "queryError": "Dopyt zlyhal.",
  "noResults": "Nebol nájdený žiadny prvok.",
  "category": "Kategória",
  "count": "Počet",
  "label": "Označenie",
  "horizontalAxis": "Vodorovná os",
  "verticalAxis": "Zvislá os",
  "dataLabels": "Popisy údajov",
  "color": "Farba",
  "colorful": "Farebná",
  "monochromatic": "Monochromatická",
  "tasks": "Úlohy",
  "results": "Výsledky",
  "applySpatialFilterToLimitResults": "Použiť priestorový filter pre obmedzenie výsledkov",
  "useCurrentExtentTip": "Čiastočne alebo úplne v rámci aktuálneho rozsahu mapy",
  "useDrawGraphicTip": "Čiastočne alebo úplne v rámci útvaru nakresleného na mape",
  "useFeaturesTip": "Na základe ich umiestnenia vzhľadom na prvky v inej vrstve",
  "noSpatialLimitTip": "Neobmedzovať výsledky priestorovo",
  "applySearchDistance": "Použiť vyhľadávaciu vzdialenosť",
  "spatialRelationship": "Priestorový vzťah",
  "relatedLayer": "Súvisiaca vrstva",
  "clear": "Vyčistiť",
  "bufferDistance": "Vzdialenosť obalovej zóny (Buffer)",
  "miles": "Míle",
  "kilometers": "Kilometre",
  "feet": "Stopy",
  "meters": "Metre",
  "yards": "Yardy",
  "nauticalMiles": "Námorné míle",
  "back": "Späť",
  "execute": "Použiť",
  "backCharts": "Späť ku grafom",
  "backOptions": "Späť k možnostiam",
  "clearCharts": "Vyčistiť všetky grafy"
});