define({
  "layersPage": {
    "allLayers": "Todas as Camadas",
    "title": "Selecione um modelo para criar feições ou clique em uma feição no mapa para editá-lo",
    "generalSettings": "Configurações Gerais",
    "layerSettings": "Configurações da Camada",
    "webmapSettingsRadioBtnLabel": "Honrar configurações no mapa da web",
    "customSettingsRadioBtnLabel": "Personalizar configurações",
    "smartActionsTabTitle": "Ações Inteligentes",
    "attributeActionsTabTitle": "Ações do Atributo",
    "geocoderSettingsText": "Configurações do Geocodificador",
    "editDescription": "Fornecer texto a ser exibido no painel de edição",
    "editDescriptionTip": "Este texto é exibido sobre o seletor de Modelos, mantenha em branco para nenhum texto.",
    "promptOnSave": "Solicite para salvar edições não salvas quando o formulário estiver fechado ou alternado para o próximo registro",
    "promptOnSaveTip": "Exibe um lembrete quando a feição atual tem edições não salvas. (A cópia de múltiplas feições é salva automaticamente).",
    "promptOnDelete": "Exigir confirmação ao excluir um registro",
    "promptOnDeleteTip": "Exibe um lembrete quando o usuário clica em excluir para confirmar a ação.",
    "removeOnSave": "Remover feição da seleção ao salvar",
    "removeOnSaveTip": "Opção para remover a feição do conjunto de seleção quando o registro for salvo.  Se ele for o único registro selecionado, o painel é trocado de volta para a página do modelo.",
    "useFilterEditor": "Utilizar filtro do modelo de feição",
    "useFilterEditorTip": "Opção para utilizar o seletor do Modelo de Filtro que fornece o recurso de visualizar o modelo de uma camada ou procurar modelos pelo nome.",
    "groupFilteredTemplates": "Agrupar resultados da pesquisa",
    "groupFilteredTemplatesTip": "Opção de agrupar resultados da pesquisa por camada.",
    "displayShapeSelector": "Mostrar opções de desenho",
    "createNewFeaturesFromExisting": "Permitir ao usuário criar novas feições a partir de feições existentes",
    "createNewFeaturesFromExistingTip": "Opção para permitir ao usuário copiar a feição existente para criar novas feições",
    "copiedFeaturesOverrideDefaults": "Valores de feições copiadas substituem os padrões",
    "copiedFeaturesOverrideDefaultsTip": "Os valores das feições copiadas substituirão os valores de modelo padrão somente para os campos correspondentes",
    "displayShapeSelectorTip": "Opção para mostrar uma lista de opções de desenho válidas para o modelo selecionado.",
    "displayPresetTop": "Exibir lista de valores pré-definidos no topo",
    "displayPresetTopTip": "Opção para mostrar a lista de valores pré-definidos acima do seletor de modelos.",
    "listenToGroupFilter": "Aplica valores de filtro a partir do widget Filtrar Grupo para os campos Preset",
    "listenToGroupFilterTip": "Quando um filtro for aplicado no widget Filtrar Grupo, aplique o valor para um campo correspondente na lista de valor do Preset.",
    "keepTemplateActive": "Mantenha o modelo selecionado ativo",
    "editLayerAddedFromAddData": "Permitir a edição de camadas adicionadas a partir do widget Adicionar Dados",
    "editLayerAddedFromAddDataTip": "Camadas editáveis adicionadas ao aplicativo usando o widget Adicionar Dados podem ser editadas",
    "keepTemplateActiveTip": "Quando o seletor de modelo for exibido, se um modelo foi selecionado anteriormente, selecione-o novamente.",
    "geometryEditDefault": "Habilitar edição de geometria por padrão",
    "autoSaveEdits": "Salvar novas feições automaticamente",
    "enableAttributeUpdates": "Botão de atualização Mostrar Ações do Atributo",
    "enableAutomaticAttributeUpdates": "Solicitar automaticamente Ações do Atributo após a atualização de geometria",
    "enableLockingMapNavigation": "Habilitar o bloqueio da navegação de mapas",
    "enableMovingSelectedFeatureToGPS": "Habilitar o movimento da feição de ponto selecionada para a localização do GPS",
    "enableMovingSelectedFeatureToXY": "Habilitar o movimento da feição de ponto selecionada para a localização XY",
    "featureTemplateLegendLabel": "Configurações de Valor do Modelo de Feição e Filtro",
    "saveSettingsLegendLabel": "Salvar Configurações",
    "geometrySettingsLegendLabel": "Configurações de Geometria",
    "actionsSettingsLegendLabel": "Configurações de Ações",
    "buttonPositionsLabel": "Botões Posição de Salvar, Excluir, Voltar e Cancelar",
    "belowEditLabel": "Abaixo de Editar Formulário",
    "aboveEditLabel": "Acima de Editar Formulário",
    "switchToMultilineInput": "Alterne para entrada de múltiplas linhas quando o comprimento do campo exceder",
    "enableValuePicker": "Habilitar seletor do valor de intersecção",
    "enableValuePickerHint": "Exibir um lembrete quando múltiplos valores estiverem disponíveis para um campo com uma ação do atributo de intersecção",
    "expandRelatedTable": "Expandir todas as camadas/tabelas relacionadas ao carregar",
    "expandMainTable": "Expandir todas as camadas principais ao carregar",
    "layerSettingsTable": {
      "allowDelete": "Permitir Exclusão",
      "allowDeleteTip": "Permitir Excluir - Opção para permitir que o usuário exclua uma feição; desativado se a camada não suportar exclusão",
      "edit": "Editável",
      "editTip": "Editável - Opção para incluir a camada no widget",
      "label": "Camada",
      "labelTip": "Camada - Nome da camada como definido no mapa",
      "update": "Desabilitar Edição de Geometria",
      "updateTip": "Desabilitar Edição de Geometria - Opção para desativar a habilidade de mover a geometria uma vez posicionada ou mover a geometria em uma feição existente",
      "allowUpdateOnly": "Atualizar Somente",
      "allowUpdateOnlyTip": "Somente Atualizar - Opção para permitir somente a modificação de feições existentes, verificada por padrão e desativada se a camada não suportar a criação de novas feições",
      "fieldsTip": "Modificar os campos a serem editados e definir Atributos Inteligentes",
      "actionsTip": "Ações - Opção para editar campos ou acessar camadas/tabelas relacionadas",
      "description": "Descrição",
      "descriptionTip": "Descrição - Opção para inserir texto para exibir na parte superior da página de atributos.",
      "relationTip": "Visualizar tabelas e camadas relacionadas"
    },
    "editFieldError": "As modificações de campo e atributos Inteligentes não estão disponíveis para camadas que não são editáveis",
    "noConfigedLayersError": "O Editor Inteligente exige um ou mais camadas editáveis",
    "toleranceErrorMsg": "Valor de Tolerância de Intersecção Padrão inválido",
    "pixelsToleranecErrorMsg": "Valor de Tolerância de Pixels Padrão inválido",
    "invalidMaxCharacterErrorMsg": "Valor inválido na alternância para entrada de múltiplas linhas",
    "featuresSelectionTolerance": "Defina a tolerância para a seleção de feição (pixels)",
    "featuresSelectionToleranceTooltip": "Permite que os usuários abram facilmente o painel de edição de atributos clicando no elemento",
    "featuresSelectionToleranceErrorMsg": "Valor de tolerância de seleção de feição inválido",
    "autoSaveAttrUpdates": "Salvar atualizações de atributos automaticamente"
  },
  "editDescriptionPage": {
    "title": "Defina o texto de visão geral dos atributos para <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Configure campos para <b>${layername}</b>",
    "copyActionTip": "Ações do Atributo",
    "editActionTip": "Ações Inteligentes",
    "description": "Utilize o botão de edição de Ações para ativar Atributos Inteligentes em uma camada. Os Atributos Inteligentes podem exigir, ocultar ou desativar um campo com base em valores em outros campos. Utilize o botão de cópia de Ações para ativar e definir a fonte do valor de campo por intersecção, endereço, coordenadas e pré-definição.",
    "fieldsNotes": "* é um campo exigido.  Se você desmarcar Exibir para este campo e a edição do modelo não preencher este valor de campo, você não poderá salvar um novo registro.",
    "smartAttachmentText": "Configurar Ações Inteligentes para anexos",
    "smartAttachmentPopupTitle": "Configurar Ações Inteligentes para anexos em <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Selecione pelo menos um campo de exibição para a camada ${layerName}",
    "fieldsSettingsTable": {
      "display": "Exibir",
      "displayTip": "Exibir - Determina se o campo não é visível",
      "edit": "Editável",
      "editTip": "Editável - Verifique se o campo está presente no formulário de atributo",
      "fieldName": "Nome",
      "fieldNameTip": "Nome - Nome do campo definido no banco de dados",
      "fieldAlias": "Nome Alternativo",
      "fieldAliasTip": "Nome Alternativo - Nome do campo definido no mapa",
      "canPresetValue": "Ajustar",
      "canPresetValueTip": "Pré-Configurado - Opção para mostrar o campo na lista do campo pré-configurado e permitir ao usuário configurar o valor antes da edição",
      "actions": "Ações",
      "actionsTip": "Ações - Altera a ordem dos campos ou configura os Atributos Inteligentes"
    },
    "smartAttSupport": "Atributos Inteligentes não são suportados em campos do banco de dados exigidos"
  },
  "actionPage": {
    "title": "Configurar as Ações do Atributo para <b>${fieldname}</b>",
    "smartActionTitle": "Configurar Ações Inteligentes para <b>${fieldname}</b>",
    "description": "As ações estão sempre desativadas a menos que você especifique os critérios nos quais elas serão ativadas.  As ações são processadas em ordem e somente uma ação será ativada por campo.  Utilize o botão Editar Critérios para definir os critérios.",
    "copyAttributesNote": "Desabilitar qualquer ação com um nome de grupo será o mesmo que editar esta ação independentemente e removerá a ação deste campo do respectivo grupo.",
    "searchPlaceHolder": "Pesquisar",
    "expandAllLabel": "Expandir todas as camadas",
    "selectAllLabel": "Selcionar todos os campos",
    "domainListTitle": "Campos de domínio",
    "noValidFieldTypeMsg": "Não há camada apropriada disponível no mapa para este tipo de dados",
    "actionsSettingsTable": {
      "rule": "Ação",
      "ruleTip": "Ação - Ação executada quando o critério é satisfatório",
      "expression": "Expressão",
      "expressionTip": "Expressão - A expressão resultante em formato SQL a partir dos critérios definidos",
      "groupName": "Nome do Grupo",
      "groupNameTip": "Nome do Grupo - Exibe o nome do grupo do qual a expressão é aplicada",
      "actions": "Critérios",
      "actionsTip": "Critérios - Altera a ordem da regra e define os critérios quando ela for ativada"
    },
    "copyAction": {
      "description": "A fonte do valor de campo é processada para que se ativada até que um critério válido seja ativado ou a lista seja completada. Utilize o botão Editar Critérios para definir os critérios.",
      "intersection": "Intersecção",
      "coordinates": "Coordenadas",
      "address": "Endereço",
      "preset": "Ajustar",
      "actionText": "Ações",
      "criteriaText": "Critérios",
      "enableText": "Habilitado"
    },
    "actions": {
      "hide": "Ocultar",
      "required": "Exigido",
      "disabled": "Desabilitado"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Aviso: Editar independentemente removerá a ação de atributo selecionada associada a este campo do grupo",
      "editGroupHint": "Aviso: Editar independentemente removerá a ação inteligente selecionada associada a este campo do grupo",
      "popupTitle": "Escolher opção de edição",
      "editAttributeGroup": "A ação de atributo selecionada é definida no grupo. Escolha uma das seguintes opções para editar a ação do atributo:",
      "expression": "A expressão da ação inteligente selecionada é definida do grupo. Escolha uma das seguintes opções para editar a expressão de ação inteligente:",
      "editGroupButton": "Editar Grupo",
      "editIndependentlyButton": "Editar Independentemente"
    }
  },
  "filterPage": {
    "submitHidden": "Enviar dados de atributo para campos mesmo quando ocultos",
    "title": "Configure a expressão para a regra ${action}",
    "filterBuilder": "Configure a ação no campo quando o registro corresponder ${any_or_all} das seguintes expressões",
    "noFilterTip": "Utilizando as ferramentas acima, defina a declaração para quando a ação estiver ativa."
  },
  "geocoderPage": {
    "setGeocoderURL": "Configurar URL do Geocodificador",
    "hintMsg": "Nota: Você está alterando o serviço do geocodificador, certifique-se de atualizar todos os mapeamentos de campo do geocodificador que você configurou.",
    "invalidUrlTip": "A URL ${URL} é inválida ou inacessível."
  },
  "addressPage": {
    "popupTitle": "Endereço",
    "checkboxLabel": "Obter valor do Geocodificador",
    "selectFieldTitle": "Atributo",
    "geocoderHint": "Para alterar o geocodificador, vá até o botão 'Configurações do Geocodificador' em configurações gerais",
    "prevConfigruedFieldChangedMsg": "O atributo configurado anteriormente não é encontrado nas configurações atuais do geocodificador. O atributo foi redefinido para o padrão.",
    "questionMark": "?",
    "consumesCredits": "Esta ferramenta consome créditos quando utilizada com Serviços de Geocodificação Mundial do ArcGIS Online."
  },
  "coordinatesPage": {
    "popupTitle": "Coordenadas",
    "checkboxLabel": "Obter coordenadas",
    "coordinatesSelectTitle": "Sistema de Referência",
    "coordinatesAttributeTitle": "Atributo",
    "mapSpatialReferenceOptionLabel": "Referência Espacial do Mapa",
    "latLongOptionLabel": "Latitude/Longitude",
    "MGRS": "MGRS",
    "allGroupsCreatedMsg": "Todos os grupos possíveis já estão criados",
    "coordinatesSourceTitle": "Origem de coordenadas",
    "featureLocation": "Localização de Feição",
    "myLocation": "Meu Local",
    "LatLong": {
      "y": "Latitude",
      "x": "Longitude",
      "xy": "Longitude Latitude",
      "yx": "Latitude Longitude"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Ajustar",
    "checkboxLabel": "Os campos serão pré-configurados",
    "showOnlyDomainFields": "Mostrar somente campos de domínio",
    "hideInPresetDisplay": "Ocultar na exibição de valor pré-definido",
    "presetValueLabel": "O valor pré-definido é:",
    "changePresetValueHint": "Para alterar este valor pré-definido, vá até o botão \"Definir valores pré-definidos\" em configurações gerais"
  },
  "intersectionPage": {
    "groupNameLabel": "Nome do Grupo",
    "dataTypeLabel": "Tipo de Dados",
    "ignoreLayerRankingCheckboxLabel": "Ignore a classificação de camadas e encontre a feição mais próxima em todas as camadas definidas",
    "intersectingLayersLabel": "Camadas para extrair um valor",
    "layerAndFieldsApplyLabel": "Camadas e campos para aplicar o valor extraído",
    "checkboxLabel": "Obter valor de campo a partir da camada de intersecção",
    "layerText": "Camadas",
    "fieldText": "Campos",
    "actionsText": "Ações",
    "toleranceSettingText": "Configurações de Tolerância",
    "addLayerLinkText": "Adicionar uma Camada",
    "useDefaultToleranceText": "Utilizar Tolerância Padrão",
    "toleranceValueText": "Valor de Tolerância",
    "toleranceUnitText": "Unidade de Tolerância",
    "pixelsUnitText": "Pixels",
    "useLayerName": "- Utilizar Nome da Camada -",
    "noLayersMessage": "Nenhum campo foi encontrado em camadas de mapa que correspondam ao tipo de dados selecionado.",
    "intersectionLayerHint": "A classificação da camada é determinada em ordem decrescente. Use as setas em Ações para reordenar as camadas e alterar a prioridade de interseção."
  },
  "presetAll": {
    "popupTitle": "Definir os valores pré-definidos padrão",
    "deleteTitle": "Excluir valor pré-definido",
    "hintMsg": "Todos os nomes de campo pré-definidos exclusivos são listados aqui. A remoção de um campo pré-definido desativará o respectivo campo como pré-definido em todas as camadas/tabelas."
  },
  "intersectionTolerance": {
    "intersectionTitle": "Tolerância de intersecção padrão para todas as feições",
    "pixelsToleranceTitle": "Tolerância de intersecção padrão (valor de pixel) a ser aplicada somente para feiões de ponto"
  },
  "smartActionsPage": {
    "smartActionLabel": "Configurar Ação Inteligente",
    "addNewSmartActionLinkText": "Adicionar Novo",
    "definedActions": "Ações Definidas",
    "priorityPopupTitle": "Definir Prioridade de Ações Inteligentes",
    "priorityPopupColumnTitle": "Ações Inteligentes",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Nome do Grupo",
    "layerForExpressionLabel": "Camada para Expressão",
    "layerForExpressionNote": "Nota: os campos desta camada são usados ​​para definir os critérios da expressão. 'Camadas e campos para aplicar em' exibe apenas camadas e tabelas que têm os campos definidos na Expressão.",
    "expressionText": "Expressão",
    "editExpressionLabel": "Editar Expressão",
    "layerAndFieldsApplyLabel": "Camadas e campos para aplicar em",
    "submitAttributeText": "Enviar dados de atributo para campos mesmo quando ocultos",
    "priorityColumnText": "Prioridade",
    "requiredGroupNameMsg": "Este valor é exigido",
    "uniqueGroupNameMsg": "Digite um nome de grupo único, o grupo com este nome já existe.",
    "deleteGroupPopupTitle": "Excluir Grupo de Ação Inteligente",
    "deleteGroupPopupMsg": "A exclusão do grupo resultará na remoção da expressão de todas as Ações de Campos associados.",
    "invalidExpression": "Expressão não pode ficar em branco",
    "warningMsgOnLayerChange": "A expressão definida e os campos nos quais ela é aplicada serão apagados.",
    "smartActionsTable": {
      "name": "Nome",
      "expression": "Expressão",
      "definedFor": "Definido Para"
    }
  },
  "attributeActionsPage": {
    "name": "Nome",
    "type": "Tipo",
    "deleteGroupPopupTitle": "Excluir Grupo de Ação do Atributo",
    "deleteGroupPopupMsg": "A exclusão do grupo resultará na remoção da ação do atributo de todos os campos associados.",
    "alreadyAppliedActionMsg": "Ação ${action} aplicada neste campo no grupo",
    "alreadyAppliedActionLayerMsg": "Ação ${action} aplicada neste campo em Configurações da Camada",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Este grupo não tem campos associados.",
    "presetNoFieldWarningMsg": "Configure pelo menos um campo para o grupo pré-defnido: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Campo",
    "valueLabel": "Valor",
    "selectValueLabel": "Selecionar Valor",
    "domainFieldHintLabel": "O valor selecionado é um domínio de valor codificado. O valor: ${domainValue} será utilizado"
  },
  "presetPopup": {
    "presetValueLAbel": "Valor Pré-Configurado"
  },
  "dataType": {
    "esriFieldTypeString": "Texto",
    "esriFieldTypeInteger": "Número",
    "esriFieldTypeDate": "Data",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Tipo de Data",
    "valueLabel": "Valor",
    "fixed": "Fixo",
    "current": "Atual",
    "past": "Passado",
    "future": "Futuro",
    "popupTitle": "Selecionar Valor",
    "hintForFixedDateType": "Dica: A data e hora especificadas serão utilizadas como valor padrão pré-definido",
    "hintForCurrentDateType": "Dica: A data e hora atuais serão utilizadas como valor padrão pré-definido",
    "hintForPastDateType": "Dica: O valor especificado será subtraído da data e hora atuais para o valor padrão da pré-definição.",
    "hintForFutureDateType": "Dica: O valor especificado será adicionado à data e hora atuais para o valor padrão da pré-definição.",
    "noDateDefinedTooltip": "Nenhuma data definida",
    "relativeDateWarning": "Um valor para data ou hora deve ser especificado para poder salvar o valor pré-definido padrão.",
    "customLabel": "Personalizada"
  },
  "relativeDomains": {
    "fieldSetTitle": "Lista",
    "valueText": "Valor",
    "defaultText": "Padrão",
    "selectedDomainFieldsHint": "Campos de domínio selecionados: ${domainFields}",
    "selectDefaultDomainMsg": "Selecione um domínio de valor padrão ou verifique se a caixa de seleção do domínio padrão selecionado está marcada"
  }
});