define({
  "taskUrl": "URL адрес на услугата Зона на видимост",
  "portalURL": "Посочете URL адреса за Вашата организация в ArcGIS Online или Portal за ArcGIS",
  "portalURLError": "Конфигурираният URL адрес към Вашата организация в ArcGIS Online или Portal for ArcGIS не е валиден.",
  "privilegeError": "Вашата потребителска роля не може да извършва анализ. За да извършите анализ, администраторът на вашата организация трябва да ви предостави определени <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">привилегии</a>.",
  "noServiceError": "Услугата за височинен анализ не е налична. Моля, проверете конфигурациите на Вашата организация в ArcGIS Online или Portal for ArcGIS.",
  "maximumRangeMessage": "Максималният обхват на наблюдение трябва да бъде по-голям от минималния обхват на наблюдение и не може да бъде по-голям от ${limit} ${units}.",
  "serviceURLPlaceholder": "Моля, въведете URL адрес на задачата за геообработка на Зоната за видимост",
  "setTask": "Настройване",
  "setTaskTitle": "Задайте задача за геообработка на Зоната за видимост",
  "serviceURLError": "Задачата за геообработка, която се опитвате да конфигурирате с този изпълним модул, не е валидна. Моля, изберете валиден URL адрес на задачата за геообработка на Зоната за видимост.",
  "defaultMilsForAnglesLabel": "Задайте мил за ъгли по подразбиране",
  "defaultObserverHeightLabel": "Стандартна единица за височина на наблюдател",
  "defaultObservableDistanceLabel": "Стандартна мерна единица за разстояние на наблюдател",
  "defaultObserveHeightLabel": "Стандартна височина на наблюдател",
  "defaultMinimumObservableDistanceLabel": "Стандартно минимално разстояние на наблюдател",
  "defaultMaximumObservableDistanceLabel": "Стандартно максимално разстояние на наблюдател",
  "units": {
    "miles": "Мили",
    "kilometers": "Километри",
    "feet": "Фут",
    "meters": "Метри",
    "yards": "Ярда",
    "nauticalMiles": "Морски мили"
  },
  "helpIconTooltip": "Списъкът на оперативния слой е попълнен със слоеве от текущата уеб карта, които са тип полигонна геометрия.",
  "selectOperationalLayerLabel": "Избиране на оперативен слой за резултати",
  "lineOfSightTabTitle": "Линия на видимост",
  "symbologyTabTitle": "Симвология",
  "transparency": "Прозрачност",
  "outline": "Контур",
  "fill": "Попълване (Цветът се прилага само когато стилът е зададен като плътен)",
  "style": "Стил",
  "selectOpLayerLabel": "Избиране на оперативен слой за резултати",
  "selectDefaultMeasurementLabel": "Избиране на мерна единица по подразбиране",
  "visibleSectionLabel": "Раздел на видимост",
  "nonVisibleSectionLabel": "Раздел на не - видимост",
  "visibleSectionButtonLabel": "Конфигуриране на настройките на раздела на видимост",
  "nonVisibleSectionButtonLabel": "Конфигуриране на настройките на невидимия раздел",
  "colorPicker": "Инструмент за избор на цвят",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире Точка",
    "esriSLSDashDotDot": "Тире Точка Точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Дълго тире",
    "esriSLSLongDashDot": "Дълго тире Точка",
    "esriSLSNull": "Нула",
    "esriSLSShortDash": "Малко тире",
    "esriSLSShortDashDot": "Малко тире Точка",
    "esriSLSShortDashDotDot": "Малко тире Точка Точка",
    "esriSLSShortDot": "Малка точка",
    "esriSLSSolid": "Плътно"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Пресичане",
    "esriSFSDiagonalCross": "Диагонал",
    "esriSFSForwardDiagonal": "Напред",
    "esriSFSHorizontal": "Хоризонтално",
    "esriSFSNull": "Нула",
    "esriSFSSolid": "Плътно",
    "esriSFSVertical": "Вертикално"
  }
});