// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/html dojo/_base/lang dojo/_base/array dojo/on dojo/Evented dojo/aspect dojo/mouse dojo/touch dojo/topic dojo/query ./Mover dojo/dnd/move dijit/_WidgetBase jimu/dijit/Message jimu/utils dojo/NodeList-dom dojo/NodeList-manipulate".split(" "),function(w,b,c,x,d,y,r,t,q,g,z,u,v,A,p,k){var h="click",m=t.enter,n=t.leave;"ontouchstart"in document&&(h=q.press,m=q.enter,n=q.leave);return w([A,y],{type:"",label:"",isMoving:!1,isMouseDown:!1,postCreate:function(){this.inherited(arguments);
if("addBtn"===this.type)this.label="addBtn",this.createAddBtn();else if("empty"===this.type)this.label="empty",this.createEmptyNode();else if("widget"===this.type){if(this.createWidgetNode(),"poolWidgets"===this.listName||"groupOnScreen"===this.listName)this.dnd=new v.boxConstrainedMoveable(this.domNode,{handle:this.boxNode,box:this.parentBox,within:!0,delay:5,mover:u}),this.bindMoveEvent()}else"placeholder"===this.type?this.createPlaceholderNode():(this.createGroupNode(),"poolWidgets"===this.listName&&
(this.dnd=new v.boxConstrainedMoveable(this.domNode,{handle:this.boxNode,box:this.parentBox,within:!0,delay:5,mover:u}),this.bindMoveEvent()));b.addClass(this.domNode,"moveable");b.setStyle(this.domNode,{width:this.w+"px",height:this.h+"px"})},bindMoveEvent:function(){r.after(this.dnd,"onMoveStart",c.hitch(this,function(){this.isMoving=!0}),!0);r.after(this.dnd,"onMoveStop",c.hitch(this,function(){this.isMoving=!1}),!0)},_createWidgetIconNode:function(){var a=k.processUrlInAppConfig(this.setting.icon);
this.iconNode=b.create("img",{"class":"icon",src:a,style:{width:"32px",height:"32px",margin:(this.w-32)/2+"px"}},this.boxNode);window.isRTL&&this.setting.mirrorIconForRTL&&b.addClass(this.iconNode,"jimu-flipx")},_createPlaceholderNode:function(){this.placeholderNode=b.create("div",{"class":"placeholder",style:{width:"32px",height:"32px",margin:(this.w-32)/2+"px"}},this.boxNode);b.create("div",{"class":"placeholder-inner",innerHTML:k.sanitizeHTML(this.setting.placeholderIndex),style:{width:"16px",
height:"16px",lineHeight:"16px",borderRadius:"8px",margin:"7px"}},this.placeholderNode)},createWidgetNode:function(){b.addClass(this.domNode,"widget-node");b.setAttr(this.domNode,"data-widget-name",this.setting.name);this.boxNode=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);this._createWidgetIconNode();this.label=this.setting.label?this.setting.label:this.nls.defaultWidgetLabel;this.name=this.setting.name?this.setting.name:this.nls.defaultWidgetLabel;this.labelNode=
b.create("div",{"class":"label",innerHTML:k.stripHTML(this.label),title:this.label},this.domNode);!1===this.setting.visible&&b.addClass(this.domNode,"hide");this.setting.openAtStart&&(this.openAtStartNode=this._createOpenAtStartNode(),this.own(d(this.openAtStartNode,h,c.hitch(this,function(a){a.stopPropagation();this.emit("clickOpenAtStart")}))));this.own(d(this.boxNode,m,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"highLight"});this.editNode=this._createEditNode();
this.own(d(this.editNode,h,c.hitch(this,function(a){a.stopPropagation();g.publish("editWidget",this.setting,this)})));this.supportOpenAtStart()&&!this.setting.openAtStart&&(this.openAtStartNode=this._createOpenAtStartNode(),this.own(d(this.openAtStartNode,h,c.hitch(this,function(a){a.stopPropagation();this.emit("clickOpenAtStart")}))));!1===this.setting.inPanel&&this.setting.isOnScreen&&"undefined"===typeof this.setting.closeable?(this.switchNode=this._createSwitchNode(),this.own(d(this.switchNode,
h,c.hitch(this,function(a){a.stopPropagation();a=c.clone(this.setting);!1===a.visible?(a.visible=!0,b.removeClass(this.domNode,"hide")):(a.visible=!1,b.addClass(this.domNode,"hide"));g.publish("widgetChanged",a)})))):(this.dropNode=this._createDropNode(),this.own(d(this.dropNode,h,c.hitch(this,function(a){a.stopPropagation();var e=this._checkDataSource(this.setting.id)?new p({message:this.nls.dataSourceIsUsed,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){this.emit("removeNode");e.close()})},
{label:this.nls.cancel}]}):new p({message:this.nls.dropWidgetMessage,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){this.emit("removeNode");e.close()})},{label:this.nls.cancel}]})}))))})));this.own(d(this.boxNode,n,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"removeHighLight"});this.editNode&&b.destroy(this.editNode);this.openAtStartNode&&!this.setting.openAtStart&&b.destroy(this.openAtStartNode);this.dropNode&&b.destroy(this.dropNode);this.switchNode&&
b.destroy(this.switchNode)})))},createPlaceholderNode:function(){b.addClass(this.domNode,"widget-node");b.addClass(this.domNode,"placeholder");b.setAttr(this.domNode,"data-placeholder-index",this.setting.placeholderIndex);this.boxNode=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);this._createPlaceholderNode();this.label=this.setting.label?this.setting.label:this.nls.defaultWidgetLabel;this.name=this.setting.name?this.setting.name:this.nls.defaultWidgetLabel;
this.labelNode=b.create("div",{"class":"label",innerHTML:k.stripHTML(this.label),title:this.label},this.domNode);this.own(d(this.boxNode,m,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"highLight"})})));this.own(d(this.boxNode,n,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"removeHighLight"})})));this.own(d(this.domNode,h,c.hitch(this,function(){g.publish("chooseWidget",this,this.listName)})))},createGroupNode:function(){"poolWidgets"===
this.listName?this._createPoolGroupNode():this._createOnScreenGroupNode()},_createOnScreenGroupNode:function(){b.addClass(this.domNode,"group-node");this.boxNode=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);if(0===this.setting.widgets.length)b.addClass(this.domNode,"placeholder"),this._createPlaceholderNode(),this.name=this.label=this.nls.defaultWidgetLabel;else if(1===this.setting.widgets.length){var a=this.setting.widgets[0],e=k.processUrlInAppConfig(a.icon);
this.iconNode=b.create("img",{"class":"icon",src:e,style:{width:"32px",height:"32px",margin:(this.w-32)/2+"px"}},this.boxNode);window.isRTL&&a.mirrorIconForRTL&&b.addClass(this.iconNode,"jimu-flipx");this.label=a.label;this.name=a.name}else this._createSmallWidgets(),this.label=this.setting.label?this.setting.label:"Group",this.name=this.setting.name?this.setting.name:"Group";this.labelNode=b.create("div",{"class":"label",innerHTML:k.stripHTML(this.label),title:this.label},this.domNode);this.own(d(this.boxNode,
m,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"highLight"});if(0!==this.setting.widgets.length){if("undefined"===typeof this.setting.maxWidgets||this.setting.widgets.length<this.setting.maxWidgets)this.addNode=this._createAddNode(),this.own(d(this.addNode,h,c.hitch(this,function(f){g.publish("chooseWidget",this,this.listName);f.stopPropagation()}))),this.own(d(this.addNode,"mousedown",function(f){f.stopPropagation()})),this.own(d(this.addNode,"mouseup",function(f){f.stopPropagation()}));
1===this.setting.widgets.length&&(this.editNode=this._createEditNode(),this.own(d(this.editNode,h,c.hitch(this,function(f){f.stopPropagation();g.publish("editWidget",this.setting.widgets[0],this)}))),this.dropNode=this._createDropNode(),this.own(d(this.dropNode,h,c.hitch(this,function(f){var l=new p({message:this.nls.dropWidgetMessage,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){this.setting.widgets=[];g.publish("groupChanged",this.setting);l.close()})},{label:this.nls.cancel}]});f.stopPropagation()}))))}})));
this.own(d(this.boxNode,n,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"removeHighLight"});this.addNode&&b.destroy(this.addNode);this.editNode&&b.destroy(this.editNode);this.dropNode&&b.destroy(this.dropNode)})));this.own(d(this.boxNode,h,c.hitch(this,function(){if(0===this.setting.widgets.length)g.publish("chooseWidget",this,this.listName);else if(1!==this.setting.maxWidgets||1!==this.setting.widgets.length)"open"===this.status?this.closeGroup():this.openGroup()})))},
_createPoolGroupNode:function(){b.addClass(this.domNode,"group-node");this.boxNode=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);this.label=this.setting.label?this.setting.label:"Group";this.name=this.setting.name?this.setting.name:"Group";this.labelNode=b.create("div",{"class":"label",innerHTML:k.stripHTML(this.setting.label),title:this.setting.label},this.domNode);this._createSmallWidgets();this.setting.openAtStart&&(this.openAtStartNode=this._createOpenAtStartNode(),
this.own(d(this.openAtStartNode,h,c.hitch(this,function(a){a.stopPropagation();this.emit("clickOpenAtStart")}))));this.own(d(this.boxNode,m,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"highLight"});this.editNode=this._createEditNode({isGroupNode:!0});this.own(d(this.editNode,h,c.hitch(this,function(a){a.stopPropagation();this.setting.groupPopupTitle=this.nls.configLabel;g.publish("editGroup",this,this.setting)})));this.own(d(this.editNode,"mousedown",function(a){a.stopPropagation()}));
this.own(d(this.editNode,"mouseup",function(a){a.stopPropagation()}));this.supportOpenAtStart()&&!this.setting.openAtStart&&(this.openAtStartNode=this._createOpenAtStartNode(),this.own(d(this.openAtStartNode,h,c.hitch(this,function(a){a.stopPropagation();this.emit("clickOpenAtStart")}))));this.dropNode=this._createDropNode();this.own(d(this.dropNode,h,c.hitch(this,function(a){var e=new p({message:this.nls.dropGroupMessage,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){this.emit("removeNode");
e.close()})},{label:this.nls.cancel}]});a.stopPropagation()})));this.own(d(this.dropNode,"mousedown",function(a){a.stopPropagation()}));this.own(d(this.dropNode,"mouseup",function(a){a.stopPropagation()}))})));this.own(d(this.boxNode,n,c.hitch(this,function(){g.publish("actionTriggered",{elementId:this.setting.id,action:"removeHighLight"});this.editNode&&b.destroy(this.editNode);this.openAtStartNode&&!this.setting.openAtStart&&b.destroy(this.openAtStartNode);this.dropNode&&b.destroy(this.dropNode)})));
this.own(d(this.boxNode,h,c.hitch(this,function(a){a.preventDefault();a.stopPropagation();"open"===this.status?this.closeGroup():this.openGroup()})))},closeGroup:function(){this.status="close"},openGroup:function(){this.status="open"},createAddBtn:function(){b.addClass(this.domNode,"add-widget-node");var a=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"},title:this.nls.addWidget},this.domNode);b.create("img",{src:this.folderUrl+"css/images/add_widget.png"},a);this.own(d(this.domNode,
h,c.hitch(this,function(){g.publish("chooseWidget",this,this.listName)})))},createEmptyNode:function(){b.addClass(this.domNode,"empty-node");b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode)},_createEditNode:function(a){var e={bottom:"0",width:"20px",height:"20px"};e[window.isRTL?"left":"right"]="0";var f=this.nls.configureWidget;a&&a.isGroupNode&&(f=this.nls.configLabel);return b.create("div",{"class":"edit-btn",style:e,title:f},this.boxNode)},supportOpenAtStart:function(){var a=
this.setting;return"group"===this.type?"poolWidgets"===this.listName?!0:!1:!a.isController&&!a.isThemeWidget&&a.visible&&(a.isOnScreen&&(a.closeable||a.inPanel&&!this.gnode)||!a.isOnScreen&&!this.gnode)},_createOpenAtStartNode:function(){var a={bottom:"4px",width:"12px",height:"12px"};a[window.isRTL?"right":"left"]="4px";return b.create("div",{"class":this.setting.openAtStart?"open-at-start-btn active":"open-at-start-btn deactive",style:a,title:this.setting.openAtStart?this.nls.activeOpenAtStart:
this.nls.deactiveOpenAtStart},this.boxNode)},_createDropNode:function(){var a={top:"0",width:"20px",height:"20px"};a[window.isRTL?"left":"right"]="0";return b.create("div",{"class":"drop-btn",style:a,title:this.nls.removeWidget},this.boxNode)},_createAddNode:function(){var a={top:"0",width:"20px",height:"20px"};a[window.isRTL?"right":"left"]="0";return b.create("div",{"class":"small-add-btn",style:a,title:this.nls.addWidget},this.boxNode)},_createSwitchNode:function(){var a=b.hasClass(this.domNode,
"hide")?this.nls.showWidget:this.nls.hideWidget,e={top:"3px",width:"15px",height:"10px"};e[window.isRTL?"left":"right"]="3px";return b.create("div",{"class":"switch-btn",style:e,title:a},this.boxNode)},_createSmallWidgets:function(){z(".small",this.boxNode).remove();var a=[],e=!1;4<this.setting.widgets.length?(a=this.setting.widgets.slice(0,3),e=!0):(a=this.setting.widgets,e=!1);a.forEach(c.hitch(this,function(f){this._createSmallWidget(f)}));e&&this._createSmallMore()},_createSmallWidget:function(a){var e=
b.create("div",{"class":"small small-widget","data-wid":a.id,style:{width:"20px",height:"20px",marginLeft:(this.w-40)/3+"px",marginTop:(this.w-40)/3+"px"}},this.boxNode);var f=a.icon;if(a.icon.startWith("widgets")||a.icon.startWith("configs")||a.icon.startWith("themes"))f=require(k.getRequireConfig()).toUrl(a.icon);f=b.create("img",{src:f,style:{width:"20px",height:"20px"}},e);window.isRTL&&a.mirrorIconForRTL&&b.addClass(f,"jimu-flipx");return e},_createSmallMore:function(){var a=b.create("div",{"class":"small small-more",
style:{width:"20px",height:"20px",marginLeft:(this.w-40)/3+"px",marginTop:(this.w-40)/3+"px"}},this.boxNode);b.create("img",{src:"builder/images/more_widget.png",style:{width:"20px"}},a);return a},addWidget:function(a){"group"!==this.type?console.log("can not add widget to widget"):(this.setting.widgets.push(a.setting),this._createSmallWidgets())},updateSmallWidgets:function(){this._createSmallWidgets()},destroy:function(){this.margin&&this.margin.destroy();this.inherited(arguments)},_checkDataSource:function(a){return this.appConfig.dataSource?
x.some(Object.keys(this.appConfig.dataSource.dataSources),function(e){if(e.startWith("widget~"+a+"~")){var f=!1;this.appConfig.visitElement(function(l){if(l.id!==a&&l.config&&"object"===typeof l.config&&-1<JSON.stringify(l.config).indexOf(e))return f=!0});return f}},this):!1}})});