define({
  "transparencyLabel": "透明度",
  "outline": "輪廓",
  "fill": "填充 (將樣式設為實心時所套用的顏色)",
  "style": "樣式",
  "selectOpLayerLabel": "選擇結果的操作圖層",
  "selectDefaultMeasurementLabel": "選擇預設的測量單位",
  "helpIconTooltip": "會在操作圖層清單中，填入多邊形幾何類型的現行 Web 地圖中的圖層。",
  "lineStyles": {
    "esriSLSDash": "虛線",
    "esriSLSDashDot": "虛線點",
    "esriSLSDashDotDot": "虛線點點",
    "esriSLSDot": "點",
    "esriSLSLongDash": "長虛線",
    "esriSLSLongDashDot": "長虛線點",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "短虛線",
    "esriSLSShortDashDot": "短虛線點",
    "esriSLSShortDashDotDot": "短雙虛線點",
    "esriSLSShortDot": "短點",
    "esriSLSSolid": "實心"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向後",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "對角線",
    "esriSFSForwardDiagonal": "轉寄",
    "esriSFSHorizontal": "水平對齊",
    "esriSFSNull": "Null",
    "esriSFSSolid": "實心",
    "esriSFSVertical": "垂直"
  },
  "threatTypeLabel": "威脅類型",
  "generalLabel": "一般",
  "addThreatTypesLabel": "新增威脅類型",
  "actions": "作業",
  "newThreatTypePopupLabel": "新威脅類型",
  "units": "單位",
  "chooseDefaultThreatLabel": "選取預設威脅類型",
  "defaultThreatTypePopUpLabel": "預設威脅類型",
  "editThreatLabel": "編輯威脅",
  "defaultThreatTypeIconTooltip": "預設威脅類型清單",
  "uniqueThreatTypeMsg": "輸入唯一威脅類型，已存在此名稱的威脅類型。",
  "requiredMsg": "此欄位為必填項",
  "unitMeasureLabel": "距離以 {0} 為單位",
  "chooseDefaultThreatTypeIconLabel": "從預設值選擇",
  "pipeBombLabel": "土製鐵管炸彈",
  "suicideBombLabel": "自殺炸彈",
  "briefcaseLabel": "公事包",
  "carLabel": "汽車",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "小型送貨卡車",
  "containerWaterTruckLabel": "容器/水車",
  "semiTrailerLabel": "半掛車",
  "chemicalThreatLegendLabel": "化學威脅",
  "lpgThreatLegendLabel": "LPG 威脅",
  "smallLPGTank": "小型 LPG 罐",
  "largeLPGTank": "大型 LPG 罐",
  "commercialResidentialLPGTank": "化學/殘餘 LPG 罐",
  "smallLPGTruck": "小型 LPG 卡車",
  "semiTankerLPG": "半罐式 LPG",
  "threatDescriptionColLabel": "威脅描述",
  "addThreatZoneButtonLabel": "新增威脅區域",
  "zoneDescColLabel": "區域描述",
  "distanceLabel": "距離 (${unitAbbr})",
  "threatTypeHelp": "<p>確認符合下列威脅類型的條件:<br/><ul><li>威脅類型不可空白，且應是唯一的</li><li>威脅應至少有一個有效區域</li><li>威脅的區域描述應是唯一的</li></ul><p/>",
  "descriptionLabel": "描述",
  "newThreatZonePopupLabel": "新建威脅區域",
  "editThreatZonePopupLabel": "編輯威脅區域",
  "uniqueZoneDescriptionMsg": "輸入唯一的區域描述，已有使用此名稱的區域描述。",
  "symbologyColLabel": "符號系統",
  "zoneDescriptionColLabel": "區域描述",
  "uniqueZoneRequiredMsg": "此項的區域名稱應是唯一的:",
  "interactive": "互動",
  "fromCoord": "固定座標",
  "existingFeature": "來自現有的圖徵",
  "defaultInputLocationLabel": "預設輸入位置",
  "defaultInputLayer": "預設輸入圖層",
  "defaultThreatType": "預設威脅類型",
  "selectLabel": "選擇",
  "mandatoryLabel": "強制疏散距離",
  "safeLabel": "安全疏散距離",
  "lpgSafeDistanceLable": "安全距離",
  "fireBallDiameterLable": "火球直徑"
});