define({
  "_widgetLabel": "Editor Atribut Kelompok",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nama Layer",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Tidak ada layer yang dapat diedit dikonfigurasikan",
  "editorPopupTitle": "Editor Atribut Kelompok",
  "editorPopupSaveBtn": "Simpan",
  "editorPopupMultipleValues": "",
  "clear": "Kosongkan",
  "featuresUpdated": "${0} / ${1} fitur diperbarui",
  "featuresSelected": "${0} fitur dipilih",
  "featuresSkipped": "Dilewati",
  "featuresNoPermision": "${0} fitur dipilih tetapi tidak ada izin untuk mengedit.",
  "search": "Cari",
  "queryInput": "Masukkan nilai pada query",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Tetapkan filter dengan benar.",
  "filterPopup": "Layer Filter",
  "filterAppend": "Jika filter sudah ada di peta web untuk layer ini",
  "filterAppendOR": "Tambahkan ekspresi apa saja ke filter peta yang ada",
  "filterAppendAND": "Tambahkan semua ekspresi ke filter peta yang ada",
  "cancel": "Batal",
  "noValue": "Tidak Ada Nilai",
  "emptyString": "String Kosong",
  "existingValue": "Simpan Nilai yang Ada",
  "newDate": "Tanggal Baru",
  "valueChooser": "Pilih/Ketikkan sebuah Nilai",
  "ok": "Ya",
  "drawBox": {
    "point": "Titik",
    "line": "Garis",
    "polyline": "Polyline",
    "freehandPolyline": "Polyline Freehand",
    "extent": "Jangkauan",
    "polygon": "Poligon",
    "freehandPolygon": "Poligon Bebas",
    "clear": "Kosongkan",
    "addPointToolTip": "Klik untuk memilih di area ini",
    "addShapeToolTip": "Gambar sebuah bentuk untuk memilih fitur",
    "freehandToolTip": "Tekan dan tahan untuk menggambar bentuk untuk memilih fitur",
    "startToolTip": "Gambar sebuah bentuk untuk memilih fitur"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Fitur dari ${0} menghasilkan ID yang tidak valid",
    "noSelectedLayers": "Tidak ada layer yang mengandung catatan dipilih untuk diperbarui",
    "inputValueError": "Nilai dalam form tidak valid",
    "saveError": "Tidak dapat menyimpan ${0} fitur",
    "requiredValue": "Nilai Harus Diisi"
  }
});