define({
  "businessAnalyst": "Ärianalüütik",
  "defaultFirstPageText": "<br><div>Avage infograafika ja aruanded, mis teevad kokkuvõtte mis tahes piirkonna põhiindikaatoritest ja andmetest.</div><br><div>Valige kaardil punkt või polügoon, otsige aadressi või kohta, joonistage polügoon või paigutage kaardile nööpnõel, et vaadata piirkonna põhiindikaatoreid ja teavet.</div>",
  "defineWhichInfographics": "Määrake, milline infograafika on vidinas saadaval:",
  "defineWhichReports": "Määrake, millised raportid on vidinas saadaval:",
  "defaultValues": "Vaikeväärtused:",
  "disable": "Keela",
  "drawFreehandPolygon": "Joonista vabakäeline polügoon",
  "drawPolygon": "Joonista polügoon",
  "driveTime": "Sõiduaeg",
  "dropPin": "Paiguta nõel",
  "dynamicHTML": "Dünaamiline HTML",
  "exportOptions": "Ekspordi suvandid:",
  "home": "Esileht",
  "image": "Pilt",
  "infographics": "Infograafika",
  "invalidValueRing": "Väärtused peavad olema vahemikus 0–1000.",
  "invalidValueDTWT": "Väärtused peavad olema vahemikus 0–300.",
  "km": "km",
  "makeDefault": "Määra vaikeväärtuseks",
  "miles": "mi",
  "minutes": "min",
  "options": "Valikud:",
  "pdf": "PDF",
  "print": "Prindi",
  "radius": "Raadius",
  "removeDefault": "Eemalda vaikesäte",
  "reports": "Aruanded",
  "rings": "Ringid",
  "searchTextBox": "Otsingu tekstiväli",
  "selectCountryOrRegion": "Valige riik või piirkond:",
  "thisEntryIsNotValid": "See kirje ei kehti.",
  "time": "Aeg",
  "walkTime": "Kõndimise aeg"
});