define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Pristupite infografiji i izveštajima koji rezimiraju ključne indikatore i podatke za bilo koju oblast.</div><br><div>Select a point or polygon on the map, search for an address or place, draw a polygon, or drop a pin on the map to view key indicators and information about the area.</div>",
  "defineWhichInfographics": "Definišite koja infografika je dostupna u vidžetu:",
  "defineWhichReports": "Definišite koji izveštaji su dostupni u vidžetu:",
  "defaultValues": "Podrazumevane vrednosti:",
  "disable": "Onemogući",
  "drawFreehandPolygon": "Nacrtajte poligon slobodnom rukom",
  "drawPolygon": "Nacrtaj poligon",
  "driveTime": "Vreme vožnje",
  "dropPin": "Zakači čiodu",
  "dynamicHTML": "Dinamički HTML",
  "exportOptions": "Opcije za izvoz:",
  "home": "Matična stranica",
  "image": "Snimak",
  "infographics": "Infografika",
  "invalidValueRing": "Vrednost mora da bude u opsegu od 0 do 1.000.",
  "invalidValueDTWT": "Vrednost mora da bude u opsegu od 0 do 300.",
  "km": "km",
  "makeDefault": "Napravi podrazumevanim",
  "miles": "milje",
  "minutes": "minuti",
  "options": "Opcije:",
  "pdf": "PDF",
  "print": "Odštampaj",
  "radius": "Poluprečnik",
  "removeDefault": "Ukloni podrazumevano",
  "reports": "Izveštaji",
  "rings": "Prstenovi",
  "searchTextBox": "Pretražite okvir za tekst",
  "selectCountryOrRegion": "Izaberite zemlju ili region:",
  "thisEntryIsNotValid": "Unos nije validan.",
  "time": "Vreme",
  "walkTime": "Vreme pešačenja"
});