// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/creation-entry/CreateNewAppPage.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"app-select-page" data-dojo-attach-point\x3d"appSelectPage"\x3e\r\n    \x3cdiv class\x3d"switch-btn-box-container"\x3e\r\n      \x3cdiv class\x3d"switch-btn-box"\x3e\r\n        \x3cdiv class\x3d"switch-btn all-app-btn selected" data-dojo-attach-point\x3d"allAppBtn"\r\n             data-dojo-attach-event\x3d"onclick:_onAllAppBtnClick"\x3e ${nls.all}\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"separate"\x3e\x3c/div\x3e\r\n        \x3cdiv class\x3d"switch-btn own-app-btn" data-dojo-attach-point\x3d"ownAppBtn"\r\n             data-dojo-attach-event\x3d"onclick:_onOwnAppBtnClick"\x3e ${nls.myTemplates}\r\n        \x3c/div\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"app-content all-app-content" data-dojo-attach-point\x3d"allAppContent"\x3e\r\n      \x3cdiv class\x3d"app-line" data-dojo-attach-point\x3d"defaultApps"\x3e\x3c/div\x3e\r\n      \x3cdiv class\x3d"app-line" data-dojo-attach-point\x3d"othersApps"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"app-content own-app-content" data-dojo-attach-point\x3d"ownAppContent"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"app-info-page" data-dojo-attach-point\x3d"appInfoPage"\x3e\r\n    \x3cdiv class\x3d"app-info-table" data-dojo-attach-point\x3d"appInfoTable"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/array dojo/_base/html builder/BasePlugin dojo/dom-style dijit/_WidgetsInTemplateMixin dojo/text!./CreateNewAppPage.html dojo/query dojo/on dojo/dom-class dojo/_base/lang dojo/Evented builder/dijit/EditItemInfo builder/serviceUtils jimu/portalUrlUtils builder/portalUtils jimu/utils".split(" "),function(n,f,d,p,q,r,t,g,u,m,k,v,w,x,y,z,l){return n([p,r,v],{templateString:t,baseClass:"create-app-page",appInfo:null,pluginManager:null,postMixInProperties:function(){this.inherited(arguments)},
postCreate:function(){this.inherited(arguments)},startup:function(){"undefined"===typeof this.isPortalSupport3D&&(this.isPortalSupport3D=!1);this.isPortalSupport3D=!!this.isPortalSupport3D;this.initAppInfoPage();this.createFromAppInfo?(this.selectedApp=this.createFromAppInfo,this._displaySecondPage(),this._hideButton(1)):(this.initAppSelectPage(),this._displayFirstPage())},destroy:function(){this.itemInfoDijit&&(this.itemInfoDijit.destroy(),this.itemInfoDijit=null);this.popup&&(this.popup=null);d.destroy(this.domNode);
this.inherited(arguments)},initAppSelectPage:function(){this._stemappExtensions=this.pluginManager.getExtensions("startup.stemapps");this._stemappExtensions.sort(function(a,b){return a.parameters.index-b.parameters.index});x.getTemplateList(!0).then(k.hitch(this,function(a){var b=this._filterInfosByIsPortalSupport3D(a);f.forEach(b,function(c){!c.id||"HTML_default"!==c.id&&"HTML3D_default"!==c.id?this._createAppNodeAndBindEvent(c,this.othersApps):("HTML_default"===c.id?c.name=this.nls.Default2D:"HTML3D_default"===
c.id&&(c.name=this.nls.Default3D),this._createAppNodeAndBindEvent(c,this.defaultApps))},this);this._selecteApp(g(".app-image-border-div",this.allAppContent)[0]);b=y.getStandardPortalUrl(window.portalUrl);z.getPortal(b).getUser().then(k.hitch(this,function(c){var e=f.filter(a,function(h){return h.isTemplate&&h.creator===c.username});e=this._filterInfosByIsPortalSupport3D(e);f.forEach(e,function(h){this._createAppNodeAndBindEvent(h,this.ownAppContent)},this)}))}))},_filterInfosByIsPortalSupport3D:function(a){var b=
this.isPortalSupport3D;return f.filter(a,function(c){return!1===b?"HTML3D"!==c.appType:!0})},initAppInfoPage:function(){this.itemInfoDijit=new w({itemInfo:this.appInfo,nls:this.nls});this.itemInfoDijit.placeAt(this.appInfoTable)},_createAppNode:function(a,b,c){this.zIndex=10;b=d.create("div",{"class":"app-node jimu-float-leading",style:c},b);c=d.create("div",{"class":"app-image-border-div",title:l.stripHTML(a.description)},b);d.create("div",{"class":"app-image-div",style:{backgroundImage:"url("+a.thumbnail+
")"}},c);var e;"HTML"===a.appType?e="2D":"HTML3D"===a.appType&&(e="3D");e=d.create("div",{"class":"flag-image flag-image-"+e},c);q.set(e,"z-index",this.zIndex++);d.create("div",{"class":"app-name",innerHTML:l.stripHTML(a.name),title:l.stripHTML(a.name)},b);return c},_createAppNodeAndBindEvent:function(a,b){b=this._createAppNode(a,b);this.own(u(b,"click",k.hitch(this,this._onAppNodeClick,b)));b.appInfo=a;return b},_onAppNodeClick:function(a){var b=g(".app-image-border-div",this.appSelectPage);f.forEach(b,
function(c){this._unselecteApp(c)},this);this._selecteApp(a)},_selecteApp:function(a){this.selectedApp=a.appInfo;m.add(a,"jimu-state-active")},_unselecteApp:function(a){m.remove(a,"jimu-state-active")},_onAllAppBtnClick:function(){var a=g(".app-image-border-div",this.allAppContent)[0];a&&(this._onAppNodeClick(a),this.creationEntryPlugin.createAppPopup.enableButton(0));d.setStyle(this.allAppContent,"display","block");d.setStyle(this.ownAppContent,"display","none");d.addClass(this.allAppBtn,"selected");
d.removeClass(this.ownAppBtn,"selected")},_onOwnAppBtnClick:function(){var a=g(".app-image-border-div",this.ownAppContent)[0];a?(this._onAppNodeClick(a),this.creationEntryPlugin.createAppPopup.enableButton(0)):this.creationEntryPlugin.createAppPopup.disableButton(0);d.setStyle(this.allAppContent,"display","none");d.setStyle(this.ownAppContent,"display","block");d.addClass(this.ownAppBtn,"selected");d.removeClass(this.allAppBtn,"selected")},_onNextClick:function(){this._displaySecondPage();"HTML"===
this.selectedApp.appType?this.itemInfoDijit.imageChooser.setDefaultSelfSrc("/webappbuilder/builder/images/appthumbnail_2d.jpg"):this.itemInfoDijit.imageChooser.setDefaultSelfSrc("/webappbuilder/builder/images/appthumbnail_3d.jpg")},_onBackClick:function(){this._displayFirstPage()},_displayFirstPage:function(){d.setStyle(this.appInfoPage,"display","none");d.setStyle(this.appSelectPage,"display","block");this._displayButtion(0);this._hideButton(1);this._hideButton(2);this.popup&&this.popup.resize()},
_displaySecondPage:function(){d.setStyle(this.appSelectPage,"display","none");d.setStyle(this.appInfoPage,"display","block");this._hideButton(0);this._displayButtion(1);this._displayButtion(2);this.popup&&this.popup.resize();this.itemInfoDijit&&this.itemInfoDijit.focusItemByName("appName")},setPopup:function(a){this.popup=a},_hideButton:function(a){d.setStyle(this.popup.enableButton(a),"display","none")},_displayButtion:function(a){d.setStyle(this.popup.enableButton(a),"display","inline-block")},
_getAppInfoFromDlg:function(){var a=this.itemInfoDijit.getProperties();a.appType=this.selectedApp.appType;a.webmap=this.webmap;a.fromAppId=this.selectedApp.id;a.isPredefined=!1;a.isTemplateApp=this.selectedApp.isTemplate;0===a.icon.indexOf("/webappbuilder/builder/images/")&&(a.icon=null);0===a.thumbnail.indexOf("/webappbuilder/builder/images/")&&(a.thumbnail=null);return a}})});