define({
  "layerSelect": "Zvoliť obrazovú vrstvu",
  "displayMeasureResultInPopup": "Zobraziť výsledky merania v kontextovom okne",
  "angularUnitSelect": "Predvolená uhlová jednotka",
  "linearUnitSelect": "Predvolená lineárna jednotka",
  "areaUnitSelect": "Predvolená plošná jednotka",
  "displayOperationSelect": "Zvoliľ operácie merania",
  "errorSectionMessage": "Žiadna z vrstiev nepodporuje možnosti merania.",
  "unitLabel": {
    "esriInches": "Palce",
    "esriFeet": "Stopy",
    "esriYards": "Yardy",
    "esriMiles": "Míle",
    "esriNauticalMiles": "Námorné míle",
    "esriMillimeters": "Milimetre",
    "esriCentimeters": "Centimetre",
    "esriDecimeters": "Decimetre",
    "esriMeters": "Metre",
    "esriKilometers": "Kilometre",
    "esriDURadians": "Radiány",
    "esriDUDecimalDegrees": "Stupne",
    "esriSquareInches": "Štvorcové palce",
    "esriSquareFeet": "Štvorcové stopy",
    "esriSquareYards": "Štvorcové yardy",
    "esriAcres": "Akre",
    "esriSquareMiles": "Štvorcové míle",
    "esriSquareMillimeters": "Štvorcové milimetre",
    "esriSquareCentimeters": "Štvorcové centimetre",
    "esriSquareDecimeters": "Štvorcové decimetre",
    "esriSquareMeters": "Štvorcové metre",
    "esriAres": "Áre",
    "esriHectares": "Hektáre",
    "esriSquareKilometers": "Štvorcové kilometre"
  },
  "operationLabel": {
    "esriMensurationPoint": "Poloha",
    "esriMensurationDistanceAndAngle": "Vzdialenosť a uhol",
    "esriMensurationAreaAndPerimeter": "Plocha a obvod",
    "esriMensurationHeightFromBaseAndTop": "Výška: od základne nahor",
    "esriMensurationHeightFromBaseAndTopShadow": "Výška: od základne po horný tieň",
    "esriMensurationHeightFromTopAndTopShadow": "Výška: zhora po horný tieň",
    "esriMensurationCentroid": "Ťažisko",
    "esriMensurationPoint3D": "Poloha (3D)",
    "esriMensurationDistanceAndAngle3D": "Vzdialenosť a uhol (3D)",
    "esriMensurationAreaAndPerimeter3D": "Plocha a obvod (3D)",
    "esriMensurationCentroid3D": "Ťažisko (3D)"
  }
});