define({
  "locatorUrl": "Konumlandırıcı URL'si",
  "set": "Ayarla",
  "locatorName": "Bulucu Adı",
  "locatorExample": "Örnek",
  "countryCode": "Ülke veya Bölge Kodları",
  "eg": "ör. ",
  "countryCodeHint": "Bu değer boş bırakılırsa tüm ülkeler ve bölgeler aranır",
  "minCandidateScore": "Minimum Aday Puanı",
  "minCandidateScoreHint": "Bu değer boş bırakıldığında minimum aday puanı olarak 90 kullanılır",
  "enableSingleField": "Tek alan Seçenekleri",
  "singleFieldHint": "Adres verileri tek alanda olacaktır",
  "enableMultiField": "Çoklu alan Seçenekleri",
  "multiFieldHint": "Adres verileri birden fazla alanda olacaktır",
  "enableXYField": "X/Y Alan Seçenekleri",
  "xyFieldHint": "Veriler X/Y koordinat değerleri içerecektir",
  "instructionGeocode": "Yer bulucu servisleri ekleyin ve yapılandırın.",
  "invalidUrlTip": "${URL} URL'si geçersiz veya erişilemez durumda.",
  "geocodeTabLabel": "Konum Ayarları",
  "lookupList": "Tanınacak Alan Adları",
  "isRecognized": "Aşağıdaki tabloda bulunan alan adları bu alan için otomatik olarak tanınmıştır",
  "needsEditablePointLayers": "Bir web haritası en az bir düzenlenebilir nokta katmanı içermelidir.",
  "editpageAlias": "Takma Ad",
  "configureFields": "Katman Alanlarını Yapılandır",
  "configureSingleFields": "Tek Bir Adres Alanı Yapılandır",
  "configureMultiFields": "Birden Fazla Adres Alanı Yapılandır",
  "configureXYFields": "X/Y Alanlarını Yapılandır",
  "noFields": "Görüntülenecek bir veya daha fazla alanı tanımlamak için düzenleme işlemini kullanın",
  "display": "Görünüm",
  "duplicate": "Yinelenenleri Bul",
  "duplicateTip": "Bu alandaki kaynak dosya ile hedef katman arasındaki aynı değerleri arayın./n Aynı eşleşme bulunduğunda dosyadaki kaydın yeri bulunmaz ve yinelenen olarak işaretlenir.",
  "noSelectField": "Önce Detay Katmanı seçeneğini belirtin",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Boylam)",
  "xyFieldsLabelY": "Y (Enlem)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Doğuya Yöneltme",
  "northing": "Kuzeye Yöneltme",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Verilerin gönderileceği katmanı seçin.",
  "layerFieldTitle": "Hedef Katman",
  "tempSymbolHint": "Detayları görüntülemek için kullanılacak simgeyi seçin.",
  "tempSymbolTitle": "Simgeyi Görüntüle",
  "maxRecords": "Maks kayıt",
  "maxRecordsHint": "Bulunacak maksimum kayıt sayısı",
  "searchRadius": "Arama yarıçapı",
  "searchRadiusHint": "Katmandan detay çoğaltmak için arama mesafesi",
  "requiresInteger": "Sayısal bir değer girin.",
  "requiresInteger0100": "0 ile 100 arasında bir sayısal değer girin",
  "requiresLocator": "En az bir geçerli yer bulucu ekleyin.",
  "layerFields": "Katman Ayarları",
  "layerFieldsHint": "Kaynak alanlarla eşlenecek Hedef Katmandaki alanları belirtin.",
  "locatorError": "Yer bulucu geçersiz veya erişilemiyor.",
  "optionNotMatch": "Alan seçenekleri, yer bulucular için tutarlı değil. Yük devretme beklendiği gibi çalışmayabilir.",
  "targetLayerTabTitle": "Hedef Katman",
  "locationSettingsTabTitle": "Konum Ayarları",
  "generalSettingsTabTitle": "Genel Ayarlar",
  "addTargetLayersLabel": "Hedef Katman Ekle",
  "introductoryText": "Gereç için eğitici içerik oluştur",
  "defaultStartPageInstructions": "Bu gereç bir dosyadaki verilerin işlenmesine ve haritadaki seçili katmana gönderilmesine yardımcı olur.<br/> <br/> Dosyadaki değerler virgül, sekme, noktalı virgül veya dikey çubukla sınırlandırılmalıdır.",
  "noTargetLayerConfiguredErrorMsg": "Yapılandırılan hedef katman yok",
  "noFieldsForTargetLayer": "Katman ayarları hedef katman için tanımlanmamış",
  "locationSettingsNotConfigured": "Yer ayarları düzgün yapılandırılmamış",
  "questionMark": "?"
});