define({
  "layersPage": {
    "allLayers": "Totes les capes",
    "title": "Seleccioneu una plantilla per crear entitats o bé feu clic en una entitat del mapa per editar-la",
    "generalSettings": "Configuració general",
    "layerSettings": "Configuració de capa",
    "webmapSettingsRadioBtnLabel": "Respecta la configuració del mapa web",
    "customSettingsRadioBtnLabel": "Configuració personalitzada",
    "smartActionsTabTitle": "Accions intel·ligents",
    "attributeActionsTabTitle": "Accions d'atributs",
    "geocoderSettingsText": "Configuració del geocodificador",
    "editDescription": "Proporcioneu el text que es mostrarà a la subfinestra d'edició",
    "editDescriptionTip": "Aquest text es mostra sobre el selector de plantilles. Deixeu-lo en blanc si no voleu utilitzar cap text.",
    "promptOnSave": "Sol·licitud per desar edicions no desades quan es tanca el formulari o es canvia al següent registre",
    "promptOnSaveTip": "Mostra una sol·licitud quan l'entitat actual té canvis que no s'han desat. (Si es copien diverses entitats, es desa automàticament).",
    "promptOnDelete": "Demana confirmació quan se suprimeixi un registre",
    "promptOnDeleteTip": "Visualitzeu una sol·licitud quan l'usuari faci clic a Suprimeix per confirmar l'acció.",
    "removeOnSave": "Elimina l'entitat de la selecció en desar",
    "removeOnSaveTip": "Opció per eliminar l'entitat del conjunt de selecció en desar el registre. Si és l'únic registre seleccionat, la subfinestra torna a canviar a la pàgina de la plantilla.",
    "useFilterEditor": "Utilitza el filtre de plantilla d'entitat",
    "useFilterEditorTip": "Opció per utilitzar el selector de plantilles de filtre que permet veure la plantilla d'una capa o cercar plantilles pel nom.",
    "groupFilteredTemplates": "Agrupa els resultats de la cerca",
    "groupFilteredTemplatesTip": "Opció per agrupar els resultats de la cerca per capa.",
    "displayShapeSelector": "Mostra les opcions de dibuix",
    "createNewFeaturesFromExisting": "Permet que l'usuari creï noves entitats a partir d'entitats existents",
    "createNewFeaturesFromExistingTip": "Opció per permetre que l'usuari copiï una entitat existent per crear entitats noves",
    "copiedFeaturesOverrideDefaults": "Els valors de les entitats copiades invaliden els valors per defecte",
    "copiedFeaturesOverrideDefaultsTip": "Els valors de les entitats copiades invalidaran els valors de la plantilla per defecte només per als camps coincidents",
    "displayShapeSelectorTip": "Opció per mostrar una llista d'opcions de dibuix vàlides per a la plantilla seleccionada.",
    "displayPresetTop": "Mostra la llista de valors predefinits a sobre",
    "displayPresetTopTip": "Opció per mostrar la llista de valors predefinits sobre el selector de plantilles.",
    "listenToGroupFilter": "Aplica valors de filtre del widget Filtre de grup als camps predefinits",
    "listenToGroupFilterTip": "Quan s'apliqui un filtre al widget Filtre de grup, apliqueu el valor a un camp coincident de la llista de valors predefinits.",
    "keepTemplateActive": "Mantén activa la plantilla seleccionada",
    "editLayerAddedFromAddData": "Permet editar capes afegides des del widget Afegeix dades",
    "editLayerAddedFromAddDataTip": "Les capes editables afegides a l'aplicació mitjançant el widget Afegeix dades es poden editar",
    "keepTemplateActiveTip": "Quan es mostri el selector de plantilles, si hi ha una plantilla seleccionada anteriorment, torneu a seleccionar-la.",
    "geometryEditDefault": "Habilita l'edició de geometria per defecte",
    "autoSaveEdits": "Desa les entitats noves automàticament",
    "enableAttributeUpdates": "Mostra el botó d'actualització d'accions d'atributs",
    "enableAutomaticAttributeUpdates": "Crida automàticament les accions d'atributs després de l'actualització de la geometria",
    "enableLockingMapNavigation": "Habilita el bloqueig de la navegació pel mapa",
    "enableMovingSelectedFeatureToGPS": "Habilita el moviment de l'entitat de punt seleccionada a la ubicació GPS",
    "enableMovingSelectedFeatureToXY": "Habilita el moviment de l'entitat de punt seleccionada a la ubicació XY",
    "featureTemplateLegendLabel": "Configuració del valors de Plantilla d'entitats i Filtre",
    "saveSettingsLegendLabel": "Desa la configuració",
    "geometrySettingsLegendLabel": "Configuració de la geometria",
    "actionsSettingsLegendLabel": "Configuració de les accions",
    "buttonPositionsLabel": "Posició dels botons Desa, Suprimeix, Enrere i Cancel·la",
    "belowEditLabel": "A sota d'Edita el formulari",
    "aboveEditLabel": "A sobre d'Edita el formulari",
    "switchToMultilineInput": "Canvieu a l'entrada de diverses línies si la longitud del camp supera",
    "enableValuePicker": "Habilita el selector de valors d'intersecció",
    "enableValuePickerHint": "Mostra un indicador quan hi ha diversos valors disponibles per a un camp amb una acció d'atribut d'interacció",
    "expandRelatedTable": "Expandeix totes les taules/capes relacionades en pujar",
    "expandMainTable": "Expandeix totes les capes pare en pujar",
    "layerSettingsTable": {
      "allowDelete": "Permet la supressió",
      "allowDeleteTip": "Permet la supressió: opció que permet que l'usuari suprimeixi una entitat; està deshabilitada si la capa no admet supressions",
      "edit": "Editable",
      "editTip": "Editable: opció per incloure la capa al widget",
      "label": "Capa",
      "labelTip": "Capa: nom de la capa tal com està definida al mapa",
      "update": "Deshabilita l'edició de geometria",
      "updateTip": "Deshabilita l'edició de geometria: opció per deshabilitar la funció per moure la geometria un cop inserida o per moure-la a una entitat existent",
      "allowUpdateOnly": "Només actualitzar",
      "allowUpdateOnlyTip": "Només actualitzar: opció per permetre únicament la modificació d'entitats existents; està activada per defecte i es desactiva si la capa no admet la creació d'entitats noves",
      "fieldsTip": "Modifica els camps que s'han d'editar i defineix els atributs intel·ligents",
      "actionsTip": "Accions: opció per editar els camps o accedir a capes o taules relacionades",
      "description": "Descripció",
      "descriptionTip": "Descripció: opció que permet introduir text perquè es mostri a la part superior de la pàgina d'atributs.",
      "relationTip": "Visualitza capes i taules relacionades"
    },
    "editFieldError": "Les modificacions de camps i els atributs intel·ligents no estan disponibles per a les capes que no es poden editar",
    "noConfigedLayersError": "L'Editor intel·ligent necessita una o més capes editables",
    "toleranceErrorMsg": "Valor de tolerància d'intersecció per defecte no vàlid",
    "pixelsToleranecErrorMsg": "Valor de tolerància de píxels per defecte no vàlid",
    "invalidMaxCharacterErrorMsg": "El valor de canvi a l'entrada de diverses línies no és vàlid",
    "featuresSelectionTolerance": "Establiu la tolerància per a la selecció de característiques (píxels)",
    "featuresSelectionToleranceTooltip": "Permet als usuaris obrir fàcilment el panell d’edició d’atributs fent clic a la característica",
    "featuresSelectionToleranceErrorMsg": "Valor de tolerància de selecció de característica no vàlid",
    "autoSaveAttrUpdates": "Desa actualitzacions d'atributs automàticament"
  },
  "editDescriptionPage": {
    "title": "Defineix el text de descripció general de l'atribut de <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Configura els camps de <b>${layername}</b>",
    "copyActionTip": "Accions d'atributs",
    "editActionTip": "Accions intel·ligents",
    "description": "Utilitzeu el botó d'edició d'accions per activar els atributs intel·ligents en una capa. Els atributs intel·ligents poden exigir, amagar o deshabilitar un camp en funció dels valors dels altres camps. Utilitzeu el botó de còpia d'accions per activar i definir l'origen del valor del camp per intersecció, adreça, coordenades i valor predefinit.",
    "fieldsNotes": "* És un camp obligatori. Si desactiveu la visualització d'aquest camp i la plantilla d'edició no emplena el valor d'aquest camp, no podreu desar un registre nou.",
    "smartAttachmentText": "Configureu les accions intel·ligents per als fitxers adjunts",
    "smartAttachmentPopupTitle": "Configureu les accions intel·ligents per als fitxers adjunts a <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Seleccioneu com a mínim un camp de visualització per a la capa ${layerName}",
    "fieldsSettingsTable": {
      "display": "Mostra",
      "displayTip": "Mostra: determina si el camp no és visible",
      "edit": "Editable",
      "editTip": "Editable: activa aquesta opció si el camp està present al formulari d'atributs",
      "fieldName": "Nom",
      "fieldNameTip": "Nom: nom del camp definit a la base de dades",
      "fieldAlias": "Àlies",
      "fieldAliasTip": "Àlies: nom del camp definit al mapa",
      "canPresetValue": "Predefineix",
      "canPresetValueTip": "Predefineix: opció per mostrar el camp a la llista de camps predefinits i permetre que l'usuari defineixi el valor abans de l'edició",
      "actions": "Accions",
      "actionsTip": "Accions: canvieu l'ordre dels camps o configureu els atributs intel·ligents"
    },
    "smartAttSupport": "Els atributs intel·ligents no s'admeten als camps de base de dades obligatoris"
  },
  "actionPage": {
    "title": "Configura les accions d'atributs de <b>${fieldname}</b>",
    "smartActionTitle": "Configureu les accions intel·ligents per a <b>${fieldname}</b>",
    "description": "Les accions estan sempre desactivades llevat que s'especifiquin els criteris que faran que s'activin. Les accions es processen en ordre i només s'activarà una acció per camp. Utilitzeu el botó d'edició de criteris per definir-los.",
    "copyAttributesNote": "Deshabilitar qualsevol acció amb un nom de grup serà el mateix que editar l'acció de manera independent; s'eliminarà l'acció del camp del grup respectiu.",
    "searchPlaceHolder": "Cerca",
    "expandAllLabel": "Expandeix totes les capes",
    "selectAllLabel": "Selecciona tots els camps",
    "domainListTitle": "Camps de domini",
    "noValidFieldTypeMsg": "No hi ha cap capa adequada disponible al mapa per a aquest tipus de dades",
    "actionsSettingsTable": {
      "rule": "Acció",
      "ruleTip": "Acció: acció que es realitza quan es compleixen els criteris",
      "expression": "Expressió",
      "expressionTip": "Expressió: expressió que resulta del criteri definit en format SQL",
      "groupName": "Nom del grup",
      "groupNameTip": "Nom del grup: mostra el nom del grup des del qual s'ha aplicat l'expressió",
      "actions": "Criteris",
      "actionsTip": "Criteris: canvien l'ordre de la regla i defineixen els criteris que s'aplicaran quan s'activi"
    },
    "copyAction": {
      "description": "L'origen del valor del camp es processa en ordre si està activat fins que s'activa un criteri vàlid o es completa la llista. Utilitzeu el botó d'edició de criteri per definir el criteri.",
      "intersection": "Intersecció",
      "coordinates": "Coordenades",
      "address": "Adreça",
      "preset": "Predefineix",
      "actionText": "Accions",
      "criteriaText": "Criteri",
      "enableText": "Habilitat"
    },
    "actions": {
      "hide": "Amaga",
      "required": "Obligatori",
      "disabled": "Deshabilitat"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Avís: l'edició independent eliminarà del grup l'acció d'atribut seleccionada associada d'aquest camp",
      "editGroupHint": "Avís: l'edició independent eliminarà del grup l'acció intel·ligent seleccionada associada d'aquest camp",
      "popupTitle": "Trieu l'opció d'edició",
      "editAttributeGroup": "L'acció d'atribut seleccionada es defineix des del grup. Trieu una de les opcions següents per editar l'acció d'atribut:",
      "expression": "L'expressió de l'acció intel·ligent seleccionada es defineix des del grup. Trieu una de les opcions següents per editar l'expressió de l'acció intel·ligent:",
      "editGroupButton": "Edita el grup",
      "editIndependentlyButton": "Edita de manera independent"
    }
  },
  "filterPage": {
    "submitHidden": "Envia les dades d'atributs dels camps encara que estiguin amagats",
    "title": "Configura l'expressió de la regla ${action}",
    "filterBuilder": "Defineix l'acció al camp quan el registre coincideixi, de les expressions següents, amb ${any_or_all}",
    "noFilterTip": "Utilitzeu les eines incloses a dalt per definir la declaració per quan l’acció estigui activa."
  },
  "geocoderPage": {
    "setGeocoderURL": "Defineix la URL del geocodificador",
    "hintMsg": "Nota: esteu canviant el servei de geocodificador. Assegureu-vos d'actualitzar les assignacions de camps del geocodificador que teniu configurades.",
    "invalidUrlTip": "L'adreça URL ${URL} no és vàlida o no s'hi pot accedir."
  },
  "addressPage": {
    "popupTitle": "Adreça",
    "checkboxLabel": "Obteniu el valor del geocodificador",
    "selectFieldTitle": "Atribut",
    "geocoderHint": "Per canviar el geocodificador, aneu al botó \"Configuració del geocodificador\" a la configuració general",
    "prevConfigruedFieldChangedMsg": "L'atribut configurat anteriorment no es troba a la configuració del geocodificador actual. L'atribut s'ha restablert al valor per defecte.",
    "questionMark": "?",
    "consumesCredits": "Aquesta eina consumeix crèdits quan es fa servir amb el servei de geocodificació mundial de l'ArcGIS Online"
  },
  "coordinatesPage": {
    "popupTitle": "Coordenades",
    "checkboxLabel": "Obteniu les coordenades",
    "coordinatesSelectTitle": "Sistema de referència",
    "coordinatesAttributeTitle": "Atribut",
    "mapSpatialReferenceOptionLabel": "Referència espacial del mapa",
    "latLongOptionLabel": "Latitud/longitud",
    "MGRS": "MGRS",
    "allGroupsCreatedMsg": "Tots els grups possibles ja s'han creat",
    "coordinatesSourceTitle": "Font de coordinades",
    "featureLocation": "Ubicación de entidad",
    "myLocation": "La meva ubicació",
    "LatLong": {
      "y": "Latitud",
      "x": "Longitud",
      "xy": "Longitud Latitud",
      "yx": "Latitud Longitud"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Predefineix",
    "checkboxLabel": "El camp estarà predefinit",
    "showOnlyDomainFields": "Mostra només els camps de domini",
    "hideInPresetDisplay": "Amaga a la visualització de valors predefinits",
    "presetValueLabel": "El valor predefinit actual és:",
    "changePresetValueHint": "Per canviar el valor predefinit, aneu al botó \"Defineix els valors predefinits\" a la configuració general"
  },
  "intersectionPage": {
    "groupNameLabel": "Nom del grup",
    "dataTypeLabel": "Tipus de dades",
    "ignoreLayerRankingCheckboxLabel": "Ignora la classificació de capes i troba l'entitat més propera entre totes les capes definides",
    "intersectingLayersLabel": "Capes de les quals s'extraurà un valor",
    "layerAndFieldsApplyLabel": "Capes i camps als quals s'aplicarà el valor extret",
    "checkboxLabel": "Obteniu el valor del camp de la capa d'intersecció",
    "layerText": "Capes",
    "fieldText": "Camps",
    "actionsText": "Accions",
    "toleranceSettingText": "Configuració de tolerància",
    "addLayerLinkText": "Afegeix una capa",
    "useDefaultToleranceText": "Utilitza la tolerància per defecte",
    "toleranceValueText": "Valor de tolerància",
    "toleranceUnitText": "Unitat de tolerància",
    "pixelsUnitText": "Píxels",
    "useLayerName": "- Utilitza el nom de la capa -",
    "noLayersMessage": "No s'ha trobat cap camp a les capes del mapa que coincideixi amb el tipus de dades seleccionat.",
    "intersectionLayerHint": "La classificació de la capa es determina en ordre descendent. Feu servir les fletxes que hi ha a sota d'Accions per canviar l'ordre de les capes i canviar la prioritat d'intersecció."
  },
  "presetAll": {
    "popupTitle": "Defineix els valors predefinits per defecte",
    "deleteTitle": "Suprimeix el valor predefinit",
    "hintMsg": "Els noms de tots els camps predefinits únics s'enumeren aquí. L'eliminació d'un camp predefinit deshabilitarà el camp respectiu com a valor predefinit de totes les capes o taules."
  },
  "intersectionTolerance": {
    "intersectionTitle": "Tolerància d'intersecció per defecte per a totes les entitats",
    "pixelsToleranceTitle": "Tolerància d'intersecció per defecte (valor del píxel) que s'aplicarà només a les entitats de punts"
  },
  "smartActionsPage": {
    "smartActionLabel": "Configura l'acció intel·ligent",
    "addNewSmartActionLinkText": "Afegeix-ne una de nova",
    "definedActions": "Accions definides",
    "priorityPopupTitle": "Defineix la prioritat de les accions intel·ligents",
    "priorityPopupColumnTitle": "Accions intel·ligents",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Nom del grup",
    "layerForExpressionLabel": "Capa de l'expressió",
    "layerForExpressionNote": "Nota: els camps d'aquesta capa s'utilitzen per definir els criteris de l'expressió. \"Capes i camps on s'aplicarà\" només mostra capes i taules que tenen els camps definits a l'expressió.",
    "expressionText": "Expressió",
    "editExpressionLabel": "Edita l'expressió",
    "layerAndFieldsApplyLabel": "Capes i camps on s'aplicarà",
    "submitAttributeText": "Envia les dades d'atributs dels camps encara que estiguin amagats",
    "priorityColumnText": "Prioritat",
    "requiredGroupNameMsg": "Aquest valor és obligatori",
    "uniqueGroupNameMsg": "Introduïu un nom de grup únic, ja existeix un grup amb aquest nom.",
    "deleteGroupPopupTitle": "Suprimeix el grup d'accions intel·ligents",
    "deleteGroupPopupMsg": "En suprimir el grup s'eliminarà l'expressió de l'acció de tots els camps associats.",
    "invalidExpression": "El camp Expressió no pot estar en blanc",
    "warningMsgOnLayerChange": "L'expressió definida i els camps on s'ha aplicat s'esborraran.",
    "smartActionsTable": {
      "name": "Nom",
      "expression": "Expressió",
      "definedFor": "Definit per a"
    }
  },
  "attributeActionsPage": {
    "name": "Nom",
    "type": "Tipus",
    "deleteGroupPopupTitle": "Suprimeix el grup d'accions d'atribut",
    "deleteGroupPopupMsg": "En suprimir el grup s'eliminarà l'acció d'atribut de tots els camps associats.",
    "alreadyAppliedActionMsg": "Acció ${action} que s'ha aplicat en aquest camp al grup",
    "alreadyAppliedActionLayerMsg": "Acció ${action} que s'ha aplicat en aquest camp de la configuració de capes",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Aquest grup no té cap camp associat.",
    "presetNoFieldWarningMsg": "Configureu com a mínim un camp per al grup predefinit: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Camp",
    "valueLabel": "Valor",
    "selectValueLabel": "Seleccioneu un valor",
    "domainFieldHintLabel": "El valor seleccionat és un domini de valor codificat. Es farà servir el valor ${domainValue}"
  },
  "presetPopup": {
    "presetValueLAbel": "Desa l'entitat nova automàticament"
  },
  "dataType": {
    "esriFieldTypeString": "Cadena",
    "esriFieldTypeInteger": "Nombre",
    "esriFieldTypeDate": "Data",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Tipus de data",
    "valueLabel": "Valor",
    "fixed": "Fix",
    "current": "Actual",
    "past": "Passat",
    "future": "Futur",
    "popupTitle": "Seleccioneu un valor",
    "hintForFixedDateType": "Suggeriment: la data i hora especificades s'utilitzaran com a valor per defecte predefinit",
    "hintForCurrentDateType": "Suggeriment: la data i hora actuals s'utilitzaran com a valor per defecte predefinit",
    "hintForPastDateType": "Suggeriment: el valor especificat es restarà de la data i hora actuals per obtenir el valor per defecte predefinit.",
    "hintForFutureDateType": "Suggeriment: el valor especificat s'afegirà a la data i hora actuals per obtenir el valor per defecte predefinit.",
    "noDateDefinedTooltip": "No s'ha definit cap data",
    "relativeDateWarning": "S'ha d'especificar un valor de data o hora per poder desar el valor predefinit per defecte.",
    "customLabel": "Personalitzat"
  },
  "relativeDomains": {
    "fieldSetTitle": "Llista",
    "valueText": "Valor",
    "defaultText": "Per defecte",
    "selectedDomainFieldsHint": "Camps de domini seleccionats: ${domainFields}",
    "selectDefaultDomainMsg": "Seleccioneu un domini de valors per defecte o assegureu-vos que la casella de selecció del domini per defecte estigui activada"
  }
});