define({
  "_widgetLabel": "Розумний редактор",
  "_featureAction_SmartEditor": "Розумний редактор",
  "noEditPrivileges": "Ваш обліковий запис не має дозволу створювати або змінювати дані.",
  "loginPopupTitle": "Увійти в систему",
  "loginPopupMessage": "${widgetName} потребує дозволів та кредитів для пошуку та зберігання адресної інформації. Бажаєте увійти у систему та використовувати цю можливість?",
  "noCreditsOrPrivilegeWarningMessage": "Ваш обліковий запис не має дозволів та кредитів для пошуку та зберігання адресної інформації за допомогою ${widgetName}. Зверніться до адміністратора вашої організації для запиту дозволів і кредитів. Натисніть кнопку OK, щоб продовжити редагування.",
  "unableToUseLocator": "Локатор недоступний. Неможливо виконати дію(-ї) атрибутів адреси. Натисніть кнопку OK, щоб продовжити редагування.",
  "locatorDisabledWaning": "Локатор не активовано. Зверніться до адміністратора вашої організації для запиту цієї можливості. Натисніть кнопку OK, щоб продовжити редагування.",
  "noFeatureInAIWarning": "Об'єкт(-и) не вибрано. Виберіть об'єкт для редагування або натисніть «Скасувати», щоб повернутися на головний екран.",
  "noEditableLayerWarning": "Ваш обліковий запис не має дозволу створювати або змінювати дані, або ця веб-карта не містить редагованих шарів.",
  "noVisibleCreateLayerWarning": "Шар(-и) не відображається на поточному рівні масштабування. Збільшіть або зменшіть масштаб, щоб створити/змінити об'єкти.",
  "noVisibleUpdateLayerWarning": "Шар(-и) не відображається на поточному рівні масштабування. Збільшіть або зменшіть масштаб, щоб змінити об'єкти.",
  "checkLayerVisibilityInWebMapWarning": "Переконайтесь, що шари відображаються на карті для створення або зміни об’єктів.",
  "showSelectionInAITitle": "Вибрані об’єкти",
  "showSelectionInAIMsg": "Завантажити поточний вибір у ${widgetName}?",
  "widgetActive": "Активний",
  "widgetNotActive": "Не активний",
  "pressStr": "Натиснути ",
  "ctrlStr": " CTRL ",
  "snapStr": " для активації замикання",
  "noAvailableTempaltes": "Немає доступних шаблонів",
  "editorCache": " - Кеш-пам’ять редактора",
  "presetFieldAlias": "Поле",
  "presetValue": "Значення за замовчуванням",
  "usePresetValues": " Використовувати значення за замовчуванням (тільки нові об'єкти)",
  "editGeometry": " Редагувати геометрію",
  "savePromptTitle": "Зберегти об'єкт",
  "savePrompt": "Бажаєте зберегти поточний об'єкт?",
  "deletePromptTitle": "Видалити об'єкт",
  "deleteAttachment": "Видалити прикріплення",
  "deletePrompt": "Бажаєте видалити вибраний об'єкт?",
  "attachmentLoadingError": "Помилка при завантаження прикріплень",
  "attachmentSaveDeleteWarning": "Попередження: зміни до прикріплень зберігаються автоматично",
  "autoSaveEdits": "Автоматично зберігати новий об'єкт",
  "addNewFeature": "Створити новий об'єкт",
  "featureCreationFailedMsg": "Неможливо створити новий запис/об'єкт",
  "relatedItemTitle": "Пов’язана таблиця/шар",
  "relatedFeatureCount": "${layerTitle} з ${featureCount} об’єктів",
  "createNewFeatureLabel": "Створити новий об’єкт для ${layerTitle}",
  "invalidRelationShipMsg": "Переконайтесь, що поле первинного ключа: '${parentKeyField}' містить дійсне значення",
  "pendingFeatureSaveMsg": "Збережіть редагування об'єкту перш ніж створювати пов’язаний об'єкт.",
  "attachmentsRequiredMsg": "(*) Потрібні прикріплення.",
  "coordinatePopupTitle": "Перемістити об'єкт у місце розташування XY",
  "coordinatesSelectTitle": "Система координат:",
  "mapSpecialReferenceDropdownOption": "Просторова прив'язка карти",
  "latLongDropdownOption": "Широта/довгота",
  "mgrsDropdownOption": "Військова система прямокутних координат (MGRS)",
  "mgrsTextBoxLabel": "Координата:",
  "xAttributeTextBoxLabel": "X-координата:",
  "yAttributeTextBoxLabel": "Y-координата:",
  "latitudeTextBoxLabel": "Широта:",
  "longitudeTextBoxLabel": "Довгота:",
  "presetGroupFieldsLabel": "'${groupName}' буде застосовано до наступних полів шару:",
  "presetGroupNoFieldsLabel": "'${groupName}' не має жодних пов’язаних полів",
  "groupInfoLabel": "Відомості про групу для '${groupName}'",
  "editGroupInfoIcon": "Редагувати значення групи для ${groupName}",
  "filterEditor": {
    "all": "Всі",
    "noAvailableTempaltes": "Немає доступних шаблонів",
    "searchTemplates": "Пошук шаблонів",
    "filterLayerLabel": "Фільтрувати шари"
  },
  "invalidConfiguration": "Віджет не налаштовано або шари у конфігурації більше не присутні у карті. Відкрийте додаток у режимі розробника та повторно налаштуйте віджет.",
  "geometryServiceURLNotFoundMSG": "Неможливо отримати URL сервісу геометрії",
  "clearSelection": "Закрити",
  "refreshAttributes": "Оновити атрибути динамічного об'єкту",
  "automaticAttributeUpdatesOn": "Автоматичне оновлення атрибутів об'єкту: УВІМКН.",
  "automaticAttributeUpdatesOff": "Автоматичне оновлення атрибутів об'єкту: ВИМКН.",
  "moveSelectedFeatureToGPS": "Перемістити вибраний об'єкт у поточне місце розташування GPS",
  "moveSelectedFeatureToXY": "Перемістити вибраний об'єкт у місце розташування XY",
  "mapNavigationLocked": "Навігація по карті: заблоковано",
  "mapNavigationUnLocked": "Навігація по карті: розблоковано",
  "copyFeatures": {
    "title": "Виберіть об'єкти для копіювання",
    "createFeatures": "Створити об'єкти",
    "createSingleFeature": "Створити 1 складений об'єкт",
    "createOneSingleFeature": "Створити об'єкт",
    "noFeaturesSelectedMessage": "Об'єкти не вибрано",
    "selectFeatureToCopyMessage": "Виберіть об'єкти для копіювання",
    "multipleFeatureSaveWarning": "При створенні кількох об’єктів за допомогою цієї функціональності всі об’єкти будуть одразу збережені. Зіставлення полів не підтримується при створенні нового складеного об'єкта.",
    "copyFeatureUpdateGeometryError": "Не вдалося оновити геометрію вибраних об'єктів",
    "canNotSaveMultipleFeatureWarning": "Ви можете скопіювати лише один об'єкт, якщо цільовий шар має унікальні поля значень.",
    "createOnlyOneMultipartFeatureWarning": "Ви можете скопіювати лише один об’єкт або створити один складений об'єкт, якщо цільовий шар має унікальні поля значень.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} з ${totalFeatures} об'єктів вибрано"
  },
  "addingFeatureError": "Помилка під час додавання вибраних об'єктів в шарі. Спробуйте знову.",
  "addingFeatureErrorCount": "Не вдалося копіювати '${copyFeatureErrorCount}' об'єкт(-и). Бажаєте повторити спробу для відсутніх об'єктів?",
  "selectingFeatureError": "Помилка під час вибору об'єктів в шарі. Спробуйте знову.",
  "customSelectOptionLabel": "Виберіть об'єкти для копіювання",
  "copyFeaturesWithPolygon": "Копіювати за полігоном",
  "copyFeaturesWithRect": "Копіювати за чотирикутником",
  "copyFeaturesWithLasso": "Копіювати за ласо",
  "noFeatureSelectedMessage": "Об'єкти не вибрано",
  "multipleFeatureSaveMessage": "Всі об'єкти будуть зразу збережені. Бажаєте продовжити?",
  "relativeDates": {
    "dateTypeLabel": "Тип дати",
    "valueLabel": "Значення",
    "fixed": "Фіксований",
    "current": "Поточний",
    "past": "Попереднє",
    "future": "Майбутнє",
    "popupTitle": "Вибрати значення",
    "hintForFixedDateType": "Підказка: Указані дата і час будуть використані як попередньо задані значення за замовчуванням.",
    "hintForCurrentDateType": "Підказка: Поточні дата і час будуть використані як попередньо задані значення за замовчуванням.",
    "hintForPastDateType": "Підказка: Попередньо задане значення за замовчуванням отримується відніманням указаного значення від поточних дати й часу.",
    "hintForFutureDateType": "Підказка: Попередньо задане значення за замовчуванням отримується додаванням указаного значення до поточних дати й часу.",
    "noDateDefinedTooltip": "Дані не визначені",
    "relativeDateWarning": "Для збереження заданого значення за замовчуванням повинне бути задане значення дати або часу.",
    "customLabel": "Задається користувачем",
    "layerLabel": "Шар",
    "domainFieldHintLabel": "Вибране значення є кодованим доменом значень. Значення: \"${domainValue}\" буде використовуватися"
  },
  "valuePicker": {
    "popupTitle": "Вибрати значення",
    "popupHint": "Поточний об'єкт перетинає декілька об'єктів, виберіть значення для відповідного поля",
    "buttonTooltip": "Виберіть значення з декількох об'єктів, які перетинаються"
  },
  "uniqueValueErrorMessage": "Значення в \"${fieldName}\" вже існує. Надайте нове значення.",
  "requiredFields": {
    "displayMsg": "Потрібні поля не можуть бути порожніми. Вкажіть значення для загальних полів нижче.",
    "popupTittle": "Потрібні поля",
    "foundNullRecordCount": "${fieldName} (Знайдено за ${count} секунд)"
  },
  "fieldsMapping": {
    "popupTittle": "Застосувати зіставлення полів",
    "fieldsMatchingCheckboxLabel": "Значення зі скопійованих об’єктів замінюють значення за замовчуванням у цільових полях",
    "resetLabel": "Скинути",
    "clearLabel": "Очистити",
    "fieldsInTargetLayerLabel": "Ціль",
    "fieldsInSourceLayerLabel": "Джерело",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} поля(-ів) зіставлено)",
    "selectSourceFieldLabel": "- Вибрати-",
    "selectFieldAriaLabel": "Вибрати вихідне поле для цільового поля ${targetField}",
    "informativeText": "Перевірте зіставлення від вихідних до цільових полів, та за потреби налаштуйте.",
    "dynamicValueText": "Встановлено динамічне значення",
    "noFieldsToMatchLabel": "Немає полів для зіставлення"
  },
  "cantLocateUserLocation": "Не вдалося визначити ваше місцезнаходження",
  "tryAgainButtonLabel": "Повторити спробу",
  "copyFeatureFailedPopupTitle": "Ой!"
});