define({
  "taskUrl": "Tjeneste-URL for udsigtsområde",
  "portalURL": "Angiv URL-adressen til din ArcGIS Online-organisation eller Portal for ArcGIS",
  "portalURLError": "Den konfigurerede URL-adresse til din ArcGIS Online-organisation eller Portal for ArcGIS.",
  "privilegeError": "Din brugerrolle kan ikke udføre analyse. For at du kan udføre analyse, skal din organisations administrator skal give dig bestemte <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">rettigheder</a>.",
  "noServiceError": "Højdeanalysetjenesten er ikke tilgængelig. Kontrollér dine ArcGIS Online-organisations- eller Portal for ArcGIS-konfigurationer.",
  "serviceURLPlaceholder": "Angiv URL for udsigtsområdets geoprocesseringsopgave",
  "setTask": "Indstil",
  "setTaskTitle": "Indstil udsigtsområdets geoprocesseringsopgave",
  "serviceURLError": "Den geoprocesseringsopgave, du forsøger at konfigurere med denne widget, er ikke gyldig. Vælg en gyldig URL for udsigtsområdets geoprocesseringsopgave.",
  "defaultMilsForAnglesLabel": "Brug miles til vinkler som standard",
  "defaultObserverHeightLabel": "Standardenhed for observatørhøjde",
  "defaultObservableDistanceLabel": "Standardenhed for observationsafstand",
  "units": {
    "miles": "Miles",
    "kilometers": "Kilometer",
    "feet": "Fod",
    "meters": "Meter",
    "yards": "Yards",
    "nauticalMiles": "Sømil"
  },
  "helpIconTooltip": "Listen med operationelle lag består af lag fra det aktuelle webkort, der er af geometritypen polygon.",
  "selectOperationalLayerLabel": "Vælg et operationelt lag for at opnå resultater",
  "lineOfSightTabTitle": "Sigtelinje",
  "symbologyTabTitle": "Symbologi",
  "transparency": "Gennemsigtighed",
  "outline": "Yderlinje",
  "fill": "Fyld (farve anvendes kun, når typografien er indstillet til massiv)",
  "style": "Style",
  "selectOpLayerLabel": "Vælg et operationelt lag for at opnå resultater",
  "selectDefaultMeasurementLabel": "Vælg en standardmåleenhed",
  "visibleSectionLabel": "Synlig sektion",
  "nonVisibleSectionLabel": "Ikke-synlig sektion",
  "visibleSectionButtonLabel": "Konfigurér indstillinger for synlig sektion",
  "nonVisibleSectionButtonLabel": "Konfigurér indstillinger for ikke-synlig sektion",
  "colorPicker": "Farvevælger",
  "lineStyles": {
    "esriSLSDash": "Streg",
    "esriSLSDashDot": "Streg-prik",
    "esriSLSDashDotDot": "Streg-prik-prik",
    "esriSLSDot": "Punktum",
    "esriSLSLongDash": "Lang streg",
    "esriSLSLongDashDot": "Lang streg-prik",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Kort streg",
    "esriSLSShortDashDot": "Kort streg-prik",
    "esriSLSShortDashDotDot": "Kort streg-prik-prik",
    "esriSLSShortDot": "Kort prik",
    "esriSLSSolid": "Udfyldt"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Baglæns",
    "esriSFSCross": "Kryds",
    "esriSFSDiagonalCross": "Diagonalt",
    "esriSFSForwardDiagonal": "Frem",
    "esriSFSHorizontal": "Vandret",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Udfyldt",
    "esriSFSVertical": "Lodret"
  }
});