define({
  "_widgetLabel": "스마트 편집기",
  "_featureAction_SmartEditor": "스마트 편집기",
  "noEditPrivileges": "내 계정에 데이터를 만들거나 수정할 권한이 없습니다.",
  "loginPopupTitle": "로그인",
  "loginPopupMessage": "주소 정보를 검색하고 저장하려면 ${widgetName}에 권한 및 크레딧이 필요합니다. 로그인하고 이 기능을 사용하시겠습니까?",
  "noCreditsOrPrivilegeWarningMessage": "이 계정은 ${widgetName}에서 주소 정보를 검색하고 저장하기 위한 권한 및 크레딧이 없습니다. 기관 관리자에게 문의하여 권한 및 크레딧을 요청하세요.",
  "unableToUseLocator": "로케이터에 접근할 수 없습니다. 주소 속성 작업이 수행되지 않습니다.",
  "locatorDisabledWaning": "로케이터가 활성화되어 있지 않습니다. 이 기능을 요청하려면 기관 관리자에게 문의하세요.",
  "noFeatureInAIWarning": "선택한 피처가 없습니다. 편집을 수행할 피처를 선택하거나 취소를 클릭하여 메인 화면으로 돌아갑니다.",
  "noEditableLayerWarning": "해당 계정에는 데이터를 만들거나 수정할 수 있는 권한이 없거나, 이 웹 맵에 편집 가능한 레이어가 없습니다.",
  "noVisibleCreateLayerWarning": "현재 확대/축소 수준에서는 레이어를 볼 수 없습니다. 확대 또는 축소하여 피처를 생성/수정하세요.",
  "noVisibleUpdateLayerWarning": "현재 확대/축소 수준에서는 레이어를 볼 수 없습니다. 확대 또는 축소하여 피처를 수정하세요.",
  "checkLayerVisibilityInWebMapWarning": "피처를 생성 또는 수정하려면 맵에서 레이어를 볼 수 있는지 확인하세요.",
  "showSelectionInAITitle": "선택한 피처",
  "showSelectionInAIMsg": "${widgetName}에서 현재 선택 항목을 불러오시겠습니까?",
  "widgetActive": "활성",
  "widgetNotActive": "비활성",
  "pressStr": "Ctrl을 ",
  "ctrlStr": " 눌러 ",
  "snapStr": " 스내핑 활성화",
  "noAvailableTempaltes": "사용 가능한 템플릿이 없음",
  "editorCache": " - 편집기 캐시",
  "presetFieldAlias": "필드",
  "presetValue": "프리셋 값",
  "usePresetValues": " 프리셋 값 사용(새 피처만)",
  "editGeometry": " 지오메트리 편집",
  "savePromptTitle": "피처 저장",
  "savePrompt": "현재 피처를 저장하시겠습니까?",
  "deletePromptTitle": "피처 삭제",
  "deleteAttachment": "첨부 파일 삭제",
  "deletePrompt": "선택한 피처를 삭제하시겠습니까?",
  "attachmentLoadingError": "첨부 파일 업로드 오류",
  "attachmentSaveDeleteWarning": "경고: 첨부 파일 변경이 자동으로 저장됨",
  "autoSaveEdits": "자동으로 새 피처 저장",
  "addNewFeature": "새 피처 생성",
  "featureCreationFailedMsg": "새 레코드/피처를 생성할 수 없음",
  "relatedItemTitle": "릴레이트 테이블/레이어",
  "relatedFeatureCount": "${featureCount}개의 피처가 있는 ${layerTitle}",
  "createNewFeatureLabel": "${layerTitle}의 새 피처 생성",
  "invalidRelationShipMsg": "기본 키 필드 '${parentKeyField}'의 값이 올바른지 확인하세요.",
  "pendingFeatureSaveMsg": "릴레이트 피처를 생성하기 전에 피처 편집 사항을 저장하세요.",
  "attachmentsRequiredMsg": "(*) 첨부 파일이 필요합니다(필수).",
  "coordinatePopupTitle": "피처를 XY 위치로 이동",
  "coordinatesSelectTitle": "좌표계:",
  "mapSpecialReferenceDropdownOption": "맵 공간 참조",
  "latLongDropdownOption": "위도/경도",
  "mgrsDropdownOption": "MGRS(Military Grid Reference System)",
  "mgrsTextBoxLabel": "좌표:",
  "xAttributeTextBoxLabel": "X 좌표:",
  "yAttributeTextBoxLabel": "Y 좌표:",
  "latitudeTextBoxLabel": "위도:",
  "longitudeTextBoxLabel": "경도:",
  "presetGroupFieldsLabel": "'${groupName}'이(가) 다음 레이어 필드에 적용됨:",
  "presetGroupNoFieldsLabel": "'${groupName}'에는 연관된 필드가 없음",
  "groupInfoLabel": "'${groupName}'의 그룹 정보",
  "editGroupInfoIcon": "${groupName}의 그룹 값 편집",
  "filterEditor": {
    "all": "모두",
    "noAvailableTempaltes": "사용 가능한 템플릿이 없음",
    "searchTemplates": "템플릿 검색",
    "filterLayerLabel": "레이어 필터링"
  },
  "invalidConfiguration": "위젯이 구성되지 않았거나 구성의 레이어가 더 이상 맵에 없습니다. 빌더 모드에서 앱을 열고 위젯을 다시 구성하세요.",
  "geometryServiceURLNotFoundMSG": "지오메트리 서비스 URL을 가져올 수 없음",
  "clearSelection": "닫기",
  "refreshAttributes": "동적 피처 속성 업데이트",
  "automaticAttributeUpdatesOn": "피처 속성 자동 업데이트: 켜짐",
  "automaticAttributeUpdatesOff": "피처 속성 자동 업데이트: 꺼짐",
  "moveSelectedFeatureToGPS": "선택한 피처를 현재 GPS 위치로 이동",
  "moveSelectedFeatureToXY": "선택한 피처를 XY 위치로 이동",
  "mapNavigationLocked": "맵 탐색: 잠금",
  "mapNavigationUnLocked": "맵 탐색: 잠금 해제",
  "copyFeatures": {
    "title": "피처 복사",
    "createFeatures": "피처 생성",
    "createSingleFeature": "멀티파트 피처 1개 생성",
    "createOneSingleFeature": "피처 생성",
    "noFeaturesSelectedMessage": "선택된 피처 없음",
    "selectFeatureToCopyMessage": "복사할 피처를 선택하세요.",
    "multipleFeatureSaveWarning": "참고: 복사 기능을 사용하여 여러 피처를 생성하면 모든 새 피처가 즉시 저장됩니다.",
    "copyFeatureUpdateGeometryError": "선택한 피처의 지오메트리를 업데이트할 수 없음",
    "canNotSaveMultipleFeatureWarning": "참고: 고유 값 필드에는 동일한 값을 사용하여 여러 피처를 복사할 수 없습니다. 피처를 하나만 선택하세요.",
    "createOnlyOneMultipartFeatureWarning": "참고: 하나의 다중 파트 피처만 생성할 수 있습니다."
  },
  "addingFeatureError": "레이어의 선택된 피처를 추가하는 중 오류가 발생했습니다. 다시 시도하세요.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}'개 피처를 복사하지 못했습니다. 누락된 피처에 대해 다시 시도하시겠습니까?",
  "selectingFeatureError": "레이어의 피처를 선택하는 중 오류가 발생했습니다. 다시 시도하세요.",
  "customSelectOptionLabel": "복사할 피처 선택",
  "noFeatureSelectedMessage": "선택한 피처 없음",
  "multipleFeatureSaveMessage": "모든 피처가 즉시 저장됩니다. 계속하시겠습니까?",
  "relativeDates": {
    "dateTypeLabel": "데이터 유형",
    "valueLabel": "값",
    "fixed": "고정",
    "current": "현재",
    "past": "이전",
    "future": "이후",
    "popupTitle": "값 선택",
    "hintForFixedDateType": "힌트: 지정된 날짜와 시간이 프리셋 기본값으로 사용됩니다.",
    "hintForCurrentDateType": "힌트: 현재 날짜와 시간이 프리셋 기본값으로 사용됩니다.",
    "hintForPastDateType": "힌트: 지정된 값이 현재 날짜와 시간에서 차감되어 프리셋 기본값으로 사용됩니다.",
    "hintForFutureDateType": "힌트: 지정된 값이 현재 날짜와 시간에 더해져 프리셋 기본값으로 사용됩니다.",
    "noDateDefinedTooltip": "정의된 날짜가 없음",
    "relativeDateWarning": "날짜 또는 시간 값은 기본 프리셋 값을 저장할 수 있도록 지정해야 합니다.",
    "customLabel": "사용자 정의",
    "layerLabel": "레이어",
    "domainFieldHintLabel": "선택한 값은 코드 값 도메인입니다. 값 \"${domainValue}\"이(가) 사용됩니다."
  },
  "valuePicker": {
    "popupTitle": "값 선택",
    "popupHint": "현재 피처는 다중 피처와 교차하고 있습니다. 해당 필드의 값을 선택하세요.",
    "buttonTooltip": "다중 교차 피처에서 값 선택"
  },
  "uniqueValueErrorMessage": "\"${fieldName}\"의 값이 이미 존재합니다. 새 값을 입력하세요.",
  "requiredFields": {
    "displayMsg": "필수 필드는 비워 둘 수 없습니다. 아래의 일반 필드에 값을 입력하세요.",
    "popupTittle": "필수 필드",
    "foundNullRecordCount": "${fieldName}(${count}개의 레코드에서 발견됨)"
  },
  "cantLocateUserLocation": "내 위치를 파악할 수 없습니다.",
  "tryAgainButtonLabel": "다시 시도",
  "copyFeatureFailedPopupTitle": "죄송합니다."
});