define({
  "_widgetLabel": "A fenyegetések elemzése",
  "threatAnalysisMainPageTitle": "A JCAT terrorizmus elleni útmutatója alapján",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Bemeneti hely",
  "interactive": "Interaktív",
  "fromCoord": "Rögzített koordináta",
  "existingFeature": "Meglévő vektoros elemből",
  "threatAnalysisCoordInputLabel": "Fenyegetés helye",
  "enterCoords": "Koordináták megadása",
  "threatAddPointToolTip": "Fenyegetés helyének hozzáadása",
  "threatDrawPointToolTip": "Kattintson ide a fenyegetés helyének hozzáadásához",
  "threatType": "Fenyegetés típusa",
  "threatPlaceholder": "Kezdje el a beírást a fenyegetés kereséséhez",
  "zoneTypeLabel": "Zóna típusa",
  "feetLabel": "Láb",
  "metersLabel": "Méter",
  "unitsLabel": "Mértékegységek",
  "threatGraphicLayer": "Fenyegetésgrafikon",
  "style": "Stílus",
  "settingsTitle": "Beállítások",
  "colorPicker": "színválasztó",
  "lineStyles": {
    "esriSLSDash": "Szaggatott",
    "esriSLSDashDot": "Vonal-pont",
    "esriSLSDashDotDot": "Vonal-pont-pont",
    "esriSLSDot": "Pont",
    "esriSLSLongDash": "Hosszú vonal",
    "esriSLSLongDashDot": "Hosszú vonal-pont",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Rövid vonal",
    "esriSLSShortDashDot": "Rövid vonal-pont",
    "esriSLSShortDashDotDot": "Rövid vonal-pont-pont",
    "esriSLSShortDot": "Rövid pont",
    "esriSLSSolid": "Folytonos"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Hátra",
    "esriSFSCross": "Kereszt",
    "esriSFSDiagonalCross": "Átlós",
    "esriSFSForwardDiagonal": "Előre",
    "esriSFSHorizontal": "Vízszintes",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Folytonos",
    "esriSFSVertical": "Függőleges"
  },
  "resultsTitle": "Eredmények",
  "publishTABtn": "Közzététel",
  "layerName": "Közzétett rétegnév",
  "invalidLayerName": "A réteg neve csak alfanumerikus karaktereket és aláhúzás karaktereket tartalmazhat",
  "missingLayerNameMessage": "Meg kell adnia egy érvényes rétegnevet a közzététel előtt",
  "publishingFailedLayerExists": "Sikertelen közzététel: Már van {0} nevű vektoros szolgáltatás. Válasszon másik rétegnevet.",
  "checkService": "Szolgáltatás ellenőrzése: {0}",
  "createService": "Szolgáltatás létrehozása: {0}",
  "unableToCreate": "Nem lehet létrehozni: {0}",
  "addToDefinition": "Hozzáadás a meghatározáshoz: {0}",
  "successfullyPublished": "Sikeresen közzétett webes réteg",
  "successfullyAppended": "Webes réteghez sikeresen hozzáadott új vektoros elemek",
  "manageWebLayerText": "Webes réteg kezelése",
  "userRole": "Nem lehet létrehozni a szolgáltatást, mert a felhasználónak nincs megfelelő engedélye",
  "retrieveExistingLayerError": "Nem lehet lekérni a következőt: {0}. A közzétételt másik rétegnévvel végezze.",
  "publishToNewLayer": "Eredmények közzététele új vektoros rétegbe.",
  "layerNameExists": "A rétegnév már létezik. Kérjük, használjon egy másik rétegnevet.",
  "pipeBombLabel": "Csőbomba",
  "suicideBombLabel": "Öngyilkos merénylő",
  "briefcaseLabel": "Aktatáska",
  "carLabel": "Autó",
  "suvVanLabel": "SUV/FURGON",
  "smallDeliveryTruckLabel": "Kisteherautó",
  "containerWaterTruckLabel": "Konténerszállító/vízszállító teherautó",
  "semiTrailerLabel": "Félpótkocsis teherautó",
  "transparencyLabel": "Átlátszóság",
  "outline": "Kontúr",
  "fill": "Kitöltés (a Szín beállítás csak az egyszínű stílus beállítása esetén érhető el)",
  "createBtn": "Zónák létrehozása",
  "clearBtn": "Törlés",
  "invalidNumberMessage": "A megadott érték nem érvényes",
  "invalidRangeMessage": "Az értéknek 0-nál nagyobbnak kell lennie",
  "parseCoordinatesError": "Nem sikerült a koordináták elemzése. Ellenőrizze a bevitt adatokat.",
  "selectDrawModeLabel": "Rajzolási mód kiválasztása",
  "selectFeatureLabel": "Vektoros elem kiválasztása a rétegről",
  "smallLPGTank": "Kis LPG-tartály",
  "largeLPGTank": "Nagy LPG-tartály",
  "commercialResidentialLPGTank": "Kereskedelmi célú/lakossági LPG-tartály",
  "smallLPGTruck": "Kis LPG-szállító teherautó",
  "semiTankerLPG": "LPG-szállító tartályos félpótkocsi",
  "zoneDescriptionColLabel": "Zóna leírása",
  "distanceColLabel": "Távolság",
  "zoneDescColLabel": "Zóna leírása",
  "descriptionLabel": "Leírás",
  "editThreatZonePopupLabel": "Fenyegetési zóna szimbólumrendszer szerkesztése",
  "symbologyColLabel": "Szimbólumrendszer",
  "actions": "Műveletek",
  "threatTypeSelectLabel": "Válasszon fenyegetéstípust:",
  "distanceLabel": "Távolság (${unitAbbr})",
  "layerCountHint": "Tipp: A(z) ${layerCount} vektoros réteggel rendelkező webes réteg közzé lesz téve.",
  "selectLabel": "Kiválasztás",
  "mandatoryLabel": "Kötelező evakuálási távolság",
  "safeLabel": "Biztonságos evakuálási távolság",
  "fireBallDiameterLable": "Tűzgömb átmérője",
  "lpgSafeDistanceLable": "Biztonságos távolság"
});