define({
  "locatorUrl": "URL Penentu Lokasi",
  "set": "Atur",
  "locatorName": "Nama Penentu Lokasi",
  "locatorExample": "Contoh",
  "countryCode": "Kode Negara atau Wilayah",
  "eg": "mis. ",
  "countryCodeHint": "Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",
  "minCandidateScore": "Skor Kandidat Minimum",
  "minCandidateScoreHint": "Jika nilai ini dibiarkan kosong, skor kandidat minimum 90 akan digunakan",
  "enableSingleField": "Opsi Kolom Tunggal",
  "singleFieldHint": "Data alamat akan berada dalam kolom tunggal",
  "enableMultiField": "Opsi Kolom Ganda",
  "multiFieldHint": "Data alamat akan berada dalam kolom ganda",
  "enableXYField": "Opsi Kolom X/Y",
  "xyFieldHint": "Data akan berisi nilai koordinat X/Y",
  "instructionGeocode": "Tambah dan konfigurasikan layanan penentu lokasi.",
  "invalidUrlTip": "URL ${URL} tidak valid atau tidak dapat diakses.",
  "geocodeTabLabel": "Pengaturan Lokasi",
  "lookupList": "Nama Kolom yang akan Dikenali",
  "isRecognized": "Nama kolom pada tabel di bawah ini secara otomatis dikenali untuk kolom ini",
  "needsEditablePointLayers": "Webmap harus berisi setidaknya satu layer titik yang dapat diedit.",
  "editpageAlias": "Alias",
  "configureFields": "Konfigurasikan Kolom Layer",
  "configureSingleFields": "Konfigurasikan Kolom Alamat Tunggal",
  "configureMultiFields": "Konfigurasikan Kolom Alamat Ganda",
  "configureXYFields": "Konfigurasikan Kolom X/Y",
  "noFields": "Gunakan tindakan edit untuk menentukan satu atau lebih kolom untuk ditampilkan",
  "display": "Tampilan",
  "duplicate": "Temukan Duplikat",
  "duplicateTip": "Cari nilai yang sama dalam kolom ini di antara file sumber dan layer target./n Saat nilai identik yang sama ditemukan, catatan dari file tidak akan ditentukan lokasinya dan akan diberi tanda sebagai duplikat.",
  "noSelectField": "Pilih opsi Feature Layer terlebih dahulu",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Garis Bujur)",
  "xyFieldsLabelY": "Y (Garis Lintang)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Bujur Timur",
  "northing": "Lintang Utara",
  "lon": "BUJUR",
  "lat": "LINTANG",
  "layerOptionHint": "Pilih layer tempat data akan dikirimkan.",
  "layerFieldTitle": "Layer Target",
  "tempSymbolHint": "Pilih simbol yang akan digunakan untuk menampilkan fitur.",
  "tempSymbolTitle": "Simbol Tampilan",
  "maxRecords": "Catatan maks",
  "maxRecordsHint": "Jumlah maks catatan yang akan ditentukan lokasinya",
  "searchRadius": "Cari radius",
  "searchRadiusHint": "Jarak untuk mencari fitur duplikasi dari layer",
  "requiresInteger": "Masukkan nilai numerik.",
  "requiresInteger0100": "Masukkan nilai numerik antara 0 dan 100",
  "requiresLocator": "Tambahkan setidaknya satu penentu lokasi yang valid.",
  "layerFields": "Pengaturan Layer",
  "layerFieldsHint": "Tentukan kolom dari Layer Target yang akan dipetakan ke kolom sumber.",
  "locatorError": "Penentu lokasi tidak valid atau tidak dapat diakses.",
  "optionNotMatch": "Opsi kolom tidak konsisten di seluruh penentu lokasi. Kegagalan mungkin tidak bekerja sesuai yang diharapkan.",
  "targetLayerTabTitle": "Layer Target",
  "locationSettingsTabTitle": "Pengaturan Lokasi",
  "generalSettingsTabTitle": "Pengaturan Umum",
  "addTargetLayersLabel": "Tambahkan Layer Target",
  "introductoryText": "Buat konten instruksional untuk widget",
  "defaultStartPageInstructions": "Widget ini akan membantu pemrosesan dan pengiriman data dari file ke layer yang dipilih di peta.<br/> <br/>Nilai dalam file harus tidak dibatasi koma, tab, titik koma, atau bilah vertikal.",
  "noTargetLayerConfiguredErrorMsg": "Tidak ada layer target yang dikonfigurasikan",
  "noFieldsForTargetLayer": "Pengaturan layer tidak ditentukan dari layer target",
  "locationSettingsNotConfigured": "Pengaturan lokasi tidak dikonfigurasikan secara tepat"
});