define({
  "transparencyLabel": "שקיפות",
  "outline": "קו מתאר",
  "fill": "מילוי (הצבע חל רק כשהסגנון הוא 'מלא')",
  "style": "סגנון",
  "selectOpLayerLabel": "בחר שכבת תפעול לקבלת תוצאות",
  "selectDefaultMeasurementLabel": "בחר יחידת מידה שתהווה ברירת מחדל",
  "helpIconTooltip": "הרשימה של שכבת התפעול מתמלאת בשכבות מה-Web Map הנוכחית, שסוג הגיאומטריה שלהן הוא פוליגון.",
  "lineStyles": {
    "esriSLSDash": "מקווקו",
    "esriSLSDashDot": "קו נקודה",
    "esriSLSDashDotDot": "קו נקודה נקודה",
    "esriSLSDot": "נקודה",
    "esriSLSLongDash": "קו ארוך",
    "esriSLSLongDashDot": "קו נקודה ארוך",
    "esriSLSNull": "ריק",
    "esriSLSShortDash": "קו קצר",
    "esriSLSShortDashDot": "קו נקודה קצר",
    "esriSLSShortDashDotDot": "קו נקודה נקודה קצר",
    "esriSLSShortDot": "נקודה קצרה",
    "esriSLSSolid": "מלא"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "לאחור",
    "esriSFSCross": "צלב",
    "esriSFSDiagonalCross": "אלכסוני",
    "esriSFSForwardDiagonal": "לפנים",
    "esriSFSHorizontal": "אופקי",
    "esriSFSNull": "ריק",
    "esriSFSSolid": "מלא",
    "esriSFSVertical": "אנכי"
  },
  "threatTypeLabel": "סוג איום",
  "generalLabel": "כללי",
  "addThreatTypesLabel": "הוסף סוג איום",
  "actions": "פעולות",
  "newThreatTypePopupLabel": "סוג איום חדש",
  "units": "יחידות",
  "chooseDefaultThreatLabel": "בחר סוג איום שמוגדר כברירת מחדל",
  "defaultThreatTypePopUpLabel": "סוגי איום שמוגדרים כברירת מחדל",
  "editThreatLabel": "ערוך איום",
  "defaultThreatTypeIconTooltip": "רשימת סוגי איומים שמוגדרים כברירת מחדל",
  "uniqueThreatTypeMsg": "הזן סוג איום ייחודי, סוג איום בשם זה כבר קיים.",
  "requiredMsg": "זהו שדה חובה",
  "unitMeasureLabel": "מרחקים הם ב-{0}",
  "chooseDefaultThreatTypeIconLabel": "בחר מתוך ברירת מחדל",
  "pipeBombLabel": "פצצת צינור",
  "suicideBombLabel": "פצצה של מתאבדים",
  "briefcaseLabel": "מזוודה",
  "carLabel": "מכונית",
  "suvVanLabel": "רכב קרוסאובר/ואן",
  "smallDeliveryTruckLabel": "משאית קטנה",
  "containerWaterTruckLabel": "משאית מכולה/להובלת מים",
  "semiTrailerLabel": "סמיטריילר",
  "chemicalThreatLegendLabel": "איום כימי",
  "lpgThreatLegendLabel": "איום LPG",
  "smallLPGTank": "מכל LPG קטן",
  "largeLPGTank": "מכל LPG גדול",
  "commercialResidentialLPGTank": "מכל LPG לאזורי מסחר/מגורים",
  "smallLPGTruck": "משאית LPG קטנה",
  "semiTankerLPG": "מכלית LPG",
  "threatDescriptionColLabel": "תיאור איום",
  "addThreatZoneButtonLabel": "הוסף אזור איום",
  "zoneDescColLabel": "תיאור אזור",
  "distanceLabel": "מרחק (${unitAbbr})",
  "threatTypeHelp": "<p>ודא שהתנאים הבאים מתקיימים עבור סוג איום:<br/><ul><li>סוג האיום לא יכול להיות ריק ועליו להיות ייחודי</li><li>לאיום חייב להיות אזור חוקי אחד לפחות</li><li>תיאור האזור צריך להיות ייחודי עבור איום</li></ul><p/>",
  "descriptionLabel": "תאור",
  "newThreatZonePopupLabel": "אזור איום חדש",
  "editThreatZonePopupLabel": "ערוך אזור איום",
  "uniqueZoneDescriptionMsg": "הזן תיאור אזור ייחודי, תיאור אזור בשם זה כבר קיים.",
  "symbologyColLabel": "סימבולוגיה",
  "zoneDescriptionColLabel": "תיאור אזור",
  "uniqueZoneRequiredMsg": "שם האזור צריך להיות ייחודי עבור ה-",
  "interactive": "אינטראקטיבי",
  "fromCoord": "קואורדינטה קבועה",
  "existingFeature": "מתוך ישויות קיימות",
  "defaultInputLocationLabel": "מיקום קלט שמוגדר כברירת מחדל",
  "defaultInputLayer": "שכבת קלט שמוגדרת כברירת מחדל",
  "defaultThreatType": "סוג איום שמוגדר כברירת מחדל",
  "selectLabel": "בחר",
  "mandatoryLabel": "מרחק פינוי חובה",
  "safeLabel": "מרחק פינוי בטוח",
  "lpgSafeDistanceLable": "מרחק בטוח",
  "fireBallDiameterLable": "קוטר כדור אש"
});