define({
  "defaultAreaUnit": "Noklusējuma laukuma mērvienība",
  "defaultLengthUnit": "Noklusējuma garuma mērvienība",
  "metric": "Metriskā",
  "imperial": "Imperiālā",
  "squareKilometers": "Kv. kilometri",
  "squareMeters": "Kv. metri",
  "squareMiles": "Kv. jūdzes",
  "squareInches": "Kvadrātcollas",
  "squareFeet": "Kv. pēdas",
  "squareYards": "Kv. jardi",
  "squareUSFeet": "Kvadrātpēdas (ASV)",
  "acres": "Akri",
  "ares": "Āri",
  "hectares": "Hektāri",
  "inches": "Collas",
  "feet": "Pēdas",
  "yards": "Jardi",
  "miles": "Jūdzes",
  "nauticalMiles": "Jūras jūdzes",
  "feetUS": "Pēdas (ASV)",
  "meters": "Metri",
  "kilometers": "Kilometri",
  "showArea": "Laukums",
  "showDistance": "Attālums",
  "showLocation": "Novietojums",
  "showSlice": "Sadalīt sektoros",
  "showtools": "Rādīt mērīšanas rīkus:",
  "allHidedTips": "Ir jāatlasa vismaz viens rīks."
});