define({
  "_widgetLabel": "Пакетный редактор атрибутов",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Имя слоя",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Нет настроенных слоев, доступных для редактирования",
  "editorPopupTitle": "Пакетный редактор атрибутов",
  "editorPopupSaveBtn": "Сохранить",
  "editorPopupMultipleValues": "",
  "clear": "Очистить",
  "featuresUpdated": "${0} / ${1} объектов обновлено",
  "featuresSelected": "${0} объектов выделено",
  "featuresSkipped": "Пропущено",
  "featuresNoPermision": "Выбрано ${0} объекта(ов), но нет разрешения на редактирование.",
  "search": "Поиск",
  "queryInput": "Введите значение для запроса",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Задайте корректный фильтр.",
  "filterPopup": "Фильтр слоя",
  "filterAppend": "Если фильтр уже задан в веб-карте для этого слоя",
  "filterAppendOR": "Присоединить какое-либо выражение к существующему фильтру карты",
  "filterAppendAND": "Присоединить все выражения к существующему фильтру карты",
  "cancel": "Отмена",
  "noValue": "Нет значения",
  "emptyString": "Пустая строка",
  "existingValue": "Сохранить существующие данные",
  "newDate": "Новая дата",
  "valueChooser": "Выберите/введите значение",
  "ok": "OK",
  "drawBox": {
    "point": "Точка",
    "line": "Линия",
    "polyline": "Линия",
    "freehandPolyline": "Произвольная полилиния",
    "extent": "Экстент",
    "polygon": "Полигон",
    "freehandPolygon": "Полигон произвольной формы",
    "clear": "Очистить",
    "addPointToolTip": "Щелкните, чтобы создать выборку в этой области",
    "addShapeToolTip": "Нарисуйте рамку, чтобы выбрать объекты",
    "freehandToolTip": "Нажмите и удерживайте, чтобы нарисовать рамку для выбора объектов",
    "startToolTip": "Нарисуйте рамку, чтобы выбрать объекты"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Объект из ${0} вернул недостоверный ID",
    "noSelectedLayers": "Нет выбранных слоев с записями для обновления",
    "inputValueError": "Недопустимое значение в форме",
    "saveError": "Не удалось сохранить ${0} объектов",
    "requiredValue": "Обязательное значение"
  }
});