define({
  "layersPage": {
    "allLayers": "Alle lag",
    "title": "Velg mal for å opprette geoobjekter, eller klikk på et geoobjekt i kartet for å redigere det.",
    "generalSettings": "Generelle innstillinger",
    "layerSettings": "Laginnstillinger",
    "webmapSettingsRadioBtnLabel": "Behold innstillingene i webkartet",
    "customSettingsRadioBtnLabel": "Egendefinerte innstillinger",
    "smartActionsTabTitle": "Smarte handlinger",
    "attributeActionsTabTitle": "Attributthandlinger",
    "geocoderSettingsText": "Innstillinger for geookoding",
    "editDescription": "Oppgi tekst som skal vises for redigeringspanelet",
    "editDescriptionTip": "Teksten vises over malvelgeren. La stå tomt om du ikke ønsker tekst.",
    "promptOnSave": "Spør om endringer skal lagres når skjemaet lukkes eller går til neste post",
    "promptOnSaveTip": "Vis en melding når det nåværende geoobjektet har ulagrede redigeringer. (Kopierer flere geoobjekter, som lagres automatisk.)",
    "promptOnDelete": "Be om bekreftelse ved sletting av post",
    "promptOnDeleteTip": "Vis en melding som ber brukeren bekrefte handlingen når bruker klikker slett.",
    "removeOnSave": "Fjern geoobjekt fra utvalg ved lagring",
    "removeOnSaveTip": "Alternativ for å fjerne geoobjektet fra utvalget som er angitt når posten lagres. Hvis posten er den eneste valgte posten, går panelet tilbake til å vise malsiden.",
    "useFilterEditor": "Bruk geoobjektmal-filter",
    "useFilterEditorTip": "Alternativ for bruk av filtermalvelgeren som gjør det mulig å vise malen for ett lag eller søke etter maler basert på navn.",
    "groupFilteredTemplates": "Grupper søkeresultater",
    "groupFilteredTemplatesTip": "Alternativ for å gruppere søkeresultatene etter lag.",
    "displayShapeSelector": "Vis tegnealternativer",
    "createNewFeaturesFromExisting": "Tillat oppretting av nytt/nye geoobjekt(er) fra eksisterende geoobjekt(er)",
    "createNewFeaturesFromExistingTip": "Alternativ som tillater at brukeren kopierer eksisterende geoobjekter for opprette nye geoobjekter",
    "copiedFeaturesOverrideDefaults": "Verdien(e) fra de(t) kopierte geoobjektet/geoobjektene overstyrer standardverdien(e) i målfeltet/målfeltene",
    "copiedFeaturesOverrideDefaultsTip": "Verdier fra de kopierte geoobjektene vil overstyre malens standardverdier bare for matchende felt",
    "displayShapeSelectorTip": "Alternativ for å vise en liste over gyldige tegnealternativer for den valgte malen.",
    "displayPresetTop": "Vis forhåndsinnstilt verdiliste øverst",
    "displayPresetTopTip": "Mulighet til å vise den forhåndsinnstilte verdilisten over malvelgeren.",
    "listenToGroupFilter": "Bruk filterverdier fra widgeten Grupper filter i Forhåndsinnstilte felt",
    "listenToGroupFilterTip": "Når et filter brukes i widgeten Grupper filter, bruker du verdien i et tilsvarende felt i listen Forhåndsinnstilte verdier.",
    "keepTemplateActive": "Hold valgt mal aktiv",
    "editLayerAddedFromAddData": "Tillat redigering av lag som er lagt til fra miniprogrammet Legg til data.",
    "editLayerAddedFromAddDataTip": "Redigerbare lag som er lagt til i applikasjonen ved hjelp av miniprogrammet Legg til data, kan redigeres.",
    "keepTemplateActiveTip": "Hvis en mal tidligere ble valgt når malvelgeren vises, velger du den på nytt.",
    "geometryEditDefault": "Aktiver geometriredigering som standard",
    "autoSaveEdits": "Lagre nye geoobjekter automatisk",
    "enableAttributeUpdates": "Vis oppdateringsknappen Attributthandlinger",
    "enableAutomaticAttributeUpdates": "Iverksett automatisk attributthandling etter geometrioppdatering",
    "enableLockingMapNavigation": "Aktiver låsing av kartnavigering",
    "enableMovingSelectedFeatureToGPS": "Aktiver flytting av valgt punktgeoobjekt til GPS-posisjon",
    "enableMovingSelectedFeatureToXY": "Aktiver flytting av valgt punktgeoobjekt til XY-posisjon",
    "featureTemplateLegendLabel": "Innstillinger for geoobjektmal og filterverdier",
    "saveSettingsLegendLabel": "Lagre innstillinger",
    "geometrySettingsLegendLabel": "Geometriinnstillinger",
    "actionsSettingsLegendLabel": "Handlingsinnstillinger",
    "buttonPositionsLabel": "Plassering av knappene Lagre, Slett, Tilbake og Lukk",
    "belowEditLabel": "Under redigeringsskjema",
    "aboveEditLabel": "Over redigeringsskjema",
    "switchToMultilineInput": "Bytt til inndata i flere linjer når feltlengden overskrides",
    "enableValuePicker": "Aktiver verdivelger for krysningspunkter",
    "enableValuePickerHint": "Vis en melding når flere verdier er tilgjengelige for et felt med en krysningspunkt attributthandling",
    "expandRelatedTable": "Utvid alle relaterte tabeller/lag ved lasting",
    "expandMainTable": "Utvid alle overordnede lag ved lasting",
    "copyAndAppendFeatureLabel": "Kopier og føy til geoobjekter",
    "allowCopyPolygonLabel": "Tillat kopiering av polygon til punkt",
    "allowCopyPolygonTooltip": "Alternativ som tillater at polygongeoobjekter kopieres inn i maler for punktbaserte målgeoobjekter med geometritransformasjoner",
    "allowCopyLineLabel": "Tillat kopiering av linje til punkt",
    "allowCopyLineTooltip": "Alternativ som tillater at linjegeoobjekter kopieres inn i maler for punktbaserte målgeoobjekter med geometritransformasjoner",
    "pointAtStartLabel": "Punkt på begynnelsen",
    "pointAtStartTooltip": "Legg til et punkt på begynnelsen av linjen som kopieres",
    "pointAtEndLabel": "Punkt på slutten",
    "pointAtEndTooltip": "Legg til et punkt på slutten av linjen som kopieres",
    "layerSettingsTable": {
      "allowDelete": "Tillat sletting",
      "allowDeleteTip": "Tillat sletting – Alternativ som tillater at brukeren sletter et geoobjekt; deaktivert dersom laget ikke støtter sletting",
      "edit": "Redigerbar",
      "editTip": "Redigerbart – Alternativ for å inkludere laget i miniprogrammet",
      "label": "Lag",
      "labelTip": "Lag – Navn på laget slik det er definert i kartet",
      "update": "Deaktiver redigering for geometri",
      "updateTip": "Deaktiver redigering av geometri – Alternativ som deaktiverer muligheten til å flytte geometrien etter at den er plassert, eller flytte geometrien på et eksisterende geoobjekt",
      "allowUpdateOnly": "Kun oppdatering",
      "allowUpdateOnlyTip": "Kun oppdatering – Alternativ som kun tillater endring av eksisterende geoobjekter; avmerket som standard og deaktivert hvis laget ikke støtter oppretting av nye geoobjekter",
      "fieldsTip": "Endre feltene som skal redigeres og definer Smart-attributter",
      "actionsTip": "Handlinger – Alternativ for å redigere felt eller få tilgang til tilknyttede lag/tabeller",
      "description": "Beskrivelse",
      "descriptionTip": "Beskrivelse – Alternativ for å skrive inn tekst som skal vises øverst på siden med attributter.",
      "relationTip": "Vis relaterte lag og tabeller"
    },
    "editFieldError": "Det er ikke mulig å endre felt og smarte attributter i lag som ikke er redigerbare",
    "noConfigedLayersError": "Smart redigering krever ett eller flere redigerbare lag",
    "toleranceErrorMsg": "Ugyldig standardverdi for krysningstoleranse",
    "pixelsToleranecErrorMsg": "Ugyldig standardverdi for pikseltoleranse",
    "invalidMaxCharacterErrorMsg": "Ugyldig verdi i bytt til inndata i flere linjer",
    "featuresSelectionTolerance": "Angi toleransen for valg av geoobjekter (piksler)",
    "featuresSelectionToleranceTooltip": "Setter brukere i stand til enkelt å åpne panelet for attributtredigering ved å klikke på det aktuelle geoobjektet",
    "featuresSelectionToleranceErrorMsg": "Ugyldig toleranseverdi for valg av geoobjekt",
    "autoSaveAttrUpdates": "Lagre attributt- og geometrioppdateringer automatisk",
    "defaultCoordinateSystem": "Standard referansesystem",
    "defaultCoordinateSystemTooltip": "Angi standard referansesystem når et valgt punktgeoobjekt skal flyttes til en ny lokasjon"
  },
  "editDescriptionPage": {
    "title": "Angi tekst for attributtoversikt for <b>${layername}</b> "
  },
  "fieldsPage": {
    "title": "Konfigurer felter for <b>${layername}</b>",
    "copyActionTip": "Attributthandlinger",
    "editActionTip": "Smarte handlinger",
    "description": "Bruk knappen for redigering av handlinger til å aktivere smarte attributter i et lag. Smarte attributter kan kreve, skjule eller deaktivere et felt basert på verdier i andre felt. Bruk knappen for kopiering av handlinger til å aktivere og definere kilden til feltverdien etter krysning, adresse, koordinater og forhåndsinnstilling.",
    "fieldsNotes": "* obligatorisk felt. Hvis du fjerner merket for Vis for dette feltet, og redigeringsmalen ikke fyller inn denne feltverdien, kan du ikke lagre en ny post.",
    "smartAttachmentText": "Konfigurer smarte handlinger for vedlegg",
    "smartAttachmentPopupTitle": "Konfigurer smarte handlinger for vedlegg i <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Velg minst ett visningsfelt for laget ${layerName}",
    "fieldsSettingsTable": {
      "display": "Vis",
      "displayTip": "Vis – Angir om feltet  er synlig eller ikke",
      "edit": "Redigerbar",
      "editTip": "Redigerbart – Merk av hvis feltet finnes i attributtskjemaet",
      "fieldName": "Navn",
      "fieldNameTip": "Navn – Navnet på feltet som er angitt i databasen",
      "fieldAlias": "Alias",
      "fieldAliasTip": "Alias – Navnet på feltet som er angitt i kartet",
      "canPresetValue": "Forhåndsinnstilt",
      "canPresetValueTip": "Forhåndsinnstilt – Alternativ for å vise feltet i listen over forhåndsinnstilte felt og tillate at brukeren angir verdien før redigering",
      "actions": "Handlinger",
      "actionsTip": "Handlinger – Endre rekkefølgen på feltene, eller konfigurer smarte attributter"
    },
    "smartAttSupport": "Smarte attributter støttes ikke i obligatoriske databasefelt"
  },
  "actionPage": {
    "title": "Konfigurer smarte handlinger for <b>${fieldname}</b>",
    "smartActionTitle": "Konfigurer smarte handlinger for <b>${fieldname}</b>",
    "description": "Disse handlingene er alltid deaktivert med mindre du angir vilkårene som skal utløse dem. Handlingene behandles i rekkefølge, og det utløses kun én handling per felt. Bruk knappen for redigering av vilkår til å definere vilkårene.",
    "copyAttributesNote": "Deaktivering av en handling med et gruppenavn blir det samme som å redigere den aktuelle handlingen uavhengig, og det fjerner handlingen for dette feltet fra den aktuelle gruppen.",
    "searchPlaceHolder": "Søk",
    "expandAllLabel": "Vis alle lag",
    "selectAllLabel": "Velg alle felt",
    "domainListTitle": "Domenefelt",
    "noValidFieldTypeMsg": "Det er ingen aktuelle lag tilgjengelig i kartet for denne datatypen",
    "actionsSettingsTable": {
      "rule": "Handling",
      "ruleTip": "Handling – Handling som utføres når vilkårene er oppfylt",
      "expression": "Uttrykk",
      "expressionTip": "Uttrykk – Resulterende uttrykk i SQL-format fra de definerte kriteriene",
      "groupName": "Gruppenavn",
      "groupNameTip": "Gruppenavn – Viser navnet på gruppen som uttrykket brukes fra",
      "actions": "Vilkår",
      "actionsTip": "Kriterier – Endrer rekkefølgen for regelen og definerer kriteriene for når den utløses"
    },
    "copyAction": {
      "description": "Hvis det er aktivert, behandles kilder til feltverdier i rekkefølge til et gyldig kriterium utløses eller listen er fullført. Bruk knappen for redigering av kriterier til å angi kriteriene.",
      "intersection": "Kryss",
      "coordinates": "Koordinater",
      "address": "Adresse",
      "preset": "Forhåndsinnstilt",
      "actionText": "Handlinger",
      "criteriaText": "Vilkår",
      "enableText": "Aktivert"
    },
    "actions": {
      "hide": "Skjul",
      "required": "Påkrevd",
      "disabled": "Deaktivert"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Advarsel: Uavhengig redigering vil fjerne fra gruppen den valgte attributthandlingen som er tilknyttet dette feltet",
      "editGroupHint": "Advarsel: Uavhengig redigering vil fjerne fra gruppen den valgte smarte handlingen som er tilknyttet dette feltet",
      "popupTitle": "Velg redigeringsalternativ",
      "editAttributeGroup": "Den valgte attributthandlingen er angitt fra gruppen. Velg ett av følgende alternativer for å redigere attributthandlingen:",
      "expression": "Uttrykket for den valgte smarte handlingen er definert fra gruppen. Velg ett av følgende alternativer for å redigere uttrykket for den smarte handlingen:",
      "editGroupButton": "Rediger gruppe",
      "editIndependentlyButton": "Rediger uavhengig"
    }
  },
  "filterPage": {
    "submitHidden": "Send inn attributtdata for felt selv om de er skjult",
    "title": "Konfigurer uttrykk for regelen ${action}",
    "filterBuilder": "Angi handling for feltet når posten samsvarer med ${any_or_all} av følgende uttrykk",
    "noFilterTip": "Bruk verktøyene ovenfor til å definere uttrykket for når handlingen er aktiv."
  },
  "geocoderPage": {
    "setGeocoderURL": "Angi geokoder-URL",
    "hintMsg": "Merk: Du er i ferd med å endre geokodingstjenesten. Du må oppdatere eventuelle felttilordninger du har konfigurert.",
    "invalidUrlTip": "URL-en ${URL} er ugyldig eller ikke tilgjengelig."
  },
  "addressPage": {
    "popupTitle": "Adresse",
    "checkboxLabel": "Hent verdi fra geokodingsverktøyet",
    "selectFieldTitle": "Attributt",
    "geocoderHint": "Hvis du vil endre geokodingsverktøy, velger du Innstillinger for geokoding i de generelle innstillingene",
    "prevConfigruedFieldChangedMsg": "Finner ikke tidligere konfigurert attributt i gjeldende innstillinger for geokoding. Attributtet er tilbakestilt til standardverdien.",
    "questionMark": "?",
    "consumesCredits": "Dette verktøyet bruker credits når det brukes sammen med tjenesten ArcGIS Online World Geocoding"
  },
  "coordinatesPage": {
    "popupTitle": "Koordinater",
    "checkboxLabel": "Hent koordinater",
    "coordinatesSelectTitle": "Referansesystem",
    "coordinatesAttributeTitle": "Attributt",
    "mapSpatialReferenceOptionLabel": "Kartets romlige referanse",
    "latLongOptionLabel": "Lengdegrad/breddegrad",
    "MGRS": "Militært rutenettsystem (MGRS)",
    "allGroupsCreatedMsg": "Alle mulige grupper er allerede opprettet",
    "coordinatesSourceTitle": "Koordinatkilde",
    "featureLocation": "Geoobjektlokasjon",
    "myLocation": "Min lokasjon",
    "LatLong": {
      "y": "Breddegrad",
      "x": "Lengdegrad",
      "xy": "Lengdegrad breddegrad",
      "yx": "Breddegrad lengdegrad"
    },
    "MapSpatialReference": {
      "y": "J",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Forhåndsinnstilt",
    "checkboxLabel": "Feltet forhåndsinnstilles",
    "showOnlyDomainFields": "Vis bare domenefelt",
    "hideInPresetDisplay": "Skjul i forhåndsvisning av verdi",
    "presetValueLabel": "Gjeldende forhåndsinnstilte verdi er:",
    "changePresetValueHint": "Hvis du vil endre den forhåndsinnstilte verdien, trykker du på knappen Definer forhåndsinnstilte verdier i de generelle innstillingene."
  },
  "intersectionPage": {
    "groupNameLabel": "Gruppenavn",
    "dataTypeLabel": "Datatype",
    "ignoreLayerRankingCheckboxLabel": "Ignorer lagenes rekkefølge og finn nærmeste geoobjekt fra alle definerte lag",
    "intersectingLayersLabel": "Lag som det skal ekstraheres en verdi fra",
    "layerAndFieldsApplyLabel": "Lag og felt som en ekstrahert verdi skal brukes på",
    "checkboxLabel": "Hent verdi fra felt i krysningslaget",
    "layerText": "Lag",
    "fieldText": "Felter",
    "actionsText": "Handlinger",
    "toleranceSettingText": "Toleranseinnstillinger",
    "addLayerLinkText": "Legg til et lag",
    "useDefaultToleranceText": "Bruk standard toleranse",
    "toleranceValueText": "Toleranseverdi",
    "toleranceUnitText": "Toleranseenhet",
    "pixelsUnitText": "Piksler",
    "useLayerName": "– Bruk lagnavn –",
    "noLayersMessage": "Finner ingen felt i kartlagene som samsvarer med den valgte datatypen.",
    "intersectionLayerHint": "Lagrangering fastsettes i synkende rekkefølge. Bruk pilene under Handlinger til å endre lagenes rekkefølge og prioriterte krysningspunkter."
  },
  "presetAll": {
    "popupTitle": "Definer standard forhåndsinnstilte verdier",
    "deleteTitle": "Slett forhåndsinnstilt verdi",
    "hintMsg": "Navnene på alle unike forhåndsinnstilte felt er oppført her. Hvis du fjerner et forhåndsinnstilt felt, deaktiveres det aktuelle feltet som forhåndsinnstilling fra alle lag/tabeller."
  },
  "intersectionTolerance": {
    "intersectionLabel": "Standard krysningtoleranse for alle geoobjekter",
    "intersectionTitle": "Aktiver en global toleranse for krysninger",
    "pixelsToleranceLabel": "Standard krysningtoleranse (pikselverdi) som skal brukes kun til punktgeoobjekter",
    "pixelsToleranceTitle": "Hvis standard krysningstoleranse for alle geoobjekter er satt til 0, skal denne innstillingen brukes for punktgeoobjekter"
  },
  "smartActionsPage": {
    "smartActionLabel": "Konfigurer smart handling",
    "addNewSmartActionLinkText": "Legg til ny",
    "definedActions": "Angitte handlinger",
    "priorityPopupTitle": "Angi prioritet for smarte handlinger",
    "priorityPopupColumnTitle": "Smarte handlinger",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Gruppenavn",
    "layerForExpressionLabel": "Lag for uttrykk",
    "layerForExpressionNote": "Merk: Dette lagets felter vil bli brukt til å definere kriterier for uttrykket. 'Lag og felter å brukes på' viser bare lag og tabeller som har feltene definert i uttrykket.",
    "expressionText": "Uttrykk",
    "editExpressionLabel": "Rediger uttrykk",
    "layerAndFieldsApplyLabel": "Lag og felter det skal brukes på",
    "submitAttributeText": "Send inn attributtdata for felt selv om de er skjult",
    "priorityColumnText": "Prioritet",
    "requiredGroupNameMsg": "Denne verdien er obligatorisk",
    "uniqueGroupNameMsg": "Skriv inn et unikt gruppenavn; det finnes allerede en gruppe med dette navnet.",
    "deleteGroupPopupTitle": "Slett gruppe for smarte handlinger",
    "deleteGroupPopupMsg": "Sletting av gruppen medfører at uttrykket fjernes fra alle de tilknyttede felthandlngene.",
    "invalidExpression": "Uttrykket må fylles ut",
    "warningMsgOnLayerChange": "Det angitte uttrykket og feltene det brukes i, vil bli slettet.",
    "smartActionsTable": {
      "name": "Navn",
      "expression": "Uttrykk",
      "definedFor": "Angitt for"
    }
  },
  "attributeActionsPage": {
    "name": "Navn",
    "type": "Type",
    "deleteGroupPopupTitle": "Slett gruppe for attributthandlinger",
    "deleteGroupPopupMsg": "Sletting av gruppen medfører at attributthandlingen fjernes fra alle de tilknyttede feltene.",
    "alreadyAppliedActionMsg": "Handlingen ${action} er utført på dette feltet.",
    "alreadyAppliedActionLayerMsg": "Handlingen ${action} er utført på dette feltet fra Laginnstillinger.",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Denne gruppen har ingen tilknyttede felter.",
    "presetNoFieldWarningMsg": "Konfigurer minst ett felt for den forhåndsinnstilte gruppen: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Felt",
    "valueLabel": "Verdi",
    "selectValueLabel": "Velg verdi",
    "domainFieldHintLabel": "Den valgte verdien er et kodet verdiområde. Verdien: ${domainValue} blir brukt"
  },
  "presetPopup": {
    "presetValueLAbel": "Forhåndsinnstilt verdi"
  },
  "dataType": {
    "esriFieldTypeString": "Streng",
    "esriFieldTypeInteger": "Tall",
    "esriFieldTypeDate": "Dato",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Datotype",
    "valueLabel": "Verdi",
    "fixed": "Fast",
    "current": "Gjeldende",
    "past": "Tidligere",
    "future": "Fremtidig",
    "popupTitle": "Velg verdi",
    "hintForFixedDateType": "Hint: Angitt dato og klokkeslett brukes som standardverdi for forhåndsinnstilling",
    "hintForCurrentDateType": "Hint: Gjeldende dato og klokkeslett brukes som standardverdi for forhåndsinnstilling",
    "hintForPastDateType": "Hint:  Den angitte verdien trekkes fra gjeldende dato og klokkeslett for standardverdien for forhåndsinnstillingen.",
    "hintForFutureDateType": "Hint: Den angitte verdien legges til gjeldende dato og klokkeslett for standardverdien for forhåndsinnstillingen.",
    "noDateDefinedTooltip": "Ingen dato angitt",
    "relativeDateWarning": "Det må angis en verdi for dato og klokkeslett for å kunne lagre standardverdien for forhåndsinnstilling.",
    "customLabel": "Tilpasset"
  },
  "relativeDomains": {
    "fieldSetTitle": "Liste",
    "valueText": "Verdi",
    "defaultText": "Standard",
    "selectedDomainFieldsHint": "Valgt(e) domenefelt: ${domainFields}",
    "selectDefaultDomainMsg": "Velg et standardverdi-domene, eller kontroller at det er merket av for valgt standarddomene"
  }
});