define({
  "locatorUrl": "URL de Localizador",
  "set": "Definir",
  "locatorName": "Nome do Localizador",
  "locatorExample": "Exemplo",
  "countryCode": "Código(s) de País ou Região",
  "eg": "ex.: ",
  "countryCodeHint": "Ao deixar este valor em branco irá pesquisar em todos os países e regiões",
  "minCandidateScore": "Pontuação Mínima de Candidato",
  "minCandidateScoreHint": "Deixar este valor em branco irá utilizar uma classificação de candidato de 90",
  "enableSingleField": "Opções de Campo Único",
  "singleFieldHint": "Os dados de endereços encontrar-se-ão num único campo",
  "enableMultiField": "Opções de Campos Múltiplos",
  "multiFieldHint": "Os dados de endereços encontrar-se-ão em múltiplos campos",
  "enableXYField": "Opções de Campo X/Y",
  "xyFieldHint": "Os dados conterão valores de coordenadas X/Y",
  "instructionGeocode": "Adicionar e configurar serviços de localização.",
  "invalidUrlTip": "O URL ${URL} é inválido ou inacessível.",
  "geocodeTabLabel": "Definições de Localização",
  "lookupList": "Nomes de Campos a Reconhecer",
  "isRecognized": "Os nomes de campos apresentados na tabela abaixo são automaticamente reconhecidos para este campo",
  "needsEditablePointLayers": "O mapa web tem de conter, pelo menos, uma camada de pontos editável.",
  "editpageAlias": "Nome Alternativo",
  "configureFields": "Configurar Campos da Layer",
  "configureSingleFields": "Configurar um Campo de Endereço Único",
  "configureMultiFields": "Configurar um Campo de Múltiplos Endereços",
  "configureXYFields": "Configurar Campos X/Y",
  "noFields": "Utilize a ação editar para definir um ou mais campos a exibir",
  "display": "Exibir",
  "duplicate": "Encontrar Duplicado",
  "duplicateTip": "Pesquise este campo por valores idênticos entre o ficheiro de fonte dos dados e a camada alvo./n Quando for encontrado um valor idêntico, o registo do ficheiro não será localizado e será sinalizado como duplicado.",
  "noSelectField": "Seleccione primeiro a opção Feature Layer.",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Longitude)",
  "xyFieldsLabelY": "Y (Latitude)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Avanço para leste",
  "northing": "Avanço para norte",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Selecione a layer à qual se deve enviar dados.",
  "layerFieldTitle": "Layer Alvo",
  "tempSymbolHint": "Selecione o símbolo que será usado para exibir as features.",
  "tempSymbolTitle": "Símbolo de Exibição",
  "maxRecords": "Máx de registos",
  "maxRecordsHint": "Número máximo de registos a localizar",
  "searchRadius": "Raio de pesquisa",
  "searchRadiusHint": "Distância para pesquisar elementos duplicados da camada",
  "requiresInteger": "Introduza um valor numérico.",
  "requiresInteger0100": "Introduza um valor numérico entre 0 e 100",
  "requiresLocator": "Adicione pelo menos um localizador válido.",
  "layerFields": "Configurações de Camada",
  "layerFieldsHint": "Especifique os campos da Layer Alvo que serão mapeados para os campos de origem.",
  "locatorError": "O localizador é inválido ou inacessível.",
  "optionNotMatch": "As opções de campo não são consistentes em todos os localizadores. A ativação pós-falha poderá não funcionar como esperado.",
  "targetLayerTabTitle": "Layer Alvo",
  "locationSettingsTabTitle": "Definições de Localização",
  "generalSettingsTabTitle": "Configurações Gerais",
  "addTargetLayersLabel": "Adicionar Layers Alvo",
  "introductoryText": "Crie conteúdo instrucional para o widget",
  "defaultStartPageInstructions": "Este widget irá contribuir para o processamento e apresentação de dados de um ficheiro para a camada selecionada no mapa.<br/> <br/> Os valores incluídos no ficheiro devem estar delimitados por vírgulas, separadores, pontos-e-vírgulas ou barras verticais.",
  "noTargetLayerConfiguredErrorMsg": "Nenhuma layer alvo configurada",
  "noFieldsForTargetLayer": "As definições da layer não estão definidas para a layer alvo",
  "locationSettingsNotConfigured": "As definições de localização não estão corretamente configuradas",
  "questionMark": "?"
});