define({
  "serviceUrl": "Service-URL instellen:",
  "minIntSpacingLabel": "Minimum gridgrootte",
  "lineOpacityLabel": "Lijnopaciteit",
  "labelOpacityLabel": "Labelopaciteit",
  "centerLabelOpacityLabel": "Middenlabelopaciteit",
  "gridZonePlacementLabel": "Labelplaatsing Rasterzone",
  "verticalLineLabels": "Verticale lijnlabels",
  "styleHeaderLabel": "Stijl",
  "indexHeaderLabel": "Gridcomponent",
  "colorHeaderLabel": "Kleur",
  "fontSizeHeaderLabel": "Tekengrootte",
  "lineWidthHeaderLabel": "Lijnbreedte",
  "horizontalLabel": "Horizontaal",
  "verticalLabel": "Verticaal",
  "upperLeftLabel": "Linksboven",
  "upperRightLabel": "Rechtsboven",
  "lowerLeftLabel": "Linksonder",
  "lowerRightLabel": "Rechtsonder",
  "centerLabel": "Centreren",
  "errorMessage": "De configuratiepagina bevat fouten. Gelieve te repareren voordat u opslaat.",
  "checkBoxLabel": "Toon raster als de widget is gesloten",
  "checkBoxLabelDashboard": "Grid weergeven",
  "gzd": "Gridzone-designator (Grid Zone Designator (GZD))",
  "gsid": "${number}-meter Grid Square Identification (GSID)",
  "grid10k": "${number}-meter Grid Lines",
  "grid1k": "${number}-meter Grid Lines",
  "grid100m": "100-meter gridlijnen",
  "grid10m": "10-meter gridlijnen",
  "switchBasemap": "Basiskaart wijzigen"
});