define({
  "layerSelect": "Избор на слой на изображение",
  "displayMeasureResultInPopup": "Показване на резултатите от измерването в изскачащ прозорец",
  "angularUnitSelect": "Стандартна ъглова мерна единица",
  "linearUnitSelect": "Стандартна линейна единица",
  "areaUnitSelect": "Стандартна единица за област",
  "displayOperationSelect": "Избор на операции за измерване",
  "errorSectionMessage": "Нито един от слоевете не поддържа възможности за измерване.",
  "unitLabel": {
    "esriInches": "Инч",
    "esriFeet": "Фута",
    "esriYards": "Ярда",
    "esriMiles": "Мили",
    "esriNauticalMiles": "Морски мили",
    "esriMillimeters": "Милиметри",
    "esriCentimeters": "Сантиметри",
    "esriDecimeters": "Дециметри",
    "esriMeters": "Метри",
    "esriKilometers": "Километри",
    "esriDURadians": "Радиани",
    "esriDUDecimalDegrees": "Градуси",
    "esriSquareInches": "Кв. инч",
    "esriSquareFeet": "Кв. фут",
    "esriSquareYards": "Кв. ярд",
    "esriAcres": "Акри",
    "esriSquareMiles": "Кв. мили",
    "esriSquareMillimeters": "Кв. милиметри",
    "esriSquareCentimeters": "Кв. сантиметри",
    "esriSquareDecimeters": "Кв. дециметри",
    "esriSquareMeters": "Кв. метри",
    "esriAres": "Ара",
    "esriHectares": "Хектари",
    "esriSquareKilometers": "Кв. километри"
  },
  "operationLabel": {
    "esriMensurationPoint": "Местоположение",
    "esriMensurationDistanceAndAngle": "Разстояние и ъгъл",
    "esriMensurationAreaAndPerimeter": "Площ и периметър",
    "esriMensurationHeightFromBaseAndTop": "Височина: от основата до върха",
    "esriMensurationHeightFromBaseAndTopShadow": "Височина: от основата до най-висока сянка",
    "esriMensurationHeightFromTopAndTopShadow": "Височина: от върха до най-висока сянка",
    "esriMensurationCentroid": "Центроид",
    "esriMensurationPoint3D": "Местоположение (3D)",
    "esriMensurationDistanceAndAngle3D": "Разстояние и ъгъл (3D)",
    "esriMensurationAreaAndPerimeter3D": "Площ и периметър (3D)",
    "esriMensurationCentroid3D": "Центроид (3D)"
  }
});