define({
  "taskUrl": "URL da Tarefa",
  "setTask": "Configurar",
  "setTaskPopupTitle": "Definir Tarefa",
  "validate": "Configurar",
  "inValidGPService": "Insira serviço de geoprocessamento válido.",
  "noOutputParameterWithGeometryType": "O serviço de geoprocessamento selecionado deve ter pelo menos um parâmetro de saída com um tipo de geometria especificado. Selecione um serviço de geoprocessamento diferente.",
  "invalidOutputGeometry": "O tipo de geometria de saída do serviço de geoprocessamento selecionado não é compatível com as configurações do projeto. Os resultados do serviço de geoprocessamento não podem ser armazenados.",
  "GPFeatureRecordSetLayerERR": "Insira um serviço de geoprocessamento com entradas do tipo 'GPFeatureRecordSetLayer’ somente.",
  "invalidInputParameters": "O número de parâmetros de entrada é menor que 1 ou maior que 3. Insira um serviço de geoprocessamento válido.",
  "projectSetting": {
    "title": "Configurações do projeto",
    "note": "Nota: As Configurações do Projeto são opcionais, após configurado, o usuário pode armazenar o projeto nas camadas do mapa da web desejadas com área de interrupção de rede e parâmetros de entrada. O usuário pode armazenar outros parâmetros de saída da guia 'Saída'.",
    "projectPolygonLayer": "Camada de polígono do projeto",
    "outputParameterName": "Nome do parâmetro de saída",
    "projectPointLayer": "Camada de ponto do projeto",
    "selectLabel": "Selecionar",
    "polygonLayerHelp": "<p>Camada(s) de polígono com as seguintes condições serão mostradas:<br/><ul><li>A camada deve ter recursos de edição, isto é 'Criar', 'Excluir' e 'Atualizar'</li><li>A camada deve ter 2 campos com o nome exato e os tipos de dados:</li><ul><li>nome (campo do tipo String)</li><li> globalid (Campo de tipo GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>As camadas de polígono de saída da URL da tarefa serão mostradas<p/>",
    "pointLayerHelp": "<p>As camadas de pontos com as seguintes condições serão mostradas:<br/><ul><li>A camada deve ter recursos de edição, isto é 'Criar', 'Excluir' e 'Atualizar'</li><li>A camada deve ter 2 campos com o nome exato e os tipos de dados:</li><ul><li>inputtype (campo do tipo String)</li><li>projectid (Campo tipo GUID)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Bandeira",
    "barrier": "Barreira",
    "skip": "Pular",
    "title": "Entrada",
    "inputTooltip": "Dica da Ferramenta",
    "typeText": "Tipo",
    "symbol": "Símbolo",
    "summaryEditorText": "Texto de Resumo",
    "summaryTextTitle": "Forneça o texto a ser exibido para guia de entrada"
  },
  "summaryTab": {
    "title": "Saída",
    "summaryFieldsetText": "Configurações sumárias",
    "inputOutput": "Entrada/Saída",
    "field": "Campo",
    "operator": "Operador",
    "inputOperatorCountOption": "Contagem",
    "outputOperatorCountOption": "Contagem",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Soma",
    "fieldOperatorMinOption": "Mín",
    "fieldOperatorMaxOption": "Máx",
    "fieldOperatorMeanOption": "Média",
    "expressionAddButtonText": "Adicionar",
    "expressionVerifyButtonText": "Verificar",
    "summaryEditorText": "Texto de Resumo",
    "zoomText": "Zoom automático após traçado",
    "summarSettingTooltipText": "Adicionar contagem de entrada/saída",
    "symbol": "Símbolo",
    "outputParametersText": "Parâmetros de Saída",
    "skipText": "Ignorável",
    "visibilityText": "Visível",
    "exportToCsvText": "Exportar para CSV",
    "settitngstext": "Configurações",
    "saveToLayerText": "Salvar na Camada (Opcional)",
    "inputLabel": "Rótulo",
    "inputTooltip": "Dica da Ferramenta",
    "outputDisplay": "Exibir texto",
    "addFieldTitle": "Adicionar Campo",
    "setScale": "Configurar Escala",
    "enterDisplayText": "Inserir texto de visualização",
    "saveToLayerHelp": "<p>A camada com as seguintes condições será exibida:<br/><ul><li>A camada deve ter recursos de edição, isto é, Criar, Excluir e Atualizar</li><li>A camada deve ter dois campos com os tipos de nome e dados:</li><ul><li>parametername (campo de tipo String)</li><li>projectid (campo de tipo Guid)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Forneça o texto sumário a ser exibido na guia de saída",
    "addSummaryItemsTitle": "Adicionar Itens Sumários"
  },
  "validationErrorMessage": {
    "webMapError": "Nenhuma camada disponível no mapa da web. Selecione um mapa da web válido.",
    "inputTypeFlagGreaterThanError": "Entrada de tipo de bandeira não pode ser mais de uma.",
    "inputTypeFlagLessThanError": "Pelo menos uma entrada de tipo de bandeira é exigida.",
    "inputTypeBarrierErr": "Entrada de tipo de barreira não pode ser mais de uma.",
    "inputTypeSkipErr": "Entrada de tipo de pulo não pode ser mais de uma.",
    "displayTextForButtonError": "Texto de exibição do botão 'Executar’ não pode estar em branco.",
    "UnableToLoadGeoprocessError": "Não é possível carregar serviço de geoprocessamento.",
    "invalidSummaryExpression": "Expressão inválida.",
    "validSummaryExpression": "Bem Sucedido !",
    "invalidProjectSettings": "Configurações do Projeto Inválidas.<br/>Selecione o valor válido em '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Sugestão: Forneça rótulo de exibição para painel do resultado do parâmetro de saída.",
    "displayTextHint": "Sugestão: Isto será exibido no painel de detalhes deste parâmetro de saída.",
    "inputTextHint": "Sugestão: Construa sua expressão abaixo utilizando o botão adicionar itens sumários.",
    "expressionHint": "Sugestão: Selecione itens e clique em adicionar para construir expressão."
  }
});