define({
  "_widgetLabel": "Analýza incidentov",
  "_featureAction_SetAsIncident": "Nastaviť ako incident",
  "incident": "Incident",
  "weather": "Počasie",
  "locate_incident": "Zamerať incident",
  "clear_incidents": "Vymazať incidenty",
  "reverse_geocoded_address": "Najbližšia adresa",
  "reverse_geocoded_error": "Nie je k dispozícii",
  "miles": "Míle",
  "kilometers": "Kilometre",
  "feet": "Stopy",
  "meters": "Metre",
  "yards": "Yardy",
  "nauticalMiles": "Námorné míle",
  "now": "TERAZ",
  "wind": "VIETOR",
  "SUN": "NEDEĽA",
  "MON": "PONDELOK",
  "TUE": "UTOROK",
  "WED": "STREDA",
  "THU": "ŠTVRTOK",
  "FRI": "PIATOK",
  "SAT": "SOBOTA",
  "defaultTabMsg": "Nezistili sa žiadne incidenty.",
  "useMapExtent": "Použiť aktuálny rozsah mapy",
  "noFeaturesFound": "Neboli nájdené žiadne prvky.",
  "downloadCSV": "STIAHNUŤ CSV",
  "sum": "SUM",
  "min": "MIN",
  "max": "MAX",
  "avg": "AVG",
  "count": "COUNT",
  "area": "PLOCHA",
  "length": "DĹŽKA"
});