define({
  "_widgetLabel": "Trusselsanalyse",
  "threatAnalysisMainPageTitle": "Baseret på JCAT Counterterrorism Guide",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Input-placering",
  "interactive": "Interaktiv",
  "fromCoord": "Fast koordinat",
  "existingFeature": "Fra eksisterende objekter",
  "threatAnalysisCoordInputLabel": "Trusselsplacering",
  "enterCoords": "Angiv koordinater",
  "threatAddPointToolTip": "Tilføj trusselsplacering",
  "threatDrawPointToolTip": "Klik for at tilføje trusselsplacering",
  "threatType": "Trusselstype",
  "threatPlaceholder": "Begynd at skrive for at søge efter en trussel",
  "mandatoryLabel": "Obligatorisk evakueringsafstand",
  "safeLabel": "Sikker evakueringsafstand",
  "zoneTypeLabel": "Zonetype",
  "feetLabel": "Fod",
  "metersLabel": "Meter",
  "unitsLabel": "Enheder",
  "threatGraphicLayer": "Trusselsbillede",
  "settingsTitle": "Indstillinger",
  "mandatoryButtonLabel": "Konfigurér indstillinger for Obligatorisk evakueringsafstand",
  "safeButtonLabel": "Konfigurer indstillinger for Beskyttelsesrum i stedzone",
  "style": "Type",
  "colorPicker": "Farvevælger",
  "lineStyles": {
    "esriSLSDash": "Streg",
    "esriSLSDashDot": "Streg-prik",
    "esriSLSDashDotDot": "Streg-prik-prik",
    "esriSLSDot": "Prik",
    "esriSLSLongDash": "Lang streg",
    "esriSLSLongDashDot": "Lang streg-prik",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Kort streg",
    "esriSLSShortDashDot": "Kort streg-prik",
    "esriSLSShortDashDotDot": "Kort streg-prik-prik",
    "esriSLSShortDot": "Kort prik",
    "esriSLSSolid": "Udfyldt"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Baglæns",
    "esriSFSCross": "Kryds",
    "esriSFSDiagonalCross": "Diagonalt",
    "esriSFSForwardDiagonal": "Frem",
    "esriSFSHorizontal": "Vandret",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Udfyldt",
    "esriSFSVertical": "Lodret"
  },
  "resultsTitle": "Resultater",
  "publishTABtn": "Publicér",
  "layerName": "Navn på publiceret lag",
  "invalidLayerName": "Lagnavnet må kun indeholde alfanumeriske tegn og understregninger",
  "missingLayerNameMessage": "Du skal indtaste et gyldigt lag-navn, før du kan publicere.",
  "publishingFailedLayerExists": "Publicering mislykkedes: Du har allerede en featuretjeneste med navnet {0}. Vælg et andet lagnavn.",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opret tjeneste: {0}",
  "unableToCreate": "Kan ikke oprette: {0}",
  "addToDefinition": "Tilføj til definition: {0}",
  "successfullyPublished": "Weblag er publiceret",
  "successfullyAppended": "Nye objekter er blevet knyttet til weblaget",
  "manageWebLayerText": "Adminidtrer weblag",
  "userRole": "Kan ikke oprette tjenesten, fordi brugeren ikke har tilladelser",
  "retrieveExistingLayerError": "Kan ikke hente {0}. Publicér ved at benytte et andet lagnavn.",
  "publishToNewLayer": "Publicér resultater til et nyt vektorlag",
  "layerNameExists": "Lagets navn findes allerede. Brug et andet navn til laget.",
  "pipeBombLabel": "Rørbombe",
  "suicideBombLabel": "Selvmordsbombe",
  "briefcaseLabel": "Dokumentmappe",
  "carLabel": "Bil",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Lille varevogn",
  "containerWaterTruckLabel": "Container-/vandlastbil",
  "semiTrailerLabel": "Sættevogn",
  "transparencyLabel": "Gennemsigtighed",
  "outline": "Kontur",
  "fill": "Fyld (farve anvendes kun, når typografien er indstillet til massiv)",
  "createBtn": "Opret zoner",
  "clearBtn": "Ryd",
  "invalidNumberMessage": "Den indtastede værdi er ikke gyldig",
  "invalidRangeMessage": "Værdien skal være større end 0",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Kontrollér dit input.",
  "selectDrawModeLabel": "Vælg tegnetilstand",
  "selectFeatureLabel": "Vælg objekt fra dette lag",
  "fireBallDiameterLable": "Fireball-diameter",
  "lpgSafeDistanceLable": "Sikker afstand",
  "threatTypeCatagoryLabel": "Trusselstypekategori",
  "fireballButtonLabel": "Konfigurér Fireball-diameterindstillinger",
  "safeDistanceButtonLabel": "Konfigurér indstillinger for Sikker afstand",
  "chemicalThreatCatagoryLabel": "Kemisk",
  "lpgThreatCatagoryLabel": "Flaskegas",
  "chemicalThreatLabel": "Kemisk trussel",
  "lpgThreatLabel": "LPG-trussel",
  "fireBallDiameterFieldAlias": "LPG Fireball-diameter",
  "lpgSafeDistanceFieldAlias": "LPG Sikker afstand",
  "smallLPGTank": "Lille LPG-tank",
  "largeLPGTank": "Stor LPG-tank",
  "commercialResidentialLPGTank": "LPG-tank til handels-/boligområde",
  "smallLPGTruck": "Lille LPG-lastvogn",
  "semiTankerLPG": "Semi-tanker LPG"
});