define({
  "locatorUrl": "Locator-URL",
  "set": "Festlegen",
  "locatorName": "Locator-Name",
  "locatorExample": "Beispiel",
  "countryCode": "Länder- oder Regionscode(s)",
  "eg": "z. B. ",
  "countryCodeHint": "Wenn dieser Wert leer gelassen wird, werden alle Länder und Regionen durchsucht",
  "minCandidateScore": "Minimale Kandidatenpunktzahl",
  "minCandidateScoreHint": "Wenn dieser Wert leer gelassen wird, wird die minimale Kandidatenpunktzahl 90 verwendet.",
  "enableSingleField": "Einzelfeldoptionen",
  "singleFieldHint": "Adressendaten befinden sich in einem einzelnen Feld",
  "enableMultiField": "Mehrfeldoptionen",
  "multiFieldHint": "Adressendaten befinden sich in mehreren Feldern",
  "enableXYField": "X-/Y-Feldoptionen",
  "xyFieldHint": "Daten enthalten X-/Y-Koordinatenwerte",
  "instructionGeocode": "Fügen Sie Locator-Services hinzu, und konfigurieren Sie sie.",
  "invalidUrlTip": "Die URL ${URL} ist ungültig oder es kann nicht darauf zugegriffen werden.",
  "geocodeTabLabel": "Positionseinstellungen",
  "lookupList": "Feldnamen für Wiedererkennung",
  "isRecognized": "Feldnamen in der nachfolgenden Tabelle werden automatisch für dieses Feld erkannt",
  "needsEditablePointLayers": "Die Webkarte muss mindestens einen editierbaren Punkt-Layer enthalten.",
  "editpageAlias": "Alias",
  "configureFields": "Layer-Felder konfigurieren",
  "configureSingleFields": "Einzelnes Adressenfeld konfigurieren",
  "configureMultiFields": "Mehrere Adressenfelder konfigurieren",
  "configureXYFields": "X-/Y-Felder konfigurieren",
  "noFields": "Verwenden Sie die Bearbeitungsaktion, um ein oder mehrere anzuzeigende Felder zu definieren.",
  "display": "Anzeige",
  "duplicate": "Duplikat suchen",
  "duplicateTip": "Dieses Feld nach identischen Werten in Quelldatei und Ziel-Layer durchsuchen./n Wenn ein identischer Wert gefunden wird, wird der Datensatz aus der Datei nicht verortet und als Duplikat gekennzeichnet.",
  "noSelectField": "Wählen Sie zuerst die Option \"Feature-Layer\" aus.",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Längengrad)",
  "xyFieldsLabelY": "Y (Breitengrad)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Rechtswert",
  "northing": "Hochwert",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Wählen Sie den Layer aus, an den Sie Daten senden möchten.",
  "layerFieldTitle": "Ziel-Layer",
  "tempSymbolHint": "Wählen Sie das Symbol aus, mit dem die Features angezeigt werden.",
  "tempSymbolTitle": "Symbol anzeigen",
  "maxRecords": "Maximale Anzahl der Datensätze",
  "maxRecordsHint": "Maximale Anzahl der zu verortenden Datensätze",
  "searchRadius": "Suchradius",
  "searchRadiusHint": "Entfernung für die Suche nach doppelten Features vom Layer",
  "requiresInteger": "Geben Sie einen numerischen Wert ein.",
  "requiresInteger0100": "Geben Sie einen numerischen Wert zwischen 0 und 100 ein.",
  "requiresLocator": "Fügen Sie mindestens einen gültigen Locator hinzu.",
  "layerFields": "Layer-Einstellungen",
  "layerFieldsHint": "Geben Sie Felder aus dem Ziel-Layer an, die den Quellfeldern zugeordnet werden.",
  "locatorError": "Der Locator ist ungültig, oder es kann nicht darauf zugegriffen werden.",
  "optionNotMatch": "Die Feldoptionen sind in den Locators nicht konsistent. Das Failover funktioniert möglicherweise nicht erwartungsgemäß.",
  "targetLayerTabTitle": "Ziel-Layer",
  "locationSettingsTabTitle": "Positionseinstellungen",
  "generalSettingsTabTitle": "Allgemeine Einstellungen",
  "addTargetLayersLabel": "Ziel-Layer hinzufügen",
  "introductoryText": "Lehrinhalte für das Widget hinzufügen",
  "defaultStartPageInstructions": "Dieses Widget unterstützt die Verarbeitung von Daten und deren Übermittlung von einer Datei an den ausgewählten Layer in der Karte.<br/> <br/> Werte innerhalb der Datei müssen durch ein Komma, einen Tabulator, ein Semikolon oder einen vertikalen Balken getrennt sein.",
  "noTargetLayerConfiguredErrorMsg": "Kein Ziel-Layer konfiguriert.",
  "noFieldsForTargetLayer": "Layer-Einstellungen sind für den Ziel-Layer nicht konfiguriert.",
  "locationSettingsNotConfigured": "Positionseinstellungen sind nicht ordnungsgemäß konfiguriert."
});