define({
  "_widgetLabel": "Hromadné editovanie atribútov",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Názov vrstvy",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Žiadne konfigurované editovateľné vrstvy",
  "editorPopupTitle": "Hromadné editovanie atribútov",
  "editorPopupSaveBtn": "Uložiť",
  "editorPopupMultipleValues": "",
  "clear": "Vyčistiť",
  "featuresUpdated": "${0} / ${1} prvkov aktualizovaných",
  "featuresSelected": "${0} prvkov vybraných",
  "featuresSkipped": "Vynechaný",
  "featuresNoPermision": "${0} prvok(ov) vybraných, ale bez povolenia editácie.",
  "search": "Vyhľadávanie",
  "queryInput": "Zadať hodnotu pre dopyt",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Nastavte filter správne.",
  "filterPopup": "Vrstva filtra",
  "filterAppend": "Ak filter už existuje v tejto webovej mape pre túto vrstvu",
  "filterAppendOR": "Pripojiť akýkoľvek výraz k existujúcemu mapovému filtru",
  "filterAppendAND": "Pripojiť všetky výrazy k existujúcemu mapovému filtru",
  "cancel": "Zrušiť",
  "noValue": "Žiadna hodnota",
  "emptyString": "Prázdny reťazec",
  "existingValue": "Ponechať existujúcu hodnotu",
  "newDate": "Nový dátum",
  "valueChooser": "Vybrať/Napísať hodnotu",
  "ok": "OK",
  "drawBox": {
    "point": "Bod",
    "line": "Línia",
    "polyline": "Lomená čiara",
    "freehandPolyline": "Čiara voľnou rukou",
    "extent": "Rozsah",
    "polygon": "Polygón",
    "freehandPolygon": "Polygón voľnou rukou",
    "clear": "Vyčistiť",
    "addPointToolTip": "Kliknite pre výber v tejto oblasti",
    "addShapeToolTip": "Nakreslite útvar na výber prvkov",
    "freehandToolTip": "Stlačením a podržaním nakreslite tvar na výber prvkov",
    "startToolTip": "Nakreslite útvar na výber prvkov"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Prvok z ${0} vrátil neplatné ID",
    "noSelectedLayers": "Žiadne vybrané vrstvy so záznamami na aktualizáciu",
    "inputValueError": "Neplatná hodnota vo formulári",
    "saveError": "Nie je možné uložiť ${0} prvky",
    "requiredValue": "Vyžadovaná hodnota"
  }
});