define({
  "transparencyLabel": "Transparantie",
  "outline": "Omtreklijn",
  "fill": "Vullen (kleur wordt alleen toegepast als stijl ingesteld is al solid)",
  "style": "Stijl",
  "selectOpLayerLabel": "Selecteer een operationele laag voor resultaten",
  "selectDefaultMeasurementLabel": "Selecteer een standaard meeteenheid",
  "helpIconTooltip": "De lijst met operationele lagen is bevolkt met lagen van de huidige web map van het type polygoongeometrie.",
  "lineStyles": {
    "esriSLSDash": "Streep",
    "esriSLSDashDot": "Streep punt",
    "esriSLSDashDotDot": "Streep punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Lange streep",
    "esriSLSLongDashDot": "Lange streep punt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Korte streep",
    "esriSLSShortDashDot": "Korte streep punt",
    "esriSLSShortDashDotDot": "Korte streep punt punt",
    "esriSLSShortDot": "Korte punt",
    "esriSLSSolid": "Ononderbroken"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Achterwaarts",
    "esriSFSCross": "Kruis",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Voorwaarts",
    "esriSFSHorizontal": "Horizontaal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Ononderbroken",
    "esriSFSVertical": "Verticaal"
  },
  "threatTypeLabel": "Dreigingstype",
  "generalLabel": "Algemeen",
  "addThreatTypesLabel": "Dreigingstype toevoegen",
  "actions": "Acties",
  "newThreatTypePopupLabel": "Nieuw dreigingstype",
  "units": "Eenheden",
  "chooseDefaultThreatLabel": "Selecteer standaard dreigingstype",
  "defaultThreatTypePopUpLabel": "Standaarddreigingstypes",
  "editThreatLabel": "Dreiging bewerken",
  "defaultThreatTypeIconTooltip": "Lijst standaarddreigingstype",
  "uniqueThreatTypeMsg": "Voer een uniek dreigingstype in, dreigingstype met deze naam bestaat al.",
  "requiredMsg": "Dit veld is verplicht.",
  "unitMeasureLabel": "Afstanden zijn in {0}",
  "chooseDefaultThreatTypeIconLabel": "Kies uit standaard opties",
  "pipeBombLabel": "Pijpbom",
  "suicideBombLabel": "Zelfmoordaanslag",
  "briefcaseLabel": "Aktetas",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/busje",
  "smallDeliveryTruckLabel": "Klein bestelbusje",
  "containerWaterTruckLabel": "Container/vrachtwagen voor vervoer van water",
  "semiTrailerLabel": "Oplegger",
  "chemicalThreatLegendLabel": "Chemische dreiging",
  "lpgThreatLegendLabel": "LPG-dreiging",
  "smallLPGTank": "Kleine LPG-tank",
  "largeLPGTank": "Grote LPG-tank",
  "commercialResidentialLPGTank": "Commerciële/Huishoudelijke LPG-tank",
  "smallLPGTruck": "Kleine LPG-truck",
  "semiTankerLPG": "Semi-tanker LPG",
  "threatDescriptionColLabel": "Dreigingsbeschrijving",
  "addThreatZoneButtonLabel": "Dreigingszone toevoegen",
  "zoneDescColLabel": "Zonebeschrijving",
  "distanceLabel": "Afstand (${unitAbbr})",
  "threatTypeHelp": "<p>Zorg ervoor dat aan de volgende voorwaarden wordt voldaan voor een bedreigingstype:<br/><ul><li>Bedreigingstype mag niet leeg zijn en moet uniek zijn</li><li>Bedreiging moet ten minste één geldige zone hebben</li><li>Zonebeschrijving moet uniek zijn voor een bedreiging</li></ul><p/>",
  "descriptionLabel": "Beschrijving",
  "newThreatZonePopupLabel": "Nieuwe dreigingszone",
  "editThreatZonePopupLabel": "Dreigingszone bewerken",
  "uniqueZoneDescriptionMsg": "Voer een uniek dreigingstype in, zonebeschrijving met deze naam bestaat al.",
  "symbologyColLabel": "Symbologie",
  "zoneDescriptionColLabel": "Zonebeschrijving",
  "uniqueZoneRequiredMsg": "Zonenaam moet uniek zijn voor de",
  "interactive": "Interactief",
  "fromCoord": "Vast coördinaat",
  "existingFeature": "Van bestaande objecten",
  "defaultInputLocationLabel": "Standaard invoerlocatie",
  "defaultInputLayer": "Standaard invoerlaag",
  "defaultThreatType": "Standaard dreigingstype",
  "selectLabel": "Selecteren",
  "mandatoryLabel": "Verplichte evacuatie-afstand",
  "safeLabel": "Veilige evacuatie-afstand",
  "lpgSafeDistanceLable": "Veilige afstand",
  "fireBallDiameterLable": "Diameter vuurbal"
});