define({
  "taskUrl": "URL Dịch vụ Tầm nhìn",
  "portalURL": "Chỉ định URL đến tổ chức ArcGIS Online hoặc Portal for ArcGIS của bạn",
  "portalURLError": "URL được cấu hình đến tổ chức ArcGIS Online hoặc Portal for ArcGIS của bạn không hợp lệ.",
  "privilegeError": "Vai trò người dùng của bạn không cho phép thực hiện phân tích. Để thực hiện phân tích, quản trị viên của tổ chức của bạn cần cấp cho bạn một số <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">quyền</a>.",
  "noServiceError": "Dịch vụ phân tích độ cao không khả dụng. Vui lòng kiểm tra cấu hình của tổ chức ArcGIS Online hoặc Portal for ArcGIS của bạn.",
  "maximumRangeMessage": "Phạm vi Có thể Quan sát Tối đa phải lớn hơn Phạm vi Có thể Quan sát Tối thiểu và không được vượt quá ${limit}${units}.",
  "serviceURLPlaceholder": "Vui lòng nhập URL tác vụ Địa xử lý Tầm nhìn",
  "setTask": "Thiết lập",
  "setTaskTitle": "Thiết lập tác vụ Địa xử lý Tầm nhìn",
  "serviceURLError": "Tác vụ Địa xử lý bạn đang cố gắng cấu hình bằng tiện ích này không hợp lệ. Vui lòng chọn URL tác vụ Địa xử lý Tầm nhìn hợp lệ.",
  "defaultMilsForAnglesLabel": "Đặt mil cho góc làm mặc định",
  "defaultObserverHeightLabel": "Đơn vị Chiều cao quan sát mặc định",
  "defaultObservableDistanceLabel": "Đơn vị Khoảng cách có thể quan sát được mặc định",
  "defaultObserveHeightLabel": "Chiều cao Quan sát Mặc định",
  "defaultMinimumObservableDistanceLabel": "Khoảng cách Quan sát Mặc định Tối thiểu",
  "defaultMaximumObservableDistanceLabel": "Khoảng cách Quan sát Mặc định Tối đa",
  "units": {
    "miles": "Dặm",
    "kilometers": "Kilômét",
    "feet": "Bộ",
    "meters": "Mét",
    "yards": "Yards",
    "nauticalMiles": "Hải lý"
  },
  "helpIconTooltip": "Danh sách lớp chuyên đề được quản lý các lớp từ bản đồ web hiện tại là loại hình học dạng vùng.",
  "selectOperationalLayerLabel": "Chọn một lớp chuyên đề cho kết quả",
  "lineOfSightTabTitle": "Đường ảnh Cơ sở",
  "symbologyTabTitle": "Biểu tượng",
  "transparency": "Độ trong suốt",
  "outline": "Đường viền",
  "fill": "Tô đầy (Màu chỉ áp dụng khi kiểu được thiết lập thành dạng khối)",
  "style": "Kiểu giao diện",
  "selectOpLayerLabel": "Chọn một lớp chuyên đề cho kết quả",
  "selectDefaultMeasurementLabel": "Chọn đơn vị mặc định của kết quả đo",
  "visibleSectionLabel": "Phần Hiển thị",
  "nonVisibleSectionLabel": "Phần Không hiển thị",
  "visibleSectionButtonLabel": "Cấu hình Thiết lập phần hiển thị",
  "nonVisibleSectionButtonLabel": "Cấu hình Thiết lập phần không hiển thị",
  "colorPicker": "Trình chọn màu",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  }
});