define({
  "_widgetLabel": "تجميع البيانات",
  "startPage": {
    "defaultStartPageInstructions": "سيساعدك عنصر واجهة المستخدم هذا في معالجة البيانات وإرسالها من ملف إلى طبقة محددة في الخريطة.<br/> <br/> يجب أن تكون القيم داخل الملف محددة بفاصلة أو علامة جدولة أو فاصلة منقوطة أو شريط عمودي.",
    "dragDrop": "سحب وإفلات",
    "browse": "استعراض الملف",
    "or": "'أو'",
    "userPrivilege": "لا يحتوي حسابك على أذونات لإنشاء أو تعديل البيانات.",
    "userCredits": "يتطلب ${widgetName} اعتمادات لاستخدام محدد المواقع ${locator}.",
    "contactAdmin": "اتصل بمسؤول المؤسسة لطلب اعتمادات إضافية.",
    "contactAdminEdit": "اتصل بمسؤول المؤسسة لطلب امتيازات تحرير.",
    "canUseLocator": "سيُستخدم محدد المواقع ${locator} لتحديد مكان المعالم.",
    "notEnoughCredits": "لا توجد اعتمادات كافية.",
    "locationAndField": "معلومات الحقل والموقع",
    "locationAndFieldHint": "اختر القيم من الحقل الذي يجب استخدامه لتحديث الطبقة الهدف.",
    "cannotUseLocator": "يتعذر استخدام ${widgetName}",
    "noAnonymousEdit": "لا تدعم طبقة ${layerName} التحرير المجهول.",
    "pleaseLogin": "سجّل الدخول إلى مؤسسة ${org} أو اتصل بمسؤول المؤسسة لطلب تمكين التحرير المجهول.",
    "invalidEdit": "امتيازات غير صالحة",
    "unableToAccess": "يتعذر الوصول إلى ${layerName}",
    "appropriateCredentials": "تحقق من تسجيل الدخول باستخدام بيانات الاعتماد الملائمة.",
    "shared": "اتصل بمسؤول My Esri لطلب الوصول إلى طبقة ${layerName}.",
    "targetLayerLabel": "طبقة الهدف",
    "homeButtonLabel": "الصفحة الرئيسية",
    "mappingErrorMsg": "انقر فوق السهم بجانب تحديد الحقول"
  },
  "mapping": {
    "schemaMapping": "معلومات الحقل",
    "schemaMappingHint": "اختر الحقل من الملف الذي يرتبط بالحقول في الطبقة.",
    "locationMapping": "معلومات الموقع",
    "locationMappingHint": "اختر نوع العنوان أو معلومات الإحداثيات المتوقع من الملف."
  },
  "locationMapping": {
    "locationMappingPageHint": "اختر نوع الموقع",
    "useAddress": "تحديد الموقع باستخدام عنوان",
    "useAddressHint": "البيانات تحتوي على معلومات العنوان",
    "useCoordinates": "تحديد الموقع باستخدام الإحداثيات",
    "useCoordinatesHint": "تحتوي البيانات على قيم إحداثيات X/Y"
  },
  "address": {
    "addressPageHint": "اختر نوع الحساب",
    "singleField": "حقل فردي",
    "singleFieldHint": "اختر الحقل الذي يحتوي على معلومات العنوان",
    "multiField": "حقول متعددة",
    "multiFieldHint": "اختر الحقول التي تحتوي على معلومات العنوان"
  },
  "coordinates": {
    "coordinatesPageHint": "اختر الحقول التي تحتوي على البيانات الإحداثية"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "اختر حقل المصدر الذي يخطط الحقل الهدف",
    "sourceField": "مطابقة الحقل المصدري",
    "targetField": "حقل الهدف"
  },
  "buttons": {
    "addToMap": "إضافة إلى الخريطة",
    "submit": "إرسال",
    "download": "تنزيل"
  },
  "review": {
    "matched": "تم العثور عليها",
    "reviewMatched": "المواقع التي تم العثور عليها",
    "reviewMatchedHint": "راجع المواقع التي تم العثور عليها.",
    "unMatched": "لم يُعثر عليها",
    "reviewUnMatched": "المواقع التي لم يُعثر عليها",
    "reviewUnMatchedHint": "راجع المواقع التي لم يُعثر عليها. لن تُقدم العناصر التي لم تُصحح.",
    "duplicate": "تكرار",
    "reviewDuplicate": "تكرار المواقع",
    "reviewDuplicateHint": "راجع المواقع التي عُثر عليها بالفعل في الطبقة. لن تُقدم العناصر التي لم تُعالج.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "استخدام:",
    "fromLayer": "معلومات الهدف",
    "target": "الهدف",
    "source": "مصدر",
    "fromFile": "معلومات المصدر",
    "locationControlHint": "مراجعة معلومات العنوان",
    "duplicateAction": "اختيار إجراء",
    "item": "سجل:",
    "locateFeature": "تحديد موقع معلم",
    "removeFeature": "إزالة معلم",
    "featureLocated": "تم العثور على الموقع",
    "valuesDoNotMatch": "لا تتطابق مع القيمة الموجودة",
    "sync": "مزامنة معلومات العنوان مع معلومات الحقل",
    "noFeaturesSaved": "لم تُحفظ المعالم بنجاح",
    "someFeaturesSaved": "تم حفظ ${num} من المعالم بنجاح.",
    "someFeaturesNotSaved": "لم يُحفظ ${num} من المعالم بنجاح.",
    "feature": "مراجعة معلومات المعلم",
    "locationInfo": "مراجعة معلومات الموقع",
    "selectValue": "حدد قيمة",
    "reviewData": "مراجعة البيانات",
    "reviewDataHint": "راجع البيانات قبل تقديمها إلى الطبقة.",
    "reviewFeatureHint": "راجع معلومات المعلم والموقع وحررها.",
    "duplicateModify": "يحتاج \"التكرار\" إلى تغيير",
    "duplicateSave": "حفظ كمعلم جديد"
  },
  "warningsAndErrors": {
    "invalidCSV": "حدث خطأ أثناء جلب العناصر من CSV، تحقق من تحديد ملف CSV صالح.",
    "noLayersWarning": "لم يتم تكوين طبقة هدف صالحة، تحقق من التكوين.",
    "loadWarning": "يتطلب عنصر واجهة المستخدم هذا مصدر بيانات خدمة معلم. كوّن عنصر واجهة المستخدم لتحديد مصدر بيانات.",
    "saveError": "حدث خطأ في حفظ المعالم.",
    "consumesCredits": "تستهلك هذه الأداة بيانات الاعتماد عند استخدام خدمة التكويد الجغرافي ArcGIS Online World.",
    "noValue": "تحديد حقل",
    "mappingTitle": "",
    "locationMappingComplete": "اكتمل تخطيط الموقع",
    "fieldMappingComplete": "اكتمل تخطيط الحقل",
    "settingsCleared": "سيتم مسح الإعدادات.",
    "proceed": "هل تود المتابعة؟",
    "itemMoveMatch": "تم تحديد موقع العنصر ونقله إلى قائمة المواقع التي عُثر عليها",
    "itemMoveUnMatched": "يتعذر تحديد موقع العنصر. نُقل إلى قائمة المواقع التي لم يُعثر عليها.",
    "itemWillBeLocated": "ستتم إزالة العنصر من قائمة المواقع المتكررة.",
    "cannotLocate": "يتعذر تحديد موقع العنصر. تحقق من صحة معلومات الموقع.",
    "invalidMessage": "قيمة غير صالحة.",
    "rangeMessage": "يجب أن تكون القيمة أقل من ${num} من الحروف.",
    "locatorError": "محدد المواقع غير صالح أو لا يمكن الوصول إليه.",
    "notConfigured": "لم يُجرى تكوين محدد المواقع لخيارات تحديد المواقع الحالية",
    "noMoreLocators": "لم يتم تكوين أي محددات مواقع إضافية"
  },
  "featureToolbar": {
    "locate": "تحديد موقع",
    "save": "حفظ السجل",
    "cancel": "إلغاء التحريرات",
    "cancelTitle": "إلغاء التحريرات",
    "cancelMessage": "إلغاء التحريرات بالسجل الحالي؟"
  }
});