define({
  "_widgetLabel": "Prúd",
  "streamControls": "Ovládacie prvky údajov v reálnom čase",
  "streamFilter": "Filter",
  "startStreaming": "Spustiť pripojenie údajov v reálnom čase",
  "stopStreaming": "Zastaviť pripojenie údajov v reálnom čase",
  "streamLayers": "Vrstvy v reálnom čase",
  "startStopStream": "Aktivovať možnosť Stop zobrazovania v reálnom čase a Štart zobrazovania v reálnom čase",
  "clearStream": "Aktivovať možnosť Vyčistiť predošlé pozorovania",
  "attributeFilter": "Aktivovať filter atribútov",
  "spatialFilter": "Aktivovať priestorový filter",
  "configFilter": "Konfigurovať atribútové filtre reálneho času",
  "drawPrevious": "Aktivovať možnosť Kresliť predošlé pozorovania",
  "addNew": "Pridať filter",
  "setFilterName": "Nastaviť meno filtra",
  "filterNameExists": "Meno filtra sa už v tabuľke nachádza!",
  "invalidFilterName": "Meno by malo byť slovo obsahujúce znaky a-z, A-Z, 0-9 alebo _.",
  "noFilterTip": "Žiadny nakonfigurovaný filter",
  "addFilterFailed": "Pridanie filtra zlyhalo",
  "filterName": "Meno filtra",
  "limitMapExtent": "Obmedziť pozorovania na súčasný rozsah mapy",
  "limitDrawExtent": "Obmedziť na používateľom definovanú oblasť",
  "newFilter": "Nový filter",
  "filterReadOnly": "Filter prebratý z webovej mapy je určený len na čítanie."
});