define({
  "chartSettingLabel": "Настройки на диаграма",
  "addNewLabel": "Добавяне на нова",
  "generalSettingLabel": "Общи настройки",
  "searchSourceSettingLabel": "Настройки за търсене в източника",
  "layerChooser": {
    "title": "Изберете слой към диаграмата",
    "selectPolygonLayerLabel": "Изберете слой",
    "selectPolygonLayerHintText": "Съвет: Ако конфигурирате множество диаграми, тогава слоевете трябва да бъдат с един и същ тип геометрия",
    "selectRelatedTableLayerLabel": "Изберете таблица, свързана със слоя",
    "selectRelatedTableLayerHintText": "Съвет: Показват се само таблици с цифрови полета",
    "errorInSelectingPolygonLayer": "Моля, изберете слой, който има свързан точков слой.",
    "errorInSelectingRelatedLayer": "Моля, изберете валидна свързана таблица/слой към слой.",
    "polygonLayerNotHavingRelationships": "Избраният слой няма свързана таблица/слой."
  },
  "ChartSetting": {
    "sectionTitle": "Заглавие на раздел",
    "sectionTitleHintText": "Съвет: Показва се в заглавието на колонтитула на раздела",
    "chartTitle": "Заглавие на диаграма",
    "chartTitleHintText": "Съвет: Показва се центрирано в горната част на диаграмата",
    "chartDescription": "Описание",
    "chartDescriptionHintText": "Подсказка: Показва се под диаграмата",
    "chartType": "Тип диаграма",
    "barChart": "Диаграма във форма на лента",
    "pieChart": "Диаграма в кръгла форма",
    "polarChart": "Полярна диаграма",
    "lineChart": "Диаграма във форма на линия",
    "dataSeriesField": "Поле за поредица от данни",
    "lineDataSeriesField": "Поле за стойност",
    "labelField": "Поле за надпис",
    "lineLabelSeriesField": "Поле за последователност",
    "chartColor": "Цвят на диаграма",
    "singleColor": "Един цвят",
    "colorByTheme": "Цвят по тема",
    "colorByFieldValue": "Цвят по стойност на полето",
    "xAxisTitle": "Заглавие на оста X",
    "xAxisHintText": "Подсказка: Заглавие на оста X",
    "yAxisTitle": "Заглавие на оста Y",
    "yAxisHintText": "Подсказка: Заглавие на оста Y",
    "fieldColorLabel": "Надпис",
    "fieldColorColor": "Цвят",
    "defaultFieldSelectLabel": "Избор",
    "errMsgFieldValuesNotFound": "Не може да се намерят стойности за избраното поле",
    "errMsgSectionTitle": "Моля, въведете заглавието на раздела",
    "errMsgFieldByValue": "Моля, изберете цвят по стойност на полето",
    "errMsgDataSeriesField": "Моля, изберете поле за стойност",
    "settingTabTitle": "Настройка",
    "layoutTabTitle": "Оформление",
    "polarChartSelectFieldsHintText": "Съвет: Изберете полета, за да генерирате полярна диаграма",
    "visibilityText": "Видимост",
    "fieldNameText": "Име на поле",
    "aliasNameText": "Псевдоним",
    "errMsgPolarFieldsRequired": "Моля, изберете три или повече полета, за да генерирате полярна диаграма",
    "polarChartPolygonFillLabel": "Запълване на полигон",
    "polarChartPolygonFillHintText": "Съвет: Поставете отметка в квадратчето, за да се покаже запълване на полигон в полярна графика",
    "viewLayoutLabel": "Оформление",
    "setValueFields": "Задаване на полета за стойност",
    "layoutSeriesLabel": "Серии",
    "ThemeSelector": {
      "themeAdobebricks": "Adobe тухли",
      "themeAlgae": "Водорасли",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Син залез",
      "themeCubanShirts": "Кубински ризи",
      "themeDesert": "Пустиня",
      "themeDistinctive": "Отличителни",
      "themeDollar": "Долар",
      "themeGrasshopper": "Скакалец",
      "themeGrasslands": "Пасище",
      "themeGreySkies": "Сиви небеса",
      "themeHarmony": "Хармония",
      "themeIndigoNation": "Индиго нация",
      "themeIreland": "Ирландия",
      "themeMiamiNice": "Маями Ница",
      "themeMinty": "Мента",
      "themePurpleRain": "Пурпурен дъжд",
      "themeRoyalPurples": "Кралско лилаво",
      "themeSageToLime": "Сиво-зелено до лимонено жълто",
      "themeTufte": "Туфи",
      "themeWatersEdge": "Водораздел",
      "themeWetlandText": "Влажни зони",
      "themePlotKitblue": "PlotKit.син",
      "themePlotKitcyan": "PlotKit.циан",
      "themePlotKitgreen": "PlotKit.зелен",
      "themePlotKitorange": "PlotKit.оранжев",
      "themePlotKitpurple": "PlotKit.лилав",
      "themePlotKitred": "PlotKit.червен"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Общи настройки",
    "locationSymbolLabel": "Графичен символ за местоположение",
    "locationSymbolHintText": "Съвет: Използвайте да покажете символ за адрес и натиснете върху местоположение",
    "refreshIntervalLabel": "Интервал за обновяване",
    "refreshIntervalHintText": "Съвет: Използва се за опресняване на диаграми, базирани на този интервал. Посочете стойност от 1 до 1440 минути",
    "errMsgRefreshInterval": "Моля, посочете интервал за опресняване от 0 до 1440 минути",
    "symbolPickerPreviewText": "Предварителен преглед:",
    "showToolToSelectLabel": "Задаване на бутон за местоположение",
    "showToolToSelectHintText": "Съвет: Предоставя бутон за задаване на местоположение на картата, вместо винаги да задава местоположението, когато картата е избрана"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Настройки на източник на търсене",
    "searchSourceSettingTitle": "Настройки на източник на търсене",
    "searchSourceSettingTitleHintText": "Добавете и конфигурирайте услуги за геокодиране или обектни слоеве като източници на търсене. Тези посочени източници определят какво може да се търси в полето за търсене",
    "addSearchSourceLabel": "Добавяне на източник за търсене",
    "featureLayerLabel": "Обектен слой",
    "geocoderLabel": "Геокодер",
    "nameTitle": "Име",
    "generalSettingLabel": "Общи настройки",
    "allPlaceholderLabel": "Алтернативен текст за търсене във всички:",
    "allPlaceholderHintText": "Съвет: Въведете текст, който да се показва като алтернативен, докато търсите във всички слоеве и геокодер",
    "generalSettingCheckboxLabel": "Показване на изскачащи прозорци за намерените обекти или местоположения",
    "countryCode": "Код (-ове) на държава или район",
    "countryCodeEg": "напр. ",
    "countryCodeHint": "Ако оставите тази стойност празна, ще търсите във всички държави и райони.",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Търсене само в обхвата на текущата карта",
    "zoomScale": "Мащаб на зуум",
    "locatorUrl": "URL адрес на геокодер",
    "locatorName": "Име на геокодер",
    "locatorExample": "Пример",
    "locatorWarning": "Тази версия на услугата за геокодиране не се поддържа. Изпълнимият модул поддържа услуга за геокодиране с версия 10.0 и по-нова.",
    "locatorTips": "Предложенията не са налични, тъй като услугата за геокодиране не поддържа възможността за предлагане.",
    "layerSource": "Източник на слой",
    "setLayerSource": "Задаване на източник на слой",
    "setGeocoderURL": "Задаване на URL адрес на геокодер",
    "searchLayerTips": "Предложенията не са налични, тъй като услугата за обекти не поддържа възможност за разбиване на страници.",
    "placeholder": "Алтернативен текст",
    "searchFields": "Полета за търсене",
    "displayField": "Поле за показване",
    "exactMatch": "Точно съвпадение",
    "maxSuggestions": "Максимален брой предложения",
    "maxResults": "Максимален брой резултати",
    "enableLocalSearch": "Активиране на локално търсене",
    "minScale": "Минимално мащабиране",
    "minScaleHint": "Когато мащабът на картата е по-голям от този мащаб, ще се приложи локално търсене",
    "radius": "Радиус",
    "radiusHint": "Задава радиус на област около текущия център на картата, която се използва за повишаване на ранга на кандидатите за геокодиране, така че кандидатите, най-близки до местоположението, да бъдат върнати първи",
    "meters": "Метри",
    "setSearchFields": "Задаване на полета за търсене",
    "set": "Настройване",
    "fieldName": "Име",
    "invalidSearchSources": "Настройките на източника на търсене са невалидни",
    "invalidUrlTip": "URL адресът ${URL} е невалиден или е недостъпен.",
    "maxSuggestionErrorMessage": "Моля, въведете валидна максимална стойност на предложенията. Стойността е извън диапазона или невалидна.",
    "maxResultsErrorMessage": "Моля, въведете валидна максимална стойност на резултатите. Стойността е извън диапазона или невалидна.",
    "zoomScaleErrorMessage": "Моля, въведете валидна стойност на мащаба за мащабиране. Стойността е извън диапазона или невалидна.",
    "minScaleErrorMessage": "Моля, въведете валидна минимална стойност за мащаб. Стойността е извън диапазона или невалидна.",
    "radiusErrorMessage": "Моля, въведете валидна стойност за радиус. Стойността е извън диапазона или невалидна."
  }
});