define({
  "_widgetLabel": "Editor de Atributo em Lote",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Nome da Camada",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Nenhuma camada editável configurada",
  "editorPopupTitle": "Editor de Atributo em Lote",
  "editorPopupSaveBtn": "Salvar",
  "editorPopupMultipleValues": "",
  "clear": "Apagar",
  "featuresUpdated": "${0} / ${1} feições atualizadas",
  "featuresSelected": "${0} feições selecionadas",
  "featuresSkipped": "Validado",
  "featuresNoPermision": "${0} feições selecionadas, mas sem permissão para editar.",
  "search": "Pesquisar",
  "queryInput": "Insira um valor para consultar",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Configure o filtro corretamente.",
  "filterPopup": "Filtrar Camada",
  "filterAppend": "Se já existe um filtro no mapa da web para esta camada",
  "filterAppendOR": "Anexar qualquer expressão ao filtro de mapa existente",
  "filterAppendAND": "Anexar todas as expressões ao filtro de mapa existente",
  "cancel": "Cancelar",
  "noValue": "Valor de Não",
  "emptyString": "String Vazia",
  "existingValue": "Manter Valor Existente",
  "newDate": "Nova Data",
  "valueChooser": "Selecionar/Digitar um Valor",
  "ok": "Ok",
  "drawBox": {
    "point": "Ponto",
    "line": "Linha",
    "polyline": "Polilinha",
    "freehandPolyline": "Polilinha À Mão Livre",
    "extent": "Extensão",
    "polygon": "Polígono",
    "freehandPolygon": "Polígono À Mão Livre",
    "clear": "Apagar",
    "addPointToolTip": "Clique para selecionar nesta área",
    "addShapeToolTip": "Desenhe uma forma para selecionar feições",
    "freehandToolTip": "Pressione e segure para desenhar uma forma para selecionar feições",
    "startToolTip": "Desenhe uma forma para selecionar feições"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "A feição do ${0} retornou um ID inválido",
    "noSelectedLayers": "Nenhuma camada selecionada com registros para atualizar",
    "inputValueError": "Valor inválido no formulário",
    "saveError": "Não foi possível salvar ${0} feições",
    "requiredValue": "Valor Exigido"
  }
});