define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Herhangi bir alan için temel göstergeleri ve verileri özetleyen Bilgi Grafikleri ve Raporlara erişim sağlayın.</div><br><div>Haritada bir nokta veya çokgen seçin, bir adres veya yer arayın, bir çokgen çizin veya önemli göstergeleri ve alan hakkındaki bilgileri görüntülemek için haritaya bir raptiye ekleyin.</div>",
  "defineWhichInfographics": "Araçta hangi bilgi grafiklerinin kullanılabilir olduğunu tanımlayın:",
  "defineWhichReports": "Araçta hangi raporların kullanılabilir olduğunu tanımlayın:",
  "defaultValues": "Varsayılan değerler:",
  "disable": "Devre Dışı Bırak",
  "drawFreehandPolygon": "Serbest Çokgen Çiz",
  "drawPolygon": "Alan Çiz",
  "driveTime": "Sürüş zamanı",
  "dropPin": "Raptiye Yerleştir",
  "dynamicHTML": "Dinamic HTML",
  "exportOptions": "Dışa Aktarma Seçenekleri:",
  "home": "Giriş Sayfası",
  "image": "Görüntü",
  "infographics": "Bilgi Grafikleri",
  "invalidValueRing": "Değerler 0 - 1.000 aralığında olmalıdır.",
  "invalidValueDTWT": "Değerler 0 - 300 aralığında olmalıdır.",
  "km": "km",
  "makeDefault": "Varsayılan yap",
  "miles": "mil",
  "minutes": "dakika",
  "options": "Seçenekler:",
  "pdf": "PDF",
  "print": "Yazdır",
  "radius": "Yarıçap",
  "removeDefault": "Varsayılanı kaldır",
  "reports": "Raporlar",
  "rings": "Halkalar",
  "searchTextBox": "Metin Kutusu Ara",
  "selectCountryOrRegion": "Ülke veya bölge seçin:",
  "thisEntryIsNotValid": "Giriş geçerli değil.",
  "time": "Saat",
  "walkTime": "Yürüme süresi"
});