define({
  "transparencyLabel": "Прозрачность",
  "outline": "Контур",
  "fill": "Заливка (Цвет применяется, только если задан сплошной)",
  "style": "Стиль",
  "selectOpLayerLabel": "Выберите операционный слой для результатов",
  "selectDefaultMeasurementLabel": "Выберите единицы измерения по умолчанию",
  "helpIconTooltip": "Список операционных слоев заполнен слоями текущей веб-карты с типом геометрии - полигон.",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире – точка",
    "esriSLSDashDotDot": "Тире – точка – точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Длинное тире",
    "esriSLSLongDashDot": "Длинное тире – точка",
    "esriSLSNull": "Пустой",
    "esriSLSShortDash": "Короткое тире",
    "esriSLSShortDashDot": "Короткое тире – точка",
    "esriSLSShortDashDotDot": "Короткое тире – точка – точка",
    "esriSLSShortDot": "Короткая точка",
    "esriSLSSolid": "Сплошной"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Обратно",
    "esriSFSCross": "Перекрестный",
    "esriSFSDiagonalCross": "Диагональ",
    "esriSFSForwardDiagonal": "Прямо",
    "esriSFSHorizontal": "Горизонтально",
    "esriSFSNull": "Пустой",
    "esriSFSSolid": "Сплошной",
    "esriSFSVertical": "Вертикальная"
  },
  "threatTypeLabel": "Тип угрозы",
  "generalLabel": "Общее",
  "addThreatTypesLabel": "Добавить тип угрозы",
  "actions": "Действия",
  "newThreatTypePopupLabel": "Новый тип угрозы",
  "units": "Ед. измерения",
  "chooseDefaultThreatLabel": "Выбрать тип угрозы по умолчанию",
  "defaultThreatTypePopUpLabel": "Типы угрозы по умолчанию",
  "editThreatLabel": "Редактировать угрозу",
  "defaultThreatTypeIconTooltip": "Список типов угрозы по умолчанию",
  "uniqueThreatTypeMsg": "Введите уникальный тип угрозы, тип угрозы с таким именем уже существует.",
  "requiredMsg": "Это поле является обязательным",
  "unitMeasureLabel": "Расстояния в {0}",
  "chooseDefaultThreatTypeIconLabel": "Выбрать из предлагаемых по умолчанию",
  "pipeBombLabel": "Самодельная бомба",
  "suicideBombLabel": "Бомба смертника",
  "briefcaseLabel": "Чемоданчик",
  "carLabel": "Легковой автомобиль",
  "suvVanLabel": "Газель",
  "smallDeliveryTruckLabel": "Грузовик",
  "containerWaterTruckLabel": "Контейнеровоз/цистерна",
  "semiTrailerLabel": "Полуприцеп",
  "chemicalThreatLegendLabel": "Химическая угроза",
  "lpgThreatLegendLabel": "Угроза от сжиженного газа",
  "smallLPGTank": "Малое хранилище сжиженного газа",
  "largeLPGTank": "Большое хранилище сжиженного газа",
  "commercialResidentialLPGTank": "Коммерческое/Частное хранилище сжиженного газа",
  "smallLPGTruck": "Малый бензовоз для сжиженного газа",
  "semiTankerLPG": "Полутанкер для сжиженного газа",
  "threatDescriptionColLabel": "Описание угрозы",
  "addThreatZoneButtonLabel": "Добавить зону риска",
  "zoneDescColLabel": "Описание зоны",
  "distanceLabel": "Расстояние (${unitAbbr})",
  "threatTypeHelp": "<p>Убедитесь, что для типа угрозы выполняются следующие условия:<br/><ul><li>Тип угрозы не может быть пустым и должен быть уникальным</li><li>Угроза должна иметь хотя бы одну допустимую зону</li><li>Описание зоны для угрозы должно быть уникальным</li></ul><p/>",
  "descriptionLabel": "Описание",
  "newThreatZonePopupLabel": "Новая зона риска",
  "editThreatZonePopupLabel": "Редактировать зону риска",
  "uniqueZoneDescriptionMsg": "Введите уникальное описание зоны, описание с таким именем уже существует.",
  "symbologyColLabel": "Символы",
  "zoneDescriptionColLabel": "Описание зоны",
  "uniqueZoneRequiredMsg": "Имя зоны должно быть уникальным для",
  "interactive": "Интерактивный",
  "fromCoord": "Фиксированные координаты",
  "existingFeature": "Из существующих объектов",
  "defaultInputLocationLabel": "Входное местоположение по умолчанию",
  "defaultInputLayer": "Входной слой по умолчанию",
  "defaultThreatType": "Тип угрозы по умолчанию",
  "selectLabel": "Выбрать",
  "mandatoryLabel": "Обязательное расстояние эвакуации",
  "safeLabel": "Безопасное расстояние эвакуации",
  "lpgSafeDistanceLable": "Безопасное расстояние",
  "fireBallDiameterLable": "Диаметр огненного шара"
});