define({
  "labelBookmarkName": "Pievienot pašreizējo skatu grāmatzīmēm",
  "labelPlay": "Atskaņot visu",
  "labelStop": "Apturēt",
  "labelDelete": "Dzēst",
  "placeholderBookmarkName": "Grāmatzīmes nosaukums",
  "errorNameExist": "Grāmatzīme pastāv!",
  "errorNameNull": "Nederīgs grāmatzīmes nosaukums.",
  "editTip": "Labot grāmatzīmes",
  "exitEditTip": "Iziet no labošanas režīma",
  "syncTip": "Sinhronizēt",
  "cardsTips": "Tīkla skats",
  "listTips": "Saraksta skats",
  "addBtn": "Pievienot",
  "deleteBtn": "Izdzēst",
  "changeThumbnailTip": "Mainīt sīktēlu",
  "dragReorderTip": "Lai pārkārtotu, turiet un velciet",
  "deleteBtnTip": "Dzēst grāmatzīmi",
  "editBtnTip": "Labot grāmatzīmi",
  "withVisibility": "Ar slāņu redzamību",
  "searchBookmark": "Meklēt",
  "bookmarksFromConfig": "Sākotnēji konfigurētas grāmatzīmes",
  "bookmarksFromCache": "Lokālās pagaidu grāmatzīmes",
  "notice": "Paziņot",
  "changeNoticeTips": "Izmaiņas tiks saglabātas tikai pārlūka kešatmiņā. Veicot izmaiņas, sinhronizācija starp logrīku un tā konfigurāciju tiek atspējota.",
  "syncNoticeTips": "Šādi tiks izdzēstas visas izmaiņas un restaurētas konfigurētās grāmatzīmes.",
  "dontShowAgain": "Vairs nerādīt",
  "saveVisibility": "Saglabāt slāņu redzamību",
  "_widgetLabel": "Grāmatzīme"
});