define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Piekļūstiet infografikām un pārskatiem, kas apkopo galvenos rādītājus un datus par jebkuru teritoriju.</div><br><div>Kartē atlasiet punktu vai laukumu, sameklējiet adresi vai vietu, uzzīmējiet laukumu vai kartē novietojiet spraudīti, lai skatītu pamata rādītājus un informāciju par šo teritoriju.</div>",
  "defineWhichInfographics": "Norādiet, kāda infografika ir pieejama logrīkā:",
  "defineWhichReports": "Norādiet, kādi pārskati ir pieejami logrīkā:",
  "defaultValues": "Noklusētā vērtības:",
  "disable": "Atspējot",
  "drawFreehandPolygon": "Zīmēt brīvas formas laukumu",
  "drawPolygon": "Zīmēt laukumu",
  "driveTime": "Braukšanas laiks",
  "dropPin": "Novietot saspraudīti",
  "dynamicHTML": "Dinamisks HTML",
  "exportOptions": "Eksporta opcijas:",
  "home": "Sākums",
  "image": "Attēls",
  "infographics": "Infografika",
  "invalidValueRing": "Vērtībām jābūt diapazonā no 0 līdz 1000.",
  "invalidValueDTWT": "Vērtībām jābūt diapazonā no 0 līdz 300.",
  "km": "km",
  "makeDefault": "Padarīt par noklusējumu",
  "miles": "jūdzes",
  "minutes": "minūtes",
  "options": "Opcijas:",
  "pdf": "PDF",
  "print": "Drukāt",
  "radius": "Rādiuss",
  "removeDefault": "Noņemt noklusējumu",
  "reports": "Pārskati",
  "rings": "Apļi",
  "searchTextBox": "Meklēšanas tekstlodziņš",
  "selectCountryOrRegion": "Izvēlieties valsti vai reģionu:",
  "thisEntryIsNotValid": "Šis ieraksts nav derīgs.",
  "time": "Laiks",
  "walkTime": "Iešanas laiks"
});