define({
  "taskUrl": "URL de servicio de cuenca visual",
  "portalURL": "Especifica la dirección URL de tu organización de ArcGIS Online o Portal for ArcGIS",
  "portalURLError": "La URL configurada para su organización de ArcGIS Online o Portal for ArcGIS no es válida.",
  "privilegeError": "Su rol de usuario no puede realizar análisis. Para realizar análisis, el administrador de su organización debe concederle ciertos <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegios</a>.",
  "noServiceError": "Servicio de análisis de elevación no disponible. Compruebe la configuración de su organización de ArcGIS Online o Portal for ArcGIS.",
  "serviceURLPlaceholder": "Introduzca la URL de la tarea de geoprocesamiento de cuenca visual",
  "setTask": "Establecer",
  "setTaskTitle": "Definir tarea de geoprocesamiento de cuenca visual",
  "serviceURLError": "La tarea de geoprocesamiento que está intentando configurar con este widget no es válida. Seleccione una URL válida de tarea de geoprocesamiento de cuenca visual",
  "defaultMilsForAnglesLabel": "Definir mils como unidad predeterminada para ángulos",
  "defaultObserverHeightLabel": "Unidad de altura del observador predeterminada",
  "defaultObservableDistanceLabel": "Unidad de distancia observable predeterminada",
  "units": {
    "miles": "Millas",
    "kilometers": "Kilómetros",
    "feet": "Pies",
    "meters": "Metros",
    "yards": "Yardas",
    "nauticalMiles": "Millas náuticas"
  },
  "helpIconTooltip": "La lista de capas operativas se rellena con las capas del mapa web actual que corresponden al tipo de geometría de polígono.",
  "selectOperationalLayerLabel": "Seleccionar una capa operativa para los resultados",
  "lineOfSightTabTitle": "Línea de visión",
  "symbologyTabTitle": "Simbología",
  "transparency": "Transparencia",
  "outline": "Contorno",
  "fill": "Relleno (el color solo se aplica si el estilo es sólido)",
  "style": "Estilo",
  "selectOpLayerLabel": "Seleccionar una capa operativa para los resultados",
  "selectDefaultMeasurementLabel": "Seleccionar una unidad de medida predeterminada",
  "visibleSectionLabel": "Sección visible",
  "nonVisibleSectionLabel": "Sección no visible",
  "visibleSectionButtonLabel": "Configurar los ajustes de Sección visible",
  "nonVisibleSectionButtonLabel": "Configurar los ajustes de Sección no visible",
  "colorPicker": "Selector de color",
  "lineStyles": {
    "esriSLSDash": "Guion",
    "esriSLSDashDot": "Guion punto",
    "esriSLSDashDotDot": "Guion punto punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Guion largo",
    "esriSLSLongDashDot": "Guion largo, Punto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Guion corto",
    "esriSLSShortDashDot": "Guion corto Punto",
    "esriSLSShortDashDotDot": "Guion corto Punto Punto",
    "esriSLSShortDot": "Corto Punto",
    "esriSLSSolid": "Cuerpo geométrico"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atrás",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Hacia delante",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Cuerpo geométrico",
    "esriSFSVertical": "Vertical"
  }
});