define({
  "taskUrl": "可視領域サービスの URL",
  "portalURL": "ArcGIS Online 組織サイトまたは Portal for ArcGIS の URL を指定します",
  "portalURLError": "ArcGIS Online 組織サイトまたは Portal for ArcGIS の構成された URL が有効ではありません。",
  "privilegeError": "このユーザー ロールでは、解析を実行できません。 解析を実行するには、組織の管理者が特定の<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">権限</a>を付与する必要があります。",
  "noServiceError": "標高解析サービスが利用できません。 ArcGIS Online 組織サイトまたは Portal for ArcGIS の URL の構成を確認してください。",
  "maximumRangeMessage": "最大観測範囲は最小観測範囲より大きい必要があり、${limit} ${units} を超えてはなりません。",
  "serviceURLPlaceholder": "可視領域ジオプロセシング タスク URL を入力してください。",
  "setTask": "設定",
  "setTaskTitle": "可視領域ジオプロセシング タスクの設定",
  "serviceURLError": "このウィジェットで構成しようとしているジオプロセシング タスクは有効ではありません。有効な可視領域ジオプロセシング タスク URL を選択してください。",
  "defaultMilsForAnglesLabel": "角度のデフォルトとしてミルを設定",
  "defaultObserverHeightLabel": "デフォルトの観測点の高度単位",
  "defaultObservableDistanceLabel": "デフォルトの観測距離単位",
  "defaultObserveHeightLabel": "デフォルトの観測点の高度",
  "defaultMinimumObservableDistanceLabel": "デフォルトの最短観測距離",
  "defaultMaximumObservableDistanceLabel": "デフォルトの最長観測距離",
  "units": {
    "miles": "マイル",
    "kilometers": "キロメートル",
    "feet": "フィート",
    "meters": "メートル",
    "yards": "ヤード",
    "nauticalMiles": "海里"
  },
  "helpIconTooltip": "操作レイヤー リストは、現在の Web マップから、ポリゴン ジオメトリ タイプであるレイヤーを使用して設定されます。",
  "selectOperationalLayerLabel": "結果の操作レイヤーを選択",
  "lineOfSightTabTitle": "見通し",
  "symbologyTabTitle": "シンボル",
  "transparency": "透過表示",
  "outline": "枠線",
  "fill": "塗りつぶし (スタイルを実線に設定した場合のみ色を適用)",
  "style": "スタイル",
  "selectOpLayerLabel": "結果の操作レイヤーを選択",
  "selectDefaultMeasurementLabel": "デフォルトの計測単位を選択",
  "visibleSectionLabel": "可視セクション",
  "nonVisibleSectionLabel": "不可視セクション",
  "visibleSectionButtonLabel": "可視セクションの設定を構成",
  "nonVisibleSectionButtonLabel": "不可視セクションの設定を構成",
  "colorPicker": "カラー パレット",
  "lineStyles": {
    "esriSLSDash": "破線",
    "esriSLSDashDot": "1 点鎖線",
    "esriSLSDashDotDot": "2 点鎖線",
    "esriSLSDot": "ドット",
    "esriSLSLongDash": "長い破線",
    "esriSLSLongDashDot": "長い 1 点鎖線",
    "esriSLSNull": "NULL",
    "esriSLSShortDash": "短い破線",
    "esriSLSShortDashDot": "短い 1 点鎖線",
    "esriSLSShortDashDotDot": "短い 2 点鎖線",
    "esriSLSShortDot": "短いドット",
    "esriSLSSolid": "ソリッド"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "逆斜線",
    "esriSFSCross": "十字",
    "esriSFSDiagonalCross": "対角線",
    "esriSFSForwardDiagonal": "斜線",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "NULL",
    "esriSFSSolid": "ソリッド",
    "esriSFSVertical": "鉛直"
  }
});