define({
  "_widgetLabel": "Agregacija podatkov",
  "startPage": {
    "defaultStartPageInstructions": "Ta pripomoček vam bo pomoč pri obdelavi in pošiljanju podatkov iz datoteke v izbrani sloj na karti.<.<br/> <br/> Vrednosti znotraj datoteke morajo ločene z vejico, presledkom, podpičjem ali navpičnico.",
    "dragDrop": "Povlecite in odložite",
    "browse": "Brskajte do datoteke",
    "or": "ALI",
    "userPrivilege": "Vaš račun nima dovoljenja za ustvarjanje ali spreminjanje podatkov.",
    "userCredits": "${widgetName} zahteva kredite za uporabo lokatorja ${locator}.",
    "contactAdmin": "Obrnite se na adminstratorja organizacije, da zahtevate dodatne kredite.",
    "contactAdminEdit": "Obrnite se na administratorja organizacije, da zahtevate urejanje pravic.",
    "canUseLocator": "Za iskanje geoobjektov bo uporabljen lokator ${locator}.",
    "notEnoughCredits": "Ni dovolj kreditov.",
    "locationAndField": "Informacije o lokaciji in polju",
    "locationAndFieldHint": "Izberite vrednosti iz datoteke, ki naj bodo uporabljene za posodobitev ciljnega sloja.",
    "cannotUseLocator": "Ni mogoče uporabiti ${widgetName}",
    "noAnonymousEdit": "Sloj ${layerName} ne podpira anonimnega urejanja.",
    "pleaseLogin": "Prijavite se v organizacijo ${org} ali pa se obrnite na administratorja organizacije, da zahtevate omogočenje anonimnega urejanja.",
    "invalidEdit": "Neveljavne pravice",
    "unableToAccess": "Do ${layerName} ni mogoče dostopati",
    "appropriateCredentials": "Preverite, da ste se prijavili z ustreznimi poverilnicami.",
    "shared": "Obrnite se na administratorja organizacije, da zahtevate dostop do sloja ${layerName}.",
    "targetLayerLabel": "Ciljni sloj",
    "homeButtonLabel": "Domov",
    "mappingErrorMsg": "Kliknite puščico za določitev polj"
  },
  "mapping": {
    "schemaMapping": "Informacije o polju",
    "schemaMappingHint": "Izberite polja iz datoteke, ki so povezana s polji v sloju.",
    "locationMapping": "Informacije o lokaciji",
    "locationMappingHint": "Izberite tip naslova ali informacije o koordinatah, ki jih pričakujete v datoteki."
  },
  "locationMapping": {
    "locationMappingPageHint": "Izberite tip lokacije",
    "useAddress": "Poiščite z naslovom",
    "useAddressHint": "Podatki vsebujejo informacije o naslovu",
    "useCoordinates": "Poišči s koordinatami",
    "useCoordinatesHint": "Podatki vsebujejo vrednosti koordinat X/Y"
  },
  "address": {
    "addressPageHint": "Izberite tip naslova",
    "singleField": "Eno polje",
    "singleFieldHint": "Izberite polje, ki vsebuje informacije o naslovu",
    "multiField": "Več polj",
    "multiFieldHint": "Izberite polja, ki vsebujejo informacije o naslovu"
  },
  "coordinates": {
    "coordinatesPageHint": "Izberite polja, ki vsebujejo podatke o koordinatah"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Izberite izvorno polje, ki se preslika v ciljno polje",
    "sourceField": "Ujemajoče se izvorno polje",
    "targetField": "Ciljno polje"
  },
  "buttons": {
    "addToMap": "Dodaj na karto",
    "submit": "Pošlji",
    "download": "Prenesi"
  },
  "review": {
    "matched": "Najdeno",
    "reviewMatched": "Lokacije najdene",
    "reviewMatchedHint": "Preglejte lokacije, ki so bile najdene.",
    "unMatched": "ni najdeno",
    "reviewUnMatched": "Lokacije niso bile najdene",
    "reviewUnMatchedHint": "Preglejte lokacije, ki niso bile najdene. Elemenit, ki niso popravljeni, ne bodo poslani.",
    "duplicate": "Podvoji",
    "reviewDuplicate": "Podvoji lokacije",
    "reviewDuplicateHint": "Preglejte lokacije, ki so že bile najdene v sloju. Elementi, ki niso obravnavani, ne bodo poslani.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Uporaba:",
    "fromLayer": "Ciljne informacije",
    "target": "Cilj",
    "source": "Vir",
    "fromFile": "Informacije o viru",
    "locationControlHint": "Preglejte informacije naslova",
    "duplicateAction": "Izberite dejanje",
    "item": "Zapis:",
    "locateFeature": "Poišči geoobjekt",
    "removeFeature": "Odstrani geoobjekt",
    "featureLocated": "Lokacija najdena",
    "valuesDoNotMatch": "Se ne ujema z obstoječo vrednostjo",
    "sync": "Sinhroniziraj informacije o naslovu z informacijami polja",
    "noFeaturesSaved": "Noben geoobjekt ni bil uspešno shranjen",
    "someFeaturesSaved": "${num} geobjektov uspešno shranjenih.",
    "someFeaturesNotSaved": "${num} geoobjektov ni bilo uspešno shranjenih.",
    "feature": "Preglejte informacije o geoprojektu",
    "locationInfo": "Preglejte informacije o lokaciji",
    "selectValue": "Izberite vrednost",
    "reviewData": "Preglejte podatke",
    "reviewDataHint": "Preglejte svoje podatke, preden jih pošljete v sloj.",
    "reviewFeatureHint": "Preglejte ali uredite svoje informacije o geoobjektu in lokaciji.",
    "duplicateModify": "Podvojitev, obvezna sprememba",
    "duplicateSave": "Shranite kot nov geoobjekt"
  },
  "warningsAndErrors": {
    "invalidCSV": "Napaka pri pridobivanju elementov iz CSV; preverite, ali je izbrana veljavna datoteka CSV.",
    "noLayersWarning": "Noben veljavni ciljni sloj ni bil konfiguriran; preverite konfiguracijo.",
    "loadWarning": "Ta pripomoček zahteva podatkovni vir geoobjektne storitve. Konfigurirajte pripomoček za določitev podatkovnega vira.",
    "saveError": "Napaka pri shranjevanju geoobjektov.",
    "consumesCredits": "To orodje porablja kredite, če uporabljate geokodirno storitev ArcGIS Online.",
    "noValue": "Izberi polje",
    "mappingTitle": "",
    "locationMappingComplete": "Preslikava lokacije je dokončana",
    "fieldMappingComplete": "Preslikava polja je dokončana",
    "settingsCleared": "Nastavite bodo počiščene.",
    "proceed": "Želite nadaljevati?",
    "itemMoveMatch": "Element je bil najden in premaknjen na seznam najdenih lokacij",
    "itemMoveUnMatched": "Elementa ni mogoče najti. Premaknjen na seznam lokacij, ki niso bile najdene.",
    "itemWillBeLocated": "Element bo odstranjen iz seznama podvojenih lokacij.",
    "cannotLocate": "Elementa ni mogoče najti. Preverite informacije o lokaciji",
    "invalidMessage": "Neveljavna vrednost.",
    "rangeMessage": "Vrednost mora imeti manj kot ${num} znakov.",
    "locatorError": "Lokator neveljaven ali nedostopen.",
    "notConfigured": "lokator ni konfiguriran za trenutne možnosti določanja lokacije",
    "noMoreLocators": "konfiguriran ni noben dodatni lokator"
  },
  "featureToolbar": {
    "locate": "Lociraj",
    "save": "Shranite zapis",
    "cancel": "Prekličite urejanja",
    "cancelTitle": "Prekličite urejanja",
    "cancelMessage": "Želite preklicati urejanja trenutnega zapisa?"
  }
});