define({
  "taskUrl": "Redzamības lauka servisa URL",
  "portalURL": "Norādiet URL uz jūsu ArcGIS Online organizāciju vai Portal for ArcGIS",
  "portalURLError": "Konfigurētais vietrādis (URL) uz jūsu ArcGIS Online organizāciju vai Portal for ArcGIS nav derīgs.",
  "privilegeError": "Ar jums piešķirto lomu nevar veikt analīzi. Lai veiktu analīzi, jūsu organizācijas administratoram jāpiešķir jums atbilstīgu <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">atļauju</a>.",
  "noServiceError": "Augstuma analīzes serviss nav pieejams. Lūdzu, pārbaudiet savu ArcGIS Online organizācijas vai Portal for ArcGIS konfigurāciju.",
  "serviceURLPlaceholder": "Lūdzu, ievadiet redzamības lauka ģeoapstrādes uzdevuma URL",
  "setTask": "Uzstādīt",
  "setTaskTitle": "Iestatīt redzamības lauka ģeoapstrādes uzdevumu",
  "serviceURLError": "Ģeoapstrādes uzdevums, ko mēģināt konfigurēt ar šo logrīku, nav derīgs. Izvēlieties derīgu redzamības lauka ģeoapstrādes uzdevuma vietrādi URL",
  "defaultMilsForAnglesLabel": "Iestatīt tūkstošdaļas leņķiem kā noklusējumu",
  "defaultObserverHeightLabel": "Noklusējuma vērotāja augstuma mērvienība",
  "defaultObservableDistanceLabel": "Noklusējuma novērojama attāluma mērvienība",
  "units": {
    "miles": "Jūdzes",
    "kilometers": "Kilometri",
    "feet": "Pēdas",
    "meters": "Metri",
    "yards": "Jardi",
    "nauticalMiles": "Jūras jūdzes"
  },
  "helpIconTooltip": "Darbības slāņu saraksts ir aizpildīts ar pašreizējās tīmekļa kartes slāņiem, kuriem ir ģeometrijas veids laukums.",
  "selectOperationalLayerLabel": "Atlasiet rezultātu darbības slāni",
  "lineOfSightTabTitle": "Tiešās redzamības līnija",
  "symbologyTabTitle": "Simbolizācija",
  "transparency": "Caurspīdīgums",
  "outline": "Kontūra",
  "fill": "Aizpildījums (krāsa tiek lietota tikai tad, ja iestatīts tīrtoņa stils)",
  "style": "Stils",
  "selectOpLayerLabel": "Atlasiet rezultātu darbības slāni",
  "selectDefaultMeasurementLabel": "Atlasiet noklusējuma mērvienību",
  "visibleSectionLabel": "Redzamā daļa",
  "nonVisibleSectionLabel": "Neredzamā daļa",
  "visibleSectionButtonLabel": "Konfigurēt redzamās daļas iestatījumus",
  "nonVisibleSectionButtonLabel": "Konfigurēt neredzamās daļas iestatījumus",
  "colorPicker": "Krāsu atlasītājs",
  "lineStyles": {
    "esriSLSDash": "Svītra",
    "esriSLSDashDot": "Svītra punkts",
    "esriSLSDashDotDot": "Svītra punkts punkts",
    "esriSLSDot": "Punkts",
    "esriSLSLongDash": "Gara svītra",
    "esriSLSLongDashDot": "Gara svītra punkts",
    "esriSLSNull": "Nulle",
    "esriSLSShortDash": "Īsa svītra",
    "esriSLSShortDashDot": "Īsa svītra punkts",
    "esriSLSShortDashDotDot": "Īsa svītra punkts punkts",
    "esriSLSShortDot": "Īsa svītra",
    "esriSLSSolid": "Tīrtoņa"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atpakaļvērsts",
    "esriSFSCross": "Krusts",
    "esriSFSDiagonalCross": "Diagonāls",
    "esriSFSForwardDiagonal": "Uz priekšu vērsts",
    "esriSFSHorizontal": "Horizontāls",
    "esriSFSNull": "Nulle",
    "esriSFSSolid": "Tīrtoņa",
    "esriSFSVertical": "Vertikāls"
  }
});