define({
  "id": "ID",
  "state": "V predvolenom nastavení sa súradnice zobrazia v aktuálnom súradnicovom systéme mapy. Ak chcete získať súradnice v iných súradnicových systémoch, musíte ich pridať a určiť príslušné geografické transformácie.",
  "outputUnit": "Výstupná jednotka",
  "wkid": "Výstupný kód WKID",
  "label": "Názov výstupného súradnicového systému",
  "transformationWkid": "WKID kód geografickej transformácie",
  "transformationLabel": "Popis transformácie",
  "transformForward": "Transformovať v priamom smere",
  "actions": "Akcie",
  "warning": "Vložte platný WKID kód súradnicového systému!",
  "tfWarning": "Vložte platný WKID kód transformácie geodetického dátumu!",
  "spinnerLabel": "Zaokrúhliť súradnice na: ",
  "eyeDecimalLabel": "Zaokrúhliť nadmorskú výšku náhľadu: ",
  "decimalPlace": "desatinné miesta",
  "separator": "Zobraziť oddeľovač tisícov",
  "getVersionError": "Nie je možné získať verziu geometrickej služby",
  "add": "Pridať výstupný súradnicový systém",
  "edit": "Upraviť súradnicový systém",
  "output": "Výstupný súradnicový systém",
  "cName": "Názov súradnicového systému",
  "units": "Zobrazovacie jednotky: ",
  "datum": "Transformácia geodetického dátumu",
  "tName": "Názov geografickej transformácie",
  "tWKIDPlaceHolder": "WKID kód geografickej transformácie",
  "forward": "Použiť transformáciu v priamom smere",
  "ok": "OK",
  "cancel": "Zrušiť",
  "olderVersion": "Služba geometrie nepodporuje operáciu transformácie",
  "REPEATING_ERROR": " Súradnicový systém existuje vo výstupom zozname.",
  "Default": "Predvolené",
  "Inches": "Palce",
  "Foot": "Stopy",
  "Yards": "Yardy",
  "Miles": "Míle",
  "Nautical_Miles": "Námorné míle",
  "Millimeters": "Milimetre",
  "Centimeters": "Centimetre",
  "Meter": "Metre",
  "Kilometers": "Kilometre",
  "Decimeters": "Decimetre",
  "Decimal_Degrees": "Desatinné stupne",
  "Degree_Minutes_Seconds": "Stupne minúty sekundy",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Poradie zobrazenia súradníc",
  "lonLatTips": "Zemepisná dĺžka / Zemepisná šírka (X,Y)",
  "latLonTips": "Zemepisná šírka / Zemepisná dĺžka (Y,X)",
  "eyeAltUnit": "Jednotka výšky náhľadu:",
  "elevationUnit": "Jednotka nadmorskej výšky:",
  "english": "anglická",
  "metric": "metrická"
});