define({
  "_widgetLabel": "Toplu Öznitelik Düzenleyici",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Katman Adı",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Yapılandırılmış düzenlenebilir katman yok",
  "editorPopupTitle": "Toplu Öznitelik Düzenleyici",
  "editorPopupSaveBtn": "Kaydet",
  "editorPopupMultipleValues": "",
  "clear": "Temizle",
  "featuresUpdated": "${0} / ${1} detay güncellendi",
  "featuresSelected": "${0} detay seçildi",
  "featuresSkipped": "Atlandı",
  "featuresNoPermision": "${0} detay seçildi ancak düzenleme izni yok.",
  "search": "Ara",
  "queryInput": "Sorgulanacak değer girin",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Filtreyi düzgün şekilde ayarlayın.",
  "filterPopup": "Katmanı Filtrele",
  "filterAppend": "Bu katman için web haritasında bir filtre zaten mevcutsa",
  "filterAppendOR": "Herhangi bir ifadeyi mevcut harita filtresine ekle",
  "filterAppendAND": "Tüm ifadeleri mevcut harita filtresine ekle",
  "cancel": "İptal",
  "noValue": "Değer Yok",
  "emptyString": "Boş Dize",
  "existingValue": "Mevcut Veriyi Tut",
  "newDate": "Yeni Tarih",
  "valueChooser": "Bir Değer Seçin/Yazın",
  "ok": "Tamam",
  "drawBox": {
    "point": "Nokta",
    "line": "Çizgi",
    "polyline": "Çoklu çizgi",
    "freehandPolyline": "Serbest Çizim Çoklu Çizgi",
    "extent": "Yayılım",
    "polygon": "Poligon",
    "freehandPolygon": "Serbest Çizim Alan",
    "clear": "Temizle",
    "addPointToolTip": "Bu alanda seçim yapmak için tıklayın",
    "addShapeToolTip": "Detay seçmek için şekil çizin",
    "freehandToolTip": "Detay seçmek üzere şekil çizmek için basın ve basılı tutun",
    "startToolTip": "Detay seçmek için şekil çizin"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "${0} detayı geçersiz bir kimlik döndürdü",
    "noSelectedLayers": "Güncellenecek kayıt içeren seçili katman yok",
    "inputValueError": "Formda geçersiz değer var",
    "saveError": "${0} detayları kaydedilemedi",
    "requiredValue": "Gerekli Değer"
  }
});