define({
  "_widgetLabel": "Smart-redigering",
  "_featureAction_SmartEditor": "Smart-redigering",
  "noEditPrivileges": "Din konto har ikke rettigheder til at oprette eller redigere data.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Ikke aktiv",
  "pressStr": "Tryk ",
  "ctrlStr": " CTRL ",
  "snapStr": " for at aktivere snapping",
  "noAvailableTempaltes": "Ingen tilgængelige skabeloner",
  "editorCache": " - Editor-cache",
  "presetFieldAlias": "Mark",
  "presetValue": "Foruddefineret værdi",
  "usePresetValues": " Brug foruddefinerede værdier (kun for nye objekter)",
  "editGeometry": " Redigér geometri",
  "savePromptTitle": "Gem objekt",
  "savePrompt": "Vil du gemme det aktuelle objekt?",
  "deletePromptTitle": "Slet objekt",
  "deleteAttachment": "Slet vedhæftning",
  "deletePrompt": "Er du sikker på, at du vil slette det valgte objekt?",
  "attachmentLoadingError": "Fejl ved overførsel af vedhæftninger",
  "attachmentSaveDeleteWarning": "Advarsel: Ændringer i vedhæftninger gemmes automatisk",
  "autoSaveEdits": "Gem nye objekter automatisk",
  "addNewFeature": "Opret et nyt objekt",
  "featureCreationFailedMsg": "Kan ikke oprette en ny post/et nyt objekt",
  "relatedItemTitle": "Tilknyttede tabeller/lag",
  "relatedFeatureCount": "${layerTitle} med ${featureCount} objekter",
  "createNewFeatureLabel": "Opret et nyt objekt for ${layerTitle}",
  "invalidRelationShipMsg": "Kontrollér, at det primære nøglefelt: '${parentKeyField}' har en gyldig værdi",
  "pendingFeatureSaveMsg": "Gem ændringerne i objektet, før du opretter et tilknyttet objekt.",
  "attachmentsRequiredMsg": "(*) Vedhæftninger er påkrævet.",
  "coordinatePopupTitle": "Flyt objekt til XY-placering",
  "coordinatesSelectTitle": "Koordinatsystem:",
  "mapSpecialReferenceDropdownOption": "Kort-spatial reference",
  "latLongDropdownOption": "Breddegrad/længdegrad",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Koordinat:",
  "xAttributeTextBoxLabel": "X-koordinat:",
  "yAttributeTextBoxLabel": "Y-koordinat:",
  "latitudeTextBoxLabel": "Bredde:",
  "longitudeTextBoxLabel": "Længde:",
  "presetGroupFieldsLabel": "'${groupName}' anvendes på følgende lagfelter:",
  "presetGroupNoFieldsLabel": "'${groupName}' har ikke nogen tilknyttede felter",
  "groupInfoLabel": "Gruppeoplysninger for '${groupName}'",
  "editGroupInfoIcon": "Rediger gruppeværdi for ${groupName}",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Ingen tilgængelige skabeloner",
    "searchTemplates": "Søgeskabeloner",
    "filterLayerLabel": "Filtrér lag"
  },
  "invalidConfiguration": "Widget'en er enten ikke konfigureret, eller lagene i konfigurationen findes ikke længere i kortet. Åbn app'en i builder-tilstand, og omkonfigurér widget'en.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente geometritjeneste-URL",
  "clearSelection": "Luk",
  "refreshAttributes": "Opdatér dynamiske objektattributter",
  "automaticAttributeUpdatesOn": "Automatisk opdatering af objekters attributter: TIL",
  "automaticAttributeUpdatesOff": "Automatisk opdatering af objekters attributter: FRA",
  "moveSelectedFeatureToGPS": "Flyt det valgte objekt til den aktuelle GPS-placering",
  "moveSelectedFeatureToXY": "Flyt det valgte objekt til XY-placering",
  "mapNavigationLocked": "Kortnavigation: låst",
  "mapNavigationUnLocked": "Kortnavigation: ulåst",
  "copyFeatures": {
    "title": "Kopiér objekter",
    "createFeatures": "Opret objekter",
    "createSingleFeature": "Opret 1 Multigeometri-objekt",
    "noFeaturesSelectedMessage": "Ingen funktioner valgt",
    "selectFeatureToCopyMessage": "Vælg de objekter, der skal kopieres.",
    "multipleFeatureSaveWarning": "Bemærk: Hvis du opretter flere objekter ved at kopiere dem, gemmes alle objekterne med det samme.",
    "copyFeatureUpdateGeometryError": "Kan ikke opdatere geometri for valgte objekter.",
    "canNotSaveMultipleFeatureWarning": "Bemærk: Kan ikke kopiere flere objekter ved hjælp af den samme værdi for unikke værdifelter, vælg kun ét objekt",
    "createOnlyOneMultipartFeatureWarning": "Bemærk: Der kan kun oprettes et multipart-objekt"
  },
  "addingFeatureError": "Fejl under tilføjelse af valgte objekter i laget. Prøv igen.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' objekter kunne ikke kopieres.",
  "selectingFeatureError": "Fejl under valg af objekter i laget. Prøv igen.",
  "customSelectOptionLabel": "Vælg objekter, der skal kopieres",
  "noFeatureSelectedMessage": "Ingen funktioner valgt.",
  "multipleFeatureSaveMessage": "Alle objekterne vil blive gemt med det samme. Vil du fortsætte?",
  "relativeDates": {
    "dateTypeLabel": "Datotype",
    "valueLabel": "Værdi",
    "fixed": "Fast",
    "current": "Aktuelt",
    "past": "Tidligere",
    "future": "Fremtidig",
    "popupTitle": "Vælg værdi",
    "hintForFixedDateType": "Tip: Den angivne dato og det angivne klokkeslæt bruges som forudindstillet standardværdi.",
    "hintForCurrentDateType": "Tip: Den aktuelle dato og det aktuelle klokkeslæt bruges som forudindstillet standardværdi.",
    "hintForPastDateType": "Tip: Den angivne værdi trækkes fra den aktuelle dato og det aktuelle klokkeslæt for at give standardværdien for forudindstilling.",
    "hintForFutureDateType": "Tip: Den angivne værdi lægges til den aktuelle dato og det aktuelle klokkeslæt for at give standardværdien for forudindstilling.",
    "noDateDefinedTooltip": "Ingen dato er defineret",
    "relativeDateWarning": "Der skal angives en værdi for dato eller klokkeslæt for at gemme den forudindstillede standardværdi.",
    "customLabel": "Brugerdefineret",
    "layerLabel": "Lag",
    "domainFieldHintLabel": "Den valgte værdi er et coded value-domæne. Værdien: ${domainValue} vil blive anvendt"
  },
  "valuePicker": {
    "popupTitle": "Vælg værdi",
    "popupHint": "Det aktuelle objekt skærer flere objekter, vælg værdi for det respektive felt",
    "buttonTooltip": "Vælg værdi fra flere objekter, der skærer hinanden"
  },
  "uniqueValueErrorMessage": "Værdien i \"${fieldName}\" findes allerede, angiv en ny værdi.",
  "requiredFields": {
    "displayMsg": "Obligatoriske felter kan ikke være tomme. Angiv værdier for almindelige felter nedenfor.",
    "popupTittle": "Krævede felter",
    "foundNullRecordCount": "${fieldName} (fundet i ${count} poster)"
  },
  "cantLocateUserLocation": "Din position kunne ikke fastslås"
});