define({
  "_widgetLabel": "Умный редактор",
  "_featureAction_SmartEditor": "Умный редактор",
  "noEditPrivileges": "У вашей учетной записи нет прав на создание или изменение данных.",
  "widgetActive": "Активный",
  "widgetNotActive": "Неактивно",
  "pressStr": "Нажмите ",
  "ctrlStr": " CTRL ",
  "snapStr": " чтобы включить замыкание",
  "noAvailableTempaltes": "Нет доступных шаблонов",
  "editorCache": " – Кэш редактора",
  "presetFieldAlias": "Поле",
  "presetValue": "Заданное значение",
  "usePresetValues": " Использовать заданные ранее значения (только новые объекты)",
  "editGeometry": " Редактировать геометрию",
  "savePromptTitle": "Сохранить объект",
  "savePrompt": "Вы хотите сохранить текущий объект?",
  "deletePromptTitle": "Удалить объект",
  "deleteAttachment": "Удалить вложение",
  "deletePrompt": "Действительно удалить выбранный объект?",
  "attachmentLoadingError": "Ошибка загрузки вложений",
  "attachmentSaveDeleteWarning": "Внимание: изменения вложений сохраняются автоматически",
  "autoSaveEdits": "Сохранить новые объекты автоматически",
  "addNewFeature": "Создать новый объект",
  "featureCreationFailedMsg": "Невозможно создать новую запись/объект",
  "relatedItemTitle": "Связанная таблица/слой",
  "relatedFeatureCount": "${layerTitle} с ${featureCount} объектами",
  "createNewFeatureLabel": "Создать новый объект для ${layerTitle}",
  "invalidRelationShipMsg": "Проверьте, что поле первичного ключа: '${parentKeyField}' имеет корректное значение",
  "pendingFeatureSaveMsg": "Сохраните изменения объекта для создания связанного объекта.",
  "attachmentsRequiredMsg": "(*) Необходимы вложения.",
  "coordinatePopupTitle": "Переместить объект в местоположение XY",
  "coordinatesSelectTitle": "Система координат:",
  "mapSpecialReferenceDropdownOption": "Пространственная привязка карты",
  "latLongDropdownOption": "Широта/Долгота",
  "mgrsDropdownOption": "Военная система прямоугольных координат (MGRS)",
  "mgrsTextBoxLabel": "Координата:",
  "xAttributeTextBoxLabel": "X-координата:",
  "yAttributeTextBoxLabel": "Y-координата:",
  "latitudeTextBoxLabel": "Широта:",
  "longitudeTextBoxLabel": "Долгота:",
  "presetGroupFieldsLabel": "'${groupName}' будет применено к следующим полям слоя:",
  "presetGroupNoFieldsLabel": "'${groupName}' не содержит связанных полей",
  "groupInfoLabel": "Информация по группе '${groupName}'",
  "editGroupInfoIcon": "Изменить значение группы ${groupName}",
  "filterEditor": {
    "all": "Все",
    "noAvailableTempaltes": "Нет доступных шаблонов",
    "searchTemplates": "Поиск шаблонов",
    "filterLayerLabel": "Отобрать слои"
  },
  "invalidConfiguration": "Виджет не настроен, или на карте больше нет слоёв из конфигурации. Откройте приложение в режиме конструктора и настройте виджет.",
  "geometryServiceURLNotFoundMSG": "Невозможно получить URL сервиса геометрии",
  "clearSelection": "Закрыть",
  "refreshAttributes": "Динамически обновлять атрибуты объектов",
  "automaticAttributeUpdatesOn": "Автоматически обновлять атрибуты объекта: ВКЛ",
  "automaticAttributeUpdatesOff": "Автоматически обновлять атрибуты объекта: ВЫКЛ",
  "moveSelectedFeatureToGPS": "Переместить выбранный объект в текущее местоположение GPS",
  "moveSelectedFeatureToXY": "Переместить выбранный объект в местоположение XY",
  "mapNavigationLocked": "Навигация по карте: Блокирована",
  "mapNavigationUnLocked": "Навигация по карте: Разблокирована",
  "copyFeatures": {
    "title": "Копировать объекты",
    "createFeatures": "Создать объекты",
    "createSingleFeature": "Создать 1 объект множественной геометрии",
    "noFeaturesSelectedMessage": "Объекты не выбраны",
    "selectFeatureToCopyMessage": "Выберите объект для копирования.",
    "multipleFeatureSaveWarning": "Примечание: создание нескольких объектов с помощью копирования приведет к немедленному сохранению всех объектов",
    "copyFeatureUpdateGeometryError": "Не удалось обновить геометрию выбранных объектов",
    "canNotSaveMultipleFeatureWarning": "Примечание: Не удалось скопировать несколько объектов, используя то же значение для полей уникальных значений; выберите только один объект",
    "createOnlyOneMultipartFeatureWarning": "Примечание: Можно сделать только один составной объект"
  },
  "addingFeatureError": "Ошибка при добавлении выбранных объектов в слое. Повторите попытку еще раз.",
  "addingFeatureErrorCount": "Не удалось скопировать объектов: '${copyFeatureErrorCount}'",
  "selectingFeatureError": "Ошибка при выборке объектов в слое. Повторите попытку еще раз.",
  "customSelectOptionLabel": "Выбрать объекты для копирования",
  "noFeatureSelectedMessage": "Объекты не выбраны.",
  "multipleFeatureSaveMessage": "Все объекты будут сразу же сохранены. Хотите продолжить?",
  "relativeDates": {
    "dateTypeLabel": "Тип даты",
    "valueLabel": "Значение",
    "fixed": "Фиксированный",
    "current": "Текущий",
    "past": "Прошедшие",
    "future": "Будущее",
    "popupTitle": "Выберите значение",
    "hintForFixedDateType": "Подсказка: указанные время и дата будут использованы как значения по умолчанию.",
    "hintForCurrentDateType": "Подсказка: текущие время и дата будут использованы как значения по умолчанию.",
    "hintForPastDateType": "Подсказка: указанное значение будет вычтено из текущего времени и даты для задания значения по умолчанию.",
    "hintForFutureDateType": "Подсказка: указанное значение будет добавлено к текущему времени и дате для задания значения по умолчанию.",
    "noDateDefinedTooltip": "Дата не задана",
    "relativeDateWarning": "Для сохранения заданного значения по умолчанию необходимо указать значение даты или времени.",
    "customLabel": "Пользовательский",
    "layerLabel": "Слой",
    "domainFieldHintLabel": "Выбранное значение принадлежит домену кодированных значений Будет использовано значение: ${domainValue}"
  },
  "valuePicker": {
    "popupTitle": "Выберите значение",
    "popupHint": "Текущий объект пересекается с несколькими объектами, выберите значение для соответствующего поля",
    "buttonTooltip": "Выберите значение из нескольких пересекающихся объектов"
  },
  "uniqueValueErrorMessage": "Значение в \"${fieldName}\" уже существует, введите новое значение.",
  "requiredFields": {
    "displayMsg": "Обязательные поля не могут быть пустыми. Укажите значения для общих полей ниже",
    "popupTittle": "Обязательные поля",
    "foundNullRecordCount": "${fieldName} (Найдено в ${count} записях)"
  },
  "cantLocateUserLocation": "Ваше местоположение невозможно определить"
});