define({
  "_widgetLabel": "Množični urejevalnik atributov",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Ime sloja",
    "numSelected": "št.",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Uredljivi sloji niso konfigurirani",
  "editorPopupTitle": "Množični urejevalnik atributov",
  "editorPopupSaveBtn": "Shrani",
  "editorPopupMultipleValues": "",
  "clear": "Počisti",
  "featuresUpdated": "Posodobljenih je ${0}/${1} geoobjektov",
  "featuresSelected": "Izbranih je ${0} geoobjektov",
  "featuresSkipped": "Zaobideno",
  "featuresNoPermision": "${0} geoobjektov je izbranih, ampak ni dovoljenja za urejanje.",
  "search": "Iskanje",
  "queryInput": "Vnesite vrednost za poizvedbo",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Pravilno nastavite filter.",
  "filterPopup": "Filtriraj sloj",
  "filterAppend": "Če filter že obstaja v spletni karti za ta sloj",
  "filterAppendOR": "Dodaj kateri koli izraz obstoječemu filtru karte",
  "filterAppendAND": "Dodaj vse izraze obstoječemu filtru karte",
  "cancel": "Prekliči",
  "noValue": "Ni vrednosti",
  "emptyString": "Prazen niz",
  "existingValue": "Obdrži obstoječo vrednost",
  "newDate": "Nov datum",
  "valueChooser": "Izberi/vpiši vrednost",
  "ok": "V redu",
  "drawBox": {
    "point": "Točka",
    "line": "Linija",
    "polyline": "Polilinija",
    "freehandPolyline": "Prostoročna polilinija",
    "extent": "Pravokotnik",
    "polygon": "Poligon",
    "freehandPolygon": "Prostoročni poligon",
    "clear": "Počisti",
    "addPointToolTip": "Kliknite, da počistite to območje",
    "addShapeToolTip": "Narišite obliko za izbiro geoobjektov",
    "freehandToolTip": "Pritisnite in držite za risanje oblike za izbiro geoobjektov",
    "startToolTip": "Narišite obliko za izbiro geoobjektov"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Geoobjekt iz ${0} je vrnil neveljaven ID",
    "noSelectedLayers": "Ni izbranih slojev z zapisi za posodabljanje",
    "inputValueError": "Neveljavna vrednost v obrazcu",
    "saveError": "Ni mogoče shraniti ${0} geoobjektov",
    "requiredValue": "Zahtevana vrednost"
  }
});