define({
  "_widgetLabel": "資料匯聚",
  "startPage": {
    "defaultStartPageInstructions": "此 widget 將協助處理檔案的資料，並將該資料提交到地圖的選定圖層。<br/> <br/> 必須以逗號、頁籤、分號或垂直列分隔檔案中的值。",
    "dragDrop": "拖放",
    "browse": "瀏覽到檔案",
    "or": "OR",
    "userPrivilege": "您的帳號沒有建立或修改資料的權限。",
    "userCredits": "${widgetName} 需要點數才能使用 ${locator} 定位器。",
    "contactAdmin": "請聯絡組織的管理員以要求其他點數。",
    "contactAdminEdit": "請聯絡組織的管理員以請求編輯權限。",
    "canUseLocator": "${locator} 定位器將用來定位圖徵。",
    "notEnoughCredits": "點數不足。",
    "locationAndField": "位置和欄位資訊",
    "locationAndFieldHint": "從必須用來更新目標圖層的檔案中選擇值。",
    "cannotUseLocator": "無法使用 ${widgetName}",
    "noAnonymousEdit": "${layerName} 圖層不支援匿名編輯。",
    "pleaseLogin": "登入 ${org} 組織或聯絡組織的管理員以請求啟用匿名編輯。",
    "invalidEdit": "權限無效",
    "unableToAccess": "無法存取 ${layerName}",
    "appropriateCredentials": "確認您已使用適當的憑證登入。",
    "shared": "聯絡組織的管理員以申請 ${layerName} 圖層的存取權。",
    "targetLayerLabel": "目標圖層",
    "homeButtonLabel": "首頁",
    "mappingErrorMsg": "按一下旁邊的箭頭以定義欄位"
  },
  "mapping": {
    "schemaMapping": "欄位資訊",
    "schemaMappingHint": "從檔案中選擇與圖層中欄位相關的欄位。",
    "locationMapping": "位置資訊",
    "locationMappingHint": "選擇預期從檔案取得的地址或座標資訊的類型。"
  },
  "locationMapping": {
    "locationMappingPageHint": "選擇位置類型",
    "useAddress": "使用地址定位",
    "useAddressHint": "資料包含地址資訊",
    "useCoordinates": "使用座標定位",
    "useCoordinatesHint": "資料包含 X/Y 座標值"
  },
  "address": {
    "addressPageHint": "選擇地址類型",
    "singleField": "單一欄位",
    "singleFieldHint": "選擇包含地址資訊的欄位",
    "multiField": "多個欄位",
    "multiFieldHint": "選擇包含地址資訊的欄位"
  },
  "coordinates": {
    "coordinatesPageHint": "選擇包含座標資料的欄位"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "選擇對應到目標欄位的來源欄位",
    "sourceField": "入對來源欄位",
    "targetField": "目標欄位"
  },
  "buttons": {
    "addToMap": "新增到地圖",
    "submit": "提交",
    "download": "下載"
  },
  "review": {
    "matched": "發現",
    "reviewMatched": "發現位置",
    "reviewMatchedHint": "檢閱找到的位置。",
    "unMatched": "找不到",
    "reviewUnMatched": "找不到位置",
    "reviewUnMatchedHint": "檢閱找不到的位置。 不會提交未更正的項目。",
    "duplicate": "重複",
    "reviewDuplicate": "重複位置",
    "reviewDuplicateHint": "檢閱已在圖層中找到的位置。 不會提交未定址的項目。",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "使用:",
    "fromLayer": "目標資訊",
    "target": "目標",
    "source": "來源",
    "fromFile": "來源資訊",
    "locationControlHint": "檢閱地址資訊",
    "duplicateAction": "選擇動作",
    "item": "記錄:",
    "locateFeature": "定位圖徵",
    "removeFeature": "移除圖徵",
    "featureLocated": "找到位置",
    "valuesDoNotMatch": "不符合現有值",
    "sync": "使用欄位資訊來同步地址資訊",
    "noFeaturesSaved": "未成功儲存任何圖徵",
    "someFeaturesSaved": "已成功儲存 ${num} 個圖徵。",
    "someFeaturesNotSaved": "未成功儲存 ${num} 個圖徵。",
    "feature": "檢閱圖徵資訊",
    "locationInfo": "檢閱位置資訊",
    "selectValue": "選擇值",
    "reviewData": "檢閱資料",
    "reviewDataHint": "先檢閱您的資料再提交到圖層。",
    "reviewFeatureHint": "檢閱或編輯您的圖徵和位置資訊。",
    "duplicateModify": "重複，需要變更",
    "duplicateSave": "另存為新圖徵"
  },
  "warningsAndErrors": {
    "invalidCSV": "從 CSV 擷取項目時發生錯誤，請檢查是否選取有效的 CSV 檔案。",
    "noLayersWarning": "未配置有效的目標圖層，請檢查配置。",
    "loadWarning": "此 widget 需要圖徵服務資料來源。 請配置 widget 來定義資料來源。",
    "saveError": "儲存圖徵時出錯。",
    "consumesCredits": "使用 ArcGIS Online 世界地理編碼服務時，此工具會耗用點數",
    "noValue": "選擇欄位",
    "mappingTitle": "",
    "locationMappingComplete": "位置製圖完成",
    "fieldMappingComplete": "現場製圖完成",
    "settingsCleared": "將清除設定。",
    "proceed": "是否要繼續?",
    "itemMoveMatch": "會尋找項目並將其移到「找到位置」清單",
    "itemMoveUnMatched": "無法找到項目。 移至「找不到位置」清單。",
    "itemWillBeLocated": "將從「重複位置」清單中移除項目。",
    "cannotLocate": "無法找到項目。 確認位置資訊。",
    "invalidMessage": "無效值。",
    "rangeMessage": "值必須少於 ${num} 個字元。",
    "locatorError": "定位器無效或無法存取。",
    "notConfigured": "未針對目前定位選項配置定位器",
    "noMoreLocators": "未配置其他定位器"
  },
  "featureToolbar": {
    "locate": "定位",
    "save": "儲存記錄",
    "cancel": "取消編輯",
    "cancelTitle": "取消編輯",
    "cancelMessage": "取消目前記錄的編輯?"
  }
});