define({
  "_widgetLabel": "Editor intel·ligent",
  "_featureAction_SmartEditor": "Editor intel·ligent",
  "noEditPrivileges": "El vostre compte no té permís per crear o modificar dades.",
  "loginPopupTitle": "Inicia la sessió",
  "loginPopupMessage": "${widgetName} necessita permisos i crèdits per cercar i emmagatzemar informació de les adreces Voleu iniciar sessió i utilitzar aquesta capacitat?",
  "noCreditsOrPrivilegeWarningMessage": "El vostre compte no té permisos i crèdits per cercar i emmagatzemar informació de les adreces amb ${widgetName}. Poseu-vos en contacte amb l'administrador de l'organització per sol·licitar permisos i crèdits.",
  "unableToUseLocator": "No es pot accedir al localitzador. No es duran a terme les accions dels atributs d'adreça.",
  "locatorDisabledWaning": "El localitzador no està habilitat. Poseu-vos en contacte amb l'administrador de l'organització per sol·licitar aquesta capacitat.",
  "noFeatureInAIWarning": "No hi ha cap entitat seleccionada. Seleccioneu una entitat per fer canvis o feu clic a Cancel·la per tornar a la pantalla principal.",
  "noEditableLayerWarning": "El vostre compte no té cap permís per crear ni modificar dades, o aquest mapa web no conté cap capa editable.",
  "noVisibleCreateLayerWarning": "Les capes no estan visibles al nivell de zoom actual. Amplieu o allunyeu per crear o modificar entitats.",
  "noVisibleUpdateLayerWarning": "Les capes no estan visibles al nivell de zoom actual. Amplieu o allunyeu per modificar entitats.",
  "checkLayerVisibilityInWebMapWarning": "Assegureu-vos que les capes estiguin visibles al mapa per crear o modificar entitats.",
  "showSelectionInAITitle": "Entidades seleccionadas",
  "showSelectionInAIMsg": "Voleu carregar la selecció actual a ${widgetName}?",
  "widgetActive": "Activa",
  "widgetNotActive": "Inactiva",
  "pressStr": "Premeu ",
  "ctrlStr": " CTRL ",
  "snapStr": " per habilitar l'ajust",
  "noAvailableTempaltes": "No hi ha plantilles disponibles",
  "editorCache": " - Memòria cau de l'editor",
  "presetFieldAlias": "Camp",
  "presetValue": "Valor predefinit",
  "usePresetValues": " Utilitza valors predefinits (només noves entitats)",
  "editGeometry": " Edita la geometria",
  "savePromptTitle": "Desa l'entitat",
  "savePrompt": "Voleu desar l'entitat actual?",
  "deletePromptTitle": "Suprimeix l'entitat",
  "deleteAttachment": "Suprimeix el fitxer adjunt",
  "deletePrompt": "Segur que voleu suprimir l'entitat seleccionada?",
  "attachmentLoadingError": "Error en pujar fitxers adjunts",
  "attachmentSaveDeleteWarning": "Avís: els canvis realitzats als fitxers adjunts es desen automàticament",
  "autoSaveEdits": "Desa les entitats noves automàticament",
  "addNewFeature": "Crea una entitat nova",
  "featureCreationFailedMsg": "No es pot crear un nou registre o entitat",
  "relatedItemTitle": "Taula o capa relacionada",
  "relatedFeatureCount": "Capa ${layerTitle} amb ${featureCount} entitats",
  "createNewFeatureLabel": "Crea una entitat nova per a la capa ${layerTitle}",
  "invalidRelationShipMsg": "Assegureu-vos que el camp de la clau principal: '${parentKeyField}' tingui un valor vàlid",
  "pendingFeatureSaveMsg": "Deseu les edicions de les entitats abans de crear una entitat relacionada.",
  "attachmentsRequiredMsg": "(*) Els fitxers adjunts són necessaris.",
  "coordinatePopupTitle": "Mou l'entitat a la ubicació XY",
  "coordinatesSelectTitle": "Sistema de coordenades:",
  "mapSpecialReferenceDropdownOption": "Referència espacial del mapa",
  "latLongDropdownOption": "Latitud/longitud",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Coordinada:",
  "xAttributeTextBoxLabel": "Coordenada X:",
  "yAttributeTextBoxLabel": "Coordenada Y:",
  "latitudeTextBoxLabel": "Latitud:",
  "longitudeTextBoxLabel": "Longitud:",
  "presetGroupFieldsLabel": "El grup \"${groupName}\" s'aplicarà als camps de la capa següents:",
  "presetGroupNoFieldsLabel": "El grup \"${groupName}\" no té cap camp associat",
  "groupInfoLabel": "Informació del grup \"${groupName}\"",
  "editGroupInfoIcon": "Edita el valor del grup ${groupName}",
  "filterEditor": {
    "all": "Totes",
    "noAvailableTempaltes": "No hi ha plantilles disponibles",
    "searchTemplates": "Cerca plantilles",
    "filterLayerLabel": "Filtra les capes"
  },
  "invalidConfiguration": "El widget no està configurat o les capes de la configuració ja no es troben al mapa. Obriu l'aplicació en el mode del builder i torneu a configurar el widget.",
  "geometryServiceURLNotFoundMSG": "No es pot obtenir l'adreça URL del servei de geometria",
  "clearSelection": "Tanca",
  "refreshAttributes": "Actualitza els atributs d'entitats dinàmics",
  "automaticAttributeUpdatesOn": "Actualitza els atributs d'entitats automàticament: ON",
  "automaticAttributeUpdatesOff": "Actualitza els atributs d'entitats automàticament: OFF",
  "moveSelectedFeatureToGPS": "Mou l'entitat seleccionada a la ubicació GPS actual",
  "moveSelectedFeatureToXY": "Mou l'entitat seleccionada a la ubicació XY",
  "mapNavigationLocked": "Navegació pel mapa: bloquejada",
  "mapNavigationUnLocked": "Navegació pel mapa: desbloquejada",
  "copyFeatures": {
    "title": "Copia les entitats",
    "createFeatures": "Crea les entitats",
    "createSingleFeature": "Crea 1 entitat de diverses parts",
    "createOneSingleFeature": "Crear entidad",
    "noFeaturesSelectedMessage": "No s'ha seleccionat cap entitat",
    "selectFeatureToCopyMessage": "Seleccioneu les entitats que voleu copiar",
    "multipleFeatureSaveWarning": "Nota: si es creen diverses entitats amb la funció de còpia, totes les entitats noves es desaran immediatament",
    "copyFeatureUpdateGeometryError": "No es pot actualitzar la geometria de les entitats seleccionades",
    "canNotSaveMultipleFeatureWarning": "Nota: no es poden copiar múltiples característiques utilitzant el mateix valor per a camps de valor únic; seleccioneu només una característica",
    "createOnlyOneMultipartFeatureWarning": "Nota: només es pot crear una característica multipart"
  },
  "addingFeatureError": "Error en afegir les entitats seleccionades a la capa. Torneu-ho a provar.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' entitats no s'han pogut copiar. Voleu tornar a provar-ho per a les entitats que falten?",
  "selectingFeatureError": "Error en seleccionar entitats a la capa. Torneu-ho a provar.",
  "customSelectOptionLabel": "Seleccioneu les entitats que voleu copiar",
  "noFeatureSelectedMessage": "No s'ha seleccionat cap entitat",
  "multipleFeatureSaveMessage": "Totes les entitats es desaran immediatament. Voleu continuar?",
  "relativeDates": {
    "dateTypeLabel": "Tipus de data",
    "valueLabel": "Valor",
    "fixed": "Fix",
    "current": "Actual",
    "past": "Passat",
    "future": "Futur",
    "popupTitle": "Seleccioneu un valor",
    "hintForFixedDateType": "Suggeriment: la data i l'hora especificades s'utilitzaran com a valor per defecte predefinit.",
    "hintForCurrentDateType": "Suggeriment: la data i l'hora actuals s'utilitzaran com a valor per defecte predefinit.",
    "hintForPastDateType": "Suggeriment: el valor especificat es restarà de la data i hora actuals per obtenir el valor per defecte predefinit.",
    "hintForFutureDateType": "Suggeriment: el valor especificat s'afegirà a la data i hora actuals per obtenir el valor per defecte predefinit.",
    "noDateDefinedTooltip": "No s'ha definit cap data",
    "relativeDateWarning": "S'ha d'especificar un valor de data o hora per poder desar el valor predefinit per defecte.",
    "customLabel": "Personalitzat",
    "layerLabel": "Capa",
    "domainFieldHintLabel": "El valor seleccionat és un domini de valor codificat. Es farà servir el valor \"${domainValue}\""
  },
  "valuePicker": {
    "popupTitle": "Seleccioneu un valor",
    "popupHint": "L'entitat actual s'interseca amb diverses entitats, trieu un valor per al camp corresponent",
    "buttonTooltip": "Seleccioneu un valor de diverses entitats que intersequen"
  },
  "uniqueValueErrorMessage": "El valor a \"${fieldName}\" ja existeix, proporcioneu-ne un de nou.",
  "requiredFields": {
    "displayMsg": "Els camps obligatoris no poden estar en blanc. Doneu valors per als camps comuns següents.",
    "popupTittle": "Camps necessaris",
    "foundNullRecordCount": "${fieldName} (s'ha trobat en ${count} registres)"
  },
  "cantLocateUserLocation": "No s’ha pogut determinar la vostra localització",
  "tryAgainButtonLabel": "Torna-ho a provar",
  "copyFeatureFailedPopupTitle": "S'ha"
});