define({
  "selectAnalysisTools": "Vyberte nástroje analýzy na použitie vo widgete.",
  "graphicalDisplay": "Grafické zobrazenie",
  "toolSetting": "Nastaviť podrobnosti nástroja",
  "toolLabel": "Zobrazovaný názov nástroja",
  "showHelpTip": "Zobraziť prepojenia na pomocníka vo widgete",
  "showCurrentMapExtent": "Zobraziť možnosti na použitie aktuálneho rozsahu mapy",
  "showCredits": "Zobrazenie<b>Ukázať možnosti</b> kreditov",
  "saveAsFeatureService": "Uložiť výsledok do konta používateľa",
  "showReadyToUseLayers": "Zobraziť vrstvy pripravené na použitie z ArcGIS Online Living Atlas",
  "toolNotAvailable": "Tento nástroj nie je k dispozícii, pretože mapa neobsahuje požadované vrstvy prvkov.",
  "aggregatePoints": "Agregované body",
  "aggregatePointsUsage": "Agregovať body do polygónov, kde sú umiestnené body.",
  "calculateDensity": "Vypočítať hustotu",
  "calculateDensityUsage": "Vytvorte mapu hustoty z prvkov bodov alebo čiar pomocou rozšírenia známych množstiev nejakého javu (predstavovaného ako atribúty bodov alebo čiar) naprieč mapou.",
  "connectOriginsToDestinations": "Spojiť počiatky s cieľmi",
  "connectOriginsToDestinationsUsage": "Merať čas cesty alebo vzdialenosť medzi pármi bodov.",
  "createBuffers": "Vytvoriť obalové zóny",
  "createBuffersUsage": "Vytvoriť polygóny obalových zón zo vstupných prvkov.",
  "createDriveTimeAreas": "Vytvoriť polygóny dojazdového času",
  "createDriveTimeAreasUsage": "Vytvoriť polygóny doby jazdy (alebo vzdialenosti jazdy) okolo vstupných bodov pre dané hodnoty doby jazdy.",
  "createViewshed": "Vytvoriť vrstvu viditeľnosti",
  "createViewshedUsage": "Vytvára oblasti, ktoré sú viditeľné na základe umiestnení, ktoré špecifikujete.",
  "createWatersheds": "Vytvoriť povodia",
  "createWatershedsUsage": "Vytvára oblasti povodia na základe umiestnení, ktoré špecifikujete.",
  "deriveNewLocations": "Odvodiť nové lokality",
  "deriveNewLocationsUsage": "Odvodzuje nové prvky zo vstupných vrstiev, ktoré spĺňajú zadané kritérium",
  "dissolveBoundaries": "Zrušiť vnútorné hranice",
  "dissolveBoundariesUsage": "Ruší polygóny, ktoré sa prekrývajú alebo zdieľajú spoločnú hranicu.",
  "enrichLayer": "Obohatiť vrstvu",
  "enrichLayerUsage": "Obohaťte vstupné prvky ľuďmi, miestami a obchodnými faktami o blízkych oblastiach.",
  "extractData": "Extrahovať dáta",
  "extractDataDesc": "Extrahujte údaje z jednej alebo viacerých vrstiev v rámci daného rozsahu",
  "findCentroids": "Nájsť centroidy",
  "findCentroidsUsage": "Nájde reprezentatívne centrum (centroid) pre každý vstupný bod, čiaru alebo polygón.",
  "findExistingLocations": "Nájsť existujúce lokality",
  "findExistingLocationsUsage": "Vyberte prvky vo vstupnej vrstve, ktoré spĺňajú zadaný atribút a/alebo priestorový dopyt",
  "findHotSpots": "Nájsť hotspoty",
  "findHotSpotsUsage": "Nájdite štatisticky významné zhluky vstupných prvkov alebo vysokých/nízkych hodnôt.",
  "findNearest": "Nájsť najbližší",
  "findNearestUsage": "Pre každý prvok na vstupnej vrstve nájdite jeho najbližší prvok na inej vrstve",
  "findPointClusters": "Nájsť zhluky bodov",
  "findPointClustersUsage": "Tento nástroj rozpoznáva oblasti, v ktorých sú body koncentrované a kde sú oddelené oblasťami, ktoré sú prázdne alebo riedke.",
  "findSimilarLocations": "Nájsť podobné lokality",
  "findSimilarLocationsUsage": "Zmerajte podobnosť potenciálnych umiestnení s jedným alebo viacerými referenčnými umiestneniami.",
  "geocodeLocations": "Geokódovať lokality z tabuľky",
  "geocodeLocationsUsage": "Pohodlný spôsob, ako geokódovať veľké tabuľky a súbory adries na body.",
  "interpolatePoints": "Interpolovať body",
  "interpolatePointsUsage": "Odhadujte hodnoty v nových umiestneniach na základe meraní zo súboru bodov.",
  "mergeLayers": "Zlúčiť vrstvy",
  "mergeLayersUsage": "Zlúčte prvky z viacerých vrstiev do novej vrstvy",
  "overlayLayers": "Prekryť vrstvy",
  "overlayLayersUsage": "Kombinujte viac vrstiev do jednej vrstvy s informáciami z pôvodných zachovaných vrstiev.",
  "planRoutes": "Plánovanie trás",
  "planRoutesUsage": "Určite, ako efektívne rozdeliť úlohy medzi pracovníkov v teréne.",
  "summarizeCenterAndDispersion": "Zhrnúť stredové hodnoty a rozptyl",
  "summarizeCenterAndDispersionUsage": "Použite bodové prvky na výpočet centrálneho prvku, geografického priemeru, geografického mediánu alebo distribučnej elipsy.",
  "summarizeNearby": "Zhrnúť okolité",
  "summarizeNearbyUsage": "Pre každý prvok vo vstupnej vrstve zhrňte údaje vo vzdialenosti od prvkov v inej vrstve.",
  "summarizeWithin": "Zhrnúť vo vnútri",
  "summarizeWithinUsage": "Pre každý polygón vo vstupnej polygónovej vrstve zhrňte údaje nachádzajúce sa v nej z prvkov na inej vrstve.",
  "traceDownstream": "Sledovať po prúde",
  "traceDownstreamUsage": "Určite dráhy toku v smere po prúde od umiestnení, ktoré určíte.",
  "allowToExport": "Povoliť export výsledkov",
  "joinFeatures": "Prepojiť prvky",
  "joinFeaturesUsage": "Nástroj Prepojiť prvky prevedie atribúty z jednej vrstvy alebo tabuľky do druhej na základe priestorových vzťahov a vzťahov atribútov. Štatistiku možno voliteľne vypočítať pre prepojené funkcie.",
  "includeRouteLayer": "Zahrnúť vrstvy trasy",
  "findOutliers": "Nájsť odľahlé prvky",
  "findOutliersUsage": "Nástroj Nájsť odľahlé prvky určí, či sa v priestorovom vzore vašich dát nachádzajú štatisticky významné odľahlé prvky."
});