define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Dostopajte do infografike in poročil, ki povzemajo ključne indikatorje in podatke za katero koli območje.</div><br><div>Izberite točko ali poligon na karti, poiščite naslov ali kraj, narišite poligon, ali spustite buciko za ogled ključnih indikatorjev in informacij o območju.</div>",
  "defineWhichInfographics": "Določite, katere infografike so na voljo v pripomočku:",
  "defineWhichReports": "Določite, katera poročila so na voljo v pripomočku:",
  "defaultValues": "Privzete vrednosti:",
  "disable": "Onemogoči",
  "drawFreehandPolygon": "Nariši prostoročni poligon",
  "drawPolygon": "Nariši poligon",
  "driveTime": "Čas vožnje",
  "dropPin": "Spusti buciko",
  "dynamicHTML": "Dinamični HTML",
  "exportOptions": "Možnosti izvoza:",
  "home": "Domov",
  "image": "Slika",
  "infographics": "Infografike",
  "invalidValueRing": "Vrednosti morajo biti v razponu od 0 do 1.000.",
  "invalidValueDTWT": "Vrednosti morajo biti v razponu od 0 do 300.",
  "km": "km",
  "makeDefault": "Naredi privzeto",
  "miles": "milje",
  "minutes": "minut",
  "options": "Možnosti:",
  "pdf": "PDF",
  "print": "Natisni",
  "radius": "Polmer",
  "removeDefault": "Odstrani privzeto",
  "reports": "Poročila",
  "rings": "Obroči",
  "searchTextBox": "Iskalno polje z besedilom",
  "selectCountryOrRegion": "Izberi državo ali regijo:",
  "thisEntryIsNotValid": "Vnos ni veljaven.",
  "time": "Čas",
  "walkTime": "Čas hoje"
});