define({
  "locatorUrl": "عنوان URL لمحدد المواقع",
  "set": "تعيين",
  "locatorName": "اسم محدد الموقع",
  "locatorExample": "مثال",
  "countryCode": "كود الدولة أو المنطقة",
  "eg": "على سبيل المثال ",
  "countryCodeHint": "سيؤدي ترك هذه القيمة فارغة إلى البحث في كل الدول والمناطق",
  "minCandidateScore": "الحد الأدنى لنقاط المرشح",
  "minCandidateScoreHint": "عند ترك هذه القيمة فارغة، يتم استخدام أدنى حد من عدد نقاط المرشح التي تبلغ 90.",
  "enableSingleField": "خيارات الحقل المفرد",
  "singleFieldHint": "بيانات العنوان في حقل مفرد",
  "enableMultiField": "خيارات الحقل المتعدد",
  "multiFieldHint": "ستوجد بيانات العنوان في حقول متعددة",
  "enableXYField": "خيارات حقل X/Y",
  "xyFieldHint": "تحتوي البيانات على قيم إحداثيات X/Y",
  "instructionGeocode": "أضف خدمات محدد المواقع وكوّنها.",
  "invalidUrlTip": "عنوان URL لـ ${URL} غير صحيح أو لا يمكن الوصول إليه.",
  "geocodeTabLabel": "إعدادات الموقع",
  "lookupList": "أسماء الحقل المطلوب التعرف عليها",
  "isRecognized": "يتم التعرف على أسماء الحقل في الجدول التالي تلقائيًا لهذا الحقل",
  "needsEditablePointLayers": "يجب أن تحتوي خريطة الويب على طبقة نقطة واحدة على الأقل قابلة للتحرير.",
  "editpageAlias": "الاسم المستعار",
  "configureFields": "تكوين حقول الطبقات",
  "configureSingleFields": "تكوين حقل عنوان مفرد",
  "configureMultiFields": "تكوين حقول العنوان المتعددة",
  "configureXYFields": "تكوين حقول X/Y",
  "noFields": "استخدام إجراء التحرير لتحديد حقل أو أكثر للعرض",
  "display": "العرض",
  "duplicate": "العثور على التكرار",
  "duplicateTip": "ابحث عن هذا الحقل للعثور على قيم متماثلة بين الملف المصدر والطبقة الهدف./n عند العثور على تطابق متماثل، لن يُحدد موقع السجل من الملف وسيوضع عليه علامة أنه مكرر.",
  "noSelectField": "تحديد خيار طبقة المعلم أولًا",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (خط طول)",
  "xyFieldsLabelY": "Y (خط عرض)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "باتجاه الشرق",
  "northing": "باتجاه الشمال",
  "lon": "خطوط الطول",
  "lat": "دوائر العرض",
  "layerOptionHint": "اختر الطبقة لتقديم البيانات إليها.",
  "layerFieldTitle": "طبقة الهدف",
  "tempSymbolHint": "اختر الرمز المستخدم لعرض المعالم.",
  "tempSymbolTitle": "عرض الرمز",
  "maxRecords": "أقصى عدد من السجلات",
  "maxRecordsHint": "أقصى عدد سجلات لتحديد موقعها",
  "searchRadius": "نطاق البحث",
  "searchRadiusHint": "مسافة البحث عن معالم مكررة من طبقة",
  "requiresInteger": "أدخل قيمة رقمية.",
  "requiresInteger0100": "إدخال قيمة رقمية بين 0 و100",
  "requiresLocator": "أضف محدد مواقع واحد صالح على الأقل.",
  "layerFields": "إعدادات الطبقة",
  "layerFieldsHint": "حدد الحقول من الطبقة الهدف التي ستُخطط إلى حقول المصدر.",
  "locatorError": "محدد المواقع غير صالح أو لا يمكن الوصول إليه.",
  "optionNotMatch": "خيارات الموقع غير متسقة عبر محددات المواقع. قد لا يعمل وقت تجاوز الفشل كما هو متوقع.",
  "targetLayerTabTitle": "طبقة الهدف",
  "locationSettingsTabTitle": "إعدادات الموقع",
  "generalSettingsTabTitle": "إعدادات عامة",
  "addTargetLayersLabel": "إضافة الطبقة الهدف",
  "introductoryText": "إنشاء محتوى إرشادي لعنصر واجهة المستخدم",
  "defaultStartPageInstructions": "سيساعدك عنصر واجهة المستخدم هذا في معالجة البيانات وإرسالها من ملف إلى الطبقة المحددة في الخريطة.<br/> <br/> يجب تحديد القيم داخل الملف بفاصلة أو علامة جدولة أو فاصلة منقوطة أو شريط رأسي.",
  "noTargetLayerConfiguredErrorMsg": "لم يتم تكوين طبقة هدف",
  "noFieldsForTargetLayer": "لم تُحدد إعدادات الطبقة للطبقة الهدف",
  "locationSettingsNotConfigured": "إعدادات الموقع غير مكونة على النحو الملائم."
});