define({
  "taskUrl": "URL-адрес сервиса обоюдной видимости",
  "portalURL": "Укажите URL-адрес вашей организации ArcGIS Online или Portal for ArcGIS",
  "portalURLError": "Указанный URL-адрес вашей организации ArcGIS Online или Portal for ArcGIS не действителен.",
  "privilegeError": "Ваша роль пользователя не может выполнять анализ. Для выполнения анализа, администратор вашей организации должен предоставить вам определенные <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">права</a>.",
  "noServiceError": "Сервис анализа высот недоступен. Проверьте настройки организации ArcGIS Online или Portal for ArcGIS.",
  "serviceURLPlaceholder": "Введите URL-адрес задачи геообработки обоюдной видимости",
  "setTask": "Задать",
  "setTaskTitle": "Задать задачу геообработки обоюдной видимости",
  "serviceURLError": "Задача геообработки, которую вы хотите настроить с этим виджетом, некорректна. Выберите URL корректной задачи Viewshed Geoprocessing",
  "defaultMilsForAnglesLabel": "Установить милы для углов по умолчанию",
  "defaultObserverHeightLabel": "Единицы измерения для высоты наблюдателя по умолчанию",
  "defaultObservableDistanceLabel": "Единицы обозреваемого расстояния по умолчанию",
  "units": {
    "miles": "Мили",
    "kilometers": "Километры",
    "feet": "Футы",
    "meters": "Метры",
    "yards": "Ярды",
    "nauticalMiles": "Морские мили"
  },
  "helpIconTooltip": "Список операционных слоев заполнен слоями текущей веб-карты с типом геометрии - полигон.",
  "selectOperationalLayerLabel": "Выберите операционный слой для результатов",
  "lineOfSightTabTitle": "Линия видимости",
  "symbologyTabTitle": "Символы",
  "transparency": "Прозрачность",
  "outline": "По главам",
  "fill": "Заливка (Цвет применяется, только если задан сплошной)",
  "style": "Стиль",
  "selectOpLayerLabel": "Выберите операционный слой для результатов",
  "selectDefaultMeasurementLabel": "Выберите единицы измерения по умолчанию",
  "visibleSectionLabel": "Видимая секция",
  "nonVisibleSectionLabel": "Невидимая секция",
  "visibleSectionButtonLabel": "Настроить параметры видимой секции",
  "nonVisibleSectionButtonLabel": "Настроить параметры невидимой секции",
  "colorPicker": "Выбор цветов",
  "lineStyles": {
    "esriSLSDash": "Штрихи",
    "esriSLSDashDot": "Тире – точка",
    "esriSLSDashDotDot": "Тире – точка – точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Длинное тире",
    "esriSLSLongDashDot": "Длинное тире – точка",
    "esriSLSNull": "Ноль",
    "esriSLSShortDash": "Короткое тире",
    "esriSLSShortDashDot": "Короткое тире – точка",
    "esriSLSShortDashDotDot": "Короткое тире – точка – точка",
    "esriSLSShortDot": "Короткая точка",
    "esriSLSSolid": "Сплошной"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Крест",
    "esriSFSDiagonalCross": "Диагональ",
    "esriSFSForwardDiagonal": "Вперед",
    "esriSFSHorizontal": "По горизонтали",
    "esriSFSNull": "Ноль",
    "esriSFSSolid": "Сплошной",
    "esriSFSVertical": "Вертикально"
  }
});