define({
  "_widgetLabel": "Sieťová trasa",
  "_featureAction_NetworkTraceSkip": "Preskočiť v trasovaní",
  "_featureAction_NetworkTraceUnskip": "Odstrániť z preskočených miest",
  "removedFromSkipLocations": "Odstránené z preskočených miest",
  "alreadyRemovedFromSkipLocations": "Už je ostránené z preskočených miest",
  "locationSkipped": "Miesto preskočené",
  "configError": "Widget nie je správne konfigurovaný.",
  "geometryServiceURLNotFoundMSG": "Nepodarilo sa získať URL geometrickej služby",
  "clearButtonValue": "Vyčistiť",
  "GPExecutionFailed": "Trasovanie sa nedá dokončiť. Skúste prosím znova.",
  "backButtonValue": "Späť",
  "exportToCSVSuccess": "Export do CSV je úspešne dokončený.",
  "lblInputLocTab": "Vstupné miesto",
  "lblBlockLocTab": "Blokovať miesta",
  "lblInputLocation": "Vstupný prvok",
  "lblBlockLocation": "Blokovať prvok",
  "lblInputLocHeader": "Vstupné miesta (0)",
  "lblBlockLocHeader": "Blokovať miesta (0)",
  "inputTabTitle": "Vstup",
  "outputTabTitle": "Výstup",
  "exportSelectAllCheckBoxLabel": "Vybrať všetko",
  "lblSkipLocHeader": "Preskočiť miesta (0)",
  "lblSkipLocation": "Poloha",
  "lblSkipLocTab": "Preskočiť miesta",
  "skipAllLocationButtonLabel": "Preskočiť všetky miesta",
  "confirmSkipAllLocationsMessage": "Všetky miesta budú preskočené, želáte si pokračovať?",
  "locationAlreadySkippedMessage": "Miesto už bola preskočená",
  "removeAllSkipLocationLabel": "Odstrániť všetky",
  "newProjectOptionText": "Nový projekt",
  "selectProject": "Vybrať projekt",
  "saveButtonLabel": "Uložiť",
  "exportToCSVText": "Exportovať do CSV",
  "editProjectAttributesToolTip": "Editovať atribúty projektu",
  "projectNameLabel": "Názov projektu",
  "saveProjectPopupTitle": "Uložiť",
  "saveAsLabel": "Uložiť ako",
  "saveChangesMsg": "Chcete uložiť vaše zmeny do <b>${loadProjectDropdownlabel}</b> alebo uložiť ako nový projekt?",
  "creatingNewProjectErrorMessage": "Chyba pri vytváraní nového projektu. Skúste prosím znova.",
  "projectNameFetchingErr": "Chyba pri získavaní existujúcich mien projektov. Skúste prosím znova.",
  "projectAttributeLoadingErr": "Chyba pri načítaní atribútov projektu. Skúste prosím znova.",
  "attributeUpdatedMsg": "Atribúty úspešne aktualizované",
  "projectAttributeUpdatingErr": "Chyba pri aktualizácii projektových atribútov.",
  "loadingProjectDetailsErrorMessage": "Chyba pri získavaní príznakov, bariér a preskočených miest. Skúste prosím znova.",
  "savingProjectDetailsErr": "Chyba pri ukladaní podrobností projektu. Prosím skúste uložiť projekt ešte raz.",
  "updatingOutagePolygonErr": "Chyba pri aktualizácii polygónu výpadku. Prosím skúste uložiť projekt ešte raz.",
  "deletingExistingPolygonErr": "Chyba pri mazaní existujúceho polygónu výpadku. Prosím skúste uložiť projekt ešte raz.",
  "loadingProjectFeaturesErr": "Chyba pri načítaní prvkov projektu. Prosím skúste projekt načítať ešte raz.",
  "addingProjectFeaturesErr": "Chyba pri pridávaní prvkov projektu. Prosím skúste uložiť projekt ešte raz.",
  "deletingExistingProjectFeaturesErr": "Chyba pri mazaní existujúcich prvkov objektu. Prosím skúste uložiť projekt ešte raz.",
  "projectNotFoundErr": "Projekt nebol nájdený.",
  "projectLayersNotFound": "Konfigurované vrstvy nastavenia projektu nie sú v mape dostupné. Widget bude načítaný v 'Režime náčrtu'.",
  "fetchingOutagePolygonMessage": "Chyba pri získavaní polygónu výpadku. Prosím skúste projekt načítať ešte raz.",
  "projectNameExistsMessage": "Názov projektu už existuje. Prosím použite unikátne meno projektu.",
  "fetchingProjectNamesErrorMessage": "Chyba pri získavaní existujúcich mien projektov. Prosím skúste uložiť projekt ešte raz.",
  "enterProjectNameMessage": "Prosím zadajte meno projektu.",
  "projectLengthErrorMessage": "Meno projektu nesmie byť väčšie ako",
  "gpServiceNotAccessible": "Váš účet nemá prístup k požadovaným službám na vykonanie tohto stopovania.",
  "loadingClonedLayerErrorMessage": "Chyba pri načítavaní klonovanej vrstvy prvkov. Skúste prosím znova.",
  "addingFeatureInClonedLayerError": "Chyba pri pridávaní grafík do klonovanej vrstvy prvkov. Skúste prosím znova.",
  "selectingFeatureInClonedLayerError": "Chyba pri výbere grafík v klonovanej vrstve prvkov. Skúste prosím znova.",
  "filteredProjectError": "Chyba pri kontrole získavaných filtrovaných podrobností projektu. Skúste prosím znova.",
  "filteredProjectMessage": "Zvolené atribúty projektu nie sú dostupné kvôli použitým filtrom z webovej mapy alebo iného widgetu. Vyčistiť filter(e) a skúste znova.",
  "filteredProjectLoadMessage": "Váš projekt už nie je dostupný. Prosím zvoľte aktívny projekt.",
  "defaultValueForRunButton": "Spustiť",
  "closeButtonLabel": "Odstrániť"
});