define({
  "_widgetLabel": "עורך חכם",
  "_featureAction_SmartEditor": "עורך חכם",
  "noEditPrivileges": "לחשבונך אין הרשאות ליצור נתונים או לשנות אותם.",
  "loginPopupTitle": "היכנס",
  "loginPopupMessage": "${widgetName} מחייב הרשאות וקרדיטים לצורך חיפוש ואחסון של פרטי כתובת. האם ברצונך להיכנס ולהשתמש ביכולת זו?",
  "noCreditsOrPrivilegeWarningMessage": "לחשבונך אין הרשאות וקרדיטים לחיפוש ואחסון של פרטי כתובת באמצעות ${widgetName}. פנה למנהל המערכת בארגון שלך ובקש הרשאות וקרדיטים.",
  "unableToUseLocator": "מגדיר עיגון הכתובות לא נגיש. הפעולות על מאפייני הכתובת לא יתבצעו.",
  "locatorDisabledWaning": "מגדיר עיגון הכתובות לא מופעל. פנה למנהל המערכת בארגון שלך ובקש יכולת זו.",
  "noFeatureInAIWarning": "לא נבחרו ישויות. בחר ישות כדי לבצע פעולות עריכה או לחץ על ביטול כדי לחזור למסך הראשי.",
  "noEditableLayerWarning": "לחשבונך אין הרשאה ליצור או לשנות נתונים, או שמפת ווב זו לא מכילה שכבות הניתנות לעריכה.",
  "noVisibleCreateLayerWarning": "השכבות לא נראות ברמת זום זו. הגדל או הקטן את רמת הזום כדי ליצור/לשנות ישויות.",
  "noVisibleUpdateLayerWarning": "השכבות לא נראות ברמת זום זו. הגדל או הקטן את רמת הזום כדי לשנות ישויות.",
  "checkLayerVisibilityInWebMapWarning": "כדי ליצור או לשנות ישויות, ודא שהשכבות נראות במפה.",
  "showSelectionInAITitle": "ישויות נבחרות",
  "showSelectionInAIMsg": "האם ברצונך לטעון את הבחירה הנוכחית ב-${widgetName}?",
  "widgetActive": "פעיל",
  "widgetNotActive": "לא פעיל",
  "pressStr": "לחץ ",
  "ctrlStr": " CTRL ",
  "snapStr": " כדי להפעיל הצמדה",
  "noAvailableTempaltes": "אין תבניות זמינות",
  "editorCache": " -- מטמון העורך",
  "presetFieldAlias": "שדה",
  "presetValue": "ערך קבוע מראש",
  "usePresetValues": " השתמש בערכים שנקבעו מראש (ישויות חדשות בלבד)",
  "editGeometry": " ערוך גיאומטריה",
  "savePromptTitle": "שמור ישות",
  "savePrompt": "האם ברצונך לשמור את הישות הנוכחית?",
  "deletePromptTitle": "מחק ישות",
  "deleteAttachment": "מחק קישור",
  "deletePrompt": "האם אתה בטוח שברצונך למחוק את הישות שנבחרה?",
  "attachmentLoadingError": "שגיאה בטעינת קישורי קבצים",
  "attachmentSaveDeleteWarning": "אזהרה: שינויים בקישורי קבצים נשמרים באופן אוטומטי",
  "autoSaveEdits": "שמור ישויות חדשות באופן אוטומטי",
  "addNewFeature": "צור ישות חדשה",
  "featureCreationFailedMsg": "לא ניתן ליצור רשומה/ישות חדשה",
  "relatedItemTitle": "טבלה/שכבה מקושרת",
  "relatedFeatureCount": "${layerTitle} עם ${featureCount} ישויות",
  "createNewFeatureLabel": "צור ישויות חדשות עבור ${layerTitle}",
  "invalidRelationShipMsg": "ודא ששדה המפתח הראשי: '‎${parentKeyField}‎' מכיל ערך חוקי",
  "pendingFeatureSaveMsg": "שמור את עריכת הישות לפני שתיצור ישות מקושרת.",
  "attachmentsRequiredMsg": "(*) נדרשות תוספות.",
  "coordinatePopupTitle": "העבר את הישות למיקום XY",
  "coordinatesSelectTitle": "מערכת קואורדינטות:",
  "mapSpecialReferenceDropdownOption": "ייחוס מרחבי של מפה",
  "latLongDropdownOption": "קו רוחב/אורך",
  "mgrsDropdownOption": "מערכת ייחוס גריד צבאי (MGRS)",
  "mgrsTextBoxLabel": "מערכת קואורדינטות:",
  "xAttributeTextBoxLabel": "קואורדינטה X:",
  "yAttributeTextBoxLabel": "קואורדינטה Y:",
  "latitudeTextBoxLabel": "קו רוחב:",
  "longitudeTextBoxLabel": "קו אורך:",
  "presetGroupFieldsLabel": "'${groupName}' יוחל על שדות השכבה הבאות:",
  "presetGroupNoFieldsLabel": "ל-'${groupName}' אין שדות מקושרים",
  "groupInfoLabel": "פרטי קבוצה עבור '${groupName}'",
  "editGroupInfoIcon": "ערוך ערך קבוצה עבור ${groupName}",
  "filterEditor": {
    "all": "הכל",
    "noAvailableTempaltes": "אין תבניות זמינות",
    "searchTemplates": "תבניות חיפוש",
    "filterLayerLabel": "סנן שכבות"
  },
  "invalidConfiguration": "תצורת הווידג'ט לא הוגדרה או שהשכבות בתצורה אינן נמצאות עוד במפה. פתח את האפליקציה במצב עריכה והגדר מחדש את תצורת הווידג'ט.",
  "geometryServiceURLNotFoundMSG": "לא ניתן לקבל כתובת URL של שירות גיאומטריה",
  "clearSelection": "סגירה",
  "refreshAttributes": "עדכן מאפייני ישויות דינמיים",
  "automaticAttributeUpdatesOn": "עדכון אוטומטי של מאפייני ישויות: פועל",
  "automaticAttributeUpdatesOff": "עדכון אוטומטי של מאפייני ישויות: כבוי",
  "moveSelectedFeatureToGPS": "העבר את הישות שנבחרה למיקום ה-GPS הנוכחי",
  "moveSelectedFeatureToXY": "העבר את הישות שנבחרה למיקום XY",
  "mapNavigationLocked": "ניווט במפה: נעול",
  "mapNavigationUnLocked": "ניווט במפה: לא נעול",
  "copyFeatures": {
    "title": "העתק ישויות",
    "createFeatures": "צור ישויות",
    "createSingleFeature": "צור ישות מרובת-חלקים אחת",
    "createOneSingleFeature": "צור ישות",
    "noFeaturesSelectedMessage": "לא נבחרו ישויות",
    "selectFeatureToCopyMessage": "בחר ישויות להעתקה",
    "multipleFeatureSaveWarning": "הערה: יצירת ישויות מרובות באמצעות פונקציונליות ההעתקה תביא לשמירה של כל הישויות החדשות באופן מיידי",
    "copyFeatureUpdateGeometryError": "לא ניתן לעדכן את הגיאומטריה של הישויות שנבחרו",
    "canNotSaveMultipleFeatureWarning": "הערה: אין אפשרות להעתיק ישויות מרובות באמצעות אותו ערך לשדות שדורשים ערכים ייחודיים, יש לבחור רק ישות אחת",
    "createOnlyOneMultipartFeatureWarning": "הערה: אפשר ליצור רק ישות אחת מרובת חלקים"
  },
  "addingFeatureError": "שגיאה בהוספת ישויות שנבחרו למפה. נסה שוב.",
  "addingFeatureErrorCount": "העתקה של ישויות '${copyFeatureErrorCount}' נכשלה. האם ברצונך לנסות שוב עבור הישויות החסרות?",
  "selectingFeatureError": "שגיאה בעת בחירת ישויות במפה. נסה שוב.",
  "customSelectOptionLabel": "בחר ישויות להעתקה",
  "noFeatureSelectedMessage": "לא נבחרו ישויות",
  "multipleFeatureSaveMessage": "כל הישויות יישמרו מיד. האם ברצונך להמשיך?",
  "relativeDates": {
    "dateTypeLabel": "סוג תאריך",
    "valueLabel": "ערך",
    "fixed": "קבוע",
    "current": "נוכחי",
    "past": "עבור",
    "future": "עתיד",
    "popupTitle": "בחר ערך",
    "hintForFixedDateType": "עצה: התאריך והשעה שצוינו ישמשו כערך ברירת מחדל מוגדר מראש.",
    "hintForCurrentDateType": "עצה: התאריך והשעה הנוכחיים ישמשו כערך ברירת מחדל מוגדר מראש.",
    "hintForPastDateType": "עצה: הערך שצוין יופחת מהתאריך והשעה הנוכחיים לקבלת ערך ברירת המחדל של ההגדרה מראש.",
    "hintForFutureDateType": "עצה: הערך שצוין יתווסף לתאריך ולשעה הנוכחיים לקבלת ערך ברירת המחדל של ההגדרה מראש.",
    "noDateDefinedTooltip": "לא הוגדר תאריך",
    "relativeDateWarning": "חובה לציין ערך עבור תאריך או שעה כדי שניתן יהיה לשמור את ערך ברירת המחדל הקבוע מראש.",
    "customLabel": "מותאם אישית",
    "layerLabel": "שכבה",
    "domainFieldHintLabel": "הערך שנבחר הוא דומיין של ערכים מקודדים. ייעשה שימוש בערך: '${domainValue}'"
  },
  "valuePicker": {
    "popupTitle": "בחר ערך",
    "popupHint": "היישות הנוכחית חוצה ישויות אחרות, בחר ערך לשדה המתאים",
    "buttonTooltip": "בחר ערך מבין הישויות המצטלבות השונות"
  },
  "uniqueValueErrorMessage": "הערך \"\" ב-\"${fieldName}\" קיים כבר, ציין ערך חדש.",
  "requiredFields": {
    "displayMsg": "שדות חובה לא יכולים להיות ריקים. יש לציין ערכים לשדות משותפים בהמשך.",
    "popupTittle": "שדות נדרשים",
    "foundNullRecordCount": "${fieldName} (נמצא ב-${count} רשומות)"
  },
  "cantLocateUserLocation": "לא ניתן לקבוע את מיקומך",
  "tryAgainButtonLabel": "נסה שוב",
  "copyFeatureFailedPopupTitle": "אופס!"
});