define({
  "_widgetLabel": "Batch-attribut-editor",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Navn på lag",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Ingen redigérbare lag er konfigureret",
  "editorPopupTitle": "Batch-attribut-editor",
  "editorPopupSaveBtn": "Gem",
  "editorPopupMultipleValues": "",
  "clear": "Ryd",
  "featuresUpdated": "${0} / ${1} objekt(er) opdateret",
  "featuresSelected": "${0} objekt(er) valgt",
  "featuresSkipped": "Tilsidesat",
  "featuresNoPermision": "${0} objekt(er) er valgt, men ingen redigeringstilladelse.",
  "search": "Search",
  "queryInput": "Angiv en værdi, der skal forespørges om",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Angiv filteret korrekt.",
  "filterPopup": "Filtrér lag",
  "filterAppend": "Der findes allerede et filter for dette lag i webkortet",
  "filterAppendOR": "Knyt ethvert udtryk til det eksisterende kortfilter",
  "filterAppendAND": "Knyt alle udtryk til det eksisterende kortfilter",
  "cancel": "Annullér",
  "noValue": "Ingen værdi",
  "emptyString": "Tom streng",
  "existingValue": "Behold eksisterende værdi",
  "newDate": "Ny dato",
  "valueChooser": "Vælg/angiv en værdi",
  "ok": "OK",
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihåndspolylinje",
    "extent": "Udstrækning",
    "polygon": "Polygon",
    "freehandPolygon": "Frihåndspolygon",
    "clear": "Ryd",
    "addPointToolTip": "Klik for at vælge i dette område",
    "addShapeToolTip": "Tegn en form for at vælge objekter",
    "freehandToolTip": "Tryk og hold nede for at tegne en form for at vælge objekter",
    "startToolTip": "Tegn en form for at vælge objekter"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Objektet fra ${0} returnerede et ugyldigt id",
    "noSelectedLayers": "Ingen valgte lag med poster, der skal opdateres",
    "inputValueError": "Ugyldig værdi i formularen",
    "saveError": "Kan ikke gemme ${0} objekter",
    "requiredValue": "Påkrævet værdi"
  }
});