define({
  "styleText": "Typ nástroja pre potiahnutie",
  "vertical": "Zvislá lišta",
  "horizontal": "Vodorovný panel",
  "scope": "Zväčšovacie sklo",
  "placement": "Smer",
  "showLeftSide": "Zobraziť potiahnuté vrstvy na ľavej strane",
  "showRigthSide": "Zobraziť potiahnuté vrstvy na pravej strane",
  "showUpSide": "Zobraziť potiahnuté vrstvy na vrchnej strane",
  "showDownSide": "Zobraziť potiahnuté vrstvy na spodnej strane",
  "barColor": "Farba stĺpca",
  "swipeMode": "Režim potiahnutia prstom",
  "singleLayer": "Jedna vrstva",
  "MultipleLayers": "Viacero vrstiev",
  "allowToSwipe": "Povoliť potiahnutie prstom",
  "layer": "Vrstva",
  "swipeByDefault": "Predvolene potiahnuť prstom",
  "defaultLayerMustBeVisible": "predvolená vrstva musí byť viditeľná",
  "noDefaultLayer": "Prosím predvolene nastavte vrstvy na potiahnutie prstom",
  "defaultLayerHolder": "Kliknite pre výber",
  "selectLayers": "Vybrať vrstvy",
  "layerText": "Predvolená vrstva(y) potiahnutia prstom",
  "spyglassText": "Vyberte vrstvu, ktorá sa predvolene objaví vo zväčšovacom skle.",
  "layerHint": "Poznámka: Ak je vrstva prekrytá hornými vrstvami, prejdenie prstom nebude mať žiadny efekt.",
  "isZoom": "Priblížiť na vrstvu potiahnutia prstom",
  "isZooms": "Priblížiť na vrstvu(y) potiahnutia prstom",
  "layersAvailable": "Potiahnuteľné vrstvy",
  "hidePanel": "Skyť vrstvu výberom panelu, keď sa widget otvorí"
});