define({
  "transparencyLabel": "Transparență",
  "outline": "Contur",
  "fill": "Umplere (culoarea se aplică doar când stilul este setat la continuu)",
  "style": "Stil",
  "selectOpLayerLabel": "Selectați un strat tematic operațional pentru rezultate",
  "selectDefaultMeasurementLabel": "Selectați o unitate de măsură implicită",
  "helpIconTooltip": "Lista cu straturi tematice operaționale este populată cu straturi tematice din harta web actuală, care au o geometrie de tip poligon.",
  "lineStyles": {
    "esriSLSDash": "Linie",
    "esriSLSDashDot": "Linie punct",
    "esriSLSDashDotDot": "Linie punct punct",
    "esriSLSDot": "Punct",
    "esriSLSLongDash": "Linie lungă",
    "esriSLSLongDashDot": "Linie lungă punct",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Linie scurtă",
    "esriSLSShortDashDot": "Linie scurtă punct",
    "esriSLSShortDashDotDot": "Linie scurtă punct punct",
    "esriSLSShortDot": "Punct scurt",
    "esriSLSSolid": "Continuu"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Înapoi",
    "esriSFSCross": "Cruce",
    "esriSFSDiagonalCross": "Diagonală",
    "esriSFSForwardDiagonal": "Înainte",
    "esriSFSHorizontal": "Orizontală",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Continuu",
    "esriSFSVertical": "Verticală"
  },
  "threatTypeLabel": "Tip de amenințare",
  "generalLabel": "General",
  "addThreatTypesLabel": "Adăugare tip de amenințare",
  "actions": "Acțiuni",
  "newThreatTypePopupLabel": "Tip de amenințare nou",
  "units": "Unități",
  "chooseDefaultThreatLabel": "Selectați tipul de amenințare implicit",
  "defaultThreatTypePopUpLabel": "Tipuri de amenințare Implicite",
  "editThreatLabel": "Editare amenințare",
  "defaultThreatTypeIconTooltip": "Listă cu tipuri de amenințare implicite",
  "uniqueThreatTypeMsg": "Introduceți un tip de amenințare unic, există deja un tip de amenințare cu acest nume.",
  "requiredMsg": "Acest câmp este obligatoriu",
  "unitMeasureLabel": "Distanțele sunt în {0}",
  "chooseDefaultThreatTypeIconLabel": "Alegeți din valorile implicite",
  "pipeBombLabel": "Bombă artizanală",
  "suicideBombLabel": "Sinucigaș cu bombă",
  "briefcaseLabel": "Servietă",
  "carLabel": "Autoturism",
  "suvVanLabel": "SUV/camionetă",
  "smallDeliveryTruckLabel": "Camion de livrare de mici dimensiuni",
  "containerWaterTruckLabel": "Container/cisternă",
  "semiTrailerLabel": "Semiremorcă",
  "chemicalThreatLegendLabel": "Amenințare chimică",
  "lpgThreatLegendLabel": "Amenințare GPL",
  "smallLPGTank": "Rezervor de GPL mic",
  "largeLPGTank": "Rezervor de GPL mare",
  "commercialResidentialLPGTank": "Rezervor de GPL comercial/rezidențial",
  "smallLPGTruck": "Camion de GPL mic",
  "semiTankerLPG": "Autocisternă de GPL",
  "threatDescriptionColLabel": "Descrierea amenințării",
  "addThreatZoneButtonLabel": "Adăugare tip de amenințare",
  "zoneDescColLabel": "Descrierea zonei",
  "distanceLabel": "Distanță (${unitAbbr})",
  "threatTypeHelp": "<p>Asigurați-vă de respectarea condițiilor următoare pentru un tip de amenințare:<br/><ul><li>Tipul de amenințare nu poate fi gol și trebuie să fie unic</li><li>Amenințarea trebuie să aibă cel puțin o zonă valabilă</li><li>Descrierea zonei trebuie să fie unică pentru o amenințare</li></ul><p/>",
  "descriptionLabel": "Descriere",
  "newThreatZonePopupLabel": "Zonă de amenințare nouă",
  "editThreatZonePopupLabel": "Editați zona de amenințare",
  "uniqueZoneDescriptionMsg": "Introduceți o descriere unică a zonei, există deja o descriere a zonei cu acest nume.",
  "symbologyColLabel": "Simbologie",
  "zoneDescriptionColLabel": "Descrierea zonei",
  "uniqueZoneRequiredMsg": "Numele zonei trebuie să fie unic pentru",
  "interactive": "Interactiv",
  "fromCoord": "Coordonată fixă",
  "existingFeature": "Din obiecte spațiale existente",
  "defaultInputLocationLabel": "Loc de intrare implicit",
  "defaultInputLayer": "Strat tematic de intrare implicit",
  "defaultThreatType": "Tip de amenințare implicit",
  "selectLabel": "Selectare",
  "mandatoryLabel": "Distanță obligatorie de evacuare",
  "safeLabel": "Distanță sigură de evacuare",
  "lpgSafeDistanceLable": "Distanță sigură",
  "fireBallDiameterLable": "Diametrul mingii de foc"
});