define({
  "settings": "Nastavenia",
  "titleSettings": "Nastavenia textu",
  "imageSettings": "Nastavenia obrázka",
  "backgroundColor": "Farba pozadia",
  "alignment": "Zarovnanie",
  "textSize": "Veľkosť textu",
  "textColor": "Farba textu",
  "dataSource": "Zdroj údajov",
  "chartSettings": "Nestavenia grafu",
  "data": "Údaje",
  "dataLabels": "Označenia údajov",
  "displayMode": "Režim zobrazenia",
  "featureOption": "Zobrazenie hodnôt po prvkoch",
  "categoryOption": "Zobrazenie hodnôt podľa kategórie",
  "countOption": "Zobrazenie počtu prvkov podľa kategórie",
  "fieldOption": "Zobrazenie hodnôt atribútu ako graf",
  "categoryField": "Stĺpec s kategóriou",
  "labelField": "Stĺpec s označeniami",
  "valueFields": "Stĺpce s hodnotami",
  "operation": "Operácia",
  "sumOption": "Súčet",
  "averageOption": "Priemer",
  "minOption": "Minimum",
  "maxOption": "Maximum",
  "countString": "Počet",
  "dataFormat": "Formát údajov",
  "decimalPlaces": "Desatinné miesta",
  "prefix": "Predpona",
  "suffix": "Prípona",
  "dataType": "Údajový typ",
  "featureCount": "Počet prvkov",
  "fieldStatistics": "Štatistika stĺpca",
  "display": "Zobrazenie",
  "chartColor": "Farba grafu",
  "horizontalAxis": "Vodorovná os",
  "verticalAxis": "Zvislá os",
  "legend": "Legenda",
  "position": "Pozícia",
  "top": "Hore",
  "bottom": "Dole",
  "useDataSourceSelection": "Použiť výber",
  "dataSourceFilterByExtent": "Filtrovať podľa rozsahu",
  "changeTemplate": "Zmeniť šablónu",
  "chooseTemplate": "Zvoliť šablónu",
  "numberSettings": "Nastavenia čísel",
  "gaugeSettings": "Nastavenia ukazovateľa",
  "indicators": "Indikátory",
  "ifValue": "If hodnota",
  "and": "a",
  "numberOperatorIsLessThan": "je menej ako",
  "numberOperatorIsGreaterThan": "je väčší ako",
  "numberOperatorIsBetween": "je medzi",
  "numberOperatorIsEqual": "rovná sa",
  "numberOperatorIsNotEqual": "nie je rovné",
  "then": "Then",
  "ratio": "Pomer",
  "trueValue": "True hodnota",
  "changeValueColor": "zmeniť farbu hodnoty na",
  "changeGaugeColor": "zmeniť farbu ukazovateľa na",
  "setIndicatorIcon": "nastaviť ikonu indikátora na",
  "icons": "Ikony",
  "style": "Štýl",
  "placement": "Rozmiestnenie",
  "left": "Vľavo",
  "replace": "Vymeniť",
  "right": "Vpravo",
  "color": "Farba",
  "categoryExists": "Kategória existuje!",
  "comboxHint": "Zadajte alebo zvoľte jeden",
  "comboxDisableInputHint": "Vybrať jednu",
  "comboxDisableSelectHint": "Zadajte jeden",
  "comboxDisableInputEmptySelectHint": "Žiadne ďaľšie kategórie",
  "sortBy": "Zoradiť podľa",
  "labelAxis": "Opis",
  "valueAxis": "Hodnota",
  "minPeriod": "Minimálne obdobie",
  "automatic": "Automatická",
  "periodsWithOutRecords": "Obdobie bez záznamov",
  "nullValue": "Hodnota Null",
  "calculatedAsZero": "Vypočítaná ako nula",
  "ignored": "Ignorované",
  "maxCategories": "Maximum kategórií",
  "useLayerSymbology": "Použiť symboliku vrstvy",
  "hollowsize": "Veľkosť dutiny",
  "splitField": "Stĺpec pre rozdelenie",
  "parsingperiodTip": "Výpočet sa nepodaril. Priveľa časových intervalov kvôli krátkemu vyhodnocovanému obdobiu",
  "manyCategoryTip": "Nepodarilo sa zobraziť graf. Príliš veľa kategórií.",
  "setColor": "Nastaviť farbu",
  "setTheColorOf": "Potom nastaviť farbu",
  "setTheColorAs": "Potom nastaviť farbu na",
  "ifStr": "If",
  "as": "ako",
  "is": "je",
  "isNot": "nie je",
  "barCluster": "zhluk stĺpcov",
  "individualBar": "jednotlivý stĺpec",
  "allOthers": "Všetky ostatné",
  "category": "Kategória",
  "indicatorSum": "SUM",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Prosím nastavte indikátory správne.",
  "dataRange": "Rozsah údajov",
  "targetValue": "Cieľová hodnota",
  "currentValue": "Aktuálna hodnota",
  "gaugeColor": "Farba ukazovateľa",
  "min": "Minimum",
  "max": "Maximum",
  "displayValueIn": "Zobraziť v",
  "noData": "Bez dát",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Upozornenie",
  "noSettingWaring1": "Kliknite na prvok pre nastavenie jeho vlastností.",
  "noSettingWaring2": "Potiahnuť pre zmenu veľkosti alebo poradia prvku.",
  "donNotShowAgain": "Znova nezobrazovať",
  "changeTemplateWarning": "Týmto sa vymažú všetky vaše nastavenia a otvorí sa nová prázdna šablóna.",
  "requiredFieldWarning": "Vyžaduje sa táto hodnota:",
  "dataSourceNotSet": "Prosím nastavte zdroj údajov.",
  "addIndicatorTip": "Pridať indikátor",
  "chooseTemplatePopupTitle": "Zvoliť šablónu",
  "filterExtentTipWithaTag": "Filter môžete deaktivovať pomocou <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'> \"Extra zdroj údajov\"</a> pod kartou atribútov.",
  "filterExtentTip": "Filter môžte deaktivovať pomocou \"Extra zdroj údajov\" pod kartou atribútov.",
  "customColorByCategory": "Vlastná farba podľa kategórie",
  "randomColor": "Náhodná farba",
  "valueString": "Hodnota",
  "fieldString": "Pole",
  "includeThresholdValue": "Zahrnúť prahovú hodnotu",
  "percentage": "Percento",
  "colorSchema": "Farebná schéma",
  "addCategory": "Pridajte kategóriu",
  "clickToEdit": "Kliknúť pre úpravy",
  "nullText": "Null",
  "others": "Iné",
  "dsErrorTipSuf": "nie je dostupný.",
  "front": "Vpredu",
  "back": "Späť",
  "title": "Názov",
  "titleColor": "Farba názvu",
  "labelString": "Opis",
  "labelSize": "Veľkosť označenia",
  "labelColor": "farba označenia",
  "addMarkLine": "Pridať značku línie",
  "addMarkArea": "Pridať značku plochy",
  "labelPosition": "Pozícia označenia",
  "toString": "do",
  "start": "Začiatok",
  "middle": "V strede (zvislo)",
  "end": "Koniec",
  "inString": "V",
  "outString": "Von",
  "lineColor": "Farba línie",
  "lineWidth": "Šírka línie",
  "dashType": "Typ pomlčky",
  "areaColor": "Farba plochy",
  "line": "Línia",
  "area": "Plocha",
  "stringsInTemplate": {
    "name_number": "Číslo",
    "name_gauge": "Miera",
    "name_vertical_gauge": "Zvislý ukazovateľ",
    "name_horizontal_gauge": "Vodorovný ukazovateľ",
    "name_pie": "Koláčový",
    "name_donut": "Široký prstenec",
    "name_bar": "Stĺpec",
    "name_stacked_bar": "Skladaný pruh",
    "name_percentage_stacked_bar": "Percentuálny skladaný pruh",
    "name_column": "Stĺpec",
    "name_stacked_column": "Skladaný stĺpec",
    "name_percentage_stacked_column": "Percentuálny skladaný stĺpec",
    "name_line": "Línia",
    "name_area": "Plocha",
    "name_stacked_area": "Skladaná plocha",
    "name_percentage_stacked_area": "Percentuálna skladaná plocha",
    "titleOfTheInfographic": "NÁZOV INFOGRAFIKY",
    "description": "Opis: ďaľšie informácie o tejto infografike."
  },
  "marks": "Značky",
  "displayValue": "Zobraziť hodnotu",
  "statistic": "Štatistika",
  "valueType": "Typ hodnoty",
  "valueField": "Stĺpec s hodnotou",
  "fixed": "Fixné",
  "sdsTip": "Vybrať štatistické údaje konfigurované v extra zdroji údajov",
  "noSdsTip": "Žiadne dostupné štatistické údaje.",
  "intScaleText": "Zobraziť len celočíselnú mierku",
  "resetLayout": "Obnoviť rozloženie",
  "fbeTip": "Upozorňujeme, že ak je vaša aplikácia zdieľaná verejne a je rozšírená, povolenie tejto možnosti výrazne spomalí výkon aplikácie. Dôrazne odporúčame použitie iných widgetov, ako Filter a Skupinový Filter, na priblíženie k prvkom.",
  "openFbeTip": "Aj tak zapnúť možnosť",
  "use1000Separator": "Použiť oddeľovač tisícov",
  "noDataReturned": "Žiadne vrátené údaje",
  "tooltipMode": "Tooltip režim",
  "single": "Jediná",
  "multiple": "Viacnásobná",
  "defaultRange": "Predvolený rozsah zobrazenia"
});