define({
  "_widgetLabel": "Tổng hợp Dữ liệu",
  "startPage": {
    "defaultStartPageInstructions": "Tiện ích này sẽ hỗ trợ việc xử lý và gửi dữ liệu từ tệp đến lớp được chọn trong bản đồ.<br/> <br/> Các giá trị trong tệp phải được phân cách bằng dấu phẩy, tab, dấu chấm phẩy hoặc dấu gạch đứng.",
    "dragDrop": "Kéo và thả",
    "browse": "Duyệt tìm Tệp",
    "or": "HOẶC",
    "userPrivilege": "Tài khoản của bạn không có quyền tạo hoặc sửa đổi dữ liệu.",
    "userCredits": "${widgetName} yêu cầu có credit để sử dụng bộ định vị ${locator}.",
    "contactAdmin": "Hãy liên hệ quản trị viên tổ chức để yêu cầu thêm credit.",
    "contactAdminEdit": "Hãy liên hệ quản trị viên tổ chức để yêu cầu chỉnh sửa quyền.",
    "canUseLocator": "Bộ định vị ${locator} sẽ được sử dụng để định vị các đối tượng.",
    "notEnoughCredits": "Không đủ credit.",
    "locationAndField": "Thông tin về Vị trí và Trường",
    "locationAndFieldHint": "Chọn các giá trị từ tệp sẽ được sử dụng để cập nhật lớp mục tiêu.",
    "cannotUseLocator": "Không sử dụng được ${widgetName}",
    "noAnonymousEdit": "Lớp ${layerName} không hỗ trợ khả năng chỉnh sửa ẩn danh.",
    "pleaseLogin": "Hãy đăng nhập vào tổ chức ${org} hoặc liên hệ quản trị viên của tổ chức bạn để yêu cầu cho phép chỉnh sửa ẩn danh.",
    "invalidEdit": "Đặc quyền hợp lệ",
    "unableToAccess": "Không thể truy cập ${layerName}",
    "appropriateCredentials": "Xác minh rằng bạn đã đăng nhập bằng thông tin xác thực phù hợp.",
    "shared": "Hãy liên hệ với quản trị viên của tổ chức để yêu cầu truy cập lớp ${layerName}.",
    "targetLayerLabel": "Lớp Mục tiêu",
    "homeButtonLabel": "Trang chủ",
    "mappingErrorMsg": "Bấm vào mũi tên bên cạnh để xác định trường"
  },
  "mapping": {
    "schemaMapping": "Thông tin về Trường",
    "schemaMappingHint": "Chọn các trường từ tệp tương quan với các trường trong lớp.",
    "locationMapping": "Thông tin về Vị trí",
    "locationMappingHint": "Chọn loại thông tin địa chỉ hoặc tọa độ sẽ mong đợi ở tệp."
  },
  "locationMapping": {
    "locationMappingPageHint": "Chọn loại vị trí",
    "useAddress": "Định vị bằng địa chỉ",
    "useAddressHint": "Dữ liệu chứa thông tin địa chỉ",
    "useCoordinates": "Định vị bằng tọa độ",
    "useCoordinatesHint": "Dữ liệu chứa giá trị tọa độ X/Y"
  },
  "address": {
    "addressPageHint": "Chọn loại địa chỉ",
    "singleField": "Một trường",
    "singleFieldHint": "Chọn trường chứa thông tin địa chỉ",
    "multiField": "Nhiều trường",
    "multiFieldHint": "Chọn các trường chứa thông tin địa chỉ"
  },
  "coordinates": {
    "coordinatesPageHint": "Chọn các trường chứa dữ liệu tọa độ"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Chọn trường nguồn ánh xạ đến trường mục tiêu",
    "sourceField": "Khớp Trường Nguồn",
    "targetField": "Trường Mục tiêu"
  },
  "buttons": {
    "addToMap": "Thêm vào Bản đồ",
    "submit": "Đệ trình",
    "download": "Tải xuống"
  },
  "review": {
    "matched": "Tìm thấy",
    "reviewMatched": "Vị trí Tìm thấy",
    "reviewMatchedHint": "Xem lại vị trí tìm thấy.",
    "unMatched": "Không tìm thấy",
    "reviewUnMatched": "Vị trí không Tìm thấy",
    "reviewUnMatchedHint": "Xem lại vị trí không tìm thấy. Các mục không chính xác sẽ không được gửi đi.",
    "duplicate": "Bản sao",
    "reviewDuplicate": "Sao lại Vị trí",
    "reviewDuplicateHint": "Xem lại vị trí đã được tìm thấy trong lớp. Các mục không được đề cập sẽ không được gửi đi.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Sử dụng:",
    "fromLayer": "Thông tin Mục tiêu",
    "target": "Đích",
    "source": "Nguồn",
    "fromFile": "Thông tin Nguồn",
    "locationControlHint": "Xem lại thông tin địa chỉ",
    "duplicateAction": "Chọn tác vụ",
    "item": "Bản ghi:",
    "locateFeature": "Định vị Đối tượng",
    "removeFeature": "Gỡ bỏ Đối tượng",
    "featureLocated": "Tìm thấy Vị trí",
    "valuesDoNotMatch": "Không khớp với giá trị hiện có",
    "sync": "Đồng bộ hóa thông tin địa chỉ với thông tin trường",
    "noFeaturesSaved": "Lưu đối tượng không thành công",
    "someFeaturesSaved": "Đã lưu thành công ${num} đối tượng.",
    "someFeaturesNotSaved": "Không thể lưu ${num} đối tượng.",
    "feature": "Xem lại Thông tin Đối tượng",
    "locationInfo": "Xem lại Thông tin Vị trí",
    "selectValue": "Chọn một Giá trị",
    "reviewData": "Xem lại Dữ liệu",
    "reviewDataHint": "Xem lại dữ liệu trước khi gửi tới lớp.",
    "reviewFeatureHint": "Xem lại hoặc chỉnh sửa đối tượng và thông tin vị trí của bạn.",
    "duplicateModify": "Trùng lặp, cần thay đổi",
    "duplicateSave": "Lưu thành đối tượng mới"
  },
  "warningsAndErrors": {
    "invalidCSV": "Đã xảy ra lỗi khi truy xuất các mục từ CSV, kiểm tra xem có chọn tệp CSV hợp lệ không.",
    "noLayersWarning": "Không có lớp mục tiêu hợp lệ nào được cấu hình, hãy kiểm tra cấu hình.",
    "loadWarning": "Tiện ích này yêu cầu có nguồn dữ liệu Dịch vụ Đối tượng. Hãy cấu hình tiện ích để xác định nguồn dữ liệu.",
    "saveError": "Lỗi khi lưu các đối tượng.",
    "consumesCredits": "Công cụ này tiêu tốn điểm tín dụng khi dùng với Dịch vụ Mã hóa địa lý Thế giới Trực tuyến của ArcGIS",
    "noValue": "Chọn một trường",
    "mappingTitle": "",
    "locationMappingComplete": "Hoàn thành Ánh xạ Vị trí",
    "fieldMappingComplete": "Hoàn thành Ánh xạ Trường",
    "settingsCleared": "Các thiết lập sẽ bị xóa.",
    "proceed": "Bạn có muốn tiếp tục?",
    "itemMoveMatch": "Mục đã được định vị và di chuyển đến danh sách vị trí tìm thấy",
    "itemMoveUnMatched": "Không thể định vị mục. Đã di chuyển đến danh sách vị trí không tìm thấy.",
    "itemWillBeLocated": "Mục sẽ bị xóa khỏi danh sách vị trí trùng lặp.",
    "cannotLocate": "Không thể định vị mục. Xác minh thông tin vị trí.",
    "invalidMessage": "Giá trị không hợp lệ.",
    "rangeMessage": "Giá trị phải ít hơn ${num} ký tự.",
    "locatorError": "Bộ định vị không hợp lệ hoặc không thể truy cập.",
    "notConfigured": "bộ định vị không được cấu hình cho các tùy chọn định vị hiện tại",
    "noMoreLocators": "không có thêm bộ định vị nào được cấu hình"
  },
  "featureToolbar": {
    "locate": "Định vị",
    "save": "Lưu bản ghi",
    "cancel": "Hủy chỉnh sửa",
    "cancelTitle": "Hủy Chỉnh sửa",
    "cancelMessage": "Hủy bỏ các chỉnh sửa cho bản ghi hiện tại?"
  }
});