define({
  "_widgetLabel": "Batch Attribute Editor",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Lagnavn",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Ingen redigerbare lag er konfigurert",
  "editorPopupTitle": "Batch Attribute Editor",
  "editorPopupSaveBtn": "Lagre",
  "editorPopupMultipleValues": "",
  "clear": "Tøm",
  "featuresUpdated": "${0} / ${1} geoobjekt(er) er oppdatert",
  "featuresSelected": "${0} geoobjekt(er) er valgt",
  "featuresSkipped": "Forbigått",
  "featuresNoPermision": "${0} geoobjekt(er) er valgt, men ingen redigeringstillatelse.",
  "search": "Søk",
  "queryInput": "Angi verdien det skal spørres etter",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Angi filteret på riktig måte.",
  "filterPopup": "Filtrer kartlag",
  "filterAppend": "Hvis det allerede eksisterer et filter i webkartet for dette laget",
  "filterAppendOR": "Legg til et uttrykk til eksisterende kartfilter",
  "filterAppendAND": "Legg til alle uttrykk til eksisterende kartfilter",
  "cancel": "Avbryt",
  "noValue": "Ingen verdi",
  "emptyString": "Tom streng",
  "existingValue": "Behold eksisterende verdi",
  "newDate": "Ny dato",
  "valueChooser": "Velg/skriv inn en verdi",
  "ok": "OK",
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihåndspolylinje",
    "extent": "Utstrekning",
    "polygon": "Polygon",
    "freehandPolygon": "Frihåndspolygon",
    "clear": "Tøm",
    "addPointToolTip": "Klikk for å velge i dette området",
    "addShapeToolTip": "Tegn en form for å velge geoobjekter",
    "freehandToolTip": "Trykk og hold for å tegne en form for å velge geoobjekter",
    "startToolTip": "Tegn en form for å velge geoobjekter"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Geoobjektet fra ${0} returnerte en ugyldig ID",
    "noSelectedLayers": "Ingen valgte lag med geoobjekter å oppdatere",
    "inputValueError": "Ugyldig verdi i skjemaet",
    "saveError": "Kan ikke lagre ${0} geoobjekter",
    "requiredValue": "Obligatorisk verdi"
  }
});