define({
  "_widgetLabel": "Геообработка",
  "_featureAction_ReceiveFeatureSet": "Задаване като входни данни на ",
  "requiredInfo": "е задължително.",
  "drawnOnMap": "Резултатът е начертан на картата.",
  "noToolConfig": "Няма налична задача за предварително конфигурирана геообработка.",
  "useUrlForGPInput": "URL адрес",
  "useUploadForGPInput": "Качване на файл",
  "selectFileToUpload": "Избор на файл...",
  "rasterFormat": "Растерен формат на данни",
  "noFileSelected": "Няма избран файл!",
  "uploadSuccess": "Файлът е качен успешно!",
  "showLayerContent": "Показване на съдържание на слой",
  "invalidUrl": "Невалиден URL адрес на услугата за обекта",
  "urlPlaceholder": "URL адрес за достъп до данните",
  "addShapefile": "Добавяне на шейп файл",
  "generateShapefileError": "Грешка при генериране на шейп файл, моля, проверете: ",
  "cleared": "Резултатът беше изчистен.",
  "enlargeView": "Уголемяване на изглед",
  "exportOutput": "Експорт",
  "emptyResult": "Резултатът е празно поле.",
  "useSelectedFeatureset": "Използвайте получения (-те) обект (-и).",
  "closeSelectedFeatureset": "Опция за изчистване и конфигуриране на входни данни.",
  "currentMapExtent": "Текущ ограничаващ правоъгълник на карта",
  "generalize": "Генерализирана геометрия",
  "jsonPlaceholder": "JSON текстов формат на данните",
  "chooseATable": "---Изберете таблица---"
});