define({
  "taskUrl": "URL storitve vidnega polja",
  "portalURL": "Navedite URL vaše organizacije na ArcGIS Online ali na Portal for ArcGIS",
  "portalURLError": "Konfiguriran URL vaše organizacije na ArcGIS Online ali na Portal for ArcGIS ni veljaven.",
  "privilegeError": "Vaša uporabniška vloga ne more opraviti analize. Če želite opraviti analizo, vam mora administrator vaše organizacije odobriti določena dovoljenja <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\"></a>.",
  "noServiceError": "Analizna storitev za višino ni na voljo. Obkljukaj konfiguracije organizacije na ArcGIS Online ali na Portal for ArcGIS.",
  "serviceURLPlaceholder": "Vnesite URL opravila geoprocesiranja vidnega polja",
  "setTask": "Nastavi",
  "setTaskTitle": "Nastavi opravilo geoprocesiranja vidnega polja",
  "serviceURLError": "Opravilo geoprocesiranja, ki ga poskušate konfigurirati s tem pripomočkom, ni veljavno. Izberite veljaven URL opravila geoprocesiranja vidnega polja",
  "defaultMilsForAnglesLabel": "Privzeto nastavi milje za kote",
  "defaultObserverHeightLabel": "Privzeta enota višine opazovalca",
  "defaultObservableDistanceLabel": "Privzeta enota za razdaljo opazovanja",
  "units": {
    "miles": "Milje",
    "kilometers": "Kilometri",
    "feet": "Čevlji",
    "meters": "Metri",
    "yards": "Jardi",
    "nauticalMiles": "Morske milje"
  },
  "helpIconTooltip": "Seznam operativnega sloja je poseljen s sloji iz trenutne spletne karte, ki so poligonske geometrijske vrste.",
  "selectOperationalLayerLabel": "Izberi operativni sloj za rezultate",
  "lineOfSightTabTitle": "Linija vidnosti",
  "symbologyTabTitle": "Simbologija",
  "transparency": "Prosojnost",
  "outline": "Obroba",
  "fill": "Polnilo (barva se uporablja le, če je slog nastavljen na enobarvno polnilo)",
  "style": "Slog",
  "selectOpLayerLabel": "Izberi operativni sloj za rezultate",
  "selectDefaultMeasurementLabel": "Izberi privzeto mersko enoto",
  "visibleSectionLabel": "Vidni razdelek",
  "nonVisibleSectionLabel": "Nevidni razdelek",
  "visibleSectionButtonLabel": "Konfiguriraj nastavitve za vidni razdelek",
  "nonVisibleSectionButtonLabel": "Konfiguriraj nastavitve za nevidni razdelek",
  "colorPicker": "Izbirnik barve",
  "lineStyles": {
    "esriSLSDash": "Črtica",
    "esriSLSDashDot": "Črtica pika",
    "esriSLSDashDotDot": "Črtica pika pika",
    "esriSLSDot": "Pika",
    "esriSLSLongDash": "Dolga črtica",
    "esriSLSLongDashDot": "Dolga črtica pika",
    "esriSLSNull": "Brez vrednosti",
    "esriSLSShortDash": "Kratka črtica",
    "esriSLSShortDashDot": "Kratka črtica pika",
    "esriSLSShortDashDotDot": "Kratka črtica pika pika",
    "esriSLSShortDot": "Kratka pika",
    "esriSLSSolid": "Polno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Nazaj",
    "esriSFSCross": "Križec",
    "esriSFSDiagonalCross": "Diagonalno",
    "esriSFSForwardDiagonal": "Naprej",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Brez vrednosti",
    "esriSFSSolid": "Polno",
    "esriSFSVertical": "Vertikalno"
  }
});