define({
  "_widgetLabel": "Urednik atributa grupe",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Ime sloja",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Nema konfigurisanih slojeva koji su mogu da se menjaju",
  "editorPopupTitle": "Urednik atributa grupe",
  "editorPopupSaveBtn": "Sačuvaj",
  "editorPopupMultipleValues": "",
  "clear": "Izbriši",
  "featuresUpdated": "${0} / ${1} geoobjekat(a) ažuriran(o)",
  "featuresSelected": "${0} geoobjekat(a) izabrano",
  "featuresSkipped": "Preskočeno",
  "featuresNoPermision": "${0}geoobjekat/geoobjekti odabran(i), ali bez dozvole za uređivanje.",
  "search": "Pretraži",
  "queryInput": "Unesite vrednost za upit",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Pravilno postavite filter.",
  "filterPopup": "Sloj filtera",
  "filterAppend": "Ako filter već postoji na veb mapi za ovaj sloj",
  "filterAppendOR": "Dodajte bilo koji izraz u postojeći filter mape",
  "filterAppendAND": "Dodajte sve izraze u postojeći filter mape",
  "cancel": "Otkaži",
  "noValue": "Nema vrednosti",
  "emptyString": "Prazan string",
  "existingValue": "Koristi postojeću vrednost",
  "newDate": "Novi podaci",
  "valueChooser": "Izaberite/unesite vrednost",
  "ok": "U redu",
  "drawBox": {
    "point": "Tačka",
    "line": "Linija",
    "polyline": "Polilinija",
    "freehandPolyline": "Polilinija slobodnom rukom",
    "extent": "Obuhvat",
    "polygon": "Poligon",
    "freehandPolygon": "Poligon slobodnom rukom",
    "clear": "Izbriši",
    "addPointToolTip": "Kliknite da biste izabrali u okviru ove površine",
    "addShapeToolTip": "Nacrtajte oblik da bi selektovali geoobjekte",
    "freehandToolTip": "Pritisnite i držite da biste nacrtali oblik za selekciju geoobjekata",
    "startToolTip": "Nacrtajte oblik da biste selektovali geoobjekte"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Geoobjekat od ${0} je vratio nevažeći ID",
    "noSelectedLayers": "Nema izabranih slojeva sa zapisima za ažuriranje",
    "inputValueError": "Nevažeća vrednost u obrascu",
    "saveError": "Nije moguće sačuvati ${0} geoobjekte",
    "requiredValue": "Zahtevana vrednost"
  }
});