define({
  "locatorUrl": "URL lokatora",
  "set": "Postavi",
  "locatorName": "Naziv lokatora",
  "locatorExample": "Primjer",
  "countryCode": "Pozivni broj za državu ili regiju",
  "eg": "npr. ",
  "countryCodeHint": "Ako ostavite ovu vrijednost praznom, pretražit će se sve države i regije",
  "minCandidateScore": "Minimalni rezultat kandidata",
  "minCandidateScoreHint": "Ako ostavite ovu vrijednost praznom, upotrijebit će se minimalni rezultat kandidata 90",
  "enableSingleField": "Opcije jednog polja",
  "singleFieldHint": "Podaci o adresi bit će u jednom polju",
  "enableMultiField": "Opcije više polja",
  "multiFieldHint": "Podaci o adresi bit će u više polja",
  "enableXYField": "Opcije polja X/Y",
  "xyFieldHint": "Podaci će sadržavati vrijednosti X/Y koordinata",
  "instructionGeocode": "Dodaj i konfiguriraj usluge lokatora.",
  "invalidUrlTip": "URL ${URL} nije valjan ili dostupan.",
  "geocodeTabLabel": "Postavke lokacije",
  "lookupList": "Nazive polja koje je potrebno prepoznati",
  "isRecognized": "Nazivi polja u tablici u nastavku automatski se prepoznaju za ovo polje",
  "needsEditablePointLayers": "Web-karta mora sadržavati barem jedan točkasti sloj koji se može uređivati.",
  "editpageAlias": "Alias",
  "configureFields": "Konfiguriraj polja sloja",
  "configureSingleFields": "Konfiguracija jednog polja adresa",
  "configureMultiFields": "Konfiguracija više polja adresa",
  "configureXYFields": "Konfiguriraj X/Y polja",
  "noFields": "Upotrijebite radnju uređivanja kako bi definirali jedno ili više polja za prikaz",
  "display": "Prikaži",
  "duplicate": "Pronađi duplikat",
  "duplicateTip": "Pretražite ovo polje za identične vrijednosti između izvorne datoteke i ciljanog sloja ./n Kada se pronađe identična podudarnost, zapis iz datoteke neće se nalaziti i označit će se kao duplikat.",
  "noSelectField": "Prvo odaberite opciju Sloj značajki",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Geografska dužina)",
  "xyFieldsLabelY": "Y (Geografska širina)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Istočno",
  "northing": "Sjeverno",
  "lon": "DUŽINA",
  "lat": "ŠIRINA",
  "layerOptionHint": "Odaberite sloj na koji ćete predati podatke.",
  "layerFieldTitle": "Ciljni sloj",
  "tempSymbolHint": "Odaberite simbol koji će se koristiti za prikazivanje značajki.",
  "tempSymbolTitle": "Simbol prikaza",
  "maxRecords": "Maksimalni broj zapisa",
  "maxRecordsHint": "Maksimalni broj zapisa za lociranje",
  "searchRadius": "Polumjer pretraživanja",
  "searchRadiusHint": "Udaljenost za pretraživanje dupliciranih geoobjekata u sloju",
  "requiresInteger": "Unesite brojčanu vrijednost.",
  "requiresInteger0100": "Unesite brojčanu vrijednost između 0 i 100",
  "requiresLocator": "Dodajte barem jedan valjani lokator.",
  "layerFields": "Postavke sloja",
  "layerFieldsHint": "Odredite polja iz Ciljnog polja koja će biti mapirana na izvorna polja.",
  "locatorError": "Lokator nije valjan ili nije dostupan.",
  "optionNotMatch": "Opcije polja nisu konzistentne kroz lokatore. Pričuvni sustav možda neće raditi u skladu s očekivanjima.",
  "targetLayerTabTitle": "Ciljni sloj",
  "locationSettingsTabTitle": "Postavke lokacije",
  "generalSettingsTabTitle": "Opće postavke",
  "addTargetLayersLabel": "Dodaj ciljni sloj",
  "introductoryText": "Kreirajte instruktivni sadržaj za widget",
  "defaultStartPageInstructions": "Ovaj widget će pomoći pri obradi i predaji podataka iz datoteke na odabrani sloj na mapi.<br/> <br/> Vrijednosti unutar datoteke moraju biti ograničene zarezom, tabom, točkom sa zarezom ili uspravnom trakom.",
  "noTargetLayerConfiguredErrorMsg": "Nijedan ciljni sloj nije konfiguriran",
  "noFieldsForTargetLayer": "Postavke sloja nisu definirane za ciljni sloj",
  "locationSettingsNotConfigured": "Lokacijske postavke nisu pravilno konfigurirane"
});