define({
  "_widgetLabel": "Проследяване на мрежата",
  "_featureAction_NetworkTraceSkip": "Пропускане при проследяване",
  "_featureAction_NetworkTraceUnskip": "Изтриване от местоположения за пропускане",
  "removedFromSkipLocations": "Изтрито от местоположения за пропускане",
  "alreadyRemovedFromSkipLocations": "Вече е изтрито от местоположения за пропускане",
  "locationSkipped": "Местоположението е пропуснато",
  "configError": "Изпълнимият модул не е конфигуриран правилно.",
  "geometryServiceURLNotFoundMSG": "Не може да се получи URL адрес на услуга за геометрия",
  "clearButtonValue": "Изчистване",
  "GPExecutionFailed": "Проследяването не може да бъде завършено. Моля, опитайте отново.",
  "backButtonValue": "Назад",
  "exportToCSVSuccess": "Експортирането към CSV е завършено успешно.",
  "lblInputLocTab": "Въвеждане на местоположения",
  "lblBlockLocTab": "Блокиране не местоположения",
  "lblInputLocation": "Входни данни за обект",
  "lblBlockLocation": "Блокиране на обект",
  "lblInputLocHeader": "Въвеждане на местоположения (0)",
  "lblBlockLocHeader": "Блокиране не местоположения (0)",
  "inputTabTitle": "Въвеждане",
  "outputTabTitle": "Извеждане",
  "exportSelectAllCheckBoxLabel": "Избиране на всички",
  "lblSkipLocHeader": "Пропускане на местоположения (0)",
  "lblSkipLocation": "Местоположение",
  "lblSkipLocTab": "Местоположения за пропускане",
  "skipAllLocationButtonLabel": "Пропускане на всички местоположения",
  "confirmSkipAllLocationsMessage": "Всички местоположения ще бъдат пропуснати, желаете ли да продължите?",
  "locationAlreadySkippedMessage": "Местоположението вече е пропуснато",
  "removeAllSkipLocationLabel": "Изтриване на всички",
  "newProjectOptionText": "Нов проект",
  "selectProject": "Избиране на проект",
  "saveButtonLabel": "Запис",
  "exportToCSVText": "Експортиране към CSV",
  "editProjectAttributesToolTip": "Редактиране на атрибути на проект",
  "projectNameLabel": "Име на проект",
  "saveProjectPopupTitle": "Запис",
  "saveAsLabel": "Запазване като",
  "saveChangesMsg": "Искате ли да запазите промените в <b>${loadProjectDropdownlabel}</b> или да ги запазите като нов проект?",
  "creatingNewProjectErrorMessage": "Грешка при създаването на нов проект. Моля, опитайте отново.",
  "projectNameFetchingErr": "Грешка при извличане на имена на съществуващ проект. Моля, опитайте отново.",
  "projectAttributeLoadingErr": "Грешка при зареждане на атрибутите на проекта. Моля, опитайте отново.",
  "attributeUpdatedMsg": "Атрибутите са заредени успешно.",
  "projectAttributeUpdatingErr": "Грешка при обновяване на атрибутите на проекта.",
  "loadingProjectDetailsErrorMessage": "Грешка при извличане на флагове, бариери и пропускане на местоположения. Моля, опитайте отново.",
  "savingProjectDetailsErr": "Грешка при запазване на подробните данни на проекта. Моля, опитайте да запазите проекта отново.",
  "updatingOutagePolygonErr": "Грешка при обновяване на прекъсване на полигон. Моля, опитайте да запазите проекта отново.",
  "deletingExistingPolygonErr": "Грешка при изтриване на прекъсване на съществуващ полигон. Моля, опитайте да запазите проекта отново.",
  "loadingProjectFeaturesErr": "Грешка при зареждане на обектите в проекта. Моля, опитайте да заредите проекта отново.",
  "addingProjectFeaturesErr": "Грешка при добавяне на обектите в проекта. Моля, опитайте да запазите проекта отново.",
  "deletingExistingProjectFeaturesErr": "Грешка при изтриване на обектите от съществуващ проект. Моля, опитайте да запазите проекта отново.",
  "projectNotFoundErr": "Проектът не е открит",
  "projectLayersNotFound": "Конфигурираните слоеве за настройки на проекта не са налични в картата. Изпълнимият модул ще бъде зареден в режим „Скица“.",
  "fetchingOutagePolygonMessage": "Грешка при извличане на прекъсване на полигон. Моля, опитайте да заредите проекта отново.",
  "projectNameExistsMessage": "Името на проекта вече съществува. Моля, използвайте уникално име на проект.",
  "fetchingProjectNamesErrorMessage": "Грешка при извличане на имена на съществуващ проект. Моля, опитайте да запазите проекта отново.",
  "enterProjectNameMessage": "Моля, въведете име на проекта.",
  "projectLengthErrorMessage": "Името на проекта не може да бъде по-дълго от",
  "gpServiceNotAccessible": "Вашият акаунт няма достъп до необходимата услуга за извършване на това проследяване.",
  "loadingClonedLayerErrorMessage": "Грешка при зареждането на клонирания слой с обекти. Моля, опитайте отново.",
  "addingFeatureInClonedLayerError": "Грешка при добавяне на графики в клонирания слой с обекти. Моля, опитайте отново.",
  "selectingFeatureInClonedLayerError": "Грешка при избора на графика в клониран слой с обекти. Моля, опитайте отново.",
  "filteredProjectError": "Грешка при проверка на извличането на филтрирани подробности за проекта. Моля, опитайте отново.",
  "filteredProjectMessage": "Избраните атрибути на проекта не са налични поради приложените филтри от уеб картата или друг изпълним модул. Изчистете филтъра (-те) и опитайте отново.",
  "filteredProjectLoadMessage": "Вашият проект вече не е наличен. Моля, изберете активен проект.",
  "defaultValueForRunButton": "Стартиране",
  "closeButtonLabel": "Изтриване"
});