define({
  "_widgetLabel": "المحرر الذكي",
  "_featureAction_SmartEditor": "المحرر الذكي",
  "noEditPrivileges": "لا يحتوي حسابك على أذونات لإنشاء أو تعديل البيانات.",
  "loginPopupTitle": "تسجيل الدخول",
  "loginPopupMessage": "يتطلب ${widgetName} أذونات واعتمادات للبحث عن معلومات العنوان وتخزينها. هل ترغب في تسجيل الدخول واستخدام هذه الإمكانية؟",
  "noCreditsOrPrivilegeWarningMessage": "لا يتضمن حسابك الأذونات والاعتمادات للبحث عن معلومات العنوان وتخزينها باستخدام ${widgetName}. يرجى الاتصال بمسؤول المؤسسة التابع لك لطلب الأذونات والاعتمادات. انقر فوق موافق لمتابعة التحرير.",
  "unableToUseLocator": "محدد المواقع لا يمكن الوصول إليه. لن يتم تنفيذ إجراءات سمات العنوان. انقر فوق موافق لمتابعة التحرير.",
  "locatorDisabledWaning": "محدد المواقع غير ممكّن. يرجى الاتصال بمسؤول المؤسسة التابع لك لطلب هذه الإمكانية. انقر فوق موافق لمتابعة التحرير.",
  "noFeatureInAIWarning": "لم يتم تحديد أي معالم. يرجى تحديد معلم لإجراء تعديلات أو انقر فوق إلغاء للعودة إلى الشاشة الرئيسية.",
  "noEditableLayerWarning": "لا يتضمن حسابك الإذن لإنشاء البيانات أو تعديلها أو أن خريطة الويب الحالية لا تتصمن أي طبقات قابلة للتحرير.",
  "noVisibleCreateLayerWarning": "الطبقات غير مرئية في مستوى التكبير/التصغير الحالي. تكبير أو تصغير لإنشاء/تعديل المعالم.",
  "noVisibleUpdateLayerWarning": "الطبقات غير مرئية في مستوى التكبير/التصغير الحالي. تكبير أو تصغير لتعديل المعالم.",
  "checkLayerVisibilityInWebMapWarning": "تأكد من أن الطبقات مرئية في الخريطة لإنشاء المعالم أو تعديلها.",
  "showSelectionInAITitle": "المعالم المحددة",
  "showSelectionInAIMsg": "هل تريد تحميل التحديد الحالي في ${widgetName}؟",
  "widgetActive": "نشط",
  "widgetNotActive": "غير نشط",
  "pressStr": "اضغط ",
  "ctrlStr": " CTRL ",
  "snapStr": " لتمكين الالتقاط",
  "noAvailableTempaltes": "لا توجد أي قوالب",
  "editorCache": " - ذاكرة التخزين المؤقت للمحرر",
  "presetFieldAlias": "حقل",
  "presetValue": "قيمة معينة مُسبقًا",
  "usePresetValues": " استخدم قيمة معينة مسبقًا (المعالم الجديدة فقط)",
  "editGeometry": " تحرير الشكل الهندسي",
  "savePromptTitle": "حفظ المعلم",
  "savePrompt": "هل تريد حفظ المعلم الحالي؟",
  "deletePromptTitle": "حذف المعلم",
  "deleteAttachment": "حذف المرفق",
  "deletePrompt": "هل أنت متأكد من رغبتك في حذف المعالم المحددة؟",
  "attachmentLoadingError": "خطأ في تحميل المرفقات",
  "attachmentSaveDeleteWarning": "تحذير: يتم حفظ التغييرات على المرفقات تلقائيًا",
  "autoSaveEdits": "حفظ المعالم الجديدة تلقائيًا",
  "addNewFeature": "إنشاء معلم جديد",
  "featureCreationFailedMsg": "يتعذر إنشاء سجل/معلم جديد",
  "relatedItemTitle": "الطبقة/الجدول ذي الصلة",
  "relatedFeatureCount": "${layerTitle} مع ${featureCount} من المعالم",
  "createNewFeatureLabel": "إنشاء معلم جديد لـ ${layerTitle}",
  "invalidRelationShipMsg": "يرجى التأكد من أن حقل المفتاح الرئيسي '${parentKeyField}' يحتوي على قيمة صحيحة",
  "pendingFeatureSaveMsg": "يرجى إدخال عمليات تحرير المعلم قبل إنشاء معلم ذي صلة.",
  "attachmentsRequiredMsg": "(*) المرفقات مطلوبة.",
  "coordinatePopupTitle": "تحريك معلم إلى موقع XY",
  "coordinatesSelectTitle": "نظام الإحداثيات:",
  "mapSpecialReferenceDropdownOption": "الإسناد المكاني للخريطة",
  "latLongDropdownOption": "دائرة العرض/خط الطول",
  "mgrsDropdownOption": "نظام إسناد الشبكة العسكرية (MGRS)",
  "mgrsTextBoxLabel": "الإحداثيات:",
  "xAttributeTextBoxLabel": "إحداثيات X:",
  "yAttributeTextBoxLabel": "أحداثيات Y:",
  "latitudeTextBoxLabel": "خط عرض:",
  "longitudeTextBoxLabel": "خط طول:",
  "presetGroupFieldsLabel": "ستُطبق \"${groupName}\" على حقول الطبقة التالية:",
  "presetGroupNoFieldsLabel": "لا تتضمن \"${groupName}\" أي حقول مرتبطة",
  "groupInfoLabel": "معلومات مجموعة \"${groupName}\"",
  "editGroupInfoIcon": "تحرير قيمة مجموعة ${groupName}",
  "filterEditor": {
    "all": "الكل",
    "noAvailableTempaltes": "لا توجد أي قوالب",
    "searchTemplates": "البحث في القوالب",
    "filterLayerLabel": "تصفية الطبقات"
  },
  "invalidConfiguration": "لم يتم تكوين عنصر واجهة المستخدم أو أن الطبقات التي توجد في التكوين لم تُعد موجودة في الخريطة. يرجى فتح التطبيق في وضع المُنشئ وإعادة تكوين عنصر واجهة المستخدم.",
  "geometryServiceURLNotFoundMSG": "يتعذر الحصول على عنوان URL لخدمة الشكل الهندسي",
  "clearSelection": "إغلاق",
  "refreshAttributes": "تحديث البيانات الجدولية الديناميكية للمعلم",
  "automaticAttributeUpdatesOn": "تحديث البيانات الجدولية للمعلم تلقائياً: تشغيل",
  "automaticAttributeUpdatesOff": "تحديث البيانات الجدولية للمعلم تلقائياً: إيقاف",
  "moveSelectedFeatureToGPS": "تحريك المعلم المحدد إلى موقع GPS الحالي",
  "moveSelectedFeatureToXY": "تحريك المعلم المحدد إلى موقع XY",
  "mapNavigationLocked": "تنقل الخريطة: مقفول",
  "mapNavigationUnLocked": "تنقل الخريطة: مفتوح",
  "copyFeatures": {
    "title": "تحديد المعالم المطلوب نسخها",
    "createFeatures": "إنشاء معالم",
    "createSingleFeature": "إنشاء معلم واحد متعدد الأجزاء",
    "createOneSingleFeature": "إنشاء معلم",
    "noFeaturesSelectedMessage": "لا توجد معالم مُحددة",
    "selectFeatureToCopyMessage": "يرجى تحديد المعالم المطلوب نسخها",
    "multipleFeatureSaveWarning": "إنشاء معالم متعددة باستخدام هذه الوظيفة سيحفظ كل المعالم الجديدة على الفور. لا يتم دعم مطابقة الحقول عند إنشاء معلم جديد متعدد الأجزاء.",
    "copyFeatureUpdateGeometryError": "يتعذر تحديث الشكل الهندسي للمعالم المحددة",
    "canNotSaveMultipleFeatureWarning": "يمكنك نسخ معلم واحد فقط عندما تحتوي طبقة النقطة الهدف على حقول قيمة فريدة.",
    "createOnlyOneMultipartFeatureWarning": "يمكنك فقط نسخ معلم واحد أو إنشاء معلم واحد متعدد الأجزاء عندما تحتوي الطبقة الهدف على حقول قيمة فريدة.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "تم تحديد ${layerName} ${selectedFeatures} من ${totalFeatures} من المعالم"
  },
  "addingFeatureError": "حدث خطأ أثناء إضافة المعالم المحددة في الطبقة. الرجاء إعادة المحاولة مرة أخرى.",
  "addingFeatureErrorCount": "فشل نسخ ${copyFeatureErrorCount} من المعالم. هل ترغب في المحاولة مرة أخرى من أجل المعالم المفقودة؟",
  "selectingFeatureError": "حدث خطأ أثناء تحديد المعالم في الطبقة. الرجاء إعادة المحاولة مرة أخرى.",
  "customSelectOptionLabel": "تحديد المعالم المطلوب نسخها",
  "copyFeaturesWithPolygon": "نسخ باستخدام مضلع",
  "copyFeaturesWithRect": "نسخ باستخدام مستطيل",
  "copyFeaturesWithLasso": "نسخ بواسطة التحديد الحر",
  "noFeatureSelectedMessage": "لا توجد معالم محددة",
  "multipleFeatureSaveMessage": "سيتم حفظ جميع المعالم على الفور. هل تريد المتابعة؟",
  "relativeDates": {
    "dateTypeLabel": "نوع التاريخ",
    "valueLabel": "قيمة",
    "fixed": "ثابت",
    "current": "حالي",
    "past": "ماضي",
    "future": "مستقبل",
    "popupTitle": "تحديد قيمة",
    "hintForFixedDateType": "تلميح: سيُستخدم التاريخ والوقت المحددين كقيمة إعداد مسبق افتراضية.",
    "hintForCurrentDateType": "تلميح: سيُستخدم التاريخ والوقت الحاليين كقيمة إعداد مسبق افتراضية.",
    "hintForPastDateType": "تلميح: ستطرح القيمة المحددة من التاريخ والوقت الحاليين للقيمة الافتراضية للإعداد المسبق.",
    "hintForFutureDateType": "تلميح: ستضاف القيمة المحددة إلى التاريخ والوقت الحاليين للقيمة الافتراضية للإعداد المسبق.",
    "noDateDefinedTooltip": "لا توجد بيانات محددة",
    "relativeDateWarning": "يجب تحديد قيمة للتاريخ أو الوقت لتتمكن من حفظ القيمة الافتراضية المحددة مسبقًا.",
    "customLabel": "تخصيص",
    "layerLabel": "الطبقة",
    "domainFieldHintLabel": "القيمة المحددة هي مجال قيمة مرمزة. القيمة: سيتم استخدام \"${domainValue}\""
  },
  "valuePicker": {
    "popupTitle": "تحديد قيمة",
    "popupHint": "يتقاطع المعلم الحالي مع معالم متعددة، اختر قيمة للحقل المعني",
    "buttonTooltip": "تحديد قيمة من معالم متعددة متقاطعة"
  },
  "uniqueValueErrorMessage": "القيمة في \"${fieldName}\" موجودة بالفعل، يرجى تقديم قيمة جديدة.",
  "requiredFields": {
    "displayMsg": "لا يمكن ترك الحقول المطلوبة فارغة. أدخل قيم الحقول المشتركة أدناه.",
    "popupTittle": "الحقول المطلوبة",
    "foundNullRecordCount": "${fieldName} (تم العثور عليها في ${count} سجلاً)"
  },
  "fieldsMapping": {
    "popupTittle": "تطبيق مطابقة الحقل",
    "fieldsMatchingCheckboxLabel": "تتجاوز القيمة (القيم) من المعالم المنسوخة القيمة (القيم) الافتراضية في الحقل (الحقول) الهدف",
    "resetLabel": "إعادة تعيين",
    "clearLabel": "مسح",
    "fieldsInTargetLayerLabel": "الهدف",
    "fieldsInSourceLayerLabel": "المصدر",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} حقول مطابقة)",
    "selectSourceFieldLabel": "- تحديد -",
    "selectFieldAriaLabel": "تحديد حقل المصدر للحقل الهدف ${targetField}",
    "informativeText": "راجع الحقول المطابقة من المصدر إلى الهدف وقم بتخصيصها إذا لزم الأمر.",
    "dynamicValueText": "تم تعيين قيمة ديناميكية",
    "noFieldsToMatchLabel": "لا توجد حقول للمطابقة"
  },
  "cantLocateUserLocation": "لا يمكن تحديد موقعك",
  "tryAgainButtonLabel": "إعادة المحاولة",
  "copyFeatureFailedPopupTitle": "للأسف!"
});