define({
  "feedbackStyleLabel": "Στιλ σχολίων για αποστάσεις και κατευθύνσεις",
  "showTabLabel": "Εμφάνιση όλων των καρτελών",
  "tabErrorMessage": "Επιλέξτε τουλάχιστον μία καρτέλα στην ομάδα \"Στιλ Σχολίων Απόστασης και Κατεύθυνσης\"",
  "lineLabel": "Γραμμή",
  "circleLabel": "Κύκλος",
  "ellipseLabel": "Έλλειψη",
  "ringsLabel": "Δακτύλιοι",
  "transparency": "Διαφάνεια",
  "operationalLineLayerSelectLabel": "Επιλέξτε ένα λειτουργικό θεματικό επίπεδο πολυγραμμής για αποτελέσματα σε γραμμές και δακτυλίους.",
  "operationalPolygonLayerSelectLabel": "Επιλέξτε ένα λειτουργικό θεματικό επίπεδο πολυγώνου για αποτελέσματα σε κύκλους και έλλειψη.",
  "helpIconPolylineTooltip": "Η λίστα των λειτουργικών θεματικών επιπέδων συμπληρώνεται με θεματικά επίπεδα τύπου γεωμετρίας πολυγραμμής από τον τρέχοντα web χάρτη.",
  "helpIconPolygonTooltip": "Η λίστα των λειτουργικών θεματικών επιπέδων συμπληρώνεται με θεματικά επίπεδα τύπου γεωμετρίας πολυγώνου από τον τρέχοντα web χάρτη.",
  "feedbackResultsLayerLabel": "Θεματικό Επίπεδο Αποτελεσμάτων Σχολίων Απόστασης και Κατεύθυνσης",
  "editSymbologyHint": "Υπόδειξη: Κάντε κλικ στο εικονίδιο προεπισκόπησης για να επεξεργαστείτε το συμβολισμό",
  "feedbackTextColorLabel": "Χρώμα κειμένου ετικέτας σχολίων",
  "feedbackTextSizeLabel": "Μέγεθος κειμένου ετικέτας σχολίων",
  "previewLabel": "Προεπισκόπηση",
  "lineSymbologyPopupTittle": "Συμβολισμός γραμμής",
  "circleSymbologyPopupTittle": "Συμβολισμός κύκλου",
  "ellipseSymbologyPopupTittle": "Συμβολισμός έλλειψης",
  "ringSymbologyPopupTittle": "Συμβολισμός δακτυλίων"
});