define({
  "feedbackStyleLabel": "距離和方向回饋樣式",
  "showTabLabel": "顯示所有頁籤",
  "tabErrorMessage": "請在「距離和方向回饋樣式」群組中至少選擇一個頁籤",
  "lineLabel": "線",
  "circleLabel": "圓形",
  "ellipseLabel": "橢圓",
  "ringsLabel": "圓環",
  "transparency": "透明度",
  "operationalLineLayerSelectLabel": "選擇線和環結果的操作折線圖層",
  "operationalPolygonLayerSelectLabel": "選擇圓形和橢圓結果的操作多邊形圖層",
  "helpIconPolylineTooltip": "會在操作圖層清單中，填入折線幾何類型的現行 Web 地圖中的圖層。",
  "helpIconPolygonTooltip": "會在操作圖層清單中，填入多邊形幾何類型的現行 Web 地圖中的圖層。",
  "feedbackResultsLayerLabel": "距離和方向回饋結果圖層",
  "editSymbologyHint": "提示: 按一下預覽圖示以編輯符號系統",
  "feedbackTextColorLabel": "回饋標籤文字顏色",
  "feedbackTextSizeLabel": "回饋標籤文字大小",
  "previewLabel": "預覽",
  "lineSymbologyPopupTittle": "線符號系統",
  "circleSymbologyPopupTittle": "圓符號系統",
  "ellipseSymbologyPopupTittle": "橢圓符號系統",
  "ringSymbologyPopupTittle": "環符號系統"
});