define({
  "locatorUrl": "Posisjonsindikator-URL",
  "set": "Angi",
  "locatorName": "Navn på posisjonsindiktaor",
  "locatorExample": "Eksempel",
  "countryCode": "Lands- eller regionskode(r)",
  "eg": "f.eks. ",
  "countryCodeHint": "Hvis du lar dette feltet stå tomt, søkes det i alle land og regioner",
  "minCandidateScore": "Minste kandidatpoengsum",
  "minCandidateScoreHint": "Hvis du lar feltet stå tomt, brukes en kandidatpoengsum på 90",
  "enableSingleField": "Alternativer for ett felt",
  "singleFieldHint": "Adressedata vil være i ett felt",
  "enableMultiField": "Alternativer for flere felt",
  "multiFieldHint": "Adressedata vil være i flere felt",
  "enableXYField": "Alternativer for X/Y-felt",
  "xyFieldHint": "Data vil inneholde X/Y-koordinatverdier",
  "instructionGeocode": "Legg til og konfigurer posisjonstjenester.",
  "invalidUrlTip": "URL-en ${URL} er ugyldig eller ikke tilgjengelig.",
  "geocodeTabLabel": "Lokasjonsinnstillinger",
  "lookupList": "Feltnavn som skal gjenkjennes",
  "isRecognized": "Feltnavnene i tabellen nedenfor gjenkjennes automatisk for dette feltet",
  "needsEditablePointLayers": "Webkartet må inneholde minst ett redigerbart punktlag.",
  "editpageAlias": "Alias",
  "configureFields": "Konfigurer felter for lagene",
  "configureSingleFields": "Konfigurer ett adressefelt",
  "configureMultiFields": "Konfigurer flere adressefelt",
  "configureXYFields": "Konfigurer X/Y-felt",
  "noFields": "Bruk redigeringshandlingen til å definere ett eller flere felt som skal vises",
  "display": "Vis",
  "duplicate": "Finn duplikat",
  "duplicateTip": "Søk i dette feltet etter verdier som er identiske i kildefilen og mållaget./n Når et identisk treff blir funnet, blir posten fra filen ikke lokalisert og den merkes som duplikat.",
  "noSelectField": "Velg alternativet for geooobjektlag først",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (lengdegrad)",
  "xyFieldsLabelY": "Y (breddegrad)",
  "xyFieldsX": "X",
  "xyFieldsY": "J",
  "easting": "Easting",
  "northing": "Northing",
  "lon": "Lengdegr.",
  "lat": "Breddegr.",
  "layerOptionHint": "Velg laget det skal sendes data til.",
  "layerFieldTitle": "Mållag",
  "tempSymbolHint": "Velg symbolet som skal brukes til å vise geoobjektene.",
  "tempSymbolTitle": "Vis symbol",
  "maxRecords": "Maks. antall poster",
  "maxRecordsHint": "Maks. antall poster som skal lokaliseres",
  "searchRadius": "Søkeradius",
  "searchRadiusHint": "Radius for søk etter dupliserte geoobjekter fra laget",
  "requiresInteger": "Angi en numerisk verdi.",
  "requiresInteger0100": "Angi en numerisk verdi mellom 0 og 100",
  "requiresLocator": "Legg til minst én gyldig posisjonsindikator.",
  "layerFields": "Laginnstillinger",
  "layerFieldsHint": "Angi feltene i mållaget som skal tilordnes kildefeltene.",
  "locatorError": "Posisjonsindikatoren er ugyldig eller utilgjengelig.",
  "optionNotMatch": "Feltalternativene er ikke konsekvente på tvers av posisjonsindikatorer. Failover fungerer kanskje ikke som forventet.",
  "targetLayerTabTitle": "Mållag",
  "locationSettingsTabTitle": "Lokasjonsinnstillinger",
  "generalSettingsTabTitle": "Generelle innstillinger",
  "addTargetLayersLabel": "Legg til mållag",
  "introductoryText": "Opprett innhold med instruksjoner for miniprogrammet",
  "defaultStartPageInstructions": "Dette miniprogrammet gjør det enklere å behandle og sende data fra en fil til laget som er valgt i kartet.<br/> <br/> Verdiene i filen må være skilt med komma, tabulator, semikolon eller loddrett strek.",
  "noTargetLayerConfiguredErrorMsg": "Det er ikke konfigurert et mållag",
  "noFieldsForTargetLayer": "Det er ikke definert laginnstillinger for mållaget",
  "locationSettingsNotConfigured": "Lokasjonsinnstillingene er ikke riktig konfigurert"
});