define({
  "_widgetLabel": "위협 분석",
  "threatAnalysisMainPageTitle": "JCAT 테러 예방 대책 가이드 기반",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "입력 위치",
  "interactive": "대화형",
  "fromCoord": "고정된 좌표",
  "existingFeature": "기존 피처에서",
  "threatAnalysisCoordInputLabel": "위협 위치",
  "enterCoords": "좌표 입력",
  "threatAddPointToolTip": "위협 위치 추가",
  "threatDrawPointToolTip": "위협 위치를 추가하려면 클릭",
  "threatType": "위협 유형",
  "threatPlaceholder": "위협 검색을 위한 입력 시작",
  "zoneTypeLabel": "구역 유형",
  "feetLabel": "피트",
  "metersLabel": "미터",
  "unitsLabel": "단위",
  "threatGraphicLayer": "위협 그래픽",
  "style": "스타일",
  "settingsTitle": "설정",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "대시",
    "esriSLSDashDot": "대시 점",
    "esriSLSDashDotDot": "대시 점 점",
    "esriSLSDot": "점",
    "esriSLSLongDash": "긴 대시",
    "esriSLSLongDashDot": "긴 대시 점",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "짧은 대시",
    "esriSLSShortDashDot": "짧은 대시 점",
    "esriSLSShortDashDotDot": "짧은 대시 점 점",
    "esriSLSShortDot": "짧은 점",
    "esriSLSSolid": "실선"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "뒤로",
    "esriSFSCross": "십자모양",
    "esriSFSDiagonalCross": "대각선",
    "esriSFSForwardDiagonal": "순방향",
    "esriSFSHorizontal": "수평",
    "esriSFSNull": "Null",
    "esriSFSSolid": "실선",
    "esriSFSVertical": "수직"
  },
  "resultsTitle": "결과",
  "publishTABtn": "발행",
  "layerName": "발행된 레이어 이름",
  "invalidLayerName": "레이어 이름에는 영숫자 문자와 밑줄만 포함해야 함",
  "missingLayerNameMessage": "발행하려면 먼저 올바른 레이어 이름을 입력해야 함",
  "publishingFailedLayerExists": "발행 실패: 이름이 {0}인 피처 서비스가 이미 있습니다. 다른 레이어 이름을 선택하세요.",
  "checkService": "서비스 확인: [0]",
  "createService": "서비스 생성: [0]",
  "unableToCreate": "생성할 수 없음: {0}",
  "addToDefinition": "정의에 추가: {0}",
  "successfullyPublished": "웹 레이어가 발행됨",
  "successfullyAppended": "새 피처가 웹 레이어에 추가됨",
  "manageWebLayerText": "웹 레이어 관리",
  "userRole": "사용자에게 권한이 없어 서비스를 생성할 수 없음",
  "retrieveExistingLayerError": "{0}을(를) 검색할 수 없습니다. 다른 레이어 이름을 사용하여 발행하세요.",
  "publishToNewLayer": "새 피처 레이어에 결과 발행",
  "layerNameExists": "레이어 이름이 이미 존재합니다. 다른 레이어 이름을 사용하세요.",
  "pipeBombLabel": "파이프 폭탄",
  "suicideBombLabel": "자살 폭탄",
  "briefcaseLabel": "서류 가방",
  "carLabel": "자동차",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "소형 배송 트럭",
  "containerWaterTruckLabel": "컨테이너/급수 트럭",
  "semiTrailerLabel": "세미 트레일러",
  "transparencyLabel": "투명도",
  "outline": "윤곽선",
  "fill": "채우기(스타일이 솔리드로 설정된 경우에만 색상이 적용됨)",
  "createBtn": "구역 생성",
  "clearBtn": "지우기",
  "invalidNumberMessage": "입력한 값이 올바르지 않음",
  "invalidRangeMessage": "값은 0보다 커야 함",
  "parseCoordinatesError": "좌표를 분석할 수 없습니다. 입력을 확인하세요.",
  "selectDrawModeLabel": "그리기 모드 선택",
  "selectFeatureLabel": "이 레이어에서 피처 선택",
  "smallLPGTank": "소형 LPG 탱크",
  "largeLPGTank": "대형 LPG 탱크",
  "commercialResidentialLPGTank": "상업용/주거용 LPG 탱크",
  "smallLPGTruck": "소형 LPG 트럭",
  "semiTankerLPG": "세미 탱커 LPG",
  "zoneDescriptionColLabel": "영역 설명",
  "distanceColLabel": "거리",
  "zoneDescColLabel": "영역 설명",
  "descriptionLabel": "설명",
  "editThreatZonePopupLabel": "위협 영역 심볼 편집",
  "symbologyColLabel": "심볼",
  "actions": "동작",
  "threatTypeSelectLabel": "위협 유형 선택:",
  "distanceLabel": "거리(${unitAbbr})",
  "layerCountHint": "힌트: ${layerCount}개의 피처 레이어가 있는 웹 레이어가 발행됩니다.",
  "selectLabel": "선택",
  "mandatoryLabel": "의무 대피 거리",
  "safeLabel": "안전 대피 거리",
  "fireBallDiameterLable": "화구 지름",
  "lpgSafeDistanceLable": "안전거리"
});