define({
  "_widgetLabel": "Εργαλείο έξυπνης επεξεργασίας",
  "_featureAction_SmartEditor": "Εργαλείο έξυπνης επεξεργασίας",
  "noEditPrivileges": "Ο λογαριασμός σας δεν έχει δικαίωμα δημιουργίας ή τροποποίησης δεδομένων.",
  "loginPopupTitle": "Είσοδος",
  "loginPopupMessage": "Το ${widgetName} απαιτεί δικαιώματα και μονάδες κατανάλωσης για την αναζήτηση και αποθήκευση πληροφοριών διεύθυνσης. Θέλετε να συνδεθείτε και να χρησιμοποιήσετε αυτή τη δυνατότητα;",
  "noCreditsOrPrivilegeWarningMessage": "Ο λογαριασμός σας δεν διαθέτει δικαιώματα και μονάδες κατανάλωσης για την αναζήτηση και αποθήκευση πληροφοριών διεύθυνσης στο ${widgetName}. Αποταθείτε στον διαχειριστή του οργανισμού σας για να ζητήσετε δικαιώματα και μονάδες κατανάλωσης. Κάντε κλικ στο OK για να συνεχίσετε την επεξεργασία.",
  "unableToUseLocator": "Το εργαλείο εντοπισμού δεν είναι προσβάσιμο. Οι ενέργειες του γνωρίσματος διεύθυνσης δεν θα εκτελεστούν. Κάντε κλικ στο OK για να συνεχίσετε την επεξεργασία.",
  "locatorDisabledWaning": "Το εργαλείο εντοπισμού δεν είναι ενεργοποιημένο. Αποταθείτε στον διαχειριστή του οργανισμού σας για να ζητήσετε αυτή τη δυνατότητα. Κάντε κλικ στο OK για να συνεχίσετε την επεξεργασία.",
  "noFeatureInAIWarning": "Δεν έχουν επιλεχθεί στοιχεία. Επιλέξτε ένα στοιχείο για να εκτελέσετε επεξεργασία ή κάντε κλικ στην ακύρωση για να επιστρέψετε στην κύρια οθόνη.",
  "noEditableLayerWarning": "Ο λογαριασμός σας δεν έχει δικαιώματα δημιουργίας ή τροποποίησης δεδομένων ή αυτός ο web χάρτης δεν περιέχει επεξεργάσιμα θεματικά επίπεδα.",
  "noVisibleCreateLayerWarning": "Το θεματικό επίπεδο (τα θεματικά επίπεδα) δεν είναι ορατό(ά) στο συγκεκριμένο επίπεδο εστίασης. Εκτελέστε εστίαση ή σμίκρυνση για να δημιουργήσετε/τροποποιήσετε στοιχεία.",
  "noVisibleUpdateLayerWarning": "Το θεματικό επίπεδο (τα θεματικά επίπεδα) δεν είναι ορατό(ά) στο συγκεκριμένο επίπεδο εστίασης. Εκτελέστε εστίαση ή σμίκρυνση για να τροποποιήσετε στοιχεία.",
  "checkLayerVisibilityInWebMapWarning": "Βεβαιωθείτε ότι τα θεματικά επίπεδα είναι ορατά στον χάρτη για τη δημιουργία ή τροποποίηση στοιχείων.",
  "showSelectionInAITitle": "Επιλεγμένα στοιχεία",
  "showSelectionInAIMsg": "Θέλετε να φορτώσετε την τρέχουσα επιλογή στο ${widgetName};",
  "widgetActive": "Ενεργή",
  "widgetNotActive": "Μη ενεργή",
  "pressStr": "Πατήστε ",
  "ctrlStr": " CTRL ",
  "snapStr": " για να ενεργοποιηθεί η λειτουργία αγκίστρωσης",
  "noAvailableTempaltes": "Δεν υπάρχουν διαθέσιμα πρότυπα",
  "editorCache": " - Εργαλείο επεξεργασίας Cache",
  "presetFieldAlias": "Πεδίο",
  "presetValue": "Προκαθορισμένη τιμή",
  "usePresetValues": " Χρήση προκαθορισμένων τιμών (μόνο σε νέα στοιχεία)",
  "editGeometry": " Επεξεργασία γεωμετρικού τύπου",
  "savePromptTitle": "Αποθήκευση στοιχείου",
  "savePrompt": "Θέλετε να αποθηκευτεί το τρέχον στοιχείο;",
  "deletePromptTitle": "Διαγραφή στοιχείου",
  "deleteAttachment": "Διαγραφή συνημμένου",
  "deletePrompt": "Είστε βέβαιοι ότι θέλετε να διαγράψετε το επιλεγμένο στοιχείο;",
  "attachmentLoadingError": "Σφάλμα στην αποστολή των συνημμένων",
  "attachmentSaveDeleteWarning": "Προειδοποίηση: Οι αλλαγές στα συνημμένα αποθηκεύτηκαν αυτόματα",
  "autoSaveEdits": "Αυτόματη αποθήκευση νέων στοιχείων",
  "addNewFeature": "Δημιουργία νέου στοιχείου",
  "featureCreationFailedMsg": "Δεν είναι δυνατή η δημιουργία νέας εγγραφής/νέου στοιχείου.",
  "relatedItemTitle": "Σχετικός πίνακας/Σχετικό θεματικό επίπεδο",
  "relatedFeatureCount": "Θεματικό επίπεδο «${layerTitle}» με ${featureCount} στοιχεία",
  "createNewFeatureLabel": "Δημιουργία νέου στοιχείου για το θεματικό επίπεδο «${layerTitle}»",
  "invalidRelationShipMsg": "Βεβαιωθείτε ότι το πεδίο πρωτεύοντος κλειδιού '${parentKeyField}' έχει έγκυρη τιμή.",
  "pendingFeatureSaveMsg": "Αποθηκεύστε τις αλλαγές στο στοιχείο προτού δημιουργήσετε σχετικό στοιχείο.",
  "attachmentsRequiredMsg": "(*) Απαιτούνται συνημμένα.",
  "coordinatePopupTitle": "Μετακίνηση στοιχείου στην τοποθεσία XY",
  "coordinatesSelectTitle": "Σύστημα συντεταγμένων:",
  "mapSpecialReferenceDropdownOption": "Χωρική αναφορά χάρτη",
  "latLongDropdownOption": "Γεωγραφικό πλάτος/Γεωγραφικό μήκος",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Συντεταγμένη:",
  "xAttributeTextBoxLabel": "Συντεταγμένη στον άξονα X:",
  "yAttributeTextBoxLabel": "Συντεταγμένη στον άξονα Y:",
  "latitudeTextBoxLabel": "Γεωγραφικό πλάτος:",
  "longitudeTextBoxLabel": "Γεωγραφικό μήκος:",
  "presetGroupFieldsLabel": "Το όνομα «${groupName}» θα εφαρμοστεί στα πεδία των εξής θεματικών επιπέδων:",
  "presetGroupNoFieldsLabel": "Το όνομα «${groupName}» δεν έχει συσχετισμένα πεδία.",
  "groupInfoLabel": "Πληροφορίες για την ομάδα «${groupName}»",
  "editGroupInfoIcon": "Επεξεργασία τιμής για την ομάδα «${groupName}»",
  "filterEditor": {
    "all": "Όλοι",
    "noAvailableTempaltes": "Δεν υπάρχουν διαθέσιμα πρότυπα",
    "searchTemplates": "Αναζήτηση προτύπων",
    "filterLayerLabel": "Φιλτράρισμα θεματικών επιπέδων"
  },
  "invalidConfiguration": "To widget δεν είναι διαμορφωμένο ή τα θεματικά επίπεδα στη διαμόρφωση δεν βρίσκονται πλέον στο χάρτη. Ανοίξτε την εφαρμογή στη λειτουργία Εργαλείο δημιουργίας και αναδιαμορφώστε το widget.",
  "geometryServiceURLNotFoundMSG": "Αδύνατη η λήψη Geometry Service URL",
  "clearSelection": "Κλείσιμο",
  "refreshAttributes": "Ενημέρωση δυναμικών γνωρισμάτων στοιχείων",
  "automaticAttributeUpdatesOn": "Αυτόματη ενημέρωση γνωρισμάτων στοιχείων: ΕΝΕΡΓΟΠΟΙΗΣΗ",
  "automaticAttributeUpdatesOff": "Αυτόματη ενημέρωση γνωρισμάτων στοιχείων: ΑΠΕΝΕΡΓΟΠΟΙΗΣΗ",
  "moveSelectedFeatureToGPS": "Μετακίνηση επιλεγμένου στοιχείου στην τρέχουσα τοποθεσία μέσω GPS",
  "moveSelectedFeatureToXY": "Μετακίνηση επιλεγμένου στοιχείου στην τοποθεσία XY",
  "mapNavigationLocked": "Πλοήγηση στον χάρτη: Κλειδωμένη",
  "mapNavigationUnLocked": "Πλοήγηση στον χάρτη: Ξεκλειδωμένη",
  "copyFeatures": {
    "title": "Επιλογή στοιχείων προς αντιγραφή",
    "createFeatures": "Δημιουργία στοιχείων",
    "createSingleFeature": "Δημιουργία 1 στοιχείου πολλαπλών μερών",
    "createOneSingleFeature": "Δημιουργία στοιχείου",
    "noFeaturesSelectedMessage": "Κανένα επιλεγμένο στοιχείο",
    "selectFeatureToCopyMessage": "Επιλέξτε στοιχεία προς αντιγραφή",
    "multipleFeatureSaveWarning": "Αν δημιουργήσετε πολλαπλά στοιχεία χρησιμοποιώντας αυτή τη δυνατότητα, όλα τα στοιχεία θα αποθηκευτούν αμέσως. Η αντιστοίχιση πεδίου δεν υποστηρίζεται κατά τη δημιουργία μιας νέας δυνατότητας πολλαπλών μερών.",
    "copyFeatureUpdateGeometryError": "Δεν είναι δυνατή η ενημέρωση της γεωμετρίας των επιλεγμένων στοιχείων.",
    "canNotSaveMultipleFeatureWarning": "Μπορείτε να αντιγράψετε ένα στοιχείο μόνο όταν το target point layer έχει μοναδικά πεδία τιμών.",
    "createOnlyOneMultipartFeatureWarning": "Μπορείτε να αντιγράψετε ένα χαρακτηριστικό ή να δημιουργήσετε ένα πολυμερές χαρακτηριστικό μόνο όταν το target layer έχει μοναδικά πεδία τιμών.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} από${totalFeatures} επιλεγμένα στοιχεία"
  },
  "addingFeatureError": "Σφάλμα κατά την προσθήκη επιλεγμένων στοιχείων στο θεματικό επίπεδο. Προσπαθήστε ξανά.",
  "addingFeatureErrorCount": "Η αντιγραφή '${copyFeatureErrorCount}' στοιχείου(ων) απέτυχε. Θέλετε να προσπαθήσετε ξανά για το στοιχείο (τα στοιχεία) που λείπουν;",
  "selectingFeatureError": "Σφάλμα κατά την επιλογή στοιχείων στο θεματικό επίπεδο. Προσπαθήστε ξανά.",
  "customSelectOptionLabel": "Επιλογή στοιχείων προς αντιγραφή",
  "copyFeaturesWithPolygon": "Αντιγραφή με πολύγωνο",
  "copyFeaturesWithRect": "Αντιγραφή με ορθογώνιο",
  "copyFeaturesWithLasso": "Αντιγραφή με λάσο",
  "noFeatureSelectedMessage": "Δεν επιλέχθηκαν στοιχεία",
  "multipleFeatureSaveMessage": "Όλα τα στοιχεία θα αποθηκευτούν αμέσως. Θέλετε να προχωρήσετε;",
  "relativeDates": {
    "dateTypeLabel": "Τύπος ημερομηνίας",
    "valueLabel": "Τιμή",
    "fixed": "Καθορισμένη",
    "current": "Τρέχουσα",
    "past": "Παλαιότερη",
    "future": "Μελλοντική",
    "popupTitle": "Επιλογή τιμής",
    "hintForFixedDateType": "Υπόδειξη: Η καθορισμένη τιμή ημερομηνίας και ώρας θα χρησιμοποιηθεί ως προκαθορισμένη προεπιλεγμένη τιμή.",
    "hintForCurrentDateType": "Υπόδειξη: Η τρέχουσα τιμή ημερομηνίας και ώρας θα χρησιμοποιηθεί ως προκαθορισμένη προεπιλεγμένη τιμή.",
    "hintForPastDateType": "Υπόδειξη: Η καθορισμένη τιμή θα αφαιρεθεί από την τρέχουσα τιμή ημερομηνίας και ώρας για να υπολογιστεί η προκαθορισμένη προεπιλεγμένη τιμή.",
    "hintForFutureDateType": "Υπόδειξη: Η καθορισμένη τιμή θα προστεθεί στην τρέχουσα τιμή ημερομηνίας και ώρας για να υπολογιστεί η προκαθορισμένη προεπιλεγμένη τιμή.",
    "noDateDefinedTooltip": "Δεν έχει καθοριστεί ημερομηνία.",
    "relativeDateWarning": "Πρέπει να καθορίσετε μια τιμή για ημερομηνία και ώρα προκειμένου να μπορέσετε να αποθηκεύσετε την προεπιλεγμένη προκαθορισμένη τιμή.",
    "customLabel": "Προσαρμοσμένη",
    "layerLabel": "Θεματικό επίπεδο",
    "domainFieldHintLabel": "Η επιλεγμένη τιμή είναι domain κωδικοποιημένων τιμών. Η τιμή: \"${domainValue}\" θα χρησιμοποιηθεί"
  },
  "valuePicker": {
    "popupTitle": "Επιλογή τιμής",
    "popupHint": "Το τρέχον στοιχείο τέμνει πολλαπλά στοιχεία. Επιλέξτε τιμή για το αντίστοιχο πεδίο.",
    "buttonTooltip": "Επιλογή τιμής από πολλαπλά τεμνόμενα στοιχεία"
  },
  "uniqueValueErrorMessage": "Η τιμή στο «${fieldName}» ήδη υπάρχει. Καταχωρίστε νέα τιμή.",
  "requiredFields": {
    "displayMsg": "Τα απαιτούμενα πεδία δεν επιτρέπεται να είναι κενά. Καταχωρίστε τιμές για κοινά πεδία παρακάτω.",
    "popupTittle": "Απαιτούμενα πεδία",
    "foundNullRecordCount": "${fieldName} (Βρέθηκαν σε ${count} εγγραφές.)"
  },
  "fieldsMapping": {
    "popupTittle": "Εφαρμογή αντιστοίχισης πεδίου",
    "fieldsMatchingCheckboxLabel": "Οι τιμές από τα αντιγραμμένα στοιχεία αντικαθιστούν τις προεπιλεγμένες τιμές στα πεδία στόχου",
    "resetLabel": "Επαναφορά",
    "clearLabel": "Απαλοιφή",
    "fieldsInTargetLayerLabel": "Προορισμός",
    "fieldsInSourceLayerLabel": "Πηγή",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} αντιστοιχισμένα πεδία)",
    "selectSourceFieldLabel": "- Επιλογή -",
    "selectFieldAriaLabel": "Επιλέξτε πεδίο προέλευσης για πεδίο προορισμού${targetField}",
    "informativeText": "Ελέγξτε τα πεδία που ταιριάζουν από προέλευση σε προορισμό και προσαρμόστε εάν χρειάζεται.",
    "dynamicValueText": "Ορίστηκε μια δυναμική τιμή",
    "noFieldsToMatchLabel": "Δεν υπάρχουν πεδία προς αντιστοίχιση"
  },
  "cantLocateUserLocation": "Δεν ήταν δυνατός ο εντοπισμός της τοποθεσίας σας.",
  "tryAgainButtonLabel": "Δοκιμάστε ξανά",
  "copyFeatureFailedPopupTitle": "Πρόβλημα!"
});