define({
  "_widgetLabel": "Atribūtu pakešredaktors",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Slāņa nosaukums",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Nav konfigurēts neviens rediģējams slānis",
  "editorPopupTitle": "Atribūtu pakešredaktors",
  "editorPopupSaveBtn": "Saglabāt",
  "editorPopupMultipleValues": "",
  "clear": "Notīrīt",
  "featuresUpdated": "Atjaunināts(-i) ${0}/${1} elementiem",
  "featuresSelected": "Atlasīts(-i) ${0} elements(-i)",
  "featuresSkipped": "Apiets",
  "featuresNoPermision": "Atlasīts(-i) ${0} elements(-i), bet nav atļaujas rediģēt.",
  "search": "Meklēšana",
  "queryInput": "Ievadiet vērtību vaicājumam",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Lūdzu, pareizi iestatiet filtru.",
  "filterPopup": "Slāņa filtrs",
  "filterAppend": "Ja šī slāņa tīmekļa kartē jau ir filtrs",
  "filterAppendOR": "Pievienot jebkuru izteiksmi esošajam kartes filtram",
  "filterAppendAND": "Pievienot visas izteiksmes esošajam kartes filtram",
  "cancel": "Atcelt",
  "noValue": "Nav vērtības",
  "emptyString": "Tukša virkne",
  "existingValue": "Paturēt esošo vērtību",
  "newDate": "Jauns datums",
  "valueChooser": "Atlasīt/ierakstīt vērtību",
  "ok": "Labi",
  "drawBox": {
    "point": "Punkts",
    "line": "Līnija",
    "polyline": "Polilīnija",
    "freehandPolyline": "Brīvrokas līnija",
    "extent": "Pārklājums",
    "polygon": "Laukums",
    "freehandPolygon": "Brīvrokas laukums",
    "clear": "Notīrīt",
    "addPointToolTip": "Noklikšķiniet, lai atlasītu šajā apgabalā",
    "addShapeToolTip": "Zīmējiet formu, lai atlasītu elementus",
    "freehandToolTip": "Nospiediet un turiet, lai zīmētu formu un atlasītu elementus",
    "startToolTip": "Zīmējiet formu, lai atlasītu elementus"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Elements no ${0} atgrieza nederīgu ID",
    "noSelectedLayers": "Nav atlasītu slāņu ar atjaunināmiem ierakstiem",
    "inputValueError": "Nederīga vērtība veidlapā",
    "saveError": "Nevar saglabāt ${0} elementus",
    "requiredValue": "Obligāta vērtība"
  }
});