define({
  "locatorUrl": "Lokaatori URL",
  "set": "Määra",
  "locatorName": "Lokaatori nimi",
  "locatorExample": "Näide",
  "countryCode": "Riigi või piirkonna kood(id)",
  "eg": "nt ",
  "countryCodeHint": "Kui jätate selle välja tühjaks, teostatakse otsing kõikides riikides ja piirkondades",
  "minCandidateScore": "Minimaalne kandidaadi skoor",
  "minCandidateScoreHint": "Selle väärtuse tühjaks jätmisel kasutatakse minimaalset kandidaadi skoori 90",
  "enableSingleField": "Ühe välja valikud",
  "singleFieldHint": "Aadressi andmed paigutatakse ühele väljale",
  "enableMultiField": "Mitme välja valikud",
  "multiFieldHint": "Aadressi andmed paigutatakse mitmele väljale",
  "enableXYField": "X/Y välja valikud",
  "xyFieldHint": "Andmed sisaldavad X/Y koordinaatväärtusi",
  "instructionGeocode": "Lisage ja konfigureerige lokaatorteenused.",
  "invalidUrlTip": "URL ${URL} ei sobi või pole kättesaadav.",
  "geocodeTabLabel": "Asukohaseaded",
  "lookupList": "Tuvastatavad väljanimed",
  "isRecognized": "Alloleva tabeli väljanimed tuvastatakse automaatselt selle välja jaoks",
  "needsEditablePointLayers": "Veebikaart peab sisaldama vähemalt ühte redigeeritavat punktikihti.",
  "editpageAlias": "Alias",
  "configureFields": "Kihi väljade seadistamine",
  "configureSingleFields": "Konfigureeri üks aadressi väli",
  "configureMultiFields": "Konfigureeri mitu aadressi välja",
  "configureXYFields": "Konfigureeri X/Y väljad",
  "noFields": "Ühe või mitme kuvatava välja määratlemiseks kasutage muutmistoimingut",
  "display": "Kuva",
  "duplicate": "Otsi duplikaati",
  "duplicateTip": "Otsige sellelt väljalt lähtefaili ja sihtkihi vahelisi identseid väärtusi./n Identse vaste leidmise korral ei paigutata failist pärit kirjet ja see märgitakse duplikaadiks.",
  "noSelectField": "Tehke esmalt objektikihi valik",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (pikkuskraad)",
  "xyFieldsLabelY": "Y (laiuskraad)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "X-koordinaat",
  "northing": "Y-koordinaat",
  "lon": "Pikkuskraad",
  "lat": "Laiuskraad",
  "layerOptionHint": "Valige kiht, kuhu andmed lisada.",
  "layerFieldTitle": "Sihtkiht",
  "tempSymbolHint": "Valige sümbol, mida kasutatakse objektide kuvamiseks.",
  "tempSymbolTitle": "Kuvatav sümbol",
  "maxRecords": "Max kirjeid",
  "maxRecordsHint": "Paigutatavate kirjete maksimumarv",
  "searchRadius": "Otsinguraadius",
  "searchRadiusHint": "Kihi dublikaatobjektide otsimise ulatus",
  "requiresInteger": "Sisestage arvväärtus.",
  "requiresInteger0100": "Sisestage arvväärtus vahemikus 0–100",
  "requiresLocator": "Lisage vähemalt üks kehtiv lokaator.",
  "layerFields": "Kihi seaded",
  "layerFieldsHint": "Määrake sihtkihilt väljad, mis vastendatakse lähteväljadega.",
  "locatorError": "Lokaator ei sobi või sellele ei pääse juurde.",
  "optionNotMatch": "Eri lokaatorite väljavalikud pole ühtsed. Tõrkesiire ei pruugi töötada ootuspäraselt.",
  "targetLayerTabTitle": "Sihtkiht",
  "locationSettingsTabTitle": "Asukohaseaded",
  "generalSettingsTabTitle": "Üldseaded",
  "addTargetLayersLabel": "Lisa sihtkiht",
  "introductoryText": "Loo vidina jaoks juhendsisu",
  "defaultStartPageInstructions": "See vidin aitab töödelda ja edastada andmeid failist kaardil valitud kihile.<br/> <br/> Failis olevad väärtused tuleb eraldada koma, tabeldusmärgi, semikooloni või püstkriipsuga.",
  "noTargetLayerConfiguredErrorMsg": "Sihtkihti pole konfigureeritud",
  "noFieldsForTargetLayer": "Sihtkihi kihiseaded on määratlemata",
  "locationSettingsNotConfigured": "Asukohaseaded pole õigesti konfigureeritud"
});