define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>Prístup k infografikám a prehľadom, ktoré sumarizujú kľúčové indikátory a dáta pre ľubovoľnú oblasť.</div><br><div>Zvoliť bod alebo polygón v mape, hľadať adresu alebo miesto, nakresliť polygón alebo pripnúť značku do mapy, aby ste zobrazili kľúčové indikátory a informácie o oblasti.</div>",
  "defineWhichInfographics": "Definovať, ktoré infografiky budú dostupné vo widgete:",
  "defineWhichReports": "Definovať, ktoré sumáre budú dostupné vo widgete:",
  "defaultValues": "Predvolené hodnoty:",
  "disable": "Zakázať",
  "drawFreehandPolygon": "Nakresliť polygón voľnou rukou",
  "drawPolygon": "Nakresliť polygón",
  "driveTime": "Čas jazdy",
  "dropPin": "Označiť značkou",
  "dynamicHTML": "Dynamické HTML",
  "exportOptions": "Možnosti exportu:",
  "home": "Domov",
  "image": "Obrázok",
  "infographics": "Infografiky",
  "invalidValueRing": "Hodnoty musia byť v rozmedzí od 0 do 1,000.",
  "invalidValueDTWT": "Hodnoty musia byť v rozmedzí od 0 do 300.",
  "km": "km",
  "makeDefault": "Urobiť predvolené",
  "miles": "míle",
  "minutes": "minúty",
  "options": "Možnosti:",
  "pdf": "PDF",
  "print": "Tlačiť",
  "radius": "Polomer",
  "removeDefault": "Odstrániť predvolené",
  "reports": "Prehľady",
  "rings": "Prstence",
  "searchTextBox": "Vyhľadávacie textové pole",
  "selectCountryOrRegion": "Zvoliť krajinu alebo región:",
  "thisEntryIsNotValid": "Tento vstup nie je platný.",
  "time": "Čas",
  "walkTime": "Čas chôdze"
});