define({
  "_widgetLabel": "Анализ на инцидентите",
  "_featureAction_SetAsIncident": "Задаване като инцидент",
  "incident": "Инцидент",
  "weather": "Времето",
  "locate_incident": "Локализиране на инцидент",
  "clear_incidents": "Изчистване на инцидент",
  "reverse_geocoded_address": "Най-близкия адрес",
  "reverse_geocoded_error": "Няма налични",
  "miles": "Мили",
  "kilometers": "Километри",
  "feet": "Фута",
  "meters": "Метри",
  "yards": "Ярда",
  "nauticalMiles": "Морски мили",
  "now": "СЕГА",
  "wind": "ВЯТЪР",
  "SUN": "НЕДЕЛЯ",
  "MON": "ПОНЕДЕЛНИК",
  "TUE": "ВТОРНИК",
  "WED": "СРЯДА",
  "THU": "ЧЕТВЪРТЪК",
  "FRI": "ПЕТЪК",
  "SAT": "СЪБОТА",
  "defaultTabMsg": "Няма определени инциденти.",
  "useMapExtent": "Употреба на текущия ограничаващ правоъгълник на картата",
  "noFeaturesFound": "Не са намерени обекти.",
  "downloadCSV": "ИЗТЕГЛЯНЕ НА CSV",
  "sum": "СУМА",
  "min": "МИН.",
  "max": "МАКС.",
  "avg": "СР.",
  "count": "БРОЙ",
  "area": "ОБЛАСТ",
  "length": "ДЪЛЖИНА"
});