define({
  "_widgetLabel": "Nakresliť",
  "selectDrawMode": "Vybrať režim kreslenia",
  "clear": "Vyčistiť",
  "point": "Bod",
  "line": "Línia",
  "polyline": "Lomená čiara",
  "freehandPolyline": "Lomená čiara voľnou rukou",
  "triangle": "Trojuholník",
  "extent": "Obálka",
  "circle": "Kruh",
  "ellipse": "Elipsa",
  "polygon": "Polygón",
  "freehandPolygon": "Polygón voľnou rukou",
  "text": "Text",
  "style": "Štýl",
  "alpha": "Priehľadnosť",
  "width": "Šírka",
  "size": "Veľkosť",
  "color": "Farba",
  "markerColor": "Farba zvýrazňovača",
  "outlineColor": "Farba obrysu",
  "lineColor": "Farba línie",
  "fillColor": "Farba výplne",
  "showMeasurements": "Zobraziť merania",
  "showLocationMeasurement": "Zobraziť meranie umiestnenia",
  "showAreaMeasurement": "Zobraziť meranie oblasti",
  "showDistanceMeasurement": "Zobraziť meranie vzdialenosti",
  "showDistanceMeasurementForLine": "Zobraziť meranie dĺžky",
  "showDistanceMeasurementForPolygon": "Zobraziť meranie obvodu",
  "locationToggleOn": "Pre zobrazenie merania umiestnenia stlačte tlačidlo prepínača",
  "locationToggleOff": "Pre skrytie merania umiestnenia stlačte tlačidlo prepínača",
  "areaToggleOn": "Pre zobrazenie merania oblasti stlačte tlačidlo prepínača",
  "areaToggleOff": "Pre skrytie merania oblasti stlačte tlačidlo prepínača",
  "distanceForLineToggleOn": "Pre zobrazenie merania dĺžky stlačte tlačidlo prepínača",
  "distanceForLineToggleOff": "Pre skrytie merania dĺžky stlačte tlačidlo prepínača",
  "distanceForPolygonToggleOn": "Pre zobrazenie merania obvodu stlačte tlačidlo prepínača",
  "distanceForPolygonToggleOff": "Pre skrytie merania obvodu stlačte tlačidlo prepínača",
  "areaUnits": "Jednotky plochy",
  "distanceUnits": "Jednotky vzdialenosti",
  "kilometers": "Kilometre",
  "miles": "Míle",
  "meters": "Metre",
  "feet": "Stopy",
  "yards": "Yardy",
  "nauticalmiles": "Námorné míle",
  "squareKilometers": "Štvorcové kilometre",
  "squareMiles": "Štvorcové míle",
  "acres": "Akre",
  "hectares": "Hektáre",
  "squareMeters": "Štvorcové metre",
  "squareFeet": "Štvorcové stopy",
  "squareYards": "Štvorcové yardy",
  "undo": "Späť",
  "redo": "Znova",
  "results": "Výsledky",
  "points": "Body",
  "lines": "Línie",
  "areas": "Plochy",
  "locationLabel": "Umiestnenie: ${value}",
  "areaLabel": "Oblasť: ${value}${unit}",
  "distanceLabel": "Vzdialenosť: ${value}${unit}",
  "distanceLabelForLine": "Dĺžka: ${value}${unit}",
  "distanceLabelForPolygon": "Obvod: ${value}${unit}"
});