define({
  "_widgetLabel": "Referenčná grafika ako mriežka",
  "newGRGFromAreaButtonLabel": "Definovať mriežku z plochy",
  "newGRGFromPointButtonLabel": "Definovať mriežku z bodu",
  "defineGridFromAreaDesc": "Vytvorte mriežky definovaním plochy zadaním jej rozmerov alebo pomocou referenčného systému",
  "defineGridFromAreaDimensionDesc": "Vytvorte mriežku podľa používateľom definovaného rozsahu a špecifovanej šírky a výšky bunky alebo počtu horizontálnych a vertikálnych buniek",
  "defineGridFromaAreaRefSystemDesc": "Vytvorte mriežku podľa používateľom definovaného rozsahu na základe referenčného systému",
  "defineGridFromPointDesc": "Pomocou bodu vytvorte mriežky definované podľa bodu rozmerom, referenčným systémom alebo časom a rýchlosťou",
  "defineGridFromPointByDimensionDesc": "Vytvorte mriežku podľa používateľom definovaného bodu, buď zadaného manuálne alebo interaktívne vybraného, na základe počtu horizontálnych a vertikálnych buniek a šírky a výšky bunky",
  "defineGridFromPointByRefSystemDesc": "Vytvorte mriežku podľa používateľom definovaného bodu, buď zadaného manuálne alebo interaktívne vybraného, na základe referenčného systému",
  "defineGridFromPointTimeSpeedDesc": "Vytvorte mriežku podľa používateľom definovaného bodu, buď zadaného manuálne alebo interaktívne vybraného, na základe času a rýchlosti",
  "newGRGFromAreaTitle": "Definovať mriežku z plochy",
  "newGRGFromPointTitle": "Definovať mriežku z bodu",
  "newGRGBySizeButtonLabel": "Podľa rozmeru",
  "newGRGFromRefSystemButtonLabel": "Podľa referenčného systému",
  "newGRGByTimeLabel": "Podľa času a rýchlosti",
  "newGRGFromNonStandardButtonLabel": "Definovať neštandardnú mriežku",
  "newGRGAreaBySizeTitle": "GRG z plochy podľa rozmeru",
  "newGRGAreaBySizeDefineAreaLabel": "GRG plocha",
  "addGRGAreaPolygonToolTip": "Nakresliť GRG plochu za použitia polygónu",
  "addGRGAreaExtentToolTip": "Nakresliť GRG plochu za použitia rozsahu (extentu)",
  "rotation": "Rotácia mriežky",
  "numberRowsColumnsLabel": "Definovať počet riadkov a stĺpcov",
  "newGRGAreaByRefSystemTitle": "GRG z plochy podľa referenčného systému",
  "gridSize": "Veľkosť mriežky",
  "UTMZoneandBand": "Zóna mrieťky",
  "100000m": "100000 metrov",
  "10000m": "10000 metrov",
  "1000m": "1000 metrov",
  "100m": "100 metrov",
  "10m": "10 metrov",
  "clipGrid": "Pripnúť mriežku na GRG plochu",
  "newGRGAreaFromNonStandardTitle": "Nové NRG",
  "newGRGPointBySizeTitle": "GRG z bodu podľa rozmeru",
  "newGRGPointByRefSystemTitle": "GRG z bodu podľa referenčného systému",
  "newGRGPointByTimeTitle": "GRG z bodu za použitia času a rýchlosti",
  "time": "Čas",
  "rate": "Rýchlosť",
  "hours": "Hodiny",
  "minutes": "Minúty",
  "seconds": "Sekundy",
  "ftPerSec": "Stopy / sekundu",
  "ftPerHour": "Stopy / hodinu",
  "kmPerSec": "Kilometre / sekundu",
  "kmPerHour": "Kilometre / hodinu",
  "mPerSec": "Metre / sekundu",
  "mPerHour": "Metre / hodinu",
  "miPerSec": "Míle / sekundu",
  "miPerHour": "Míle / hodinu",
  "nMPerSec": "Námorné míle / sekundu",
  "nMPerHour": "Námorné míle / hodinu",
  "settingsTitle": "Nastavenia",
  "labelSettingsLabel": "Nastavenia označenia",
  "labelSettingsButtonLabel": "Konfigurovať nastavenia označenia",
  "gridSettingsLabel": "Nastavenia mriežky",
  "gridSettingsButtonLabel": "Konfigurovať nastavenia mriežky",
  "transparency": "Priehľadnosť",
  "labelStyle": "Štýl označenia",
  "font": "Písmo",
  "textSize": "Veľkosť textu",
  "textColor": "Farba textu",
  "halo": "Tieň",
  "show": "Zobraziť",
  "lockSettings": "Nastavenia boli uzamknuté vlastníkom aplikácie",
  "gridSettings": {
    "cellShape": "Tvar bunky",
    "cellUnits": "Jednotky bunky",
    "cellOutline": "Nastavenia obrysu bunky",
    "cellFill": "Nastavenia výplne bunky",
    "gridReferenceSystem": "Referenčný systém",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Počiatok označenia",
    "labelType": "Typ označenia",
    "labelDirection": "Smer označenia",
    "gridOrigin": "Počiatok mriežky",
    "default": "Obdĺžnik",
    "hexagon": "Šesťuholník",
    "miles": "Míle",
    "kilometers": "Kilometre",
    "feet": "Stopy",
    "meters": "Metre",
    "yards": "Yardy",
    "nautical-miles": "Námorné míle",
    "lowerLeft": "Ľavá dolná",
    "lowerRight": "Pravá dolná",
    "upperLeft": "Ľavá horná",
    "upperRight": "Pravá horná",
    "center": "V strede (vodorovne)",
    "alphaNumeric": "Alfa-numerický",
    "alphaAlpha": "Alpha-Alpha",
    "numeric": "Číselné",
    "horizontal": "Vodorovný",
    "vertical": "Zvislý",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "UTM": "UTM",
    "showLabels": "Zobraziť označenia",
    "colorPicker": "Výber farby",
    "bold": "Tučné",
    "italic": "Kurzíva",
    "underline": "Podčiarknuté"
  },
  "publishTitle": "Publikovať GRG na Portal",
  "publishGRGBtn": "Publikovať",
  "GRGLayerName": "Publikovaný názov vrstvy GRG",
  "invalidGRGLayerName": "Názov vrstvy musí obsahovať iba alfanumerické znaky a podčiarkovníky",
  "publishWorskpaceError": "CHYBA: Chyba pri otváraní pracovnej oblasti",
  "publishToNewLayer": "Publikovať výsledky do novej vrstvy prvkov",
  "publishingFailedLayerExists": "Publikovanie zlyhalo: Už máte službu pre prvky s názvom {0}. Vyberte iný názov.",
  "checkService": "Skontrolovať službu: {0}",
  "createService": "Vytvoriť službu: {0}",
  "unableToCreate": "Nebolo možné vytvoriť: {0}",
  "addToDefinition": "Pridať do definície: {0}",
  "successfullyPublished": "Webová vrstva úspešne publikovaná{0} Spravovať webovú vrstvu",
  "userRole": "Nebolo možné vytvoriť službu, pretože používateľ nemá povolenia",
  "layerNameExists": "Názov vrstvy už existuje. Použite iný názov vrstvy.",
  "createGRGBtn": "Vytvoriť GRG",
  "clearGRGBtn": "Vyčistiť",
  "labelFormat": "Formát popisu",
  "helpIconTooltip": "Z: Grid Zone Designator (GZD)\nS: ${number}-metrov Grid Square Identifikácia (GSID)\nX: Východné súradnice (X Súradnica)\nY: Severné súradnice (Y Súradnica)\n\nPríklady:\nZSXY je 15SWC8081751205\nZS X,Y je 15SWC 80817,51205",
  "addPointToolTip": "Pridať GRG počiatok",
  "cellWidth": "Šírka bunky (x)",
  "cellHeight": "Výška bunky (y)",
  "invalidNumberMessage": "Zadaná hodnota nie je platná",
  "invalidRangeMessage": "Hodnota musí byť väčšia ako 0",
  "gridAngleInvalidRangeMessage": "Hodnota musí byť medzi -89,9 a 89,9",
  "formatIconTooltip": "Formát vstupu",
  "coordInputLabel": "GRG počiatok",
  "setCoordFormat": "Nastaviť zápis formátu súradníc",
  "prefixNumbers": "Pridať \"+/-\" ku kladným a záporným číslam",
  "cancelBtn": "Zrušiť",
  "applyBtn": "Použiť",
  "comfirmInputNotation": "Potvrdiť zápis vstupu",
  "notationsMatch": "zápisy zodpovedajú vášmu vstupu, prosím potvrďte, ktoré chcete použiť:",
  "numberOfCellsHorizontal": "# Vodorovné bunky",
  "numberOfCellsVertical": "# Vertikálne bunky",
  "gridAngle": "Rotácia mriežky",
  "tooManyCellsErrorMessage": "Pokúšate sa vytvoriť mriežku pozostávajúcu z viac ako 2000 buniek. Je odporúčané znížiť počet vytváraných buniek zmenou veľkosti mriežky alebo plochy mriežky.",
  "missingParametersMessage": "<p>Formulár vytvorenia GRG má chýbajúce alebo nesprávne parametre, Prosím uistite sa, že:</p><ul><li>GRG plocha bola nakreslená.</li><li>Šírka a výška bunky obsahuje platné hodnoty.</li></ul>",
  "missingOriginParametersMessage": "<p>Formulár vytvorenia GRG má chýbajúce alebo nesprávne parametre, Prosím uistite sa, že:</p><ul><li>GRG počiatok bol nastavený.</li><li>Čas, rýchlosť a vstupy uhlov obsahujú platné hodnoty</li></ul>",
  "projectionNotSupported": "Váš prehliadač nepodporuje WebAssembly. Podpora pre WebAssembly je vyžadovaná, kedže tento widget používa zobrazovací engine na strane klienta na vytvorenie GRGs",
  "invalidWidthHeightParametersMessage": "<p>Formulár vytvorenia GRG má chýbajúce alebo nesprávne parametre. Prosím uistite sa, že vstupy šírky a výšky bunky obsahujú platné hodnoty.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Formulár vytvorenia GRG má chýbajúce alebo nesprávne parametre. Prosím uistite sa, že počet vstupov vodorovných a zvislých buniek obsahuje platné hodnoty.</p>",
  "drawPointToolTip": "Kliknúť na pridanie bodu počiatku GRG",
  "missingLayerNameMessage": "Pred publikovaním musíte zadať platný názov vrstvy",
  "parseCoordinatesError": "Nie je možné interpretovať súradnice. Skontrolujte svoj vstup.",
  "grgPolarRegionError": "Rozsah GRG je v rámci polárneho regiónu. Bunky, ktoré spadajú do polárneho regiónu nebudú vytvorené.",
  "grgPolarOriginError": "Bod počiatku GRG sa nesmie nachádzať v polárnom regióne keď vytvárate GRG podľa referenčného systému.",
  "deleteBtn": "Odstrániť",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desatinné stupne - Zemepisná šírka/dĺžka",
  "DDLongLatNotation": "Desatinné stupne - Zemepisná dĺžka/šírka",
  "DDMLatLongNotation": "Stupne desatinné minúty - Zemepisná šírka/dĺžka",
  "DDMLongLatNotation": "Stupne desatinné minúty - Zemepisná dĺžka/šírka",
  "DMSLatLongNotation": "Stupne minúty sekundy - Zemepisná šírka/dĺžka",
  "DMSLongLatNotation": "Stupné minúty sekundy - Zemepisná dĺžka/šírka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - znak pásma",
  "UTMHemNotation": "UTM - pologuľa (S/J)"
});