define({
  "_widgetLabel": "Andmete agregeerimine",
  "startPage": {
    "defaultStartPageInstructions": "See vidin aitab töödelda ja edastada andmeid failist kaardil valitud kihile.<br/> <br/> Failis olevad väärtused tuleb eraldada koma, tabeldusmärgi, semikooloni või püstkriipsuga.",
    "dragDrop": "Lohistage",
    "browse": "Sirvi faili juurde",
    "or": "VÕI",
    "userPrivilege": "Teie kontol puudub andmete loomise või muutmise õigus.",
    "userCredits": "${widgetName} nõuab lokaatori ${locator} kasutamiseks krediiti.",
    "contactAdmin": "Lisakrediidi taotlemiseks pöörduge oma organisatsiooni administraatori poole.",
    "contactAdminEdit": "Muutmisõiguste taotlemiseks pöörduge oma organisatsiooni administraatori poole.",
    "canUseLocator": "Lokaatorit ${locator} kasutatakse objektide paigutamiseks.",
    "notEnoughCredits": "Krediiti pole piisavalt.",
    "locationAndField": "Asukoha- ja väljateave",
    "locationAndFieldHint": "Valige failist väärtused, mida tuleks kasutada sihtkihi uuendamiseks",
    "cannotUseLocator": "Vidinat ${widgetName} ei saa kasutada",
    "noAnonymousEdit": "Kiht ${layerName} ei toeta anonüümset muutmist.",
    "pleaseLogin": "Logige sisse organisatsiooni ${org} või pöörduge organisatsiooni administraatori poole, et taotleda anonüümse muutmise lubamist.",
    "invalidEdit": "Sobimatud õigused",
    "unableToAccess": "Kihile ${layerName} ei pääse juurde",
    "appropriateCredentials": "Veenduge, et olete sisse loginud õigete sisselogimisandmetega.",
    "shared": "Kihile ${layerName} juurdepääsu taotlemiseks võtke ühendust organisatsiooni administraatoriga.",
    "targetLayerLabel": "Sihtkiht",
    "homeButtonLabel": "Avaleht",
    "mappingErrorMsg": "Väljade defineerimiseks klõpsake kõrvalasuvat noolt"
  },
  "mapping": {
    "schemaMapping": "Välja teave",
    "schemaMappingHint": "Valige faili väljad, mis on korrelatsioonis kihi väljadega.",
    "locationMapping": "Asukoha teave",
    "locationMappingHint": "Valige aadressi tüüp või koordinaatide teave, mida failist eeldada."
  },
  "locationMapping": {
    "locationMappingPageHint": "Vali asukohatüüp",
    "useAddress": "Leia asukoht aadressi abil",
    "useAddressHint": "Andmed sisaldavad aadressi teavet",
    "useCoordinates": "Leia asukoht koordinaatide abil",
    "useCoordinatesHint": "Andmed sisaldavad X/Y koordinaatväärtusi"
  },
  "address": {
    "addressPageHint": "Vali aadressi tüüp",
    "singleField": "Üks väli",
    "singleFieldHint": "Valige väli, mis sisaldab aadressiteavet",
    "multiField": "Mitu välja",
    "multiFieldHint": "Valige väljad, mis sisaldavad aadressiteavet"
  },
  "coordinates": {
    "coordinatesPageHint": "Valige väljad, mis sisaldavad koordinaatide andmeid"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "Valige lähteväli, mis vastendub sihtväljaga",
    "sourceField": "Kattuv lähteväli",
    "targetField": "Sihtväli"
  },
  "buttons": {
    "addToMap": "Lisa kaardile",
    "submit": "Esita",
    "download": "Laadi alla"
  },
  "review": {
    "matched": "Leitud",
    "reviewMatched": "Leitud asukohad",
    "reviewMatchedHint": "Vaadake leitud asukohad üle.",
    "unMatched": "ei leitud",
    "reviewUnMatched": "Asukohti ei leitud",
    "reviewUnMatchedHint": "Vaadake üle asukohad, mida ei leitud. Parandamata üksusi ei edastata.",
    "duplicate": "Duplikaat",
    "reviewDuplicate": "Duplikaatasukohad",
    "reviewDuplicateHint": "Vaadake üle asukohad, mis leiti kihilt. Käsitlemata üksusi ei edastata.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "Kasutamine:",
    "fromLayer": "Sihtteave",
    "target": "Siht",
    "source": "Allikas",
    "fromFile": "Allika teave",
    "locationControlHint": "Vaata aadressiteave üle",
    "duplicateAction": "Valige toiming",
    "item": "Kirje:",
    "locateFeature": "Paiguta objekt",
    "removeFeature": "Eemalda objekt",
    "featureLocated": "Asukohta ei leitud",
    "valuesDoNotMatch": "Ei vasta olemasolevale väärtusele",
    "sync": "Sünkrooni aadressiteave väljateabega",
    "noFeaturesSaved": "Objekte ei salvestatud",
    "someFeaturesSaved": "${num} objekt(i) on salvestatud.",
    "someFeaturesNotSaved": "${num} objekti ei salvestatud.",
    "feature": "Vaata objektiteave üle",
    "locationInfo": "Vaata asukohateave üle",
    "selectValue": "Vali väärtus",
    "reviewData": "Vaata andmed üle",
    "reviewDataHint": "Vaadake andmed enne kihile lisamist üle.",
    "reviewFeatureHint": "Vaadake oma objekti- ja asukohateave läbi või muutke seda.",
    "duplicateModify": "Duplikaat, vajab muutmist",
    "duplicateSave": "Salvesta uue objektina"
  },
  "warningsAndErrors": {
    "invalidCSV": "Tõrge CSV-failist üksuste toomisel. Kontrollige, kas valitud on sobiv CSV-fail.",
    "noLayersWarning": "Sobivat sihtkihti pole konfigureeritud. Kontrollige konfiguratsiooni.",
    "loadWarning": "See vidin vajab objektiteenuse andmeallikat. Andmeallika määratlemiseks konfigureerige vidin.",
    "saveError": "Tõrge objektide salvestamisel.",
    "consumesCredits": "Kasutamisel koos teenusega ArcGIS Online World Geocoding Service tarbib see tööriist krediiti",
    "noValue": "Vali väli",
    "mappingTitle": "",
    "locationMappingComplete": "Asukoha vastendamine on lõpule viidud",
    "fieldMappingComplete": "Välja vastendamine on lõpule viidud",
    "settingsCleared": "Seaded eemaldatakse.",
    "proceed": "Kas soovite jätkata?",
    "itemMoveMatch": "Üksus paigutati ja teisaldati leitud asukohtade loendisse",
    "itemMoveUnMatched": "Üksust ei saa paigutada. Teisaldatud leidmata asukohtade loendisse.",
    "itemWillBeLocated": "Üksus eemaldatakse duplikaatasukohtade loendist.",
    "cannotLocate": "Üksust ei saa paigutada. Kinnitage asukohateave.",
    "invalidMessage": "Sobimatu väärtus.",
    "rangeMessage": "Väärtus peab olema lühem kui ${num} märki.",
    "locatorError": "Lokaator ei sobi või sellele ei pääse juurde.",
    "notConfigured": "lokaator pole konfigureeritud praeguste paigutusvalikute jaoks",
    "noMoreLocators": "täiendavaid lokaatoreid pole konfigureeritud"
  },
  "featureToolbar": {
    "locate": "Paiguta",
    "save": "Salvesta kirje",
    "cancel": "Tühista muudatused",
    "cancelTitle": "Tühista muudatused",
    "cancelMessage": "Kas soovite praeguse kirje muudatused tühistada?"
  }
});