define({
  "locatorUrl": "ロケーターの URL",
  "set": "設定",
  "locatorName": "ロケーター名",
  "locatorExample": "例",
  "countryCode": "国コードまたは地域コード",
  "eg": "例: ",
  "countryCodeHint": "この値を空白のままにすると、すべての国および地域を検索します",
  "minCandidateScore": "候補とする最小スコア",
  "minCandidateScoreHint": "この値を空白のままにすると、候補とする最小スコアに 90 が使用されます",
  "enableSingleField": "単一フィールド オプション",
  "singleFieldHint": "住所データは単一フィールドになります",
  "enableMultiField": "複数フィールド オプション",
  "multiFieldHint": "住所データは複数フィールドになります",
  "enableXYField": "X/Y フィールド オプション",
  "xyFieldHint": "データに X/Y 座標値が含まれます",
  "instructionGeocode": "ロケーター サービスを追加および構成します。",
  "invalidUrlTip": "URL ${URL} は無効であるか、アクセスできません。",
  "geocodeTabLabel": "位置情報の設定",
  "lookupList": "認識するフィールド名",
  "isRecognized": "以下のテーブル内のフィールド名は、このフィールドで自動的に認識されます",
  "needsEditablePointLayers": "Web マップには、少なくとも 1 つの編集可能ポイント レイヤーが含まれている必要があります。",
  "editpageAlias": "エイリアス",
  "configureFields": "レイヤー フィールドの構成",
  "configureSingleFields": "単一住所フィールドの構成",
  "configureMultiFields": "複数住所フィールドの構成",
  "configureXYFields": "X/Y フィールドの構成",
  "noFields": "表示する 1 つ以上のフィールドを定義するには、編集アクションを使用します",
  "display": "表示",
  "duplicate": "重複の検索",
  "duplicateTip": "このフィールドで、ソース ファイルとターゲット レイヤー間で同じ値を検索します。/n 完全な一致が見つかった場合、ファイルのレコードは検索されず、重複のフラグが設定されます。",
  "noSelectField": "最初に [フィーチャ レイヤー] オプションを選択します",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (経度)",
  "xyFieldsLabelY": "Y (緯度)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "東距",
  "northing": "北距",
  "lon": "経度",
  "lat": "緯度",
  "layerOptionHint": "データの送信先のレイヤーを選択します。",
  "layerFieldTitle": "ターゲット レイヤー",
  "tempSymbolHint": "フィーチャの表示に使用するシンボルを選択します。",
  "tempSymbolTitle": "表示シンボル",
  "maxRecords": "最大レコード",
  "maxRecordsHint": "検索するレコードの最大数",
  "searchRadius": "検索範囲",
  "searchRadiusHint": "レイヤーから重複フィーチャを検索する距離",
  "requiresInteger": "数値を入力します。",
  "requiresInteger0100": "0 ～ 100 までの数値を入力します",
  "requiresLocator": "少なくとも 1 つの有効なロケーターを追加します。",
  "layerFields": "レイヤー設定",
  "layerFieldsHint": "ソース フィールドにマッピングされるターゲット レイヤーのフィールドを指定します。",
  "locatorError": "ロケーターは無効であるか、アクセスできません。",
  "optionNotMatch": "フィールド オプションがロケーター全体で一定ではありません。 フェイルオーバーが予想どおりに動作しない可能性があります。",
  "targetLayerTabTitle": "ターゲット レイヤー",
  "locationSettingsTabTitle": "位置情報の設定",
  "generalSettingsTabTitle": "一般設定",
  "addTargetLayersLabel": "ターゲット レイヤーの追加",
  "introductoryText": "ウィジェットの説明コンテンツの作成",
  "defaultStartPageInstructions": "このウィジェットは、ファイルからマップ内で選択したレイヤーへのデータの処理および送信を支援します。<br/> <br/> ファイル内の値は、カンマ、タブ、セミコロン、または縦棒で区切る必要があります。",
  "noTargetLayerConfiguredErrorMsg": "ターゲット レイヤーが構成されていません",
  "noFieldsForTargetLayer": "ターゲット レイヤーのレイヤー設定が定義されていません",
  "locationSettingsNotConfigured": "位置設定が適切に構成されていません"
});