define({
  "transparencyLabel": "透過表示",
  "outline": "アウトライン",
  "fill": "塗りつぶし (スタイルを実線に設定した場合のみ色を適用)",
  "style": "スタイル",
  "selectOpLayerLabel": "結果の操作レイヤーを選択",
  "selectDefaultMeasurementLabel": "デフォルトの計測単位を選択",
  "helpIconTooltip": "操作レイヤー リストは、現在の Web マップから、ポリゴン ジオメトリ タイプであるレイヤーを使用して設定されます。",
  "lineStyles": {
    "esriSLSDash": "破線",
    "esriSLSDashDot": "1 点鎖線",
    "esriSLSDashDotDot": "2 点鎖線",
    "esriSLSDot": "点",
    "esriSLSLongDash": "長い破線",
    "esriSLSLongDashDot": "長い 1 点鎖線",
    "esriSLSNull": "NULL",
    "esriSLSShortDash": "短い破線",
    "esriSLSShortDashDot": "短い 1 点鎖線",
    "esriSLSShortDashDotDot": "短い 2 点鎖線",
    "esriSLSShortDot": "点線",
    "esriSLSSolid": "実線"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "逆方向",
    "esriSFSCross": "十字",
    "esriSFSDiagonalCross": "対角線",
    "esriSFSForwardDiagonal": "正方向",
    "esriSFSHorizontal": "水平方向",
    "esriSFSNull": "NULL",
    "esriSFSSolid": "実線",
    "esriSFSVertical": "垂直"
  },
  "threatTypeLabel": "脅威タイプ",
  "generalLabel": "全般",
  "addThreatTypesLabel": "脅威タイプの追加",
  "actions": "アクション",
  "newThreatTypePopupLabel": "新しい脅威タイプ",
  "units": "単位",
  "chooseDefaultThreatLabel": "デフォルト脅威タイプの選択",
  "defaultThreatTypePopUpLabel": "デフォルトの脅威タイプ",
  "editThreatLabel": "脅威の編集",
  "defaultThreatTypeIconTooltip": "デフォルトの脅威タイプ リスト",
  "uniqueThreatTypeMsg": "一意の脅威タイプを入力します。この名前の脅威タイプはすでに存在します。",
  "requiredMsg": "このフィールドは必須です。",
  "unitMeasureLabel": "距離の単位は {0} です",
  "chooseDefaultThreatTypeIconLabel": "デフォルトから選択",
  "pipeBombLabel": "パイプ爆弾",
  "suicideBombLabel": "自爆爆弾",
  "briefcaseLabel": "ブリーフケース",
  "carLabel": "自動車",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "小型配送トラック",
  "containerWaterTruckLabel": "コンテナー/給水車",
  "semiTrailerLabel": "セミトレーラー",
  "chemicalThreatLegendLabel": "化学的脅威",
  "lpgThreatLegendLabel": "LPG 脅威",
  "smallLPGTank": "小さな LPG タンク",
  "largeLPGTank": "大きな LPG タンク",
  "commercialResidentialLPGTank": "商用/住居用 LPG タンク",
  "smallLPGTruck": "小さな LPG トラック",
  "semiTankerLPG": "セミタンカー LPG",
  "threatDescriptionColLabel": "脅威の説明",
  "addThreatZoneButtonLabel": "脅威ゾーンの追加",
  "zoneDescColLabel": "ゾーンの説明",
  "distanceLabel": "距離 (${unitAbbr})",
  "threatTypeHelp": "<p>脅威タイプが次の条件を満たしていることを確認してください。<br/><ul><li>脅威タイプは空白にできず、一意にする必要がある</li><li>脅威には 1 つ以上の有効なゾーンが必要</li><li>ゾーンの説明は脅威ごとに一意にする必要がある</li></ul><p/>",
  "descriptionLabel": "説明",
  "newThreatZonePopupLabel": "新しい脅威ゾーン",
  "editThreatZonePopupLabel": "脅威ゾーンの編集",
  "uniqueZoneDescriptionMsg": "一意のゾーンの説明を入力してください。この名前のゾーンの説明はすでに存在しています。",
  "symbologyColLabel": "シンボル",
  "zoneDescriptionColLabel": "ゾーンの説明",
  "uniqueZoneRequiredMsg": "ゾーン名は一意でなければなりません",
  "interactive": "対話的",
  "fromCoord": "固定座標",
  "existingFeature": "既存のフィーチャから",
  "defaultInputLocationLabel": "デフォルト入力位置",
  "defaultInputLayer": "デフォルト入力レイヤー",
  "defaultThreatType": "デフォルト脅威タイプ",
  "selectLabel": "選択",
  "mandatoryLabel": "必須避難距離",
  "safeLabel": "安全避難距離",
  "lpgSafeDistanceLable": "安全距離",
  "fireBallDiameterLable": "ファイアボールの直径"
});