define({
  "_widgetLabel": "批次屬性編輯器",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "圖層名稱",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "未配置可編輯的圖層",
  "editorPopupTitle": "批次屬性編輯器",
  "editorPopupSaveBtn": "儲存",
  "editorPopupMultipleValues": "",
  "clear": "清除",
  "featuresUpdated": "已更新 ${0} / ${1} 圖徵",
  "featuresSelected": "已選擇 ${0} 圖徵",
  "featuresSkipped": "已略過",
  "featuresNoPermision": "已選擇 ${0} 個圖徵，但無編輯權限。",
  "search": "搜尋",
  "queryInput": "輸入要查詢的值",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "請正確設定篩選程式。",
  "filterPopup": "篩選圖層",
  "filterAppend": "如果 Web 地圖已存在此圖層的篩選器。",
  "filterAppendOR": "將任何表達式附加到現有的地圖篩選器",
  "filterAppendAND": "將所有表達式附加到現有的地圖篩選器",
  "cancel": "取消",
  "noValue": "沒有值",
  "emptyString": "空字串",
  "existingValue": "保留現有值",
  "newDate": "新增資料",
  "valueChooser": "選擇/鍵入值",
  "ok": "確定",
  "drawBox": {
    "point": "點(P)",
    "line": "線",
    "polyline": "折線",
    "freehandPolyline": "手繪折線",
    "extent": "範圍",
    "polygon": "面",
    "freehandPolygon": "手繪多邊形",
    "clear": "清除",
    "addPointToolTip": "按一下以在此區域中選擇",
    "addShapeToolTip": "繪製形狀以選擇圖徵",
    "freehandToolTip": "按住以繪製形狀來選擇圖徵",
    "startToolTip": "繪製形狀以選擇圖徵"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "${0} 的圖徵傳回無效的 ID",
    "noSelectedLayers": "沒有包含要更新記錄的所選圖層",
    "inputValueError": "表單中有無效值",
    "saveError": "無法儲存 ${0} 個圖徵",
    "requiredValue": "必要值"
  }
});