define({
  "_widgetLabel": "Súradnica",
  "hintMessage": "Pre získanie súradníc kliknite na mapu",
  "defaultLabel": "Predvolené",
  "realtimeLabel": "Pre získanie súradníc pohnite myšou",
  "computing": "Prebieha výpočet...",
  "latitudeLabel": "Zemepisná šírka",
  "longitudeLabel": "Zemepisná dĺžka",
  "loading": "načítava sa...",
  "enableClick": "Kliknite pre aktiváciu mapy a získanie súradníc",
  "disableClick": "Kliknite pre deaktiváciu mapy a získanie súradníc",
  "Default": "Predvolené",
  "Inches": "Palce",
  "Foot": "Stopy",
  "Yards": "Yardy",
  "Miles": "Míle",
  "Nautical_Miles": "Námorné míle",
  "Millimeters": "Milimetre",
  "Centimeters": "Centimetre",
  "Meter": "Metre",
  "Kilometers": "Kilometre",
  "Decimeters": "Decimetre",
  "Decimal_Degrees": "Stupne",
  "Degree_Minutes_Seconds": "Stupne minúty sekundy",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "výška náhľadu",
  "ELEV": "nadmorská výška"
});