define({
  "taskUrl": "Oppgave-URL",
  "setTask": "Angi",
  "setTaskPopupTitle": "Angi oppgave",
  "validate": "Angi",
  "inValidGPService": "Angi gyldig geoprosesseringstjeneste.",
  "noOutputParameterWithGeometryType": "Den valgte geoprosesseringstjenesten må ha minst én utdataparameter med en angitt geometritype. Angi en annen geoprosesseringstjeneste.",
  "invalidOutputGeometry": "Utdatageometritypen for den valgte geoprosesseringstjenesten er ikke kompatibel med prosjektinnstillingene. Kan ikke lagre resultatene fra geoprosesseringstjenesten.",
  "GPFeatureRecordSetLayerERR": "Angi en geoprosesseringstjeneste med inndata bare av typen «GPFeatureRecordSetLayer».",
  "invalidInputParameters": "Antall inndataparametere er enten mindre enn 1 eller flere enn 3. Angi en gyldig geoprosesseringstjeneste.",
  "projectSetting": {
    "title": "Prosjektinnstillinger",
    "note": "Merk: Prosjektinnstillinger er valgfrie, når de først er konfigurert, kan brukeren lagre prosjektet i ønskede webkartlag med nettverkets område for nedetid og inndataparametere. Brukeren kan lagre andre utdataparametere fra fanen Utdata.",
    "projectPolygonLayer": "Prosjektets polygonlag",
    "outputParameterName": "Navn på utdataparameter",
    "projectPointLayer": "Prosjektets punktlag",
    "selectLabel": "Velg",
    "polygonLayerHelp": "<p>Polygonlag med følgende vilkår vises:<br/><ul><li>Laget må ha redigeringsfunksjonene Opprett, Slett og Oppdater</li><li>Laget må ha to felt med eksakt navn og datatype:</li><ul><li>name (strengfelt)</li><li>globalid (felttypen GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Polygonlag som utdata fra oppgave-URL-en vises<p/>",
    "pointLayerHelp": "<p>Punktlag med følgende vilkår vises:<br/><ul><li>Laget må ha redigeringsfunksjonene Opprett, Slett og Oppdater</li><li>Laget må ha to felt med eksakt navn og datatype:</li><ul><li>inputtype (strengfelt)</li><li>projectid (felt av typen GUID)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Flagg",
    "barrier": "Hindring",
    "skip": "Hopp over",
    "title": "Inndata",
    "inputTooltip": "Verktøytips",
    "typeText": "Type",
    "symbol": "Symbol",
    "summaryEditorText": "Sammendragtekst",
    "summaryTextTitle": "Oppgi tekst som skal vises for inndatafanen"
  },
  "summaryTab": {
    "title": "Resultat",
    "summaryFieldsetText": "Oversikt over innstillinger",
    "inputOutput": "Inndata/utdata",
    "field": "Felt",
    "operator": "Operator",
    "inputOperatorCountOption": "Antall",
    "outputOperatorCountOption": "Antall",
    "outputOperatorSkipCountOption": "Hopp over antall",
    "fieldOperatorSumOption": "Sum",
    "fieldOperatorMinOption": "Min",
    "fieldOperatorMaxOption": "Maks",
    "fieldOperatorMeanOption": "Gjennomsnitt",
    "expressionAddButtonText": "Legg til",
    "expressionVerifyButtonText": "Bekreft",
    "summaryEditorText": "Sammendragtekst",
    "zoomText": "Automatisk zoom etter sporing",
    "summarSettingTooltipText": "Legg til antall inndata/utdata",
    "symbol": "Symbol",
    "outputParametersText": "Parametere for utdata",
    "skipText": "Kan hoppes over",
    "visibilityText": "Synlig",
    "exportToCsvText": "Eksporter til CSV",
    "settitngstext": "Innstillinger",
    "saveToLayerText": "Lagre i lag (valgfritt)",
    "inputLabel": "Etikett",
    "inputTooltip": "Verktøytips",
    "outputDisplay": "Vis tekst",
    "addFieldTitle": "Legg til felt",
    "setScale": "Angi målestokk",
    "enterDisplayText": "Skriv inn visningstekst",
    "saveToLayerHelp": "<p>Lag med følgende vilkår blir vist:<br/><ul><li>Laget må ha redigeringsfunksjonene Opprett, Slett og Oppdater</li><li>Laget må ha to felt med eksakt navn og datatype:</li><ul><li>parametername (felt av typen streng)</li><li>projectid (felt av typen GUID)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Oppgi tekst som skal vises for utdatafanen",
    "addSummaryItemsTitle": "Legg til sammendragselementer"
  },
  "validationErrorMessage": {
    "webMapError": "Ingen lag er tilgjengelige i webkartet. Velg et gyldig webkart.",
    "inputTypeFlagGreaterThanError": "Inndata av typen flagg kan ikke være mer enn én.",
    "inputTypeFlagLessThanError": "Minst én inndata av typen flagg kreves.",
    "inputTypeBarrierErr": "Inndata av typen hindring kan ikke være mer enn én.",
    "inputTypeSkipErr": "Inndata av typen hopp over kan ikke være mer enn én.",
    "displayTextForButtonError": "Visningstekst for Kjør-knappen må være utfylt.",
    "UnableToLoadGeoprocessError": "Kan ikke laste geoprosesseringstjeneste.",
    "invalidSummaryExpression": "Ugyldig uttrykk.",
    "validSummaryExpression": "Vellykket!",
    "invalidProjectSettings": "Ugyldige prosjektinnstillinger.<br/> Velg en gyldig verdi i '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Tips: Opprett visningsetikett til resultatpanelet for utdataparameteren.",
    "displayTextHint": "Tips: Dette vises i detaljpanelet for denne utdataparameteren.",
    "inputTextHint": "Tips: Bygg uttrykket nedenfor ved hjelp av knappen Legg til sammendragselementer.",
    "expressionHint": "Tips: Velg elementer og klikk på Legg til for å bygge uttrykk."
  }
});