define({
  "locatorUrl": "定位器 URL",
  "set": "設定",
  "locatorName": "定位器名稱",
  "locatorExample": "範例",
  "countryCode": "國碼或地區代碼",
  "eg": "例如 ",
  "countryCodeHint": "留空此值會搜尋所有國家和地區",
  "minCandidateScore": "最低候選分數",
  "minCandidateScoreHint": "留空此值將使用最低候選分數 90",
  "enableSingleField": "單一欄位選項",
  "singleFieldHint": "地址資料將位於單一欄位",
  "enableMultiField": "多個欄位選項",
  "multiFieldHint": "地址資料將位於多個欄位",
  "enableXYField": "X/Y 欄位選項",
  "xyFieldHint": "資料將包含 X/Y 座標值",
  "instructionGeocode": "新增和配置定位器服務。",
  "invalidUrlTip": "URL ${URL} 無效或不可存取。",
  "geocodeTabLabel": "位置設定",
  "lookupList": "要辨識的欄位名稱",
  "isRecognized": "會自動針對此欄位辨識下表中的欄位名稱",
  "needsEditablePointLayers": "Web 地圖至少必須包含一個可編輯點圖層。",
  "editpageAlias": "別名",
  "configureFields": "配置圖層欄位",
  "configureSingleFields": "配置單一地址欄位",
  "configureMultiFields": "配置多個地址欄位",
  "configureXYFields": "配置 X/Y 欄位",
  "noFields": "使用編輯動作來定義要顯示的一或多個欄位",
  "display": "顯示",
  "duplicate": "尋找重複項",
  "duplicateTip": "在此欄位中搜尋來源檔與目標圖層之間的相同值。/n如果找到相同的符合項，則不會從檔案中尋找記錄，並會將其標記為重複項。",
  "noSelectField": "請先選擇圖徵圖層選項",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (經度)",
  "xyFieldsLabelY": "Y (緯度)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "東移",
  "northing": "北移",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "選擇要將資料提交到的圖層。",
  "layerFieldTitle": "目標圖層",
  "tempSymbolHint": "選擇將用來顯示圖徵的符號。",
  "tempSymbolTitle": "顯示符號",
  "maxRecords": "記錄數上限",
  "maxRecordsHint": "要尋找的記錄數上限",
  "searchRadius": "搜尋半徑",
  "searchRadiusHint": "要從圖層搜尋重複圖徵的距離",
  "requiresInteger": "輸入數值。",
  "requiresInteger0100": "輸入介於 0 到 100 的數值",
  "requiresLocator": "至少新增一個有效定位器。",
  "layerFields": "圖層設定",
  "layerFieldsHint": "從將對應到來源欄位的目標圖層中指定欄位。",
  "locatorError": "定位器無效或無法存取。",
  "optionNotMatch": "跨定位器的欄位選項不一致。 容錯移轉可能無法依預期運作。",
  "targetLayerTabTitle": "目標圖層",
  "locationSettingsTabTitle": "位置設定",
  "generalSettingsTabTitle": "一般設定",
  "addTargetLayersLabel": "新增目標圖層",
  "introductoryText": "建立 widget 的指示內容",
  "defaultStartPageInstructions": "此 widget 將協助處理檔案的資料，並將該資料提交到地圖的選定圖層。<br/> <br/> 必須以逗號、tab、分號或垂直軸隔檔案中的值。",
  "noTargetLayerConfiguredErrorMsg": "未配置目標圖層",
  "noFieldsForTargetLayer": "未針對目標圖層定義圖層設定",
  "locationSettingsNotConfigured": "未適當配置位置設定"
});