define({
  "layersPage": {
    "allLayers": "Visi sluoksniai",
    "title": "Norėdami sukurti elementus, pasirinkite šabloną, o norėdami elementą redaguoti, spustelėkite ant jo žemėlapyje",
    "generalSettings": "Bendrieji parametrai",
    "layerSettings": "Sluoksnio parametrai",
    "webmapSettingsRadioBtnLabel": "Paisyti internetinio žemėlapio parametrų",
    "customSettingsRadioBtnLabel": "Adaptuoti parametrai",
    "smartActionsTabTitle": "Išmanieji veiksmai",
    "attributeActionsTabTitle": "Atributų veiksmai",
    "geocoderSettingsText": "Geokodavimo nustatymai",
    "editDescription": "Įveskite tekstą, kuris bus rodomas redagavimo srityje",
    "editDescriptionTip": "Šis tekstas rodomas virš šablono parinkiklio. Jei nereikia jokio teksto, palikite lauką tuščią.",
    "promptOnSave": "Priminti įrašyti neįrašytus pakeitimus, kai forma uždaroma arba pereinama prie kito įrašo",
    "promptOnSaveTip": "Rodyti priminimą, kai neįrašyti dabartinio elemento redagavimai. (Kopijuojant kelis elementus, įrašoma automatiškai.)",
    "promptOnDelete": "Reikalauti patvirtinimo prieš ištrinant įrašą",
    "promptOnDeleteTip": "Rodyti priminimą, prašant patvirtinti veiksmą, kai naudotojas spusteli Ištrinti.",
    "removeOnSave": "Pašalinti elementą iš žymėjimo, kai paspaudžiama Įrašyti",
    "removeOnSaveTip": "Parinktis pašalinti elementą iš žymėjimo, kai įrašas išsaugojamas.  Jei tai yra vienintelis pažymėtas įrašas, skydelis perjungiamas į šablono puslapį.",
    "useFilterEditor": "Naudoti elementų šablonų filtrą",
    "useFilterEditorTip": "Parinktis naudoti filtrų šablonų parinkiklį, kuris leidžia peržiūrėti vieno sluoksnio šabloną ir ieškoti šablonų pagal pavadinimą.",
    "groupFilteredTemplates": "Grupuoti paieškos rezultatus",
    "groupFilteredTemplatesTip": "Galimybė grupuoti paieškos rezultatus pagal sluoksnį",
    "displayShapeSelector": "Rodyti braižymo parinktis",
    "createNewFeaturesFromExisting": "Leisti kurti naują (-us) elementą (-us) iš esamo (-ų)",
    "createNewFeaturesFromExistingTip": "Parinktis, leidžianti vartotojui kopijuoti esamus elementus, norint sukurti naujus",
    "copiedFeaturesOverrideDefaults": "Reikšmė(s) iš nukopijuoto (-ų) elemento (-ų) perrašo numatytąją (-sias) reikšmę (-es) tiksliniame (-iuose) lauke (-uose)",
    "copiedFeaturesOverrideDefaultsTip": "Nukopijuotų elementų reikšmės pakeis tik sutampančių laukų numatytąsias šablono reikšmes",
    "displayShapeSelectorTip": "Parinktis, parodanti pasirinkto šablono galimų braižymo parinkčių sąrašą.",
    "displayPresetTop": "Rodyti iš anksto nustatytų reikšmių sąrašą viršuje",
    "displayPresetTopTip": "Parinktis, parodanti iš anksto nustatytų reikšmių sąrašą virš šablono parinkiklio.",
    "listenToGroupFilter": "Filtro reikšmių taikymas iš grupių filtro valdiklio norint iš anksto nustatyti laukus",
    "listenToGroupFilterTip": "Kai grupių filtro valdiklyje pritaikomas filtras, taikykite reikšmę atitinkamam iš anksto nustatytų reikšmių sąrašo laukui.",
    "keepTemplateActive": "Palikti pasirinktą šabloną aktyvų",
    "editLayerAddedFromAddData": "Leisti redaguoti sluoksnius, pridėtus iš duomenų pridėjimo valdiklio.",
    "editLayerAddedFromAddDataTip": "Redaguojami sluoksniai, pridėti prie programos per duomenų pridėjimo valdiklį, gali būti redaguojami",
    "keepTemplateActiveTip": "Jei šablonas buvo pasirinktas anksčiau, iš naujo jį pasirinkite, kai bus rodomas šablonų parinkiklis.",
    "geometryEditDefault": "Įgalinti geometrijos redagavimą pagal numatytuosius nustatymus",
    "autoSaveEdits": "Automatiškai įrašyti naujus elementus",
    "enableAttributeUpdates": "Rodyti atributų veiksmų atnaujinimo mygtuką",
    "enableAutomaticAttributeUpdates": "Automatiškai iškviesti atributų veiksmus po geometrijos atnaujinimo",
    "enableLockingMapNavigation": "Įgalinti žemėlapio naršymo užrakinimą",
    "enableMovingSelectedFeatureToGPS": "Įgalinti pasirinkto taškinio elemento perkėlimą į GPS vietą",
    "enableMovingSelectedFeatureToXY": "Įgalinti pasirinkto taškinio elemento perkėlimą į XY vietą",
    "featureTemplateLegendLabel": "Elementų šablonas ir filtro reikšmės nustatymai",
    "saveSettingsLegendLabel": "Įrašyti nustatymus",
    "geometrySettingsLegendLabel": "Geometrijos nustatymai",
    "actionsSettingsLegendLabel": "Veiksmų parametrai",
    "buttonPositionsLabel": "Mygtukų Įrašyti, Naikinti, Atgal ir Uždaryti vieta",
    "belowEditLabel": "Po Redaguoti formą",
    "aboveEditLabel": "Virš Redaguoti formą",
    "switchToMultilineInput": "Perjungti į kelių eilučių įvestį, kai viršijamas lauko ilgis",
    "enableValuePicker": "Įjungti sankirtos reikšmės parinkiklį",
    "enableValuePickerHint": "Rodyti priminimą, kai naudojant sankirtos atributo veiksmą, laukui galimos kelios vertės",
    "expandRelatedTable": "Išskleisti visas susijusias lenteles / sluoksnius įkėlus",
    "expandMainTable": "Išskleisti visus pagrindinus sluoksnius įkėlus",
    "copyAndAppendFeatureLabel": "Kopijuoti ir pridėti elementus",
    "allowCopyPolygonLabel": "Leisti kopijuoti poligoną į tašką",
    "allowCopyPolygonTooltip": "Parinktis, leidžianti kopijuoti poligono elementus į taško tikslinio elemento šablonus su geometrijos transformacijomis",
    "allowCopyLineLabel": "Leisti kopijuoti liniją į tašką",
    "allowCopyLineTooltip": "Parinktis, leidžianti kopijuoti linijos elementus į taško tikslinio elemento šablonus su geometrijos transformacijomis",
    "pointAtStartLabel": "Pradžios taškas",
    "pointAtStartTooltip": "Pridėti tašką kopijuojamos linijos pradžioje",
    "pointAtEndLabel": "Pabaigos taškas",
    "pointAtEndTooltip": "Pridėti tašką kopijuojamos linijos pabaigoje",
    "layerSettingsTable": {
      "allowDelete": "Leisti ištrinti",
      "allowDeleteTip": "Leisti ištrinti – parinktis, leidžianti naudotojui ištrinti elementą; išjungiama, jei sluoksnio ištrinti negalima",
      "edit": "Redaguojama",
      "editTip": "Redaguojama – parinktis, leidžianti įtraukti sluoksnį į valdiklį",
      "label": "Sluoksnis",
      "labelTip": "Sluoksnis – sluoksnio pavadinimas, kaip nurodyta žemėlapyje",
      "update": "Išjungti geometrijos redagavimą",
      "updateTip": "Išjungti geometrijos redagavimą – parinktis, leidžianti išjungti galimybę perkelti geometriją, kai įkeliama, arba perkelti geometriją į esamą elementą",
      "allowUpdateOnly": "Tik naujinti",
      "allowUpdateOnlyTip": "Tik atnaujinti – parinktis, leidžianti tik modifikuoti esamus elementus. Ji įjungiama pagal numatytuosius nustatymus ir išjungiama, jei sluoksnis nepalaiko naujų elementų kūrimo",
      "fieldsTip": "Modifikuoti redaguotinus laukus ir apibrėžti išmaniuosius atributus",
      "actionsTip": "Veiksmai – parinktis laukams redaguoti arba susijusiems sluoksniams / lentelėms pasiekti",
      "description": "Aprašymas",
      "descriptionTip": "Aprašas – teksto, kuris turėtų būti rodomas atributų puslapio viršuje, įvedimo parinktis.",
      "relationTip": "Rodyti susijusius sluoksnius ir lenteles"
    },
    "editFieldError": "Neredaguotinuose sluoksniuose laukų modifikavimas ir išmanieji atributai negalimi",
    "noConfigedLayersError": "Išmanusis redaktorius reikalauja vieno ar kelių redaguojamų sluoksnių",
    "toleranceErrorMsg": "Netinkama numatytoji sankirtos tolerancijos reikšmė",
    "pixelsToleranecErrorMsg": "Netinkama numatytoji pikselių tolerancijos reikšmė",
    "invalidMaxCharacterErrorMsg": "Netinkama reikšmė perkeliant į kelių eilučių įvestį",
    "featuresSelectionTolerance": "Nustatyti elemento pasirinkimo toleranciją pikseliais",
    "featuresSelectionToleranceTooltip": "Leidžia naudotojams lengvai atverti atributo redagavimo sritį spustelėjus ant elemento",
    "featuresSelectionToleranceErrorMsg": "Netinkama elemento pasirinkimo tolerancijos reikšmė",
    "autoSaveAttrUpdates": "Automatiškai įrašyti atributų ir geometrijos naujinimus",
    "defaultCoordinateSystem": "Numatytoji koordinačių sistema",
    "defaultCoordinateSystemTooltip": "Nustatykite numatytąją koordinačių sistemą, naudojamą perkeliant pasirinktą taškinį elementą į naują padėtį"
  },
  "editDescriptionPage": {
    "title": "Nurodyti <b>${layername}</b> atributų apžvalgos tekstą "
  },
  "fieldsPage": {
    "title": "Konfigūruoti <b>${layername}</b> laukus",
    "copyActionTip": "Atributų veiksmai",
    "editActionTip": "Išmanieji veiksmai",
    "description": "Veiksmų redagavimo mygtuku įjunkite išmaniųjų atributų sluoksnį. Išmaniesiems atributams gali reikėti, slėpti arba išjungti lauką atsižvelgiant į kitų laukų reikšmes. Veiksmų kopijavimo mygtuku aktyvinkite ir nurodykite lauko reikšmės šaltinį pagal sankirtą, adresą, koordinates ir iš anksto nustatytą reikšmę.",
    "fieldsNotes": "* tai yra privalomas laukas.  Jei šiam laukui nepažymėjote Rodyti, o redagavimo šablone nepateikiama to lauko reikšmė, jūs negalėsite įrašyti naujo įrašo.",
    "smartAttachmentText": "Konfigūruoti išmaniuosius veiksmus priedams",
    "smartAttachmentPopupTitle": "Konfigūruoti išmaniuosius veiksmus priedams <b>${layername}</b>",
    "noDisplayFieldWarningMsg": "Pasirinkite bent vieną rodymo lauką sluoksniui ${layerName}",
    "fieldsSettingsTable": {
      "display": "Rodyti",
      "displayTip": "Atvaizdavimas – nurodyti, ar laukas yra matomas",
      "edit": "Redaguojama",
      "editTip": "Redaguojama – patikrinti, ar laukas yra atributų formoje",
      "fieldName": "Pavadinimas",
      "fieldNameTip": "Pavadinimas – lauko pavadinimas, nurodytas duomenų bazėje",
      "fieldAlias": "Pseudonimas",
      "fieldAliasTip": "Pseudonimas – lauko pavadinimas, nurodytas žemėlapyje",
      "canPresetValue": "Nustatyta iš anksto",
      "canPresetValueTip": "Iš anksto nustatytos reikšmės – parinktis, leidžianti parodyti lauką iš anksto nustatytame laukų sąraše ir leidžianti naudotojui nustatyti reikšmę prieš redaguojant",
      "actions": "Veiksmai",
      "actionsTip": "Veiksmai – keisti laukų tvarką ar nustatyti išmaniuosius atributus"
    },
    "smartAttSupport": "Išmanieji atributai nėra palaikomi būtinuose duomenų bazės laukuose"
  },
  "actionPage": {
    "title": "Konfigūruoti <b>${fieldname}</b> atributų veiksmus",
    "smartActionTitle": "Konfigūruoti išmaniuosius veiksmus laukui <b>${fieldname}</b>",
    "description": "Veiksmai visada išjungiami, nebent nurodote kriterijus, kurie juos suaktyvintų.  Veiksmai apdorojami tam tikra tvarka ir vienam laukui suaktyvinamas tik vienas veiksmas.  Norėdami nustatyti kriterijus, naudokite mygtuką Kriterijų redagavimas.",
    "copyAttributesNote": "Bet kurio veiksmo su grupės pavadinimu išjungimas yra tas pat kaip nepriklausomas veiksmo redagavimas. Tokiu būdu šio atitinkamos grupės lauko veiksmas bus pašalintas.",
    "searchPlaceHolder": "Paieška",
    "expandAllLabel": "Išskleisti visus sluoksnius",
    "selectAllLabel": "Pasirinkti visus laukus",
    "domainListTitle": "Domeno laukai",
    "noValidFieldTypeMsg": "Šiam duomenų tipui žemėlapyje nėra tinkamo sluoksnio",
    "actionsSettingsTable": {
      "rule": "Veiksmas",
      "ruleTip": "Veiksmas – veiksmas atliekamas, kai yra atitinkami kriterijai",
      "expression": "Išraiška",
      "expressionTip": "Išraiška – gauta sąlyga SQL formatu pagal nustatytus kriterijus",
      "groupName": "Grupės pavadinimas",
      "groupNameTip": "Grupės pavadinimas – rodomas grupės, iš kurios pritaikyta išraiška, pavadinimas",
      "actions": "Kriterijai",
      "actionsTip": "Kriterijai – keisti taisyklių tvarką ir nustatyti kriterijus, kai jie suaktyvinami"
    },
    "copyAction": {
      "description": "Jei suaktyvinta, lauko reikšmės šaltiniai apdorojami eiliškumo tvarka, kol suaktyvinamas tinkamas kriterijus arba baigiasi sąrašas. Norėdami apibrėžti kriterijus, naudokite kriterijų redagavimo mygtuką.",
      "intersection": "Sankirta",
      "coordinates": "Koordinatės",
      "address": "Adresas",
      "preset": "Nustatyta iš anksto",
      "actionText": "Veiksmai",
      "criteriaText": "Kriterijai",
      "enableText": "Įjungta"
    },
    "actions": {
      "hide": "Slėpti",
      "required": "Privalomas",
      "disabled": "Neleidžiama"
    },
    "editOptionsPopup": {
      "editAttributeGroupHint": "Įspėjimas: redaguojant nepriklausomai bus pašalintas pasirinktas atributo veiksmas, susijęs su šiuo šios grupės lauku",
      "editGroupHint": "Įspėjimas: redaguojant nepriklausomai bus pašalintas pasirinktas išmanusis veiksmas, susijęs su šiuo šios grupės lauku",
      "popupTitle": "Pasirinkti redagavimo parinktį",
      "editAttributeGroup": "Pasirinktas atributo veiksmas apibrėžiamas per grupę. Norėdami redaguoti atributo veiksmą, pasirinkite vieną iš šių parinkčių:",
      "expression": "Pasirinkto išmaniojo veiksmo išraiška apibrėžiama per grupę. Norėdami redaguoti išmanųjį veiksmą, pasirinkite vieną iš šių išraiškų:",
      "editGroupButton": "Redaguoti grupę",
      "editIndependentlyButton": "Redaguoti atskirai"
    }
  },
  "filterPage": {
    "submitHidden": "Pateikti laukų atributų duomenis, net jei jie paslėpti",
    "title": "Konfigūruoti ${action} taisyklės sąlygą",
    "filterBuilder": "Nustatyti veiksmą laukui, kai įrašas atitinka ${any_or_all} iš šių sąlygų",
    "noFilterTip": "Naudodami aukščiau pateiktus įrankius, nustatykite patvirtinimą tam atvejui, kai veiksmas nėra aktyvus."
  },
  "geocoderPage": {
    "setGeocoderURL": "Nustatyti geokodavimo paslaugos URL",
    "hintMsg": "Pastaba: keičiate geokodavimo paslaugą, atnaujinkite sukonfigūruotų geokodavimo laukų susiejimus.",
    "invalidUrlTip": "URL ${URL} yra neteisingas arba nepasiekiamas."
  },
  "addressPage": {
    "popupTitle": "Adresas",
    "checkboxLabel": "Gauti reikšmę iš geokodavimo paslaugos",
    "selectFieldTitle": "Aprašas",
    "geocoderHint": "Norėdami pakeisti geokodavimo paslaugą, paspauskite geokodavimo nustatymų mygtuką bendruosiuose nustatymuose",
    "prevConfigruedFieldChangedMsg": "Anksčiau sukonfigūruotas atributas esamuose geokodavimo paslaugos nustatymuose nerastas. Atributo reikšmė nustatyta iš naujo kaip numatytoji.",
    "questionMark": "?",
    "consumesCredits": "Šis įrankis naudoja kreditus, kai pasitelkiama ArcGIS Online pasaulinio geokodavimo paslauga"
  },
  "coordinatesPage": {
    "popupTitle": "Koordinatės",
    "checkboxLabel": "Gauti koordinates",
    "coordinatesSelectTitle": "Nuorodinė sistema",
    "coordinatesAttributeTitle": "Aprašas",
    "mapSpatialReferenceOptionLabel": "Žemėlapio koordinačių sistema",
    "latLongOptionLabel": "Platuma/Ilguma",
    "MGRS": "Karinio tinklelio atskaitos sistema (MGRS)",
    "allGroupsCreatedMsg": "Visos galimos grupės jau sukurtos",
    "coordinatesSourceTitle": "Koordinačių šaltinis",
    "featureLocation": "Elemento vieta",
    "myLocation": "Mano vieta",
    "LatLong": {
      "y": "Platuma",
      "x": "Ilguma",
      "xy": "Ilguma, platuma",
      "yx": "Platuma, ilguma"
    },
    "MapSpatialReference": {
      "y": "Y",
      "x": "X",
      "xy": "XY",
      "yx": "YX"
    }
  },
  "presetPage": {
    "popupTitle": "Nustatyta iš anksto",
    "checkboxLabel": "Laukas bus nustatytas iš anksto",
    "showOnlyDomainFields": "Rodyti tik domeno laukus",
    "hideInPresetDisplay": "Slėpti dabar rodomą reikšmę",
    "presetValueLabel": "Dabartinė iš anksto nustatyta reikšmė yra:",
    "changePresetValueHint": "Norėdami pakeisti šią iš anksto nustatytą reikšmę, spauskite mygtuką Apibrėžti iš anksto nustatytas reikšmes bendruosiuose nustatymuose"
  },
  "intersectionPage": {
    "groupNameLabel": "Grupės pavadinimas",
    "dataTypeLabel": "Duomenų tipas",
    "ignoreLayerRankingCheckboxLabel": "Nepaisyti sluoksnių rūšiavimo ir rasti artimiausią elementą visuose nurodytuose sluoksniuose",
    "intersectingLayersLabel": "Sluoksnis (-iai) reikšmei išgauti",
    "layerAndFieldsApplyLabel": "Sluoksnis (-iai) ir laukas (-ai) išgautai reikšmei taikyti",
    "checkboxLabel": "Gauti reikšmę iš sankirtos sluoksnio lauko",
    "layerText": "Sluoksniai",
    "fieldText": "Laukai",
    "actionsText": "Veiksmai",
    "toleranceSettingText": "Tolerancijos nustatymai",
    "addLayerLinkText": "Pridėti sluoksnį",
    "useDefaultToleranceText": "Naudoti numatytąją toleranciją",
    "toleranceValueText": "Tolerancijos reikšmė",
    "toleranceUnitText": "Tolerancijos vienetai",
    "pixelsUnitText": "Pikseliai",
    "useLayerName": "- Naudoti sluoksnio pavadinimą -",
    "noLayersMessage": "Jokiame žemėlapio sluoksnyje nerasta laukų, kurie atitiktų pasirinktą duomenų tipą.",
    "intersectionLayerHint": "Sluoksnių reitingavimas nustatytas mažėjimo tvarka. Naudokite žemiau Veiksmai esančias rodykles, kad pakeistumėte sluoksnių eiliškumą ir sankirtos prioritetą."
  },
  "presetAll": {
    "popupTitle": "Apibrėžti numatytąsias iš anksto nustatytas reikšmes",
    "deleteTitle": "Ištrinti iš anksto nustatytą reikšmę",
    "hintMsg": "Čia pateikti visi unikalūs iš anksto nustatytų laukų pavadinimai. Pašalinus iš anksto nustatytą lauką, atitinkamas laukas bus pašalintas iš visų sluoksnių / lentelių."
  },
  "intersectionTolerance": {
    "intersectionLabel": "Numatotoji sankirtos tolerancija visiems objektams",
    "intersectionTitle": "Įjungti visuotinę sankirtų toleranciją",
    "pixelsToleranceLabel": "Numatotoji sankirtos tolerancija (taško vertė), kuri turi būti taikoma tik taškų objektams",
    "pixelsToleranceTitle": "Jei visų elementų numatytoji sankirtos tolerancija nustatyta kaip 0, taškiniams elementams taikyti šį nustatymą"
  },
  "smartActionsPage": {
    "smartActionLabel": "Konfigūruoti išmanųjį veiksmą",
    "addNewSmartActionLinkText": "Pridėti naują",
    "definedActions": "Nurodyti veiksmai",
    "priorityPopupTitle": "Nustatyti išmaniųjų veiksmų prioritetą",
    "priorityPopupColumnTitle": "Išmanieji veiksmai",
    "priorityOneText": "1",
    "priorityTwoText": "2",
    "priorityThreeText": "3",
    "groupNameLabel": "Grupės pavadinimas",
    "layerForExpressionLabel": "Išraiškų sluoksnis",
    "layerForExpressionNote": "Pastaba: šio sluoksnio laukai naudojami išraiškos kriterijams apibrėžti. Parinktis Sluoksniai ir laukai, skirti taikyti rodo tik tuos sluoksnius ir lenteles, kurių laukai apibrėžti išraiškoje.",
    "expressionText": "Išraiška",
    "editExpressionLabel": "Redaguoti užklausą",
    "layerAndFieldsApplyLabel": "Sluoksniai ir laukai, skirti taikyti",
    "submitAttributeText": "Pateikti laukų atributų duomenis, net jei jie paslėpti",
    "priorityColumnText": "Prioritetas",
    "requiredGroupNameMsg": "Ši reikšmė privaloma",
    "uniqueGroupNameMsg": "Įveskite unikalų grupės pavadinimą, nes grupė tokiu pavadinimu jau yra.",
    "deleteGroupPopupTitle": "Ištrinti išmaniųjų veiksmų grupę",
    "deleteGroupPopupMsg": "Ištrynus grupę, išraiška bus pašalinta iš visų susijusių laukų veiksmų.",
    "invalidExpression": "Turi būti įrašyta išraiška",
    "warningMsgOnLayerChange": "Nurodyta išraiška ir laukai, kuriai ji taikoma, bus išvalyti.",
    "smartActionsTable": {
      "name": "Pavadinimas",
      "expression": "Išraiška",
      "definedFor": "Apibrėžta"
    }
  },
  "attributeActionsPage": {
    "name": "Pavadinimas",
    "type": "Tipas",
    "deleteGroupPopupTitle": "Ištrinti atributų veiksmų grupę",
    "deleteGroupPopupMsg": "Ištrynus grupę, atributo veiksmas bus pašalintas iš visų susijusių laukų.",
    "alreadyAppliedActionMsg": "${action} veiksmas taikomas šiam grupės laukui",
    "alreadyAppliedActionLayerMsg": "${action} veiksmas taikomas šiame lauke iš sluoksnių parametrų",
    "appliedGroupName": "${groupName}",
    "noPresetFieldsMsg": "Ši grupė neturi susietų laukų.",
    "presetNoFieldWarningMsg": "Sukonfigūruokite bent vieną lauką iš anksto nustatytai grupei: ${groupName}"
  },
  "chooseFromLayer": {
    "fieldLabel": "Darbui lauke",
    "valueLabel": "Reikšmė",
    "selectValueLabel": "Pasirinkite reikšmę",
    "domainFieldHintLabel": "Pasirinkta reikšmė yra koduotos reikšmės domenas. Reikšmė: bus naudojama ${domainValue}"
  },
  "presetPopup": {
    "presetValueLAbel": "Iš anksto nustatyta reikšmė"
  },
  "dataType": {
    "esriFieldTypeString": "Tekstas",
    "esriFieldTypeInteger": "Skaičius",
    "esriFieldTypeDate": "Data",
    "esriFieldTypeGUID": "GUID"
  },
  "relativeDates": {
    "dateTypeLabel": "Datos tipas",
    "valueLabel": "Reikšmė",
    "fixed": "Fiksuotas",
    "current": "Dabartinis",
    "past": "Praėjęs",
    "future": "Būsimas",
    "popupTitle": "Pasirinkti reikšmę",
    "hintForFixedDateType": "Patarimas: nurodyta data ir laikas bus naudojami kaip iš anksto nustatyta numatytoji reikšmė",
    "hintForCurrentDateType": "Patarimas: dabartinė data ir laikas bus naudojami kaip iš anksto nustatyta numatytoji reikšmė",
    "hintForPastDateType": "Patarimas: nurodyta data ir laikas bus atimti iš dabartinės datos ir laiko ir skirti iš anksto nustatytai numatytai reikšmei.",
    "hintForFutureDateType": "Patarimas: nurodyta data ir laikas bus pridėti prie dabartinės datos ir laiko ir skirti iš anksto nustatytai numatytai reikšmei.",
    "noDateDefinedTooltip": "Data neapibrėžta",
    "relativeDateWarning": "Kad galėtumėte įrašyti numatytąją iš anksto nustatytą reikšmę, turi būti nurodytos datos ir laiko reikšmės.",
    "customLabel": "Adaptuotas"
  },
  "relativeDomains": {
    "fieldSetTitle": "Sąrašas",
    "valueText": "Vertė",
    "defaultText": "Numatytoji",
    "selectedDomainFieldsHint": "Pasirinkti domeno laukai: ${domainFields}",
    "selectDefaultDomainMsg": "Pasirinkite numatytosios reikšmės domeną arba užtikrinkite, kad pasirinkto numatyto domeno žymimasis langelis yra pažymėtas"
  }
});