define({
  "transparencyLabel": "Priehľadnosť",
  "outline": "Obrys",
  "fill": "Výplň (Farba sa použije iba v prípade, že je štýl nastavený na plný)",
  "style": "Štýl",
  "mandatoryLabel": "Povinná evakuačná vzdialenosť",
  "mandatoryButtonLabel": "Konfigurovať nastavenia povinnej evakuačnej vzdialenosti",
  "safeLabel": "Bezpečná evakuačná vzdialenosť",
  "safeButtonLabel": "Konfigurovať nastavenia bezpečnej evakuačnej vzdialenosti",
  "selectOpLayerLabel": "Vyberte operačnú vrstvu pre výsledky",
  "selectDefaultMeasurementLabel": "Vyberte predvolenú mernú jednotku",
  "helpIconTooltip": "Zoznam operačných vrstiev je vyplnený vrstvami z aktuálnej webovej mapy, ktoré sú typom geometrie polygónu.",
  "lineStyles": {
    "esriSLSDash": "Pomlčka",
    "esriSLSDashDot": "Pomlčka bodka",
    "esriSLSDashDotDot": "Pomlčka bodka bodka",
    "esriSLSDot": "Bodka",
    "esriSLSLongDash": "Dlhá pomlčka",
    "esriSLSLongDashDot": "Dlhá pomlčka bodka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Krátka pomlčka",
    "esriSLSShortDashDot": "Krátka pomlčka bodka",
    "esriSLSShortDashDotDot": "Krátka pomlčka bodka bodka",
    "esriSLSShortDot": "Krátka bodka",
    "esriSLSSolid": "Plné"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Späť",
    "esriSFSCross": "Priečne",
    "esriSFSDiagonalCross": "Uhlopriečne",
    "esriSFSForwardDiagonal": "Vpred",
    "esriSFSHorizontal": "Vodorovný",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Plné",
    "esriSFSVertical": "Zvislý"
  },
  "threatTypeLabel": "Typ ohrozenia",
  "symbologyLabel": "Symbolika",
  "generalLabel": "Všeobecné",
  "addThreatTypesLabel": "Pridať typ ohrozenia",
  "threatTypeColLabel": "Typ chemického ohrozenia",
  "actions": "Akcie",
  "newThreatTypePopupLabel": "Nový typ ohrozenia",
  "chooseDefaultThreatTypeIconLabel": "Vybrať z predvoleného",
  "mandatoryDistance": "Povinná evakuačná vzdialenosť",
  "safeDistance": "Bezpečná evakuačná vzdialenosť",
  "units": "Jednotky",
  "chooseDefaultThreatLabel": "Zvoľte predvolený typ ohrozenia",
  "defaultThreatTypePopUpLabel": "Predvolené typy ohrozenia",
  "editThreatLabel": "Upraviť ohrozenia",
  "defaultThreatTypeIconTooltip": "Zoznam predvolených typov ohrozenia",
  "uniqueThreatTypeMsg": "Zadať unikátny typ ohrozenia, ohrozenia s týmto menom už existuje.",
  "requiredThreatTypeMsg": "Tento stĺpec je povinný",
  "unitMeasureLabel": "Vzdialenosti sú v {0}",
  "pipeBombLabel": "Potrubná bomba",
  "suicideBombLabel": "Samovražedná bomba",
  "briefcaseLabel": "Kufrík",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/DODÁVKA",
  "smallDeliveryTruckLabel": "Malé nákladné auto",
  "containerWaterTruckLabel": "Kontajner/Cisterna",
  "semiTrailerLabel": "Polo-karavan",
  "lpgSafeDistanceLable": "Bezpečná vzdialenosť",
  "fireBallDiameterLable": "Priemer explózie",
  "lpgthreatTypeColLabel": "Typ ohrozenia LPG",
  "threatTypeCatagoryLabel": "Kategória typu ohrozenia",
  "chemicalThreatLegendLabel": "Chemické ohrozenie",
  "lpgThreatLegendLabel": "Ohrozenie LPG",
  "fireballButtonLabel": "Konfigurovať nastavenia priemeru explózie",
  "safeDistanceButtonLabel": "Konfigurovať nastavenia bezpečnej vzdialenosti",
  "chemicalThreatCatagoryLabel": "Chemické",
  "lpgThreatCatagoryLabel": "LPG",
  "smallLPGTank": "Malá nádrž LPG",
  "largeLPGTank": "Veľká nádrž LPG",
  "commercialResidentialLPGTank": "Priemyselná/rezidenčná nádrž LPG",
  "smallLPGTruck": "Malé nákladné auto na LPG",
  "semiTankerLPG": "Polo-nádrž LPG"
});