define({
  "_widgetLabel": "Analiză privind amenințările",
  "threatAnalysisMainPageTitle": "Pe baza ghidului de combatere a terorismului (JCAT)",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Locație de intrare",
  "interactive": "Interactiv",
  "fromCoord": "Coordonată fixă",
  "existingFeature": "Din obiecte spațiale existente",
  "threatAnalysisCoordInputLabel": "Localizare amenințare",
  "enterCoords": "Introducere coordonate",
  "threatAddPointToolTip": "Adăugare localizare amenințare",
  "threatDrawPointToolTip": "Faceți clic pentru a adăuga localizarea amenințării",
  "threatType": "Tip de amenințare",
  "threatPlaceholder": "Scrieți pentru a căuta o amenințare",
  "mandatoryLabel": "Distanță obligatorie de evacuare",
  "safeLabel": "Distanță sigură de evacuare",
  "zoneTypeLabel": "Tip de zonă",
  "feetLabel": "Ft",
  "metersLabel": "Metri",
  "unitsLabel": "Unități",
  "threatGraphicLayer": "Grafic cu amenințarea",
  "settingsTitle": "Setări",
  "mandatoryButtonLabel": "Configurare setări distanță obligatorie de evacuare",
  "safeButtonLabel": "Configurare setări adăpost",
  "style": "Stil",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Linie",
    "esriSLSDashDot": "Linie punct",
    "esriSLSDashDotDot": "Linie punct punct",
    "esriSLSDot": "Punct",
    "esriSLSLongDash": "Linie lungă",
    "esriSLSLongDashDot": "Linie lungă punct",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Linie scurtă",
    "esriSLSShortDashDot": "Linie scurtă punct",
    "esriSLSShortDashDotDot": "Linie scurtă punct punct",
    "esriSLSShortDot": "Punct scurt",
    "esriSLSSolid": "Continuu"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Înapoi",
    "esriSFSCross": "Cruce",
    "esriSFSDiagonalCross": "Diagonală",
    "esriSFSForwardDiagonal": "Înainte",
    "esriSFSHorizontal": "Orizontală",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Continuu",
    "esriSFSVertical": "Verticală"
  },
  "resultsTitle": "Rezultate",
  "publishTABtn": "Publicare",
  "layerName": "Nume strat tematic publicat",
  "invalidLayerName": "Numele stratului tematic trebuie să includă doar caractere alfanumerice și de subliniere",
  "missingLayerNameMessage": "Trebuie să introduceți un nume valabil al stratului tematic înainte de a putea publica",
  "publishingFailedLayerExists": "Publicarea a eșuat: Aveți deja un serviciu de obiecte spațiale denumit {0}. Alegeți un alt nume pentru stratul tematic.",
  "checkService": "Bifați serviciu: {0}",
  "createService": "Creați serviciu: {0}",
  "unableToCreate": "Nu se poate crea: {0}",
  "addToDefinition": "Adăugați la definiție: {0}",
  "successfullyPublished": "A fost publicat cu succes stratului tematic web",
  "successfullyAppended": "Noile obiecte spațiale au fost adăugate cu succes la stratul tematic web",
  "manageWebLayerText": "Administrați stratul tematic web",
  "userRole": "Nu se poate crea serviciu, deoarece utilizatorul nu are permisiunile",
  "retrieveExistingLayerError": "Imposibil de preluat {0}. Publicați utilizând un alt nume pentru stratul tematic",
  "publishToNewLayer": "Publicați rezultatele în cadrul unui nou strat tematic de obiect spațial",
  "layerNameExists": "Numele stratului tematic există deja. Utilizați un nume de strat tematic diferit.",
  "pipeBombLabel": "Bombă artizanală",
  "suicideBombLabel": "Sinucigaș cu bombă",
  "briefcaseLabel": "Servietă",
  "carLabel": "Autoturism",
  "suvVanLabel": "SUV/camionetă",
  "smallDeliveryTruckLabel": "Camion de livrare de mici dimensiuni",
  "containerWaterTruckLabel": "Container/cisternă",
  "semiTrailerLabel": "Semiremorcă",
  "transparencyLabel": "Transparență",
  "outline": "Contur",
  "fill": "Umplere (culoarea se aplică doar când stilul este setat la continuu)",
  "createBtn": "Creați zone",
  "clearBtn": "Golire",
  "invalidNumberMessage": "Valoarea introdusă nu este valabilă",
  "invalidRangeMessage": "Valoarea trebuie să fie mai mare decât 0",
  "parseCoordinatesError": "Imposibil de analizat coordonatele. Verificați datele introduse.",
  "selectDrawModeLabel": "Selectaţi modul de trasare",
  "selectFeatureLabel": "Selectați obiectul spațial din acest strat",
  "fireBallDiameterLable": "Diametrul mingii de foc",
  "lpgSafeDistanceLable": "Distanță sigură",
  "threatTypeCatagoryLabel": "Categoria tipului de amenințare",
  "fireballButtonLabel": "Configurați setările diametrului mingii de foc",
  "safeDistanceButtonLabel": "Configurați setările distanță sigure",
  "chemicalThreatCatagoryLabel": "Chimică",
  "lpgThreatCatagoryLabel": "Gaz Petrolier Lichefiat",
  "chemicalThreatLabel": "Amenințare chimică",
  "lpgThreatLabel": "Amenințare GPL",
  "fireBallDiameterFieldAlias": "Diametrul mingii de foc GPL",
  "lpgSafeDistanceFieldAlias": "Distanță sigură GPL",
  "smallLPGTank": "Rezervor de GPL mic",
  "largeLPGTank": "Rezervor de GPL mare",
  "commercialResidentialLPGTank": "Rezervor de GPL comercial/rezidențial",
  "smallLPGTruck": "Camion de GPL mic",
  "semiTankerLPG": "Autocisternă de GPL"
});