define({
  "_widgetLabel": "Inteligentny edytor",
  "_featureAction_SmartEditor": "Inteligentny edytor",
  "noEditPrivileges": "Twoje konto nie ma uprawnień do tworzenia ani modyfikowania danych.",
  "loginPopupTitle": "Zaloguj się",
  "loginPopupMessage": "Widżet ${widgetName} wymaga uprawnień i kredytów, aby wyszukiwać i przechowywać informacje adresowe. Czy chcesz się zalogować i korzystać z tej funkcji?",
  "noCreditsOrPrivilegeWarningMessage": "Twoje konto nie ma uprawnień ani kredytów, aby wyszukiwać i przechowywać informacje adresowe za pomocą widżetu ${widgetName}. Skontaktuj się z administratorem swojej instytucji, aby uzyskać uprawnienia i kredyty. Kliknij przycisk OK, aby kontynuować edytowanie.",
  "unableToUseLocator": "Lokalizator jest niedostępny. Działanie lub działania dotyczące atrybutów adresu nie zostaną wykonane. Kliknij przycisk OK, aby kontynuować edytowanie.",
  "locatorDisabledWaning": "Lokalizator nie jest włączony. Skontaktuj się z administratorem swojej instytucji, aby poprosić o dostęp do tej funkcji. Kliknij przycisk OK, aby kontynuować edytowanie.",
  "noFeatureInAIWarning": "Nie wybrano obiektu (obiektów). Wybierz obiekt, aby dokonać zmian lub kliknij opcję Anuluj, aby wrócić do ekranu głównego.",
  "noEditableLayerWarning": "Twoje konto nie ma uprawnień do tworzenia lub modyfikowania danych. Możliwe też, że ta mapa internetowa nie zawiera żadnych warstw edytowalnych.",
  "noVisibleCreateLayerWarning": "Warstwa lub warstwy nie są widoczne przy bieżącym poziomie powiększenia. Powiększ lub pomniejsz, aby utworzyć/zmodyfikować obiekty.",
  "noVisibleUpdateLayerWarning": "Warstwa lub warstwy nie są widoczne przy bieżącym poziomie powiększenia. Powiększ lub pomniejsz, aby zmodyfikować obiekty.",
  "checkLayerVisibilityInWebMapWarning": "Upewnij się, że warstwy są widoczne na mapie, aby utworzyć lub zmodyfikować obiekty.",
  "showSelectionInAITitle": "Obiekty wybrane",
  "showSelectionInAIMsg": "Czy chcesz wczytać bieżący wybór w widżecie ${widgetName}?",
  "widgetActive": "Aktywny",
  "widgetNotActive": "Nieaktywny",
  "pressStr": "Naciśnij ",
  "ctrlStr": " CTRL, ",
  "snapStr": " aby włączyć dociąganie",
  "noAvailableTempaltes": "Brak dostępnych szablonów",
  "editorCache": " — bufor edytora",
  "presetFieldAlias": "Pole",
  "presetValue": "Wartość ustawiona wstępnie",
  "usePresetValues": " Użyj wartości ustawionych wstępnie (tylko nowe obiekty)",
  "editGeometry": " Edytuj geometrię",
  "savePromptTitle": "Zapisz obiekt",
  "savePrompt": "Czy chcesz zapisać bieżący obiekt?",
  "deletePromptTitle": "Usuń obiekt",
  "deleteAttachment": "Usuń załącznik",
  "deletePrompt": "Czy na pewno chcesz usunąć wybrany obiekt?",
  "attachmentLoadingError": "Błąd przesyłania załączników",
  "attachmentSaveDeleteWarning": "Ostrzeżenie: zmiany w załącznikach są zapisywane automatycznie",
  "autoSaveEdits": "Automatycznie zapisuj nowe obiekty",
  "addNewFeature": "Utwórz nowy obiekt",
  "featureCreationFailedMsg": "Nie można utworzyć nowego rekordu/obiektu",
  "relatedItemTitle": "Powiązana tabela/warstwa",
  "relatedFeatureCount": "${layerTitle} z obiektami (${featureCount})",
  "createNewFeatureLabel": "Utwórz nowy obiekt dla warstwy ${layerTitle}",
  "invalidRelationShipMsg": "Upewnij się, że pole klucza podstawowego: '${parentKeyField}' ma prawidłową wartość",
  "pendingFeatureSaveMsg": "Zapisz edycje obiektów przed utworzeniem powiązanego obiektu.",
  "attachmentsRequiredMsg": "(*) Wymagane są załączniki.",
  "coordinatePopupTitle": "Przesuń obiekt do lokalizacji XY",
  "coordinatesSelectTitle": "Układ współrzędnych:",
  "mapSpecialReferenceDropdownOption": "Odniesienie przestrzenne mapy",
  "latLongDropdownOption": "Szer. geogr./dł. geogr.",
  "mgrsDropdownOption": "Military Grid Reference System (MGRS)",
  "mgrsTextBoxLabel": "Współrzędne:",
  "xAttributeTextBoxLabel": "Współrzędna X:",
  "yAttributeTextBoxLabel": "Współrzędna Y:",
  "latitudeTextBoxLabel": "Szerokość geograficzna:",
  "longitudeTextBoxLabel": "Długość geograficzna:",
  "presetGroupFieldsLabel": "Grupa '${groupName}' zostanie zastosowana dla następujących pól warstwy:",
  "presetGroupNoFieldsLabel": "Grupa '${groupName}' nie ma żadnych powiązanych pól",
  "groupInfoLabel": "Informacje o grupie dla grupy '${groupName}'",
  "editGroupInfoIcon": "Edytuj wartość grupy dla grupy ${groupName}",
  "filterEditor": {
    "all": "Wszystkie",
    "noAvailableTempaltes": "Brak dostępnych szablonów",
    "searchTemplates": "Szablony wyszukiwania",
    "filterLayerLabel": "Filtrowanie warstw"
  },
  "invalidConfiguration": "Widżet nie został skonfigurowany lub warstwy w tej konfiguracji nie znajdują się już na mapie. Otwórz aplikację w trybie kreatora i ponownie skonfiguruj widżet.",
  "geometryServiceURLNotFoundMSG": "Nie można uzyskać adresu URL usługi geometrii",
  "clearSelection": "Zamknij",
  "refreshAttributes": "Zaktualizuj dynamiczne atrybuty obiektu",
  "automaticAttributeUpdatesOn": "Automatyczna aktualizacja atrybutów obiektu: Wł.",
  "automaticAttributeUpdatesOff": "Automatyczna aktualizacja atrybutów obiektu: Wył.",
  "moveSelectedFeatureToGPS": "Przesuń wybrany obiekt do bieżącej lokalizacji GPS",
  "moveSelectedFeatureToXY": "Przesuń wybrany obiekt do lokalizacji XY",
  "mapNavigationLocked": "Nawigacja po mapie: Zablokowane",
  "mapNavigationUnLocked": "Nawigacja po mapie: Odblokowane",
  "copyFeatures": {
    "title": "Wybierz obiekty do skopiowania",
    "createFeatures": "Utwórz obiekty",
    "createSingleFeature": "Utwórz jeden obiekt wieloczęściowy",
    "createOneSingleFeature": "Utwórz obiekt",
    "noFeaturesSelectedMessage": "Nie wybrano obiektów",
    "selectFeatureToCopyMessage": "Wybierz obiekty do skopiowania",
    "multipleFeatureSaveWarning": "Utworzenie wielu obiektów za pomocą tej funkcji spowoduje natychmiastowe zapisanie wszystkich nowych obiektów. Dopasowywanie pól nie jest obsługiwane podczas tworzenia nowego obiektu wieloczęściowego.",
    "copyFeatureUpdateGeometryError": "Nie można zaktualizować geometrii wybranych obiektów",
    "canNotSaveMultipleFeatureWarning": "Można skopiować tylko jeden obiekt, gdy docelowa warstwa punktowa ma unikalne pola wartości.",
    "createOnlyOneMultipartFeatureWarning": "Można skopiować tylko jeden obiekt lub utworzyć jeden obiekt wieloczęściowy, gdy warstwa docelowa ma unikalne pola wartości.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "Wybrane obiekty w warstwie ${layerName}: ${selectedFeatures} z ${totalFeatures}"
  },
  "addingFeatureError": "Wystąpił błąd podczas dodawania wybranych obiektów na warstwie. Spróbuj ponownie.",
  "addingFeatureErrorCount": "Nie powiodło się skopiowanie obiektu lub obiektów: '${copyFeatureErrorCount}'. Czy chcesz spróbować ponownie dla brakującego obiektu lub brakujących obiektów?",
  "selectingFeatureError": "Wystąpił błąd podczas wybierania obiektów na warstwie. Spróbuj ponownie.",
  "customSelectOptionLabel": "Wybierz obiekty do skopiowania",
  "copyFeaturesWithPolygon": "Kopiuj poligonem",
  "copyFeaturesWithRect": "Kopiuj prostokątem",
  "copyFeaturesWithLasso": "Kopiuj lassem",
  "noFeatureSelectedMessage": "Nie wybrano obiektów",
  "multipleFeatureSaveMessage": "Wszystkie obiekty zostaną zapisane niezwłocznie. Czy chcesz kontynuować?",
  "relativeDates": {
    "dateTypeLabel": "Rodzaj dat",
    "valueLabel": "Wartość",
    "fixed": "Stała",
    "current": "Bieżący",
    "past": "Przeszły",
    "future": "Przyszły",
    "popupTitle": "Wybierz wartość",
    "hintForFixedDateType": "Wskazówka: podana data i czas zostaną użyte jako wstępnie ustawiona wartość domyślna.",
    "hintForCurrentDateType": "Wskazówka: bieżąca data i czas zostaną użyte jako wstępnie ustawiona wartość domyślna.",
    "hintForPastDateType": "Wskazówka: podana wartość zostanie odjęta od bieżącej daty i czasu dla wartości domyślnej ustawienia wstępnego.",
    "hintForFutureDateType": "Wskazówka: podana wartość zostanie dodana do bieżącej daty i czasu dla wartości domyślnej ustawienia wstępnego.",
    "noDateDefinedTooltip": "Nie zdefiniowano daty",
    "relativeDateWarning": "Należy podać wartość daty lub czasu, aby można było zapisać domyślną wartość skonfigurowaną wstępnie.",
    "customLabel": "Niestandardowy",
    "layerLabel": "Warstwa",
    "domainFieldHintLabel": "Wybrana wartość jest domeną wartości kodowych. Zostanie użyta wartość \"${domainValue}\""
  },
  "valuePicker": {
    "popupTitle": "Wybierz wartość",
    "popupHint": "Bieżący obiekt przecina się z wieloma obiektami; wybierz wartość dla odpowiedniego pola",
    "buttonTooltip": "Wybierz wartość z wielu przecinających się obiektów"
  },
  "uniqueValueErrorMessage": "Wartość w polu „${fieldName}” już istnieje. Podaj nową wartość.",
  "requiredFields": {
    "displayMsg": "Pola wymagane nie mogą być puste. Podaj wartości wspólnych pól poniżej.",
    "popupTittle": "Wymagane pola",
    "foundNullRecordCount": "${fieldName} (znaleziono w następującej liczbie rekordów: ${count})"
  },
  "fieldsMapping": {
    "popupTittle": "Zastosuj dopasowywanie pól",
    "fieldsMatchingCheckboxLabel": "Wartości ze skopiowanych obiektów zastępują wartości domyślne w polach docelowych",
    "resetLabel": "Resetuj",
    "clearLabel": "Wyczyść",
    "fieldsInTargetLayerLabel": "Cel",
    "fieldsInSourceLayerLabel": "Źródło",
    "targetFieldsMatchedLabel": "${layerName} (dopasowane pola: ${matchedFields}/${totalFields})",
    "selectSourceFieldLabel": "— Wybierz —",
    "selectFieldAriaLabel": "Wybierz pole źródłowe dla pola docelowego ${targetField}",
    "informativeText": "Przejrzyj dopasowywanie pól z elementu źródłowego na docelowy i dostosuj je, jeśli to konieczne.",
    "dynamicValueText": "Ustawiono wartość dynamiczną",
    "noFieldsToMatchLabel": "Brak pól do dopasowania"
  },
  "cantLocateUserLocation": "Nie można ustalić Twojej lokalizacji",
  "tryAgainButtonLabel": "Spróbuj ponownie",
  "copyFeatureFailedPopupTitle": "Ojej!"
});