define({
  "symbolologyTabLabel": "Конфигуриране на симвология",
  "facilitiesDescription": "Слоеве със съоръжения",
  "demographicsDescription": "Слой с демографски данни",
  "settingsTitle": "Настройки",
  "spillLocationLabel": "Местоположение на разлив",
  "spillLocationButtonLabel": "Конфигуриране на настройките на места на разлив",
  "IISettingsLabel": "Първоначална зона на изолация",
  "IIButtonLabel": "Конфигуриране на настройките на първоначалната зона на изолация",
  "PASettingsLabel": "Защитна зона на действие",
  "PAButtonLabel": "Конфигуриране на настройките за защитно действие",
  "downwindSettingsLabel": "Зона на въздушен поток",
  "downwindButtonLabel": "Конфигуриране на настройките за въздушен поток",
  "fireSettingsLabel": "Зона на локализация на пожар",
  "fireButtonLabel": "Конфигуриране на настройките за локализация на пожар",
  "bleveSettingsLabel": "Зона на изолация на BLEVE (експлозия поради разширяване на парите на вряща течност)",
  "bleveButtonLabel": "Конфигуриране на настройките на BLEVE (експлозия поради разширяване на парите на вряща течност) зона",
  "transparency": "Прозрачност",
  "outline": "Контур",
  "fill": "Попълване (Цветът се прилага само когато стилът е зададен като плътен)",
  "style": "Стил",
  "selectOpLayerLabel": "Избиране на оперативен слой за резултати",
  "selectDefaultMeasurementLabel": "Избиране на мерна единица по подразбиране",
  "helpIconTooltip": "Списъкът на оперативния слой е попълнен със слоеве от текущата уеб карта, които са тип полигонна геометрия.",
  "colorPicker": "Избор на цвят",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире Точка",
    "esriSLSDashDotDot": "Тире Точка Точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Дълго тире",
    "esriSLSLongDashDot": "Дълго тире Точка",
    "esriSLSNull": "Нула",
    "esriSLSShortDash": "Малко тире",
    "esriSLSShortDashDot": "Малко тире Точка",
    "esriSLSShortDashDotDot": "Малко тире Точка Точка",
    "esriSLSShortDot": "Малка точка",
    "esriSLSSolid": "Плътни"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Пресичане",
    "esriSFSDiagonalCross": "Диагонал",
    "esriSFSForwardDiagonal": "Напред",
    "esriSFSHorizontal": "Хоризонтално",
    "esriSFSNull": "Нула",
    "esriSFSSolid": "Плътни",
    "esriSFSVertical": "Вертикално"
  }
});