define({
  "settings": "Настройки",
  "titleSettings": "Настройки на текст",
  "imageSettings": "Настройки на изображение",
  "backgroundColor": "Цвят на фона",
  "alignment": "Подравняване",
  "textSize": "Размер на текст",
  "textColor": "Цвят на текст",
  "dataSource": "Източник на данни",
  "chartSettings": "Настройки на диаграма",
  "data": "Данни",
  "dataLabels": "Надписи на данни",
  "displayMode": "Режим на показване",
  "featureOption": "Показване на стойностите обект по обект",
  "categoryOption": "Показване на стойности по категория",
  "countOption": "Показване на броя на обектите по категории",
  "fieldOption": "Показване на стойностите на атрибутите като диаграми",
  "categoryField": "Поле за категория",
  "labelField": "Поле за надпис",
  "valueFields": "Полета за стойност",
  "operation": "Операция",
  "sumOption": "Сума",
  "averageOption": "Средни",
  "minOption": "Минимални",
  "maxOption": "Максимални",
  "countString": "Брой",
  "dataFormat": "Формат на данни",
  "decimalPlaces": "Десетични места",
  "prefix": "Префикс",
  "suffix": "Суфикс",
  "dataType": "Тип данни",
  "featureCount": "Брой на обекти",
  "fieldStatistics": "Статистика на поле",
  "display": "Показване",
  "chartColor": "Цвят на диаграма",
  "horizontalAxis": "Хоризонтална ос",
  "verticalAxis": "Вертикална ос",
  "legend": "Легенда",
  "position": "Позиция",
  "top": "Горен",
  "bottom": "Най-долу",
  "useDataSourceSelection": "Използване на избор",
  "dataSourceFilterByExtent": "Филтриране по ограничаващ правоъгълник",
  "changeTemplate": "Смяна на шаблон",
  "chooseTemplate": "Избор на шаблон",
  "numberSettings": "Настройки на числа",
  "gaugeSettings": "Настройки на измервателните уреди",
  "indicators": "Индикатори",
  "ifValue": "Ако стойността",
  "and": "и",
  "numberOperatorIsLessThan": "е по-малко от",
  "numberOperatorIsGreaterThan": "е по-голямо от",
  "numberOperatorIsBetween": "е между",
  "numberOperatorIsEqual": "е равна на",
  "numberOperatorIsNotEqual": "не е равна на",
  "then": "Тогава",
  "ratio": "Съотношение",
  "trueValue": "Вярна стойност",
  "changeValueColor": "промяна на цвета на стойността на",
  "changeGaugeColor": "промяна цвета на измервателния уред на",
  "setIndicatorIcon": "задаване на иконата на индикатора като",
  "icons": "Икони",
  "style": "Стил",
  "placement": "Поставяне",
  "left": "Ляво",
  "replace": "Смяна",
  "right": "Дясно",
  "color": "Цвят",
  "categoryExists": "Категорията съществува!",
  "comboxHint": "Изпишете или изберете една",
  "comboxDisableInputHint": "Изберете един",
  "comboxDisableSelectHint": "Изпишете една",
  "comboxDisableInputEmptySelectHint": "Няма повече категории",
  "sortBy": "Сортиране по",
  "labelAxis": "Надпис",
  "valueAxis": "Стойност",
  "minPeriod": "Минимален период",
  "automatic": "Автоматично",
  "periodsWithOutRecords": "Периоди без записи",
  "nullValue": "Нулева стойност",
  "calculatedAsZero": "Изчислено като нула",
  "ignored": "Пренебрегнати",
  "maxCategories": "Максимален брой категории",
  "useLayerSymbology": "Използване на симвология на слой",
  "hollowsize": "Размер на кухина",
  "splitField": "Разделяне на повърхност",
  "parsingperiodTip": "Неуспешно изчисление. Твърде много времеви интервали поради краткия период на анализиране.",
  "manyCategoryTip": "Диаграмата не може да се покаже. Твърде много категории.",
  "setColor": "Задаване на цвят",
  "setTheColorOf": "След това задайте цвят на",
  "setTheColorAs": "След това задайте цвета като",
  "ifStr": "Ако",
  "as": "като",
  "is": "е",
  "isNot": "не е",
  "barCluster": "щрих на клъстер",
  "individualBar": "индивидуален щрих",
  "allOthers": "Всички останали",
  "category": "Категория",
  "indicatorSum": "СУМА",
  "indicatorAve": "СРЕДНА",
  "indicatorMax": "МАКС.",
  "indicatorMin": "МИН.",
  "setCorrectyIndicatorTip": "Моля, изберете правилни индикатори.",
  "dataRange": "Диапазон на данни",
  "targetValue": "Целева стойност",
  "currentValue": "Текуща стойност",
  "gaugeColor": "Цвят на измервателния уред",
  "min": "Минимални",
  "max": "Максимални",
  "displayValueIn": "Показване на стойност в",
  "noData": "Няма данни",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Предупреждение",
  "noSettingWaring1": "Натиснете върху елемент, за да зададете неговите стойности.",
  "noSettingWaring2": "Плъзнете, за да промените размера или реда на елемент.",
  "donNotShowAgain": "Не показвайте това отново",
  "changeTemplateWarning": "Това ще изтрие всички Ваши настройки и ще отвори нов празен шаблон.",
  "requiredFieldWarning": "Стойността е задължителна.",
  "dataSourceNotSet": "Моля, изберете източник на данни.",
  "addIndicatorTip": "Добавяне на индикатор",
  "chooseTemplatePopupTitle": "Избор на шаблон",
  "filterExtentTipWithaTag": "Можете да деактивирате филтрирането по <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>източник на допълнителни данни</a> в раздела за атрибути.",
  "filterExtentTip": "Можете да деактивирате филтрирането по източник на допълнителни данни в раздела за атрибути.",
  "customColorByCategory": "Потребителски цвят по категория",
  "randomColor": "Произволен цвят",
  "valueString": "Стойност",
  "fieldString": "Поле",
  "includeThresholdValue": "Включване на прагова стойност",
  "percentage": "Процент",
  "colorSchema": "Цветова схема",
  "addCategory": "Добавяне на категория",
  "clickToEdit": "Натиснете, за да редактирате",
  "nullText": "Нула",
  "others": "Други",
  "dsErrorTipSuf": "не е налично.",
  "front": "Отпред",
  "back": "Назад",
  "title": "Заглавие",
  "titleColor": "Цвят на заглавие",
  "labelString": "Етикет",
  "labelSize": "Размер на надпис",
  "labelColor": "Цвят на надпис",
  "addMarkLine": "Добавяне на маркировка за линия",
  "addMarkArea": "Добавяне на маркировка за област",
  "labelPosition": "Позиция на надпис",
  "toString": "до",
  "start": "Начало",
  "middle": "Среден",
  "end": "Край",
  "inString": "В/във",
  "outString": "Извън",
  "lineColor": "Цвят на линия",
  "lineWidth": "Ширина на линия",
  "dashType": "Тип тире",
  "areaColor": "Цвят на област",
  "line": "Линия",
  "area": "Област",
  "stringsInTemplate": {
    "name_number": "число",
    "name_gauge": "Датчик",
    "name_vertical_gauge": "Вертикален измервателен уред",
    "name_horizontal_gauge": "Хоризонтален измервателен уред",
    "name_pie": "Кръгла форма",
    "name_donut": "Кръг",
    "name_bar": "Щрих",
    "name_stacked_bar": "Подредена лента",
    "name_percentage_stacked_bar": "Процент на подредена лента",
    "name_column": "Колона",
    "name_stacked_column": "Подредена колона",
    "name_percentage_stacked_column": "Процент на подредена колона",
    "name_line": "Линия",
    "name_area": "Област",
    "name_stacked_area": "Подредена област",
    "name_percentage_stacked_area": "Процент на подредена област",
    "titleOfTheInfographic": "ЗАГЛАВИЕ НА ИНФОГРАФИКА",
    "description": "Описание: допълнителна информация за тази инфографика."
  },
  "marks": "Знаци",
  "displayValue": "Показване на стойност",
  "statistic": "Статистика",
  "valueType": "Тип стойност",
  "valueField": "Поле за стойност",
  "fixed": "Фиксирани",
  "sdsTip": "Избор на статистически данни, конфигурирани в източник на допълнителни данни",
  "noSdsTip": "Няма налични статистически данни.",
  "intScaleText": "Показване само на мащаб с цели числа",
  "resetLayout": "Възстановяване на оформление",
  "fbeTip": "Имайте предвид, че приложението Ви се споделя публично и е широко разпространено. Активирането на тази опция ще забави драстично работата на приложението. Вместо това, ние препоръчваме да използвате други изпълними модули, като например „Филтър“ и „Групов филтър“ за мащабиране на обектите.",
  "openFbeTip": "Включване на опцията въпреки това",
  "use1000Separator": "Използване на разделител за хилядни",
  "noDataReturned": "Няма върнати данни",
  "tooltipMode": "Режим ToolTip",
  "single": "Първи",
  "multiple": "Многобройни",
  "defaultRange": "Диапазон на стандартно показване"
});