define({
  "businessAnalyst": "Business Analyst",
  "defaultFirstPageText": "<br><div>存取資訊圖表和報告，其摘要了任何區域的關鍵指標和資料。</div><br><div>在地圖上選擇點或多邊形、搜尋地址或地點、繪製多邊形，或在地圖上放置大頭針以檢視區域的關鍵指標和相關資訊。</div>",
  "defineWhichInfographics": "定義 widget 中的可用資訊圖表:",
  "defineWhichReports": "定義 widget 中的可用報告:",
  "defaultValues": "預設值:",
  "disable": "停用",
  "drawFreehandPolygon": "繪製手繪多邊形",
  "drawPolygon": "繪製面",
  "driveTime": "行駛時間",
  "dropPin": "放下大頭針",
  "dynamicHTML": "動態 HTML",
  "exportOptions": "匯出選項:",
  "home": "首頁",
  "image": "圖像",
  "infographics": "資訊圖表",
  "invalidValueRing": "值必須位於範圍 0 到 1,000。",
  "invalidValueDTWT": "值必須位於範圍 0 到 300。",
  "km": "km",
  "makeDefault": "設為預設",
  "miles": "英哩",
  "minutes": "分鐘",
  "options": "Options:",
  "pdf": "PDF",
  "print": "列印",
  "radius": "半徑",
  "removeDefault": "移除預設值",
  "reports": "報告",
  "rings": "圓環",
  "searchTextBox": "搜尋文字方塊",
  "selectCountryOrRegion": "選擇國家或地區:",
  "thisEntryIsNotValid": "此項目無效。",
  "time": "時間",
  "walkTime": "步行時間"
});