define({
  "_widgetLabel": "Analýza ohrozenia",
  "threatAnalysisMainPageTitle": "Založené na Protiteroristickej príručke JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Vstupné umiestnenie",
  "interactive": "Interaktívne",
  "fromCoord": "Fixné súradnice",
  "existingFeature": "Z existujúcich prvkov",
  "threatAnalysisCoordInputLabel": "Umiestnenie ohrozenia",
  "enterCoords": "Zadať súradnice",
  "threatAddPointToolTip": "Pridať umiestnenie ohrozenia",
  "threatDrawPointToolTip": "Kliknite pre pridanie umiestnenia ohrozenia",
  "threatType": "Typ ohrozenia",
  "threatPlaceholder": "Pre vyhľadanie ohrozenia začnite písať",
  "zoneTypeLabel": "Typ zóny",
  "feetLabel": "Stopy",
  "metersLabel": "Metre",
  "unitsLabel": "Jednotky",
  "threatGraphicLayer": "Grafika ohrozenia",
  "style": "Štýl",
  "settingsTitle": "Nastavenia",
  "colorPicker": "výber farby",
  "lineStyles": {
    "esriSLSDash": "Pomlčka",
    "esriSLSDashDot": "Pomlčka bodka",
    "esriSLSDashDotDot": "Pomlčka bodka bodka",
    "esriSLSDot": "Bodka",
    "esriSLSLongDash": "Dlhá pomlčka",
    "esriSLSLongDashDot": "Dlhá pomlčka bodka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Krátka pomlčka",
    "esriSLSShortDashDot": "Krátka pomlčka bodka",
    "esriSLSShortDashDotDot": "Krátka pomlčka bodka bodka",
    "esriSLSShortDot": "Krátka bodka",
    "esriSLSSolid": "Plné"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Späť",
    "esriSFSCross": "Priečne",
    "esriSFSDiagonalCross": "Uhlopriečne",
    "esriSFSForwardDiagonal": "Vpred",
    "esriSFSHorizontal": "Vodorovný",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Plné",
    "esriSFSVertical": "Zvislý"
  },
  "resultsTitle": "Výsledky",
  "publishTABtn": "Publikovať",
  "layerName": "Názov publikovanej vrstvy",
  "invalidLayerName": "Názov vrstvy musí obsahovať iba alfanumerické znaky a podčiarkovníky",
  "missingLayerNameMessage": "Pred publikovaním musíte zadať platný názov vrstvy",
  "publishingFailedLayerExists": "Publikovanie zlyhalo: Už máte službu pre prvky s názvom {0}. Vyberte iný názov vrstvy.",
  "checkService": "Skontrolovať službu: {0}",
  "createService": "Vytvoriť službu: {0}",
  "unableToCreate": "Nebolo možné vytvoriť: {0}",
  "addToDefinition": "Pridať do definície: {0}",
  "successfullyPublished": "Úspešne publikovaná webová vrstva",
  "successfullyAppended": "Úspešne pridané nové prvky do webovej vrstvy",
  "manageWebLayerText": "Spravovať webovú vrstvu",
  "userRole": "Nebolo možné vytvoriť službu, pretože používateľ nemá povolenia",
  "retrieveExistingLayerError": "Nie je možné získať {0}. Prosím vypublikujte používajúc iné meno vrstvy",
  "publishToNewLayer": "Publikovať výsledky do novej vrstvy prvkov",
  "layerNameExists": "Názov vrstvy už existuje. Použite iný názov vrstvy.",
  "pipeBombLabel": "Potrubná bomba",
  "suicideBombLabel": "Samovražedná bomba",
  "briefcaseLabel": "Kufrík",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/Dodávka",
  "smallDeliveryTruckLabel": "Malé nákladné auto",
  "containerWaterTruckLabel": "Kontajner/Cisterna",
  "semiTrailerLabel": "Polo-karavan",
  "transparencyLabel": "Priehľadnosť",
  "outline": "Obrys",
  "fill": "Výplň (Farba sa použije iba v prípade, že je štýl nastavený na plný)",
  "createBtn": "Vytvoriť zóny",
  "clearBtn": "Vyčistiť",
  "invalidNumberMessage": "Zadaná hodnota nie je platná",
  "invalidRangeMessage": "Hodnota musí byť väčšia ako 0",
  "parseCoordinatesError": "Nie je možné interpretovať súradnice. Skontrolujte svoj vstup.",
  "selectDrawModeLabel": "Zvoliť mód kreslenia",
  "selectFeatureLabel": "Vybrať prvok z tejto vrstvy",
  "smallLPGTank": "Malá nádrž LPG",
  "largeLPGTank": "Veľká nádrž LPG",
  "commercialResidentialLPGTank": "Priemyselná/rezidenčná nádrž LPG",
  "smallLPGTruck": "Malé nákladné auto na LPG",
  "semiTankerLPG": "Polo-nádrž LPG",
  "zoneDescriptionColLabel": "Popis zóny",
  "distanceColLabel": "Vzdialenosť",
  "zoneDescColLabel": "Popis zóny",
  "descriptionLabel": "Popis",
  "editThreatZonePopupLabel": "Editovať symboliku zóny ohrozenia",
  "symbologyColLabel": "Symbolika",
  "actions": "Akcie",
  "threatTypeSelectLabel": "Vybrať typ ohrozenia:",
  "distanceLabel": "Vzdialenosť (${unitAbbr})",
  "layerCountHint": "Nápoveda: Webová vrstva s ${layerCount} prvkovou vrstvou(ami) bude publikovaná.",
  "selectLabel": "Vybrať",
  "mandatoryLabel": "Povinná evakuačná vzdialenosť",
  "safeLabel": "Bezpečná evakuačná vzdialenosť",
  "fireBallDiameterLable": "Priemer explózie",
  "lpgSafeDistanceLable": "Bezpečná vzdialenosť"
});