define({
  "_widgetLabel": "ניתוח איומים",
  "threatAnalysisMainPageTitle": "מבוסס על המדריך למאבק בטרור של JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "הזן מיקום",
  "interactive": "אינטראקטיבי",
  "fromCoord": "קואורדינטה קבועה",
  "existingFeature": "מתוך ישויות קיימות",
  "threatAnalysisCoordInputLabel": "מיקום האיום",
  "enterCoords": "הקלד קואורדינטות",
  "threatAddPointToolTip": "הוסף מיקום של איום",
  "threatDrawPointToolTip": "לחץ להוספת מיקום של איום",
  "threatType": "סוג איום",
  "threatPlaceholder": "התחל להקליד לחיפוש איום",
  "zoneTypeLabel": "סוג אזור",
  "feetLabel": "רגליים",
  "metersLabel": "מטרים",
  "unitsLabel": "יחידות",
  "threatGraphicLayer": "גרפיקה של איומים",
  "style": "סגנון",
  "settingsTitle": "הגדרות",
  "colorPicker": "בוחר הצבעים",
  "lineStyles": {
    "esriSLSDash": "מקווקו",
    "esriSLSDashDot": "קו נקודה",
    "esriSLSDashDotDot": "קו נקודה נקודה",
    "esriSLSDot": "נקודה",
    "esriSLSLongDash": "קו ארוך",
    "esriSLSLongDashDot": "קו נקודה ארוך",
    "esriSLSNull": "ריק",
    "esriSLSShortDash": "קו קצר",
    "esriSLSShortDashDot": "קו נקודה קצר",
    "esriSLSShortDashDotDot": "קו נקודה נקודה קצר",
    "esriSLSShortDot": "נקודה קצרה",
    "esriSLSSolid": "מלא"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "לאחור",
    "esriSFSCross": "צלב",
    "esriSFSDiagonalCross": "אלכסוני",
    "esriSFSForwardDiagonal": "לפנים",
    "esriSFSHorizontal": "אופקי",
    "esriSFSNull": "ריק",
    "esriSFSSolid": "מלא",
    "esriSFSVertical": "אנכי"
  },
  "resultsTitle": "תוצאות",
  "publishTABtn": "פרסם",
  "layerName": "שם השכבה פורסם",
  "invalidLayerName": "שם השכבה חייב להכיל תווי אותיות ומספרים וקווים תחתונים בלבד",
  "missingLayerNameMessage": "עליך להזין שם חוקי של שכבה לפני שתוכל לפרסם",
  "publishingFailedLayerExists": "הפרסום נכשל: כבר יש לך שירות ישויות בשם {0}. בחר שם שכבה אחר.",
  "checkService": "בדוק שירות: {0}",
  "createService": "צור שירות: {0}",
  "unableToCreate": "לא ניתן ליצור: {0}",
  "addToDefinition": "הוסף להגדרה: {0}",
  "successfullyPublished": "פרסום שכבת הווב בוצע בהצלחה",
  "successfullyAppended": "הוספת ישויות חדשות לשכבת ווב בוצעה בהצלחה",
  "manageWebLayerText": "ניהול שכבת ווב",
  "userRole": "לא ניתן ליצור את השירות משום למשתמש אין הרשאות",
  "retrieveExistingLayerError": "לא ניתן לאסוף לאחזר את {0}. פרסם עם שם שכבה אחר",
  "publishToNewLayer": "פרסם את התוצאות לשכבת ישויות חדשה",
  "layerNameExists": "שם השכבה כבר קיים. השתמש בשם שכבה אחר.",
  "pipeBombLabel": "פצצת צינור",
  "suicideBombLabel": "פצצה של מתאבדים",
  "briefcaseLabel": "מזוודה",
  "carLabel": "מכונית",
  "suvVanLabel": "רכב קרוסאובר/ואן",
  "smallDeliveryTruckLabel": "משאית קטנה",
  "containerWaterTruckLabel": "משאית מכולה/להובלת מים",
  "semiTrailerLabel": "סמיטריילר",
  "transparencyLabel": "שקיפות",
  "outline": "קו מתאר",
  "fill": "מילוי (הצבע חל רק כשהסגנון הוא 'מלא')",
  "createBtn": "צור אזורים",
  "clearBtn": "נקה",
  "invalidNumberMessage": "הערך שהוזן אינו חוקי",
  "invalidRangeMessage": "הערך חייב להיות גדול מאפס",
  "parseCoordinatesError": "לא ניתן לנתח את הקואורדינטות. בדוק את הקלט שלך.",
  "selectDrawModeLabel": "בחר מצב שרטוט",
  "selectFeatureLabel": "בחר ישות מהשכבה",
  "smallLPGTank": "מכל LPG קטן",
  "largeLPGTank": "מכל LPG גדול",
  "commercialResidentialLPGTank": "מכל LPG לאזורי מסחר/מגורים",
  "smallLPGTruck": "משאית LPG קטנה",
  "semiTankerLPG": "מכלית LPG",
  "zoneDescriptionColLabel": "תיאור אזור",
  "distanceColLabel": "מרחק",
  "zoneDescColLabel": "תיאור אזור",
  "descriptionLabel": "תאור",
  "editThreatZonePopupLabel": "ערוך סימבולוגיית אזור איום",
  "symbologyColLabel": "סימבולוגיה",
  "actions": "פעולות",
  "threatTypeSelectLabel": "בחר סוג איום",
  "distanceLabel": "מרחק (${unitAbbr})",
  "layerCountHint": "עצה: שכבת אינטרנט עם ${layerCount} שכבות ישויות תתפרסם.",
  "selectLabel": "בחר",
  "mandatoryLabel": "מרחק פינוי חובה",
  "safeLabel": "מרחק פינוי בטוח",
  "fireBallDiameterLable": "קוטר כדור אש",
  "lpgSafeDistanceLable": "מרחק בטוח"
});