define({
  "transparencyLabel": "Độ trong suốt",
  "outline": "Viền",
  "fill": "Tô đầy (Màu chỉ áp dụng khi kiểu được thiết lập thành dạng khối)",
  "style": "Kiểu",
  "selectOpLayerLabel": "Chọn một lớp chuyên đề cho kết quả",
  "selectDefaultMeasurementLabel": "Chọn đơn vị mặc định của kết quả đo",
  "helpIconTooltip": "Danh sách lớp chuyên đề được quản lý với các lớp từ bản đồ web hiện tại là loại hình học dạng vùng.",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  },
  "threatTypeLabel": "Loại Mối đe dọa",
  "generalLabel": "Chung",
  "addThreatTypesLabel": "Thêm loại mối đe dọa",
  "actions": "Các hành động",
  "newThreatTypePopupLabel": "Loại mối đe dọa mới",
  "units": "Đơn vị",
  "chooseDefaultThreatLabel": "Chọn loại mối đe dọa mặc định",
  "defaultThreatTypePopUpLabel": "Loại Mối đe dọa Mặc định",
  "editThreatLabel": "Chỉnh sửa Mối đe dọa",
  "defaultThreatTypeIconTooltip": "Danh sách Loại Mối đe dọa Mặc định",
  "uniqueThreatTypeMsg": "Hãy nhập loại mối đe dọa duy nhất, đã tồn tại loại mối đe dọa có tên này.",
  "requiredMsg": "Trường này là bắt buộc",
  "unitMeasureLabel": "Khoảng cách tính bằng {0}",
  "chooseDefaultThreatTypeIconLabel": "Chọn từ mục mặc định",
  "pipeBombLabel": "Bom ống",
  "suicideBombLabel": "Bom tự sát",
  "briefcaseLabel": "Cặp tài liệu",
  "carLabel": "Xe ô tô",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Xe tải giao hàng nhỏ",
  "containerWaterTruckLabel": "Container/Xe tưới nước",
  "semiTrailerLabel": "Xe bán tải",
  "chemicalThreatLegendLabel": "Mối đe dọa từ Hóa chất",
  "lpgThreatLegendLabel": "Mối đe dọa LPG",
  "smallLPGTank": "Bồn LPG nhỏ",
  "largeLPGTank": "Bồn LPG lớn",
  "commercialResidentialLPGTank": "Bồn LPG thương mại/sinh hoạt",
  "smallLPGTruck": "Xe tải LPG nhỏ",
  "semiTankerLPG": "Xe bán tải LPG",
  "threatDescriptionColLabel": "Mô tả Mối đe dọa",
  "addThreatZoneButtonLabel": "Thêm vùng mối đe dọa",
  "zoneDescColLabel": "Thông tin mô tả vùng",
  "distanceLabel": "Khoảng cách (${unitAbbr})",
  "threatTypeHelp": "<p>Đảm bảo đáp ứng các điều kiện sau cho từng loại mối đe dọa:<br/><ul><li>Loại mối đe dọa không được trống và phải là duy nhất</li><li>Mối đe dọa cần có ít nhất một vùng hợp lệ</li><li>Mô tả vùng phải là duy nhất đối với một mối đe dọa</li></ul><p/>",
  "descriptionLabel": "Thông tin mô tả",
  "newThreatZonePopupLabel": "Vùng mối đe dọa mới",
  "editThreatZonePopupLabel": "Chỉnh sửa vùng mối đe dọa",
  "uniqueZoneDescriptionMsg": "Nhập thông tin mô tả vùng duy nhất, thông tin mô tả vùng có tên này đã tồn tại.",
  "symbologyColLabel": "Diễn đạt bằng ký hiệu",
  "zoneDescriptionColLabel": "Mô tả vùng",
  "uniqueZoneRequiredMsg": "Tên vùng phải là duy nhất đối với",
  "interactive": "Tương tác",
  "fromCoord": "Tọa độ cố định",
  "existingFeature": "Từ các đối tượng hiện tại",
  "defaultInputLocationLabel": "Thông tin vị trí đầu vào mặc định",
  "defaultInputLayer": "Lớp đầu vào mặc định",
  "defaultThreatType": "Loại mối đe dọa mặc định",
  "selectLabel": "Chọn",
  "mandatoryLabel": "Khoảng cách Sơ tán Bắt buộc",
  "safeLabel": "Khoảng cách Sơ tán An toàn",
  "lpgSafeDistanceLable": "Khoảng cách An toàn",
  "fireBallDiameterLable": "Đường kính Cầu lửa"
});