define({
  "transparencyLabel": "Transparência",
  "outline": "Contorno",
  "fill": "Preencher (a cor somente se aplica quando o estilo é definido para sólido)",
  "style": "Estilo",
  "selectOpLayerLabel": "Selecione uma camada operacional para resultados",
  "selectDefaultMeasurementLabel": "Selecione uma unidade de medição padrão.",
  "helpIconTooltip": "A lista de camada operacional é preenchida com camadas a partir do mapa da web atual que são do tipo de geometria de polígono.",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Ponto Traço Curto",
    "esriSLSShortDashDotDot": "Ponto Ponto Traço Curto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Para Trás",
    "esriSFSCross": "Transversal",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para Frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "threatTypeLabel": "Tipo de Camada",
  "generalLabel": "Geral",
  "addThreatTypesLabel": "Adicionar tipo de camada",
  "actions": "Ações",
  "newThreatTypePopupLabel": "Novo tipo de camada",
  "units": "Unidades",
  "chooseDefaultThreatLabel": "Selecionar tipo de camada padrão",
  "defaultThreatTypePopUpLabel": "Tipos de Camada Padrão",
  "editThreatLabel": "Editar Camada",
  "defaultThreatTypeIconTooltip": "Lista do Tipo de Camada Padrão",
  "uniqueThreatTypeMsg": "Insira o tipo de camada único, o tipo de camada com este nome já existe.",
  "requiredMsg": "Este campo é obrigatório",
  "unitMeasureLabel": "As distâncias estão em {0}",
  "chooseDefaultThreatTypeIconLabel": "Escolher do padrão",
  "pipeBombLabel": "Bomba Caseira",
  "suicideBombLabel": "Ataque Suicida",
  "briefcaseLabel": "Porta-arquivos",
  "carLabel": "Carro",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Caminhão de entrega pequeno",
  "containerWaterTruckLabel": "Contêiner/Caminhão Pipa",
  "semiTrailerLabel": "Semi-Trailer",
  "chemicalThreatLegendLabel": "Ameaça Química",
  "lpgThreatLegendLabel": "Ameaça de LPG",
  "smallLPGTank": "Tanque LPG Pequeno",
  "largeLPGTank": "Tanque LPG Grande",
  "commercialResidentialLPGTank": "Tanque LPG Comercial/Residencial",
  "smallLPGTruck": "Caminhão LPG Pequeno",
  "semiTankerLPG": "Semi-petroleiro LPG",
  "threatDescriptionColLabel": "Este campo é exigido",
  "addThreatZoneButtonLabel": "Adicionar zona de ameaça",
  "zoneDescColLabel": "Descrição da zona",
  "distanceLabel": "Distância (${unitAbbr})",
  "threatTypeHelp": "<p>Certifique-se que as seguintes condições sejam atendidas para um tipo de camada:<br/><ul><li>O tipo de camada não pode ficar em branco e deve ser único</li><li>A camada deve ter pelo menos uma zona válida</li><li>A descrição da zona deve ser única para uma camada</li></ul><p/>",
  "descriptionLabel": "Descrição",
  "newThreatZonePopupLabel": "Nova zona de ameaça",
  "editThreatZonePopupLabel": "Editar zona de ameaça",
  "uniqueZoneDescriptionMsg": "Insira a descrição de zona única, a descrição da zona com este nome já existe.",
  "symbologyColLabel": "Simbologia",
  "zoneDescriptionColLabel": "Descrição da zona",
  "uniqueZoneRequiredMsg": "o nome da zona deve ser único para",
  "interactive": "Interativo",
  "fromCoord": "Coordenada Fixa",
  "existingFeature": "Das Feições Existentes",
  "defaultInputLocationLabel": "Local de entrada padrão",
  "defaultInputLayer": "Camada de entrada padrão",
  "defaultThreatType": "Tipo de camada padrão",
  "selectLabel": "Selecionar",
  "mandatoryLabel": "Distância Obrigatória de Evacuação",
  "safeLabel": "Distância de Evacuação Segura",
  "lpgSafeDistanceLable": "Distância Segura",
  "fireBallDiameterLable": "Diâmetro da Bola de Fogo"
});