define({
  "locatorUrl": "URL do Localizador",
  "set": "Configurar",
  "locatorName": "Nome do Localizador",
  "locatorExample": "Exemplo",
  "countryCode": "Códigos de Região e País",
  "eg": "por exemplo ",
  "countryCodeHint": "Deixar este valor em branco pesquisará todos os países e regiões",
  "minCandidateScore": "Pontuação Mínima do Candidato",
  "minCandidateScoreHint": "Deixar este valor em branco utilizará uma pontuação de candidato mínimo de 90",
  "enableSingleField": "Opções de campo único",
  "singleFieldHint": "Os dados de endereço estarão em um único campo",
  "enableMultiField": "Opções de múltiplos campos",
  "multiFieldHint": "Os dados de endereço estarão em múltiplos campos",
  "enableXYField": "Opções de Campo X/Y",
  "xyFieldHint": "Os dados irão conter valores de coordenadas X/Y",
  "instructionGeocode": "Adicione e configure serviços do localizador.",
  "invalidUrlTip": "A URL ${URL} é inválida ou inacessível.",
  "geocodeTabLabel": "Configurações de Local",
  "lookupList": "Nomes dos Campos para Reconhecer",
  "isRecognized": "Os nomes de campo na tabela abaixo são automaticamente reconhecidos para este campo",
  "needsEditablePointLayers": "O mapa da web deve conter pelo menos uma camada de ponto editável.",
  "editpageAlias": "Nome Alternativo",
  "configureFields": "Configurar Campos da Camada",
  "configureSingleFields": "Configurar Campos de Único Endereço",
  "configureMultiFields": "Configurar Campos de Múltiplos Endereços",
  "configureXYFields": "Configurar Campos X/Y",
  "noFields": "Utilize a ação de editar para definir um ou mais campos para exibir",
  "display": "Exibir",
  "duplicate": "Localizar Duplicata",
  "duplicateTip": "Pesquise neste campo por valores idênticos entre o arquivo de origem e a camada de destino./n Quando uma correspondência idêntica for encontrada, o registro do arquivo não será localizado e será sinalizado como duplicado.",
  "noSelectField": "Selecione a opção da Camada de Feição primeiro",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Longitude)",
  "xyFieldsLabelY": "Y (Latitude)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Para Leste",
  "northing": "Para Norte",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Escolha a camada na qual enviar os dados.",
  "layerFieldTitle": "Camada de Destino",
  "tempSymbolHint": "Escolha o símbolo que será utilizado para exibir as feições.",
  "tempSymbolTitle": "Símbolo de Exibição",
  "maxRecords": "Máximo de registros",
  "maxRecordsHint": "Número máximo de registros para localizar",
  "searchRadius": "Raio de Pesquisa",
  "searchRadiusHint": "Distância para procurar por feições duplicadas a partir da camada",
  "requiresInteger": "Insira um valor numérico.",
  "requiresInteger0100": "Insira um valor numérico entre 0 e 100",
  "requiresLocator": "Adicione pelo menos um localizador válido.",
  "layerFields": "Configurações da Camada",
  "layerFieldsHint": "Especifique os campos da Camada de Destino que serão mapeados para os campos de origem.",
  "locatorError": "O localizador é inválido ou inacessível.",
  "optionNotMatch": "As opções de campo não são consistentes entre os localizadores. A ativação após falha pode não funcionar conforme esperado.",
  "targetLayerTabTitle": "Camada de Destino",
  "locationSettingsTabTitle": "Configurações de Local",
  "generalSettingsTabTitle": "Configurações Gerais",
  "addTargetLayersLabel": "Adicionar Camada de Destino",
  "introductoryText": "Criar conteúdo instrutivo para o widget",
  "defaultStartPageInstructions": "Este widget ajudará no processamento e envio de dados de um arquivo para a camada selecionada no mapa.<br/> <br/> Os valores no arquivo devem ser delimitados por vírgula, tabulação, ponto e vírgula ou barra vertical.",
  "noTargetLayerConfiguredErrorMsg": "Nenhuma camada de destino configurada",
  "noFieldsForTargetLayer": "As configurações da camada não estão definidas para a camada de destino",
  "locationSettingsNotConfigured": "As configurações de localização não estão configuradas corretamente"
});