define({
  "locatorUrl": "URL Bộ định vị",
  "set": "Thiết lập",
  "locatorName": "Tên bộ định vị",
  "locatorExample": "Ví dụ",
  "countryCode": "Mã Quốc gia hoặc Khu vực",
  "eg": "ví dụ: ",
  "countryCodeHint": "Để trống giá trị này sẽ tìm kiếm tất cả các quốc gia và khu vực",
  "minCandidateScore": "Điểm số Tối thiểu của Đối tượng tiềm năng",
  "minCandidateScoreHint": "Bỏ trống giá trị này để sử dụng điểm số tối thiểu của đối tượng tiềm năng là 90",
  "enableSingleField": "Tùy chọn Một Trường",
  "singleFieldHint": "Dữ liệu địa chỉ sẽ nằm trong một trường",
  "enableMultiField": "Tùy chọn Nhiều Trường",
  "multiFieldHint": "Dữ liệu địa chỉ sẽ nằm trong nhiều trường",
  "enableXYField": "Tùy chọn Trường X/Y",
  "xyFieldHint": "Dữ liệu sẽ chứa giá trị tọa độ X/Y",
  "instructionGeocode": "Thêm và cấu hình các dịch vụ định vị.",
  "invalidUrlTip": "URL ${URL} không hợp lệ hoặc không thể truy cập được.",
  "geocodeTabLabel": "Thiết lập vị trí",
  "lookupList": "Tên Trường cần Nhận biết",
  "isRecognized": "Các tên trường trong bảng dưới đây sẽ được nhận biết tự động cho trường này",
  "needsEditablePointLayers": "Bản đồ web phải chứa ít nhất một lớp điểm có thể chỉnh sửa.",
  "editpageAlias": "Bí danh",
  "configureFields": "Cấu hình Trường Lớp",
  "configureSingleFields": "Cấu hình Một Trường Địa chỉ",
  "configureMultiFields": "Cấu hình Nhiều Trường Địa chỉ",
  "configureXYFields": "Cấu hình Trường X/Y",
  "noFields": "Sử dụng tác vụ chỉnh sửa để xác định thêm các trường sẽ hiển thị",
  "display": "Hiển thị",
  "duplicate": "Tìm Bản sao",
  "duplicateTip": "Tìm kiếm trường này để xem các giá trị giống nhau giữa tệp tin nguồn và lớp mục tiêu./n Khi tìm thấy kết quả trùng khớp, bản ghi từ tệp tin sẽ không được định vị và sẽ được gắn cờ là bản sao.",
  "noSelectField": "Chọn tùy chọn Lớp Đối tượng trước",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (Kinh độ)",
  "xyFieldsLabelY": "Y (Vĩ độ)",
  "xyFieldsX": "X",
  "xyFieldsY": "Y",
  "easting": "Hướng đông",
  "northing": "Hướng bắc",
  "lon": "Kinh độ",
  "lat": "Vĩ độ",
  "layerOptionHint": "Chọn lớp để gửi dữ liệu tới",
  "layerFieldTitle": "Lớp Mục tiêu",
  "tempSymbolHint": "Chọn ký hiệu được sử dụng để hiển thị các đối tượng.",
  "tempSymbolTitle": "Ký hiệu Hiển thị",
  "maxRecords": "Số bản ghi tối đa",
  "maxRecordsHint": "Số lượng bản ghi tối đa cần định vị",
  "searchRadius": "Bán kính tìm kiếm",
  "searchRadiusHint": "Khoảng cách sẽ tìm kiếm các đối tượng giống nhau từ lớp",
  "requiresInteger": "Nhập một giá trị số.",
  "requiresInteger0100": "Nhập một giá trị số từ 0 đến 100",
  "requiresLocator": "Thêm ít nhất một bộ định vị hợp lệ.",
  "layerFields": "Thiết lập Lớp",
  "layerFieldsHint": "Xác định các trường trong Lớp Mục tiêu sẽ được ánh xạ đến các trường nguồn.",
  "locatorError": "Bộ định vị không hợp lệ hoặc không truy cập được.",
  "optionNotMatch": "Tùy chọn trường không nhất quán giữa các bộ định vị. Khả năng chịu lỗi có thể không cho kết quả như kỳ vọng.",
  "targetLayerTabTitle": "Lớp Mục tiêu",
  "locationSettingsTabTitle": "Thiết lập vị trí",
  "generalSettingsTabTitle": "Thiết lập Tổng quan",
  "addTargetLayersLabel": "Thêm Lớp Mục tiêu",
  "introductoryText": "Tạo nội dung hướng dẫn cho tiện ích",
  "defaultStartPageInstructions": "Tiện ích này sẽ hỗ trợ việc xử lý và gửi dữ liệu từ tệp đến lớp được chọn trong bản đồ.<br/> <br/> Các giá trị trong tệp phải được phân cách bằng dấu phẩy, tab, dấu chấm phẩy hoặc dấu gạch đứng. Tiện ích này sẽ hỗ trợ việc xử lý và gửi dữ liệu từ tệp đến lớp được chọn trong bản đồ.<br/> <br/> Các giá trị trong tệp phải được phân cách bằng dấu phẩy, tab, dấu chấm phẩy hoặc dấu gạch đứng.",
  "noTargetLayerConfiguredErrorMsg": "Không có lớp mục tiêu nào được cấu hình",
  "noFieldsForTargetLayer": "Các thiết lập lớp không được xác định cho lớp mục tiêu",
  "locationSettingsNotConfigured": "Thiết lập vị trí không được cấu hình đúng"
});