define({
  "transparencyLabel": "Permatomumas",
  "outline": "Kontūras",
  "fill": "Užpildas (spalva taikoma, tik kai pasirinktas vientisas stilius)",
  "style": "Stilius",
  "selectOpLayerLabel": "Pasirinkite rezultatų darbinį sluoksnį",
  "selectDefaultMeasurementLabel": "Pasirinkite numatytąjį matavimo vienetą",
  "helpIconTooltip": "Darbinio sluoksnio sąrašas automatiškai užpildytas dabartinio internetinio žemėlapio poligonų geometrijos tipo sluoksniais.",
  "lineStyles": {
    "esriSLSDash": "Brūkšnys",
    "esriSLSDashDot": "Brūkšnys taškas",
    "esriSLSDashDotDot": "Brūkšnys taškas taškas",
    "esriSLSDot": "Taškas",
    "esriSLSLongDash": "Ilgas brūkšnys",
    "esriSLSLongDashDot": "Ilgas brūkšnys taškas",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trumpas brūkšnys",
    "esriSLSShortDashDot": "Trumpas brūkšnys taškas",
    "esriSLSShortDashDotDot": "Trumpas brūkšnys taškas taškas",
    "esriSLSShortDot": "Trumpas taškas",
    "esriSLSSolid": "Vientisas"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atgal",
    "esriSFSCross": "Skersai",
    "esriSFSDiagonalCross": "Įstrižai",
    "esriSFSForwardDiagonal": "Pirmyn",
    "esriSFSHorizontal": "Horizontalė",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vientisas",
    "esriSFSVertical": "Vertikalė"
  },
  "threatTypeLabel": "Grėsmės tipas",
  "generalLabel": "Bendra",
  "addThreatTypesLabel": "Pridėti grėsmės tipą",
  "actions": "Veiksmai",
  "newThreatTypePopupLabel": "Naujas grėsmės tipas",
  "units": "Vienetai",
  "chooseDefaultThreatLabel": "Pasirinkti numatytąjį grėsmės tipą",
  "defaultThreatTypePopUpLabel": "Naujas grėsmės tipas",
  "editThreatLabel": "Redaguoti grėsmę",
  "defaultThreatTypeIconTooltip": "Numatytųjų grėsmės tipų sąrašas",
  "uniqueThreatTypeMsg": "Įveskite unikalų grėsmės tipą. Grėsmės tipas tokiu pavadinimu jau yra.",
  "requiredMsg": "Šis laukas privalomas",
  "unitMeasureLabel": "Atstumas išreikšti {0}",
  "chooseDefaultThreatTypeIconLabel": "Pasirinkti iš numatytųjų",
  "pipeBombLabel": "Vamzdinė bomba",
  "suicideBombLabel": "Savižudžio bomba",
  "briefcaseLabel": "Portfelis",
  "carLabel": "Automobilis",
  "suvVanLabel": "SUV / VAN",
  "smallDeliveryTruckLabel": "Mažų siuntų pristatymo sunkvežimis",
  "containerWaterTruckLabel": "Konteinervežis/ vandenvežis",
  "semiTrailerLabel": "Puspriekabė",
  "chemicalThreatLegendLabel": "Cheminė grėsmė",
  "lpgThreatLegendLabel": "SND grėsmė",
  "smallLPGTank": "Mažas SND rezervuaras",
  "largeLPGTank": "Didelis SND rezervuaras",
  "commercialResidentialLPGTank": "Komercinis / gyvenamasis SND rezervuaras",
  "smallLPGTruck": "Mažas SND sunkvežimis",
  "semiTankerLPG": "Puspriekabė su SND",
  "threatDescriptionColLabel": "Grėsmės aprašas",
  "addThreatZoneButtonLabel": "Pridėti grėsmės zoną",
  "zoneDescColLabel": "Zonos aprašas",
  "distanceLabel": "Atstumas (${unitAbbr})",
  "threatTypeHelp": "<p>Įsitikinkite, kad grėsmės tipas atitinka šias sąlygas :<br/><ul><li>Grėsmės tipas negali būti tuščias ir turi būti unikalus</li><li>Grėsmė turi turėti bent vieną leistiną zoną</li><li>Zonos aprašas turi būti unikalus grėsmei</li></ul><p/>",
  "descriptionLabel": "Aprašas",
  "newThreatZonePopupLabel": "Nauja grėsmės zona",
  "editThreatZonePopupLabel": "Redaguoti grėsmės zoną",
  "uniqueZoneDescriptionMsg": "Įveskite unikalų zonos aprašą; jau yra zonos aprašas su šiuo pavadinimu.",
  "symbologyColLabel": "Simbolizacija",
  "zoneDescriptionColLabel": "Zonos aprašas",
  "uniqueZoneRequiredMsg": "Zonos pavadinimas turi būti unikalus",
  "interactive": "Interaktyvi",
  "fromCoord": "Fiksuota koordinatė",
  "existingFeature": "Iš esamų elementų",
  "defaultInputLocationLabel": "Numatytoji įvesties padėtis",
  "defaultInputLayer": "Numatytasis įvesties sluoksnis",
  "defaultThreatType": "Numatytasis grėsmės tipas",
  "selectLabel": "Pasirinkti",
  "mandatoryLabel": "Būtinas evakuacijos atstumas",
  "safeLabel": "Saugus evakuacijos atstumas",
  "lpgSafeDistanceLable": "Saugus atstumas",
  "fireBallDiameterLable": "Fireball skersmuo"
});