define({
  "_widgetLabel": "Situačné povedomie",
  "locate_incident": "Zamerať incident",
  "reverse_geocoded_address": "Najbližšia adresa",
  "reverse_geocoded_error": "Nie je k dispozícii",
  "actionLabel": "Nastaviť umiestnenie",
  "drawPoint": "Nakresliť bod",
  "drawLine": "Nakresliť líniu",
  "drawPolygon": "Nakresliť polygón",
  "saveIncident": "Uložiť",
  "clearIncident": "Začať odznova",
  "noFeaturesFound": "Neboli nájdené žiadne prvky.",
  "downloadCSV": "Stiahnuť",
  "sum": "Súčet",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Priemer",
  "count": "COUNT",
  "area": "PLOCHA",
  "length": "DĹŽKA",
  "update_btn": "Hotovo",
  "delete_btn": "Odstrániť",
  "get_directions": "Získať navigačné pokyny",
  "incident": "Incident",
  "incidents": "Incidenty",
  "buffer": "Obalová zóna",
  "buffers": "Obalové zóny",
  "_featureAction_ActionLabel": "Nastaviť umiestnenie",
  "_featureAction_AddRemoveActionLabel": "Pridať/Odstrániť umiestnenie",
  "snapshot": "Priečinok snímkov vytvorený aplikáciou s identifikátorom:",
  "user_credentials": "Používateľ nemá platné oprávnenia.",
  "notPolySnapShot": "Prosím špecifikujte šírku obalovej zóny pred vytvorením snímku.",
  "notPolyReport": "Žiadne platné výsledky na pridanie do hlásenia.",
  "notValidDownload": "Žiadne platné výsledky na prevzatie.",
  "of_append": "z",
  "layer_append": "vrstva",
  "downloadAll": "Stiahnuť všetky",
  "createSnapshot": "Vytvoriť snímku",
  "createReport": "Vytvoriť prehľad",
  "calculated_results": "Súhrn informácií",
  "closest": "Najbližší prvok",
  "proximity": "Blízkosť",
  "summary": "Súhrn",
  "groupedSummary": "Zoskupené počty",
  "_count": "Počet",
  "approximate": "približný",
  "snapshot_name": "Nastaviť vlastnosti snímky",
  "report_name": "Nastaviť vlastnosti hlásenia",
  "invalid_snapshot_name": "Neplatné meno snímky.",
  "invalid_report_name": "Neplatný názov hlásenia.",
  "orientation": "Orientácia",
  "pageSize": "Veľkosť strany",
  "comments": "Komentáre",
  "choose_group": "Skupiny",
  "forecast": "Predpoveď",
  "select_group": "Vybrať skupinu",
  "select_group_instruction": "Snímka bude vytvorená a zdieľaná s vybranou skupinou",
  "information_append": " Informácie",
  "distance": "VZDIALENOSŤ",
  "buffer_invalid": "Zadajte platné číslo medzi ${min} a ${max}",
  "layerNotAvalible": "Vrstva nebola nájdená",
  "missingLayer": "Názov:${name}",
  "missingLayerHint": "Jedna alebo viac vrstiev spomenutých v tejto konfigurácií aktuálne nie sú dostupné.",
  "zoomToFeature": "Priblížiť na prvok",
  "saveIncidentErrorMessage": "Nie je možné uložiť prvky. <br> <br> <b> Popis: </b> <br>"
});