define({
  "_widgetLabel": "Dávkový editor atributů",
  "widgetIntroSelectByArea": "Use one of the tools below to create a selected set of features to update.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeature": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> layer.  This feature will be used select and update all intersecting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByFeatureQuery": "Use the tool below to select a feature from <font class='layerInIntro'>${0}</font> .  This feature's <font class='layerInIntro'>${1}</font> attribute will be used to query the layers below and update the resulting features.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "widgetIntroSelectByQuery": "Enter a value to create a selection set.  If the row is <font class='maxRecordInIntro'>highlighted</font>, the maximum number of records has been exceeded.",
  "layerTable": {
    "colLabel": "Jméno vrstvy",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Nejsou nakonfigurovány žádné editovatelné vrstvy",
  "editorPopupTitle": "Dávkový editor atributů",
  "editorPopupSaveBtn": "Uložit",
  "editorPopupMultipleValues": "",
  "clear": "Zrušit",
  "featuresUpdated": "Aktualizované prvky: ${0} / ${1}",
  "featuresSelected": "Počet vybraných prvků: ${0}",
  "featuresSkipped": "Vynecháno",
  "featuresNoPermision": "Počet vybraných prvků: ${0}, ale žádné oprávnění k úpravám.",
  "search": "Hledat",
  "queryInput": "Zadejte hodnotu pro dotázání",
  "noFilterTip": "Without filter expression defined, this query task will list all features in the specified data source.",
  "setFilterTip": "Nastavte filtr správně.",
  "filterPopup": "Filtr vrstvy",
  "filterAppend": "Pokud filtr ve webové mapě pro tuto vrstvu již existuje",
  "filterAppendOR": "Připojit jakýkoliv výraz k existujícímu mapovému filtru",
  "filterAppendAND": "Připojit všechny výrazy k existujícímu mapovému filtru",
  "cancel": "Storno",
  "noValue": "Žádná hodnota",
  "emptyString": "Prázdný řetězec",
  "existingValue": "Zachovat stávající hodnotu",
  "newDate": "Nové datum",
  "valueChooser": "Vyberte či zadejte hodnotu",
  "ok": "OK",
  "drawBox": {
    "point": "Bod",
    "line": "Linie",
    "polyline": "Polylinie",
    "freehandPolyline": "Polylinie od ruky",
    "extent": "Rozsah",
    "polygon": "Polygon",
    "freehandPolygon": "Polygon od ruky",
    "clear": "Zrušit",
    "addPointToolTip": "Kliknutím provedete výběr v této oblasti",
    "addShapeToolTip": "Nakreslete tvar, který chcete použít k výběru prvků",
    "freehandToolTip": "Stisknutím a přidržením nakreslíte tvar, který se použije k výběru prvků",
    "startToolTip": "Nakreslete tvar, který chcete použít k výběru prvků"
  },
  "errors": {
    "layerNotFound": "Layer ${0} with ID ${1} was not found in the map, the map may have changed since the widgets configuration",
    "queryNullID": "Prvek z ${0} vrátil neplatné ID",
    "noSelectedLayers": "Nebyly zvoleny žádné vrstvy se záznamy k aktualizování",
    "inputValueError": "Formulář obsahuje neplatnou hodnotu",
    "saveError": "Prvky ${0} nelze uložit",
    "requiredValue": "Vyžadovaná hodnota"
  }
});