define({
  "locatorUrl": "Adres URL lokatora",
  "set": "Ustaw",
  "locatorName": "Nazwa lokatora",
  "locatorExample": "Przykład",
  "countryCode": "Kod kraju lub regionu",
  "eg": "np. ",
  "countryCodeHint": "Pozostawienie pustego pola uruchomi wyszukiwanie we wszystkich krajach i regionach",
  "minCandidateScore": "Minimalny wynik kandydata",
  "minCandidateScoreHint": "Pozostawienie pustego pola spowoduje użycie minimalnego wyniku kandydata o wartości 90",
  "enableSingleField": "Opcje z jednym polem",
  "singleFieldHint": "Dane adresowe będą znajdować się w jednym polu",
  "enableMultiField": "Opcje z wieloma polami",
  "multiFieldHint": "Dane adresowe będą znajdować się w wielu polach",
  "enableXYField": "Opcje z polami X/Y",
  "xyFieldHint": "Dane będą zawierać wartości współrzędnych X/Y",
  "instructionGeocode": "Dodaj i skonfiguruj usługi lokalizatora.",
  "invalidUrlTip": "Adres URL ${URL} jest nieprawidłowy lub nieosiągalny.",
  "geocodeTabLabel": "Ustawienia lokalizacji",
  "lookupList": "Nazwy pól do rozpoznania",
  "isRecognized": "Dla tego pola nazwy pól w poniższej tabeli są rozpoznawane automatycznie",
  "needsEditablePointLayers": "Mapa internetowa musi zawierać co najmniej jedną warstwę punktową możliwą do edycji.",
  "editpageAlias": "Alias",
  "configureFields": "Skonfiguruj pola warstwy",
  "configureSingleFields": "Skonfiguruj jedno pole adresu",
  "configureMultiFields": "Skonfiguruj wiele pól adresu",
  "configureXYFields": "Skonfiguruj pola X/Y",
  "noFields": "Użyj tego działania edycji, aby zdefiniować jedno lub większą liczbę pól do wyświetlenia",
  "display": "Wyświetl",
  "duplicate": "Znajdź duplikat",
  "duplicateTip": "Szukaj identycznych wartości występujących w tym polu w pliku źródłowym i warstwie docelowej./n Gdy zostaną znalezione takie same wartości, rekord z pliku nie będzie lokalizowany i zostanie oznaczony jako duplikat.",
  "noSelectField": "Najpierw wybierz opcję Warstwa obiektowa",
  "newNamePlaceholder": "",
  "xyFieldsLabelX": "X (długość geograficzna)",
  "xyFieldsLabelY": "Y (szerokość geograficzna)",
  "xyFieldsX": "X",
  "xyFieldsY": "T",
  "easting": "Współrzędne wschodnie",
  "northing": "Współrzędne północne",
  "lon": "LON",
  "lat": "LAT",
  "layerOptionHint": "Wybierz warstwę, do której chcesz przesłać dane.",
  "layerFieldTitle": "Warstwa docelowa",
  "tempSymbolHint": "Wybierz symbol, który będzie używany do wyświetlania tych obiektów.",
  "tempSymbolTitle": "Wyświetl symbol",
  "maxRecords": "Maksymalna liczba rekordów",
  "maxRecordsHint": "Maksymalna liczba rekordów do zlokalizowania",
  "searchRadius": "Promień wyszukiwania",
  "searchRadiusHint": "Odległość do wyszukania zduplikowanych obiektów z warstwy",
  "requiresInteger": "Wprowadź wartość liczbową.",
  "requiresInteger0100": "Wprowadź wartość liczbową z przedziału od 0 do 100",
  "requiresLocator": "Dodaj co najmniej jeden prawidłowy lokalizator.",
  "layerFields": "Ustawienia warstwy",
  "layerFieldsHint": "Wskaż pola z warstwy docelowej, które zostaną przyporządkowane do pól źródłowych.",
  "locatorError": "Lokalizator jest nieprawidłowy lub niedostępny.",
  "optionNotMatch": "Opcje dotyczące pól nie są spójne w lokalizatorach. Przełączanie awaryjne może nie działać w oczekiwany sposób.",
  "targetLayerTabTitle": "Warstwa docelowa",
  "locationSettingsTabTitle": "Ustawienia lokalizacji",
  "generalSettingsTabTitle": "Ustawienia ogólne",
  "addTargetLayersLabel": "Dodaj warstwę docelową",
  "introductoryText": "Utwórz zasoby instruktażowe dotyczące widżetu",
  "defaultStartPageInstructions": "Ten widżet ułatwia przetwarzanie i wysłanie danych z pliku do wybranej warstwy na mapie.<br/> <br/> Wartości w pliku muszą być rozdzielane przecinkami, tabulatorami, średnikami lub kreskami pionowymi.",
  "noTargetLayerConfiguredErrorMsg": "Nie skonfigurowano warstwy docelowej",
  "noFieldsForTargetLayer": "Nie zdefiniowano ustawień warstwy docelowej",
  "locationSettingsNotConfigured": "Ustawienia lokalizacji nie są prawidłowo skonfigurowane",
  "questionMark": "?"
});