define({
  "_widgetLabel": "צבירת נתונים",
  "startPage": {
    "defaultStartPageInstructions": "ווידג'ט זה יסייע בעיבוד ושליחה של נתונים מקובץ אל השכבה שנבחרה במפה.<br/> <br/> יש להפריד את הערכים בקובץ באמצעות פסיק, טאב, נקודה-פסיק או פס אנכי.",
    "dragDrop": "גרור ושחרר",
    "browse": "עיין לאיתור הקובץ",
    "or": "'או'",
    "userPrivilege": "לחשבונך אין הרשאות ליצור נתונים או לשנות אותם.",
    "userCredits": "ל-${widgetName} נדרשים אישורים כדי להשתמש במגדיר עיגון הכתובות ${locator}.",
    "contactAdmin": "פנה אל מנהל המערכת בארגון כדי לבקש אישורים נוספים.",
    "contactAdminEdit": "פנה אל מנהל המערכת בארגון כדי לבקש הרשאות עריכה.",
    "canUseLocator": "מגדיר עיגון הכתובות ${locator} ישמש לאיתור ישויות.",
    "notEnoughCredits": "אין מספיק קרדיטים.",
    "locationAndField": "פרטי מיקום ושדה",
    "locationAndFieldHint": "בחר בערכים מהקובץ שבהם יש להשתמש כדי לעדכן את שכבת היעד.",
    "cannotUseLocator": "אפשר שימוש ב-${widgetName}",
    "noAnonymousEdit": "השכבה ${layerName} לא תומכת בעריכה בעילום שם.",
    "pleaseLogin": "התחבר לארגון ${org} או פנה למנהל המערכת של הארגון כדי לבקש שעריכה בעילום שם תאופשר.",
    "invalidEdit": "הרשאות לא חוקיות",
    "unableToAccess": "אין אפשרות לגשת ל-${layerName}",
    "appropriateCredentials": "ודא שהתחברת עם האישורים המתאימים.",
    "shared": "פנה אל מנהל המערכת של הארגון בארגונך כדי לבקש גישה לשכבה ${layerName}.",
    "targetLayerLabel": "שכבת יעד",
    "homeButtonLabel": "דף הבית",
    "mappingErrorMsg": "לחץ על החץ הבא כדי להגדיר את השדות"
  },
  "mapping": {
    "schemaMapping": "פרטי שדה",
    "schemaMappingHint": "בחר מהקובץ שדות התואמים לשדות בשכבה.",
    "locationMapping": "פרטי מיקום",
    "locationMappingHint": "בחר את הסוג של פרטי הכתובות או הקואורדינטות שיש לצפות למצוא בקובץ."
  },
  "locationMapping": {
    "locationMappingPageHint": "בחר סוג מיקום",
    "useAddress": "איתור באמצעות כתובת",
    "useAddressHint": "הנתונים מכילים נתוני כתובת",
    "useCoordinates": "איתור באמצעות קואורדינטות",
    "useCoordinatesHint": "הנתונים מכילים ערכי X/Y של קואורדינטות"
  },
  "address": {
    "addressPageHint": "בחר סוג כתובת",
    "singleField": "שדה בודד",
    "singleFieldHint": "בחר בשדה שמכיל את פרטי הכתובת",
    "multiField": "שדות מרובים",
    "multiFieldHint": "בחר בשדות שמכילים את פרטי הכתובת"
  },
  "coordinates": {
    "coordinatesPageHint": "בחר בשדות שמכילים את נתוני הקואורדינטות"
  },
  "fieldMapping": {
    "fieldMappingPageHint": "בחר את שדה המקור הממפה אל שדה היעד",
    "sourceField": "שדה מקור תואם",
    "targetField": "שדות יעד"
  },
  "buttons": {
    "addToMap": "הוסף למפה",
    "submit": "שלח",
    "download": "הורדה"
  },
  "review": {
    "matched": "נמצא",
    "reviewMatched": "מיקומים שנמצאו",
    "reviewMatchedHint": "סקור את המיקומים שנמצאו.",
    "unMatched": "לא נמצא",
    "reviewUnMatched": "לא נמצאו מיקומים",
    "reviewUnMatchedHint": "סקור את המיקומים שלא נמצאו. פריטים שאינם נכונים לא יישלחו.",
    "duplicate": "שכפול",
    "reviewDuplicate": "מיקומים כפולים",
    "reviewDuplicateHint": "סקור מיקומים שכבר נמצאו בשכבה. פריטים שלא טופלו לא יישלחו.",
    "reviewLabelWithCount": "${totalMatchedFeatures} ${headerString} ${headerStringHint}",
    "use": "שימוש:",
    "fromLayer": "פרטי יעד",
    "target": "יעד",
    "source": "מקור",
    "fromFile": "מקור מידע",
    "locationControlHint": "סקור פרטי כתובת",
    "duplicateAction": "בחר פעולה",
    "item": "רשומה:",
    "locateFeature": "אתר ישות",
    "removeFeature": "הסר ישות",
    "featureLocated": "מיקום נמצא",
    "valuesDoNotMatch": "לא תואם לערך הקיים",
    "sync": "סנכרן פרטי כתובת עם פרטי שדה",
    "noFeaturesSaved": "אף ישות לא נשמרה בהצלחה",
    "someFeaturesSaved": "${num} ישות/יות נשמרה/ו בהצלחה.",
    "someFeaturesNotSaved": "${num} ישות/יות לא נשמרה/ו בהצלחה.",
    "feature": "סקור פרטי ישות",
    "locationInfo": "סקור פרטי מיקום",
    "selectValue": "בחר ערך",
    "reviewData": "סקור נתונים",
    "reviewDataHint": "סקור את הנתונים שלך לפני שליחה לשכבה.",
    "reviewFeatureHint": "סקור או ערוך את פרטי הישות והמיקום שלך.",
    "duplicateModify": "כפילות, נדרש שינוי",
    "duplicateSave": "שמור כיישות חדשה"
  },
  "warningsAndErrors": {
    "invalidCSV": "שגיאה בהבאת פריטים מ-CSV, בדוק אם נבחר קובץ CSV תקין.",
    "noLayersWarning": "לא הוגדרה שכבת יעד תקינה, בדוק את הגדרת התצורה.",
    "loadWarning": "ווידג'ט זה מחייב מקור נתונים מסוג 'שירות ישויות'. קבע את תצורת הווידג'ט כדי להגדיר מקור נתונים.",
    "saveError": "אירעה שגיאה בעת שמירת הישויות.",
    "consumesCredits": "כלי זה צורך קרדיטים בעת השימוש עם שירות עיגון הכתובות העולמי של ArcGIS Online.",
    "noValue": "בחר שדה",
    "mappingTitle": "",
    "locationMappingComplete": "מיפוי המיקומים הושלם",
    "fieldMappingComplete": "מיפוי השדות הושלם",
    "settingsCleared": "ההגדרות יימחקו.",
    "proceed": "האם ברצונך להמשיך?",
    "itemMoveMatch": "הפריט נמצא והועבר לרשימת המיקומים שנמצאו",
    "itemMoveUnMatched": "לא ניתן לאתר את הפריט. הועבר לרשימת המיקומים שלא נמצאו.",
    "itemWillBeLocated": "הפריט יוסר מרשימת המיקומים הכפולים.",
    "cannotLocate": "לא ניתן לאתר את הפריט. אמת את פרטי המיקום.",
    "invalidMessage": "ערך לא חוקי.",
    "rangeMessage": "הערך לא יכול להכיל יותר מ-${num} תווים.",
    "locatorError": "מגדיר עיגון הכתובות לא חוקי או לא נגיש.",
    "notConfigured": "מגדיר עיגון הכתובות לא הוגדר עבור אפשרויות האיתור הנוכחיות",
    "noMoreLocators": "לא הוגדרו מגדירי עיגון כתובות נוספים"
  },
  "featureToolbar": {
    "locate": "Locate",
    "save": "שמור רשומה",
    "cancel": "בטל שינויים",
    "cancelTitle": "בטל שינויים",
    "cancelMessage": "לבטל שינויים ברשומה הנוכחית?"
  }
});