define({
  "_widgetLabel": "Pametni uređivač",
  "_featureAction_SmartEditor": "Pametni uređivač",
  "noEditPrivileges": "Vaš račun nema dopuštenje za stvaranje ili mijenjanje podataka.",
  "loginPopupTitle": "Prijava",
  "loginPopupMessage": "${widgetName} zahtijeva dozvole i kredite za pretragu i pohranu podataka o adresi. Želite li se prijaviti i koristiti ovu mogućnost?",
  "noCreditsOrPrivilegeWarningMessage": "Vaš račun nema dozvole i kredite za pretragu i pohranu podataka o adresi s ${widgetName}. Molimo kontaktirajte administratora organizacije kako biste zatražili dozvole i kredite. Kliknite OK za nastavak uređivanja.",
  "unableToUseLocator": "Lokator nije dostupan. Radnja(e) atributa adrese neće se izvršiti. Kliknite OK za nastavak uređivanja.",
  "locatorDisabledWaning": "Lokator nije omogućen. Molimo kontaktirajte administratora organizacije kako biste zatražili ovu mogućnost. Kliknite OK za nastavak uređivanja.",
  "noFeatureInAIWarning": "Nijedan geoobjekt(i) nije(su) odabrani. Molimo odaberite geoobjekt za izvršavanje uređivanja ili kliknite Poništi za povratak na glavni zaslon.",
  "noEditableLayerWarning": "Vaš račun nema dozvolu za stvaranje ili izmjenu podataka ili ova web karta ne sadrži slojeve koji se mogu uređivati.",
  "noVisibleCreateLayerWarning": "Sloj(evi) nije(su) vidljiv(i) na trenutnoj razini zumiranja. Povećajte ili smanjite za stvaranje / izmjenu geoobjekata.",
  "noVisibleUpdateLayerWarning": "Sloj(evi) nije(su) vidljiv(i) na trenutnoj razini zumiranja. Povećajte ili smanjite za izmjenu geoobjekata.",
  "checkLayerVisibilityInWebMapWarning": "Provjerite jesu li slojevi vidljivi na karti kako biste stvorili ili izmijenili geoobjekte.",
  "showSelectionInAITitle": "Odabrani geoobjekti",
  "showSelectionInAIMsg": "Želite li učitati trenutni odabir u ${widgetName}?",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Nije aktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL ",
  "snapStr": " za omogućivanje priljepljivanja",
  "noAvailableTempaltes": "Nema dostupnih predložaka",
  "editorCache": " - Predmemorija uređivača",
  "presetFieldAlias": "Polje",
  "presetValue": "Prethodno postavljena vrijednost",
  "usePresetValues": " Upotrijebi prethodne postavljene vrijednosti (samo novi geoobjekti)",
  "editGeometry": " Uredi geometriju",
  "savePromptTitle": "Spremi geoobjekt",
  "savePrompt": "Želite li spremiti trenutačni geoobjekt?",
  "deletePromptTitle": "Izbriši geoobjekt",
  "deleteAttachment": "Izbriši privitak",
  "deletePrompt": "Jeste li sigurni da želite izbrisati odabrani geoobjekt?",
  "attachmentLoadingError": "Pogreška pri učitavanju privitaka",
  "attachmentSaveDeleteWarning": "Upozorenje: promjene na privicima automatski se spremaju",
  "autoSaveEdits": "Automatski spremaj nove geoobjekte",
  "addNewFeature": "Stvori novi geoobjekt",
  "featureCreationFailedMsg": "Nije moguće stvoriti novi zapis/geoobjekt",
  "relatedItemTitle": "Povezana tablica/sloj",
  "relatedFeatureCount": "${layerTitle} s ${featureCount} geoobjektima",
  "createNewFeatureLabel": "Stvori novi geoobjekt za ${layerTitle}",
  "invalidRelationShipMsg": "Pobrinite se da primarno polje ključa: „${parentKeyField}” ima valjanu vrijednost",
  "pendingFeatureSaveMsg": "Spremite uređivanja geoobjekta prije stvaranja povezanog geoobjekta.",
  "attachmentsRequiredMsg": "(*) Privici su obvezni.",
  "coordinatePopupTitle": "Pomakni geoobjekt na XY lokaciju",
  "coordinatesSelectTitle": "Koordinatni sustav:",
  "mapSpecialReferenceDropdownOption": "Prostorna referenca karte",
  "latLongDropdownOption": "Geografska dužina/širina",
  "mgrsDropdownOption": "Vojni pravokutni koordinatni sustav (MGRS)",
  "mgrsTextBoxLabel": "Koordinata:",
  "xAttributeTextBoxLabel": "X-koordinata:",
  "yAttributeTextBoxLabel": "Y-koordinata:",
  "latitudeTextBoxLabel": "Geografska širina:",
  "longitudeTextBoxLabel": "Geografska dužina:",
  "presetGroupFieldsLabel": "'${groupName}' bit će primijenjen na sljedeća polja slojeva:",
  "presetGroupNoFieldsLabel": "'${groupName}’ nema pridruženih polja",
  "groupInfoLabel": "Informacije o grupi za '${groupName}'",
  "editGroupInfoIcon": "Uredi vrijednost grupe za ${groupName}",
  "filterEditor": {
    "all": "Svi",
    "noAvailableTempaltes": "Nema dostupnih predložaka",
    "searchTemplates": "Pretraži predloške",
    "filterLayerLabel": "Slojevi za filtriranje"
  },
  "invalidConfiguration": "Widget nije konfiguriran ili slojevi u konfiguraciji više nisu u karti. Otvorite app u načinu sastavljača i ponovo konfigurirajte widget.",
  "geometryServiceURLNotFoundMSG": "Nije moguće dohvatiti URL usluge geometrije",
  "clearSelection": "Zatvori",
  "refreshAttributes": "Ažuriranje atributa dinamičnih geoobjekata",
  "automaticAttributeUpdatesOn": "Automatsko ažuriranje atributa geoobjekata: uključeno",
  "automaticAttributeUpdatesOff": "Automatsko ažuriranje atributa geoobjekata: isključeno",
  "moveSelectedFeatureToGPS": "Pomakni odabrani geoobjekt na trenutnu GPS lokaciju",
  "moveSelectedFeatureToXY": "Pomakni odabrani geoobjekt na XY lokaciju",
  "mapNavigationLocked": "Navigacija karte: zaključana",
  "mapNavigationUnLocked": "Navigacija karte: otključana",
  "copyFeatures": {
    "title": "Odaberi geoobjekte za kopiranje",
    "createFeatures": "Stvori geoobjekte",
    "createSingleFeature": "Stvori 1 višedijelni geoobjekt",
    "createOneSingleFeature": "Stvori geoobjekt",
    "noFeaturesSelectedMessage": "Nema odabranog geoobjekta",
    "selectFeatureToCopyMessage": "Odaberite geoobjekte za kopiranje",
    "multipleFeatureSaveWarning": "Stvaranje više geoobjekata pomoću ove funkcije odmah će spremiti sve nove geoobjekte. Podudaranje polja nije podržano kada se stvara novi višedjelni geoobjekt.",
    "copyFeatureUpdateGeometryError": "Nije moguće ažurirati geometriju odabranih geoobjekata",
    "canNotSaveMultipleFeatureWarning": "Možete kopirati samo jedan geoobjekt kada sloj ciljne točke ima polja jedinstvene vrijednosti.",
    "createOnlyOneMultipartFeatureWarning": "Možete kopirati samo jedan geoobjekt ili stvoriti jedan višedijelni geoobjekt kada ciljni sloj ima polja jedinstvene vrijednosti.",
    "layerLabel": "${layerName} (${selectedFeatures}/${totalFeatures})",
    "layerAriaLabel": "${layerName} ${selectedFeatures} od ${totalFeatures} geoobjekata odabrano"
  },
  "addingFeatureError": "Pogreška prilikom dodavanja odabranih geoobjekata u sloj. Pokušajte ponovno.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' geoobjekt(i) nije(su) se uspio(jeli) kopirati. Želite li pokušati ponovno za geoobjekt(e) koji nedostaje(u)?",
  "selectingFeatureError": "Pogreška prilikom odabira geoobjekata u sloju. Pokušajte ponovno.",
  "customSelectOptionLabel": "Odaberi geoobjekte za kopiranje",
  "copyFeaturesWithPolygon": "Kopiraj poligonom",
  "copyFeaturesWithRect": "Kopiraj pravokutnikom",
  "copyFeaturesWithLasso": "Kopiraj lasom",
  "noFeatureSelectedMessage": "Geoobjekti nisu odabrani",
  "multipleFeatureSaveMessage": "Svi će se geoobjekti odmah spremiti. Želite li nastaviti?",
  "relativeDates": {
    "dateTypeLabel": "Vrsta datuma",
    "valueLabel": "Vrijednost",
    "fixed": "Popravljeno",
    "current": "Trenutačno",
    "past": "Prošli",
    "future": "Buduće",
    "popupTitle": "Odaberi vrijednost",
    "hintForFixedDateType": "Savjet: određeni datum i vrijeme bit će upotrijebljeni kao prethodno postavljene zadane vrijednosti.",
    "hintForCurrentDateType": "Savjet: trenutačni datum i vrijeme bit će upotrijebljeni kao prethodno postavljene zadane vrijednosti.",
    "hintForPastDateType": "Savjet: Određena vrijednost bit će odbijena od trenutačnog datuma i vremena za zadanu prethodno postavljenu vrijednost.",
    "hintForFutureDateType": "Savjet: Određena vrijednost bit će dodana trenutačnom datumu i vremenu za zadanu prethodno postavljenu vrijednost.",
    "noDateDefinedTooltip": "Nije određen datum",
    "relativeDateWarning": "Vrijednost datuma ili vremena mora se specificirati kako bi se mogla spremiti zadana unaprijed postavljena vrijednost.",
    "customLabel": "Prilagodi",
    "layerLabel": "Sloj",
    "domainFieldHintLabel": "Odabrana vrijednost je domena kodirane vrijednosti. Vrijednost: \"${domainValue}\" će biti korištena"
  },
  "valuePicker": {
    "popupTitle": "Odaberi vrijednost",
    "popupHint": "Trenutni geoobjekt se presijeca s više geoobjekata, odaberite vrijednost za određeno polje",
    "buttonTooltip": "Odaberite vrijednost iz više geoobjekata koji se presijecaju"
  },
  "uniqueValueErrorMessage": "Vrijednost u \"${fieldName}\" već postoji, navedite novu vrijednost.",
  "requiredFields": {
    "displayMsg": "Obavezna polja ne mogu biti prazna. U nastavku navedite vrijednosti za uobičajena polja.",
    "popupTittle": "Potrebna polja",
    "foundNullRecordCount": "${fieldName} (Pronađeno u ${count} zapisa)"
  },
  "fieldsMapping": {
    "popupTittle": "Primijeni podudaranje polja",
    "fieldsMatchingCheckboxLabel": "Vrijednosti iz kopiranih geoobjekata nadjačat će zadane vrijednosti u ciljnim poljima",
    "resetLabel": "Vrati izvorno",
    "clearLabel": "Ukloni",
    "fieldsInTargetLayerLabel": "Cilj",
    "fieldsInSourceLayerLabel": "Izvor",
    "targetFieldsMatchedLabel": "${layerName} (${matchedFields}/${totalFields} polja se podudara)",
    "selectSourceFieldLabel": "-- Odaberite --",
    "selectFieldAriaLabel": "Odaberite izvorno polje za ciljno polje ${targetField}",
    "informativeText": "Pregledajte podudaranje izvornih polja s ciljnima i prilagodite ako je potrebno.",
    "dynamicValueText": "Postavljena je dinamična vrijednost",
    "noFieldsToMatchLabel": "Nema polja za podudaranje"
  },
  "cantLocateUserLocation": "Vaša se lokacija ne može utvrditi",
  "tryAgainButtonLabel": "Pokušajte ponovno",
  "copyFeatureFailedPopupTitle": "Ups!"
});