define({
  "defaultAreaUnit": "Стандартна единица за площ",
  "defaultLengthUnit": "Стандартна единица за дължина",
  "metric": "Метрични",
  "imperial": "Имперски",
  "squareKilometers": "Кв. километри",
  "squareMeters": "Кв. метри",
  "squareMiles": "Кв. мили",
  "squareInches": "Кв. инч",
  "squareFeet": "Кв. фут",
  "squareYards": "Кв. ярд",
  "squareUSFeet": "Кв. фут (Ам.)",
  "acres": "Акри",
  "ares": "Ар",
  "hectares": "Хектари",
  "inches": "Инч",
  "feet": "Фут",
  "yards": "Ярда",
  "miles": "Мили",
  "nauticalMiles": "Морски мили",
  "feetUS": "Фут (Ам.)",
  "meters": "Метри",
  "kilometers": "Километри",
  "showArea": "Площ",
  "showDistance": "Разстояние",
  "showLocation": "Местоположение",
  "showSlice": "Изрязване",
  "showtools": "Показване на инструменти за измерване:",
  "allHidedTips": "Трябва да бъде избран най-малко един инструмент:"
});