define({
  "_widgetLabel": "Hromadné editovanie atribútov",
  "widgetIntroSelectByArea": "Na vytvorenie vybranej množiny prvkov, ktoré sa majú aktualizovať, použite jeden z nižšie uvedených nástrojov. Ak je riadok <font class='maxRecordInIntro'>zvýraznený</font>, maximálny počet záznamov bol prekročený.",
  "widgetIntroSelectByFeature": "Použite nižšieuvedený nástroj na výber prvku z <font class='layerInIntro'>${0}</font>vrstvy. Tento prvok bude použitý na výber a aktualizáciu všetkých pretínajúcich sa prvkov. Ake je riadok <font class='maxRecordInIntro'>zvýraznený</font>, maximálny počet záznamov bol prekročený.",
  "widgetIntroSelectByFeatureQuery": "Použite nižšieuvedený nástroj na výber prvku z <font class='layerInIntro'>${0}</font>. Atribút <font class='layerInIntro'>${1}</font> prvku bude použitý na dopytovanie vrstiev nižšie a aktualizáciu výsledných prvkov. Ak je riadok <font class='maxRecordInIntro'>zvýraznený</font>, maximálny počet záznamov bol prekročený.",
  "widgetIntroSelectByQuery": "Zadajte hodnotu na vytvorenie sady výberu. Ak je riadok <font class='maxRecordInIntro'>zvýraznený</font>, maximálny počet záznamov bol prekročený.",
  "layerTable": {
    "colLabel": "Názov vrstvy",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Žiadne konfigurované editovateľné vrstvy",
  "editorPopupTitle": "Hromadné editovanie atribútov",
  "editorPopupSaveBtn": "Uložiť",
  "editorPopupMultipleValues": "",
  "clear": "Vyčistiť",
  "featuresUpdated": "${0} / ${1} prvkov aktualizovaných",
  "featuresSelected": "${0} prvkov vybraných",
  "featuresSkipped": "Vynechaný",
  "search": "Vyhľadávanie",
  "queryInput": "Zadať hodnotu pre dopyt",
  "noFilterTip": "Bez definovaného výrazu filtra bude táto úloha dopytu obsahovať všetky prvky v zadanom zdroji dát.",
  "setFilterTip": "Nastavte filter správne.",
  "filterPopup": "Vrstva filtra",
  "filterAppend": "Ak filter už existuje v tejto webovej mape pre túto vrstvu",
  "filterAppendOR": "Pripojiť akýkoľvek výraz k existujúcemu mapovému filtru",
  "filterAppendAND": "Pripojiť všetky výrazy k existujúcemu mapovému filtru",
  "cancel": "Zrušiť",
  "noValue": "Žiadna hodnota",
  "emptyString": "Prázdny reťazec",
  "existingValue": "Ponechať existujúcu hodnotu",
  "newDate": "Nový dátum",
  "valueChooser": "Vybrať/Napísať hodnotu",
  "ok": "OK",
  "drawBox": {
    "point": "Bod",
    "line": "Línia",
    "polyline": "Lomená čiara",
    "freehandPolyline": "Čiara voľnou rukou",
    "extent": "Rozsah",
    "polygon": "Polygón",
    "freehandPolygon": "Polygón voľnou rukou",
    "clear": "Vyčistiť",
    "addPointToolTip": "Kliknite pre výber v tejto oblasti",
    "addShapeToolTip": "Nakreslite útvar na výber prvkov",
    "freehandToolTip": "Stlačením a podržaním nakreslite tvar na výber prvkov",
    "startToolTip": "Nakreslite útvar na výber prvkov"
  },
  "errors": {
    "layerNotFound": "Vrstva ${0} s ID ${1} nebola nájdená na mape, mapa mohla byť od konfigurácie widgetu zmenená",
    "queryNullID": "Prvok z ${0} vrátil neplatné ID",
    "noSelectedLayers": "Žiadne vybrané vrstvy so záznamami na aktualizáciu",
    "inputValueError": "Neplatná hodnota vo formulári",
    "saveError": "Nie je možné uložiť prvky ${0}, podrobnosti pridané do konzoly",
    "requiredValue": "Vyžadovaná hodnota"
  }
});