define({
  "_widgetLabel": "Разстояние и посока",
  "tabLineTitle": "Линия",
  "tabCircleTitle": "Окръжност",
  "tabEllipseTitle": "Елипса",
  "tabRingsTitle": "Кръгове",
  "multipleNotationsMessage": " нотации, които съответстват на въведеното от вас. Моля, потвърдете кое бихте желали да използвате:",
  "invalidCoordinateMessage": "Невалидни координати",
  "confirmInputNotationMessage": "Потвърждаване на нотацията за входни данни",
  "prefixSuffixMessage": "Входната координата е открита като имаща и префикс, и суфикс за стойността на географската ширина или дължина, координатата е върната поради префикса.",
  "rememberDecisionMessage": "Запомни решението ми и не ме питай отново.<br/>",
  "majorAxisTooltipMessage": "Натиснете върху дължината на голямата ос",
  "minorAxisTooltipMessage": "Преместете мишката назад в начална позиция, за да зададете най-късата ос и завършете чертането на елипса",
  "clickToFinishLineMessage": "Натиснете, за да дочертаете линията",
  "doubleClickEllipseMesage": "Натиснете два пъти, за да завършите чертането на диапазона от кръгове",
  "invalidCoordinateTypeMessage": "Не може да се определи типът на входните координати. Моля, проверете входните си данни.",
  "noCenterPointSetMessage": "Не е зададена централна точка. Моля, проверете входните си данни.",
  "ellipseMajorAxis": "Голяма ос",
  "ellipseMinorAxis": "Най-късата ос",
  "degreesRangeMessage": "Стойността трябва да бъде между 0 и 360",
  "millsRangeMessage": "Стойността трябва да бъде между 0 и 6400",
  "lengthLabel": "Дължина",
  "angleLabel": "Ъгъл",
  "startPointLabel": "Начална точка",
  "endPointLabel": "Крайна точка",
  "centerPointLabel": "Централна точка",
  "distanceTableErrorMessage": "Таблицата за разстояния е празна. Моля, уверете се, че сте въвели някои разстояния.",
  "setCoordFormatStringMessage": "Задайте текстов формат на координати",
  "prefixMessage": "Добавете префикса „+/-“ съответно за положителни и отрицателни числа",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM (Универсална напречна проекция на Меркатор)",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Десетични градуси – географска ширина/географска дължина",
  "DDLongLatNotation": "Десетични градуси – географска дължина/географска ширина",
  "DDMLatLongNotation": "Десетични градуси минути – геаографска ширина/географска дължина",
  "DDMLongLatNotation": "Десетични градуси минути – географска дължина/географска ширина",
  "DMSLatLongNotation": "Десетични минути секунди – географска ширина/географска дължина",
  "DMSLongLatNotation": "Десетични минути секунди – географска дължина/географска ширина",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Буква на честотна лента",
  "UTMHemNotation": "UTM - Полукълбо (С/Ю)",
  "circleTitle": "Създаване на окръжност от",
  "radiusLabel": "Радиус",
  "diameterLabel": "Диаметър",
  "startPointPlaceHolderLabel": "Въвеждане на координати",
  "formatInputLabel": "Формат на въвеждане",
  "drawCircleLabel": "Начертаване на окръжност",
  "drawLineLabel": "Начертаване на линия",
  "createCircleInteractivelyLabel": "Интерактивно начертаване на окръжност",
  "rangeErrorMessage": "Невалиден радиус или диаметър",
  "numericInvalidMessage": "Моля, въведете цифрова стойност",
  "timeLabel": "Време",
  "invalidTimeMessage": "Невалидна стойност на времето",
  "hoursLabel": "Часове",
  "minutesLabel": "Минути",
  "secondsLabel": "Секунди",
  "rateLabel": "Скорост на възпроизвеждане",
  "invalidDistanceMessage": "Невалидна стойност за разстояние",
  "feetSecondsLabel": "Фута / секунда",
  "feetHourLabel": "Фута / час",
  "kmSecondLabel": "Километри / секунда",
  "kmHourLabel": "Километри / час",
  "metersSecondLabel": "Метри / секунда",
  "metersHourLabel": "Метри / час",
  "milesSecondLabel": "Мили / секунда",
  "milesHourLabel": "Мили / час",
  "nauticalMilesSecondLabel": "Морски мили / секунда",
  "nauticalMilesHourLabel": "Морски мили / час",
  "clearGraphicsLabel": "Изчистване на графики",
  "ellipseTypeLabel": "Тип елипса",
  "ellipseSemiLabel": "Полу-",
  "ellipseFullLabel": "Напълно",
  "drawEllipseLabel": "Начертаване на елипса",
  "createEllipseInteractively": "Интерактивно начертаване на елипса",
  "axisLabel": "Ос",
  "unitLabel": "Единица",
  "majorRadiusLabel": "Голям (Радиус)",
  "majorDiameterLabel": "Голям (Диаметър)",
  "axisErrorMessage": "Стойността трябва да е по-голяма от 0",
  "minorRadiusLabel": "Малък (Радиус)",
  "minorDiameterLabel": "Малък (Диаметър)",
  "orientationLabel": "Ориентация",
  "orientationErrorMessage": "Стойността трябва да бъде между 0 и 360",
  "warningMessage": "Предупреждение: Графиките, генерирани с помощта на инструмента елипса, не са геодезични",
  "fromLabel": "От",
  "distanceBearingLabel": "Разстояние и ъгъл от известна посока",
  "pointsLabel": "Точки",
  "createLineInteractively": "Интерактивно начертаване на линия",
  "lineLengthErrorMessage": "Невалидна дължина на линия",
  "degreesLabel": "Градуси",
  "milsLabel": "Милс",
  "lineTypeLabel": "Тип",
  "interactiveLabel": "Интерактивни",
  "fixedLabel": "Фиксирани",
  "originLabel": "Базова точка",
  "cumulativeLabel": "Кумулативни",
  "numberOfRingsLabel": "Брой кръгове",
  "ringsErrorMessage": "Невалиден брой кръгове",
  "distanceBetweenRingsLabel": "Разстояние между кръгове",
  "ringsDecimalErrorMessage": "Въведете числова стойност до 2 знака след десетичната запетая",
  "distanceUnitsLabel": "Единици за разстояние",
  "distancesLabel": "Разстояния",
  "numberOfRadialsLabel": "Брой радиали",
  "upLabel": "Нагоре",
  "downLabel": "Надолу",
  "deleteLabel": "Изтриване",
  "radialsErrorMessage": "Невалиден брой радиали. Максимално разрешения брой е 360",
  "radialsInvalidMessage": "Невалидна стойност за радиали",
  "addPointLabel": "Добавяне на точка",
  "valueLabel": "Стойност",
  "valueText": "Въвеждане на стойност",
  "actionLabel": "Действие",
  "distanceCalculatorLabel": "Калкулатор на разстояние",
  "abbrevMetersLabel": "м",
  "abbrevFeetLabel": "фут",
  "abbrevKmLabel": "км",
  "abbrevMilesLabel": "миля",
  "abbrevYardsLabel": "ярд",
  "abbrevNauticalMilesLabel": "нм",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "мил",
  "abbrevHoursLabel": "ч",
  "abbrevMinutesLabel": "м",
  "abbrevSecondsLabel": "сек.",
  "abbrevFeetSecondsLabel": "фута/сек",
  "abbrevFeetHourLabel": "фута/ч.",
  "abbrevKmSecondLabel": "км/сек",
  "abbrevKmHourLabel": "км/ч",
  "abbrevMetersSecondLabel": "м/сек",
  "abbrevMetersHourLabel": "м/ч",
  "abbrevMilesSecondLabel": "ми/сек",
  "abbrevMilesHourLabel": "ми/ч",
  "abbrevNauticalMilesSecondLabel": "нм/сек",
  "abbrevNauticalMilesHourLabel": "нм/ч",
  "publishDDBtn": "Публикуване",
  "publishTitle": "Публикуване на графики",
  "ddLayerName": "Публикувано име на слой",
  "publishToNewLayer": "Публикуване на резултати на нов обектен слой",
  "checkService": "Поставете отметка на услугата: {0}",
  "createService": "Създаване на услуга: {0}",
  "unableToCreate": "Не може да се създаде: {0}",
  "addToDefinition": "Добавяне към дефиниция: {0}",
  "successfullyPublished": "Успешно публикуван уеб слой {0}Управление на уеб слоя",
  "userRole": "Не може да се създаде услуга, тъй като потребителят няма разрешения",
  "missingLayerNameMessage": "Трябва да въведете валидно име на слой, преди да можете да публикувате",
  "invalidLayerName": "Името на слоя трябва да съдържа само буквено-цифрови знаци и долни черти",
  "layerNameExists": "Името на слоя вече съществува. Моля, използвайте различно име на слой.",
  "distanceLabel": "Разстояние",
  "radiusDistance": "Радиус на разстояние",
  "radials": "Радиали",
  "rings": "Кръгове",
  "orientationUnit": "Единица за ориентация",
  "radiusUnit": "Единица за радиус",
  "angleUnitLabel": "Единица за ъгъл",
  "editSymbologyHint": "Съвет: Натиснете върху иконата за преглед, за да редактирате символогията.",
  "lineSymbologyPopupTittle": "Симвология на линия",
  "circleSymbologyPopupTittle": "Симвология на окръжност",
  "ellipseSymbologyPopupTittle": "Симвология на елипса",
  "ringSymbologyPopupTittle": "Симвология на кръгове",
  "symbolAndLabelSettingsLabel": "Настройки на символ и етикет",
  "symbologyPreviewLabel": "Преглед на симвология",
  "ColorAndSizeLabel": "Цвят и размер на етикет",
  "colorPickerLabel": "Инструмент за избор на цвят"
});